### ISSUE TITLE
Android build fails with certain string resource values

### ISSUE THREAD

**Issue by wooseopkim** [bazelbuild/bazel#10010]
### Description of the problem / feature request:

Android build seems to fail when a string resource value contains `&amp;가`. I've tried with the following:
```xml
<!-- strings.xml -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="foo">&amp;가</string>
</resources>
```
I've also tried changing it into `<![CDATA[...]]>` but that didn't work. You could replace `가` with any [Hangul](https://en.wikipedia.org/wiki/Hangul) character, `ф`(Cyrillic), `ひ`(Hiragana), or `大`(Chinese) and they all cause the same error on my machine. I could reproduce the error with my company's app, and also with the offical example repo.

I installed Bazel using Homebrew. The output for `bazel version` is:
```
Build label: 1.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:19:27 2019 (1570702767)
Build timestamp: 1570702767
Build timestamp as int: 1570702767
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `git clone https://github.com/bazelbuild/examples`
2. `cd` into the `android/firebase-cloud-messaging` directory
3. Run `bazel build //app:app` and it should work (Otherwise, set up your Android dev environment I guess)
4. Open `app/src/main/res/values/strings.xml` and add a new line like this:
```diff
<resources>
    <string name="app_name">My Application</string>
+    <string name="foo">&amp;가</string>
</resources>
```
5. Run `bazel build //app:app` and it should fail

### What operating system are you running Bazel on?

macOS Mojave 10.14.6

### What's the output of `bazel info release`?

```shell
INFO: Writing tracer profile to '/private/var/tmp/_bazel_rainist-m016/435b0ed4741db2f8b6d0e76cddcaf6a5/command.profile.gz'
release 1.0.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://wooseopkim@github.com/Rainist/<private-repo-name>
a9ada1e14556427ebc266221c35c5f5704b211ca
a9ada1e14556427ebc266221c35c5f5704b211ca
```

###  Have you found anything relevant by searching the web?

No. I've googled `bazel cjk`, `bazel hangul`, `bazel "Protocol message had invalid UTF-8"`, and `bazel merging error`, but couldn't find anyting relevant.

### Any other information, logs, or outputs that you want to share?

```
> bazel build //app/src/main:app --verbose_failures
INFO: Writing tracer profile to '/private/var/tmp/_bazel_rainist-m016/435b0ed4741db2f8b6d0e76cddcaf6a5/command.profile.gz'
INFO: Analyzed target //app/src/main:app (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/rainist-m016/banksalad/app/src/main/BUILD:3:1: Merging compiled Android resources for //app/src/main:app_base failed (Exit 1) ResourceProcessorBusyBox failed: error executing command 
  (cd /private/var/tmp/_bazel_rainist-m016/435b0ed4741db2f8b6d0e76cddcaf6a5/sandbox/darwin-sandbox/126/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput bazel-out/darwin-fastbuild/bin/app/src/main/app_base_resources.jar --targetLabel //app/src/main:app_base --manifestOutput bazel-out/darwin-fastbuild/bin/app/src/main/app_base_processed_manifest/AndroidManifest.xml --androidJar external/androidsdk/platforms/android-28/android.jar --primaryManifest bazel-out/darwin-fastbuild/bin/app/src/main/_renamed/app_base/AndroidManifest.xml --packageForR main --primaryData 'app/src/main/res;;//app/src/main:app_base;bazel-out/darwin-fastbuild/bin/app/src/main/app_base_symbols/symbols.zip')
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
Oct 14, 2019 12:03:50 PM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
SEVERE: Unexpected
com.google.devtools.build.android.DeserializationException: Error deserializing bazel-out/darwin-fastbuild/bin/app/src/main/app_base_symbols/symbols.zip
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:702)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
        at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:841)
        at com.android.aapt.Resources$String.<init>(Resources.java:19413)
        at com.android.aapt.Resources$String.<init>(Resources.java:19375)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19892)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19886)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14531)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14475)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16363)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16357)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13092)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13024)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14349)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14343)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12215)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12161)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12913)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12907)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10225)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10123)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12104)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12098)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5477)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5414)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6636)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6630)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3586)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3523)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4809)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4803)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1888)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1832)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2903)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2897)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.android.aapt.Resources$ResourceTable.parseFrom(Resources.java:2126)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:254)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        ... 6 more

Oct 14, 2019 12:03:50 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
com.google.devtools.build.android.DeserializationException: Error deserializing bazel-out/darwin-fastbuild/bin/app/src/main/app_base_symbols/symbols.zip
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:702)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
        at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:841)
        at com.android.aapt.Resources$String.<init>(Resources.java:19413)
        at com.android.aapt.Resources$String.<init>(Resources.java:19375)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19892)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19886)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14531)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14475)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16363)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16357)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13092)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13024)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14349)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14343)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12215)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12161)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12913)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12907)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10225)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10123)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12104)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12098)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5477)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5414)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6636)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6630)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3586)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3523)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4809)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4803)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1888)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1832)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2903)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2897)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.android.aapt.Resources$ResourceTable.parseFrom(Resources.java:2126)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:254)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        ... 6 more

Exception in thread "main" com.google.devtools.build.android.DeserializationException: Error deserializing bazel-out/darwin-fastbuild/bin/app/src/main/app_base_symbols/symbols.zip
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:702)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
        at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:841)
        at com.android.aapt.Resources$String.<init>(Resources.java:19413)
        at com.android.aapt.Resources$String.<init>(Resources.java:19375)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19892)
        at com.android.aapt.Resources$String$1.parsePartialFrom(Resources.java:19886)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14531)
        at com.android.aapt.Resources$Item.<init>(Resources.java:14475)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16363)
        at com.android.aapt.Resources$Item$1.parsePartialFrom(Resources.java:16357)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13092)
        at com.android.aapt.Resources$Value.<init>(Resources.java:13024)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14349)
        at com.android.aapt.Resources$Value$1.parsePartialFrom(Resources.java:14343)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12215)
        at com.android.aapt.Resources$ConfigValue.<init>(Resources.java:12161)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12913)
        at com.android.aapt.Resources$ConfigValue$1.parsePartialFrom(Resources.java:12907)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10225)
        at com.android.aapt.Resources$Entry.<init>(Resources.java:10123)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12104)
        at com.android.aapt.Resources$Entry$1.parsePartialFrom(Resources.java:12098)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5477)
        at com.android.aapt.Resources$Type.<init>(Resources.java:5414)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6636)
        at com.android.aapt.Resources$Type$1.parsePartialFrom(Resources.java:6630)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3586)
        at com.android.aapt.Resources$Package.<init>(Resources.java:3523)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4809)
        at com.android.aapt.Resources$Package$1.parsePartialFrom(Resources.java:4803)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1888)
        at com.android.aapt.Resources$ResourceTable.<init>(Resources.java:1832)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2903)
        at com.android.aapt.Resources$ResourceTable$1.parsePartialFrom(Resources.java:2897)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.android.aapt.Resources$ResourceTable.parseFrom(Resources.java:2126)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:254)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        ... 6 more
Target //app/src/main:app failed to build
INFO: Elapsed time: 1.003s, Critical Path: 0.72s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```

**Comment by wooseopkim** [comment]
Nobody answered this for a year and finally I'm closing this due to inactivity
