### ISSUE TITLE
http_archive cannot use BUILD file from root package

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#10020]
### Description of the problem / feature request:

`http_archive` fails if `build_file = "foo.BUILD"`, i.e. the BUILD file is in the root package. All works well if the BUILD file is in some package, e.g. `build_file = "//bar:foo.BUILD"`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "foo",
    urls = ["https://github.com/bazelbuild/bazelisk/archive/master.zip"],
    build_file = "foo.BUILD",
)
```

foo.BUILD:
```
filegroup(
    name = "x",
    visibility = ["//visibility:public"],
)
```

BUILD:
```
filegroup(
    name = "x",
    srcs = ["@foo//:x"],
)
```

Repro:
```
  $ bazel --ignore_all_rc_files build :x
INFO: Writing tracer profile to '/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/command.profile.gz'
INFO: SHA256 (https://github.com/bazelbuild/bazelisk/archive/master.zip) = 88e4a37057b2a54734a34800b8368949a8962d2fff035645f06c9f69945f1953
INFO: Call stack for the definition of repository 'foo' which is a http_archive (rule definition at /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr/local/google/home/laszlocsomor/stuff/my-projects/bazel/http_archive-with-root-build-file/WORKSPACE:3:1
ERROR: An error occurred during the fetch of repository 'foo':
   Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 60
                workspace_and_buildfile(ctx)
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: /usr/local/google/home/laszlocsomor/stuff/my-projects/bazel/http_archive-with-root-build-file/external/foo.BUILD
ERROR: /usr/local/google/home/laszlocsomor/stuff/my-projects/bazel/http_archive-with-root-build-file/BUILD:1:1: //:x depends on @foo//:x in repository @foo which failed to fetch. no such package '@foo//': Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 60
                workspace_and_buildfile(ctx)
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/135be5809e9835adefb5e1554428164e/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: /usr/local/google/home/laszlocsomor/stuff/my-projects/bazel/http_archive-with-root-build-file/external/foo.BUILD
ERROR: Analysis of target '//:x' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

### What operating system are you running Bazel on?

Debian testing

### What's the output of `bazel info release`?

release 1.0.0

**Comment by laszlocsomor** [comment]
Bazel at HEAD (0c05851b40caa1d826c1ec8eb24b57dd727ea90f) is also buggy.

**Comment by aehlig** [comment]
This is working as specified; labels are interpreted in the context of the repository they are used in, and for repository rules this (unfortunately) is already the newly defined repository. I.e., label arguments in the definition of an external repository have most likely to be fully qualified.

Changing the `WORKSPACE` to

```load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "foo",
    urls = ["https://github.com/bazelbuild/bazelisk/archive/master.zip"],
    build_file = "@//:foo.BUILD",
)
```

i.e., only changing the `build_file` to the fully qualified label makes the build succeed.

```
$ bazel build :x
(22:56:17) INFO: Writing tracer profile to '/crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/command.profile.gz'
(22:56:17) INFO: Current date is 2019-10-14
(22:56:18) INFO: SHA256 (https://github.com/bazelbuild/bazelisk/archive/master.zip) = 88e4a37057b2a54734a34800b8368949a8962d2fff035645f06c9f69945f1953
(22:56:18) DEBUG: Rule 'foo' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "88e4a37057b2a54734a34800b8368949a8962d2fff035645f06c9f69945f1953"
(22:56:18) DEBUG: Call stack for the definition of repository 'foo' which is a http_archive (rule definition at /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /memfs/tmp/work/WORKSPACE:3:1
(22:56:18) INFO: Analyzed target //:x (1 packages loaded, 3 targets configured).
(22:56:18) INFO: Found 1 target...
Target //:x up-to-date (nothing to build)
(22:56:18) INFO: Elapsed time: 1.628s, Critical Path: 0.04s
(22:56:18) INFO: 0 processes.
(22:56:18) INFO: Build completed successfully, 1 total action
$
```

**Comment by laszlocsomor** [comment]
Thanks, that makes sense!

The docs indeed say "This attribute is an absolute label (use '@//' for the main repo)", can we maybe enforce that? Now it's easy to make the mistake I did, because the attribute expects a Label and those typically accept relative labels too. The error message is _correct_, but doesn't _help_ if you're unaware of a possible restriction on the Label format.

**Comment by bcsgh** [comment]
It would be nice if `build_file` could take a Label object:

```
http_archive(
    name = "foo",
    urls = ["https://github.com/bazelbuild/bazelisk/archive/master.zip"],
    build_file = Label(":foo.BUILD"),
)
```

This would also solve the problem of what package name to put in there when the invocation is in a macro loaded from a repo that might not have the expected name. However I *think* that only works from inside a `.bzl` file and not directly from a `WORKSPACE`.

**Comment by Wyverald** [comment]
Just use `build_file = Label("//:foo.BUILD")`.
