### ISSUE TITLE
tulsi broken with 1.1.0 rc1

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#10026]
See https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a822417e-f2f7-4927-abe7-b01289011f67/src/TulsiGeneratorIntegrationTests/AspectTests/attempt_1.log

```
> S: ** Completed bazel_extract_source_info in 6.4039s
> Critical error logged: Failed to retrieve information about the Bazel workspace. This usually means that the contents of a BUILD file are incorrect or flags are missing. Read the message log carefully for details.
Details:
ERROR: /private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/fake_execroot/__main__/tulsi_test/BUILD:46:1: in ios_application rule //tulsi_test:Application: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/fake_execroot/__main__/tulsi_test/BUILD", line 46
		ios_application(name = 'Application')
	File "/private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/_bazel_buildkite/b61762b4ce3449d35b22b9c44c3f828e/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 160, in _ios_application_impl
		run_support.register_simulator_executable(<2 more arguments>)
	File "/private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/_bazel_buildkite/b61762b4ce3449d35b22b9c44c3f828e/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 28, in run_support.register_simulator_executable
		ctx.actions.expand_template(<4 more arguments>)
	File "/private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/_bazel_buildkite/b61762b4ce3449d35b22b9c44c3f828e/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 36, in ctx.actions.expand_template
		shell.quote(<1 more arguments>)
	File "/private/var/tmp/_bazel_buildkite/028a712aa7331be9a769b3cf28a067b2/sandbox/darwin-sandbox/102/execroot/__main__/_tmp/f5aea879286710a48502a37fbbd95210/_bazel_buildkite/b61762b4ce3449d35b22b9c44c3f828e/external/bazel_skylib/lib/shell.bzl", line 49, in shell.quote
		s.replace("'", "'\\''")
type 'NoneType' has no method replace()
```

This may have been fixed by
https://github.com/bazelbuild/rules_apple/commit/5caccdd4c758ea6c5c903966423b1ab69371b90b
but tulsi points to 0.18 of rules_apple here:
https://github.com/bazelbuild/tulsi/blob/master/WORKSPACE#L6

I don't know why this would not be broken in current downstream, but it is broken with the new RC.

Root cause seems to be https://github.com/bazelbuild/bazel/pull/9191

**Comment by meisterT** [comment]
cc @keith

**Comment by meisterT** [comment]
cc @dslomov since I see the same error for the 1.0.1 patch release in https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1233#a74aabfa-d709-4ab8-a3f6-922062382737

**Comment by keith** [comment]
Looking into this

**Comment by keith** [comment]
Submitted https://github.com/bazelbuild/tulsi/pull/106, is there anyway we can verify this failed job against my branch?

**Comment by meisterT** [comment]
I don't know whether this is possible. Perhaps @meteorcloudy knows...
Do you have any explanation why this starts failing now?

**Comment by meisterT** [comment]
@philwo suggested that you include in your branch a change to https://github.com/bazelbuild/tulsi/blob/master/.bazelci/presubmit.yml
and use a different bazel version there.
See for example https://github.com/bazelbuild/rules_apple/blob/master/.bazelci/presubmit.yml#L20
Use either `last_green` or `last_rc`.

**Comment by meisterT** [comment]
@keith I just did that myself,

- without your fix: https://buildkite.com/bazel/tulsi-bazel-darwin/builds/439
- with your fix: https://buildkite.com/bazel/tulsi-bazel-darwin/builds/440
