### ISSUE TITLE
bazelisk broken in downstream

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#10024]
Bazelisk breaks with the new 1.1.0rc1. It seems there's a bug in the pipeline setup since I cannot repro the error locally

Example:
```
2019/10/14 15:04:11 could not run Bazel: could not start Bazel: fork/exec /tmp/tmp6_mk0eou/bazel-bin/src/bazel: no such file or directory

(15:04:11) FAIL: //:go_bazelisk_test (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1179f58d0393eff3edc155a5d1c44b5b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/go_bazelisk_test/test.log)
--
  | # test_bazel_version
  | Python 2.7.15+
  | Running Bazelisk with ...
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1179f58d0393eff3edc155a5d1c44b5b/sandbox/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/py_bazelisk_test.runfiles/__main__/bazelisk.py", line 343, in <module>
  | sys.exit(main())
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1179f58d0393eff3edc155a5d1c44b5b/sandbox/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/py_bazelisk_test.runfiles/__main__/bazelisk.py", line 337, in main
  | bazel_path = download_bazel_into_directory(bazel_version, is_commit, bazel_directory)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1179f58d0393eff3edc155a5d1c44b5b/sandbox/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/py_bazelisk_test.runfiles/__main__/bazelisk.py", line 236, in download_bazel_into_directory
  | url = determine_url(version, is_commit, bazel_filename)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1179f58d0393eff3edc155a5d1c44b5b/sandbox/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/py_bazelisk_test.runfiles/__main__/bazelisk.py", line 228, in determine_url
  | (version, rc) = re.match(r"(\d*\.\d*(?:\.\d*)?)(rc\d+)?", version).groups()
  | AttributeError: 'NoneType' object has no attribute 'groups'
  | (15:04:11) [17 / 20] 1 / 3 tests, 1 failed;  1 action; last test: //:go_bazelisk_test
  | Testing //:py_bazelisk_test; 0s remote-cache, linux-sandbox
  | [Errno 13] Permission denied: '/go_bazelisk_test'


```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1234#e07c0487-06ac-4b59-a253-c7fae5f00ae9

**Comment by meisterT** [comment]
This also affects rules_go:
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/3f43ae25-959d-421d-b16d-6b15190d25cb/tests/core/coverage/binary_coverage_test/attempt_1.log

```
    binary_coverage_test.go:59: 2019/10/14 15:11:18 could not parse Bazel fork and version: invalid version "/tmp/tmplnrdai4u/bazel-bin/src/bazel", could not parse version with more than one slash
```

@meteorcloudy

**Comment by meteorcloudy** [comment]
For rules_go, that is an error message from an older version of Bazelisk. It's gone after upgrading Bazelisk on CI, I didn't find this failure in the latest downstream build.

**Comment by meteorcloudy** [comment]
The Bazelisk failure will be fixed by https://github.com/bazelbuild/bazelisk/pull/94
