### ISSUE TITLE
Crash if cc_toolchain_suite toolchain is an alias

### ISSUE THREAD

**Issue by chronal-xnor** [bazelbuild/bazel#10059]
### Description of the problem / feature request:

If one of the `toolchains` dict values of `cc_toolchain_suite` is an `alias` target, Bazel crashes with the following error:

<details>
<summary>Bazel exception</summary> 

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//:toolchain BuildConfigurationValue.K
ey[1781306360df9b9971f0a5f5e5874dcc] false' (requested by nodes '//:foo BuildConfigurationValue.Key[1781306360df9b9971f0a5f5e5874dcc] false', '@bazel_tools//tools/cpp:
malloc BuildConfigurationValue.Key[1781306360df9b9971f0a5f5e5874dcc] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteMap(RuleContext.java:841)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.selectCcToolchain(CcToolchainSuite.java:116)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:71)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:331)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:343)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
        ... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:toolchain BuildConfigurationValue.Key[1781306360df9b9971f0a5f5e5874dcc] false' (requested by nodes '//:foo BuildConfigurationValue.Key[1781306360df9b9971f0a5f5e5874dcc] false', '@bazel_tools//tools/cpp:malloc BuildConfigurationValue.Key[1781306360df9b9971f0a5f5e5874dcc] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteMap(RuleContext.java:841)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.selectCcToolchain(CcToolchainSuite.java:116)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:71)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:331)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:343)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
```

</details>

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `cc_toolchain_suite` where one of the `toolchains` is an alias. Patch file of a minimal example workspace that reproduces this problem attached: [repro-bazel-crash.patch.txt](https://github.com/bazelbuild/bazel/files/3740926/repro-bazel-crash.patch.txt). Run `bazel build --crosstool_top=//:toolchain //:foo`

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

```
bazel info release
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/zikomo3/bazel-cache/_bazel_chronal/a8924f358796dff6f7a26f0da9fe5049/command.profile.gz'
release 1.0.0
```

###  Have you found anything relevant by searching the web?

This [old commit](https://github.com/bazelbuild/bazel/commit/440919933dc11d8aa4394dbd53790271a2073bc5) mentions a rule called `cc_toolchain_alias` which I can't find any information about and doesn't seem relevant to what I'm trying to do.

### Any other information, logs, or outputs that you want to share?

My goal is to have a configurable toolchain, so that I can use a build setting to select the specific `cc_toolchain` to rule use depending on which device I'm cross-compiling for. This is to avoid overloading the `cpu` attribute with values that aren't meaningfully distinct CPUs. I.e. I would prefer to say `--cpu=arm` and then select a toolchain with an appropriate libc and optimization flags for a particular ARM device (say, with a Cortex A53). The current solution is to use different `crosstool_top`s depending on the device, which is resulting in a lot of code duplication and is becoming difficult to maintain.

Using an alias for this is probably not the best way to solve this problem, but Bazel should probably not dump an exception if I'm doing something out of spec.

**Comment by irengrig** [comment]
P1 because of NPE: Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteMap(RuleContext.java:841)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.selectCcToolchain(CcToolchainSuite.java:116)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:71)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:331)

**Comment by speedskater** [comment]
We stumbled across the same error, when trying to distinguish our toolchains based on the execution platform. 
In our particular case the mac os toolchain requires files, which are not compatible with the windows filesystem. Hence we wanted to use an alias to prevent loading of the mac and linux toolchains on windows.

@chronal-xnor did you find a workaround for this issue?

**Comment by chronal-xnor** [comment]
@speedskater our current workaround, which I was trying to replace, is to pick a `--crosstool_top` at the command line depending on the platform. For ergonomics we do this with a `--config` value rather than directly specifying the command line flag, e.g.:

```bash
# In .bazelrc:
build:rpi3  --crosstool_top=//crosstool/rpi3:toolchain --cpu=arm ...

# When running builds for rpi3:
bazel build --config=rpi3 //some:target
```

This allows us to use different toolchains for different build targets (and host platforms) but puts the burden of using the correct flag on the person invoking the build, and results in a nontrivial amount of duplication each time we want to add a build target. YMMV.

Repro still crashes on Bazel 2.0.0

**Comment by speedskater** [comment]
@chronal-xnor Thank you for your reply and your suggested solution.
 
We finally settled with a workaround using the commandline switch `--incompatible_enable_cc_toolchain_resolution` and the platform based toolchain resolution instead of defining the toolchain using `--crosstool_top`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
