### ISSUE TITLE
IllegalStateException if register_execution_platforms() argument can't be resolved

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#10101]
### Description of the problem / feature request:

If `register_execution_platforms()` is called with a label that can't be resolved, Bazel will crash with a `java.lang.IllegalStateException`. Ideally it would either ignore the bad label and accept the others, or at least fail with a nicer error message.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat BUILD
genrule(
    name = "hello",
    outs = ["hello.txt"],
    cmd = "touch $@",
)
$ cat WORKSPACE
register_execution_platforms("@//:noexist")
$ bazel build //:hello
[...]
java.lang.IllegalStateException: //:hello BuildConfigurationValue.Key[9a088452797200c5bf92e0469646fb64] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsFunction$InvalidExecutionPlatformLabelException: invalid registered execution platform '@//:noexist': no such target '//:noexist': target 'noexist' not declared in package '' defined by /home/john/src/bazeltest/badexecplatform/BUILD, rootCauses={com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@204e5adc}, cycles=[], isCatastrophic=false, rootCauseOfException=com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@204e5adc, isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:664)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:530)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:442)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
FAILED: Build did NOT complete successfully (4 packages loaded, 5 targets configured)

```

### What operating system are you running Bazel on?

`Linux desktop 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### What's the output of `bazel info release`?

`release 1.1.0`

**Comment by gregestren** [comment]
I've got a fix in transit...
