### ISSUE TITLE
Bazel CI: Bazel, rules_go, rules_nodejs failing on Windows in downstream pipeline

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10124]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1257

Log from rules_go
```
fatal: cannot create directory at 'go/packages/testdata/TestName_ModulesDedup/pkg/mod/cache/download/github.com/heschik': Filename too long
        ERROR: Analysis of target '//:cmd' failed; build aborted: no such package '@org_golang_x_tools//go/analysis': Traceback (most recent call last):
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                        _clone_or_update(ctx)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                        git_repo(ctx, directory)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                        _update(ctx, git_repo)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 104, in _update
                        reset(ctx, git_repo)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 141, in reset
                        _git(ctx, git_repo, "reset", <2 more arguments>)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git
                        _error(ctx.name, <2 more arguments>)
                File "C:/src/tmp/7vvwt6pp/execroot/io_bazel_rules_go/_tmp/cc8d18bc88b1b27e88dea6105251a7c411477f80fdf21f8cdfa213ce2f12227d/_bazel_pcloudy/dz5uqw3r/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                        fail(<1 more arguments>)
        error running 'git reset --hard c9f9432ec4b21a28c4d47f172513698febb68e9c' while working with @org_golang_x_tools:
fatal: cannot create directory at 'go/packages/testdata/TestName_ModulesDedup/pkg/mod/cache/download/github.com/heschik': Filename too long
```

**Comment by meteorcloudy** [comment]
Suspect culprit: https://github.com/bazelbuild/bazel/commit/2b6a435a1c5bb683f3e69e92ca878af6e119918e

**Comment by meteorcloudy** [comment]
Bisecting result: https://buildkite.com/bazel/culprit-finder/builds/231

**Comment by meteorcloudy** [comment]
The bisect gave c92e0da9662397518153303fcf60fc6311052a10 as the culprit.

**Comment by meteorcloudy** [comment]
Bisect result of rules_go: https://buildkite.com/bazel/culprit-finder/builds/229

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/culprit-finder/builds/233 
rules_apple is also failing due to the same commit.
