### ISSUE TITLE
Integer overflow when build is too slow

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#10149]
### Description of the problem / feature request:

When the build is too slow and you're trying to debug it using 

```
$ time bazel build --experimental_generate_json_trace_profile --experimental_profile_cpu_usage --profile trace-profile.json //:target
```

I get
```
INFO: Elapsed time: 81983.972s, Critical Path: 2056.42s
INFO: 9202 processes: 8703 darwin-fake-sandbox, 499 local.
INFO: Build completed successfully, 11954 total actions
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: startTime was -50421716336292
	at com.google.common.base.Preconditions.checkState(Preconditions.java:573)
	at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:687)
	at com.google.devtools.build.lib.profiler.Profiler.logEventAtTime(Profiler.java:782)
	at com.google.devtools.build.lib.profiler.CollectLocalCpuUsage.logCollectedData(CollectLocalCpuUsage.java:73)
	at com.google.devtools.build.lib.profiler.Profiler.stop(Profiler.java:635)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:643)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: startTime was -50421716336292
	at com.google.common.base.Preconditions.checkState(Preconditions.java:573)
	at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:687)
	at com.google.devtools.build.lib.profiler.Profiler.logEventAtTime(Profiler.java:782)
	at com.google.devtools.build.lib.profiler.CollectLocalCpuUsage.logCollectedData(CollectLocalCpuUsage.java:73)
	at com.google.devtools.build.lib.profiler.Profiler.stop(Profiler.java:635)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:643)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
/Users/obonilla/o/bazel/bazel-bin/src/bazel build   --spawn_strategy=sandboxe  2.86s user 1.76s system 0% cpu 22:46:29.41 total
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I was trying to figure out why the build is so slow.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure how to repro other than have a build that is about 22 hours long and try to generate a trace profile.

### What operating system are you running Bazel on?

```
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```

### What's the output of `bazel info release`?

```
$ bazel info release
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 28ae6faa-8a0f-4903-9b06-ce89de1d6b8e
release 0.29.1
```

**Comment by meisterT** [comment]
This might have been fixed by https://github.com/bazelbuild/bazel/commit/a3c29c44d3ef6f4b1dd33240b9972cda4eca1a4f

How reproducible is this for you?

**Comment by ob** [comment]
It's reproducible but slow... 22 hours slow. I also need to update a bunch of rules in order to test with a newer Bazel. I'll post back once I do that.

**Comment by meisterT** [comment]
Did you have time to try again?

**Comment by ob** [comment]
Sorry no. After upgrading the OS and Xcode the build stopped being that slow. We can close this issue and I’ll reopen if I see it again. I hope I never have to deal with a build so slow it overflows an integer though. :-)
