### ISSUE TITLE
`--noremote_upload_local_results` does not imply `--experimental_build_event_upload_strategy=local`

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10183]
### Description of the problem / feature request:

Currently if you have a separation between read and write credentials for your gRPC based remote cache, and with the readonly credentials you pass `--noremote_upload_local_results`, bazel still crashes if you generate a build event protocol local because it's trying to upload it.

```
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission "remotebuildexecution.blobs.create" denied on resource "projects/sandbox-238123/instances/default_instance/uploads/6e7238bd-7e3d-4917-b789-97e9c6dc3f83/blobs/2bd8cc61df4aeb8bc93f78aac22989333e372212faa416bf9969a9cc92f4e4a9/2187392" (or it may not exist)
        at io.grpc.Status.asRuntimeException(Status.java:523)
        at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload$1.onClose(ByteStreamUploader.java:515)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 193 total actions
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel \
 --bazelrc=/dev/null \
 test \
 //... \
 --google_default_credentials \
 --remote_cache=remotebuildexecution.googleapis.com \
 --remote_instance_name=projects/SOMETHING/instances/default_instance \
 --build_event_json_file=bep.json \
 --noremote_accept_cached \
 --noremote_upload_local_results
```

### What operating system are you running Bazel on?

Ubuntu bionic

### What's the output of `bazel info release`?

release 1.1.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/9243

**Comment by technillogue** [comment]
On a related note, could there please be better documentation for this than

> `--experimental_build_event_upload_strategy=<a string>` **default: see description**
Selects how to upload artifacts referenced in the build event protocol.
Tags: `affects_outputs`

What are the possible values? What description should one see?
