### ISSUE TITLE
RBE "Failed to query remote execution capabilities" after proxy disconnect

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10204]
### Description of the problem / feature request:

Currently if you're using Google's RBE service as a remote cache, you can end up in a state where you have to run `bazel shutdown` to recover your connection to the service.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `bazel shutdown`
2. Launch [Charles Proxy](https://www.charlesproxy.com/) on macOS and enable the local macOS proxy
3. Run `bazel build --remote_cache=remotebuildexecution.googleapis.com --remote_instance_name=whatever //...
4. Quick Charles Proxy
5. Run your build again

At this point you are in a broken state where you only ever get this error:

```
ERROR: Failed to query remote execution capabilities: UNAVAILABLE: io exception
```

Until your run `bazel shutdown` again

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.1.0

###  Have you found anything relevant by searching the web?

I've attempted to use `no_proxy` to avoid this, but it seems that that doesn't apply for grpc connections

**Comment by byronyi** [comment]
Try add "grpc://" URL scheme before your remote cache/executor service. It works for me when I upgrades from <1.0 to post 1.0.

**Comment by keith** [comment]
Adding that to the scheme does not help. Which I'm kind of glad about since that's the scheme being inferred anyways.

Honestly in this case if the bazel server died it would fix it, and that would be a fine easy solution for us.

Note this still repros with bazel 3.0.0

**Comment by ulfjack** [comment]
It would be good to know what the exception is. Unfortunately, my 141997756ebea59fb697568f2d91760f51c51e01 didn't make it into 3.0.0. I wonder if gRPC is caching the error - how long did you wait before shutting down Bazel?

**Comment by keith** [comment]
Here's the trace with bazel 3.1.0rc2:

```
INFO: Invocation ID: fbe81716-46df-4fac-8c42-b1934b31a767
ERROR: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:8888
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        ... 11 more
```

This makes sense since that address was the previous proxy address that it's still trying to hit after it's shut down

**Comment by ulfjack** [comment]
Ok. It sounds like the problem is that Bazel takes the proxy address from when the server was started and doesn't realize that the proxy is no longer there. Do you see the same problem the other way round? I.e., run bazel without proxy, and then run again with the proxy - it probably doesn't connect to the proxy, but continues to attempt a direct connection?

**Comment by keith** [comment]
> but continues to attempt a direct connection?

Yes it looks like this is only a problem if you open the proxy, then run bazel the first time. If you run bazel, open proxy, run bazel, close proxy, run bazel, that entire flow works

**Comment by ulfjack** [comment]
It's odd if it's asymmetric. Are you sure it's using the proxy?

**Comment by keith** [comment]
No I'm not sure it is. Afaik Charles doesn't support gRPC so I can't tell. In our use case no one was ever trying to do that, they just had the proxy open for other reasons.

**Comment by ulfjack** [comment]
If we want to support this, I think we'll need to write a custom proxy detector, like partially documented here:
https://github.com/grpc/grpc-java/issues/5600

According to the grpc docs, it's using the Java ProxySelector:
https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html

That, in turn, uses configuration documented here:
https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html#Proxies

And that says that it's only using a bunch of Java properties, which we don't set.

I suspect that it's also reading the HTTP_PROXY env variable, but I don't know for sure.

Looking at the Bazel code, it only does something explicit for proxies in the repository downloader.

Do you know how the information about the proxy is passed along? Is it using HTTP_PROXY?

**Comment by keith** [comment]
We're definitely not using the env var, we exec bazel with `env -i` to pass very limited variables and do not include that one
