### ISSUE TITLE
.netrc files with comments break http_archive downloads

### ISSUE THREAD

**Issue by segiddins** [bazelbuild/bazel#10215]
### Description of the problem / feature request:

With the following `~/.netrc`, `bazel build ...` fails when the `WORKSPACE` has an un-downloaded repository:

```ini
# Production
machine build.company login foo password bar
machine build-prod.company login foo password bar

# Staging
machine build.stage.company login foo password bar
machine build-dev.company login foo password bar
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel build` with the above `.netrc` in the user's home directory.

### What operating system are you running Bazel on?

macOS 10.14.4

### What's the output of `bazel info release`?

`release 1.1.0`

###  Have you found anything relevant by searching the web?

Looks like this was caused by https://github.com/bazelbuild/bazel/pull/9388, which does not handle `#` as a token

### Any other information, logs, or outputs that you want to share?

```
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 287, in read_netrc
		fail(<1 more arguments>)
Unexpected token '#' while reading /Users/build/.netrc
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_build/a0b0a7899b2e91189412dbb548223580/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 287, in read_netrc
		fail(<1 more arguments>)
Unexpected token '#' while reading /Users/build/.netrc
```

**Comment by shs96c** [comment]
The problem could well be alleviated by skipping lines that begin with a `#`. This is probably somewhere in the `read_netrc` function in `tools/build_defs/repo/utils.bzl` at around line 231, where `continue`ing after passing a check for `line.startswith("#")` might suffice.

**Comment by jin** [comment]
@shs96c https://github.com/bazelbuild/bazel/pull/10337
