### ISSUE TITLE
Crash when build with cross toolchain like armeabi-v7a or k8

### ISSUE THREAD

**Issue by kevinwhzou** [bazelbuild/bazel#10224]
**Description of the problem / feature request:**
Bazel crashes when build bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data with cross toolchain like cc-compiler-armeabi-v7a or  cc-compiler-k8
`bazel build //:hello  --verbose_explanations --crosstool_top=//tools/arm_compiler:cc-compiler-armeabi-v7a`
`bazel build //:hello --crosstool_top=//tools/arm_compiler:cc-compiler-k8`

**Bugs: bazel crash  with internal error as following:**

> Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@bazel_tools//tools/cpp:malloc BuildConfigurationValue.Key[6af6afb2b354be1b3e8882d2c9c44e7c] false' (requested by nodes '//:hello BuildConfigurationValue.Key[6af6afb2b354be1b3e8882d2c9c44e7c] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider cannot be cast to class com.google.devtools.build.lib.rules.cpp.CcToolchainProvider (com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider and com.google.devtools.build.lib.rules.cpp.CcToolchainProvider are in unnamed module of loader 'app')
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainFromCrosstoolTop(CppHelper.java:349)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:321)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:313)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:302)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainUsingDefaultCcToolchainAttribute(CppHelper.java:232)
        at com.google.devtools.build.lib.rules.cpp.CcCommon.<init>(CcCommon.java:168)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:120)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:90)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:65)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:331)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:891)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:351)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
        ... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@bazel_tools//tools/cpp:malloc BuildConfigurationValue.Key[6af6afb2b354be1b3e8882d2c9c44e7c] false' (requested by nodes '//:hello BuildConfigurationValue.Key[6af6afb2b354be1b3e8882d2c9c44e7c] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider cannot be cast to class com.google.devtools.build.lib.rules.cpp.CcToolchainProvider (com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider and com.google.devtools.build.lib.rules.cpp.CcToolchainProvider are in unnamed module of loader 'app')
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainFromCrosstoolTop(CppHelper.java:349)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:321)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:313)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:302)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainUsingDefaultCcToolchainAttribute(CppHelper.java:232)
        at com.google.devtools.build.lib.rules.cpp.CcCommon.<init>(CcCommon.java:168)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:120)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:90)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:65)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:331)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:891)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:351)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
FAILED: Build did NOT complete successfully (16 packages loaded, 4018 targets configured)

**The Version and Environment:**
   Bazel 1.1.0 , 1.0.1, 0.29.1 ,   other versions haven't been validated.
   OS ubuntu 16.04 , centos 7 , debian9

**Comment by kevinwhzou** [comment]
only if command follows "bazel build //:hello --crosstool_top=//tools/arm_compiler:toolchain --cpu=armeabi-v7a   --spawn_strategy=standalone "，bazel will build target embedded executive

**Comment by katre** [comment]
Reassigning to rules-cpp since this happens when using `--crosstool_top`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
