### ISSUE TITLE
Option to use d8 dexmerger

### ISSUE THREAD

**Issue by gyias** [bazelbuild/bazel#10287]
### Description of the problem / feature request:

Make d8 dexmerger available to use optionally.

**Comment by ahumesky** [comment]
as of bazel 1.2.0, d8 can be used by specifying the following command line options:

`--define=android_dexmerger_tool=d8_dexmerger --define=android_incremental_dexing_tool=d8_dexbuilder --nouse_workers_with_dexbuilder`

(these can be put in your bazelrc file so you don't have to put it on the command line)

**Comment by nkoroste** [comment]
bazel version 1.2.1

I just tried your recommendation and it looks to me that it's still using `dexFileMerger` 

```
$ ./bazelw build -s --verbose_failures --define=android_dexmerger_tool=d8_dexmerger --define=android_incremental_dexing_tool=d8_dexbuilder --nouse_workers_with_dexbuilder  //apps/mushroom:mushroom-apk
INFO: Invocation ID: 81857777-9343-488f-88c6-0ad4c20be662
INFO: Analyzed target //apps/mushroom:mushroom-apk (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //apps/mushroom:mushroom-apk [action 'Assembling dex files into apps/mushroom/_dx/mushroom-apk/classes.dex.zip', configuration: bc4dc7f554b64133a76ca709d45d4a07d8c11880ba77ba3131763df84c2246e8]
(cd /home/nk/.cache/bazel/_bazel_nk/2007fbffc9ead87bb25ae587ecaccc95/execroot/__main__ && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger --input bazel-out/k8-fastbuild/bin/apps/mushroom/_dx/mushroom-apk/classes.jar --output bazel-out/k8-fastbuild/bin/apps/mushroom/_dx/mushroom-apk/classes.dex.zip '--multidex=minimal' --main-dex-list apps/mushroom/mainDexList.txt)
ERROR: /apps/mushroom/BUILD.bazel:1:1: Assembling dex files into apps/mushroom/_dx/mushroom-apk/classes.dex.zip failed (Exit 1) DexFileMerger failed: error executing command 
  (cd /home/nk/.cache/bazel/_bazel_nk/2007fbffc9ead87bb25ae587ecaccc95/sandbox/linux-sandbox/1496/execroot/__main__ && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger --input bazel-out/k8-fastbuild/bin/apps/mushroom/_dx/mushroom-apk/classes.jar --output bazel-out/k8-fastbuild/bin/apps/mushroom/_dx/mushroom-apk/classes.dex.zip '--multidex=minimal' --main-dex-list apps/mushroom/mainDexList.txt)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
com.android.dex.DexIndexOverflowException: Cannot merge new index 68608 into a non-jumbo instruction!
	at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:137)
	at com.android.dx.merge.InstructionTransformer.access$1000(InstructionTransformer.java:26)
	at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:78)
	at com.android.dx.io.CodeReader.callVisit(CodeReader.java:130)
	at com.android.dx.io.CodeReader.visitAll(CodeReader.java:103)
	at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:52)
	at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:906)
	at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:880)
	at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:853)
	at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:749)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:603)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:197)
	at com.google.devtools.build.android.dexer.DexFileAggregator.merge(DexFileAggregator.java:164)
	at com.google.devtools.build.android.dexer.DexFileAggregator.access$000(DexFileAggregator.java:40)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:199)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:188)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

 I'm trying to workaround some DexFileMerger related issues:
#9384
#9383

and so far the only thing that works is not using incremental dexing which impacts performance (via `--noincremental_dexing`).

**Comment by gyias** [comment]
I don't think the commit(8d866f3259957b5cdda5d29c57fd8bdc3df85d8f) was included in 1.2.1. 2.0.0 doesn't have it either. I'll update here and close this issue once it's officially released.

**Comment by nkoroste** [comment]
Did this make it to the latest 2.1.0 release?

Also, can you give some background on why `d8_dexbuilder` & `d8_dexmerger` don't support incremental dexing and workers i.e. require the following 2 commands in order to work :
```
--nouse_workers_with_dexbuilder
--noincremental_dexing
```
Is it because it's still experimental?

**Comment by gyias** [comment]
> Did this make it to the latest 2.1.0 release?

Yes, it did.

> 
> Also, can you give some background on why `d8_dexbuilder` & `d8_dexmerger` don't support incremental dexing and workers i.e. require the following 2 commands in order to work :
> 
> ```
> --nouse_workers_with_dexbuilder
> --noincremental_dexing
> ```
> 
> Is it because it's still experimental?

It's just that D8 doesn't support the persistent worker mode yet. I believe the team is aware of the issue, though.

**Comment by nkoroste** [comment]
Thanks for the info!
Found https://github.com/bazelbuild/bazel/issues/10241 bug that I can follow for persistent workers
