### ISSUE TITLE
HttpDownloader: java.io.IOException: thread interrupted

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#10294]
### Description of the problem / feature request:

Our Bazel builds intermittently fail during analysis when transferring Maven artifacts from an internal Artifactory server. The console only displays a vague error like the following:

```
ERROR: An error occurred during the fetch of repository 'org_apache_neethi_neethi_jar_sources_2_0_4':
   java.io.IOException: thread interrupted
ERROR: .../92b8e37af6d4337248d7dd4b9c25861a/external/vlsi_maven_deps/BUILD:224:1: @vlsi_maven_deps//:org_apache_neethi_neethi_jar_sources_2_0_4_extension depends on @org_apache_neethi_neethi_jar_sources_2_0_4//file:file in repository @org_apache_neethi_neethi_jar_sources_2_0_4 which failed to fetch. no such package '@org_apache_neethi_neethi_jar_sources_2_0_4//file': java.io.IOException: thread interrupted
ERROR: Analysis of target '//vim/vlsi/dist:dist' failed; build aborted: Analysis failed
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Difficult to say. Run lots of builds which download small artifacts from a flaky server?

### What operating system are you running Bazel on?

CentOS 7.2 and macOS High Sierra and Mojave.

### What's the output of `bazel info release`?

release 1.1.0+vmware

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

na

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

na

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/bazel/issues/3851
- https://github.com/bazelbuild/bazel/issues/8974#issuecomment-516590432

### Any other information, logs, or outputs that you want to share?

All failures encountered having this signature involved files < 32KB in size, possibly implicating the 32KB precheck logic in HttpStream.java.

----

I applied a small patch to try to get more context, and the next failure produced the following:

```
ERROR: An error occurred during the fetch of repository 'com_google_protobuf_protobuf_java_util_jar_sources_3_4_0':
   java.io.IOException: thread interrupted
Printing stack trace: com.google.devtools.build.lib.syntax.EvalExceptionWithStackTrace: java.io.IOException: thread interrupted
 at com.google.devtools.build.lib.syntax.Eval.maybeTransformException(Eval.java:715)
 at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:414)
 at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:89)
 at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:203)
 at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:194)
 at com.google.devtools.build.lib.syntax.Eval.execStatementsInternal(Eval.java:233)
 at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:60)
 at com.google.devtools.build.lib.syntax.StarlarkFunction.call(StarlarkFunction.java:80)
 at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:460)
 at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:422)
 at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:179)
 at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:300)
 at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:227)
 at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
 at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
 at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
 at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
 at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
 at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.google.devtools.build.lib.rules.repository.RepositoryFunction$RepositoryFunctionException: java.io.IOException: thread interrupted
 at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.download(SkylarkRepositoryContext.java:621)
 at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:128)
 at com.google.devtools.build.lib.syntax.CallUtils.callMethod(CallUtils.java:739)
 at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:492)
 at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:412)
 ... 19 more
Caused by: java.io.IOException: thread interrupted
 ... 27 more
ERROR: .../807eb668ba050db454d42ea2f77f3947/external/hvc_deps/BUILD:74:1: @hvc_deps//:com_google_protobuf_protobuf_java_util_jar_sources_3_4_0_extension depends on @com_google_protobuf_protobuf_java_util_jar_sources_3_4_0//file:file in repository @com_google_protobuf_protobuf_java_util_jar_sources_3_4_0 which failed to fetch. no such package '@com_google_protobuf_protobuf_java_util_jar_sources_3_4_0//file': java.io.IOException: thread interrupted
```

**Comment by kiinoo** [comment]
got the same problem when running `_go_download_sdk`, the download process did not even started..
