### ISSUE TITLE
x.f(g()) evaluates g() before x.f

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#10339]
Bazel's implementation of Starlark evaluates `x.f(g())` in the wrong order: it evaluates the argument `g()` before the field selection operation `x.f`. This causes the side effects of g to be observed even when x.f fails, which is confusing. In principle, the effects of g could even influence the behavior of the x.f operation.

```
$ cat a.sky
def f(): print("f")
"".nonesuch(f())

$ blaze-bin/third_party/bazel/src/main/java/com/google/devtools/starlark/Starlark  a.sky
f
type 'string' has no method nonesuch()

Contrast:
$ python2 a.sky
Traceback (most recent call last):
  File "a.sky", line 4, in <module>
    "".nonesuch(f())
AttributeError: 'str' object has no attribute 'nonesuch'

$ python3 a.sky
Traceback (most recent call last):
  File "a.sky", line 4, in <module>
    "".nonesuch(f())
AttributeError: 'str' object has no attribute 'nonesuch'

$ starlark a.sky # in Go
Traceback (most recent call last):
  a.sky:4:3: in <toplevel>
Error: string has no .nonesuch field or method
```

(The cause of this behavior is an unsound optimization to avoid allocating a closure for x.f.)

**Comment by alandonovan** [comment]
This optimization also hides other cases in which `x.f()` cannot be decomposed into `y= x.f; y()` without changing its behavior, as in this example which accesses `struct.to_json`:

```$ cat test/BUILD
load("inc.bzl", "f")
f()

$ cat test/inc.bzl 
def f():
    print(struct(x = 1).to_json())

    y = struct(x = 1).to_json; print(y)

$ blaze query test/BUILD
DEBUG: test/inc.bzl:2:5: {"x":1}
ERROR: test/inc.bzl:4:9: Traceback (most recent call last):
	File "test/BUILD", line 3
		f()
	File "test/inc.bzl", line 4, in f
		struct(x = 1).to_json
'struct' object has no attribute 'to_json'
Available attributes: x
```
