### ISSUE TITLE
bazel-bin symlink cycle causes crash

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#10365]
Starting with no symlinks in the workspace, create a bogus bazel-bin that points to `.`.
```sh
$ ln -s . bazel-bin
```

Run bazel (in my repro, to build itself) and crash.

```sh
$ bazel build //src:bazel
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
DEBUG: /usr/local/google/home/brandjon/.cache/bazel/_bazel_brandjon/2c3f940c491acfe06dc1cf8b48325f83/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /usr/local/google/home/brandjon/.cache/bazel/_bazel_brandjon/2c3f940c491acfe06dc1cf8b48325f83/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/local/google/home/brandjon/src/dev-bazel
/usr/local/google/home/brandjon/src/dev-bazel/bazel-bin
[end of symlink chain]
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //src:bazel BuildConfigurationValue.Key[3b7735e5f50c87f46f758d8a57e508cac18f76f2c5be2e7251c0415de6f7ed61] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkInfiniteExpansionException: Infinite symlink expansion, rootCauses={FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin], isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:665)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:531)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:443)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:271)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:541)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 0.398s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 5 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //src:bazel BuildConfigurationValue.Key[3b7735e5f50c87f46f758d8a57e508cac18f76f2c5be2e7251c0415de6f7ed61] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkInfiniteExpansionException: Infinite symlink expansion, rootCauses={FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin], isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:665)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:531)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:443)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:271)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:541)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: //src:bazel BuildConfigurationValue.Key[3b7735e5f50c87f46f758d8a57e508cac18f76f2c5be2e7251c0415de6f7ed61] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkInfiniteExpansionException: Infinite symlink expansion, rootCauses={FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/usr/local/google/home/brandjon/src/dev-bazel]/[bazel-bin], isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:665)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:531)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:443)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:271)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:541)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
FAILED: Build did NOT complete successfully (5 packages loaded, 5 targets configured)
```

**Comment by firstprayer** [comment]
I run into similar issue when using new_local_repository. Any update on this?

**Comment by brandjon** [comment]
This bug arises when the user manually creates a bogus symlink in the workspace. I don't know why `new_local_repository` would cause this error. Do you have a repro?

**Comment by janakdr** [comment]
No longer crashes. I think the issue was just that when we were evaluating globs, we might hit this symlink cycle and we previously didn't tolerate it. Now we do. Please reopen if there's anything else to be done.
