### ISSUE TITLE
Trying to build the Android Demo

### ISSUE THREAD

**Issue by islamoc** [bazelbuild/bazel#1036]
Hello I'm trying to build the Android Demo but I'm getting this error

ERROR: /home/islamoc/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar ... (remaining 14 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Mar 12, 2016 2:48:29 AM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp3833908848337265106/tmp-deduplicated/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /tmp/android_resources_tmp3833908848337265106/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
        at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
        at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
        at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
        at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:390)
        at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:321)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp3833908848337265106/tmp-deduplicated/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /tmp/android_resources_tmp3833908848337265106/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
        at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.913s, Critical Path: 13.51s

**Comment by dslomov** [comment]
@damienmg, could you take a quick look? Sounds like android SDK misconfiguration

**Comment by damienmg** [comment]
I guess it's missing the build_tools_version. What is the content of your WORKSPACE file?

**Comment by ahumesky** [comment]
The build_tools_version is a mandatory attribute (though I'm not sure if we
check for empty...), but from the error, bazel is looking for things here:
external/androidsdk/build-tools/23.0.1/aapt

**Comment by ahumesky** [comment]
So it looks like the build_tools_version is set to 23.0.1
Mennouchi, is build tools version 23.0.1 installed in your android sdk
through the android sdk manager?

**Comment by islamoc** [comment]
Hello After Updating the Android SDK I m getting this error

```
ERROR: /home/islamoc/tensorflow/tensorflow/core/BUILD:647:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib' failed: arm-linux-androideabi-gcc failed: error executing command external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables ... (remaining 63 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by damienmg** [comment]
Build with --verbose-failures?
Is the error consistent?

**Comment by islamoc** [comment]
with the --verbose-failures I get this

```
ERROR: /home/islamoc/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-23/android.jar --primaryData tensorflow/examples/android/res:tensorflow/examples/android/assets:tensorflow/examples/android/AndroidManifest.xml --srcJarOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --packagePath bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: resources_processor failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-23/android.jar --primaryData tensorflow/examples/android/res:tensorflow/examples/android/assets:tensorflow/examples/android/AndroidManifest.xml --srcJarOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --packagePath bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Mar 16, 2016 12:10:53 PM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp7182833080681937742/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp7182833080681937742/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
        at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
        at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
        at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
        at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:390)
        at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:321)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp7182833080681937742/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp7182833080681937742/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
        at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 9.359s, Critical Path: 8.31s
```

**Comment by ahumesky** [comment]
There should be an android_sdk_repository rule in the workspace file that points to the android sdk on your machine. Does that path + build-tools/23.0.1/aapt exist?

**Comment by islamoc** [comment]
yes it does exists and even when I check the directory that the error says it was not fount I can find it and I can find the aapt bin inside it

**Comment by ahumesky** [comment]
Hmm, well, I cloned tensorflow and bazel from head, build bazel, ran tensorflow's configure script, set the android_sdk_repository and android_ndk_repository rules to the appropriate paths, and did `bazel build tensorflow/examples/android:tensorflow_demo` and it seems to build...

Can you try running aapt directly? Do you have a 64 bit machine? As a wild guess, it might have to do with running a 32 bit binary on a 64 bit machine. Try running `ldd` on aapt, e.g.:
http://stackoverflow.com/questions/3949161/no-such-file-or-directory-but-it-exists

**Comment by islamoc** [comment]
Fixed the 64bit problem and now I'm getting a new error

```
ERROR: /home/islamoc/tensorflow/tensorflow/core/BUILD:647:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib' failed: arm-linux-androideabi-gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -iquote . -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles -iquote external/re2 -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive -isystem external/re2 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/google/protobuf/src -isystem third_party/eigen3 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-db7b61411772 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive/eigen-eigen-db7b61411772 '-mfpu=neon' '-std=c++11' '-DMIN_LOG_LEVEL=0' -DTF_LEAN_BINARY -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward '-frandom-seed=bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o' -MD -MF bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.d -c tensorflow/core/kernels/cwise_op_sub.cc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4: arm-linux-androideabi-gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -iquote . -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles -iquote external/re2 -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive -isystem external/re2 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/google/protobuf/src -isystem third_party/eigen3 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-db7b61411772 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive/eigen-eigen-db7b61411772 '-mfpu=neon' '-std=c++11' '-DMIN_LOG_LEVEL=0' -DTF_LEAN_BINARY -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward '-frandom-seed=bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o' -MD -MF bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.d -c tensorflow/core/kernels/cwise_op_sub.cc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 208.522s, Critical Path: 206.77s
```

**Comment by ahumesky** [comment]
Guessing from the "killed" part of "arm-linux-androideabi-gcc: internal compiler error: Killed", it might be that your machine is running out of memory. How much ram does the machine have?

You might consider setting the --jobs flag to something lower (the default is 200),
or try --local_resources or --ram_utilization_factor
See http://bazel.io/docs/bazel-user-manual.html for details on these flags

**Comment by islamoc** [comment]
I have 3.5Gb of RAM Yes I just found that I will use just 2 jobs and get back to you thank you for the help

**Comment by islamoc** [comment]
@ahumesky thank you it worked

**Comment by ahumesky** [comment]
Great, glad it's working for you now. --jobs 2 might be pretty slow, hopefully you can find a higher number that will still work for you
