### ISSUE TITLE
CC Toolchain broken with BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#10439]
The cc toolchain autodetection is supposed to honor the `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN` environment variable and disable itself. However, due to a bug in cc_configure.bzl, this does not work:

Error:
```
$ BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 /tmp/bazelisk query 'deps(//:hello)'
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at /root/.cache/bazel/_bazel_root/0ac9aaa84be7596bd25756e85851d609/external/bazel_tools/tools/cpp/cc_configure.bzl:143:15):
 - /root/.cache/bazel/_bazel_root/0ac9aaa84be7596bd25756e85851d609/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:385:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/0ac9aaa84be7596bd25756e85851d609/external/bazel_tools/tools/cpp/cc_configure.bzl", line 104
		repository_ctx.symlink(<2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/0ac9aaa84be7596bd25756e85851d609/external/bazel_tools/tools/cpp/cc_configure.bzl", line 104, in repository_ctx.symlink
		paths(<1 more arguments>)
'dict' object is not callable
```

[Actual cause](https://source.bazel.build/bazel/+/f511f09df0053a77f2660a1bd38cd08ca8dd3866:tools/cpp/cc_configure.bzl;l=104):
```
repository_ctx.symlink(paths("@bazel_tools//tools/cpp:BUILD.empty"), "BUILD")
```

The `paths` variable is a dict and the value should be accessed as `paths[...]`, not `paths(...)`.

**Comment by katre** [comment]
Reproduction:
```sh
touch WORKSPACE
cat >>hello.cc <<EOF
#include <iostream>

int main(int argc, char* argv[]) {
  std::cout << "Hello!" << std::endl;
  return 0;
}
EOF
cat >>BUILD.bazel <<EOF
cc_binary(
    name = "tool",
    srcs = ["hello.cc"],
)
genrule(
    name = "demo",
    outs = ["demo.out"],
    cmd = "\$(location :tool) > \$@",
    tools = [":tool"],
)
EOF
BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 bazel build //:demo
```

This should give an error, but not this error.
