### ISSUE TITLE
Generating code coverage report fails

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/bazel#10485]
#10071 # Description of the problem / feature request:

I'm trying to generate a code coverage report by running
```
bazel coverage --instrument_test_targets --instrumentation_filter="-test" -- //...
```

but I get the error

```
ERROR: /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/jdk/BUILD:309:1: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1851)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:333)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1530)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1860)
	... 14 more
```

I believe the --add-exports option was removed in later versions of java

### What operating system are you running Bazel on?

ubuntu 18.04

### What's the output of `bazel info release`?

(through bazelisk)

release 1.2.0

**Comment by j-bro** [comment]
I'm seeing this same issue (though using bazel 1.1.0). No local JDK installed either, it seems to be using `remotejdk11_linux` as per the given error. For me this only occurs when running the `coverage` command.

**Comment by ajguerrer** [comment]
I think this error is produced because `bazel coverage` requires building Java code (see the [installing Bazel](https://docs.bazel.build/versions/master/install-ubuntu.html#step-3-install-a-jdk-optional)).

**Comment by j-bro** [comment]
@ajguerrer thanks for the tip, I installed a JDK and the `bazel coverage` works now. Is it documented anywhere that this command requires building Java code? It's not clear to me which commands have this dependency and which don't.

**Comment by ajguerrer** [comment]
@j-bro I only happen to be passing by while waiting for #9406

**Comment by j-bro** [comment]
@ajguerrer thanks anyway, now I'm waiting on that issue as well.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
