### ISSUE TITLE
Bazel seems to require a ~/.netrc file to exist

### ISSUE THREAD

**Issue by brianduff** [bazelbuild/bazel#10486]
### Description of the problem / feature request:

Building simple java projects fails with a FileNotFoundException about .netrc. It doesn't seem like this file existing should be required.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# Ensure you don't yet have a .netrc
cp ~/.netrc ~/.netrc-bak
# Get the samples
git clone https://github.com/bazelbuild/examples/
# Build
cd java-tutorial && bazel build :ProjectRunner
```

See error message:

```
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'rules_java' which is a http_archive (rule definition at /private/var/tmp/_bazel_bduff/8033788efa3f2dab8262c5c3dfc67d9b/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_bduff/8033788efa3f2dab8262c5c3dfc67d9b/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:290:1
ERROR: An error occurred during the fetch of repository 'rules_java':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_bduff/8033788efa3f2dab8262c5c3dfc67d9b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_bduff/8033788efa3f2dab8262c5c3dfc67d9b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_bduff/8033788efa3f2dab8262c5c3dfc67d9b/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 219, in read_netrc
		ctx.read(filename)
java.io.FileNotFoundException: /Users/bduff/.netrc (No such file or directory)
```

### What operating system are you running Bazel on?

Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### What's the output of `bazel info release`?

release 2.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/examples/
84f298060b00f37924495ba4d8cbde1ff6d8e969
84f298060b00f37924495ba4d8cbde1ff6d8e969

**Comment by brianduff** [comment]
fwiw, it looks related to this:

https://github.com/bazelbuild/bazel/commit/c3d73f704f415248dc0f92d77e171cfd1fb1f327#diff-0a0d5a6b64e11b6bc5bab80ad3a90003R51

However, on my system, the return code is 1:

```
$ test -f /Users/bduff/.netrc; echo $?
1
```

So I'm not sure why it's passing this check.

**Comment by brianduff** [comment]
Bleh, I had a funky version of test on my PATH :) Closing.
