### ISSUE TITLE
java.nio.file.InvalidPathException: Trailing char < >

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#10481]
### Description of the problem:

`repository_ctx.which` can fail with an exception on Windows if `PATH` contains invalid entries. In particular this seems to be triggered by a non-existent entry ending on white-space such as `C:\Program Files `.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write a repository rule that calls `repository_ctx.which`. E.g.

```
# debug.bzl
def _debug(repository_ctx):
    print("cmd.exe", str(repository_ctx.which("cmd.exe")))
    repository_ctx.file("BUILD.bazel")

debug = repository_rule(
    _debug,
    environ = ["PATH"],
)

# WORKSPACE
load("//:debug.bzl", "debug")
debug(name = "debug")
```

And call Bazel with `PATH` containing an invalid entry as described above.
```
$ export PATH="C:\\Program Files "
$ bazel build @debug//...
```

This should produce the following error
```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@debug' (requested by nodes '@debug//..., excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 16: D:/Program Files /cmd.exe
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
	at com.google.devtools.build.lib.vfs.JavaIoFileSystem.exists(JavaIoFileSystem.java:119)
	at com.google.devtools.build.lib.vfs.Path.exists(Path.java:356)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.findCommandOnPath(SkylarkRepositoryContext.java:541)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.which(SkylarkRepositoryContext.java:518)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:128)
	at com.google.devtools.build.lib.syntax.CallUtils.callMethod(CallUtils.java:739)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:492)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:412)
	at com.google.devtools.build.lib.syntax.Eval.evalArguments(Eval.java:797)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:497)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:412)
	at com.google.devtools.build.lib.syntax.Eval.evalArguments(Eval.java:797)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:497)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:412)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:209)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:194)
	at com.google.devtools.build.lib.syntax.Eval.execStatementsInternal(Eval.java:233)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:60)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.call(StarlarkFunction.java:80)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:460)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:422)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:178)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:300)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:227)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
	... 4 more
```

See https://github.com/tweag/rules_haskell/commit/17f3cbacd02e752057383d6f249c63ed6b47b6b6 and [Azure CI pipeline](https://dev.azure.com/tweag/rules_haskell/_build/results?buildId=3352&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=11583e49-0f85-5cbb-c630-f1a2c5389c8b&l=53) for details.

### Expected behavior

Bazel should not throw an exception and ignore the inexistent `PATH` entry. If the tool is found in another entry then `repository_ctx.which` should use that one, otherwise return `None`.

### What operating system are you running Bazel on?

Windows Server 2016 (Azure vmImage: 'vs2017-win2016')

### What's the output of `bazel info release`?

release 1.1.0

(Observed the same with 1.2.1)

**Comment by laurentlb** [comment]
cc @laszlocsomor

**Comment by laszlocsomor** [comment]
Thanks for the easy repro.
The bug is present in Bazel 2.1.0rc1 too.
