### ISSUE TITLE
Illegal char "<" in Windows

### ISSUE THREAD

**Issue by JimHan75d8c5** [bazelbuild/bazel#10521]
### Description of the problem :
Bazel tried to create a Directory with char "<" and ">" in the name, and failed:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//release:amd64_package BuildConfigurationValue.Key[5c022c84dbdf6c26c419419a7b34dfd9277563d6f1fff84f0c1b1c57749e9900] false, actionIndex=0}' (requested by nodes 'ActionLookupData{actionLookupKey=//release:amd64_package BuildConfigurationValue.Key[5c022c84dbdf6c26c419419a7b34dfd9277563d6f1fff84f0c1b1c57749e9900] false, actionIndex=1}')  
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 103: C:/users/jimhan/_bazel_jimhan/um2gyhv3/execroot/core/bazel-out/x64_windows-fastbuild/bin/release/<derived root>
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.createDirectoryAndParents(JavaIoFileSystem.java:251)
        at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:549)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.createOutputDirectories(SkyframeActionExecutor.java:1208)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:134)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:972)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:585)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:288)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
```

### What operating system are you running Bazel on?

Windows 1909, version 10.0.18363.535

### What's the output of `bazel info release`?

release 2.0.0

**Comment by irengrig** [comment]
Maybe related: #10096

**Comment by laurentlb** [comment]
cc @laszlocsomor

**Comment by laszlocsomor** [comment]
@JimHan75d8c5 : how can we repro this issue?

**Comment by JimHan75d8c5** [comment]
Try [this](https://github.com/v2ray/v2ray-core) ?
``` bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:all ```

I'm sorry about the delay. 😐
