### ISSUE TITLE
AndroidResourceLink worker spews errors to stdout, killing worker contract

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#10527]
### Description of the problem / feature request:

AndroidResourceLink reports aapt2 errors to stdout, causing the build to crash, rather than to fail in an orderly way. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use a project with a bad manifest (say, butterknife which has a package attribute of "butterknife" which aapt2 rejects, and build. The aapt2 error will spew into stdout, and the worker will crash. 

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

1.2.0
2.0.0

**Comment by cgruber** [comment]
```
ERROR: /private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/external/maven/com/jakewharton/BUILD.bazel:56:1: Linking static android resource library for @maven//com/jakewharton:butterknife_main failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log snippet, file at /private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/bazel-workers/worker-7-AndroidResourceLink.log ---8<---8<---
[... truncated ...]
vyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/filtered/bazel-out/android-x86_64-fastbuild/bin/external/maven/com/jakewharton/butterknife_main_symbols/symbols.zip\
	-I\
	external/androidsdk/platforms/android-29/android.jar\
	--auto-add-overlay\
	-o\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/lib.apk\
	--java\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/java\
	--output-text-symbols\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/R.txt
Output:
aapt2 W 01-06 10:12:48 90382 4748714 ApkAssets.cpp:138] resources.arsc in APK 'external/androidsdk/platforms/android-29/android.jar' is compressed.
/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/manifest-aapt-dummy/AndroidManifest.xml:2: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'butterknife'.

	at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:254)
	at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:195)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$11.call(ResourceProcessorBusyBox.java:126)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.runPersistentWorker(ResourceProcessorBusyBox.java:211)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:196)

Exception in thread "main" java.lang.RuntimeException: Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@1e6d1014:
Command: bazel-out/host/bin/external/androidsdk/aapt2_binary\
	link\
	--static-lib\
	--manifest\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/manifest-aapt-dummy/AndroidManifest.xml\
	--no-static-lib-packages\
	--no-version-vectors\
	-R\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/filtered/bazel-out/android-x86_64-fastbuild/bin/external/maven/com/jakewharton/butterknife_main_symbols/symbols.zip\
	-I\
	external/androidsdk/platforms/android-29/android.jar\
	--auto-add-overlay\
	-o\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/lib.apk\
	--java\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/java\
	--output-text-symbols\
	/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/R.txt
Output:
aapt2 W 01-06 10:12:48 90382 4748714 ApkAssets.cpp:138] resources.arsc in APK 'external/androidsdk/platforms/android-29/android.jar' is compressed.
/var/folders/80/cvns3bxx7x9gnhvyy2sttysh0000gn/T/android_resources_tmp2401537380624932024/manifest-aapt-dummy/AndroidManifest.xml:2: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'butterknife'.

	at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:254)
	at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:195)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$11.call(ResourceProcessorBusyBox.java:126)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.runPersistentWorker(ResourceProcessorBusyBox.java:211)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:196)
---8<---8<--- End of log snippet, 2979 chars omitted ---8<---8<---
Target //samples/api-demo:api-demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by cgruber** [comment]
What's weird, is that if I do `--strategy=AndroidResourceLink=standalone` (or sandboxed) it seems to have no effect in 2.0.0, but it does seem to work in 1.2.0.  Regression?

**Comment by ahumesky** [comment]
Looks like this is solved by https://github.com/bazelbuild/bazel/pull/10911, please reopen if this is still an issue

**Comment by jeraldsun** [comment]
I got the same aapt2 error(`attribute 'package' in <manifest> tag is not a valid Android package name: 'butterknife'`), how can we fix it in Bazel? (PS, this problem doesn't appear in gradle). Looking forward to your kindly reply.

**Comment by keith** [comment]
Can you file a new issue with a repro case?

**Comment by jeraldsun** [comment]
> Can you file a new issue with a repro case?

Sure. I'll file a new issue.
