### ISSUE TITLE
Bazel CI: rules_jvm_external, //tests/integration:UnsafeSharedCacheTest is failing with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10551]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1344#447a34e2-beeb-4889-91f6-c5e4a56a4190
The test log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tests/integration:UnsafeSharedCacheTest
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.025
There was 1 failure:
1) test_jarsOnClassPath_areInTheSharedCache(com.jvm.external.UnsafeSharedCacheTest)
java.lang.AssertionError: 
Expected: a string containing ".cache/coursier/v1"
     but: was "/tmp/custom_coursier_cache/https/repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.jvm.external.UnsafeSharedCacheTest.test_jarsOnClassPath_areInTheSharedCache(UnsafeSharedCacheTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2020-01-09 13:13:55 --

```

I couldn't reproduce this on my local machine.
@jin, can you help investigating this issue?

**Comment by jin** [comment]
yes, I can look into this.

**Comment by jin** [comment]
Fixed by https://github.com/bazelbuild/rules_jvm_external/commit/e799854e25ed687fda29f5fc43e2dd907eadc7c9

**Comment by jin** [comment]
Confirmed fixed in tonight's downstream run https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1345
