### ISSUE TITLE
Bazel 'MSVC_ENVVARS' is referenced before assignment Windows 10

### ISSUE THREAD

**Issue by coded5282** [bazelbuild/bazel#10565]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

When I run 'bazel build //examples/cpp:hello-world" as shown in the tutorial (https://docs.bazel.build/versions/master/windows.html#build-c) , I get this:

C:\Users\test\Downloads\bazel-master>bazel build //example/cpp:hello-world
ERROR: C:/users/test/downloads/bazel-master/src/main/res/winsdk_configure.bzl:39:1: file '@bazel_tools//tools/cpp:cc_configure.bzl' does not contain symbol 'MSVC_ENVVARS'
ERROR: C:/users/test/downloads/bazel-master/src/main/res/winsdk_configure.bzl:172:20: Traceback (most recent call last):
        File "C:/users/test/downloads/bazel-master/src/main/res/winsdk_configure.bzl", line 169
                repository_rule(implementation = _impl, local = Tr..., ...))
        File "C:/users/test/downloads/bazel-master/src/main/res/winsdk_configure.bzl", line 172, in repository_rule
                list(MSVC_ENVVARS)
        File "C:/users/test/downloads/bazel-master/src/main/res/winsdk_configure.bzl", line 172, in list
                MSVC_ENVVARS
global variable 'MSVC_ENVVARS' is referenced before assignment.
ERROR: error loading package '': Extension file 'src/main/res/winsdk_configure.bzl' has errors
ERROR: error loading package '': Extension file 'src/main/res/winsdk_configure.bzl' has errors
INFO: Elapsed time: 0.610s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

Windows 10. Also using Visual Studio 2017.

### What's the output of `bazel info release`?

release 0.24.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/10049 looks similar but for Ubuntu and doesn't seem to have a conclusive solution.

> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

My overall goal for building with Bazel is so that I can use Tensorflow with GPU in C++. I've been following this tutorial (https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows) for that. According to this table (https://www.tensorflow.org/install/source_windows), I need bazel 0.24.1, even though I know it might be a bit old at this point since I'm using tensorflow-gpu-1.14.0 and CUDA 10.0.

The output of "set BAZEL_" in the Command Prompt is:
BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
BAZEL_WINSDK_FULL_VERSION=10.0.17763.0

Any suggestions would be greatly appreciated, thanks!

**Comment by coded5282** [comment]
My bad, I was getting this error because I downloaded the wrong branch of bazel when running the example. I accidentally downloaded master instead of 0.24.1
