### ISSUE TITLE
Hard crash with bazel cquery //external:all

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#10602]
Repro with Bazel 2.0.0:

```
mkdir /tmp/cquery_crash
cd !$
touch WORKSPACE
bazel cquery //external:all
```

crashes with

```
FAILED: Build did NOT complete successfully (0 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//external:all, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e' (requested by nodes '[//external:all] EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:bazel_tools
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:268)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:64)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:226)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:107)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:87)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:146)
	at com.google.devtools.build.lib.pkgcache.TargetPatternResolverUtil.resolvePackageTargets(TargetPatternResolverUtil.java:46)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:135)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:480)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:76)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//external:all, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e' (requested by nodes '[//external:all] EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:bazel_tools
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:268)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:64)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:226)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:107)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:87)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:146)
	at com.google.devtools.build.lib.pkgcache.TargetPatternResolverUtil.resolvePackageTargets(TargetPatternResolverUtil.java:46)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:135)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:480)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:76)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by gregestren** [comment]
This is relevant: https://github.com/bazelbuild/bazel/blob/007315319a72d62ae2d6d0e3d8de6701e8d095a1/src/main/java/com/google/devtools/build/lib/packages/TargetUtils.java#L222-L225

I think that comment is already outdated (this already applies to non-test rules). But it still assumes rules have the `tags` attribute, which most do. This big shows not *all* do. :/

**Comment by jin** [comment]
I cannot reproduce this on 6.1.0. It appears to have been fixed.
