### ISSUE TITLE
Build event uploader is leaking threads

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#10603]
### Description of the problem:

When running my build over and over again, the Bazel server increases the thread count by 100-200 new threads. At about 3000 threads, my system collapses when there are no free resources to spawn new threads or processes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately, I don't have a minimal example, but it is reproducible every time on my setup.

The system constraint is as follows:
OS: CentOS Linux 7 (Core)
uname -srv: Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018

Inside this, I have a docker image based on ubuntu:18.04. The docker container runs with --read-only, but mounts a source code repository, another directory to which I set `--output_user_root` and `/tmp`.

Inside the docker container, I run `bazel test --remote_executor=grpc://xyz --genrule_strategy=remote --spawn_strategy=remote --remote_download_toplevel ...` several times.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 2.0.0

###  Have you found anything relevant by searching the web?

#8432 Bazel 0.25.2 hangs after running a few jobs
#6806 Unbounded thread pool in ByteStreamBuildEventArtifactUploader

https://support.datastax.com/hc/en-us/articles/206259833-Nodes-appear-unresponsive-due-to-a-Linux-futex-wait-kernel-bug
This site recommends to run `sudo rpm -q --changelog kernel-`uname -r` | grep futex | grep ref` and the output shows that the patches are included.

### Any other information, logs, or outputs that you want to share?

I've attached a couple of `jstack` dumps before, during and after running a build together with output from `ps`.
[ps-bazel-thread-pool-after-3-builds.txt](https://github.com/bazelbuild/bazel/files/4074075/ps-bazel-thread-pool-after-3-builds.txt)
[jstack-a-after-2-builds.txt](https://github.com/bazelbuild/bazel/files/4074076/jstack-a-after-2-builds.txt)
[jstack-b-during-build-3.txt](https://github.com/bazelbuild/bazel/files/4074077/jstack-b-during-build-3.txt)
[jstack-c-after-3-builds.txt](https://github.com/bazelbuild/bazel/files/4074078/jstack-c-after-3-builds.txt)

**Comment by moroten** [comment]
The bug is probably here:
`src/main/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploader.java`
```
    this.uploadExecutor =
        MoreExecutors.listeningDecorator(
            Executors.newFixedThreadPool(Math.min(maxUploadThreads, 1000)));
```
There is no shutdown call, so these threads will stay around forever. 

After removing the `--bes_backend` and `--bes_results_url` flags solves the problem. Thread count is now stable.

Also, please add names to threads in this thread pool to simplify future investigations.

**Comment by endobson** [comment]
I'm seeing similar issues on macOS.

Example stack trace of crashing bazel:

```
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at com.google.devtools.build.lib.skyframe.FilesystemValueChecker.getDirtyValues(FilesystemValueChecker.java:515)
        at com.google.devtools.build.lib.skyframe.FilesystemValueChecker.getDirtyKeys(FilesystemValueChecker.java:104)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:509)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:359)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:260)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:598)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:506)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:205)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
unable to create native thread: possibly out of memory or process/resource limits reached
```

**Comment by meisterT** [comment]
cc @ericfelly

**Comment by ericfelly** [comment]
@michaeledgar please take a look

**Comment by kzadorozhny** [comment]
We just hit the same problem after enabling `--bes_backend` in our CI builds. We do not run distributed builds, but we do keep build workers hot to shave 2-3 minutes from build startup time.

The one example of unhealthy bazel process:
```
$ ps H -o 'tid comm' $(pidof bazel) | wc -l
4471
```

**Comment by michaeledgar** [comment]
I've reproduced this in bazel 3.0 using Google's RBE for remote caching (no execution necessary). Should have a fix coming shortly.

**Comment by michaeledgar** [comment]
Fix out for review: https://bazel-review.googlesource.com/c/bazel/+/133578
