### ISSUE TITLE
`.../test.cache_status (Permission denied)` crashes Bazel server

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#10633]
### Description of the problem / feature request:

Attempts to read the `test.cache_status` file flakily results in a hard crash of the Bazel server with `Permission denied`.

### Feature requests: what underlying problem are you trying to solve with this feature?

The remote cache should not crash the Bazel server.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Due to low flake rate, we have not found a minimal repro. Our setup is:
1. Environment: fresh docker container for each build, but shared output base between container instances (concurrency limited to 1, so an output base has at most one container using it).
0. Bazel setup: Remote cache using GCS backend.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

`release 2.0.0`

###  Have you found anything relevant by searching the web?

Possible related (from 2016): https://github.com/bazelbuild/bazel/issues/1413

### Any other information, logs, or outputs that you want to share?

Crash stack trace:
```
ERROR: /code/<redacted: package>/BUILD:87:1: Couldn't build file <redacted: package>/<redacted: target>/test.log:  failed due to unexpected I/O exception: /tmp/build_output/2.0.0/933c2f549343e099e3a6911b282cb71c/execroot/__main__/bazel-out/<redacted: cpu>/testlogs/<redacted: package>/<redacted: target>/test.cache_status (Permission denied)
  | com.google.devtools.build.lib.vfs.FileAccessException: /tmp/build_output/2.0.0/933c2f549343e099e3a6911b282cb71c/execroot/__main__/bazel-out/<redacted: cpu>/testlogs/<redacted: package>/<redacted: target>/test.cache_status (Permission denied)
  | at com.google.devtools.build.lib.vfs.AbstractFileSystem.getOutputStream(AbstractFileSystem.java:137)
  | at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:524)
  | at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:512)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.saveCacheStatus(TestRunnerAction.java:374)
  | at com.google.devtools.build.lib.exec.TestStrategy.postTestResult(TestStrategy.java:304)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.finalizeTest(StandaloneTestStrategy.java:226)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.access$300(StandaloneTestStrategy.java:74)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.finalizeTest(StandaloneTestStrategy.java:471)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction$RunAttemptsContinuation.process(TestRunnerAction.java:1130)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction$RunAttemptsContinuation.execute(TestRunnerAction.java:1074)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:827)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:816)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:905)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1040)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1011)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:589)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:902)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:292)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
```
The above trace is repeated is printed 3 times.

**Comment by janakdr** [comment]
Is there anything more to that stack trace? It on its own shouldn't lead to a hard crash. There might be something more in the bazel logfile, even if not on the console?

**Comment by aiuto** [comment]
closing for lack of action
