### ISSUE TITLE
Bazel@HEAD can't build some projects on Bazel CI

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#10644]
### Description of the problem / feature request:

Commit a948eb7255b8418f0bba1c819a58972066577d6f broke "Bazel Codelabs" on Bazel CI.

Log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1362#7804d324-576c-4e08-b5ba-d532cf8230bd

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro:
1. get https://github.com/bazelbuild/codelabs/commit/00431a92aea39eacdbb49a5cf23e31e2ad82ebaf
2. build Bazel at https://github.com/bazelbuild/bazel/commit/a948eb7255b8418f0bba1c819a58972066577d6f
3. with that Bazel do: `bazel build --nobuild //...`

Output:
```
INFO: Repository 'go_googleapis' used the following cache hits instead of downloading the corresponding file.
 * Hash 'f01a10f3624f078e9d250c9d958f8dc816d29e34cb19709adb5428dea58fb4f2' for https://mirror.bazel.build/github.com/googleapis/googleapis/archive/91ef2d9dd69807b0b79555f22566fb2d81e49ff9.zip
If the definition of 'go_googleapis' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'go_googleapis':
   Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
ERROR: /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/org_golang_google_grpc/status/BUILD.bazel:3:1: @org_golang_google_grpc//status:go_default_library depends on @go_googleapis//google/rpc:status_go_proto in repository @go_googleapis which failed to fetch. no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
ERROR: Analysis of target '//go/cmd/server:go-server' failed; build aborted: no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/a845ef458794d1b017aa1d5bf09ca4e1/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
INFO: Elapsed time: 7.828s
```

### What operating system are you running Bazel on?

Debian Testing

**Comment by laszlocsomor** [comment]
Similar pipeline failures:
- rules_go [log](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1362#26c58118-908c-4eb6-a545-2664d373cbb7)
- rules_k8s [log](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1362#a3a69bd7-f377-4ca8-aae5-19f74cff2d8c)

**Comment by c-parsons** [comment]
What's the status of this?

**Comment by meteorcloudy** [comment]
This is due to https://github.com/bazelbuild/bazel/issues/10681

**Comment by meteorcloudy** [comment]
The fix for rules_go is at https://github.com/bazelbuild/rules_go/pull/2355, we need to update the rules_go version after that's merged.

**Comment by nlopezgi** [comment]
Could we get a patch release of rules_go to go with this fix please. See https://github.com/bazelbuild/rules_k8s/pull/517#issuecomment-581451960
