### ISSUE TITLE
Crash for --compilation_mode in transition

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#10690]
### Description of the problem

`//command_line_option:compilation_mode` exposes a Java class when used as input in a transition, not a string. It is possible to set it to a string as output, but not to read the input.

The same problem also applies for `//command_line_option:run_under` and possibly more.

I would prefer a quick fix for `compilation_mode` whereas `run_under` is not such a big problem for me (just annoying).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
touch WORKSPACE

cat <<EOF > BUILD.bazel
load(":rules.bzl", "rule_with_transition")

rule_with_transition(
    name = "my_target",
)
EOF

cat <<EOF > rules2.bzl
def _my_transition_impl(settings, attr):
    print(settings)
    return dict(settings)

inputs_and_outputs = [
    "//command_line_option:cpu",
    "//command_line_option:compilation_mode",
    "//command_line_option:platform_suffix",
]

my_transition = transition(
    implementation = _my_transition_impl,
    inputs = inputs_and_outputs,
    outputs = inputs_and_outputs,
)

def _rule_impl(ctx):
    pass

rule_with_transition = rule(
    implementation = _rule_impl,
    cfg = my_transition,
    attrs = {
        "_whitelist_function_transition": attr.label(default = "@bazel_tools//tools/whitelists/function_transition_whitelist"),
    },
)
EOF

bazel build :my_target
```

### What operating system are you running Bazel on?

Linux (Ubuntu 17.04)

### What's the output of `bazel info release`?

`release 2.0.0`

###  Have you found anything relevant by searching the web?

GitHub issues: https://github.com/bazelbuild/bazel/issues
- Nothing found.

### Any other information, logs, or outputs that you want to share?

```
Internal error thrown during build. Printing stack trace: java.lang.IllegalArgumentException: cannot expose internal type to Starlark: class com.google.devtools.build.lib.analysis.config.CompilationMode
	at com.google.devtools.build.lib.syntax.Starlark.fromJava(Starlark.java:122)
	at com.google.devtools.build.lib.syntax.Dict.putAllUnsafe(Dict.java:350)
	at com.google.devtools.build.lib.syntax.Dict.plus(Dict.java:531)
	at com.google.devtools.build.lib.syntax.MethodLibrary.dict(MethodLibrary.java:584)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:126)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.call(BuiltinCallable.java:69)
	at com.google.devtools.build.lib.syntax.CallUtils.call(CallUtils.java:600)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:493)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:407)
	at com.google.devtools.build.lib.syntax.Eval.execReturn(Eval.java:186)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:224)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:197)
	at com.google.devtools.build.lib.syntax.Eval.execStatementsInternal(Eval.java:233)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:59)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.call(StarlarkFunction.java:93)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:326)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:290)
	at com.google.devtools.build.lib.analysis.config.StarlarkDefinedConfigTransition$RegularTransition.evalFunction(StarlarkDefinedConfigTransition.java:285)
	at com.google.devtools.build.lib.analysis.config.StarlarkDefinedConfigTransition$RegularTransition.evaluate(StarlarkDefinedConfigTransition.java:213)
	at com.google.devtools.build.lib.analysis.skylark.FunctionTransitionUtil.applyAndValidate(FunctionTransitionUtil.java:78)
	at com.google.devtools.build.lib.analysis.skylark.StarlarkRuleTransitionProvider$FunctionPatchTransition.patch(StarlarkRuleTransitionProvider.java:111)
	at com.google.devtools.build.lib.analysis.config.transitions.PatchTransition.apply(PatchTransition.java:70)
	at com.google.devtools.build.lib.analysis.config.transitions.ComposingTransition.apply(ComposingTransition.java:53)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.applyTransition(ConfigurationResolver.java:546)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfigurations(SkyframeExecutor.java:2039)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.getConfigurationsFromExecutor(ConfigurationResolver.java:710)
	at com.google.devtools.build.lib.analysis.AnalysisUtils.getTargetsWithConfigs(AnalysisUtils.java:209)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:254)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:271)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:543)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:205)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by sdtwigg** [comment]
There is a systematic issue where the transitions API will blindly return the current value of any command_line_arg requested as an input. A lot of them, e.g. compilation_mode, are stored as various Java classes, e.g. an Enum, that do do not have the proper StarlarkAPIs attached.

Raising the issue with the Front End team to see if we can determine a generally applicable solution (versus playing too much whack-a-mole with Starlark options).

**Comment by laurentlb** [comment]
cc @alandonovan

**Comment by alandonovan** [comment]
FunctionTransitionUtil.buildSettings constructs a Dict whose values are options, which are not legal Starlark values, so it must be changed. (Also, the type of the argument passed to Starlark.call should be Map not Dict, as 'call' does not implicitly convert values as if by Starlark.fromJava. The actual value is in fact a Dict, at least for now, but we should enforce this in the Java types.)

The doc for the transition implementation function says: 

"This function always has two parammeters [sic]: settings and attr. The settings param is a dictionary whose set of keys is defined by the inputs parameter. So, for each build setting --//foo=bar, if inputs contains //foo, settings will have an entry settings['//foo']='bar'."

From this description, I would expect the dict values to be strings of text as they appeared on the command line. Whether or not this was the intent, the documentation should be made more explicit. Similarly, the documentation of the return value should also be clarified with respect to the dict element types, and the meaning of the dict-of-dict case for split transitions.

**Comment by gregestren** [comment]
@brandjon @juliexxia  this reminds me of older discussions of how much typing should be applied at the point of usage in transitions. Was this documented or recorded anywhere?

There was some real thought in what `settings` and the return values should support. I think we should recall that as a starting point for figuring out how to handle this. I agree that we really need to advance this from a principled root perspective vs. one-off tweaks.

**Comment by sventiffe** [comment]
According to the descriptions in the commits this bug can be considered fixed?
