### ISSUE TITLE
bazel and rhel 7.7 mapio

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/bazel#10763]
### Description of the problem / feature request:

bazel is not working on rhel7.7 . Works fine on Ubuntu image

### Feature requests: what underlying problem are you trying to solve with this feature?

moving infra on redhat.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

docker run -it registry.redhat.io/rhel7:latest bash 
some packages in WORKSPACE
bazel build //...

### What operating system are you running Bazel on?

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)

### What's the output of `bazel info release`?

29.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

IBM repo.

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
DEBUG: Call stack for the definition of repository 'build_bazel_rules_nodejs' which is a git_repository (rule definition at /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /app/WORKSPACE:349:1
INFO: Call stack for the definition of repository 'com_github_golang_protobuf' which is a git_repository (rule definition at /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/go/private/repositories.bzl:188:9
 - /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/go/private/repositories.bzl:92:5
 - /app/WORKSPACE:252:1
ERROR: An error occurred during the fetch of repository 'com_github_golang_protobuf':
   Traceback (most recent call last):
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/git.bzl", line 178
		patch(ctx)
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/third_party/com_github_golang_protobuf-gazelle.patch: java.io.IOException: Cannot run program "patch" (in directory "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/com_github_golang_protobuf"): error=2, No such file or directory
ERROR: /app/tools/cedp_ci/BUILD.bazel:5:1: //tools/cedp_ci:go_default_library depends on @com_github_golang_protobuf//ptypes:go_default_library in repository @com_github_golang_protobuf which failed to fetch. no such package '@com_github_golang_protobuf//ptypes': Traceback (most recent call last):
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/git.bzl", line 178
		patch(ctx)
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/third_party/com_github_golang_protobuf-gazelle.patch: java.io.IOException: Cannot run program "patch" (in directory "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/com_github_golang_protobuf"): error=2, No such file or directory
ERROR: Analysis of target '//tools/cedp_ci:cedp_ci' failed; build aborted: no such package '@com_github_golang_protobuf//ptypes': Traceback (most recent call last):
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/git.bzl", line 178
		patch(ctx)
	File "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/third_party/com_github_golang_protobuf-gazelle.patch: java.io.IOException: Cannot run program "patch" (in directory "/home/jenkins/.cache/bazel/_bazel_jenkins/8c069df52082beee3c95ca17836fb8e2/external/com_github_golang_protobuf"): error=2, No such file or directory
INFO: Elapsed time: 71.074s

```

**Comment by systemlogic** [comment]
Patch is not available on the rhel7.7
