### ISSUE TITLE
bazel query //external:all and //external:* fails with exception

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1088]
Running the bazel query from the example on external repositories fails:

    $ bazel query 'kind(maven_jar, //external:*)'
    ..........
    java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN://external:*' (requested by nodes )
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:996)
            at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalArgumentException
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
            at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:33)
            at com.google.devtools.build.lib.skyframe.PackageValue.key(PackageValue.java:57)
            at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackage(EnvironmentBackedRecursivePackageProvider.java:60)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getPackage(RecursivePackageProviderBackedTargetPatternResolver.java:89)      
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:136)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:129)
            at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:372)
            at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:69)
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:947)

Our repository does, in fact, have a maven_jar in it, but more relevant is a desire to easily track down all of the direct dependencies of bound external targets.

**Comment by kchodorow** [comment]
Definitely shouldn't crash, thanks for the report.

**Comment by bsilver8192** [comment]
Looks related to my massive "use labels in the main repository than the default one" change. However, I can't reproduce it with current master (e25642a2bcb68d553fe56b0c3d6262544b15a870). Have you tried that? If it still crashes, can you also try `bazel query 'kind(maven_jar, @//external:*)'`?

**Comment by shahms** [comment]
This appears to be fixed in 0.2.1:

    $ bazel info release
    release 0.2.1-2016-03-31 (@950c1ab)
    $ bazel query 'kind(maven_jar, @//external:*)'
    //external:maven_guava
    $ bazel query 'kind(maven_jar, @//external:all)'
    //external:maven_guava
    $ bazel query 'kind(maven_jar, //external:all)'
    //external:maven_guava
    $ bazel query 'kind(maven_jar, //external:*)'
    //external:maven_guava

**Comment by shahms** [comment]
Apparently spoke too soon, this does appear to be an issue with bazel release 0.2.1:

    $ bazel info release
    ......
    release 0.2.1
    $ PATTERNS=(
    > "@//external:*"
    > "@//external:all"
    > "//external:*"
    > "//external:all"
    > )
    $ for pattern in "${PATTERNS[@]}"; do bazel query "kind(maven_jar, $pattern)"; done
    ......
    //external:maven_guava
    //external:maven_guava
    java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN://external:*' (requested by nodes )
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:996)
            at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalArgumentException
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
            at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:33)
            at com.google.devtools.build.lib.skyframe.PackageValue.key(PackageValue.java:57)
            at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackage(EnvironmentBackedRecursivePackageProvider.java:60)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getPackage(RecursivePackageProviderBackedTargetPatternResolver.java:89)      
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:136)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:129)
            at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:372)
            at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:69)
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:947)
            ... 4 more
    ......
    java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN://external:all' (requested by nodes )
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:996)
            at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalArgumentException
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
            at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:33)
            at com.google.devtools.build.lib.skyframe.PackageLookupValue.key(PackageLookupValue.java:100)
            at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.isPackage(EnvironmentBackedRecursivePackageProvider.java:97)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.isPackage(RecursivePackageProviderBackedTargetPatternResolver.java:172)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetOrNull(RecursivePackageProviderBackedTargetPatternResolver.java:100)
            at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetOrNull(RecursivePackageProviderBackedTargetPatternResolver.java:55) 
            at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.getWildcardConflict(TargetPattern.java:429)

I suspect it depends on something in our BUILD/WORKSPACE triggering the bug.  The same results happen without the `kind()` filter, but the output is much longer :-)

**Comment by bsilver8192** [comment]
Does it fail consistently with some version of your code, or is it sometimes failing and sometimes succeeding, possibly after a `bazel shutdown`?

**Comment by shahms** [comment]
The non-@-prefixed patterns consistently fail at https://github.com/google/kythe/commit/9022741ae18b2911fd180b1770e0c562ff3fd0b9 with bazel release 0.2.1

**Comment by shahms** [comment]
FWIW this consistently succeeds with 812227f8733a2b6679cd9b06cea26fe238afb8dd. Marking this "fixed", although unintentional fixes make me worry about future regressions.
