### ISSUE TITLE
SkyframeTests's testThreeSharedActionsRacing is flaky

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10903]
This test looks to be inherently racy with various `Thread.sleep` calls employed to get racing threads into the right state.

Here's the hanging stacks:
```
Executing tests from //src/test/java/com/google/devtools/build/lib/skyframe:SkyframeTests
-----------------------------------------------------------------------------
JUnit4 Test Runner
...........Mar 05, 2020 12:31:28 AM com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate run
WARNING: Aborting evaluation due to com.google.devtools.build.lib.skyframe.DirectoryListingFunction$DirectoryListingFunctionException: com.google.devtools.build.lib.actions.InconsistentFilesystemException: Inconsistent filesystem operations. /root/workspace/pkg is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'bazel clean' and investigate the filesystem inconsistency (likely due to filesystem updates concurrent with the build) while evaluating DIRECTORY_LISTING:[/root/workspace]/[pkg]
.......Mar 05, 2020 12:31:32 AM com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate run
WARNING: Aborting evaluation due to com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction$SkylarkImportLookupFunctionException: com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction$SkylarkImportFailedException: Every .bzl file must have a corresponding package, but '//does_not:exist.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist. while evaluating //does_not:exist.bzl
......Mar 05, 2020 12:31:35 AM com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate run
WARNING: Aborting evaluation due to com.google.devtools.build.lib.skyframe.FileFunction$FileFunctionException: com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle while evaluating FILE:[/workspace]/[local/repo/WORKSPACE]
..........Mar 05, 2020 12:31:41 AM com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate run
WARNING: Aborting evaluation due to com.google.devtools.build.lib.skyframe.RegisteredToolchainsFunction$RegisteredToolchainsFunctionException: com.google.devtools.build.lib.skyframe.RegisteredToolchainsFunction$InvalidToolchainLabelException: invalid registered toolchain '/:invalid:label:syntax': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/:invalid:label:syntax' while evaluating RegisteredToolchainsValue.Key{configurationKey: BuildConfigurationValue.Key[3c75e754036d687484a6df3e1cc6e40d2a40146cf8773c2e3438ad2dc844d14b]}
...
Received SIGTERM; writing test XML
Done writing test XML
Dumping stack traces for all threads

Starting full thread dump ...

"main" Id=1 WAITING on java.lang.Object@32988502
	at java.base@11.0.6/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@32988502
	at java.base@11.0.6/java.lang.Object.wait(Object.java:328)
	at app//com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.reallyAwaitTermination(AbstractQueueVisitor.java:571)
	at app//com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.awaitTermination(AbstractQueueVisitor.java:530)
	at app//com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.awaitQuiescence(AbstractQueueVisitor.java:276)
	at app//com.google.devtools.build.skyframe.NodeEntryVisitor.waitForCompletion(NodeEntryVisitor.java:73)
	at app//com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:277)
	at app//com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:250)
	at app//com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at app//com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:77)
	at app//com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at app//com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at app//com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorTest.evaluate(SequencedSkyframeExecutorTest.java:627)
	at app//com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorTest.testThreeSharedActionsRacing(SequencedSkyframeExecutorTest.java:923)
	at java.base@11.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.6/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at app//org.junit.runners.Suite.runChild(Suite.java:128)
	at app//org.junit.runners.Suite.runChild(Suite.java:27)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at app//com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at app//com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at app//com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
	at app//com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)

"skyframe-evaluator 0" Id=1381 TIMED_WAITING on java.util.concurrent.CountDownLatch$Sync@2567b697
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CountDownLatch$Sync@2567b697
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base@11.0.6/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at app//com.google.common.util.concurrent.Uninterruptibles.awaitUninterruptibly(Uninterruptibles.java:84)
	at app//com.google.devtools.build.skyframe.TrackingAwaiter.waitAndMaybeThrowInterrupt(TrackingAwaiter.java:57)
	at app//com.google.devtools.build.skyframe.TrackingAwaiter.awaitLatchAndTrackExceptions(TrackingAwaiter.java:74)
	at app//com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorTest.lambda$testThreeSharedActionsRacing$7d690940$1(SequencedSkyframeExecutorTest.java:817)
	at app//com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorTest$$Lambda$400/0x00000008407c8040.call(Unknown Source)
	at app//com.google.devtools.build.lib.actions.util.TestAction.execute(TestAction.java:126)
	at app//com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:966)
	at app//com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1114)
	at app//com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1085)
	at app//com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:136)
	at app//com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
	at app//com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:612)
	at app//com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
	at app//com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
	at app//com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	at app//com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@4d5d945d

"skyframe-evaluator 1" Id=1382 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@53ea9080
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@53ea9080
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.6/java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:547)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

"skyframe-evaluator 2" Id=1383 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@53ea9080
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@53ea9080
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.6/java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:547)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

"Reference Handler" Id=2 RUNNABLE (daemon)
	at java.base@11.0.6/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@11.0.6/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
	at java.base@11.0.6/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@4b803f0e (daemon)
	at java.base@11.0.6/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@4b803f0e
	at java.base@11.0.6/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@11.0.6/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@11.0.6/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" Id=4 RUNNABLE (daemon)

"Common-Cleaner" Id=11 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@4093c67 (daemon)
	at java.base@11.0.6/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@4093c67
	at java.base@11.0.6/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@11.0.6/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
	at java.base@11.0.6/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"globbing pool-0" Id=364 WAITING on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@543449e2 (daemon)
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@543449e2
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"globbing pool-0" Id=374 WAITING on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@227266f3 (daemon)
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@227266f3
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"globbing pool-0" Id=398 WAITING on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@684045fc (daemon)
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on com.google.devtools.build.lib.concurrent.NamedForkJoinPool@684045fc
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"SIGTERM handler" Id=1384 RUNNABLE (daemon)
	at java.management@11.0.6/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@11.0.6/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:502)
	at java.management@11.0.6/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:490)
	at app//com.google.testing.junit.runner.internal.StackTraces.printAll(StackTraces.java:43)
	at app//com.google.testing.junit.runner.internal.junit4.JUnit4TestStackTraceListener$WriteStackTraceSignalHandler.handle(JUnit4TestStackTraceListener.java:52)
	at app//com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:62)
	at app//com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:65)
	at jdk.unsupported@11.0.6/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base@11.0.6/jdk.internal.misc.Signal$1.run(Signal.java:220)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)


Done full thread dump.
```

**Comment by benjaminp** [comment]
I haven't noticed any more timeouts since 812cc595b6ee9df867d9111bdf001fd3e72fcb45. Thanks!
