### ISSUE TITLE
--notrack_incremental_state crashes on some repos

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#10912]
### Description of the problem / feature request:

On our private monorepo, we get the following crash when using `--notrack_incremental_state` (with or without `--nokeep_state_after_build`):

```
$ bazel --output_base=$(mktemp -d) --bazelrc=/dev/null test --notrack_incremental_state --nokeep_state_after_build -- //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 12181eb9-1387-4dfb-b351-0e712c8cf52a
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=1390763634, value=directory, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor.run(InvalidatingNodeVisitor.java:135)
        at com.google.devtools.build.skyframe.EagerInvalidator.invalidate(EagerInvalidator.java:104)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.performInvalidation(InMemoryMemoizingEvaluator.java:282)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:179)
        at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:474)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:358)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:258)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:609)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=1390763634, value=directory, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertKeepDeps(InMemoryNodeEntry.java:485)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.markDirty(InMemoryNodeEntry.java:496)
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor$1.run(InvalidatingNodeVisitor.java:478)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        ... 3 more
java.lang.IllegalStateException: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=1390763634, value=directory, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor.run(InvalidatingNodeVisitor.java:135)
        at com.google.devtools.build.skyframe.EagerInvalidator.invalidate(EagerInvalidator.java:104)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.performInvalidation(InMemoryMemoizingEvaluator.java:282)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:179)
        at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:474)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:358)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:258)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:609)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=1390763634, value=directory, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertKeepDeps(InMemoryNodeEntry.java:485)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.markDirty(InMemoryNodeEntry.java:496)
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor$1.run(InvalidatingNodeVisitor.java:478)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        ... 3 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have not been able to reproduce this bug on a public repo. I will be happy to dig any specific information out, or try creating a reproducible example with guidance.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 2.2.0

###  Have you found anything relevant by searching the web?

A search on the internet does not yield any results for the `EdgelessInMemoryNodeEntry` or a bazel error for "Not keeping deps"

**Comment by siddharthab** [comment]
Thanks! I can try running on smaller sections of the repo.

**Comment by vpanta** [comment]
We just hit this when adding a `managed_directories` entry to our WORKSPACE (for `@npm`/`node_modules` with `rules_nodejs`). For some reason, adding that causes a similar error for us when building (Bazel 3.1.0)

```
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=114401793, value=RegularFileStateValue{digest=null, size=5308, contentsProxy=ctime of 1618438017350 and nodeId of 11919313}, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor.run(InvalidatingNodeVisitor.java:135)
	at com.google.devtools.build.skyframe.EagerInvalidator.invalidate(EagerInvalidator.java:104)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.performInvalidation(InMemoryMemoizingEvaluator.java:282)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:179)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:466)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:350)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:256)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:611)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:663)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=114401793, value=RegularFileStateValue{digest=null, size=5308, contentsProxy=ctime of 1618438017350 and nodeId of 11919313}, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertKeepDeps(InMemoryNodeEntry.java:485)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.markDirty(InMemoryNodeEntry.java:496)
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor$1.run(InvalidatingNodeVisitor.java:478)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	... 3 more
java.lang.IllegalStateException: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=114401793, value=RegularFileStateValue{digest=null, size=5308, contentsProxy=ctime of 1618438017350 and nodeId of 11919313}, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor.run(InvalidatingNodeVisitor.java:135)
	at com.google.devtools.build.skyframe.EagerInvalidator.invalidate(EagerInvalidator.java:104)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.performInvalidation(InMemoryMemoizingEvaluator.java:282)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:179)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:466)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:350)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:256)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:611)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:663)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=114401793, value=RegularFileStateValue{digest=null, size=5308, contentsProxy=ctime of 1618438017350 and nodeId of 11919313}, lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertKeepDeps(InMemoryNodeEntry.java:485)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.markDirty(InMemoryNodeEntry.java:496)
	at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor$1.run(InvalidatingNodeVisitor.java:478)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	... 3 more
```

I verified removing `--notrack_incremental_state` from our `.bazelrc` in this case allows it to build normally.

**Comment by janakdr** [comment]
Thanks for the report, @vpanta ! Is there a minimal repro that you can share?

**Comment by vpanta** [comment]
So far I have not been able to get minimal repro unfortunately. I don't know if it's being caused by a specific NPM package we have installed or what.

However we have since updated to Bazel 4.0.0 so the error being reported now is:

(Note: `${WORKSPACE_DIR}` is actually the path to the Bazel workspace directory I'm running this from)
```
$ bazel build //packages/... --notrack_incremental_state --nokeep_state_after_build
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 58a26c0b-06b4-41b5-b752-021d4b03d48d
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: java.lang.IllegalStateException: Crash caused by FILE:[${WORKSPACE_DIR}]/[]
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor.run(InvalidatingNodeVisitor.java:135)
        at com.google.devtools.build.skyframe.EagerInvalidator.invalidate(EagerInvalidator.java:104)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.performInvalidation(InMemoryMemoizingEvaluator.java:278)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:175)
        at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation(SequencedSkyframeExecutor.java:496)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:377)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:266)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:674)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:539)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Crash caused by FILE:[${WORKSPACE_DIR}]/[]
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor.lambda$visit$0(InvalidatingNodeVisitor.java:483)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        ... 3 more
Caused by: java.lang.IllegalStateException: Not keeping deps: EdgelessInMemoryNodeEntry{identity=1298311046, value=non-symlink (path=[${WORKSPACE_DIR}]/[], state=directory), lastChangedVersion=IntVersion: 0, lastEvaluatedVersion=IntVersion: 0, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=null, singleReverseDep=true, dataToConsolidate=null}, dirtyBuildingState=null}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertKeepDeps(InMemoryNodeEntry.java:486)
        at com.google.devtools.build.skyframe.InMemoryNodeEntry.markDirty(InMemoryNodeEntry.java:510)
        at com.google.devtools.build.skyframe.InvalidatingNodeVisitor$DirtyingNodeVisitor.lambda$visit$0(InvalidatingNodeVisitor.java:474)
        ... 4 more
```

**Comment by ronisec** [comment]
This is impacting our monorepo as well, not sure if it's related, but we are also using a `managed_directories` entry in our WORKSPACE (for `@npm/node_modules` with `rules_nodejs`)

**Comment by janakdr** [comment]
Passing over to Justin.
