### ISSUE TITLE
bazel run command fails on Windows : process-wrapper not found in embedded tools

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1100]
When I tried to run an example cc_binary target with bazel run command, it failed like this:

```
$ bazel --batch run examples/cpp:hello-world
INFO: Found 1 target...
Target //examples/cpp:hello-world up-to-date:
  C:/tools/msys64/var/tmp/_bazel_pcloudy/0179298ce5ca273cde050e2854e34ba5/bazel/bazel-out/local_windows_msys64-fastbuild/bin/examples/cpp/hello-world.exe
INFO: Elapsed time: 9.688s, Critical Path: 3.27s
java.lang.NullPointerException: process-wrapper not found in embedded tools
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:349)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:250)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:380)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:983)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:791)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

But directly run `C:/tools/msys64/var/tmp/_bazel_pcloudy/0179298ce5ca273cde050e2854e34ba5/bazel/bazel-out/local_windows_msys64-fastbuild/bin/examples/cpp/hello-world.exe` succeed.

**Comment by tfarina** [comment]
@meteorcloudy could you make sure you have process-wrapper in the "install" equivalent directory for Windows?

For example, mine, on Linux is located at:
~/.cache/bazel/_bazel_tfarina/install/04eeb18597e2e9843fc4c6fe846b026d/_embedded_binaries/process-wrapper

Maybe it should be there in C:/tools/msys64/var/tmp/_bazel_pcloudy/install/sha1/_embedded_binaries/, but for some reason it wasn't extracted there?

Could you confirm this?
