### ISSUE TITLE
Crash if cc_toolchain is given to --crosstool_top instead of cc_toolchain_suite

### ISSUE THREAD

**Issue by erenon** [bazelbuild/bazel#11011]
### Description of the problem / feature request:

If a `cc_toolchain` is given to `--crosstool_top` instead of `cc_toolchain_suite`, Bazel crashes:

```
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider cannot be cast to class com.google.devtools.build.lib.rules.cpp.CcToolchainProvider (com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider and com.google.devtools.build.lib.rules.cpp.CcToolchainProvider are in unnamed module of loader 'app')
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainFromCrosstoolTop(CppHelper.java:354)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:326)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:318)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:307)
        at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainUsingDefaultCcToolchainAttribute(CppHelper.java:231)
        at com.google.devtools.build.lib.rules.cpp.CcCommon.<init>(CcCommon.java:168)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:144)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:95)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:483)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:832)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cc_toolchain_config(name = "mygcc_toolchain_config")

cc_toolchain(
  name = 'mygcc',
  all_files = ':empty', # must be superset of other *_files
  compiler_files = ':empty',
  strip_files = ':empty',
  objcopy_files = ':empty',
  linker_files = ':empty',
  dwp_files = ':empty',
  toolchain_config = ':mygcc_toolchain_config',
)
```
```
$ bazel build //app:app -s --crosstool_top=//toolchain:toolchain
```

### What operating system are you running Bazel on?

```
$ uname -s -r -v
Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020
```

### What's the output of `bazel info release`?

```
$ bazel info release
release 2.2.0
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

The fix is trivial, the input is obviously incorrect - but I don't know what's the stance of the Bazel team on crashes. I'd prefer to get an error message instead, that explains what went wrong. It was difficult to me to figure it out otherwise. I suspect the fix is not too difficult, getToolchainFromCrosstoolTop should make sure the cast to CcToolchainProvider is possible.

**Comment by gregestren** [comment]
@katre not sure if we or C++ rules folks should look at this. Can you triage?
