### ISSUE TITLE
Exception when generating gen_class

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1104]
```
$ /Users/dmarting/git/bazel/output/bazel --watchfs build --package_path %workspace%:/Users/dmarting/Documents/workspace/com.google.devtools.ebazel/resources --experimental_interleave_loading_and_analysis --strategy=Javac=worker --aspects=tools/must/be/unique/ebazel.bzl%ebazel_aspect --output_groups=ide-resolve src/test/java/... src/main/java/...
INFO: Found 143 targets...
ERROR: /Users/dmarting/git/bazel/src/main/java/com/google/devtools/build/lib/BUILD:347:1: Building genclass jar src/main/java/com/google/devtools/build/lib/libsyntax-gen.jar failed: java failed: error executing command external/local_jdk/bin/java -Xverify:none -client -Xmx64m -jar external/bazel_tools/tools/jdk/GenClass_deploy.jar --manifest_proto ... (remaining 7 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.nio.file.FileAlreadyExistsException: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/_javac/syntax/libsyntax-gen_temp/com/google/devtools/build/lib/syntax/AutoValue_FunctionSignature.class
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at com.google.devtools.build.buildjar.genclass.GenClass.extractGeneratedClasses(GenClass.java:107)
	at com.google.devtools.build.buildjar.genclass.GenClass.main(GenClass.java:42)
INFO: Elapsed time: 0.960s, Critical Path: 0.43s
```

/cc @dslomov @ahumesky 

I can share the aspect implementation if you want but I believe it has nothing to do with it. it's a rewrite of the intellij_info.bzl to be simpler and output in json instead of proto.

**Comment by ahumesky** [comment]
The javadoc for extractGeneratedClasses() says:
Unzip all the class files that correspond to annotation processor-
generated sources into the temporary directory.

maybe that temp directory isn't getting cleared or something? (bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/_javac/syntax/libsyntax-gen_temp)

**Comment by damienmg** [comment]
Ok updating to bazel head did fix the issue, closing.

**Comment by damienmg** [comment]
This is happening again, even outside of Eclipse.

**Comment by damienmg** [comment]
Oh gosh I think I understand what is happening: it creating output in the outputbase that are not needed. On OSX it runs outside of any sandbox. Re-running it several time on OS X should be a correct repro.

**Comment by damienmg** [comment]
with `-s` I found the genclass invcation and running it outside fails.

```
$ (cd /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004/bazel && \
>   exec env - \
>   external/local_jdk/bin/java -Xverify:none -client -Xmx64m -jar external/bazel_tools/tools/jdk/GenClass_deploy.jar --manifest_proto bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/analysis_test.jar_manifest_proto --class_jar bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/analysis_test.jar --output_jar bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/analysis_test-gen.jar --temp_dir bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/_javac/analysis_test/analysis_test-gen_temp)
Exception in thread "main" java.nio.file.FileAlreadyExistsException: bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/_javac/analysis_test/analysis_test-gen_temp/com/google/devtools/build/lib/analysis/AutoValue_AnalysisUtilsTest_AutoValuedClass.class
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at com.google.devtools.build.buildjar.genclass.GenClass.extractGeneratedClasses(GenClass.java:107)
	at com.google.devtools.build.buildjar.genclass.GenClass.main(GenClass.java:42)
```

**Comment by damienmg** [comment]
Of course the command line says where the exception comes from:
`--temp_dir bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/lib/_javac/analysis_test/analysis_test-gen_temp`

temp_dir should not be in the output root.

Assigning to @ahumesky for further triage.

**Comment by damienmg** [comment]
Ok sorry I spoke too fast, it might be correct to have `temp_dir` in the output root (maybe rename it in that case), but genclass should be able to overwrite files (maybe clean the dir before running)

**Comment by damienmg** [comment]
It's blocking me so I'll fix it.
