### ISSUE TITLE
Hard crash with --override_repository and non existent directory

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#11071]
### Description of the problem / feature request:

Bazel hard crashes during build when an invalid --override_repository is specified. I expect bazel to never hard crash and instead handle error conditions gracefully and print error messages relating to user level concepts not internal details (e.g. stack traces).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Code in usable form: https://gist.github.com/endobson/15e514982870cb2fb6f060b9c557c73b
Inline WORKSPACE file for issue readability:

```bzl
workspace(name = "yaspl")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "minimal_racket",
  sha256 = "14f39796b51bdcf89dd765573dfb8f7f671fbbd4c3734a5329edab9f03911494",
  strip_prefix = "minimal-racket-e0f352a7d7b5b5fc9dedb708a2d5c8aedc6d6eb0",
  urls = ["https://github.com/endobson/minimal-racket/archive/e0f352a7d7b5b5fc9dedb708a2d5c8aedc6d6eb0.tar.gz"]
)
```
Command: 

```shell
$ bazel build @minimal_racket//... --override_repository=minimal_racket=/does_not_exist
INFO: Invocation ID: c95b833b-9089-414c-93ab-d12f7d24e259
Loading: 
Loading: 0 packages loaded
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: The repository's path is "minimal_racket" (absolute: "/does_not_exist") but this directory does not exist.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getTargetPatternPhaseValue(SkyframeExecutor.java:2902)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatternsWithFilters(SkyframeExecutor.java:2873)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:144)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:288)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:94)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 0.132s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: The repository's path is "minimal_racket" (absolute: "/does_not_exist") but this directory does not exist.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getTargetPatternPhaseValue(SkyframeExecutor.java:2902)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatternsWithFilters(SkyframeExecutor.java:2873)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:144)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:288)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:94)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: The repository's path is "minimal_racket" (absolute: "/does_not_exist") but this directory does not exist.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getTargetPatternPhaseValue(SkyframeExecutor.java:2902)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatternsWithFilters(SkyframeExecutor.java:2873)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:144)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:288)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:94)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### What operating system are you running Bazel on?

macOS 10.15.2

### What's the output of `bazel info release`?
release 2.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

This is not relevant. This question should be qualified with only if this is bazel was a git version.

###  Have you found anything relevant by searching the web?

No.

**Comment by mai12** [comment]
@endobson Were you using the [no]keep_going `-k` option in your build? I could only reproduce this bug with this option set.

**Comment by endobson** [comment]
Almost surely. It is in my blazerc.

**Comment by mai12** [comment]
In release 2.2.0, if the `-k` option is set, this internal error is thrown if a problem occurred during loading target patterns.

I think this behavior has changed in the latest release 3.4.1. In this version, whether the -k option is used or not, the internal error is not thrown. Only an error message is given like this:
```
ERROR: The repository's path is "minimal_racket" (absolute: "/does_not_exist") but this directory does not exist.
```
