### ISSUE TITLE
//src/main/java/com/google/devtools/build/lib:gen_command-line-reference is broken

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#11095]
Bisected to 09924273efc7050a2e342cd89b823a619ca073f8 (cc @anakanemison)

```
$ bazel build //src/main/java/com/google/devtools/build/lib:gen_command-line-reference --verbose_failures
...

INFO: Analyzed target //src/main/java/com/google/devtools/build/lib:gen_command-line-reference (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/jingwen/bazels/github/src/main/java/com/google/devtools/build/lib/BUILD:756:1: Executing genrule //src/main/java/com/google/devtools/build/lib:gen_command-line-reference failed (Exit 37): bash failed: error executing command

...

  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cat site/command-line-reference-prefix.html > bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html && TMP=`mktemp -d /tmp/tmp.XXXXXXXXXX` && bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer --jvm_flag=-Dio.bazel.EnableJni=0 --batch --install_base=${TMP} --output_base=${TMP}/output/ --output_user_root=${TMP} help everything-as-html >> bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html 2>/dev/null && cat site/command-line-reference-suffix.html >> bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html')
Execution platform: //:default_host_platform

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cat site/command-line-reference-prefix.html > bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html && TMP=`mktemp -d /tmp/tmp.XXXXXXXXXX` && bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer --jvm_flag=-Dio.bazel.EnableJni=0 --batch --install_base=${TMP} --output_base=${TMP}/output/ --output_user_root=${TMP} help everything-as-html >> bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html 2>/dev/null && cat site/command-line-reference-suffix.html >> bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/command-line-reference.html')
Execution platform: //:default_host_platform

Use --sandbox_debug to see verbose messages from the sandbox
Target //src/main/java/com/google/devtools/build/lib:gen_command-line-reference failed to build
INFO: Elapsed time: 1.082s, Critical Path: 0.88s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Same error is happening on the Cloud Build job for docs.bazel.build. 

https://pantheon.corp.google.com/cloud-build/builds/90b4bb72-5e19-4379-948e-79267dec30fb?project=bazel-public

**Comment by jin** [comment]
cc @gregestren

**Comment by jin** [comment]
Figured out the problem:

```
$ TMP=`mktemp -d /tmp/tmp.XXXXXXXXXX` && bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer --jvm_flag=-Dio.bazel.EnableJni=0 --batch --install_base=${TMP} --output_base=${TMP}/output/ --output_user_root=${TMP} help everything-as-html
Apr 08, 2020 3:03:24 PM com.google.devtools.build.lib.analysis.BlazeVersionInfo logVersionInfo
WARNING: Bazel release version information not available
Apr 08, 2020 3:03:24 PM com.google.devtools.build.lib.runtime.BlazeRuntime batchMain
INFO: Running Bazel in batch mode with startup args [--batch, --install_base=/tmp/tmp.4SOLYWMRux, --output_base=/tmp/tmp.4SOLYWMRux/output/, --output_user_root=/tmp/tmp.4SOLYWMRux]
Apr 08, 2020 3:03:24 PM com.google.devtools.build.lib.bugreport.BugReport logCrash
SEVERE: Crash: java.lang.IllegalArgumentException: Bad --failure_detail_out option specified: 'null' java.lang.IllegalArgumentException: Bad --failure_detail_out option specified: 'null'
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:993)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:814)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:79)

Apr 08, 2020 3:03:24 PM com.google.devtools.build.lib.bugreport.BugReport sendBugReport
INFO: (Not a released binary; not logged.)
java.lang.IllegalArgumentException: Bad --failure_detail_out option specified: 'null'
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:993)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:814)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:79)
Apr 08, 2020 3:03:24 PM com.google.devtools.build.lib.bugreport.BugReport printThrowableTo
SEVERE: <unknown> crashed
java.lang.IllegalArgumentException: Bad --failure_detail_out option specified: 'null'
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:993)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:814)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:79)

ERROR: <unknown> crash in async thread:
java.lang.IllegalArgumentException: Bad --failure_detail_out option specified: 'null'
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:993)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:814)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:79)
```

We should consider adding the site build target (https://github.com/bazelbuild/bazel/pull/11093), or at least docgen targets, to presubmit.

**Comment by michajlo** [comment]
Why does this call the server jar directly?

**Comment by jin** [comment]
It uses the output of `bazel help everything-as-html` to generate the command line reference.

**Comment by michajlo** [comment]
Why doesn't it call the launcher?

**Comment by jin** [comment]
In https://bazel-review.googlesource.com/c/bazel/+/3880/2/src/main/java/com/google/devtools/build/lib/BUILD#982, @damienmg asked the same question, and @ulfjack said:

> Tried that, didn't work. By default, there's no JDK in the sandbox, and JAVA_HOME isn't set.

> Also, the packaging step is fairly expensive, compared to 'just' building the Java binary, so it seemed ok to go with this.

**Comment by jin** [comment]
Interesting, I filed a breakage on this before too: https://github.com/bazelbuild/bazel/issues/4730

https://github.com/bazelbuild/bazel/issues/4730#issuecomment-369150294 laments that we don't have presubmits for this, which I'm adding in https://github.com/bazelbuild/bazel/pull/11096

**Comment by michajlo** [comment]
I feel like that can be revisited, that was from 2016. Also, it seems like getting it to use the launcher would reduce future brittleness.

**Comment by jin** [comment]
I can definitely do that, but for now, the site generation is broken/blocked, so the fix is rather high priority.

**Comment by michajlo** [comment]
Opened https://github.com/bazelbuild/bazel/issues/11102
