### ISSUE TITLE
NPE in aspect-based build with bazel 3.0.0.

### ISSUE THREAD

**Issue by dws-uber** [bazelbuild/bazel#11114]
### Description of the problem / feature request:

NPE in aspect-based build with bazel 3.0.0.

### Feature requests: what underlyng problem are you trying to solve with this feature?

I would like for bazel to not fail due to an NPE.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Our build system is somewhat large and it will take me some time to come up with a small reproducer. So far, the problem has shown up in two out of two attempts to do this particular build.  Pending a small reproducer, I will be happy to try out speculative fixes if you like.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.0.0

###  Have you found anything relevant by searching the web?

An NPE in bazel is always a bug, so I didn't look elsewhere.

### Any other information, logs, or outputs that you want to share?

```
# ./bazel build --config=compile_commands --config=ci --config=remote ...
(22:30:12) INFO: Invocation ID: a26c261c-e649-4a0d-964f-766433cd793b
(22:30:12) INFO: Current date is 2020-04-10
(22:30:12) Loading: 
(22:30:12) Loading: 0 packages loaded
(22:30:13) Loading: 0 packages loaded
(22:30:14) Loading: 425 packages loaded
(22:30:15) Loading: 1167 packages loaded
(22:30:16) Loading: 2026 packages loaded
(22:30:17) Analyzing: 9754 targets (2232 packages loaded)
(22:30:17) Analyzing: 9754 targets (2232 packages loaded, 0 targets configured)
(22:30:18) Analyzing: 9754 targets (2255 packages loaded, 6007 targets configured)
(22:30:19) Analyzing: 9754 targets (2284 packages loaded, 7192 targets configured)
(22:30:21) Analyzing: 9754 targets (2296 packages loaded, 15391 targets configured)
(22:30:22) Analyzing: 9754 targets (2339 packages loaded, 15802 targets configured)
(22:30:24) Analyzing: 9754 targets (2359 packages loaded, 19958 targets configured)
(22:30:25) Analyzing: 9754 targets (2415 packages loaded, 32995 targets configured)
(22:30:27) Analyzing: 9754 targets (2427 packages loaded, 38947 targets configured)
(22:30:30) Analyzing: 9754 targets (2472 packages loaded, 44589 targets configured)
(22:30:33) Analyzing: 9754 targets (2479 packages loaded, 45031 targets configured)
(22:30:38) Analyzing: 9754 targets (2479 packages loaded, 45031 targets configured)
(22:30:42) Analyzing: 9754 targets (2568 packages loaded, 48591 targets configured)
(22:30:47) Analyzing: 9754 targets (2572 packages loaded, 51633 targets configured)
(22:30:52) Analyzing: 9754 targets (2576 packages loaded, 51742 targets configured)
(22:30:59) Analyzing: 9754 targets (2615 packages loaded, 56407 targets configured)
(22:31:09) Analyzing: 9754 targets (2728 packages loaded, 74618 targets configured)
(22:31:20) Analyzing: 9754 targets (2729 packages loaded, 75169 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#//tools/compile_commands:aspects.bzl%compilation_database_aspect BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] //atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false {}' (requested by nodes 'SkylarkAspectLoadingKey{targetLabel=//atg/calibration/base:base, aspectConfigurationKey=BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed], baseConfiguredTargetKey=//atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false, skylarkFileLabel=//tools/compile_commands:aspects.bzl, skylarkValueName=compilation_database_aspect}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.cpp.CcModule.configureFeatures(CcModule.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:589)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:424)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:81)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:247)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:237)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:54)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:38)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:116)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:335)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:91)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:649)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:650)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:479)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more

(22:31:26) INFO: Elapsed time: 74.677s
(22:31:26) INFO: 0 processes.
(22:31:26) FAILED: Build did NOT complete successfully (2821 packages loaded, 89301 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#//tools/compile_commands:aspects.bzl%compilation_database_aspect BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] //atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false {}' (requested by nodes 'SkylarkAspectLoadingKey{targetLabel=//atg/calibration/base:base, aspectConfigurationKey=BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed], baseConfiguredTargetKey=//atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false, skylarkFileLabel=//tools/compile_commands:aspects.bzl, skylarkValueName=compilation_database_aspect}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.cpp.CcModule.configureFeatures(CcModule.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:589)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:424)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:81)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:247)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:237)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:54)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:38)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:116)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:335)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:91)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:649)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:650)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:479)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#//tools/compile_commands:aspects.bzl%compilation_database_aspect BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] //atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false {}' (requested by nodes 'SkylarkAspectLoadingKey{targetLabel=//atg/calibration/base:base, aspectConfigurationKey=BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed], baseConfiguredTargetKey=//atg/calibration/base:base BuildConfigurationValue.Key[678b566578a497005e6dcf4f466cc46da73fbb2d69373d4ce7f0163bbfc2c7ed] false, skylarkFileLabel=//tools/compile_commands:aspects.bzl, skylarkValueName=compilation_database_aspect}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.cpp.CcModule.configureFeatures(CcModule.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:589)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:424)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:81)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:247)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:237)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:54)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:38)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:116)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:360)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:335)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:91)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:649)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:650)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:479)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
(22:31:27) FAILED: Build did NOT complete successfully (2821 packages loaded, 89301 targets configured)
(22:31:27) INFO: Build Event Protocol files produced successfully.
(22:31:27) FAILED: Build did NOT complete successfully (2821 packages loaded, 89301 targets configured)
```

**Comment by dws-uber** [comment]
@werkt

**Comment by dws-uber** [comment]
@laurentlb Per instructions in https://github.com/bazelbuild/bazel/issues/11076 I am unable to apply a "Release blocker" label, but I would invite you to do so.

**Comment by werkt** [comment]
That method, configureFeatures, is an unholy mess, and it looks like the check in question was added without regard for the `@Nullable ruleContext`. PR #11115 fixes this.

**Comment by laurentlb** [comment]
@lberki @oquenchil 
Can you take a look?
Also, let me know if you think it's a release blocker or not.

**Comment by oquenchil** [comment]
Yes, it's a release blocker. I can import werkt's change. Can it be cherrypicked?

**Comment by laurentlb** [comment]
Yes, let me know the commit hash once it's submitted.

**Comment by laurentlb** [comment]
The fix was cherrypicked on Friday.
If you try the release candidate, let me know if there's any other blocker (we might do the release tomorrow, but can delay it if it helps).
