### ISSUE TITLE
Setting a java_runtime in your own repo, based on an external repository fails on the invocation of "platformclasspath"

### ISSUE THREAD

**Issue by Faqa** [bazelbuild/bazel#11130]
### Description of the problem / feature request:

If you try to point the `javabase` flag at a `java_runtime` target in your own repo, where that target relies on an external repository (say you download the JDK in WORKSPACE, but create the `java_runtime` target in your repository, pointing at the files in the external repo), any compilation will terminate with an error in the vein of:

```
Exception in thread "main" java.lang.IllegalArgumentException: <PATH_TO_BUILD_FILE>
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1853)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
```

If you simply create the `java_runtime` target inside the repository where you download the JDK, and point the `javabase` flag at that, everything works fine. This is obviously a workaround for the issue, but when you are trying, for example, to set the JDK you're using based on your build target via `select` statements, it's annoying to have to duplicate the `java_runtime` target in each JDK repository.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[repro.tar.gz](https://github.com/bazelbuild/bazel/files/4478281/repro.tar.gz)

`bazel build //:HelloWorld` results in an error.

`bazel build --config=aliased //:HelloWorld` works.

The difference is whether the `java_runtime` target is used or the `alias` target.

### What operating system are you running Bazel on?

OSX 

### What's the output of `bazel info release`?

release 2.0.0

**Comment by comius** [comment]
Problem is that `java_runtime` reconstructs `java_home` attribute based on the current repo, here `src/main/java/com/google/devtools/build/lib/rules/java/JavaRuntime.java:52`. Defining it in one repo and pointing to another one does not work. `java_home` is used in bootclasspath.

Possible solution is to reconstruct `java_home` based on `srcs` attribute.
