### ISSUE TITLE
NullPointerException fetching rules

### ISSUE THREAD

**Issue by davidvancleve** [bazelbuild/bazel#11133]
Title should read: NullPointerException fetching io_bazel_rules_docker

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- clone github.com/kythe/kythe on debian-like linux
- from the main kythe directory, run `bazel build kythe/go/serving/tools/kythefs`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 3.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/kythe/kythe
4b86d4f4b5ac7fd282da0a0e7f5d19405f83459b
4b86d4f4b5ac7fd282da0a0e7f5d19405f83459b

###  Have you found anything relevant by searching the web?

Nope

### Any other information, logs, or outputs that you want to share?

Errors out with 
```
FAILED: Build did NOT complete successfully (9 packages loaded, 6 targets configured)
    currently loading: @local_config_sh//
    Fetching @go_sdk; fetching
    Fetching @local_config_cc_toolchains; fetching
    Fetching @local_config_lexyacc; fetching
    Fetching @io_bazel_rules_docker; Cloning c4bc29fd0e07429a874669197613f0606459bc7e of https://github.com/bazelbuild/rules_docker.git
Internal error thrown during build. Printing stack trace: java.lang.NullPointerException: //kythe/go/serving/tools/kythefs:kythefs BuildConfigurationValue.Key[cfdb5a1c1c89d62f0c9ddfd9f5664c118e65f55425d93acf3e2511bbdabceac9] false
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:121)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:773)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:616)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:454)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:404)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:213)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:290)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:95)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException: //kythe/go/serving/tools/kythefs:kythefs BuildConfigurationValue.Key[cfdb5a1c1c89d62f0c9ddfd9f5664c118e65f55425d93acf3e2511bbdabceac9] false
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:121)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:773)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:616)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:454)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:404)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:213)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:290)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:95)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
FAILED: Build did NOT complete successfully (9 packages loaded, 6 targets configured)
    currently loading: @local_config_sh//
    Fetching @go_sdk; fetching
    Fetching @local_config_cc_toolchains; fetching
    Fetching @local_config_lexyacc; fetching
    Fetching @io_bazel_rules_docker; Cloning c4bc29fd0e07429a874669197613f0606459bc7e of https://github.com/bazelbuild/rules_docker.git
```

**Comment by davidvancleve** [comment]
Can't repro.
