### ISSUE TITLE
starlark: fails to report error for string.replace(old, new, None)

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#11273]
According to the spec, the count argument to string.replace must be an int.

```
$ python2 -c "'banana'.replace('a', 'A', None)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: an integer is required

$ python3 -c "'banana'.replace('a', 'A', None)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object cannot be interpreted as an integer

$ starlark -c "'banana'.replace('a', 'A', None)" # go.starlark.net
Traceback (most recent call last):
  cmdline:1:17: in <toplevel>
  <builtin>: in replace
Error: replace: for parameter 3: got NoneType, want int

$ blaze run third_party/bazel/src/main/java/com/google/devtools/starlark/cmd/Starlark  -- -c "print('banana'.replace('a', 'A', None))"
bAnAnA
```

**Comment by brandjon** [comment]
This has been fixed.
