### ISSUE TITLE
Building with rules_python fails on 403 response.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [bazelbuild/bazel#11328]
### Description of the problem:

Building with `rules_python` causes failure on 403 response. As far as I can tell this is an issue with the hosting of [this release](https://github.com/bazelbuild/rules_python/releases/tag/0.0.1).

Code that caused the error:
```bazel
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
```

Log of the error:
```shell
INFO: Call stack for the definition of repository 'rules_python' which is a http_archive (rule definition at /github/home/.cache/bazel/_bazel_root/4584916dfcfb338dd37ec7118133b12a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /__w/iree/iree/WORKSPACE:35:1
 - /__w/iree/iree/WORKSPACE:35:1
WARNING: Download from https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz failed: class java.io.IOException GET returned 403 Forbidden
ERROR: An error occurred during the fetch of repository 'rules_python':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz] to /github/home/.cache/bazel/_bazel_root/4584916dfcfb338dd37ec7118133b12a/external/rules_python/rules_python-0.0.1.tar.gz: GET returned 403 Forbidden
ERROR: no such package '@rules_python//python': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz] to /github/home/.cache/bazel/_bazel_root/4584916dfcfb338dd37ec7118133b12a/external/rules_python/rules_python-0.0.1.tar.gz: GET returned 403 Forbidden
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: no such package '@rules_python//python': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz] to /github/home/.cache/bazel/_bazel_root/4584916dfcfb338dd37ec7118133b12a/external/rules_python/rules_python-0.0.1.tar.gz: GET returned 403 Forbidden
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getTargetPatternPhaseValue(SkyframeExecutor.java:2901)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatternsWithFilters(SkyframeExecutor.java:2872)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:142)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:270)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:130)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:108)
	at 
com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:543)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:205)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:601)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:652)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### What operating system are you running Bazel on?

Linux Ubuntu 18.04 in the `l.gcr.io/google/bazel:2.1.0` docker container.

**Comment by keith** [comment]
GitHub seems to be having an outage, https://www.githubstatus.com/ isn't updated yet

**Comment by phoenix-meadowlark** [comment]
It looks like it's back up again – thanks for the help.
