### ISSUE TITLE
Systhrow error during Bazel ppc64le build on Power8 machine

### ISSUE THREAD

**Issue by sheltongeosx** [bazelbuild/bazel#11407]
System: Red Hat Enterprise Linux Server 7.4 (Maipo)
platform: IBM power8, ppc64le
java version:

     java version "1.8.0_251"
     Java(TM) SE Runtime Environment (build 8.0.6.10 - pxl6480sr6fp10-20200408_01(SR6 FP10))
     IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20200402_443261 (JIT enabled, AOT enabled)
Bazel source distributions:   bazel-3.1.0,  bazel-3.0.0,  bazel-2.2.0

### Description of the problem / feature request:
 Running ./compile.sh produces the following errors:

      .....
    JVMDUMP010I Snap dump written to /data/gpfs/Users/l0538797/apps/ppc64le/bazel/bazel- 
    2.2.0/Snap.20200515.092741.104677.0013.trc
    JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
    Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.newNode(HashMap.java:1761)
        at java.util.HashMap.putVal(HashMap.java:642)
        at java.util.HashMap.put(HashMap.java:623)
        at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:215)
        at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:141)
        at java.util.ResourceBundle.getObject(ResourceBundle.java:452)
        at java.util.ResourceBundle.getString(ResourceBundle.java:418)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:202)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:153)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
        at com.sun.tools.javac.util.Log.localize(Log.java:696)
        at com.sun.tools.javac.util.Log.printLines(Log.java:509)
        at com.sun.tools.javac.main.Main.resourceMessage(Main.java:622)
        at com.sun.tools.javac.main.Main.compile(Main.java:555)
        at com.sun.tools.javac.main.Main.compile(Main.java:393)
        at com.sun.tools.javac.main.Main.compile(Main.java:382)
        at com.sun.tools.javac.main.Main.compile(Main.java:373)
        at com.sun.tools.javac.Main.compile(Main.java:68)
        at com.sun.tools.javac.Main.main(Main.java:54)

It happens to all three versions of code (3.1.0, 3.0.0 and 2.2.0). Please advice to resolve the issue. Thanks.

Best,
Shelton

**Comment by philwo** [comment]
Hi Shelton,

the error is here: `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`

You need to add more RAM to the machine and/or increase the Java heap of the invocation that fails (from the log it is not clear whether this is the `javac` invocation in compile.sh or something that Bazel runs).

Hope that helps.
