### ISSUE TITLE
Crash when attempting to instantiate a repository rule in BUILD file

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#11461]
This is illegal but we shouldn't crash.

cc @alandonovan because it's indicative of a conceptual problem in how we conflate (or differentiate) WORKSPACE- and BUILD-loaded .bzls.

```starlark
# BUILD
load("foo.bzl", "reporule")

reporule(
    name = "a",
)
```

```starlark
# foo.bzl
def _impl(repository_ctx):
    pass

reporule = repository_rule(
    implementation = _impl,
)
```

```sh
$ bazel build :a 
Starting local Bazel server and connecting to it...
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes ':a, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
	at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:429)
	at com.google.devtools.build.lib.packages.Package.access$3100(Package.java:81)
	at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1591)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:535)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 4 more

INFO: Elapsed time: 1.796s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes ':a, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
	at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:429)
	at com.google.devtools.build.lib.packages.Package.access$3100(Package.java:81)
	at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1591)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:535)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes ':a, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
	at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:429)
	at com.google.devtools.build.lib.packages.Package.access$3100(Package.java:81)
	at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1591)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:535)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
FAILED: Build did NOT complete successfully (1 packages loaded)

```

**Comment by TUMAAA** [comment]
I am facing this problem. From your description above I understand the thrown exception is the intended behavior. However, I am not understanding from the message what the problem is. I am importing rules from an external repository (python_rules) in the WORKSPACE file and then loading the rule pip3_import() in the build file. This works. As soon as I create the target based on the pip3_import rule I get this exception. Can you tell me what is the mistake in this?

**Comment by alandonovan** [comment]
The unhandled exception (a crash) is the bug. The desired behavior is that bazel prints an informative error: "you can't instantiate a repository_rule except from a WORKSPACE initialization thread". The fix is either to instantiate the rule from a WORKSPACE file instead of a BUILD file (or perhaps the intent was to declare the rule as an ordinary `rule` instead of `repository_rule`).

**Comment by crt-31** [comment]
This ticket should stay open. Adding a good error message (instead of unhandled exception) in this case would save lots of time and frustration.
