### ISSUE TITLE
StandaloneTestStrategy NPE/RuntimeException on shutdown after abort handled.

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#11468]
Encountered the following runtime exception seemingly *after* a build has begun handling an abort signal. Despite shutting down, this should not be printing noisy NPEs that might distract from real discovery of a build failure reason.

Version was 3.1.0, running on linux. Abort message is uninteresting, but was definitely printed *before* this NPE trace.  I've included it at the end of the issue for reference.

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=<target> BuildConfigurationValue.Key[dda694ec6988aadc6904a86cb5a2ead6a2c7e63ef4697d3e33bf2f01b333cb51] false, actionIndex=8}' (requested by nodes 'TestCompletionKey{configuredTargetKey=<target> BuildConfigurationValue.Key[dda694ec6988aadc6904a86cb5a2ead6a2c7e63ef4697d3e33bf2f01b333cb51] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@500abbf6, exclusiveTesting=false}')
  at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
  at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  at com.google.devtools.build.lib.exec.StandaloneTestStrategy.processTestAttempt(StandaloneTestStrategy.java:252)
  at com.google.devtools.build.lib.exec.StandaloneTestStrategy.finalizeTest(StandaloneTestStrategy.java:205)
  at com.google.devtools.build.lib.exec.StandaloneTestStrategy.access$300(StandaloneTestStrategy.java:68)
  at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.finalizeTest(StandaloneTestStrategy.java:461)
  at com.google.devtools.build.lib.analysis.test.TestRunnerAction$RunAttemptsContinuation.process(TestRunnerAction.java:1163)
  at com.google.devtools.build.lib.analysis.test.TestRunnerAction$RunAttemptsContinuation.execute(TestRunnerAction.java:1105)
  at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:862)
  at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:851)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:961)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1109)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
  at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
  at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
  at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
  ... 4 more
```

It looks as though StandaloneTestStrategy::processTestAttempt needs to be made aware of the shutdown, since it is attempting to access a null `renamedTestLog` after getting out of this loop without a match:

```
    // Recover the test log path, which may have been renamed, and add it to the data builder.
    Path renamedTestLog = null;
    for (Pair<String, Path> pair : testOutputs) {
      if (TestFileNameConstants.TEST_LOG.equals(pair.getFirst())) {
        renamedTestLog = pair.getSecond();
      }
    }
```

Abort included for reference:

```
com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15
  at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:84)
  at com.google.devtools.build.lib.shell.Command.execute(Command.java:249)
  at com.google.devtools.build.lib.exec.SymlinkTreeHelper.createSymlinksUsingCommand(SymlinkTreeHelper.java:160)
  at com.google.devtools.build.lib.exec.SymlinkTreeStrategy.createSymlinks(SymlinkTreeStrategy.java:120)
  at com.google.devtools.build.lib.analysis.actions.SymlinkTreeAction.execute(SymlinkTreeAction.java:194)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:961)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1109)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
  at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
  at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
  at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
  at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by haxorz** [comment]
Thanks for the report. Was this not fixed by your https://github.com/bazelbuild/bazel/pull/11494?
