### ISSUE TITLE
Experimental persistent test runner throws NPEs during test action creation

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#11519]
### Description of the problem / feature request:

Using the experimental persistent test runner via `--test_strategy=local --strategy=TestRunner=worker --experimental_persistent_test_runner` results in null pointer exceptions in the test infrastructure, during sh tests. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In our case, we have a sh_test which is a build test, which takes deps and just runs a no-op shell script. When we run with the persistent worker, we get errors during createTestAction:

```
[2020-05-29 00:17:13] Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//some/package:build_test BuildConfigurationValue.Key[7d4ce192e5215a83aa74a7a7cd93945e19e5a13e743c096f71a6bdd8a3c44352] false' (requested by nodes )
[2020-05-29 00:17:13] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[2020-05-29 00:17:13] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[2020-05-29 00:17:13] Caused by: java.lang.NullPointerException
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.createTestAction(TestActionBuilder.java:405)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.build(TestActionBuilder.java:101)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.initializeTestProvider(RuleConfiguredTargetBuilder.java:431)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:156)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:101)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:43)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
[2020-05-29 00:17:13] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
[2020-05-29 00:17:13] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
[2020-05-29 00:17:13] 	... 7 more
```

### What operating system are you running Bazel on?

Mac OS X

### What's the output of `bazel info release`?

3.1.0

###  Have you found anything relevant by searching the web?

Nope.

**Comment by cgruber** [comment]
It seems to happen with java/kotlin tests as well in our repo. 

```
FAILED: Build did NOT complete successfully (161 packages loaded, 803 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tools/migration/javatests/com/squareup/tools/migration/bazel/core:UtilsTest BuildConfigurationValue.Key[1161f44308ef9f9b52fbb9faa62606aa2a1a4187cf705c148fdbb483fa43942b] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.createTestAction(TestActionBuilder.java:405)
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.build(TestActionBuilder.java:101)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.initializeTestProvider(RuleConfiguredTargetBuilder.java:431)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:156)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:234)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:156)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:468)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tools/migration/javatests/com/squareup/tools/migration/bazel/core:UtilsTest BuildConfigurationValue.Key[1161f44308ef9f9b52fbb9faa62606aa2a1a4187cf705c148fdbb483fa43942b] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.createTestAction(TestActionBuilder.java:405)
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.build(TestActionBuilder.java:101)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.initializeTestProvider(RuleConfiguredTargetBuilder.java:431)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:156)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:234)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:156)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:468)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)

```

**Comment by cgruber** [comment]
Happens in 3.2.0 as well:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tools/migration/javatests/com/squareup/tools/migration/bazel/core:UtilsTest BuildConfigurationValue.Key[306aafb5af58a56b06a97e760d5daa0e2d7e8881a7120aae1b0a729e013be0c5] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.createTestAction(TestActionBuilder.java:374)
	at com.google.devtools.build.lib.analysis.test.TestActionBuilder.build(TestActionBuilder.java:100)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.initializeTestProvider(RuleConfiguredTargetBuilder.java:406)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:156)

```

**Comment by ulfjack** [comment]
Are you using the persistent test runner for Java? Does it work for you?

Looking through the code, I'd say it currently throws an NPE for any test rule that isn't the built-in `java_test` rule. It's probably not exposed to Starlark yet, so that also means every custom Starlark test rule.
