### ISSUE TITLE
Desugaring for Android failed: Worker process did not return a WorkResponse

### ISSUE THREAD

**Issue by steelrooter** [bazelbuild/bazel#11530]
### Description of the problem:

While building an Android project, with Bazel from latest master, an error is thrown in Desugar worker log saying: `Error parsing command line: Unrecognized option: --persistent_worker`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Though I faced it in multiple projects, this project can be used for reproducing the issue: https://github.com/steelrooter/bazel-android-samples
Run: `bazel build //app:app`

### What operating system are you running Bazel on?

macOS (darwin)

### What's the output of `bazel info release`?

`development version`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`bazelisk build //src:bazel`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

`git@github.com:bazelbuild/bazel.git`
c063b5caf776dee665497b64c5c17d4ed7e6750a
`4eee205df99e42922d0d658c7f41f72af2397895`

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
ERROR: /Users/sachin/PersonalProjects/samples-bazel-android/app/src/main/java/com/xachin/playground/BUILD.bazel:3:19: Desugaring app/src/main/java/com/xachin/playground/playground-app_kt.jar for Android failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_sachin/6af8cdc15b57945be280298fb5d977c4/bazel-workers/worker-2-Desugar.log ---8<---8<---
Error parsing command line: Unrecognized option: --persistent_worker
Try --help.
---8<---8<--- End of log ---8<---8<---
Target //app:app failed to build
```

**Comment by jin** [comment]
I can reproduce the error in your project. The fix is not use a custom `@android_tools` repository by removing the `build --override_repository=android_tools=/tmp/android_tools` line from your .bazelrc file. 

https://github.com/steelrooter/bazel-android-samples/blob/master/.bazelrc

Desugar and resource processing tools are bundled separately in that repository. It looks like you have a stale local copy.

**Comment by steelrooter** [comment]
I removed the `build --override_repository=android_tools=/tmp/android_tools` line from Bazel configuration, and now facing a different error:
```
ERROR: /Users/sachin/PersonalProjects/samples-bazel-android/app/BUILD.bazel:1:15: Processing data binding for //app:app failed (Exit 1): ResourceProcessorBusyBox failed: error executing command
  (cd /private/var/tmp/_bazel_sachin/6af8cdc15b57945be280298fb5d977c4/sandbox/darwin-sandbox/53/execroot/__main__ && \
  exec env - \
    PATH=/Users/sachin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sachin/Library/Android/sdk/platform-tools:/usr/local/sbin:/Users/sachin/go/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool PROCESS_DATABINDING -- --output_resource_directory bazel-out/darwin-fastbuild/bin/app/databinding-processed-resources/app --resource_root app/src/main/res --dataBindingInfoOut bazel-out/darwin-fastbuild/bin/app/databinding/app/layout-info.zip --appId com.xachin.playground)
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox ResourceProcessorBusyBox failed: error executing command
  (cd /private/var/tmp/_bazel_sachin/6af8cdc15b57945be280298fb5d977c4/sandbox/darwin-sandbox/53/execroot/__main__ && \
  exec env - \
    PATH=/Users/sachin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sachin/Library/Android/sdk/platform-tools:/usr/local/sbin:/Users/sachin/go/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool PROCESS_DATABINDING -- --output_resource_directory bazel-out/darwin-fastbuild/bin/app/databinding-processed-resources/app --resource_root app/src/main/res --dataBindingInfoOut bazel-out/darwin-fastbuild/bin/app/databinding/app/layout-info.zip --appId com.xachin.playground)
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox
Jun 02, 2020 2:56:41 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: android/databinding/tool/writer/JavaFileWriter
	at com.google.devtools.build.android.AndroidResourceProcessor.processDataBindings(AndroidResourceProcessor.java:434)
	at com.google.devtools.build.android.AndroidDataBindingProcessingAction.main(AndroidDataBindingProcessingAction.java:134)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$12.call(ResourceProcessorBusyBox.java:135)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
Caused by: java.lang.NoClassDefFoundError: android/databinding/tool/writer/JavaFileWriter
	at com.google.devtools.build.android.AndroidResourceProcessor.processDataBindings(AndroidResourceProcessor.java:432)
	... 4 more
Caused by: java.lang.ClassNotFoundException: android.databinding.tool.writer.JavaFileWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: android/databinding/tool/writer/JavaFileWriter
	at com.google.devtools.build.android.AndroidResourceProcessor.processDataBindings(AndroidResourceProcessor.java:434)
	at com.google.devtools.build.android.AndroidDataBindingProcessingAction.main(AndroidDataBindingProcessingAction.java:134)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$12.call(ResourceProcessorBusyBox.java:135)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
Caused by: java.lang.NoClassDefFoundError: android/databinding/tool/writer/JavaFileWriter
	at com.google.devtools.build.android.AndroidResourceProcessor.processDataBindings(AndroidResourceProcessor.java:432)
	... 4 more
Caused by: java.lang.ClassNotFoundException: android.databinding.tool.writer.JavaFileWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
Target //app:app failed to build
ERROR: /Users/sachin/PersonalProjects/samples-bazel-android/app/BUILD.bazel:1:15 Processing data binding for //app:app failed (Exit 1): ResourceProcessorBusyBox failed: error executing command
  (cd /private/var/tmp/_bazel_sachin/6af8cdc15b57945be280298fb5d977c4/sandbox/darwin-sandbox/53/execroot/__main__ && \
  exec env - \
    PATH=/Users/sachin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sachin/Library/Android/sdk/platform-tools:/usr/local/sbin:/Users/sachin/go/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool PROCESS_DATABINDING -- --output_resource_directory bazel-out/darwin-fastbuild/bin/app/databinding-processed-resources/app --resource_root app/src/main/res --dataBindingInfoOut bazel-out/darwin-fastbuild/bin/app/databinding/app/layout-info.zip --appId com.xachin.playground)
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox ResourceProcessorBusyBox failed: error executing command
  (cd /private/var/tmp/_bazel_sachin/6af8cdc15b57945be280298fb5d977c4/sandbox/darwin-sandbox/53/execroot/__main__ && \
  exec env - \
    PATH=/Users/sachin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sachin/Library/Android/sdk/platform-tools:/usr/local/sbin:/Users/sachin/go/bin \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool PROCESS_DATABINDING -- --output_resource_directory bazel-out/darwin-fastbuild/bin/app/databinding-processed-resources/app --resource_root app/src/main/res --dataBindingInfoOut bazel-out/darwin-fastbuild/bin/app/databinding/app/layout-info.zip --appId com.xachin.playground)
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 2.293s, Critical Path: 2.04s
INFO: 5 processes: 5 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
That's a databinding error. Could we merge that into the [databinding issue](https://github.com/bazelbuild/bazel/issues/2694)

**Comment by steelrooter** [comment]
Sure

**Comment by nkoroste** [comment]
I just got the same issue after upgrading to Bazel 3.3.0

**Comment by jin** [comment]
@nkoroste do you have a way to repro this failure?

**Comment by nkoroste** [comment]
Created https://github.com/bazelbuild/bazel/issues/11618 with repro steps
