### ISSUE TITLE
HTTPConnector test: IOException thrown instead of SocketTimeOutException 

### ISSUE THREAD

**Issue by ehrtro** [bazelbuild/bazel#11569]
**BACKGROUND**
We're trying to run the [HttpConnectorTest](https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnectorTest.java) on our RHEL7 system, and are receiving the following failure:

```
socketTimeout_throwsIOExceptionInsteadOfSocketTimeoutException(com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorTest)
value of: throwable.getCause().getMessage()
expected: connect timed out
but was : Read timed out
```
We think that the issue might be due our Linux-distribution. The problem might be of the same cause as https://github.com/bazelbuild/bazel/commit/35800bdbc51744b3437f088043d9a7f44aa455a9 where the exception message depends on the operating system.

**DESIRED OUTCOME**
As stated in the window above, we are looking for the outcome `connect timed out`

**WORKAROUND**
Change the following code:
`      } catch (IOException expected) {
        assertThat(expected).hasCauseThat().isInstanceOf(SocketTimeoutException.class);
        assertThat(expected)
            .hasCauseThat()
            .hasMessageThat()
            .ignoringCase()
            .isEqualTo("connect timed out");`

To:
`      } catch (IOException expected) {
        assertThat(expected).hasCauseThat().isInstanceOf(SocketTimeoutException.class);
        assertThat(expected)
            .hasCauseThat()
            .hasMessageThat()
            .ignoringCase()
            .contains("timed out");`

**STACKTRACE**
`1) socketTimeout_throwsIOExceptionInsteadOfSocketTimeoutException(com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorTest)
value of: throwable.getCause().getMessage()
expected: connect timed out
but was : Read timed out
(case is ignored)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorTest.socketTimeout_throwsIOExceptionInsteadOfSocketTimeoutException(HttpConnectorTest.java:368)
Caused by: java.io.IOException: Read timed out
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:216)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorTest.socketTimeout_throwsIOExceptionInsteadOfSocketTimeoutException(HttpConnectorTest.java:356)
	Suppressed: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
		at java.net.SocketInputStream.read(SocketInputStream.java:171)
		at java.net.SocketInputStream.read(SocketInputStream.java:141)
		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
		at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
		at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
		at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
		at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
		at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
		at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
		at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
		at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:130)`

**Comment by aiuto** [comment]
I'll do a PR, this is trivial and your suggestion is obviously better. We should rarely, if ever, test for exact equality of an error message.
