### ISSUE TITLE
HttpConnectorMultiplexerIntegrationTest: firstUrlSocketTimeout_secondOk times out due to large ReadTimeout

### ISSUE THREAD

**Issue by ehkloaj** [bazelbuild/bazel#11578]
### Description of the problem:

We're trying to run the [HttpConnectorMultiplexerIntegrationTest](https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnectorMultiplexerIntegrationTest.java) and are facing some issues on our RHEL7 system. The test firstUrlSocketTimeout_secondOk times out before it can do its assertion: `test timed out after 20000 milliseconds`.

In the test, the **globalTimeout** is set to 20 sec and the **HttpConnection**'s **timeoutScaling** to 0.15. This causes the **HttpConnection**'s **readTimeout** to be 3 sec (**READ_TIMEOUT_MS** * **timeoutScaling** = 20000 * 0.15). 

In [HttpConnector](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnector.java) the variable **MAX_RETRIES** is set to 8 and **READ_TIMEOUT_MS** to 20000 (which is multiplied with **timeoutScaling** as stated above). This results in a minimum execution time of 24 sec for the entire test (8 retries * 3 sec) when having to wait for the read to time out in all the eight retries. 

According to the documentation for [URLConnection](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setReadTimeout-int-) the program should wait at least the specified timeout value if there is not any data to read, which is the case in this test. 

We are not sure if this due to our environment and that reading works differently on your systems resulting in a lower reading time for you. 

We suggest solving this by decreasing the **timeoutScaling** to 0.1 resulting in a **readTimeout** of 2 sec (20000 * 0.1) resulting in an execution time of 16 sec (8 retries * 2 sec) and therefore increase the chances of a successful test. 

**globalTimeout** and **timeoutScaling** was recently changed in https://github.com/bazelbuild/bazel/commit/b9786cae0aca3b33ff48da056f09e076b1f20ff6 from 10000 and 0.1 but this also caused the test to fail since it resulted in a minimum execution time of 16 sec (8 retries * 2 sec). A combination of **globalTimeout** = 20 000 and **timeoutScaling** = 0.1 results in a successful test on our system.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is tricky since the problem seems to be related to our internal environment. 

### What operating system are you running Bazel on?

Red Hat Enterprise Linux Server release 7.7 (Maipo).

### What's the output of `bazel info release`?

release 2.2.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/bazelbuild/bazel.git
1e4f0690e66b6e36b5f92b072d40e2b3fc95616f
1e4f0690e66b6e36b5f92b072d40e2b3fc95616f
```
###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

We are receiving the following error message:

`
test timed out after 20000 milliseconds
org.junit.runners.model.TestTimedOutException: 
	at java.base@11.0.7/java.lang.Object.wait(Native Method)
	at java.base@11.0.7/java.lang.Object.wait(Object.java:328)
	at app//com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:177)
	at app//com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:101)
	at app//com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexerIntegrationTest.firstUrlSocketTimeout_secondOk(HttpConnectorMultiplexerIntegrationTest.java:279)
	at java.base@11.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.7/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base@11.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
`

**Comment by philwo** [comment]
I'm happy to merge something that improves the test, but I don't think it's flaky for us on CI and I can't immediately see what the right behavior here is with all the interactions of timeouts, so I'd rather just leave it as is, tbh. :/
