### ISSUE TITLE
Bazel crash for cc_binary with tree artifact in srcs

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#11616]
Tested on Ubuntu Linux with Bazel 3.1 and Bazel 3.3.

gentree.bzl:
```
def _gentree(ctx):
    out = ctx.actions.declare_directory("dir")
    ctx.actions.run_shell(
        outputs = [out],
        command = "echo 'int main(int c, char** v){return 1;}' > %s/foo.cc" % (out.path),
        progress_message = "Generating into %s" % out.short_path,
    )
    return DefaultInfo(files = depset([out]))

gentree = rule(
    implementation = _gentree,
    attrs = {
    },
)
```

BUILD:
```
load(":gentree.bzl", "gentree")
gentree(name = "tree")
cc_binary(
  name = "main",
  srcs = [":tree"],
)
```

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tree_artifacts:main BuildConfigurationValue.Key[45d0b89373a0dfd75ac4b432cf2b12138c1203b34bdec57557dfef52e7a6ed03]' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.getActionName(CppCompileActionBuilder.java:199)
	at com.google.devtools.build.lib.bazel.rules.cpp.BazelCppSemantics.finalizeCompileActionBuilder(BazelCppSemantics.java:69)
	at com.google.devtools.build.lib.rules.cpp.CcCompilationHelper.createCompileActionTemplate(CcCompilationHelper.java:1441)
	at com.google.devtools.build.lib.rules.cpp.CcCompilationHelper.createCcCompileActions(CcCompilationHelper.java:1388)
	at com.google.devtools.build.lib.rules.cpp.CcCompilationHelper.compile(CcCompilationHelper.java:753)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:404)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:282)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:96)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:488)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:189)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:896)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:947)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:343)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
```

It looks like the comment at https://github.com/bazelbuild/bazel/blob/6a93a463e94a3808bf624ec588606265e5c1f65f/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileActionBuilder.java#L198 is not true anymore.

**Comment by ulfjack** [comment]
This issue is for the crash - Bazel shouldn't crash. The CC rules require the tree artifact *directory* to end with .cc for them to process the tree artifact correctly, i.e.:
```
def _gentree(ctx):
    out = ctx.actions.declare_directory("dir.cc")
    ctx.actions.run_shell(
        outputs = [out],
        command = "echo 'int main(int c, char** v){return 1;}' > %s/foo.cc" % (out.path),
        progress_message = "Generating into %s" % out.short_path,
    )
    return DefaultInfo(files = depset([out]))

gentree = rule(
    implementation = _gentree,
    attrs = {
    },
)
```

**Comment by meisterT** [comment]
I'm not sure core is the correct team for this.

Cc @oquenchil
