### ISSUE TITLE
configurable size limit for worker logs printed to the console

### ISSUE THREAD

**Issue by dsilvasc** [bazelbuild/bazel#11639]
### Description of the problem / feature request:

When a worker fails, bazel prints a portion of the worker logs, up to a fixed size limit:
https://github.com/bazelbuild/bazel/blob/9716d31534d2121e8712cd1c07bcec8ecd09dff1/src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java#L419

In CI builds that don't keep the bazel output base around or don't have an easy way to access files outside of the workspace directory, sometimes that limit isn't enough to tell what caused a build to fail.

Can the limit be configurable?

### Feature requests: what underlying problem are you trying to solve with this feature?

Determine what caused a build to fail in CI.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Make a worker produce more than 4096 bytes of logs, then fail.

### What operating system are you running Bazel on?

Linux and mac

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using a company internal fork of 3.0.0.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Company internal repository

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/1082

### Any other information, logs, or outputs that you want to share?

Example failure:

```
2020-06-25 13:32:03 ERROR: /var/lib/jenkins/workspace/.../BUILD.bazel:7:16: scala //...example.proto.scala-lib failed: Worker process did not return a WorkResponse:
2020-06-25 13:32:03 
2020-06-25 13:32:03 ---8<---8<--- Start of log snippet, file at /home/jenkins/tmp.noindex/bazel/output_user_root/172202e61855f233608f5675a2bdd976/bazel-workers/worker-8-Scalac.log ---8<---8<---
2020-06-25 13:32:03 [... truncated ...]
2020-06-25 13:32:03 imination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:412)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:98)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform(Trees.scala:1410)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1374)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:416)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.fail$1(TailCalls.scala:250)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.failHere$1(TailCalls.scala:255)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.rewriteApply$1(TailCalls.scala:270)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:388)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:412)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:98)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform(Trees.scala:1410)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1374)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:416)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.fail$1(TailCalls.scala:250)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.failHere$1(TailCalls.scala:255)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.rewriteApply$1(TailCalls.scala:270)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:388)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:412)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:98)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform(Trees.scala:1410)
2020-06-25 13:32:03 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1374)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
2020-06-25 13:32:03 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:416)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.noTailTransform(TailCalls.scala:222)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.fail$1(TailCalls.scala:250)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.failHere$1(TailCalls.scala:255)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.rewriteApply$1(TailCalls.scala:270)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:388)
2020-06-25 13:32:03 	at scala.tools.nsc.transform.TailCalls$TailCallElimination.transform(TailCalls.scala:217)
2020-06-25 13:32:03 ---8<---8<--- End of log snippet, 82634 chars omitted ---8<---8<---
2020-06-25 13:32:04 INFO: Elapsed time: 467.374s (7.79m), Critical Path: 163.17s (2.72m)
2020-06-25 13:32:04 INFO: 78903 processes: 73471 local, 5432 worker (0.00%).
2020-06-25 13:32:04 FAILED: Build did NOT complete successfully
```

**Comment by susinmotion** [comment]
This is a sticky issue. Since the worker logs might contain data from lots of invocations, they can be very long, which is why we truncate them. Adding a user option to set the printed log length involves poking some holes in the worker creation, which is possible, but seems like overkill. It's also possible to upload the logs to the BEP,  but this is also a major change.

To get a better idea of how to prioritize this... 
Do you have an alternate way to look at the log file generated with CI?
How much pain is this causing?

**Comment by dsilvasc** [comment]
Thanks for looking into this.  For now I'm wrapping bazel to print all worker logs on failure:

```bash
bazel_or_log() {
  if ! ./bazel "$@"; then
    for f in $(./bazel info output_base)/bazel-workers/*.log; do
      if [ -s "$f" ]; then
        echo "$f:" >/dev/stderr
        cat $f >/dev/stderr
      fi
    done
    exit 1
  fi
}
```

With that in place, the log limit doesn't cause much pain.  Otherwise it would lead to build errors like the one above that don't have enough information to diagnose.
