### ISSUE TITLE
Fresh Bazel install fails on Windows due to Cyrillic username

### ISSUE THREAD

**Issue by PeterZhizhin** [bazelbuild/bazel#11649]
### Description of the problem / feature request:

I tried official Bazel installation instructions on Windows. [Here is the link.](https://docs.bazel.build/versions/master/install-windows.html)

I downloaded the latest official package from the Github repo: `bazel-3.3.0-windows-x86_64.exe`.

Here is what happens when I try to launch it:
```
PS C:\Users\Петр\Downloads> .\bazel-3.3.0-windows-x86_64.exe
Extracting Bazel installation...
Error: Unable to access jarfile C:\\Users\\peter\\_bazel_????\\install\\80fc65b95db8e3302b5f3cb0c5c1c48e\\A-server.jar
```

I had similar problems with other packages before. In order to solve them, I did the following:
1. Created a symlink for my `C:\Users\Петр` folder (it is `C:\Users\peter`).
2. Changed all env variables to point to the ascii symlink instead. At least the ones I can change. The full list of env vars:
```
Name                      Value
----                      -----
ALLUSERSPROFILE           C:\ProgramData
APPDATA                   C:\Users\Петр\AppData\Roaming
CARGO_HOME                C:\Users\peter\.cargo
ChocolateyInstall         C:\ProgramData\chocolatey
ChocolateyLastPathUpdate  132375544650803135
ChocolateyToolsLocation   C:\tools
CommonProgramFiles        C:\Program Files\Common Files
CommonProgramFiles(x86)   C:\Program Files (x86)\Common Files
CommonProgramW6432        C:\Program Files\Common Files
COMPUTERNAME              LAPTOP-MAO9JA8F
ComSpec                   C:\WINDOWS\system32\cmd.exe
configsetroot             C:\WINDOWS\ConfigSetRoot
DriverData                C:\Windows\System32\Drivers\DriverData
GSTREAMER_1_0_ROOT_X86_64 C:\gstreamer\1.0\x86_64\
HOME                      C:\Users\peter
HOMEDRIVE                 C:
HOMEPATH                  \Users\Петр
LOCALAPPDATA              C:\Users\Петр\AppData\Local
LOGONSERVER               \\LAPTOP-MAO9JA8F
NUMBER_OF_PROCESSORS      8
OneDrive                  C:\Users\Петр\OneDrive
OS                        Windows_NT
Path                      C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Anaconda;C:\Anaconda\Scripts;C:\A
                          naconda\Library\bin;C:\Anaconda\libs;C:\Program Files (x86)\Common Files\Oracle\Java\javapath
                          ;C:\Anaconda;C:\Anaconda\Scripts;C:\Anaconda\Library\bin;C:\Anaconda\libs;%path%;C:\Users\pet
                          er\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-
                          packages\Python37\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\
                          System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\In
                          tel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Com
                          ponents\DAL;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\W
                          INDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.
                          0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common File
                          s\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Fil
                          es\LLVM\bin;C:\Python27;C:\Program Files\Cppcheck;C:\Program Files\Conan\conan;C:\Users\peter
                          \.cargo\bin;C:\Users\peter\AppData\Local\Microsoft\WindowsApps;C:\tools\neovim\Neovim\bin;C:\
                          Users\peter\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Петр\AppData\Local\Programs
                          \Microsoft VS Code\bin;C:\Users\peter\AppData\Local\Packages\PythonSoftwareFoundation.Python.
                          3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C
                          :\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenS
                          SH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\I
                          ntel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\system32\config\systemprofile\AppDa
                          ta\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WIN
                          DOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiF
                          i\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Progra
                          mData\chocolatey\bin;C:\Program Files\LLVM\bin;C:\Python27;C:\Program Files\Cppcheck;C:\Progr
                          am Files\Conan\conan;C:\Users\peter\.cargo\bin;C:\Users\peter\AppData\Local\Microsoft\Windows
                          Apps;C:\tools\neovim\Neovim\bin;C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\bin;C
                          :\Users\Петр\AppData\Local\Programs\Microsoft VS Code\bin
PATHEXT                   .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE    AMD64
PROCESSOR_IDENTIFIER      Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL           6
PROCESSOR_REVISION        8e0a
ProgramData               C:\ProgramData
ProgramFiles              C:\Program Files
ProgramFiles(x86)         C:\Program Files (x86)
ProgramW6432              C:\Program Files
PSModulePath              C:\Users\Петр\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;
                          C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                    C:\Users\Public
PYTHON                    C:\Python27\python.exe
PYTHON3                   C:\Python37\python.exe
RUSTUP_HOME               C:\Users\peter\.rustup
SystemDrive               C:
SystemRoot                C:\WINDOWS
TEMP                      C:\Users\B19A~1\AppData\Local\Temp
TMP                       C:\Users\B19A~1\AppData\Local\Temp
USERDOMAIN                LAPTOP-MAO9JA8F
USERDOMAIN_ROAMINGPROFILE LAPTOP-MAO9JA8F
USERNAME                  Петр
USERPROFILE               C:\Users\Петр
windir                    C:\WINDOWS
WSLENV                    WT_SESSION::WT_PROFILE_ID
WT_PROFILE_ID             {61c54bbd-c2c6-5271-96e7-009a87ff44bf}
WT_SESSION                e6f9da1a-eea3-4059-9bf9-615df727ec51
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get a Windows machine.
2. Create a new user with a non-ascii username (for example: `Петр`).
3. Get Bazel from the official website.
4. Run it.

### What operating system are you running Bazel on?

Windows.

###  Have you found anything relevant by searching the web?

I tried, but unfortunately Windows is not a very popular platform for development. Additionally, not so many people have non-latin alphabet usernames.

### Idea for mitigation

Is there a flag or an environment variable I can use to override the default Bazel extraction path? It seems that it tries to extract Bazel to something like `$HOME/_bazel_$USERNAME`. For example, Rust's language package manager, Cargo allows to change it's installation folder by setting `$CARGO_HOME` [environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads).

**Comment by PeterZhizhin** [comment]
I found the `--install_base` flag. Here is the error:
```
PS C:\Users\peter\Downloads> .\bazel-3.3.0-windows-x86_64.exe --install_base C:\Users\peter\_bazel
Extracting Bazel installation...
java.nio.file.InvalidPathException: Illegal char <?> at index 21: C:/users/????/_bazel_????/u5mzpase/failure_detail.rawproto
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.util.CustomFailureDetailPublisher.setFailureDetailFilePath(CustomFailureDetailPublisher.java:38)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1178)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:938)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
ERROR: <unknown> crash in async thread:
java.nio.file.InvalidPathException: Illegal char <?> at index 21: C:/users/Петр/_bazel_????/u5mzpase/failure_detail.rawproto
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.util.CustomFailureDetailPublisher.setFailureDetailFilePath(CustomFailureDetailPublisher.java:38)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1178)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:938)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
```

**Comment by PeterZhizhin** [comment]
I also found the `--output_base` flag, here is the output:
```
PS C:\Users\peter\Downloads> .\bazel-3.3.0-windows-x86_64.exe --output_base C:\Users\peter\_bazel --install_base C:\Users\peter\_bazel
java.util.logging.ErrorManager: 4: Failed to open log file
java.io.FileNotFoundException: c:\users\????????\_bazel\java.log.laptop-mao9ja8f.Петр.log.java.20200626-191751.8876 (Системе не удается найти указанный путь)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.devtools.build.lib.util.SimpleLogHandler$Output.open(SimpleLogHandler.java:712)
        at com.google.devtools.build.lib.util.SimpleLogHandler.openOutputIfNeeded(SimpleLogHandler.java:799)
        at com.google.devtools.build.lib.util.SimpleLogHandler.publish(SimpleLogHandler.java:418)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at com.google.common.flogger.backend.system.AbstractBackend.log(AbstractBackend.java:76)
        at com.google.common.flogger.backend.system.SimpleLoggerBackend.log(SimpleLoggerBackend.java:31)
        at com.google.common.flogger.AbstractLogger.write(AbstractLogger.java:137)
        at com.google.common.flogger.LogContext.logImpl(LogContext.java:566)
        at com.google.common.flogger.LogContext.log(LogContext.java:686)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.logVersionInfo(BlazeVersionInfo.java:64)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.setBuildInfo(BlazeVersionInfo.java:79)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:83)
Internal error thrown during build. Printing stack trace: java.nio.file.InvalidPathException: Illegal char <?> at index 22: C:/users/peter/_bazel_????/cache/repos/v1
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.createDirectoryAndParents(JavaIoFileSystem.java:251)
        at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:549)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:614)
        at com.google.devtools.build.lib.bazel.BazelRepositoryModule.beforeCommand(BazelRepositoryModule.java:271)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:383)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
java.nio.file.InvalidPathException: Illegal char <?> at index 22: C:/users/peter/_bazel_????/cache/repos/v1
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.createDirectoryAndParents(JavaIoFileSystem.java:251)
        at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:549)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:614)
        at com.google.devtools.build.lib.bazel.BazelRepositoryModule.beforeCommand(BazelRepositoryModule.java:271)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:383)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
java.nio.file.InvalidPathException: Illegal char <?> at index 22: C:/users/peter/_bazel_????/cache/repos/v1
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.createDirectoryAndParents(JavaIoFileSystem.java:251)
        at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:549)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:614)
        at com.google.devtools.build.lib.bazel.BazelRepositoryModule.beforeCommand(BazelRepositoryModule.java:271)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:383)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
java.lang.NullPointerException: env not initialized; was beforeCommand called?
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.google.devtools.build.lib.sandbox.SandboxModule.afterCommand(SandboxModule.java:529)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:623)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:623)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
ERROR: bazel crash in async thread:
java.lang.NullPointerException: env not initialized; was beforeCommand called?
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.google.devtools.build.lib.sandbox.SandboxModule.afterCommand(SandboxModule.java:529)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:623)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:623)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:763)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
```

**Comment by laszlocsomor** [comment]
Try this before running Bazel:
```
set HOME=C:/Users/peter
```

**Comment by laszlocsomor** [comment]
Explanation: Bazel will check the home directory for the "home RC" (see: <https://docs.bazel.build/versions/3.3.0/guide.html#where-are-the-bazelrc-files>).

You can override what path it checks by setting the HOME or the USERPROFILE envvar. I recommend setting HOME, for two reasons: (1) it's Linux-specific so Windows programs won't expect it to be set, but Bazel supports it on Windows for consistency, and (2) setting USERPROFILE may mess with other programs.

Alternatively you can create another user with Latin letters in the name, so its home directory will be safe for Bazel.

**Comment by laszlocsomor** [comment]
> Try this before running Bazel:
> 
> ```
> set HOME=C:/Users/peter
> ```

Ah, you mentioned this is just a symlink. The real path still has a non-Latin character -- that might be a problem.

Try this then:
```
md c:\bazel-home

set HOME=c:\bazel-home

bazel version
```

**Comment by PeterZhizhin** [comment]
I tried running the commands in PowerShell. Here is the result:
```powershell
PS C:\Users\Петр\Downloads> $env:HOME = 'C:\bazel-home'
PS C:\Users\Петр\Downloads> $env:Home
C:\bazel-home
PS C:\Users\Петр\Downloads> & '.\bazel-3.3.1-windows-x86_64(1).exe'
Extracting Bazel installation...
Error: Unable to access jarfile C:\\bazel-home\\_bazel_????\\install\\70f0c774398659e732ad15d5201c011f\\A-server.jar
PS C:\Users\Петр\Downloads> ls C:\bazel-home


    Каталог: C:\bazel-home


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        09.07.2020     19:06                _bazel_����
PS C:\Users\Петр\Downloads> Remove-Item C:\bazel-home\_bazel_????\ -Recurse -Force
PS C:\Users\Петр\Downloads> & '.\bazel-3.3.1-windows-x86_64(1).exe' --output_base 'C:\bazel-home\_bazel' --install_base 'C:\bazel-home\_bazel'
FATAL: corrupt installation: file 'c:\bazel-home\_bazel\A-server.jar' is missing or modified.  Please remove 'c:\bazel-home\_bazel' and try again.
PS C:\Users\Петр\Downloads> Remove-Item C:\bazel-home\_bazel\ -Recurse -Force
PS C:\Users\Петр\Downloads> & '.\bazel-3.3.1-windows-x86_64(1).exe' --output_base 'C:\bazel-home\_bazel' --install_base 'C:\bazel-home\_bazel'
FATAL: corrupt installation: file 'c:\bazel-home\_bazel\A-server.jar' is missing or modified.  Please remove 'c:\bazel-home\_bazel' and try again.
```

**Comment by laszlocsomor** [comment]
Ah, it includes the user name. Then let's try this:
```
set USER=Peter
```
And try again.

You may need to set `--output_user_base=c:\something`. Don't set `--output_base` or `--install_base`; they are computed from output_user_base.

Does that work?

**Comment by PeterZhizhin** [comment]
It worked! `--output_user_base` doesn't exist, though. But it works!
In the meantime, I will create a script that overrides these environment variables before it runs Bazel.

**Comment by laszlocsomor** [comment]
Great!
Yes, it's actually `output_user_root`, my bad.

**Comment by pancwchengwei** [comment]
"In the meantime, I will create a script that overrides these environment variables before it runs Bazel."
how to do this? I faced the same question as you.

**Comment by laszlocsomor** [comment]
@pancwchengwei : here's an idea:
1. create a script called `bazel.bat`:
    ```
    @set HOME=C:\Users\foo
    C:\path\to\real\bazel.exe --output_user_root=C:\_b %*
    ```

    (Replace the paths above as needed.)

2. Save the file under `C:\Windows` (or in some directory that's on your PATH)

**Comment by pancwchengwei** [comment]
Thank you very much！
Solve the problem perfectly！

**Comment by Cheney2333** [comment]
Have you solved this problem??
