### ISSUE TITLE
TreeArtifacts don't have support for special files

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/bazel#11669]
### Description of the problem / feature request:

I have developed a set of custom rules for building a VM image. In the process of creating the image, we create a filesystem, and that filesystem is visible to Bazel. Unfortunately, since the filesystem contains device nodes (/dev/zero for example), Bazel throws an internal exception whenever we try to build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a genrule that executes `mknod zero c 3 3`. When the output of this genrule is depended upon (possibly even if it's built) you'll get a stack trace and failed build.

### What operating system are you running Bazel on?

macOS 10.15.5 (19F101)

### What's the output of `bazel info release`?

`release 3.1.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
[REDACTED: internal GHE instance url]
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
a811eabf7cdde73db2ba2d705c5c7be2b88fe10e
```

**Note**: we use `main` as the default branch. Replacing that branch name in the command returns:

```
[REDACTED: internal GHE instance url]
a811eabf7cdde73db2ba2d705c5c7be2b88fe10e
a811eabf7cdde73db2ba2d705c5c7be2b88fe10e
```

###  Have you found anything relevant by searching the web?

Nope, looked at google searches for parts of the stack trace and 'special file' and 'device node' with no luck, as well as directly searching the group archives.

### Any other information, logs, or outputs that you want to share?

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//[REDACTED] BuildConfigurationValue.Key[20660e0ad500c9539eccb6618ce68164a3f9708eef075d02d6af7665738b50d9] false, actionIndex=0}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin][REDACTED]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Could not determine type of file [REDACTED]/rootfs/dev/zero
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:251)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:219)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:219)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:265)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.constructTreeArtifactValueFromFilesystem(ActionMetadataHandler.java:463)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getTreeArtifactValue(ActionMetadataHandler.java:408)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getMetadata(ActionMetadataHandler.java:240)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkOutputs(SkyframeActionExecutor.java:1610)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$1900(SkyframeActionExecutor.java:141)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.actuallyCompleteAction(SkyframeActionExecutor.java:1198)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1158)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//[REDACTED] BuildConfigurationValue.Key[20660e0ad500c9539eccb6618ce68164a3f9708eef075d02d6af7665738b50d9] false, actionIndex=0}' (requested by nodes 'File:[[<execution_root>][REDACTED]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Could not determine type of file [REDACTED]/rootfs/dev/zero
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:251)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:219)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:219)
	at com.google.devtools.build.lib.skyframe.TreeArtifactValue.explodeDirectory(TreeArtifactValue.java:265)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.constructTreeArtifactValueFromFilesystem(ActionMetadataHandler.java:463)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getTreeArtifactValue(ActionMetadataHandler.java:408)
	at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getMetadata(ActionMetadataHandler.java:240)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkOutputs(SkyframeActionExecutor.java:1610)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$1900(SkyframeActionExecutor.java:141)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.actuallyCompleteAction(SkyframeActionExecutor.java:1198)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1158)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
FAILED: Build did NOT complete successfully
```

**Comment by haxorz** [comment]
I'm a Github noob. Why can't I assign this to @ericfelly ?

**Comment by haxorz** [comment]
@janakdr @justinhorvitz 
^ Other interested parties

**Comment by jin** [comment]
@haxorz I'd check if @ericfelly is in the Bazel team within the bazelbuild GitHub Organization. @philwo or @aiuto, could you help please?

**Comment by haxorz** [comment]
Thanks. He's not. Was he removed ~recently? (I was not removed)

**Comment by justinhorvitz** [comment]
As of https://github.com/bazelbuild/bazel/commit/0d0758aeaaf7ade4fbacfb99e222b9a8a0f08a21 we now fail gracefully in this case as opposed to a crash. But the build still fails.

Adding support should be possible - see https://github.com/bazelbuild/bazel/blob/77497410a23bd212e8c3b4e48903d805e7d9097f/src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java#L273

**Comment by aiuto** [comment]
@swsnider   Can you describe the overall intent a little more. Do you build a filesystem and expect it all to be in a tree artifact that you pass directly to a consuming rule? Or, do you build it and bundle it into a .iso, which is a dep of other rules.

**Comment by justinhorvitz** [comment]
@swsnider I'm also a bit confused because your example mentions a genrule that outputs mknod, but the stack trace you give is for a tree artifact (not a genrule). Can you please clarify?

**Comment by justinhorvitz** [comment]
I've confirmed that it is technically possible to create special files using `mknod` from a genrule in combination with `sudo`. Some special file types don't work, however - for example:

- A named pipe will make bazel hang indefinitely (assuming no writes to the pipe) because it tries to read the file to digest its contents.
-  The "zero" special file mentioned in the original report won't work because we can't read it - "No such device or address".

Tree artifacts explicitly prohibit special files. The question is whether we want to:

1. Make tree artifacts consistent with other artifacts in their handling of special files, i.e., attempt to support them with the caveat of the aforementioned potential issues of reading their contents.
2. Explicitly prohibit special files for all outputs because of the potential bugs with edge cases mentioned here.
3. Maintain the status quo because (1) opens up possibilities of new bugs and (2) might break people.

Assigning to @swsnider for more information before we make this decision.

**Comment by swsnider** [comment]
I have a new rule set developed in house for building Centos images for putting onto machines. The rules invoke the normal tools to do this, such as mknod. I summarized this as 'genrule' because I misunderstood what the pertinent info would be.

The huge problem we have is that we want to pass the directory containing the rootfs around between rules that construct 'layers' on top of that rootfs so that we don't incur the tar/untar cost constantly, but there's no way to do that for us right now because of this issue with bazel. We specifically need *all* device nodes to work, especially /dev/zero and /dev/null since that's a basic part of a rootfs that RPM can install things into.

**Comment by swsnider** [comment]
To be clear, right now we're working around it by tar-ing up the rootfs, then *deleting* the original dir at the end of *every* rule. The beginning of every rule untars so that everything continues to work.

**Comment by swsnider** [comment]
@justinhorvitz I can't assign back to you, but this is my response, hope it helps.

**Comment by swsnider** [comment]
@aiuto we have a set of rules that add to the fs in a layered fashion, then a final rule that squashfs-es it all together.

**Comment by justinhorvitz** [comment]
I think it will be fine to remove the ban on special files in a tree artifact, and that is trivial. However I'm concerned that there will still be more changes necessary to support outputting the device nodes, and if so we will have to consider the cost of maintaining the support for an obscure use case (I personally had no experience working with special files prior to this issue and I'm sure the same is true for many team members).

@swsnider could you attempt to create the device nodes you need as regular (non-tree) artifacts and see what issues you run into? That way we could have a better understanding of the additional work that would need to be done beyond the trivial step of lifting the tree artifact ban. Also, concrete examples (`BUILD` and `.bzl` files) of what you are doing would be helpful.

**Comment by swsnider** [comment]
@justinhorvitz if by 'create the device nodes as regular (non-tree) artifacts', you mean that I should try explicitly declaring each such device node as an output, instead of declaring the enclosing directory, that's not possible in our situation, as the nodes are created by the RPM packages we install inside the chroot, and we have no way of knowing which nodes will be created by a given RPM (and the RPMs are not static, but instead part of the input to the build rule).

**Comment by justinhorvitz** [comment]
I was hoping for an example build rule that creates the device node(s) you are requesting support for because as mentioned above, I expect that there will be more barriers to supporting this use case beyond just the tree artifact issue. I need to enumerate the barriers prior to determining whether support is feasible.

The example can be a tree artifact or the zipping approach you are using now. I just need something to work with.

**Comment by swsnider** [comment]
```
OsImageLayerInfo = provider(
    fields = ["imagec_dir", "artifacts", "tar"],
)

def _os_image_layer_impl(ctx):
    dir = ctx.actions.declare_directory(ctx.attr.name + "_imagec")

    fakeroot_info = ctx.toolchains["//lib/bzl/rules_os_image:fakeroot"].fakerootinfo
    cmd = ctx.executable._imagec.path
    args = [
        "--rpm-versions",
        ctx.file.rpm_versions.path,
        "--outdir",
        dir.path,
        "--bazel-status-path",
        ctx.info_file.path,
        "--repo-dir",
        ctx.file.src.dirname,
    ]
    if ctx.attr.imagec_extra_opts:
        args += ctx.attr.imagec_extra_opts

    inputs = [ctx.file.src, ctx.file.rpm_versions, ctx.info_file]
    if ctx.files.data:
        inputs += ctx.files.data
    if ctx.attr.parent:
        parent_dir = ctx.attr.parent[OsImageLayerInfo].imagec_dir
        args += ["--parent", parent_dir.path]
        inputs.append(ctx.attr.parent[OsImageLayerInfo].imagec_dir)
    args.append("-D")
    args.append(ctx.file.src.path)

    if fakeroot_info.fakechroot_path != "":
        args = [
            "-s",
            "--",
            cmd,
        ] + args
        cmd = "/usr/bin/fakechroot"
    if fakeroot_info.fakeroot_path != "":
        args = [
            "-s",
            dir.path + "/fakeroot_log",
            "--",
            cmd,
        ] + args
        cmd = fakeroot_info.fakeroot_path
    ctx.actions.run(
        inputs = inputs,
        outputs = [dir],
        mnemonic = "LayerImagec",
        executable = cmd,
        arguments = args,
        env = fakeroot_info.extra_env,
        tools = [ctx.executable._imagec],
    )
    return [
        OsImageLayerInfo(
            imagec_dir = dir,
        ),
        DefaultInfo(
            files = depset([dir]),
        ),
    ]

os_image_layer = rule(
    implementation = _os_image_layer_impl,
    attrs = {
        "data": attr.label_list(
            allow_files = True,
            allow_empty = True,
            default = [],
        ),
        "imagec_extra_opts": attr.string_list(
            mandatory = False,
            default = [],
            doc = "Extra options to pass to imagec",
        ),
        "parent": attr.label(
            providers = [(OsImageLayerInfo,)],
            doc = "The parent layer, if any",
        ),
        "rpm_versions": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The file containing the actual RPM versions to be used by this layer",
        ),
        "src": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The file containing the layer descriptor JSON",
        ),
        "_imagec": attr.label(
            executable = True,
            default = "//cli/imagec:imagec",
            allow_files = True,
            cfg = "host",
        ),
    },
    toolchains = ["//lib/bzl/rules_os_image:fakeroot"],
)
```

**Comment by swsnider** [comment]
@justinhorvitz is that what you need? or more?

**Comment by justinhorvitz** [comment]
The executable that outputs the artifacts in question is `//cli/imagec:imagec`. Can I run that somehow? Is that from some open source rules?

**Comment by swsnider** [comment]
No, it's closed source internal. It just runs RPM though (with some set dressing)

**Comment by justinhorvitz** [comment]
The `bzl` code alone doesn't give me enough context to know exactly which types of special outputs you need support for. Here are some options for proceeding.

1. @janakdr was wondering if you could just use an output directory instead of a tree artifact (just switch from `declare_directory` to `declare_file`, but the argument would still be a directory). It wouldn't benefit from the same incrementality support as tree artifacts because its digest would be based on mtime rather than contents. However it may be good enough for you.

2. If you need a tree artifact, modify `TreeArtifactValue#visitTree` to remove [these lines](https://github.com/bazelbuild/bazel/blob/fc27996491c84db1b3213a5a6dd6ca5b50c849e0/src/main/java/com/google/devtools/build/lib/skyframe/TreeArtifactValue.java#L354-L357) and build a custom bazel version (`bazel build //src:bazel`). Then use the output bazel binary (`bazel-bin/src/bazel`) to build your rules and see what if any issues you run into. I am hesitant to simply submit a change to remove these lines because I don't want to widen the tree artifact API unnecessarily.

3. Give me a concrete example that I can copy/paste/run that outputs all of the special file types you need to support.
