### ISSUE TITLE
interrupting build-runfiles prints a stacktrace

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#11661]
If you hit Control-C while `build-runfiles` is executing, the following stacktrace will be printed:
```
ERROR: BUILD:2:10: Creating runfiles tree bazel-out/k8-fastbuild/bin/hi.runfiles failed due to build-runfiles failed: error executing command 
  (cd /home/benjamin/.cache/bazel/_bazel_benjamin/52df745ebfeeb80d15cfd285068ffc99/execroot/__main__ && \
  exec env - ): Process terminated by signal 15: Process terminated by signal 15
com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15
	at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:84)
	at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
	at com.google.devtools.build.lib.exec.SymlinkTreeHelper.createSymlinksUsingCommand(SymlinkTreeHelper.java:163)
	at com.google.devtools.build.lib.exec.SymlinkTreeStrategy.createSymlinks(SymlinkTreeStrategy.java:119)
	at com.google.devtools.build.lib.analysis.actions.SymlinkTreeAction.execute(SymlinkTreeAction.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:785)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:948)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:907)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:128)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:425)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:926)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:310)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by janakdr** [comment]
Looks like this was introduced by @ulfjack in https://github.com/bazelbuild/bazel/commit/572bc144e77864fb0458155b432547af9cb260a0#diff-dccfcb0f29153facb4684e51d3482874. Fix should be trivial, test may be less so.

**Comment by janakdr** [comment]
Actually, it predates that commit: that commit just moved it from https://github.com/bazelbuild/bazel/commit/572bc144e77864fb0458155b432547af9cb260a0#diff-9adb486bf563283be597ba05dd2b06bcL334, which says that it's intentional. So we just need to suppress it when the exception comes from an interrupt.

**Comment by janakdr** [comment]
One more correction: it is the fault of that commit. We used to only print the stack trace for IOException, now it's unconditional. This is kind of a mess, especially since EnvironmentalExecException has an "Exception" constructor.

**Comment by janakdr** [comment]
I have a pending fix, sent internally. The change to EnvironmentalExecException was maybe ok, on further reflection. I think it was an (unintentional?) behavior change, but since EnvironmentalExecException is only supposed to happen on "system" errors anyway, the right firs for this issue is just to make this exception not an EnvironmentalExecException, since it's a user-triggered failure. There's a separate question of whether EnvironmentalExecException should embed a stack trace or (probably better) log a stack trace to the info log and try to show the user something nicer.
