### ISSUE TITLE
Add instructions for offline bootstrapping of Bazel

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#11692]
It was reported that attempting to bootstrap Bazel 3.3.x offline on Fedora, following the directions at https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel, results in the following error: 

```
$ env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Repository bazel_toolchains instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/gwyn/Downloads/test/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_toolchains':
   Traceback (most recent call last):
File "/home/gwyn/Downloads/test/tools/build_defs/repo/http.bzl", line 109
_get_auth(ctx, all_urls)
File "/home/gwyn/Downloads/test/tools/build_defs/repo/http.bzl", line 85, in _get_auth
read_netrc(ctx, netrcfile)
File "/home/gwyn/Downloads/test/tools/build_defs/repo/utils.bzl", line 215, in read_netrc
ctx.read(filename)
java.io.FileNotFoundException: /home/gwyn/.netrc (No such file or directory)
ERROR: no such package '@bazel_toolchains//rules': Traceback (most recent call last):
File "/home/gwyn/Downloads/test/tools/build_defs/repo/http.bzl", line 109
_get_auth(ctx, all_urls)
File "/home/gwyn/Downloads/test/tools/build_defs/repo/http.bzl", line 85, in _get_auth
read_netrc(ctx, netrcfile)
File "/home/gwyn/Downloads/test/tools/build_defs/repo/utils.bzl", line 215, in read_netrc
ctx.read(filename)
java.io.FileNotFoundException: /home/gwyn/.netrc (No such file or directory)
INFO: Elapsed time: 1.627s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

ERROR: Could not build Bazel
```

Bootstrapping offline _should_ be possible, and we need to document how to do it - distro maintainers need to know.

**Comment by tetromino** [comment]
On further conversation with the user, it appears that there is some weirdness about the user's environment. Marking 'more data needed' for now.

**Comment by tetromino** [comment]
It appears to have been a problem in the user's environment (a non-POSIX `test` command in PATH).
