### ISSUE TITLE
Documentation issue: Build Tutorial - Android: Example does not build

### ISSUE THREAD

**Issue by stoyicker** [bazelbuild/bazel#11739]
Documentation URL: https://docs.bazel.build/versions/3.3.0/tutorial/android-app.html

Installed bazel following the Ubuntu Linux using the apt repository on 18.04.4 LTS. 

Stacktrace:
```
SEVERE: Unexpected
com.google.common.base.VerifyException: Unexpected magic number in generated/src/main/java/com/example/bazel/res/values_colors.arsc.flat: 470425098
	at com.google.common.base.Verify.verify(Verify.java:301)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceContainer(AndroidCompiledDataDeserializer.java:719)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:668)
	at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:108)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:258)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Jul 10, 2020 12:52:58 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
com.google.common.base.VerifyException: Unexpected magic number in generated/src/main/java/com/example/bazel/res/values_colors.arsc.flat: 470425098
	at com.google.common.base.Verify.verify(Verify.java:301)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceContainer(AndroidCompiledDataDeserializer.java:719)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:668)
	at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:108)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:258)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Exception in thread "main" com.google.common.base.VerifyException: Unexpected magic number in generated/src/main/java/com/example/bazel/res/values_colors.arsc.flat: 470425098
	at com.google.common.base.Verify.verify(Verify.java:301)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceContainer(AndroidCompiledDataDeserializer.java:719)
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:668)
	at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:108)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:258)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
Target //src/main:app failed to build
INFO: Elapsed time: 11.369s, Critical Path: 4.85s
INFO: 18 processes: 11 linux-sandbox, 7 worker.
FAILED: Build did NOT complete successfully
```

Patch with what I've done so far (on top of https://github.com/bazelbuild/examples/tree/e5d77821c2cd686f87310111499b11e70ca56f8e):
```
diff --git a/android/tutorial/WORKSPACE b/android/tutorial/WORKSPACE
new file mode 100644
index 0000000..6f41f30
--- /dev/null
+++ b/android/tutorial/WORKSPACE
@@ -0,0 +1,6 @@
+android_sdk_repository(
+    name = "androidsdk",
+    path = "/home/jorge/Android/Sdk",
+    api_level = 25,
+    build_tools_version = "26.0.1"
+)
diff --git a/android/tutorial/src/main/BUILD b/android/tutorial/src/main/BUILD
new file mode 100644
index 0000000..ce1490e
--- /dev/null
+++ b/android/tutorial/src/main/BUILD
@@ -0,0 +1,5 @@
+android_binary(
+    name = "app",
+    manifest = "AndroidManifest.xml",
+    deps = ["//src/main/java/com/example/bazel:greeter_activity"],
+)
diff --git a/android/tutorial/src/main/java/com/example/bazel/BUILD b/android/tutorial/src/main/java/com/example/bazel/BUILD
new file mode 100644
index 0000000..76f8ba7
--- /dev/null
+++ b/android/tutorial/src/main/java/com/example/bazel/BUILD
@@ -0,0 +1,13 @@
+package(
+    default_visibility = ["//src:__subpackages__"],
+)
+
+android_library(
+    name = "greeter_activity",
+    srcs = [
+        "Greeter.java",
+        "MainActivity.java",
+    ],
+    manifest = "AndroidManifest.xml",
+    resource_files = glob(["res/**"]),
+)
```

**Comment by meisterT** [comment]
See also #11695

**Comment by stoyicker** [comment]
With the updated documentation and Bazel 3.4.1, this now works.
