### ISSUE TITLE
Skylark aspects can give rise to IllegalStateException

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1176]
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/SkylarkProviders.java#L85

This line throws when two aspects provide the same provider, and the set of providers provided is controllable form Skylark. We also raise the same exception when merging native aspects, which can also be a problem (I'm not sure if we can create native providers from Skylark)

**Comment by paladine** [comment]
This is also affecting Android builds that use the built-in android_sdk rules, aka //external:android/appcompat_v4, //external:android:palette_v7, etc.

I am unable to build my Android project.

java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:@androidsdk//:mediarouter_v7#JackAspect d7c66fabf0de386cca5fd59b2d2d4dab d7c66fabf0de386cca5fd59b2d2d4dab {}' (requested by nodes 'ASPECT://external:android/mediarouter_v7#JackAspect d7c66fabf0de386cca5fd59b2d2d4dab d7c66fabf0de386cca5fd59b2d2d4dab {}')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: JackAspect aspect on android_library attribute :android_sdk produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:682)
	at com.google.devtools.build.lib.rules.android.AndroidSdkProvider.fromRuleContext(AndroidSdkProvider.java:99)
	at com.google.devtools.build.lib.rules.android.AndroidSdkProvider.verifyPresence(AndroidSdkProvider.java:110)
	at com.google.devtools.build.lib.rules.android.JackAspect.create(JackAspect.java:66)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:329)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:318)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:243)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
	... 4 more

**Comment by dslomov** [comment]
This has actually been fixed a while ago, there is an error message instead of an assertion
