### ISSUE TITLE
BES upload fails on build without the bytes + broken builds

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#11764]
### Description of the problem:

When running a build as follows:
1. Using remote execution
2. With build without the bytes flag (`--remote_download_minimal`)
3. With BES backend defined (`--bes_backend`)
4. When one of the target fails to build (compilation error , for instance)

The build finishes with error message:
```
ERROR: The Build Event Protocol local file upload failed: /root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/k8-fastbuild/bin/src/main/com/example/app/app_runner.jar (No such file or directory)
```
And the BES upload fails.
Instead of seeing broken build - we see Tool failure in the BES backend.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created [minimal repo for example](https://github.com/or-shachar/bazel-sample-repo).
To see the issue run the build (on linux, or using the docker image `l.gcr.io/google/bazel:2.2.0`)
```bash
bazel --bazelrc=.bazelrc.remote test -k //... \
    --config=remote --config=results \
    --remote_instance_name=<your-project> \
    --project_id=<gcp-project-id>
```

### What operating system are you running Bazel on?

Linux (we're using bazel image `l.gcr.io/google/bazel:2.2.0`)

### What's the output of `bazel info release`?

We've been using bazel `2.1.0` for while and started seeing the issue when we tried to upgrade to `3.3.0`.
Using bazelisk I ran the build on several releases and it seem like the first version that fails like this is `2.2.0`.

###  Have you found anything relevant by searching the web?
Looking in 2.2.0 release notes I see 
> _Actions with `parse` on the critical path should no longer finish in the future_

which might be related. I haven't tracked down the specific commit for this.

### Any other information, logs, or outputs that you want to share?
here's the last few lines of the `java.log`:
```
200714 08:39:13.491:WT 41 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.waitForUploads] Failed to upload files referenced by build event: java.io.FileNotFoundException: /root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/k8-fastbuild/bin/src/main/com/example/app/app_runner.jar (No such file or directory)
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/k8-fastbuild/bin/src/main/com/example/app/app_runner.jar (No such file or directory)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:487)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.waitForUploads(BuildEventServiceUploader.java:620)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents(BuildEventServiceUploader.java:412)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.run(BuildEventServiceUploader.java:286)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/k8-fastbuild/bin/src/main/com/example/app/app_runner.jar (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:185)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:176)
	at com.google.devtools.build.lib.unix.UnixFileSystem.getFileSize(UnixFileSystem.java:363)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:648)
	at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:60)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:126)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.lambda$upload$3(ByteStreamBuildEventArtifactUploader.java:219)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
200714 08:39:13.496:I 41 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Publish interrupt. Showing up to 30 items from queues: ack_queue_size: 7, ack_queue: [SendRegularBuildEventCommand{seq_num=87} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@6f1e94e2], SendRegularBuildEventCommand{seq_num=88} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@77a26330], SendRegularBuildEventCommand{seq_num=89} - [ActionExecutedEvent{exception=com.google.devtools.build.lib.actions.ActionExecutionException: scala //src/main/com/example/core:core failed (Exit 1), timing=AFTER_EXECUTION, stdout=/root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/_tmp/actions/stdout-579, stderr=null, action=action 'scala //src/main/com/example/core:core' (Scalac[[File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/main/com/example/api/api-ijar.jar, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/maven/v1/https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/maven/v1/https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.13.3/log4j-core-2.13.3.jar, File:[/root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577[source]]external/io_bazel_rules_scala_scala_library/scala-library-2.11.12.jar, File:[/root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577[source]]external/io_bazel_rules_scala_scala_reflect/scala-reflect-2.11.12.jar, File:[/workspace2[source]]src/main/com/example/core/Logger.scala, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/main/com/example/core/core_MANIFEST.MF, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/main/com/example/core/core_scalac_worker_input, File:[[<execution_root>]bazel-out/k8-fastbuild/internal]_middlemen/external_Sio_Ubazel_Urules_Uscala_Ssrc_Sjava_Sio_Sbazel_Srulesscala_Sscalac_Sscalac-runfiles, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac.jar, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac] -> [File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/main/com/example/core/core.jar, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/main/com/example/core/core.statsfile]])}], SendRegularBuildEventCommand{seq_num=90} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@58bb75e5], SendRegularBuildEventCommand{seq_num=91} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@7541b08], SendRegularBuildEventCommand{seq_num=92} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@5ffad609], SendRegularBuildEventCommand{seq_num=93} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@5323c024]], event_queue_size: 11, event_queue: [SendRegularBuildEventCommand{seq_num=94} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@34ca1e95], SendRegularBuildEventCommand{seq_num=95} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@54acdf09], SendRegularBuildEventCommand{seq_num=96} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@7b6e3764], SendRegularBuildEventCommand{seq_num=97} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@3601eacd], SendRegularBuildEventCommand{seq_num=98} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@3c513b75], SendRegularBuildEventCommand{seq_num=99} - [com.google.devtools.build.lib.buildtool.buildevent.TestingCompleteEvent@5bd5093e], SendRegularBuildEventCommand{seq_num=100} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@283e8968], SendRegularBuildEventCommand{seq_num=101} - [com.google.devtools.build.lib.metrics.BuildMetricsEvent@2455cfb5], SendRegularBuildEventCommand{seq_num=102} - [com.google.devtools.build.lib.buildeventstream.BuildToolLogs@78fd4a42], SendRegularBuildEventCommand{seq_num=103} - [com.google.devtools.build.lib.buildeventstream.LastBuildEvent@22614e1c], SendLastBuildEventCommand{seq_num=104}]
200714 08:39:15.044:X 41 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.logAndExitAbruptly] The Build Event Protocol local file upload failed: /root/.cache/bazel/_bazel_root/dce55d95a5c7d41723d018413f8a7577/execroot/my_bazel_example/bazel-out/k8-fastbuild/bin/src/main/com/example/app/app_runner.jar (No such file or directory)
200714 08:39:15.049:I 18 [com.google.devtools.build.lib.profiler.AutoProfiler$LoggingElapsedTimeReceiver.log] Spent 1601 milliseconds doing waiting for BES close
200714 08:39:15.065:I 18 [com.google.devtools.build.lib.runtime.CacheFileDigestsModule.logStats] Accumulated cache stats after command: hit count=2, miss count=794, hit rate=0.002512562814070352, eviction count=0
200714 08:39:15.065:I 18 [com.google.devtools.build.lib.runtime.CacheFileDigestsModule.logStats] Cache stats for finished command: hit count=2, miss count=794, hit rate=0.002512562814070352, eviction count=0
```
(This is from running with bazel 2.2.0)

cc: @ericfelly

**Comment by ericfelly** [comment]
I believe I understand what's going on here.

We have a feature to report successful output groups of top-level targets even if other output groups in the same top-level target failed. This is relatively new. We have a bug here where we're not appropriately applying path transformation to the "remote" filesystem related to --experimental_remote_download_outputs=minimal. When we go to upload the properly built output file, we're improperly consulting the _local_ filesystem where it will not be present.

A similar issue occurs in Blaze, but we're more tolerant to missing files in that case. Here, we fail to upload the file, which fails the BES upload, and that triggers a follow-on threadpool crash.

**Comment by ericfelly** [comment]
@michaeledgar

**Comment by or-shachar** [comment]
@ericfelly Please kindly update here if you have any ETA for this...

we would really love to move to the latest release of Bazel but we love the build without the bytes flag (90% improvement in build times) and we just won't give it up :-)

**Comment by ericfelly** [comment]
I understand! Mike is going to provide an update shortly. My assessment is that I don't think it will take very long to submit a fix to the depot for this.

**Comment by michaeledgar** [comment]
Hi Or! Thanks for making this issue so easy to reproduce - I've done so locally. I haven't yet dug into the code but once I have a handle on the issue will offer an estimate for landing the fix.

**Comment by michaeledgar** [comment]
I've [identified a fix](https://bazel-review.googlesource.com/c/bazel/+/137695) to properly resolve these artifact paths in failed builds, and confirmed that it produces the expected output for your example repo.

I'd like to introduce a regression test before submitting so this may not land until early next week.

**Comment by or-shachar** [comment]
Amazing! thanks for the update!

**Comment by or-shachar** [comment]
Thanks for issuing a fix so quickly!

Just making sure that this is not left forgotten :) 🌹

**Comment by michaeledgar** [comment]
Haven't forgotten - had an impromptu vacation last week and am picking this back up now.
