### ISSUE TITLE
Bazel CI: rules_nodejs and rules_webtesting are broken downstream

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#11813]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1572

```
Caused by: java.lang.NullPointerException
--
  | at com.google.devtools.build.lib.util.Fingerprint.addBytes(Fingerprint.java:145)
  | at com.google.devtools.build.lib.skyframe.TreeArtifactValue.create(TreeArtifactValue.java:122)
  | at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.constructTreeArtifactValueFromFilesystem(ActionMetadataHandler.java:353)
  | at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getTreeArtifactValue(ActionMetadataHandler.java:302)
  | at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getMetadata(ActionMetadataHandler.java:251)
```

Culprit: 5bb9514
https://buildkite.com/bazel/culprit-finder/builds/416

**Comment by comius** [comment]
cc @meteorcloudy

**Comment by justinhorvitz** [comment]
Culprit was rolled back.

**Comment by justinhorvitz** [comment]
Follow up: culprit is a tree artifact containing a symlink to a directory. Adding test coverage shortly.
