### ISSUE TITLE
Got DirectoryNotEmptyException When Execution Build Task

### ISSUE THREAD

**Issue by lizhiguo0811** [bazelbuild/bazel#11956]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
When following the website's Getting Start Section with Google Code, After Execute build task, I got the following errors:
 `processing Android resources for //mediarecorder/java/com/example/android/mediarecorder:mediarecorder failed (Exit 1)
Exception in thread "main" java.nio.file.DirectoryNotEmptyException: C:\Users\<username>\AppData\Local\Temp\android_resources_tmp13118465052724916687\linked`

And I try to remove the tip directory throgh the current CMD but successful. I've tried another times, but got the same results.

### Feature requests: what underlying problem are you trying to solve with this feature?

None 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

When install Bazel in newly win10 operation system.

### What operating system are you running Bazel on?

Win10

### What's the output of `bazel info release`?

release 3.4.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/googlecodelabs/bazel-android-intro
dbac9036550baa02dcf23233d9ae87cfd3eba8ff
dbac9036550baa02dcf23233d9ae87cfd3eba8ff

###  Have you found anything relevant by searching the web?

I've searched none about my question.

### Any other information, logs, or outputs that you want to share?

None

**Comment by pmuetschard** [comment]
I'm getting this exception all the time on our Kokoro build machines. It appears to affect Windows Server, i.e. I don't see it on my Windows 10 workstation. I can reproduce it by creating a Windows Server VM on GCP. I get the error every time I run the build - even if I keep invoking the build, it never succeeds, so not a "random timing" issue. However, of course, if I check the directory right after the build fails, it is indeed empty, so some kind of race during the deletion.

I've tried to build my own bazel and add some diagnostics to `ScopedTemporaryDirectory.java`, however, changing that file had absolutely no effect on building bazel. I couldn't find any documentation anywhere on how to build and use your own Android bazel tools. Sad.

Seeing how this is just an error during cleanup of temporary files, at the very least it shouldn't fail the build.

This is blocking us from upgrading from bazel 2.0 to the LTS release.

```
Exception in thread "main" java.nio.file.DirectoryNotEmptyException: T:\tmp\android_resources_tmp10185824535454917878\linked
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:271)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1141)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.postVisitDirectory(ScopedTemporaryDirectory.java:94)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.postVisitDirectory(ScopedTemporaryDirectory.java:36)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.close(ScopedTemporaryDirectory.java:100)
	at com.google.devtools.build.android.Aapt2ResourcePackagingAction.main(Aapt2ResourcePackagingAction.java:498)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$8.call(ResourceProcessorBusyBox.java:111)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
```

**Comment by ahumesky** [comment]
The reason that changing ScopedTemporaryDirectory.java and rerunning the build didn't rebuild the tool is that these tools are prebuilt and downloaded to save on bazel's binary size. To see changes here you build the tools archive and tell bazel to use that, e.g.:

```
~/bazel-src$ bazel build //tools/android/runtime_deps:android_tools.tar.gz
~/bazel-src$ tar -xvf bazel-bin/tools/android/runtime_deps/android_tools.tar.gz -C /tmp/android_tools
~/bazel-src$ cd ~/your-project
~/your-project$ bazel build --override_repository=android_tools=/tmp/android_tools //.......
```
