### ISSUE TITLE
Duplicate key encountered while applying Starlark transition

### ISSUE THREAD

**Issue by iKevinY** [bazelbuild/bazel#11969]
We observed a build failure for google/asylo@b7d0a80a83b106965b5e11f155cdd4347276a109 on Bazel version bazelbuild/bazel@7a11752a8ae7689d2bd482e23d466cb44a3261a1:

```
ERROR: /home/kbuilder/.cache/bazel/_bazel_kbuilder/e99e07f24ebd301f8e219cdfec3646b6/external/com_google_asylo_backend_provider/transitions.bzl:59:5: Starlark transition interrupted during attribute transition implementation
ERROR: Errors encountered while applying Starlark transition
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//asylo/platform/primitives/test:dlopen_proxy_primitives_dlopen_test, config=BuildConfigurationValue.Key[6cf3d438fd70c68bf272523ce41e60188d0973839098caa5304a8b8c32e73291]}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: @com_google_asylo_backend_provider//:backend=@com_google_asylo_backend_provider//:none and @com_google_asylo_backend_provider//:backend=@com_google_asylo_backend_provider//:none
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkTransition.getDefaultValues(StarlarkTransition.java:423)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.applyTransition(ConfigurationResolver.java:422)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.resolveGenericTransition(ConfigurationResolver.java:256)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.resolveConfiguration(ConfigurationResolver.java:201)
	at com.google.devtools.build.lib.analysis.config.ConfigurationResolver.resolveConfigurations(ConfigurationResolver.java:169)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:662)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:309)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
```

As far as I'm aware, we haven't seen this issue before, and also haven't made any changes to Asylo's build system that would've caused this. /cc @deeglaze

**Comment by deeglaze** [comment]
Tagging @gregestren and @juliexxia

**Comment by KeithMoyer** [comment]
For extra context, it was passing the day before on Bazel version https://github.com/bazelbuild/bazel/commit/460ab684b4203cf87663038e67db352775adfdde .

So, probably one of the following Bazel commits:

* 7a11752a8a Don't run DexFileMergerTest as it is not supported for all r8.jar's
* 9993785fa0 Allow dot ('.') in workspace names.
* b9706675a7 Stop needlessly parsing WORKSPACE files from external repositories.
* 47943beac5 Fix log printing to correctly associate comp steps and numPackages>
* a7a0d48fbe Make no-op starlark transition not affect the output directory.
* d483d6f628 Support deterministic mode when using a version of libtool that su>
* 05f137a625 Remove obsolete references to JavaBuilder canaries
* b47f2287d9 Add --flag_alias flag. Currently no-op.
* f82a44b47e Check for errors from config conditions before checking for missing
* eadadbd3c4 Handle transition exceptions inside AspectFunction

**Comment by juliexxia** [comment]
Oop, pretty sure its from a7a0d48 Make no-op starlark transition not affect the output directory. Let me take a look.

**Comment by juliexxia** [comment]
I've mailed out a fix for it. Will hopefully get submitted before the end of the day. Apologies!

**Comment by iKevinY** [comment]
Thanks for the speedy fix @juliexxia!

**Comment by juliexxia** [comment]
Welcome!
