### ISSUE TITLE
Inlined jars in bazel_tools jar conflicting with our libraries

### ISSUE THREAD

**Issue by helenaut** [bazelbuild/bazel#1203]
Hello!

We have some conflicts with inlined jars in bazel_tools.jar conflicting with the jars that we're using. For example, we depend on the version of Guice that includes AOP support, but the inlined version in bazel_tools.jar is listed first on the classpath.

This is probably the same root cause as #1150, but presents with a different error.

Example error:

```
java.lang.NoSuchMethodError: redfin.util.statsd.StatsdModule.bindInterceptor(Lcom/google/inject/matcher/Matcher;Lcom/google/inject/matcher/Matcher;[Lorg/aopalliance/intercept/MethodInterceptor;)V
	at redfin.util.statsd.StatsdModule.configure(StatsdModule.java:359)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at redfin.stingray.accountManager.FacebookLoginControllerTest.<init>
... <snip> ...
com.google.testing.junit.runner.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:103)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:90)
```

**Comment by ulfjack** [comment]
Damien says that Guice is being removed from our test runner, so this specific issue should go away.

**Comment by helenaut** [comment]
Thanks for the update

**Comment by helenaut** [comment]
Hello! Was Guice removed from the test runner in 0.3.0?

**Comment by ulfjack** [comment]
The checked-in code at head uses dagger, not guice any more, but I'm not sure if that made it into 0.3.0.

**Comment by ulfjack** [comment]
Uhm, unfortunately, I just looked through the BUILD files and there's still a guice dependency. Probably someone forgot to remove that. :-(

**Comment by ulfjack** [comment]
I'll send a fix.

**Comment by ulfjack** [comment]
This should be fixed at head, and in the next release.
