### ISSUE TITLE
bazel-bench is stale

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#12076]
The most recent result on Mac is from Aug 20:
![image](https://user-images.githubusercontent.com/418721/92694753-cade1100-f347-11ea-874f-6f3909e496c4.png)

cc @joeleba

**Comment by meisterT** [comment]
There's a bunch of errors in the log, starting with this one:
```
Collecting smmap>=3.0.1
--
  | Downloading smmap-3.0.4-py2.py3-none-any.whl (25 kB)
  | Building wheels for collected packages: absl-py, googleapis-common-protos, numpy, psutil, scipy, PyYAML
  | Building wheel for absl-py (setup.py) ... done
  | Created wheel for absl-py: filename=absl_py-0.7.0-py3-none-any.whl size=113528 sha256=ed38d3f130f28c9726f2f568bd5b94f12c97e9754fc922ec59f560ac562d092e
  | Stored in directory: /Users/buildkite/Library/Caches/pip/wheels/64/ff/e3/634dc88c616c358232ed4c6a8d2f74f18b7aa86c0c8f3cfa06
  | Building wheel for googleapis-common-protos (setup.py) ... done
  | Created wheel for googleapis-common-protos: filename=googleapis_common_protos-1.6.0-py3-none-any.whl size=77575 sha256=cc03eb0a4c0aa36add4052a21bdb40a2f0f190367ec9e988840284d35b5b8536
  | Stored in directory: /Users/buildkite/Library/Caches/pip/wheels/b2/12/ab/c41ac6acb73f848aae7b74bd7c0c782f16330121362041147c
  | Building wheel for numpy (setup.py) ... done
  | Created wheel for numpy: filename=numpy-1.16.6-cp38-cp38-macosx_10_15_x86_64.whl size=3543194 sha256=036924160503d706123dc802020ae9153a1a28cfdf58211bac388fced4e72e40
  | Stored in directory: /Users/buildkite/Library/Caches/pip/wheels/22/6f/a6/069db0c95f9bb6b73e07da014891c58460fef1eb84f49576f0
  | Building wheel for psutil (setup.py) ... done
  | Created wheel for psutil: filename=psutil-5.6.6-cp38-cp38-macosx_10_15_x86_64.whl size=226807 sha256=03d5e93e26a17d7d6a4907f9a9e5f4a1611e9e66d513bdaf22ab9eb2e6d1d7aa
  | Stored in directory: /Users/buildkite/Library/Caches/pip/wheels/79/67/93/91114b71e0965edb6233d607d82bb5de75ad02e3d9d469ba17
  | Building wheel for scipy (setup.py) ... error
  | ERROR: Command errored out with exit status 1:
  | command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-13ej5as_/scipy/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-13ej5as_/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-e4gdppjd
  | cwd: /private/tmp/pip-install-13ej5as_/scipy/
  | Complete output (9 lines):
  | /private/tmp/pip-install-13ej5as_/scipy/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  | import imp
  | Traceback (most recent call last):
  | File "<string>", line 1, in <module>
  | File "/private/tmp/pip-install-13ej5as_/scipy/setup.py", line 492, in <module>
  | setup_package()
  | File "/private/tmp/pip-install-13ej5as_/scipy/setup.py", line 468, in setup_package
  | from numpy.distutils.core import setup
  | ModuleNotFoundError: No module named 'numpy'
  | ----------------------------------------
  | ERROR: Failed building wheel for scipy
  | Running setup.py clean for scipy
  | ERROR: Command errored out with exit status 1:
  | command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-13ej5as_/scipy/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-13ej5as_/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  | cwd: /private/tmp/pip-install-13ej5as_/scipy
  | Complete output (11 lines):
  | /private/tmp/pip-install-13ej5as_/scipy/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  | import imp
  |  
  | `setup.py clean` is not supported, use one of the following instead:
  |  
  | - `git clean -xdf` (cleans all files)
  | - `git clean -Xdf` (cleans all versioned files, doesn't touch
  | files that aren't checked into the git repo)
  |  
  | Add `--force` to your command to use it anyway if you must (unsupported).
  |  
  | ----------------------------------------
  | ERROR: Failed cleaning build dir for scipy
```

Example log: https://buildkite.com/bazel-trusted/bazel-bench-nightly/builds/476#9c188b75-20e1-4ab2-89ee-1e0784938452

@philwo did you do any environmental changes to the Macs during that time?

**Comment by meisterT** [comment]
This is still stale, but now with a different error:

```

Traceback (most recent call last):
--
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 666, in <module>
  | app.run(main)
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_7_0/absl/app.py", line 300, in run
  | _run_main(main, args)
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_7_0/absl/app.py", line 251, in _run_main
  | sys.exit(main(argv))
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/__main__/benchmark.py", line 565, in main
  | logger.log('Preparing bazelbuild/bazel repository.')
  | File "/Users/buildkite/builds/bk-trusted-macpro-2/bazel-trusted/bazel-bench-nightly/utils/logger.py", line 34, in log
  | logging.info(_maybe_colorize_text(text, 'info'))
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_7_0/absl/logging/__init__.py", line 335, in info
  | log(INFO, msg, *args, **kwargs)
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_7_0/absl/logging/__init__.py", line 476, in log
  | _absl_logger.log(standard_level, msg, *args, **kwargs)
  | File "/private/var/tmp/_bazel_buildkite/17366bc57044bd561636578e7eefc8d0/execroot/__main__/bazel-out/darwin-fastbuild/bin/benchmark.runfiles/third_party_pypi__absl_py_0_7_0/absl/logging/__init__.py", line 1038, in log
  | super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  | File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1500, in log
  | self._log(level, msg, args, **kwargs)
  | File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1565, in _log
  | fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
  | TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
  | 🚨 Error: The command exited with status 1


```
