### ISSUE TITLE
IncompatibleMergeException in branch coverage for C++ headers

### ISSUE THREAD

**Issue by c-mita** [bazelbuild/bazel#12142]
_This only occurs when C++ branch coverage is enabled._
_Add `-b` to the gcov command line in collect_cc_coverage.sh and rebuild bazel._

An assumption made in commits 3481d5ec and 51ec2228 is that the number of branches recorded in coverage reports for a given line are constant across the reports to be merged from a single bazel invocation. This is not a valid assumption, at least for header files in C++. Functions defined in header files may be compiled several times in different contexts, resulting in slightly different structures that can fail the naive check made in the coverage merge tool.

Suppose the following function exists in a header file `lib.h`:
```
template <typename T>
T foo(T x, T y) {
    T z = y > 0 ? x + y : x - y; // line N
    return z;
}
```
If `foo` is instantiated with `int` or similar, there is a single branch at line N with two paths.
If `foo` is instantiated with a more complicated struct with the required operators, then more branches may be generated by the compiler at the same line.

Since two object files may have instantiated this function differently, it is entirely possible for a coverage run to fail to merge the reports and fail to produce a final coverage.dat file.

A demonstration is provided here:
https://github.com/c-mita/bazel_issues/tree/master/lcov_issues/branch_merge

```
cd lcov_issues
bazel coverage --combined_report=lcov --instrumentation_filter="lib" //branch_merge:foo_test //branch_merge:bar_test //branch_merge:baz_test
```
Error extract:
```
Sep 21, 2020 5:59:16 PM com.google.devtools.coverageoutputgenerator.Main getTracefiles
INFO: Found 3 tracefiles.
Sep 21, 2020 5:59:16 PM com.google.devtools.coverageoutputgenerator.Main parseFilesSequentially
INFO: Parsing file bazel-out/k8-fastbuild/testlogs/branch_merge/bar_test/coverage.dat
Sep 21, 2020 5:59:16 PM com.google.devtools.coverageoutputgenerator.Main parseFilesSequentially
INFO: Parsing file bazel-out/k8-fastbuild/testlogs/branch_merge/foo_test/coverage.dat
Sep 21, 2020 5:59:16 PM com.google.devtools.coverageoutputgenerator.Main parseFilesSequentially
INFO: Parsing file bazel-out/k8-fastbuild/testlogs/branch_merge/baz_test/coverage.dat
Sep 21, 2020 5:59:16 PM com.google.devtools.coverageoutputgenerator.Main main
SEVERE: Unhandled exception on lcov tool: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.IllegalStateException: com.google.devtools.coverageoutputgenerator.IncompatibleMergeException: Different number of branches found at line 7 for branch_merge/lib.h
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.IllegalStateException: com.google.devtools.coverageoutputgenerator.IncompatibleMergeException: Different number of branches found at line 7 for branch_merge/lib.h
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.google.devtools.coverageoutputgenerator.Main.parseFilesInParallel(Main.java:356)
        at com.google.devtools.coverageoutputgenerator.Main.parseFiles(Main.java:321)
        at com.google.devtools.coverageoutputgenerator.Main.runWithArgs(Main.java:82)
        at com.google.devtools.coverageoutputgenerator.Main.main(Main.java:55)
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.IllegalStateException: com.google.devtools.coverageoutputgenerator.IncompatibleMergeException: Different number of branches found at line 7 for branch_merge/lib.h
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        ... 5 more

```

* `lib.h` contains a template function similar to the one described above
* `foo` instantiates the template with `int`
* `bar` instantiates the template with a struct
* `baz` instantiates with template with both `int` and a struct.

The branch information output:
```
$ cat bazel-out/k8-fastbuild/testlogs/branch_merge/foo_test/coverage.dat
SF:branch_merge/lib.h
FN:5,_Z10do_t_thingIiET_S0_i
FNDA:1,_Z10do_t_thingIiET_S0_i
FNF:1
FNH:1
BRDA:7,0,0,1
BRDA:7,0,1,0
BRF:2
BRH:1
DA:5,1
DA:6,1
DA:7,1
DA:8,1
LH:4
LF:4
end_of_record
```
```
$ cat bazel-out/k8-fastbuild/testlogs/branch_merge/bar_test/coverage.dat
SF:branch_merge/lib.h
FN:5,_Z10do_t_thingI5thingET_S1_i
FNDA:1,_Z10do_t_thingI5thingET_S1_i
FNF:1
FNH:1
BRDA:7,0,0,1
BRDA:7,0,1,0
BRDA:7,0,2,1
BRDA:7,0,3,0
BRDA:7,0,4,1
BRDA:7,0,5,0
BRDA:7,0,6,0
BRDA:7,0,7,0
BRDA:7,0,8,1
BRDA:7,0,9,0
BRDA:7,0,10,0
BRDA:7,0,11,0
BRF:12
BRH:4
DA:5,1
DA:6,1
DA:7,1
DA:8,1
LH:4
LF:4
end_of_record
```
```
$ cat bazel-out/k8-fastbuild/testlogs/branch_merge/baz_test/coverage.dat
SF:branch_merge/lib.h
FN:5,_Z10do_t_thingI5thingET_S1_i
FN:5,_Z10do_t_thingIiET_S0_i
FNDA:1,_Z10do_t_thingI5thingET_S1_i
FNDA:1,_Z10do_t_thingIiET_S0_i
FNF:2
FNH:2
BRDA:7,0,0,1
BRDA:7,0,1,0
BRDA:7,0,0,1
BRDA:7,0,1,0
BRDA:7,0,2,1
BRDA:7,0,3,0
BRDA:7,0,4,1
BRDA:7,0,5,0
BRDA:7,0,6,0
BRDA:7,0,7,0
BRDA:7,0,8,1
BRDA:7,0,9,0
BRDA:7,0,10,0
BRDA:7,0,11,0
BRF:14
BRH:5
DA:5,2
DA:6,2
DA:7,2
DA:8,2
LH:4
LF:4
end_of_record
```

**Comment by limdor** [comment]
@c-mita @sgowroji shouldn't this stay opened?
https://github.com/bazelbuild/bazel/commit/67e4aaa46b574c9452c99f1719fbfdec59c6f0e7 was a workaround and I'm not aware of another issue to follow up on that.
If there is could you share it here? Thanks

**Comment by c-mita** [comment]
Honestly, I don't think there is a good solution; inconsistent data cannot be meaningfully merged

Something that might be fixable is the inconsistency in the output when faced with mismatched inputs. We keep the "first" set of branches when there's a mismatch; if the order changes between runs, then we can end up with a different result.

**Comment by limdor** [comment]
I agree, inconsistency data cannot be merged.

Having said that, I understand the solution for this is hard, but choosing the first set does not sound like a final solution to me. I'm not exepert in code coverage in C++ to say how this is resolved in other environments, I don't think this is a Bazel problem but a more generic one.
If you grab the example in the ticket and you apply it to a real life scenario, you can imagine that `baz` is the object file that instantiated the header for testing it with all possible instantiations you might have in the project.
In that case, what the user might want is to grab the set of branches from `baz` but taking the first you are just relying on lack.

One way to mitigate the problem is to use some tool like gcovr to exclude branches generated by the compiler.
https://gcovr.com/en/stable/faq.html#why-does-c-code-have-so-many-uncovered-branches
In the end, I would expect that most of the users when they want to test different branches they care mainly about the branches that are visible in the C++ code.

Maybe a flag where you can choose between taking the first set or throw an exception would be the best? Do you see a way how a user could in practice influence how the first set of branches is choosen?
