### ISSUE TITLE
Fix and enable tests under src/test/java/com/google/devtools/build/lib/buildtool/BUILD

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#12141]
Many rules migrated from Blaze to Bazel in https://github.com/bazelbuild/bazel/commit/5c730b8904a4eb5f539502039fac7b75f04fd0db
Too many are tagged `manual` and being skipped.

**Comment by janakdr** [comment]
@aiuto should team-Core be the owner here? I don't think we're planning to do any work on this.

**Comment by aiuto** [comment]
Note for future triage:
This does  not belong to any team in particular. It is part of the "make the tests public" milestone.

**Comment by jin** [comment]
If there are no owners for this workstream, then it's unlikely that it'll ever get fixed. Either find an owner or close this issue to clean up our backlog of issues without team owners?

**Comment by aiuto** [comment]
I did some investigation today. Most of the tests fail because the Posix jni code is not loading.
It also seems that src/test/java/com/google/devtools/build/lib/unix/BUILD  does not exist to test the jni code.

@janakdr This seems like Core to me, since it is all about file system interface. 
@philwo But, since this is the Bazel interface and not what we use for our source control, perhaps it is Xproduct?

**Comment by michajlo** [comment]
4d6ae2c9c5e3943aff020e43c84f4cf153fda710 is the change that migrated the majority of the tests. If there are unix-jni failures now I'd bet they're from bit rot. The reason cited in 5c730b8904a4eb5f539502039fac7b75f04fd0db (lack of `BuildIntegrationTests`) seems like it'd be the core issue, which would be more consistent with my experience.

**Comment by aiuto** [comment]
Sorry. I should have included the failure.  All of the tests I looked at show the same kind of thing.

`$ bazel test src/test/java/com/google/devtools/build/lib/buildtool:DanglingSymlinkTest`

Logs show
```
.Mar 02, 2021 6:01:28 PM com.google.devtools.build.lib.jni.JniLoader <clinit>
WARNING: Failed to load JNI library
java.lang.UnsatisfiedLinkError: /mnt/d1/home/aiuto/.cache/bazel/_bazel_aiuto/c42451a13f00e0b53b5ffe5391e00b77/sandbox/
linux-sandbox/2/execroot/io_bazel/_tmp/12aabb5d6e46cc93d793ec65cdc5e118/bazel-jni.9210224339703604221/libunix_jni.so:
libstdc++.so.6: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2443)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2499)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2715)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2628)
	at java.base/java.lang.Runtime.load0(Runtime.java:769)
	at java.base/java.lang.System.load(System.java:1840)
	at com.google.devtools.build.lib.jni.JniLoader.loadLibrary(JniLoader.java:106)
	at com.google.devtools.build.lib.jni.JniLoader.<clinit>(JniLoader.java:44)
	at com.google.devtools.build.lib.unix.NativePosixFiles.<clinit>(NativePosixFiles.java:52)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createDirectoryAndParents(UnixFileSystem.java:330)
	at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:559)
	at com.google.devtools.build.lib.buildtool.util.BuildIntegrationTestCase.createFilesAndMocks(BuildIntegrationT
estCase.java:172)
```

**Comment by janakdr** [comment]
@aiuto, I see those same warning lines in passing tests internally, and I'm
pretty sure they're also present in passing tests externally. I think @jmmv
might have made some changes that led to this verbose but harmless warning.
Maybe the real root cause shows up later? Or maybe in this case this
warning is really pointing at something bad?

**Comment by aiuto** [comment]
I believe the warning is actually an error.  The warning is first, but each test errors out with
```
4) testDanglingSymlinks(com.google.devtools.build.lib.buildtool.DanglingSymlinkTest)
java.lang.UnsatisfiedLinkError: 'com.google.devtools.build.lib.unix.ErrnoFileStatus com.google.devtools.build.lib.unix.NativePosixFiles.errnoLstat(java.lang.String)'
```
[dangling_symlink_test.txt](https://github.com/bazelbuild/bazel/files/6071568/dangling_symlink_test.txt)

**Comment by michajlo** [comment]
Setting `JAVA_HOME` to jdk8 the `UnsatisfiedLinkErrors` go away and I get:

```
java.lang.UnsupportedOperationException: TODO
        at com.google.devtools.build.lib.packages.util.BazelMockCcSupport.getRealFilesystemCrosstoolTopPath(BazelMockCcSupport.java:39)
        at com.google.devtools.build.lib.packages.util.MockCcSupport.setupCcToolchainConfig(MockCcSupport.java:219)
        at com.google.devtools.build.lib.packages.util.MockCcSupport.setupCcToolchainConfig(MockCcSupport.java:213)
        at com.google.devtools.build.lib.packages.util.BazelMockCcSupport.setup(BazelMockCcSupport.java:56)
        at com.google.devtools.build.lib.analysis.mock.BazelAnalysisMock.setupMockClient(BazelAnalysisMock.java:366)
        at com.google.devtools.build.lib.analysis.mock.BazelAnalysisMock.setupMockClient(BazelAnalysisMock.java:86)
        at com.google.devtools.build.lib.buildtool.util.BuildIntegrationTestCase.setupMockTools(BuildIntegrationTestCase.java:295)
        at com.google.devtools.build.lib.buildtool.util.BuildIntegrationTestCase.createFilesAndMocks(BuildIntegrationTestCase.java:186)
```

which comes from https://github.com/bazelbuild/bazel/blob/3b60948815400fc24fad89c1375575d689a0b3db/src/test/java/com/google/devtools/build/lib/packages/util/BazelMockCcSupport.java#L39

Which goes back to what appears to be a partial effort to get some tests working back in 20262fdf40be0ba7fc74cb03d552cadebd76af6d

**Comment by michajlo** [comment]
Replacing https://github.com/bazelbuild/bazel/blob/3b60948815400fc24fad89c1375575d689a0b3db/src/test/java/com/google/devtools/build/lib/buildtool/util/BuildIntegrationTestCase.java#L279 with `getJavaIoFilesystem()` gets the tests to the same failing point.

**Comment by aiuto** [comment]
@comius   I know you haven't seen this thread before, but it sounds like a case for refactoring MockCcSupport so it is operable for both Bazel and Blaze.

**Comment by janakdr** [comment]
What component should this be in? XProduct, Bazel, or Server rules seem like the most likely candidate?

**Comment by aiuto** [comment]
Now that we know this is in C++ mocks, let's say server rules.. I will re-assign.

**Comment by comius** [comment]
Failing JNI looks more related to Java than CC. Since I'm working on native libs support, I'll have a closer look.

So if I understand correctly, the problem is running manual tests in //src/test/java/com/google/devtools/build/lib/buildtool?
