### ISSUE TITLE
Builds using Android SDK compat libraries fail immediately

### ISSUE THREAD

**Issue by paladine** [bazelbuild/bazel#1222]
When compiling an Android app with a dependency against built-in targets such as //external:android/palette_v7, compilation immediately fails with the following exception

Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ASPECT:@androidsdk//:palette_v7#JackAspect a141fe61f38490182024c7a7bbd0c958 a141fe61f38490182024c7a7bbd0c958 {}' (requested by nodes 'ASPECT://external:android/palette_v7#JackAspect a141fe61f38490182024c7a7bbd0c958 a141fe61f38490182024c7a7bbd0c958 {}')
INFO: Elapsed time: 2.140s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:@androidsdk//:palette_v7#JackAspect a141fe61f38490182024c7a7bbd0c958 a141fe61f38490182024c7a7bbd0c958 {}' (requested by nodes 'ASPECT://external:android/palette_v7#JackAspect a141fe61f38490182024c7a7bbd0c958 a141fe61f38490182024c7a7bbd0c958 {}')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: JackAspect aspect on android_library attribute :android_sdk produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:683)
	at com.google.devtools.build.lib.rules.android.AndroidSdkProvider.fromRuleContext(AndroidSdkProvider.java:99)
	at com.google.devtools.build.lib.rules.android.AndroidSdkProvider.verifyPresence(AndroidSdkProvider.java:110)
	at com.google.devtools.build.lib.rules.android.JackAspect.create(JackAspect.java:85)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:329)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:317)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:242)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
	... 4 more

**Comment by damienmg** [comment]
For which version of Bazel? Android Tools?

/cc @ahumesky can you further triage this one?

**Comment by paladine** [comment]
Latest version of bazel 08bd44c, with the following android_sdk_repository

android_sdk_repository(
    name="androidsdk",
    path="/var/lib/jenkins/tools/android-sdk",
    api_level=23,
    build_tools_version="23.0.1")

It's been happening for a few days now. I think 0ba2555 was affected.

**Comment by ahumesky** [comment]
@serynth can you take a look at this?

**Comment by serynth** [comment]
A fix for this is in the pipeline and on its way!
