### ISSUE TITLE
serve-docs.sh script broken

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#12245]
There is an error with option parsing, leading to this crash on my system (with updated ruby gems and jekyll):
```
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'blog/_posts/2015-07-08-Java-Configuration.md':
                    undefined method `include?' for nil:NilClass
jekyll 3.8.3 | Error:  undefined method `include?' for nil:NilClass
Traceback (most recent call last):
	35: from /usr/local/bin/jekyll:23:in `<main>'
	34: from /usr/local/bin/jekyll:23:in `load'
	33: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
	32: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	31: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	30: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	29: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	28: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	27: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	26: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `start'
	25: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `each'
	24: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `block in start'
	23: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:36:in `process'
	22: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:65:in `build'
	21: from /usr/lib/ruby/vendor_ruby/jekyll/command.rb:28:in `process_site'
	20: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:71:in `process'
	19: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:191:in `render'
	18: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:462:in `render_docs'
	17: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:462:in `each_value'
	16: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:463:in `block in render_docs'
	15: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:463:in `each'
	14: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	13: from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:479:in `render_regenerated'
	12: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:62:in `run'
	11: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:83:in `render_document'
	10: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:99:in `convert'
	 9: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:99:in `reduce'
	 8: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:99:in `each'
	 7: from /usr/lib/ruby/vendor_ruby/jekyll/renderer.rb:101:in `block in convert'
	 6: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/converters/markdown.rb:77:in `convert'
	 5: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/converters/markdown/kramdown_parser.rb:39:in `convert'
	 4: from /var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/converters/markdown/kramdown_parser.rb:39:in `new'
	 3: from /usr/lib/ruby/vendor_ruby/kramdown/document.rb:102:in `initialize'
	 2: from /usr/lib/ruby/vendor_ruby/kramdown/parser/base.rb:68:in `parse'
	 1: from /usr/lib/ruby/vendor_ruby/kramdown/parser/base.rb:68:in `new'
/var/lib/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/parser/gfm.rb:23:in `initialize': undefined method `include?' for nil:NilClass (NoMethodError)
```

**Comment by jin** [comment]
I noticed that you are using Jekyll 3.8.3, but the site infra is pinned to Jekyll 3.8.6: https://github.com/bazelbuild/bazel/blob/master/scripts/docs/Gemfile a 

Could you try using 3.8.6?

**Comment by jin** [comment]
For some reason, your stacktrace says that Jekyll 3.8.7 is being used: 

```
/var/lib/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll ...
```

**Comment by katre** [comment]
This is what I just did (I have no idea how ruby gems work):
```
jcater@jcater:~/repos/bazel/scripts/docs:master$ sudo gem install -g  
Using public_suffix (4.0.6)
Using addressable (2.7.0)
Using colorator (1.1.0)
Using eventmachine (1.2.7)
Using http_parser.rb (0.6.0)
Using em-websocket (0.5.2)
Using concurrent-ruby (1.1.7)
Using i18n (0.9.5)
Using ffi (1.13.1)
Using rb-inotify (0.10.1)
Using rb-fsevent (0.10.4)
Using sass-listen (4.0.0)
Using sass (3.7.4)
Using jekyll-sass-converter (1.5.2)
Using listen (3.2.1)
Using jekyll-watch (2.2.1)
Using kramdown (1.17.0)
Using liquid (4.0.3)
Using mercenary (0.3.6)
Using forwardable-extended (2.6.0)
Using pathutil (0.16.2)
Using rouge (3.23.0)
Using safe_yaml (1.0.5)
Using jekyll (3.8.7)
Using jekyll-paginate (1.1.0)
Using posix-spawn (0.3.15)
Using yajl-ruby (1.2.3)
Using pygments.rb (0.6.3)
Using redcarpet (3.5.0)
Using mini_portile2 (2.4.0)
Using nokogiri (1.10.10)
Using jekyll-toc (0.13.1)
Using jekyll-sitemap (1.4.0)
```

You're right, this is using jekyll 3.8.7, but I don't know how or why.

**Comment by jin** [comment]
I cannot reproduce this (serve-docs.sh worked after installing the gems), although it looks like the default ruby version on gLinux got upgraded to 2.7.0. 

```
$ ./scripts/serve-docs.sh
...

Serving docs.bazel.build site at localhost:12345
./scripts/serve-docs.sh: /usr/local/bin/jekyll: /usr/bin/ruby2.5: bad interpreter: No such file or directory

$ which jekyll
/usr/local/bin/jekyll

$ jekyll -v
-bash: /usr/local/bin/jekyll: /usr/bin/ruby2.5: bad interpreter: No such file or directory

$ sudo !!
sudo gem install -g
[sudo] password for jingwen:
Fetching colorator-1.1.0.gem
Fetching eventmachine-1.2.7.gem
Fetching concurrent-ruby-1.1.7.gem
Fetching public_suffix-4.0.6.gem
Fetching addressable-2.7.0.gem
Fetching http_parser.rb-0.6.0.gem
Fetching em-websocket-0.5.2.gem
Fetching i18n-0.9.5.gem
Fetching ffi-1.13.1.gem
Fetching rb-inotify-0.10.1.gem
Fetching rb-fsevent-0.10.4.gem
Fetching sass-listen-4.0.0.gem
Fetching sass-3.7.4.gem
Fetching jekyll-sass-converter-1.5.2.gem
Fetching listen-3.2.1.gem
Fetching jekyll-watch-2.2.1.gem
Fetching kramdown-1.17.0.gem
Fetching liquid-4.0.3.gem
Fetching mercenary-0.3.6.gem
Fetching forwardable-extended-2.6.0.gem
Fetching pathutil-0.16.2.gem
Fetching rouge-3.23.0.gem
Fetching jekyll-3.8.7.gem
Fetching jekyll-paginate-1.1.0.gem
Fetching posix-spawn-0.3.15.gem
Fetching yajl-ruby-1.2.3.gem
Fetching pygments.rb-0.6.3.gem
Fetching redcarpet-3.5.0.gem
Fetching mini_portile2-2.4.0.gem
Fetching nokogiri-1.10.10.gem
Fetching jekyll-toc-0.13.1.gem
Fetching jekyll-sitemap-1.4.0.gem
Installing public_suffix (4.0.6)
Installing addressable (2.7.0)
Installing colorator (1.1.0)
Installing eventmachine (1.2.7)
Building native extensions. This could take a while...
Installing http_parser.rb (0.6.0)
Building native extensions. This could take a while...
Installing em-websocket (0.5.2)
Installing concurrent-ruby (1.1.7)
Installing i18n (0.9.5)
Installing ffi (1.13.1)
Building native extensions. This could take a while...
Installing rb-inotify (0.10.1)
Installing rb-fsevent (0.10.4)
Installing sass-listen (4.0.0)
Installing sass (3.7.4)

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Installing jekyll-sass-converter (1.5.2)
Installing listen (3.2.1)
Installing jekyll-watch (2.2.1)
Installing kramdown (1.17.0)
Installing liquid (4.0.3)
Installing mercenary (0.3.6)
Installing forwardable-extended (2.6.0)
Installing pathutil (0.16.2)
Installing rouge (3.23.0)
Using safe_yaml (1.0.5)
Installing jekyll (3.8.7)
Installing jekyll-paginate (1.1.0)
Installing posix-spawn (0.3.15)
Building native extensions. This could take a while...
Installing yajl-ruby (1.2.3)
Building native extensions. This could take a while...
Installing pygments.rb (0.6.3)
Installing redcarpet (3.5.0)
Building native extensions. This could take a while...
Installing mini_portile2 (2.4.0)
Installing nokogiri (1.10.10)
Building native extensions. This could take a while...
Installing jekyll-toc (0.13.1)
Installing jekyll-sitemap (1.4.0)

$ ./serve-docs.sh
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True
WARNING: Download from https://mirror.bazel.build/github.com/grpc/grpc/archive/v1.31.1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //site:jekyll-tree.tar (1 packages loaded, 8 targets configured).
INFO: Found 1 target...
Target //site:jekyll-tree.tar up-to-date:
  bazel-bin/site/jekyll-tree.tar
INFO: Elapsed time: 0.723s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/392345bbd6222a5a401120338f0f67da/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True
WARNING: Download from https://mirror.bazel.build/github.com/grpc/grpc/archive/v1.31.1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Serving docs.bazel.build site at localhost:12345
Type q to quit, r to rebuild docs and restart jekyll

$ which jekyll
/usr/local/bin/jekyll
```

Do you maybe have a different `jekyll` version on your PATH?

**Comment by katre** [comment]
```
jcater@jcater:~/repos/bazel/scripts/docs:master$ which jekyll
/usr/local/bin/jekyll
jcater@jcater:~/repos/bazel/scripts/docs:master$ jekyll -v
/var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
jekyll 3.8.3
```

**Comment by jin** [comment]
Did you install `jekyll` through `apt-get`? If so, could you remove it from `apt`?

**Comment by katre** [comment]
I just removed half-a-dozen packages via apt (including jekyll and several ruby libraries), re-installed through "gem", and now "serve-docs.sh" seems to work.

Closing this (and also #12246), but this is a real mess to deal with as someone who is not a ruby expert.
