### ISSUE TITLE
Bazel CI: Bazel is broken with itself in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#12287]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1704
Tests failing with
```
1) testIdeInfoProviderOutsideJavaRoot(com.google.devtools.build.lib.rules.android.AndroidLibraryTest)
java.lang.RuntimeException: Couldn't read rules_cc file from cc/BUILD
	at com.google.devtools.build.lib.packages.util.MockCcSupport.setupRulesCc(MockCcSupport.java:241)
	at com.google.devtools.build.lib.packages.util.BazelMockCcSupport.setup(BazelMockCcSupport.java:55)
	at com.google.devtools.build.lib.analysis.mock.BazelAnalysisMock.setupMockClient(BazelAnalysisMock.java:322)
	at com.google.devtools.build.lib.analysis.mock.BazelAnalysisMock.setupMockClient(BazelAnalysisMock.java:100)
	at com.google.devtools.build.lib.analysis.util.BuildViewTestCase.initializeMockClient(BuildViewTestCase.java:369)
	at com.google.devtools.build.lib.analysis.util.BuildViewTestCase.initializeSkyframeExecutor(BuildViewTestCase.java:267)
	at com.google.devtools.build.lib.analysis.util.BuildViewTestCase.initializeSkyframeExecutor(BuildViewTestCase.java:235)
	... 27 trimmed
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:220)
	at com.google.devtools.build.lib.packages.util.ResourceLoader.readFromResources(ResourceLoader.java:31)
	at com.google.devtools.build.lib.packages.util.MockCcSupport.setupRulesCc(MockCcSupport.java:239)
	... 34 more
```
Culprit finder: https://buildkite.com/bazel/culprit-finder/builds/591
Culprit: ecb7bd2c640989d88decfd2771e26b7e24398640

**Comment by meteorcloudy** [comment]
Fixed by the rollback.
