### ISSUE TITLE
JNI error: Failed to load JNI library

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#12375]
### Description of the problem / feature request:

While debugging some weirdness around `//src/test/bazel/remote:remote_execution_test`, I am seeing this in the test logs:
```
201028 15:32:55.513:WT 1 [com.google.devtools.build.lib.jni.JniLoader.<clinit>] Failed to load JNI library
java.lang.UnsatisfiedLinkError: /usr/local/google/home/twerth/.cache/bazel/_bazel_twerth/f01bc937da326f5bb0feb15c854c110c/sandbox/linux-sandbox/2355/execroot/io_bazel/_tmp/e29069609bc298cb3b1996e685786dd3/bazel-jni.4974307323357703982/libunix_jni.so: libstdc++.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2714)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at com.google.devtools.build.lib.jni.JniLoader.loadLibrary(JniLoader.java:106)
        at com.google.devtools.build.lib.jni.JniLoader.<clinit>(JniLoader.java:44)
        at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:24)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:51)
        at com.google.devtools.build.remote.worker.RemoteWorker.createPidFile(RemoteWorker.java:197)
        at com.google.devtools.build.remote.worker.RemoteWorker.main(RemoteWorker.java:287)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int com.google.devtools.build.lib.unix.ProcessUtils.getpid()'
        at com.google.devtools.build.lib.unix.ProcessUtils.getpid(Native Method)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:51)
        at com.google.devtools.build.remote.worker.RemoteWorker.createPidFile(RemoteWorker.java:197)
        at com.google.devtools.build.remote.worker.RemoteWorker.main(RemoteWorker.java:287)
```

I believe this is unrelated to the test itself and may point to a bigger, hidden problem.

**Comment by meisterT** [comment]
cc @alandonovan who reviewed recent JNI changes by Julio

**Comment by meisterT** [comment]
Ah, with
`USE_BAZEL_VERSION=last_green bazelisk test --test_arg=test_fail //src/test/shell/bazel/remote:remote_execution_test`
this is gone, so probably can be ignored / deduplicated.

**Comment by oquenchil** [comment]
Installing openjdk-8 and then bazel clean --expunge should get rid of this error.

**Comment by meisterT** [comment]
But why? We ship Bazel with an embedded JVM so you don't have to install it yourself just to run the server. Do we need to include more files there?

**Comment by meisterT** [comment]
I already have openjdk-8 installed, this doesn't help for me.

**Comment by coeuvre** [comment]
@meteorcloudy Yun, is this related to what you have fixed recently?

**Comment by meteorcloudy** [comment]
Nope, I fixed https://github.com/bazelbuild/bazel/issues/12376 and https://github.com/bazelbuild/bazel/issues/12377, it doesn't seem to be related to this issue.

**Comment by meteorcloudy** [comment]
@meisterT This test isn't failing on CI, it looks like the failure may be related to your local environment?

**Comment by meisterT** [comment]
It's not failing, I just saw that in the logs. But it seems to be triggered by my local environment. Closing.
