### ISSUE TITLE
type 'cc_common' has no method create_linker_input()

### ISSUE THREAD

**Issue by zengyuxing007** [bazelbuild/bazel#12414]
bazel version: 1.1.0

error message: 

```shell

ERROR: /home/yuzeng.zyx/Work/configserver-cpp-sdk/bazel/foreign_cc/BUILD:29:1: in cmake_external rule //bazel/foreign_cc:zlib:
Traceback (most recent call last):
        File "/home/yuzeng.zyx/Work/configserver-cpp-sdk/bazel/foreign_cc/BUILD", line 29
                cmake_external(name = 'zlib')
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cmake.bzl", line 54, in _cmake_external
                cc_external_rule_impl(ctx, <1 more arguments>)
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 209, in cc_external_rule_impl
                _define_out_cc_info(ctx, attrs, <2 more arguments>)
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 657, in _define_out_cc_info
                create_linking_info(ctx, <2 more arguments>)
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 216, in create_linking_info
                cc_common.create_linking_context(<1 more arguments>)
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 217, in cc_common.create_linking_context
                depset(<1 more arguments>)
        File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 218, in depset
                cc_common.create_linker_input(<3 more arguments>)
type 'cc_common' has no method create_linker_input()

```

**Comment by keith** [comment]
1.1.0 is a very old version, you should upgrade bazel or downgrade to a version of rules foreign cc that says it supports that version.

**Comment by philwo** [comment]
Sorry, we cannot do anything about bugs in Bazel 1.1.0. Please comment if you can still reproduce this with the latest Bazel version.

**Comment by jimmysue** [comment]
> bazel version: 1.1.0
> 
> error message:
> 
> ```shell
> ERROR: /home/yuzeng.zyx/Work/configserver-cpp-sdk/bazel/foreign_cc/BUILD:29:1: in cmake_external rule //bazel/foreign_cc:zlib:
> Traceback (most recent call last):
>         File "/home/yuzeng.zyx/Work/configserver-cpp-sdk/bazel/foreign_cc/BUILD", line 29
>                 cmake_external(name = 'zlib')
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cmake.bzl", line 54, in _cmake_external
>                 cc_external_rule_impl(ctx, <1 more arguments>)
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 209, in cc_external_rule_impl
>                 _define_out_cc_info(ctx, attrs, <2 more arguments>)
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 657, in _define_out_cc_info
>                 create_linking_info(ctx, <2 more arguments>)
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 216, in create_linking_info
>                 cc_common.create_linking_context(<1 more arguments>)
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 217, in cc_common.create_linking_context
>                 depset(<1 more arguments>)
>         File "/home/yuzeng.zyx/.cache/bazel/_bazel_yuzeng.zyx/3837811bb881b369b2139b8ac48dcd2a/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 218, in depset
>                 cc_common.create_linker_input(<3 more arguments>)
> type 'cc_common' has no method create_linker_input()
> ```

Have you solved the problem? And how?
