### ISSUE TITLE
rules_closure job on ci.bazel.io is broken @HEAD

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1241]
It looks like a flake related to runfiles.
See http://ci.bazel.io/job/rules_closure/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/101/console

@kchodorow to further triage it because it is not clear if the problem is on our side or on rules_closure side

**Comment by damienmg** [comment]
/cc @jart also might not be bazel related.

The extract:
```
FAIL: //closure/testing/test:noto_fonts_render_as_expected (see /private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/darwin-x86_64/bazel-out/local-fastbuild/testlogs/closure/testing/test/noto_fonts_render_as_expected/test.log)
____From Testing //closure/testing/test:noto_fonts_render_as_expected:
==================== Test output for //closure/testing/test:noto_fonts_render_as_expected:
FILES DO NOT HAVE EQUAL CONTENTS
closure/testing/test/fontdemo-darwin.png 0e48c707ba6f0054b946190eb8666fd60a7ae90a
closure/testing/test/fontdemo-generated.png c43598dc97762731af94a09c83829a77d9020445
================================================================================
FAIL: //closure/library/test:lint (see /private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/darwin-x86_64/bazel-out/local-fastbuild/testlogs/closure/library/test/lint/test.log)
____From Testing //closure/library/test:lint:
==================== Test output for //closure/library/test:lint:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/darwin-x86_64/bazel-out/local-fastbuild/bin/external/closure_linter/gjslint.runfiles/io_bazel_rules_closure/../closure_linter/closure_linter/gjslint.py", line 48, in <module>
    from closure_linter import errorrecord
ImportError: cannot import name errorrecord
================================================================================
FAIL: //closure/testing:lint (see /private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/darwin-x86_64/bazel-out/local-fastbuild/testlogs/closure/testing/lint/test.log)
____From Testing //closure/testing:lint:
==================== Test output for //closure/testing:lint:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/darwin-x86_64/bazel-out/local-fastbuild/bin/external/closure_linter/gjslint.runfiles/io_bazel_rules_closure/../closure_linter/closure_linter/gjslint.py", line 48, in <module>
    from closure_linter import errorrecord
ImportError: cannot import name errorrecord
================================================================================
```

**Comment by damienmg** [comment]
ping @kchodorow @jart I am pushing a new release and this will hit closure_rules.

**Comment by damienmg** [comment]
I finally took more time to look at rules_closure because the fonts breakage looked like a flake on their side and https://github.com/bazelbuild/rules_closure/commit/cc94e421415743d405c87ff5a364b57b6e9b20f7 might be the actual culprit for everything. Moving the bug to rules_closure

**Comment by jart** [comment]
Closure Rules is now green according to Mr. Jenkins.
