### ISSUE TITLE
Docker sandboxing is disabled, because running 'docker info' failed

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel#12429]
### Description of the problem / feature request:

```

ERROR: Docker sandboxing is disabled, because running 'docker info' failed: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
--
  | at com.google.devtools.build.lib.shell.FutureCommandResult.get(FutureCommandResult.java:97)
  | at com.google.devtools.build.lib.shell.Command.execute(Command.java:260)
  | at com.google.devtools.build.lib.sandbox.DockerSandboxedSpawnRunner.isSupported(DockerSandboxedSpawnRunner.java:120)
  | at com.google.devtools.build.lib.sandbox.SandboxModule.setup(SandboxModule.java:314)
  | at com.google.devtools.build.lib.sandbox.SandboxModule.registerSpawnStrategies(SandboxModule.java:151)
  | at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:166)
  | at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:174)
  | at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:405)
  | at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:97)
  | at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:589)
  | at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:235)
  | at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:546)
  | at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:611)
  | at io.grpc.Context$1.run(Context.java:605)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)


```

How can I extract any more information? What did `docker info` return? It works fine on the machine, not sure why bazel doesn't like it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am not sure.

### What operating system are you running Bazel on?

linux amd64 / ubuntu 16

### What's the output of `bazel info release`?

3.7.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Bazelisk, 3.7.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

This is in a buildkite agent, running in kubernetes, with a sidecar for dind. `docker info` works in the agent.

**Comment by prestonvanloon** [comment]
This was a configuration issue on my end where environment variables were ignored, specifically DOCKER_HOST. 

I'll close this issue, but it would have been helpful for more information from `docker info`.
