### ISSUE TITLE
Make a patch execute timeout in http_archive configurable

### ISSUE THREAD

**Issue by danmx** [bazelbuild/bazel#12432]
### Description of the problem / feature request:

My patching/compilation of Python 3.9.0 is timing out because of a [default 600 sec ctx.timeout](https://docs.bazel.build/versions/3.7.0/skylark/lib/repository_ctx.html#execute) ([use of ctx.execute in the code](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/utils.bzl#L159)).

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to be able to provide an overwrite for patch execute timeout. E.g.:

```starlark
http_archive(
    name = "python_interpreter",
    build_file = "//bazel/python:python.BUILD",
    patch_cmds = [
        "mkdir $(pwd)/bazel_install",
        _py_configure,
        "make",
        "make install",
        "ln -s python3 bazel_install/bin/python",
    ],
    patch_timeout = 700,
    sha256 = "9c73e63c99855709b9be0b3cc9e5b072cb60f37311e8c4e50f15576a0bf82854",
    strip_prefix = "Python-3.9.0",
    urls = ["https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz"],
)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to pull and compile Python on a limited resource machine (e.g. use VSCode's Dev Container).

### What operating system are you running Bazel on?

VSCode Dev Container in Docker on Mac

`Linux 7e5a91b3cffb 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 GNU/Linux`

### What's the output of `bazel info release`?

```
bazel-bin: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/execroot/maia/bazel-out/k8-fastbuild/bin
bazel-genfiles: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/execroot/maia/bazel-out/k8-fastbuild/bin
bazel-testlogs: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/execroot/maia/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/command.log
committed-heap-size: 154MB
execution_root: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/execroot/maia
gc-count: 91
gc-time: 13562ms
install_base: /root/.cache/bazel/_bazel_root/install/f1f06b37c54db45d54451bf6dea565c4
java-home: /root/.cache/bazel/_bazel_root/install/f1f06b37c54db45d54451bf6dea565c4/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 3141MB
output_base: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae
output_path: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/execroot/maia/bazel-out
package_path: %workspace%
release: release 3.7.0
repository_cache: /root/.cache/bazel/_bazel_root/cache/repos/v1
server_log: /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/java.log.7e5a91b3cffb.root.log.java.20201107-222755.585
server_pid: 585
used-heap-size: 75MB
workspace: /workspaces/maia
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`release 3.7.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

It's a private repo.

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```console
$ bazel test ...
INFO: Repository python_interpreter instantiated at:
  /workspaces/maia/WORKSPACE:16:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'python_interpreter' used the following cache hits instead of downloading the corresponding file.
 * Hash '9c73e63c99855709b9be0b3cc9e5b072cb60f37311e8c4e50f15576a0bf82854' for https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
If the definition of 'python_interpreter' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'python_interpreter':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "/root/.cache/bazel/_bazel_root/d00e9ab90ee7195ef43aef446128b8ae/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, column 21, in patch
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command make:
Timed out
ERROR: error loading package 'project/tests': Encountered error while reading extension file 'requirements.bzl': no such package '@project_deps//': no such package '@python_interpreter//': Error applying patch command make:
Timed out
INFO: Elapsed time: 803.890s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: project ... (2 packages)
```

**Comment by danmx** [comment]
Mitigated by increasing the `--experimental_scale_timeouts`
