### ISSUE TITLE
Bazel build with non-existent external repository gives bad error message 

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#1247]
This shouldn't raise an unhandled exception, but instead print a good error message to the user.

```
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel test --keep_going @racket_minimal//... --test_output=errors                                                                                                                        (37)
.
Unhandled exception thrown during build; message: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': The repository named 'racket_minimal' could not be resolved rootCauses={REPOSITORY_DIRECTORY:@racket_minimal} cycles=[]>
INFO: Elapsed time: 0.493s
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': The repository named 'racket_minimal' could not be resolved rootCauses={REPOSITORY_DIRECTORY:@racket_minimal} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:159)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:400)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:122)
        at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:424)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:344)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:119)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:104)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:479)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:317)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
        at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:411)
        at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:862)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:644)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

**Comment by aehlig** [comment]
The ``--keep_going`` flag is essential; without, the error is reported correctly.

**Comment by kchodorow** [comment]
Is this still happening?  I get:

```
$ bazel build --keep_going @garbage//:all
ERROR: no such package '@garbage//': error loading package 'external': The repository named 'garbage' could not be resolved
.
ERROR: Skipping '@garbage//:all': while parsing '@garbage//:all': no such package '@garbage//': error loading package 'external': The repository named 'garbage' could not be resolved.
WARNING: Target pattern parsing failed. Continuing anyway.
INFO: Found 0 targets...
ERROR: execution phase successful, but there were errors parsing the target pattern.
INFO: Elapsed time: 0.226s, Critical Path: 0.00s
$
```

which seems reasonable.

**Comment by endobson** [comment]
Yes I can still reproduce at head. The issue is that your test did `@garbage//:all` instead of `@garbage//...`. With the first I get the good error message, with the second I still get the bad one.

```
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel version                                                                                                                                                                             (0)
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=31800)... done.
.
Build label: 0.3.0-2016-06-18 (@ff1332d)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jun 18 19:16:34 2016 (1466277394)
Build timestamp: 1466277394
Build timestamp as int: 1466277394
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel test --keep_going @racket_minimal//... --test_output=errors                                                                                                                         (0)
Unhandled exception thrown during build; message: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': The repository named 'racket_minimal' could not be resolved rootCauses={REPOSITORY_DIRECTORY:@racket_minimal} cycles=[]>
INFO: Elapsed time: 0.528s
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': The repository named 'racket_minimal' could not be resolved rootCauses={REPOSITORY_DIRECTORY:@racket_minimal} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:159)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:400)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:122)
        at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:409)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:160)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:329)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:119)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:104)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:478)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:316)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
        at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:411)
        at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:868)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:650)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel test --keep_going @racket_minimal//:all --test_output=errors                                                                                                                       (37)
.
ERROR: no such package '@racket_minimal//': error loading package 'external': The repository named 'racket_minimal' could not be resolved.
ERROR: Skipping '@racket_minimal//:all': while parsing '@racket_minimal//:all': no such package '@racket_minimal//': error loading package 'external': The repository named 'racket_minimal' could not be resolved.
ERROR: Skipping '@racket_minimal//:all': while parsing '@racket_minimal//:all': no such package '@racket_minimal//': error loading package 'external': The repository named 'racket_minimal' could not be resolved.
WARNING: Target pattern parsing failed. Continuing anyway.
INFO: Found 0 test targets...
ERROR: execution phase successful, but there were errors parsing the target pattern.
INFO: Elapsed time: 2.494s, Critical Path: 0.01s
ERROR: No test targets were found, yet testing was requested.
```

**Comment by dslomov** [comment]
Fixed at HEAD
