### ISSUE TITLE
java.io.IOException: thread interrupted when building

### ISSUE THREAD

**Issue by david-siqi-liu** [bazelbuild/bazel#12471]
### Description of the problem / feature request:

Unable to build `mediapipe`. Same issue posted here:
https://github.com/google/mediapipe/issues/1275

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build

### What operating system are you running Bazel on?

- macOS: Catalina v10.15.7
- xcode-select: v2373
- SDK: 29
- NDK: r18b

### What's the output of `bazel info release`?

release 3.7.0-homebrew

###  Have you found anything relevant by searching the web?

Similar issue: https://github.com/google/mediapipe/issues/1244

### Any other information, logs, or outputs that you want to share?

```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Command: git diff --name-status --no-renames f15da632dec186f2c1d3c780f47086477e2286a9

DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110"
DEBUG: Repository rules_foreign_cc instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:39:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Computing VCS working set...
  .DS_Store (added)
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.gitignore (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  .cache/content_addressable/sha256/213733991310b904b11b053ac224fee2d4e0179e46b52fe7f8735b8831e04dcc/file (added)
  .cache/content_addressable/sha256/3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025/file (added)
  .cache/content_addressable/sha256/43146e6f56cb5218a8caaab6b5d1601a083f1f31c06ff474a4378a7d35be9cfb/file (added)
  .cache/content_addressable/sha256/5f4dabc2ae21e1f537425d58a49cdca1c49ea11db0d6271e2a4b27e9697548eb/file (added)
  .cache/content_addressable/sha256/b1f2ee97e46d8917a66bcb47452fc510d511829556c93b83e06841b9b35261a5/file (added)
  WORKSPACE (modified)
  WORKSPACE-e (added)
  build_android_examples.sh (modified)
  out_dir/helloworld.apk (added)
  setup_android_sdk_and_ndk.sh (modified)
  (and 1 more)

Querying targets building source files...
Command: /usr/local/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going same_pkg_direct_rdeps(//:.DS_Store+//:.cache/content_addressable/sha256/213733991310b904b11b053ac224fee2d4e0179e46b52fe7f8735b8831e04dcc/file+//:.cache/content_addressable/sha256/3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025/file+//:.cache/content_addressable/sha256/43146e6f56cb5218a8caaab6b5d1601a083f1f31c06ff474a4378a7d35be9cfb/file+//:.cache/content_addressable/sha256/5f4dabc2ae21e1f537425d58a49cdca1c49ea11db0d6271e2a4b27e9697548eb/file+//:.cache/content_addressable/sha256/b1f2ee97e46d8917a66bcb47452fc510d511829556c93b83e06841b9b35261a5/file+//:WORKSPACE-e+//:out_dir/helloworld.apk+//third_party:opencv_android.BUILD-e+//:WORKSPACE+//:build_android_examples.sh+//:setup_android_sdk_and_ndk.sh) --

Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/var/folders/hw/7lr6yp7s3g378s_yzlk33f600000gn/T/intellij-bep-a3f18f27-2fa5-4764-a267-52f3b8528471 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/dliu/Library/Application Support/Google/AndroidStudio4.1/plugins/aswb/aspect" --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Analyzing: 76 targets (28 packages loaded, 0 targets configured)
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6"
DEBUG: Repository rules_cc instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:33:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
Analyzing: 76 targets (45 packages loaded, 88 targets configured)
Analyzing: 76 targets (74 packages loaded, 152 targets configured)
Analyzing: 76 targets (86 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (87 packages loaded, 180 targets configured)
Analyzing: 76 targets (124 packages loaded, 1410 targets configured)
Analyzing: 76 targets (154 packages loaded, 3720 targets configured)
WARNING: Download from https://mirror.bazel.build/github.com/Maratyszcza/FP16/archive/4dfe081cf6bcd15db339cf2680b9281b8451eeb3.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository remotejdk11_macos instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:181:6: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remote_java_tools_darwin instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:259:6: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository android_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:325:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository cpuinfo instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:388:13: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:75:20: in tf_workspace
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:105:27: in tf_repositories
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:49:12: in initialize_third_party
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/cpuinfo/workspace.bzl:11:29: in repo
Repository rule third_party_http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl:216:43: in <toplevel>
INFO: Repository maven instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:322:14: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/rules_jvm_external/defs.bzl:94:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
INFO: Repository arm_neon_2_x86_sse instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:388:13: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:75:20: in tf_workspace
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:907:20: in tf_repositories
Repository rule tf_http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl:131:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'arm_neon_2_x86_sse':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl", line 97, column 33, in _tf_http_archive
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'cpuinfo':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl", line 185, column 33, in _third_party_http_archive
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'android_tools':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'remote_java_tools_darwin':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'remotejdk11_macos':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/rules_jvm_external/coursier.bzl", line 452, column 28, in _coursier_fetch_impl
		repository_ctx.download([
Error in download: java.io.IOException: thread interrupted
INFO: Repository XNNPACK instantiated at:
  /Users/dliu/GitHub/mediapipe/WORKSPACE:388:13: in <toplevel>
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:75:20: in tf_workspace
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/tensorflow/workspace.bzl:136:20: in tf_repositories
Repository rule tf_http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl:131:34: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/30d4b250aef4ee74271c2254943f062a8356a23e.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'XNNPACK':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl", line 97, column 33, in _tf_http_archive
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1025)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more

INFO: Elapsed time: 17.599s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (163 packages loaded, 4066 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1025)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[4cc9233839169cb9ac0feb34a8b8c8d8698062d023b6ce85b243ecf6588adb56]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1025)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
FAILED: Build did NOT complete successfully (163 packages loaded, 4066 targets configured)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (163 packages loaded, 4066 targets configured)
build invocation result: fatal_error
Sync finished

Timing summary:
BlazeInvocation: 18.5s, Prefetching: 0ms, Other: 0ms
Sync failed
```

**Comment by oquenchil** [comment]
Can you provide the command?

I would say that this should just have been filed with mediapipe but it is true that Bazel shouldn't crash. To help with debugging please provide a  repository with example code and exactly the build command you are using.

**Comment by david-siqi-liu** [comment]
I figured out the issue - had to do with my XCode installation. All works now.

**Comment by NoobCheese** [comment]
> I figured out the issue - had to do with my XCode installation. All works now.

i get the same issue now. Could u describe more details ? u mean re-install the xcode-select  or sth else ? Thx

**Comment by janboeye** [comment]
@david-siqi-liu I meet same issue. how do you fix this issue? Thanks

**Comment by david-siqi-liu** [comment]
@janboeye just re-installed XCode, simple as that
