### ISSUE TITLE
Debugging grpc OUT_OF_RANGE (proto 2GB serialization limit?)

### ISSUE THREAD

**Issue by luxe** [bazelbuild/bazel#12487]
bazel 3.1.0 is crashing with the following error:  
`Caused by: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 2460924504 exceeds 2147483648`.  

Here is the full stacktrace:

```
ERROR: /repo/BUILD:110:1:  failed (Exit 34): com.google.devtools.build.lib.remote.BulkTransferException
--
  | at com.google.devtools.build.lib.remote.RemoteCache.waitForBulkTransfer(RemoteCache.java:223)
  | at com.google.devtools.build.lib.remote.RemoteExecutionCache.uploadMissing(RemoteExecutionCache.java:58)
  | at com.google.devtools.build.lib.remote.RemoteExecutionCache.ensureInputsPresent(RemoteExecutionCache.java:110)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:315)
  | at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:237)
  | at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:304)
  | at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:238)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:126)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:96)
  | at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:39)
  | at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.beginTestAttempt(StandaloneTestStrategy.java:308)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.access$100(StandaloneTestStrategy.java:68)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.beginExecution(StandaloneTestStrategy.java:442)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.beginIfNotCancelled(TestRunnerAction.java:835)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.beginExecution(TestRunnerAction.java:804)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:860)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:851)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:961)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1109)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: java.io.IOException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 2460924504 exceeds 2147483648
  | at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$uploadBlobAsync$1(ByteStreamUploader.java:248)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:175)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:107)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:93)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:93)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:752)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:116)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:752)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:116)
  | at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
  | at io.grpc.Context$1.run(Context.java:595)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at io.grpc.Context$1FixedContextExecutor.execute(Context.java:634)
  | at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:987)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)
  | at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload$1.onClose(ByteStreamUploader.java:505)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at com.google.devtools.build.lib.remote.util.NetworkTime$NetworkTimeCall$1.onClose(NetworkTime.java:93)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
  | at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
  | at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
  | at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  | at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
  | ... 3 more
  | Caused by: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 2460924504 exceeds 2147483648
  | at io.grpc.Status.asRuntimeException(Status.java:523)
  | ... 23 more
  | . Note: Remote connection/protocol failed with: execution failed com.google.devtools.build.lib.remote.BulkTransferException
  | at com.google.devtools.build.lib.remote.RemoteCache.waitForBulkTransfer(RemoteCache.java:223)
  | at com.google.devtools.build.lib.remote.RemoteExecutionCache.uploadMissing(RemoteExecutionCache.java:58)
  | at com.google.devtools.build.lib.remote.RemoteExecutionCache.ensureInputsPresent(RemoteExecutionCache.java:110)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:315)
  | at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:237)
  | at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:304)
  | at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:238)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:126)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:96)
  | at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:39)
  | at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.beginTestAttempt(StandaloneTestStrategy.java:308)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy.access$100(StandaloneTestStrategy.java:68)
  | at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.beginExecution(StandaloneTestStrategy.java:442)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.beginIfNotCancelled(TestRunnerAction.java:835)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.beginExecution(TestRunnerAction.java:804)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:860)
  | at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:851)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:961)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1109)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: java.io.IOException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 2460924504 exceeds 2147483648
  | at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$uploadBlobAsync$1(ByteStreamUploader.java:248)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:175)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:107)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:93)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:93)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:752)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:116)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:752)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
  | at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
  | at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:116)
  | at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
  | at io.grpc.Context$1.run(Context.java:595)
  | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
  | at io.grpc.Context$1FixedContextExecutor.execute(Context.java:634)
  | at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:987)
  | at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
  | at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
  | at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
  | at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)
  | at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload$1.onClose(ByteStreamUploader.java:505)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at com.google.devtools.build.lib.remote.util.NetworkTime$NetworkTimeCall$1.onClose(NetworkTime.java:93)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
  | at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  | at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  | at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  | at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
  | at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
  | at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
  | at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
  | at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  | at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
  | ... 3 more
  | Caused by: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 2460924504 exceeds 2147483648
  | at io.grpc.Status.asRuntimeException(Status.java:523)
  | ... 23 more

```

I think I'm hitting the 2GB limit on protobuf serialization for remote execution.  I didn't find any related issues that include this message.  Are there any flags I could use to find the offending files?

**Comment by larsrc-google** [comment]
If you're up for building your own Bazel, you could catch the exception in
the first place that has the relevant information and throw a more
informative error.

You could also do an aquery and grep for actions that have very large
inputs.

-Lars

**Comment by oquenchil** [comment]
Can you please provide the build command and the code you are trying to build?

**Comment by luxe** [comment]
for context, this occurred when upgrading cuda from 10.2 to 11 in which 11's libraries have become significantly larger. I'll see about making a minimal example if I can't get any further with aquery or patching bazel.

With aquery, I see the action inputs as a list of filenames.  Is the 2GB limit the entire serialized action that aquery prints? or is it also the content of these input files?  Maybe I need to iterate over each input file name and see which ones exceed 2GB, since the error is likely the upload of one of these files.

**Comment by luxe** [comment]
Thanks for your suggestion on using aquery.  aquery shows all the "action inputs" or "artifacts" (whatever you want to call them)... but those files might not actually exist and the file sizes cannot be known through that query output.  

so I did a remote build for speed (let it crash on serialization), finish the build locally, run aquery, iterate all inputs (which exist from building), and size/sort them:

**before:**
```
aquery_size --target="//<target>"
47274616 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
137870656 bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sllvm_Slibllvm-dev-common.so
166854720 bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sllvm_Slibclang-dev-common.so
319377072 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so
1859676064 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so
```

**after:**
```
aquery_size --target="//<target>"
47282864 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
137870656 bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sllvm_Slibllvm-dev-common.so
166854720 bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sllvm_Slibclang-dev-common.so
319377072 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so
2460924504 external/pypi_torch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so
```
int_max = 2147483647
sure enough, that finds the problem file.  

I'll try to improve the error message in bazel.  Do you know where I can find more info about why this limit exists?

**Comment by joeleba** [comment]
>  Is the 2GB limit the entire serialized action that aquery prints? or is it also the content of these input files? 

Aquery doesn't know about the content of any file. It basically just gives info about the action graph (i.e. the relationship between actions and artifacts). The 2GB limit is with protobuf (Reason: https://stackoverflow.com/a/34186672).

**Comment by luxe** [comment]
thanks, I guess we'll need to just fix our build artifacts.  Getting around this limitation doesn't seem as feasible.
