### ISSUE TITLE
Workers sometimes get stuck due to a deadlock in Java's process handling

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#1250]
Compilation hangs, please see the last console messages before hanging. Repeatable.
Version: 0.2.2b
OS: FreeBSD
Java: openjdk8-8.66.17_1

---example 1---

```
INFO: From Building src/main/java/com/google/devtools/build/lib/libbazel-repository.jar (37 source files):
Note: src/main/java/com/google/devtools/build/lib/bazel/repository/MavenJarFunction.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[531 / 543] Still waiting for 2 jobs to complete:
      Running (worker):
        Building src/tools/android/java/com/google/devtools/build/android/zipu\
tils/libziputils_lib.jar (12 source files), 276 s
        Building src/tools/android/java/com/google/devtools/build/android/idlc\
lass/classes.jar (), 276 s
```

---example 2---

```
[523 / 543] Still waiting for 3 jobs to complete:
      Running (worker):
        Building src/main/protobuf/libworker_protocol_java_proto.jar (1 source\
 jar), 209 s
        Building src/tools/android/java/com/google/devtools/build/android/clas\
ses.jar (), 209 s
        Building src/tools/android/java/com/google/devtools/build/android/zipu\
tils/libziputils_lib.jar (12 source files), 209 s
```

---process tree in the hung state---

```
 |         \-+- 34925 root make CONFIG_DONE_BAZEL=1 /usr/ports/devel/bazel/work/.stage_done.bazel._usr_local
 |           \-+- 54152 root bash ./compile.sh
 |             \-+- 55999 root /usr/local/openjdk8/bin/java -client -Xms256m -XX:NewRatio=4 -XX:+HeapDumpOnOutOfMemoryError -Xverify:none -Dfile.encoding=ISO-8859-1 -XX:HeapDumpPath=/tmp/bazel.mo4oihj3 -Djava.util.logging.config.file=/tmp/bazel.mo4oihj3/javalog.properties -Dio.bazel.UnixFileSystem=0 -jar /tmp/bazel.mo4oihj3/archive/libblaze.jar --batch --install_base=/tmp/bazel.mo4oihj3/archive --output_base=/tmp/bazel.mo4oihj3/out --install_md5= --workspace_directory=/usr/ports/devel/bazel/work/bazel-0.2.2b --nodeep_execroot --nofatal_event_bus_exceptions build --ignore_unsupported_sandboxing --startup_time=329 --extract_data_time=523 --rc_source=/dev/null --isatty=1 --ignore_client_env --client_cwd=/usr/ports/devel/bazel/work/bazel-0.2.2b --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --genclass_top=//src/java_tools/buildjar:bootstrap_genclass_deploy.jar --ijar_top=//third_party/ijar --strategy=Javac=worker --worker_quit_after_build --genrule_strategy=standalone --spawn_strategy=standalone --verbose_failures --javacopt=-source 1.8 -target 1.8 --stamp --embed_label 0.2.2b- (@non-git) src:bazel
 |               |--- 57416 root /tmp/bazel.mo4oihj3/out/bazel-0.2.2b/external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar --persistent_worker
 |               |--- 57417 root /tmp/bazel.mo4oihj3/out/bazel-0.2.2b/external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar --persistent_worker
 |               |--- 57418 root /tmp/bazel.mo4oihj3/out/bazel-0.2.2b/external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar --persistent_worker
 |               \--- 57419 root /tmp/bazel.mo4oihj3/out/bazel-0.2.2b/external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar --persistent_worker
```

**Comment by aehlig** [comment]
Some notes on that observation.

-  That hang seems to be somehow FreeBSD-specific (maybe the java implementation
    on FreeBSD).

- While the hang is reproducible, the compile calls that hang differ from attempt
  to attempt, at least on my FreeBSD box (stable/10); however, there seems to be a
  small set of calls that are quite likely to occur among the processes that hang.

- Interestingly enough, the hang does not occur on sequential builds, at least not on
  my stable/10 (ports from head) machine. You can get sequential builds by adding
  a ``-j 1`` option to the call in ``bootstrap_build()`` in ``scripts/bootstrap/compile.sh``.

Can you confirm that ``-j 1`` gets a successful build for you? My guess is that
somehow we might have some race leading to a deadlock or similar in the java
code that is only uncovered by a different thread scheduling strategy on the other
platform. But this is wide speculation and we have to investigate further.

**Comment by ulfjack** [comment]
Can you try disabling the persistent workers?

**Comment by yurivict** [comment]
> Can you confirm that -j 1 gets a successful build for you?

Yes, build finishes with -j 1

> Can you try disabling the persistent workers?

Not sure how to do this. But -j 1 already helped.

**Comment by yurivict** [comment]
Now, in 0.4.0, even with the add ```-j 1``` in ```run_bazel_jar``` in ```scripts/bootstrap/compile.sh```, it still runs concurrently and hangs. What is the right way to ensure single-cpu now?

**Comment by brian-peloton** [comment]
Are there children of any actions which escape from their parent? By this, I mean processes which inherit the stdout/stderr file descriptors from the command an action runs and are then not waited on, so they end up reparented to init. I just spent half the day discovering that OpenJDK has a lovely race condition in this situation, where reading from the file descriptors of the action processes *usually* indicates they've been closed but occasionally hangs instead. When a test of mine lets a child process escape, I end up with exactly these same symptoms.

I'm on Linux, but with the PID namespace disabled due to #1972, and all the relevant code looks the same.

I found this issue by attaching to the hung bazel server process with `jdb -connect sun.jvm.hotspot.jdi.SAPIDAttachingConnector:pid=<THE_PID>` and then entering `where all` because I didn't have access to stdout/stderr of the bazel client (it's complicated...). If you do (like if you're running it yourself on the command line), you can get that same information by typing ctrl+\ into the client. The symptom to look for is a thread named `Command-Accumulator-Thread-*` blocking under `com.google.devtools.build.lib.shell.InputStreamSink$CopySink.run` and a `process reaper` thread blocking under `java.lang.UNIXProcess$ProcessPipeInputStream.processExited` (might mention "
waiting for monitor entry"). Can you do that and confirm this is the same issue?

I just filed an OpenJDK bug but apparently those go to a non-public tracker first. I'll respond back once I have an actual bug number for it.

Workarounds on the Bazel end are tough. Relying on the PID namespace doesn't seem possible older Linux kernels, and for non-Linux systems without any sandboxing support it's even worse. The alternative seems to be non-blocking reads on process output streams, but that's hard to implement without a big performance hit.

**Comment by yurivict** [comment]
At this point, I don't know how to make bazel run on FreeBSD. No workaround.

**Comment by aehlig** [comment]
See my comment on [your PR 204512](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204512). The work-around is to change the strategy
for `Javac`. The patch in question is

```
--- scripts/bootstrap/bootstrap.sh.orig 1979-12-31 23:00:00 UTC
+++ scripts/bootstrap/bootstrap.sh
@@ -39,7 +39,7 @@ if [ "${JAVA_VERSION}" = "1.7" ]; then
 else
   : ${BAZEL_ARGS:=--java_toolchain=//src/java_tools/buildjar:bootstrap_toolchain \
         --host_java_toolchain=//src/java_tools/buildjar:bootstrap_toolchain \
-        --strategy=Javac=worker --worker_quit_after_build --ignore_unsupported_sandboxing \
+        --strategy=Javac=standalone --ignore_unsupported_sandboxing \
         --compilation_mode=opt \
         "${EXTRA_BAZEL_ARGS:-}"}
 fi
@@ -91,7 +91,7 @@ function bootstrap_test() {
   local BAZEL_BIN=$1
   local BAZEL_SUM=$2
   local BAZEL_TARGET=${3:-src:bazel}
-  local STRATEGY="--strategy=Javac=worker --worker_quit_after_build"
+  local STRATEGY="--strategy=Javac=standalone"
   if [ "${JAVA_VERSION}" = "1.7" ]; then
     STRATEGY=
   fi
```

**Comment by aehlig** [comment]
@yurivict, can you please verify if this works for you as well? Because if it does, I will downgrade this issue to a low-priority feature request of having persistent workers work on FreeBSD.

**Comment by yurivict** [comment]
Your version of the port breaks on 11 amd64:
```
third_party/ijar/zip.cc:151:10: warning: private field 'uncompressed_data_allocated_' is not used [-Wunused-private-field]
  size_t uncompressed_data_allocated_;
         ^
2 warnings generated.
ERROR: /usr/ports/devel/bazel/work/bazel-0.4.2a/src/main/cpp/util/BUILD:26:1: C++ compilation of rule '//src/main/cpp/util:file' failed: clang failed: error executing command 
  (cd /usr/ports/devel/bazel/work/bazel_tmp/bazel_rGj8KfjW/out/execroot/bazel-0.4.2a && \
  exec env - \
    PATH=.:/home/yuri/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin \
    TMPDIR=/usr/ports/devel/bazel/work/bazel_tmp \
  /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local_freebsd-opt/bin/src/main/cpp/util/_objs/file/src/main/cpp/util/file.pic.d '-frandom-seed=bazel-out/local_freebsd-opt/bin/src/main/cpp/util/_objs/file/src/main/cpp/util/file.pic.o' -fPIC -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/local_freebsd-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_freebsd-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/util/file.cc -o bazel-out/local_freebsd-opt/bin/src/main/cpp/util/_objs/file/src/main/cpp/util/file.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from src/main/cpp/util/file.cc:23:
./src/main/cpp/util/file_platform.h:74:1: error: unknown type name 'time_t'
time_t GetMtimeMillisec(const std::string& path);
^
./src/main/cpp/util/file_platform.h:79:48: error: unknown type name 'time_t'
bool SetMtimeMillisec(const std::string& path, time_t mtime);
                                               ^
2 errors generated.
```

**Comment by aehlig** [comment]
That looks more like additional header files should be included in some source files than a hanging compilation. Feel free to file a separate issue about this or send appropriate patches. However, it seems that the originally reported problem is successfully worked around.

**Comment by yurivict** [comment]
yes

**Comment by excitoon** [comment]
This looks like discussion mentioned by @aehlig: https://bugs.openjdk.java.net/browse/JDK-8169565
Btw, I wonder, why do we constantly poll input streams even if we got 0 bytes of data? This looks suboptimal (InputStreamSink.java):
```java
    @Override
    public void run() {
      try {
        byte[] buffer = new byte[2048];
        int bytesRead;
        while ((bytesRead = in.read(buffer)) >= 0) {
          out.write(buffer, 0, bytesRead);
          out.flush();
        }
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
```
See also: https://docs.oracle.com/javase/8/docs/api/java/io/BufferedInputStream.html

**Comment by excitoon** [comment]
```
"Command-Accumulator-Thread-36" #368 daemon prio=5 os_prio=0 cpu=15.74ms elapsed=1795.47s tid=0x00007f3a7000f000 nid=0x17bb7 runnable  [0x00007f3a617d8000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@11.0.2/Native Method)
	at java.io.FileInputStream.read(java.base@11.0.2/Unknown Source)
	at java.io.BufferedInputStream.fill(java.base@11.0.2/Unknown Source)
	at java.io.BufferedInputStream.read1(java.base@11.0.2/Unknown Source)
	at java.io.BufferedInputStream.read(java.base@11.0.2/Unknown Source)
	- locked <0x0000000672193350> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at java.io.FilterInputStream.read(java.base@11.0.2/Unknown Source)
	at com.google.devtools.build.lib.shell.InputStreamSink$CopySink.run(InputStreamSink.java:97)
	at com.google.devtools.build.lib.shell.Consumers$ClosingSink.run(Consumers.java:302)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.2/Unknown Source)
	at java.util.concurrent.FutureTask.run(java.base@11.0.2/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/Unknown Source)
	at java.lang.Thread.run(java.base@11.0.2/Unknown Source)
```

**Comment by jrpally** [comment]
I believe is the same issue:
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks process reaper@2438
	  at java.io.FileInputStream.readBytes(FileInputStream.java:-1)
	  at java.io.FileInputStream.read(FileInputStream.java:255)
	  at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	  - locked <0x98c> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	  at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	  - locked <0x98f> (a java.io.InputStreamReader)
	  at java.io.InputStreamReader.read(InputStreamReader.java:184)
	  at java.io.BufferedReader.fill(BufferedReader.java:161)
	  at java.io.BufferedReader.readLine(BufferedReader.java:324)
	  at java.io.BufferedReader.readLine(BufferedReader.java:389)
	  at com.mastercard.commons.connection.LocalShellEngine.execute(LocalShellEngine.java:67)


"process reaper@2438" daemon prio=10 tid=0xf nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for main@1 to release lock on <0x98c> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	  at java.lang.UNIXProcess$ProcessPipeInputStream.processExited(UNIXProcess.java:527)
	  at java.lang.UNIXProcess.lambda$initStreams$3(UNIXProcess.java:298)
	  at java.lang.UNIXProcess$$Lambda$15.1822525972.run(Unknown Source:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

sudo su - mc --session-command $'export JAVA_HOME="$(ls -td /sys_apps_01/java/java-1.8*| head -1)" && echo $JAVA_HOME && export PATH=$JAVA_HOME/bin:$PATH && export APIE_PLATFORM=DEV  && export APIE_REGION=US && export APIE_ZONE=STL && cd /myapps/webapps/JBoss/bin && /myapps/webapps/JBoss/bin/myserver.sh -a start'


Myapp takes some time to start.

THis is causing a lock

**Comment by jmmv** [comment]
Given that we do not officially support FreeBSD and there is no activity here or anything for us to do... I'll have to close this as not actionable. We'll take PRs to make this better though, if it's still a problem.

**Comment by bsilver8192** [comment]
I disagree that this only affects FreeBSD. I've seen what I think is the same bug on Linux, as mentioned in https://github.com/bazelbuild/bazel/issues/1250#issuecomment-259620892. https://bugs.openjdk.java.net/browse/JDK-8169565 is indeed the openjdk bug I mentioned. Might want to track that as a separate bug though, and bazel also might avoid triggering the behavior now.

**Comment by jmmv** [comment]
Fair enough. Reopening and changing the title to better describe the problem without losing history.

**Comment by larsrc-google** [comment]
What's the current status? Is there an easy way to reproduce this on Linux?

**Comment by larsrc-google** [comment]
No response, closing.
