### ISSUE TITLE
java coverage crash on 4.0.0rc2

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#12619]
running `bazel coverage //...` in a big multi-lang monorepo.
Bazel version `37a429ad12b4c9e6a62dbae4881a1ff03b81ab40` (4.0.0-rc2)
rules_java at `d43b0aa2d3b2173fcc54d3c194e89fa66cdc6e1a` (current HEAD)

let me know if I can provide anything else short of a minimal repro

```

(21:13:45) FATAL: bazel crashed due to an internal error. Printing stack trace:
--
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//test/java/com/rh/ledger:LedgerTest, config=BuildConfigurationValue.Key[f35c31b1baf1ab2bed1284160072656c995dfa7db8c9f4349087d4fbbb2e27de]}' (requested by nodes )
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
  | at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
  | at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  | at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
  | at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
  | at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
  | Caused by: java.lang.NullPointerException
  | at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.addCoverageSupport(JavaCompilationHelper.java:382)
  | at com.google.devtools.build.lib.bazel.rules.java.BazelJavaSemantics.addCoverageSupport(BazelJavaSemantics.java:613)
  | at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:199)
  | at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:65)
  | at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
  | at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
  | at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
  | at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
  | at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
  | ... 7 more

```

**Comment by alexeagle** [comment]
From https://github.com/bazelbuild/bazel/blob/37a429ad12b4c9e6a62dbae4881a1ff03b81ab40/src/main/java/com/google/devtools/build/lib/rules/java/JavaCompilationHelper.java#L382
it looks like jacoco runner isn't in my Java toolchain. Seems like the conditional right above that line was meant to error out in this case, but fell through instead.

**Comment by alexeagle** [comment]
I see this was recently changed in https://github.com/bazelbuild/bazel/commit/29362026e2e3c1a2cdbbdd549176e8395426bdb4

**Comment by jin** [comment]
cc @comius
