### ISSUE TITLE
insufficient validation of run(_shell) "arguments" argument

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#12692]
```
$ cat myrule.bzl
def _my_rule(ctx):
    ctx.actions.run_shell(arguments = 42, command = "touch $@", outputs = [ctx.actions.declare_file('f')])

my_rule = rule(
    implementation = _my_rule,
)
$ cat BUILD
load(":myrule.bzl", "my_rule")

my_rule(
    name = "x",
)
$ bazel build //:x
Analyzing: target //:x (1 packages loaded, 0 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:x, config=BuildConfigurationValue.Key[8cb8315356b64ac573a7b895d1afb8f4ab2e0f2e77d229908b65db76f6aa88e9]}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: java.lang.ClassCastException: class net.starlark.java.eval.StarlarkInt$Int32 cannot be cast to class net.starlark.java.eval.Sequence (net.starlark.java.eval.StarlarkInt$Int32 and net.starlark.java.eval.Sequence are in unnamed module of loader 'app') (Starlark stack: [_my_rule@//myrule.bzl:2:26, run_shell@<builtin>])
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:621)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:634)
	at net.starlark.java.eval.Eval.eval(Eval.java:450)
	at net.starlark.java.eval.Eval.exec(Eval.java:272)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:191)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:617)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.buildRule(StarlarkRuleConfiguredTargetUtil.java:130)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:365)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
Caused by: java.lang.ClassCastException: class net.starlark.java.eval.StarlarkInt$Int32 cannot be cast to class net.starlark.java.eval.Sequence (net.starlark.java.eval.StarlarkInt$Int32 and net.starlark.java.eval.Sequence are in unnamed module of loader 'app')
	at com.google.devtools.build.lib.analysis.starlark.StarlarkActionFactory.runShell(StarlarkActionFactory.java:425)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:617)
	... 21 more
```

**Comment by aiuto** [comment]
I might argue that we should get rid of run_shell, because it anti-windows biased.  :-)

Is the bug that we crash when you specify a scaler for args rather than a list of strings? Or did I misunderstand.

**Comment by benjaminp** [comment]
> I might argue that we should get rid of run_shell, because it anti-windows biased. :-)

I find shell rarely defensible on any platform.

> 
> Is the bug that we crash when you specify a scaler for args rather than a list of strings? Or did I misunderstand.

`s/args/arguments/`, but yes

**Comment by janakdr** [comment]
This seems like a bug in Starlark that the argument isn't being validated? I don't think team-Core has any control over the relevant code.

**Comment by benjaminp** [comment]
8a43e0cb973ab979da8140bc31fd94651537ce5b
