### ISSUE TITLE
[ERROR] Android data-binding. 'Argument list too long' / 'Method too large'

### ISSUE THREAD

**Issue by Morfly** [bazelbuild/bazel#12697]
### Description of the problem:

I'm trying to build a large Android project (around 1000 Bazel packages/modules)
The project uses AndroidX data-binding and Kotlin language.

When I build separate data-binding enabled modules - it completes successfully.

However, when I'm trying to build a root `android_binary` target that depends on a large amount of all other packages I'm getting a build error.

There are 2 variants of output:
- In the first case the output is entirely filled out with the raw text that consists of the following items:
`-dependencyClassInfoList bazel-out/android-armeabi-v7a-fastbuild/bin/<package/path>/databinding/view_models_base/class-info.zip`
And at the end:
`Action failed to execute: java.io.IOException: Cannot run program "/usr/bin/sandbox-exec" (in directory "/private/var/tmp/_bazel_pavlo.stavytskyi/d5ffa3720af924ed92a5c1df70b58707/sandbox/darwin-sandbox/5687/execroot/application"): error=7, Argument list too long`
- if I use `--experimental_use_rtxt_from_merged_resources` flag I can see the following output:
```
Dec 14, 2020 9:59:08 PM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
SEVERE: Unexpected
org.objectweb.asm.MethodTooLargeException: Method too large: com/application/R$id.<clinit> ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:496)
        at com.google.devtools.build.android.resources.RClassGenerator.writeInnerClass(RClassGenerator.java:193)
        at com.google.devtools.build.android.resources.RClassGenerator.writeClasses(RClassGenerator.java:165)
        at com.google.devtools.build.android.resources.RClassGenerator.write(RClassGenerator.java:111)
        at com.google.devtools.build.android.AndroidResourceClassWriter.writeAsClass(AndroidResourceClassWriter.java:134)
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:116)
        at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Dec 14, 2020 9:59:08 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
org.objectweb.asm.MethodTooLargeException: Method too large: com/application/R$id.<clinit> ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:496)
        at com.google.devtools.build.android.resources.RClassGenerator.writeInnerClass(RClassGenerator.java:193)
        at com.google.devtools.build.android.resources.RClassGenerator.writeClasses(RClassGenerator.java:165)
        at com.google.devtools.build.android.resources.RClassGenerator.write(RClassGenerator.java:111)
        at com.google.devtools.build.android.AndroidResourceClassWriter.writeAsClass(AndroidResourceClassWriter.java:134)
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:116)
        at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Exception in thread "main" org.objectweb.asm.MethodTooLargeException: Method too large: com/application/R$id.<clinit> ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:496)
        at com.google.devtools.build.android.resources.RClassGenerator.writeInnerClass(RClassGenerator.java:193)
        at com.google.devtools.build.android.resources.RClassGenerator.writeClasses(RClassGenerator.java:165)
        at com.google.devtools.build.android.resources.RClassGenerator.write(RClassGenerator.java:111)
        at com.google.devtools.build.android.AndroidResourceClassWriter.writeAsClass(AndroidResourceClassWriter.java:134)
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:116)
        at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Target //:app failed to build

INFO: Elapsed time: 14.465s, Critical Path: 11.56s
INFO: 240 processes: 146 remote cache hit, 39 internal, 55 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

To build the project with AndroidX data-binding I was using this approach: https://github.com/bazelbuild/bazel/issues/2694#issuecomment-649912743
with this commit: f4430e4e7ec9e832e2b6d0e7f1c108256563bd23

### Feature requests: what underlying problem are you trying to solve with this feature?

As far as I understood, if the project has a large number of targets, data binding generates too much text for some internal function and exceeds 64KB JVM limit.

Is there a way to overcome this issue currently?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build the project with a large number of `data-binding-enabled` targets. (~1000 targets)

### What operating system are you running Bazel on?

macOS Catalina

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From `master` using this approach:
https://github.com/bazelbuild/bazel/issues/2694#issuecomment-649912743

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
7a65cadb1a1496af4d4f01fbb15d82da79fa7403
7a65cadb1a1496af4d4f01fbb15d82da79fa7403

###  Have you found anything relevant by searching the web?

The method size limit on JVM is 64KB. 
https://dzone.com/articles/method-size-limit-java
https://stackoverflow.com/a/17422590/14281926

### Any other information, logs, or outputs that you want to share?

.bazelrc
```
build --strategy=Desugar=sandboxed
build --android_databinding_use_v3_4_args
build --experimental_android_databinding_v2
build --override_repository=android_tools=/Users/<path>/android_tools
build --android_databinding_use_androidx
build --java_header_compilation=false
build --verbose_failures
build --disk_cache=bazel-cache
build --experimental_google_legacy_api
build --define=android_incremental_dexing_tool=d8_dexbuilder
build --nouse_workers_with_dexbuilder
build --strict_java_deps=OFF
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java8
build --incompatible_disable_depset_items
build --experimental_ui_max_stdouterr_bytes=104857600
build --check_visibility=false
#build --experimental_use_rtxt_from_merged_resources
```

**Comment by ahumesky** [comment]
It would be most helpful if we can get a repro of some kind. I don't suppose the large android project is available somewhere? We'll have to come up with some kind of artificial repro instead.

**Comment by Morfly** [comment]
Sure, I will generate an artificial project with the same Bazel configuration and try to reproduce the issue there. I will share the link once ready.

**Comment by Morfly** [comment]
Hi @ahumesky 
I have an update regarding the sample project.
I have built a tool that allows generating `Bazel` projects using `Kotlin DSL`.
Here you can check the example data-binding project that can be useful during the issue triaging: https://github.com/Morfly/bazel-gen/tree/master/examples/examples-generation/androidx-data-binding-no-stubs
1. `config` directory contains the configuration Gradle project that generates the project. In `Main.kt` class, it is possible to specify the number of data-binding modules. Also, it is possible to `disable strict java deps`, which will add the appropriate flag to `.bazelrc` and reduce the dependency graph by eliminating duplicate entries.
2. `generated-project` directory will contain the generated Bazel project.

The link to the tool itself: https://github.com/Morfly/bazel-gen

The generated project can be already used for testing. Currently, I'm trying to find the most representative configuration that would help in resolving the issue.

**Comment by arunkumar9t2** [comment]
Thanks @Morfly.

Hello @ahumesky, I believe the root cause of the argument length problem arises from the way databinding data are propogated. I created https://github.com/bazelbuild/bazel/issues/12780 which has a small project that explains the problem. 

Method too large error seems to be a different problem, I do not have pointers on how it can be overcome other than reducing resources. This is a blocker for us atm. 

Considering the error being thrown due to JVM validation inside ASM `org.objectweb.asm.MethodWriter.computeMethodInfoSize`, I am curious of the impact from increasing the size limit and seeing if the limit still applies after .class to .dex conversion. Any thoughts appreciated.

**Comment by ahumesky** [comment]
Great thanks @Morfly 
I've tried out the example project at `examples/examples-generation/androidx-data-binding-no-stubs/generated-project` and I was able to get it to build, so just let us know when you find a configuration that reproduces the error here.

**Comment by Morfly** [comment]
Hi, @ahumesky 
I'm able to successfully build a simple large project as well. It turns out that the number of targets itself is not the reason for the issue which is interesting. Looks like there are some additional conditions that cause build failure on a large project.

**Comment by ahumesky** [comment]
Thanks for the update. Let us know if you're able to find more information about what conditions cause the problem.

**Comment by arunkumar9t2** [comment]
@ahumesky It seems we have a reproducable sample to https://github.com/bazelbuild/bazel/issues/12697 here.
