### ISSUE TITLE
RemoteWorker broken on JDK 7

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1271]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/5/console:

```
Note: Recompile with -Xlint:deprecation for details.
____[2,328 / 2,425] Extracting interface //src/main/java/com/google/devtools/build/lib/remote:remote
ERROR: /Users/ci/workspace/bazel-tests/BAZEL_VERSION/HEAD-jdk7/PLATFORM_NAME/darwin-x86_64/src/tools/remote_worker/src/main/java/com/google/devtools/build/remote/BUILD:1:1: Couldn't build file src/tools/remote_worker/src/main/java/com/google/devtools/build/remote/libremote.jar: Java compilation in rule '//src/tools/remote_worker/src/main/java/com/google/devtools/build/remote:remote' failed: java failed: error executing command 
  (cd /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/darwin-x86_64 && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac7.jar -client -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/local-fastbuild/bin/src/tools/remote_worker/src/main/java/com/google/devtools/build/remote/libremote.jar-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/tools/remote_worker/src/main/java/com/google/devtools/build/remote/RemoteWorker.java:153: error: local variable server is accessed from within inner class; needs to be declared final
                server.shutdown();
                ^
1 error
```

CC @hhclam

**Comment by hhclam** [comment]
looking

**Comment by hhclam** [comment]
Looks like just need to make server final in this line: https://github.com/bazelbuild/bazel/blob/master/src/tools/remote_worker/src/main/java/com/google/devtools/build/remote/RemoteWorker.java#L130

Not sure why jdk8 didn't complain about it..

**Comment by hhclam** [comment]
I'll prepare a patch.

**Comment by kchodorow** [comment]
Thanks for responding so quickly!  Yeah, JDK 8 loosened the requirements for what needs to be final in closures.

**Comment by hhclam** [comment]
No problem. I just happen to see the email on the screen.

Patch here: https://bazel-review.googlesource.com/#/c/3630/

**Comment by kchodorow** [comment]
Also looks like //src/test/shell/bazel:remote_execution_test is failing: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=ubuntu_15.10-x86_64/8/console.

```
==================== Test output for //src/test/shell/bazel:remote_execution_test:
bazel binary is at /home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/io_bazel/src/bazel
INFO: Reading 'startup' options from /home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/bazelrc: --output_user_root=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/root --host_javabase=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54'.
Extracting Bazel installation...
..
INFO: Reading 'startup' options from /home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/bazelrc: --output_user_root=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/root --host_javabase=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54'.
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
INFO: Reading 'startup' options from /home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/bazelrc: --output_user_root=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54/root --host_javabase=/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/home/ci/.cache/bazel/_bazel_ci/334f53535817c1f5147fb3c4afc04bac/execroot/ubuntu_15.10-x86_64/_tmp/remote_execution_test_54'.

Remote execution tests

** test_cc_binary **************************************************************
-- Test log: -----------------------------------------------------------
*** Starting Hazelcast server.
May 17, 2016 5:21:25 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast-default.xml' from classpath.
------------------------------------------------------------------------
test_cc_binary FAILED: terminated because this command returned a non-zero status:
src/test/shell/bazel/remote_execution_test:25: in call to set_up
FAILED: test_cc_binary

** 0 / 1 tests passed. *********************************************************
** There were errors. **********************************************************
================================================================================
```

**Comment by kchodorow** [comment]
(For future reference, JDK7 issue fixed by https://github.com/bazelbuild/bazel/commit/ab94f7fd173432ecff383d171ab486faa960cad0.)

**Comment by hhclam** [comment]
I think that's because the test timed out waiting for the worker to start.

I uploaded a speculative fix here: https://bazel-review.googlesource.com/#/c/3631/

**Comment by kchodorow** [comment]
Not quite fixed, OS X is having trouble starting the server multiple times (see http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/9/console):

```
May 18, 2016 2:35:06 PM com.hazelcast.core.LifecycleService
INFO: [192.168.154.226]:5702 [dev] [3.5.4] Address[192.168.154.226]:5702 is STARTED
*** Starting grpc server at 0.0.0.0:8080.
Exception in thread "main" java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:136)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:148)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:78)
	at com.google.devtools.build.remote.RemoteWorker.main(RemoteWorker.java:134)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1398)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeBindNow(ChannelHandlerInvokerUtil.java:108)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeBind(DefaultChannelHandlerInvoker.java:215)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:196)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1135)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:240)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:358)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
------------------------------------------------------------------------
test_cc_binary FAILED: Timed out waiting for remote worker to start. .
src/test/shell/bazel/remote_execution_test:50: in call to set_up
FAILED: test_cc_binary
```

**Comment by hhclam** [comment]
Is it possible there are multiple instances of the same test running at the same time? Once the test is completed the listening process should be teared down.

**Comment by hhclam** [comment]
I can change it so that each test instance starts with a random port number. This will it should avoid reused port when multiple instances of the tests are running.

**Comment by kchodorow** [comment]
I think using pick_random_unused_port would probably be safer.

**Comment by hhclam** [comment]
Uploaded this patch: https://bazel-review.googlesource.com/#/c/3650
