### ISSUE TITLE
NPE when passing remote_jdk11 as java_toolchain

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#12796]
It doesn't make any sense, but it could be a better outcome, that just to crash?

```bash
  $ bazel build --java_toolchain=@bazel_tools//tools/jdk:remote_jdk11 java/com/google/gerrit/common:server
  [...]
  FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@j2objc//jar:jar, config=BuildConfigurationValue.Key[f25303087b19358976571d4c573de7d3f56b9f28b60a44be9244f5df457a786e]}' (requested by nodes 'ConfiguredTargetKey{label=//lib:j2objc, config=BuildConfigurationValue.Key[f25303087b19358976571d4c573de7d3f56b9f28b60a44be9244f5df457a786e]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.createIjarAction(JavaCompilationHelper.java:802)
	at com.google.devtools.build.lib.rules.java.JavaImport.processWithIjarIfNeeded(JavaImport.java:214)
	at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:75)
	at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:38)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:385)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:195)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:940)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1015)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:370)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

**Comment by comius** [comment]
True, it could provide a better error. We're in the process of Java toolchainisation where --java_toolchain flag is going to be obsolete. So I'd rather focus on providing better error messages for the new set of flags.

**Comment by davido** [comment]
+1. Thanks for clarifying.
