### ISSUE TITLE
Remote execution: Internal Java error thrown by Bazel during build: "Unexpected result of remote execution: no result"

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/bazel#12862]
### Description of the problem / feature request:

While building a target using Bazel remote execution I'm getting the following internal error thrown by Bazel:

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=@com_google_protobuf//:protobuf_lite, config=BuildConfigurationValue.Key[a8c7180d651fbdfcc642f6b9e083ed39e8dd642b04a11bd890533d319dfa081a]}, actionIndex=16}' (requested by nodes 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=@com_google_protobuf//:protoc, config=BuildConfigurationValue.Key[a8c7180d651fbdfcc642f6b9e083ed39e8dd642b04a11bd890533d319dfa081a]}, actionIndex=4}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Unexpected result of remote execution: no result
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.getOperationResponse(GrpcRemoteExecutor.java:83)
        at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$0(GrpcRemoteExecutor.java:183)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:237)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:115)
        at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:144)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:369)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:237)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:115)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:347)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:240)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:134)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:102)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.beginExecution(CppCompileAction.java:1453)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:859)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1019)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:978)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:469)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:845)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:314)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        ... 4 more
```

The remote executor that I'm working on probably has a bug with the way that it's spawning containers and trying to execute actions, which I am attempting to fix separately. But I believe that the Bazel CLI shouldn't be throwing an internal error in this case. Instead I guess it should probably show `NO STATUS` for the build, with an error message saying something like "the remote executor didn't respond because [...]"

Happy to help debug this any way I can.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No easy way to repro, currently. I'm running this build against our internal remote execution platform which we eventually plan to open source, but we aren't quite there yet.

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

`release 3.7.0`

###  Have you found anything relevant by searching the web?

Couldn't find any issues specifically citing the error message "Unexpected result of remote execution: no result"

**Comment by bduffany** [comment]
I see in the Bazel source that this error happens only if `op.getDone()` is true, and the result is missing. But this is confusing to me because in our executor source, there aren't any places where we are setting `op.Done = true` while not also setting an execute response. 

Strangely enough though, if I print the serialized Operation received on the Bazel side (built from source), I get:

```
name: "/uploads/0611cec7-f406-49d4-9510-6f73afc9b831/blobs/ab526e2eb2d6fcb2fd80f2b3bdaa2ff82770474d3c0cceb2b377adeca49b4b28/141"
metadata {
  type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteOperationMetadata"
  value: "\b\004\022E\n@ab526e2eb2d6fcb2fd80f2b3bdaa2ff82770474d3c0cceb2b377adeca49b4b28\020\215\001"
}
done: true
response {
  type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteResponse"
}
```

**Comment by bduffany** [comment]
Closing since the stack trace does show "Unexpected result of remote execution: No result", which is probably a good enough error message
