### ISSUE TITLE
FATAL: bazel crashed due to an internal error. - Platforms

### ISSUE THREAD

**Issue by thna123459** [bazelbuild/bazel#12879]
### Description of the problem / feature request:

Crash NullPointerException

```
$ ./run.sh
Starting local Bazel server and connecting to it...
Analyzing: target //:main (24 packages loaded, 576 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:main, config=BuildConfigurationValue.Key[86e57527e1c8bb10edc853e734cb858f8159d8f3e0a4df9ceb16f80aad784b93]}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.platform.ConstraintCollection.hasConstraintValue(ConstraintCollection.java:216)
	at com.google.devtools.build.lib.analysis.RuleContext.targetPlatformHasConstraint(RuleContext.java:1226)
	at com.google.devtools.build.lib.analysis.constraints.RuleContextConstraintSemantics.lambda$incompatibleConfiguredTarget$1(RuleContextConstraintSemantics.java:904)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:120)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:120)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.google.devtools.build.lib.analysis.constraints.RuleContextConstraintSemantics.incompatibleConfiguredTarget(RuleContextConstraintSemantics.java:905)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:327)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazelisk build :main` with Bazel 4.0.0 on MacOS with the following `BUILD` file:

```python
platform(
    name = "myplatform",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm",
    ],
)

java_binary(
    name = "main",
    srcs = ["Foo.java"],
    main_class = "Foo",
    target_compatible_with = [":myplatform"]
)
```

### What operating system are you running Bazel on?

MacOS or Linux

### What's the output of `bazel info release`?

```
$ bazel info release
Starting local Bazel server and connecting to it...
release 4.0.0
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

See attachment: [testcase.tar.gz](https://github.com/bazelbuild/bazel/files/5855203/testcase.tar.gz)

**Comment by katre** [comment]
The crash is concerning and I'll address it immediately. Bazel shouldn't crash, it should fail gracefully and report an error.

The good news is, there's a simple fix: the correct type of target to use in `target_compatible_with` is a `constraint_value`, not a `platform` target. If you re-write your target to be:

```
java_binary(
    name = "main",
    srcs = ["Foo.java"],
    main_class = "Foo",
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:arm",
    ],
)
```

This will correctly report that the target can't be built.

**Comment by holaworlds** [comment]
I am receiving simirlar error. My bazel version is : bazel 4.1.0

<img width="1426" alt="Screen Shot 2021-08-03 at 10 40 34 PM" src="https://user-images.githubusercontent.com/13123340/128076025-791e006b-93aa-4457-93f4-341dbbd5ae77.png">

**Comment by katre** [comment]
@holaworlds This is a similar error message but a different underlying cause. Please open a new issue with details on how to reproduce the error.
