### ISSUE TITLE
Crash on flaky test attr when requesting execution log 

### ISSUE THREAD

**Issue by mattem** [bazelbuild/bazel#12874]
### Description of the problem / feature request:

When running `bazel test //:foo --execution_log_json_file=exec.json` (or with `--execution_log_binary_file=exec.json`) where `//:foo` is a test with the `flaky` attribute set truthy, bazel crashes with:

```
WARNING: Execution log might not have been populated. Raw execution log is at /var/folders/35/trmgpj6j1q5dj0jrx200sryw0000gn/T/exec15419926391042373086.log
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.devtools.build.lib.bazel.execlog.StableSort.stableSort(StableSort.java:72)
	at com.google.devtools.build.lib.bazel.execlog.StableSort.stableSort(StableSort.java:60)
	at com.google.devtools.build.lib.bazel.SpawnLogModule.afterCommand(SpawnLogModule.java:161)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:626)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:603)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`/WORKSPACE`:
```
workspace(
    name = "test",
)
```

`/test.sh`
```
exit 1
```

`/BUILD.bazel`
```
sh_test(
    name = "foo",
    flaky = 1,
    srcs = [
        "test.sh",
    ],
)
```

### What operating system are you running Bazel on?

MacOS 10.15.7 (19H114)

### What's the output of `bazel info release`?

release 4.0.0
This issue is also observed on 3.7.2 (I haven't checked other versions)

**Comment by benjaminp** [comment]
#12510

**Comment by mattem** [comment]
Looks like my searching skills aren't all I thought they were 😄 Closing in favor of existing issue #12510
