### ISSUE TITLE
cquery with --output=graph crashes

### ISSUE THREAD

**Issue by nikola-sh** [bazelbuild/bazel#12915]
### Description of the problem / feature request:

`bazel cquery` with `--output=graph` crashes with message
```
Starting local Bazel server and connecting to it...
DEBUG: /home/nikola/.cache/bazel/_bazel_nikola/cdd5da0d482563cb2bf964e63e3b5128/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/nikola/.cache/bazel/_bazel_nikola/cdd5da0d482563cb2bf964e63e3b5128/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True
DEBUG: /home/nikola/.cache/bazel/_bazel_nikola/cdd5da0d482563cb2bf964e63e3b5128/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/nikola/.cache/bazel/_bazel_nikola/cdd5da0d482563cb2bf964e63e3b5128/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True
INFO: Analyzed target //src:bazel (329 packages loaded, 9069 targets configured).
INFO: Found 1 target...
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@bazel_tools//tools/jdk:dummy_toolchain, config=BuildConfigurationValue.Key[86d23d2b5aedbeecfc6e6954ea9486ec39e9e40bcbc4b17cec46a06eed198d11]}]
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@bazel_tools//tools/jdk:dummy_toolchain, config=BuildConfigurationValue.Key[d8d0eb07eb92791668ac973282be1523379b0025b22f0ade56b13d519f2feb2a]}]
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@bazel_tools//tools/jdk:dummy_toolchain, config=BuildConfigurationValue.Key[86d23d2b5aedbeecfc6e6954ea9486ec39e9e40bcbc4b17cec46a06eed198d11]}]
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@bazel_tools//tools/jdk:dummy_toolchain, config=BuildConfigurationValue.Key[d8d0eb07eb92791668ac973282be1523379b0025b22f0ade56b13d519f2feb2a]}]

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException
        at java.base/java.lang.String.compareTo(Unknown Source)
        at com.google.devtools.build.lib.query2.cquery.GraphOutputFormatterCallback$1.lambda$$0(GraphOutputFormatterCallback.java:54)
        at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:37)
        at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:43)
        at com.google.common.collect.LexicographicalOrdering.compare(LexicographicalOrdering.java:42)
        at com.google.common.collect.LexicographicalOrdering.compare(LexicographicalOrdering.java:26)
        at java.base/java.util.TimSort.mergeHi(Unknown Source)
        at java.base/java.util.TimSort.mergeAt(Unknown Source)
        at java.base/java.util.TimSort.mergeForceCollapse(Unknown Source)
        at java.base/java.util.TimSort.sort(Unknown Source)
        at java.base/java.util.Arrays.sort(Unknown Source)
        at java.base/java.util.ArrayList.sort(Unknown Source)
        at java.base/java.util.Collections.sort(Unknown Source)
        at com.google.devtools.build.lib.query2.query.output.GraphOutputWriter.orderPartition(GraphOutputWriter.java:159)
        at com.google.devtools.build.lib.query2.query.output.GraphOutputWriter.outputFactored(GraphOutputWriter.java:170)
        at com.google.devtools.build.lib.query2.query.output.GraphOutputWriter.write(GraphOutputWriter.java:114)
        at com.google.devtools.build.lib.query2.cquery.GraphOutputFormatterCallback.processOutput(GraphOutputFormatterCallback.java:111)
        at com.google.devtools.build.lib.query2.engine.OutputFormatterCallback.process(OutputFormatterCallback.java:54)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.doPostAnalysisQuery(PostAnalysisQueryBuildTool.java:179)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.postProcessAnalysisResult(PostAnalysisQueryBuildTool.java:76)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:198)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:401)
        at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:141)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:579)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
git clone https://github.com/bazelbuild/bazel .
git checkout 4.0.0
bazel-4.0.0-linux-x86_64 cquery 'deps(//src:bazel)' --output=graph
```
### What operating system are you running Bazel on?

Linux, Windows

### What's the output of `bazel info release`?

release 4.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
```
https://github.com/bazelbuild/bazel
8c7e11a81c35563d951062fe6f00e4e85b3009fb
6b33bdb1e22514304c0e35ce8e067f2175685245
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?
bazel built from master (8c7e11a81c35563d951062fe6f00e4e85b3009fb) doesn't have this issue.

**Comment by gregestren** [comment]
I can reproduce this. Thanks for filing.
