### ISSUE TITLE
Documentation issue: Common C   Build Use Cases

### ISSUE THREAD

**Issue by kkzheng** [bazelbuild/bazel#12976]
Documentation URL: https://docs.bazel.build/versions/master/cpp-use-cases.html

when i run the command:
         bazel test test:hello-test
i got a error:
ERROR: /opt/meituan/zhangjinhao05/bazel_build_example/cpp-tutorial/stage3/test/BUILD:1:1: no such package '@gtest//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/5bac4b831d23b0a51bee0286e6bbac18/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/root/.cache/bazel/_bazel_root/5bac4b831d23b0a51bee0286e6bbac18/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 60, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //:gtest.BUILD: not found. and referenced by '//test:hello-test'

Q: where should i put my gtest.BUILD file

**Comment by kkzheng** [comment]
i got it.
touch BUILD at your WORKSPACE root
