### ISSUE TITLE
"." doesn't work as a target name

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13037]
Documentation URL: https://docs.bazel.build/versions/master/build-ref.html says:

>  a target name may consist of exactly '.'.

But, when I take stage3/main/BUILD from the C++ tutorial and change the name of the `cc_binary` target to `"."`, and then issue `bazel build "//main:."` from the stage3/main directory, I get:

```
Loading: 
Loading: 0 packages loaded
Analyzing: target //main:. (1 packages loaded, 0 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//main:., config=BuildConfigurationValue.Key[86e57527e1c8bb10edc853e734cb858f8159d8f3e0a4df9ceb16f80aad784b93]}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures.getArtifactNameForCategory(CcToolchainFeatures.java:1771)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getArtifactNameForCategory(CppHelper.java:826)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getLinkedArtifact(CppHelper.java:464)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getLinkedArtifact(CppHelper.java:448)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:359)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:294)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:99)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

**Comment by aiuto** [comment]
From the stack trace this appears to be a C++ specific problem.

**Comment by dws** [comment]
I get the same error with an `sh_binary` target, so it doesn't appear to be specific to C++:
```
$ bazel run //:.
Starting local Bazel server and connecting to it...
Analyzing: target //:. (17 packages loaded, 47 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:., config=BuildConfigurationValue.Key[86d23d2b5aedbeecfc6e6954ea9486ec39e9e40bcbc4b17cec46a06eed198d11]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:847)
        at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:837)
        at com.google.devtools.build.lib.analysis.RunfilesSupport.createRunfilesInputManifestArtifact(RunfilesSupport.java:242)
        at com.google.devtools.build.lib.analysis.RunfilesSupport.create(RunfilesSupport.java:131)
        at com.google.devtools.build.lib.analysis.RunfilesSupport.withExecutable(RunfilesSupport.java:420)
        at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:88)
        at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:40)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        ... 7 more
```

```
$ cat BUILD
sh_binary(
    name = ".",
    srcs = ["ahoy.sh"],
)
$ cat ahoy.sh
#!/bin/bash
echo "$0"
```

**Comment by dws** [comment]
There's a similar problem with using `...` as a target name:

```
$ cat BUILD
sh_binary(
    name = "...",
    srcs = ["ahoy.sh"],
)
$ bazel run //:...
Analyzing: target //:... (8 packages loaded, 13 targets configured)
    currently loading: @bazel_tools//tools/jdk ... (3 packages)
    Fetching @local_config_sh; fetching
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:..., config=BuildConfigurationValue.Key[86d23d2b5aedbeecfc6e6954ea9486ec39e9e40bcbc4b17cec46a06eed198d11]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: ...
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at com.google.devtools.build.lib.actions.ArtifactFactory.validatePath(ArtifactFactory.java:182)
        at com.google.devtools.build.lib.actions.ArtifactFactory.getDerivedArtifact(ArtifactFactory.java:224)
        at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:293)
        at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:850)
        at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:837)
        at com.google.devtools.build.lib.analysis.RuleContext.internalCreateOutputArtifact(RuleContext.java:735)
        at com.google.devtools.build.lib.analysis.RuleContext.createOutputArtifact(RuleContext.java:685)
        at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:51)
        at com.google.devtools.build.lib.bazel.rules.sh.ShBinary.create(ShBinary.java:40)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        ... 7 more
```

I would have expected a diagnostic similar to what I get when using a `*` as a target name:
```
WARNING: The target pattern '//:*' is ambiguous: ':*' is both a wildcard, and the name of an existing sh_binary rule; using the latter interpretation
WARNING: The target pattern '//:all' is ambiguous: ':all' is both a wildcard, and the name of an existing sh_binary rule; using the latter interpretation
WARNING: The target pattern '//:all-targets' is ambiguous: ':all-targets' is both a wildcard, and the name of an existing sh_binary rule; using the latter interpretation
```

**Comment by oquenchil** [comment]
I'm not sure if this is documented already but if it isn't we should just write somewhere that it isn't supported and fail gracefully instead of crashing.

**Comment by dabrahams** [comment]
Nice! If you ignore an issue long enough, it goes away… for maintainers, not for users

**Comment by dabrahams** [comment]
> Nice! If you ignore an issue long enough, it goes away… for maintainers, not for users
