### ISSUE TITLE
bazel cquery --output=starlark --starlark:expr="providers(target)" crashes with java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#13060]
`bazel cquery --output=starlark --starlark:expr="providers(target)" //pkg:target` not uncommonly crashes the bazel server process due to an OOM error:

```java
FATAL: bazel ran out of memory and crashed. Printing stack trace:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at net.starlark.java.eval.Printer.append(Printer.java:57)
	at com.google.devtools.build.lib.analysis.configuredtargets.RuleConfiguredTarget.repr(RuleConfiguredTarget.java:218)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
```

In my hands, `go_binary`, `go_test`, (some `go_library`) targets produce this outcome.

Will try to narrow down to simpler case.

```
$ bazel info release
release 4.0.0
```

```java
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at net.starlark.java.eval.Printer.append(Printer.java:51)
	at net.starlark.java.eval.Printer.appendQuoted(Printer.java:214)
	at net.starlark.java.eval.Printer.repr(Printer.java:150)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
	at net.starlark.java.eval.StarlarkList.repr(StarlarkList.java:268)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at com.google.devtools.build.lib.packages.StructImpl.repr(StructImpl.java:154)
	at net.starlark.java.eval.Printer.repr(Printer.java:177)
	at net.starlark.java.eval.Printer.printList(Printer.java:83)
```

**Comment by aiuto** [comment]
We're going to need some sort of reproduction for this.

**Comment by aiuto** [comment]
pcj@  Can you provide a reproduction.

**Comment by pcj** [comment]
@aiuto Yes I can try to give you a repro
