### ISSUE TITLE
DynamicSpawnStrategy crashes with AssertionError: No branch completed

### ISSUE THREAD

**Issue by tomrenn** [bazelbuild/bazel#13149]
### Description of the problem / feature request:

When using the dynamic scheduler in Bazel 4.0.0, we infrequently (< 1%) see the following crash

```
(18:21:05) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.AssertionError: No branch completed, which might mean they cancelled each other
	at com.google.devtools.build.lib.dynamic.DynamicSpawnStrategy.waitBranches(DynamicSpawnStrategy.java:257)
	at com.google.devtools.build.lib.dynamic.DynamicSpawnStrategy.exec(DynamicSpawnStrategy.java:422)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a consistent way to reproduce this bug at this time. It may happen slightly more frequently with `--experimental_local_execution_delay=0` but I have not tested this.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

I am using a custom build of Bazel 4.0.0 with a patch to address https://github.com/bazelbuild/bazel/issues/12972

This very well could be a bug with my patch (multi-threading is hard), but I suspect this is a separate issue. I'll post an update if this crash continues to exist after an official fix is available for https://github.com/bazelbuild/bazel/issues/12972

**Comment by larsrc-google** [comment]
We have seen this every so often internally as well (b/173153395), but haven't been able to pin it down yet. I have added some small debugging information, and so far I have found that there's always exactly one branch that thinks it's cancelled.

I would expect it to happen more frequently with a lower `--experimental_local_execution_delay` setting, since that would cause more tight races.

**Comment by larsrc-google** [comment]
We have a couple of related changes in the pipeline. One handles an issue that should only appear under `--experimental_local_lockfree_output` and can cause both branches to think they succeeded, which is rather the opposite of this. The other handles the case where it turns out neither branch can actually run the spawn after all, which is also not quite like this. Commit #1b9e2fb also adds some more debugging, so if you're still seeing these errors, you can update to include that for more info.

**Comment by sventiffe** [comment]
Adjusting priority as this bug seems to be not active. Please update the bug if this turns out to be incorrect or if the bug requires active work.

**Comment by larsrc-google** [comment]
https://github.com/bazelbuild/bazel/commit/fe1e25b1373bc9d4294ee354add4011916e9f44a fixed a case that looked like this, @tomrenn could you try with that fix included and see if you're still having these problems?

**Comment by tomrenn** [comment]
@larsrc-google could you champion that fix into the 4.2 release branch? Meanwhile, I'll try to see if I can still reproduce this on my machine with that fix applied

**Comment by larsrc-google** [comment]
It's high on my list to pick, yes.

**Comment by tomrenn** [comment]
I could not reproduce this locally on my machine, but our CI system failed on Bazel 4.2.0RC2 with

```
(16:38:35) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.AssertionError: No branch completed, which might mean they cancelled each other
	at com.google.devtools.build.lib.dynamic.DynamicSpawnStrategy.waitBranches(DynamicSpawnStrategy.java:267)
	at com.google.devtools.build.lib.dynamic.DynamicSpawnStrategy.exec(DynamicSpawnStrategy.java:432)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by larsrc-google** [comment]
Yeah, looks like it. I'm currently working on getting that fix in, but there's a lot of divergence.

**Comment by larsrc-google** [comment]
Long done.
