### ISSUE TITLE
Crash using --experimental_sandbox_async_tree_delete_idle_threads="auto"

### ISSUE THREAD

**Issue by luxe** [bazelbuild/bazel#13240]
### Description of the problem / feature request:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.ClassCastException: class com.google.devtools.build.lib.sandbox.SynchronousTreeDeleter cannot be cast to class com.google.devtools.build.lib.sandbox.AsynchronousTreeDeleter (com.google.devtools.build.lib.sandbox.SynchronousTreeDeleter and com.google.devtools.build.lib.sandbox.AsynchronousTreeDeleter are in unnamed module of loader 'app')
        at com.google.devtools.build.lib.sandbox.SandboxModule.afterCommand(SandboxModule.java:565)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:626)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:603)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Using --experimental_sandbox_async_tree_delete_idle_threads="auto"

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'll have to create a simple use-case to show the problem, but the stacktrace may be enough as the code shows that casting between two types cannot be done.

### What operating system are you running Bazel on?

Ubuntu.

### What's the output of `bazel info release`?

Bazel 4.0

**Comment by larsrc-google** [comment]
I'm guessing you first ran with `--experimental_sandbox_async_tree_delete_idle_threads=0` (or not set) and then in the same Bazel instance changed the flag. `SandboxModule.java:610` uses the flag setting rather than the type of `this.treeDeleter` to decide whether to set threads, but it's strange that there's a wrong kind of `TreeDeleter`, that should have been handled during `setup`. The direct fix would be to check `treeDeleter instanceof AsynchronousTreeDeleter` before casting, but that would leave the unfortunate fact that changing the option didn't seem to change the deleter here. This can happen if you interrupt the build after changing the option before the start of the execution phase - then `afterCommand` can get called without `registerSpawnStrategies()` having been called (through `BuildTool.buildTargets()`).  But if `registerSpawnStrategies()` has not been called, we also know there's nothing to clean up, so we can safely ignore this case and only set #threads if we have an `AsynchronousTreeDeleter`.
