### ISSUE TITLE
Bazel crashes on Ubuntu with "failed to delete output files before executing action"

### ISSUE THREAD

**Issue by chenmy0917** [bazelbuild/bazel#13307]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
My compilation failed, the error message is:
1. File name too long [36]
2. failed to delete output files before executing action

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Sorry, I don't know how to reproduce on other environment

### What operating system are you running Bazel on?

> Ubuntu 16.04

### What's the output of `bazel info release`?

> ERROR: /autocar/modules/perception/obstacle/lidar/object_detector/utils/BUILD:5:11: failed to delete output files before executing action

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> No, `bazel info release` returns "release 3.5.1" 
![image](https://user-images.githubusercontent.com/22138217/113808248-33835400-9798-11eb-8f32-4d6a1304ef11.png)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Our company's internal git

###  Have you found anything relevant by searching the web?

> Places to look:
> - GitHub issues: https://github.com/bazelbuild/bazel/issues/8963

### Any other information, logs, or outputs that you want to share?

> INFO: Analyzed 2250 targets (92 packages loaded, 39008 targets configured).
INFO: Found 2250 targets...
ERROR: /autocar/modules/perception/v2/lidar/lidar_internal_tracking/BUILD:150:8: Creating runfiles tree bazel-out/k8-opt/bin/modules/perception/v2/lidar/lidar_internal_tracking/association_loss_calculator_test.runfiles failed due to build-runfiles failed: error executing command 
  (cd /autocar/.cache/6f4204935a34301b5a6755383c15c682/execroot/autocar && \
  exec env - \
    LD_LIBRARY_PATH=/autocar/third_party/can_card_library/zlg_can/lib/:/autocar/third_party/can_card_library/kvaser_can/lib/:/usr/local/share/libtorch/lib:/autocar/third_party/can_card_library/kvaser_can/lib/::lib \
    PATH=/home/walle/.nvm/versions/node/v14.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin:/opt/autocar/simtool:/opt/autocar/simeditor \
  /autocar/.cache/install/34c2b2925d29f26adbd2afb9a2ac4610/build-runfiles bazel-out/k8-opt/bin/modules/perception/v2/lidar/lidar_internal_tracking/association_loss_calculator_test.runfiles_manifest bazel-out/k8-opt/bin/modules/perception/v2/lidar/lidar_internal_tracking/association_loss_calculator_test.runfiles): Process exited with status 1: Process exited with status 1
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
	at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:82)
	at com.google.devtools.build.lib.shell.Command.execute(Command.java:259)
	at com.google.devtools.build.lib.exec.SymlinkTreeHelper.createSymlinksUsingCommand(SymlinkTreeHelper.java:163)
	at com.google.devtools.build.lib.exec.SymlinkTreeStrategy.createSymlinks(SymlinkTreeStrategy.java:119)
	at com.google.devtools.build.lib.analysis.actions.SymlinkTreeAction.execute(SymlinkTreeAction.java:197)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:848)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1011)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:970)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:838)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:313)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
/autocar/.cache/install/34c2b2925d29f26adbd2afb9a2ac4610/build-runfiles (args bazel-out/k8-opt/bin/modules/perception/v2/lidar/lidar_internal_tracking/association_loss_calculator_test.runfiles_manifest bazel-out/k8-opt/bin/modules/perception/v2/lidar/lidar_internal_tracking/association_loss_calculator_test.runfiles): mkdir 'autocar/_solib_k8/_U_S_Smodules_Sperception_Sobstacle_Slidar_Sobject_Udetector_Sutils_Cobject_Udetector_Uutils___Umodules_Sperception_Sobstacle_Slidar_Sobject_Udetector_Sutils': File name too long [36]
INFO: Elapsed time: 102.714s, Critical Path: 34.92s
INFO: 1182 processes: 1182 local.
FAILED: Build did NOT complete successfully
INFO: Analyzed 1719 targets (8 packages loaded, 1359 targets configured).
INFO: Found 1719 targets...
ERROR: /autocar/modules/perception/obstacle/lidar/object_detector/utils/BUILD:5:11: failed to delete output files before executing action
INFO: Elapsed time: 51.448s, Critical Path: 31.25s
INFO: 395 processes: 395 local.
FAILED: Build did NOT complete successfully
[ERROR] Build failed!

**can you help me, look forward your reply @laurentlb**

**Comment by meisterT** [comment]
I seem to have seen this before cc @oquenchil @meteorcloudy

**Comment by chenmy0917** [comment]
I solved this problem by reinstalling the system
