### ISSUE TITLE
Bazel crashes when user sets their own `DEVELOPER_DIR`

### ISSUE THREAD

**Issue by thii** [bazelbuild/bazel#13330]
### Description of the problem / feature request:

Bazel crashes when the user sets their own `DEVELOPER_DIR` environment variable.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set `DEVELOPER_DIR` environment variable to a value in the Apple CROSSTOOL file and build with that.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 4.0.0

### Any other information, logs, or outputs that you want to share?

```
SUBCOMMAND: # //:main [action 'Compiling main.m', configuration: bcb20af40ce0ec204cc0564ea50f3ad16d447e6a99fa61ace3503a019411c0e4, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_admin/eac612c5359b6f8a5bb45f21e493eb6a/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.4 \
    DEVELOPER_DIR=external/xcode_toolchain/developer_dir \
    PATH=external/xcode_toolchain/developer_dir/Toolchains/XcodeDefault.xctoolchain/usr/bin:/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
    ZERO_AR_DATE=1 \
  external/xcode_toolchain/wrapped_clang -arch x86_64 -target x86_64-apple-ios '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -iquote . -iquote bazel-out/ios_x86_64-fastbuild/bin -MD -MF bazel-out/ios_x86_64-fastbuild/bin/_objs/main/arc/main.d -DOS_IOS -fno-autolink -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -fobjc-arc '-mios-simulator-version-min=14.4' -O0 '-DDEBUG=1' -c main.m -o bazel-out/ios_x86_64-fastbuild/bin/_objs/main/arc/main.o)
[1 / 4] 2 actions, 0 running
    [Prepa] Compiling main.m
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//:main, config=BuildConfigurationValue.Key[bcb20af40ce0ec204cc0564ea50f3ad16d447e6a99fa61ace3503a019411c0e4]}, actionIndex=1}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@524aae23, actionLookupKey=ConfiguredTargetKey{label=//:main, config=BuildConfigurationValue.Key[bcb20af40ce0ec204cc0564ea50f3ad16d447e6a99fa61ace3503a019411c0e4]}, willTest=false}', 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//:main, config=BuildConfigurationValue.Key[bcb20af40ce0ec204cc0564ea50f3ad16d447e6a99fa61ace3503a019411c0e4]}, actionIndex=2}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: DEVELOPER_DIR=/Applications/Xcode-12.4.0.app/Contents/Developer and DEVELOPER_DIR=external/xcode_toolchain/developer_dir
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:394)
        at com.google.devtools.build.lib.exec.local.XcodeLocalEnvProvider.rewriteLocalEnv(XcodeLocalEnvProvider.java:110)
        at com.google.devtools.build.lib.sandbox.DarwinSandboxedSpawnRunner.prepareSpawn(DarwinSandboxedSpawnRunner.java:225)
        at com.google.devtools.build.lib.sandbox.AbstractSandboxSpawnRunner.exec(AbstractSandboxSpawnRunner.java:87)
        at com.google.devtools.build.lib.sandbox.SandboxModule$SandboxFallbackSpawnRunner.exec(SandboxModule.java:472)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:240)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:140)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:102)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.beginExecution(CppCompileAction.java:1452)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        ... 4 more
```

**Comment by bytearth** [comment]
same problem with me!
