### ISSUE TITLE
Symlinks in action outputs are not yet supported by --experimental_remote_download_outputs=minimal

### ISSUE THREAD

**Issue by glukasiknuro** [bazelbuild/bazel#13355]
### Description of the problem / feature request:

While building with `--remote_download_minimal` getting a warning:

```
WARNING: Reading from Remote Cache:
java.io.IOException: Symlinks in action outputs are not yet supported by --experimental_remote_download_outputs=minimal
 at com.google.devtools.build.lib.remote.RemoteCache.downloadMinimal(RemoteCache.java:568)
 at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:192)
 at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:135)
 at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:102)
 at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
 at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
 at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
 at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
 at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:859)
 at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1019)
 at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:978)
 at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
 at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
 at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:469)
 at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:845)
 at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:314)
 at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
 at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?
Custom build on top of 3.7

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/6862

### Any other information, logs, or outputs that you want to share?
I assume this warning is benign - in the sense the build still proceeds, although some additional actions need to be executed.

- Are there plans to support symlinks for remote download minimal, or is this intrinsic issue with builds without bytes?

**Comment by coeuvre** [comment]
> Are there plans to support symlinks for remote download minimal

Yes, I will work on this once #12665 is implemented.
