### ISSUE TITLE
starlarkdebug GetChildrenRequest message on rule context restarts server listener and continues starlark thread

### ISSUE THREAD

**Issue by torgil** [bazelbuild/bazel#13387]
### Description of the problem / feature request:

=== rules.bzl ====
```
def _my_rule_impl(ctx):
    output = ctx.actions.declare_file(ctx.label.name + ".txt")
    ctx.actions.write(output, "")
    return [
        DefaultInfo(files = depset([output])),
    ]

my_rule = rule(
    implementation = _my_rule_impl,
)
```
==== BUILD.bazel ====
```
load(":rules.bzl", "my_rule")

my_rule(
    name = "a",
)
```

If we set and wait for a breakpoint at line 4 (return statement) and send a ListFramesRequest we can see the rule context in the response as
```
      binding {
        label: "ctx"
        description: "<rule context for //:a>"
        type: "ctx"
        has_children: true
        id: 1
      }
```

Asking for it's children with GetChildrenRequest causes the debug server to restart and the thread to continue.
```
sequence_number: 4
get_children {
  thread_id: 69
  value_id: 1
}
ERROR: Debug server listener thread died: com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment$MissingDepException: Restart due to missing build info
        at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getWorkspaceStatusValue(CachingAnalysisEnvironment.java:389)
        at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getStableWorkspaceStatusArtifact(CachingAnalysisEnvironment.java:377)
        at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.getStableWorkspaceStatus(StarlarkRuleContext.java:847)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
        at net.starlark.java.eval.MethodDescriptor.callField(MethodDescriptor.java:147)
        at net.starlark.java.eval.CallUtils.getAnnotatedField(CallUtils.java:174)
        at net.starlark.java.eval.Starlark.getAnnotatedField(Starlark.java:750)
        at com.google.devtools.build.lib.starlarkdebug.server.DebuggerSerialization.getChildren(DebuggerSerialization.java:145)
        at com.google.devtools.build.lib.starlarkdebug.server.DebuggerSerialization.getChildren(DebuggerSerialization.java:104)
        at com.google.devtools.build.lib.starlarkdebug.server.ThreadHandler.getChildrenForValue(ThreadHandler.java:261)
        at com.google.devtools.build.lib.starlarkdebug.server.StarlarkDebugServer.getChildren(StarlarkDebugServer.java:212)
        at com.google.devtools.build.lib.starlarkdebug.server.StarlarkDebugServer.handleClientRequest(StarlarkDebugServer.java:172)
        at com.google.devtools.build.lib.starlarkdebug.server.StarlarkDebugServer.lambda$listenForClientRequests$0(StarlarkDebugServer.java:94)
        at java.base/java.lang.Thread.run(Unknown Source)
INFO: Debug server listener thread closed; shutting down debug server and resuming all threads
DEBUG: Closing debug server
DEBUG: Sending debug event:
thread_continued {
  thread_id: 69
}
```

No response to the get children request is sent.

### Feature requests: what underlying problem are you trying to solve with this feature?

The server listener restart makes it not possible to examine rule context during a debug session.
The thread continuation disrupts the debugging session.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unpack this archive:
[ctx_debugissue.tar.gz](https://github.com/bazelbuild/bazel/files/6349826/ctx_debugissue.tar.gz)

Run this command:
`bazel-dev build --experimental_skylark_debug --experimental_skylark_debug_server_port=7200 --keep_state_after_build=false --experimental_skylark_debug_verbose_logging=true`

Connect a socket to port 7200 and send messages according to this log (thread number may vary):
[ctx_debuglog.txt](https://github.com/bazelbuild/bazel/files/6349830/ctx_debuglog.txt)

### What operating system are you running Bazel on?

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

$ # checkout latest git version on bazelbuild/master
$ bazel-4.0.0-linux-x86_64 build --javabase=@bazel_tools//tools/jdk:remote_jdk11 //src:bazel-dev
$ git status
HEAD detached at bazelbuild/master
nothing to commit, working tree clean

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
8d93e47107309ff9c9f7fd17fcb450613b1d86d6
8d93e47107309ff9c9f7fd17fcb450613b1d86d6

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

See files above.

**Comment by brandjon** [comment]
The particular ctx information being retrieved here triggers a skyframe restart that is ordinarily intercepted and retried in normal rule analysis. The debugger doesn't know how to handle a skyframe restart (nor should it). This can probably be fixed by tweaking `ctx` to not attempt to include this info when its children are requested.

**Comment by mdrabic5** [comment]
@bazelbuild/triage

**Comment by brandjon** [comment]
We're doing 2025 planning and improving the Starlark debugger is in scope, so I'm happy to have this stale issue reopened. Picking up on my previous comment, it sounds like there should be some capability to mark certain fields (or at least their values) as invisible to the debugger, e.g. via an annotation in `@StarlarkMethod`.

Tracing through the logic in `DebuggerSerialization#getChildren(ThreadObjectMap, StarlarkValue)`, through `Starlark#getAnnotatedFieldNames` and `CallUtils#buildStarlarkClassDescriptor`, it looks like the proper place to add this might be a `visibleToDebugger` bool in `MethodDescriptor`, which could be used to filter the results seen by the debugger.

**Comment by hvadehra** [comment]
ISTM this may have been indirectly fixed by https://github.com/bazelbuild/bazel/commit/41f7f8aa9a7cc714fe5f12a346b91e04ec9d7561#diff-4c4185a81eaf37656a520362722051be6cb2571556d03451773b05ef632be005R619 which ensures the workspace status value is always already available, and so invoking `ctx.info_file` / `ctx.version_file` no longer cause any skyframe restarts.

**Comment by quic-torgil** [comment]
@mdrabic5 Thanks for triaging this. 

> We're doing 2025 planning and improving the Starlark debugger is in scope

@brandjon  Awesome news. I'll try to also push our debug tools open source as I got poked about that some BazelCons ago.

> ISTM this may have been indirectly fixed by 41f7f8aa9a7cc714fe5f12a346b91e04ec9d7561

@hvadehra I can confirm this with the addition that `--experimental_merged_skyframe_analysis_execution` must be enabled. Disabling that flag makes the problem reappear (on master branch HEAD of today). I managed to find this by bisecting the fix first to commit  1b729a5bb44c244556437ed6a330d25f7e19e3c4

When bisecting old bazel versions that didn't have the ".bazelversion" file checked in, I found the following oneliner useful. It could probably be optimized with an octopus commit.
```
fix_bazel_version () { if git ls-tree HEAD | grep -q .bazelversion; then   echo "$(cat .bazelversion)"; else for version in `git tag | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' | sort -Vr`; do if ! git merge-base --is-ancestor HEAD $version; then break; fi; done; echo "$version"  | tee .bazelversion; fi; }
```

**Comment by quic-torgil** [comment]
We managed to push through the debugger to a pull request: #24814

This also means you can run this script (with the workspace in the description) to reproduce this issue:

```
import argparse
import os
from debugger import StarlarkDebugger

parser = argparse.ArgumentParser(description="Reproduce that bug")
StarlarkDebugger.add_parser_arguments(parser)
args = parser.parse_args()
dbg = StarlarkDebugger.from_parser_args(args)
dbg.initialize()
dbg.set_breakpoints(f"{os.getcwd()}/rules.bzl:4", "")
dbg.continue_execution(wait_for_breakpoint=True)
[thread] = [t for t in dbg.list_threads() if t.paused and t.pause_reason == "HIT_BREAKPOINT"]
frames = dbg.list_frames(thread.id)
print(frames[0].evaluate("ctx.version_file"))  # will fail here
```
