### ISSUE TITLE
compiling from source gives java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by schristley** [bazelbuild/bazel#1341]
Compiling from git source and I'm not able to get past this java error.

```
$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
WARNING: /tmp/bazel.Z6YTLTV2/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.Z6YTLTV2/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Loading package: src
unable to create new native thread

bazel ran out of memory and crashed.
unable to create new native thread

bazel ran out of memory and crashed.
unable to create new native thread

bazel crash in async thread:
bazel crash in async thread:
bazel crash in async thread:
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Building output/bazel
```

I managed to get past the first OutOfMemoryError with this change:

```
--- a/scripts/bootstrap/compile.sh
+++ b/scripts/bootstrap/compile.sh
@@ -145,7 +145,7 @@ function java_compilation() {
     cat "$paramfile" >&2
   fi
 
-  run "${JAVAC}" -classpath "${classpath}" -sourcepath "${sourcepath}" \
+  run "${JAVAC}" -J-Xms256m -J-Xmx512m -classpath "${classpath}" -sourcepath "${sourcepath}" \
       -d "${output}/classes" -source "$JAVA_VERSION" -target "$JAVA_VERSION" \
       -encoding UTF-8 "@${paramfile}"
```

But now it cannot build Bazel with Bazel, I saw another mention of this error so tried restricting the number of jobs with this change, but it had no effect.  Any ideas?

```
--- a/scripts/bootstrap/compile.sh
+++ b/scripts/bootstrap/compile.sh
@@ -273,7 +273,7 @@ function bootstrap_build() {
       --workspace_directory=${PWD} \
       --nodeep_execroot --nofatal_event_bus_exceptions \
       build \
-      --ignore_unsupported_sandboxing \
+      --ignore_unsupported_sandboxing --jobs=50 \
       --startup_time=329 --extract_data_time=523 \
       --rc_source=/dev/null --isatty=1 \
       --ignore_client_env \
```

```
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
```

**Comment by meteorcloudy** [comment]
Can you add following to your ~/.bazelrc file, then try to build Bazel with Bazel again:
```
--host_jvm_args="-Xms256m"
--host_jvm_args="-Xmx512m"
```
`bazel help startup_options` might give you more information.

**Comment by meteorcloudy** [comment]
And can you tell us which architecture you are running on?

**Comment by schristley** [comment]
x86_64 architecture

I added `-Xmx512m` but it gave the same error, java.lang.OutOfMemoryError: unable to create new native thread

**Comment by michajlo** [comment]
Your ulimit settings may be restricting the number of threads (ulimit -a)? Adjusting thread stack size may also be of interest (-Xss).

**Comment by schristley** [comment]
It is not a large limit at 150. I saw a mention of this on another bazel forum and thus why I put the `--jobs=50` as that seemed to work for them.

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514788
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 150
virtual memory          (kbytes, -v) 8388608
file locks                      (-x) unlimited
```

I added `-Xss2m` to scripts/bootstrap/compile.sh but no change.

**Comment by michajlo** [comment]
Can you up the user processes to something like 1024 and see how it goes?

**Comment by schristley** [comment]
I'm not able to increase the limit, however I tried running the compile on a compute node (versus the login node) and it has a much higher limit at 8192. This did the trick and got past the java error, however I'm getting a new error now which is similar to what reported in #1251 

```
No toolchain found for cpu 'piii'. Valid cpus are: [
  k8,
  armeabi-v7a,
].
```

`uname -m` returns `x86_64` so not sure why it's thinking `piii`

**Comment by schristley** [comment]
my bad, I was using 32 vs 64-bit java, installing 64-bit java got me past that last error, onto the next!

**Comment by schristley** [comment]
In my environment, I'm using a gcc that isn't at the default /usr/bin/gcc location. I've seen numerous issues about this but haven't found the right answer. The compile error is

```
ERROR: /work/03898/schristl/stampede/tools/tensorflow/bazel/src/main/tools/BUILD:26:1: C++ compilation of rule '//src/main/tools:build-runfiles' failed: gcc failed: error executing command 
  (cd /tmp/bazel.XhYv3i0y/out/bazel && \
  exec env - \
    PATH=/opt/apps/gcc4_9/mvapich2/2.1/bin:/opt/apps/gcc/4.9.1/bin:/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/bin:/opt/apps/python/2.7.3-epd-7.3.2:modules/bin:/opt/apps/python/2.7.3-epd-7.3.2/bin:/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/bin:/opt/apps/xalt/0.6/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/ofed/bin:/opt/ofed/sbin:. \
    TMPDIR=/tmp \
  /opt/apps/gcc/4.9.1/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/opt/apps/gcc/4.9.1/bin -B/usr/bin -B/opt/apps/gcc/4.9.1/lib -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.d -c src/main/tools/build-runfiles.cc -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/opt/apps/gcc/4.9.1/libexec/gcc/x86_64-unknown-linux-gnu/4.9.1/cc1plus: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory
```

The issue is simple, the cc1plus program is not able to run because it cannot find one of its shared llibraries. This works normally because LD_LIBRARY_PATH is set, but in this command that bazel run, it is doing "exec env" and not passing appropriate LD_LIBRARY_PATH. For example, if I manually do the gcc command

```
/opt/apps/gcc/4.9.1/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/opt/apps/gcc/4.9.1/bin -B/usr/bin -B/opt/apps/gcc/4.9.1/lib -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.d -c src/main/tools/build-runfiles.cc -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o
```

it runs fine without error.  How I can have bazel set LD_LIBRARY_PATH?

**Comment by meteorcloudy** [comment]
I think you can add a linker_flag into CROSSTOOL, `linker_flag: "-L<searchdir>"`
Then run compile.sh to build Bazel again.

**Comment by schristley** [comment]
Nope, that solves the wrong problem, `-L<searchdir>` tells the linker where to look for library files, the issue is library the linker program itself needs just so it can be executed, i.e. `ldd cc1plus` has a line
```
libcloog-isl.so.4 => /opt/apps/gcc/4.9.1/lib/libcloog-isl.so.4 (0x00002b1b3f1de000)
```

What is needed is for LD_LIBRARY_PATH to be set properly when gcc is run, specifically the exec line above needs to look like this.

```
cd /tmp/bazel.74lUETaY/out/bazel && \
  exec env - \
    PATH=/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/bin:/opt/apps/python/2.7.3-epd-7.3.2:modules/bin:/opt/apps/python/2.7.3-epd-7.3.2/bin:/opt/apps/gcc4_9/mvapich2/2.1/bin:/opt/apps/gcc/4.9.1/bin:/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/bin:/opt/apps/xalt/0.6/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/ofed/bin:/opt/ofed/sbin:. \
    LD_LIBRARY_PATH=/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/lib:/opt/apps/python/2.7.3-epd-7.3.2/lib:/opt/apps/gcc4_9/mvapich2/2.1/lib:/opt/apps/gcc4_9/mvapich2/2.1/lib/shared:/opt/apps/gcc/4.9.1/lib64:/opt/apps/gcc/4.9.1/lib:/work/03898/schristl/stampede/tools/java/jdk1.8.0_92/lib \
    TMPDIR=/tmp \
  /opt/apps/gcc/4.9.1/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/opt/apps/gcc/4.9.1/bin -B/usr/bin -B/opt/apps/gcc/4.9.1/lib -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-std=c99' -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/network-tools/src/main/tools/network-tools.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/network-tools/src/main/tools/network-tools.pic.d -c src/main/tools/network-tools.c -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/network-tools/src/main/tools/network-tools.pic.o
```

Can you tell me what code produces this output command?  I've tried finding it in the code but it is not readily apparent. If I can find the place in the code, then maybe I can insert it myself.

**Comment by meteorcloudy** [comment]
Oh, I see. I think it's here
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/standalone/StandaloneSpawnStrategy.java#L166

**Comment by philwo** [comment]
@schristley We recently came across a number of failing builds due to LD_LIBRARY_PATH being set in the environment and Bazel removing it.

Arguably, LD_LIBRARY_PATH is considered a "debug flag" by e.g. The Linux Documentation Project (http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) and shouldn't be used during normal operation, but that ship has sailed - there are way too many envs that rely on this :)

I'm trying to get a patch in that makes Bazel not remove this from the environment and will update this bug then.
