### ISSUE TITLE
java_plugin attribute data produces more than one prerequisite

### ISSUE THREAD

**Issue by jdai8** [bazelbuild/bazel#13475]
### Description of the problem / feature request:

Passing multiple files to `java_plugin`'s `data` attribute fails with an internal exception:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//redacted/foo/bar, config=BuildConfigurationValue.Key[e6a64f618ec822ee8e75ec21c2f0616dff9adcd5433fba69efc073c6f370797e]}' (requested by nodes 'ConfiguredTargetKey{label=//redacted/foo/bar, config=BuildConfigurationValue.Key[e6a64f618ec822ee8e75ec21c2f0616dff9adcd5433fba69efc073c6f370797e]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: java_plugin attribute data produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteConfiguredTargetAndData(RuleContext.java:989)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:976)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:966)
	at com.google.devtools.build.lib.rules.java.JavaCommon.getJavaPluginInfoProvider(JavaCommon.java:814)
	at com.google.devtools.build.lib.rules.java.JavaLibrary.init(JavaLibrary.java:176)
	at com.google.devtools.build.lib.rules.java.JavaPlugin.create(JavaPlugin.java:34)
	at com.google.devtools.build.lib.rules.java.JavaPlugin.create(JavaPlugin.java:22)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

I can work around this by wrapping the data files in a filegroup.

For example, this fails:
```
java_plugin(
  name = "foo",
  data = ["one", "two"],
)
```

But this seems to work:
```
filegroup(
  name = "my_two_files",
  srcs = ["one", "two"],
)

java_plugin(
  name = "foo",
  data = [":my_two_files"],
)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unsure if this is a feature request or a bug. The workaround is pretty easy, but wrapping in a filegroup feels like an unnecessary limitation.

If this is working as intended, a better error message why this is intended would be nice.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

My use case is trying to support lombok's [configuration](https://projectlombok.org/features/configuration). This is hierarchical (a lombok.config at the root of the repo can be overriden by sub-projects' lombok.config). These config files are read by the annotation processor, which suggests the need for something like:
```
java_plugin(
  name = "my_project_lombok"
  data = [
    "//:lombok.config",
    "lombok.config",
  ],
  ...
)

**Comment by comius** [comment]
I'm confirming this is a bug. Since it has an easy workaround I've set it to P3 - will be accepting fixes.
