### ISSUE TITLE
Proxy address 127.0.0.1:7890 is not a valid URL

### ISSUE THREAD

**Issue by alwaysblue3** [bazelbuild/bazel#13542]
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I want to use bazel to generate a Xcode project.I have to use vpn.But I encounter one problem.When I run Tulsi,select bazel 4.1.0 to generate Xcode project,There is a error tip "[Proxy address 127.0.0.1:7890 is not a valid URL](url)".

### Feature requests: what underlying problem are you trying to solve with this feature?

> I have to use a proxy.Even I remove this proxy,the error is still there. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Download mediapipe examples from "https://google.github.io/mediapipe/getting_started/ios.html".

### What operating system are you running Bazel on?

> macOS Big Sur 11.3.1

### What's the output of `bazel info release`?

> INFO: Repository bazel_skylib instantiated at:
  /Users/wf/mediapipe/WORKSPACE:5:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp15567454784139718445/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp15567454784139718445/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp15567454784139718445/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL

Another command (pid=16141) is running. Waiting for it to complete on the server (server_pid=813)...
INFO: Repository bazel_skylib instantiated  #at:
  /Users/wf/mediapipe/WORKSPACE:5:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp8471450665678725493/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp8471450665678725493/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp8471450665678725493/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL

ERROR: An error occurred during the fetch of repository 'bazel_skylib':
ERROR: Error fetching repository: Traceback (most recent call last):
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp13032310249034339567/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
ERROR: Error fetching repository: Traceback (most recent call last):
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp14068454732888151453/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
Another command (pid=16141) is running. Waiting for it to complete on the server (server_pid=813)...
Another command (pid=16150) is running. Waiting for it to complete on the server (server_pid=813)...
Another command (pid=16191) is running. Waiting for it to complete on the server (server_pid=813)...
Another command (pid=16244) is running. Waiting for it to complete on the server (server_pid=813)...
INFO: Repository bazel_skylib instantiated at:
  /Users/wf/mediapipe/WORKSPACE:5:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp13658324801953742942/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp13658324801953742942/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp13658324801953742942/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL

ERROR: An error occurred during the fetch of repository 'bazel_skylib':
ERROR: Error fetching repository: Traceback (most recent call last):
ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz] to /private/var/tmp/_bazel_wf/85c13641f28d814728914c9a6a5c7452/external/bazel_skylib/temp5227800042876204690/bazel-skylib-1.0.3.tar.gz: Proxy address 127.0.0.1:7890 is not a valid URL
General failure: Bazel aspects could not be built.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> The version of bazel is 4.1.0.

###  Have you found anything relevant by searching the web?

> https://github.com/bazelbuild/bazel/pull/2007
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> See the attachment.

**Comment by alwaysblue3** [comment]
![bazelFail](https://user-images.githubusercontent.com/52742890/120137755-92e56980-c207-11eb-94a7-c9511699a7db.png)

**Comment by alwaysblue3** [comment]
Is there any way I can download this bazel_skylib repository by hand.Then I put it to somewhere.I can not find the right folder。Because this folder is tempory.It will be deleted when next time run.
