### ISSUE TITLE
Bazel CI: Envoy broken with Bazel@HEAD

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#13549]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2054#7e314e9b-848f-4a7c-82b9-e58d4bdf2fed

```
(04:03:29) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dbda33db3229dc32070b4de3da7e6888/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
		ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dbda33db3229dc32070b4de3da7e6888/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
		rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dbda33db3229dc32070b4de3da7e6888/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
		apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
```

Culprit Found: https://github.com/bazelbuild/bazel/commit/d6830672311d54c8072e0b48c440c2edde65314d

/cc @allevato

**Comment by coeuvre** [comment]
PR used to update rules_apple in Envoy is merged but the tests are still failing. https://github.com/envoyproxy/envoy/pull/16404

**Comment by allevato** [comment]
rule_factory.bzl shows that the 0.31.2 tag on bazelbuild/rules_apple **doesn't** reference `apple_common.objc_proto_aspect` at the location indicated above: https://github.com/bazelbuild/rules_apple/blob/0.31.2/apple/internal/rule_factory.bzl

I also downloaded the tarball and it's consistent with that change. Is the Envoy build getting the wrong release of the rules somehow?

**Comment by keith** [comment]
I imagine Envoy is getting a version through some transitive dependency that isn't what they expect

**Comment by meteorcloudy** [comment]
https://github.com/envoyproxy/envoy/issues/16542 is blocking Bazel CI from updating the last green commit of Envoy, so even  envoyproxy/envoy#16404 is merged, we are still testing with an older commit of envoy in the downstream pipeline.

We should probably get https://github.com/envoyproxy/envoy/issues/16542 fixed first.

**Comment by philwo** [comment]
@coeuvre @meteorcloudy Who would be a good assignee for this issue?

**Comment by meteorcloudy** [comment]
Envoy is green in downstream again~
