### ISSUE TITLE
Bazel 4.1 fails to desugar kotlinx-coroutines-core-jvm:1.5.0

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/bazel#13553]
### Description of the problem / feature request:

Bazel 4.1 fails to desugar `kotlinx-coroutines-core-jvm:1.5.0` producing the following exception:

```console
ERROR: /private/var/tmp/_bazel_blee/f1f2afba98d721e05bb8ec203ca691d8/external/maven/BUILD:57:11: Desugaring v1/https/repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.jar for Android failed: (Exit 1): desugar_java8 failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/desugar_java8 ... (remaining 1 argument(s) skipped)
java.lang.TypeNotPresentException: Type sun.misc.SignalHandler not present
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:97)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:69)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)
        at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)
        at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)
Caused by: java.lang.ClassNotFoundException: Class sun.misc.SignalHandler not found
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)
        ... 18 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Steps to reproduce can be found here https://github.com/Bencodes/bazel_issue_13553

Example failure: https://github.com/Bencodes/bazel_issue_13553/runs/2742154274?check_suite_focus=true#step:5:44

### What operating system are you running Bazel on?

macOs 10.15.7

### What's the output of `bazel info release`?

release 4.1.0

### Any other information, logs, or outputs that you want to share?

java-runtime: OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode) by Azul Systems, Inc.

**Comment by Bencodes** [comment]
Tested against HEAD and it also fails

**Comment by alexjlockwood** [comment]
This issue appears to be a blocker for adopting Jetpack Compose in Bazel projects. (The latest 1.0.0-beta08 release requires Kotlin 1.5.10 and Kotlin coroutines 1.5.0).

**Comment by cgruber** [comment]
A related issue occurred in kotlin/kotlinx.coroutines#2046. The workaround there was to make proguard not spew typenotfound errors like so.

```
-dontwarn java.lang.instrument.ClassFileTransformer
-dontwarn sun.misc.SignalHandler
-dontwarn java.lang.instrument.Instrumentation
-dontwarn sun.misc.Signal
```

This case seems to be different - the desugarer blows up, not proguard, but it may be a clue on the hunt.

I know we ran into inconsistencies between the bazel desugarer and the desugaring in the android toolchain, and in some cases resolved things by calling out to d8 in a custom toolchain, but it's not clear whether the problems we had were connected to this one. I know gradle uses d8's desugaring, and may simply have special case logic around sun.misc stuff, which I think gets magically swapped by Android's jvm impl anyway (or things that rely on it are swizzled in)

**Comment by kevin1e100** [comment]
The original report seems to indicate that desugaring is run on JDK11. Does this also happen when using a JDK8 as host JDK?

**Comment by Kernald** [comment]
I just tried with a JDK8:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

And got what looks like the exact same stacktrace:
```
ERROR: /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/external/maven/BUILD:8498:11: Desugaring external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotli
nx/kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.jar for Android failed: (Exit 1): desugar_java8 failed: error executing command bazel-out/k8-py2-opt-exec-2B5CBBC6/bin
/external/bazel_tools/tools/android/desugar_java8 ... (remaining 1 argument(s) skipped)                                                                                                      
java.lang.TypeNotPresentException: Type sun.misc.SignalHandler not present                                                                                                                   
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:97)                                                                                                 
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:69)                                                                                              
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)                                                                                              
        at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)                                                                                                        
        at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)                                                                                            
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)                                                
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)                                                                                                                     
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)                                                                                                                   
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)                                                                                                                        
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)                                                                                         
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)                                                                                                       
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)                                                                                           
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)                                                                                                          
Caused by: java.lang.ClassNotFoundException: Class sun.misc.SignalHandler not found                                                                                                          
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)                                                                               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)                                                                                                                   
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                   
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)                                                                                                 
        ... 18 more                                                                                     
```

Interestingly enough, I had to use `--keep_going` as I was otherwise hitting a different desugar-related exception (which I also get with a JDK11):
```
ERROR: /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/external/maven/BUILD:8447:11: Desugaring external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotli
nx/kotlinx-coroutines-android/1.5.0/kotlinx-coroutines-android-1.5.0.jar for Android failed: Worker process did not return a WorkResponse:                                                   
                                                                                                                                                                                             
---8<---8<--- Start of log, file at /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/bazel-workers/worker-24-Desugar.log ---8<---8<---                             
Jun 10, 2021 4:36:03 PM com.google.devtools.build.android.desugar.Desugar runPersistentWorker                                                                                                
INFO: Processing Request success:                                                                                                                                                            
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation                                                                                                    
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)                                                                                                                       
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)                                                                                                                
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)                                                                                                                 
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:67)                                                                               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)                                                                                                                   
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                   
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)                                                                                                 
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:60)                                                                                              
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)                                                                                              
        at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)                                                                                                        
        at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)                                                                                            
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)                                                
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)                                                                                                                     
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)                                                                                                                   
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)                                                                                                                        
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)                                                                                         
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)                                                                                                       
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)                                                                                           
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)                                                                                                          
Caused by: java.lang.ClassNotFoundException: Class kotlin.coroutines.Continuation not found                                                                                                  
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)                                                                               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)                                                                                                                   
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                   
        ... 25 more                                                                                                                                                                          
---8<---8<--- End of log ---8<---8<---                                                                           
```

**Comment by kevin1e100** [comment]
The second error suggests that kotlin-stdlib.jar isn't on the classpath of kotlinx-coroutines-core-jvm-1.5.0.jar. You may need to add the former as a dep to the import of the latter.  Could you also possibly share the output you get from including `--verbose_failures` in your Bazel command?

**Comment by Kernald** [comment]
> The second error suggests that kotlin-stdlib.jar isn't on the classpath of kotlinx-coroutines-core-jvm-1.5.0.jar. You may need to add the former as a dep to the import of the latter.

Wouldn't `kotlin.coroutines.Continuation` be in `kotlinx-coroutines-core-jvm` rather than `kotlin-stdlib`? Either way, I don't have an easy way to add a dependency to the classpath by using `rules_jvm_external` as far as I'm aware - I tried wrapping every use of `kotlinx-coroutines-core-jvm` that I have in a `java_library` target depending on `kotlin-stdlib`, but it doesn't help.

> Could you also possibly share the output you get from including `--verbose_failures` in your Bazel command?

This is what I get for the `sun.misc.SignalHandler` not found exception:
```
ERROR: /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/external/maven/BUILD:8498:11: Desugaring external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.jar for Android failed: (Exit 1): desugar_java8 failed: error executing command 
  (cd /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/execroot/fr_enoent && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/k8-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/desugar_java8 @bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/_dx/org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm/kotlinx-coroutines-core-jvm-1.5.0.jar_desugared.jar-0.params)
Execution platform: @local_config_platform//:host
java.lang.TypeNotPresentException: Type sun.misc.SignalHandler not present
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:97)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:69)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)
        at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)
        at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)
Caused by: java.lang.ClassNotFoundException: Class sun.misc.SignalHandler not found
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)
        ... 18 more
```

And not much more for the continuation related one:
```
ERROR: /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/external/maven/BUILD:8447:11: Desugaring external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotli
nx/kotlinx-coroutines-android/1.5.0/kotlinx-coroutines-android-1.5.0.jar for Android failed: Worker process did not return a WorkResponse:                                                   
                                                                                                                                                                                             
---8<---8<--- Start of log, file at /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/bazel-workers/worker-41-Desugar.log ---8<---8<---                             
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation                                                                                                    
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)                                                                                                                       
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)                                                                                                                
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)                                                                                                                 
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:67)                                                                               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)                                                                                                                   
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                   
        at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)                                                                                                 
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:60)                                                                                              
        at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)                                                                                              
        at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)                                                                                                        
        at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)                                                                                            
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)                                                
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)                                                                                                    
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)                                                                                                                     
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)                                                                                                                   
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)                                                                                                                        
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)                                                                                         
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)                                                                                                       
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)                                                                                               
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)                                                                                           
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)                                                                                                          
Caused by: java.lang.ClassNotFoundException: Class kotlin.coroutines.Continuation not found                                                                                                  
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)                                                                               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)                                                                                                                   
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                                                   
        ... 25 more                                                                                                                                                                          
---8<---8<--- End of log ---8<---8<---                                                                   
```

**Comment by kevin1e100** [comment]
> Wouldn't kotlin.coroutines.Continuation be in kotlinx-coroutines-core-jvm rather than kotlin-stdlib?

Note the missing `x` in `kotlin.coroutines.Continuation`: to my knowledge this class is in the stdlib.

Thanks for the `--verbose_failures` output, which I had unfortunately failed to anticipate wouldn't be enough: I'm interested in the contents of the `@...` params file included in the printed command line, i.e., `bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/_dx/org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm/kotlinx-coroutines-core-jvm-1.5.0.jar_desugared.jar-0.params` in the shared output.  Could you share the contents of that file, possibly?

**Comment by Bencodes** [comment]
>  Could you share the contents of that file, possibly?

This is what i'm seeing in the param file for `kotlinx-coroutines-core-jvm`

```console
❯ cat bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/_dx/org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm/kotlinx-coroutines-core-jvm-1.5.0.jar_desugared.jar-0.params
--input
external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.jar
--output
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/_dx/org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm/kotlinx-coroutines-core-jvm-1.5.0.jar_desugared.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.0/header_kotlinx-coroutines-core-jvm-1.5.0.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.0/header_kotlin-stdlib-jdk8-1.5.0.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/annotations/13.0/header_annotations-13.0.jar
--classpath_entry
bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.0/header_kotlin-stdlib-jdk7-1.5.0.jar
--bootclasspath_entry
external/androidsdk/platforms/android-29/android.jar
--emit_dependency_metadata_as_needed
```

**Comment by kevin1e100** [comment]
Aha thanks. It's _possible_ that `--bootclasspath_entry external/androidsdk/platforms/android-29/android.jar` is causing confusion here. All else equal it may be better to supply a JDK 8 bootclasspath, because that is what the input Jar was presumably compiled against. I'm not sure how/why it's using an `android.jar` in the first place, and this may well not be the issue, so I'm not sure if I'm helping or hurting here, but if someone has a way to try using a different bootclasspath I'd hope that that would allow making progress in diagnosing the issue.

**Comment by geaden** [comment]
Is there way to workaround the issue? Can we add `sun.misc.SignalHandler` into  https://github.com/google/desugar_jdk_libs/tree/master/jdk11/src/java.base/share/classes/sun/misc and use updated version of the libs?

**Comment by Kernald** [comment]
https://github.com/Bencodes/bazel_issue_13553/pull/1 is a working workaround.

**Comment by geaden** [comment]
> [Bencodes/bazel_issue_13553#1](https://github.com/Bencodes/bazel_issue_13553/pull/1) is a working workaround.

Thanks a lot!

**Comment by nohe427** [comment]
Reproduced on release 5.2.0

**Comment by ahumesky** [comment]
Is this still an issue with the D8-based desugarer, or with the starlark android rules? We can reopen and transfer to rules_android if so
