### ISSUE TITLE
http_archive looks for netrc file inside external dependency rather than local file system

### ISSUE THREAD

**Issue by jiawen** [bazelbuild/bazel#13662]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

As the title says, http_archive appears to have a bug where it looks for netrc inside the external dependency, rather than in the local workspace.

### Feature requests: what underlying problem are you trying to solve with this feature?

The ability to use with http_archive a custom netrc file in the local workspace instead of in my home directory. Current behavior makes it effectively unusable.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE contents:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "halide-x86-64-osx",
    build_file = "//third_party/halide:halide.BUILD",
    netrc = "artifactory.netrc",
    sha256 = "e83d2efa273c92ba8c14da7ac3fda88a25c8970c2099befa92caee67573d9681",
    strip_prefix = "Halide-12.0.1-x86-64-osx",
    url = "http://localhost",  # Doesn't actually matter - bug manifests before actually parsing this.
)
```

BUILD contents:

```
cc_library(
    name = "my_lib",  # No sources doesn't matter - bug manifests when trying to resolve the dependency
    deps = ["@halide-x86-64-osx//:halide"],
)
```

`artifactory.netrc` can be an empty file - its contents don't matter when reproducing this bug.

Build result:

```
$ bazel build :my_lib
INFO: Repository halide-x86-64-osx instantiated at:
  /Users/jiawen/tmp/y/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'halide-x86-64-osx':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 109, column 21, in _http_archive_impl
		auth = _get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 79, column 27, in _get_auth
		netrc = read_netrc(ctx, ctx.attr.netrc)
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 215, column 24, in read_netrc
		contents = ctx.read(filename)
Error in read: java.io.FileNotFoundException: /private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/halide-x86-64-osx/artifactory.netrc (No such file or directory)
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 109, column 21, in _http_archive_impl
		auth = _get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 79, column 27, in _get_auth
		netrc = read_netrc(ctx, ctx.attr.netrc)
	File "/private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 215, column 24, in read_netrc
		contents = ctx.read(filename)
Error in read: java.io.FileNotFoundException: /private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/halide-x86-64-osx/artifactory.netrc (No such file or directory)
ERROR: /Users/jiawen/tmp/y/BUILD:1:11: //:my_lib depends on @halide-x86-64-osx//:halide in repository @halide-x86-64-osx which failed to fetch. no such package '@halide-x86-64-osx//': java.io.FileNotFoundException: /private/var/tmp/_bazel_jiawen/d9402db5073cf8cd36f8900f74d53c1a/external/halide-x86-64-osx/artifactory.netrc (No such file or directory)
ERROR: Analysis of target '//:my_lib' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.229s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 2 targets configured)
```

### What operating system are you running Bazel on?

MacOS Big Sur

### What's the output of `bazel info release`?

release 4.1.0-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

<Redacted>

###  Have you found anything relevant by searching the web?

No, http_archive with custom netrc files seems to be not broadly used.

### Any other information, logs, or outputs that you want to share?

No - it is clear that the path to the netrc file is somehow read from the wrong context. The implementation is here:

[_get_auth](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L79) calls [read_netrc](https://github.com/bazelbuild/bazel/blob/786b418d1fcd1ad1df66237be45682624007ed2e/tools/build_defs/repo/utils.bzl#L247) with a context but I'm not well versed enough in Bazel to fix this.

**Comment by dmivankov** [comment]
interestingly .netrc attribute is a string so `//:artifactory.netrc` probably wouldn't work
https://github.com/bazelbuild/bazel/blob/4.1.0/tools/build_defs/repo/http.bzl#L79 - gets passed from here
https://github.com/bazelbuild/bazel/blob/4.1.0/tools/build_defs/repo/utils.bzl#L203 - to here as filepath
it then proceeds to `repository_ctx.read(filename)` and reads from external repository relative location

rules_jvm_external have some hacks around being able to combine HOME netrc with custom lines and auth patterns, so maybe a hack like `../YOUR_WORKSPACE_NAME/artifactory.netrc` may work
similar to https://github.com/bazelbuild/rules_jvm_external/blob/8feca27d7efed5a3343f8dbfe1199987598ca778/coursier.bzl#L444
doesn't look future-proof though

**Comment by jiawen** [comment]
I'm happy to take this on as my first contribution to Bazel. Quick question - how do I run a subset of the tests found in [starlark_repository_test.sh](https://github.com/bazelbuild/bazel/blob/c2bdd034014f66ce14529cc353cda18a32320f6c/src/test/shell/bazel/starlark_repository_test.sh)?

In particular, I'd like to run individual tests such as `test_netrc_reading()` and its siblings in isolation with `bazel test`. 

I tried various `--test_filter` regexs and even went as far as commenting out parts of the shell script's code but it seemed to introduce more bugs.

Thanks!

**Comment by jiawen** [comment]
> interestingly .netrc attribute is a string so `//:artifactory.netrc` probably wouldn't work https://github.com/bazelbuild/bazel/blob/4.1.0/tools/build_defs/repo/http.bzl#L79 - gets passed from here https://github.com/bazelbuild/bazel/blob/4.1.0/tools/build_defs/repo/utils.bzl#L203 - to here as filepath it then proceeds to `repository_ctx.read(filename)` and reads from external repository relative location
> 
> rules_jvm_external have some hacks around being able to combine HOME netrc with custom lines and auth patterns, so maybe a hack like `../YOUR_WORKSPACE_NAME/artifactory.netrc` may work similar to https://github.com/bazelbuild/rules_jvm_external/blob/8feca27d7efed5a3343f8dbfe1199987598ca778/coursier.bzl#L444 doesn't look future-proof though

I think the Right Thing to do is basically turn `netrc` from an `attr.string` to an `attr.label(allow_single_file=True)`. I haven't tried this but I think that would allow `ctx.file` to access its file contents given a fully qualified `Label`.

**Comment by jiawen** [comment]
Just submitted PR 14498.

**Comment by chronicc** [comment]
Hello, I currently experience this problem on bazel 5.2.0. This issue is open for nearly a year now. Using authentication for archive downloads seems like a commonly used concept to me. Is there another way of solving this? Otherwise i have the feeling this bug does not get the attention it deserves.

**Comment by Wyverald** [comment]
The netrc attribute currently works well with an absolute path. Would that cover your use case? I agree that having it fail for a relative path is not ideal, but fixing it is also not super easy since there's currently no API in repository_ctx to resolve a path relative to the main repo.

We can't make the type of the attribute a label directly since that would make it impossible to supply an absolute path.

**Comment by chronicc** [comment]
@Wyverald Understandable. I'm currently using the netrc in the home directory of the user which forces every user of the repository to configure it by themselfes. This is a workable solution but not the best when I want to easen the usage of bazel in the company.

Would it be possible to provide a `netrc_label` attribute in addition to the `netrc` attribute? This way the current implementation stays the way it is currently used by bazel users and allows using labels for users that like to add the netrc to the bazel workspace. It might not be the most beautiful solution but it is something, that can be worked with.

**Comment by jiawen** [comment]
I authored the original PR that changed the current attr to a Label, but it had to be rolled back due to downstream breakages. I'm using a similar workaround (forcing all users to put credentials into their home directories) so haven't prioritized a proper fix.

@Wyverald if it's acceptable to you, I can try and find cycles to add a `netrc_label` attr, making it mutually exclusive with the current `netrc` attr. How much test coverage do you expect it to require? I'm happy to write some but I don't work with Bazel internal testing shell scripts day to day and it's a big context switch :).
