### ISSUE TITLE
Bazel 3.7.1 fails to desugar org.mockito:mockito-core:3.11.2 with android test

### ISSUE THREAD

**Issue by Nikolas-LFDesigns** [bazelbuild/bazel#13684]
### Description of the problem / feature request:

Trying to run Bazel android test which starts to desugar mockito-core, which is provided inside a mockito-android. Fails on finding pure-JVM class (java.lang.instrument.ClassFileTransformer) required by pure-JVM library (log below).
The same setup but in Gradle perfectly circumvents the problem (by possibly ignoring checks for this exact class, see this [link](https://developer.android.com/studio/preview/features?hl=da-DK&%3Bskip_cache=true&skip_cache=true#r8-missing-class-warning)).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Try to run `//app/src/androidTest/java/com/test/myapplication:main_test` test on this repo:
https://github.com/Nikolas-LFDesigns/mockito-3-bazel-example

### What operating system are you running Bazel on?
Ubuntu 21.04

### What's the output of `bazel info release`?
release 3.7.1

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/13553
sounds very related but seem still unsolved.

### Any other information, logs, or outputs that you want to share?

Build failure:
```
ERROR: /home/l_f/.cache/bazel/_bazel_l_f/e810e7b62577a3b59b8845a708b42f0a/external/org_mockito_mockito_core/BUILD:11:12: Desugaring org_mockito_mockito_core/mockito-core-3.11.2.jar for Android failed (Exit 1): desugar_java8 failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/desugar_java8 ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox desugar_java8 failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/desugar_java8 ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.NullPointerException: Couldn't find interface java/lang/instrument/ClassFileTransformer implemented by org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1227)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.stubMissingDefaultAndBridgeMethods(DefaultMethodClassFixer.java:304)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.stubMissingDefaultAndBridgeMethods(DefaultMethodClassFixer.java:283)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:170)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:127)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:153)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
	at com.google.devtools.build.android.desugar.nest.NestDesugaring.visitEnd(NestDesugaring.java:171)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:374)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:544)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)
	at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:956)
```

**Comment by ahumesky** [comment]
bazel 6.0 and recent pre-releases use D8-based desugaring, so it's probably worth a try with a recent pre-release to see if this is still a problem.
