### ISSUE TITLE
bazel run failed on abseil-hello

### ISSUE THREAD

**Issue by weiby3** [bazelbuild/bazel#13723]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel run failed

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone https://github.com/abseil/abseil-hello/tree/master/bazel-hello
and run `bazel run //:hello_main -- a_commandline_arg`

### What operating system are you running Bazel on?

archlinux latest

  ### What's the output of `bazel info release`?

release 4.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

NO

### Any other information, logs, or outputs that you want to share?

output:
```
➜  bazel-hello git:(master) bazel run //:hello_main -- a_commandline_arg
INFO: Analyzed target //:hello_main (21 packages loaded, 175 targets configured).
INFO: Found 1 target...
[0 / 5] [Prepa] Creating source manifest for //:hello_main
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.google.devtools.build.lib.unsafe.StringUnsafe
        at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:118)
        at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:111)
        at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction$ParamFileWriter.writeOutputFile(ParameterFileWriteAction.java:175)
        at com.google.devtools.build.lib.exec.FileWriteStrategy.beginWriteOutputToFile(FileWriteStrategy.java:58)
        at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:66)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by sventiffe** [comment]
I cannot reproduce the issue. I've followed the instructions from https://github.com/abseil/abseil-hello/tree/master/bazel-hello and installed 4.1.0, cloned the repo with `git clone https://github.com/abseil/abseil-hello` and ran bazel and it succeeded.

Please try with a clean install of Bazel and reopen the issue if it persists.

**Comment by weiby3** [comment]
I try `bazel clean --expunge` and `bazel run //:hello_main -- a_commandline_arg`, still got the same result.
bazel is installed via pacman, `pacman -S bazel`, with latest clang and gcc.

**Comment by sventiffe** [comment]
Just realized that I've tried to reproduce on a Mac only, now verified with https://github.com/bazelbuild/bazel/releases/download/4.1.0/bazel-4.1.0-installer-linux-x86_64.sh 

Did you use a binary (installer)?

**Comment by sventiffe** [comment]
I am not familiar with arch linux at all. It looks like Bazel is available through https://archlinux.org/packages/community/x86_64/bazel/ (is this how it gets installed via pacman?).

The issue looks as if the installation is incorrect. Could you try one of the installers from https://github.com/bazelbuild/bazel/releases and see if that works?

**Comment by weiby3** [comment]
I found the reason. I have install openjdk-16, and bazel depends openjdk-11.
After uninstall openjdk-16 and reinstall bazel, this problem solved.
:joy:
