### ISSUE TITLE
Use git_repository failed the build 

### ISSUE THREAD

**Issue by doniwinata0309** [bazelbuild/bazel#13762]
### Description of the problem / feature request:

> My computer not able to run bazel when git_repository rules exist on Workspace:
For example::

```
workspace(name = "android")

load("@bazel_tools//tools/build_defs/repo:git.bzl",  "git_repository")
git_repository(
  name = "io_bazel_rules_kotlin",
  commit = "55867f8ea4070207778964be008497c669867d82",
  remote = "https://github.com/bazelbuild/rules_kotlin.git"
)

```

Running `bazel info` will failed the build, please find the stacktrace below.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> 
My friend not have this issue, seems only happen on my computer. 
clone this repo:
https://github.com/grab/Grazel
Run `bazel info` will error.

### What operating system are you running Bazel on?

> Mac OS 11

### What's the output of `bazel info release`?

> INFO: Invocation ID: 05c819ae-9b14-4a57-8bf5-360d0098d789
release 4.1.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> https://github.com/grab/Grazel.git
c8917a8e5d6935bb80c665b7682f077aba3a2e47
c8917a8e5d6935bb80c665b7682f077aba3a2e47

###  Have you found anything relevant by searching the web?

> No, but this one got error on python while mine is git:
https://github.com/bazelbuild/bazel/issues/12000

### Any other information, logs, or outputs that you want to share?
Logs
> ERROR: An error occurred during the fetch of repository 'grab_bazel_common':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/grab_bazel_common' while working with @grab_bazel_common:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /private/var/tmp/_bazel_doni.winata/56299760bfa4a70922ed6bad7d534148/external/grab_bazel_common' while working with @grab_bazel_common:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory

**Comment by keith** [comment]
Based on the last line here:

```
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
```

I think this is saying you don't have `git` installed? (or maybe not in your `$PATH`?)

**Comment by doniwinata0309** [comment]
I already have git installed and updated it to the latest version
MacBook-Pro:Grazel doni.winata$ git --version
git version 2.32.0

I also make sure the folder permission works and did able to run git  init manually on bazel target folder. Do you have other clue what may be wrong ? Thanks

**Comment by Wyverald** [comment]
Could you run `echo $PATH; which git` on your command line?

**Comment by sgowroji** [comment]
Hello @doniwinata0309, Can you please try this [comment](https://github.com/bazelbuild/bazel/issues/13762#issuecomment-1335614346) and let us know your observation. Thanks!
