### ISSUE TITLE
Bazel crash in com.google.devtools.build.lib.bazel.execlog.StableSort.stableSort

### ISSUE THREAD

**Issue by pjk25** [bazelbuild/bazel#13761]
### Description of the problem / feature request:

Bazel occassionally crashes with the following:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.devtools.build.lib.bazel.execlog.StableSort.stableSort(StableSort.java:72)
	at com.google.devtools.build.lib.bazel.execlog.StableSort.stableSort(StableSort.java:60)
	at com.google.devtools.build.lib.bazel.SpawnLogModule.afterCommand(SpawnLogModule.java:161)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:626)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:603)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately I'm not yet aware of a minimal case. The crash occurred in CI but passed when re-run. Remote build execution via BuildBuddy.io is used.

### What operating system are you running Bazel on?

Ubuntu 18.04 as provided by Github Actions

### What's the output of `bazel info release`?

I don't have this information from the original run, but provided github didn't change the version in the last 12 hours it would be `release 4.1.0`

###  Have you found anything relevant by searching the web?

Not with regard to this particular error

### Any other information, logs, or outputs that you want to share?

Not at this time

**Comment by aiuto** [comment]
Sending to team-RemoteExec only because this is happening in a remote exec situation.
But that might be just coincidence.

@anakanemison @agoulti   You both look like editors of this area of the code. Any thoughts?

**Comment by pjk25** [comment]
Removing `--execution_log_binary_file=/tmp/exec.log` from the bazel invocation seems to avoid the issue, so I think there is a good chance this is the same as #12510

**Comment by styurin** [comment]
Should be fixed by https://github.com/bazelbuild/bazel/pull/13650

**Comment by pjk25** [comment]
@styurin is the preference to close this issue now, or wait until I've tried out the release that ships #13650 first? (In which case when would I expect to see the fix land?)

**Comment by meisterT** [comment]
Let's close the issue - feel free to reopen when it still shows up with the next rolling release.
