### ISSUE TITLE
android_binary target fails compilation if --nojava_header_compilation + use of default method of generic interface

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/bazel#13825]
### Description of the problem / feature request:

Compilation of android app will fail under these circumstances :

    1. android app is built with --nojava_header_compilation option
    2. a separate module defines a generic interface
    3. a child subclass of this interface defines a default for one of the generics interface method
    4. another module defines a subclass of child interface

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone repo and run build : https://github.com/oliviernotteghem/bazel_r8_crash_repro 

### What operating system are you running Bazel on?

both macosx / linux

### What's the output of `bazel info release`?

INFO: Invocation ID: 41011e45-7531-4c94-be7a-bf9f048680e0
release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

###  Have you found anything relevant by searching the web?

nothing

### Any other information, logs, or outputs that you want to share?

Crash callstack : 

```
Error in bazel-out/android-armeabi-v7a-fastbuild/bin/src/main/java/com/example/bazel/_dx/greeter_activity/libgreeter_activity.jar_desugared.jar:com/example/bazel/Greeter$MyBooleanParameter.class at java.lang.Object com.example.bazel.Greeter$MyBooleanParameter.getDefaultValue():
NullPointerException during IR Conversion
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.android.tools.r8.compatdexbuilder.CompatDexBuilder.a(:115)
	at com.android.tools.r8.compatdexbuilder.CompatDexBuilder.main(:1)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	... 3 more
Caused by: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1453)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.W.a(:87)
	at com.android.tools.r8.D8.run(:11)
	at com.android.tools.r8.compatdexbuilder.CompatDexBuilder.a(:199)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	... 5 more
Caused by: com.android.tools.r8.utils.b: Error: bazel-out/android-armeabi-v7a-fastbuild/bin/src/main/java/com/example/bazel/_dx/greeter_activity/libgreeter_activity.jar_desugared.jar:com/example/bazel/Greeter$MyBooleanParameter.class, java.lang.Object com.example.bazel.Greeter$MyBooleanParameter.getDefaultValue(), NullPointerException during IR Conversion
	at com.android.tools.r8.utils.P0.a(:21)
	at com.android.tools.r8.utils.W.a(:73)
	... 8 more

```

**Comment by ahumesky** [comment]
we're moving to d8-based desugaring, and we're updating the version of d8 that bazel uses in bazel 6.0 and recently released pre-releases, it's probably worth a try with a recent pre-release to see if this is still an issue

**Comment by ahumesky** [comment]
We've moved to D8-based desugaring with a newer version of D8, so if this is still a problem please reopen in https://github.com/bazelbuild/rules_android
