### ISSUE TITLE
androidx databinding compile error 'NoClassDefFoundError: javax/annotation/processing/AbstractProcessor'

### ISSUE THREAD

**Issue by zhouyuanbin** [bazelbuild/bazel#13835]
### Description of the problem / feature request:
hi, 
     When I add `androidx.databinding` to my project.  I got the compile error message as follow:

ERROR: /private/var/tmp/_bazel_herbertzhou/f7e00a0a141ff828fd6f4a361ed4aa57/external/maven/BUILD:313:11: Desugaring v1/https/maven.google.com/androidx/databinding/databinding-compiler/3.4.2/databinding-compiler-3.4.2.jar for Android failed: Worker process did not return a WorkResponse:

```
---8<---8<--- Start of log snippet, file at /private/var/tmp/_bazel_herbertzhou/f7e00a0a141ff828fd6f4a361ed4aa57/bazel-workers/worker-22-Desugar.log ---8<---8<---
[... truncated ...]
esugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:08 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:09 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:09 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
8? 12, 2021 7:19:09 ?? com.google.devtools.build.android.desugar.Desugar runPersistentWorker
??: Processing Request success: 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:67)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.loadFromInternal(LambdaDesugaring.java:337)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.access$500(LambdaDesugaring.java:56)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.createLookup(LambdaDesugaring.java:617)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:402)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at com.google.devtools.build.android.desugar.strconcat.IndyStringConcatDesugaring$IndifiedStringConcatInvocationConverter.visitInvokeDynamicInsn(IndyStringConcatDesugaring.java:141)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:461)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1487)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:549)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:246)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1019)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:979)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:957)
Caused by: java.lang.ClassNotFoundException: Class javax.annotation.processing.AbstractProcessor not found
        at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 23 more
---8<---8<--- End of log snippet, 822 chars omitted ---8<---8<---
Target //Application:qqnt failed to build
INFO: Elapsed time: 118.626s, Critical Path: 33.50s
INFO: 723 processes: 104 internal, 552 darwin-sandbox, 67 worker.
FAILED: Build did NOT complete successfully
```

   I use view binding in serveral modules of the project, by using  the following switch in build.gradle
    buildFeatures {
        viewBinding true
    } 

   How can I solve this problem?

> Replace this line with your answer.

### What operating system are you running Bazel on?

Mac OS

### What's the output of `bazel info release`?

release 4.1.0-homebrew

### Android tool version?
   I use android tool downloaded from `https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.23.0.tar.gz`, and use `build --override_repository=android_tools=xxx` to specify .

**Comment by ahumesky** [comment]
The native Android rules have been removed in Bazel 8, and migrated to Starlark in https://github.com/bazelbuild/rules_android, if this is still a problem in the Starlark version, please feel free to reopen.
