### ISSUE TITLE
Bazel 4.1.0: analysis phase NPE with --java_toolchain

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#13844]
### Description of the problem / feature request:

I get an NPE when passing `--java_toolchain` to Bazel 4.1.0

The same works with 5.0.0-pre.20210802.5

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have an empty `WORKSPACE`, a trivial `Y.java` (`public class Y {}`), and this `BUILD` file:

```
java_library(
    name = "y",
    srcs = ["Y.java"],
)

java_runtime(
    name = "jdk11",
    java_home = "/usr/local/openjdk-11",
)
```

Then:

```
  $ bazel --version
bazel 4.1.0

  $ bazel --ignore_all_rc_files build --nobuild --java_toolchain=//:jdk11 -- //:y
Starting local Bazel server and connecting to it...
Analyzing: target //:y (11 packages loaded, 19 targets configured)
    currently loading: @bazel_tools//tools/build_defs/cc/whitelists/parse_headers_and_layering_check
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:y, config=BuildConfigurationValue.Key[ebe42d9bdf6bb902a8cea2ea260d0d1d960fcd031db4ac5600c35538662a510d]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.java.JavaCommon.computeJavacOpts(JavaCommon.java:398)
        at com.google.devtools.build.lib.rules.java.JavaCommon.initCommon(JavaCommon.java:559)
        at com.google.devtools.build.lib.rules.java.JavaCommon.initCommon(JavaCommon.java:545)
        at com.google.devtools.build.lib.rules.java.JavaLibrary.init(JavaLibrary.java:57)
        at com.google.devtools.build.lib.rules.java.JavaLibrary.create(JavaLibrary.java:43)
        at com.google.devtools.build.lib.rules.java.JavaLibrary.create(JavaLibrary.java:32)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1018)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        ... 7 more
```

The same works with the 5.0 pre-release:

```
  $ ~/Downloads/bazel-5.0.0-pre.20210802.5-linux-x86_64 --ignore_all_rc_files build --nobuild --java_toolchain=//:jdk11 -- //:y
Starting local Bazel server and connecting to it...
WARNING: Option 'java_toolchain' is deprecated
INFO: Analyzed target //:y (40 packages loaded, 695 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 4.876s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

```
release 4.1.0
```

**Comment by comius** [comment]
The problem is that `--java_toolchain` needs to refer to `java_toolchain` target not `java_runtime`. `--javabase` can refer to `java_runtime`.

We discussed before if we should improve error reporting. Because this flag were replaces with toolchain resolution mechanisms in versions >=5.0.0, we opted not to fix it.
