### ISSUE TITLE
--experimental_multi_cpu broken?

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1400]
I haven't confirmed this, but we got a report that --experimental_multi_cpu crashes with an exception when passed two values:

java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@23aa6a57' (requested by nodes )
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:846)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:439)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
        at com.google.devtools.build.lib.analysis.config.BuildConfiguration.setConfigurationTransitions(BuildConfiguration.java:1302)
        at com.google.devtools.build.lib.bazel.rules.BazelConfigurationCollection.setupTransitions(BazelConfigurationCollection.java:246)
        at com.google.devtools.build.lib.bazel.rules.BazelConfigurationCollection.createConfigurations(BazelConfigurationCollection.java:129)
        at com.google.devtools.build.lib.analysis.config.ConfigurationFactory.createConfigurations(ConfigurationFactory.java:84)
        at com.google.devtools.build.lib.skyframe.ConfigurationCollectionFunction.createConfiguration(ConfigurationCollectionFunction.java:162)
        at com.google.devtools.build.lib.skyframe.ConfigurationCollectionFunction.getConfigurations(ConfigurationCollectionFunction.java:94)
        at com.google.devtools.build.lib.skyframe.ConfigurationCollectionFunction.compute(ConfigurationCollectionFunction.java:58)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:810)
        ... 4 more

**Comment by damienmg** [comment]
@gregestren when will this be fixed? We are running down to 0.4 so I am trying to figure out what is realistic.

**Comment by damienmg** [comment]
pinging @ulfjack too because assigned to him

**Comment by ulfjack** [comment]
I have a fix. It's due to the Android split transition. Well, the underlying issue is that experimental_multi_cpu is incompatible with split transitions in general given the current way we setup the configurations. I'm sure we can also trigger this internally, and I filed an internal bug for that. I have a patch that makes the exception go away.
