### ISSUE TITLE
Java <name>_deploy.jar targets do not contain native libraries

### ISSUE THREAD

**Issue by connorworley** [bazelbuild/bazel#14060]
### Description of the problem / feature request:

Implicit `<name>_deploy.jar` targets that are derived from `java_binary` do not seem to include native libraries. This contradicts the docs.

> The deploy jar contains all the classes that would be found by a classloader that searched the classpath from the binary's wrapper script from beginning to end. It also contains the native libraries needed for dependencies. These are automatically loaded into the JVM at runtime.

https://docs.bazel.build/versions/main/be/java.html#java_binary

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am using https://github.com/hlopko/bazel-jni-example as an example project. When I build the deploy jar and inspect it, native libraries are not included.

```
[11:55:35] ~/Downloads/bazel-jni-example env JAVA_HOME=/usr/local/Cellar/openjdk@11/11.0.9/libexec/openjdk.jdk/Contents/Home/ bazel build //java:Main_deploy.jar
INFO: Analyzed target //java:Main_deploy.jar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //java:Main_deploy.jar up-to-date:
  bazel-bin/java/Main_deploy.jar
INFO: Elapsed time: 0.105s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action


[11:55:48] ~/Downloads/bazel-jni-example unzip -l bazel-bin/java/Main_deploy.jar
Archive:  bazel-bin/java/Main_deploy.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-2010 00:00   META-INF/
       66  01-01-2010 00:00   META-INF/MANIFEST.MF
      195  01-01-2010 00:00   build-data.properties
      675  01-01-2010 00:00   Main.class
---------                     -------
      936                     4 files
```

The native library is missing from the deploy jar, and running it with `java -jar` fails.

```
[12:04:20] ~/Downloads/bazel-jni-example java -jar bazel-bin/java/Main_deploy.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: no main-jni in java.library.path: [/Users/cbworley/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at Main.<clinit>(Main.java:3)
```

### What operating system are you running Bazel on?

```
[11:59:43] ~/Downloads/bazel-jni-example uname -a
Darwin <serial> 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

### What's the output of `bazel info release`?

```
release 4.2.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
[12:05:35] ~/Downloads/bazel-jni-example git remote get-url origin ; git rev-parse main ; git rev-parse HEAD
https://github.com/hlopko/bazel-jni-example
815afcb97f80caaea4fe043a9d98c8a24f4884e5
815afcb97f80caaea4fe043a9d98c8a24f4884e5
```

I have a small diff to build on darwin.

```
[12:05:40] ~/Downloads/bazel-jni-example git diff
diff --git a/tools/jni/BUILD b/tools/jni/BUILD
index 39387ff..2f90ddd 100644
--- a/tools/jni/BUILD
+++ b/tools/jni/BUILD
@@ -4,7 +4,7 @@ package(default_visibility = ["//visibility:public"])

 genrule(
     name = "copy_link_jni_md_header",
-    srcs = ["@bazel_tools//tools/jdk:jni_md_header-linux"],
+    srcs = ["@bazel_tools//tools/jdk:jni_md_header-darwin"],
     outs = ["jni_md.h"],
     cmd = "cp -f $< $@",
 )
```

###  Have you found anything relevant by searching the web?

No.

**Comment by comius** [comment]
It's true, Bazel java_binary does not put native libraries into deploy.jar, but it would be beneficial for users if it did. So I rather keep the documentation as is and call this a bug.
