### ISSUE TITLE
Strange "Operation not permitted" problem for test program accessing files in the sand box on MacOS

### ISSUE THREAD

**Issue by a4z** [bazelbuild/bazel#14183]
### Description of the problem / feature request:

I have a java/scala program, to which I would like to add a bazel build
https://github.com/a4z/djinni-generator/tree/bazel

There is a test that runs the generated program , and then the tests compares generated files.
Problem is, the test program can not access control files, since java fails with
```
Exception in thread "main" java.io.FileNotFoundException: src/it/resources/result/my_enum/generated-files.txt (Operation not permitted)
``` 

The build / test works without any doubt, it works on Linux, on OSX on github CI, 
and when I run the test command in the sanbox by hand, it also works.

Just when run the test via bazel on my developer notebook, I get a `java.io.FileNotFoundException: ... (Operation not permitted)`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test //:test1 

### What operating system are you running Bazel on?

MacOS BigSur / and recently updated to 12

### What's the output of `bazel info release`?

INFO: Invocation ID: 2da4c077-0365-4ada-b434-fa886848744a
release 4.2.1-homebrew

###  Have you found anything relevant by searching the web?

Unfortunately not, the only think I found was to disable csrutil , but I do not think this is a good idea on general
And also, since everything works when not executed via bazle, same files in the sandbox, the reason must be something else

### Any other information, logs, or outputs that you want to share?

Nothing other than 
```
-> bazel test //:test -s --sandbox_debug
INFO: Invocation ID: e9da7b3e-4f95-4f91-b276-34bccd7f5c06
INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
SUBCOMMAND: # //:test [action 'Testing //:test', configuration: 51eca898bf06b62dddc4e4762e2e193fc5c16e384d78bdf88fb0dd0f0af3120c, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_a4z/17f906b247640ec62f33d1e307ea4825/execroot/djinni && \
  exec env - \
    EXPERIMENTAL_SPLIT_XML_GENERATION=1 \
    JAVA_RUNFILES=bazel-out/darwin-fastbuild/bin/test.runfiles \
    PATH=/Users/a4z/.asdf/shims:/Users/a4z/.asdf/bin:/Users/a4z/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/a4z/bin \
    PYTHON_RUNFILES=bazel-out/darwin-fastbuild/bin/test.runfiles \
    RUNFILES_DIR=bazel-out/darwin-fastbuild/bin/test.runfiles \
    RUN_UNDER_RUNFILES=1 \
    TEST_BINARY=./test \
    TEST_INFRASTRUCTURE_FAILURE_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.infrastructure_failure \
    TEST_LOGSPLITTER_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.raw_splitlogs/test.splitlogs \
    TEST_PREMATURE_EXIT_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.exited_prematurely \
    TEST_SIZE=medium \
    TEST_SRCDIR=bazel-out/darwin-fastbuild/bin/test.runfiles \
    TEST_TARGET=//:test \
    TEST_TIMEOUT=300 \
    TEST_TMPDIR=_tmp/d487e625d400282a1427a5d16893f726 \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS=bazel-out/darwin-fastbuild/testlogs/test/test.outputs_manifest/ANNOTATIONS \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR=bazel-out/darwin-fastbuild/testlogs/test/test.outputs_manifest \
    TEST_UNDECLARED_OUTPUTS_DIR=bazel-out/darwin-fastbuild/testlogs/test/test.outputs \
    TEST_UNDECLARED_OUTPUTS_MANIFEST=bazel-out/darwin-fastbuild/testlogs/test/test.outputs_manifest/MANIFEST \
    TEST_UNDECLARED_OUTPUTS_ZIP=bazel-out/darwin-fastbuild/testlogs/test/test.outputs/outputs.zip \
    TEST_UNUSED_RUNFILES_LOG_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.unused_runfiles_log \
    TEST_WARNINGS_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.warnings \
    TEST_WORKSPACE=djinni \
    TZ=UTC \
    XML_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/test/test.xml \
  external/bazel_tools/tools/test/test-setup.sh ./test)
FAIL: //:test (see /private/var/tmp/_bazel_a4z/17f906b247640ec62f33d1e307ea4825/execroot/djinni/bazel-out/darwin-fastbuild/testlogs/test/test.log)
Target //:test up-to-date:
  bazel-bin/test.jar
  bazel-bin/test
INFO: Elapsed time: 13,128s, Critical Path: 12,91s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//:test                                                                  FAILED in 12.8s
  /private/var/tmp/_bazel_a4z/17f906b247640ec62f33d1e307ea4825/execroot/djinni/bazel-out/darwin-fastbuild/testlogs/test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions

```

the error is / log fie starts with :

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
...
sandbox/476/execroot/djinni/bazel-out/darwin-fastbuild/bin/test.runfiles/djinni
Exception in thread "main" java.io.FileNotFoundException: src/it/resources/result/my_enum/generated-files.txt (Operation not permitted)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at djinni.Main$.main(Main.scala:839)
	at djinni.Main.main(Main.scala)
```
 
however, if I do in a terminal

```
cd /private/var/tmp/_bazel_a4z/17f906b247640ec62f33d1e307ea4825/execroot/djinni/bazel-out/darwin-fastbuild/bin/test.runfiles/djinni

./test
```

the test work

**Comment by a4z** [comment]
I removed all bazel files, even in /var/tmp , did not work, 

checked out the repo into a different working folder, problem is gone and it works again.
Super strange and odd. But as usual there will for sure be some explanation, but I have no time to dig into it, I am just happy every thing just works again 

Feel free to close that issue if you want

**Comment by a4z** [comment]
Btw, I had the same problem on my Linux box with the same project.

did not work for some time on this device, pulled the last changes, bazel build did not work.
clean, removing tmp folders, no success

checking out the project under a different folder, it worked. Strange ......
