### ISSUE TITLE
Bazel internal crash during query on rolling

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#14257]
### Description of the problem

I was running `bazel query "..."` to investigate another issue over in Tulsi, and there was an internal crash that seemed like it'd be worth reporting. The crash comes from a somewhat pathological case, in which the bazel repo contains a symlink to its own output base.

### Thoughts on a solution

I get that this seems like a weird case--but it's a real one encountered by someone else using Tulsi's output. Probably Bazel should ignore symlinks into its own innards, just as it already ignores the symlinks it creates?
 I'm not sure exactly Bazel's philosophy on symlinks in the workspace and reproducibility. I also haven't looked at the part of the code where the crash occurs--maybe there's some interesting edge case exercised there.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
mkdir querycrashtest && cd querycrashtest
touch WORKSPACE
ln -s $(bazel info output_base) loop
bazel query "..." # First one fails differently but doesn't crash Bazel.  
bazel query "..." # Leads to the crash log listed at the bottom of this issue
```

### What operating system are you running Bazel on?

macOS 12.0.1

### What's the output of `bazel info release`?

Crash happens on both latest and rolling at the time of writing (and presumably other versions, too).
Those versions are 4.2.1 and release 6.0.0-pre.20211025.1

### Any other information, logs, or outputs that you want to share?

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@WORKSPACE' (requested by nodes 'FILE_STATE:[<absolute root>]/[/private/var/tmp/_bazel_cpsauer/79f6da2a1111e791e2fbf4f2d7fbef1b/external/WORKSPACE]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.packages.InputFile cannot be cast to class com.google.devtools.build.lib.packages.Rule (com.google.devtools.build.lib.packages.InputFile and com.google.devtools.build.lib.packages.Rule are in unnamed module of loader 'app')
        at com.google.devtools.build.lib.packages.Package.getRule(Package.java:636)
        at com.google.devtools.build.lib.repository.ExternalPackageHelper$ExternalPackageRuleExtractor.processAndShouldContinue(ExternalPackageHelper.java:168)
        at com.google.devtools.build.lib.repository.ExternalPackageHelper.iterateWorkspaceFragments(ExternalPackageHelper.java:142)
        at com.google.devtools.build.lib.repository.ExternalPackageHelper.getRuleByName(ExternalPackageHelper.java:77)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.getRepoRuleFromWorkspace(RepositoryDelegatorFunction.java:443)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:280)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 7 more
```

**Comment by meisterT** [comment]
@haxorz ISTR you have hit this case before. If so, what was your conclusion?

**Comment by haxorz** [comment]
@meisterT No, I don't recall hitting this sort of crash in `ExternalPackageHelper#getRuleByName` before. I've definitely run into issues with symlinks, esp in `bazel query ...` situations, but this repro case seems *very* specific to Bazel's external repro support.

I'm guessing this has nothing to do with `bazel query`. Read my "@cpsauer's repro is very curious" paragraph below and then consider changing labels to whatever label has to do with Bazel's external repro support.

----------------

The proximate bug is that `ExternalPackageHelper#getRuleByName` assumes `repositoryName.strippedName()` is the name of a rule instance target in the `//external` package. I don't know enough about the innards of Bazel's external repo impl to know if that's a reasonable assumption, but it seems to be wrong in this case. And I'm not sure if this assumption can be wrong in cases other than the one seemingly here (symlink from dirent of top-level dir to the output_base).

@cpsauer's repro is very curious. I think someone should run it under a debugger and see what's going on. I'd also like to just see the full stderr output from Bazel, esp. from the first `bazel query` invocation (i.e. "First one fails differently but doesn't crash Bazel." <-- how does it fail? Maybe that's a huge hint.)

**Comment by meisterT** [comment]
>  how does it fail? Maybe that's a huge hint.

```
ERROR: error loading package 'loop/install/embedded_tools/src/tools/launcher/util': Every .bzl file must have a corresponding package, but '//src/tools/launcher:win_rules.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

The weird thing is this that there is a `BUILD` file.
```
$ find loop/install/embedded_tools/ -name win_rules.bzl
loop/install/embedded_tools/src/tools/launcher/win_rules.bzl

$ ls $(dirname $(find loop/install/embedded_tools/ -name win_rules.bzl))/BUILD
loop/install/embedded_tools/src/tools/launcher/BUILD
```

-----

But there's more errors (and which one you see first seems non-deterministic):
```
ERROR: error loading package 'loop/install/embedded_tools/src/main/protobuf': Unable to find package for @com_google_protobuf//:protobuf.bzl: The repository '@com_google_protobuf' could not be resolved.
```

as well as
```
ERROR: error loading package 'loop/install/embedded_tools/third_party/def_parser': Every .bzl file must have a corresponding package, but '//tools/python:private/defs.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

-----

What is weird is that
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/Package.java;l=1866;drc=630be025a3e8803e6b81017f4073b5e877c29dc3
adds an `InputFile` while
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/Package.java;l=636;drc=630be025a3e8803e6b81017f4073b5e877c29dc3
expects to be able to cast it to a `Rule`.

**Comment by haxorz** [comment]
> ERROR: error loading package 'loop/install/embedded_tools/src/tools/launcher/util': Every .bzl file must have a corresponding package, but '//src/tools/launcher:win_rules.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
> The weird thing is this that there is a BUILD file.

See the "but '//src/tools/launcher:win_rules.bzl' does not have one" part of the error message. Bazel is looking for the file `src/tools/launcher/BUILD`, not the file you were looking for.

As for "why" it's doing that... Is `--package_path` at play? Or is there a `WORKSPACE` file at `loop/install/embedded_tools` (or something else that would cause Bazel to treat `loop/install/embedded_tools` as a package root)? Idk I don't have a working Bazel installation setup at the moment.

-------

Fwiw,

This "issue" [above] seems WAI to me (assuming there's an explanation for the "why" above). And it seems unrelated to external repo stuff.

The crash bug is probably related to external repo stuff though. That still needs to be debugged.

-------

Taking a step back, I definitely agree with @cpsauer's "Probably Bazel should ignore symlinks into its own innards, just as it already ignores the symlinks it creates?". I'd even go a step further and say Bazel should fail-fast in this case. Such a symlink is almost certainly unintentional by the user, and even if it were intentional it'd be easiest for Bazel to not have to out of its way to support this elegantly.

**Comment by cpsauer** [comment]
Thanks so much for looking into this, guys.

Re: taking a step back (above): Agree in general, but I think there are (sadly) cases where this is intentional. We can debate about if they're good...but the tulsi user who pointed this out definitely intended to put the symlink there, because he intended to put his Tulsi output in the workspace. Maybe that steers us more toward ignoring the symlink gracefully?

The reason you'd want to do this in more detail:
IDE project generators will in general need to symlink into output base to support external dependencies correctly (long story there), and (anecdotally) I've seen quite a few people choose to put their generated projects in their WORKSPACE. Symlinks to execroot seem to be handled gracefully.

Separately/additionally, ideally there'd be a way to have tulsi just mark the generated project as "no bazel" from within the generated project. (I know you can use .bazelignore, but to my understanding, only from the workspace root, not as something the project generator could add inside the project.)

**Comment by tinder-cwybranowski** [comment]
My team encountered the same issues with our wrapper over Tulsi -- subsequent `//...` queries triggered the same crash and stack trace. For our case, I resolved the issue by using [`.bazelignore`](https://docs.bazel.build/versions/main/guide.html#bazelignore) to explicitly ignore the gitignored directory where we store the generated Tulsi projects.

This solution might be unique to our setup, but felt it was worth sharing.

**Comment by cpsauer** [comment]
^ .bazelignore definitely a good workaround more generally! 
(Referenced above, but certainly good to say explicitly. Sorry to hear this is still causing people pain.)

However, maybe a better workaround still is to not generate the Tulsi project into your source tree, but rather to treat it as the build output by putting it in a new directory under Bazel's output. That is, e.g., passing `--outputfolder "$(bazel info output_base)"` to Tulsi in your Tulsi wrapper. That's what I moved our team over to doing.
(If anyone sees a reason that might be a bad idea, please lmk. You can't so easily put output under bazel-bin because of https://github.com/bazelbuild/tulsi/commit/aab93a782c6865ac36a03ab2e92b7c4337ea1aa8, though I don't know the context that motivated that change.)

Sorry I didn't explicitly provide a good workaround here. Was thinking this as the abstract, bazel-core issue, separate from the discussion over at Tulsi's repo. But of course searches for the crash bring people here.

**Comment by tinder-cwybranowski** [comment]
> However, maybe a better workaround still is to not generate the Tulsi project into your source tree, but rather to treat it as the build output by putting it in a new directory under Bazel's output. That is, e.g., passing --outputfolder "$(bazel info output_base)" to Tulsi in your Tulsi wrapper.

I like this idea, especially since it'll reduce the amount of repo-specific configuration needed to consume the wrapper! Will definitely add it to our backlog, and monitor this thread in case someone identifies a reason to avoid that approach.

**Comment by cpsauer** [comment]
Sg. FWIW, we haven't had any problems in a few months of usage, and it was super fast to integrate (just copy the flag).

@tinder-cwybranowski, I'm curious what goodies you guys have in your wrapper!

**Comment by tinder-cwybranowski** [comment]
> Sg. FWIW, we haven't had any problems with that workaround in a few months of usage, and it was super fast to integrate (just copy the flag).
> 
> @tinder-cwybranowski, I'm curious what goodies you guys have in your wrapper!

Apologies for the very late response! Our wrapper mainly included post-Tulsi-generation augmentations to generated artifacts (e.g. fixing target path references, changing target architecture, etc.). We've since switched our project generation stack to [buildbuddy-io/rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj), however, which has been working great for my team.

**Comment by meisterT** [comment]
This seems resolved at head
