### ISSUE TITLE
Crash when targeting platform with invalid crosstool

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel#14265]
### Description of the problem / feature request:

Bazel crashes with a cast error when targeting a platform with an invalid crosstool.

#### .bazelrc
```bash
build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64_cgo
build --crosstool_top=@zig_sdk//:x86_64-linux-gnu.2.28_toolchain_cc
```

#### WORKSPACE
```py3
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel-zig-cc",
    sha256 = "f28327aaf5d66cb7ca42977af6284faf9b8306df8e152fcfc82ae33ad92c443b",
    strip_prefix = "bazel-zig-cc-v0.3.2",
    urls = ["https://git.sr.ht/~motiejus/bazel-zig-cc/archive/v0.3.2.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "2b1641428dff9018f9e85c0384f03ec6c10660d935b750e3fa1492a281a53b0f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
    ],
)
```

Attempt to build any cgo binary and it should crash.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

`release 4.2.1`

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

```
(15:30:47) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=<REDACTED>, config=BuildConfigurationValue.Key[a049b56e6e736ccde967916a39f8d51cd0bab31e483eecffba0efd38aee91aab]}' (requested by nodes 'ConfiguredTargetKey{label=<REDACTED> config=BuildConfigurationValue.Key[a049b56e6e736ccde967916a39f8d51cd0bab31e483eecffba0efd38aee91aab]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider cannot be cast to class com.google.devtools.build.lib.rules.cpp.CcToolchainProvider (com.google.devtools.build.lib.rules.cpp.CcToolchainAttributesProvider and com.google.devtools.build.lib.rules.cpp.CcToolchainProvider are in unnamed module of loader 'app')
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainFromCrosstoolTop(CppHelper.java:363)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:335)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:327)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchain(CppHelper.java:316)
	at com.google.devtools.build.lib.rules.cpp.CppHelper.getToolchainUsingDefaultCcToolchainAttribute(CppHelper.java:240)
	at com.google.devtools.build.lib.rules.cpp.CcImport.create(CcImport.java:76)
	at com.google.devtools.build.lib.rules.cpp.CcImport.create(CcImport.java:38)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:385)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:195)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:940)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1031)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

**Comment by katre** [comment]
I'm not sure exactly what's wrong, but you're mixing two sets of flag here. The flag `--crosstool_top` uses the legacy CC toolchain selection mechanism: the values of `--cpu` and `--compiler` are compared to the keys of the entires in the `toolchains` attribute of the `cc_toolchain_suite` that the flag points to.

The new system, instead, uses the `--platforms` flag to define a target platform, and various candidate toolchains are registered with Bazel (via the `--extra_toolchains` flag and the `register_toolchains` function in WORKSPACE). When a CC toolchain is needed, Bazel checks for a toolchain the is compatible with the target platform and other configuration, and that is used.

Since you don't seem to be passing `--incompatible_enable_cc_toolchain_resolution`, you are using the legacy system. I suspect from this that either `@zig_sdk//:x86_64-linux-gnu.2.28_toolchain_cc` isn't a `cc_toolchain_suite`, or the values of `@zig_sdk//:x86_64-linux-gnu.2.28_toolchain_cc`'s `toolchains` attribute aren't `cc_toolchain` targets.

I'm moving this into the appropriate team, so that they can advise you further.
