### ISSUE TITLE
Remote execution of bazel coverage encounters a runtime exception when adding remote download flags

### ISSUE THREAD

**Issue by bradb423** [bazelbuild/bazel#14337]
## Description of the problem / feature request:

Remote execution of `bazel coverage` encounters a runtime exception when adding the flags:
  - `--remote_download_minimal`
or
  - `--remote_download_toplevel`

This seems to be the case regardless of the tests, or the language the tests are written in.

## Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Produce a script and some tests, eg:

```java
# Example.java
public class Example {
  public static String fizzbuzz(int i) {
    if (i % 3 == 0) {
      if (i % 5 == 0) {
        return "FizzBuzz";
      }
      return "Fizz";
    } else if (i % 5 == 0) {
      return "Buzz";
    } else {
      return Integer.toString(i);
    }
  }
}
```

```java
# ExampleTest.java
public class ExampleTest {
  @Test
  public void various() {
    assertEquals("1", Example.fizzbuzz(1));
    assertEquals("2", Example.fizzbuzz(2));
    assertEquals("Fizz", Example.fizzbuzz(3));
    assertEquals("4", Example.fizzbuzz(4));
    assertEquals("Buzz", Example.fizzbuzz(5));
    assertEquals("FizzBuzz", Example.fizzbuzz(15));
  }
}
```

With an accompanying ```BUILD``` file:
```java
package(default_visibility = ["//visibility:public"])

java_library(
  name = "example",
  srcs = glob(["Example.java"]),
)

java_test(
  name = "ExampleTest",
  srcs = glob(["ExampleTest.java"]),
  deps = [":example"],
  size = "small",
)
```

You will also need a `.bazelrc` for remote execution of the above, and a `WORKSPACE` file.

Use the command ```bazel coverage``` remotely on a small test using the following flags:
  - `--combined_report=lcov`
  - `--experimental_split_coverage_postprocessing`
  - `--experimental_fetch_all_coverage_outputs`
  - `-nocache_test_results`
  - `--test_output=errors`
  - `--strategy=CoverageReport=local,remote`
  - `--remote_download_minimal` **OR** `--remote_download_toplevel`

Using this combination of flags gives the following error:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'UnshareableActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//java/com/no_coverage:NoCoverageTest, config=BuildConfigurationValue.Key[8811a74c4059155cb43e57b5e92ddc3a9455b9c5937ad1a87d52def4244e3399]}, actionIndex=12}' (requested by nodes 'UnshareableActionLookupData{actionLookupKey=CoverageReportKeySingleton, actionIndex=1}', 'TestCompletionKey{configuredTargetKey=ConfiguredTargetKey{label=//java/com/no_coverage:NoCoverageTest, config=BuildConfigurationValue.Key[8811a74c4059155cb43e57b5e92ddc3a9455b9c5937ad1a87d52def4244e3399]}, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.base.VerifyException
        at com.google.common.base.Verify.verify(Verify.java:100)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy$BazelTestAttemptContinuation.execute(StandaloneTestStrategy.java:876)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction$RunAttemptsContinuation.execute(TestRunnerAction.java:1161)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:932)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:921)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:909)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1078)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1033)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:496)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 4 more
```

## What operating system are you running Bazel on?
`Debian 10(Buster)`

## Bazel Version
4.2.1, though this error is repeatable on 5.0.0 pre release, and 6.0.0 pre release.

**Comment by tjgq** [comment]
Not stale. I'll check whether this is still a problem at head (there have been numerous BwoB changes since it was reported).

**Comment by tjgq** [comment]
I was unable to reproduce the crash; it appears that this has been fixed.
