### ISSUE TITLE
Jacoco fails for Kotlin code coverage

### ISSUE THREAD

**Issue by bu3** [bazelbuild/bazel#14386]
### Description of the problem / feature request:

I'm using Bazel 4.2.2 and when I try to get Kotlin code coverage, Jacoco fails with the following exception:

```
Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
	at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
	at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.filter(KotlinInlineFilter.java:43)
	at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:57)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:110)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.access$100(ClassAnalyzer.java:31)
	at org.jacoco.core.internal.analysis.ClassAnalyzer$1.accept(ClassAnalyzer.java:99)
	at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:122)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:138)
	... 3 more
```

I think the Jacoco issue has been fixed in v0.8.7

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Trying to get code coverage on any Kotlin code with rules_kotlin v1.5.0-beta-4

### What operating system are you running Bazel on?

Linux and macOS

### What's the output of `bazel info release`?

```
Build command: info  Time: Tue  7 Dec 2021 11:45:44 GMT
Verbose environment data has been logged to /tmp/bazel_env.txt
Verbose process data has been logged to /tmp/bazel_ps.txt
INFO: Invocation ID: 6346ec70-d7b4-48a4-be6e-a6ccb967795f
release 4.2.2
```

###  Have you found anything relevant by searching the web?

Yes, I found this: https://youtrack.jetbrains.com/issue/KT-44757
I noticed that you have already the right Jacoco version in master

**Comment by oquenchil** [comment]
Can you confirm you no longer get this error with the Bazel 5 candidates? If so, there is nothing else we can do.

**Comment by bu3** [comment]
@oquenchil I tried with version 5.0.0-pre.20211011.2 but the build fails for another reason.
```
ERROR: /private/var/tmp/_bazel_fmangione/1ee60ce477e4ed463af08dfc91d18302/external/bazel_tools/tools/jdk/BUILD:147:14: Target '@remote_java_tools_darwin//:prebuilt_singlejar' contains an error and its package is in error and referenced by '@bazel_tools//tools/jdk:prebuilt_singlejar_darwin'
```

We recently managed to upgrade to Bazel 4.2.2 and I guess we would need more time and effort do deal with Bazel 5 at this stage.
Is there any chance you can bump Jacoco version in 4.x instead?

**Comment by bu3** [comment]
Hi @c-mita , yes the error is totally unrelated to code coverage but that's what I get trying to use Bazel 5 RCs with our massive mono-repo.

At this stage, it would be very expensive for us to try to fix that issue and whatever might come after that only to be sure that a Bazel 5 RC works as expected.
