### ISSUE TITLE
Broke machine's bazel setup and can't fix it (even with reinstallation)

### ISSUE THREAD

**Issue by lizziemac** [bazelbuild/bazel#14422]
### Description of the problem / feature request:

I was building my project with Bazel, and at one point hit `ctl-c` perhaps one too many times.  Now I can't get anything to build because a package is being fetched until it times out, at which point I get the below error:

```shell
liz@~/Projects/github/stratis3 $ bazel run services/activity:tests
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository celery_test_py_deps instantiated at:
  /Users/liz/Projects/github/stratis3/WORKSPACE:206:12: in <toplevel>
  /private/var/tmp/_bazel_liz/6528c5f701f5ec1d4e1da50c62ae2214/external/rules_python/python/pip.bzl:128:15: in pip3_import
Repository rule pip_import defined at:
  /private/var/tmp/_bazel_liz/6528c5f701f5ec1d4e1da50c62ae2214/external/rules_python/python/pip.bzl:51:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'celery_test_py_deps':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_liz/6528c5f701f5ec1d4e1da50c62ae2214/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
                fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Timed out)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_liz/6528c5f701f5ec1d4e1da50c62ae2214/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
                fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Timed out)
ERROR: no such package '@celery_test_py_deps//': pip_import failed:  (Timed out)
INFO: Elapsed time: 702.420s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
In order to fix it I have tried:
1. Running `bazel clean --expunge`
2. Changing the version of python I'm using (NOTE: I use pyenv and have been running on different iterations of 3.8).
3. Running bazel in a virtualenv with different python versions
4. Deleting the project that uses bazel and redownloading it from GitHub.
5. Deleting the lines of code that bazel was getting stuck on (ended up getting stuck on a different pip3 import and so on)
    ```
    pip3_import(
        name = "celery_test_py_deps",
        requirements = "//lib/python/celery:requirements-test.txt"
    )
    load("@celery_test_py_deps//:requirements.bzl",celery_test_pip_install = "pip_install")
    celery_test_pip_install()
    ```
5. Deleting the directory `/private/var/tmp/_bazel_liz`
6. Reinstalling bazel with brew
7. Reinstalling bazel with bazelisk
8. Using a newer version of bazel (4.2.2)
9. Rebooting my computer
10. Running a different bazel command (e.g. `bazel build <target2>` as opposed to `bazel run <target1>`)

All of these attempts resulted in getting stuck at the same spot, fetching a repository and timing out after 10 minutes.  **My working theory is that there is a cache file or directory I'm not aware of that is caching something corrupted by the `ctl-c` spamming.**

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Honestly not sure how to replicate this.  One minute my builds were working, the next minute none of them worked.  Maybe spamming `ctl-c` when the bazel build or run starts up.

### What operating system are you running Bazel on?

> Mac OS Big Sur, v11.6

### What's the output of `bazel info release`?

> release 4.2.1

###  Have you found anything relevant by searching the web?

> I tried the solution at https://github.com/bazelbuild/bazel/issues/12000 with no luck/same result.

### Any other information, logs, or outputs that you want to share?

> I'm not utilizing remote caching, and there is no bazel directory under `~/.cache` - let me know if there's anything else you need for context, I'm still relatively new to Bazel.

**Comment by lizziemac** [comment]
Update: It looks like the repositories bazel was loading had `Django==3.2.10` in their `requirements.txt` files.  Changing this version to `3.2.9` enabled bazel to retrieve the package and proceed with the build.
