### ISSUE TITLE
remote string in label_list default leads to RuntimeException

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1442]
When I add  the following line in external repo `foo`

    "_python_runfiles": attr.label_list(default=["@python//:whatever"]),

Bazel excepts:
    
    Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@b926050d' (requested by nodes 'PACKAGE:@foo//')
    INFO: Elapsed time: 0.604s
    java.lang.RuntimeException: Unrecoverable error while evaluating node 'SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@b926050d' (requested by nodes 'PACKAGE:@foo//')
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1024)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
    at com.google.devtools.build.lib.packages.BuildType$LabelType.convert(BuildType.java:227)
    at com.google.devtools.build.lib.packages.BuildType$LabelType.convert(BuildType.java:199)
    at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:550)
    at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:496)
    at com.google.devtools.build.lib.syntax.Type.convert(Type.java:85)
    at com.google.devtools.build.lib.packages.Attribute$Builder.defaultValue(Attribute.java:620)
    at com.google.devtools.build.lib.rules.SkylarkAttr.createAttribute(SkylarkAttr.java:141)
    at com.google.devtools.build.lib.rules.SkylarkAttr.access$100(SkylarkAttr.java:68)
    at com.google.devtools.build.lib.rules.SkylarkAttr$6.invoke(SkylarkAttr.java:747)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:157)
    at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
    at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:591)
    at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:680)
    at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:666)
    at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
    at com.google.devtools.build.lib.syntax.DictionaryLiteral.doEval(DictionaryLiteral.java:89)
    at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
    at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:642)
    at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:694)
    at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:666)
    at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
    at com.google.devtools.build.lib.syntax.AssignmentStatement.doExec(AssignmentStatement.java:62)
    at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
    at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:152)
    at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.createExtension(SkylarkImportLookupFunction.java:365)
    at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.computeInternal(SkylarkImportLookupFunction.java:208)
    at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.compute(SkylarkImportLookupFunction.java:85)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:975)
    ... 4 more

Now looking at the code it seems like the problem originates from this call in `Type.java:85`

    return convert(x, what, null);

It can be worked around by wrapping `@python//:whatever` in `Label`.
So if in lower code the context is actually necessary to convert values I think it needs to be passed.
OR there needs to be check in `Attribute.java:620`, whether a conversion without context is actually possible (or catch the exception).

**Comment by damienmg** [comment]
ping @fweikert: can you update the ticket?

**Comment by fweikert** [comment]
The fix is currently being reviewed and should be pushed to GitHub shortly.
