### ISSUE TITLE
bazel 5.x.x crashes if uncompressed CAS is sent back to client

### ISSUE THREAD

**Issue by shirchen** [bazelbuild/bazel#14522]
### Description of the problem / feature request:

When experimenting with compression (https://github.com/bazelbuild/bazel/pull/14041), I ran into crashes if the server isn't on the same page as the client. I think these are edge cases as in this case, remote cache server hasn't fully implemented compression support, but it's possible bazel may want to guard against these and not crash fatally since we are just using remote cache. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Running with compression flag: `bazel build //... --experimental_remote_cache_compression`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is a bit tricky, but if one has the server claim they have compression capabilities, and then return something that client isn't expecting:
- uncompressed CAS when reading
- fail to respond to one of the remote cache rpcs calls 

### What operating system are you running Bazel on?

Mac OS.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`origin/release-5.0.0rc3` tag.

### Any other information, logs, or outputs that you want to share?

This stack is if server throws an error (expected), which I think should be warning and let bazel build locally instead of crashing. 

```
...	
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: compressed-blobs/zstd/f7675cc879aba2e38d0d059ad60e3ed19d3d062c3fdb9b2fd37a2a8c8ed848ee/202: Url path not recognized
		at io.grpc.Status.asRuntimeException(Status.java:535)
		... 14 more
[96 / 99] GoCompilePkg src/code.uber.internal/base/io/fileutil/go_default_test_test.external.a; 0s remote-cache
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//src/code.uber.internal/base/io/fileutil:go_default_test, config=BuildConfigurationValue.Key[1bb1b4d6ce810b0badbe269c1bb76d3539cd5517823c629b93b9bf6dc6f01409]}, actionIndex=1}' (requested by nodes 'ArtifactNestedSetKey{rawChildren=[File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_davecgh_go_spew/spew/spew.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_pmezard_go_difflib/difflib/difflib.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/in_gopkg_yaml_v3/yaml_v3.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_stretchr_testify/assert/assert.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_stretchr_testify/require/require.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/org_uber_go_atomic/atomic.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/org_uber_go_multierr/multierr.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]src/code.uber.internal/base/io/fileutil/go_default_test.internal.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]src/code.uber.internal/base/io/fileutil/go_default_test_test.external.a]}', ...)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	
```
and here is if server incorrectly passes back uncompressed CAS 
```
	Caused by: java.io.IOException: Decompression error: Unknown frame descriptor
		at com.github.luben.zstd.ZstdInputStreamNoFinalizer.readInternal(ZstdInputStreamNoFinalizer.java:171)
		at com.github.luben.zstd.ZstdInputStreamNoFinalizer.read(ZstdInputStreamNoFinalizer.java:123)
		at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:87)
		at com.google.protobuf.ByteString.readChunk(ByteString.java:540)
		at com.google.protobuf.ByteString.readFrom(ByteString.java:517)
		at com.google.protobuf.ByteString.readFrom(ByteString.java:485)
		at com.google.devtools.build.lib.remote.zstd.ZstdDecompressingOutputStream.write(ZstdDecompressingOutputStream.java:60)
		at com.google.devtools.build.lib.remote.zstd.ZstdDecompressingOutputStream.write(ZstdDecompressingOutputStream.java:54)
		at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1381)
		at com.google.devtools.build.lib.remote.GrpcCacheClient$1.onNext(GrpcCacheClient.java:389)
		... 12 more
[96 / 99] GoCompilePkg src/code.uber.internal/base/io/fileutil/go_default_test_test.external.a; 0s remote-cache
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//src/code.uber.internal/base/io/fileutil:go_default_test, config=BuildConfigurationValue.Key[1bb1b4d6ce810b0badbe269c1bb76d3539cd5517823c629b93b9bf6dc6f01409]}, actionIndex=1}' (requested by nodes 'ArtifactNestedSetKey{rawChildren=[File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_davecgh_go_spew/spew/spew.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_pmezard_go_difflib/difflib/difflib.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/in_gopkg_yaml_v3/yaml_v3.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_stretchr_testify/assert/assert.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/com_github_stretchr_testify/require/require.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/org_uber_go_atomic/atomic.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]external/org_uber_go_multierr/multierr.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]src/code.uber.internal/base/io/fileutil/go_default_test.internal.a, File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]src/code.uber.internal/base/io/fileutil/go_default_test_test.external.a]}', ...)
```

**Comment by Wyverald** [comment]
cc @AlessandroPatti

This likely won't count as a release blocker since it's guarded behind an experimental flag and is not a regression.

**Comment by AlessandroPatti** [comment]
@shirchen do you use `--remote_download_[toplevel|minimal]` (a.k.a Builds w/o the bytes)? AFAIK, Bazel is unable to recover from cache errors when it is enabled. The issue is more largely tracked in https://github.com/bazelbuild/bazel/issues/6862

**Comment by shirchen** [comment]
@AlessandroPatti no, it was just a straight build w/out bwotb.  I'm familiar with bazel being unable to recover if a promised artifact is missing, however, i believe that may be fixed with recently merged [rewind feature](https://github.com/bazelbuild/bazel/pull/14126). Even then, I have never seen bazel crash with fatal and print a stack trace (usually it errors that something is missing and bazel can't handle that case), so do you mind linking to a task where using bwotb would cause a fatal and a stack trace from bazel? 

Assuming that what I'm describing is an issue related to compression, I think problem here is that zstd [throws an IO exception](https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java#L171)  and bazel doesn't recover if a stream isn't actually zstd ([throws that exception immediately](https://github.com/bazelbuild/bazel/blob/release-5.0.0rc3/src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java#L316)).

I am not familiar with zstd library, but from UX for bazel I think warning a user that an artifact isn't compressed and then maybe trying to download it as uncompressed or just catching IO exception and moving on w/out using remote_cache would be a slight improvement. Maybe latter would be better?

@Wyverald I agree, this isn't release blocking since this feature is hidden behind an experimental flag.

**Comment by AlessandroPatti** [comment]
@shirchen I tried reproducing the issue but I couldn't. I modified `bazel-remote` to return uncompressed blobs when compressed are requested and I do see the error, but it fails only if bwotb is enabled (otherwise it just shows a warning but the builds continues locally and succeeds) and the stack trace is only printed if `--verbose_failures` is passed.

> Assuming that what I'm describing is an issue related to compression, I think problem here is that zstd throws an IO exception and bazel doesn't recover if a stream isn't actually zstd (throws that exception immediately).

This does not seem the only place where `IOException`s are wrapped in the future and returned (e.g. [here](https://github.com/bazelbuild/bazel/blob/release-5.0.0rc3/src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java#L426), just one call below), so I would expect bazel to crash in more cases, for example if the remote cache [returns an unexpected blob](https://github.com/bazelbuild/bazel/blob/9c1c622fed219cb6b9c0656ebe4a4f3c117029b9/src/main/java/com/google/devtools/build/lib/remote/util/Utils.java#L429).

Do you have a small example I could use to reproduce the issue you are experiencing?

**Comment by shirchen** [comment]
> Hello @shirchen, Could you please respond to the above [comment](https://github.com/bazelbuild/bazel/issues/14522#issuecomment-1009357893). Thanks!

> This does not seem the only place where IOExceptions are wrapped in the future and returned (e.g. [here](https://github.com/bazelbuild/bazel/blob/release-5.0.0rc3/src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java#L426), just one call below), so I would expect bazel to crash in more cases, for example if the remote cache [returns an unexpected blob](https://github.com/bazelbuild/bazel/blob/9c1c622fed219cb6b9c0656ebe4a4f3c117029b9/src/main/java/com/google/devtools/build/lib/remote/util/Utils.java#L429).

I guess then maybe this bug can be reframed as better UX for client instead of a crash?

**Comment by meisterT** [comment]
Likely no longer relevant at HEAD, please re-open if you have more info
