### ISSUE TITLE
py_binary doesn't work with default_runfiles

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#14608]
py_binary doesn't work as a tool dependency, using default_runfiles.

Ubuntu 20.04

**.bazelversion**

```txt
5.0.0
```

**WORKSPACE.bazel**

```bzl
workspace(name = "test_python")
```

**BUILD.bazel**

```bzl
load(":rules.bzl", "example")

py_binary(name = "tool", srcs = ["tool.py"])

example(name = "bin")
```

**rules.bzl**

```bzl
def _example_impl(ctx):
    bin = ctx.actions.declare_file(ctx.attr.name)
    ctx.actions.symlink(output = bin, target_file = ctx.file._bin)
    runfiles = ctx.runfiles(files = ctx.files._bash_runfiles)
    runfiles = runfiles.merge(ctx.attr._tool[DefaultInfo].default_runfiles) # problem
    return DefaultInfo(executable = bin, runfiles = runfiles)

example = rule(
    _example_impl,
    attrs = {
        "_bash_runfiles": attr.label(default = "@bazel_tools//tools/bash/runfiles"),
        "_bin": attr.label(allow_single_file = True, default = ":bin.sh"),
        "_tool": attr.label(default = ":tool"),
    },
    executable = True,
)
```

**bin.sh**

```sh
#!/bin/bash

# --- begin runfiles.bash initialization v2 ---
# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
source "$0.runfiles/$f" 2>/dev/null || \
source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
{ echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v2 ---

exec "$(rlocation test_python/py)"
```

**tool.py**

```py
print("Hello world")
```

Running

```sh
bazel run :bin
```

yields

```txt
Traceback (most recent call last):
  File "/home/paul/.cache/bazel/_bazel_paul/242a6cf316fb8bbb1239699298f689cf/execroot/test_python/bazel-out/k8-fastbuild/bin/tool", line 392, in <module>
    Main()
  File "/home/paul/.cache/bazel/_bazel_paul/242a6cf316fb8bbb1239699298f689cf/execroot/test_python/bazel-out/k8-fastbuild/bin/tool", line 292, in Main
    module_space = FindModuleSpace()
  File "/home/paul/.cache/bazel/_bazel_paul/242a6cf316fb8bbb1239699298f689cf/execroot/test_python/bazel-out/k8-fastbuild/bin/tool", line 122, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for /home/paul/.cache/bazel/_bazel_paul/242a6cf316fb8bbb1239699298f689cf/execroot/test_python/bazel-out/k8-fastbuild/bin/tool
```

---

Instead, the rule has to use data_runfiles from the py_binary.

Note: If you run `bazel build :tool` first, then `bazel run :bin` works, because Bazel has populated the tool runfiles. Make sure to clean for repro.

**Comment by comius** [comment]
cc @rickeylev

**Comment by comius** [comment]
Default and data runfiles in Python rules are used to handle BuildInfo correctly and I believe this can be done better, but I don't know what is the correct fix.

I'll mark this P3, with some caution, because the fix might be tricky.

**Comment by pcjanzen** [comment]
related: https://github.com/bazelbuild/bazel/issues/11997

If you change bin.sh to read
```
#!/bin/bash

exec "$0.runfiles/test_python/py"
```
(i.e., bypassing the manifest lookup, and using the runfiles of `:tool` that are built in the runfiles of `:bin`) then it works with default_runfiles.

**Comment by pauldraper** [comment]
Thanks. This appears to be a dupe of #11997.

Good to know that I can use RUNFILES_DIR instead of the dereferenced path.
