### ISSUE TITLE
Rust + cc_configure == crash

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1469]
I get a Bazel crash if I add both cc_configure and Rust setup to my WORKSPACE file:
```
git_repository(
    name = "io_bazel_rules_rust",
    remote = "https://github.com/bazelbuild/rules_rust.git",
    tag = "0.0.2",
)
load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_repositories")
cc_configure()

rust_repositories()
```

```
$ bazel build
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/Users/ulfjack/Projects/experiment/Rust]/[WORKSPACE], 2' (requested by nodes 'EXTERNAL_PACKAGE:[/Users/ulfjack/Projects/experiment/Rust]/[WORKSPACE]')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1044)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@19951b19 and @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@19951b19
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:190)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:175)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:112)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:995)
	... 4 more

```

**Comment by ulfjack** [comment]
It looks like switching from ImmutableMap.Builder to LinkedHashMap works. See:
https://github.com/ulfjack/bazel/commits/fix-workspace-factory

**Comment by ulfjack** [comment]
I think this is just the duplicate cc_configure call, and doesn't have anything to do with rust.

**Comment by damienmg** [comment]
change is inflight
