### ISSUE TITLE
[install error] install failed on RedHat 

### ISSUE THREAD

**Issue by dzhwinter** [bazelbuild/bazel#1474]
(gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) )
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
it complains about the G_LIBC Version `GLIBC_2.14' not found , but my ldd command responce me this.which is the libc6 version of system.

```
[work@yq01-bdl-offline0 bazel]$ ldd --version
ldd  2.18
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I had followed the install guideline, but install failed after build successfully. Any suggestions?
Thanks in advance.

```
Build successful! Binary is here: /home/work/dongzhihong/github/bazel/output/bazel
[work@yq01-bdl-offline0 bazel]$ /home/work/dongzhihong/github/bazel/output/bazel
Extracting Bazel installation...
Found non-responsive server process (pid=9165). Killing it.
.
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/home/work/.cache/bazel/_bazel_work/1f58e0713f35bddd6dc5e21678fe270d/server/jvm.out':
JNI initialization failed: /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655/_embedded_binaries/libunix.so: /home/work/.jumbo/opt/glibc/libc.so.6: version `GLIBC_2.14' not found (required by /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655/_embedded_binaries/libunix.so).  Possibly your installation has been corrupted; if this problem persists, try 'rm -fr /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655'.
java.lang.UnsatisfiedLinkError: /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655/_embedded_binaries/libunix.so: /home/work/.jumbo/opt/glibc/libc.so.6: version `GLIBC_2.14' not found (required by /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655/_embedded_binaries/libunix.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1855)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
    at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
    at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
    at com.google.devtools.build.lib.util.OsUtils.forceJNI(OsUtils.java:55)
    at com.google.devtools.build.lib.util.OsUtils.maybeForceJNI(OsUtils.java:43)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1016)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:917)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:862)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:655)
    at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
```

**Comment by dzhwinter** [comment]
Can  I ask another question, which release can avoid such a bug to build tensorflow successfully?
Thanks.

**Comment by dslomov** [comment]
What does 
```
ldd /home/work/.cache/bazel/_bazel_work/install/8a917d6538096d0f77fca8d93a739655/_embedded_binaries/libunix.so
```
say?

What is your LD_LIBRARY_PATH? What is your PATH? What does ``which gcc`` say on your system?

It looks like the settings you have during the bazel execution are incompatible with the environment bazel used while building itself.

**Comment by dzhwinter** [comment]
my environment is:
```
declare -x GCC48="/opt/compiler/gcc-4.8.2"
declare -x LD_LIBARAY_PATH="/opt/compiler/gcc-4.8.2/lib:/home/work/local/samba/lib"
/opt/compiler/gcc-4.8.2/bin has added to PATH
```
it return me this string as response
```
[work@yq01-bdl-offline0 bazel]$ ldd /home/work/.cache/bazel/_bazel_work/install/f251d87c9971f62b5390d2aa0229a75f/_embedded_binaries/libunix.so
/home/work/.cache/bazel/_bazel_work/install/f251d87c9971f62b5390d2aa0229a75f/_embedded_binaries/libunix.so: error while loading shared libraries: /opt/compiler/gcc-4.8.2/lib/libm.so.6: ELF file OS ABI invalid
```

**Comment by dzhwinter** [comment]
Any suggestions?  I will use bazel to build tensorflow, Is there any release may be work?
Thanks.

**Comment by dslomov** [comment]
When Bazel builds itself, it uses gcc from /usr/bin/gcc, which is apparently a different gcc from what you have in `/opt/compiler`.  I think you can try to set `CC=/opt/compiler/gcc-4.8.2` before you compile Bazel.

**Comment by damienmg** [comment]
Closing as this is user support that has no update since July
