### ISSUE TITLE
select() in rule attribute used in output causes exception

### ISSUE THREAD

**Issue by k6project** [bazelbuild/bazel#1479]
Hello,

I have a custom rule set up as follows:

the_rule = rule(
    implementation = _the_rule_impl,
    attrs = {
        "json_prms": attr.label(allow_files = True, mandatory = True, single_file = True),
        "file_name": attr.string(mandatory = True),
    },
    outputs = {
        "out": "%{file_name}",
    }
)

Now, when invoking:

the_rule(
    name = "run_my_rule",
    .....
    file_name = select({
        ":darwin_x86_64": "osx.source",
        "//conditions:default": "common.source"
    }),
    .....
)

the exception is thrown:

Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:@assets//assets/structures/mining/materials/source/structure_mining_matid02_platings_001.intmat.dir' (requested by nodes 'RECURSIVE_PKG:rootedPath=[/private/var/tmp/_bazel_e.brusilovskyy/cd596da2e7b78aa423572dc4754dd5bc/external/assets]/[assets/structures/mining/materials/source/structure_mining_matid02_platings_001.intmat.dir], excludedPaths=<omitted>)')
INFO: Elapsed time: 10.932s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:@assets//assets/structures/mining/materials/source/structure_mining_matid02_platings_001.intmat.dir' (requested by nodes 'RECURSIVE_PKG:rootedPath=[/private/var/tmp/_bazel_e.brusilovskyy/cd596da2e7b78aa423572dc4754dd5bc/external/assets]/[assets/structures/mining/materials/source/structure_mining_matid02_platings_001.intmat.dir], excludedPaths=<omitted>)')
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1024)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "file_name" in rule @assets//assets/structures/mining/materials/source/structure_mining_matid02_platings_001.intmat.dir:fuse_shader
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:69)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.attributeValues(ImplicitOutputsFunction.java:296)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.access$000(ImplicitOutputsFunction.java:55)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$1.get(ImplicitOutputsFunction.java:171)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:405)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:378)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$3.getImplicitOutputs(ImplicitOutputsFunction.java:217)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunctionWithMap.calculateOutputs(ImplicitOutputsFunction.java:134)
    at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunction.getImplicitOutputs(ImplicitOutputsFunction.java:68)
    at com.google.devtools.build.lib.packages.Rule.populateImplicitOutputFiles(Rule.java:483)
    at com.google.devtools.build.lib.packages.Rule.populateOutputFiles(Rule.java:450)
    at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1346)
    at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:130)
    at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:176)
    at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:217)
    at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:550)
    at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
    at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:695)
    at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:666)
    at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
    at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
    at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
    at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:140)
    at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
    at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:695)
    at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:666)
    at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
    at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
    at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
    at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:152)
    at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1621)
    at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1272)
    at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1203)
    at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:486)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:975)
    ... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.lang.String
    at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:377)
    at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:374)
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:65)
    ... 38 more

**Comment by philsc** [comment]
I'm encountering this also.

**Comment by philsc** [comment]
What's the priority of this? It would be awesome to have. Would I be better of trying to fix it myself?

**Comment by katre** [comment]
The problem is when a configured attribute is used in the outputs section.

Reproduction:
rule.bzl:
```
def _impl(ctx):
  print('%s' % (ctx.attr.foo))
  return [] 

demo_rule = rule(
  _impl,
  attrs = {
    'foo': attr.string(),
  },
  outputs = {
    'out': '%{foo}.txt'
  })
```

BUILD:
```
load(':rule.bzl', 'demo_rule', 'wrapped_rule', 'wrapped_rule_2')

demo_rule(
  name = 'demo',
  foo = select({
    '//conditions:default': 'selected string'
  }))
```

**Comment by katre** [comment]
We need to find out whether having outputs use configurable attributes makes sense, but at the least we need a better error message if this is not supported.

**Comment by philsc** [comment]
I would like to think that it'd be possible, but I'll defer to people with more insight than myself.

I figure if we can change the dependency graph based on a `--cpu=` flag, then why not change the output file names?

**Comment by katre** [comment]
Outputs are evaluated before selects can be decided, which makes sense because the set of outputs needs to be deterministic in order for other targets to properly depend on them. The best we can do for this is to add a better error handling.

**Comment by philsc** [comment]
You're right. I do remember a few explaining that to me at the conference on Monday. Thank you very much for taking a look!

As a work around, Michael and one of the Johns (I can't remember last names) suggested the following workaround. This was for my use case of `select`ing on the CPU architecture:
```python

def _adapter_suffix_rule_impl(ctx):
  input_file = ctx.file.src
  cfg_stuff = ctx.fragments.cpp.cpu
  output_file = ctx.actions.declare_file(name_transformation(input_file.base_name, cfg_stuff), sibling=input_file)

  args = ctx.action.args()
  args.add(input_file)
  args.add(output_file)
  ctx.actions.run_shell(outputs=[output_file], inputs=[input_file], command="cp $1 $2", arguments = args)
  return [DefaultInfo(files=[output_file])]

adapter_suffix_rule = rule(
  implementation = adapter_suffix_rule_impl,
  attrs = {"src": attr.label(), single_file=True},
  fragments = ["cpp]",
)
```
where `name_transoformation` is a function that changes the input file name somehow.

A non-crash would be nice. In the long-term it'd be nice to be able to use a select-like syntax to change the file names based on things like architecture directly.
