### ISSUE TITLE
crash attempting to glob toolchains

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#14801]
```
$ bazel version
Build label: 8.0.0-pre.20240814.2
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Tue Aug 20 19:05:29 2024 (1724180729)
Build timestamp: 1724180729
Build timestamp as int: 1724180729
$ touch MODULE.bazel
$ cat > BUILD
cc_binary(name = 'x', srcs = ['x.c'])
$ bazel build --extra_toolchains //:* //:x
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:*, excludedSubdirs=[], filteringPolicy=RuleTypeFilter{ruleName=toolchain, keepExplicit=true}' (requested by nodes 'RegisteredToolchainsValue.Key{configurationKey: BuildConfigurationKey[ae8af14c9deccc70ea256a4e8a74a30a950bcd3331204c7d24de2e84a6b0c05a], debug: false}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.packages.Rule.getRuleClass()" because the return value of "com.google.devtools.build.lib.packages.Target.getAssociatedRule()" is null
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$RuleTypeFilter.shouldRetain(FilteringPolicies.java:121)
	at com.google.devtools.build.lib.pkgcache.TargetPatternResolverUtil.resolvePackageTargets(TargetPatternResolverUtil.java:47)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:148)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:463)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:92)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	... 7 more

```

**Comment by benjaminp** [comment]
@bazelbuild/triage

**Comment by benjaminp** [comment]
This issue still exists.

**Comment by benjaminp** [comment]
This issue still exists.
