### ISSUE TITLE
block-network does not allow binding to localhost on Mac

### ISSUE THREAD

**Issue by ngeor** [bazelbuild/bazel#14828]
### Description of the problem / feature request:

On a Mac, unit tests that listen to localhost fail when "block-network" tag is used.
On our CI (Linux), those unit tests pass.
The expectation is that binding to localhost should work when "block-network" tag is used.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a unit test that binds to localhost with Java. We have the same symptoms for OkHttp MockWebServer and Dropwizard's Integration test framework. They both work fine on CI (Linux) when block-network is activated, but fail on Mac. They work anywhere when block-network is deactivated.

Edit: this is a minimal project that can be used to reproduce the issue https://github.com/ngeor/bazel-block-network 

### What operating system are you running Bazel on?

MacOS Monterey 12.2.1 

### What's the output of `bazel info release`?

5.0.0

```
bazel info release
2022-02-16 09:17:45,626 INFO executing "['/Users/ngeorgiou/Library/Caches/bazelisk/downloads/https---jfrog-redacted-com-artifactory-github-release-mirror-bazelbuild-bazel-releases-download/bazel-5.0.0-darwin-x86_64/bin/bazel', 'info', 'release']"
release 5.0.0
2022-02-16 09:17:45,728 INFO return code 0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not an open source project.

###  Have you found anything relevant by searching the web?

I have found an old GitHub issue that is resolved https://github.com/bazelbuild/bazel/issues/10305 
This commit indicates this was a problem in the past https://github.com/bazelbuild/bazel/commit/fe7b4ef4e05d65b4bb56626d622225a9c81b7903

### Any other information, logs, or outputs that you want to share?

This is an example stacktrace from the Mac:

```
java.net.ConnectException: Operation not permitted (connect failed)
javax.ws.rs.ProcessingException: 
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:267)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:408)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:308)
	at com.redacted.dropwizard.bundle.ShutdownDetectionBundleDisabledTest.testHealthCheckEndpointDoesNotIncludeShutdownHealthCheck(ShutdownDetectionBundleDisabledTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
	at com.redacted.junit5.BazelTestRunner.main(BazelTestRunner.java:31)
Caused by: 
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:376)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:265)
	... 85 more
```

**Comment by jvolkman** [comment]
Maybe related to this comment: https://github.com/bazelbuild/bazel/issues/5206#issuecomment-402398624

**Comment by meisterT** [comment]
This behavior stems from a fundamental limitation in macOS sandboxing compared to Linux:

- **Linux (`linux-sandbox`)**: Uses Linux network namespaces (`CLONE_NEWNET`) with an isolated `lo` (loopback) interface. Tests tagged with `block-network` can hermetically bind to `127.0.0.1`/`localhost` with zero external access.
- **macOS (`DarwinSandboxedSpawnRunner`)**: Uses Apple Seatbelt (`sandbox-exec`) via `.sb` profiles:
  ```scheme
  (deny network*)
  (allow network-inbound (local ip "localhost:*"))
  (allow network* (remote ip "localhost:*"))
  ```

Most mock servers and test frameworks (such as OkHttp `MockWebServer`, Dropwizard, and Java `ServerSocket(0)`) bind to wildcard `INADDR_ANY` (`0.0.0.0` or `::`) by default. Under Apple's Seatbelt:
1. `(local ip "localhost:*")` does not match `0.0.0.0` or numeric `127.0.0.1`/`::1`, causing the kernel to throw `EPERM` (`Operation not permitted` / `ConnectException`).
2. Broadening the profile to `(allow network-bind)` or `(allow network*)` would allow binding and traffic across physical network interfaces (LAN/WAN), defeating the hermetic isolation guarantees of `block-network`.
3. Because Apple's `sandbox-exec` is deprecated and macOS does not expose unprivileged network namespace APIs, Bazel cannot enforce hermetic loopback-only networking on Darwin without compromising sandbox isolation.

### Recommended Workarounds
- **Platform-conditional tagging**:
  ```python
  java_test(
      name = "my_test",
      srcs = ["MyTest.java"],
      tags = select({
          "@platforms//os:osx": ["requires-network"],
          "//conditions:default": ["block-network"],
      }),
  )
  ```
- **Local strategy override**: Run tests locally on macOS with `--strategy=TestRunner=standalone` or `--spawn_strategy=local`.

**Comment by pcjanzen** [comment]
> * **Platform-conditional tagging**:
> ```       
>       tags = select({
>           "@platforms//os:osx": ["requires-network"],
>           "//conditions:default": ["block-network"],
>       }),
>   )

Sadly, tags are non-configurable, so this doesn't actually work.

**Comment by fmeum** [comment]
@meisterT What do you think of making this change? It would solve the issue at the cost of allowing inbound connections from the local machine into the sandbox (but not the other way round):

```patch
diff --git a/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java b/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java
index 84ed0b15de1f1b..e0d5e8cb67f8a4 100644
--- a/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java
+++ b/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java
@@ -282,8 +282,18 @@ private static void writeConfig(
 
       if (!allowNetwork) {
         out.println("(deny network*)");
+        // Binding to any local address must be allowed: servers commonly bind to the wildcard
+        // address (0.0.0.0 or ::), which the "localhost" filter does not match, and a bound
+        // socket cannot be used to talk to other hosts anyway because inbound and outbound
+        // traffic is restricted to loopback below. This mirrors the Linux sandbox, where
+        // arbitrary binds succeed inside the network namespace but only the loopback
+        // interface is available. See https://github.com/bazelbuild/bazel/issues/14828.
+        out.println("(allow network-bind (local ip \"*:*\"))");
         out.println("(allow network-inbound (local ip \"localhost:*\"))");
         out.println("(allow network* (remote ip \"localhost:*\"))");
+        // Unix domain sockets are filesystem-scoped IPC and cannot reach other hosts, so
+        // allow them in both directions, just like the Linux network namespace does.
+        out.println("(allow network* (local unix-socket))");
         out.println("(allow network* (remote unix-socket))");
       }
```

**Comment by meisterT** [comment]
Thanks Paul for calling this out.

Fabian, interesting idea - I assume this addresses what people requested here without compromising the idea of the network sandbox
