### ISSUE TITLE
NPE when building code (possibly due to cache corruption?)

### ISSUE THREAD

**Issue by neal-codaio** [bazelbuild/bazel#14856]
### Description of the problem / feature request:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//modules/browser-website:browser-website, config=BuildConfigurationValue.Key[0b97c0460d3ead7cb9105b5fe406d7886ee022fbfe3ec33cc470d420328b1588]}, actionIndex=1}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, actionLookupKey=ConfiguredTargetKey{label=//modules/browser-website:browser-website, config=BuildConfigurationValue.Key[0b97c0460d3ead7cb9105b5fe406d7886ee022fbfe3ec33cc470d420328b1588]}, willTest=false}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.http.HttpCacheClient.isChannelPipelineEmpty(HttpCacheClient.java:434)
	at com.google.devtools.build.lib.remote.http.HttpCacheClient.lambda$acquireUploadChannel$1(HttpCacheClient.java:304)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The above crash happened twice on the same commit containing the following single code change.  On two subsequent runs, it succeeded with the same commit.  Thus, we suspect a corrupt cache unrelated to this code change.

The code change was not to any BUILD files and seems unrelated.

### What operating system are you running Bazel on?

```
 Kernel Version: 5.11.0-1027-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
```

### What's the output of `bazel info release`?

`release 5.0.0`

### Any other information, logs, or outputs that you want to share?

This occurred when running our build on CircleCI.  We restore the cache and it's possible the cache was corrupted.

**Comment by aiuto** [comment]
There is not enough data here to reproduce your issue.

**Comment by nigel-codaio** [comment]
This might be related to https://github.com/bazelbuild/bazel/pull/14258 which concerns failures when using a remote HTTP cache which we are using.   It's an intermittent issue that seems to be occurring more frequently and seems to align with rate limit errors.

In the build logs we see:
```
WARNING: Remote Cache: 429 Too Many Requests
```

**Comment by sgowroji** [comment]
Hello @neal-codaio, Could you please respond to the above [comments](https://github.com/bazelbuild/bazel/issues/14856#issuecomment-1051414977) and provide the necessary information required to triage this issue. We will be closing this issue after 7 days if there is no significant update on it. Thanks!
