### ISSUE TITLE
cquery crashes Bazel while computing all external targets

### ISSUE THREAD

**Issue by mvukov** [bazelbuild/bazel#14855]
### Description of the problem / feature request:

cquery crashes Bazel while computing all external targets.

I found this out while extending [bazel-diff](https://github.com/Tinder/bazel-diff) to support cquery under the hood.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is the minimum example together with the command output:
```
$ bazel cquery '//external:all-targets'
Starting local Bazel server and connecting to it...
Analyzing: 448 targets (0 packages loaded, 0 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//external:WORKSPACE, config=null}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:257)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1018)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more
```

I ran this on two repos, I get the same output.

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

4.1.0

###  Have you found anything relevant by searching the web?

Nope.

**Comment by gregestren** [comment]
Wow. That's a pretty bad crash and so easy to reproduce!

Note this isn't caused by `cquery`. You can also reproduce with:

```
$ bazel build --nobuild //external:all-targets    # --nobuild just skips action execution for working builds (which this isn't!)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node '//external:all-targets, excludedSubdirs=[], filteringPolicy=com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual@7dab797e' (requested by nodes '[//external:all-targets] EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:bazel_tools
	at com.google.devtools.build.lib.packages.Rule.getAttr(Rule.java:499)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:61)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:44)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:230)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:109)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:87)
	at com.google.devtools.build.lib.pkgcache.TargetPatternResolverUtil.resolvePackageTargets(TargetPatternResolverUtil.java:47)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:139)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:446)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:95)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
	... 4 more
```

I replicated this with Bazel 5.0.

**Comment by gregestren** [comment]
Switched to `team-ExternalDeps` since the error is builds on `//external`.  

Actually my stack trace looks a little different. Mine says

    No such attribute tags in local_repository rule //external:bazel_tools

I see that on both 5.0 and 4.1.0. 

`team-ExternalDeps`: if you decide the cquery error really is cquery-specific, please let me know and we'll look at that side.

**Comment by Wyverald** [comment]
`//external` is an abomination. It doesn't really work with *anything* (other than some very limited `bazel query`, I suppose). Targets in there can't be built or configured, so `build` or `cquery` not working is expected.

What we should really do is to fail early and just error with "this doesn't make sense".

**Comment by mvukov** [comment]
In all honesty, I don't need anything fancy, just something like [this](https://github.com/Tinder/bazel-diff/blob/master/src/main/java/com/bazel_diff/BazelClient.java#L52) for bazel-diff -- I'd like to use cquery instead of query in there. Are there alternatives?

**Comment by Wyverald** [comment]
Why do you want to use cquery for `//external`? What information are you expecting from it? (Sorry I'm not very familiar with bazel-diff)

**Comment by gregestren** [comment]
Semantics aside, it is worth at least stopping bazel from crashing.  @Wyverald what do you think would be the easiest fix that at least avoids a crash? 

Note there's a history here:

- https://github.com/bazelbuild/bazel/issues/10602
- https://github.com/bazelbuild/bazel/issues/13454
- https://github.com/bazelbuild/bazel/issues/14855

**Comment by gregestren** [comment]
As reference in my earlier comment, I think a "crash -> error message" fix probably belongs in the `build` command, since that crashes too. That would automatically propagate to `cquery`.

**Comment by Wyverald** [comment]
Note that the last one (#12604) isn't quite the same as this one; it's not querying in `//external`, but in `@some_repo//...`. But all 3 others look like dupes.

**Comment by mvukov** [comment]
[Here](https://github.com/Tinder/bazel-diff) is a short intro on how bazel-diff works. One of the important aspects where bazel-diff shines is returning relevant targets from the main workspace when an external repository changes. For instance, when we upgrade an external package version via http_archive. That's why it needs to query all external targets as well.

Just for the reference: at the moment I run bazel-diff (which internally uses query) and then I pass the results to cquery. This can become problematic if the number of returned targets from bazel-diff would be huge as cquery doesn't support `--query_file` argument (yet). So, I thought it would be smarter to run cquery directly in bazel-diff.

**Comment by Wyverald** [comment]
Then it sounds like the sensible thing to do here is cquery the main repo and query `//external` and check the union for diffs, no? Running cquery on `//external` still doesn't make sense.

**Comment by mvukov** [comment]
Didn't look into the details, but a recent bazel-diff can work with cquery under the hood. Thanks for all the feedback.
