### ISSUE TITLE
bazel  --experimental_use_sandboxfs crashes on Windows:

### ISSUE THREAD

**Issue by korDen** [bazelbuild/bazel#14927]
### Description of the problem / feature request:

bazel  --experimental_use_sandboxfs crashes on Windows:

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException
        at com.google.devtools.build.lib.windows.WindowsSubprocessFactory.create(WindowsSubprocessFactory.java:54)
        at com.google.devtools.build.lib.shell.SubprocessBuilder.start(SubprocessBuilder.java:230)
        at com.google.devtools.build.lib.versioning.GnuVersionParser.fromProgram(GnuVersionParser.java:132)
        at com.google.devtools.build.lib.sandbox.RealSandboxfsProcess.mount(RealSandboxfsProcess.java:114)
        at com.google.devtools.build.lib.sandbox.SandboxModule.setup(SandboxModule.java:255)
        at com.google.devtools.build.lib.sandbox.SandboxModule.registerSpawnStrategies(SandboxModule.java:150)
        at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:170)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:206)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:446)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:413)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:164)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:295)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

cc_binary(
    name = "test",
    srcs = ["test.cc"], // test.cc is blank
)

 bazel run --experimental_use_sandboxfs test

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by larsrc-google** [comment]
I don't expect that SandboxFS would work on Windows. The [docs](https://docs.bazel.build/versions/main/sandboxing.html#install-sandboxfs) certainly don't say anything about that, and I believe a number of the features used are Unix-only.

**Comment by benjaminp** [comment]
217fafe2b492de7349547cc3be2b9eef38628055
