### ISSUE TITLE
Bazel cquery crashing with a stack trace, asking to ping "b/150301500 or contact the blaze configurability team"

### ISSUE THREAD

**Issue by borancar** [bazelbuild/bazel#15079]
### Description of the problem / feature request:

Bazel cquery will crash with something similar to:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: query-requested node 'ConfiguredTargetKey{label=@org_golang_x_tools//cmd/goimports:goimports, config=BuildConfigurationValue.Key[4d498c45554873ec5759362a68427cef5b8c3da393a8813902396bb756aafdf5]}' was unavailable in the query environment graph. If you come across this error, please ping b/150301500 or contact the blaze configurability team.
```
or
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: ToolchainContextKey{configurationKey=BuildConfigurationValue.Key[beffc25b26347f53bb6e6aa5e7c410d14dd4082be0e4b4b9ebdcf0cee34e129c], requiredToolchainTypeLabels=[@io_bazel_rules_go//go:toolchain], execConstraintLabels=[], forceExecutionPlatform=Optional.empty, debugTarget=false}
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Any cquery invocation has a small chance to crash. We do have a sizeable build graph.

### What operating system are you running Bazel on?

Seen this both on OSX and Linux.

### What's the output of `bazel info release`?

release 5.0.0, though we have seen this with previous relases too.

### Any other information, logs, or outputs that you want to share?

Here are the two recent stack traces:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: query-requested node 'ConfiguredTargetKey{label=@org_golang_x_tools//cmd/goimports:goimports, config=BuildConfigurationValue.Key[4d498c45554873ec5759362a68427cef5b8c3da393a8813902396bb756aafdf5]}' was unavailable in the query environment graph. If you come across this error, please ping b/150301500 or contact the blaze configurability team.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:428)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:476)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:296)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:101)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction$1.process(AllRdepsFunction.java:106)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:135)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:132)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:183)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.CombinedFuture$CombinedFutureInterruptibleTask.execute(CombinedFuture.java:104)
	at com.google.common.util.concurrent.CombinedFuture.handleAllCompleted(CombinedFuture.java:62)
	at com.google.common.util.concurrent.AggregateFuture.processCompleted(AggregateFuture.java:283)
	at com.google.common.util.concurrent.AggregateFuture.decrementCountAndMaybeComplete(AggregateFuture.java:265)
	at com.google.common.util.concurrent.AggregateFuture.access$200(AggregateFuture.java:42)
	at com.google.common.util.concurrent.AggregateFuture$1.run(AggregateFuture.java:147)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
	at com.google.common.util.concurrent.AggregateFuture.init(AggregateFuture.java:128)
	at com.google.common.util.concurrent.CombinedFuture.<init>(CombinedFuture.java:52)
	at com.google.common.util.concurrent.Futures$FutureCombiner.call(Futures.java:719)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenAllSucceedCall(AbstractQueryEnvironment.java:183)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenSucceedsCall(AbstractQueryEnvironment.java:160)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:130)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction.eval(AllRdepsFunction.java:88)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.lambda$evalWithBoundedDepth$0(RdepsFunction.java:130)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.lambda$transformAsync$0(AbstractQueryEnvironment.java:192)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:39)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:446)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.transformAsync(AbstractQueryEnvironment.java:190)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.evalWithBoundedDepth(RdepsFunction.java:132)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.eval(RdepsFunction.java:75)
	at com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
	at com.google.devtools.build.lib.query2.engine.RegexFilterExpression.eval(RegexFilterExpression.java:72)
	at com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:115)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:155)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.evaluateQuery(PostAnalysisQueryEnvironment.java:152)
	at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.doPostAnalysisQuery(PostAnalysisQueryBuildTool.java:182)
	at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.postProcessAnalysisResult(PostAnalysisQueryBuildTool.java:78)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:229)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:446)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:413)
	at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:152)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
 Exception 
Bazel query error (37): INFO: Reading 'startup' options from /Users/kdavydov/repos/grail/.bazelrc: --host_jvm_args=-Xmx4G
```

```
Bazel query error (37): INFO: Reading 'startup' options from /Users/bzhang/grail/.bazelrc: --host_jvm_args=-Xmx4G
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'cquery' from /Users/bzhang/grail/.bazelrc:
  Inherited 'build' options: --workspace_status_command=bazel/get_workspace_status.sh --define=gotags=bazel --stamp --copt=-ggdb -c opt --incompatible_enable_cc_toolchain_resolution --define=use_fast_cpp_protos=true --incompatible_strict_action_env --action_env=PATH=/usr/local/bin:/usr/sbin:/bin:/usr/bin --test_env=V23_CREDENTIALS --test_env=V23_CREDENTIALS_NO_LOCK=1 --test_env=V23_CREDENTIALS_NO_AGENT=1 --java_runtime_version=remotejdk_11 --tool_java_runtime_version=remotejdk_11 --tls_client_certificate=bazel/buildbuddy/buildbuddy-cert.pem --tls_client_key=bazel/buildbuddy/buildbuddy-key.pem --announce_rc

INFO: Found 93 targets...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: ToolchainContextKey{configurationKey=BuildConfigurationValue.Key[beffc25b26347f53bb6e6aa5e7c410d14dd4082be0e4b4b9ebdcf0cee34e129c], requiredToolchainTypeLabels=[@io_bazel_rules_go//go:toolchain], execConstraintLabels=[], forceExecutionPlatform=Optional.empty, debugTarget=false}
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:899)
	at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:124)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:462)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:476)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:296)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:101)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction$1.process(AllRdepsFunction.java:106)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:135)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:132)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:183)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.CombinedFuture$CombinedFutureInterruptibleTask.execute(CombinedFuture.java:104)
	at com.google.common.util.concurrent.CombinedFuture.handleAllCompleted(CombinedFuture.java:62)
	at com.google.common.util.concurrent.AggregateFuture.processCompleted(AggregateFuture.java:283)
	at com.google.common.util.concurrent.AggregateFuture.decrementCountAndMaybeComplete(AggregateFuture.java:265)
	at com.google.common.util.concurrent.AggregateFuture.access$200(AggregateFuture.java:42)
	at com.google.common.util.concurrent.AggregateFuture$1.run(AggregateFuture.java:147)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
	at com.google.common.util.concurrent.AggregateFuture.init(AggregateFuture.java:128)
	at com.google.common.util.concurrent.CombinedFuture.<init>(CombinedFuture.java:52)
	at com.google.common.util.concurrent.Futures$FutureCombiner.call(Futures.java:719)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenAllSucceedCall(AbstractQueryEnvironment.java:183)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenSucceedsCall(AbstractQueryEnvironment.java:160)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:130)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction.eval(AllRdepsFunction.java:88)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.lambda$evalWithBoundedDepth$0(RdepsFunction.java:130)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.lambda$transformAsync$0(AbstractQueryEnvironment.java:192)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:39)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:446)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.transformAsync(AbstractQueryEnvironment.java:190)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.evalWithBoundedDepth(RdepsFunction.java:132)
	at com.google.devtools.build.lib.query2.engine.RdepsFunction.eval(RdepsFunction.java:75)
	at com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
	at com.google.devtools.build.lib.query2.engine.RegexFilterExpression.eval(RegexFilterExpression.java:72)
	at com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:115)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:155)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.evaluateQuery(PostAnalysisQueryEnvironment.java:152)
	at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.doPostAnalysisQuery(PostAnalysisQueryBuildTool.java:182)
	at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.postProcessAnalysisResult(PostAnalysisQueryBuildTool.java:78)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:229)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:446)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:413)
	at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:152)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by borancar** [comment]
I now have a local repo where I can reproduce it every time. The repo is quite large (~10 GB packed), so am open to running inspection queries or suggestions how to convert it into a minimally reproducible example.

**Comment by gregestren** [comment]
Thanks for reporting this, @borancar and thanks for the clarifying error PR https://github.com/gkgoat1.

b/150301500 doesn't have much other insight beyond Googler user reports. The two other relevant comments on that bug are:

 - @janakdr : "looks like this can happen when a target in error has already declared a dep. That means there's an edge there to traverse, but no configured target on the other end of it." 
 - @gregestren - struggling to reproduce any of the failures (although @janakdr showed a reproduction on Google's repo I can try to replicate).

So the short story is, yes, getting a consistent reproduction is key to addressing this. I'd love a more minimal one from you @borancar but I'm not sure what to suggest to help you minimize it?

**Comment by janakdr** [comment]
@borancar does your reproduction repo have any loading/analysis errors in it?

Note, by the way, that contents of source files are not relevant for cquery, only BUILD/bzl files, and existence of some source files (ones consumed by globs), so there's probably a hacky way to get it smaller, although that's probably not the direction to expend our efforts in.

**Comment by gregestren** [comment]
Got a nice small repro from https://github.com/bazelbuild/bazel/issues/15380 (Bazel 5.1.1. for me). Adding `--noinclude_aspects` to the cquery call removes the crash (but that's not a suggested workaround since that reduces results).

**Comment by JamesMBartlett** [comment]
This is happening for me without aspects. I put together a fairly minimal repro here: https://github.com/JamesMBartlett/bazel_fatal_repro.

Running `./fail.sh` in that repo should fail with a very similar error to the above. Interestingly, if I remove either the `--action_env=HOME` in the .bazelrc or the `bazel info execution_root` in `fail.sh`, I no longer see the error.

**Comment by gregestren** [comment]
@JamesMBartlett interesting. It looks like calling `bazel info` in between is crucial to getting the failure.

A next step diagnosis would be to explore why.

**Comment by welshm** [comment]
I ran into this when running `cquery` in a loop (and I updated some of the bazel files in that loop, as a result of the `cquery` contents). My query didn't change in the loop

**Comment by cpsauer** [comment]
If useful, I was seeing this erratically on super simple test examples that I was cooking up for #18289.

Most recently `bazel cquery "allpaths(A, B)"` on
```
alias(
    name = "A",
    actual = ":a",
)
cc_library(
    name = "a",
    deps = ["B", "C"],
)
cc_library(
    name = "B",
    deps = ["C"],
)
cc_library(
    name = "C",
)
```
Blank WORKSPACE, blank .bazelrc. Latest rolling. No (intentional) calls to bazel info. latest macOS

**Comment by illicitonion** [comment]
> Got a nice small repro from #15380 (Bazel 5.1.1. for me). Adding `--noinclude_aspects` to the cquery call removes the crash (but that's not a suggested workaround since that reduces results).

Was there any progress on investigating this repro?

I did a little poking around, and it seems like there's a stale edge in the underlying `SkyframeExecutor` graph pointing at a GC'd node, which presumably is being kept around by a bug in aspect evaluation of a shared dependency which keeps edges falsely alive? But I definitely don't know the Skyframe/aspect code enough to be efficient at fixing this!

**Comment by gregestren** [comment]
@haxorz does the comment above sound  Bazel core relevant? i.e. is there an issue with `SkyframeExeuctor` and GCing, or does this read like an issue at the cquery or Skyframe consumer layer?

**Comment by haxorz** [comment]
> I did a little poking around, and it seems like there's a stale edge in the underlying SkyframeExecutor graph pointing at a GC'd node

What do you mean when you say "GC'd node"? Are you just trying to convey that there's seemingly an edge to a no-longer-existent node?

> @haxorz does the comment above sound Bazel core relevant? i.e. is there an issue with SkyframeExeuctor and GCing, or does this read like an issue at the cquery or Skyframe consumer layer?

Not sure. I'd need more information to have a strong guess. A more minimal repro would be nice too.

The consumer code in `PostAnalysisQueryEnvironment#targetifyValues` is a little weird in the sense that it's peeking at the values of direct deps. But the inconsistency described by @illicitonion would have been introduced elsewhere.

My weak guess is that this is related to the `cquery`/`aquery` side of what I wrote in internal issue 145772216 ("skyquery is blatantly incorrect on flips of the value of the --universe_scope flag"). Does every repro of this issue here involve varying the universe (the phrasing of #15380 makes me think the universe is varying)?

**Comment by illicitonion** [comment]
> > I did a little poking around, and it seems like there's a stale edge in the underlying SkyframeExecutor graph pointing at a GC'd node
> 
> What do you mean when you say "GC'd node"? Are you just trying to convey that there's seemingly an edge to a no-longer-existent node?

Yes, exactly that :)
 
> > @haxorz does the comment above sound Bazel core relevant? i.e. is there an issue with SkyframeExeuctor and GCing, or does this read like an issue at the cquery or Skyframe consumer layer?
> 
> Not sure. I'd need more information to have a strong guess. A more minimal repro would be nice too.

https://github.com/alexander-scott/bazel_bug_reproduce_1 is the smallest repro I've seen so far.

> My weak guess is that this is related to the `cquery`/`aquery` side of what I wrote in internal issue 145772216 ("skyquery is blatantly incorrect on flips of the value of the --universe_scope flag"). Does every repro of this issue here involve varying the universe (the phrasing of #15380 makes me think the universe is varying)?

Every repro I've seen has involved a target getting deleted between the two invocations. This does change what's in the universe being queried over, but doesn't involve the `--universe_scope` flag.

**Comment by tbaing** [comment]
I just hit this on successive cquery invocations with no changes to my Bazel files and no `bazel info` invocations in between. I did run slightly different queries (I was querying for deps of specific targets, with the failed second query looking at a different target than the first), but no other actions I'm aware of that match the things listed in this thread. I then re-ran the failed query and it succeeded, so it's not reliably reproducible.

There were no loading/analysis errors in any of the three queries.

**Comment by qyang-nj** [comment]
We are running into this as well and following the error message to post here. In our case, after we upgraded one of the dependency rule set,  it now constantly happens on `cquery` with test targets,

**Comment by gregestren** [comment]
> > My weak guess is that this is related to the `cquery`/`aquery` side of what I wrote in internal issue 145772216 ("skyquery is blatantly incorrect on flips of the value of the --universe_scope flag"). Does every repro of this issue here involve varying the universe (the phrasing of #15380 makes me think the universe is varying)?
> 
> Every repro I've seen has involved a target getting deleted between the two invocations. This does change what's in the universe being queried over, but doesn't involve the `--universe_scope` flag.

I can reproduce https://github.com/alexander-scott/bazel_bug_reproduce_1 as you have. 

To be clear, this Github issue refers to two different errors: an `IllegalStateException` that says `ping b/150301500` and a `NullPointerException` that doesn't. This produces the latter. I'm not sure if both errors have the same root cause.

The [relevant code](https://github.com/alexander-scott/bazel_bug_reproduce_1/blob/3fa8a44b3da793088bb391bbbcb5b5481663bce7/glob_scenario/BUILD#L1-L11):

```
[
    cc_test(
        name = test_name,
        srcs = [
            test_name + ".cpp",
        ],
    )
    for test_name in [filename.replace(".cpp", "") for filename in glob(
        include = ["*_test.cpp"],
    )]
]
```

where originally both `1_test.cpp` and `2_test.cpp` exist. But the user manually deletes `2_test.cpp` before running the breaking `NullPointerException` `cquery`. 

This: 

https://github.com/bazelbuild/bazel/blob/69fa6cb169e23c1b985bfa08ea8bc0b1f1199a63/src/main/java/com/google/devtools/build/skyframe/InMemoryGraphImpl.java#L265 

returns an `InMemoryNodeEntry` with a `reverseDeps` field with an entry to `ConfiguredTargetKey(//glob_scenario:2_test`.

That fails to resolve to a valid `ConfiguredTarget` value at https://github.com/bazelbuild/bazel/blob/69fa6cb169e23c1b985bfa08ea8bc0b1f1199a63/src/main/java/com/google/devtools/build/skyframe/InMemoryGraphImpl.java#L265 (same code but on the rdep) which causes the `NullPointerException`.

So `InMemoryGraphImpl` is in an inconsistent state. As @illicitonion mentions the *actual* query scope changes because of the deleted file, but the `--universal_scope` *flag* doesn't.

**Comment by gregestren** [comment]
I added breakpoints on https://github.com/bazelbuild/bazel/blob/620d617b440258799caa1be434ed66e9ca8fa8c5/src/main/java/com/google/devtools/build/skyframe/ReverseDepsUtility.java#L141 and https://github.com/bazelbuild/bazel/blob/620d617b440258799caa1be434ed66e9ca8fa8c5/src/main/java/com/google/devtools/build/skyframe/ReverseDepsUtility.java#L145 and noticed neither hits before the `NullPointerException`. 

That intuitively sounds wrong?

**Comment by gregestren** [comment]
> * Due to our CI disabling Bazel convenience symlinks, there are no `bazel-*` symlinks available. This forces developers to create scripts that depend on `bazel info bazel-bin` output. Therefore, the usage of `bazel info` is quite extensive in that setup.

@sluongng I'm not sure if this helps for you, but do you know about `bazel cquery --output=files`? That can avoid some uses of `bazel info`.

**Comment by wsmoses** [comment]
Hey folks, just hit this issue in our CI here: https://github.com/EnzymeAD/Enzyme-JAX/actions/runs/10019102897/job/27695284936?pr=105

**Comment by fmeum** [comment]
~https://github.com/bazelbuild/bazel/commit/099f0e50610c9abbdb71c6d88553f99df7bead9f is the first commit with which the reproducer no longer crashes.~ Turned out to be a red herring, I'll send a completely different fix.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.4.0rc1. Thanks!
