### ISSUE TITLE
JacocoCoverage_jarjar_deploy.jar's shading of Guava is incomplete, causing some user tests to fail with bazel coverage

### ISSUE THREAD

**Issue by thirtyseven** [bazelbuild/bazel#15124]
### Description of the problem / feature request:

While upgrading our repo to Bazel 5.1 from 4.2.2, we found some Java tests that depend on Guava were now failing but only with `bazel coverage`, not with `bazel test`. Test failures gave this stacktrace:

```
java.lang.NoSuchFieldError: EXACT
	at com.google.common.net.InternetDomainName.findSuffixOfType(InternetDomainName.java:170)
	at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:151)
	at com.google.common.net.InternetDomainName.from(InternetDomainName.java:209)
        at <ourcode>
```

When stepping through in the debugger, I noticed that `com.google.thirdparty.publicsuffix.PublicSuffixPatterns.EXACT` was being loaded from JacocoCoverage_jarjar_deploy.jar, not the Guava jar being pulled in by the code under test. It seems JacocoCoverage has [shaded com.google.common using JarJar](https://github.com/bazelbuild/bazel/blob/6a219b5aa4a44682f25fdd7bdf7108aed7b0b816/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage.jarjar), but not com.google.thirdparty, which is also part of Guava.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel coverage` on a JUnit test that invokes `com.google.common.net.InternetDomainName.from("example.com")`

### What operating system are you running Bazel on?

macOS 12.3

### What's the output of `bazel info release`?

release 5.1.0

### Any other information, logs, or outputs that you want to share?

This looks easy to fix, JacocoCoverage.jarjar just needs a rule to shade com.google.thirdparty.

**Comment by thirtyseven** [comment]
Created a minimal test case here: https://github.com/thirtyseven/bazel-coverage-bug-example

`bazel test //java:Test` passes, but `bazel coverage //java:Test` fails.
