### ISSUE TITLE
Upgrade netty to 4.1.75

### ISSUE THREAD

**Issue by dragonsinth** [bazelbuild/bazel#15142]
### Description of the problem / feature request:

Please upgrade Netty 4.1.69 -> 4.1.75

On linux, we frequently run into https://github.com/netty/netty/issues/11815

This is likely solved in Netty 4.1.75 via https://github.com/netty/netty/commit/1df38d2c7be98e11fa13c7ee52aadbfbea7669e6

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

There is no easy repro, it seems to be a race condition.  Only seems to appear on Linux, not Mac.  See below for stack trace.

### What operating system are you running Bazel on?

CircleCI image:

```
Build-agent version 1.0.117438-72c2fbdd (2022-03-29T17:30:21+0000)
System information:
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.13.0-1017-aws
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 ```

### What's the output of `bazel info release`?

```
root@62d8983e8522:/src/mn/projects/fullstory# bazel version
Bazelisk version: v1.4.0
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334


root@62d8983e8522:/src/mn/projects/fullstory# bazel info release
INFO: Invocation ID: 92faf5b1-4236-49ef-a704-9c2ee74d5bcb
INFO: Reading 'startup' options from /src/mn/projects/fullstory/.bazelrc.user: --shutdown_on_low_sys_mem, --max_idle_secs=5
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=179
INFO: Reading rc options for 'info' from /src/mn/projects/fullstory/.bazelrc:
  Inherited 'common' options: --enable_platform_specific_config --repository_cache=./bazel-cache/repos --experimental_repository_cache_hardlinks
INFO: Reading rc options for 'info' from /src/mn/projects/fullstory/.bazelrc.user:
  Inherited 'common' options: --repository_cache=/tmp/bazel/repo_cache
INFO: Reading rc options for 'info' from /src/mn/projects/fullstory/.bazelrc:
  Inherited 'build' options: --strategy=TypeScriptCompile=worker --remote_cache=https://bazel-cache.ops.fs.team --google_default_credentials --remote_upload_local_results=false --disk_cache=./bazel-cache --incompatible_remote_results_ignore_disk --incompatible_exclusive_test_sandboxed --define=GCR_REPOSITORY=fs-ops/feature-builds --define=GCR_REGISTRY_PREFIX=gcr.io --incompatible_strict_action_env --workspace_status_command=./tools/bazelbuild/load_build_info.sh
INFO: Reading rc options for 'info' from /src/mn/projects/fullstory/.bazelrc.user:
  Inherited 'build' options: --show_progress --build_tag_filters=-no-ci --local_cpu_resources=2 --local_ram_resources=2048 --action_env=NODE_OPTIONS --worker_max_instances=TypeScriptCompile=1 --discard_analysis_cache --nokeep_state_after_build --notrack_incremental_state --announce_rc --google_credentials=/root/gcloud-service-key.json --disk_cache=/tmp/bazel/action_cache --remote_upload_local_results=true --jobs 10
release 5.0.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
fatal: not a git repository (or any of the parent directories): .git
```

###  Have you found anything relevant by searching the web?

Yes.. see above Netty issue. https://github.com/netty/netty/issues/11815

### Any other information, logs, or outputs that you want to share?

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//go/src/fs/services/alexa/main/alexa:alexa, config=BuildConfigurationValue.Key[48a7a349feeea004bb328fa5c50a7b593c6e17033e218e2151db12a21b868035]}, actionIndex=1}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, actionLookupKey=ConfiguredTargetKey{label=//go/src/fs/services/alexa/main/alexa:alexa, config=BuildConfigurationValue.Key[48a7a349feeea004bb328fa5c50a7b593c6e17033e218e2151db12a21b868035]}, willTest=false}', 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//go/src/fs/services/alexa/main/alexa:alexa, config=BuildConfigurationValue.Key[48a7a349feeea004bb328fa5c50a7b593c6e17033e218e2151db12a21b868035]}, actionIndex=4}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: javax.net.ssl.SSLException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1071)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1365)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1305)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1392)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:217)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	... 21 more
```

**Comment by vpanta** [comment]
I have put up a prospective PR for this upgrade, and as far as I can tell everything is still hooked up correctly in my branch.

**Comment by vpanta** [comment]
Fun stuff, the `netty` update isn't working because `grpc-java` has a bug the new version of `netty` triggers. It was fixed in release `1.45.1`, which I'll need to update as well.

**Comment by vpanta** [comment]
After attempting to bring `grpc-java` up to `1.45.1` (along with `grpc` up to `1.45.0`), I now get a new slew of build errors around not being able to find `@io_bazel_rules_go_name_hack` repository (formatted for readability):
```
ERROR: /private/var/tmp/_bazel_vasilios/a66b1d3a8126aa917c2980f966604cd1/external/com_github_grpc_grpc/BUILD:5254:23:
    error loading package '@com_github_cncf_udpa//xds/data/orca/v3':
     at /private/var/tmp/_bazel_vasilios/a66b1d3a8126aa917c2980f966604cd1/external/com_github_cncf_udpa/bazel/api_build_system.bzl:1:6:
     at /private/var/tmp/_bazel_vasilios/a66b1d3a8126aa917c2980f966604cd1/external/com_envoyproxy_protoc_gen_validate/bazel/pgv_proto_library.bzl:1:6:
     at /private/var/tmp/_bazel_vasilios/a66b1d3a8126aa917c2980f966604cd1/external/io_bazel_rules_go/proto/compiler.bzl:25:5:
     at /private/var/tmp/_bazel_vasilios/a66b1d3a8126aa917c2980f966604cd1/external/io_bazel_rules_go/go/private/rules/transition.bzl:32:5:
     Unable to find package for @io_bazel_rules_go_name_hack//:def.bzl:
       The repository '@io_bazel_rules_go_name_hack' could not be resolved:
         Repository '@io_bazel_rules_go_name_hack' is not defined.
         and referenced by '@com_github_grpc_grpc//:xds_orca_upb'
```

This seems to be a [recently-removed piece of `rules_go`](https://github.com/bazelbuild/rules_go/commit/80d5afeb3f9d5eef99161e9f032a90d3c6074525), but given how deep that is (4 workspaces beneath the top-level), I have no idea how to fix it.

**Comment by vpanta** [comment]
Woohoo! I've updated #15145 to do a minor re-org, update `grpc-java` to `1.45.1`, and update `netty` to `4.1.75` and things seem happy. It should be ready for review, everything in CI is passing and bazel seems to be working appropriately.

**Comment by vpanta** [comment]
https://github.com/bazelbuild/bazel/commit/68277ec256fc6827ad46e909727d8e146741814d (#15145) should allow this to be closed, at least given the initial comment.

Unfortunately, it does not seem that this change has (fully) fixed the `BAD_DECRYPT` errors we're seeing in CI (https://github.com/bazelbuild/bazel/issues/15142). We've been using a forked version based on the branch under #15145 and we just got another error today :(

But still, this GH Issue should be closable at the moment, and if we find more steps we can open a new issue.

**Comment by coeuvre** [comment]
Closing and feel free to create another issue.
