### ISSUE TITLE
Changes to builtin (java) rules are not reflected with documented workflow

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/bazel#15544]
### Description of the bug:

Changes made to local bazel fork, under `src/main/java/com/google/devtools/build/lib/rules/java` for example, are not reflected at runtime. This blocks contributor development to this project as there is not way to test our changes without documented how this should be done.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. For bazel, edit locally src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java and add in constructor something that should crash (`Object o = null; o.hashCode()`, a division by 0, whatever)
2. Build bazel locally, as explained in [doc](https://bazel.build/contribute/getting-started) : `bazel build //src:bazel `
3. Use locally built bazel (i.e `bazel-bin/src/bazel`) to build a simple java project. 

Result : compilation should fail, but it succeeds.. The changes done locally to builtin java rule are not taken into account.

### Which operating system are you running Bazel on?

macos

### Have you found anything relevant by searching the web?

No.

**Comment by oliviernotteghem** [comment]
cc @alexjski @comius @katre

You guys have been making changes to java rule recently, so you probably know the workflow to get my changes deployed locally / testable. thanks.

**Comment by alexjski** [comment]
I just tried that, added an exception to the constructor of JavaCompileAction, build new bazel ran it and got a failure:

```
$ bazel build //src:bazel-bin
$ bazel-bin/src/bazel --output_base=/tmp/not_here build //src:bazel-bin
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Analyzing: target //src:bazel-bin (355 packages loaded, 8593 targets configured)
    Fetching @remotejdk11_linux; fetching 25s
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//src/main/java/com/google/devtools/build/lib/skyframe/serialization:codec-scanning-constants, config=BuildConfigurationKey[5a6b118716980ecf2532d6026f846cd142a09988b3da11746de1255390a151ae]}' (requested by nodes 'ConfiguredTargetKey{label=//src/main/java/com/google/devtools/build/lib/skyframe/serialization/autocodec:serialization-constant-processor, config=BuildConfigurationKey[5a6b118716980ecf2532d6026f846cd142a09988b3da11746de1255390a151ae]}', 'ConfiguredTargetKey{label=//src/main/java/com/google/devtools/build/lib/skyframe/serialization:serialization, config=BuildConfigurationKey[5a6b118716980ecf2532d6026f846cd142a09988b3da11746de1255390a151ae]}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:665)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalStateException thrown during Starlark evaluation (//src/main/java/com/google/devtools/build/lib/skyframe/serialization:codec-scanning-constants)
        at <starlark>.compile(<builtin>:0)
        at <starlark>.compile_action(/virtual_builtins_bzl/common/java/compile_action.bzl:137)
        at <starlark>.basic_java_library(/virtual_builtins_bzl/common/java/java_common.bzl:127)
        at <starlark>.bazel_java_library_rule(/virtual_builtins_bzl/common/java/java_library.bzl:68)
        at <starlark>._proxy(/virtual_builtins_bzl/common/java/java_library.bzl:98)
Caused by: java.lang.IllegalStateException: oh no
        at com.google.devtools.build.lib.rules.java.JavaCompileAction.<init>(JavaCompileAction.java:201)
        at com.google.devtools.build.lib.rules.java.JavaCompileActionBuilder.build(JavaCompileActionBuilder.java:295)
...
```
This makes me want to close that as no-repro/WAI. Are you sure you were running the Bazel you built yourself after you changed `JavaCompileAction`? Or were you running the one in your path?

`JavaCompileAction` is a native action, therefore it actually comes in the Bazel binary as opposed to from the repository, therefore your local installation of Bazel will keep using whatever is built-into it, irrespective of local code changes.

**Comment by comius** [comment]
I regularly follow the workflow that's in the description and I can confirm it's working. Closing the issue as not reproducible.

**Comment by oliviernotteghem** [comment]
@[alexjski](https://github.com/alexjski) : thanks. I tried on a different machine and workflow works 100%. 

Let's close!
