### ISSUE TITLE
Bazel crashes due to internal error(Could not build bazel)

### ISSUE THREAD

**Issue by veera20** [bazelbuild/bazel#15622]
### Description of the bug:

~/vee# ls
AUTHORS       CODEOWNERS	  ISSUE_TEMPLATE.md  WORKSPACE		   combine_distfiles_to_tar.sh	distdir_deps.bzl  site
BUILD	      CODE_OF_CONDUCT.md  LICENSE	     WORKSPACE.bzlmod	   compile.sh			examples	  src
CHANGELOG.md  CONTRIBUTING.md	  README.md	     bazel-5.1.1-dist.zip  derived			platforms	  third_party
CODEBASE.md   CONTRIBUTORS	  SECURITY.md	     combine_distfiles.py  distdir.bzl			scripts		  tools
root@Exaleap-Unmatched-Linux-1:~/vee# env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
🍃  Building Bazel from scratch..

....
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Analyzing: target //src:bazel_nojdk (100 packages loaded, 264 targets configur\
ed)
    currently loading: src/tools/android/java/com/google/devtools/build/androi\
d/desugar/scan
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:@local_jdk//' (requested by nodes '@local_jdk//:runtime_toolchain_definition, excludedSubdirs=[], filteringPolicy=RuleTypeFilter{ruleName=toolchain, keepExplicit=true}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/bazel_AZQivv1a/out/external/local_jdk/lib/ssl-1.1/certs/NetLock_Arany_=Class_Gold=_F??tan??s??tv??ny.pem
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:121)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:80)
	at com.google.devtools.build.lib.vfs.JavaIoFileSystem.stat(JavaIoFileSystem.java:435)
	at com.google.devtools.build.lib.vfs.FileSystem.statNullable(FileSystem.java:510)
	at com.google.devtools.build.lib.vfs.FileSystem.readdir(FileSystem.java:630)
	at com.google.devtools.build.lib.vfs.Path.readdir(Path.java:285)
	at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.readdirImpl(PerBuildSyscallCache.java:247)
	at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.access$300(PerBuildSyscallCache.java:34)
	at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache$Builder.lambda$build$1(PerBuildSyscallCache.java:96)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:239)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:235)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.readdir(PerBuildSyscallCache.java:103)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobVisitor.reallyGlob(UnixGlob.java:837)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobVisitor.access$900(UnixGlob.java:494)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobVisitor$1.run(UnixGlob.java:637)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobVisitor.lambda$enqueue$0(UnixGlob.java:670)
	at com.google.devtools.build.lib.packages.GlobCache.lambda$new$0(GlobCache.java:110)
	... 6 more

ERROR: Could not build Bazel

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am trying to replica the steps provided in Build Bazel from scratch (bootstrapping) document ,from https://github.com/bazelbuild/bazel/releases from this link downloaded bazel-5.1.1-dist.zip file and i am using openjdk19 version ,running (env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh ) i am facing above bug

### Which operating system are you running Bazel on?

linux,riscv target

**Comment by sgowroji** [comment]
Hello @veera20, Do you have any specific steps to reproduce the above exception.

**Comment by veera20** [comment]
I am trying to replica the steps provided in Build Bazel from scratch (bootstrapping) document(https://bazel.build/install/compile-source) ,from https://github.com/bazelbuild/bazel/releases from this link downloaded bazel-5.1.1-dist.zip file and i am using openjdk19 version ,running (env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh ) i am facing above bug

**Comment by veera20** [comment]
@sgowroji and also i am using openjdk19 to build bazel
