### ISSUE TITLE
socks5h proxy incompatible with bazel

### ISSUE THREAD

**Issue by michael-etzkorn** [bazelbuild/bazel#15652]
### Description of the bug:

Set socks5h proxy up. 
Get 'unexpected end of file' even though a server request isn't dropped from the remote. 

If I define the socks proxy through https_proxy or http_proxy environment variables, I get this:
```
  /home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/google/bazel_rules_install/archive/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip failed: class java.net.SocketException Unexpected end of file from server
ERROR: An error occurred during the fetch of repository 'com_github_google_rules_install':
   Traceback (most recent call last):
        File "/home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/bazel_rules_install/archive/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip] to /home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/com_github_google_rules_install/temp13652766119651506365/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip: Unexpected end of file from server
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/bazel_rules_install/archive/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip] to /home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/com_github_google_rules_install/temp13652766119651506365/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip: Unexpected end of file from server
ERROR: no such package '@com_github_google_rules_install//': java.io.IOException: Error downloading [https://github.com/google/bazel_rules_install/archive/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip] to /home/michaele/.cache/bazel/_bazel_michaele/399ee26744b01017f647eca996d74b04/external/com_github_google_rules_install/temp13652766119651506365/4cd8ab0b5d8a0117bb5b8c89a0024508d5d4d5ed.zip: Unexpected end of file from server

```

Other build servers like sbt and running `git clone` work with no issue. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not particularly easy to set-up. 

- two servers
- one offline. On offline one attempt to run build from verible at https://github.com/chipsalliance/verible
- use /etc/yum.conf to add a ssh as a socks5h proxy. 
   - proxy=socks5h://localhost:port
- `ssh -D port USER@SERVER_WITH_WEB_ACCESS`
- One of the following:
    - $JAVA_OPTS are set to `-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=port'
        - passed in through `--host_jvm_args` 
    - $http_proxy and $https_proxy are set to http://localhost:port and https://localhost:port 
- then tried running  `bazel build -c opt //...`

### Which operating system are you running Bazel on?

CentOS Linux release 7.9.2009 (Core)

### What is the output of `bazel info release`?

release 4.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
I'm on version 1.8 of git. This doesn't work.

But it's the master branch of verible: https://github.com/chipsalliance/verible
commit: dd5e91a4c632b47c8721784e23bf3acc6f46afbc
```

### Have you found anything relevant by searching the web?

https://docs.bazel.build/versions/0.29.1/external.html
doesn't mention socks5h at all for proxy. 

I don't think this is a case of "unexpected end of file" due to server issues like discussed here https://stackoverflow.com/questions/19824339/java-simple-code-java-net-socketexception-unexpected-end-of-file-from-server

Other build servers, `yum update`, and `git clone` are working. 

### Any other information, logs, or outputs that you want to share?

It's possible I just have this set-up wrong, but it'd be nice if there was a built in socks_proxy offerred. Git http.proxy is set to socks5h://127.0.0.1:port and that works fine
- - -
Related Issues: #3893

**Comment by michael-etzkorn** [comment]
What I'm gathering is there's simply no socks5 proxy support. wget suffers a similar issue. Tools like `curl`, `sbt` ,and `git` work which suggests to me some limitation with how the requests are made. `$JAVA_OPTS` seems to be ignored even with the socks server specified.

**Comment by michael-etzkorn** [comment]
`--host_jvm_args="$JAVA_OPTS"` results in "Can't connect to SOCKS proxy"

**Comment by michael-etzkorn** [comment]
Ok, if I pass the `--host_jvm_args` one at a time, I can fetch with Java.IO over the socks proxy. I'm now hitting pip installation errors which I imagine can be fixed in a similar manner, but really the issue is Bazel has no switch for socks5 overall.

**Comment by michael-etzkorn** [comment]
I was able to resolve this by `--host_jvm_args` and installing PySocks for the build.
