### ISSUE TITLE
Allow repository rules to perform integrity checks

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel#15759]
### Description of the feature request:

Repository rules should be able to perform integrity checks or calculate the integrity of files.

Something like:

```starlark
# where ctx is repository_ctx

integrity = ctx.calculate_integrity(file = "some_file.txt")

# the format of the integrity object could be:
integrity == struct(
    sha1 = "",
    sha256 = "",
    sha384 = "",
    sha512 = "",
)

ctx.verify_integrity(
    file = "some_file.txt",
    integrity = "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC",
)
```

Alternatively, there could be just one `ctx.integrity` function which will both calculate and verify depending on whether the `integrity` attribute is given?

### What underlying problem are you trying to solve with this feature?

There are cases where resources cannot be fetched over HTTP and external tools must be used. In such case, it would be nice to have a native way to verify integrity without having to rely on the host to have `sha256sum`, `openssl`, etc installed.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

5.2.1

### Have you found anything relevant by searching the web?

Not much.

https://github.com/bazelbuild/bazel/issues/7323

**Comment by willstranton** [comment]
See #29179

Instead of naming the method `ctx.calculate_integrity()`, I named it `ctx.integrity_hash()`

I don't use the integrity return object/struct you had and instead just return the integrity hash.  When calling `integrity_hash`, you need to specify the hash algorithm to use.  The currently supported algorithms are the same as the [SRI spec](https://www.w3.org/TR/sri-2/):

* `sha256`
* `sha384`
* `sha512`

I didn't add a corresponding `verify_integrity` function since that can be accomplished with an if comparison check of the returned integrity hash. 

Example usage:

```
ctx.integrity_hash("sha256", ctx.attr.file)
# returns string "sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
```

**Comment by uhthomas** [comment]
Thanks! I guess the reason I thought a function specifically for checking integrity would be nice is that it could handle throwing integrity error messages to match the same format as native rules. The error messages usually contain the correct digest, and the calculated digest, and sometimes a suggestion of what attribute to set on the rule itself. I don't know if it would also make caching easier, rather than having to recalculate the digest every time the rule is invoked. It's been a few years, so please excuse me as I haven't thought about this for a while.

**Comment by willstranton** [comment]
> I don't know if it would also make caching easier... having to recalculate the digest every time the rule is invoked

Sorry, I don't know either.

> handle throwing integrity error messages to match the same format as native rules

Fwiw, see the below example `verify_integrity` code and the example output, which copies what I think the output that the native code has here: 

### Native code

https://github.com/bazelbuild/bazel/blob/93f38093f8e24875c1d015e67311853756bdb27e/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HashOutputStream.java#L84-L90

### Native failure output (`ctx.download(sha256='',...)`)

```
DEBUG: /home/ubuntu/project/example.bzl:10:8: <pending download to '/home/ubuntu/.cache/bazel/_bazel_ubuntu/aad5c67d9809019b8486943c7d2ff968/external/+example+rule/file'>
WARNING: Download from https://example.com/file failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 86d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6 but wanted 96d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6
INFO: Repo +test+rule defined by rule convert in @@//:example.bzl
ERROR: /home/ubuntu/project/example.bzl:11:19: An error occurred during the fetch of repository '+example+rule':
   Traceback (most recent call last):
	File "/home/ubuntu/project/example.bzl", line 11, column 19, in _impl
		token = ctx.download(
Error in download: java.io.IOException: Error downloading [https://example.com/file] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/aad5c67d9809019b8486943c7d2ff968/external/+example+rule/file: Checksum was 86d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6 but wanted 96d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6
ERROR: java.io.IOException: Error downloading [https://example.com/file] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/aad5c67d9809019b8486943c7d2ff968/external/+example+rule/file: Checksum was 86d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6 but wanted 96d3dc8f59d253524f933aaf2f3c05896cb0b605fc35b460c0b4b039996124c6
INFO: Elapsed time: 0.729s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

### Starlark reproduction

```python
def verify_integrity(ctx, file, integrity):
    actual_integrity_hash = ctx.integrity_hash("sha256", file)
    if integrity != actual_integrity_hash:
        fail(
            "Error verifying integrity of {}. Checksum was {} but wanted {}".format(
                file, actual_integrity_hash, integrity
            )
        )
```

### Example output

```
ERROR: /home/ubuntu/project/example.bzl:21:9: An error occurred during the fetch of repository '+example+rule':
   Traceback (most recent call last):
	File "/home/ubuntu/project/example.bzl", line 16, column 19, in _impl
		verify_integrity(ctx, file=ctx.attr.file, integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=")
	File "/home/ubuntu/project/example.bzl", line 21, column 9, in verify_integrity
		fail("Error verifying integrity of {}. Checksum was {} but wanted {}".format(file, actual_integrity_hash, integrity))
Error in fail: Error verifying integrity of @@//:file. Checksum was sha256-OaVG6prZf4v69dPg6PhVattBXkcOWQB62pdZ3ORyrao= but wanted sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
ERROR: Error verifying integrity of @@//:file. Checksum was sha256-OaVG6prZf4v69dPg6PhVattBXkcOWQB62pdZ3ORyrao= but wanted sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
INFO: Elapsed time: 7.213s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

**Comment by jmillikin** [comment]
You may be interested in the `repository_ctx.execute_wasm()` feature -- I've been using it for computing `go.mod` checksums, and it should be pretty straightforward to write a module that implements `sha{256,384,512}-{hex,sri}`.

It's not as fast a pure Java implementation, but should be much faster than Starlark. See also <https://github.com/bazelbuild/bazel/pull/29320> which should provide a decent performance improvement if you're going to be checksumming large files.
