### ISSUE TITLE
java.lang.IllegalStateException on missing "inputs" from "ctx.resolve_tools" with remote cache

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#15755]
### Description of the bug:

Bazel crashes with the following error message:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//:crash, config=BuildConfigurationKey[cf45c98382a5425c9423e9818198d63bfc53a7210804a6e52827c219c726f757]}, actionIndex=0}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, actionLookupKey=ConfiguredTargetKey{label=//:crash, config=BuildConfigurationKey[cf45c98382a5425c9423e9818198d63bfc53a7210804a6e52827c219c726f757]}, willTest=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:665)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: File:[/home/aj/.cache/bazel/_bazel_aj/8758014692deaa5c41d233f7a8ed2db2/external/bazel_tools[source]]tools/bash/runfiles/runfiles.bash is not present in declared outputs: [File:[[<execution_root>]bazel-out/k8-fastbuild/bin]crash]
        at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
        at com.google.devtools.build.lib.skyframe.ActionMetadataHandler.getMetadata(ActionMetadataHandler.java:249)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1766)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.lambda$buildFromActionInputs$1(DirectoryTreeBuilder.java:141)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.build(DirectoryTreeBuilder.java:221)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.buildFromActionInputs(DirectoryTreeBuilder.java:125)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.fromActionInputs(DirectoryTreeBuilder.java:63)
        at com.google.devtools.build.lib.remote.merkletree.MerkleTree.build(MerkleTree.java:219)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.buildInputMerkleTree(RemoteExecutionService.java:358)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.buildRemoteAction(RemoteExecutionService.java:406)
        at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:93)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:144)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:111)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:64)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:351)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:924)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1091)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1049)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:497)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:819)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:318)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:163)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:591)
        ... 4 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Check out [this repository](https://github.com/aherrmann/bazel-repro-resolve-ctx-inputs-crash)
* Run `bazel build //:crash`
* Observe the crash

The crash can be avoided by uncommenting the `#inputs = ...` line in `defs.bzl` or by disabling the remote cache in `.bazelrc`.

### Which operating system are you running Bazel on?

Ubuntu 21.10

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

I have also tested and reproduced this issue on the Bazel versions 4.2.1 and "last_green" at commit de491da931cef4b063f93d20747256ae38518160.
This issue was discovered in the context of https://github.com/tweag/rules_sh/pull/23#issuecomment-1165408559.

**Comment by fmeum** [comment]
Curious because I also encountered this while working on https://github.com/bazelbuild/bazel/issues/16573#issuecomment-1292864530: Do you think that the repro you linked should fail with a more descriptive error instead of crashing Bazel or would you actually expect it to build without errors?

**Comment by aherrmann** [comment]
@fmeum Right, should have clarified that. I'd expect a proper error instead of a crash. And I'd expect it to consistently fail with that error also if the remote cache is disabled.

**Comment by meisterT** [comment]
This is obsolete
