### ISSUE TITLE
python error local_java_repository failure message when java_home path does not exist 

### ISSUE THREAD

**Issue by nickbreen** [bazelbuild/bazel#15761]
### Description of the bug:

When defining a local_java_repository and the java_home path does not exist, the construction of the error message results in a python error.

The bug is in `tools/jdk/local_java_repository.bzl` lines 125:126

Notice that the `%` operator is operating on the wrong string (and has precedence over the string concatenation `+` operator).

The following patch corrects the syntax.

```
Index: tools/jdk/local_java_repository.bzl
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tools/jdk/local_java_repository.bzl b/tools/jdk/local_java_repository.bzl
--- a/tools/jdk/local_java_repository.bzl	(revision 94cc0985ea07a2d69ef07ac9d3a9943e094794f2)
+++ b/tools/jdk/local_java_repository.bzl	(date 1656463750536)
@@ -123,8 +123,7 @@
     java_home = repository_ctx.attr.java_home
     java_home_path = repository_ctx.path(java_home)
     if not java_home_path.exists:
-        fail('The path indicated by the "java_home" attribute "%s" (absolute: "%s") ' +
-             "does not exist." % (java_home, str(java_home_path)))
+        fail('The path indicated by the "java_home" attribute "%s" (absolute: "%s") does not exist.' % (java_home, str(java_home_path)))
 
     repository_ctx.file(
         "WORKSPACE",

```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
#WORKSPACE
load("@bazel_tools//tools/jdk:local_java_repository.bzl", "local_java_repository")

local_java_repository(
    name = "jdk",
    version = "11",
    java_home = "a/path/that/does/not/exist",
)
```

### Which operating system are you running Bazel on?

Fedora 36

### What is the output of `bazel info release`?

release 5.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

No, seems like a trivial bug that generally not exercised except with a configuration that can't possibly work anyway.

### Any other information, logs, or outputs that you want to share?

Example failure output (personalized paths: [elided]):

```
Repository rule _local_java_repository_rule defined at:
  [elided]/external/bazel_tools/tools/jdk/local_java_repository.bzl:202:46: in <toplevel>
ERROR: An error occurred during the fetch of repository 'jdk':
   Traceback (most recent call last):
        File "[elided]/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 127, column 32, in _local_java_repository_impl
                "does not exist." % (java_home, str(java_home_path)))
Error: not all arguments converted during string formatting
ERROR: WORKSPACE:102:22: fetching _local_java_repository_rule rule //external:jdk: Traceback (most recent call last):
        File "[elided]/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 127, column 32, in _local_java_repository_impl
                "does not exist." % (java_home, str(java_home_path)))
Error: not all arguments converted during string formatting

```

**Comment by nickbreen** [comment]
This is indeed a duplicate of that PR. Apologies for the noise.

I can see that the change is present on [master](https://github.com/bazelbuild/bazel/tree/master), but it is not present on the [release-5.1.1](https://github.com/bazelbuild/bazel/tree/release-5.1.1), [release-5.2.0](https://github.com/bazelbuild/bazel/tree/release-5.2.0), [release-5.3.0](https://github.com/bazelbuild/bazel/tree/release-5.3.0) branches.

I assume 5.3.0 is not quite released yet as it's not listed as such on [releases](https://github.com/bazelbuild/bazel/releases).

Given this is already fixed on master, I'm happy for this issue to be closed.
