### ISSUE TITLE
Failed to build Bazel 5.2.0 on MIPS64el

### ISSUE THREAD

**Issue by imhjh** [bazelbuild/bazel#15775]
### Description of the bug:

The build failed on MIPS64el, base on Debian 10. Java.lang.OutOfMemoryError.

I tried to build bazel from scratch (bootstrapping) and run the compilation script:
env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" BAZEL_JAVAC_OPTS="-J-Xmx1024m -J-Xms200m" bash ./compile.sh

It's succeed in Building Bazel from scratch but failed in the next step.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

loongson@ls2k:~$ screen -r bz
external/local_jdk/bin/javac  -classpath '\''third_party/auto/auto-value-1.8.2.jar:third_party/auto/auto-value-annotations-1.8.2.jar:derived/jars/com_google_protobuf/java/core/libcore.jar:derived/jars/com_google_protobuf/java/core/liblite.jar:derived/jars/com_google_protobuf/java/util/libutil.jar:derived/jars/zstd-jni/libzstd-jni.jar:third_party/error_prone/error_prone_annotations-2.9.0.jar:third_party/error_prone/threeten-extra-1.5.0.jar:third_party/guava/guava-30.1.1-jre.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/java/jacoco/org.jacoco.core-0.8.7.jar:third_party/grpc/grpc-api-1.41.0.jar:third_party/grpc/grpc-auth-1.41.0.jar:third_party/grpc/grpc-context-1.41.0.jar:third_party/grpc/grpc-core-1.41.0.jar:third_party/grpc/grpc-netty-1.41.0.jar:third_party/grpc/grpc-protobuf-1.41.0.jar:third_party/grpc/grpc-protobuf-lite-1.41.0.jar:third_party/grpc/grpc-stub-1.41.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar'\'' -d bazel-out/mips64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output @bazel-out/mips64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar-2.params
external/local_jdk/bin/jar cf bazel-out/mips64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar -C bazel-out/mips64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output .
touch bazel-out/mips64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output
')
.# Configuration: 3f9b9e88d842312a3ac6849b41728cecdac70ee94836f166375d3953a65b6ae6
.# Execution platform: //:default_host_platform
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.HashMap.resize(HashMap.java:699)
        at java.base/java.util.HashMap.putVal(HashMap.java:624)
        at java.base/java.util.HashMap.put(HashMap.java:607)
        at java.base/java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:204)
        at java.base/java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:555)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:220)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:166)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Log.localize(Log.java:810)
        at jdk.compiler/com.sun.tools.javac.util.Log.printLines(Log.java:608)
        at jdk.compiler/com.sun.tools.javac.main.Main.resourceMessage(Main.java:414)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:326)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 26857.650s, Critical Path: 3815.16s
INFO: 1368 processes: 66 internal, 1302 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
loongson@ls2k:~/yali/bazel$

### Which operating system are you running Bazel on?

Loongbian(Base on Debian 10)

### What is the output of `bazel info release`?

FAILED: Build did NOT complete successfully  ERROR: Could not build Bazel

**Comment by imhjh** [comment]
Thank you！
