### ISSUE TITLE
bazel 0.3.0: Unhandled exception thrown during build of Tensorflow 0.9

### ISSUE THREAD

**Issue by rupflz** [bazelbuild/bazel#1581]
Ubuntu 14.04, bazel 0.3.0, tensorflow 0.9
Proxy is required in this setup but is known to work. In fact, bazel 0.2.2b successfully builds TF 0.8 on this same system. Recently, both bazel 0.3.0 and TF 0.9 were installed, which is where the issue is seen.

Attempt to build TF: bazel.0.3.0 build -c opt //tensorflow/tools/pip_package:build_pip_package
Result:
INFO: Elapsed time: 1.926s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@eigen_archive' (requested by nodes 'REPOSITORY:@eigen_archive')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1089)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at com.google.devtools.build.lib.bazel.repository.downloader.ProxyHelper.createProxy(ProxyHelper.java:88)
	at com.google.devtools.build.lib.bazel.repository.downloader.ProxyHelper.createProxyIfNeeded(ProxyHelper.java:59)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnection.createAndConnect(HttpConnection.java:78)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:139)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:82)
	at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:59)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1031)
	... 4 more

**Comment by rupflz** [comment]
Nevermind. Issue traced back to environment after bazel install. Closing.

**Comment by kchodorow** [comment]
Bazel's downloading logic uses [this regex](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/ProxyHelper.java#L78) to decide if a proxy is a valid URL.  It obviously should be handling exceptional cases better, but can you try setting HTTP_PROXY (and/or HTTPS_PROXY) environment variable to something of the form http://host:port?

And, if you don't mind sharing, what is the proxy URL it's choking on?
