### ISSUE TITLE
Outdated JDK version (< 1.0.4): NullPointerException in FlowAnalyzer.visitApply

### ISSUE THREAD

**Issue by ysfaran** [bazelbuild/bazel#15851]
### Description of the bug:

There is a [known issue using OpenJDK with version `11.0.2`](https://stackoverflow.com/a/54776592/6489012) that should've been fixed in version `11.0.4` when using `ParameterizedTypeReference<>`. Although this issue is long fixed and running `bazel info` on `5.2.0` displays following lines (JDK version > 1.0.4):

```sh
java-runtime: OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode) by Azul Systems, Inc.
```

`bazel build` returns the same error as in the StackOverflow question when compiling this code:

```java
package ysfaran.npebug;

import org.springframework.core.ParameterizedTypeReference;

public class NpeBugMain {
  public static void main(String[] args) {
    new Bug<>() {
    };
  }

  static class Bug<T> {

    Bug() {
      test(new ParameterizedTypeReference<>() {
      });
    }

    void test(ParameterizedTypeReference<T> typeReference) {
    }
  }
}
```

<details>
<summary>Error Log</summary>

```sh
INFO: Analyzed target //java/src/ysfaran/npebug:npe-bug (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/yusufaran/Projects/tmp/bazel-npe-bug/java/src/ysfaran/npebug/BUILD:5:12: Building java/src/ysfaran/npebug/npe-bug.jar (1 source file) failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.12, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.NullPointerException
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1235)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:213)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1452)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:997)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:964)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:927)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:872)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1327)
        at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1317)
        at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:218)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1401)
        at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:102)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:137)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:105)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:67)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:105)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:85)
        at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestHandlerBuilder.lambda$new$0(WorkRequestHandler.java:264)
        at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestCallback.apply(WorkRequestHandler.java:230)
        at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:424)
        at com.google.devtools.build.lib.worker.WorkRequestHandler.lambda$startResponseThread$1(WorkRequestHandler.java:381)
        at java.base/java.lang.Thread.run(Thread.java:829)
Target //java/src/ysfaran/npebug:npe-bug failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.242s, Critical Path: 0.08s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```
</details>

To get around this issue I tried to **only** use `amazon-corretto-11.jdk` for building and running, since my team uses it anyway as of now (FYI: I'm currently trying to migrate from a maven based build system to bazel). So I added a `remote_java_repository`: 

```bzl
remote_java_repository(
    name = "amazon_corretto_macos",
    exec_compatible_with = [
        "@platforms//os:macos",
    ],
    prefix = "amazon_corretto",
    sha256 = "36afb7f091cd9b986a50c3f878f167c59eae615f004b2cb1c5c394f9f2fc215a",
    strip_prefix = "amazon-corretto-11.jdk/Contents/Home",
    urls = [
        "https://corretto.aws/downloads/latest/amazon-corretto-11-x64-macos-jdk.tar.gz",
    ],
    version = "11",
)
```

And updated `.bazelrc` accordingly:

```bzl 
build --java_language_version=11
build --tool_java_language_version=11
build --tool_java_runtime_version=amazon_corretto_11
build --java_runtime_version=amazon_corretto_11
build --extra_toolchains=@amazon_corretto_macos//:all
build --repo_env=JAVA_HOME=../amazon_corretto_macos/
```

(I got the idea to set `JAVA_HOME` like that from [here](https://github.com/bazelbuild/rules_jvm_external/issues/445))

Surprisingly it still uses `external/remotejdk11_macos/bin/java` for compilation instead of `amazon-corretto-11.jdk`. As far as I understood the [docs](https://bazel.build/docs/bazel-and-java#compile-using-jdk) this can be configured with `--extra-toolschains` option (as I already did):

>Bazel by default compiles using remote JDK, because it is overriding JDK's internals. The compilation toolchains using locally installed JDK are configured, however not used.
>
>To compile using locally installed JDK, that is use the compilation toolchains for local JDK, use additional flag --extra_toolchains=@local_jdk//:all, however, mind that this may not work on JDK of arbitrary vendors.

I also ran `bazel build` with `--verbose_failures` and `--toolchain_resolution_debug=.*` where `amazon-corretto` was not chosen or even an option of the below `Type`/`Target platform`:

```sh
Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform @local_config_platform//:host: execution @local_config_platform//:host: Selected toolchain @remotejdk11_macos//:jdk
```

```sh
Target platform @local_config_platform//:host: Selected execution platform @local_config_platform//:host, type @bazel_tools//tools/jdk:runtime_toolchain_type -> toolchain @remotejdk11_macos//:jdk
```

Pinning the version to a pre release number (`6.0.0-pre.20220608.2`) is the only way I could make this code compile.
This not ideal since I really don't want to run a production pipeline with a prelease version. Also it seems to be a bug anyway, because `--extra_toolchains` is not working as expected. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created a repo with 3 branches including a README.md with instructions: https://github.com/ysfaran/bazel-npe-bug.
`bazelisk` is required to reproduce the example.

Branches:

* `master`
  * state: not working
  * bazel version: `5.2.0`
* `corretto`
  * state: not working
  * bazel version: `5.2.0`
  * updated `.bazelrc` to only use `amazon-corretto-11.jdk`
* `prerelease`
  * state: working
  * bazel version: `6.0.0-pre.20220608.2`

### Which operating system are you running Bazel on?

macOS Monterey Version 12.4

### What is the output of `bazel info release`?

release 5.2.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:ysfaran/bazel-npe-bug.git
333650afbcf23687c7e7880f2670848a8eeee5f5
333650afbcf23687c7e7880f2670848a8eeee5f5
```

### Have you found anything relevant by searching the web?

* [StackOverflow question regarding OpenJDK bug](https://stackoverflow.com/questions/54775253/jdk-11-0-2-compilation-fails-with-javac-npe-on-anonymous-parameterized-class-typ)
* [Discussions prior to ths GitHub issue on bazel's Slack channel](https://bazelbuild.slack.com/archives/CD42R4HJL/p1657008566846249)

**Comment by ysfaran** [comment]
I also tried to setup my own toolchain (see branch `toolchain`), by adding following to the root `BUILD`:

```bzl
load(
    "@bazel_tools//tools/jdk:default_java_toolchain.bzl",
    "BASE_JDK9_JVM_OPTS",
    "DEFAULT_JAVACOPTS",
    "DEFAULT_TOOLCHAIN_CONFIGURATION",
    "default_java_toolchain",
)

default_java_toolchain(
    name = "repository_default_toolchain",
    configuration = DEFAULT_TOOLCHAIN_CONFIGURATION,
    java_runtime = "//:amazon_corretto_macos",
    javacopts = DEFAULT_JAVACOPTS,
    jvm_opts = BASE_JDK9_JVM_OPTS,
    source_version = "11",
)
```
and this to `WORKSPACE`:

```bzl
register_toolchains(
    "//:repository_default_toolchain",
)
```

Still ending up in this error: 

```sh
$ bazelisk build //java/src/ysfaran/npebug:npe-bug
ERROR: Misconfigured toolchains: //:repository_default_toolchain is declared as a toolchain but has inappropriate dependencies. Declared toolchains should be created with the 'toolchain' rule and should not have dependencies that themselves require toolchains.
.-> @bazel_tools//tools/jdk:current_java_runtime
|   toolchain types @bazel_tools//tools/jdk:runtime_toolchain_type
|   toolchain type @bazel_tools//tools/jdk:runtime_toolchain_type
|   RegisteredToolchains
|   //:repository_default_toolchain
|   @bazel_tools//tools/jdk:platformclasspath
`-- @bazel_tools//tools/jdk:current_java_runtime
ERROR: Analysis of target '//java/src/ysfaran/npebug:npe-bug' failed; build aborted
INFO: Elapsed time: 0.199s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Not sure what I can do else anymore.

**Comment by comius** [comment]
You are on the right path.

**With custom toolchain:**
To get rid of the cycle, you need to append `_definition` when registering: 
```
register_toolchains(
    "//:repository_default_toolchain_definition",
)
```

**With default toolchain:**
You should omit `prefix` argument in your `remote_java_repository`. (or set it to `remotejdk`). Default toolchain uses any `remotejdk` version `11`, corresponding to you platform (OS+CPU). The ones listed in WORKSPACE take precedence.

**Comment by ysfaran** [comment]
@comius thanks for the hints.

Unfortunately it's  still not working.

> **With custom toolchain:**
>  To get rid of the cycle, you need to append `_definition` when registering:
> 
> ```
> register_toolchains(
>     "//:repository_default_toolchain_definition",
> )
> ```

On `toolchain` branch I did this change:

```diff
 register_toolchains(
-    "//:repository_default_toolchain",
+    "//:repository_default_toolchain_definition",
 )
```

Build results in:

```sh
$ bazelisk build //java/src/ysfaran/npebug:npe-bug
ERROR: /Users/yusufaran/Projects/tmp/bazel-npe-bug/BUILD:9:23: in java_runtime attribute of java_toolchain rule //:repository_default_toolchain: rule '//:amazon_corretto_macos' does not exist. Since this rule was created by the macro 'default_java_toolchain', the error might have been caused by the macro implementation
ERROR: /Users/yusufaran/Projects/tmp/bazel-npe-bug/BUILD:9:23: Analysis of target '//:repository_default_toolchain' failed
ERROR: /private/var/tmp/_bazel_yusufaran/6cb4a6b95e5e1b85b19a519aeefb8e4d/external/bazel_tools/tools/jdk/BUILD:35:21: errors encountered resolving toolchains for @bazel_tools//tools/jdk:current_java_toolchain
ERROR: Analysis of target '//java/src/ysfaran/npebug:npe-bug' failed; build aborted: 
INFO: Elapsed time: 0.645s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (45 packages loaded, 671 targets configured)
```

> **With default toolchain:**
> You should omit `prefix` argument in your `remote_java_repository`. (or set it to `remotejdk`). Default toolchain uses any `remotejdk` version `11`, corresponding to you platform (OS+CPU). The ones listed in WORKSPACE take precedence.

On `corretto` branch I did this change:

```diff
remote_java_repository(
     exec_compatible_with = [
         "@platforms//os:macos",
     ],
-    prefix = "amazon_corretto",
     sha256 = "36afb7f091cd9b986a50c3f878f167c59eae615f004b2cb1c5c394f9f2fc215a",
     strip_prefix = "amazon-corretto-11.jdk/Contents/Home",
     urls = [

```

Build results in:

```sh
 $ bazelisk build //java/src/ysfaran/npebug:npe-bug
ERROR: /private/var/tmp/_bazel_yusufaran/6cb4a6b95e5e1b85b19a519aeefb8e4d/external/bazel_tools/tools/jdk/BUILD:29:19: While resolving toolchains for target @bazel_tools//tools/jdk:current_java_runtime: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//java/src/ysfaran/npebug:npe-bug' failed; build aborted: 
INFO: Elapsed time: 0.613s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 8 targets configured)
```

I tried different combinations and changes still can't figure out to get this running with bazel v5.. What am I missing?
