### ISSUE TITLE
Malformed `bazel query` command crashes with "Illegal char <*> at index" on Windows

### ISSUE THREAD

**Issue by Marcono1234** [bazelbuild/bazel#15962]
### Description of the bug:

It looks like using a malformed (?) `bazel query` command can crash Bazel on Windows:
```
Loading: 0 packages loaded
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE_STATE:[#redacted#/gson]/[*]' (requested by nodes 'FILE:[#redacted#/gson]/[*]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 42: #redacted#\gson\*
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.io.File.toPath(Unknown Source)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:251)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:153)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:493)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:339)
        at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.statImpl(PerBuildSyscallCache.java:235)
        at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.access$400(PerBuildSyscallCache.java:34)
        at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache$Builder.lambda$build$0(PerBuildSyscallCache.java:95)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:239)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:235)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.statIfFound(PerBuildSyscallCache.java:114)
        at com.google.devtools.build.lib.skyframe.PerBuildSyscallCache.getType(PerBuildSyscallCache.java:181)
        at com.google.devtools.build.lib.actions.FileStateValue.create(FileStateValue.java:83)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:63)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:33)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 7 more
```

Even if the command is invalid, it should probably not crash Bazel.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download Bazel; I used https://github.com/bazelbuild/bazel/releases/download/5.2.0/bazel-5.2.0-windows-x86_64.exe
2. Clone https://github.com/bazelbuild/examples at commit https://github.com/bazelbuild/examples/commit/12e1ab69e6b239f63908113cd6936a6de77f4477
3. Run:
    ```
    cd examples/java-tutorial
    ```
    ```
    bazel-5.2.0-windows-x86_64.exe query "//*"
    ```
    :x: It crashes

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

There are mutliple other "Illegal char <...> at index" issues at this GitHub repository here, though all are closed (not sure if all are really fixed however).

**Comment by Marcono1234** [comment]
I have updated the reproduction steps now to use the example project from https://github.com/bazelbuild/examples and included how I obtained the Bazel binary. Do you need any additional information?
