### ISSUE TITLE
Allow directories as "resources" in an objc_binary

### ISSUE THREAD

**Issue by jbeder** [bazelbuild/bazel#160]
I have an entire directory that I'd like to copy directly to my app. I tried

```
objc_binary(
  ...
  resources = glob(["data/**"]),
)
```

but this effectively flattens my files (I want to request, e.g., `"data/foo/bar.txt"` in my app). And specifying

```
resources = ["data"],
```

leads to an exception:

```
Exception in thread "main" java.io.IOException: Is a directory
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:158)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at java.io.InputStream.read(InputStream.java:101)
    at com.google.devtools.build.singlejar.ZipCombiner.copyStreamToEntry(ZipCombiner.java:1344)
    at com.google.devtools.build.singlejar.ZipCombiner.addFile(ZipCombiner.java:1397)
    at com.google.devtools.build.xcode.zip.ZipInputEntry.add(ZipInputEntry.java:101)
    at com.google.devtools.build.xcode.zip.ZipInputEntry.addAll(ZipInputEntry.java:109)
    at com.google.devtools.build.xcode.bundlemerge.BundleMerging.execute(BundleMerging.java:210)
    at com.google.devtools.build.xcode.bundlemerge.BundleMerging.merge(BundleMerging.java:225)
    at com.google.devtools.build.xcode.bundlemerge.BundleMerge.main(BundleMerge.java:47)
```

**Comment by damienmg** [comment]
I think this is incorrect to have a directory as a ressources but having them flatten when globbing is probably incorrect too. The IOException is incorrect too.

**Comment by damienmg** [comment]
Assigning to Daniel because I cannot assign it to peter apparently. Can you do the follow-up?

**Comment by jbeder** [comment]
Damien, what is the reason that it's incorrect to have a directory in "resources"?

I'd like to be able to refer to files by `data/foo/bar.txt` - is there another way to do that?

**Comment by damienmg** [comment]
jbeder: I meant it is not the good syntax. it should be the first one you tried (with the glob). And the glob should not flatten the directory structures (so your first solution should be the one working).

**Comment by jbeder** [comment]
I didn't notice this field before, but it appears that `structured_resources` is what I'm looking for. `resources` explicitly flattens the directories. This was explicitly added in revision 56dd176d, which was before my original issue report - I just missed it :/

So I think this issue should really be:

1. Better documentation - at a minimum, use the word "flatten" in the documentation for `resources`, and reference `structured_resources from it (and vice-versa).

2. Don't throw an exception when specifying a directory from `resources` - and possibly even give an error message that mentions `structured_resources`.

3. Possibly - and I'm really not sure about this - rename `structured_resources` to `resources` and `resources` to `flattened_resources`. For my own projects, at least, I *never* want to flatten. I can see its utility, but it strikes me as an option that you'd want to invoke explicitly.

What do you think?

**Comment by damienmg** [comment]
I think 1 and 2 makes sense. 3 is probably impossible (especially the part about renaming structured_resources to resources) because of use of that feature inside Google.

**Comment by meisterT** [comment]
@c-parsons what's the status of this work?

**Comment by c-parsons** [comment]
This issue is very stale and obsolete -- closing.

For one, `objc_binary` no longer exists :) Apple-related rules are now defined in Starlark under rules_apple: https://github.com/bazelbuild/rules_apple

Please file feature requests against that repository.
