### ISSUE TITLE
An empty external/ directory causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1606]
Creating an external/ directory under the workspace is a stupid thing. However, due to the lack of useful debug information, I spent like 10 minutes before discovered it was caused by my stupidness. Maybe we could use some better diagnostics.

**Comment by kchodorow** [comment]
Can you provide steps to reproduce? Just doing a `mkdir external` and building various targets isn't causing an NPE for me.

**Comment by ahyangyi** [comment]
I can reproduce it with the following steps:
`
$ mkdir empty_project
$ cd empty_project
$ touch WORKSPACE
$ bazel build //...:all
ERROR: no targets found beneath ''.  // This is a reasonable error message
$ mkdir external
$ bazel build //...:all
*Bazel now throws NPE*
`

Possibly related: `bazel build //external:all` always throws NPE

**Comment by ahyangyi** [comment]
(FYI, the above steps triggers the bug for both Bazel 0.3.0 and Bazel 0.3.1)

**Comment by ulfjack** [comment]
I can confirm the reproduction:

Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:148)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:76)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:74)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:106)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:278)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:263)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryParImpl(RecursivePackageProviderBackedTargetPatternResolver.java:263)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:197)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:483)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:71)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	... 4 more

**Comment by dslomov** [comment]
Fixed
