### ISSUE TITLE
How to: declare that a custom rule depends on the current C++ toolchain?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1624]
What I was trying to do is exactly what the title says.

I'm creating a vendor-specific rule as a replacement for cc_binary.

With `fragments = ["cc"]` on, I could get enough information about the toolchain used; with the information from the (undocumented) `CcSkylarkApiProvider`, I could also get enough information about the dependent `cc_library`'s.

Now there seems to be only one problem: I cannot actually declare that my rule depends on **the current cc toolchain**! This might sound extremely silly, but I can't find a way to express that...

(I'm not using auto-detecting `cc_toolchain`'s. Instead I included them in my repo to ensure repeatability.)

**Comment by hermione521** [comment]
@lberki do you have any idea?

**Comment by ahyangyi** [comment]
I'd like to point out that I'm virtually unable to customize anything related to the C++ compilation process due to this.

In a distant future when you migrate the `src/main/java/com/google/devtools/build/lib/rules/cpp/` code into skylark maybe things will be more hackable for me, but that's not happening very soon I'm afraid.

**Comment by lberki** [comment]
I don't think that is doable right know :( Our C++ rules don't integrate with Skylark very well (which is a worse state to be in if they didn't integrate with Skylark at all). It's on our agenda to improve them, but they are quite complicated, so I can't give you a deadline.

**Comment by bsilver8192** [comment]
I've just been including an attribute like this as an input to all my actions (the label needs to be changed to match the value of `--crosstool_top` you're using):
```python
    '_cc_toolchain': attr.label(
      default = Label('@bazel_tools//tools/cpp:toolchain'),
    ),
```

It definitely includes more files than necessary (all linker, compiler etc files for all toolchains), and is definitely brittle wrt specifying other `--crosstool_top`s, but it works OK for me. Could you live with those limitations too until there's something better?

**Comment by ahyangyi** [comment]
Yeah, that's what I plan to do. It would make regular development easy, but the testing of new toolchains hard. Since the latter involves only one person (that is, me), it won't be a huge problem hopefully.

Thanks a lot!

**Comment by ahyangyi** [comment]
Not sure if you want to close this issue or keep it as a remainder/tracking issue that we are still waiting for something better. I'll keep it open for now.

**Comment by ahyangyi** [comment]
It seems @bsilver8192's solution does not work for me.

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportL
ookupKey@c0007ed6' (requested by nodes 'PACKAGE:redacted/redacted')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.packages.BuildType$LabelType.convert(BuildType.java:227)
        at com.google.devtools.build.lib.packages.BuildType$LabelType.convert(BuildType.java:199)
        at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:550)
        at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:496)
        at com.google.devtools.build.lib.syntax.Type.convert(Type.java:85)
        at com.google.devtools.build.lib.packages.Attribute$Builder.defaultValue(Attribute.java:623)
        at com.google.devtools.build.lib.rules.SkylarkAttr.createAttribute(SkylarkAttr.java:171)
        at com.google.devtools.build.lib.rules.SkylarkAttr.access$100(SkylarkAttr.java:72)
        at com.google.devtools.build.lib.rules.SkylarkAttr$6.invoke(SkylarkAttr.java:856)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

Maybe related: the toolchain I am using is a `cc_toolchain_suite`, as opposed to a `filegroup`.

**Comment by ahyangyi** [comment]
Um... changing it to a filegroup does _not_ help.  :(

**Comment by ahyangyi** [comment]
FYI:

Creating a separate filegroup would fix the first problem @bsilver8192 mentioned, since you can use `select` on it. Basically:
```
filegroup(
    name="toolchain_files",
    srcs=select({
        ":foo_toolchain": [":foo_toolchain_files"],
        ":bar_toolchain": [":bar_toolchain_files"],
        ":baz_toolchain": [":baz_toolchain_files"],
        }),
    )
```

where `:foo_toolchain` is a `config_setting` and `foo_toolchain_files` is the filegroup you provide to your `cc_toolchain` rule as `all_files`.

That's quite some boilerplate code, but adding a new toolchain already involves lots of boilerplate code here and there, and this is definitely not the worst thing we have.

This, however, does not directly solve the second problem. If the maintainer know about all possible `crosstool_top` however, they can use a similar `select`-based trick to make sure the correct toolchain is pulled.

**Comment by hlopko** [comment]
The principled way to depend on C++ toolchain is to have an attribute `_cc_toolchain` and use `find_cpp_toolchain`, see e.g. `compiler_flag` rule: https://source.bazel.build/bazel/+/6ff84bb27d1e487651f4baea3a68a61e835a89b4:tools/cpp/compiler_flag.bzl.

We're working on end-to-end docs for bazel.build on how to integrate with C++ rules.
