### ISSUE TITLE
Enabling stripping via --experimental_output_paths = strip causes failure on simple java project using rules_jvm_external

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/bazel#16242]
### Description of the bug:

Enabling experimental_output_paths=strip will causes stripped location to be used by java compilation workers, however it seems the non-stripped location is used somewhere else : 

```
bazel build //experimental/sample/simple/lib1:src_main --experimental_output_paths=strip

ERROR: /Users/oliviern/Uber/android/build/.bazelw_cache/91a99194e71852b0e089ca5cc1c48073/external/rules_jvm_external/private/tools/java/rules/jvm/external/BUILD:1:13: Building external/rules_jvm_external/private/tools/java/rules/jvm/external/libbyte-streams.jar (1 source file) [for tool] failed: IOException while borrowing a worker from the pool:

---8<---8<--- Exception details ---8<---8<---
java.nio.file.NoSuchFileException: /Users/oliviern/Uber/android/build/.bazelw_cache/91a99194e71852b0e089ca5cc1c48073/execroot/__main__/bazel-out/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/libbyte-streams.jar-0.params
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
	at java.base/java.nio.file.Files.newInputStream(Unknown Source)
	at java.base/java.nio.file.Files.newBufferedReader(Unknown Source)
	at java.base/java.nio.file.Files.readAllLines(Unknown Source)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.expandArgument(WorkerSpawnRunner.java:296)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.createWorkRequest(WorkerSpawnRunner.java:241)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:441)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:201)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:289)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:151)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:111)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:64)
	at com.google.devtools.build.lib.rules.java.JavaCompileAction.beginExecution(JavaCompileAction.java:433)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:924)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1091)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1049)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:497)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:823)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:318)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:163)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:592)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---
Aspect @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect of //experimental/sample/simple/lib1:src_main up-to-date (nothing to build)
```

```
oliviern@oliviern-KFFWL6T16N android % ls /Users/oliviern/Uber/android/build/.bazelw_cache/91a99194e71852b0e089ca5cc1c48073/execroot/__main__/bazel-out/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/
_javac					libbyte-streams.jar_manifest_proto	libbyte-streams.jdeps
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Any project using rules_jvm_external should exhibit the issue.

Using bazel version : 6.0.0-pre.20220630.1

**Comment by oliviernotteghem** [comment]
@gregestren : any idea what's going on?

**Comment by gregestren** [comment]
I don't yet expect `--experimental_output_paths=strip` to be functional. We need to write some more code for it to even integrate with executors, and then it has to be vetted against different targets. Trying to follow up on that work but I'm not surprised at all at arbitrary crashes with this flag.

**Comment by gregestren** [comment]
Since `--experimental_output_paths=strip`is still in development, closing this for now to declutter the bug queue.

Let's revisit when the feature is generally more usable. Note https://github.com/bazelbuild/bazel/pull/15542 is also under development. So the ultimate user API is still in flux.

Also see https://github.com/bazelbuild/bazel/issues/6526.
