### ISSUE TITLE
incompatible_enable_android_toolchain_resolution

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#16285]
We are migrating Android builds to use platforms and toolchain resolution to find the SDK and NDK. The work is progressing well but we need to execute more testing before we provide migration directions and flip this flag.

**Comment by katre** [comment]
Ran a downstream test of #19726:
- Hard bazel crashes
  - Looks like an [NPE in `AndroidSdkProvider.getAndroidJar`](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3369#018b1b2e-f948-407c-8abc-ec1e6c40bc6c)
  - Fix ASAP
  - Bazel
  - rules_jvm_external - examples (Android Robolectric test example)
  - rules_kotlin (Example - Anvil)
  - rules_kotlin (Example - Jetpack Compose)
  - rules_kotlin (Example Bzlmod - Android)
- Project doesn't set `--android_platforms` but probably should
  - Bazel Examples (android (Android Firebase Cloud Messaging)
  - Bazel Examples (android (Android NDK)
  - Bazel Examples (tutorials (Bazel end-to-end example)
  - rules_android
  - rules_android_ndk
  - rules_foreign_cc (Examples (spawn_strategy=standalone))
  - rules_jvm_external - examples (Android instrumentation test example)
  - rules_jvm_external - examples (Simple example)
  - rules_kotlin (Example - Android)
  - rules_rust (Android Examples)

**Comment by katre** [comment]
To reproduce the crash (in a clean Bazel checkout with with Bazel built from HEAD):

```
$ bazel-dev build --nobuild --incompatible_enable_android_toolchain_resolution -- //src/test/java/com/google/devtools/build/android/r8:desugar_testdata_lambda
Building dev version of bazel...
WARNING: Download from https://mirror.bazel.build/github.com/madler/zlib/releases/download/v1.3/zlib-1.3.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //src:bazel-dev (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src:bazel-dev up-to-date:
  bazel-bin/src/bazel-dev
INFO: Elapsed time: 0.221s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Executing bazel-dev...
WARNING: Build option --incompatible_enable_android_toolchain_resolution has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
Analyzing: target //src/test/java/com/google/devtools/build/android/r8:desugar_testdata_lambda (0 pack\
ages loaded, 0 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@bazel_tools//tools/android:android_jar, config=BuildConfigurationKey[0bf75dd232dadeb1aae161cb11ea8439ac21f80b21714964ff16886adcd0633d]}' (requested by nodes 'ConfiguredTargetKey{label=//src/test/java/com/google/devtools/build/android/r8:desugar_testdata_lambda, config=BuildConfigurationKey[0bf75dd232dadeb1aae161cb11ea8439ac21f80b21714964ff16886adcd0633d]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.rules.android.AndroidSdkProvider.getAndroidJar()" because the return value of "com.google.devtools.build.lib.rules.android.AndroidSdkProvider.fromRuleContext(com.google.devtools.build.lib.analysis.RuleContext)" is null
	at com.google.devtools.build.lib.rules.android.AndroidToolsDefaultsJar.create(AndroidToolsDefaultsJar.java:48)
	at com.google.devtools.build.lib.bazel.rules.android.BazelAndroidToolsDefaultsJar.create(BazelAndroidToolsDefaultsJar.java:20)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:399)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1305)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:385)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:312)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	... 7 more
```

**Comment by katre** [comment]
I started the internal merge for #19726 and ran into test failures that I thought were already resolved. I'm moving this from the "branch cut" milestone to the "release blocker" milestone so that it can be cherry-picked when ready.

**Comment by katre** [comment]
(Copied from #19726)

Downstream projects are mostly clean at this point. A typical error looks like 
```
'android_library' rule '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_stub_application' requested an android sdk via toolchain resolution but hasn't set an appropriate --android_platforms value: Either set --noincompatible_enable_android_toolchain_resolution or --android_platforms.
```

If any more downstream projects fail, assign an issue to me to triage.

**Comment by iancha1992** [comment]
@bazel-io fork 7.0.0

**Comment by cpsauer** [comment]
Would it make sense to set a usable default value for --android_platforms to avoid having everyone configure manually?
(e.g. all 4 architectures Google would like people to build for)

I think we'll probably also need to update the [rules_android_ndk readme](https://github.com/bazelbuild/rules_android_ndk) (depending on the default)

**Comment by katre** [comment]
Unfortunately, there's no useful default to set it _to_: we very deliberately don't want to define any actual platforms in the `@bazel_tools` repo, and there's nowhere else to define them that's guaranteed to be present for all users.

**Comment by cpsauer** [comment]
What about in `@platforms`, parallel to your https://github.com/bazelbuild/platforms/issues/36?

**Comment by cpsauer** [comment]
(Just, ofc, seems like a bummer from a product standpoint to require users to discover boilerplate config on error rather than have a usable (but configurable) default.)

**Comment by cpsauer** [comment]
More importantly, thanks so much for all your work getting these flipped. It's *awesome* to have platform selection working smoothly without platform_mappings!
