### ISSUE TITLE
macOS Ventura: UnsatisfiedLinkError void com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.create

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#16328]
### Description of the bug:

The following exception is thrown trying to build on macOS Ventura:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.UnsatisfiedLinkError: 'void com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.create(java.lang.String[], double)'
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.create(Native Method)
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.init(MacOSXFsEventsDiffAwareness.java:79)
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.getCurrentView(MacOSXFsEventsDiffAwareness.java:140)
	at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:95)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:361)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:276)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:700)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:545)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install macOS Ventura Beta/Preview

### Which operating system are you running Bazel on?

macOS Ventura

### What is the output of `bazel info release`?

release 5.1.0

### Have you found anything relevant by searching the web?

no

**Comment by guw** [comment]
@sgowroji Same problem with 5.3.1 (ARM nojdk version, JDK is Azul _aarch64_ version _OpenJDK 64-Bit Server VM Zulu11.56+20-SA_)

```
Starting local Bazel server and connecting to it...
INFO: Invocation ID: ...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.UnsatisfiedLinkError: 'void com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.create(java.lang.String[], double)'
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.create(Native Method)
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.init(MacOSXFsEventsDiffAwareness.java:79)
	at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.getCurrentView(MacOSXFsEventsDiffAwareness.java:140)
	at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:95)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:361)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:276)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:704)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:545)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by guw** [comment]
This version seems to work: `bazel-5.3.1-darwin-x86_64` 
So Intel emulation is a good workaround for now.
