### ISSUE TITLE
bzlmod crashes when it can't resolve a module

### ISSUE THREAD

**Issue by vapier** [bazelbuild/bazel#16370]
### Description of the bug:

trying to use a local registry, but bzlmod crashes when it can't find the module

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cd ~/ && mkdir x && cd x
$ touch WORKSPACE
$ printf '%s\n' 'module(name = "example")' 'bazel_dep(name = "mydep", version = "1.0")' > MODULE.bazel

$ bazelisk build --experimental_enable_bzlmod --registry=$PWD/foo //:all
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'Key{moduleKey=mydep@1.0, override=null}' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelModuleResolutionValue$$Lambda$375/0x00000008004cd040@6704563f')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.bazel.bzlmod.RegistryFactoryImpl.getRegistryWithUrl(RegistryFactoryImpl.java:38)
        at com.google.devtools.build.lib.bazel.bzlmod.ModuleFileFunction.getModuleFile(ModuleFileFunction.java:254)
        at com.google.devtools.build.lib.bazel.bzlmod.ModuleFileFunction.compute(ModuleFileFunction.java:92)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 4 more
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.1

**Comment by meteorcloudy** [comment]
This is already fixed at https://github.com/bazelbuild/bazel/commit/00bd2910bf76df9a10d7fff466fab6485ad71cbe
