### ISSUE TITLE
Fail to build bazel from source

### ISSUE THREAD

**Issue by AlvinChen13** [bazelbuild/bazel#1638]
Hi all,

Since I got error while run bazel which is installed by binary, then I try to build it from source, but I get the following errors. It seem some issue for java? Anyone can help on it? Appreciated!

/share/bazel-master$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.java.lang.InternalError: internal error: SHA-1 not available.
	at sun.security.provider.SecureRandom.init(SecureRandom.java:108)
	at sun.security.provider.SecureRandom.<init>(SecureRandom.java:79)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:198)
	at java.security.SecureRandom.<init>(SecureRandom.java:162)
	at java.util.UUID$Holder.<clinit>(UUID.java:96)
	at java.util.UUID.randomUUID(UUID.java:142)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1030)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:931)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:689)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:510)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: java.security.NoSuchAlgorithmException: SHA MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at sun.security.provider.SecureRandom.init(SecureRandom.java:106)
	... 10 more
alvin@hal-dev:/share/bazel-master$

**Comment by ahyangyi** [comment]
Looks like you are using a very different JRE (that does not support SHA-1) from everyone else.  What's your JRE version?

**Comment by kchodorow** [comment]
Is it possible the export situation described [in this thread](https://bugs.eclipse.org/bugs/show_bug.cgi?id=23760) applies? Could you try adding the security.provider line?

**Comment by AlvinChen13** [comment]
@kchodorow My security.provider is as following:

hal-dev:~$ sudo vi /usr/java/jdk1.8.0_101/jre/lib/security/java.security

 66 # List of providers and their preference orders (see above):
 67 #
 68 security.provider.1=sun.security.provider.Sun
 69 security.provider.2=sun.security.rsa.SunRsaSign
 70 security.provider.3=sun.security.ec.SunEC
 71 security.provider.4=com.sun.net.ssl.internal.ssl.Provider
 72 security.provider.5=com.sun.crypto.provider.SunJCE
 73 security.provider.6=sun.security.jgss.SunProvider
 74 security.provider.7=com.sun.security.sasl.Provider
 75 security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
 76 security.provider.9=sun.security.smartcardio.SunPCSC
 77  
 78 #
 79 # Sun Provider SecureRandom seed source.

**Comment by AlvinChen13** [comment]
@ahyangyi @kchodorow Is that possible the issue of my java env? I just write a very simple java app, but it runs failed. It likes this:


  1 import java.security.MessageDigest;                                                 
  2  
  3 public class Sha {
  4             public static void main(String[] args) throws Exception {
  5                         MessageDigest md = MessageDigest.getInstance("SHA");
  6                             }
  7 }

it reports errors:
alvin@hal-dev:~/javaapp$ java Sha
Exception in thread "main" java.security.NoSuchAlgorithmException: SHA MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at Sha.main(Sha.java:5)
alvin@hal-dev:~/javaapp$

**Comment by AlvinChen13** [comment]
Solve the issue by re-install the JDK instead of deb
