### ISSUE TITLE
aquery: have a better error message in case of interruption from an IOException

### ISSUE THREAD

**Issue by stnma7e** [bazelbuild/bazel#16390]
### Description of the bug:

When trying to run `aquery` on a target, I get the following error:
```
$ tools/bazel aquery --config=bp2build --output=jsonproto --config=linux_x86_64 //packages/modules/adb:adb_test --verbose_failures
WARNING: Bazel support for the Android Platform is experimental and is undergoing development.
WARNING: Currently, build stability is not guaranteed. Thank you.

INFO: Analyzed target //packages/modules/adb:adb_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: build interrupted
INFO: Elapsed time: 0.459s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I had it print a stack trace using a local copy of Bazel@390d212d76e91f413f143b53a997b0bf846c453a:
```
java.lang.InterruptedException: Interrupting due to a IOException in the OutputFormatter
        at com.google.devtools.build.lib.query2.engine.OutputFormatterCallback.process(OutputFormatterCallback.java:57)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryProcessor.doPostAnalysisQuery(PostAnalysisQueryProcessor.java:198)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryProcessor.process(PostAnalysisQueryProcessor.java:83)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:212)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:492)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:460)
        at com.google.devtools.build.lib.runtime.commands.AqueryCommand.exec(AqueryCommand.java:138)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:607)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:232)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
ERROR: build interrupted
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure. None of my teammates can reproduce, and it just started happened (as far as I can tell) when I got into work this morning. However, I had been running this exact command (via a script) frequently during this past week.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

This error occurs on multiple versions:
- release 5.3.1
and two separate development versions 
  - one that is part of AOSP https://cs.android.com/android/platform/superproject/+/master:prebuilts/bazel/linux-x86_64/bazel;drc=8522739dea1fbc9df388c4e3c56518436a63418c
  - one that is a local checkout at commit 390d212d76e91f413f143b53a997b0bf846c453a from Github, and built with `bazel build //src:bazel-dev`

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
For local dev version (where stack trace originated)

https://github.com/bazelbuild/bazel
390d212d76e91f413f143b53a997b0bf846c453a
390d212d76e91f413f143b53a997b0bf846c453a
```

### Have you found anything relevant by searching the web?

https://github.com/eth-sri/Nice2Predict/issues/26
 - (no responses)

https://groups.google.com/g/grpc-io/c/J8mSRbZHkSg/m/M78QqfKXCgAJ
 - says that this error happened from a network timeout
 - I believe that our Bazel configuration (for AOSP) has network connections disabled

### Any other information, logs, or outputs that you want to share?

`strace -f -o bazel.strace.txt tools/bazel aquery --config=bp2build --config=linux_x86_64 //packages/modules/adb:adb_test --verbose_failures`:
[bazel.strace.txt](https://github.com/bazelbuild/bazel/files/9716971/bazel.strace.txt)

**Comment by stnma7e** [comment]
Also, this behavior has persisted across Bazel server restarts (and different Bazel versions, as mentioned above).

**Comment by stnma7e** [comment]
I just found the root cause of this. I had changed the `libraries_to_link` feature in the cc toolchain, and got to this exception after some digging:
```
java.io.IOException: Invalid toolchain configuration: Cannot expand variable 'libraries_to_link.path': structure libraries_to_link doesn't have a field named 'path'
```

**Comment by joeleba** [comment]
I guess the action item here is to provide better error messages in case of such an error.
