### ISSUE TITLE
HEAD crash after incompatible_enforce_config_setting_visibility

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#16446]
### Description of the bug:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//doc:test_setup, config=BuildConfigurationKey[630cafa1c48a364b2467476885d51433a52c036dcff80d6d9ae99bce1a4ff886]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:642)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Configurations don't match: BuildConfigurationKey[630cafa1c48a364b2467476885d51433a52c036dcff80d6d9ae99bce1a4ff886] BuildConfigurationKey[6a7278dae5db84a0f240ae2ba630f3e2171f37f2bbf86ba0cd0f54949d474623] 630cafa1c48a364b2467476885d51433a52c036dcff80d6d9ae99bce1a4ff886 (ConfiguredTarget(@bazel_tools//src/conditions:host_windows_x64_constraint, 6a7278dae5db84a0f240ae2ba630f3e2171f37f2bbf86ba0cd0f54949d474623) config_setting rule @bazel_tools//src/conditions:host_windows_x64_constraint)
        at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetAndData.<init>(ConfiguredTargetAndData.java:72)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetAndData.fromConfiguredTarget(ConfiguredTargetAndData.java:124)
        at com.google.devtools.build.lib.analysis.RuleContext$Builder.build(RuleContext.java:1759)
        at com.google.devtools.build.lib.analysis.RuleContext$Builder.build(RuleContext.java:1704)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:324)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:192)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1231)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1197)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:414)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
        ... 7 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone rules_swift, run `USE_BAZEL_VERSION=174c67f0911c1cb013658f9b2b2d8959d6ef388c bazelisk build ...`

I bisected to 174c67f0911c1cb013658f9b2b2d8959d6ef388c, setting the flag to false does not avoid it

CI logs: https://buildkite.com/bazel/rules-swift-swift/builds/3745#0183c3e2-c2a4-4abc-9330-16b8c93f1b71

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

174c67f0911c1cb013658f9b2b2d8959d6ef388c

**Comment by keith** [comment]
cc @gregestren

**Comment by gregestren** [comment]
Thanks for the repro: I was trying to figure out how to trigger this from https://github.com/bazelbuild/bazel/issues/12932#issuecomment-1273536368.

**Comment by gregestren** [comment]
More direct:

```
USE_BAZEL_VERSION=174c67f0911c1cb013658f9b2b2d8959d6ef388c bazelisk build //doc:test_setup
```

**Comment by gregestren** [comment]
Found a minimal repro:

```
$ cat aa/defs.bzl
def _impl(ctx):
    output = ctx.outputs.out
    ctx.actions.write(output = output, content = "hi", is_executable = True)
    return [DefaultInfo(executable = output)]

fake_test = rule(
    attrs = {
        "msg": attr.string(),
    },
    test = True,
    outputs = {"out": "foo.out"},
    implementation = _impl,
)
```

```
$ cat aa/BUILD
load(":defs.bzl", "fake_test")

config_setting(
    name = "actual_setting",
    define_values = {"a": "1"},
)

alias(
    name = "alias_setting",
    actual = ":actual_setting",
)

fake_test(
    name = "foo",
    msg = select({
        ":alias_setting": "hi",
        "//conditions:default": "there",
    }),
)
```

    $ bazel build //aa:foo --incompatible_enforce_config_setting_visibility --trim_test_configuration
    <crash>

This is how I found it:

- `$ bazel query --output=build //doc:test_setup`
- Built a filegroup target with the same `select()` as in the above.
- That succeeded.
- Since Bazel didn't crash, I could run `$ bazel config 630c 6a72`
- That showed me that one config had `TestOptions` while the other didn't
- That's basically the definition of `--trim_test_configuration`. This also explains why the filegroup succeeded but `diff_test` didn't: `--trim_test_configuration` only trims non-test targets. So in the failing build you get two distinct configurations: one for the `*_test`* and one for the `config_setting` it depends on

**Comment by gregestren** [comment]
https://bazel-review.googlesource.com/c/bazel/+/205341 will fix.

**Comment by meteorcloudy** [comment]
Looks like the fix still need some tweaks, I'm rolling back the flag flip first.
