### ISSUE TITLE
bazel crash: ExceptionInInitializerError / InaccessibleObjectException

### ISSUE THREAD

**Issue by jonmeow** [bazelbuild/bazel#16502]
### Description of the bug:

This was reported to us by @vit1251 at https://github.com/carbon-language/carbon-lang/issues/2268:

```
$ bazel build //explorer/...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 6f16fe52-e33c-4450-98ff-99a2f313ae36
INFO: Analyzed 597 targets (106 packages loaded, 4403 targets configured).
INFO: Found 597 targets...
[0 / 341] [Prepa] Creating source manifest for //explorer:gen_rtti [for host]
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:118)
        at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:111)
        at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction$ParamFileWriter.writeOutputFile(ParameterFileWriteAction.java:170)
        at com.google.devtools.build.lib.exec.FileWriteStrategy.beginWriteOutputToFile(FileWriteStrategy.java:58)
        at com.google.devtools.build.lib.analysis.actions.FileWriteActionContext.beginWriteOutputToFile(FileWriteActionContext.java:49)
        at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:66)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @1817d444
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:191)
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:184)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<init>(StringUnsafe.java:75)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.initInstance(StringUnsafe.java:56)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<clinit>(StringUnsafe.java:37)
        ... 21 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

gh repo clone github.com/carbon-language/carbon-lang
cd carbon-lang
bazel build //explorer/...

### Which operating system are you running Bazel on?

Not provided to us, probably linux?

### What is the output of `bazel info release`?

Not provided to us, probably 5.3.1

`bazel version` should be:

```
Build label: 5.3.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 21 14:59:28 2022 (1663772368)
Build timestamp: 1663772368
Build timestamp as int: 1663772368
```

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Not provided to us
```

### Have you found anything relevant by searching the web?

This looks similar to https://github.com/bazelbuild/bazel/issues/14548, but that was reported as fixed in 5.2.0. We're told a 5.3.1 release was in use. Perhaps a regression?

I can't reproduce it myself.

**Comment by vit1251** [comment]
> Not provided to us, probably linux?

Yep. ArchLinux update version.

**Comment by sgowroji** [comment]
Dupe of https://github.com/bazelbuild/bazel/issues/14548

**Comment by sgowroji** [comment]
Can you try the workaround mentioned  here https://github.com/bazelbuild/bazel/issues/14548#issuecomment-1016025098

**Comment by vit1251** [comment]
Change Java execution binary with `sudo archlinux-java set java-11-openjdk` allow me to make next step. Thanks.
But here I receive next one issue:

```
ERROR: /home/user1/.cache/bazel/_bazel_user1/1fe5914633202e24ffa4f83e09405189/external/flex_v2.6.4/bin/BUILD.bazel:8:10: Linking external/flex_v2.6.4/bin/flex [for host] failed: (Exit 1): clang++ failed: error executing command /usr/bin/clang++ @bazel-out/host/bin/external/flex_v2.6.4/bin/flex-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: unable to find library -l:libunwind.a
ld.lld: error: unable to find library -l:libunwind.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 7.290s, Critical Path: 0.96s
INFO: 254 processes: 246 disk cache hit, 8 internal.
FAILED: Build did NOT complete successfully
```
`libunwind` is already installed in our system.

**Comment by jonmeow** [comment]
Closing this: blaze is not just a build system, it's not setting choosing the flags to pass to lld, that comes from Carbon. You can ask on Carbon's forums, but it's probably another arch-specific issue and as I said before we're mostly Debian and Ubuntu: libunwind.a should be in /usr/lib/llvm-14 alongside the rest of the libraries.
