### ISSUE TITLE
[6.0.0rc1] `cc_proto_library` analysis failure

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#16577]
### Description of the bug:

```
in @_builtins//:common/cc/cc_proto_library.bzl%_cc_proto_aspect aspect on proto_library rule @bazel//src/main/protobuf:execution_statistics_proto: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/cc_proto_library.bzl", line 99, column 48, in _aspect_impl
	File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 191, column 17, in _find_cpp_toolchain
Error in fail: In order to use find_cpp_toolchain, you must include the '//tools/cpp:toolchain_type' in the toolchains argument to your rule.
```

### Which operating system are you running Bazel on?

Linux, macOS

### What is the output of `bazel info release`?

6.0.0rc1

### Any other information, logs, or outputs that you want to share?

Relevant commits: https://github.com/bazelbuild/bazel/commit/c8b7ed3fecbcee39bf1557fc3d608f42baaffdcd

**Comment by Yannic** [comment]
@bazel-io flag

**Comment by Yannic** [comment]
```
INFO: Writing tracer profile to '/private/var/tmp/_bazel_ec2-user/a3fd1e83c84cae2e0d3dfb1700a941e6/command.profile.gz'
INFO: Invocation ID: 570f963f-61b0-4d38-bc44-7bb1c0931683
INFO: Streaming build results to: https://glass.cluster.engflow.com/invocation/570f963f-61b0-4d38-bc44-7bb1c0931683
INFO: Options provided by the client:5  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'test' from /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc:7  Inherited 'common' options: --enable_platform_specific_config --experimental_announce_profile_path
INFO: Reading rc options for 'test' from /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc:9  Inherited 'build' options: --explicit_java_test_deps --nostamp --incompatible_strict_action_env --verbose_failures --incompatible_enable_cc_toolchain_resolution --features=-supports_dynamic_linker --custom_malloc=//lang/cpp:runtime --java_language_version=11 --java_runtime_version=11 --tool_java_language_version=11 --tool_java_runtime_version=11 --build_tag_filters=-ci-only --test_tag_filters=-ci-only,-ci-only-test --instrumentation_filter=<redacted>
INFO: Reading rc options for 'test' from /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc:11  'test' options: --test_summary=testcase --test_output=errors1
INFO: Found applicable config definition build:ci in file /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc: --config=release --color=yes --curses=yes --show_timestamps --announce_rc --test_output=summary --show_progress_rate_limit=2.01
INFO: Found applicable config definition build:release in file /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc: --compilation_mode=opt1
INFO: Found applicable config definition build:macos in file /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc: --config=clang --experimental_one_version_enforcement=ERROR --workspace_status_command=infra/get_workspace_status
INFO: Found applicable config definition build:clang in file /private/var/lib/github-actions/_work/engflow/engflow/.bazelrc: --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --cxxopt=-fno-exceptions --host_cxxopt=-fno-exceptions --cxxopt=-fvisibility=hidden --host_cxxopt=-fvisibility=hidden --cxxopt=-Werror=reorder --host_cxxopt=-Werror=reorder --cxxopt=-Werror=unused-function --host_cxxopt=-Werror=unused-function --cxxopt=-Werror=return-type --host_cxxopt=-Werror=return-type1
INFO: Current date is 2022-10-26
```

**Comment by buildbreaker2021** [comment]
Will take a look

**Comment by buildbreaker2021** [comment]
https://github.com/bazelbuild/bazel/commit/f5711170da68d0d212710283f0e6e2b3254ccc86
Should fix it.
However I could not reproduce the failure since it was not specified how I could do so - please close the issue if the commit fixes it.

**Comment by Wyverald** [comment]
@bazel-io fork 6.0.0

**Comment by fmeum** [comment]
@buildbreaker2021 @Yannic I think that neither of your changes fix this issue:

1. #16585 would need to move the `toolchains` definition from the rule to the aspect definition. It comes with a test that indeed fails because of this.
2. https://github.com/bazelbuild/bazel/commit/f5711170da68d0d212710283f0e6e2b3254ccc86 adds the toolchain type as a label attribute rather than to `toolchains`. Grepping for `_cc_toolchain_type` in Bazel turns up a similar attribute in `cc_binary`, but it isn't used elsewhere. I don't think `find_cpp_toolchain` would pick it up, it even hardcodes the same label.

@buildbreaker2021 You can use the integration test @Yannic added in https://github.com/bazelbuild/bazel/pull/16585/files#diff-6991d88c914706dc4238fc5d870e151d40411e1c9f2163d5b9da6cce9488132e to verify the fix.

**Comment by buildbreaker2021** [comment]
Thanks for your input @fmeum 

I will defer to the author of the issue to answer if the fix works or not - as for the test https://github.com/bazelbuild/bazel/pull/16585 seems to have some failures I did not have a good look into it, but I assumed that I could not use it until it was green.

**Comment by meteorcloudy** [comment]
I believe the test failure in https://github.com/bazelbuild/bazel/pull/16585 is exactly the integration test that reproduces this error, which we want to fix. You can patch that test based on HEAD and check if it passes. If not, we probably need further fix.

**Comment by Yannic** [comment]
Rebasing #16585 to master and removing my fix still reproduces the issue: https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/12978#01841fd2-6d67-4003-b75a-c6e1d6c2f289

**Comment by Yannic** [comment]
https://github.com/bazelbuild/bazel/commit/6c1e4b72ae63417e5e0f2c7aef42fdcb4c172fe6 is sufficient because it reverts https://github.com/bazelbuild/bazel/commit/f5711170da68d0d212710283f0e6e2b3254ccc86.

**Comment by meteorcloudy** [comment]
@Yannic Thanks! @kshyanashree please cherry pick https://github.com/bazelbuild/bazel/commit/6c1e4b72ae63417e5e0f2c7aef42fdcb4c172fe6 for https://github.com/bazelbuild/bazel/issues/16600

**Comment by kshyanashree** [comment]
Sure @meteorcloudy, I will do it. Thanks!
