### ISSUE TITLE
Bazel gets hung indefinitly when remote_timeout is exceeded for downloads

### ISSUE THREAD

**Issue by 80degreeswest** [bazelbuild/bazel#16587]
### Description of the bug:

When --remote_timeout is set to a fairly small value (ex: 2m) and bazel is trying to download a large blob (ex: 2GB) over a fairly saturated network from Buildfarm RBE, exceeding the remote timeout, bazel gets stuck indefinitely with Executing..... message.

Increasing --remote_timeout to a larger value resolves the issue.

```
Writing: bazel-out/k8-fastbuild/bin/***/***/***.tar; Downloading ***/***/***.tar, 986.5 MiB / 2.1 GiB; 699s remote ... (128 actions, 28 running)
Executing genrule //***/***/***:***; 1024s remote ... (3 actions, 2 running)
...
Executing genrule //***/***/***:***; 1024s remote; 4530s remote

```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set --remote_timeout=30s

Try executing an action which has a cached result of a very large size over a network with very low speed.

Build will be stuck.

### Which operating system are you running Bazel on?

ubuntu 18.04

### What is the output of `bazel info release`?

release 5.3.1

**Comment by hauserx** [comment]
Got this problem when upgrading from 5.2.0 to 5.3.1. Looks like this commit contains fix for this problem, and possibly should be included in 5.3.3 release?

https://github.com/bazelbuild/bazel/commit/8b61746cf18d3d8413b569e0b5fca639d28914ea

For reference, here is a sample jstack when this problem occurs.

```
"skyframe-evaluator 105" #1124 prio=5 os_prio=0 cpu=3493.21ms elapsed=1080.36s tid=0x00007f3469538800 nid=0x2256a3 waiting on condition  [0x00007f2975a5c000]
   java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
    - parking to wait for  <0x00007f3375c41fc0> (a java.util.concurrent.CountDownLatch$Sync)
    at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.6/Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.6/Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.6/Unknown Source)
    at java.util.concurrent.CountDownLatch.await(java.base@11.0.6/Unknown Source)
    at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:86)
    at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1468)
    at com.google.devtools.build.lib.remote.RemoteExecutionCache.ensureInputsPresent(RemoteExecutionCache.java:101)
    at com.google.devtools.build.lib.remote.RemoteExecutionService.uploadInputsIfNotPresent(RemoteExecutionService.java:1350)
    at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:251)
    at com.google.devtools.build.lib.remote.RemoteSpawnRunner$$Lambda$977/0x00007f296e67cc40.call(Unknown Source)
    at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)
    at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)
    at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)
    at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:244)
    at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
    at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
    at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
    at com.google.devtools.build.lib.rules.cpp.CppLinkAction.beginExecution(CppLinkAction.java:286)
    at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
    at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
    at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/Unknown Source)
    at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

**Comment by coeuvre** [comment]
Can you check whether this is reproducible with the latest release?

**Comment by 80degreeswest** [comment]
https://github.com/bazelbuild/bazel/commit/8b61746cf18d3d8413b569e0b5fca639d28914ea fixes the issue.

**Comment by glukasiknuro** [comment]
@coeuvre should there be 5.3.3 release with this fix?
