### ISSUE TITLE
Uncaught exception with ctx.action.symlink and remote caching

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#16580]
### Description of the bug:

Using `--experimental_allow_unresolved_symlinks` with `--remote_cache` and `ctx.action.symlink`, I get a crash.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a workspace:

```
mkdir /tmp/foo && cd /tmp/foo


touch WORKSPACE


cat >BUILD <<'eof'
load(":sym.bzl", "sym")

genrule(
    name = "x",
    srcs = [":sym"],
    outs = ["x.out"],
    cmd = "ls -la $$(realpath $(SRCS)) > $@",
)

sym(
    name = "sym",
    src = ":dep",
)

genrule(
    name = "dep",
    outs = ["dep.out"],
    cmd = "fallocate -l 1000000 $@",
)
eof


cat >sym.bzl  <<'eof'
def _impl(ctx):
    out = ctx.actions.declare_symlink("%s.sym" % ctx.label.name)
    ctx.actions.symlink(
        output = out,
        target_path = ctx.file.src.path,
    )
    return [DefaultInfo(files = depset([out]))]

sym = rule(
    implementation = _impl,
    attrs = {
        "src": attr.label(allow_single_file = True, mandatory = True),
    },
)
eof
```

Run a remote cache (using https://github.com/buchgr/bazel-remote):

```
bazel run //:bazel-remote -- --dir=/tmp/cas --grpc_address=127.0.0.1:5300 --max_size=1000000000
```

Run the build to repro the crash:

```
bazel --batch --ignore_all_rc_files build --action_env=FOO=$RANDOM --remote_cache=grpc://localhost:5300 --experimental_allow_unresolved_symlinks //:x
INFO: Invocation ID: dfe6ef52-d203-499f-9153-36212133d068
INFO: Analyzed target //:x (5 packages loaded, 9 targets configured).
INFO: Found 1 target...
[1 / 3] 2 actions, 0 running
    [Prepa] BazelWorkspaceStatusAction stable-status.txt
    [Prepa] Executing genrule //:x
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//:x, config=BuildConfigurationValue.Key[8987fef7c89c3216cdea2b3da6f0a1988996c7aa30d0c13eae6cd7e36f9317a5]}, actionIndex=0}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, actionLookupKey=ConfiguredTargetKey{label=//:x, config=BuildConfigurationValue.Key[8987fef7c89c3216cdea2b3da6f0a1988996c7aa30d0c13eae6cd7e36f9317a5]}, willTest=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Encountered symlink input 'bazel-out/k8-fastbuild/bin/sym.sym', but all symlinks should have been resolved by SkyFrame. This is a bug.
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.lambda$buildFromActionInputs$1(DirectoryTreeBuilder.java:160)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.build(DirectoryTreeBuilder.java:221)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.buildFromActionInputs(DirectoryTreeBuilder.java:125)
        at com.google.devtools.build.lib.remote.merkletree.DirectoryTreeBuilder.fromActionInputs(DirectoryTreeBuilder.java:63)
        at com.google.devtools.build.lib.remote.merkletree.MerkleTree.build(MerkleTree.java:217)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.buildInputMerkleTree(RemoteExecutionService.java:403)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.buildRemoteAction(RemoteExecutionService.java:451)
        at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:95)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:141)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 4 more
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.3.2

**Comment by laszlocsomor** [comment]
An even simpler repro:

```
  $ cat BUILD
load(":sym.bzl", "sym")

genrule(
    name = "x",
    srcs = [":sym"],
    outs = ["x.out"],
    cmd = "ls -la $$(realpath $(SRCS)) > $@",
)

sym(
    name = "sym",
)


  $ cat sym.bzl
def _impl(ctx):
    out = ctx.actions.declare_symlink("%s.sym" % ctx.label.name)
    ctx.actions.symlink(
        output = out,
        target_path = "dangling",
    )
    return [DefaultInfo(files = depset([out]))]

sym = rule(
    implementation = _impl,
)
```

**Comment by fmeum** [comment]
Does this repro with Bazel 6.0.0rc1? It looks like the expected failure of `ctx.actions.declare_symlink` with RBE before all the recent improvements to `--experimental_allow_unresolved_symlinks`.

**Comment by laszlocsomor** [comment]
It doesn't! Nice find @fmeum , thanks.
