### ISSUE TITLE
Improve error handling for the remote cache

### ISSUE THREAD

**Issue by glinscott** [bazelbuild/bazel#1682]
Sometimes, when building using the caching (`--hazelcast_node=bcache:5701 --spawn_strategy=remote --genrule_strategy=remote`), we get this type of output, which completely overwhelms the terminal.

It starts with a few things like `ERROR: Crashes detected` or `java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION`

It consists of many thousands of Artifact things like this:

```
Artifact:[[/home/gary/.cache/bazel/_bazel_gary/3a6c2c616f54535a231d0290fdddf8bb/execroot/repo]bazel-out/host/bin]third_party/file
```

**Comment by trainman419** [comment]
I'm seeing this too, and it seems to cause my local bazel server to crash. When I retry the build, it looks like it's starting a new server, and the build succeeds.

**Comment by glinscott** [comment]
Ping @hhclam -- this is happening on every error, which basically breaks the caching.

**Comment by hhclam** [comment]
Do you mean the log has a lot of lines what read like this?

Artifact:[[/home/gary/.cache/bazel/_bazel_gary/3a6c2c616f54535a231d0290fdddf8bb/execroot/repo]bazel-out/host/bin]third_party/file

Is there a repo case for this or the full stack trace or log when this happens?

**Comment by glinscott** [comment]
@hhclam apologies, should have added that before.

Repro requires setting up a cache server, and then introducing an error in a c++ file, then attempting to build.

Callstack here:
```
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1021)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:532)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.hazelcast.core.HazelcastException: java.lang.InterruptedException
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:67)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:133)
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:198)
	at com.google.devtools.build.lib.remote.MemcacheActionCache.writeActionOutput(MemcacheActionCache.java:120)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.writeActionOutput(RemoteSpawnStrategy.java:251)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:143)
	at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:65)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:760)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:699)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:102)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:589)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:551)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:373)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:387)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:174)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:972)
	... 4 more
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:117)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:102)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
	... 20 more
```

**Comment by glinscott** [comment]
Right above that exception there are thousands of lines of output similar to this:

```
nal]_middlemen/_S_Sbase_Sparams_Cimpl-cpp_compilation_prerequisites] -> [Artifact:[[/home/parallels/.cache/bazel/_bazel_parallels/6ca8bc9fe7f0716ca400b8a48dc45a17/execroot/driving]bazel-out/local_linux-optcuda/bin]base/params/_objs/impl/base/params/impl/yml_param_buffer.pic.o, Artifact:[[/home/parallels/.cache/bazel/_bazel_parallels/6ca8bc9fe7f0716ca400b8a48dc45a17/execroot/driving]bazel-out/local_linux-optcuda/bin]base/params/_objs/impl/base/params/impl/yml_param_buffer.pic.d]])' (requested by nodes 'ARTIFACT:base/params/_objs/impl/base/params/impl/yml_param_buffer.pic.o //base/params:impl 0820bfecf1a91f0b9e43b78e75d380ae')
```

**Comment by glinscott** [comment]
I'm trying out this patch which seems to solve the issue (not very clean though).

```
diff --git a/src/main/java/com/google/devtools/build/lib/remote/MemcacheActionCa
index e821f12..46e4a6c 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/MemcacheActionCache.jav
+++ b/src/main/java/com/google/devtools/build/lib/remote/MemcacheActionCache.jav
@@ -117,7 +117,12 @@ public final class MemcacheActionCache implements RemoteAct
   @Override
   public void writeActionOutput(String key, Path execRoot)
       throws IOException, CacheNotFoundException {
-    byte[] data = cache.get(key);
+    byte[] data = null;
+    try {
+      data = cache.get(key);
+    } catch (com.hazelcast.core.HazelcastException e) {
+      throw new CacheNotFoundException("Hazelcast exception for key: " + key);
+    }
     if (data == null) {
       throw new CacheNotFoundException("Action output cannot be found with key:
     }
```

**Comment by damienmg** [comment]
@glinscott: I think this is a correct patch. If you have a repro for adding a test that would be awesome :) Anyway, is there any chance you could send a code review for it?

**Comment by ulfjack** [comment]
If the HazelcastException wraps an InterruptedException, we should unwrap and throw the InterruptedException, not throw a CacheNotFoundException.

**Comment by ulfjack** [comment]
We're planning to discontinue Hazelcast support, but there's a similar issue with the remote cache wrapping everying in a RuntimeException rather than propagating the lower-level exception that we should fix.

**Comment by ulfjack** [comment]
Changing title to clarify that this isn't specific to Hazelcast.

**Comment by ulfjack** [comment]
One of my recent changes (2936047ae407fdba9ac432694ae8b72ebee4f488) should have improved the error handling here with fallback happening more reliably.

**Comment by ulfjack** [comment]
Note that we didn't improve Hazelcast error handling - Hazelcast support is deprecated, please use the either the HTTP Rest implementation or the gRPC implementation. You can setup HTTP Rest with Hazelcast, of course.
