### ISSUE TITLE
Stack trace exception with an error in the workspace file and doing `bazel info`

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1693]
```
$ bazel info 
INFO: Reading 'startup' options from /usr/local/google/home/dmarting/.bazelrc: --watchfs
java.lang.IllegalStateException: Unknown error during ConfigurationCollectionValue evaluation
    at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1021)
    at com.google.devtools.build.lib.runtime.CommandEnvironment.getConfigurations(CommandEnvironment.java:326)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:124)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:108)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:175)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
    at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
    at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
    at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:418)
    at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:737)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
    at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: com.google.devtools.build.lib.skyframe.PackageFunction$PackageFunctionException: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path
    at com.google.devtools.build.lib.skyframe.PackageFunction.fetchImportsFromBuildFile(PackageFunction.java:706)
    at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:107)
    at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUp(ParallelEvaluator.java:1591)
    at com.google.devtools.build.skyframe.ParallelEvaluator.waitForCompletionAndConstructResult(ParallelEvaluator.java:1435)
    at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:1404)
    at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:1365)
    at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:189)
    at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:39)
    at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1012)
    ... 13 more
Caused by: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path
    ... 22 more
java.lang.IllegalStateException: Unknown error during ConfigurationCollectionValue evaluation
    at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1021)
    at com.google.devtools.build.lib.runtime.CommandEnvironment.getConfigurations(CommandEnvironment.java:326)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:124)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:108)
    at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:175)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
    at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
    at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
    at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:418)
    at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:737)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
    at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: com.google.devtools.build.lib.skyframe.PackageFunction$PackageFunctionException: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path
    at com.google.devtools.build.lib.skyframe.PackageFunction.fetchImportsFromBuildFile(PackageFunction.java:706)
    at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:107)
    at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUp(ParallelEvaluator.java:1591)
    at com.google.devtools.build.skyframe.ParallelEvaluator.waitForCompletionAndConstructResult(ParallelEvaluator.java:1435)
    at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:1404)
    at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:1365)
    at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:189)
    at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:39)
    at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1012)
    ... 13 more
Caused by: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path
    ... 22 more
```

This is coming because we try to load build configuration that depends on it. It is a bit weird to have an exception here and I am not even sure this should be an error.

Ping @lberki for getting more opinion on if this is possible to complete the info command in that case.

**Comment by kchodorow** [comment]
I'm actually working on something related to this right now (#1681).

The info command prints the execution root and output paths, both of which should include the workspace name (which requires at least _parsing_ the WORKSPACE file). So, I think it should print an error (but obviously it shouldn't throw a stack trace).

**Comment by damienmg** [comment]
If that's only the workspace name, we can probably work around it by just asking for it. Maybe we should make it an independent skyvalue. It does not needs the workspace to be semantically correct, just syntaxically.

**Comment by lberki** [comment]
Well, if the configuration does depend on `third_party/gpus:stuff`, we can't create it. It should be fine to also catch `BuildFileContainsErrorsException` in `#createConfigurations` and wrap that in an `InvalidConfigurationException`.

**Comment by girving** [comment]
@damienmg Is there a bug corresponding to the underlying broken `WORKSPACE`?  I'm seeing exactly the same error and have no idea how to fix it:

    (master) beltrami:hol% bazel build ...
    ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path.
    INFO: Elapsed time: 0.141s

Background: I'm trying to make a repository that depends on tensorflow as a submodule.

**Comment by damienmg** [comment]
@girving you should track https://github.com/tensorflow/serving/pull/166 where we are resolving that issue.

**Comment by dslomov** [comment]
Not reproducible at HEAD
