### ISSUE TITLE
build_file_content in new_local_repository overwrites original BUILD file

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#1697]
`build_file_content` in `new_local_repository` overwrites original `BUILD` file at the source and not just locally... `build_file` works as expected and overwrites`BUILD` file only locally, without modifying `BUILD` file at the source.

**Comment by katre** [comment]
If you already have a BUILD file, use local_repository, not new_local_repository.

**Comment by PiotrSikora** [comment]
I'm well aware of `local_repository`, but sometimes `BUILD` file needs to be extended with custom targets.

Anyway, this seems like an inconsistency, since `build_file` itself doesn't overwrite the source.

**Comment by damienmg** [comment]
We should definitely not overwrite the source's BUILD file, I think this is happening because we write the BUILD file after symlinking everything from the source path. So if a build file exist we overwrite it, that is not good.

**Comment by PiotrSikora** [comment]
Hey @kchodorow,
it looks that your fix broke existing behavior in which it was possible to use `build_file_content` with a repository that already had `BUILD` file, i.e. it was possible to provide alternative `BUILD` file.

    // Make sure we're not overwriting an existing BUILD file.
    if (buildFilePath.exists()) {
      Preconditions.checkState(buildFilePath.isSymbolicLink());
      buildFilePath.delete();
    }

throws:

    java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ngx_brotli' (requested by nodes 'REPOSITORY:@ngx_brotli')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:447)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:159)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:196)
        at com.google.devtools.build.lib.rules.repository.RepositoryFunction.writeBuildFile(RepositoryFunction.java:203)
        at com.google.devtools.build.lib.rules.repository.NewRepositoryBuildFileHandler.finishBuildFile(NewRepositoryBuildFileHandler.java:112)
        at com.google.devtools.build.lib.bazel.repository.NewGitRepositoryFunction.fetch(NewGitRepositoryFunction.java:42)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:388)
        ... 4 more

**Comment by kchodorow** [comment]
Whoops. Thanks for the report.

**Comment by kchodorow** [comment]
Wait, how do you have a BUILD file in that directory that isn't a symbolic link?  Could you do `ls -l $(bazel info output_base)/external/ngx_brotli`?

**Comment by PiotrSikora** [comment]
Yes, it's git repository.

**Comment by kchodorow** [comment]
Note: 2bc0939 should be cherry picked into the release.

**Comment by PiotrSikora** [comment]
Thanks! It works fine now.
