### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib/remote:BuildWithoutTheBytesIntegrationTest fails on Apple Silicon machines

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#17006]
https://buildkite.com/bazel/bazel-bazel/builds/21550#01850a26-7114-4154-8eaa-e259ee8e5693
```
There was 1 failure:
1) disableRunfiles_buildSuccessfully(com.google.devtools.build.lib.remote.BuildWithoutTheBytesIntegrationTest)
com.google.devtools.build.lib.analysis.ViewCreationFailedException: Analysis of target '//:foobar' failed; build aborted: 
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.createViewCreationFailedException(SkyframeErrorProcessor.java:633)
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.throwOrReturnAspectAnalysisException(SkyframeErrorProcessor.java:429)
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.processErrors(SkyframeErrorProcessor.java:316)
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.processAnalysisErrors(SkyframeErrorProcessor.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:419)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:400)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:242)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:140)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:180)
	at com.google.devtools.build.lib.buildtool.util.BlazeRuntimeWrapper.executeBuild(BlazeRuntimeWrapper.java:369)
	at com.google.devtools.build.lib.buildtool.util.BuildIntegrationTestCase.buildTarget(BuildIntegrationTestCase.java:715)
	at com.google.devtools.build.lib.remote.BuildWithoutTheBytesIntegrationTestBase.disableRunfiles_buildSuccessfully(BuildWithoutTheBytesIntegrationTestBase.java:102)
	... 27 trimmed
Caused by: com.google.devtools.build.lib.skyframe.ConfiguredValueCreationException: 
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction$ReportedException.withoutMessage(ConfiguredTargetFunction.java:1309)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction$ReportedException.<init>(ConfiguredTargetFunction.java:1297)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:460)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUp(ParallelEvaluator.java:427)
	at com.google.devtools.build.skyframe.ParallelEvaluator.waitForCompletionAndConstructResult(ParallelEvaluator.java:216)
	at com.google.devtools.build.skyframe.ParallelEvaluator.doMutatingEvaluation(ParallelEvaluator.java:182)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:677)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:203)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2219)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:357)
	... 35 more

FAILURES!!!
Tests run: 6,  Failures: 1
```

**Comment by meteorcloudy** [comment]
Please re-enable the failing tests in Bazel's [presubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml) and [postsubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml) file after fixing them!
