### ISSUE TITLE
baseline_coverage.dat missing with BES + BwtB

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17001]
### Description of the bug:

We're seeing a log like:

```
(13:23:40) WARNING: Uploading BEP referenced local files: /private/var/tmp/_bazel_iosci/6462d53b34f6666019a2973c03de6978/execroot/lyftios/bazel-out/darwin_arm64-fastbuild/testlogs/Modules/.../baseline_coverage.dat (No such file or directory)
java.io.FileNotFoundException: /private/var/tmp/_bazel_iosci/6462d53b34f6666019a2973c03de6978/execroot/lyftios/bazel-out/darwin_arm64-fastbuild/testlogs/Modules/.../baseline_coverage.dat (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:209)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:199)
	at com.google.devtools.build.lib.vfs.PathTransformingDelegateFileSystem.stat(PathTransformingDelegateFileSystem.java:252)
	at com.google.devtools.build.lib.remote.RemoteActionFileSystem.stat(RemoteActionFileSystem.java:460)
	at com.google.devtools.build.lib.remote.RemoteActionFileSystem.getFileSize(RemoteActionFileSystem.java:392)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:559)
	at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:61)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:186)
```

For every single test target when we run them on CI with BES uploads and `--remote_download_toplevel --experimental_remote_build_event_upload=minimal`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not sure, it's hard to debug with cache hits vs not

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.0.0rc4

**Comment by brentleyjones** [comment]
@coeuvre @tjgq

**Comment by coeuvre** [comment]
Probably the test action hit the cache so some files are not downloaded. Might related https://github.com/bazelbuild/bazel/pull/16556.

Can you please provide an repro? Not exactly sure how to trigger this error.

**Comment by thirtyseven** [comment]
I am also getting this error on Bazel 6.1.0, but it doesn't seem to matter what values I specify for `--remote_download_toplevel` or `--experimental_remote_build_event_upload=minimal`. What's odder is that after the build completes, the `baseline_coverage.dat` file that Bazel complains it couldn't find is present in the output tree.

**Comment by UebelAndre** [comment]
I'm seeing this spam in `rules_rust` builds on Bazel 6.2.1 for the following pull-request https://github.com/bazelbuild/rules_rust/pull/2001

@coeuvre does this provide you a sufficient repro?

https://buildkite.com/bazel/rules-rust-rustlang/builds/8715#0188aaec-43c1-4ad1-a9fe-62cdbf7d03e3
```
(14:48:09) WARNING: Uploading BEP referenced local files: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/rules_rust/bazel-out/k8-fastbuild/testlogs/test/unit/proc_macro/extern_flag_passed_when_compiling_macro_2018/baseline_coverage.dat (No such file or directory)
java.io.FileNotFoundException: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/rules_rust/bazel-out/k8-fastbuild/testlogs/test/unit/proc_macro/extern_flag_passed_when_compiling_macro_2018/baseline_coverage.dat (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:210)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:200)
	at com.google.devtools.build.lib.unix.UnixFileSystem.getFileSize(UnixFileSystem.java:391)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:559)
	at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:61)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:194)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.lambda$upload$7(ByteStreamBuildEventArtifactUploader.java:330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:185)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle$CollectorSingleObserver.onSubscribe(FlowableCollectWithCollectorSingle.java:102)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle.subscribeActual(FlowableCollectWithCollectorSingle.java:71)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by UebelAndre** [comment]
@scentini do you know what would be needed to gain some traction here? These warnings are exploding logs in my projects.

**Comment by coeuvre** [comment]
Sorry for the delay. I will look into it.

**Comment by coeuvre** [comment]
I can reproduce this issue using rules_rust with Bazel 6.2.1, but can't reproduce it with Bazel@HEAD. The root cause is similar to the issue described in #17798. I will work on a fix for 6.3.0.

**Comment by coeuvre** [comment]
And this issue exists without using BwoB. It's just that the file was not generated at the time when the BEP event was emitted.

**Comment by coeuvre** [comment]
cc @c-mita in case you are ware of this issue.

**Comment by c-mita** [comment]
I'm not aware of anything regarding this.

Does it complain about missing baseline_coverage.dat files for all transitive targets? Or just the top-level test targets?

**Comment by coeuvre** [comment]
Just the top-level targets. The missing `baseline_coverage.dat` files are generated afterwards. My suspicion is there are missing deps between the `BaselineCoverageAction` and `CompletionFunction` so that the `TargetCompletedEvent` was emitted without waiting for `baseline_coverage.dat` to be generated. I am running a bisection to look which commit fixed this.

**Comment by coeuvre** [comment]
Bisection points me to 30cf799f58128d2922d3af59a6a907c4d8115952 which forces skyframe to use FJP. And if I rerun the repro with flag `--experimental_use_fork_join_pool` using 6.2.1, guess what, the issue disappeared.

cc @meisterT

**Comment by tjgq** [comment]
We believe this has been fixed at head through a combination of recent changes; please reopen otherwise.

**Comment by brentleyjones** [comment]
Starting in Bazel 9 we started to see this:
```
WARNING: Uploading BEP referenced local file /private/var/tmp/_bazel_brentley.jones/b99e0a057b45e1bdfe9189087df384f2/execroot/_main/bazel-out/_coverage/_baseline_report.dat: [unix_jni.cc:382] /private/var/tmp/_bazel_brentley.jones/b99e0a057b45e1bdfe9189087df384f2/execroot/_main/bazel-out/_coverage/_baseline_report.dat (No such file or directory)
java.io.FileNotFoundException: [unix_jni.cc:382] /private/var/tmp/_bazel_brentley.jones/b99e0a057b45e1bdfe9189087df384f2/execroot/_main/bazel-out/_coverage/_baseline_report.dat (No such file or directory)
        at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
        at com.google.devtools.build.lib.unix.NativePosixFiles.stat(NativePosixFiles.java:93)
        at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:124)
        at com.google.devtools.build.lib.vfs.Path.stat(Path.java:322)
        at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:81)
        at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:203)
        at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.lambda$doUpload$1(ByteStreamBuildEventArtifactUploader.java:370)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:185)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129)
        at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
        at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle$CollectorSingleObserver.onSubscribe(FlowableCollectWithCollectorSingle.java:102)
        at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle.subscribeActual(FlowableCollectWithCollectorSingle.java:71)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

We use `--collect_code_coverage` with `bazel build` and `bazel test` to ensure cache hits.
