### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib/skyframe/serialization:SerializationTests failing with Bazel 6.0.0rc5 and Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#17016]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2783#01850f44-ca27-4f15-868b-e0e09da937e3

https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01850f44-ca27-4f15-868b-e0e09da937e3/src/test/java/com/google/devtools/build/lib/skyframe/serialization/SerializationTests/test.log
```
There was 1 failure:
1) stackOverflowTransformedIntoSerializationException(com.google.devtools.build.lib.skyframe.serialization.ArrayCodecTest)
java.lang.AssertionError: expected com.google.devtools.build.lib.skyframe.serialization.SerializationException to be thrown, but nothing was thrown
	at org.junit.Assert.assertThrows(Assert.java:1028)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at com.google.devtools.build.lib.skyframe.serialization.ArrayCodecTest.stackOverflowTransformedIntoSerializationException(ArrayCodecTest.java:52)

FAILURES!!!
Tests run: 115,  Failures: 1
```

**Comment by meteorcloudy** [comment]
Please re-enable the failing tests in Bazel's [presubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml) and [postsubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml) file after fixing them!
