### ISSUE TITLE
Windows processes sometimes hang on termination

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1708]
Directly observable on `ci.bazel.io`. Stack traces look like this:

```
"skyframe-evaluator 146" #730 prio=5 os_prio=0 tid=0x000000002ac3c800 nid=0x2114 waiting on condition [0x00000000
342bd000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000073c6d5380> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
        at com.google.devtools.build.lib.shell.Consumers$FutureConsumption.waitForCompletion(Consumers.java:226)
        at com.google.devtools.build.lib.shell.Consumers$OutErrConsumers.waitForCompletion(Consumers.java:85)
        at com.google.devtools.build.lib.shell.Command.waitForProcessToComplete(Command.java:851)
        at com.google.devtools.build.lib.shell.Command.access$000(Command.java:117)
        at com.google.devtools.build.lib.shell.Command$2.get(Command.java:721)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:421)
        at com.google.devtools.build.lib.standalone.StandaloneSpawnStrategy.exec(StandaloneSpawnStrategy.java:116)
        at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:64)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1170)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:774)
```

```
"Command-Accumulator-Thread-8" #794 daemon prio=5 os_prio=0 tid=0x000000003fe31000 nid=0x1e94 runnable [0x000000002c0de000]
   java.lang.Thread.State: RUNNABLE
        at com.google.devtools.build.lib.windows.WindowsProcesses.nativeReadStream(Native Method)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessInputStream.read(WindowsSubprocess.java:82)
        - locked <0x000000073c6d53d8> (a com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessInputStream)
        at java.io.InputStream.read(InputStream.java:101)
        at com.google.devtools.build.lib.shell.InputStreamSink$CopySink.run(InputStreamSink.java:98)
        at com.google.devtools.build.lib.shell.Consumers$ClosingSink.run(Consumers.java:316)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Process Explorer shows that the Bazel process doesn't have a relevant subprocess (only JavaBuilder worker threads, but this is a `CppCompileAction`). It has a bunch of file handles open (`\Device\NamedPipe`) and a bunch of `\Device\Afd` ones, which are apparently something something networking. 

My conjecture is that this is because the Bazel process does not get notified about the other end of the pipe being closed when the subprocess terminates. It's somewhat odd, though, because it only happens sometimes.

Ways this could not be true:
 * Process Explorer doesn't show subprocesses in jobs
 * We redirect the output of this process to a file and not use a named pipe. Looking at the code, this doesn't seem to be the case. In fact, the overloads of `Command#execute()` that redirect to files don't seem to be used at all.

**Comment by lberki** [comment]
There are also a few process handles still open that refer to non-existent processes.

**Comment by lberki** [comment]
I suppose the `\Device\NamedPipe` things are actually the anonymous pipes created by `CreatePipe()`?

**Comment by lberki** [comment]
We could work around this by forcibly interrupting the `ReadFile()` system calls when we know that the process terminates, but before we do that, I'd rather we try to understand what's going on.

**Comment by lberki** [comment]
I tried forcibly closing the handles referring to non-existent processes from Process Explorer to no avail; process is still hung.

**Comment by lberki** [comment]
I'll start running a simple genrule in a loop in an effort to trigger this bug locally.

**Comment by lberki** [comment]
~1000 Bazel invocations later, nothing.

**Comment by lberki** [comment]
So, I added code to close the read side of the pipes when `WaitForMultipleObjects()` returns... and did manage to reproduce the issue then, with the very same stack traces. This is weird. And it was two MSVC C++ compile actions. This is odd...

**Comment by lberki** [comment]
This is definitely specific to `CppCompileAction`, which explains why I couldn't reproduce it with those above 1000 invocations. Shot in the dark: maybe the process whose termination we are watching passes the handle *further*, so that when it dies, the handle still exists? 

Strangely, now that I am closing the handles at the end of `#nativeWaitFor()`, this is reproducible 100%. On the flip side, I can use printf-debugging from the native code, so I got that going for me, which is nice.

**Comment by lberki** [comment]
Whoa, `CloseHandle()` seems to hang (!) (or else the last log line does not get output). To be continued tomorrow the earliest.

**Comment by lberki** [comment]
Verified experimentally: if a thread is stopped in `ReadFile()` on a handle, `CloseHandle()` will block. Wat.

**Comment by lberki** [comment]
I *think* 76b3fb9 fixes this. Let's wait for a few days to make sure that the CI didn't just accidentally finish.

**Comment by ulatekh** [comment]
I ran into this today, not in your project.
My call to CloseHandle() was hanging, and the thread calling ReadFile() didn't exit automatically.
You probably already know you have to close the "write" side of the pipe before the "read" side.

The issue turned out to be that I had to close *all* copies of the "write" side...in my case, I had a file-descriptor that had been created from the handle, using _open_osfhandle().
I had to close that file-descriptor, then all was well.
BTW, that automatically closed the associated handle.
