### ISSUE TITLE
[Build failure] FreeBSD 14-CURRENT/Gentoo Linux amd64 with OpenJDK 17.0 and 18.0

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazel#17103]
### Description of the bug:

Bazel release version 6.0.0 fails to build on FreeBSD 14-CURRENT amd64 with the following error:

```
Sun Jan 01 03:13 PM yesudeep at mongolia running bash5.2 on FreeBSD 14.0-CURRENT amd64
in ~/src/tmp6   master
>> env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
DEBUG: /tmp/bazel_3aV1Io3I/out/external/build_bazel_rules_nodejs/index.bzl:122:10: WARNING: check_rules_nodejs_version has been removed. This is a no-op, please remove the call.
INFO: Analyzed target //src:bazel_nojdk (383 packages loaded, 10302 targets configured).
INFO: Found 1 target...
INFO: From Generating Descriptor Set proto_library @com_github_cncf_udpa//xds/service/orca/v3:pkg:
xds/service/orca/v3/orca.proto:14:1: warning: Import validate/validate.proto is unused.
INFO: From Compiling src/core/lib/security/transport/client_auth_filter.cc:
external/com_github_grpc_grpc/src/core/lib/security/transport/client_auth_filter.cc:153:8: warning: initialized lambda captures are a C++14 extension [-Wc++14-extensions]
      [call_args =
       ^
1 warning generated.
INFO: From Compiling src/core/ext/filters/fault_injection/fault_injection_filter.cc:
external/com_github_grpc_grpc/src/core/ext/filters/fault_injection/fault_injection_filter.cc:138:8: warning: initialized lambda captures are a C++14 extension [-Wc++14-extensions]
      [decision = std::move(decision)]() { return decision.MaybeAbort(); },
       ^
1 warning generated.
INFO: From Compiling src/core/ext/filters/channel_idle/channel_idle_filter.cc:
external/com_github_grpc_grpc/src/core/ext/filters/channel_idle/channel_idle_filter.cc:200:8: warning: initialized lambda captures are a C++14 extension [-Wc++14-extensions]
      [decrementer = Decrementer(this),
       ^
external/com_github_grpc_grpc/src/core/ext/filters/channel_idle/channel_idle_filter.cc:201:8: warning: initialized lambda captures are a C++14 extension [-Wc++14-extensions]
       next = next_promise_factory(std::move(call_args))]() mutable
       ^
2 warnings generated.
[1,294 / 1,313] [Prepa] @bazel_tools//third_party/ijar:zip
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.actions.ParameterFile.writeContentLatin1(ParameterFile.java:141)
        at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:120)
        at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:112)
        at com.google.devtools.build.lib.actions.CommandLines$ParamFileActionInput.writeTo(CommandLines.java:319)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:368)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.runOnce(LocalSpawnRunner.java:258)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:229)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:170)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:299)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:152)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:112)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:64)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:352)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:940)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1107)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1065)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:160)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:93)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:507)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:826)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:323)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:161)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @5b7d6536
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:191)
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:184)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<init>(StringUnsafe.java:61)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<clinit>(StringUnsafe.java:36)
        ... 29 more

ERROR: Could not build Bazel
```

System information:

```
>> uname -mrs
FreeBSD 14.0-CURRENT amd64

>> echo $JAVA_HOME
/usr/local/openjdk18

>> java --version
openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9-1)
OpenJDK 64-Bit Server VM (build 18.0.2+9-1, mixed mode, sharing)

>> java --version
openjdk 17.0.5 
OpenJDK Runtime Environment (build 18.0.2+9-1)
OpenJDK 64-Bit Server VM (build 18.0.2+9-1, mixed mode, sharing)

>> g++ --version
g++ (FreeBSD Ports Collection) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Release file used: https://github.com/bazelbuild/bazel/releases/download/6.0.0/bazel-6.0.0-dist.zip

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download https://github.com/bazelbuild/bazel/releases/download/6.0.0/bazel-6.0.0-dist.zip
2. Run `unzip bazel-6.0.0-dist.zip`
3. Run `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" ./compile.sh`

### Which operating system are you running Bazel on?

FreeBSD 14-CURRENT amd64

### What is the output of `bazel info release`?

release 5.3.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Not a git repository.
```

### Have you found anything relevant by searching the web?

Possible related information: 
- [ ] https://github.com/bazelbuild/bazel/issues/15531
- [ ] https://github.com/bazelbuild/bazel/issues/14548
- [ ] https://github.com/bazelbuild/bazel/issues/15831
- [ ] https://groups.google.com/g/repo-discuss/c/v3EHHdjDhiU
- [ ] Flag appears to have been added to address this in 6.0.0, but the problem persists: https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1

**Comment by cushon** [comment]
I agree this is supposed to work, and that it was supposed to be fixed by https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1

> What is the output of bazel info release?
> release 5.3.0

Was this tested with 6.0.0, or with 5.3.0?

**Comment by lima-limon-inc** [comment]
Hi, I am having the same problem with trying to build bazel with open jdk17
Have you found any solution?

**Comment by meteorcloudy** [comment]
While upgrading testing platforms for Bazel to ubuntu2204 with JDK 17, we are also encountering this problem:
- https://buildkite.com/bazel/google-bazel-presubmit/builds/66842#01880058-5b44-465b-b1fb-8ec4d704ac95
- https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01880058-5b44-465b-b1fb-8ec4d704ac95/src/test/shell/bazel/bazel_bootstrap_distfile_tar_test/test_attempts/attempt_1.log

**Comment by lima-limon-inc** [comment]
Switching to Open JDK 11 seems to continue the compilation. 
Are there any major problems in using this approach?

**Comment by fmeum** [comment]
The version of Bazel used to build (not the version of Bazel that is being built) has to include https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1 for it to work with JDK 17, so it's expected that 5.3.0 won't work.

@meteorcloudy  The CI issue you are facing is a different one, but can probably be fixed along the lines of the commit @cushon and I linked, just with `java.lang.invoke` instead of `java.lang`.

**Comment by lima-limon-inc** [comment]
[81e368f](https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1) is included in the latest release [6.2.0](https://github.com/bazelbuild/bazel/releases/tag/6.2.0), right?

**Comment by meteorcloudy** [comment]
During bootstrapping Bazel, we are running the Bazel server directly without client: https://github.com/bazelbuild/bazel/blob/df728bdb51e75b9f7789b42e3371d858fa08d3f9/scripts/bootstrap/bootstrap.sh#L49, I guess that's why https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1 didn't work.

**Comment by lima-limon-inc** [comment]
> Switching to Open JDK 11 seems to continue the compilation. Are there any major problems in using this approach?

Can confirm, Open JDK indeed worked and tensorflow was compiled correclty (or so I hope :sweat_smile: )

**Comment by lima-limon-inc** [comment]
New bazel version 6.2.0 compiles correctly with openJDK 17
Tensorflow compiles correctly as well.
Thanks @fmeum !

**Comment by lima-limon-inc** [comment]
As of  today, version 6.2.0 has been included into Gentoo's main tree!
Thanks for the help!

**Comment by blackgnezdo** [comment]
FWIW, I neutered this code to get past the problem on OpenBSD with jdk-17:
```patch

Index: src/main/java/com/google/devtools/build/lib/actions/ParameterFile.java
--- src/main/java/com/google/devtools/build/lib/actions/ParameterFile.java.orig
+++ src/main/java/com/google/devtools/build/lib/actions/ParameterFile.java
@@ -116,11 +116,6 @@ public class ParameterFile {
 
   private static void writeContent(
       OutputStream outputStream, Iterable<String> arguments, Charset charset) throws IOException {
-    if (charset.equals(ISO_8859_1)) {
-      writeContentLatin1(outputStream, arguments);
-    } else if (charset.equals(UTF_8)) {
-      writeContentUtf8(outputStream, arguments);
-    } else {
       // Generic charset support
       OutputStreamWriter out = new OutputStreamWriter(outputStream, charset);
       for (String line : arguments) {
@@ -128,7 +123,6 @@ public class ParameterFile {
         out.write('\n');
       }
       out.flush();
-    }
   }
 
   /**

```

**Comment by rikenm1** [comment]
This still happens with Bazel 6.5.0 with JDK 17. We recently just updated our OpenJDK and we are getting this error now. Everything was building fine with OpenJDK 11 prior.

-Azure Linux

**Comment by hvadehra** [comment]
Given https://github.com/bazelbuild/bazel/issues/17103#issuecomment-1991381219 , I'm closing this as obsolete. Please open a fresh issue if you're having still problems building Bazel with jdk 21+.
