### ISSUE TITLE
bazel_windows_example_test is still failling

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1747]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/803/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/console

When I run this test locally, I get #1743.
But on ci, it's failing with following error:
```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "C:/tools/msys64/var/tmp/Bazel/O-AzRGhi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 464
		_tpl(repository_ctx, "CROSSTOOL", {"%{cpu...)})
	File "C:/tools/msys64/var/tmp/Bazel/O-AzRGhi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 466, in _tpl
		_get_windows_crosstool_content(repository_ctx)
	File "C:/tools/msys64/var/tmp/Bazel/O-AzRGhi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 293, in _get_windows_crosstool_content
		_execute(repository_ctx, ["cygpath", "-m", ..."])
	File "C:/tools/msys64/var/tmp/Bazel/O-AzRGhi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 93, in _execute
		auto_configure_fail(result.stderr)
	File "C:/tools/msys64/var/tmp/Bazel/O-AzRGhi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configure_fail
		fail("
%sAuto-Configuration Error:%s ...))

Auto-Configuration Error: java.io.IOException: File handle closed
```

**Comment by meteorcloudy** [comment]
Also saw a similar error here:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=windows-x86_64/804/console
```
[1A[K[31m[1mERROR: [0mC:/jenkins/workspace/Bazel/JAVA_VERSION/1.7/PLATFORM_NAME/windows-x86_64/tools/osx/BUILD:17:1: Executing genrule //tools/osx:xcode-locator-genrule failed: bash failed: error executing command 
  cd C:/bazel_ci/temp/bazel_YQwT2ry2/out/execroot/windows-x86_64
  SET PATH=C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl;C:\python_27_amd64\files
    SET TMPDIR=C:\bazel_ci\temp
  C:/tools/msys64/usr/bin/bash -c source external/bazel_tools/tools/genrule/genrule-setup.sh; cp tools/osx/xcode_locator_stub.sh bazel-out/local-fastbuild/bin/tools/osx/xcode-locator: com.google.devtools.build.lib.shell.AbnormalTerminationException: java.io.IOException: File handle closed.
```

**Comment by meteorcloudy** [comment]
//cc @lberki , Do you think 76b3fb9869af6dac0d872176a2e6aebe55f69c90 has anything to do with this? I couldn't verify it because I am not able to reproduce this error...

**Comment by lberki** [comment]
Yep, sounds like it. Let me send out a change to fix this...

**Comment by meteorcloudy** [comment]
Thanks to @lberki , it is fixed!
