### ISSUE TITLE
bazel-5.3.0 build failure with module java.base does not "opens java.lang" to unnamed module @7586cfea

### ISSUE THREAD

**Issue by nrwahl2** [bazelbuild/bazel#17476]
### Description of the bug:

Bazel completely fails to build. I have never used Bazel before, and I know very little about Java, so I don't know where to begin in debugging this or gathering info.

```
[reid@laptop bazel]$ env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
INFO: Analyzed target //src:bazel_nojdk (369 packages loaded, 10323 targets configured).
INFO: Found 1 target...
[0 / 337] 2 actions, 0 running
    [Prepa] BazelWorkspaceStatusAction stable-status.txt
    [Prepa] Writing file src/main/cpp/client-2.params
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.ExceptionInInitializerError
	at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:118)
	at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:111)
	at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction$ParamFileWriter.writeOutputFile(ParameterFileWriteAction.java:170)
	at com.google.devtools.build.lib.exec.FileWriteStrategy.beginWriteOutputToFile(FileWriteStrategy.java:58)
	at com.google.devtools.build.lib.analysis.actions.FileWriteActionContext.beginWriteOutputToFile(FileWriteActionContext.java:49)
	at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:66)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @7586cfea
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.google.devtools.build.lib.unsafe.StringUnsafe.<init>(StringUnsafe.java:75)
	at com.google.devtools.build.lib.unsafe.StringUnsafe.initInstance(StringUnsafe.java:56)
	at com.google.devtools.build.lib.unsafe.StringUnsafe.<clinit>(StringUnsafe.java:37)
	... 21 more
```

I have both version 11 and version 17 of openjdk installed. Version 17 is the default on my system, but I've tried updating the `/etc/alternatives` symlink to point to version 11. The result is exactly the same.

I've also tried using `--tool_java_runtime_version=remotejdk_11` instead of `=local_jdk`. Same result.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
```

### Which operating system are you running Bazel on?

Fedora 36

### What is the output of `bazel info release`?

N/A, not installed

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
I'm using a release tarball, not a source checkout.
```

### Have you found anything relevant by searching the web?

Yes, this seems almost identical to https://github.com/bazelbuild/bazel/issues/14548, but that issue was fixed in v5.2.0.

**Comment by nrwahl2** [comment]
By the way, I hit the same issue when using the RPM package from the `vbatts/bazel` copr repo with Bazel 5.4.0. In that case, I didn't have to build Bazel, but the `//tensorflow/tools/pip_package:build_pip_package` target failed with the same traceback that's in the description.

**Comment by fmeum** [comment]
This should have already been fixed in Bazel 6.0.0 and higher (https://github.com/bazelbuild/bazel/commit/81e368f0aa1f66f8626bb2423322a4d8a0a152c1). Could you try again with that version?

**Comment by nrwahl2** [comment]
It works (both 5.3.0 and 6.0.0) after updating the whole list of my relevant `/etc/alternatives` to use OpenJDK 11 instead of 17.

It would be really nice for Bazel to support v17, so that I don't have to either leave my alternatives set to 11 or devise a way to override/reset them for Bazel only. However, this is fine for now. I just want to have Bazel working so that I can build TensorFlow.

**Comment by strophy** [comment]
I'm facing a similar problem - looks like support for OpenJDK 17 is coming in Bazel 7.0.0 #14040
