### ISSUE TITLE
IllegalArgumentException raised by cc_configure()

### ISSUE THREAD

**Issue by dubov94** [bazelbuild/bazel#1753]
Hi!

I am trying to utilize cc_configure for creating CROSSTOOL.

My project structure by far is fairly simple:
```
project
----WORKSPACE
----source
     ----fibonacci
          ----fibonacci.h
          ----fibonacci.cc
          ----BUILD
     ----main.cc
````

BUILD:
```
cc_library(
	name = "fibonacci",
	srcs = ["fibonacci.cc"],
	hdrs = ["fibonacci.h"]
)
```

I installed Bazel under Xubuntu 14.04:
```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install bazel
sudo apt-get upgrade bazel
```

WORKSPACE:
```
load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")
cc_configure()
```

But when I try `bazel build source/fibonacci:fibonacci`, I encounter the error:
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/home/user/project]/[WORKSPACE], 2' (requested by nodes 'EXTERNAL_PACKAGE:[/home/user/project]/[WORKSPACE]')
INFO: Elapsed time: 0.299s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/home/user/project]/[WORKSPACE], 2' (requested by nodes 'EXTERNAL_PACKAGE:[/home/user/project]/[WORKSPACE]')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@b3e79dd and @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@b3e79dd
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:190)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:175)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:112)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/home/user/project]/[WORKSPACE], 2' (requested by nodes 'EXTERNAL_PACKAGE:[/home/user/project]/[WORKSPACE]')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@b3e79dd and @bazel_tools//tools/cpp:cc_configure.bzl=com.google.devtools.build.lib.syntax.Environment$Extension@b3e79dd
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:190)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:175)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:112)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
	... 4 more
```

Am I doing something wrong?

**Comment by damienmg** [comment]
Dup of #1469
