### ISSUE TITLE
Killed non-responsive server process

### ISSUE THREAD

**Issue by EthanMacdonald** [bazelbuild/bazel#1754]
I've recently tried installing bazel every which way on OSX 10.10.5

Regardless of the method I use (e.g., brew, installer, from source) I wind up getting some variant of the following error as soon as bazel is called (or sometimes part way through installation):

```
Killed non-responsive server process (pid=4111)
.
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/private/var/tmp/_bazel_EthanMacdonald/7f571a2e1a97af4cd1c685fdb0ac2002/server/jvm.out':
java.lang.VerifyError: class com.google.devtools.build.lib.runtime.proto.InvocationPolicyOuterClass$InvocationPolicy overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.google.devtools.build.lib.runtime.ServerBuilder.<init>(ServerBuilder.java:32)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1059)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:965)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:781)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:726)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

I've Googled all over the place and found a couple similar issues, but ultimately they all seemed to only have error messages that were slightly different or fixes that don't work for me.

**Comment by pcj** [comment]
Not sure if related, but are you on java9?  I've seen other errors that don't look like this one, but there are newer security constraints in java9 that make me wonder if a VerifyError is related.

**Comment by EthanMacdonald** [comment]
Makes sense, but I'm using Java 8 still!

```
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

I also tried doing a clean re-install of the JDK but no dice. :p

**Comment by dslomov** [comment]
This seems to be a protobuf version mismatch, but I am not sure how you got into this stage :(
1) Can you try using bazel with '--batch'?
2) Does compilation from source succeed?

**Comment by EthanMacdonald** [comment]
I have no idea what a protobuf version mismatch is, so this will be interesting! Excuse me while I start googling new words...

The command `bazel --batch` doesn't spit out any errors, so... it doesn't *not* work?

Compiling from source fails every time, unfortunately. :(

**Comment by hermione521** [comment]
Friendly ping @dslomov

**Comment by dslomov** [comment]
Sorry for dropping this on the floor... :(
How does it fail when you compile from source? Can you attach a log (`compile.sh > log`))? (or better still, add  `set -x` to `compile.sh` and then do `compile.sh > log`)

**Comment by dslomov** [comment]
@EthanMacdonald

**Comment by ulfjack** [comment]
We had multiple different versions of the protobuf runtime checked in, and it sometimes accidentally picked up the wrong one. We've removed all of the duplicates, so this should be fixed now.
