### ISSUE TITLE
Multiple circular action dependencies crashes with `java.lang.IllegalStateException: Argument is not Action, TargetCompletion, AspectCompletion, or TestCompletion`

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#17573]
### Description of the bug:

With some combinations of actions and rules, I get this crash instead of the helpful error message:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Argument is not Action, TargetCompletion, AspectCompletion, or TestCompletion: ArtifactNestedSetKey{rawChildren=[File:[[<execution_root>]bazel-out/k8-fastbuild/bin]x, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]x2]}
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.prettyPrint(ActionArtifactCycleReporter.java:67)
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.prettyPrint(ActionArtifactCycleReporter.java:48)
	at com.google.devtools.build.lib.skyframe.AbstractLabelCycleReporter.maybeReportCycle(AbstractLabelCycleReporter.java:110)
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.maybeReportCycle(ActionArtifactCycleReporter.java:31)
	at com.google.devtools.build.skyframe.CyclesReporter.maybeReportCycle(CyclesReporter.java:106)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.processResult(SkyframeErrorProcessor.java:797)
	at com.google.devtools.build.lib.buildtool.SkyframeBuilder.buildArtifacts(SkyframeBuilder.java:161)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:469)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:224)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:530)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:498)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:103)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:608)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:233)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

It's crashing while attempting to print the error. I don't know if the problem is a `File` making it to that code, or if that code should handle printing a `File`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With an empty `WORKSPACE`:
```console
$ cat BUILD
load(":build_rules.bzl", "x", "y")

genrule(
    name = "gen_touch",
    outs = ["touch.sh"],
    cmd = 'echo "#!/bin/bash\nexec touch \\"$@\\"" > $@',
    executable = True,
)

sh_binary(
    name = "touch",
    srcs = ["touch.sh"],
)

x(name = "x")

x(name = "x2")

y(
    name = "y",
    x = [
        ":x",
        ":x2",
    ],
)
$ cat build_rules.bzl 
def _x_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.run(
        inputs = [out],
        outputs = [out],
        executable = "/usr/bin/touch",
        arguments = [out.path],
    )
    return DefaultInfo(files = depset(direct = [out]))

x = rule(implementation = _x_impl)

def _y_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.run(
        inputs = ctx.files.x,
        outputs = [out],
        executable = ctx.executable._touch,
        arguments = [out.path],
    )
    return DefaultInfo(files = depset(direct = [out]))

y = rule(implementation = _y_impl, attrs = {"x": attr.label_list(allow_files = True), "_touch": attr.label(default = Label("//:touch"), executable = True, cfg = "exec")})
$ bazel-7.0.0-pre.20230209.2-linux-x86_64 build :y
INFO: Analyzed target //:y (1 packages loaded, 6 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Argument is not Action, TargetCompletion, AspectCompletion, or TestCompletion: ArtifactNestedSetKey{rawChildren=[File:[[<execution_root>]bazel-out/k8-fastbuild/bin]x, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]x2]}
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.prettyPrint(ActionArtifactCycleReporter.java:67)
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.prettyPrint(ActionArtifactCycleReporter.java:48)
	at com.google.devtools.build.lib.skyframe.AbstractLabelCycleReporter.maybeReportCycle(AbstractLabelCycleReporter.java:110)
	at com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter.maybeReportCycle(ActionArtifactCycleReporter.java:31)
	at com.google.devtools.build.skyframe.CyclesReporter.maybeReportCycle(CyclesReporter.java:106)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeErrorProcessor.processResult(SkyframeErrorProcessor.java:797)
	at com.google.devtools.build.lib.buildtool.SkyframeBuilder.buildArtifacts(SkyframeBuilder.java:161)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:469)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:224)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:530)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:498)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:103)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:608)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:233)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This is the smallest example I can come up with. Both of these seem to be necessary to reproduce:
* Using an executable for the action in `y`
* Having two inputs with circular dependencies

### Which operating system are you running Bazel on?

Debian 11 (bullseye), amd64

### What is the output of `bazel info release`?

`release 7.0.0-pre.20230209.2`, I have also reproduced on `release 5.3.0` and `release 6.0.0`

**Comment by haxorz** [comment]
@joeleba , I was actually thinking that you should take a look at this. The exception's message suggests the bug is in the NSOS area of the codebase. 68765a4a2c259ca48476110aaa1f79469d29a6e0 (authored by @justinhorvitz ; reviewed by @joeleba) was trying to fix internal issue 152958633, which seems really similar to this. So maybe that commit didn't cover all the cases or maybe a new one popped up in between now and then.
