### ISSUE TITLE
Bazel cquery crash on //external:all-targets

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#17608]
### Description of the bug:

Bazel would crash when running `bazel cquery //external:all-targets`:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//external:WORKSPACE, config=null}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:591)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:375)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:254)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1193)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:328)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:245)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:501)
	... 7 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a Bazel repo, run `bazel cquery //external:all-targets`

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.0.0-homebrew

**Comment by gregestren** [comment]
Assigned to @katre for triage.

**Comment by katre** [comment]
This happens with any cquery on `//external`, because the magic `external` package has a source root of `Optional.empty`.

I'm going to keep investigating a fix.

**Comment by katre** [comment]
The crash was added in d0b2d68783c1e23cc6bfa58b709aa8288ca3f6fe, because `ConfiguredTargetFactory` is accessing the source root without checking whether the `Optional` is present.

This crash isn't strictly due to cquery, I'm reassigning to @c-parsons who wrote the commit.

**Comment by c-parsons** [comment]
This is still an issue we'd like to address, just has been deprioritized. At the very least, Bazel should not error with a crash (and stack trace) given such an input.
