### ISSUE TITLE
Exec transition is missing on lcov_merger in sh_test and cc_test

### ISSUE THREAD

**Issue by thirtyseven** [bazelbuild/bazel#17630]
### Description of the bug:

This is basically the same bug as #17568 but for `sh_test` and `cc_test`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Sample workspace: [testrepo.zip](https://github.com/bazelbuild/bazel/files/10856212/testrepo.zip)

```
unzip testrepo.zip
cd testrepo
bazel coverage :ShTest
```

Test output:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:ShTest
-----------------------------------------------------------------------------
GCov does not exist at the given path: ''
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/devtools/coverageoutputgenerator/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.google.testing.coverage.JacocoCoverageRunner.getMainClass(JacocoCoverageRunner.java:321)
        at com.google.testing.coverage.JacocoCoverageRunner.main(JacocoCoverageRunner.java:584)
```

### Which operating system are you running Bazel on?

macOS 13.2.1

### What is the output of `bazel info release`?

6.1.0rc2

**Comment by sgowroji** [comment]
Hi @thirtyseven, Could you please add a Reproducible example for the above issue. Thanks!

**Comment by thirtyseven** [comment]
I have added an example @sgowroji
