### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:cpp-rules-tests is failing on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1765]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/810/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/consoleFull
```
There were 6 failures:
1) testFilesToBuildWithInterfaceSharedObjects(com.google.devtools.build.lib.rules.cpp.CcLibraryConfiguredTargetTest)
java.lang.AssertionError: Not true that <{Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.a, Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.so}> contains exactly <[Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.a, Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.ifso, Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.so]>. It is missing <[Artifact:[[/usr/local/google/_blaze_jrluser/FAKEMD5/workspace]bazel-out/local_windows_msys64-fastbuild/bin]hello/libhello.ifso]>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
	at com.google.common.truth.IterableSubject.failWithBadResultsAndSuffix(IterableSubject.java:370)
	at com.google.common.truth.IterableSubject.containsExactly(IterableSubject.java:321)
	at com.google.common.truth.IterableSubject.containsExactly(IterableSubject.java:244)
	at com.google.devtools.build.lib.rules.cpp.CcLibraryConfiguredTargetTest.testFilesToBuildWithInterfaceSharedObjects(CcLibraryConfiguredTargetTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:90)

```
Culprit is 111006ea81de3cabf1ad30a3fcd83035f8f888a3
I am trying to fix it, but if I can't fix in a short time, we should rollback...
And //cc the author @ulfjack

**Comment by meteorcloudy** [comment]
Actually, I don't think these failing tests should run on Windows, they are testing some "ifso", "so" releated things, maybe we just exclude them? //cc @damienmg @ulfjack

**Comment by damienmg** [comment]
SGTM, mark them with a TODO to add the same kind of coverage test for windows.

**Comment by ulfjack** [comment]
useConfiguration("--cpu=k8") might help?

**Comment by meteorcloudy** [comment]
Ha, I did fix all the tests, Thanks!  So I guess we keep this test class for now? WDYT? @damienmg

**Comment by damienmg** [comment]
Yeah \o/
