### ISSUE TITLE
docker strategy fails to execute when SELinux is enforcing

### ISSUE THREAD

**Issue by nickbreen** [bazelbuild/bazel#17778]
### Description of the bug:

When using [--experimental_enable_docker_sandbox](https://bazel.build/reference/command-line-reference#flag--experimental_enable_docker_sandbox) on a host with SELinux (e.g. Fedora) any volume file access inside the container is denied.

Volume mounts on SELinux systems need the `Z` or `z` volume/mount option specified.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com//nickbreen/bz-platforms

1. run `./images.sh` to build the executor images
2. run `./test.sh` to use the images with the docker sandbox

### Which operating system are you running Bazel on?

Fedora 36

### What is the output of `bazel info release`?

release 6.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label 

### Any other information, logs, or outputs that you want to share?

> Docker version 20.10.21, build baeda1f

> `/usr/bin/docker` provided by `moby-engine-20.10.21-1.fc36.x86_64`

**Comment by nickbreen** [comment]
I think that the mount options from https://github.com/bazelbuild/bazel/blob/844b5d2dbc3ff1dda43d78b81a00c6323e4e8115/src/main/java/com/google/devtools/build/lib/sandbox/DockerCommandLineBuilder.java#L155 should be specified as `:z` 

From memory this option is harmless on non-SELinux systems, but I cannot find a source to back that up.

**Comment by nickbreen** [comment]
It seems that [--experimental_docker_privileged](https://bazel.build/reference/command-line-reference#flag--experimental_docker_privileged) is available as a work-around.

**Comment by nickbreen** [comment]
Also fails with podman with its Docker CLI shim.

[--experimental_docker_privileged](https://bazel.build/reference/command-line-reference#flag--experimental_docker_privileged) does **not** appear to work as a work-around.

**Comment by nickbreen** [comment]
Root cause is that SELinux, by default denies access for containers (container_t) to a user's home directory (home_t) and more specifically the user's XDG_CACHE_DIR (cache_home_t).

Relabeling with `:z` or `:Z` is... not in the spirit of SELinux.

**Comment by nickbreen** [comment]
https://github.com/containers/udica

**Comment by nickbreen** [comment]
The SELinux compliant way to address this is to allow one to [specify the context](https://docs.docker.com/engine/reference/run/#security-configuration) for the container

**Comment by nickbreen** [comment]
Given that `PATH` is searched for the docker executable, we may be able to place a shim script in the right place as a wrapper, exposing the docker binary location as a CLI parameter might be a more-obvious more-easily documentable approach too.

**Comment by nickbreen** [comment]
Testing in progress:

```shell
chcon -t container_type_t -R bazel-out/
```

It takes a very long time, because the output tree is large, but appears to apply the containment type such that the container executor might work...

**Comment by nickbreen** [comment]
This is the error we ultimately get (with `podman`).

Even with `--sandbox_debug` and manually executing the step and (each in isolation):
- using `--security-opt=label=disable`
- appending `:z` for the volume mount

```
Traceback (most recent call last):
  File "/execroot/__main__/bazel-out/k8-opt-exec-4F2F2F5B/bin/external/rules_pkg/pkg/make_rpm.runfiles/rules_pkg/pkg/make_rpm.py", line 524, in <module>
    main(sys.argv[1:])
  File "/execroot/__main__/bazel-out/k8-opt-exec-4F2F2F5B/bin/external/rules_pkg/pkg/make_rpm.runfiles/rules_pkg/pkg/make_rpm.py", line 517, in main
    rpmbuild_args=options.rpmbuild_args)
  File "/execroot/__main__/bazel-out/k8-opt-exec-4F2F2F5B/bin/external/rules_pkg/pkg/make_rpm.runfiles/rules_pkg/pkg/make_rpm.py", line 447, in Build
    self.SaveResult(out_file)
  File "/execroot/__main__/bazel-out/k8-opt-exec-4F2F2F5B/bin/external/rules_pkg/pkg/make_rpm.runfiles/rules_pkg/pkg/make_rpm.py", line 411, in SaveResult
    shutil.copy(self.rpm_path, out_file)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/execroot/__main__/bazel-out/k8-fastbuild/bin/support/scotty/agent-el6/tf-scotty-12345-6789.el6.x86_64.rpm'
```

Note this container is an CentOS6 container: the same error occurs with a RockyLinux8 container (with different python paths).

The error with `docker` is just less verbose (same options appear to have no effect):

```
exec bazel-out/k8-opt-exec-37C21199/bin/external/rules_pkg/pkg/make_rpm: permission denied
```
