### ISSUE TITLE
Missing files from embedded_tools

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1787]
This issue was discovered in tensorflow/tensorflow#4285

The non-GPU TF CI builds with that PR are failing consistently with messages similar to the following:

```
ERROR: package contains errors: bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/install/2ed8c6c819c55073ad03a9309500f9b2/_embedded_binaries/embedded_tools/src/main/protobuf.
ERROR: error loading package 'bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/install/2ed8c6c819c55073ad03a9309500f9b2/_embedded_binaries/embedded_tools/src/main/protobuf': Extension file not found. Unable to load package for '//tools/build_rules:genproto.bzl': BUILD file not found on package path.
```

The error occurs when running `bazel fetch //...` after running `bazel clean --expunge`.

It appears that this error is caused by files, namely `.bzl` files under `//tools/build_rules` that are missing in `embedded_tools`. This can be reproduced by running the following:

```
❯❯❯ bazel fetch @bazel_tools//...
Extracting Bazel installation...
..
ERROR: package contains errors: third_party/jformatstring.
ERROR: error loading package '@bazel_tools//third_party/jformatstring': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file.
```

**Comment by damienmg** [comment]
We should stub out the BUILD file for third_party so bazel query @bazel_tools//... works

**Comment by laszlocsomor** [comment]
This looks like a serious issue. I'm starting to investigate.

**Comment by laszlocsomor** [comment]
Can repro at https://github.com/bazelbuild/bazel/commit/36395c417899bd4009efc3a6cda5ea838f3d98ef:

```
$ bazel fetch @bazel_tools//...
ERROR: package contains errors: third_party/jformatstring.
ERROR: error loading package '@bazel_tools//third_party/jformatstring': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file.

$ cat third_party/jformatstring/BUILD | grep '^load'
load("//tools/build_rules:java_rules_skylark.bzl", "bootstrap_java_library")

$ cat tools/build_rules/java_rules_skylark.bzl | grep 'bootstrap_java_library'
bootstrap_java_library = rule(
```

**Comment by laszlocsomor** [comment]
Something seriously broken:

```
$ bazel query --output=label_kind @bazel_tools//...:*
ERROR: error loading package '@bazel_tools//third_party/jformatstring': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file.

$ echo > third_party/jformatstring/BUILD

$ echo > third_party/checker_framework_javacutil/BUILD 

$ bazel query --output=label_kind @bazel_tools//...:*
ERROR: error loading package '@bazel_tools//third_party/checker_framework_javacutil': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file.
```

**Comment by damienmg** [comment]
Oh yes you are not modifying the source file. bazel_tools point to a directory in the install base

**Comment by laszlocsomor** [comment]
We can properly invalidate if we use a... wait for it... [FilesetEntryFunction](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/FilesetEntryFunction.java) ;) (Or the underlying mechanism, [RecursiveFilesystemTraversalFunction](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/RecursiveFilesystemTraversalFunction.java).)

**Comment by laszlocsomor** [comment]
I think we just have to update [`RepositoryFunction.getRepositoryDirectory`](https://github.com/bazelbuild/bazel/blob/f92ecb3d12a8a966524cda067029dc0aaae409b3/src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryFunction.java#L344) to request a [`RecursiveFilesystemTraversalValue`](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/RecursiveFilesystemTraversalValue.java).

**Comment by laszlocsomor** [comment]
Working a repro case so we can test a bugfix.

**Comment by laszlocsomor** [comment]
More info: apparently not all files are mapped into the local repository. The missing bzl file is there in `tools/build_rules` but not in the symlink tree of the repo.

```
$ bazel fetch @bazel_tools//third_party/jformatstring
ERROR: error loading package '@bazel_tools//third_party/jformatstring': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file.

$ ls tools/build_rules
BUILD  BUILD.tools  genproto.bzl  gensrcjar.sh	java_rules_skylark.bzl	py_rules.bzl  test_rules.bzl

$ ls $(bazel query //external:bazel_tools --output=build | grep path | awk '{print $3}' | sed 's/[",]*//g')/tools/build_rules
BUILD  test_rules.bzl
```

**Comment by laszlocsomor** [comment]
And the BUILD files in the two differ.
Apparently I was wrong about the repo being a symlink tree; it's comprised of regular files.

**Comment by laszlocsomor** [comment]
Found the culprit: [`tools/build_rules:embedded_tools_srcs`](https://github.com/bazelbuild/bazel/blob/19eadbe896b7796233ff15a3741d2ccbbb70f79d/tools/build_rules/BUILD#L15) should have a glob for all bzl files. If I add that and rebuild Bazel then I can fetch `@bazel_tools//third_party/jformatstring` but not `@bazel_tools//...` because some more BUILD files need fixing.

**Comment by damienmg** [comment]
No it should not. Ulf specifically trimmed down that filegroup to only
includes what is necessary in the embedded_tools. If we want to fix that we
should rewrite the BUILD files of the embedded_tools to accept the absence
of the unused files.

**Comment by laszlocsomor** [comment]
Hm, I don't think I follow. What do you mean by rewriting BUILD files "to accept the absence
of the unused files"? Also, when saying "the BUILD files of the embedded_tools" are you referring to `BUILD.tools` files?

**Comment by sulthonzh** [comment]
Same Error, How to solve this? need internal bazel extension , 

ERROR: error loading package 'sms/server': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/docker:docker.bzl': BUILD file not found on package path
ERROR: error loading package 'sms/server': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/docker:docker.bzl': BUILD file not found on package path

**Comment by laszlocsomor** [comment]
@sulthonzh : Can you provide repro instructions or a minimal repro project?

**Comment by asv** [comment]
I have the same problem after define $TMP_TESTDIR on CI server...

```
# bazel test //...
$TEST_TMPDIR defined: output root default is '/app/.bazel-cache' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
........
ERROR: error loading package '.bazel-cache/_bazel_root/8c069df52082beee3c95ca17836fb8e2/install/_embedded_binaries/embedded_tools/third_party/jformatstring': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
INFO: Elapsed time: 4.161s
INFO: 0 processes.
```

**Comment by laszlocsomor** [comment]
@asv : Is your code on GitHub and if so, where? What Bazel version and platform are you using on your CI? Can you repro the issue locally?

**Comment by asv** [comment]
@laszlocsomor

Platform: Ubuntu 17.10 - host system, Debian 9.4 - container system.
Bazel:
```
$ bazel version                
Build label: 0.14.1                                
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar                                                                                                 
Build time: Fri Jun 8 12:17:35 2018 (1528460255)   
Build timestamp: 1528460255                        
Build timestamp as int: 1528460255
```

Tests are run in container on CI.

Yes, I can reproduce this issue locally: https://github.com/asv/bazel-issue

Steps to reproduce:
```
$ docker build -t bazel-issue-env .

# No issue
$ docker run --rm -i -v $(pwd):/app --workdir /app bazel-issue-env bazel test //...

# BUG
$ docker run --rm -i -e TEST_TMPDIR=/app/.bzl-cache -v $(pwd):/app --workdir /app bazel-issue-env bazel test //...
```
NOTICE: if `.bzl-cache` not in a workspace directory bug not reproduce...

**Comment by asv** [comment]
Any updates? Bug is still reproducing even bazel 0.23.2

**Comment by laszlocsomor** [comment]
The repro no longer works with Bazel 0.23.2:
```
  $ git remote get-url origin
https://github.com/asv/bazel-issue

  $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

  $ git rev-parse master
92d375659466db95c2f353a9ca2f201345f60af8

  $ bazel info release
release 0.23.2

  $ bazel test //...
ERROR: /usr/local/google/home/laszlocsomor/stuff/gh-1787/WORKSPACE:15:1: Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/stuff/gh-1787/WORKSPACE", line 15
                container_repositories()
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/io_bazel_rules_docker/container/container.bzl", line 40, in container_repositories
                native.http_file(name = "puller", url = (("https://..."), <2 more arguments>)
type 'struct' has no method http_file()
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.081s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by laszlocsomor** [comment]
I managed to build all with these changes:
```diff
  $ git diff
diff --git a/WORKSPACE b/WORKSPACE
index 4f1f275..582fd22 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -2,23 +2,20 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")                         

 http_archive(
     name = "io_bazel_rules_docker",
-    sha256 = "6dede2c65ce86289969b907f343a1382d33c14fbce5e30dd17bb59bb55bb6593",                              
-    strip_prefix = "rules_docker-0.4.0",
-    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.4.0.tar.gz"],                              
+    strip_prefix = "rules_docker-0.7.0",
+    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],                              
 )

-load(
-    "@io_bazel_rules_docker//container:container.bzl",
-    "container_pull",
-    container_repositories = "repositories",
-)
-container_repositories()
+load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")                                          

 http_archive(
     name = "io_bazel_rules_go",
-    url = "https://github.com/bazelbuild/rules_go/releases/download/0.12.0/rules_go-0.12.0.tar.gz",           
-    sha256 = "c1f52b8789218bb1542ed362c4f7de7052abcf254d865d96fb7ba6d44bc15ee3",                              
+    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",                              
+    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz"],        
 )
-load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")                     
+
+load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")                    
+
 go_rules_dependencies()
+
 go_register_toolchains()
```

**Comment by laszlocsomor** [comment]
I reproed locally without Docker:

```
 $ bazel clean --expunge
(...)

  $ TEST_TMPDIR=$PWD/.foo bazel test -t- //...
(...)
ERROR: error loading package '.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/bazel_skylib': Unable to load file '//:bzl_library.bzl': file doesn't exist
INFO: Elapsed time: 1.947s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading:  ... (105 packages)

  $ TEST_TMPDIR=$PWD/.foo bazel test -t- //...
$TEST_TMPDIR defined: output root default is '/usr/local/google/home/laszlocsomor/stuff/gh-1787/.foo' and max_idle_secs default is '15'.
ERROR: error loading package '.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/install/_embedded_binaries/embedded_tools/tools/build_defs/pkg': Unable to load package for '//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path
INFO: Elapsed time: 0.523s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded)
FAILED: Build did NOT complete successfully (11 packages loaded)
    currently loading: .foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/com_google_protobuf \
... (3 packages)
```

Once there's an output tree under the workspace, Bazel goes nuts.

```
  $ TEST_TMPDIR=$PWD/../.foo bazel test -t- //...
(...)
ERROR: error loading package '.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/install/_embedded_binaries/embedded_tools/third_party/jformatstring': Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
INFO: Elapsed time: 6.929s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded)
FAILED: Build did NOT complete successfully (3 packages loaded)
    currently loading:  ... (7 packages)

  $ bazel test -t- //...
Starting local Bazel server and connecting to it...
ERROR: error loading package '.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/install/_embedded_binaries/embedded_tools/third_party/jformatstring': Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
INFO: Elapsed time: 2.169s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded)
FAILED: Build did NOT complete successfully (9 packages loaded)
    currently loading:  ... (238 packages)

  $ bazel shutdown ; bazel test -t- //...
Starting local Bazel server and connecting to it...
ERROR: error loading package '.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/io_bazel_rules_go/proto': Unable to load package for '//proto:gogo.bzl': BUILD file not found on package path
INFO: Elapsed time: 1.698s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading:  ... (2 packages)

  $ bazel clean --expunge ; bazel test //...
(...)
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/local/google/home/laszlocsomor/stuff/gh-1787/.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/com_github_kevinburke_go_bindata/testdata/symlinkRecursiveParent/symlinkTarget
/usr/local/google/home/laszlocsomor/stuff/gh-1787/.foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/com_github_kevinburke_go_bindata/testdata/symlinkRecursiveParent
[end of symlink chain]
ERROR: Failed to get information about path, for .foo/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/com_github_kevinburke_go_bindata/testdata/symlinkRecursiveParent/symlinkTarget, skipping: Infinite symlink expansion
ERROR: Infinite symlink expansion
INFO: Elapsed time: 1.824s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Only deleting `.foo` helps.

Bazel should error out if TEST_TMPDIR or the output root are under the source tree. See also https://github.com/bazelbuild/bazel/issues/2335.

**Comment by asv** [comment]
Oh, I forgot to update the repro repository. Sorry. Updated. 

I get this error in the repro steps above:
```bash
$ docker build -t bazel-issue-env .
Sending build context to Docker daemon  89.09kB
Step 1/4 : FROM debian:9.4
 ---> 9a5d7185d3a6
Step 2/4 : ADD https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel-0.23.2-linux-x86_64 /usr/local/bin/bazel
Downloading [==================================================>]  146.6MB/146.6MB
 ---> Using cache
 ---> f51022ce58a3
Step 3/4 : RUN chmod +x /usr/local/bin/bazel
 ---> Using cache
 ---> 5cd3ebb3377c
Step 4/4 : RUN apt-get update && apt-get install -y g++ python git
 ---> Using cache
 ---> b69f7269b4cd
Successfully built b69f7269b4cd
Successfully tagged bazel-issue-env:latest
```

```bash
$ docker run --rm -i -e TEST_TMPDIR=/app/.bzl-cache -v $(pwd):/app --workdir /app bazel-issue-env bazel test //...
$TEST_TMPDIR defined: output root default is '/app/.bzl-cache' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
ERROR: error loading package '.bzl-cache/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_docker/testdata': Unable to load package for '//testdata:utils.bzl': BUILD file not found on package path
INFO: Elapsed time: 14.997s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (145 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (145 packages loaded)
```

**Comment by laszlocsomor** [comment]
With latest version:

```
  $ git rev-parse HEAD
0cb2365978e0de7fe362724726e3271440ddd785

  $ bazel test //...
(...)
//:go_default_test                                                       PASSED in 0.1s

  $ TEST_TMPDIR=$PWD/.bzl-cache bazel test //...
(...)
ERROR: error loading package 'bazel-gh-1787/.bzl-cache/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/bazel_tools/tools/cpp': in /usr/local/google/home/laszlocsomor/stuff/gh-1787/bazel-gh-1787/.bzl-cache/_bazel_laszlocsomor/01d3126b99f53b5f3d8111819a05a7a7/external/bazel_tools/tools/cpp/compiler_flag.bzl: Unable to load package for '//tools/cpp:toolchain_utils.bzl': BUILD file not found on package path
INFO: Elapsed time: 9.234s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (406 packages loaded)
FAILED: Build did NOT complete successfully (406 packages loaded)
    currently loading:  ... (503 packages)
```

I stand by my diagnosis:

> Bazel should error out if TEST_TMPDIR or the output root are under the source tree. See also #2335.

**Comment by meisterT** [comment]
I am attempting a fix in https://github.com/bazelbuild/bazel/pull/11404
