### ISSUE TITLE
[Question]Is there a method to force upload local cache to remote cache

### ISSUE THREAD

**Issue by hxndg** [bazelbuild/bazel#17885]
Hello, We are facing a awkward problem.
We have CI context and office context which are separated, while CI hold buildfarm to compile, and  office use remote-cache.

So We setup a computer which can contact with CI buildfarm and office remote-cache, We set it config to use remote_executor buildfarm to perform compile job, after all compile job is done,  restart the build job while change setting to use remote_cache point to office remote cache , so that it can upload the artifacts to remote cache,

But if we start the second build job, it just find the cache result and never update to remote cache

Is there any method to force bazel upload it's local compiled cache to office remote cache? 

PS I Tried setting remote_cache and remote_executor at the same time ,it just report below error

```
(16:22:20) ERROR: /builds/pzaznihD/0/root/qcraft/onboard/base/BUILD:63:17: Action onboard/base/build_info.cc failed: (Exit 34): Remote Execution Failure:
Failed Precondition: Action bed7a8e3bd13964544601dd461c65702c89eeb5d42dc22431bff14b3c3e533a1/144 is invalid: The action was not found in the CAS..
  Precondition Failure:
    (MISSING) blobs/bed7a8e3bd13964544601dd461c65702c89eeb5d42dc22431bff14b3c3e533a1/144: The action was not found in the CAS.

java.io.IOException: com.google.devtools.build.lib.remote.ExecutionStatusException: FAILED_PRECONDITION: Action bed7a8e3bd13964544601dd461c65702c89eeb5d42dc22431bff14b3c3e533a1/144 is invalid: The action was not found in the CAS..
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:235)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.executeRemotely(RemoteExecutionService.java:1394)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:269)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:244)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.devtools.build.lib.remote.ExecutionStatusException: FAILED_PRECONDITION: Action bed7a8e3bd13964544601dd461c65702c89eeb5d42dc22431bff14b3c3e533a1/144 is invalid: The action was not found in the CAS..
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.handleStatus(GrpcRemoteExecutor.java:71)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.getOperationResponse(GrpcRemoteExecutor.java:83)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$2(GrpcRemoteExecutor.java:194)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$3(GrpcRemoteExecutor.java:140)
	at com.google.devtools.build.lib.remote.util.Utils.refreshIfUnauthenticated(Utils.java:537)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:138)
	... 27 more
```

**Comment by tjgq** [comment]
No, it's not possible to ask Bazel to upload build outputs already in the output tree into a remote cache. In addition, pointing `--remote_cache` to a separate cache than the one used by `--remote_executor` won't work; a remote execution service has its own cache and expects to find the artifacts there.

I think this problem is better solved outside of Bazel (e..g. have a service that keeps the two caches in sync, or route the requests through a caching proxy).
