### ISSUE TITLE
Crash when applying patch to external repository

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel#17897]
### Description of the bug:

```
(19:26:10) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_github_abc' (requested by nodes 'PACKAGE_LOOKUP:@com_github_abc//')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:642)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IndexOutOfBoundsException thrown during Starlark evaluation (LOADING)
        at <starlark>.patch(<builtin>:0)
        at <starlark>.patch(/private/var/tmp/_bazel_thomas/d95eb470615df18f91feffc144a9a015/external/bazel_tools/tools/build_defs/repo/utils.bzl:167)
        at <starlark>._http_archive_impl(/private/var/tmp/_bazel_thomas/d95eb470615df18f91feffc144a9a015/external/bazel_tools/tools/build_defs/repo/http.bzl:143)
Caused by: java.lang.IndexOutOfBoundsException: Index 15096 out of bounds for length 15096
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at com.github.difflib.patch.Chunk.verify(Chunk.java:72)
        at com.github.difflib.patch.AbstractDelta.verifyChunk(AbstractDelta.java:57)
        at com.github.difflib.patch.ChangeDelta.applyTo(ChangeDelta.java:43)
        at com.google.devtools.build.lib.bazel.repository.PatchUtil.applyDelta(PatchUtil.java:149)
        at com.google.devtools.build.lib.bazel.repository.PatchUtil.applyTo(PatchUtil.java:103)
        at com.google.devtools.build.lib.bazel.repository.PatchUtil.applyOffsetPatchTo(PatchUtil.java:90)
        at com.google.devtools.build.lib.bazel.repository.PatchUtil.applyPatchToFile(PatchUtil.java:303)
        at com.google.devtools.build.lib.bazel.repository.PatchUtil.apply(PatchUtil.java:648)
        at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryContext.patch(StarlarkRepositoryContext.java:399)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
        at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
        at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
        at net.starlark.java.eval.Eval.eval(Eval.java:497)
        at net.starlark.java.eval.Eval.exec(Eval.java:271)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execFor(Eval.java:126)
        at net.starlark.java.eval.Eval.exec(Eval.java:276)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execIf(Eval.java:205)
        at net.starlark.java.eval.Eval.exec(Eval.java:283)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
        at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
        at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
        at net.starlark.java.eval.Eval.eval(Eval.java:497)
        at net.starlark.java.eval.Eval.exec(Eval.java:271)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
        at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
        at net.starlark.java.eval.Starlark.call(Starlark.java:604)
        at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:220)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:413)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:344)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure, it could be important to note the external repository is a Bazel projects.

### Which operating system are you running Bazel on?

macOS aarch64

### What is the output of `bazel info release`?

release 6.1.1

**Comment by kshyanashree** [comment]
Hi @uhthomas! Could you please provide the steps to reproduce the above issue with code repo. Thanks!

**Comment by kshyanashree** [comment]
> Yep, here you go @kshyanashree.
> 
> https://github.com/uhthomas/bazel-17897
> 
> It looks like it crashes if the patch is bad. In this case, the original file had an extra newline when it shouldn't have, which is why there is a lone `-` at the end of the diff.

Thanks for the information!

**Comment by meteorcloudy** [comment]
```
      at java.base/java.util.ArrayList.get(Unknown Source)
        at com.github.difflib.patch.Chunk.verify(Chunk.java:72)
        at com.github.difflib.patch.AbstractDelta.verifyChunk(AbstractDelta.java:57)
        at com.github.difflib.patch.ChangeDelta.applyTo(ChangeDelta.java:43)
```

This is actually a bug in the java-diff-utils library, the problem is probably fixed in the latest version (4.12) by https://github.com/java-diff-utils/java-diff-utils/pull/125, but upgrading to this version failed due to some function are no longer public:
```
src/main/java/com/google/devtools/build/lib/bazel/repository/PatchUtil.java:149: error: applyTo(List<T>) has protected access in AbstractDelta
      delta.applyTo(result);
           ^
  where T is a type-variable:
    T extends Object declared in class AbstractDelta
Target //src:bazel failed to build
```
Refactoring the PatchUtil.java class to adapt the change isn't trivial, I guess what we can do in short term is to catch this error and through a better error message instead of just crashing.

**Comment by meteorcloudy** [comment]
OK, turns out https://github.com/java-diff-utils/java-diff-utils/pull/125 adds fuzzy match which also support apply the patch with an offset, this actually removes the need to call the `applyTo` function from `AbstractDelta`. I guess we can upgrade java-diff-utils version to solve this problem, the only problem is that we also need to upgrade the Google internal one, which may take some time.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/5c843397d9f2da548ec5f5b4a75b4be74b42df74 didn't fix the issue
```
ERROR: /usr/local/google/home/pcloudy/workspace/tmp_repos/bazel-17897/WORKSPACE:3:13: fetching http_archive rule //external:com_github_sourcegraph_sourcegraph: Traceback (most recent call last):
	File "/usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/bd7b498f5fd49e1954631059835dd016/external/bazel_tools/tools/build_defs/repo/http.bzl", line 150, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/bd7b498f5fd49e1954631059835dd016/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 174, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Error applying patch /usr/local/google/home/pcloudy/workspace/tmp_repos/bazel-17897/com_github_sourcegraph_sourcegraph.patch: in patch applied to /usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/bd7b498f5fd49e1954631059835dd016/external/com_github_sourcegraph_sourcegraph/README.md: could not apply patch due to CONTENT_DOES_NOT_MATCH_TARGET
```

**Comment by meteorcloudy** [comment]
Oh, it did solve the crashing issue, although the error message isn't very understandable.

**Comment by meteorcloudy** [comment]
Reopen to track https://github.com/kythe/kythe/issues/5864#issuecomment-1749349358
