### ISSUE TITLE
IJ plugin: Network shouldn't be accessed in EDT or inside read action

### ISSUE THREAD

**Issue by benol** [bazelbuild/bazel#1815]
Here's an exception I got when using the IntelliJ plugin with 2016.3 EAP.

```
Assertion failed: Network shouldn't be accessed in EDT or inside read action
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:372)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:246)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:74)
	at com.google.idea.blaze.base.experiments.WebExperimentSyncer$WebExperimentsDownloader.call(WebExperimentSyncer.java:130)
	at com.google.idea.blaze.base.experiments.WebExperimentSyncer$WebExperimentsDownloader.call(WebExperimentSyncer.java:123)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:61)
	at com.google.idea.blaze.base.experiments.WebExperimentSyncer.initialize(WebExperimentSyncer.java:99)
	at com.google.idea.blaze.base.experiments.WebExperimentSyncer.getExperimentValues(WebExperimentSyncer.java:83)
	at com.google.idea.blaze.base.experiments.WebExperimentLoader.getExperiments(WebExperimentLoader.java:26)
	at com.google.idea.blaze.base.experiments.ExperimentServiceImpl.reloadExperiments(ExperimentServiceImpl.java:69)
	at com.google.idea.blaze.base.experiments.ExperimentServiceImpl.getExperiment(ExperimentServiceImpl.java:110)
	at com.google.idea.blaze.base.experiments.ExperimentServiceImpl.getExperiment(ExperimentServiceImpl.java:87)
	at com.google.idea.blaze.base.experiments.BoolExperiment.getValue(BoolExperiment.java:32)
	at com.google.idea.blaze.base.lang.buildfile.parser.BuildParserDefinition$BuildParser.parse(BuildParserDefinition.java:108)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:169)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.findReparseableRoots(BlockSupportImpl.java:114)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:89)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:802)
	at com.intellij.psi.impl.DocumentCommitThread$6.run(DocumentCommitThread.java:569)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:597)
	at com.intellij.psi.impl.DocumentCommitThread.access$300(DocumentCommitThread.java:77)
	at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:398)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:395)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:346)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benol** [comment]
Sorry, I just noticed that there's a separate GitHub repo for the IJ plugin.
