### ISSUE TITLE
Windows: Path.relativeTo is unaware of Windows paths

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1827]
```
$ bazel --batch info --client_cwd=${PWD}
java.lang.IllegalArgumentException: Path /c/work/bazel2 is not beneath C:/work/bazel2
        at com.google.devtools.build.lib.vfs.Path.relativeTo(Path.java:726)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.beforeCommand(CommandEnvironment.java:480)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:480)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:723)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:531)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
java.lang.IllegalArgumentException: Path /c/work/bazel2 is not beneath C:/work/bazel2
        at com.google.devtools.build.lib.vfs.Path.relativeTo(Path.java:726)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.beforeCommand(CommandEnvironment.java:480)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:480)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:723)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:531)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

**Comment by dslomov** [comment]
I bet 
`$ bazel --batch info --clien_cwd=$(cygpath -w ${PWD})`
works. I.e. we only allow Windows paths.

**Comment by laszlocsomor** [comment]
Probably yes, but I think that's only symptomatic treatment. There's nothing preventing the user from passing a Unix-style path.

On top of that the uncaught ISE is bad in its own right.

**Comment by laszlocsomor** [comment]
This is superseded by https://github.com/bazelbuild/bazel/issues/1463, fixing that fixes this one too.
