### ISSUE TITLE
HttpCacheClient.uploadAsync can dead-lock itself via HttpCacheClient.close

### ISSUE THREAD

**Issue by alexofortune** [bazelbuild/bazel#18296]
### Description of the bug:

While debugging our build probing setup, we noticed that in some ( very rare ) cases, Bazel can enter some kind of a zombie state where no commands work until the server is hard shut down.

Thread dump from bazel client indicated a hanging grpc command towards the server, and server indeed had a hanging grpc command execution due to inability to close `BlockWaitingModule` executor. I looked for other operations on that executor and found this:

```
"block-waiting-0" #32642 prio=5 os_prio=0 cpu=0.23ms elapsed=3494.97s tid=0x00007f7864426000 nid=0x38bd03 in Object.wait()  [0x00007f77d1cfe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.6/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.6/Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:253)
        - waiting to re-lock in wait() <0x00000007429aa490> (a io.netty.util.concurrent.DefaultPromise)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:35)
        at io.netty.channel.pool.FixedChannelPool.close(FixedChannelPool.java:451)
        at com.google.devtools.build.lib.remote.http.HttpCacheClient.close(HttpCacheClient.java:736)
        - locked <0x00000007429aa4f8> (a java.lang.Object)
        at com.google.devtools.build.lib.remote.disk.DiskAndRemoteCacheClient.close(DiskAndRemoteCacheClient.java:72)
        at com.google.devtools.build.lib.remote.RemoteCache.deallocate(RemoteCache.java:429)
        at io.netty.util.AbstractReferenceCounted.handleRelease(AbstractReferenceCounted.java:86)
        at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
        at com.google.devtools.build.lib.remote.RemoteActionContextProvider.afterCommand(RemoteActionContextProvider.java:226)
        at com.google.devtools.build.lib.remote.RemoteModule.afterCommandTask(RemoteModule.java:821)
        at com.google.devtools.build.lib.remote.RemoteModule.lambda$afterCommand$1(RemoteModule.java:799)
        at com.google.devtools.build.lib.remote.RemoteModule$$Lambda$393/0x000000080053d040.call(Unknown Source)
        at com.google.devtools.build.lib.runtime.BlockWaitingModule.lambda$submit$0(BlockWaitingModule.java:73)
        at com.google.devtools.build.lib.runtime.BlockWaitingModule$$Lambda$394/0x000000080053d440.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.6/Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@11.0.6/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/Unknown Source)
        at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

Since it clearly seems to not be able to close the HttpCacheClient, I looked for another thread that is working with it and surely enough - I found something. The thread below is calling uploadAsync ( which acquires `channelPool` ), which upon completion somehow manages to do `RemoteCache.deallocate` which in turn tries to do `HttpCacheClient.close()` - while still being inside `uploadAsync` lambda ( so `channelPool` is stil acquired ):
   
```
"nioEventLoopGroup-123-1" #32045 prio=10 os_prio=0 cpu=79670.64ms elapsed=426629.34s tid=0x00007f781c23e800 nid=0x8cf34 in Object.wait()  [0x00007f77a39fd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.6/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.6/Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:253)
        - waiting to re-lock in wait() <0x000000073ff4c138> (a io.netty.util.concurrent.PromiseTask)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:35)
        at io.netty.channel.pool.FixedChannelPool.close(FixedChannelPool.java:451)
        at com.google.devtools.build.lib.remote.http.HttpCacheClient.close(HttpCacheClient.java:736)
        - locked <0x00000006d0ac2bd0> (a java.lang.Object)
        at com.google.devtools.build.lib.remote.disk.DiskAndRemoteCacheClient.close(DiskAndRemoteCacheClient.java:72)
        at com.google.devtools.build.lib.remote.RemoteCache.deallocate(RemoteCache.java:429)
        at io.netty.util.AbstractReferenceCounted.handleRelease(AbstractReferenceCounted.java:86)
        at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
        at com.google.devtools.build.lib.remote.RemoteExecutionService$$Lambda$903/0x00000008007ea040.accept(Unknown Source)
        at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:143)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:112)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onComplete(CompletableToSingle.java:67)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:85)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.onComplete(CompletableDoFinally.java:78)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:65)
        at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:85)
        at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:82)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
        at com.google.devtools.build.lib.remote.util.RxFutures$1.onComplete(RxFutures.java:211)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:65)
        at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:85)
        at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:82)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
        at com.google.devtools.build.lib.remote.http.HttpCacheClient.lambda$uploadAsync$10(HttpCacheClient.java:612)
        at com.google.devtools.build.lib.remote.http.HttpCacheClient$$Lambda$937/0x0000000800805c40.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:78)
        at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:73)
        at com.google.devtools.build.lib.remote.http.HttpUploadHandler.channelRead0(HttpUploadHandler.java:83)
        at com.google.devtools.build.lib.remote.http.HttpUploadHandler.channelRead0(HttpUploadHandler.java:40)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

This leads to a dead-lock as `channelPool` will never close.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No easy way other than build continuously a lot of code - this seems to rely on very subtle timing. Hopefully thread dumps will be enough to diagnose.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.1.0

### Have you found anything relevant by searching the web?

Nothing

### Any other information, logs, or outputs that you want to share?

See bug description.

**Comment by alexofortune** [comment]
Digged a bit more into heap dump and to give more clarity - All relevant classes ( `RemoteCache`, `HttpCacheClient` etc. ) are not shared between those two threads, they are completely separate. It seems to me that the `HttpCacheClient` and `FixedChannelPool` that block `BlockWaitingModule` are actually perfectly healthy, my hypothesis after reading `FixedChannelPool` 's code is that it simply is not able to close because internally, netty is implementing close as `closeAsync.await()`, and that one is scheduling onto a single-threaded executor that is blocked by the other unhealthy Channel Pool due to deadlock mentioned in original issue message.

I found this executor which seems to confirm it, but I need to dig more to be 100% sure:

```
"globalEventExecutor-2-159" #32182 prio=5 os_prio=0 cpu=0.18ms elapsed=426190.39s tid=0x00007f7788e5b000 nid=0x93ceb in Object.wait()  [0x00007f77a4bfe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.6/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.6/Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
        - waiting to re-lock in wait() <0x0000000xd6c2e49b20> (a io.netty.channel.DefaultChannelPromise)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
        at io.netty.channel.pool.SimpleChannelPool.close(SimpleChannelPool.java:408)
        at io.netty.channel.pool.FixedChannelPool.access$1301(FixedChannelPool.java:42)
        at io.netty.channel.pool.FixedChannelPool$6.call(FixedChannelPool.java:512)
        at io.netty.channel.pool.FixedChannelPool$6.call(FixedChannelPool.java:509)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

**Comment by alexofortune** [comment]
Thanks @coeuvre !
