### ISSUE TITLE
How can i solve this probelm

### ISSUE THREAD

**Issue by xiaobai0102** [bazelbuild/bazel#18375]
### Description of the bug:

Traceback (most recent call last):
  File "/home/whoami/.cache/bazel/_bazel_whoami/085bcd6af4a7f7f89d6a65e75a71d38f/sandbox/linux-sandbox/1609/execroot/org_onosproject_onos/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/build/bazel/onos_app_tools.runfiles/org_onosproject_onos/tools/build/bazel/onos_app_tools.py", line 241, in <module>
    **values))
  File "/home/whoami/.cache/bazel/_bazel_whoami/085bcd6af4a7f7f89d6a65e75a71d38f/sandbox/linux-sandbox/1609/execroot/org_onosproject_onos/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/build/bazel/onos_app_tools.runfiles/org_onosproject_onos/tools/build/bazel/onos_app_tools.py", line 154, in write
    file.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)
----------------
Note: The failure of target //tools/build/bazel:onos_app_tools (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
1683809064.817413779: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1683809064.817441501: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1683809064.862657778: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //:onos failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 162.346s, Critical Path: 66.77s
INFO: 219 processes: 3 internal, 213 linux-sandbox, 3 worker.

**Comment by Wyverald** [comment]
![image](https://github.com/bazelbuild/bazel/assets/453203/44539c76-189d-474b-a76d-c727fd93d30a)
