### ISSUE TITLE
Windows, native: envvars are case-insensitive

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1842]
Just like paths, environment variables are case-insensitive.
This causes trouble when running _not_ under msys but under cmd.exe [1]:

```
C:\work\bazel2\bzl>java -XX:+HeapDumpOnOutOfMemoryError -Xverify:none -Dfile.encoding=ISO-8859-1 -Djava.util.logging.config.file="C:\work\bazel2\bzl\javalog.properties" -Dio.bazel.EnableJni=1 -Djava.library.path="C:\work\bazel2\bzl\_embedded_binaries" -jar "C:/work/bazel2/bzl/libblaze.jar" --batch --install_base="C:\work\bazel2\bzl" --output_base="C:\work\bazel2\bzl\out" --install_md5= --workspace_directory="c:/work/bazel2" --nofatal_event_bus_exceptions --host_jvm_debug build --ignore_unsupported_sandboxing --startup_time=329 --extract_data_time=523 --rc_source=/dev/null --isatty=1 --ignore_client_env --client_cwd="c:/work/bazel2" --java_toolchain="//src/java_tools/buildjar:bootstrap_toolchain" --host_java_toolchain="//src/java_tools/buildjar:bootstrap_toolchain" --strategy=Javac=worker --worker_quit_after_build --ignore_unsupported_sandboxing --color=no --curses=no --show_timestamps --verbose_failures --javacopt="-g -source 1.8 -target 1.8" "src:bazel"
WARNING: (09-27 18:16:26.934) C:/work/bazel2/bzl/out/external/bazel_tools/WORKSPACE:1: Workspace name in C:/work/bazel2/bzl/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
____(09-27 18:16:26.990) Loading package: src
____(09-27 18:16:27.096) Loading...
____(09-27 18:16:27.176) Loading package: @local_config_xcode//
____(09-27 18:16:27.279) Loading package: @local_jdk//
WARNING: (09-27 18:16:27.331) C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start looking for python in PATH.
.
ERROR: (09-27 18:16:27.384) in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 451
                _find_python(repository_ctx)
        File "C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 377, in _find_python
                _which_cmd(repository_ctx, "python.exe", "C:\Py...")
        File "C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 81, in _which_cmd
                _get_env_var(repository_ctx, "PATH")
        File "C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 67, in _get_env_var
                auto_configure_fail("'%s' environment variable is no...)
        File "C:/work/bazel2/bzl/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configure_fail
                fail("
%sAuto-Configuration Error:%s ...))

Auto-Configuration Error: 'PATH' environment variable is not set
.
____(09-27 18:16:27.427) Elapsed time: 1.231s
```

The reason we see the error above is that the envvar is `Path`, not `PATH`. `cmd.exe` treats those as the same, but Bazel doesn't.

[1] as of 2016/09/27 this is only possible if you copy `libblaze.jar` as built by `compile.sh` (need to fiddle with the script not to delete the bootstrapping outputs), and run it like [`scripts/bootstrap/compile.sh:run_bazel_jar()`](https://github.com/bazelbuild/bazel/blob/a5b226942bd8e7667e8da7067ec9bf55d1d62508/scripts/bootstrap/compile.sh#L305) does

**Comment by laszlocsomor** [comment]
Assigning this to @dslomov who agreed to work on it. Thanks!

**Comment by laszlocsomor** [comment]
Closing this issue, was fixed in https://github.com/bazelbuild/bazel/commit/4950111c591f5d7352c83898e35a5f18ff92a0cc.
