### ISSUE TITLE
Windows, native: windows paths may be mistaken for escaped strings

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1843]
When running from cmd.exe instead of msys [1], if for example `--install_base` points to `"c:\foo\bar\"`, then Bazel crashes with a NPE, because the option parser believes the second `"` is escaped and keeps reading until the next "unescaped" one:

```
C:\work\bazel2\bzl>java -XX:+HeapDumpOnOutOfMemoryError -Xverify:none -Dfile.encoding=ISO-8859-1 -Djava.util.logging.config.file="C:\work\bazel2\bzl\javalog.properties" -Dio.bazel.EnableJni=1 -Djava.library.path="C:\work\bazel2\bzl\_embedded_binaries" -jar "C:/work/bazel2/bzl/libblaze.jar" --batch --install_base="C:\work\bazel2\bzl\" --output_base="C:\work\bazel2\bzl\out" --install_md5= --workspace_directory="c:/work/bazel2" --nofatal_event_bus_exceptions --host_jvm_debug build --ignore_unsupported_sandboxing --startup_time=329 --extract_data_time=523 --rc_source=/dev/null --isatty=1 --ignore_client_env --client_cwd="c:/work/bazel2" --java_toolchain="//src/java_tools/buildjar:bootstrap_toolchain" --host_java_toolchain="//src/java_tools/buildjar:bootstrap_toolchain" --strategy=Javac=worker --worker_quit_after_build --ignore_unsupported_sandboxing --color=no --curses=no --show_timestamps --verbose_failures --javacopt="-g -source 1.8 -target 1.8" "src:bazel"
java.lang.NullPointerException
        at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:86)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:931)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:714)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:535)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

If you remove the trailing `\` from `--install_base`'s path, then it works (and fails with #1842).

[1] as of 2016/09/27 this is only possible if you copy `libblaze.jar` as built by `compile.sh` (need to fiddle with the script not to delete the bootstrapping outputs), and run it like [`scripts/bootstrap/compile.sh:run_bazel_jar()`](https://github.com/bazelbuild/bazel/blob/a5b226942bd8e7667e8da7067ec9bf55d1d62508/scripts/bootstrap/compile.sh#L305) does

**Comment by laszlocsomor** [comment]
This is not a problem when running from cmd.exe

**Comment by laszlocsomor** [comment]
msys-less version is the default since long ago (0.5 or 0.6), this is obsolete
