### ISSUE TITLE
Internal crash issue with JNI

### ISSUE THREAD

**Issue by Shams1363** [bazelbuild/bazel#18644]
### Description of the bug:

When I build with bazel and set up a toolchain, I receive the following error message. It is originated from JNI:
FATAL: bazel crashed due to an internal error. Printing stack trace:
net.starlark.java.eval.Starlark$UncheckedEvalError: ExceptionInInitializerError thrown during Starlark evaluation (LOADING)
	at <starlark>.download_and_extract(<builtin>:0)
	at <starlark>._http_archive_impl([PATHbazel_tools/tools/build_defs/repo/http.bzl:132)
Caused by: java.lang.ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.2-3: Permission denied
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(Unknown Source)
	at com.github.luben.zstd.util.Native.load(Native.java:99)
	at com.github.luben.zstd.util.Native.load(Native.java:55)
	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
	at com.google.devtools.build.lib.bazel.repository.TarZstFunction.getDecompressorStream(TarZstFunction.java:34)
	at com.google.devtools.build.lib.bazel.repository.CompressedTarFunction.decompress(CompressedTarFunction.java:56)
	at com.google.devtools.build.lib.bazel.repository.DecompressorValue.decompress(DecompressorValue.java:126)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkBaseExternalContext.downloadAndExtract(StarlarkBaseExternalContext.java:720)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
	at net.starlark.java.eval.Eval.eval(Eval.java:497)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:109)
	at net.starlark.java.eval.Eval.exec(Eval.java:268)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
	at net.starlark.java.eval.Starlark.call(Starlark.java:604)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:220)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:413)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:344)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by tjgq** [comment]
The zstd JNI is extracted to whatever directory the `java.io.tmpdir` system property points to (usually `/tmp` on Linux) -see the `load` method in https://github.com/luben/zstd-jni/blob/v1.5.2-3/src/main/java/com/github/luben/zstd/util/Native.java). Can you verify that that directory is writable?

(Also, please let us know which OS and Bazel version you're running, otherwise it's hard to debug further.)
