### ISSUE TITLE
NPE when building with --profile on Linux on 0.3.2rc2

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1865]
Reported by mail:

```
Unhandled exception thrown during build; message: Unrecoverable error
while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode'
(requested by nodes 'REPOSITORY:@local_config_xcode')
INFO: Elapsed time: 1.924s
java.lang.RuntimeException: Unrecoverable error while evaluating node
'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes
'REPOSITORY:@local_config_xcode')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:447)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception while processing
@SkylarkSignature.Param executable, default value True
        at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:185)
        at com.google.devtools.build.lib.syntax.FuncallExpression.convertArgumentList(FuncallExpression.java:480)
        at com.google.devtools.build.lib.syntax.FuncallExpression.findJavaMethod(FuncallExpression.java:384)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:706)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:759)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
        at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
        at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
        at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:100)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:129)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:388)
        ... 4 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
        at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:731)
        at com.google.devtools.build.lib.profiler.Profiler.logSimpleTask(Profiler.java:780)
        at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:114)
        at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:123)
        at com.google.devtools.build.lib.syntax.Parser.parseFileForSkylark(Parser.java:235)
        at com.google.devtools.build.lib.syntax.BuildFileAST.parseSkylarkString(BuildFileAST.java:333)
        at com.google.devtools.build.lib.syntax.Environment.eval(Environment.java:953)
        at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:183)
        ... 17 more
java.lang.RuntimeException: Unrecoverable error while evaluating node
'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes
'REPOSITORY:@local_config_xcode')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:447)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception while processing
@SkylarkSignature.Param executable, default value True
        at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:185)
        at com.google.devtools.build.lib.syntax.FuncallExpression.convertArgumentList(FuncallExpression.java:480)
        at com.google.devtools.build.lib.syntax.FuncallExpression.findJavaMethod(FuncallExpression.java:384)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:706)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:759)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
        at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
        at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
        at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:100)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:129)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:388)
        ... 4 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
        at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:731)
        at com.google.devtools.build.lib.profiler.Profiler.logSimpleTask(Profiler.java:780)
        at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:114)
        at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:123)
        at com.google.devtools.build.lib.syntax.Parser.parseFileForSkylark(Parser.java:235)
        at com.google.devtools.build.lib.syntax.BuildFileAST.parseSkylarkString(BuildFileAST.java:333)
        at com.google.devtools.build.lib.syntax.Environment.eval(Environment.java:953)
        at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:183)
        ... 17 more

```

**Comment by damienmg** [comment]
Why wasn't this cherry-picked in the release?
