### ISSUE TITLE
Bazel build failure for Tensorflow while building from source

### ISSUE THREAD

**Issue by sskgit** [bazelbuild/bazel#1871]
While creating Tensorflow build from the source bazel build repeatedly fails.

I am trying Tensoflow from the source and receive build error for 
a) C++ compilation of rule '@grpc//:gpr' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc

b) ERROR: I/O error while writing action log: No space left on device.

Enviornment:

Cuda 8.0
CuDNN 5
Ubuntu 16.04
bazel 0.31
Nvidia K80
Azure VM N6 (56 GB Memory)

Tried ./configure and build several times. Configure is successful but build fails.

Also tried, bazel clean, bazel clean --expunge and ran the build with reduced number of jobs
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

but the error continues..

Looked at this thread and also

#190

https://github.com/tensorflow/tensorflow/issues/4105

Here is the full error message:

52adb8ea4f53b1b72067611e8a7eb020/external/grpc/BUILD:69:1: C++ compilation of rule '@grpc//:gpr' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ERROR: I/O error while writing action log: No space left on device.
java.util.logging.ErrorManager: 2
java.io.IOException: No space left on device
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.util.logging.FileHandler$MeteredStream.flush(FileHandler.java:196)
at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
at java.util.logging.StreamHandler.flush(StreamHandler.java:259)
at java.util.logging.FileHandler.publish(FileHandler.java:683)
at java.util.logging.Logger.log(Logger.java:738)
at java.util.logging.Logger.doLog(Logger.java:765)
at java.util.logging.Logger.log(Logger.java:788)
at java.util.logging.Logger.info(Logger.java:1489)
at com.google.devtools.build.lib.profiler.AutoProfiler$LoggingElapsedTimeReceiver.accept(AutoProfiler.java:315)
at com.google.devtools.build.lib.profiler.AutoProfiler$SequencedElapsedTimeReceiver.accept(AutoProfiler.java:262)
at com.google.devtools.build.lib.profiler.AutoProfiler.completeAndGetElapsedTimeNanos(AutoProfiler.java:226)
at com.google.devtools.build.lib.buildtool.ExecutionTool.saveCaches(ExecutionTool.java:725)
at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:470)
at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:201)
at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:333)
at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)

============

Update 1:

df
Filesystem 1K-blocks Used Available Use% Mounted on
udev 28837212 0 28837212 0% /dev
tmpfs 5771196 9244 5761952 1% /run
/dev/sda1 29711408 29329736 365288 99% /
tmpfs 28855968 0 28855968 0% /dev/shm
tmpfs 5120 0 5120 0% /run/lock
tmpfs 28855968 0 28855968 0% /sys/fs/cgroup
none 64 0 64 0% /etc/network/interfaces.dynamic.d
/dev/sdb1 356513788 135524 356378264 1% /mnt
tmpfs 5771196 0 5771196 0% /run/user/1000

It shows mounted on / has almost no space, and I think $VM/Username (i.e. $HOME) is on the same mount /, as there is no $HOME mounted on, in the output. Is this the right command?

At / (used space)

du -sch
2.3G .
2.3G total

At $HOME (used space)

du -sch
4.4G .
4.4G total

So, I am not sure what is occupying the remaining space? Total storage on this VM is 380 GB.

Is there any way to get rid of bazel logs? Is it causing the space issue? If so, where? 
Also, if it is how do I free up some space?

Update 2:

used bazel clean --expunge (this cleaned 500MB space) and re-configured tensorflow using ./configure

Run the bazel build again..

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR: /$HOME/Downloads/tensorflow/tensorflow/core/kernels/BUILD:1710:1: error while parsing .d file: /$HOME/.cache/bazel/_bazel_gpuadmin/52adb8ea4f53b1b72067611e8a7eb020/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.d (No such file or directory).
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
: fatal error: when writing output to : No space left on device
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

At $HOME:
du -sch
4.6G .
4.6G total

At /:
du -sch
2.3G .
2.3G total

df -h
Filesystem Size Used Avail Use% Mounted on
udev 28G 0 28G 0% /dev
tmpfs 5.6G 9.1M 5.5G 1% /run
/dev/sda1 29G 29G 9.8M 100% /
tmpfs 28G 0 28G 0% /dev/shm
tmpfs 5.0M 0 5.0M 0% /run/lock
tmpfs 28G 0 28G 0% /sys/fs/cgroup
none 64K 0 64K 0% /etc/network/interfaces.dynamic.d
/dev/sdb1 340G 133M 340G 1% /mnt
tmpfs 5.6G 0 5.6G 0% /run/user/1000

This is a fairly new machine with few installer software (<200MB)

Am I missing something to complete the build???

Thanks,

**Comment by davidzchen** [comment]
Can you try to figure out which directory is using all the space?

If the Bazel `.cache` directory exists in your home directory, can you try measuring its size?

**Comment by damienmg** [comment]
What is /mnt? It's is totally full (350G)!

Where is home?

**Comment by sskgit** [comment]
Sorry for the delay.
Space at / is 29GB (used space 98%)
Space at /mnt is 340GB (used space is 1%)
home is /home/username (2.3 GB)

May not be a bazel issue, we are trying to resolve the partition issue. Will update the issue on further findings.

**Comment by damienmg** [comment]
Ok / is definitely full no surprise the build fails, let me know if you need anymore help.

**Comment by sskgit** [comment]
Clearing up some space on / resolved the issue. Tensorflow build is complete and it works now. Thanks @damienmg and @davidchen.

**Comment by iamharshit** [comment]
@sskgit  i am getting exactly the same error, approximately home much space did i need to clean up?

**Comment by Magrathea42** [comment]
hi @sskgit 
How did you solve the build error a) that you described?
Thanks

**Comment by Emixam23** [comment]
Hi,

Same, I don't get how did you solve it :/ #MacUser

**Comment by felipemaion** [comment]
approximately how much space do i need free?
I have 7GB free at home. And 500gb free in the external drive (where I'm trying to compile it.)
Is there a way to have .cache at the external drive?
