### ISSUE TITLE
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.

### ISSUE THREAD

**Issue by olszowka-cargurus** [bazelbuild/bazel#18735]
### Description of the bug:

The build log requests I report this as a bug.  Below is the contents of the log.

```
Command: bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --build_event_binary_file=/var/folders/nh/hjzt0mb502gf6rl8ydn779q80000gp/T/intellij-bep-7f0321a8-c727-4caf-bbd4-370549ad87a4 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --remote_download_outputs=all --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/polszowka/Library/Application Support/JetBrains/IntelliJIdea2022.1/plugins/ijwb/aspect" --output_groups=intellij-resolve-java,intellij-resolve-js,intellij-info-generic,intellij-info-java,intellij-info-js -- //cargurus-on-site-notifications:checkstyle //cargurus-on-site-notifications:cargurus-on-site-notifications

INFO: Invocation ID: 8a5c0d27-a9bd-405c-ba9f-b7e4512dc091
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/8a5c0d27-a9bd-405c-ba9f-b7e4512dc091
Loading: 
Loading: 0 packages loaded
Analyzing: 2 targets (0 packages loaded)
Analyzing: 2 targets (0 packages loaded, 0 targets configured)
Analyzing: 2 targets (4 packages loaded, 6 targets configured)
Analyzing: 2 targets (16 packages loaded, 25 targets configured)
Analyzing: 2 targets (16 packages loaded, 25 targets configured)
Analyzing: 2 targets (29 packages loaded, 74 targets configured)
Analyzing: 2 targets (32 packages loaded, 86 targets configured)
Analyzing: 2 targets (35 packages loaded, 94 targets configured)
Analyzing: 2 targets (35 packages loaded, 94 targets configured)
Analyzing: 2 targets (37 packages loaded, 94 targets configured)
Analyzing: 2 targets (44 packages loaded, 487 targets configured)
Analyzing: 2 targets (44 packages loaded, 487 targets configured)
Analyzing: 2 targets (326 packages loaded, 2310 targets configured)
Analyzing: 2 targets (327 packages loaded, 2350 targets configured)
Analyzing: 2 targets (327 packages loaded, 2350 targets configured)
Analyzing: 2 targets (329 packages loaded, 2477 targets configured)
Analyzing: 2 targets (330 packages loaded, 2604 targets configured)
INFO: Analyzed 2 targets (717 packages loaded, 9693 targets configured).
INFO: Found 2 targets...
[0 / 1,335] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (7 actions, 0 running)
ERROR: /private/var/tmp/_bazel_polszowka/dca2dc285204f089bf52ab92166f98cb/external/bazel_tools/tools/jdk/BUILD:350:14: Couldn't build file external/bazel_tools/tools/jdk/platformclasspath.jar: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1): java failed: error executing command 
  (cd /private/var/tmp/_bazel_polszowka/dca2dc285204f089bf52ab92166f98cb/sandbox/darwin-sandbox/159/execroot/com_cargurus && \
  exec env - \
  external/local_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/local_jdk/lib/tools.jar DumpPlatformClassPath bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/remotejdk11_macos)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox java failed: error executing command 
  (cd /private/var/tmp/_bazel_polszowka/dca2dc285204f089bf52ab92166f98cb/sandbox/darwin-sandbox/159/execroot/com_cargurus && \
  exec env - \
  external/local_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/local_jdk/lib/tools.jar DumpPlatformClassPath bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/remotejdk11_macos)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.AssertionError: 
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
	at DumpPlatformClassPath.writeEntries(DumpPlatformClassPath.java:136)
	at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:174)
	at DumpPlatformClassPath.dumpJDK8BootClassPath(DumpPlatformClassPath.java:77)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:65)
INFO: From Building cargurus-iterable-api/libcargurus-iterable-api-class.jar (106 source files) and running annotation processors (ProxyProcessor):
cargurus-iterable-api/src/main/java/com/cargurus/iterable/api/list/core/IterableListApiResponseConverter.java:17: warning: (immutables:untype) Wildcards are not supported as elements or key/values. Make it lose its special treatment
    List<? extends IterableList> getLists();
                                 ^
INFO: Elapsed time: 88.144s, Critical Path: 4.03s
INFO: 1264 processes: 879 remote cache hit, 385 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/8a5c0d27-a9bd-405c-ba9f-b7e4512dc091
FAILED: Build did NOT complete successfully
Build command finished. Retrieving BEP outputs...

```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I get this error every time I build or sync with IJ bazel plug-in.  

Bazel plug-in version 2022.11.29.0.1-api-version-221

### Which operating system are you running Bazel on?

macOS Ventura 13.2.1

### What is the output of `bazel info release`?

INFO: Invocation ID: f81c245f-e5b2-48fe-8e58-5fb1309489e3 release 3.7.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

git@code.cargurus.com:cargurus-eng/cg-main.git
988eb7145e20bc8121357ea5b761d526de3a4b63
f79508024896eb2b5946505175c2d5668031413b

**Comment by ehthayer** [comment]
our codebase is using jdk8 and adding `--sandbox_debug` to the errorful command and changing `remotejdk11_macos` to `local_jdk` causes the command to succeed

**Comment by hvadehra** [comment]
> release 3.7.2

This version is [no longer supported](https://bazel.build/release#support-matrix). 

Please re-open this issue if you still have problems with a  newer (supported) version of Bazel.
