### ISSUE TITLE
OutofMemoryError

### ISSUE THREAD

**Issue by seaurching** [bazelbuild/bazel#18795]
### Description of the bug:

```
cat .bazelrc
# Enable Java 11 language features (https://github.com/bazelbuild/bazel/issues/14592)
build --java_language_version=11
build --tool_java_language_version=11
build --host_jvm_args=-Xmx32g
build --jobs=10
```
```
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk --tool_java_runtime_version=local_jdk --cxxopt=-std=c++11 --copt=-std=c99"  bash ./compile.sh
??  Building Bazel from scratch../usr/lib/jvm/java-17-openjdk-mips64el/bin/javac -classpath derived/jars/com_google_protobuf/java/core/libcore.jar:derived/jars/com_google_protobuf/java/core/liblite.jar:derived/jars/com_google_protobuf/java/util/libutil.jar:derived/jars/zstd-jni/libzstd-jni.jar:third_party/allocation_instrumenter/java-allocation-instrumenter-3.3.0.jar:third_party/android_common/com.android.tools.build_builder-model_2.0.0.jar:third_party/android_common/com.android.tools.build_builder-test-api_2.0.0.jar:third_party/android_common/com.android.tools.build_builder_2.0.0.jar:third_party/android_common/com.android.tools.build_manifest-merger_25.0.0-patched.jar:third_party/android_common/com.android.tools.external.lombok_lombok-ast_0.2.3.jar:third_party/android_common/com.android.tools.layoutlib_layoutlib_26.1.2-stripped.jar:third_party/android_common/com.android.tools.layoutlib_layoutlib_26.1.2.jar:third_party/android_common/com.android.tools.lint_lint-api_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-checks_25.0.0.jar:third_party/android_common/com.android.tools_common_25.0.0.jar:third_party/android_common/com.android.tools_dvlib_25.0.0.jar:third_party/android_common/com.android.tools_repository_25.0.0.jar:third_party/android_common/com.android.tools_sdk-common_25.0.0-patched-stripped.jar:third_party/android_common/com.android.tools_sdk-common_25.0.0-patched.jar:third_party/android_common/com.android.tools_sdklib_25.0.0.jar:third_party/android_common/com.android_annotations_25.0.0.jar:third_party/animal_sniffer/animal-sniffer-annotations-1.14.jar:third_party/antlr/antlr4-4.5.3.jar:third_party/apache_commons_codec/commons-codec-1.10.jar:third_party/apache_commons_collections/commons-collections-3.2.2.jar:third_party/apache_commons_compress/apache-commons-compress-1.19.jar:third_party/apache_commons_io/commons-io-2.4.jar:third_party/apache_commons_lang/commons-lang-2.6.jar:third_party/apache_commons_pool2/commons-pool2-2.8.0.jar:third_party/apache_velocity/velocity-1.7.jar:third_party/api_client/google-api-client-1.22.0.jar:third_party/api_client/google-api-client-gson-1.22.0.jar:third_party/api_client/google-http-client-1.41.4.jar:third_party/api_client/google-http-client-gson-1.41.4.jar:third_party/asm/asm-9.2-sources.jar:third_party/asm/asm-9.2.jar:third_party/asm/asm-analysis-9.2-sources.jar:third_party/asm/asm-analysis-9.2.jar:third_party/asm/asm-commons-9.2-sources.jar:third_party/asm/asm-commons-9.2.jar:third_party/asm/asm-tree-9.2-sources.jar:third_party/asm/asm-tree-9.2.jar:third_party/asm/asm-util-9.2-sources.jar:third_party/asm/asm-util-9.2.jar:third_party/auth/google-auth-library-credentials-1.6.0.jar:third_party/auth/google-auth-library-oauth2-http-1.6.0.jar:third_party/auto/auto-common-1.1.2.jar:third_party/auto/auto-service-1.0-rc7.jar:third_party/auto/auto-service-annotations-1.0-rc7.jar:third_party/auto/auto-value-1.8.2.jar:third_party/auto/auto-value-annotations-1.8.2.jar:third_party/auto/auto-value-gson-extension-1.3.1.jar:third_party/auto/auto-value-gson-factory-1.3.1.jar:third_party/auto/auto-value-gson-runtime-1.3.1.jar:third_party/auto/autotransient-1.0.0.jar:third_party/bazel_bootstrap/libautocodec-annotation.jar:third_party/bazel_bootstrap/libautocodec-processor.jar:third_party/bazel_bootstrap/libregistered-singleton.jar:third_party/bazel_bootstrap/libserialization-constant-annotation.jar:third_party/bazel_bootstrap/libserialization-constant-processor.jar:third_party/bazel_bootstrap/libserialization-processor-util.jar:third_party/bazel_bootstrap/libserialization.jar:third_party/bazel_bootstrap/libunsafe-provider.jar:third_party/bytebuddy/byte-buddy-1.9.7.jar:third_party/bytebuddy/byte-buddy-agent-1.9.7.jar:third_party/caffeine/caffeine-2.9.2.jar:third_party/checker_framework_annotations/checker-qual-3.2.0-sources.jar:third_party/checker_framework_annotations/checker-qual-3.2.0.jar:third_party/checker_framework_dataflow/dataflow-errorprone-3.15.0-sources.jar:third_party/checker_framework_dataflow/dataflow-errorprone-3.15.0.jar:third_party/checker_framework_dataflow/dataflow-shaded-3.11.0-sources.jar:third_party/checker_framework_dataflow/dataflow-shaded-3.11.0.jar:third_party/checker_framework_javacutil/javacutil-3.2.0-sources.jar:third_party/checker_framework_javacutil/javacutil-3.2.0.jar:third_party/compile_testing/compile-testing-0.18.jar:third_party/diffutils/diffutils-1.3.0.jar:third_party/error_prone/error_prone_annotation-2.11.0.jar:third_party/error_prone/error_prone_annotations-2.11.0.jar:third_party/error_prone/error_prone_check_api-2.11.0.jar:third_party/error_prone/error_prone_core-2.11.0.jar:third_party/error_prone/error_prone_type_annotations-2.11.0.jar:third_party/error_prone/threeten-extra-1.5.0.jar:third_party/flogger/flogger-0.5.1.jar:third_party/flogger/flogger-system-backend-0.5.1.jar:third_party/flogger/google-extensions-0.5.1.jar:third_party/grpc-java/grpc-api-1.45.1.jar:third_party/grpc-java/grpc-api-1.47.0.jar:third_party/grpc-java/grpc-auth-1.45.1.jar:third_party/grpc-java/grpc-auth-1.47.0.jar:third_party/grpc-java/grpc-context-1.45.1.jar:third_party/grpc-java/grpc-context-1.47.0.jar:third_party/grpc-java/grpc-core-1.45.1.jar:third_party/grpc-java/grpc-core-1.47.0.jar:third_party/grpc-java/grpc-netty-1.45.1.jar:third_party/grpc-java/grpc-netty-1.47.0.jar:third_party/grpc-java/grpc-protobuf-1.45.1.jar:third_party/grpc-java/grpc-protobuf-1.47.0.jar:third_party/grpc-java/grpc-protobuf-lite-1.45.1.jar:third_party/grpc-java/grpc-protobuf-lite-1.47.0.jar:third_party/grpc-java/grpc-stub-1.45.1.jar:third_party/grpc-java/grpc-stub-1.47.0.jar:third_party/gson/gson-2.8.6.jar:third_party/guava/failureaccess-1.0.1.jar:third_party/hamcrest/hamcrest-core-1.3.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0-src.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0.jar:third_party/ijar/test/jar-with-manifest-and-target-label.jar:third_party/ijar/test/jar-with-manifest.jar:third_party/ijar/test/jar-without-manifest.jar:third_party/ijar/test/libwrongcentraldir.jar:third_party/ijar/test/nestmates/nestmates.jar:third_party/ijar/test/records/records.jar:third_party/ijar/test/sealed/sealed.jar:third_party/java-diff-utils/java-diff-utils-4.0.jar:third_party/java/android_databinding/v3_4_0/base.jar:third_party/java/android_databinding/v3_4_0/compiler.jar:third_party/java/android_databinding/v3_4_0/compiler_common.jar:third_party/java/android_databinding/v3_4_0/exec.jar:third_party/java/android_databinding/v3_4_0/x_common.jar:third_party/java/j2objc-annotations/j2objc-annotations-1.1.jar:third_party/java/jacoco/jacocoagent-0.8.7.jar:third_party/java/jacoco/org.jacoco.agent-0.8.7-sources.jar:third_party/java/jacoco/org.jacoco.agent-0.8.7.jar:third_party/java/jacoco/org.jacoco.ant-0.8.7-nodeps.jar:third_party/java/jacoco/org.jacoco.ant-0.8.7-sources.jar:third_party/java/jacoco/org.jacoco.ant-0.8.7.jar:third_party/java/jacoco/org.jacoco.core-0.8.7-sources.jar:third_party/java/jacoco/org.jacoco.core-0.8.7.jar:third_party/java/jacoco/org.jacoco.report-0.8.7-sources.jar:third_party/java/jacoco/org.jacoco.report-0.8.7.jar:third_party/java/javapoet/javapoet-1.12.1.jar:third_party/java/jcommander/jcommander-1.48.jar:third_party/java/proguard/proguard6.2.2/lib/proguard.jar:third_party/java/proguard/proguard6.2.2/lib/proguardgui.jar:third_party/java/proguard/proguard6.2.2/lib/retrace.jar:third_party/javax_activation/javax.activation-api-1.2.0-sources.jar:third_party/javax_activation/javax.activation-api-1.2.0.jar:third_party/javax_annotations/javax.annotation-api-1.3.2-sources.jar:third_party/javax_annotations/javax.annotation-api-1.3.2.jar:third_party/jaxb/2.3.0/jaxb-api-2.3.0-sources.jar:third_party/jaxb/2.3.0/jaxb-api-2.3.0.jar:third_party/jaxb/2.3.0/jaxb-core-2.3.0-sources.jar:third_party/jaxb/2.3.0/jaxb-core-2.3.0.jar:third_party/jaxb/2.3.0/jaxb-impl-2.3.0-sources.jar:third_party/jaxb/2.3.0/jaxb-impl-2.3.0.jar:third_party/jaxb/jaxb-api-2.3.1-patched.jar:third_party/jaxb/jaxb-api-2.3.1-sources.jar:third_party/jaxb/jaxb-api-2.3.1.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jetbrains_annotations/annotations-13.0.jar:third_party/jetifier/jetifier-core-1.0.0-beta04.jar:third_party/jimfs/jimfs-1.1.jar:third_party/jsr305/jsr-305.jar:third_party/jsr330_inject/javax.inject.jar:third_party/junit/junit-4.13.jar:third_party/juniversalchardet/juniversalchardet-1.0.3.jar:third_party/kotlin_stdlib/kotlin-stdlib-1.3.21.jar:third_party/kotlin_stdlib/kotlin-stdlib-common-1.3.21.jar:third_party/kotlin_stdlib/kotlin-stdlib-jdk7-1.3.21.jar:third_party/kotlin_stdlib/kotlin-stdlib-jdk8-1.3.21.jar:third_party/mockito/mockito-core-3.12.4.jar:third_party/netty/netty-buffer-4.1.75.Final.jar:third_party/netty/netty-codec-4.1.75.Final.jar:third_party/netty/netty-codec-http-4.1.75.Final.jar:third_party/netty/netty-codec-http2-4.1.75.Final.jar:third_party/netty/netty-common-4.1.75.Final.jar:third_party/netty/netty-handler-4.1.75.Final.jar:third_party/netty/netty-handler-proxy-4.1.75.Final.jar:third_party/netty/netty-resolver-4.1.75.Final.jar:third_party/netty/netty-resolver-dns-4.1.75.Final.jar:third_party/netty/netty-transport-4.1.75.Final.jar:third_party/netty/netty-transport-classes-epoll-4.1.75.Final.jar:third_party/netty/netty-transport-classes-kqueue-4.1.75.Final.jar:third_party/netty/netty-transport-native-epoll-4.1.75.Final-linux-aarch_64.jar:third_party/netty/netty-transport-native-epoll-4.1.75.Final-linux-x86_64.jar:third_party/netty/netty-transport-native-kqueue-4.1.75.Final-osx-aarch_64.jar:third_party/netty/netty-transport-native-kqueue-4.1.75.Final-osx-x86_64.jar:third_party/netty/netty-transport-native-unix-common-4.1.75.Final-linux-aarch_64.jar:third_party/netty/netty-transport-native-unix-common-4.1.75.Final-linux-x86_64.jar:third_party/netty/netty-transport-native-unix-common-4.1.75.Final-osx-aarch_64.jar:third_party/netty/netty-transport-native-unix-common-4.1.75.Final-osx-x86_64.jar:third_party/netty/netty-transport-native-unix-common-4.1.75.Final.jar:third_party/netty/netty-transport-sctp-4.1.75.Final.jar:third_party/objenesis/objenesis-1_3.jar:third_party/opencensus/opencensus-api-0.24.0.jar:third_party/opencensus/opencensus-contrib-grpc-metrics-0.24.0.jar:third_party/opencensus/opencensus-contrib-http-util-0.31.0.jar:third_party/pcollections/pcollections-2.1.2.jar:third_party/perfmark/perfmark-api-0.19.0.jar:third_party/reactive_streams/reactive-streams-1.0.3.jar:third_party/rxjava3/rxjava-3.1.2.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/truth/truth-1.0.1.jar:third_party/truth8/truth-java8-extension-1.0.1.jar:third_party/truth_proto/truth-liteproto-extension-1.0.1.jar:third_party/truth_proto/truth-proto-extension-1.0.1.jar:third_party/turbine/turbine_direct.jar:third_party/xz/xz-1.9.jar:::third_party/guava/guava-31.1-jre.jar:third_party/guava/guava-testlib-31.1-jre.jar::/tmp/bazel_tdewi6z4 -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip:src/main/java:tools/java/runfiles:/tmp/bazel_tdewi6z4/src -d /tmp/bazel_tdewi6z4/classes -source 11 -target 11 -encoding UTF-8 @/tmp/bazel_Z2qUdHv8/param
warning: [options] system modules path not set in conjunction with -source 11
1 warning


The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at jdk.compiler/com.sun.tools.javac.util.Position$LineMapImpl.build(Position.java:156)
	at jdk.compiler/com.sun.tools.javac.util.Position.makeLineMap(Position.java:80)
	at jdk.compiler/com.sun.tools.javac.parser.JavadocTokenizer.getLineMap(JavadocTokenizer.java:285)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.getLineMap(Scanner.java:127)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3718)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:620)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:657)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1006)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:993)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:919)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at jdk.compiler/com.sun.tools.javac.util.Position$LineMapImpl.build(Position.java:156)
	at jdk.compiler/com.sun.tools.javac.util.Position.makeLineMap(Position.java:80)
	at jdk.compiler/com.sun.tools.javac.parser.JavadocTokenizer.getLineMap(JavadocTokenizer.java:285)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.getLineMap(Scanner.java:127)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3718)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:620)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:657)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1006)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:993)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:919)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

### Which operating system are you running Bazel on?

mips64

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk --tool_java_runtime_version=local_jdk --cxxopt=-std=c++11 --copt=-std=c99"  bash ./compile.sh

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
6.2.1-dist
```

**Comment by seaurching** [comment]
#### git clone the sourcecode,then use ```root@ed7d09768525:~/bazel# bazel-4 build //src:bazel``` build it, finaly tips:
```
DEBUG: /root/bazel/tools/build_defs/repo/http.bzl:142:10: ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.2/rules_cc-0.0.2.tar.gz"]
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: test -f BUILD && chmod u+w BUILD || true
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: echo >> BUILD
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: echo 'exports_files(["WORKSPACE"], visibility = ["//visibility:public"])' >> BUILD
ERROR: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl", line 16, column 76, in <toplevel>
		load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //src/main/cpp:client: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
DEBUG: /root/bazel/tools/build_defs/repo/http.bzl:142:10: ["https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip", "https://github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip"]
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: test -f BUILD && chmod u+w BUILD || true
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: echo >> BUILD
DEBUG: /root/bazel/tools/build_defs/repo/utils.bzl:192:18: echo 'exports_files(["WORKSPACE"], visibility = ["//visibility:public"])' >> BUILD
DEBUG: /root/bazel/tools/build_defs/repo/http.bzl:142:10: ["https://mirror.bazel.build/github.com/bazelbuild/rules_license/releases/download/0.0.3/rules_license-0.0.3.tar.gz", "https://github.com/bazelbuild/rules_license/releases/download/0.0.3/rules_license-0.0.3.tar.gz"]
ERROR: Analysis of target '//src:bazel' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 3.834s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 0 targets configured)
    currently loading: src/main/protobuf
```

**Comment by seaurching** [comment]
```
root@ed7d09768525:~/bazel# uname -m
mips64
root@ed7d09768525:~/bazel# bazel-4 build //src:bazel
INFO: Repository bazelci_rules instantiated at:
  /root/bazel/WORKSPACE:258:18: in <toplevel>
  /root/bazel/distdir.bzl:94:17: in dist_http_archive
Repository rule http_archive defined at:
  /root/bazel/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository 'bazelci_rules' used the following cache hits instead of downloading the corresponding file.
 * Hash 'eca21884e6f66a88c358e580fd67a6b148d30ab57b1680f62a96c00f9bc6a07e' for https://mirror.bazel.build/github.com/bazelbuild/continuous-integration/releases/download/rules-1.0.0/bazelci_rules-1.0.0.tar.gz
If the definition of 'bazelci_rules' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'bazelci_rules':
   Traceback (most recent call last):
	File "/root/bazel/tools/build_defs/repo/http.bzl", line 143, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/root/bazel/tools/build_defs/repo/utils.bzl", line 193, column 21, in patch
		fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command test -f BUILD && chmod u+w BUILD || true:
java.io.IOException: Cannot run program "/usr/share/bazel/process-wrapper" (in directory "/root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/bazelci_rules"): error=0, Failed to exec spawnhelper: pid: 78290, exit value: 1
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/bazel/tools/build_defs/repo/http.bzl", line 143, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/root/bazel/tools/build_defs/repo/utils.bzl", line 193, column 21, in patch
		fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command test -f BUILD && chmod u+w BUILD || true:
java.io.IOException: Cannot run program "/usr/share/bazel/process-wrapper" (in directory "/root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/bazelci_rules"): error=0, Failed to exec spawnhelper: pid: 78290, exit value: 1
ERROR: no such package '@bazelci_rules//': Error applying patch command test -f BUILD && chmod u+w BUILD || true:
java.io.IOException: Cannot run program "/usr/share/bazel/process-wrapper" (in directory "/root/.cache/bazel/_bazel_root/038a9c24c67a3f14ac28680c554d9af8/external/bazelci_rules"): error=0, Failed to exec spawnhelper: pid: 78290, exit value: 1
INFO: Elapsed time: 3.698s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by seaurching** [comment]
```
ERROR: /tmp/bazel_Wi5Cq8sn/out/external/bazel_tools/third_party/ijar/BUILD:72:10: Linking external/bazel_tools/third_party/ijar/zipper [for tool] failed: (Exit 1): gcc failed: error executing command (from target @bazel_tools//third_party/ijar:zipper) 
  (cd /tmp/bazel_Wi5Cq8sn/out/execroot/io_bazel && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc @bazel-out/mips64-opt-exec-EDC14992/bin/external/bazel_tools/third_party/ijar/zipper-2.params)
# Configuration: 40272a6ece154fb00ee7235b617530863841496c2bdeda0e6675b53f4fd6b9b6
# Execution platform: //:default_host_platform
collect2: fatal error: ld terminated with signal 10 [Bus error], core dumped
compilation terminated.
[418 / 2,946] checking cached actions
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 854.109s, Critical Path: 200.22s
INFO: 418 processes: 145 internal, 273 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```

**Comment by hvadehra** [comment]
@seaurching the linked/related issues appear to be fixed. Are you still having this problem?

**Comment by seaurching** [comment]
> [@seaurching](https://github.com/seaurching) the linked/related issues appear to be fixed. Are you still having this problem?

Thanks, I haven't the mips64el device environments yet.
