### ISSUE TITLE
Server terminated abruptly error with Bazel@HEAD. 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18797]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3125#0189002d-af12-4fc8-a49c-7097d0edb169

Platform : Macos, Windows, ubuntu

Logs  :  
```

FATAL: bazel ran out of memory and crashed. Printing stack trace:
java.lang.OutOfMemoryError: Java heap space
	at com.google.common.escape.CharEscaper.growBuffer(CharEscaper.java:167)
	at com.google.common.escape.CharEscaper.escapeSlow(CharEscaper.java:127)
	at com.google.common.escape.CharEscaperBuilder$CharArrayDecorator.escape(CharEscaperBuilder.java:62)
	at com.google.devtools.common.options.OptionsBase.mapToCacheKey(OptionsBase.java:114)
	at com.google.devtools.common.options.OptionsBase.cacheKey(OptionsBase.java:95)
	at com.google.devtools.build.lib.analysis.config.BuildOptions.checksum(BuildOptions.java:176)
	at com.google.devtools.build.lib.analysis.producers.TransitionApplier.convertOptionsToKeys(TransitionApplier.java:151)
	at com.google.devtools.build.lib.analysis.producers.TransitionApplier.applyStarlarkTransition(TransitionApplier.java:143)
	at com.google.devtools.build.lib.analysis.producers.TransitionApplier.step(TransitionApplier.java:106)
	at com.google.devtools.build.skyframe.state.TaskTreeNode.run(TaskTreeNode.java:95)
	at com.google.devtools.build.skyframe.state.Driver.drive(Driver.java:89)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeTargetAndConfiguration(ConfiguredTargetFunction.java:489)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:247)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:506)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

Steps : 
```
git clone -v https://github.com/bazelbuild/rules_rust.git
git reset 9442aed8ca9e07e024f9daaf06030c968623c9c1 --hard
export USE_BAZEL_VERSION=3bfd9220f847844c66b5a8991eeb6e68ae840b89
bazel build //...
# Terminal hangs after that.
```

Relative issue : https://github.com/bazelbuild/bazel/issues/18771

CC Greenteam @comius

**Comment by sgowroji** [comment]
Dupe of https://github.com/bazelbuild/bazel/issues/18795

**Comment by sgowroji** [comment]
Closing this issue as the dupe is fixed!
