### ISSUE TITLE
Bazel crashed when querying external repositories with none-rule targets

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#18813]
### Description of the bug:

```
FATAL: [0mbazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@WORKSPACE' (requested by nodes 'IGNORED_PACKAGE_PREFIXES:@WORKSPACE')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:642)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.packages.InputFile cannot be cast to class com.google.devtools.build.lib.packages.Rule (com.google.devtools.build.lib.packages.InputFile and com.google.devtools.build.lib.packages.Rule are in unnamed module of loader 'app')
	at com.google.devtools.build.lib.packages.Package.getRule(Package.java:656)
	at com.google.devtools.build.lib.repository.ExternalPackageHelper$ExternalPackageRuleExtractor.processAndShouldContinue(ExternalPackageHelper.java:144)
	at com.google.devtools.build.lib.repository.ExternalPackageHelper.iterateWorkspaceFragments(ExternalPackageHelper.java:118)
	at com.google.devtools.build.lib.repository.ExternalPackageHelper.getRuleByName(ExternalPackageHelper.java:52)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.getRepoRuleFromWorkspace(RepositoryDelegatorFunction.java:446)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:285)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
	... 7 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Query for all external repositories `bazel query //external:* --output label`

2. Process the list like this:
```
var externals = ... // all labels (lines) returned by first query
var setOfExternalsToQuery = externals.stream()
        .filter(s -> s.startsWith("//external:"))
        .map(s -> s.substring("//external:".length()))
        .map(s -> format("@%s//...", s))
        .collect(joining(" "));
var javaImportQuery = String.format("kind('java_import rule', set( %s ))", setOfExternalsToQuery);
```

Something in `setOfExternalsToQuery` is triggering the behavior.

Workaround/fix, ensure the first query is properly scoped, eg. : `kind(jvm_import_external, //external:*)`

### Which operating system are you running Bazel on?

mac

### What is the output of `bazel info release`?

6.1.0

**Comment by mattnworb** [comment]
do you by any chance have a symlink in the bazel workspace to its own output base? https://github.com/bazelbuild/bazel/issues/20172#issuecomment-1968125915
