### ISSUE TITLE
`IllegalArgumentException` when aspect & rule share attribute name of differing types

### ISSUE THREAD

**Issue by lpulley** [bazelbuild/bazel#18901]
### Description of the bug:

Bazel crashes with `IllegalArgumentException` when applying an aspect to a rule if the aspect and the rule share an `attr` name but with different types; for example, a rule with a `bool` attr `x` and an aspect with a `string` attr `x`.

In the below example (on `last_green` `2f888a7d7ce61c2f4b46a32361ecae4a02042b08`), this results in:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#//:foobar.bzl%foo[x="a"] ConfiguredTargetKey{label=//:bar, config=BuildConfigurationKey[dd319536d130cd051c3b13b00266c866288f87a7812124a766746c5d8e3cdd83]} {x=[a]}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectKeyCreator$TopLevelAspectsKey@9eb08b9a')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:596)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Attribute x is of type boolean and not of type string in bar rule //:bar
        at com.google.devtools.build.lib.packages.Rule.checkAttrType(Rule.java:668)
        at com.google.devtools.build.lib.packages.Rule.getAttr(Rule.java:524)
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:57)
        at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.getAndValidate(ConfiguredAttributeMapper.java:132)
        at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.get(ConfiguredAttributeMapper.java:297)
        at com.google.devtools.build.lib.analysis.DependencyResolver.resolveAttribute(DependencyResolver.java:685)
        at com.google.devtools.build.lib.analysis.DependencyResolver.resolveAttributes(DependencyResolver.java:649)
        at com.google.devtools.build.lib.analysis.DependencyResolver.visitRule(DependencyResolver.java:560)
        at com.google.devtools.build.lib.analysis.DependencyResolver.computeDependencyLabels(DependencyResolver.java:261)
        at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:179)
        at com.google.devtools.build.lib.skyframe.PrerequisiteProducer.computeDependencies(PrerequisiteProducer.java:669)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:296)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:506)
        ... 7 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://gist.github.com/lpulley/a2a0c0f2ec962e6f007ec4e030646a83

```bash
bazel build //:bar --aspects=//:foobar.bzl%foo
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

I tested with several versions, most recently (`last_green` at time of writing) `2f888a7d7ce61c2f4b46a32361ecae4a02042b08`

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

This seems to have been introduced between 0.22.0 and 0.23.0. `bazelisk --bisect` does not seem to work here; some old artifacts are missing.

```
--- Getting the list of commits between 0.22.0 and 0.23.0

The good Bazel commit is not an ancestor of the bad Bazel commit, overriding the good Bazel commit to the merge base commit deb028e3fb30b4e2953df16f35ab1f55a08ea8fa
Found 512 commits between (deb028e3fb30b4e2953df16f35ab1f55a08ea8fa, 0.23.0]


--- Verifying if the given good Bazel commit (deb028e3fb30b4e2953df16f35ab1f55a08ea8fa) is actually good

2023/07/11 16:02:46 Using unreleased version at commit deb028e3fb30b4e2953df16f35ab1f55a08ea8fa
2023/07/11 16:02:46 Downloading https://storage.googleapis.com/bazel-builds/artifacts/centos7/deb028e3fb30b4e2953df16f35ab1f55a08ea8fa/bazel...
2023/07/11 16:02:47 could not run Bazel: could not download Bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/centos7/deb028e3fb30b4e2953df16f35ab1f55a08ea8fa/bazel failed with error 404
```

It works in 0.22.0:

```
DEBUG: /ocient/db/xgsrc1/btest/foobar.bzl:13:5: False
DEBUG: /ocient/db/xgsrc1/btest/foobar.bzl:2:5: a
INFO: Analysed target //:bar (2 packages loaded, 17 targets configured).
INFO: Found 1 target...
Aspect //:foobar.bzl%foo of //:bar up-to-date (nothing to build)
INFO: Elapsed time: 14.153s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

**Comment by c-mita** [comment]
I believe this only occurs with public attributes; implicit/private attributes work fine.
@mai93 - should this be supported? At the very least it shouldn't crash Bazel.

**Comment by lpulley** [comment]
Thanks @mai93! Can confirm this fixes the case I bumped into.
