### ISSUE TITLE
[skymeld-dogfood] Missing files in external repositories

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#18969]
### Description of the bug:

I attempted to enable Skymeld for [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer), but it caused CI failures with actions failing to find files in external repositories. I can reproduce the failures locally.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Clone the `skymeld` branch of https://github.com/CodeIntelligenceTesting/jazzer.
2. Run `bazel build //deploy:jazzer-junit-project //deploy:jazzer-project //deploy:jazzer-api-project //selffuzz:jazzer_selffuzz`.

This can result in a number of failures. Locally, I get:
```
ERROR: /home/fhenneke/tmp/foo/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD:1:13: Compiling Java headers external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/librules_jvm_external-hjar.jar (4 source files) [for tool] failed: (Exit 1): java failed: error executing Turbine command (from target @rules_jvm_external//private/tools/java/com/github/bazelbuild/rules_jvm_external:rules_jvm_external) external/remotejdk17_linux/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 49 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
java.nio.file.NoSuchFileException: external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/ByteStreams.java
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at com.google.common.io.MoreFiles$PathByteSource.read(MoreFiles.java:162)
	at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:486)
	at com.google.turbine.main.Main.parseAll(Main.java:320)
	at com.google.turbine.main.Main.compile(Main.java:139)
	at com.google.turbine.main.Main.compile(Main.java:132)
	at com.google.turbine.main.Main.main(Main.java:88)
Target //deploy:jazzer-api-project failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

In CI, I have seen:
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/a85cf0f1020a89dc6ff7f251b188c44c/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD:1:13: Building external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/librules_jvm_external.jar (4 source files) [for tool] failed: (Exit 1): java failed: error executing Javac command (from target @rules_jvm_external//private/tools/java/com/github/bazelbuild/rules_jvm_external:rules_jvm_external) external/remotejdk17_linux/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments skipped)
error: error reading external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/ByteStreams.java; /home/runner/.cache/bazel/_bazel_runner/a85cf0f1020a89dc6ff7f251b188c44c/execroot/jazzer/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/ByteStreams.java
error: error reading external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/Coordinates.java; /home/runner/.cache/bazel/_bazel_runner/a85cf0f1020a89dc6ff7f251b188c44c/execroot/jazzer/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/Coordinates.java
error: error reading external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/Hasher.java; /home/runner/.cache/bazel/_bazel_runner/a85cf0f1020a89dc6ff7f251b188c44c/execroot/jazzer/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/Hasher.java
error: error reading external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/MavenRepositoryPath.java; /home/runner/.cache/bazel/_bazel_runner/a85cf0f1020a89dc6ff7f251b188c44c/execroot/jazzer/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/MavenRepositoryPath.java
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.0-pre.20230628.2

**Comment by fmeum** [comment]
@joeleba

**Comment by joeleba** [comment]
Hey, thanks for filing the issue. Could you please try again at HEAD? I observed something similar last week and it was fixed after https://github.com/bazelbuild/bazel/commit/fa28cf28f6a9210793039bbecef05018499b3b96.

**Comment by fmeum** [comment]
Thanks for the pointer, can't reproduce the failure anymore on https://github.com/bazelbuild/bazel/commit/fa28cf28f6a9210793039bbecef05018499b3b96.
