### ISSUE TITLE
Unrecoverable Error when a toolchain has the wrong providers

### ISSUE THREAD

**Issue by saribe0** [bazelbuild/bazel#19078]
### Description of the bug:

I am trying to set up two toolchains to compile a sample program on my M1 MacBook for both arm64 and x86 to be run with Rosetta. When running I am getting an "Unrecoverable Error" and Java stack trace that I'm not sure how to debug. This post suggests that Bazel shouldn't crash so I'm posting here. Any advice on how to get the two toolchains to work is also welcome :). 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

./toolchain/gcc/BUILD
```
package(default_visibility = ["//visibility:public"])

load(":gcc_toolchain_config.bzl", "gcc_toolchain")

gcc_toolchain(
    name = "arm64_8_3_toolchain",
    prefix = "arch -arm64 "
)

gcc_toolchain(
    name = "gcc_m1_x86_64_toolchain",
    prefix = ""
)

toolchain(
    name = "gcc_m1_arm64",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    toolchain = ":arm64_8_3_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)

toolchain(
    name = "gcc_m1_x86_64",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
    toolchain = ":gcc_m1_x86_64_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)
```
./toolchain/gcc/gcc_toolchain_config.bzl
```
load("@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl", "tool_path")

def _gcc_toolchain_impl(ctx):
    return [
        platform_common.ToolchainInfo(
            compiler = ctx.attr.prefix + "gcc",
            archiver = ctx.attr.prefix + "ar",
            linker = ctx.attr.prefix + "ld",
        )
    ]

gcc_toolchain = rule(
    implementation = _gcc_toolchain_impl,
    attrs = {
        "prefix": attr.string()
    },
)
```
./platform/BUILD
```
package(default_visibility = ["//visibility:public"])

platform(
    name = "linux_x86_64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

platform(
    name = "macos_m1_x86_64",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
)

platform(
    name = "macos_m1_arm64",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
)
```
./hello_world/BUILD
```

cc_binary(
    name = "hello",
    srcs = [
        "main.cpp"
    ],
    visibility = ["//visibility:public"],
)
```
./hello_world/main.cpp
```
#include <iostream>

int main() {

    std::cout << "hello world" << std::endl;

    return 0;
}
```
Execution & result:
```
% bazel build -s //hello_world:hello --platforms=//platform:macos_m1_x86_64
Starting local Bazel server and connecting to it...
Analyzing: target //hello_world:hello (33 packages loaded, 10 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@bazel_tools//tools/cpp:malloc, config=BuildConfigurationValue.Key[0cbf8f1e9d69e0e329ba03b41d48da5b494666829425075abc936d34606975c9]}' (requested by nodes 'ConfiguredTargetKey{label=//hello_world:hello, config=BuildConfigurationValue.Key[0cbf8f1e9d69e0e329ba03b41d48da5b494666829425075abc936d34606975c9]}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:880)
        at com.google.devtools.build.lib.rules.cpp.CcCommon.<init>(CcCommon.java:173)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:132)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:95)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:364)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:188)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1108)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:980)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:368)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        ... 7 more
```

### Which operating system are you running Bazel on?

macOS 13.1

### What is the output of `bazel info release`?

release 5.2.0-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
fatal: not a git repository (or any of the parent directories): .git
```

### Have you found anything relevant by searching the web?

No luck.

**Comment by Pavank1992** [comment]
Could you please try latest Bazel [version](https://github.com/bazelbuild/bazel/releases) and conform if issue still persist?

**Comment by saribe0** [comment]
Updated to 6.3 and still see the same/a similar error:
```
% bazel info release                                                       
Starting local Bazel server and connecting to it...
release 6.3.0-homebrew
```
Output:
```
% bazel build -s //hello_world:hello --platforms=//platform:macos_m1_x86_64
Starting local Bazel server and connecting to it...
Analyzing: target //hello_world:hello (40 packages loaded, 221 targets configured)
    currently loading: @local_config_xcode//
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@bazel_tools//tools/cpp:current_cc_toolchain, config=BuildConfigurationKey[e4220a1781e2469f06f2ffc20ff8af34bba3ff92b371218584755adcfbd23139]}' (requested by nodes 'ConfiguredTargetKey{label=//hello_world:hello, config=BuildConfigurationKey[e4220a1781e2469f06f2ffc20ff8af34bba3ff92b371218584755adcfbd23139]}', 'ConfiguredTargetKey{label=@bazel_tools//tools/cpp:malloc, config=BuildConfigurationKey[e4220a1781e2469f06f2ffc20ff8af34bba3ff92b371218584755adcfbd23139]}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.cpp.CcToolchain.createMakeVariableProvider(CcToolchain.java:124)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainAliasRule$CcToolchainAlias.create(CcToolchainAliasRule.java:78)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainAliasRule$CcToolchainAlias.create(CcToolchainAliasRule.java:68)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:371)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:192)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1231)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1218)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:431)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
        ... 7 more
```

**Comment by katre** [comment]
The problem here is that you declare that your `gcc_toolchain` rule is suitable as a `@rules_cc//cc:toolchain_type`, but it doesn't expose a `CcToolchainProvider` instance.

Instead of creating your own rule, use the existing `cc_toolchain` rule, which is more complex to set up but will actually create the providers needed for the `cc_library` etc rules.

That said, we shouldn't crash in this case, either, so I'll take a look at fixing the code to provide a better error.

**Comment by katre** [comment]
I can reproduce your crash using Bazel 6.3.0 (adding `--incompatible_enable_cc_toolchain_resolution`, since this uses toolchains).

When I try and reproduce your crash with Bazel at head, I don't get a crash, I get:
```
ERROR: /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/509d793b7b65e46935d56133652bbc5b/external/bazel_tools/tools/cpp/BUILD:58:19: in cc_toolchain_alias rule @bazel_tools//tools/cpp:current_cc_toolchain: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/cc_toolchain_alias.bzl", line 29, column 34, in _impl
Error: 'ToolchainInfo' value has no field or method 'get_additional_make_variables'
Available attributes: archiver, compiler, linker
ERROR: /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/509d793b7b65e46935d56133652bbc5b/external/bazel_tools/tools/cpp/BUILD:58:19: Analysis of target '@bazel_tools//tools/cpp:current_cc_toolchain' failed
```

Since this isn't a crash and shows better what the error was, I'm going to consider this to be closed. Thanks!
