### ISSUE TITLE
Make file substitution broken in cc_test copts in 6.3.0

### ISSUE THREAD

**Issue by mkruskal-google** [bazelbuild/bazel#19124]
### Description of the bug:

While upgrading the protobuf repo to 6.3.0, we saw a Bazel crash pointing to one of our tests.  After investigating it, we found that this was caused by using Make variable substitution in the `copts` flag (which the documentation does say is supported https://bazel.build/reference/be/c-cpp#cc_test).  Removing this fixes the crash, but ofc it breaks our test.

The error we see:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey***label=//src/google/protobuf/compiler:command_line_interface_unittest, config=BuildConfigurationKey[8679faf3db300196937e208298ecacc926d51dcbe7263f8ddfdb49e30abca07a]***' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//src/google/protobuf/compiler:command_line_interface_unittest)
	at <starlark>.expand_location(<builtin>:0)
	at <starlark>._expand_nested_variable(/virtual_builtins_bzl/common/cc/cc_helper.bzl:718)
	at <starlark>._expand(/virtual_builtins_bzl/common/cc/cc_helper.bzl:783)
	at <starlark>._expand_make_variables_for_copts(/virtual_builtins_bzl/common/cc/cc_helper.bzl:875)
	at <starlark>._get_copts(/virtual_builtins_bzl/common/cc/cc_helper.bzl:892)
	at <starlark>.cc_binary_impl(/virtual_builtins_bzl/common/cc/cc_binary.bzl:639)
	at <starlark>._cc_test_impl(/virtual_builtins_bzl/common/cc/cc_test.bzl:28)
	at <starlark>._impl(/virtual_builtins_bzl/common/cc/cc_test.bzl:70)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: //src/google/protobuf:testdata=[File:[/workspace[source]]src/google/protobuf/testdata/bad_utf8_string, File:[/workspace[source]]src/google/protobuf/testdata/golden_message, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_maps, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_oneof_implemented, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_proto3, File:[/workspace[source]]src/google/protobuf/testdata/golden_packed_fields_message, File:[/workspace[source]]src/google/protobuf/testdata/map_test_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_oneof_implemented.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_pointy.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_pointy_oneof.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_extensions_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_extensions_data_pointy.txt, File:[/workspace[source]]src/google/protobuf/descriptor.cc] and //src/google/protobuf:testdata=[File:[/workspace[source]]src/google/protobuf/testdata/bad_utf8_string, File:[/workspace[source]]src/google/protobuf/testdata/golden_message, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_maps, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_oneof_implemented, File:[/workspace[source]]src/google/protobuf/testdata/golden_message_proto3, File:[/workspace[source]]src/google/protobuf/testdata/golden_packed_fields_message, File:[/workspace[source]]src/google/protobuf/testdata/map_test_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_oneof_implemented.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_pointy.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_data_pointy_oneof.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_extensions_data.txt, File:[/workspace[source]]src/google/protobuf/testdata/text_format_unittest_extensions_data_pointy.txt, File:[/workspace[source]]src/google/protobuf/descriptor.cc]
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241)
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.makeLabelMap(StarlarkRuleContext.java:1153)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.expandLocation(StarlarkRuleContext.java:921)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
```

The problematic build rule:
```
cc_test(
    name = "command_line_interface_unittest",
    srcs = ["command_line_interface_unittest.cc"],
    copts = COPTS + select({
        "//build_defs:config_msvc": [],
        "//conditions:default": [
            "-Wno-deprecated",
            "-Wno-deprecated-declarations",
        ],
    }) + [
        # Note: This only works on Windows with symlinks and runfiles enabled.
        "-DGOOGLE_PROTOBUF_FAKE_PLUGIN_PATH=\\\"$(rootpath :fake_plugin)\\\"",
        "-DGOOGLE_PROTOBUF_TEST_PLUGIN_PATH=\\\"$(rootpath :test_plugin)\\\"",
    ],
    data = [
        ":fake_plugin",
        ":test_plugin",
        "//:test_proto_srcs",
        "//src/google/protobuf:descriptor_proto_srcs",
        "//src/google/protobuf:testdata",
    ],
    deps = [
        ":code_generator",
        ":command_line_interface",
        ":command_line_interface_tester",
        ":mock_code_generator",
        "//:protobuf",
        "//src/google/protobuf:cc_test_protos",
        "//src/google/protobuf:test_textproto",
        "//src/google/protobuf:test_util2",
        "//src/google/protobuf/compiler/cpp:names",
        "//src/google/protobuf/io",
        "//src/google/protobuf/stubs",
        "//src/google/protobuf/testing",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using Bazel 6.3.0:

git clone https://github.com/protocolbuffers/protobuf.git
git checkout 24.x
bazel build //src/google/protobuf/compiler:command_line_interface_unittest

### Which operating system are you running Bazel on?

Linux, MacOS, Windows

### What is the output of `bazel info release`?

release 6.3.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

This was working in Bazel 5.4.0, but I'm not sure where it broke.  Likely in the migration from native cc rules to starlark?

**Comment by brentleyjones** [comment]
Can you try the 6.3.1rc1? Should be fixed there.

**Comment by sgowroji** [comment]
Hi @mkruskal-google, Did you get a chance to check with 6.3.1 ?

**Comment by brentleyjones** [comment]
Pretty sure this was fixed. We can re-open if not.
