### ISSUE TITLE
FATAL: bazel crashed due to an internal error. Printing stack trace: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazel#19250]
### Description of the bug:

When I run bazelisk to load the latest rolling version of bazel to build some code on Windows running on an ARM 64 machine, I see:

```
pwsh❯ bazel build ...
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing c:\users\yesudeep\_bazel_yesudeep\dtybepaq\server\jvm.out
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.UnsatisfiedLinkError: 'int com.google.devtools.build.lib.windows.WindowsFileOperations.nativeIsSymlinkOrJunction(java.lang.String, boolean[], java.lang.String[])'
        at com.google.devtools.build.lib.windows.WindowsFileOperations.nativeIsSymlinkOrJunction(Native Method)
        at com.google.devtools.build.lib.windows.WindowsFileOperations.isSymlinkOrJunction(WindowsFileOperations.java:143)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.isSymlinkOrJunction(WindowsFileSystem.java:264)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.fileIsSymbolicLink(WindowsFileSystem.java:135)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:158)
        at com.google.devtools.build.lib.vfs.FileSystem.statNullable(FileSystem.java:511)
        at com.google.devtools.build.lib.vfs.FileSystem.readdir(FileSystem.java:632)
        at com.google.devtools.build.lib.vfs.Path.readdir(Path.java:268)
        at com.google.devtools.build.lib.exec.BinTools.scanDirectoryRecursively(BinTools.java:132)
        at com.google.devtools.build.lib.exec.BinTools.forProduction(BinTools.java:80)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1299)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1024)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:769)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:96)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel build ...`

### Which operating system are you running Bazel on?

Windows 11 arm64

### What is the output of `bazel info release`?

The output is that error.

### Any other information, logs, or outputs that you want to share?

 No matter what bazel subcommand I run, I get the same error.

**Comment by meteorcloudy** [comment]
@yesudeep This probably because we didn't build Bazel correctly for Windows arm64 after https://github.com/bazelbuild/bazel/commit/5647b26d7152f0a5ebd5d5fec2643d8e0b8dd661, which should be fixed by https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687 and https://github.com/bazelbuild/bazel/commit/d0de5e044c65fe7c5e414f860887be20087732da

Can you try with `USE_BAZEL_VERSION=last_green`? The next rolling release should also be fixed.

**Comment by meteorcloudy** [comment]
Please re-open if the issue persists.

**Comment by meteorcloudy** [comment]
@yesudeep Can you help debug which change caused this using https://github.com/bazelbuild/bazelisk#--bisect?

We don't have a Windows arm64 machine available for testing.

**Comment by meteorcloudy** [comment]
I see, this is because we are using a wrong embedded JDK for Windows arm64: 

https://github.com/bazelbuild/bazel/blob/a83810d641487523fba19ea06217e69d5fd8e451/src/BUILD#L153
