### ISSUE TITLE
`java.lang.OutOfMemoryError: Direct buffer memory` during cache uploads

### ISSUE THREAD

**Issue by phlax** [bazelbuild/bazel#19262]
### Description of the bug:

The above error occurs pretty frequently during cache uploads

### Which category does this issue belong to?

caching

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

this issue seems to be related to having a fairly large build requirement and occurs flakily so it doesnt seem like it would be easy to create a minimal reproducer

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

i have tried with both `release 6.3.2` and `release 6.3.1`

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```
git@github.com:phlax/envoy
e72d3e58832b96f05cfaa32ad313d2362b10ce9f
fd0a5bf219046f080b652217a6b3a1b69e0a1201
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Not sure - we have started seeing this since upgrading to bazel 6.3.1 _and_ switching to the `collect_cc_coverage.sh` script provided here

### Have you found anything relevant by searching the web?

no, not really

I tried adding `startup --host_jvm_args=-XX:MaxDirectMemorySize=512m` to bazelrc but it doesnt seem to help

### Any other information, logs, or outputs that you want to share?

First reported here https://github.com/buchgr/bazel-remote/issues/688 but i then switched the failing CI to using google's RBE and have seen the same issue so it would appear to be a bazel rather than bazel-remote issue

typical failure

```console

WARNING: Remote Cache: Error while uploading artifact with digest 'dd662f55f250fdc85f7d649f5deb2a38995973e85edc0b36a23b12bec6a0e71c/3594364'
com.google.devtools.build.lib.remote.common.BulkTransferException: Error while uploading artifact with digest 'dd662f55f250fdc85f7d649f5deb2a38995973e85edc0b36a23b12bec6a0e71c/3594364'
	at com.google.devtools.build.lib.remote.util.RxUtils$BulkTransferExceptionCollector.onResult(RxUtils.java:91)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onNext(FlowableCollectSingle.java:94)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.innerSuccess(FlowableFlatMapSingle.java:173)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber$InnerObserver.onSuccess(FlowableFlatMapSingle.java:342)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:73)
	at io.reactivex.rxjava3.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:91)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onFailure(RxFutures.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1124)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
		at io.grpc.Status.asRuntimeException(Status.java:535)
		... 10 more
	Caused by: java.lang.OutOfMemoryError: Direct buffer memory
		at java.base/java.nio.Bits.reserveMemory(Unknown Source)
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=146213&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=00ade0d6-ffae-5af0-b5e0-e33b1813c8bc&l=201

**Comment by phlax** [comment]
closing this as we seem to have resolved our issues one way or another - mostly i think by more carefully applying `MaxDirectMemorySize`
