### ISSUE TITLE
Running bazel in a subshell causes subshell to hang

### ISSUE THREAD

**Issue by jacky8hyf** [bazelbuild/bazel#19309]
### Description of the bug:

This hangs. This only ends after I manually shutdown the server from another terminal window.

```
bazel shutdown;
( ( tools/bazel version ) | cat ) 3>&1 1>&2 2>&3  | cat
```

This only happens when the bazel server is started within a subshell within a subshell (hence the `bazel shutdown` at the beginning). I checked the process tree and the bazel server is attached to `systemd`, but the second `cat` still waits for the server to shutdown.

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel shutdown;
( ( tools/bazel version ) | cat ) 3>&1 1>&2 2>&3  | cat
```

OR, here's a simplified version of my original build command that causes the issue. I am trying to `tee` stdout and stderr to different files.

```
( ( bazel build //foo:bar ) | tee stdout.txt ) 3>&1 1>&2 2>&3 | tee stderr.txt
``` 

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

From https://cs.android.com/android/kernel/superproject/+/common-android-mainline:prebuilts/bazel/linux-x86_64/

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Probably not

### Any other information, logs, or outputs that you want to share?

Workaround is to run `bazel version > /dev/null` right after `bazel shutdown` to start the bazel server not in a subshell.

**Comment by jacky8hyf** [comment]
Bazel version is https://cs.android.com/android/_/android/platform/prebuilts/bazel/linux-x86_64/+/b2cd3cd1fe6d7ad4f6ac6a49a6bf9fb381a818a2

**Comment by jacky8hyf** [comment]
We found a workaround by using something like this:

```
bazel build //foo:bar 1> >( tee stdout.txt ) 2> >( tee stderr.txt >&2 )
```

This is not urgent nor important for Kleaf now. We are just curious if this is an expected behavior.

**Comment by lberki** [comment]
This is really surprising.  I found a more minimal reproduction by the brainless approach of just deleting parts of your reproduction until it stops working:

`bazel shutdown; ( bazel info server_pid ) 3>&1 1>&2 2>&3  | cat`

but that doesn't give me any further insights as to why this is broken. At least replacing `version` with `info server_pid` allowed me to easily get a stack trace:

```
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.6/Native Method)
        - waiting on <0x00000000fd400000> (a java.lang.Object)
        at java.lang.Object.wait(java.base@11.0.6/Unknown Source)
        at io.grpc.internal.ServerImpl.awaitTermination(ServerImpl.java:320)
        - waiting to re-lock in wait() <0x00000000fd400000> (a java.lang.Object)
        at com.google.devtools.build.lib.server.GrpcServerImpl.serve(GrpcServerImpl.java:432)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1063)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:767)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:94)
```

which indicates that the server correctly finished serving the request, which means that this must be an issue on the client side.

**Comment by snakethatlovesstaticlibs** [comment]
Would this impact running `bazel` via `cmake`? It's possible that I'm also seeing this in a pipeline where the build finishes, but then hangs
