### ISSUE TITLE
riscv64 : Error building bazel from scratch

### ISSUE THREAD

**Issue by CoolKingYY** [bazelbuild/bazel#19331]
### Description of the bug:

ERROR: /tmp/bazel_LlLP4lR1/out/external/upb/upbc/BUILD:44:10: Linking external/upb/upbc/protoc-gen-upb [for tool] failed: (Exit 1): gcc failed: error executing command (from target @upb//upbc:protoc-gen-upb)
  (cd /tmp/bazel_LlLP4lR1/out/execroot/io_bazel && \
  exec env - \
    PATH=/home/fedora/.local/bin:/home/fedora/bin:/usr/local/gcc-12.2.0/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin \
    PWD=/proc/self/cwd \
  /usr/local/gcc-12.2.0/bin/gcc @bazel-out/riscv64-opt-exec-EDC14992/bin/external/upb/upbc/protoc-gen-upb-2.params)

### Which category does this issue belong to?

C++/Objective-C Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh -j32

### Which operating system are you running Bazel on?

Linux fedora-riscv 6.1.42 #1 SMP Fri Aug 18 02:30:30 CST 2023 riscv64 GNU/Linux

**Comment by Pavank1992** [comment]
@CoolKingYY, Could you please provide complete steps to reproduce this issue?

**Comment by CoolKingYY** [comment]
> @CoolKingYY，您能否提供重现此问题的完整步骤？

I've updated the question, do you need any other info?

**Comment by iancha1992** [comment]
@CoolKingYY do you have a repo that you can share so that we can reproduce the errors that you're seeing?

**Comment by CoolKingYY** [comment]
> @CoolKingYY您是否有可以分享的存储库，以便我们可以重现您所看到的错误？

### Now, an error is reported as follows：

**
ERROR: /home/fedora/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:169:23: JavacBootstrap src/java_tools/buildjar/java/com/gle/devtools/build/buildjar/libstarlark-deps.jar [for tool] failed: (Exit 1): bash failed: error executing command (from target //src/java_tools/buildjaava/com/google/devtools/build/buildjar:starlark-deps)
  (cd /tmp/bazel_0xQdH7bw/out/execroot/io_bazel && \
  exec env - \
    PATH=/bin:/home/fedora/.local/bin:/home/fedora/bin:/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/varb/snapd/snap/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jbuild_output bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_java bazout/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_java_list
mkdir bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output bazel-ouiscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_java
external/local_jdk/bin/javac  -classpath '\''third_party/auto/auto-value-1.8.2.jar:third_party/auto/auto-value-annotations-1.8.2.jar:derived/jars/com_goe_protobuf/java/core/libcore.jar:derived/jars/com_google_protobuf/java/core/liblite.jar:derived/jars/com_google_protobuf/java/util/libutil.jar:derived/j/zstd-jni/libzstd-jni.jar:third_party/error_prone/error_prone_annotations-2.20.0.jar:third_party/error_prone/threeten-extra-1.5.0.jar:third_party/guava/va-31.1-jre.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/java/jacoco/org.jacoco.core-0.8.7.jarird_party/grpc-java/grpc-api-1.45.1.jar:third_party/grpc-java/grpc-api-1.47.0.jar:third_party/grpc-java/grpc-auth-1.45.1.jar:third_party/grpc-java/grpc-h-1.47.0.jar:third_party/grpc-java/grpc-context-1.45.1.jar:third_party/grpc-java/grpc-context-1.47.0.jar:third_party/grpc-java/grpc-core-1.45.1.jar:thirarty/grpc-java/grpc-core-1.47.0.jar:third_party/grpc-java/grpc-netty-1.45.1.jar:third_party/grpc-java/grpc-netty-1.47.0.jar:third_party/grpc-java/grpc-pobuf-1.45.1.jar:third_party/grpc-java/grpc-protobuf-1.47.0.jar:third_party/grpc-java/grpc-protobuf-lite-1.45.1.jar:third_party/grpc-java/grpc-protobuf-l-1.47.0.jar:third_party/grpc-java/grpc-stub-1.45.1.jar:third_party/grpc-java/grpc-stub-1.47.0.jar:third_party/tomcat_annotations_api/tomcat-annotations--8.0.5.jar'\'' -d bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_out @bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar-2.params
external/local_jdk/bin/jar cf bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.j-C bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output .
touch bazel-out/riscv64-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libstarlark-deps.jar.build_output
')
# Configuration: fa0af6636a47b9bd34c9376022c62e6bb7a91b65435b12dc1052c57bbe67ab9a
# Execution platform: //:default_host_platform
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.HashMap.resize(HashMap.java:699)
        at java.base/java.util.HashMap.putVal(HashMap.java:624)
        at java.base/java.util.HashMap.put(HashMap.java:607)
        at java.base/java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:204)
        at java.base/java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:555)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:220)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:166)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Log.localize(Log.java:810)
        at jdk.compiler/com.sun.tools.javac.util.Log.printLines(Log.java:608)
        at jdk.compiler/com.sun.tools.javac.main.Main.resourceMessage(Main.java:414)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:326)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 4170.143s, Critical Path: 1455.85s
INFO: 1902 processes: 330 internal, 1572 local.
FAILED: Build did NOT complete successfully
**

_[fedora@fedora-riscv bazel]$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Zero VM 18.9 (build 11.0.11+9, interpreted mode)_

**Comment by CoolKingYY** [comment]
> @CoolKingYY do you have a repo that you can share so that we can reproduce the errors that you're seeing?

Hi, the reason for the first problem is that I didn't handle the soft links for gcc12 as well as for java-11-openjdk.

**Comment by CoolKingYY** [comment]
Thanks to the help of bazel techs, this issue has been resolved and closed.

**Comment by pourpourr** [comment]
Hi can you explain further what you did and you fixxed it?
