### ISSUE TITLE
Error using multidex='native' with android_binary

### ISSUE THREAD

**Issue by zvh** [bazelbuild/bazel#1936]
When I try using multidex='native' in my android_binary rule I get:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://java/com/android/dialer:dialer ca510958d69683c1784639d54cbec906 (1133577026 1901055024)' (requested by nodes )
INFO: Elapsed time: 0.249s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://java/com/android/dialer:dialer ca510958d69683c1784639d54cbec906 (1133577026 1901055024)' (requested by nodes )
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:430)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: android_binary attribute $zip is not defined
    at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:858)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.createCleanDexZipAction(AndroidBinary.java:1408)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.dex(AndroidBinary.java:1200)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.createAndroidBinary(AndroidBinary.java:424)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.init(AndroidBinary.java:355)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.create(AndroidBinary.java:114)
    at com.google.devtools.build.lib.rules.android.AndroidBinary.create(AndroidBinary.java:86)
    at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:271)
    at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:171)
    at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:488)
    at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:984)
    at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:238)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:371)
    ... 4 more

```

Also note that if I don't use multidex I get:
..........

```
INFO: Found 1 target...
ERROR: /tmp/tmpnS5HYi/java/com/android/dialer/BUILD:7:1: Converting bazel-out/local-fastbuild/bin/java/com/android/dialer/dialer_deploy.jar to dex format failed: linux-sandbox failed: error executing command /usr/local/google/home/zachh/.cache/bazel/_bazel_zachh/d27fe19dac8bfc48db48176258f08bb5/execroot/tmpnS5HYi/_bin/linux-sandbox ... (remaining 7 argument(s) skipped).

trouble writing output: Too many field references: 66196; max is 65536.
You may try using --multi-dex option.

```

But "--multi-dex" is not a flag AFAICT; should this message be changed to say "multidex attribute"?

**Comment by aj-michael** [comment]
Unfortunately, multidex is not yet supported in Bazel. Specifically, https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/android/AndroidBinary.java#L1435 is using an attribute `$zip` that is not defined in `AndroidBinaryBaseRule.java`. `$zip` either needs to be added or that method changed to use singlejar.

**Comment by aj-michael** [comment]
In case anyone runs into this, it can currently be worked around by using the `--experimental_android_use_singlejar_for_multidex` flag.

**Comment by cwoodwar6** [comment]
@aj-michael Is there a timeline for multidex support?

**Comment by aj-michael** [comment]
@cwoodwar6 As I mentioned above, multidex support works if you use the `--experimental_android_use_singlejar_for_multidex` build flag, e.g. `bazel build --experimental_android_use_singlejar_for_multidex //java/com/example:app`. I would recommend putting this in a [`.bazelrc`](https://bazel.build/versions/master/docs/bazel-user-manual.html#bazelrc) file so that you don't have to type that out all the time.

The only changes to Bazel to stop requiring this flag is for me to change the default value for this flag here:
https://github.com/bazelbuild/bazel/blob/304da48921ebca7a1948dac787c7cb95e31cc381/src/main/java/com/google/devtools/build/lib/rules/android/AndroidConfiguration.java#L407

I don't have a timeline as for when that will be changed, as it affects both the open source Bazel and the internal version, and changing things in the internal version can take a bit more time.

**Comment by mhlopko** [comment]
Hello Adam and Alex, is this still expected to be fixed in 0.5? It's still at least 2 weeks away, but we're getting there :)

**Comment by aj-michael** [comment]
I will try to roll this out this week.

**Comment by aj-michael** [comment]
Ok, the change for this is in-flight. It should be in in the next day or two.

**Comment by mhlopko** [comment]
Thanks Adam, that's awesome!
