### ISSUE TITLE
java_library javacopts not passed to header compiler

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#19360]
### Description of the bug:

Turbine header compiler fails to compile java_library with annotation processor because annotation processor options from javacopts are not passed to the header compiler.

```
java_library(
  name = "A",
  plugins = ["//some/plugin"],
  javacopts = [
    "-Asome.annotation.processor.option=true",
  ]
)
```

Bazel fails with:

```
ERROR: .. Compiling Java headers ... and running annotation processors (MyGenerator, ..., ...) failed: (Exit 1): java failed: error executing command ...

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
<>: error: An exception occurred in MyGenerator:
java.lang.IllegalArgumentException: Property some.annotation.processor.option not set! 
	at MyGenerator.init(...)
	at com.google.turbine.binder.Processing.process(Processing.java:131)
	at com.google.turbine.binder.Binder.bind(Binder.java:107)
	at com.google.turbine.main.Main.bind(Main.java:270)
	at com.google.turbine.main.Main.compile(Main.java:162)
	at com.google.turbine.main.Main.compile(Main.java:133)
	at com.google.turbine.main.Main.main(Main.java:89)
```

### Which category does this issue belong to?

Java Rules

### What is the output of `bazel info release`?

6.3.2

**Comment by hvadehra** [comment]
Considering that the java rules tokenize javacopts, I would expect 
```
  javacopts = [
    "-Asome.annotation.processor.option=vale1,value2, value3",
  ]
```
to fail with an error like `error: invalid flag: value3`

@guw Does this need something more to reproduce?

**Comment by guw** [comment]
@hvadehra Not that I am aware of. Which tokenization are you referring to? Do you have a link to the code?

**Comment by hvadehra** [comment]
https://github.com/bazelbuild/bazel/blob/5932bee129b189baa5e4cbec116176b2f15d723e/src/main/java/com/google/devtools/build/lib/rules/java/JavaHelper.java#L98C39-L98C58

**Comment by guw** [comment]
Ah ... thanks for sharing that code. I omitted a tiny detail: `'`. Here is how the annotation processor option is actually being populated in our macro.

```
   javacopts.append("-Asome.annotation.processor.option='%s'" % generator.get("option"))
```

The correct value is:
```
  javacopts = [
    "-Asome.annotation.processor.option='vale1,value2, value3'",
  ]
```

This is handled/supported by the [tokenization](https://github.com/bazelbuild/bazel/blob/6d1fefff9f3bec13b07bb149a05eccf59a54f3ef/src/main/java/com/google/devtools/build/lib/shell/ShellUtils.java#L90).
