### ISSUE TITLE
NPE with --profile on OS X with bazel 0.3.2 

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1942]
In protobuf: NPE with --watchfs and --profile on OS X with bazel 0.3.2

```
$ bazel build :protoc --profile=/tmp/protoc.profile
INFO: Reading 'startup' options from /Users/dmarting/.bazelrc: --watchfs
................
INFO: Writing profile data to '/tmp/protoc.profile'
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes 'REPOSITORY:@local_config_xcode')
INFO: Elapsed time: 1.304s
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes 'REPOSITORY:@local_config_xcode')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:447)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception while processing @SkylarkSignature.Param timeout, default value 600
	at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:185)
	at com.google.devtools.build.lib.syntax.FuncallExpression.convertArgumentList(FuncallExpression.java:480)
	at com.google.devtools.build.lib.syntax.FuncallExpression.findJavaMethod(FuncallExpression.java:384)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:706)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:759)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:774)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.BinaryOperatorExpression.doEval(BinaryOperatorExpression.java:143)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.AssignmentStatement.doExec(AssignmentStatement.java:62)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.IfStatement$ConditionalStatements.doExec(IfStatement.java:55)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.IfStatement.doExec(IfStatement.java:128)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:100)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:129)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:388)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:731)
	at com.google.devtools.build.lib.profiler.Profiler.logSimpleTask(Profiler.java:780)
	at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:114)
	at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:123)
	at com.google.devtools.build.lib.syntax.Parser.parseFileForSkylark(Parser.java:235)
	at com.google.devtools.build.lib.syntax.BuildFileAST.parseSkylarkString(BuildFileAST.java:333)
	at com.google.devtools.build.lib.syntax.Environment.eval(Environment.java:953)
	at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:183)
	... 30 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes 'REPOSITORY:@local_config_xcode')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:447)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception while processing @SkylarkSignature.Param timeout, default value 600
	at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:185)
	at com.google.devtools.build.lib.syntax.FuncallExpression.convertArgumentList(FuncallExpression.java:480)
	at com.google.devtools.build.lib.syntax.FuncallExpression.findJavaMethod(FuncallExpression.java:384)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:706)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:759)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:774)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:745)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.BinaryOperatorExpression.doEval(BinaryOperatorExpression.java:143)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.AssignmentStatement.doExec(AssignmentStatement.java:62)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.IfStatement$ConditionalStatements.doExec(IfStatement.java:55)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.IfStatement.doExec(IfStatement.java:128)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:443)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:100)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:129)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:388)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.profiler.Profiler.logTask(Profiler.java:731)
	at com.google.devtools.build.lib.profiler.Profiler.logSimpleTask(Profiler.java:780)
	at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:114)
	at com.google.devtools.build.lib.syntax.Lexer.<init>(Lexer.java:123)
	at com.google.devtools.build.lib.syntax.Parser.parseFileForSkylark(Parser.java:235)
	at com.google.devtools.build.lib.syntax.BuildFileAST.parseSkylarkString(BuildFileAST.java:333)
	at com.google.devtools.build.lib.syntax.Environment.eval(Environment.java:953)
	at com.google.devtools.build.lib.syntax.SkylarkSignatureProcessor.getDefaultValue(SkylarkSignatureProcessor.java:183)
	... 30 more
```

**Comment by damienmg** [comment]
removing --watchfs keep the NPE

**Comment by damienmg** [comment]
with a clean --expunge before it is 100% reproducible

**Comment by damienmg** [comment]
Ok this is not reproducible at HEAD.

**Comment by damienmg** [comment]
faster repro with fetch instead of build.

**Comment by damienmg** [comment]
Ok this was already signaled as blocker for 0.3.2 but wasn't cherry-picked apparently. See #1865

**Comment by damienmg** [comment]
Closing as this will be fixed by the new release, sad we forgot to cherry-pick it
