### ISSUE TITLE
Error: key "generatedRepoSpecs" not found in dictionary at HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#19506]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3303#018a8c4d-a786-404a-9daa-e4c5abacf2ae

Platform : MacOS, Windows, Ubuntu

Logs:
```
ERROR: An error occurred during the fetch of repository '_main~bazel_build_deps~bootstrap_repo_cache':
   Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-9/bazel-downstream-projects/bazel/distdir.bzl", line 88, column 42, in _repo_cache_tar_impl
		http_artifacts = parse_http_artifacts(ctx, lockfile_path, ctx.attr.repos)
	File "/Users/buildkite/builds/bk-imacpro-9/bazel-downstream-projects/bazel/src/tools/bzlmod/utils.bzl", line 80, column 38, in parse_http_artifacts
		for _, repo_spec in extension["generatedRepoSpecs"].items():
Error: key "generatedRepoSpecs" not found in dictionary
(04:18:08) ERROR: <builtin>: fetching repo_cache_tar rule //:_main~bazel_build_deps~bootstrap_repo_cache: Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-9/bazel-downstream-projects/bazel/distdir.bzl", line 88, column 42, in _repo_cache_tar_impl
		http_artifacts = parse_http_artifacts(ctx, lockfile_path, ctx.attr.repos)
	File "/Users/buildkite/builds/bk-imacpro-9/bazel-downstream-projects/bazel/src/tools/bzlmod/utils.bzl", line 80, column 38, in parse_http_artifacts
		for _, repo_spec in extension["generatedRepoSpecs"].items():
Error: key "generatedRepoSpecs" not found in dictionary

```

Culprit : https://github.com/bazelbuild/bazel/commit/b27ca73617c5319d4b15a9e5ba499cf476679a95

CC Greenteam @meteorcloudy

**Comment by meteorcloudy** [comment]
Thanks for reporting, I'll fix this.
