### ISSUE TITLE
AbstractActionInputPrefetcher does not always finish before the action whose inputs it prefetches starts executing

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#19579]
### Description of the bug:

Sometimes `chmod()` calls are observed from `AbstractActionInputPrefetcher` after the action on behalf of which it runs starts executing. Some impressive debugging work resulted in this stack trace:

```
   java.lang.Thread.State: RUNNABLE
	at com.google.devtools.build.lib.unix.NativePosixFiles.chmod(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.chmod(UnixFileSystem.java:314)
	at com.google.devtools.build.lib.vfs.Path.chmod(Path.java:883)
	at com.google.devtools.build.lib.remote.AbstractActionInputPrefetcher$DirectoryContext.lambda$close$2(AbstractActionInputPrefetcher.java:195)
	at com.google.devtools.build.lib.remote.AbstractActionInputPrefetcher$DirectoryContext$$Lambda$1483/0x00000008009c7040.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.6/Unknown Source)
	- locked <0x0000000453ba6420> (a java.util.concurrent.ConcurrentHashMap$Node)
	at com.google.devtools.build.lib.remote.AbstractActionInputPrefetcher$DirectoryContext.close(AbstractActionInputPrefetcher.java:188)
	at com.google.devtools.build.lib.remote.AbstractActionInputPrefetcher$$Lambda$1449/0x00000008009ae040.accept(Unknown Source)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableUsing$UsingObserver.onComplete(CompletableUsing.java:180)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:68)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableEmpty.subscribeActual(CompletableEmpty.java:27)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:120)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:92)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.innerSuccess(FlowableFlatMapSingle.java:178)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber$InnerObserver.onSuccess(FlowableFlatMapSingle.java:342)
	at io.reactivex.rxjava3.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onComplete(CompletableToSingle.java:67)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onSuccess(CompletableFromSingle.java:51)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.google.devtools.build.lib.remote.util.AsyncTaskCache$1.onSuccess(AsyncTaskCache.java:333)
	at com.google.devtools.build.lib.remote.util.AsyncTaskCache$Execution.onSuccess(AsyncTaskCache.java:186)
	- locked <0x00000000a060c678> (a java.lang.Object)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onComplete(CompletableToSingle.java:67)
	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableUsing$UsingObserver.onComplete(CompletableUsing.java:191)
	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:65)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:85)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe$1.onSuccess(RxFutures.java:82)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:119)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:167)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:119)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:119)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
	at com.google.devtools.build.lib.remote.util.RxFutures$2.onSuccess(RxFutures.java:249)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:112)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceSingleOnSubscribe$1.onSuccess(RxFutures.java:155)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
	at com.google.devtools.build.lib.remote.GrpcCacheClient$1.onCompleted(GrpcCacheClient.java:443)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:476)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.devtools.build.lib.remote.NetworkTimeInterceptor$NetworkTimeCall$1.onClose(NetworkTimeInterceptor.java:81)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/Unknown Source)
	at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

, which was captured by trapping `chmod()` calls on inputs of an action after the action starts executing

The stack trace in itself is not a surefire indication that there is a race condition because there can be other actions whose inputs are being prefetched while the action in question is running, but the above `chmod()` machinery excludes this possibility.

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately, there is none. I tried to run a stress test with Bazel@HEAD and this did not trigger after 10M downloads, so it's either fixed at HEAD or I got unlucky,

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

bazel 6.2.0 (from https://releases.bazel.build/6.2.0/release/bazel-6.2.0-linux-x86_64)

### Any other information, logs, or outputs that you want to share?

This bug was spawned from (Google-internal) link b/290829535 after we ascertained that this is in fact an issue with Bazel.

More logs (including stacks for all threads) available [here](https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket/8769363540182137873/+/u/install_packages/call_chromite.api.SysrootService_InstallPackages/call_build_API_script/stdout) .

**Comment by lberki** [comment]
I tried to do so some stress testing to reproduce this in a controlled environment, without success. I tried ~10M downloads of tiny files, ~10M downloads of 1MB files and ~1M downloads of 100MB files, all succeeding, all with Bazel 6.2.0 in case this issue got fixed in the meantime.

**Comment by tjgq** [comment]
@coeuvre and I narrowed this down. Minimal repro:
```
*** defs.bzl ***
def _tree_impl(ctx):
  out = ctx.actions.declare_directory(ctx.label.name)
  ctx.actions.run_shell(
    mnemonic = "Tree",
    outputs = [out],
    command = "for i in `seq %s`; do echo hello > %s/file${i}.txt; done" % (ctx.attr.num_files, out.path),
  )
  return DefaultInfo(files = depset([out]))

tree = rule(
    implementation = _tree_impl,
    attrs = {"num_files": attr.int()},
)

*** BUILD ***
load(":defs.bzl", "tree")

N = 1000

tree(
  name = "tree",
  num_files = N,
)

[genrule(
  name = "gen{}".format(i),
  srcs = [":tree"],
  outs = ["gen{}".format(i)],
  cmd = """if [[ -w $< ]]; then echo "tree is writable"; exit 1; fi; touch $@""",
  tags = ["no-remote", "no-cache"],
) for i in range(N)]

filegroup(
  name = "fg",
  srcs = ["gen{}".format(i) for i in range(N)],
)

*** .bazelrc ***
build --genrule_strategy=standalone
build --jobs=1000
build --disk_cache=disk_cache
build --remote_download_minimal
```

In short: a tree artifact with 1k files is produced and then consumed by 1k parallel genrules. The genrules must run without sandboxing and cause the tree artifact to be prefetched from a remote/disk cache. So you need to `build :fg` once to populate the disk cache with the tree artifact, `clean`, then `build :fg` again. The repro is expected to **fail** and print `tree is writable` when the bug is present; the bug is still present at head.

The root cause is as follows: each genrule will attempt to prefetch the tree artifact; every such call to the prefetcher has an associated `DirectoryContext`. The intended purpose of the `DirectoryContext` is to keep a count of the number of times a tree artifact has been made writable (to avoid redundant filesystem operations) and automatically make it readonly when the count reaches zero. However, the `close` method as implemented is buggy: if the count is greater than 1, it merely decrements it and lets the respective action proceed, without waiting for it to reach 0.

The actual fix is probably going to be more complex than simply having `close` wait for the count to reach 0, because we suspect this would unnecessarily slow things down for non-tree artifacts (even though non-tree directories don't have to be made readonly, it's possible for a fileset or nested artifact to refer to a file inside a tree artifact without marking it as such, forcing all files to participate in the locking scheme).

**Comment by lberki** [comment]
I have two questions, mostly for my education:

1. Can we get away with not worrying about nested artifacts? `--incompatible_strict_conflict_checks` now defaults to true and will be removed in Bazel 7.0 (hopefully), so it's becoming more and more of a niche use case (and it was an abuse of Bazel to begin with)
2. Why do Filesets need to be considered? Those are legacy functionality we are working to remove from the Google monorepo and they are unavailable in Bazel, but we don't have the RBE interface in said monorepo so I'd think that there is no use case where both `AbstractActionInputPrefetcher` and Filesets are available.

**Comment by tjgq** [comment]
> 1. Can we get away with not worrying about nested artifacts? `--incompatible_strict_conflict_checks` now defaults to true and will be removed in Bazel 7.0 (hopefully), so it's becoming more and more of a niche use case (and it was an abuse of Bazel to begin with)

Yes, I will remove support for nested artifacts (i.e. hardcode `--incompatible_strict_conflict_checks` once the 7.0.0 release branch is cut. For 6.x, if we ever backport a fix for this issue, we need not worry about correctness in the presence of nested artifacts, we only need to ensure that builds don't crash. So it's fine if the post-fetching permissions are incorrect (this is already the case today) but the prefetcher still needs to synchronize on their parent directory, otherwise it might get an EACCESS.

> 2. Why do Filesets need to be considered? Those are legacy functionality we are working to remove from the Google monorepo and they are unavailable in Bazel, but we don't have the RBE interface in said monorepo so I'd think that there is no use case where both `AbstractActionInputPrefetcher` and Filesets are available.

The `AbstractActionInputPrefetcher` is used by the internal equivalent of build-without-the-bytes, and we'd prefer to keep sharing the core of the prefetcher internally and externally (so the core must care about filesets).

**Comment by lberki** [comment]
> The `AbstractActionInputPrefetcher` is used by the internal equivalent of build-without-the-bytes, and we'd prefer to keep sharing the core of the prefetcher internally and externally (so the core must care about filesets).

Thanks, that's what I was missing. Then at least regular files (which are the overwhelming majority) get by without expensive locking wouldn't they?

**Comment by tjgq** [comment]
> > The `AbstractActionInputPrefetcher` is used by the internal equivalent of build-without-the-bytes, and we'd prefer to keep sharing the core of the prefetcher internally and externally (so the core must care about filesets).
> 
> Thanks, that's what I was missing. Then at least regular files (which are the overwhelming majority) get by without expensive locking wouldn't they?

If we can reliably identify that an artifact belongs to a fileset, yes. Currently they're `BasicActionInput`s created out of thin air by the `SpawnInputExpander`, which might (?) be mistaken for other things, but we could introduce another `ActionInput` implementation to make them unambigous. Alternatively (as we've just discussed over lunch :)) we could try to properly track artifacts in the fileset implementation, but this is a bit of a speculative project.

**Comment by lberki** [comment]
At least in the long term, I think tracking the enclosing `TreeArtifact` with each `ActionInput` is the right thing to do; otherwise, you'll be working around the fact that you don't have it.

**Comment by tjgq** [comment]
This has been fixed in e38f44d.
