### ISSUE TITLE
Bazel server crash when using the C++ Starlark API

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#19620]
### Description of the bug:

`cc_common.compile` throws an exception with the following stack trace:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//missing_file:hello_bug, config=BuildConfigurationKey[442d8db79c046018027f86fb6ba2e9e3560c56c0504c8b6423d08c7d06207c4d]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalStateException thrown during Starlark evaluation (//missing_file:hello_bug)
        at <starlark>.compile(<builtin>:0)
        at <starlark>._my_binary(/usr/local/google/home/lberki/bazel/cfrantz/bazel6/rules/defs.bzl:34)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
        at com.google.devtools.build.lib.rules.cpp.CcCompilationHelper.addSource(CcCompilationHelper.java:579)
        at com.google.devtools.build.lib.rules.cpp.CcCompilationHelper.addSources(CcCompilationHelper.java:512)
        at com.google.devtools.build.lib.rules.cpp.CcModule.compile(CcModule.java:2267)
        at com.google.devtools.build.lib.bazel.rules.cpp.BazelCcModule.compile(BazelCcModule.java:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
        at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
        at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
        at net.starlark.java.eval.Eval.eval(Eval.java:497)
        at net.starlark.java.eval.Eval.execAssignment(Eval.java:109)
        at net.starlark.java.eval.Eval.exec(Eval.java:268)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
        at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
        at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.buildRule(StarlarkRuleConfiguredTargetUtil.java:99)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:363)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:192)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1231)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1218)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:431)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
...
```

I also tried with Bazel at HEAD, but it doesn't work because one needs how to depend on the C++ toolchain as a toolchain and I ran out of time today so I couldn't update it.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone this repository (I used commithash `1d206d36ca`): 

https://github.com/cfrantz/bugs/

Then:

```
cd bazel6
bazel build //missing_file:hello_bug
```

### Which operating system are you running Bazel on?

gLinux

### What is the output of `bazel info release`?

bazel 6.3.2

**Comment by cfrantz** [comment]
We have determined that the crash is provoked by having a header file listed in the `srcs` passed to `cc_common.compile` (thanks to @pamaury for investigating this further). 

If one separates the input files into sources and headers and passes them appropriately to `compile` (via srcs and private_hdrs), then bazel doesn't crash but rather reports a missing file:
```
ERROR: src/bugs/bazel6/missing_file/BUILD:13:10: Middleman _middlemen/_S_Smissing_Ufile_Chello_Ubug-BazelCppSemantics_build_arch_k8-fastbuild failed: missing input file '//missing_file:missing.h'
ERROR: src/bugs/bazel6/missing_file/BUILD:13:10: Middleman _middlemen/_S_Smissing_Ufile_Chello_Ubug-BazelCppSemantics_build_arch_k8-fastbuild failed: 1 input file(s) do not exist
```

**Comment by lberki** [comment]
@cfrantz is this causing pain for you? (I'm assuming it doesn't, but if it does, let us know and we'll try to prioritize it)

**Comment by cfrantz** [comment]
> @cfrantz is this causing pain for you? (I'm assuming it doesn't, but if it does, let us know and we'll try to prioritize it)

No, we've worked around this problem as described in my last comment.  Just providing the additional information we discovered.  I don't think the problem is the fact that the header file is missing, but rather that a header file gets passed to `srcs` instead of `hdrs` or `private_hdrs`.
