### ISSUE TITLE
Bazel creates an empty lockfile and crashes in subsequent invocation

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#19672]
I'm having the same exact issue with a very minimal example ([repro.zip](https://github.com/bazelbuild/bazel/files/12752816/repro.zip)) that sets up a simple python binary. No custom `.bazelrc` at all.

Running:
```
bazel run --enable_bzlmod --lockfile_mode=update //:main
```

Results in the creation of a MODULE.bazel.lock file that contains an empty JSON object:
```
{}
```

The next attempt to run the bazel command above results in the following crash:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue$$Lambda$219/0x00000008002a1440@4b69424b' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphValue$$Lambda$361/0x00000008004c0840@2403fbb8')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: Failed to invoke public com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileFunction.getLockfileValue(BazelLockFileFunction.java:101)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileFunction.compute(BazelLockFileFunction.java:79)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
	... 7 more
Caused by: java.lang.InstantiationException
	at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)
	... 15 more
```

Bazel version:
```bash
> bazel --version
bazel 6.3.2-homebrew
```

macOS version:
```bash
> sw_vers
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
```

_Originally posted by @csmulhern in https://github.com/bazelbuild/bazel/issues/18455#issuecomment-1739824415_

**Comment by Wyverald** [comment]
I can't actually reproduce this. Running the command you posted gives me a full-fledged lockfile.

Furthermore, manually editing the MODULE.bazel.lock file to have the contents of `{}` and running that same command, I get the proper error message:

```
ERROR: Error computing the main repository mapping: Failed to read and parse the MODULE.bazel.lock file with error: java.lang.IllegalStateException: Missing required properties: moduleFileHash flags localOverrideHashes moduleDepGraph. Try deleting it and rerun the build.
```

@csmulhern , could you try reproducing using [Bazelisk](https://github.com/bazelbuild/bazelisk)? Maybe the Homebrew formula is somehow borked?

**Comment by Wyverald** [comment]
cc @SalmaSamy @meteorcloudy

**Comment by csmulhern** [comment]
Thanks for the quick response, @Wyverald.

I downloaded the Bazel release directly from GitHub (https://github.com/bazelbuild/bazel/releases/download/6.3.2/bazel-6.3.2-darwin-arm64), and this does appear to be fixed. It does look like it's the homebrew distribution that's broken.

Thanks for helping me find the root cause.

**Comment by Wyverald** [comment]
Thanks for confirming!

**Comment by avdv** [comment]
I am also seeing this with Bazel 6.4.0 from nixpkgs (see https://github.com/NixOS/nixpkgs/issues/273500). So this seems to be some kind of packaging problem. Has anyone an idea what might be causing this? TIA !

**Comment by avdv** [comment]
This is a problem that turns up when you bootstrap bazel from scratch; I have opened a new issue: https://github.com/bazelbuild/bazel/issues/20501
