### ISSUE TITLE
HardlinkedExecRoot fails when an input is a directory

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1974]
If a target has a directory in its inputs, HardlinkedExecRoot sometimes seems to fail, because when it tries to create a symlink to it in the line: "symlinkName.createSymbolicLink(hardlinkName)", it already exists. I noticed this while fixing the broken bazel_toolchain_test.

@hermione521 Could you write a test for this and then try to fix the issue? To reproduce, you could revert my fix to the bazel_toolchain_test and then figure out what's going wrong there.

I'll add the commit hash of my fix here, once it has been pushed.

This is the stack trace I got while debugging this:

```
java.io.IOException: /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/bazel-sandbox/997ef66a-0b89-48cc-ba49-d898bfd7ed92-0/execroot/bazel/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_toolchain_test.runfiles/io_bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler (File exists)
  at com.google.devtools.build.lib.unix.NativePosixFiles.symlink(Native Method)
  at com.google.devtools.build.lib.vfs.UnixFileSystem.createSymbolicLink(UnixFileSystem.java:323)
  at com.google.devtools.build.lib.vfs.Path.createSymbolicLink(Path.java:785)
  at com.google.devtools.build.lib.sandbox.HardlinkedExecRoot.linkInputs(HardlinkedExecRoot.java:123)
  at com.google.devtools.build.lib.sandbox.HardlinkedExecRoot.createFileSystem(HardlinkedExecRoot.java:65)
  at com.google.devtools.build.lib.sandbox.DarwinSandboxedStrategy.exec(DarwinSandboxedStrategy.java:193)
  at com.google.devtools.build.lib.sandbox.DarwinSandboxedStrategy.exec(DarwinSandboxedStrategy.java:148)
  at com.google.devtools.build.lib.rules.test.StandaloneTestStrategy.execute(StandaloneTestStrategy.java:196)
  at com.google.devtools.build.lib.rules.test.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:140)
  at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:42)
  at com.google.devtools.build.lib.rules.test.TestRunnerAction.execute(TestRunnerAction.java:523)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:780)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:720)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:101)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:610)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:572)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:377)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:411)
  at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:195)
  at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
  at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by hermione521** [comment]
Is the fix done?

**Comment by philwo** [comment]
I can't remember what this was about. Closing for now.
