### ISSUE TITLE
BEP referenced local file (Is a directory) warning with --nozip_undeclared_test_outputs

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#19847]
When running a test with remote execution, BEP enabled, and `--nozip_undeclared_test_outputs`, an error like this is produced:

```
WARNING: Uploading BEP referenced local file /home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/execroot/jazzer/bazel-out/k8-opt/testlogs/sanitizers/src/test/java/com/example/XPathInjection/test.outputs: /home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/execroot/jazzer/bazel-out/k8-opt/testlogs/sanitizers/src/test/java/com/example/XPathInjection/test.outputs (Is a directory)
```

This is likely because we declare the undeclared outputs directory as a regular file, so the BEP code doesn't know that it's a directory and must be expanded. The principled fix here is to declare it as a tree artifact instead, but that requires forking the declaration for the zip and non-zip case (for Google reasons, we can't produce a tree artifact containing the zip file in the zip case). If the principled fix isn't possible, it might be okay to have the BEP code traverse directories even when the artifact is declared as a file.

**Comment by tjgq** [comment]
It's because the undeclared outputs directory comes from a `TestAttempt` and we currently don't propagate the tree artifact metadata (or indeed any output metadata) there: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/test/TestAttempt.java;l=205?q=testattempt.java&ss=bazel%2Fbazel

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC2](https://releases.bazel.build/7.0.0/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by layus** [comment]
Probably unrelated, but I am trying to port our build to bazel 7.0.0rc2, and I get tons of these:

```
WARNING: Uploading BEP referenced local file $outputBase/external/rules_nixpkgs_generated_repo/include/net : $outputBase/external/rules_nixpkgs_generated_repo/include/net (Is a directory)
java.io.FileNotFoundException: $outputBase/external/rules_nixpkgs_generated_repo/include/net (Is a directo
ry)                                                                                                                                                                                                                 
        at java.base/java.io.FileInputStream.open0(Native Method)                                                                                                                                                   
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)                                                                                                                                         
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)                                                                                                                                       
        at com.google.devtools.build.lib.unix.UnixFileSystem.createFileInputStream(UnixFileSystem.java:497)               
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.createMaybeProfiledInputStream(AbstractFileSystem.java:90)                                                                                          
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.getInputStream(AbstractFileSystem.java:59) 
        at com.google.devtools.build.lib.vfs.FileSystem$1.openStream(FileSystem.java:350)
        at com.google.common.io.ByteSource.copyTo(ByteSource.java:256)                                                                                                                                              
        at com.google.common.io.ByteSource.hash(ByteSource.java:340)                           
        at com.google.devtools.build.lib.vfs.FileSystem.getDigest(FileSystem.java:352)         
        at com.google.devtools.build.lib.unix.UnixFileSystem.getDigest(UnixFileSystem.java:453)                                                                                                                     
        at com.google.devtools.build.lib.vfs.Path.getDigest(Path.java:690)                                                                                                                                          
        at com.google.devtools.build.lib.remote.RemoteActionFileSystem.getDigest(RemoteActionFileSystem.java:365)                                                                                                   
        at com.google.devtools.build.lib.vfs.Path.getDigest(Path.java:690)                                                                                                                                          
        at com.google.devtools.build.lib.vfs.DigestUtils.manuallyComputeDigest(DigestUtils.java:200)                                                                                                                
        at com.google.devtools.build.lib.vfs.DigestUtils.getDigestWithManualFallback(DigestUtils.java:160)                                                                                                          
        at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:72)                                                                                                                         
        at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:67)                                                                                                                         
        at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:239)                                           
        at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.lambda$doUpload$8(ByteStreamBuildEventArtifactUploader.java:413)                                        
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)                            
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:185)                                                                       
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129)                                                                      
        at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)                                           
        at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle$CollectorSingleObserver.onSubscribe(FlowableCollectWithCollectorSingle.java:102)
        at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)     
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.jdk8.FlowableCollectWithCollectorSingle.subscribeActual(FlowableCollectWithCollectorSingle.java:71)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83) 
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

In our case fixing the glob patterns to not include directories, or removing `exclude_directories=0` in glob fixed the issue.
Just in case someone lands here like me.
