### ISSUE TITLE
Bazel Java tests fail on ubuntu2204 with JDK 17

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#19850]
### Description of the bug:

In https://bazel-review.googlesource.com/c/bazel/+/220425, I'm trying to drop ubuntu 1804 since it's EOL and add ubuntu 2204.

However some Java tests are failing with
```
1) smoke(com.google.devtools.build.lib.skyframe.serialization.FileSymlinkExceptionCodecTest)
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.google.devtools.build.lib.skyframe.serialization.AutoRegistry.create(AutoRegistry.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at com.google.devtools.build.lib.skyframe.serialization.AutoRegistry.get(AutoRegistry.java:80)
	at com.google.devtools.build.lib.skyframe.serialization.testutils.SerializationTester.createObjectCodecs(SerializationTester.java:163)
	at com.google.devtools.build.lib.skyframe.serialization.testutils.SerializationTester.runTests(SerializationTester.java:134)
	at com.google.devtools.build.lib.skyframe.serialization.testutils.SerializationTester.runTests(SerializationTester.java:143)
	at com.google.devtools.build.lib.skyframe.serialization.FileSymlinkExceptionCodecTest.smoke(FileSymlinkExceptionCodecTest.java:51)
	... 25 trimmed
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.google.devtools.build.lib.skyframe.serialization.CodecScanner.processLikelyCodec(CodecScanner.java:82)
	at com.google.devtools.build.lib.skyframe.serialization.CodecScanner.initializeCodecRegistry(CodecScanner.java:59)
	at com.google.devtools.build.lib.skyframe.serialization.AutoRegistry.create(AutoRegistry.java:86)
	... 32 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Object java.lang.invoke.SerializedLambda.readResolve() throws java.io.ObjectStreamException accessible: module java.base does not "opens java.lang.invoke" to unnamed module @62bd2070
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.google.devtools.build.lib.skyframe.serialization.LambdaCodec.<init>(LambdaCodec.java:45)
	... 40 more
```
See more at https://buildkite.com/bazel/google-bazel-presubmit/builds/72890

The major difference is that on ubuntu 2204, we have JDK 17 installed, the docker image is `gcr.io/bazel-public/ubuntu2204-java17`

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
docker run -it gcr.io/bazel-public/ubuntu2204-java17

# clone bazel repo

bazel test //src/test/java/com/google/devtools/build/lib/skyframe/serialization:FileSymlinkExceptionCodecTest
```

**Comment by cushon** [comment]
The JDK 17 change is https://openjdk.org/jeps/403

The internal build rule for [this target](https://github.com/bazelbuild/bazel/blob/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e/src/main/java/com/google/devtools/build/lib/skyframe/serialization/BUILD#L23) sets 

```
    add_opens = [
        "java.base/java.lang.invoke",
    ],
```

If that's available in the version of rules_java the external Bazel build is using we can just add that config.

Another option is to pass `--add-opens=java.base/java.lang.invoke=ALL-UNNAMED` to that test (and everything else that depends on `com.google.devtools.build.lib.skyframe.serialization.LambdaCodec`)

**Comment by cushon** [comment]
@meteorcloudy can you check if https://github.com/bazelbuild/bazel/commit/6a7e9ba0c99a41bb99239425b4cbee48b78f734d helps?

**Comment by meteorcloudy** [comment]
Nice, this seems to fix the issue, but with some warnings:
```
INFO: From Building src/main/java/com/google/devtools/build/lib/unsafe/libstring.jar (1 source file):
warning: [options] --add-opens has no effect at compile time
INFO: From Building src/main/java/com/google/devtools/build/lib/unsafe/libstring.jar (1 source file) [for tool]:
warning: [options] --add-opens has no effect at compile time
INFO: From Building src/main/java/com/google/devtools/build/lib/skyframe/serialization/libserialization.jar (57 source files) and running annotation processors (SerializationConstantProcessor) [for tool]:
warning: [options] --add-opens has no effect at compile time
INFO: From Building src/main/java/com/google/devtools/build/lib/skyframe/serialization/libserialization.jar (57 source files) and running annotation processors (SerializationConstantProcessor):
warning: [options] --add-opens has no effect at compile time
```

**Comment by cushon** [comment]
> warning: [options] --add-opens has no effect at compile time

Thanks, I'll fix that as a follow-up
