### ISSUE TITLE
Use of `aspects` with `cquery rdeps` greatly increases memory usage 

### ISSUE THREAD

**Issue by adamporich** [bazelbuild/bazel#19914]
### Description of the bug:

I recently tried adding an aspect that is instantiated once per `cc_*` rule and propagates on `deps` to all C++ libraries in our tree (~1000 targets mostly C++).

I had no problems with `build` or `test` (well there were a few but they weren't bazel's fault :) ) but running an `rdeps` query that looks like `rdeps(//path/to/package/..., //path/to/package:target)` caused bazel to throw `java.lang.OutOfMemoryError`

After some more tests I found I could run with `--host_jvm_args=-Xmx2g` without the aspect propagating on `deps` and required `--host_jvm_args=-Xmx16g` with it. In addition it goes from near instant without the aspect to 50s with the aspect.

I tried to follow https://bazel.build/rules/performance and used the memory tracker but the increase didn't see a substantial amount about of memory tracked only ~512k for the aspect and reducing the implementation to just returning empty providers and no logic didn't help the issue.

I did confirm using `cquery --include_aspects=false` works to avoid the issue.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I suspect I wouldn't be able to notice on a small repro so best I have is depend on

```
def _my_aspect_impl(target, ctx):
  return []

aspect(
    implementation = _my_aspect_impl,
    attr_aspects = ['deps', 'implementation_deps'],
    attrs = {}
)
```

from at least a thousand or so interconnected targets :shrug: 

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

6.1.2

**Comment by laz-** [comment]
`--include_aspects=false` solves my `bazel cquery` oom also:

```shell
% bazel cquery 'kind(container_image_, rdeps(//..., @common_deps_geopandas//:pkg))'
13:36:03) INFO: Analyzed 1832 targets (1031 packages loaded, 48123 targets configured).
(13:36:03) INFO: Found 1832 targets...
(13:36:03)  checking cached actions
(13:43:15) FATAL: bazel ran out of memory and crashed. Printing stack trace:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at java.base/java.util.HashSet.add(Unknown Source)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:448)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:470)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:487)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:306)
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:104)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction.lambda$eval$0(AllRdepsFunction.java:99)
	at com.google.devtools.build.lib.query2.engine.AllRdepsFunction$$Lambda$1019/0x00000008008a4440.process(Unknown Source)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.lambda$eval$0(AbstractBlazeQueryEnvironment.java:264)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment$$Lambda$1012/0x00000008008a6440.call(Unknown Source)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:196)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.CombinedFuture$CombinedFutureInterruptibleTask.execute(CombinedFuture.java:108)
	at com.google.common.util.concurrent.CombinedFuture.handleAllCompleted(CombinedFuture.java:65)
	at com.google.common.util.concurrent.AggregateFuture.processCompleted(AggregateFuture.java:301)
	at com.google.common.util.concurrent.AggregateFuture.decrementCountAndMaybeComplete(AggregateFuture.java:283)
	at com.google.common.util.concurrent.AggregateFuture.lambda$init$0(AggregateFuture.java:157)
	at com.google.common.util.concurrent.AggregateFuture$$Lambda$831/0x0000000800644040.run(Unknown Source)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.addListener(FluentFuture.java:114)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractBlazeQueryEnvironment.java:508)
	at com.google.common.util.concurrent.AggregateFuture.init(AggregateFuture.java:140)
	at com.google.common.util.concurrent.CombinedFuture.<init>(CombinedFuture.java:55)
	at com.google.common.util.concurrent.Futures$FutureCombiner.call(Futures.java:745)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.whenAllSucceedCall(AbstractBlazeQueryEnvironment.java:300)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.whenSucceedsCall(AbstractBlazeQueryEnvironment.java:288)
```

but with `--include_aspects=false` it completes with results 1s after "INFO: Found 1832 targets..."

**Comment by gregestren** [comment]
It's possible (but by no means guaranteed) that https://github.com/bazelbuild/bazel/issues/16310#issuecomment-1876108171 could help. 

I'd be wary of using `rdeps` at all with `cquery` without the above update. See https://docs.google.com/document/d/1x-RqFFEcGIzVgtYHIq6s6Qt4vYtJWz3nuHIuqeI89dU/edit#heading=h.5mcn15i0e1ch for details.

To be clear, you say that `$ bazel build //path/to/package/...` works fine?
