### ISSUE TITLE
Migration of Automatic Exec Groups [Exec platform per toolchain] in Bazel downstream

### ISSUE THREAD

**Issue by kotlaja** [bazelbuild/bazel#19981]
## Goals of this document
1. A short description of this migration, without going into the details. In case you would like to see more, check: [Exec platform per toolchain](https://docs.google.com/document/d/1-rbP_hmKs9D639YWw5F_JyxPxL2bi6dSmmvj_WXak9M/edit#heading=h.5mcn15i0e1ch). Additional information will also be available soon on official Bazel documentation.
2. **Important note to reviewers**: Please double check if the correct toolchain type is added for each action. I’ve done the best on my part but additional precaution is not harmful. 🙂

## Goal of this migration
Each toolchain type should have its own execution platform. Before this change, the execution platform was selected on a rule level, not on a toolchain type level. 

Each action which uses a tool or executable coming from a toolchain should specify the toolchain type inside ctx.action.{run, run_shell} `toolchain` attribute. 

## What is needed for this migration
In order to use Automatic Exec Groups, two things are required:
Each `ctx.actions.{run, run_shell}` which uses a toolchain as a tool/executable needs to add its toolchain type inside the toolchain parameter. In this way, actions are sent to the right platform.   
Moreover, rule which creates that action needs to define that toolchain_type inside its own rule definition. In other words, the toolchain must be registered on the rule.

For example:
```
# Registering toolchain on the rule
custom_rule = rule(
        implementation = _impl,
        toolchains = ['@bazel_tools//tools/jdk:toolchain_type']
)
```
```
# Using toolchain inside the action
ctx.actions.run(
        toolchain = '@bazel_tools///tools/jdk:toolchain_type'
        executable = ctx.toolchains['@bazel_tools///tools/jdk:toolchain_type'].tool
        …
)
```
## Why does a rule creator need to take care of a toolchain type?
If an action’s executable is not coming from a toolchain, `toolchain` parameter doesn’t need to be set or it could be set to None.
If an action’s executable is coming from a toolchain, `toolchain` parameter should be set. The reason is simple: A correct execution platform will be selected for the action since it will be  mapped with this toolchain type.

## Why must toolchain_type be added manually and not reused from a tool coming from the toolchain?
The tool is a file and we don’t know which toolchain_type it refers to.
Or, the tool is a provider, inside which we could add a toolchain_type but that would increase overall memory.

## Which Bazel versions support this migration?
AEGs are fully supported from Bazel 7. 
`toolchain` parameter is supported from Bazel 6.

If your project supports lower Bazel versions, you need to disable AEGs.

## How to disable AEGs in case of an error?
Set the [incompatible_auto_exec_groups](https://github.com/bazelbuild/bazel/issues/17134) flag to false or disable a particular rule with the `_use_auto_exec_groups`
attribute.

## Potential errors you could step on while migrating to AEGs

`Couldn't identify if tools are from implicit dependencies or a toolchain. Please set the toolchain parameter. If you're not using a toolchain, set it to 'None'.`
* In this case you will be given a stack of calls before the error happened and you will be able to clearly see which exact action needs the toolchain parameter. Check which toolchain is used for the action and set it with the toolchain param. If no toolchain is used inside the action for tools or executable, set it to `None`.

`Action declared for non-existent toolchain '//rule:toolchain_type_1'.`
* This means that you've set the toolchain parameter on the action but didn't register it on the rule. Register the toolchain or set `None` inside the action.

**Comment by anguslees** [comment]
I've read the above, and the referenced doc, but the answer didn't jump out at me.

Question:  What should we do for rules that need more than one toolchain?
Eg golang rules with cgo need both go and cpp toolchains resolved _for the same platform_.

Iiuc, currently we would list both toolchains on the rule(toolchains) attribute, toolchain resolution would take them _all_ into account when choosing an exec platform, and then (aiui) the same exec platform is used for all actions in that rule.

**Comment by anguslees** [comment]
Duh, found the answer right after posting 😮‍💨.  The new bazel [docs](https://bazel.build/extending/auto-exec-groups) explain the answer clearly:

> If you need to use multiple toolchains on a single execution platform (an action uses executable or tools from two or more toolchains), you need to manually define [exec_groups](https://bazel.build/extending/exec-groups) (check [When should I use a custom exec_group?](https://bazel.build/extending/auto-exec-groups#when-should-use-exec-groups) section).

@kotlaja: Iiuc, I think your rules_go [PR](https://github.com/bazelbuild/rules_go/pull/3740) above does not follow this advice - and should.

**Comment by fmeum** [comment]
@kotlaja @comius I tried to enable `--incompatible_auto_exec_groups` in rules_go, but found it to be incompatible with `--incompatible_enable_proto_toolchain_resolution`. 

The root cause is that https://github.com/protocolbuffers/protobuf/blob/6690ab42d855ea19d9a24cd99b0375910ea772ca/bazel/private/toolchain_helpers.bzl#L48 and https://github.com/bazelbuild/rules_proto/blob/db09d58959ed951db34c2e056cef084954e55640/proto/private/rules/proto_toolchain_rule.bzl#L23 (depending on where the proto rules are consumed from) are strings, not `Label`s. They thus get resolved relative to the current repo when passed to the `toolchains` parameter of `ctx.actions.run`, which results in errors such as:

```
ERROR: /Users/fmeum/git/rules_go/tests/legacy/examples/proto/embed/BUILD.bazel:5:14: in proto_library rule //tests/legacy/examples/proto/embed:embed_proto:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/proto/proto_library.bzl", line 88, column 26, in _proto_library_impl
	File "/virtual_builtins_bzl/common/proto/proto_library.bzl", line 226, column 25, in _write_descriptor_set
	File "/virtual_builtins_bzl/common/proto/proto_common.bzl", line 231, column 16, in _compile
Error in run: Action declared for non-existent toolchain '//proto:toolchain_type'.
```

We would need to get new releases of `rules_proto` (say 6.0.3) and `protobuf` out to unblock CI.

**Comment by purkhusid** [comment]
Was going to update rules_dotnet to support `--incompatible_auto_exec_groups` but was blocked due to rules_go not supporting it yet(dev dependency). Will follow this and do the migration once rules_proto/rules_go is migrated.

**Comment by kotlaja** [comment]
Thanks folks for raising these issues. Let's then wait for `rules_proto` and `protobuf` before flipping this flag since otherwise we'll be blocked with this migration in quite a few rules.

**Comment by kotlaja** [comment]
@meteorcloudy thanks for gathering that information!

I talked to @fmeum and it seems that https://github.com/protocolbuffers/protobuf/commit/e358a4025ec6c7043a2e9837f957129f7996e009 fixed the issue Fabian noted in this thread. Still, multiple projects are blocked by rules_python, and rules_python [is blocked](https://github.com/bazelbuild/rules_python/pull/2306) on protobuf. 

Hence, I opened [an issue](https://github.com/protocolbuffers/protobuf/issues/19261) for protobuf and tried migrating on my own (https://github.com/protocolbuffers/protobuf/pull/19262) in order to unblock other projects. I fixed a few actions and then I came to an obstacle with rules_kotlin, so I'm waiting for protobuf team to let me know their thoughts (if they'd like to try upgrading rules_kotlin since some troubling files changed in the meantime)

**Comment by fmeum** [comment]
rules_go is finally fixed at HEAD.

**Comment by anguslees** [comment]
> rules_go is finally fixed at HEAD.

Unless you use cgo and have more than one exec platform 😛 

https://github.com/bazel-contrib/rules_go/pull/3740#issuecomment-2872828465
