### ISSUE TITLE
[7.0.0] Suggest `integrity` instead of `sha256` attribute in `http_*` rules

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20158]
Forked from #20156

**Comment by keertk** [comment]
Taking a look

**Comment by keertk** [comment]
@meteorcloudy @fmeum The conflict is the with MODULE.bazel.lock but I'm not able to run the command to update it this time. Can you help?

```
$ bazel mod deps --lockfile_mode=update

Starting local Bazel server and connecting to it...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue$$Lambda$221/0x00000008002b2440@4c83a4a6' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphValue$$Lambda$352/0x00000008004d5840@2407b282')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by meteorcloudy** [comment]
Hmm, bazel shouldn't crash like this, which bazel version are you using?

**Comment by keertk** [comment]
Ah it was a mistake on my end, sorry for the noise!
Cherry-picked here: https://github.com/bazelbuild/bazel/pull/20177
