### ISSUE TITLE
Bazel tools pkg_tar fails on Fedora 39

### ISSUE THREAD

**Issue by neckbosov** [bazelbuild/bazel#20211]
### Description of the bug:

After updating my host system to fedora 39 I notices failure of `pkg_tar` targets (from `@bazel_tools`) in my project with the following traceback:
```
Traceback (most recent call last):
  File "/home/nikitabosov/.cache/bazel/_bazel_nikitabosov/d68312c3b2467869e50e3f7db2c64b88/sandbox/linux-sandbox/240/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/tools/build_defs/pkg/build_tar.py", line 21, in <module>
    from absl import app
  File "/home/nikitabosov/.cache/bazel/_bazel_nikitabosov/d68312c3b2467869e50e3f7db2c64b88/sandbox/linux-sandbox/240/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/abseil/absl/app.py", line 38, in <module>
    from absl import flags
  File "/home/nikitabosov/.cache/bazel/_bazel_nikitabosov/d68312c3b2467869e50e3f7db2c64b88/sandbox/linux-sandbox/240/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/abseil/absl/flags/__init__.py", line 40, in <module>
    from absl.flags import _argument_parser
  File "/home/nikitabosov/.cache/bazel/_bazel_nikitabosov/d68312c3b2467869e50e3f7db2c64b88/sandbox/linux-sandbox/240/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/abseil/absl/flags/_argument_parser.py", line 29, in <module>
    from absl.flags import _helpers
  File "/home/nikitabosov/.cache/bazel/_bazel_nikitabosov/d68312c3b2467869e50e3f7db2c64b88/sandbox/linux-sandbox/240/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/abseil/absl/flags/_helpers.py", line 38, in <module>
    from six.moves import range  # pylint: disable=redefined-builtin
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'six.moves'
```

I tried to fix it by installing `absl` to system (`python3.six` was already installed) but it didn't help. The only workaround I found is to use `pkg_tar` rule from `@rules_pkg`. On Fedora 38 both ways worked well.

### Which operating system are you running Bazel on?

Fedora 39

### What is the output of `bazel info release`?

release 5.4.0

### Have you found anything relevant by searching the web?

Found similar issue #11663 but it's already closed.

**Comment by sgowroji** [comment]
Hi @neckbosov, Could you please provide complete steps to reproduce this issue?

**Comment by neckbosov** [comment]
Hi @sgowroji, just set up some project which uses `pkg_tar` rules, when try to build it on Fedora 39. I cannot share exact code because it's proprientary.

BTW found [discussion](https://groups.google.com/g/weewx-user/c/PLYefyx2Pnw?pli=1) on Google groups, so I'm not sure it's Bazel problem, but you definetely have more ways to investigate.

**Comment by joeleba** [comment]
@aiuto maybe you have some context on this.

**Comment by aiuto** [comment]
This is not for rules_pkg
> `external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/tools/build_defs/pkg/build_tar.py", line 21,`

That is the ancient (unsupported) pkg_tar from within Bazel itself.  The current rules_pkg release should work with bazel 5.x, so just convert to that.

**Comment by jtillwickEA** [comment]
> This is not for rules_pkg
> 
> > `external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/tools/build_defs/pkg/build_tar.py", line 21,`
> 
> That is the ancient (unsupported) pkg_tar from within Bazel itself. The current rules_pkg release should work with bazel 5.x, so just convert to that.

I have the exact same issue and for reasons I cannot use the version of `rules_pkg` that has `pkg_tar`. How do I fix the original error with the built in version?
