### ISSUE TITLE
Use of Remote Asset API broken in 7.0.0

### ISSUE THREAD

**Issue by mortenmj** [bazelbuild/bazel#20342]
### Description of the bug:

Starting with https://github.com/bazelbuild/bazel/commit/0d36c6baee286fabef4a5188208a02c61031c762, Bazel will call GetCapabilities on the Asset service when using `--experimental_remote_downloader`.
As Capabilities is not a part of the Remote Asset v1 API spec, this breaks faithful implementations of the API.

This commit, and therefore the error, is not in Bazel 6.4.0 but exists in all 7.0.0 RCs

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a build/test with Bazel newer than 0d36c6baee286fabef4a5188208a02c61031c762 with `--experimental_remote_downloader`, using an implementation of the Remote Asset API that does not expose Capabilities, e.g. https://github.com/buildbarn/bb-remote-asset

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.0rc4

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

This is a regression. Some existing implementations of Remote Asset are incompatible with Bazel 7.0.0, because they do not expose a service which is not part of the API. The bug was introduced with https://github.com/bazelbuild/bazel/commit/0d36c6baee286fabef4a5188208a02c61031c762

### Any other information, logs, or outputs that you want to share?

Bazel errors with this message:

```
ERROR: Failed to query remote execution capabilities: UNIMPLEMENTED: unknown service build.bazel.remote.execution.v2.Capabilities
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service build.bazel.remote.execution.v2.Capabilities
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:432)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:465)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by sluongng** [comment]
cc: @coeuvre

**Comment by mortenmj** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by coeuvre** [comment]
Thanks for the report. Working on the fix.
