### ISSUE TITLE
[Bug]: Unknown object using migration tool on rules_rust crate_universe

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/bazel#20453]
### What happened?

When trying to use the migration tool, I get an error:

```
INFO: Executing command: bazel --version
bazel 6.0.0
INFO: Detected original workspace name: examples
INFO: Found existing ./resolved_deps.py file, if it's out of date, please delete it and rerun the script.
Traceback (most recent call last):
  File "/tmp/bazel-central-registry/tools/migrate_to_bzlmod.py", line 510, in <module>
    sys.exit(main())
  File "/tmp/bazel-central-registry/tools/migrate_to_bzlmod.py", line 473, in main
    resolved_deps = load_resolved_deps(argv)
  File "/tmp/bazel-central-registry/tools/migrate_to_bzlmod.py", line 455, in load_resolved_deps
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/rules_rust/examples/crate_universe/./resolved_deps.py", line 255
    "_action_listener": <unknown object com.google.devtools.build.lib.packages.Attribute$LabelListLateBoundDefault>,
                        ^
SyntaxError: invalid syntax
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

```
bazel version
Bazelisk version: development
Build label: 6.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:52:35 2022 (1671465155)
Build timestamp: 1671465155
Build timestamp as int: 1671465155
```

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

Uses `crate_universe` to resolve rust dependencies.

Language(s) and/or frameworks involved:

rules_rust

### How to reproduce

```shell
cd /tmp
git clone git@github.com:bazelbuild/rules_rust.git
git clone https://github.com/bazelbuild/bazel-central-registry.git
cd rules_rust/examples/crate_universe
mv WORKSPACE.bazel WORKSPACE
/tmp/bazel-central-registry/tools/migrate_to_bzlmod.py //...:all
```

### Any other information?

```
grep "<unknown" -A 30 -B 10 -m 1 resolved_deps.py
               "generator": "@cargo_bazel_bootstrap//:cargo-bazel",
               "lockfile": "//cargo_aliases:cargo-bazel-lock.json",
               "manifests": [
                    "//cargo_aliases:Cargo.toml"
               ]
          },
          "repositories": [
               {
                    "rule_class": "@rules_rust//crate_universe/private:crates_repository.bzl%crates_repository",
                    "attributes": {
                         "_action_listener": <unknown object com.google.devtools.build.lib.packages.Attribute$LabelListLateBoundDefault>,
                         "_config_dependencies": [],
                         "_configure": False,
                         "_environ": [
                              "CARGO_BAZEL_GENERATOR_URL",
                              "CARGO_BAZEL_GENERATOR_SHA256",
                              "CARGO_BAZEL_REPIN",
                              "REPIN",
                              "CARGO_BAZEL_ISOLATED"
                         ],
                         "annotations": {
                              "names": [
                                   "[\"0.12.1-dev\",{\"additive_build_file\":null,\"additive_build_file_content\":null,\"build_script_data\":null,\"build_script_data_glob\":null,\"build_script_deps\":null,\"build_script_env\":null,\"build_script_proc_macro_deps\":null,\"build_script_rustc_env\":null,\"build_script_toolchains\":null,\"build_script_tools\":null,\"compile_data\":null,\"compile_data_glob\":null,\"crate_features\":null,\"data\":null,\"data_glob\":null,\"deps\":null,\"gen_build_script\":null,\"patch_args\":null,\"patch_tool\":null,\"patches\":null,\"proc_macro_deps\":null,\"rustc_env\":null,\"rustc_env_files\":null,\"rustc_flags\":null,\"shallow_since\":\"1646516410 -0700\"}]"
                              ]
                         },
                         "applicable_licenses": [],
                         "aspect_hints": [],
                         "cargo_config": None,
                         "cargo_lockfile": "//cargo_aliases:Cargo.Bazel.lock",
                         "compatible_with": [],
                         "deprecation": <unknown object com.google.devtools.build.lib.analysis.BaseRuleClasses$2>,
                         "expect_failure": "",
                         "features": [],
                         "generate_build_scripts": True,
                         "generator": "@cargo_bazel_bootstrap//:cargo-bazel",
                         "generator_function": "",
                         "generator_location": "",
                         "generator_name": "",
                         "generator_sha256s": {},
                         "generator_urls": {},
                         "isolated": True,
```

**Comment by meteorcloudy** [comment]
@SalmaSamy Oh sorry, I misunderstood, this is not from the lockfile, but from the generated file from [--experimental_repository_resolved_file](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html#the-new-flag-experimental_repository_resolved_file). But still, maybe it's worth fixing from Bazel side.

**Comment by Wyverald** [comment]
The part in question looks like a BUILD rule target instead of a repo rule, which would explain all the weirdness. The problem then is to figure out _why_ we're trying to include this in the resolved workspace file at all...

**Comment by meteorcloudy** [comment]
OK, maybe a P3...
