### ISSUE TITLE
Error calling `attr` for generated `repository_rule` inside macro called by `WORKSPACE`

### ISSUE THREAD

**Issue by Silic0nS0ldier** [bazelbuild/bazel#20463]
### Description of the bug:

An in-house `env_vars` macro creates a `_env_vars` repository rule. This is done so `environ` can be set, so the repository is regenerated should any listed environment variable change.

In Bazel 7 (tested on `7.0.0-pre.20231011.2`, `7.0.0rc6` and `7.0.0rc7`) this leads to the following error.

```
(13:47:18) ERROR: Traceback (most recent call last):
        File "[REDACTED]/WORKSPACE", line 49, column 17, in <toplevel>
                workspace_stage1()
        File "[REDACTED]/tools/build/bazel/workspace/stage1.bzl", line 39, column 13, in workspace_stage1
                env_vars(
        File "[REDACTED]/tools/build/bazel/vars.bzl", line 148, column 48, in env_vars
                "default_to_zero_values": attr.bool(
Error in bool: attr.bool() can only be used during .bzl initialization (top-level evaluation) or package evaluation (a BUILD file or macro)
```

As a workaround (and realistically, an optimisation) attribute declaration was moved out of the macro.

e.g.

```starlark
_attrs = {
    "foo": attr.bool(),
    # ...
}

def foo_bar(name, foo):
    _foo_bar = repository_rule(
        implementation = # ...,
        attrs = _attrs,
        # ...
    )
    # ...
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Setup:

```starlark
# WORKSPACE
load("//:foo_bar.bzl", "foo_bar")

foo_bar(
    name = "bar",
    foo = True,
)

# foo_bar.bzl
def _impl(rctx):
    pass

def foo_bar(name, foo):
    _foo_bar = repository_rule(
        implementation = _impl.
        attrs = {
            "foo": attr.bool(),
        },
    )
    _foo_bar(
        name = name,
        foo = foo,
    )

# BUILD
# (empty)
```

Reproducing:

```sh
bazel query //... --noenable_bzlmod
```

### Which operating system are you running Bazel on?

macOS Sonoma

### What is the output of `bazel info release`?

release 7.0.0rc7

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

_Maybe_. There has been a lot of work in this area for bzlmod and I understand some compatibility breaks are intentional. This could be one such instance.

Given the error message implies this use case is supported, I'm inclined to believe this is a regression.

Note that this issue is not present in Bazel 6.3.2.

### Any other information, logs, or outputs that you want to share?

Potentially related, this is pulled from the [draft Bazel 7 release announcement](https://docs.google.com/document/d/1clxBctsjpei40wqqjwiU2EltTzsrf_kvZ4dJyZVqghM/edit).

> `rule()` and `attr.*` can no longer be (pointlessly) called during WORKSPACE evaluation and repository rule evaluation.

**Comment by Silic0nS0ldier** [comment]
@bazel-io flag

**Comment by keertk** [comment]
cc @meteorcloudy
