### ISSUE TITLE
java.lang.IllegalArgumentException: invalid count: -1 from javac during test compilation

### ISSUE THREAD

**Issue by mickeyreiss** [bazelbuild/bazel#2073]
### Description of the problem / feature request / question:

Transient crasher during java tests build.

### If possible, provide a minimal example to reproduce the problem:

I'm not sure what caused this. A subsequent build passed.

### Environment info
* Operating System:

      OS X 10.11.5

* Bazel version (output of `bazel info release`):

      release 0.3.2

<details>
<summary>Stacktrace</summary>

```
$ bazel test //server:tests                                                                                                                                                                                   8 ↵
INFO: (11-10 18:32:49.696) Found 1 test target...
ERROR: (11-10 18:33:17.590) /Users/mickeyreiss/github.com/[redacted]/server/BUILD:1:1: Java compilation in rule '//server:server' failed: Worker process sent response with exit code: 4.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: server/src/main/java/[redacted].java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.IllegalArgumentException: invalid count: -1
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
        at com.google.common.base.Strings.repeat(Strings.java:160)
        at com.google.errorprone.ErrorProneError.formatMessage(ErrorProneError.java:76)
        at com.google.errorprone.ErrorProneError.<init>(ErrorProneError.java:42)
        at com.google.errorprone.scanner.ErrorProneScanner.handleError(ErrorProneScanner.java:1251)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:956)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.visitBinary(TreeScanner.java:626)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:562)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1958)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:510)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:960)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitThrow(TreeScanner.java:482)
        at com.google.errorprone.scanner.ErrorProneScanner.visitThrow(ErrorProneScanner.java:1113)
        at com.google.errorprone.scanner.ErrorProneScanner.visitThrow(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:1543)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitCase(TreeScanner.java:347)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCase(ErrorProneScanner.java:607)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCase(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1222)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitSwitch(TreeScanner.java:333)
        at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:1083)
        at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1193)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:577)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:945)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:637)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:652)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:125)
        at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:113)
        at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:134)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1257)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:865)
        at com.sun.tools.javac.main.Main.compile(Main.java:253)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:140)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:132)
        at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.invokeJavac(AbstractJavaBuilder.java:66)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:66)
        at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:69)
        at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:108)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:92)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:70)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)
Target //server:tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: (11-10 18:33:17.672) Elapsed time: 32.319s, Critical Path: 27.68s

Executed 0 out of 1 test: 1 fails to build.

```
</details>

**Comment by aehlig** [comment]
@damienmg, @philwo you last touched the buildjar code in question; can you have a look and help triaging?

**Comment by damienmg** [comment]
Error-Prone and java error, I summon @cushon and @iirina

**Comment by philwo** [comment]
ErrorProneError.formatMessage calls Strings.repeat with the second parameter being "column - 1". It seems like column is 0, which results in -1 being passed to Strings.repeat, which triggers the assertion failure.

This seems like a bug in ErrorProne. Too bad it wasn't reproducible. :| I agree that cushon will probably know best what to do with this.

**Comment by cushon** [comment]
Columns are 1-indexed, so this suggests we're reporting a crash at a non-existent source position. That shouldn't happen, but I'll make the obvious fix so we don't crash if it does.

The fact that this isn't reproducible makes me suspect the persistent worker, Error Prone bugs should always be deterministic.

**Comment by philwo** [comment]
I agree, non-deterministic behaviour sounds suspicious. If it's the persistent worker mode, that means that possibly something somewhere keeps state or a cache in a static class field that doesn't get invalidated between runs, doesn't it?

**Comment by cushon** [comment]
Could be. The last non-deterministic worker crash I remember was a [hotspot bug](https://www.google.com/url?q=https://bugs.openjdk.java.net/browse/JDK-8006960?focusedCommentId%3D13605633%26page%3Dcom.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel%23comment-13605633&sa=D&usg=AFQjCNGzbWMPC7yBaCdGH25h1009g6D9vg).

**Comment by cushon** [comment]
google/error-prone@0bb5a2944ce8f8d0eab1f69ae26a0c2bd9816acd should have fixed those symptoms. I'm still not sure what the root cause was, so please re-eopen if you see this again.
