### ISSUE TITLE
Add CUDA compiler support on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2075]
On unix platform, for GPU build, TF is using the crosstool under https://github.com/tensorflow/tensorflow/tree/master/third_party/gpus/crosstool.
NVCC is invoked by this python script https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

The script can recognize it's a cuda compilation if `-x cuda` is in the compile options and then construct a proper command line for nvcc.

I am basically adding the same logic into Bazel's MSVC python wrapper script [msvc_tools.py](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_tools.py.tpl).
It is definitely not the most ideal solution, but I managed to make it work.

With some other changes, the latest progress is I can build the pip package with GPU support, but it crashed when I do `import tensorflow as tf`
```
C:\Windows\system32>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "C:\Program Files\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Invalid access to memory location.


During handling of the above exception, another exception occurred:

```

I also tried to build the C++ example trainer, it also crash during runtime.

It might be some linking problem, but I have no clue yet. I'll keep investigating this.

**Comment by meteorcloudy** [comment]
Ha, looks like it is a linking problem.
I tried with non-WHOLEARCHIVE mode, (meaning when don't use /WHOLEARCHIVE option).
I succeed to build the C++ example trainer, and when I run it I got this:
```
...
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000006 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000006 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000000/000002 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\dso_loader.cc:119] Couldn't open CUDA library cublas.dll
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:2294] Unable to load cuBLAS DSO.
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\dso_loader.cc:119] Couldn't open CUDA library cudnn.dll
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:3459] Unable to load cuDNN DSO
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\dso_loader.cc:119] Couldn't open CUDA library cufft.dll
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\cuda\cuda_fft.cc:344] Unable to load cuFFT DSO.
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\dso_loader.cc:119] Couldn't open CUDA library curand.dll
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\stream_executor\cuda\cuda_rng.cc:338] Unable to load cuRAND DSO.
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: Quadro 600
major: 2 minor: 1 memoryClockRate (GHz) 1.28
pciBusID 0000:05:00.0
Total memory: 1.00GiB
Free memory: 784.11MiB
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: Quadro 600, pci bus id: 0000:05:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.5.
```

**Comment by meteorcloudy** [comment]
Although there are some dll failed to load, I believe it should be easy to fix.

**Comment by meteorcloudy** [comment]
And the pip package is also working if compiled with non-WHOLEARCHIVE mode,  but it seems my GPU is too old so it's not enabled.
```
...
>>>
>>> # Fit the line.
... for step in range(201):
...     sess.run(train)
...     if step % 20 == 0:
...         print(step, sess.run(W), sess.run(b))
...
0 [ 0.72356522] [-0.07103202]
20 [ 0.26303026] [ 0.2101941]
40 [ 0.1418431] [ 0.27695057]
60 [ 0.11073938] [ 0.29408416]
80 [ 0.10275637] [ 0.29848164]
100 [ 0.10070746] [ 0.29961032]
120 [ 0.10018156] [ 0.2999]
140 [ 0.1000466] [ 0.29997435]
160 [ 0.10001197] [ 0.29999343]
180 [ 0.10000308] [ 0.29999831]
200 [ 0.1000008] [ 0.29999956]
>>> # Learns best fit is W: [0.1], b: [0.3]
>>> sess = tf.Session()
I C:\temp\Bazel\YDZZGvfX\execroot\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:948] Ignoring visible gpu device (device:
 0, name: Quadro 600, pci bus id: 0000:05:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.5.
>>>
```

**Comment by mrry** [comment]
@meteorcloudy This is awesome! Do you have a branch where this is working? I can test it out on my Windows box, which has a newer GPU.

**Comment by meteorcloudy** [comment]
@mrry I just pushed to https://github.com/meteorcloudy/tensorflow/tree/fix-gpu-support.
I copyed `local_config_cc` to the sources tree, so it's easier to test the change in python script(I don't have to build bazel everytime.)

My cuda and cudnn is installed at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0`, and some paths are hardcoded in the python script for now.

Just in case the fragile build fails on your machine, I can also share the whl file with you. :)

You can try the following to reproduce the build:

-  Using `~/.bazelrc` file like:

```
build -c opt
build --cpu=x64_windows_msvc
build --host_cpu=x64_windows_msvc
build:win-cuda --define=using_cuda=true --define=using_cuda_nvcc=true
build:win-cuda --crosstool_top=//tools/local_config_cc:toolchain  # This could be removed after changes are submitted to Bazel
build --copt="/w"                  # Suppress some warning messages
build --experimental_ui            # Enable a nice UI
build --verbose_failures
```

- Run `./configure` , enable GPU support, my output is:

```
pcloudy@PCLOUDY1-W MSYS ~/workspace/test/meteorcloudy/tensorflow
$ ./configure
~/workspace/test/meteorcloudy/tensorflow ~/workspace/test/meteorcloudy/tensorflow
Found possible Python library paths:
  C:\Program Files\Anaconda3\lib\site-packages
  C:\Program Files\Anaconda3
Please input the desired Python library path to use.  Default is [C:\Program Files\Anaconda3\lib\site-packages]

Using python library path: C:\Program Files\Anaconda3\lib\site-packages
Junction created for util\python\python_include <<===>> C:\Program Files\Anaconda3\include
Junction created for util\python\python_lib <<===>> C:\Program Files\Anaconda3\lib\site-packages
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Program Files\Anaconda3\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe]:
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]:
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]:
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]:
ERROR: CreateFile(C:\temp\Bazel\$-G5ceWX\install): The system cannot find the file specified.
 (2)
........................
WARNING: C:/tools/msys64/home/pcloudy/workspace/test/meteorcloudy/tensorflow/tensorflow/tensorflow.bzl:29:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/tools/msys64/home/pcloudy/workspace/test/meteorcloudy/tensorflow/tensorflow/tensorflow.bzl:30:5: Make sure that you are running at least Bazel 0.3.2.
.
INFO: All external dependencies fetched successfully.
Configuration finished
```


- Run ` bazel build --config=win-cuda tensorflow/tools/pip_package:build_pip_package`
   
   I am using bazel built from HEAD, 0.4.0 doesn't work, because I have [this change](https://github.com/bazelbuild/bazel/commit/001f8afcfe6d7d41cf2f84cee0d13e1123b6aa5c) after it.


- Run `./bazel-bin/tensorflow/tools/pip_package/build_pip_package $PWD` to build the pip


There are still a lot of things to improve, and I'll also keep investigating why it's not working with /WHOLEARCHIVE, since without it, the build is slower.

**Comment by mrry** [comment]
Thanks for sending over the compiled .whl file :). I can confirm that it works on my GPU (a GTX 980 Ti). This is awesome!

**Comment by meteorcloudy** [comment]
That's great!

**Comment by mrry** [comment]
So I haven't managed to get this building using Bazel-on-Windows (current error when running `./configure` is `Cannot create a file when that file already exists`... so perhaps it's in a bad state), but there is one fix needed: it seems that the build .whl is looking for libraries with the wrong name (e.g. `curand.dll` whereas CUDA-on-Windows calls that file `curand64_80.dll` on my installation). Perhaps this can be fixed in the cuda_configure setup?

**Comment by meteorcloudy** [comment]
Hmm, I never saw that error, can you show me which file it was trying to create?

It might be a little more complex to fix the name issue, because we need .lib file during compilation time, but .dll file during runtime. The lib files don't have a version number, but dll files do. We'll figure it out.

**Comment by snnn** [comment]
Hi @meteorcloudy 

Does it work with wraper free msvc toolchain?

**Comment by meteorcloudy** [comment]
@snnn No, because we have to construct arguments for nvcc compler, even the linux Cuda CROSSTOOL uses a wrapper script. See https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
