### ISSUE TITLE
Bazel 7.0.0: custom rule using py_binary resulting in AssertionError: Cannot find .runfiles directory for

### ISSUE THREAD

**Issue by SimonVleugels** [bazelbuild/bazel#20805]
### Description of the bug:

After upstep to Bazel 7.0.0 (working with bazel 6.4.0) building a custom rule with a py_binary fails with error: 

```
$ bazel-7.0.0 --output_base=/tmp/bazel-cache build //main:example_custom_rule
INFO: Analyzed target //main:example_custom_rule (71 packages loaded, 608 targets configured). 
ERROR: /tmp/bazel-examples/main/BUILD:29:20: Action main/test_output failed: (Exit 1): script_example.sh failed: error executing Action command (from target //main:example_custom_rule)
(cd /tmp/bazel-cache/sandbox/linux-sandbox/9/execroot/_main && \ 
exec env - \ 
main/script_example.sh --tool bazel-out/k8-fastbuild/bin/main/python_example --output bazel-out/k8-fastbuild/bin/main
/test_output)
# Configuration: 5b7f3dabfc121df34b8e60c12f9cd32618465e27acf1e3f88765b47e8d5ec800
# Execution platform: @@local_config_platform//:host
Traceback (most recent call last): 
   File "/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/main/python_example", line 559, in <module>
      Main() 
   File "/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/main/python_example", line 457, in Main  
      module_space = FindModuleSpace(main_rel_path) 
   File "/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/main/python_example", line 172, in FindModuleSpace
      raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for /tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/main/python_example
```

BUILD file:
```
load("@rules_cc//cc:defs.bzl", "cc_binary")
load(":example_custom_rule.bzl", "example_custom_rule")

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

py_binary(
    name = "python_example",
    srcs = [
        "python_example.py",
    ],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "script_example",
    srcs = ["script_example.sh"],
    visibility = ["//visibility:public"],
)

example_custom_rule(
    name = "example_custom_rule",
    output = "test_output"
)
```

example_custom_rule.bzl:
```
def _rule_impl(ctx):
    output_file = ctx.actions.declare_file(ctx.attr.output)

    args = ctx.actions.args()
    args.add('--tool', ctx.files._tool[0].path)
    args.add('--output', output_file.path)
   
    ctx.actions.run(
        outputs = [output_file],
        inputs = ctx.files._tool,
        executable = ctx.file._script,
        arguments = [args],
        tools = ctx.files._tool
    )

    return [
        DefaultInfo(
            files = depset([output_file]),
            runfiles = ctx.runfiles(ctx.files._tool)
        ),
    ]

example_custom_rule = rule(
    implementation = _rule_impl,
    attrs = {
        'output': attr.string(mandatory=True),
        '_script': attr.label(allow_single_file=True, default='@//main:script_example'),
        '_tool': attr.label_list(allow_files=True, default=['@//main:python_example']),
    }
)

```

### Which category does this issue belong to?

Python Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example project code:
https://drive.google.com/file/d/1TeuZ6U1ukEcXZuvWnBM7nQUhO_dLsqoK/view?usp=sharing

```
$ bazel --output_base=/tmp/bazel-cache build //main:example_custom_rule
```

### Which operating system are you running Bazel on?

Rocky linux 8

### What is the output of `bazel info release`?

release 7.0.0

**Comment by fmeum** [comment]
@lberki I don't see any runfiles created in this case, but only with an output base under `/tmp`. This reproduces even on master, which doesn't have all your fixes though.

**Comment by fmeum** [comment]
@bazel-io fork 7.0.1

**Comment by fmeum** [comment]
Sorry for the false alarm, this rule definition definitely has some issues: You are adding the *files* of the Python target, but not the *runfiles*. Since you run the Python target as a tool, you should pass something like `ctx.executable._tool` to the `tools` parameter of `ctx.actions.run` and make `_tool` an `attr.label(executable = True)`. 

This probably worked on 6.4.0 due to weaker sandbox, but wasn't hermetic.

**Comment by rickeylev** [comment]
This doesn't look to be an issue in Bazel or the python rules, closing.
