### ISSUE TITLE
Windows error because "+" isn't a label

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2081]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/324/console:

```
c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\HEAD\PLATFORM_NAME\windows-x86_64>c:\bazel_ci\installs\HEAD\bazel.exe --bazelrc=c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\HEAD\PLATFORM_NAME\windows-x86_64\.bazelrc test //src/test/java/... + //src/test/shell/bazel:bazel_windows_example_test 
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
____Loading package: src/test/java/com/google/devtools/build/lib/bazel/repository
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
```

This was introduced in https://github.com/bazelbuild/continuous-integration/commit/3198e0f8a3b0e9d798754a176ddcd10709623be6, `"WINDOWS_TESTS": " + ".join(windows_tests)`.  I'd guess the + just has has to be removed because *nix tests are querying the test list whereas windows is just running the list, but please verify.

**Comment by meteorcloudy** [comment]
Yes, that's a problem, but not the problem causing the current failure. Bazel can actually safely skip it. See previous succeeded job: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/320/console

The real failing test is `//src/test/java/com/google/devtools/build/lib:ProtoLangToolchainTest`
```
There was 1 failure:
1) protoToolchain(com.google.devtools.build.lib.rules.proto.ProtoLangToolchainTest)
org.junit.ComparisonFailure: expected:<x/plugin[]> but was:<x/plugin[.exe]>
	at com.google.common.truth.Platform.comparisonFailure(Platform.java:133)
	at com.google.common.truth.Truth$1.failComparing(Truth.java:76)
	at com.google.common.truth.StringSubject.isEqualTo(StringSubject.java:76)
	at com.google.devtools.build.lib.rules.proto.ProtoLangToolchainTest.protoToolchain(ProtoLangToolchainTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:140)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:79)

FAILURES!!!
Tests run: 2,  Failures: 1
```
Which is introduced in 51f64da2d9a917a18c292e624260e50544a09347 , I can fix it.

**Comment by kchodorow** [comment]
Yup, filed #2082 for that one.  I still think this should be fixed, but dropping the priority.

**Comment by meteorcloudy** [comment]
Agree, I'll fix it later. :)

**Comment by meteorcloudy** [comment]
This is fixed by @damienmg  https://github.com/bazelbuild/continuous-integration/commit/c78a3384c0a38a139d27dd807cf3e54306b018e6
