### ISSUE TITLE
[Bazel 7.0.0] Upgrade JaCoCo to 0.8.11-SNAPSHOT

### ISSUE THREAD

**Issue by nlou9** [bazelbuild/bazel#20845]
### Description of the bug:

When I use bazel 7.0.0 to run bazel coverage on java 21. It has the error:
```
Failures: 0
java.io.IOException: Error while analyzing org/apache/kafka/clients/producer/internals/RecordAccumulator$PartitionerConfig.class.uninstrumented.
	at com.google.testing.coverage.BranchDetailAnalyzer.analyzerError(BranchDetailAnalyzer.java:110)
	at com.google.testing.coverage.BranchDetailAnalyzer.analyzeClass(BranchDetailAnalyzer.java:71)
	at com.google.testing.coverage.JacocoCoverageRunner.analyzeBranch(JacocoCoverageRunner.java:209)
	at com.google.testing.coverage.JacocoCoverageRunner.create(JacocoCoverageRunner.java:131)
	at com.google.testing.coverage.JacocoCoverageRunner$2.run(JacocoCoverageRunner.java:568)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at com.google.testing.coverage.jarjar.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at com.google.testing.coverage.BranchDetailAnalyzer.analyzeClass(BranchDetailAnalyzer.java:105)
	at com.google.testing.coverage.BranchDetailAnalyzer.analyzeClass(BranchDetailAnalyzer.java:69)
```

the latest release of JaCoCo 0.8.11 has added the support for java 21. https://github.com/jacoco/jacoco/releases

Should we upgrade the JaCoCo snapshot to 0.8.11? 

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel coverage instruments the java 21 targets.

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

bazel 7.0.0

**Comment by hvadehra** [comment]
We'll also need to update ASM, along the lines of https://github.com/bazelbuild/bazel/pull/17514

**Comment by hvadehra** [comment]
The upgrade to jacoco v0.8.11 / asm v9.6 is done[^1] in the Bazel source tree.

I suppose now we will need a `java_tools` release to make it available. cc @keertk Once that happens, we can close this as completed.

[^1]: https://github.com/bazelbuild/bazel/pull/21027 is yet to be merged, but we don't need to necessarily wait for that to happen.

**Comment by hvadehra** [comment]
So, using this isn't tied to a Bazel version. 

in a non-bzlmod setup, you can use just upgrade your `java_tools` version ([example instructions]( https://github.com/bazelbuild/java_tools/releases/tag/java_v13.3))

With bzlmod, we'll additionally need a `rules_java` release to the BCR which you can then depend on in your `MODULE.bazel`.

**Comment by keertk** [comment]
java_tools: https://github.com/bazelbuild/java_tools/releases/tag/java_v13.4
rules_java: https://github.com/bazelbuild/rules_java/releases/tag/7.4.0
