### ISSUE TITLE
bazel crash on windows with `java.nio.file.InvalidPathException: Illegal char <*> at index ...`

### ISSUE THREAD

**Issue by cloudhan** [bazelbuild/bazel#20906]
### Description of the bug:

Bazel crashed as follows:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.nio.file.InvalidPathException: Illegal char <*> at index 43: C:/users/cloud/workspaces/rules_cuda/bazel-*
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at com.google.devtools.build.lib.skyframe.LocalDiffAwareness$Factory.lambda$maybeCreate$0(LocalDiffAwareness.java:113)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.google.devtools.build.lib.skyframe.LocalDiffAwareness$Factory.maybeCreate(LocalDiffAwareness.java:113)
        at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.maybeGetDiffAwarenessState(DiffAwarenessManager.java:169)
        at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:108)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.handleDiffs(SkyframeExecutor.java:3138)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:285)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:737)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:567)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:621)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/bazel-contrib/rules_cuda/actions/runs/7531757668/job/20501002440#step:7:21

To reproduce locally:

[rules_cuda-cloudhan-v7.zip](https://github.com/bazelbuild/bazel/files/13944192/rules_cuda-cloudhan-v7.zip)
```
# to repo root
cd rules_cuda-cloudhan-v7

# out of repo @examples build with --noenable_bzlmod crashes bazel
bazelisk build --noenable_bzlmod @rules_cuda_examples//basic:all

# the following works correctly however...
cd examples
bazelisk build --noenable_bzlmod @rules_cuda_examples//basic:all
```

### Which operating system are you running Bazel on?

Windows 11 and Windows Server 2019

### What is the output of `bazel info release`?

release 7.0.0, `bazel info` (no ` release`) crashed with the same error

### Any other information, logs, or outputs that you want to share?

`bazel info` crashed with the same error

**Comment by cloudhan** [comment]
The direct cause should be the `bazel-*` in the `.bazelignore`. But the root cause is unknown, these have been working correctly during bazel 5 and 6.

**Comment by fmeum** [comment]
@bazel-io fork 7.0.1

**Comment by fmeum** [comment]
Looks like a regression introduced by https://github.com/bazelbuild/bazel/commit/4dabe43494cf4b13d3b08349ba92d6e7c662a20b.

Cc @sushain97

**Comment by sushain97** [comment]
I agree that Bazel shouldn't crash in this case. That being said, aren't wildcards not supported per https://github.com/bazelbuild/bazel/issues/7093? So, the fix would be just improving the error message?

**Comment by meteorcloudy** [comment]
@sushain97 Yes, fixing the crashing is the immediate goal.

In the meantime, giving this is not that serious. I'm making this a soft release blocker for 7.0.1, which means it won't block 7.0.1 if other things clear out.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by cloudhan** [comment]
@iancha1992 Now it doesn't crash but produe the following error

```
ERROR: Error computing the main repository mapping: error during computation of main repo mapping: Invalid path in C:/rules_cuda-cloudhan-v7/.bazelignore: java.nio.file.InvalidPathException: Illegal char <*> at index 6: bazel-*
```

I am not sure if it is by design if you want to address the root cause. For example, in the case someone want it ignore `foobar-*` will still result in `Illegal char <*> at index 7: foobar-* ` as manually verified.

I am OK with deleting the line in `.bazelignore` as a workaround for my case, tho.

**Comment by sushain97** [comment]
> I am not sure if it is by design if you want to address the root cause. For example, in the case someone want it ignore `foobar-*` will still result in `Illegal char <*> at index 7: foobar-* ` as manually verified.

@cloudhan adding support for wildcards is tracked in https://github.com/bazelbuild/bazel/issues/7093.

You will need to delete the entry from `.bazelignore` for your builds to pass.
