### ISSUE TITLE
FileNotFoundException when following runfile loading instructions from Runfiles.java

### ISSUE THREAD

**Issue by ekohlwey** [bazelbuild/bazel#20900]
### Description of the bug:

[Runfiles.java](https://github.com/bazelbuild/bazel/blob/38918be4f665e4eca69c9f3f5d469be6d63a486b/src/main/java/com/google/devtools/build/lib/analysis/Runfiles.java#L2) contains relatively simple instructions on how to include runfile dependencies in a Java application. When implementing runfile loading as described, however, I am unable to load the runfiles. I suspect that my usage is incorrect and that the docs should be clarified.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See this repo: https://github.com/ekohlwey/simple-bazel-data-example

`BUILD.bazel`:

```python
load("@rules_java//java:defs.bzl",  "java_binary")


genrule(
    name = "make_test_text_file",
    outs = ["test_text_file.txt"],
    cmd = "echo 'TEST_FILE' > $@",
)

java_binary(
    name = "binary_with_data",
    srcs = glob(["src/**/*.java"]),
    data = [":test_text_file.txt"],
    deps = [
        "@bazel_tools//tools/java/runfiles",
        ],
    main_class = "com.example.BinaryWithData",
)
```

`BinaryWithData.java`:

```java
package com.example;

import com.google.devtools.build.runfiles.AutoBazelRepository;
import java.io.BufferedReader;
import java.io.FileReader;
import com.google.devtools.build.runfiles.Runfiles;

@AutoBazelRepository
class BinaryWithData{
    public static void main(String[] args) throws Throwable {
        String path = Runfiles.preload().withSourceRepository(AutoBazelRepository_BinaryWithData.NAME)
            .rlocation("test_text_file.txt");
        BufferedReader reader = new BufferedReader(new FileReader(path));
        String line = reader.readLine();
        System.out.println("test_text_file.txt contains:");
        System.out.println(line);
        reader.close();
    }
}
```

Output of `bazel run //:binary_with_data`:

```

Starting local Bazel server and connecting to it...
INFO: Analyzed target //:binary_with_data (54 packages loaded, 1012 targets configured).
INFO: From Building external/bazel_tools/tools/java/runfiles/libauto_bazel_repository.jar (1 source file):
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
INFO: From Building external/bazel_tools/tools/java/runfiles/librunfiles.jar (2 source files):
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
INFO: Found 1 target...
Target //:binary_with_data up-to-date:
  bazel-bin/binary_with_data
  bazel-bin/binary_with_data.jar
INFO: Elapsed time: 8.902s, Critical Path: 2.61s
INFO: 5 processes: 1 internal, 2 darwin-sandbox, 2 worker.
INFO: Build completed successfully, 5 total actions
INFO: Running command line: bazel-bin/binary_with_data
Exception in thread "main" java.io.FileNotFoundException: /private/var/tmp/_bazel_ekohlwey/7dc8051309d81e5a83c7efb16c818670/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/binary_with_data.runfiles/test_text_file.txt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at com.example.BinaryWithData.main(BinaryWithData.java:13)
```

I can see the file is there, the Java code simply fails to map the location properly. It is symlinked from in a `_main` folder in the runfiles directory:

```sh
ls bazel-out/darwin_arm64-fastbuild/bin/binary_with_data.runfiles/
MANIFEST                              _repo_mapping                         rules_java~7.1.0~toolchains~local_jdk
_main                                 bazel_tools
```

```sh
ls bazel-out/darwin_arm64-fastbuild/bin/binary_with_data.runfiles/_main 
binary_with_data     binary_with_data.jar external             test_text_file.txt
```

### Which operating system are you running Bazel on?

OSX

### What is the output of `bazel info release`?

release 7.0.0

**Comment by fmeum** [comment]
The path you pass to `rlocation` always has to start with a repository name. In your case, you can:
* use `_main/test_text_file.txt`
* add a `module(name = "my_module")` call to `MODULE.bazel` and use `my_module/test_text_file.txt`
* Use `$(rlocationpath :make_test_text_file)` to pass in the correct path via `args` or `env`.

**Comment by ekohlwey** [comment]
Thanks! I've updated my example based on your feedback and it works now.
