### ISSUE TITLE
Error Rule family java_binary in link tag does not match any rule or BE page


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20969]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3608#018d2f53-d27a-4df1-a2b1-1cb6c114fb7d

 Platform: Multiple ( Windows, Linux, MacOS)

 Logs: 
```ERROR: Error in @@_builtins//:common/java/java_import.bzl: Rule family java_binary in link tag does not match any rule or BE page: ${link java_binary}
com.google.devtools.build.docgen.BuildEncyclopediaDocException: Error in @@_builtins//:common/java/java_import.bzl: Rule family java_binary in link tag does not match any rule or BE page: ${link java_binary}
	at com.google.devtools.build.docgen.RuleDocumentation.getHtmlDocumentation(RuleDocumentation.java:234)
	at com.google.devtools.build.docgen.ApiExporter.collectRuleInfo(ApiExporter.java:289)
	at com.google.devtools.build.docgen.ApiExporter.appendTypes(ApiExporter.java:81)
	at com.google.devtools.build.docgen.ApiExporter.main(ApiExporter.java:371)
(03:22:30) ERROR: /Users/buildkite/builds/bk-imacpro-13/bazel-org-repo-root/bazel/src/main/java/com/google/devtools/build/lib/BUILD:623:8: declared output 'src/main/java/com/google/devtools/build/lib/builtin.pb' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(03:22:30) ERROR: /Users/buildkite/builds/bk-imacpro-13/bazel-org-repo-root/bazel/src/main/java/com/google/devtools/build/lib/BUILD:623:8: Executing genrule //src/main/java/com/google/devtools/build/lib:gen_api_proto failed: not all outputs were created or valid
(03:22:30) INFO: Elapsed time: 230.765s, Critical Path: 74.05s
(03:22:30) INFO: 5872 processes: 356 remote cache hit, 136 internal, 3595 darwin-sandbox, 1 local, 1784 worker.
(03:22:30) ERROR: Build did NOT complete successfully.
```

 CC Greenteam @comius

**Comment by comius** [comment]
cc @hvadehra
