### ISSUE TITLE
Error in compile: Expected action_config for 'objc-compile' to be configured

### ISSUE THREAD

**Issue by mayt-moonboy** [bazelbuild/bazel#21014]
## Context
I am trying to get a minimal example a glfw project running on my mac m1 in bazel. My build file for glwf includes an objc_library which is giving me a headache but I think its the last roadblock before I get my example running.
##.Error
I get the following error when running the binary of the minimal example:
```
Error in compile: Expected action_config for 'objc-compile' to be configured
```

### Which operating system are you running Bazel on?

MacOS Version 14.2.1 (23C71)

### What is the output of `bazel info release`?

release 6.4.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

not that I know of

### Have you found anything relevant by searching the web?

I have searched around looking for the answer to this to no avail. Mostly I am pointed in the direction of this being a crosstool error (which it shouldn't be) or an xcode not installed issue.

### Any other information, logs, or outputs that you want to share?

Machine: 2020 Mac M1 Mac Mini
OS: Version 14.2.1 (23C71)
Bazel Version: 6.4.0
Xcode Version: 15.2

**Comment by bfsoyc** [comment]
@mayt-moonboy Did you have Xcode installed?

**Comment by mayt-moonboy** [comment]
> @mayt-moonboy Did you have Xcode installed?

Yes. My xcode version is listed in the other information section.

**Comment by keith** [comment]
I don't see the same failure mode when testing locally, can you pass `--xcode_version=15.2` to potentially kick bazel into using that if it somehow picked the command line tools instead? Alternatively you can inspect the contents of `bazel-out/../external/local_config_cc/BUILD` and `bazel-out/../external/local_config_xcode/BUILD` to make sure things didn't silently fail somehow

**Comment by mayt-moonboy** [comment]
```./bazel run //packages/example --xcode_version=15.2
INFO: Build option --xcode_version has changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_trammelmay/dde546f78e35dbbd51fa07a6dd693b93/external/glfw/BUILD.bazel:133:13: in objc_library rule @glfw//:glfw_src_darwin: Expected action_config for 'objc-compile' to be configured
ERROR: /private/var/tmp/_bazel_trammelmay/dde546f78e35dbbd51fa07a6dd693b93/external/glfw/BUILD.bazel:133:13: in objc_library rule @glfw//:glfw_src_darwin: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 57, column 82, in _objc_library_impl
        File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 315, column 50, in _register_compile_and_archive_actions
        File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 392, column 66, in _cc_compile_and_link
        File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 184, column 29, in _compile
Error in compile: Expected action_config for 'objc-compile' to be configured
ERROR: /private/var/tmp/_bazel_trammelmay/dde546f78e35dbbd51fa07a6dd693b93/external/glfw/BUILD.bazel:133:13: Analysis of target '@glfw//:glfw_src_darwin' failed
ERROR: Analysis of target '//packages/example:example' failed; build aborted: 
INFO: Elapsed time: 1.056s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 332 targets configured)
```

**Comment by keith** [comment]
I can reproduce this error in a VM where I only have the command line tools, is `xcode-select -p` correctly pointing to Xcode vs the command line tools? I think there's an issue where after you setup Xcode the first time (open it to make sure you accept the license etc), you have to run `bazel clean --expunge` and then build again

**Comment by mayt-moonboy** [comment]
```
xcode-select -p
/Applications/Xcode.app/Contents/Developer
```
I also just started a new project in xcode to confirm it is set up properly. Everything appears to be fine in that regard.

**Comment by bfsoyc** [comment]
> > @mayt-moonboy Did you have Xcode installed?
> 
> Yes. My xcode version is listed in the other information section.

I have the same env setting with yours. I suppose you could reboost the system to check if everything goes ok then.
The code you provided test normally by my side.

**Comment by mayt-moonboy** [comment]
> > > @mayt-moonboy Did you have Xcode installed?
> > 
> > 
> > Yes. My xcode version is listed in the other information section.
> 
> I have the same env setting with yours. I suppose you could reboost the system to check if everything goes ok then. The code you provided runs sucess by my side.

Thanks. Yes I have tried rebooting, and yesterday I installed an os update as well. All to no avail. I am getting the same error.

**Comment by mayt-moonboy** [comment]
I uninstalled xcode and am currently reinstalling. I will report back success or failure.

**Comment by mayt-moonboy** [comment]
unforutnately, that did not work.

**Comment by comius** [comment]
Do you have `--platforms` set to point to one of Apple platforms, defined in @apple_support?

**Comment by cemlyn007** [comment]
Did you guys have any luck? Hitting something similar and I suspect it's Xcode/Bazel configuration related. I assume the full Xcode installation is just the installation from the App Store.

**Comment by keith** [comment]
A few things since this issue:

1. The apple_support toolchain supports command line tools only installations
2. If you install Xcode while the bazel server is running, you need to `bazel shutdown` and potentially rerun bazel with `DEVELOPER_DIR` set (as the easiest way) you can see the recommendations here https://github.com/bazelbuild/rules_apple/blob/eed702ea4b42dca3081a63bb6abd030878abcb6f/doc/common_info.md#xcode-version-selection-and-invalidation
