### ISSUE TITLE
Bazel reports non-actionable errors when ctx.download_and_extract(..) fails with --experimental_remote_downloader enabled.

### ISSUE THREAD

**Issue by bgianfo** [bazelbuild/bazel#21132]
### Description of the bug:

We have a few repositories where we enabled the `--experimental_remote_downloader`, when there is an error during `ctx.download_and_extract(...)` execution we have observed that the the error message reported seem to be raw GRPC status messages instead of the actual underlying issue. For example, in a contrived example of editing a checksum for an external `http_archvie` so that it doesn't match, we see the following message when running `bazel build //...`

```
ERROR: An error occurred during the fetch of repository 'com_gitlab_libeigen_eigen':
   Traceback (most recent call last):
	File "/home/brian.gianforcaro/.cache/bazel/_bazel_brian.gianforcaro/388c206dbb0a63034b032674cd60d01d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 145, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: @1 ChDt9e5_8DlDM5UA7F8j9KGWEgdkZWZhdWx0GiUKIMpUKz21xMv2LKP7ueXksQXeuMb0eBHG5QjN3vGHL-tyEJAB: No matching action runner found (available: com.engflow.re.exec.worker.WorkerInDockerActionRunner@3bba2cab,com.engflow.re.exec.docker.CachedDockerActionRunner@7e9c70a3,com.engflow.re.exec.docker.DockerActionRunner@1149e0f1), client-provided platform proto:
properties {
  name: "sandboxNetwork"
  value: "standard"
}
```

When we disable the `--experimental_remote_downloader` flag and run the build again you get the expected error message: 

```
ERROR: An error occurred during the fetch of repository 'com_gitlab_libeigen_eigen':
   Traceback (most recent call last):
	File "/home/brian.gianforcaro/.cache/bazel/_bazel_brian.gianforcaro/388c206dbb0a63034b032674cd60d01d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 145, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz] to /home/brian.gianforcaro/.cache/bazel/_bazel_brian.gianforcaro/388c206dbb0a63034b032674cd60d01d/external/com_gitlab_libeigen_eigen/temp6352546979305926533/eigen-3.4.0.tar.gz: Checksum was 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72 but wanted 8586084f71f9bde545ee7fa6d00288b264a2c7ac3607b974e54d13e7162c1c72
```

The lack of actionable error messages decrease the usability for our users who may not be bazel experts. It is unclear to me if this is a bazel bug, or a bug in the remote execution service we use (EngFlow). 

### Which category does this issue belong to?

Remote Execution

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.3.2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Not that I can find.

**Comment by bgianfo** [comment]
The `EngFlow` team appears to have patched this on their side, so I believe this was an issue with their remote executor service implementation .
