### ISSUE TITLE
ERROR: An error occurred during the fetch of repository '_main~bazel_build_deps~bootstrap_repo_cache' in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21292]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3652#018d9b79-7e09-47a4-be42-d0ebc248311a

 Platform: Multiple

 Logs: 
```
ERROR: An error occurred during the fetch of repository '_main~bazel_build_deps~bootstrap_repo_cache':
   Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-8/bazel-org-repo-root/bazel/distdir.bzl", line 89, column 42, in _repo_cache_tar_impl
		http_artifacts = parse_http_artifacts(ctx, lockfile_path, ctx.attr.repos)
	File "/Users/buildkite/builds/bk-imacpro-8/bazel-org-repo-root/bazel/src/tools/bzlmod/utils.bzl", line 108, column 13, in parse_http_artifacts
		fail("Could not find all required repos, missing: %s" % missing_repos)
Error in fail: Could not find all required repos, missing: ["abseil-cpp~", "apple_support~", "bazel_skylib~", "blake3~", "c-ares~", "grpc~", "protobuf~", "stardoc~", "rules_cc~", "rules_go~", "rules_java~", "rules_jvm_external~", "rules_kotlin~", "rules_graalvm~", "rules_license~", "rules_pkg~", "rules_proto~", "rules_python~", "upb~", "zlib~", "zstd-jni~", "grpc~~grpc_repo_deps_ext~bazel_gazelle", "grpc~~grpc_repo_deps_ext~bazel_skylib", "grpc~~grpc_repo_deps_ext~com_envoyproxy_protoc_gen_validate", "grpc~~grpc_repo_deps_ext~com_github_cncf_udpa", "grpc~~grpc_repo_deps_ext~com_google_googleapis", "grpc~~grpc_repo_deps_ext~envoy_api", "grpc~~grpc_repo_deps_ext~rules_cc", "rules_kotlin~~rules_kotlin_extensions~com_github_jetbrains_kotlin"]
``` 

 CC Greenteam @mai93

**Comment by fmeum** [comment]
@meteorcloudy Could we make it so that Bazel at HEAD builds first update the lockfile before they build Bazel?

**Comment by meteorcloudy** [comment]
This is still failing in downstream:

https://github.com/bazelbuild/bazel/blame/909a628aab265707abde7f2a0824b56cc3bef701/src/tools/bzlmod/utils.bzl#L137-L140

It's because this function actually always return the old canonical repo name (with version), so even if we update the lockfile, it doesn't work. I think we need to detect which format should be used in this function.
