### ISSUE TITLE
With --experimental_remote_execution_keepalive, Execution/WaitExecution NOT_FOUND not retried

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#21530]
### Description of the bug:

At EngFlow, one of our customers reported their builds failed when our remote execution service returned `NOT_FOUND` for `Execution/WaitExecution` calls. We return `NOT_FOUND` when a remote action is interrupted due to a server-side problem, for example, when the worker machine executing the action is terminated. Normally in response to `NOT_FOUND`, Bazel retries by calling `Execution/Execute` again, which restarts the action.

Unfortunately, that didn't happen here. From server logs, it looked like Bazel called `Execution/Execute` once, encountered some error, called `Execution/WaitExecution` to resume, got `NOT_FOUND`, then gave up. Bazel didn't retry by calling `Execution/Execute`.

The customer's Bazel stack trace included `ExperimentalGrpcRemoteExecutor`, pasted below. They indicated they were using `--experimental_remote_execution_keepalive`. After disabling that flag, Bazel retries worked normally.

<details><pre>
com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor$Execution.waitExecution(ExperimentalGrpcRemoteExecutor.java:201)
	at com.google.devtools.build.lib.remote.util.Utils.refreshIfUnauthenticated(Utils.java:525)
	at com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor$Execution.lambda$start$1(ExperimentalGrpcRemoteExecutor.java:165)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
	at com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor$Execution.start(ExperimentalGrpcRemoteExecutor.java:163)
	at com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor.executeRemotely(ExperimentalGrpcRemoteExecutor.java:359)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.executeRemotely(RemoteExecutionService.java:1493)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:292)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:265)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:159)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:119)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:261)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1144)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1061)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:558)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:859)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:333)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:171)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Operation not found: (redacted server message) 
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:660)
	at com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor$Execution.handleOperationStream(ExperimentalGrpcRemoteExecutor.java:213)
	at com.google.devtools.build.lib.remote.ExperimentalGrpcRemoteExecutor$Execution.waitExecution(ExperimentalGrpcRemoteExecutor.java:199)
	... 32 more
</pre></details>

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately, I don't have an easy way to reproduce this. Should be something like:

1. Run a long-running remote action, like a test with a long sleep.
2. Terminate the machine running the remote action before it finishes.
3. Bazel should get `NOT_FOUND` from `WaitExecution`, then retry.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

unknown, I think they're on 7.0.2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
n/a
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Unknown

### Have you found anything relevant by searching the web?

n/a

**Comment by iancha1992** [comment]
@jayconrod Could you please provide sample code to reproduce this issue?

**Comment by jayconrod** [comment]
I'm afraid I'm not able to provide an example. This relied on a rather specific error coming from our servers. The actual action executed by Bazel doesn't matter.

**Comment by celestialorb** [comment]
I believe we're hitting this issue as well on Bazel 6.5.0. The symptoms are an exact match and disabling the experimental remote execution keepalive feature seems to resolve the issue.

**Comment by coeuvre** [comment]
Might be fixed by https://github.com/bazelbuild/bazel/pull/22067.

**Comment by jayconrod** [comment]
Our customer has upgraded to Bazel 7.2.0 and verified they're no longer seeing this issue. Sounds like #22067 did fix this issue, so it can be closed.
