### ISSUE TITLE
Some tests are failing on Bazel CI because of JDK21

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#21593]
### Description of the bug:

- `//src/test/shell/bazel/android:android_local_test_integration_test`
- `//src/test/shell/bazel/android:android_local_test_integration_test_with_head_android_tools`
- `//src/java_tools/junitrunner/javatests/com/google/testing/junit/runner:AllTests`
- `//src/java_tools/junitrunner/javatests/com/google/testing/junit/runner:antxmlresultwriter_integration_test`
- `//src/java_tools/junitrunner/javatests/com/google/testing/junit/runner:junit4_testbridge_integration_test`
- `//src/java_tools/junitrunner/javatests/com/google/testing/junit/runner:utf8_test_log_test`

are failing with following error on Bazel CI because we recently upgrade the host JDK to JDK21:

```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.installSecurityManager(JUnit4Runner.java:256)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:113)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.testing.coverage.JacocoCoverageRunner.main(JacocoCoverageRunner.java:592)
```

https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/20432#018e13ed-069f-43fd-b7fb-b0bbbff0ef0a

**Comment by meteorcloudy** [comment]
Also `//src/test/java/com/google/devtools/build/lib/bazel/repository/downloader:DownloaderTestSuite` is failing on Windows with JDK 21

**Comment by meteorcloudy** [comment]
```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.installSecurityManager(JUnit4Runner.java:256)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:113)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.testing.coverage.JacocoCoverageRunner.main(JacocoCoverageRunner.java:592)
```

@hvadehra @cushon This looks like a problem in the java test runner. Do you know what's happening?

**Comment by hvadehra** [comment]
(internally b/257121191)

The only use is to prevent test code from (accidentally or otherwise) calling `System.exit()`. There doesn't seem to be any other way to do it for now: https://bugs.openjdk.org/browse/JDK-8199704

**Comment by meteorcloudy** [comment]
OK, then probably setting `--jvmopt=-Djava.security.manager=allow` somewhere is the solution? /cc @zhengwei143

**Comment by zhengwei143** [comment]
> FYI, this is already set for java_test targets: https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/bazel/java/bazel_java_binary.bzl#L66-L67

Hmm, does that not affect `bazel test` in a shell test? ([the failing test](https://github.com/bazelbuild/bazel/blob/f8b1b7e126550713199f0e81fd3a72512b600b5d/src/test/shell/bazel/android/android_local_test_integration_test.sh#L161))

**Comment by meteorcloudy** [comment]
Good to know! Those failing tests are not java_test, probably should also set them in https://cs.opensource.google/search?q=SUITE_FLAG&sq=&ss=bazel

**Comment by meteorcloudy** [comment]
> Hmm, does that not affect bazel test in a shell test? ([the failing test](https://github.com/bazelbuild/bazel/blob/f8b1b7e126550713199f0e81fd3a72512b600b5d/src/test/shell/bazel/android/android_local_test_integration_test.sh#L161))

I guess it's because [`/javatests/com/bin:test`](https://github.com/bazelbuild/bazel/blob/f8b1b7e126550713199f0e81fd3a72512b600b5d/src/test/shell/bazel/android/android_local_test_integration_test.sh#L91) is not a java test.

**Comment by meteorcloudy** [comment]
We still have one test failing on Windows:
https://github.com/bazelbuild/bazel/blob/facee7a94f5f005f4b13fd33e897f9810c8f762f/.bazelci/presubmit.yml#L359-L360

**Comment by zhengwei143** [comment]
Forgot about that one - will have a look at it

**Comment by meteorcloudy** [comment]
Np, it's not super urgent, feel free to prioritize other JDK 21 work first!
