### ISSUE TITLE
`bazel mod show_repo <canonical repo name>` doesn't work for module extension generated repos.

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#21621]
### Description of the bug:

For a module extension generated repo, the following works:

```
bazel mod show_repo <apparent repo name> --base_module=<module name>
```

However, it'll be nice to also also have 

```
bazel mod show_repo <canonical repo name>
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In the Bazel repo, with Bazel 7.1.0rc2

```
bazel mod show_repo @@rules_jvm_external~~maven~maven

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.cmdline.RepositoryName.equals(Object)" because the return value of "com.google.common.collect.ImmutableMap.get(Object)" is null
	at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModuleArg$CanonicalRepoName.lambda$resolveToRepoNames$1(ModuleArg.java:340)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$tryAdvance$0(CollectSpliterators.java:67)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:67)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findAny(Unknown Source)
	at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModuleArg$CanonicalRepoName.resolveToRepoNames(ModuleArg.java:341)
	at com.google.devtools.build.lib.bazel.commands.ModCommand.execInternal(ModCommand.java:340)
	at com.google.devtools.build.lib.bazel.commands.ModCommand.exec(ModCommand.java:138)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:664)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

7.1.0rc2

**Comment by meteorcloudy** [comment]
/cc @Wyverald @SalmaSamy 

Relevant code: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModuleArg.java;l=333-343

**Comment by Wyverald** [comment]
ah, I think this is as simple as removing that `if` check. if a nonexistent canonical repo name is passed in, we could just let it fail a bit later instead.

**Comment by meteorcloudy** [comment]
@Wyverald I don't quite understand, I didn't see anywhere in the code that is checking the canonical repo name generated by module extension? (`@@rules_jvm_external~~maven~maven` does exist)

**Comment by Wyverald** [comment]
I meant removing the check at https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/bzlmod/modcommand/ModuleArg.java;drc=a54a393d209ab9c8cf5e80b2a0ef092196c17df3;l=339, so we don't check that the canonical repo name is from a module. We can simply not check anything at all and let it fail later if the repo doesn't actually exist.

**Comment by fmeum** [comment]
@bazel-io fork 7.1.1

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.1 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.1.1rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.1.1rc1. Thanks!

**Comment by meteorcloudy** [comment]
FYI @lberki

**Comment by lberki** [comment]
Thanks! (any news about reporting something useful when there are modules/repositories that are in error but the one I am interested in is not?)

**Comment by meteorcloudy** [comment]
I believe a successful resolution result is still a requirement for the `bazel mod` command? @Wyverald can confirm that.

**Comment by lberki** [comment]
That's why I think too, although I certainly hoped that that one somehow got fixed in the meantime

**Comment by wingsofovnia** [comment]
I am still having the issue on `7.1.1`:
```
> bazel --version                                                   
bazel 7.1.1

> bazel mod show_extension @@rules_oci~6.0.5//oci:extensions.bzl%oci
Starting local Bazel server and connecting to it...
 checking cached actions
    Fetching https://bcr.bazel.build/modules/rules_python_gazelle_plugin/0.31.0/source.json
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.cmdline.RepositoryName.equals(Object)" because the return value of "com.google.common.collect.ImmutableMap.get(Object)" is null
        at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModuleArg$CanonicalRepoName.lambda$resolveToModuleKeys$0(ModuleArg.java:308)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$tryAdvance$0(CollectSpliterators.java:67)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Unknown Source)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:67)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.findAny(Unknown Source)
        at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModuleArg$CanonicalRepoName.resolveToModuleKeys(ModuleArg.java:309)
        at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ExtensionArg.resolveToExtensionId(ExtensionArg.java:66)
        at com.google.devtools.build.lib.bazel.commands.ModCommand.execInternal(ModCommand.java:365)
        at com.google.devtools.build.lib.bazel.commands.ModCommand.exec(ModCommand.java:139)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:664)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by meteorcloudy** [comment]
@wingsofovnia Thanks for reporting, we'll fix it.

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.2.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
