### ISSUE TITLE
Bazel@HEAD failed to build Bazel with remote execution and `--experimental_remote_merkle_tree_cache`

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#21628]
### Description of the bug:

The error messages maybe different, but they all point to the missing of runfiles:

```
ERROR: /usr/local/google/home/chiwang/dev/github/bazelbuild/bazel/BUILD:187:8: Writing: bazel-out/k8-opt/bin/rules_java-srcs.tar failed: (Exit 1): build_tar failed: error executing PackageTar command (from target //:rules_java-srcs) bazel-out/k8-opt-exec-ST-778d9d0c251b/bin/external/rules_pkg~/pkg/private/tar/build_tar '--output=bazel-out/k8-opt/bin/rules_java-srcs.tar' '--mode=0555' '--owner=0.0' '--owner_name=.' '--directory=/' ... (remaining 2 arguments skipped)
Traceback (most recent call last):
  File "bazel-out/k8-opt-exec-ST-778d9d0c251b/bin/external/rules_pkg~/pkg/private/tar/build_tar", line 559, in <module>
    Main()
  File "bazel-out/k8-opt-exec-ST-778d9d0c251b/bin/external/rules_pkg~/pkg/private/tar/build_tar", line 457, in Main
    module_space = FindModuleSpace(main_rel_path)
  File "bazel-out/k8-opt-exec-ST-778d9d0c251b/bin/external/rules_pkg~/pkg/private/tar/build_tar", line 172, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/k8-opt-exec-ST-778d9d0c251b/bin/external/rules_pkg~/pkg/private/tar/build_tar
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Clone https://github.com/bazelbuild/bazel
2. Run `USE_BAZEL_VERSION=last_green bazel build --config=remote --experimental_remote_merkle_tree_cache --noremote_accept_cached -- //src:bazel`

**Comment by coeuvre** [comment]
cc @tjgq

**Comment by tjgq** [comment]
Broken by 404d8d97fafedb7c43a3c164a7446d2e1bf2e436. I'll try to find a minimal test case because there's too much going on in a Bazel build to debug effectively. (I tried a trivial Java binary with a single runfile and it worked, so it must be something more complicated than that.)
