### ISSUE TITLE
java.lang.IllegalStateException: Unknown error during ConfigurationCollectionValue evaluation

### ISSUE THREAD

**Issue by baditaflorin** [bazelbuild/bazel#2168]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When trying to run `bazel info` command, i get this error
bazel info
```
java.lang.IllegalStateException: Unknown error during ConfigurationCollectionValue evaluation
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1052)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.getConfigurations(CommandEnvironment.java:396)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:119)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:104)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:170)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:509)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:735)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1500(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:802)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Unknown error during ConfigurationCollectionValue evaluation
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1052)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.getConfigurations(CommandEnvironment.java:396)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:119)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand$1.get(InfoCommand.java:104)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:170)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:509)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:735)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1500(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:802)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Environment info
* Operating System:
Ubuntu 14.04 Virtual Machine VirtualBox

* Bazel version (output of `bazel info release`):

4 something. I cannot run this command.

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment]
Hi Baditaflorin,

well we will need much more information. How did you install the bazel? Can you run bazel version? Can you paste the content of your WORKSPACE file? Can you reproduce with 0.4.1? Anything relevant comes to your mind?

Thanks!

**Comment by mhlopko** [comment]
Closing due the lack of information.
