### ISSUE TITLE
Hang in 'checking cached actions'

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#21712]
### Description of the bug:

I've not got a reliable way to reproduce this yet, but I've been seeing Bazel 7.1 hang during 'checking cached actions', on a 16-core Windows machine.  This is quite new. The thing I've changed recently is to write a 'warm commit builder' that, in a loop, checks out latest commit, builds it, then moves onto next.  Each new checkout probably changes only 100 files in the source directory. The hang happens every 10 or so builds, and might last 5-20 minutes before it continues. I've reverted to bazel 7.0.1 for now, and will monitor.

Has anyone else seen this recently?

### Which operating system are you running Bazel on?

windows

### What is the output of `bazel info release`?

release 7.1.0

**Comment by iancha1992** [comment]
@peakschris Could you please provide sample code to reproduce this issue?

**Comment by Wyverald** [comment]
Unfortunately, 'checking cached actions' is just the (poorly chosen) default message when Bazel doesn't really know what's going on.

Could you maybe capture a `jstack` while it's hanging?

**Comment by peakschris** [comment]
I'm also seeing this in 7.0.1.

Attached are jstack captures, every 20 seconds, during a hang. I started capturing around half way through. It had unhung by the last 1 or two. It seems to be related to file hashing?

Chris
[hang1.zip](https://github.com/bazelbuild/bazel/files/14623358/hang1.zip)

**Comment by coeuvre** [comment]
It seems like Bazel was indeed busy at checking action cache according to the stack dump. How large is your action cache, how many actions does your build have and how large is your output tree?

The action cache is at `$(bazel info output_base)/action_cache`.

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.2

**Comment by iancha1992** [comment]
@bazel-io fork 7.2.0

**Comment by keithl-stripe** [comment]
I caught a frozen build. Its last output was an hour ago:
```
[72,497 / 72,620] 3460 / 3468 tests; [Prepa] Action datasets/XXX; 39s ... (106 actions, 0 running)
Analyzing: 211082 targets (96735 packages loaded, 794243 targets configured)
[72,546 / 72,620] 3465 / 3468 tests; [Prepa] Action datasets/XXX.pb; 39s ... (64 actions, 0 running)
Analyzing: 211082 targets (96735 packages loaded, 794243 targets configured)
[72,617 / 72,620] 3468 / 3468 tests; Action datasets/all_datasets.pb; 0s remote
Analyzing: 211082 targets (96735 packages loaded, 794243 targets configured)
[72,620 / 72,620] 3468 / 3468 tests; checking cached actions
```

Bazel is using 0-2% CPU - this seems like a deadlock.

I've [attached the stack dump](https://github.com/bazelbuild/bazel/files/15178290/bazel-cached-actions-hang-stack-dump.txt.zip) (all 33 MB of it :) ) 

Most `skyframe-evaluator` threads are stuck in repository fetching:

```

"skyframe-evaluator-17394" #44414 [26510] daemon prio=5 os_prio=0 cpu=3.13ms elapsed=4143.57s tid=0x00007f9c38045ae0 nid=26510 waiting on condition  [0x00007f86150eb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21/Native Method)
	- parking to wait for  <0x00007f9def8f19f8> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(java.base@21/Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21/Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@21/Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(java.base@21/Unknown Source)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:170)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:200)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:200)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:200)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:418)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:205)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinPool.scan(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@21/Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@21/Unknown Source)
```

Oddly, each thread is all waiting on a **_different_** lock.
```
% grep -o 'parking to wait .*TransferStack' ~/Downloads/bazel-cached-actions-hang-stack-dump.txt | wc -l
   11275
% grep -o 'parking to wait .*TransferStack' ~/Downloads/bazel-cached-actions-hang-stack-dump.txt | sort -u | wc -l
   11275
```

**Comment by fmeum** [comment]
Likely to be resolved by https://github.com/bazelbuild/bazel/pull/22100

**Comment by Wyverald** [comment]
Thanks for the info, @keithl-stripe . This pretty much confirms this to be the repo worker thing. It's my top priority to fix at the moment for 7.2.0 (along with #22003, #22206, etc).

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!

**Comment by oakad** [comment]
To my humble opinion you must retract the 7.1 release. This bug is of severe enough nature as to void the basic "tool fit for purpose" assumption: a minor change to a dependency can cause the build job to never terminate. Moreover, it is a proverbial "rubber bomb that keeps jumping", as different teams and systems usually have different version adoption timelines.

**Comment by peakschris** [comment]
@oakad I believe a workaround is to set `common --experimental_worker_for_repo_fetching=off` in .bazelrc. This may help you?

**Comment by peakschris** [comment]
@iancha1992 I am no longer seeing this issue in 7.2.0rc1. @Wyverald thank you for the fix!

**Comment by oakad** [comment]
@peakschris Of course there are workarounds, a safer one being to stick to 7.0. However, my point is, that 7.1 is broken by default*. This is a particular problem for various CICD containers where the underlying image gets updated on some random schedule.

* When installed without much afterthought and applied to the existing workspaces.

**Comment by Wyverald** [comment]
I agree, this bug is quite bad indeed. Did you have an idea in mind how we should 'retract' 7.1? Either way, when 7.2.0 is released (hopefully early next week), most automated update tools with point to that instead.

**Comment by xiemotongye** [comment]
I'm trying to upgrade bazel to 7.3.2. It is wierd  that this issue reappeared in version 7.3.2. When I downgraded version to 7.2.0, it was gone.
