### ISSUE TITLE
bzlmod NullPointerException: null value in entry: bazel_gazelle=nul

### ISSUE THREAD

**Issue by jbedard** [bazelbuild/bazel#21737]
### Description of the bug:

While trying to migrate to bzlmod. The rules_python and gazelle repository rules seen in the trace have moved to MODULE.bazel, other repo rules in WORKSPACE.bzlmod reference those. I haven't been able to figure out which specific change (moving things into MODULE.bazle etc) triggered this.

Crash when building any targets:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'SINGLE_EXTENSION_EVAL:ModuleExtensionId{bzlFileLabel=@@rules_python~//python/extensions:python.bzl, extensionName=python, isolationKey=Optional.empty}' (requested by nodes 'BZLMOD_REPO_RULE:@@rules_python~~python~pythons_hub')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null value in entry: bazel_gazelle=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:341)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:450)
	at com.google.devtools.build.lib.bazel.bzlmod.Module.getRepoMappingWithBazelDepsOnly(Module.java:67)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphFunction.getExtensionUsagesById(BazelDepGraphFunction.java:233)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphFunction.getExtensionUsagesById(BazelDepGraphFunction.java:221)
	at com.google.devtools.build.lib.bazel.bzlmod.SingleExtensionEvalFunction.tryGettingValueFromLockFile(SingleExtensionEvalFunction.java:258)
	at com.google.devtools.build.lib.bazel.bzlmod.SingleExtensionEvalFunction.compute(SingleExtensionEvalFunction.java:165)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	... 7 more
```

If I remove all use of rules_python + gazelle from the MODULE + WORKSPACE it changes but seems related still:
```
bazel is crashing: Crashed: (java.lang.RuntimeException) Unrecoverable error while evaluating node 'SINGLE_EXTENSION_EVAL:ModuleExtensionId{bzlFileLabel=@@bazel_features~//private:extensions.bzl, extensionName=version_extension, isolationKey=Optional.empty}' (requested by nodes 'BZLMOD_REPO_RULE:@@bazel_features~~version_extension~bazel_features_globals', 'BZLMOD_REPO_RULE:@@bazel_features~~version_extension~bazel_features_version'), (java.lang.NullPointerException) null value in entry: bazel_gazelle=null
```

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 7.1.0

**Comment by fmeum** [comment]
Could you test with Bazel 7.1.1rc2? It fixes one issue of this kind.

**Comment by jbedard** [comment]
Same error with 7.1.1rc2

**Comment by fmeum** [comment]
Even if you delete the `MODULE.bazel.lock` file before running the build with 7.1.1rc2?

**Comment by jbedard** [comment]
Ok, after deleting the lockfile it seems to work, and also works with 7.1.0 again after dropping the lockfile? I'll post again if I run into the issue again.

**Comment by Wyverald** [comment]
Thanks for confirming. I'll close this for now, but will re-open if new information surfaces.
