### ISSUE TITLE
[Bazel CI] Bazel@HEAD failed to build Bazel itself in downstream

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21864]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3765#018e97d5-1a26-4f83-9b08-3570811e9ea6

 Platform: MacOS

 Logs: 
```
ERROR: An error occurred during the fetch of repository '_main~bazel_build_deps~bootstrap_repo_cache':
   Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/bazel/distdir.bzl", line 89, column 42, in _repo_cache_tar_impl
		http_artifacts = parse_http_artifacts(ctx, lockfile_path, ctx.attr.repos)
	File "/Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/bazel/src/tools/bzlmod/utils.bzl", line 108, column 13, in parse_http_artifacts
		fail("Could not find all required repos, missing: %s" % missing_repos)
Error in fail: Could not find all required repos, missing: ["grpc~~grpc_repo_deps_ext~bazel_gazelle", "grpc~~grpc_repo_deps_ext~bazel_skylib", "grpc~~grpc_repo_deps_ext~com_envoyproxy_protoc_gen_validate", "grpc~~grpc_repo_deps_ext~com_github_cncf_udpa", "grpc~~grpc_repo_deps_ext~com_google_googleapis", "grpc~~grpc_repo_deps_ext~envoy_api", "grpc~~grpc_repo_deps_ext~rules_cc", "rules_kotlin~~rules_kotlin_extensions~com_github_jetbrains_kotlin"]
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/bazel
git reset 753dc9750714af581147f6aa338adeb07a9dcb57  --hard
export USE_BAZEL_VERSION=753dc9750714af581147f6aa338adeb07a9dcb57
bazel test - //scripts/... //src/main/starlark/tests/builtins_bzl/... //src/test/... //src/tools/execlog/... //src/tools/singlejar/... //src/tools/workspacelog/... //third_party/ijar/... //tools/android/... //tools/aquery_differ/... //tools/python/... //tools/bash/... -//src/test/shell/bazel:starlark_repository_test -//src/test/shell/bazel/apple:bazel_apple_test -//src/test/shell/bazel/apple:bazel_objc_test -//src/test/java/com/google/devtools/build/lib/platform:SystemMemoryPressureEventTest -//src/test/shell/bazel:bazel_determinism_test -//src/test/shell/bazel:jdeps_test -//src/test/shell/bazel:srcs_test -//src/test/shell/bazel/android:android_instrumentation_test_integration_test -//src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_head_android_tools -//src/test/shell/bazel/android:aapt_integration_test -//src/test/shell/bazel/android:aapt_integration_test_with_head_android_tools 
 ``` 
 CC Greenteam @fweikert

**Comment by meteorcloudy** [comment]
Bazel is now green at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3797
