### ISSUE TITLE
cc_shared_library ignores objc_library transitive dependencies

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#21893]
### Description of the bug:

If you have a cc_shared_library with a direct dependency on an objc_library it fails to build with this error:

```
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 666, column 114, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 382, column 48, in _filter_inputs
Error: <target //:bar> (rule 'objc_library') doesn't contain declared provider 'GraphNodeInfo'
ERROR: /private/tmp/objc_library_cc_shared_library/BUILD:11:18: Analysis of target '//:baz' failed
```

If it has a transitive dependency instead, it is ignored and the symbols from it are not linked in.

You can work around this now with this:

```bzl
    additional_linker_inputs = [
        ":lib",
    ],
    user_link_flags = [
        "$(location :lib)",
    ],
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build this project [objc_library_cc_shared_library.zip](https://github.com/bazelbuild/bazel/files/14859479/objc_library_cc_shared_library.zip)

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

7.1.1

**Comment by comius** [comment]
cc @pzembrod for triage
cc @oquenchil for potential insights

**Comment by oquenchil** [comment]
`cc_shared_library` wasn't designed with `objc_library` rules in mind so I'm surprised it even works with that small workaround. Looking quickly at the `objc_library` rule definition it doesn't announce that it provides `CcInfo` with `provides = `. If all the information that you need is in `CcInfo` and the rule starts announcing that it provides it, then it should work. Apart from that the `cc_shared_library` rule doesn't currently make any special considerations for `objc_library`.

**Comment by HackAttack** [comment]
I have a similar issue, commenting here instead of opening a new one—
> If all the information that you need is in `CcInfo` and the rule starts announcing that it provides it, then it should work.

This is how I fixed a problem I had with a custom rule that returns `CcInfo` without it being in `provides`. The documentation seems to imply that it shouldn’t be necessary to put it in `provides`, specifically this section:

> When a target of the rule is used as a dependency for a target that declares a required provider, it is not necessary to specify that provider here. It is enough that the implementation function returns it. However, it is considered best practice to specify it, even though this is not required.

but it is indeed required because I was getting missing symbols in a dependent otherwise. So it seems at minimum the documentation is wrong.

**Comment by AustinSchuh** [comment]
Just hit this in our project.  The correct fix for this is to modify objc_library to return a CcInfo ?

**Comment by keith** [comment]
Probably yes. The objc specific provider has been mostly replaced for ccinfo

**Comment by woockashek** [comment]
It looks that `objc_library` rule already returns CcInfo https://github.com/bazelbuild/bazel/blob/123f7aacdb4785bcdfc920da5ec40f419c702734/src/main/starlark/builtins_bzl/common/objc/objc_library.bzl#L99

But at the same time it doesn't inform about that with `provides = [CcInfo]` in the rule definition:
https://github.com/bazelbuild/bazel/blob/123f7aacdb4785bcdfc920da5ec40f419c702734/src/main/starlark/builtins_bzl/common/objc/objc_library.bzl#L108

I faced the same issue in my project and adding this information to objc_library rule fixes the problem. Still I'm not a bazel expert so I don't know the impact of such change for the whole framework.

**Comment by keith** [comment]
submitted https://github.com/bazelbuild/rules_cc/pull/530 which i verified fixes my original repro here

**Comment by woockashek** [comment]
For bazel 7.7.0 change in rules_cc repo is not solving the issue. For some reason it needs to be modified in bazel repo.

**Comment by woockashek** [comment]
@Keith do you think it would be possible to apply the change to the Bazel (and ideally backport to bazel 7 and 8. Those versions are using native versions of cc_rules and your fix is not covering them.

**Comment by keith** [comment]
If you submit a similar PR to bazel there you can flag it for inclusion in the previous LTS releases

**Comment by YungRaj** [comment]
+1 to this thread. Had the same issue and the workaround works like a charm! Thanks all
