### ISSUE TITLE
ci.bazel.io/job/bazel-tests on Windows is failing SkyframeTests

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2191]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/385/console

```There were 3 failures:
1) splitDeps(com.google.devtools.build.lib.skyframe.ConfigurationsForTargetsTest)
com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: No toolchain found for cpu 'ppc'. Valid cpus are: [
  k8,
  piii,
  darwin,
  x64_windows,
  armeabi-v7a,
]
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.selectToolchain(CrosstoolConfigurationLoader.java:346)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:134)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:72)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:47)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:66)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2) splitDeps(com.google.devtools.build.lib.skyframe.ConfigurationsForTargetsTest$WithDynamicConfigurations)
com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: No toolchain found for cpu 'ppc'. Valid cpus are: [
  k8,
  piii,
  darwin,
  x64_windows,
  armeabi-v7a,
]
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.selectToolchain(CrosstoolConfigurationLoader.java:346)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:134)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:72)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:47)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:66)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
3) splitDeps(com.google.devtools.build.lib.skyframe.ConfigurationsForTargetsTest$WithDynamicConfigurationsNoTrim)
com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: No toolchain found for cpu 'ppc'. Valid cpus are: [
  k8,
  piii,
  darwin,
  x64_windows,
  armeabi-v7a,
]
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.selectToolchain(CrosstoolConfigurationLoader.java:346)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:134)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:72)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:47)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:66)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURES!!!
Tests run: 523,  Failures: 3
```

**Comment by damienmg** [comment]
culprit is 7505d94c19727e3100ac5e16a960bff2cb324f23, rolling-back
