### ISSUE TITLE
Bazel CI flaky error __main__.BazelExternalRepositoryTest testNewHttpTarArchiveWithSymlinks


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21993]
CI: https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/018a9945-300c-7030-a16b-dff6d58298a8?branch=master

 Platform: 

 Logs: 
```
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/_main/src/test/py/bazel/bazel_external_repository_test.py", line 162, in testNewHttpTarArchiveWithSymlinks
    self.RunBazel([
  File "/b/f/w/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/_main/src/test/py/bazel/test_base.py", line 424, in RunBazel
    return self.RunProgram(
  File "/b/f/w/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/_main/src/test/py/bazel/test_base.py", line 580, in RunProgram
    self.AssertExitCode(exit_code, 0, stderr_lines, stdout_lines)
  File "/b/f/w/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/_main/src/test/py/bazel/test_base.py", line 191, in AssertExitCode
    self._AssertExitCodeIs(actual_exit_code, lambda x: x == expected_exit_code,
  File "/b/f/w/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/_main/src/test/py/bazel/test_base.py", line 176, in _AssertExitCodeIs
    self.fail('\n'.join([
AssertionError: Bazel exited with 48 (expected 0), stderr:

``` 
 Culprit: 

 Steps:
  ``` 
  
 ``` 
 CC Greenteam @comius

**Comment by meteorcloudy** [comment]
This flaky failure actually doesn't happen very often, so not prioritizing it as P1.
