### ISSUE TITLE
Bazel crash on `fail(*some_tuple)`

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#22066]
### Description of the bug:

Bazel crashes when `fail()` is applied to a tuple using the splat operator, i.e. `fail(*some_tuple)`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout https://github.com/aherrmann/rules_zig/commit/c2f9bb6b97a6a7b429f99d81dde74167ba61c49a.
Then run
```
$ cd e2e/workspace
$ bazel test //...
...
java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.skyframe.PackageValue.getPackage()" because the return value of "java.util.Map.get(Object)" is null
        at com.google.devtools.build.lib.skyframe.StarlarkBuildSettingsDetailsFunction.verifyBuildSettingsAndGetAliases(StarlarkBuildSettingsDetailsFunction.java:209)
        at com.google.devtools.build.lib.skyframe.StarlarkBuildSettingsDetailsFunction.getBuildSettingPackages(StarlarkBuildSettingsDetailsFunction.java:172)
        at com.google.devtools.build.lib.skyframe.StarlarkBuildSettingsDetailsFunction.compute(StarlarkBuildSettingsDetailsFunction.java:71)
        at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUp(ParallelEvaluator.java:422)
        at com.google.devtools.build.skyframe.ParallelEvaluator.waitForCompletionAndConstructResult(ParallelEvaluator.java:212)
        at com.google.devtools.build.skyframe.ParallelEvaluator.doMutatingEvaluation(ParallelEvaluator.java:178)
        at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:676)
        at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:147)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateBuildDriverKeys(SkyframeExecutor.java:2040)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.analyzeAndExecuteTargets(SkyframeBuildView.java:667)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:292)
        at com.google.devtools.build.lib.buildtool.AnalysisAndExecutionPhaseRunner.runAnalysisAndExecutionPhase(AnalysisAndExecutionPhaseRunner.java:241)
        at com.google.devtools.build.lib.buildtool.AnalysisAndExecutionPhaseRunner.execute(AnalysisAndExecutionPhaseRunner.java:139)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargetsWithMergedAnalysisExecution(BuildTool.java:305)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:173)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:510)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:478)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:163)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:116)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:664)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 7.1.1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

not that I know

### Any other information, logs, or outputs that you want to share?

`fail` is invoked [here in the example](https://github.com/aherrmann/rules_zig/commit/c2f9bb6b97a6a7b429f99d81dde74167ba61c49a#diff-46706bc3c7c7ccc520a62cd9b91eaa921610a014eeaa75dc68ba23c83924f311R79)

**Comment by hypdeb** [comment]
Similar stack trace on this repo: https://github.com/[hypdeb/gallery](https://github.com/hypdeb/gallery), when running `bazel run @rules_huggingface//:requirements.update`

**Comment by rickeylev** [comment]
I'm encountering this same error. It seems to happen when a module extension fails in some way.

Two weird things, though:
* It's happening in one workspace, but not another
* It happens with 7.0, 7.1, 7.2, 7.3, 7.4 and latest 8.x in the broken workspace.

So, something weird is definitely going on. I've tried bazel clean --expunge, deleting the bazel cache under $HOME, shutting down.

A mandatory attribute, or value outside of accepted values results in a no-error crash message.

A fail() in the module extension will print the message, but also result in a crash.

My repro is to add a fail() call to the start of `_python_impl` in `@rules_python//python/private/python.bzl`, around L277.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.3.0rc1. Thanks!
