### ISSUE TITLE
[Bazel CI] Bazel remote tests are failing with Bazel@HEAD in Downstream CI.


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#22190]
CI: https://docs.google.com/spreadsheets/d/1cTjhsv3E-wkvOvMAB1ZCRNeL2LEg86vR1ZYjw5NX-gs/edit?pli=1#gid=0

 Platform: Windows

 Logs: 
```

FAIL: [0m//src/test/java/com/google/devtools/build/lib/remote:DiskCacheIntegrationTest (Exit 1) (see C:/b/snpjvwjs/execroot/_main/bazel-out/x64_windows-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/remote/DiskCacheIntegrationTest/test_attempts/attempt_1.log)

FAIL: [0m//src/test/java/com/google/devtools/build/lib/remote:BuildWithoutTheBytesIntegrationTest (shard 1 of 5) (Exit 1) (see C:/b/snpjvwjs/execroot/_main/bazel-out/x64_windows-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/remote/BuildWithoutTheBytesIntegrationTest/shard_1_of_5/test_attempts/attempt_1.log)

FAIL: [0m//src/test/shell/bazel/android:proguard_integration_test_with_head_android_tools (Exit 1) (see C:/b/snpjvwjs/execroot/_main/bazel-out/x64_windows-fastbuild/testlogs/src/test/shell/bazel/android/proguard_integration_test_with_head_android_tools/test_attempts/attempt_1.log)
``` 
 
Culprit : [c92ecbf6b47c69b29baded7c5382398308372005](https://github.com/bazelbuild/bazel/commit/c92ecbf6b47c69b29baded7c5382398308372005)

 CC Greenteam @salmasamy

**Comment by tjgq** [comment]
All of the failures look like this:

```
1) bwobAndRemoteExec_blobsReferencedInAcAreMissingFromCas_ignoresAc(com.google.devtools.build.lib.remote.DiskCacheIntegrationTest)
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.readAllBytes()" because the return value of "com.google.devtools.build.lib.shell.Subprocess.getErrorStream()" is null
	at com.google.devtools.build.lib.remote.util.IntegrationTestUtils.waitForPortOpen(IntegrationTestUtils.java:54)
	at com.google.devtools.build.lib.remote.util.IntegrationTestUtils$WorkerInstance.start(IntegrationTestUtils.java:169)
	at com.google.devtools.build.lib.remote.util.IntegrationTestUtils.startWorker(IntegrationTestUtils.java:85)
	at com.google.devtools.build.lib.remote.util.IntegrationTestUtils.startWorker(IntegrationTestUtils.java:73)
	at com.google.devtools.build.lib.remote.DiskCacheIntegrationTest.startWorker(DiskCacheIntegrationTest.java:78)
	at com.google.devtools.build.lib.remote.DiskCacheIntegrationTest.bwobAndRemoteExec_blobsReferencedInAcAreMissingFromCas_ignoresAc(DiskCacheIntegrationTest.java:185)
```

which is a crash when handling a worker death while attempting to connect to it. I'll first fix the crash and include the worker stdout/stderr in the exception message; we can then understand what the actual problem looks like.

**Comment by fmeum** [comment]
@bazel-io fork 7.2.0
