### ISSUE TITLE
module retrieved from URL without extension fails

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22421]
### Description of the bug:

If a module is retrieved from a URL that does not have an archive extension, then the build fails. The URL can be set in a custom module definition, or with archive_override, or via a rewrite in downloader.cfg, all these cases fail.

For example, retrieving from a corporate cache:
```
bazel_dep(name = "rules_java", version = "7.5.0")
archive_override(
    module_name = "rules_java",
    urls = ["https://artifacts.ourcompany.com/artifactory/api/vcs/downloadTag/github/bazelbuild/rules_java/7.5.0?ext=tar.gz"]
)
```

Results in output:
```
D:\workspace>bazel build //src/build/out:all --config=offline2
INFO: Repository rules_java~ instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  D:/b/nag22qmp/external/bazel_tools/tools/build_defs/repo/http.bzl:391:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_java~':
   Traceback (most recent call last):
        File "D:/b/nag22qmp/external/bazel_tools/tools/build_defs/repo/http.bzl", line 136, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: Expected a file with a .zip, .jar, .war, .aar, .tar, .tar.gz, .tgz, .tar.xz, .txz, .tar.zst, .tzst, .tar.bz2, .tbz, .ar or .deb suffix (got D:/b/nag22qmp/external/rules_java~/temp9089459162989031511/7.5.0)
ERROR: <builtin>: fetching http_archive rule //:rules_java~: Traceback (most recent call last):
        File "D:/b/nag22qmp/external/bazel_tools/tools/build_defs/repo/http.bzl", line 136, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: Expected a file with a .zip, .jar, .war, .aar, .tar, .tar.gz, .tgz, .tar.xz, .txz, .tar.zst, .tzst, .tar.bz2, .tbz, .ar or .deb suffix (got D:/b/nag22qmp/external/rules_java~/temp9089459162989031511/7.5.0)
ERROR: Error computing the main repository mapping: error during computation of main repo mapping: Expected a file with a .zip, .jar, .war, .aar, .tar, .tar.gz, .tgz, .tar.xz, .txz, .tar.zst, .tzst, .tar.bz2, .tbz, .ar or .deb suffix (got D:/b/nag22qmp/external/rules_java~/temp9089459162989031511/7.5.0)
```

download_and_extract takes an expected suffix, but ideally any fix would support URL rewrites to URLs without extensions in downloader.cfg. When such URLs are retrieved from artifactory, they come back with these headers:
```
x-artifactory-filename: rules_java-7.5.0.tar.gz
content-type: application/x-gzip
content-disposition: attachment; filename="rules_java-7.5.0.tar.gz"
```

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Put an archive on a server with no extension, supply as archive_override (see above)

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 7.2.0rc1

**Comment by peakschris** [comment]
Note, I have found a workaround to this, by using a 'generic' mirror rather than 'vcs' mirror in Artifactory. This results in filenames that are the same as original. Feel free to close or leave open if a fix would still be useful to others.

**Comment by HarveyJMartin** [comment]
+1 on a real fix

**Comment by Wyverald** [comment]
This should've been fixed with https://github.com/bazelbuild/bazel/issues/24412. Could you try to use the `type` parameter in `archive_override` with 8.0?
