### ISSUE TITLE
7.2.0rc1 crashes on startup: Unrecoverable Error

### ISSUE THREAD

**Issue by kolloch** [bazelbuild/bazel#22489]
### Description of the bug:

When I update our internal Bazel repo from `7.1.2` to `7.2.0rc1`, I get the following error on startup:

```
2024/05/22 09:47:04 Downloading https://releases.bazel.build/7.2.0/rc1/bazel-7.2.0rc1-linux-x86_64...
2024/05/22 09:47:04 Skipping basic authentication for releases.bazel.build because no credentials found in /home/peter/.netrc
Downloading: 68 MB out of 68 MB (100%) 
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Computing main repo mapping: 
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'Key{moduleKey=<root>, override=null}' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelModuleResolutionValue$$Lambda/0x00000008004c51e0@f40784e')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.NoSuchElementException
        at java.base/java.util.List.getFirst(Unknown Source)
        at com.google.devtools.build.lib.bazel.bzlmod.ModuleFileFunction.evaluateRootModuleFile(ModuleFileFunction.java:443)
        at com.google.devtools.build.lib.bazel.bzlmod.ModuleFileFunction.computeForRootModule(ModuleFileFunction.java:280)
        at com.google.devtools.build.lib.bazel.bzlmod.ModuleFileFunction.compute(ModuleFileFunction.java:141)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
        ... 7 more
```

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Locally, in this repo, even `bazel info` crashes.

```
# MODULE.bazel
module(
    name = "nx0",
    version = "0.1",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

```

```
# .bazelversion
7.2.0rc1
```

### Which operating system are you running Bazel on?

Ubuntu 22.04.4 LTS (jammy) amd64

### What is the output of `bazel info release`?

release 7.2.0rc1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

first bad commit is https://github.com/bazelbuild/bazel/commit/298d3d619777982a23e6a683a13406b6a6f188d0

### Any other information, logs, or outputs that you want to share?

I happy to, just let me know!

**Comment by kolloch** [comment]
I could reduce the repo to a quite minimal example:

```
# MODULE.bazel
module(
    name = "nx0",
    version = "0.1",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

```

```
# .bazelversion
7.2.0rc1
```

**Comment by kolloch** [comment]
Ok, funnily enough, we don't even need that http_archive repo rule :) But maybe it is an interesting edge case and at least the error message could be better.

**Comment by fmeum** [comment]
@bazel-io fork 7.2.0
