### ISSUE TITLE
Duplicate error message in evaluation of module.bazel

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#22520]
### Description of the bug:

In some cases, errors in a MODULE.bazel file lead to a duplicate error message, with duplicate Starlark stacktrace.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here's a small repro:

```starlark
# MODULE.bazel

bazel_dep(name = "mydep")
archive_override(
  module_name = "mydep",
  urls = ["invalid"],
)
```

```bash
$ bazel build ...
INFO: Repository mydep~ instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  /Users/laurent/output_base/external/bazel_tools/tools/build_defs/repo/http.bzl:397:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'mydep~':
   Traceback (most recent call last):
	File "/Users/laurent/output_base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Bad URL: invalid
ERROR: <builtin>: fetching http_archive rule //:mydep~: Traceback (most recent call last):
	File "/Users/laurent/output_base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Bad URL: invalid
ERROR: Error computing the main repository mapping: error during computation of main repo mapping: java.io.IOException: Bad URL: invalid
```

Notice that the Starlark stacktrace appears twice. In this mini example, the stacktrace is still short, but it can be longer in other scenarios.

### What is the output of `bazel info release`?

release 7.1.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I've tested with both bazel 7.1.0 and last_green.

**Comment by laurentlb** [comment]
Thank you for the quick fix! ❤️
