### ISSUE TITLE
Error prone integration is broken

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2254]
Bazel forked different version for `checker_framework_dataflow` library > 2.0, as used in error prone itself: 1.8.10. To trigger the crash, specific bug pattern checks must be activated (that are not run per default). To reliably reproduce the problem on 0.4.2, apply this patch on Gerrit Code Review [1] and run:

```
$ bazel build gerrit-server:reviewer-predicate 
INFO: Found 1 target...
ERROR: /home/davido/projects/gerrit/gerrit-server/BUILD:20:1: Java compilation in rule '//gerrit-server:reviewer-predicate' failed: Worker process sent response with exit code: 4.
gerrit-server/src/main/java/com/google/gerrit/server/query/change/IsReviewedPredicate.java:55: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    return !reviewedBy.isEmpty() ? reviewedBy.contains(id) : id == NOT_REVIEWED;
                                                                ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.13
     Stack Trace:
     com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.checkerframework.dataflow.cfg.UnderlyingAST$CFGStatement.<init>(Lcom/sun/source/tree/Tree;)V
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
  	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
  	at com.google.errorprone.dataflow.DataFlow.methodDataflow(DataFlow.java:144)
  	at com.google.errorprone.dataflow.DataFlow.expressionDataflow(DataFlow.java:190)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessAnalysis.getNullness(NullnessAnalysis.java:61)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.getNullness(AbstractReferenceEquality.java:109)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.addFixes(AbstractReferenceEquality.java:84)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.matchBinary(AbstractReferenceEquality.java:65)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:554)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1958)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.visitConditionalExpression(TreeScanner.java:406)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:681)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1361)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:470)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:1066)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1518)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:575)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:943)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:635)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:123)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:101)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:134)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1257)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:865)
  	at com.sun.tools.javac.main.Main.compile(Main.java:253)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:140)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:132)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.invokeJavac(AbstractJavaBuilder.java:66)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:64)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:69)
  	at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:108)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:92)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:70)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)
  Caused by: java.lang.NoSuchMethodError: org.checkerframework.dataflow.cfg.UnderlyingAST$CFGStatement.<init>(Lcom/sun/source/tree/Tree;)V
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.fieldInitializerNullnessIfAvailable(NullnessPropagationTransfer.java:648)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.fieldNullness(NullnessPropagationTransfer.java:602)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.visitFieldAccess(NullnessPropagationTransfer.java:437)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitFieldAccess(AbstractNullnessPropagationTransfer.java:293)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitFieldAccess(AbstractNullnessPropagationTransfer.java:125)
  	at org.checkerframework.dataflow.cfg.node.FieldAccessNode.accept(FieldAccessNode.java:79)
  	at org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:362)
  	at org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:199)
  	at com.google.errorprone.dataflow.DataFlow$1.load(DataFlow.java:81)
  	at com.google.errorprone.dataflow.DataFlow$1.load(DataFlow.java:72)
  	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  	... 82 more
1 error
Target //gerrit-server:reviewer-predicate failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.629s, Critical Path: 0.40s
```

FWIW, Buck error prone integration, implemented in this CL: [2] just works, as it consequently uses error prone and all transitive dependencies from error prone 2.0.15 release:

```
$ buck build --config sanitizers.error_prone=1 gerrit-server:server
```

And all error prone default warnings are reported in Buck log file:

```
$ cat buck-out/log/buck-0.log
[...]
[2016-12-16 10:15:52.928][debug][command:3c6161b6-8be7-4585-90df-469782c3c8e7][tid:52][com.facebook.buck.jvm.java.Jsr199Javac] javac: /home/davido/projects/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/query/change/IsReviewedPredicate.java:55: warning: [ReferenceEquality] Comparison using reference equality instead of value equality
    return !reviewedBy.isEmpty() ? reviewedBy.contains(id) : id == NOT_REVIEWED;
                                                                ^
    (see http://errorprone.info/bugpattern/ReferenceEquality)
  Did you mean 'return !reviewedBy.isEmpty() ? reviewedBy.contains(id) : Objects.equals(id, NOT_REVIEWED);' or 'return !reviewedBy.isEmpty() ? reviewedBy.contains(id) : id.equals(NOT_REVIEWED);'?
[...]
```

* [1] https://gerrit-review.googlesource.com/93159
* [2] https://gerrit-review.googlesource.com/92919

**Comment by davido** [comment]
Started a downgrade attempt for dataflow dependency: [1].

* [1] https://bazel-review.googlesource.com/8390
