### ISSUE TITLE
Bazel crashes when loading from non-existing repository

### ISSUE THREAD

**Issue by AlexanderGolovlev** [bazelbuild/bazel#22565]
### Description of the bug:

Bazel 7.0 crashes when load() statement in WORKSPACE file refers to undefined repository:

`FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because "cause" is null
        at com.google.devtools.build.lib.analysis.config.InvalidConfigurationException.<init>(InvalidConfigurationException.java:53)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createBuildConfigurationKey(SkyframeExecutor.java:1794)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfiguration(SkyframeExecutor.java:1733)
        at com.google.devtools.build.lib.runtime.commands.InfoCommand.lambda$exec$0(InfoCommand.java:158)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:215)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:664)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)`

Version 6.5.0 handles this error properly:

`ERROR: Failed to load Starlark extension '@missing//:setup.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @missing
This could either mean you have to add the '@missing' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cannot load build configuration because of this cycle`

### Which category does this issue belong to?

Starlark Interpreter

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a WORKSPACE.bazel file with following content:
`load("@missing//:setup.bzl", "init")`
`init()`

Run `bazel info`

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 7.0.2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, version 6.5.0 properly handles the error.

**Comment by meisterT** [comment]
This doesn't crash at HEAD anymore
