### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:cpp-rules-tests fails on Windows and Darwin

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#2258]
//src/test/java/com/google/devtools/build/lib:cpp-rules-tests is consistently failing on Windows in CI.

Attaching error log as a file.
[windows-cpp-error.txt](https://github.com/bazelbuild/bazel/files/657739/windows-cpp-error.txt)

**Comment by katre** [comment]
Looks like this isn't windows-specific, it is also failing on Darwin:
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/lastBuild/console

**Comment by katre** [comment]
Looking into this.

**Comment by katre** [comment]
git bisect fingers 0f4260bf916d70457f358a1f1dfbbd55d4c4b04c as the culprit.

**Comment by katre** [comment]
The test is specifically looking for k8 output, ignoring darwin, etc.

**Comment by katre** [comment]
Still failing on windows:
```
1) testCompilesTestSourcesIntoDynamicLibrary(com.google.devtools.build.lib.rules.cpp.CppLinkActionTest)
java.lang.AssertionError: <[src external/bazel_tools/tools/cpp/empty, src external/bazel_tools/tools/cpp/link_dynamic_library.sh, / _bin/build_interface_so, bin _solib_x64_windows/libx_Sliba.so, bin x/a.exe-2.params]> should have contained <bin _solib_x64_windows/libx_Sliba.ifso>
```

Looks like the extension is different there.

**Comment by laszlocsomor** [comment]
@katre , thanks for looking into this and sorry I didn't reply, it was Friday night when I got this bug.

**Comment by laszlocsomor** [comment]
It's currently failing because it [can't find Visual Studio](http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/416/console), even though it's installed (I just RDP'd into the machine).

```

c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64>c:\bazel_ci\installs\latest\bazel.exe --bazelrc=c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64\.bazelrc test //src/test/java/... //src/test/shell/bazel:bazel_windows_example_test 
____Loading package: src/test/shell/bazel
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
WARNING: C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3: 
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start looking for python in PATH.
.
WARNING: C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3: 
Auto-Configuration Warning: Python found at C:/python_27_amd64/files/python.exe
.
WARNING: C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3: 
Auto-Configuration Warning: 'BAZEL_VS' is not set, start looking for the latest Visual Studio installed.
.
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl", line 520
		_find_vs_path(repository_ctx)
	File "C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl", line 426, in _find_vs_path
		auto_configure_fail("Visual Studio not found on your...")
	File "C:/bazel_ci/temp/_bazel_SYSTEM/ufohOx12/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configure_fail
		fail("
%sAuto-Configuration Error:%s ...))

Auto-Configuration Error: Visual Studio not found on your machine.
```

**Comment by katre** [comment]
@laszlocsomor Do you know what the issue with VS is?

**Comment by laszlocsomor** [comment]
I don't, @meteorcloudy is the one who knows the autoconfig rule but he's on vacation already. I can take a look.

**Comment by laszlocsomor** [comment]
Wait, "bazel-tests" is green at HEAD (417).
The VS not found error came from "bazel", I thought that was the affected job.
As it happens "bazel" is also green now so I proclaim this is a flake.

**Comment by katre** [comment]
Sounds good, thanks!
