### ISSUE TITLE
NPE with mod show_extension

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#22642]
### Description of the bug:

```

$ bazel mod show_extension @bazel_skylib//foo%bar.bzl
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableSetMultimap.keySet()" because the return value of "com.google.common.collect.ImmutableMap.get(Object)" is null
	at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModExecutor.displayExtension(ModExecutor.java:472)
	at com.google.devtools.build.lib.bazel.bzlmod.modcommand.ModExecutor.showExtension(ModExecutor.java:145)
	at com.google.devtools.build.lib.bazel.commands.ModCommand.execInternal(ModCommand.java:549)
	at com.google.devtools.build.lib.bazel.commands.ModCommand.exec(ModCommand.java:132)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:683)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:252)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:676)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Note that @bazel_skylib exists, but foo and bar.bzl don't.

This still crashes with last_green.

### Which category does this issue belong to?

External Dependency

### What is the output of `bazel info release`?

release 7.1.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.3.0rc1`. Thanks!
