### ISSUE TITLE
bazel help *rulename* crashes

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2270]
```
$ bazel help cc_library
java.lang.NullPointerException
	at com.google.devtools.build.docgen.SourceFileReader$1.endBlazeAttributeDoc(SourceFileReader.java:216)
	at com.google.devtools.build.docgen.SourceFileReader$1.readLineImpl(SourceFileReader.java:119)
	at com.google.devtools.build.docgen.SourceFileReader$ReadAction.readLine(SourceFileReader.java:70)
	at com.google.devtools.build.docgen.SourceFileReader.readTextFile(SourceFileReader.java:317)
	at com.google.devtools.build.docgen.SourceFileReader.readDocsFromComments(SourceFileReader.java:88)
	at com.google.devtools.build.docgen.BuildDocCollector.collectDocs(BuildDocCollector.java:276)
	at com.google.devtools.build.docgen.BuildDocCollector.collectDocs(BuildDocCollector.java:297)
	at com.google.devtools.build.docgen.BuildDocCollector.collectDocs(BuildDocCollector.java:297)
	at com.google.devtools.build.docgen.BuildDocCollector.collect(BuildDocCollector.java:127)
	at com.google.devtools.build.docgen.BuildDocCollector.collect(BuildDocCollector.java:165)
	at com.google.devtools.build.docgen.BlazeRuleHelpPrinter.getRuleDoc(BlazeRuleHelpPrinter.java:40)
	at com.google.devtools.build.lib.runtime.commands.HelpCommand.exec(HelpCommand.java:187)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:517)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:332)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:735)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1500(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:802)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ulfjack** [comment]
Setting P1, because it's a crasher bug. Note that this can't possibly work because we don't ship the rule Java source files as part of the binary, as we shouldn't.
