### ISSUE TITLE
experimental_execution_log_compact_file with toplevel flags fails with IOException while logging spawn: 

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#22920]
### Description of the bug:

With Bazel 7.2.1 if you have the following flags enabled
```
--experimental_execution_log_compact_file=compact_exec.log
--remote_download_outputs=toplevel
```

The build will fail with an `IOException ` if you have an action that uses a directory as input/output. Example:
```
12:35:50 19:35:51 [Bazel] ERROR: /var/lib/jenkins/workspace/android/snapchat/platform/media/decoders/gav1-dynamic-feature/BUILD.bazel:4:11: Merging AAR embedded jars failed: IOException while logging spawn: /home/jenkins/Snapchat/Dev/.cache/bazel/x86_64/6f9c9cb8506de64f63094a5ee74046fa/execroot/__main__/bazel-out/arm64-v8a-fastbuild-android-ST-f6ab2eff499b/bin/platform/media/decoders/gav1-dynamic-feature/_aar/unzipped (No such file or directory)
```
or 
```
21:54:30 [Bazel] ERROR: /Users/devicelab/Snapchat/Dev/.cache/bazel/arm64/200c81ba794154ad95d9a76cac3f836f/external/snap_client/src/composer_modules/src/composer/jasmine/BUILD.bazel:9:16: Linking external/snap_client/src/composer_modules/src/composer/jasmine/libjasmine_api_objc.a failed: IOException while logging spawn: /Users/devicelab/Snapchat/Dev/.cache/bazel/arm64/200c81ba794154ad95d9a76cac3f836f/execroot/phantom/bazel-out/ios_arm64-dbg-ios-arm64-min14.0-applebin_ios-ST-90933ed6271b/bin/external/snap_client/src/composer_modules/src/composer/jasmine/_objs/jasmine_api_objc/arc/debug_api_objc_srcs (No such file or directory)

```

This is similar to https://github.com/bazelbuild/bazel/issues/21820 
and related to https://github.com/bazelbuild/bazel/pull/22253

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

Mac and Linux 

### What is the output of `bazel info release`?

7.2.1

### Have you found anything relevant by searching the web?

This is similar to https://github.com/bazelbuild/bazel/issues/21820 
and related to https://github.com/bazelbuild/bazel/pull/22253

**Comment by nkoroste** [comment]
FYI @iancha1992 and @tjgq

**Comment by nkoroste** [comment]
The repro steps are in the PR description

**Comment by tjgq** [comment]
@nkoroste Can you provide a self-contained repro, including the BUILD and .bzl files? I can't repro with a trivial pair of rules that produce/consume a tree artifact, so there must be something else causing the issue.

**Comment by nkoroste** [comment]
The key for repro is to `have an action that uses a **directory** as input/output`. I believe `rules_android` might do this by default. I can try to create a sample project but wont be able to do it any time soon.

**Comment by criemen** [comment]
We're also hitting this, on 7.3.1 and `last_green`, on all 3 OS, reproducible.

Some extra information: We also have a directory dependency, and we run the test therefore outside of the sandbox.
I failed to recreate a small reproducing example - despite my best efforts, that just works.
I checked that the directory in the execution root is indeed missing (the IOException is correct), even though it's a declared data dependency of the test. For the "reproducer", the directory exists in the exec root, therefore we're also not seeing the exception.
I'm not sure what triggers the deletion/absence of that directory in our build.

**Comment by tjgq** [comment]
@criemen Can you please confirm that the directory in question is indeed a `ctx.actions.declare_directory`, and not something weirder (e.g. a source directory, or an output directory that was actually declared as a `ctx.actions.declare_file`)?

**Comment by criemen** [comment]
It's quite weird: We are declaring a data dependency on a source directory that is, in fact, a bazel module by itself (and a git repository).

We need this as we maintain our own programming language (CodeQL), and have unit tests that need access to all the source code published in https://github.com/github/codeql. So we do break test isolation (on purpose) by having that directory dependency.

**Comment by tjgq** [comment]
Thanks, that's useful information. Let me find some time to play around and try to come up with a repro. It might take a while, though - I'm already oversubscribed with Bazel 8 work :(

**Comment by criemen** [comment]
My reproducer that doesn't work is here: https://github.com/criemen/bazel-repro-exec-log
This mirrors our internal setup quite closely, while ripping out a lot of intermediate layers/macros.

**Comment by veJoshua** [comment]
The bug seems to be still present in Bazel 8.1.1

Are there any updates @tjgq ?
What would you need to further analyze the issue? Using the JSON format of the log file works just fine but is not feasible due to the sheer size of the generated log file.

**Comment by veJoshua** [comment]
Are there any updates @tjgq ?

**Comment by fmeum** [comment]
@criemen I just tried your reproducer, but can't get it to fail with any of 7.3.1 and HEAD. Do I need to do more than run `bazel test //...`?

**Comment by criemen** [comment]
@fmeum I never got the reproducer to actually reproduce the issue :/ It was in spirit of our failing setup, but it's clearly failing to replicate the problem (either because I missed an important detail, or due to scale). Sorry :(

**Comment by chitoge** [comment]
We are also encountering this issue reliably on Bazel 7.5.0 and 7.6.1.

**Comment by pswaminathan** [comment]
We are encountering this on 8.3.1, and it doesn't seem to matter what we set the `remote_download` flag to. That is, `--remote_download_all` doesn't resolve it. But again, it is specific to the compact execution log—using no log or the full log avoids it. A specific example file failing is an object output from a `cc_common.compile` call. i.e.:

```
(compilation_context, compilation_outputs) = cc_common.compile(...)
print(compilation_outputs.objects)

Output:
[<generated file src/proto/galley/messages/_objs/ergatta_galley_messages_proto.upb_minitable/biome.upb_minitable.o>, <generated file src/proto/galley/messages/_objs/ergatta_galley_messages_proto.upb_minitable/biome>]
```

And then the error:

```
Linking _nativedeps/8f977558.so failed: IOException while logging spawn: /private/var/tmp/_bazel_p/76c752657a731857d55964ee27c09392/execroot/_main/bazel-out/darwin_arm64-opt-android-ST-4cf3fc44044d/bin/src/proto/galley/messages/_objs/ergatta_galley_messages_proto.upb_minitable/biome (No such file or directory)
```

This looks similar to the second example file in the original report, but not the first.

**Comment by iancha1992** [comment]
@bazel-io fork 7.7.0

**Comment by iancha1992** [comment]
@fmeum @tjgq Is there any update on this issue?

**Comment by fmeum** [comment]
@pswaminathan Could you try to create a reproducer? I've received reports of this offline and would like to fix it, but likely need a reproducer to make progress.

**Comment by fmeum** [comment]
If anyone can still reproduce this, please run with `--verbose_failures` so that we can see a stack trace.

**Comment by hauserx** [comment]
Here is repro for a similar issue, extracted from `Permission denied` I got in some actual rule. This works with no issues if execution log is not being created. Fails on `last_green` as well.

`BUILD.bazel`

```python
load("gen_unreadable_file.bzl", "gen_unreadable_file")

gen_unreadable_file(
    name = "gen_unreadable",
)
```

`gen_unreadable_file.bzl`

```python
def _impl(ctx):
    out_dir = ctx.actions.declare_directory("out_dir")

    ctx.actions.run_shell(
        command = 'echo xx > "%s/unreadable" && chmod 000 "%s/unreadable"' % (out_dir.path, out_dir.path),
        outputs = [out_dir],
    )

    return [DefaultInfo(files=depset(direct=[out_dir]))]

gen_unreadable_file = rule(
    implementation = _impl,
)
```

```bash
touch MODULE.bazel

USE_BAZEL_VERSION=8.4.2 bazel build :gen_unreadable  --experimental_execution_log_compact_file=compact_exec.log

ERROR: /tmp/ioexc-repro/BUILD.bazel:3:20: Action out_dir failed: IOException while logging spawn: /(...)/66e9556618aff7305c008afff91a92a7/execroot/_main/bazel-out/k8-fastbuild/bin/out_dir/unreadable (Permission denied)
```

**Comment by fmeum** [comment]
I think that this happens because output file permissions are only fixed up by `SkyframeActionExecutor#checkOutputs`, which necessarily runs after the spawn has been logged.

**Comment by hauserx** [comment]
Just FYI, in case if it's any help in this other issue with file not found, stack trace for Permission denied error taken from the server log - the Permission denied error is rather an annoyance for us, not a real blocker. Posting it if helps with solving actual issue others have.  

<details>

```
251016 08:00:05.765:WT 345 [com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run] Aborting evaluation while evaluating ActionLookupData0{actionLookupKey=ConfiguredTargetKey{label=//:gen_unreadable, config=BuildConfigurationKey[e8494724f8baac23aca058d3505bda14b53b5306128c401b729b89c7aeb7b13c]}, actionIndex=0}
com.google.devtools.build.lib.skyframe.ActionExecutionFunction$ActionExecutionFunctionException: com.google.devtools.build.lib.actions.AlreadyReportedActionExecutionException: IOException while logging spawn: /home/grzegorz.lukasik/.cache/bazel/_bazel_grzegorz.lukasik/a81b5ac6b5d7900969957b5de3807d8b/execroot/_main/bazel-out/k8-fastbuild/bin/out_dir/unreadable (Permission denied)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:406)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:218)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.google.devtools.build.lib.actions.AlreadyReportedActionExecutionException: IOException while logging spawn: /home/grzegorz.lukasik/.cache/bazel/_bazel_grzegorz.lukasik/a81b5ac6b5d7900969957b5de3807d8b/execroot/_main/bazel-out/k8-fastbuild/bin/out_dir/unreadable (Permission denied)
	... 11 more
Caused by: com.google.devtools.build.lib.actions.EnvironmentalExecException: IOException while logging spawn: /home/grzegorz.lukasik/.cache/bazel/_bazel_grzegorz.lukasik/a81b5ac6b5d7900969957b5de3807d8b/execroot/_main/bazel-out/k8-fastbuild/bin/out_dir/unreadable (Permission denied)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:214)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:121)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:46)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:253)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1177)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1082)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:166)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:95)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:566)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:946)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:377)
	... 10 more
Caused by: com.google.devtools.build.lib.vfs.FileAccessException: /home/grzegorz.lukasik/.cache/bazel/_bazel_grzegorz.lukasik/a81b5ac6b5d7900969957b5de3807d8b/execroot/_main/bazel-out/k8-fastbuild/bin/out_dir/unreadable (Permission denied)
	at com.google.devtools.build.lib.vfs.AbstractFileSystem.getInputStream(AbstractFileSystem.java:66)
	at com.google.devtools.build.lib.vfs.FileSystem$1.openStream(FileSystem.java:356)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:256)
	at com.google.common.io.ByteSource.hash(ByteSource.java:340)
	at com.google.devtools.build.lib.vfs.FileSystem.getDigest(FileSystem.java:358)
	at com.google.devtools.build.lib.unix.UnixFileSystem.getDigest(UnixFileSystem.java:497)
	at com.google.devtools.build.lib.vfs.Path.getDigest(Path.java:711)
	at com.google.devtools.build.lib.vfs.DigestUtils.manuallyComputeDigest(DigestUtils.java:179)
	at com.google.devtools.build.lib.vfs.DigestUtils.getDigestWithManualFallback(DigestUtils.java:142)
	at com.google.devtools.build.lib.exec.SpawnLogContext.computeDigest(SpawnLogContext.java:194)
	at com.google.devtools.build.lib.exec.CompactSpawnLogContext.lambda$expandDirectory$8(CompactSpawnLogContext.java:615)
	at com.google.devtools.build.lib.exec.CompactSpawnLogContext$DirectoryVisitor.visitSubdirectory(CompactSpawnLogContext.java:118)
	at com.google.devtools.build.lib.exec.CompactSpawnLogContext$DirectoryVisitor.lambda$run$0(CompactSpawnLogContext.java:102)
	... 8 more
```

</details>

**Comment by simonrummert** [comment]
Hi @fmeum and others. We are also facing the same issue in our workspace. We are planning to migrate to Bazel 8 soon, would it be possible to backport this fix also to Bazel 8?

Thanks in advance!

**Comment by fmeum** [comment]
cc @iancha1992 

Probably yes if there is going to be a further release, but 8.8.0 already has an RC at this point.

**Comment by iancha1992** [comment]
> Hi [@fmeum](https://github.com/fmeum) and others. We are also facing the same issue in our workspace. We are planning to migrate to Bazel 8 soon, would it be possible to backport this fix also to Bazel 8?
> 
> Thanks in advance!

@simonrummert  You should consider migrating to Bazel 9 because it does contain the fix.

**Comment by simonrummert** [comment]
@iancha1992 We are planning to go to Bazel 9 after we finalize our migration to Bzlmod. As we have a very large monorepo, this migration will take some time and is not something we can do quickly.

So if you are planning to do another Bazel 8 release after 8.8.0, it would be awesome if you could include this fix as a backport :-)

**Comment by iancha1992** [comment]
@bazel-io fork 8.8.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.8.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.8.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.8.0rc2`. Thanks!

**Comment by iancha1992** [comment]
> A fix for this issue has been included in [Bazel 8.8.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.8.0rc2). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.8.0rc2`. Thanks!

cc: @simonrummert

**Comment by pswaminathan** [comment]
This is still happening in 8.8.0rc2 for me. I put together a reproducer [here](https://github.com/pswaminathan/compact-cppoutput-repro).

**Comment by iancha1992** [comment]
> This is still happening in 8.8.0rc2 for me. I put together a reproducer [here](https://github.com/pswaminathan/compact-cppoutput-repro).

cc: @fmeum @tjgq @coeuvre

**Comment by fmeum** [comment]
@pswaminathan Could you test https://github.com/bazelbuild/bazel/pull/30816?

**Comment by pswaminathan** [comment]
@fmeum it's a litlte hard for me to test directly, because we aren't yet on Bazel 9, and we seem to see non-trivial breakages to fix. So it's not an apples-to-apples test. I cherry picked it onto 8.8.0rc2, with one basic conflict resolution and one not-as-basic method implementation. I am attaching a patch so you can see if this still maintains the intention. It does not fix the issue on our codebase—I see the same error I did previously. I'm having trouble getting the repro to build with this—it fails for a seemingly different reason.

[0001-Expand-tree-artifact-inputs-from-metadata-in-the-com.patch](https://github.com/user-attachments/files/31278578/0001-Expand-tree-artifact-inputs-from-metadata-in-the-com.patch)

**Comment by fmeum** [comment]
@pswaminathan That cherry-pick is incomplete, could you test with https://github.com/bazelbuild/bazel/pull/30830?

**Comment by pswaminathan** [comment]
@fmeum that fixes it—I'm able to use the compact execlog. Thank you!

**Comment by iancha1992** [comment]
> [@fmeum](https://github.com/fmeum) that fixes it—I'm able to use the compact execlog. Thank you!

A fix for this issue has been included in [Bazel 8.8.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.8.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.8.0rc3`. Thanks!

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 9.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/9.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=9.3.0rc1`. Thanks!
