### ISSUE TITLE
CI failure: //src/test/java/com/google/devtools/build/lib:actions_test is failing on Windows

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2300]
Log: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/437/console

Extract:
```
JUnit4 Test Runner
ERROR: 'null' is not recognized as an internal or external command,
operable program or batch file.
 (exit code: 1)
.....WARNING: There are no active jobs - stopping the build
WARNING: Still waiting for unfinished jobs
WARNING: Still waiting for 3 jobs to complete:
      Running (remote):
        action3, 1 s
      Running (something else):
        action4, 0 s
      Scheduling:
        action2, 2 s
Build will be stopped after these tasks terminate
........................................................................................E.E.E.........................................
Time: 33.656
There were 3 failures:
1) testAMDMachine(com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest)
java.lang.UnsatisfiedLinkError: no windows_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.windows.WindowsJniLoader.loadJni(WindowsJniLoader.java:27)
	at com.google.devtools.build.lib.windows.WindowsFileOperations.isJunction(WindowsFileOperations.java:37)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isJunction(WindowsFileSystem.java:383)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isDirectory(WindowsFileSystem.java:352)
	at com.google.devtools.build.lib.vfs.Path.isDirectory(Path.java:605)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTreesBelow(FileSystemUtils.java:565)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTree(FileSystemUtils.java:553)
	at com.google.devtools.build.lib.vfs.util.FsApparatus.newNative(FsApparatus.java:63)
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest.<init>(LocalHostResourceManagerLinuxTest.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:87)
2) testHyperthreadedMachine(com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest)
java.lang.UnsatisfiedLinkError: no windows_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.windows.WindowsJniLoader.loadJni(WindowsJniLoader.java:27)
	at com.google.devtools.build.lib.windows.WindowsFileOperations.isJunction(WindowsFileOperations.java:37)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isJunction(WindowsFileSystem.java:383)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isDirectory(WindowsFileSystem.java:352)
	at com.google.devtools.build.lib.vfs.Path.isDirectory(Path.java:605)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTreesBelow(FileSystemUtils.java:565)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTree(FileSystemUtils.java:553)
	at com.google.devtools.build.lib.vfs.util.FsApparatus.newNative(FsApparatus.java:63)
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest.<init>(LocalHostResourceManagerLinuxTest.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:87)
3) testNonHyperthreadedMachine(com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest)
java.lang.UnsatisfiedLinkError: no windows_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.windows.WindowsJniLoader.loadJni(WindowsJniLoader.java:27)
	at com.google.devtools.build.lib.windows.WindowsFileOperations.isJunction(WindowsFileOperations.java:37)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isJunction(WindowsFileSystem.java:383)
	at com.google.devtools.build.lib.vfs.WindowsFileSystem.isDirectory(WindowsFileSystem.java:352)
	at com.google.devtools.build.lib.vfs.Path.isDirectory(Path.java:605)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTreesBelow(FileSystemUtils.java:565)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.deleteTree(FileSystemUtils.java:553)
	at com.google.devtools.build.lib.vfs.util.FsApparatus.newNative(FsApparatus.java:63)
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinuxTest.<init>(LocalHostResourceManagerLinuxTest.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:87)

FAILURES!!!
Tests run: 136,  Failures: 3
```

**Comment by damienmg** [comment]
First failure was on run [#421](http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/421/console). It probably got ignored because of the various other failures. This was testing commit 4fb378c0fa08131394dc5e815f6fe5597d007a66 to 87532156cf3ed7b66c6db5cb1e57dff7424031ab both included.

**Comment by damienmg** [comment]
likely culprit: d40c78a98e2b1f562170396f94bf54d17c6958d0

**Comment by damienmg** [comment]
I finally was able to repro and confirmed that d40c78a is responsible for this breakage.
