### ISSUE TITLE
[riscv][risc-v][riscv64]Cannot build Bazel 7.1.0 on RISC-V 64 (Lichee PI4A)

### ISSUE THREAD

**Issue by lazyprogrammerio** [bazelbuild/bazel#23018]
### Description of the bug:

Hello,

I am running Ubuntu 24.04 stock (riscv64) on the LicheePi 4A.

When trying to build bazel from source (7.1.0), I get an error, as it weirdly tries to build Bazel with Bazel (?) and it fails.

My first question is: why is it trying to build Bazel with Bazel -> `Building Bazel with Bazel`?

Reproduction steps:

```
# download and unzip / cd into bazel-7.1.0-dist.zip
# apt install java 21 jre and jdk
# dpkg --list |grep -i jdk
# ii  default-jdk-headless                             2:1.21-75+exp1                            riscv64      Standard Java or Java compatible  Development Kit (headless)
#
# ii  libanimal-sniffer-java                           1.16-1                                    all          JDK/API verification tools
#ii  openjdk-21-jdk:riscv64                           21.0.3+9-1ubuntu1                         riscv64      OpenJDK Development Kit (JDK)
#ii  openjdk-21-jdk-headless:riscv64                  21.0.3+9-1ubuntu1                         riscv64      OpenJDK Development Kit (JDK) (headless)
#ii  openjdk-21-jre:riscv64                           21.0.3+9-1ubuntu1                         riscv64      OpenJDK Java runtime, using Hotspot JIT
#ii  openjdk-21-jre-headless:riscv64                  21.0.3+9-1ubuntu1                         riscv64      OpenJDK Java runtime, using Hotspot JIT (headless)

env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
INFO: Repository rules_python~~python~pythons_hub instantiated at:
  <builtin>: in <toplevel>
Repository rule hub_repo defined at:
  /tmp/bazel_Jag75LiP/out/external/rules_python~/python/extensions/private/pythons_hub.bzl:107:27: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python~~python~pythons_hub':
   Traceback (most recent call last):
        File "/tmp/bazel_Jag75LiP/out/external/rules_python~/python/extensions/private/pythons_hub.bzl", line 86, column 33, in _hub_repo_impl
                platform = get_host_platform(os, arch)
        File "/tmp/bazel_Jag75LiP/out/external/rules_python~/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: <builtin>: fetching hub_repo rule //:rules_python~~python~pythons_hub: Traceback (most recent call last):
        File "/tmp/bazel_Jag75LiP/out/external/rules_python~/python/extensions/private/pythons_hub.bzl", line 86, column 33, in _hub_repo_impl
                platform = get_host_platform(os, arch)
        File "/tmp/bazel_Jag75LiP/out/external/rules_python~/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
```

### Which category does this issue belong to?

Core

**Comment by lazyprogrammerio** [comment]
For Bazel 6.1.0 I got this error:

```
🍃  Building Bazel from scratch....

..
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
DEBUG: /tmp/bazel_cZ6Gd5bJ/out/external/build_bazel_rules_nodejs/index.bzl:122:10: WARNING: check_rules_nodejs_version has been removed. This is a no-op, please remove the call.
INFO: Analyzed target //src:bazel_nojdk (383 packages loaded, 10322 targets configured).
INFO: Found 1 target...
[4 / 20] 2 actions, 1 running
    //src:create_embedded_tools; 0s local
    [Prepa] Writing file third_party/ijar/zipper-2.params
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.google.devtools.build.lib.unsafe.StringUnsafe
        at com.google.devtools.build.lib.actions.ParameterFile.writeContentLatin1(ParameterFile.java:141)
        at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:120)
        at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:112)
        at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction$ParamFileWriter.writeOutputFile(ParameterFileWriteAction.java:172)
        at com.google.devtools.build.lib.exec.FileWriteStrategy.beginWriteOutputToFile(FileWriteStrategy.java:58)
        at com.google.devtools.build.lib.analysis.actions.FileWriteActionContext.beginWriteOutputToFile(FileWriteActionContext.java:49)
        at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:66)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:957)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1082)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:160)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:93)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:516)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:827)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:323)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:161)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @6ce2b319 [in thread "skyframe-evaluator 2"]
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:194)
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:187)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<init>(StringUnsafe.java:61)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<clinit>(StringUnsafe.java:36)
        ... 22 more
```

**Comment by lazyprogrammerio** [comment]
For Bazel 7.1.0 and JDK 17:

```
nv EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
INFO: Repository rules_python~~python~pythons_hub instantiated at:
  <builtin>: in <toplevel>
Repository rule hub_repo defined at:
  /tmp/bazel_AXQaB2i5/out/external/rules_python~/python/extensions/private/pythons_hub.bzl:107:27: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python~~python~pythons_hub':
   Traceback (most recent call last):
        File "/tmp/bazel_AXQaB2i5/out/external/rules_python~/python/extensions/private/pythons_hub.bzl", line 86, column 33, in _hub_repo_impl
                platform = get_host_platform(os, arch)
        File "/tmp/bazel_AXQaB2i5/out/external/rules_python~/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: <builtin>: fetching hub_repo rule //:rules_python~~python~pythons_hub: Traceback (most recent call last):
        File "/tmp/bazel_AXQaB2i5/out/external/rules_python~/python/extensions/private/pythons_hub.bzl", line 86, column 33, in _hub_repo_impl
                platform = get_host_platform(os, arch)
        File "/tmp/bazel_AXQaB2i5/out/external/rules_python~/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: No platform declared for host OS linux on arch riscv64
INFO: Elapsed time: 30.732s, Critical Path: 0.35s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED:
    Fetching repository @@stardoc~; starting 7s
    Fetching repository @@rules_go~; starting 6s
    Fetching ...B2i5/out/external/stardoc~; Extracting stardoc-0.5.3.tar.gz 5s
    Fetching ...2i5/out/external/rules_go~; Extracting rules_go-v0.39.1.zip 5s
    Fetching repository @@apple_support~; starting
    Fetching ...external/apple_support~; Extracting apple_support.1.8.1.tar.gz

ERROR: Could not build Bazel
```

**Comment by lazyprogrammerio** [comment]
Seems like https://github.com/bazelbuild/rules_python/pull/1907/files is required to be able to build on riscv64.
https://github.com/bazelbuild/rules_python/commit/daf422472325a5ab3e56e8a4d1bd59699fb3280a -> present in version 0.33+ of the rules_python.

Which means that only Bazel v8.00+ will be able to properly build, see https://github.com/bazelbuild/bazel/commit/01f6decac7aa7ccd4c7c511517b1e1b4ab28c985.

One has to backport this commit https://github.com/bazelbuild/bazel/commit/01f6decac7aa7ccd4c7c511517b1e1b4ab28c985 to 7.1.0 and hope it builds.

**Comment by lazyprogrammerio** [comment]
From the documentation, I do not see a way to bootstrap without having a .dist release, how can I do it though with the git repo? Otherwise, I ll need to wait for a new tag and a release of 8.x.

**Comment by lazyprogrammerio** [comment]
RISC-V master is broken because this commit has been reverted/changed https://github.com/bazelbuild/bazel/commit/b34be09c480f94d000e1965956067275b199362d and it was not applied when it got reverted in the main repo and the functionality was switched to using the bazel_rules repository https://github.com/bazelbuild/rules_java/blame/master/toolchains/BUILD#L141

I opened a PR here: https://github.com/bazelbuild/rules_java/pull/198

**Comment by 6eanut** [comment]
@lazyprogrammerio hi
i am working on building tensorflow2.15.0 from source by bazel6.1.0.
i notice that the WORKFILE in tensorflow2.15.0 point to the rules_python is 0.26.0, which not support risc-v.
when i change the 0.26.0 to 0.33.0, i meet the error:
```
ERROR: /home/tf2150/tensorflow/WORKSPACE:61:10: //external:pypi: no such attribute 'requirements' in 'pip_repository' rule
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'requirements.bzl': no such package '@pypi//': error loading package 'external': Could not load //external package
```

you know something about it?
thanks very much!

**Comment by Geremia** [comment]
@lazyprogrammerio 
I get this error, too, when trying to build Bazel 6.5.0 with `JAVA_HOME=/usr/lib64/zulu-openjdk21`:
```
Building Bazel from scratch......
Building Bazel with Bazel.
.OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
DEBUG: /tmp/bazel_NSS5PyJI/out/external/build_bazel_rules_nodejs/index.bzl:122:10: WARNING: check_rules_nodejs_version has been removed. This is a no-op, please remove the call.
INFO: Analyzed target //src:bazel_nojdk (388 packages loaded, 10504 targets configured).
INFO: Found 1 target...
[0 / 1,032] 13 actions, 0 running
    @bazel_tools//third_party/ijar:zipper; 0s local
    //src:create_embedded_tools; 0s local
    //src/tools/singlejar:singlejar; 0s local
    @com_github_grpc_grpc//src/compiler:grpc_cpp_plugin; 0s local
    Writing file src/embedded_tools_nojdk.params; 0s local
    .../google/devtools/build/buildjar:bootstrap_VanillaJavaBuilder; 0s local
    @bazel_tools//tools/python:_generate_wrappers; 0s local
    @com_google_protobuf//:protoc; 0s local ...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NoClassDefFoundError: Could not initialize class com.google.devtools.build.lib.unsafe.StringUnsafe
        at com.google.devtools.build.lib.actions.ParameterFile.writeContentLatin1(ParameterFile.java:141)
        at com.google.devtools.build.lib.actions.ParameterFile.writeContent(ParameterFile.java:120)
        at com.google.devtools.build.lib.actions.ParameterFile.writeParameterFile(ParameterFile.java:112)
        at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction$ParamFileWriter.writeOutputFile(ParameterFileWriteAction.java:172)
        at com.google.devtools.build.lib.exec.FileWriteStrategy.beginWriteOutputToFile(FileWriteStrategy.java:58)
        at com.google.devtools.build.lib.analysis.actions.FileWriteActionContext.beginWriteOutputToFile(FileWriteActionContext.java:49)
        at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:66)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:961)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1128)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1086)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:160)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:93)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:519)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:827)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:323)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:161)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @1fc2b765 [in thread "skyframe-evaluator-5"]
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:194)
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:187)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<init>(StringUnsafe.java:61)
        at com.google.devtools.build.lib.unsafe.StringUnsafe.<clinit>(StringUnsafe.java:36)
        ... 25 more

ERROR: Could not build Bazel
```

**Comment by kxxt** [comment]
I have opened a PR to fix bazel 7.x for riscv64: https://github.com/bazelbuild/bazel/pull/25699
But there seems to be some trouble with the lockfile and the CI.

BTW, tensorflow main branch is now using bazel 7.
