### ISSUE TITLE
CI Failure: //src/test/java/com/google/devtools/build/lib:cpp-rules-tests is failing on windows

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2301]
Log: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/437/console

Extract:
```
==================== Test output for //src/test/java/com/google/devtools/build/lib:cpp-rules-tests:
JUnit4 Test Runner
ERROR: 'null' is not recognized as an internal or external command,
operable program or batch file.
 (exit code: 1)
.Dec 27, 2016 10:39:07 AM com.google.devtools.build.lib.skyframe.SkyframeBuildView setConfigurations
<snip snip snip>
Dec 27, 2016 10:40:05 AM com.google.devtools.build.lib.concurrent.AbstractQueueVisitor maybeSaveUnhandledThrowable
WARNING: Found critical error in queue visitor
java.lang.AssertionError: ERROR /workspace/hello/BUILD:1:1: in cc_library rule //hello:hello: Invalid toolchain configuration: Cannot find variable named 'bad_variable'.
	at org.junit.Assert.fail(Assert.java:88)
	at com.google.devtools.build.lib.testutil.FoundationTestCase$1.handle(FoundationTestCase.java:55)
	at com.google.devtools.build.lib.events.Reporter.handle(Reporter.java:110)
	at com.google.devtools.build.skyframe.ParallelEvaluatorContext$NestedSetEventReceiver.accept(ParallelEvaluatorContext.java:223)
	at com.google.devtools.build.skyframe.ParallelEvaluatorContext$NestedSetEventReceiver.accept(ParallelEvaluatorContext.java:211)
	at com.google.devtools.build.lib.collect.nestedset.NestedSetVisitor.visitRaw(NestedSetVisitor.java:76)
	at com.google.devtools.build.lib.collect.nestedset.NestedSetVisitor.visit(NestedSetVisitor.java:64)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:583)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

.Dec 27, 2016 10:40:06 AM com.google.devtools.build.lib.skyframe.SkyframeBuildView setConfigurations
<snip snip snip>
................
Time: 97.866
There was 1 failure:
1) testCompilesTestSourcesIntoDynamicLibrary(com.google.devtools.build.lib.rules.cpp.CppLinkActionTest)
java.lang.AssertionError: <[src external/bazel_tools/tools/cpp/empty, src external/bazel_tools/tools/cpp/link_dynamic_library.sh, / _bin/build_interface_so, bin _solib_x64_windows/libx_Sliba.so, bin x/a.exe-2.params]> should have contained <bin _solib_x64_windows/libx_Sliba.ifso>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
	at com.google.common.truth.IterableSubject.contains(IterableSubject.java:99)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionTest.testCompilesTestSourcesIntoDynamicLibrary(CppLinkActionTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:87)

FAILURES!!!
Tests run: 273,  Failures: 1
```

**Comment by damienmg** [comment]
I think the test is incorrect ifso file probably do not exists on Windows

**Comment by damienmg** [comment]
First failure was on run #414

**Comment by damienmg** [comment]
And git bisect blame 0f4260bf916d70457f358a1f1dfbbd55d4c4b04c

**Comment by damienmg** [comment]
It added the culprit test actually: testCompilesTestSourcesIntoDynamicLibrary, let just skip it on Windows.
