### ISSUE TITLE
internal error when using apple_support module

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#23111]
### Description of the bug:

Repro:

```
$ cat BUILD
cc_binary(
  name = "cc",
  srcs = ["main.cc"],
)

$ cat MODULE.bazel
bazel_dep(name = "apple_support", version = "1.16.0", repo_name = "build_bazel_apple_support")

$ bazel info release
release 7.2.1


$ bazel build :cc
INFO: Invocation ID: a0fd3096-62f7-4866-813a-0507f46964e2
INFO: Analyzed target //:cc (84 packages loaded, 441 targets configured).
[1 / 1] checking cached actions
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData0{actionLookupKey=ConfiguredTargetKey{label=//:cc, config=BuildConfigurationKey[c790c51cd204efcfc5fd8a11d0eb60ca464a606489367032bb6bb067b47d73fd]}, actionIndex=0}' (requested by nodes 'ActionLookupData2{actionLookupKey=ConfiguredTargetKey{label=//:cc, config=BuildConfigurationKey[c790c51cd204efcfc5fd8a11d0eb60ca464a606489367032bb6bb067b47d73fd]}, actionIndex=2}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: com.google.devtools.build.lib.rules.apple.DottedVersion$InvalidDottedVersionException: Dotted version components must all start with the form \d+([a-z0-9]*?)?(\d+)? but got 'None'
	at com.google.devtools.build.lib.rules.apple.DottedVersion.fromStringUnchecked(DottedVersion.java:180)
	at com.google.devtools.build.lib.exec.local.XcodeLocalEnvProvider.rewriteLocalEnv(XcodeLocalEnvProvider.java:98)
	at com.google.devtools.build.lib.sandbox.DarwinSandboxedSpawnRunner.prepareSpawn(DarwinSandboxedSpawnRunner.java:218)
	at com.google.devtools.build.lib.sandbox.AbstractSandboxSpawnRunner.exec(AbstractSandboxSpawnRunner.java:111)
	at com.google.devtools.build.lib.sandbox.SandboxModule$SandboxFallbackSpawnRunner.exec(SandboxModule.java:474)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:158)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:118)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1402)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1159)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:573)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:859)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:333)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:171)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	... 7 more
Caused by: com.google.devtools.build.lib.rules.apple.DottedVersion$InvalidDottedVersionException: Dotted version components must all start with the form \d+([a-z0-9]*?)?(\d+)? but got 'None'
	at com.google.devtools.build.lib.rules.apple.DottedVersion.fromString(DottedVersion.java:202)
	at com.google.devtools.build.lib.rules.apple.DottedVersion.fromStringUnchecked(DottedVersion.java:178)
	... 24 more
```

The line in the MODULE file is copied from https://github.com/bazelbuild/apple_support/releases/tag/1.16.0. I report the bug against Bazel itself because it crashes with an internal error.

### Which category does this issue belong to?

C++ Rules

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

7.2.1

**Comment by fmeum** [comment]
CC @keith @BalestraPatrick

**Comment by keith** [comment]
🤔 you might need a `bazel clean --expunge` between because of bad state invalidation

**Comment by laurentlb** [comment]
Yes, it works after clean. Thanks a lot!

**Comment by seh** [comment]
I found that running _bazel clean --expunge_ didn't help.

This is odd:
```
$ which xcodebuild
/usr/bin/xcodebuild

$ file /usr/bin/xcodebuild
/usr/bin/xcodebuild: Mach-O universal binary with 2 architectures: [x86_64:\012- Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>] [\012- arm64e (caps: 0x2):\012- Mach-O 64-bit arm64e (caps: PAC00) executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>]

$ xcodebuild -version
error: tool 'xcodebuild' not found

$ xcode-select -p
/nix/store/lsjl29pwp5if71jfgxlv8fifsrpax805-apple-sdk-11.3
```

**Comment by seh** [comment]
I also tried installing the _darwin.xcode_ module—including installing _Xcode.app_ within Nix's store—and I still can't get past this error:
> Dotted version components must all start with the form \d+([a-z0-9]*?)?(\d+)? but got 'None'

**Comment by keith** [comment]
Note that just `xcodebuild -version` running is not enough to get this logic to run correctly. It looks like you might not be on macOS running these commands? in which case some assumptions are definitely broken. Right now bazel runs xcode_locator.m which uses macOS APIs to discover the correct Xcode version

**Comment by seh** [comment]
> It looks like you might not be on macOS running these commands?

I'm running macOS, but I'm invoking Bazel inside of a Nix shell created with [the `mkShellNoCC` function](https://nixos.org/manual/nixpkgs/unstable/#sec-pkgs-mkShell-variants).

**Comment by akirchhoff-modular** [comment]
> It looks like something is setting the "XCODE_VERSION_OVERRIDE" environment variable to "None", and then `local.rewriteLocalEnv` fails to interpret "None" satisfactorily:
> 
> https://github.com/bazelbuild/bazel/blob/528c2c5e2e7341f9bf538f35077d29dd41988a71/src/main/java/com/google/devtools/build/lib/exec/local/XcodeLocalEnvProvider.java#L94-L95

I tracked this down a little further. That `None` string comes from here:

https://github.com/bazelbuild/bazel/blob/39b9d3ccdc9b5e160705506c7ea9b57a991d551a/src/main/starlark/builtins_bzl/common/objc/apple_env.bzl#L20

I wonder if it should be checking for `None` before barging ahead and doing `str(None)`? Though I doubt we're supposed to have a `None` by this point, in any case.

I believe the only way `xcode_version_info.xcode_version()` could be `None` is if on this line:

https://github.com/bazelbuild/bazel/blob/39b9d3ccdc9b5e160705506c7ea9b57a991d551a/src/main/starlark/builtins_bzl/common/xcode/xcode_config.bzl#L89

`xcode_version_properties.xcode_version` is `None`. I don't know under what circumstances that would be the case. I'm also not reproducing this issue myself, so not investigating further right now.

**Comment by akirchhoff-modular** [comment]
I'm experiencing this issue myself now. I believe Xcode updated and has a new license, because I'm also getting these warnings earlier in the build:

> You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.

This seems like it could cause the issue.

**Comment by akirchhoff-modular** [comment]
> I'm experiencing this issue myself now. I believe Xcode updated and has a new license, because I'm also getting these warnings earlier in the build:
> 
> > You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
> 
> This seems like it could cause the issue.

I agreed to the license and Bazel no longer crashes.  I would not be surprised if Bazel could not complete a build like this, but it probably shouldn't crash the way it does now.

**Comment by akirchhoff-modular** [comment]
> > I'm experiencing this issue myself now. I believe Xcode updated and has a new license, because I'm also getting these warnings earlier in the build:
> > > You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
> > 
> > 
> > This seems like it could cause the issue.
> 
> I agreed to the license and Bazel no longer crashes. I would not be surprised if Bazel could not complete a build like this, but it probably shouldn't crash the way it does now.

I stand corrected… After agreeing to the license, Bazel now crashes every other run. Aka:

1. Successful build
2. Bazel crash
3. Successful build
4. Bazel crash
5. Successful build
6. Bazel crash

**Comment by mhart** [comment]
> you have to have a full version of Xcode installed

Btw, why is this the case @keith ? The [`apple_support` repo](https://github.com/bazelbuild/apple_support) says "The toolchain supports using a full Xcode installation or the Xcode Command Line Tools"

**Comment by keith** [comment]
I improved that since that comment, no longer required

**Comment by mhart** [comment]
> I improved that since that comment, no longer required

Ah ok – I'm seeing this error when I only have Xcode Command Line Tools installed (it goes away when I install XCode and clean the cache). But I'm guessing that's going to be fixed elsewhere and then this should be fine?

**Comment by keith** [comment]
The original issue here isn't helped by that improvement, idk how these issues got so mixed up but this newer issue is also tracking what was reported here https://github.com/bazelbuild/bazel/issues/25728

and i have a pending fix here https://github.com/bazelbuild/bazel/pull/27043 to avoid the crash. even w/ the crash being avoided it's required that you get your Xcode install to a good state before any actual apple specific actions run, it will just fail with a different error w/ my fix, see the other issue for more discussion

**Comment by keith** [comment]
@akirchhoff-modular how'd you get out of that loop?

**Comment by akirchhoff-modular** [comment]
> [@akirchhoff-modular](https://github.com/akirchhoff-modular) how'd you get out of that loop?

I think I may have needed a `bazel clean --expunge`, though I don't completely recall.

**Comment by vibbix** [comment]
`bazel clean --expunge` didn't fix this issue. I only have the XCode CLI installed, not the full install.

**Comment by quinneden** [comment]
> > It looks like you might not be on macOS running these commands?
> 
> I'm running macOS, but I'm invoking Bazel inside of a Nix shell created with [the `mkShellNoCC` function](https://nixos.org/manual/nixpkgs/unstable/#sec-pkgs-mkShell-variants).

@seh have you found a fix for this? I am running into this issue in the exact same env you described (bazel + mkShellNoCC)

**Comment by seh** [comment]
> have you found a fix for this?

I did, yes, but that's not the same as me being able to explain completely _why_ this works.

I added the following to my _.envrc_ file (for use with [_direnv_](https://github.com/direnv/direnv)) at the root of my Bazel repositories that I use within macOS:
```shell
# Used by Bazel's rules_apple, as needed when run within a Nix shell.
# See https://github.com/bazelbuild/apple_support/blob/master/README.md#toolchain-configuration.
#
# One or the other of these bindings may be necessary, depending on
# whether you have Xcode installed or not.
#export BAZEL_ALLOW_NON_APPLICATIONS_XCODE=1
export BAZEL_NO_APPLE_CPP_TOOLCHAIN=1
```
I still think that the root of the problem has to do with _rules_apple_ not dealing well with the absolute paths that the Nix shell sets in a few environment variables that point at the tool directories.

Please let me know whether setting either of those two environment variables helps you get past this problem.
