### ISSUE TITLE
[Bazel CI] Build failed due to missing repositories in `@@+bazel_build_deps+bootstrap_repo_cache//`


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#23182]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-bde0-4464-84c4-e4dcc1c8463b

Platform: CentOS, Linux, Windows

Logs:

```

ERROR: An error occurred during the fetch of repository '+bazel_build_deps+bootstrap_repo_cache':
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-3gmr/bazel-org-repo-root/bazel/distdir.bzl", line 89, column 42, in _repo_cache_tar_impl
  | http_artifacts = parse_http_artifacts(ctx, lockfile_path, ctx.attr.repos)
  | File "/var/lib/buildkite-agent/builds/bk-docker-3gmr/bazel-org-repo-root/bazel/src/tools/bzlmod/utils.bzl", line 114, column 13, in parse_http_artifacts
  | fail("Could not find all required repos, missing: %s" % missing_repos)
  | Error in fail: Could not find all required repos, missing: ["grpc++grpc_repo_deps_ext+bazel_gazelle", "grpc++grpc_repo_deps_ext+bazel_skylib", "grpc++grpc_repo_deps_ext+com_envoyproxy_protoc_gen_validate", "grpc++grpc_repo_deps_ext+com_github_cncf_udpa", "grpc++grpc_repo_deps_ext+com_google_googleapis", "grpc++grpc_repo_deps_ext+envoy_api", "grpc++grpc_repo_deps_ext+rules_cc", "rules_kotlin++rules_kotlin_extensions+com_github_jetbrains_kotlin"]
  | (04:12:34) ERROR: no such package '@@+bazel_build_deps+bootstrap_repo_cache//': Could not find all required repos, missing: ["grpc++grpc_repo_deps_ext+bazel_gazelle", "grpc++grpc_repo_deps_ext+bazel_skylib", "grpc++grpc_repo_deps_ext+com_envoyproxy_protoc_gen_validate", "grpc++grpc_repo_deps_ext+com_github_cncf_udpa", "grpc++grpc_repo_deps_ext+com_google_googleapis", "grpc++grpc_repo_deps_ext+envoy_api", "grpc++grpc_repo_deps_ext+rules_cc", "rules_kotlin++rules_kotlin_extensions+com_github_jetbrains_kotlin"]
  | (04:12:34) ERROR: /var/lib/buildkite-agent/builds/bk-docker-3gmr/bazel-org-repo-root/bazel/BUILD:238:8: //:bazel-distfile depends on @@+bazel_build_deps+bootstrap_repo_cache//:archives.tar in repository @@+bazel_build_deps+bootstrap_repo_cache which failed to fetch. no such package '@@+bazel_build_deps+bootstrap_repo_cache//': Could not find all required repos, missing: ["grpc++grpc_repo_deps_ext+bazel_gazelle", "grpc++grpc_repo_deps_ext+bazel_skylib", "grpc++grpc_repo_deps_ext+com_envoyproxy_protoc_gen_validate", "grpc++grpc_repo_deps_ext+com_github_cncf_udpa", "grpc++grpc_repo_deps_ext+com_google_googleapis", "grpc++grpc_repo_deps_ext+envoy_api", "grpc++grpc_repo_deps_ext+rules_cc", "rules_kotlin++rules_kotlin_extensions+com_github_jetbrains_kotlin"]
  | (04:12:34) ERROR: Analysis of target '//:bazel-distfile.zip' failed; build aborted: Analysis failed
  | (04:12:34) INFO: Elapsed time: 3.073s, Critical Path: 0.04s
  | (04:12:34) INFO: 1 process: 1 internal.
  | (04:12:34) ERROR: Build did NOT complete successfully
  | (04:12:34) FAILED:
```

Culprit:

Steps:

```
 git clone https://github.com/bazelbuild/bazel
git reset 5a8280a7e90319e6ac0641d507158eb3c4628eba  --hard
export USE_BAZEL_VERSION=a7264d99e2d14463cb683a4091d5ad0e08431205
bazel build -- //:bazel-distfile.zip //scripts/packages/debian:bazel-debian.deb //scripts/packages:with-jdk/install.sh //src:bazel //src:bazel_jdk_minimal //src:test_repos //src/main/java/... //src/tools/execlog/... 
```

CC Greenteam @fweikert

**Comment by Wyverald** [comment]
this is kind of to be expected -- Bazel at HEAD can only be built with Bazel 7.2.1, not Bazel at HEAD itself. This will be fixed once we release 7.3.0 and switch to building Bazel at HEAD with Bazel 7.3.0.
