### ISSUE TITLE
bazel crashes when applying aspects to aliases

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#2338]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

We're using Aspects to apply a doxygen build to many of our targets. To simplify the naming for some of our third-party dependencies, I've added an alias that wraps a cc_library rule.

Unfortunately this alias is a dependency of many of our other rules, and applying the aspect to this alias results in the following backtrace:

java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT://third_party/ros:roscpp#//doc/doxygen:doxygen.bzl%_doxygen_aspect 68b2443eaa1ec80f3eb541b8d721f707 68b2443eaa1ec80f3eb541b8d721f707 {}' (requested by nodes 'ASPECT://base/diag/core:ros_transport#//doc/doxygen:doxygen.bzl%_doxygen_aspect 68b2443eaa1ec80f3eb541b8d721f707 68b2443eaa1ec80f3eb541b8d721f707 {}')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1021)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:532)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.rules.AliasConfiguredTarget cannot be cast to com.google.devtools.build.lib.analysis.RuleConfiguredTarget
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:207)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:972)
	... 4 more

### Environment info
* Operating System:

Ubuntu 14.04

* Bazel version (output of `bazel info release`):

`release 0.3.0-2016-09-26 (@ac731df)`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

We've pulled a few minor patches from 0.3.1 for hazelcast into our fork of bazel.

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I had a look through the existing issues and wasn't able to find anything related to using aspects and aliases together.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by bangjieliu** [comment]
Hi, isthmus bug fixed? it looks Bazel is still not able to apply aspect to alias? (it won't crash though)

**Comment by brandjon** [comment]
If this is still crashing and anyone has a repro, we can look at removing the crash, but I don't think we can prioritize fixing aspects+alias at the moment.
