### ISSUE TITLE
JarJar gets "Access Denied" error on Windows

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#2343]
When building Bazel's //src:bazel on Windows:

```
ERROR: C:/tools/msys64/home/jcater/bazel/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD:72:1: Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar failed: bash failed: error executing command
  cd C:/bazel_ci/temp/_bazel_jcater/6UZ4go3n/execroot/bazel
  SET PATH=C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl;C:\python_27_amd64\files;C:\python_27_amd64\files;C:\python_27_amd64\files
  C:/tools/msys64/usr/bin/bash -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/java/jarjar/jarjar_bin.cmd process src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage.jarjar bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar bazel-out/local-fastbuild/genfiles/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_jarjar_deploy.jar: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.io.IOException: Access is denied
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at com.tonicsystems.jarjar.ext_util.StandaloneJarProcessor.run(StandaloneJarProcessor.java:32)
        at com.tonicsystems.jarjar.Main.process(Main.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.tonicsystems.jarjar.MainUtil.runMain(MainUtil.java:37)
        at com.tonicsystems.jarjar.Main.main(Main.java:50)
ERROR: C:/tools/msys64/home/jcater/bazel/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: output 'src/tools/android/java/com/google/devtools/build/android/ziputils/libziputils_lib-ijar.jar' was not created.
```

**Comment by katre** [comment]
JarJar was added recently in 823091f7516abf7d854021edc765daf1467f1647, will revert that to resolve the breakage for now.

**Comment by katre** [comment]
Now that the offending commit is reverted I will downgrade the severity of this issue.
