### ISSUE TITLE
Missing Apache CXF files within the fat JAR

### ISSUE THREAD

**Issue by dbutragueno** [bazelbuild/bazel#23618]
### Description of the bug:

The `java_binary` rule isn't including certain Apache CXF files when generating the fat JAR. Specifically, the files located under the path META-INF/cxf are being excluded. As a result, when the application is deployed within a container, it encounters an error for those missing files.

I propose modifying the [DefaultJarEntryFilter](https://github.com/bazelbuild/bazel/blob/master/src/java_tools/singlejar/java/com/google/devtools/build/singlejar/DefaultJarEntryFilter.java) implementation to ensure that the META-INF/cxf directory is correctly included in the generated fat JAR.

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Develop an application that creates a web service using Apache CXF, and package it into a containerized environment. Utilize the java_binary rule to generate a fat JAR for deployment.

### Which operating system are you running Bazel on?

macOs Sonoma Version 14.5

### What is the output of `bazel info release`?

release 6.3.2

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:bazelbuild/bazel.git
e0e678f7d361e61b5bc510af25c5c682fe5a0682
```

### Have you found anything relevant by searching the web?

Ticket in Apache CXF Jira
https://issues.apache.org/jira/browse/CXF-9053

### Any other information, logs, or outputs that you want to share?

Log when deploying the application

`java.lang.NullPointerException: null
    at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.generatedWrapperBeanClass(JaxWsServiceFactoryBean.java:670) ~[service_deploy.jar:?]
    at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.getExtraClass(JaxWsServiceFactoryBean.java:642) ~[service_deploy.jar:?]
    at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:463) ~[service_deploy.jar:?]
    at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693) ~[service_deploy.jar:?]
    at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529) ~[service_deploy.jar:?]
    at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262) ~[service_deploy.jar:?]
    at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199) ~[service_deploy.jar:?]
    at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103) ~[service_deploy.jar:?]
    at org.apache.cxf.frontend.ClientFactoryBean.create(ClientFactoryBean.java:91) ~[service_deploy.jar:?]
    at org.apache.cxf.frontend.ClientProxyFactoryBean.create(ClientProxyFactoryBean.java:158) ~[service_deploy.jar:?]
    at org.apache.cxf.jaxws.JaxWsProxyFactoryBean.create(JaxWsProxyFactoryBean.java:142) ~[service_deploy.jar:?]`

**Comment by hvadehra** [comment]
> I propose modifying the [DefaultJarEntryFilter](https://github.com/bazelbuild/bazel/blob/master/src/java_tools/singlejar/java/com/google/devtools/build/singlejar/DefaultJarEntryFilter.java) implementation

Aside, the java implementation of singlejar is no longer used. Changes if any will be to the cpp implementation here: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar

This looks like a special case of #7330, and is something we're looking to fix in a general fashion. Closing this as a dupe, please use #7330 as the canonical issue for this.
