### ISSUE TITLE
Bazel crash on toolchain registration if toolchain declaration has incompatible dependency

### ISSUE THREAD

**Issue by alexander-shiryaev** [bazelbuild/bazel#23846]
### Description of the bug:

Bazel crashes if, when registering a toolchain, in the chain of its dependencies
it encounters a target with `target_compatible_with = ["@platforms//:incompatible"]` set.

```
Starting local Bazel server and connecting to it...
Computing main repo mapping: 
Computing main repo mapping: 
Computing main repo mapping: 
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //:require_toolchain (1 packages loaded, 0 targets configured)
Analyzing: target //:require_toolchain (1 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:toolchain, config=BuildConfigurationKey[60f5dea2735e7a00db22cffca4067ff08ba19e8732f149961005afa9128121f4]}' (requested by nodes 'RegisteredToolchainsValue.Key{configurationKey: BuildConfigurationKey[60f5dea2735e7a00db22cffca4067ff08ba19e8732f149961005afa9128121f4]}')
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
    at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
    at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:815)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
    at com.google.devtools.build.lib.rules.platform.Toolchain.create(Toolchain.java:57)
    at com.google.devtools.build.lib.rules.platform.Toolchain.create(Toolchain.java:38)
    at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:408)
    at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
    at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1312)
    at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:385)
    at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:312)
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
    ... 7 more
```

### Which category does this issue belong to?

Configurability, Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# https://github.com/alexander-shiryaev/bazel_issue/tree/main/bug/bazel_crash_on_error_during_toolchain_registration
bazel build :require_toolchain
```

### Which operating system are you running Bazel on?

does not matter

### What is the output of `bazel info release`?

release 7.1.0

### Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Code for the example: https://github.com/alexander-shiryaev/bazel_issue/tree/main/bug/bazel_crash_on_error_during_toolchain_registration

**Comment by katre** [comment]
I think there's a real bug here, but I can't cause it to happen with your reproduction using Bazel built from head (specifically, we've been steadily removing support for `config_common.FeatureFlagInfo`).

Can you reproduce this without a flag, or with a `label_flag`, instead? When I try I get reasonable-looking error messages.

**Comment by alexander-shiryaev** [comment]
The whole point here is that we use `config_common.FeatureFlagInfo + config_setting` to implement custom conditions for the `select` operator. Even if the bug is reproduced somehow, it is of little use to us.

> specifically, we've been steadily removing support for `config_common.FeatureFlagInfo`

This is extremely worrying news for us, since a significant part of our core build rules library is built on creating custom conditions for the `select` operator. Will there be any alternative to implement this scenario if you plan to get rid of `config_common.FeatureFlagInfo`?

**Comment by gregestren** [comment]
> > specifically, we've been steadily removing support for `config_common.FeatureFlagInfo`
> 
> This is extremely worrying news for us, since a significant part of our core build rules library is built on creating custom conditions for the `select` operator. Will there be any alternative to implement this scenario if you plan to get rid of `config_common.FeatureFlagInfo`?

We don't intend to make `select()`s less flexible. It's more a matter of `FeatureFlagInfo` being a legacy APi that was never designed to properly support this.

What kind of customization do you need? In [your code example](https://github.com/alexander-shiryaev/bazel_issue/blob/8d2ad99efaf2da4f0ffd7bfec312513db85c70af/bug/bazel_crash_on_error_during_toolchain_registration/defs.bzl#L3) it looks like you're hard-setting the condition to a string literal?

**Comment by alexander-shiryaev** [comment]
@gregestren
> We don't intend to make select()s less flexible. It's more a matter of FeatureFlagInfo being a legacy APi that was never designed to properly support this.

Ok, but is there any alternative to `config_common.FeatureFlagInfo` to make a custom condition for `select` operator?

> What kind of customization do you need? In [your code example](https://github.com/alexander-shiryaev/bazel_issue/blob/8d2ad99efaf2da4f0ffd7bfec312513db85c70af/bug/bazel_crash_on_error_during_toolchain_registration/defs.bzl#L3) it looks like you're hard-setting the condition to a string literal?

We have our own implementation of C++ toolchain, which provides clients with the C++ compiler version, the platform SDK version, etc. Clients can write conditions like `is current compiler version >= 10.3`. We achieve this by using the `config_common.FeatureFlagInfo + config_setting` bundle, which are wrapped in our macros for convenience.

So, roughly speaking, we need a way to turn a **computed** string (i.e. a string returned by some target via some provider) into a condition for the `select` operator.

**Comment by alexander-shiryaev** [comment]
Here is an example:
```starlark
load("@baldr//cc:compiler.bzl", "BALDR_CC_COMPILER")
load("@bazel_skylib//lib:structs.bzl", "structs")

visibility("//...")

def _compiler_flag_impl(ctx):
    toolchain_info = ctx.toolchains["@baldr//cc/info:toolchain_type"]

    if toolchain_info:
        allowed_compilers = structs.to_dict(BALDR_CC_COMPILER).keys()

        if toolchain_info.compiler not in allowed_compilers:
            fail(
                "C/C++ compiler in a selected toolchain is {}, but expected one of {}".format(
                    repr(toolchain_info.compiler),
                    allowed_compilers,
                ),
            )

        compiler, compiler_version = toolchain_info.compiler, toolchain_info.compiler_version

    else:
        compiler, compiler_version = BALDR_CC_COMPILER.none, "0.0.0"

    return [
        config_common.FeatureFlagInfo(
            value = "{}-{}".format(compiler, compiler_version),
        ),
    ]

compiler_flag = rule(
    implementation = _compiler_flag_impl,
    toolchains = [
        config_common.toolchain_type("@baldr//cc/info:toolchain_type", mandatory = False),
    ],
)
```

**Comment by fmeum** [comment]
This is also a crucial feature in rules_cc: https://github.com/bazelbuild/rules_cc/blob/8c94e11c2b05b5f25ced5f23cd07d0cdd36edc1a/cc/toolchains/compiler_flag.bzl#L21

**Comment by katre** [comment]
I'm re-investigating the crash.

As for supporting more flexible selects, we're collecting [requirements for user-defined `config_setting` rules](https://docs.google.com/document/d/1p02Y9joQSgdXtiTA2mJ_UXHBiBDPPTqrO-oJcupLAu8/edit?usp=sharing). The core idea is to be able to implement a rule that returns a `ConfigMatchingProvider` using your own custom logic, and then the rest of the `select` resolution would act as it currently does. Please feel free to add comments describing your use case.

**Comment by katre** [comment]
Okay, good news: this no longer crashes in Bazel at head (although it does in Bazel 8.0.0, not sure which change fixed it but I'll look shortly.

Bad news: the error message is very unhelpful:
```
$ bazel-dev build //:require_toolchain
Building dev version of bazel...
Starting local Bazel server (no_version) and connecting to it...
ERROR: /usr/local/google/home/jcater/repos/bazel_issue/bug/bazel_crash_on_error_during_toolchain_registration/BUILD.bazel:18:15: in flag_values attribute of config_setting rule //:is_toolchain_supported: error while parsing user-defined configuration values: flag_values keys must be build settings or feature flags and //:feature_flag is not
ERROR: /usr/local/google/home/jcater/repos/bazel_issue/bug/bazel_crash_on_error_during_toolchain_registration/BUILD.bazel:18:15: Analysis of target '//:is_toolchain_supported' failed
ERROR: /usr/local/google/home/jcater/repos/bazel_issue/bug/bazel_crash_on_error_during_toolchain_registration/BUILD.bazel:4:18: Analysis failed
INFO: Analyzed target //:require_toolchain (57 packages loaded, 427 targets configured).
WARNING: errors encountered while analyzing target '//:require_toolchain', it will not be built.
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 3.914s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

What's happening:
1. The target `//:is_toolchain_supprted` is a `config_setting`, so it checks the `flag_values` attribute, specifically looking for either the `config_common.FeatureFlagInfo` or `BuildSettingProvider` providers.
2. However, `//:feature_flag` is incompatible, so the only provider it has is an `IncompatiblePlatformProvider`
3. So `config_setting` reports that `//:feature_flag` isn't a valid feature flag, because in this case, it's not.

Probably what is needed is for `config_setting` to check earlier for incompatible targets, but I'm not really sure of the logic here (and, specifically, how it connects in to reporting incompatibility errors). Re-assigning to @gregestren to untangle that, because he has more context than I do.

**Comment by katre** [comment]
Bisect shows that the change that converted this from a crash to an error was 916e8581bb2861838fbec0cb6e9228caac7efddc (which looks very likely, reading the description).

**Comment by alexander-shiryaev** [comment]
We have cherry-picked [916e858](https://github.com/bazelbuild/bazel/commit/916e8581bb2861838fbec0cb6e9228caac7efddc) and it works.

Thank you!

**Comment by gregestren** [comment]
Recap: no longer crashes, but produces a confusing error.

Questions:
1. Do we want to patch this into Bazel 8? Complications:
     1. it's a bit of a corner case so I'm not sure how widespread this is
     1.  the fix https://github.com/bazelbuild/bazel/commit/916e8581bb2861838fbec0cb6e9228caac7efddc is subtle and not a 100% trivial backward-compatible change (we'd have to make a judgment call)
     1. https://github.com/bazelbuild/bazel/commit/916e8581bb2861838fbec0cb6e9228caac7efddc wasn't technically a crash fix even though it fixes this crash
     1. a confusing error message is better but still not the desired end state
3. What's the desired user experience?
    1. When registering a toolchain, this shouldn't be an error at all? Just that the toolchain is skipped for consideration?
    1. When building the toolchain directly like https://github.com/bazelbuild/bazel/issues/23846#issuecomment-2578420512, same or different outcome?
