### ISSUE TITLE
build bazel on arm32

### ISSUE THREAD

**Issue by tonghyun** [bazelbuild/bazel#23897]
### Description of the feature request:

Add arm32 to bazel builds

### Which category does this issue belong to?

CLI, Core

### What underlying problem are you trying to solve with this feature?

I'm trying to build bazel on an arm32 platform.

### Which operating system are you running Bazel on?

Ubuntu on armv7l

### What is the output of `bazel info release`?

$ bazel info release FATAL: Your platform/architecture combination linux - arm is not yet supported.     You may need to compile Bazelisk yourself, or use the Python version.     See instructions at https://github.com/bazelbuild/bazelisk/blob/master/README.md. node:internal/validators:162     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);     ^  TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Promise     at new NodeError (node:internal/errors:405:5)     at validateString (node:internal/validators:162:11)     at normalizeSpawnArguments (node:child_process:548:3)     at spawn (node:child_process:754:13)     at main (/usr/local/lib/node_modules/@bazel/bazelisk/bazelisk.js:55:14)     at Object.<anonymous> (/usr/local/lib/node_modules/@bazel/bazelisk/bazelisk.js:69:3)     at Module._compile (node:internal/modules/cjs/loader:1356:14)     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)     at Module.load (node:internal/modules/cjs/loader:1197:32)     at Module._load (node:internal/modules/cjs/loader:1013:12) {   code: 'ERR_INVALID_ARG_TYPE' }  Node.js v18.19.1

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
$ git remote get-url origin; git rev-parse HEAD
https://github.com/bazelbuild/bazel.git
d0285222b0060847d815d87d6757ca22e43ebd93
```

### Have you found anything relevant by searching the web?

I looked it up, but couldn't find a solution.

### Any other information, logs, or outputs that you want to share?

```
~/bazel$ sudo npm install -g @bazel/bazelisk

changed 1 package in 8s
~/bazel$ bazel
FATAL: Your platform/architecture combination linux - arm is not yet supported.
    You may need to compile Bazelisk yourself, or use the Python version.
    See instructions at https://github.com/bazelbuild/bazelisk/blob/master/README.md.
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Promise
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at normalizeSpawnArguments (node:child_process:548:3)
    at spawn (node:child_process:754:13)
    at main (/usr/local/lib/node_modules/@bazel/bazelisk/bazelisk.js:55:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bazel/bazelisk/bazelisk.js:69:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.1
~/bazel$ uname -m
armv7l
```

**Comment by tonghyun** [comment]
Hi. any progress?
