### ISSUE TITLE
Sandbox crash due to .DS_Store

### ISSUE THREAD

**Issue by venkatchandrasekaran** [bazelbuild/bazel#23963]
### Description of the bug:

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Found unexpected entries in sandbox base. Please report this in https://github.com/bazelbuild/bazel/issues. The entries are: .DS_Store, _moved_trash_dir, sandbox_stash
	at com.google.devtools.build.lib.sandbox.SandboxModule.checkSandboxBaseTopOnlyContainsPersistentDirs(SandboxModule.java:564)
	at com.google.devtools.build.lib.sandbox.SandboxModule.afterCommand(SandboxModule.java:602)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:627)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:688)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### Which category does this issue belong to?

Core

**Comment by sgowroji** [comment]
Hi @venkatchandrasekaran, Could you please provide sample code to reproduce this issue?

**Comment by alexkirsz** [comment]
I also ran into this issue today. After restarting the bazel server, I couldn't get this issue to reproduce. Note: I'm running bazel with a custom `output_base`.

Running Bazel 7.3.2.

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Found unexpected entries in sandbox base. Please report this in https://github.com/bazelbuild/bazel/issues. The entries are: .DS_Store, _moved_trash_dir, sandbox_stash
	at com.google.devtools.build.lib.sandbox.SandboxModule.checkSandboxBaseTopOnlyContainsPersistentDirs(SandboxModule.java:564)
	at com.google.devtools.build.lib.sandbox.SandboxModule.afterCommand(SandboxModule.java:602)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:627)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:688)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:244)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:644)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tjgq** [comment]
@bazel-io fork 8.0.0
