### ISSUE TITLE
ArrayIndexOutOfBound in Skylark related code when using analyze-profile --html --html_details 

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2412]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

bazel build //src:bazel --profile profile
$ bazel analyze-profile profile --html --html_details
INFO: Reading 'startup' options from /Users/dmarting/.bazelrc: --watchfs
WARNING: This information is intended for consumption by Blaze developers only, and may change at any time.  Script against it at your own risk
INFO: Loading /Users/dmarting/git/bazel/profile
INFO: bazel profile for /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004 at Tue Jan 24 18:45:07 CET 2017, build ID: 44ada83b-5e2e-49f5-a440-f18ff97c5c08, 67684 record(s)
INFO: Aggregating task statistics
INFO: Creating HTML output in /Users/dmarting/git/bazel/profile.html
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.google.devtools.build.lib.profiler.output.SkylarkHtml.printStatsJs(SkylarkHtml.java:222)
	at com.google.devtools.build.lib.profiler.output.SkylarkHtml.printVisualizationCallbackJs(SkylarkHtml.java:124)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.printVisualizationJs(HtmlCreator.java:135)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.htmlFrontMatter(HtmlCreator.java:96)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.print(HtmlCreator.java:70)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.create(HtmlCreator.java:195)
	at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:261)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:517)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:332)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:733)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1500(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:800)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Building: no action running
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.google.devtools.build.lib.profiler.output.SkylarkHtml.printStatsJs(SkylarkHtml.java:222)
	at com.google.devtools.build.lib.profiler.output.SkylarkHtml.printVisualizationCallbackJs(SkylarkHtml.java:124)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.printVisualizationJs(HtmlCreator.java:135)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.htmlFrontMatter(HtmlCreator.java:96)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.print(HtmlCreator.java:70)
	at com.google.devtools.build.lib.profiler.output.HtmlCreator.create(HtmlCreator.java:195)
	at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:261)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:517)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:332)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:733)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1500(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:800)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Environment info
* Operating System: macOS Sierra

* Bazel version (output of `bazel info release`): 0.4.3-homebrew

**Comment by laurentlb** [comment]
Seems to be obsolete (I cannot reproduce the crash).
