### ISSUE TITLE
Bazel@HEAD on Windows: //src/test/java/com/google/devtools/common/options:options_test fails

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2416]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/512/console

**Comment by laszlocsomor** [comment]
I can repro it locally at c4e92b1.
```
FAIL: //src/test/java/com/google/devtools/common/options:options_test (see C:/Users/laszlocsomor/AppData/Local/Temp/_bazel_laszlocsomor/nYhaG828/execroot/bazel/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/common/options/options_test/test.log).
INFO: From Testing //src/test/java/com/google/devtools/common/options:options_test:
==================== Test output for //src/test/java/com/google/devtools/common/options:options_test:
JUnit4 Test Runner
...................................E.......................................................................................................
Time: 0.268
There was 1 failure:
1) parseWithParamsFileMultiline(com.google.devtools.common.options.OptionsParserTest)
com.google.devtools.common.options.OptionsParsingException: While parsing option --bar: '' is not an int
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:648)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:536)
        at com.google.devtools.common.options.OptionsParser.parseWithSourceFunction(OptionsParser.java:626)
        at com.google.devtools.common.options.OptionsParser.parse(OptionsParser.java:610)
        at com.google.devtools.common.options.OptionsParser.parse(OptionsParser.java:587)
        at com.google.devtools.common.options.OptionsParserTest.parseWithParamsFileMultiline(OptionsParserTest.java:262)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
        at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:87)
Caused by: com.google.devtools.common.options.OptionsParsingException: '' is not an int
        at com.google.devtools.common.options.OptionsParserImpl$2.convert(OptionsParserImpl.java:76)
        at com.google.devtools.common.options.OptionsParserImpl$2.convert(OptionsParserImpl.java:70)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:643)
        ... 36 more
```

**Comment by laszlocsomor** [comment]
@meteorcloudy : could you please take a look? Thanks!

**Comment by meteorcloudy** [comment]
Looks like the culprit is 3f06748eb6c4fe1a8d30aae118f37885c23ec984, the failing test is added in this commit.

**Comment by meteorcloudy** [comment]
It's still failing on ci, should we rollback it?

**Comment by laszlocsomor** [comment]
it's only failing on Windows, not other platforms.. i'll give it another 30 minutes to try and figure out what's wrong

**Comment by laszlocsomor** [comment]
(i'm looking at it)

**Comment by laszlocsomor** [comment]
Found the culprit. This is a funny one.

The failing test creates a params file and then asserts that the option parser recognizes that the flag is a path to a params file, parses the params file, and substitutes the args vector with the flags from the file.

This is the buggy line:
https://github.com/bazelbuild/bazel/blob/54223b019817c329d7bff1c174d497ef3d64695a/src/main/java/com/google/devtools/common/options/ParamsFilePreProcessor.java#L70

The parser processes the file character-by-character, in order to handle multiline flag values, e.g. `--foo=line1\nline2`. Problem is, Windows has CRLF line endings, so we terminate the arg parsing on the CR, and treat the LF as a standalone flag value, and push it into the args vector. So instead of ["--baz", "oops", "--bar", 17], we end up with ["--baz", "", "oops", "", "--bar", "", 17]
