### ISSUE TITLE
docker-tests on debian stretch with -c opt often throw NPE (flake)

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2418]
So specifically that means that bootstrapping on debian stretch is flaky.

Instances of the failure:
http://ci.bazel.io/job/bazel-docker-tests/BAZEL_VERSION=latest,PLATFORM_NAME=docker/390/console
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@local_config_cc//:empty 8a314b3505ab58c3622e3bb532245599 (488063321 1758714757)' (requested by nodes 'CONFIGURED_TARGET:@local_config_cc//:cc-compiler-k8 1bb17f751baec4ec4e9560830940c6e2 (1587637863 660904783)')
____Elapsed time: 4.169s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@local_config_cc//:empty 8a314b3505ab58c3622e3bb532245599 (488063321 1758714757)' (requested by nodes 'CONFIGURED_TARGET:@local_config_cc//:cc-compiler-k8 1bb17f751baec4ec4e9560830940c6e2 (1587637863 660904783)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.addOutputGroup(RuleConfiguredTargetBuilder.java:388)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:109)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:99)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:47)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:276)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:176)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:491)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1094)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:251)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
```

http://ci.bazel.io/job/bazel-docker-tests/387/BAZEL_VERSION=HEAD,PLATFORM_NAME=docker/console
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@bazel_tools//tools/cpp:link_dynamic_library b9d86d877ad0881baa7827acc85b3a48 (1999886527 156802903)' (requested by nodes 'CONFIGURED_TARGET:@local_config_cc//:cc-compiler-k8 b9d86d877ad0881baa7827acc85b3a48 (1634298164 156802903)')
____Elapsed time: 4.161s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@bazel_tools//tools/cpp:link_dynamic_library b9d86d877ad0881baa7827acc85b3a48 (1999886527 156802903)' (requested by nodes 'CONFIGURED_TARGET:@local_config_cc//:cc-compiler-k8 b9d86d877ad0881baa7827acc85b3a48 (1634298164 156802903)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.constraints.ConstraintSemantics$EnvironmentCollector.<init>(ConstraintSemantics.java:229)
	at com.google.devtools.build.lib.analysis.constraints.ConstraintSemantics.getSupportedEnvironments(ConstraintSemantics.java:399)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.checkConstraints(RuleConfiguredTargetBuilder.java:191)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:85)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:99)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:47)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:276)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:176)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:491)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1094)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:251)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
```

http://ci.bazel.io/job/bazel-docker-tests/373/BAZEL_VERSION=HEAD,PLATFORM_NAME=docker/console
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@bazel_tools//tools/cpp:link_dynamic_library e27a98f94821c643322c9287c9d7e4b3 (260525456 1672627141)' (requested by nodes 'CONFIGURED_TARGET:@local_config_cc//:cc-compiler-k8 e27a98f94821c643322c9287c9d7e4b3 (1713920535 1672627141)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.analysis.constraints.ConstraintSemantics$EnvironmentCollector.<init>(ConstraintSemantics.java:229)
	at com.google.devtools.build.lib.analysis.constraints.ConstraintSemantics.getSupportedEnvironments(ConstraintSemantics.java:399)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.checkConstraints(RuleConfiguredTargetBuilder.java:191)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:85)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:99)
	at com.google.devtools.build.lib.rules.filegroup.Filegroup.create(Filegroup.java:47)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:276)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:176)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:491)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1094)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:251)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
```

**Comment by damienmg** [comment]
Interesting bit:
[com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.addOutputGroup(RuleConfiguredTargetBuilder.java:388)](https://github.com/bazelbuild/bazel/blob/c4e92b1ba06fba48121e4db8050a69b6d998e2e9/src/main/java/com/google/devtools/build/lib/analysis/RuleConfiguredTargetBuilder.java#L388) is not a place that can throw an NPE, maybe the test is wrong?

**Comment by damienmg** [comment]
(confirmed that the distfile has indeed the same source)

How can a 'return this;' throw an NPE???

**Comment by damienmg** [comment]
The second NPE is on a } statement, I would sya the -c opt mess up the stack information, cannot believe it.

See https://github.com/bazelbuild/bazel/blob/ec5837de94117515d89c5f172d73b4f9a5fc8a36/src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintSemantics.java#L229

**Comment by damienmg** [comment]
Ok this is not during bootstrapping but building the example

**Comment by damienmg** [comment]
The test is doing:

```sh
export EXTRA_BAZEL_ARGS= "--spawn_strategy=standalone --genrule_strategy=standalone -c opt"
/opt/workspace/compile.sh && ./output/bazel test ${EXTRA_BAZEL_ARGS} //examples/cpp:hello-success_test
```

**Comment by damienmg** [comment]
So let summarize:
C++ compilation with -c opt sometime fails with NPE on debian stretch during loading of C++ toolchain. The NPE stack is corrupted probably because of the -c opt (why would that be I have no idea).

The first one of the NPE is totally impossible in that function to I think the stack trace is wrong

**Comment by damienmg** [comment]
Ok I am out of idea so delegating to marcel for further investigation.

**Comment by damienmg** [comment]
Repro instruction: `bazel test //tools/cpp/test:test_cc_configure-debian-stretch-dbg`

This requires to have docker installed and to be in the docker group.

Now getting a shell on the docker image that is created by that test:
1. Comment line [153 of tools/cpp/test/docker_test.py](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/test/docker_test.py#L153) (side-note: maybe we should add a flag to not cleanup after the test)
2. Run the test `bazel test //tools/cpp/test:test_cc_configure-debian-stretch-dbg`
3. Spawn a new docker container and attach a shell: `docker run -t -i --entrypoint /bin/bash bazel/docker_test:tools_cpp_test_bazel_cc_configure-debian-stretch-dbg`

**Comment by mhlopko** [comment]
Just FYI: I wasn't able to reproduce the exception, will look into it after I come back from vacation.

**Comment by damienmg** [comment]
pinging this bug because it happened again today

**Comment by damienmg** [comment]
Deactivated the test.

**Comment by meisterT** [comment]
This doesn't exist anymore.
