### ISSUE TITLE
cc_binary rule don't allow files to have an extension like ".include" 

### ISSUE THREAD

**Issue by mpatou-openai** [bazelbuild/bazel#24216]
### Description of the bug:

I'm trying to bazelify some code that relies on https://github.com/calccrypto/uint256_t and `cc_binary` are failing when I try to includes the `.include` files:
```
src/cpp/BUILD.bazel:1577:10: in cc_binary rule //cpp:backend_test:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_binary.bzl", line 905, column 44, in _impl
        File "/virtual_builtins_bzl/common/cc/cc_binary.bzl", line 570, column 36, in cc_binary_impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 104, column 27, in _check_srcs_extensions
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 88, column 25, in _check_file_extensions
Error in fail: in srcs attribute of cc_binary rule @@//cpp:backend_test: source file '@@//cpp:third-party/uint256_t/uint128_t/uint128_t.include' is misplaced here
ERROR: src/cpp/BUILD.bazel:1577:10: Analysis of target '//cpp:backend_test' failed
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* clone the repository https://github.com/calccrypto/uint256_t in a third-party directory
* create a `cc_binary` that has the following sources
```
srcs = [
       "third-party/uint256_t/uint128_t/endianness.h",
       "third-party/uint256_t/uint128_t/uint128_t.h",
       "third-party/uint256_t/uint256_t.h",
       "third-party/uint256_t/uint128_t/uint128_t.include",
       "third-party/uint256_t/uint128_t/uint128_t_config.include",
       "third-party/uint256_t/uint256_t.include",
       "third-party/uint256_t/uint256_t_config.include",
       "foo.cc"
 ],
 ```
 * run `bazel build`

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

 release 7.3.1

### Have you found anything relevant by searching the web?

Yes haven't found something. Asked AI chat bot too.

**Comment by jwnimmer-tri** [comment]
I believe this is a duplicate of #10552.
