### ISSUE TITLE
Bazel@HEAD Darwin: tests failing due to too many open FDs

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2422]
Maybe we're leaking file descriptors?

http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/514/consoleFull

```
FAIL: //src/test/java/com/google/devtools/build/lib:analysis_config_test (see /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/darwin-x86_64/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/analysis_config_test/test.log)
____From Testing //src/test/java/com/google/devtools/build/lib:analysis_config_test:
==================== Test output for //src/test/java/com/google/devtools/build/lib:analysis_config_test:
JUnit4 Test Runner
.E
Time: 0.006
There was 1 failure:
1) initializationError(com.google.devtools.build.lib.AllTests)
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.google.devtools.build.lib.testutil.CustomSuite.evalSuite(CustomSuite.java:50)
	at com.google.devtools.build.lib.testutil.CustomSuite.getClasses(CustomSuite.java:37)
	at com.google.devtools.build.lib.testutil.CustomSuite.<init>(CustomSuite.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:33)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.createRunner(MemoizingRequest.java:48)
	at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.getRunner(MemoizingRequest.java:34)
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:51)
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:30)
	at com.google.testing.junit.runner.util.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:92)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:146)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.testutil.CustomSuite.evalSuite(CustomSuite.java:48)
	... 20 more
Caused by: java.lang.AssertionError: Can't read classpath entry src/main/java/com/google/devtools/build/lib/libshell.jar: src/main/java/com/google/devtools/build/lib/libshell.jar (Too many open files in system)
	at com.google.devtools.build.lib.testutil.Classpath.findClasses(Classpath.java:62)
	at com.google.devtools.build.lib.testutil.TestSuiteBuilder.getClassesRecursive(TestSuiteBuilder.java:62)
	at com.google.devtools.build.lib.testutil.TestSuiteBuilder.addPackageRecursive(TestSuiteBuilder.java:54)
	at com.google.devtools.build.lib.testutil.BlazeTestSuiteBuilder.getBuilder(BlazeTestSuiteBuilder.java:35)
	at com.google.devtools.build.lib.AllTests.suite(AllTests.java:30)
	... 25 more
```

**Comment by laszlocsomor** [comment]
I did some digging with `lsof` but didn't find anything conclusive.
Java occurred the most time (~1000) but even the most FD-intensive process had only about 380 open, while the system max limit (`sysctl kern.maxfilesperproc`) is over 10K.
Rebooting the machine to see if it helps. :/

**Comment by davido** [comment]
We had a [similar report on Mac Os X](https://groups.google.com/d/topic/repo-discuss/tl8IIv5EaJc/discussion):

Using Bazel 0.4.4 the build of release.war fails with "Too many open files in system" on Mac OS 10.12.3.
Increasing kern.maxfiles from default 12288 to 16384 fixes this issue:

```
  $ sudo sysctl -w kern.maxfiles=16384
```

**Comment by laszlocsomor** [comment]
@davido : Thanks for reporting that. I briefly reopened the bug but then thought otherwise -- I'm not aware of newer occurrences of it and it's not clear to me whether it's a Bazel bug or something else. Leaving it closed for now.

**Comment by davido** [comment]
@laszlocsomor Thanks. I will report if I hear something new hear.

**Comment by philwo** [comment]
Maybe interesting for others: It seems like macOS High Sierra comes with an even higher maxfiles out of the box. It was 98304 on our Mac Pro, so the sysctl command that we had in our CI scripts actually reduced it. I've removed it from our setup.
