### ISSUE TITLE
When use IBM JDK to build tensorflow, it failed because of a JVM api

### ISSUE THREAD

**Issue by jimht011** [bazelbuild/bazel#2428]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
@damienmg  @hanwen 
We use bazel 0.3.2 and IBM JDK try to build tensorflow in a RHEL 6.8 with glibc 2.12 environment. We have successfully built it by using Oracle JDK. However we got error when use IBM JDK1.8, below is the error msg

java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:1471)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:211)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:486)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:454)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:184)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:332)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:499)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:655)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1400(GrpcServerImpl.java:99)
        at com.google.devtools.build.lib.server.GrpcServerImpl$3$1.run(GrpcServerImpl.java:722)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:785)
Caused by: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
        at com.google.devtools.build.lib.util.ResourceUsage.<clinit>(ResourceUsage.java:45)

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

Since our application use websphere, we have no option to use oracle JDK. Could you please provide a work around on below code which use an API depends on oracle JVM.  Very appreciate your help as we tested everything under oracle JDK successfully and were  just blocked now by this issue.

### Environment info
* Operating System:

RHEL 6.8
* Bazel version (output of `bazel info release`):
0.3.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

NO.
### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
When check the source code I saw below comments: 
/*
   * Use com.sun.management.OperatingSystemMXBean instead of
   * java.lang.management.OperatingSystemMXBean because the latter does not
   * support getTotalPhysicalMemorySize() and getFreePhysicalMemorySize().
   */
private static final OperatingSystemMXBean OS_BEAN

**Comment by hanwen** [comment]
I don't work on bazel anymore.

**Comment by damienmg** [comment]
Hi, you are hitting an unsupported part.

We cannot support other JDK. However you might get around by doing `export JAVA_VERSION=1.7` to compile the Java 7 support but I cannot guarantee.

I don't believe we will ever support random JDK for our Java support and since we need our java support to build bazel itself, I have to close that issue, sorry :/

**Comment by pcj** [comment]
Note this is the default JDK (ibm) that one gets on a fresh ubuntu 16.04 box for some reason when `sudo apt-get install bazel`
