### ISSUE TITLE
IllegalStateException: Undefined symbol in --incompatible_autoload_externally

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#24317]
### Description of the bug:

```
$ bazel build ... --incompatible_autoload_externally=rules_android
Starting local Bazel server and connecting to it...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Undefined symbol in --incompatible_autoload_externally
	at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:146)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1499)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2712)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2667)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:282)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:779)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:608)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:678)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

`Build label: 8.0.0rc2`

If `rules_android` is not a valid value, a better error message was expected.

**Comment by laurentlb** [comment]
It seems like I should use `@rules_android` above.

I got a slightly different crash here:

```
$ bazel build ... --incompatible_autoload_externally=ProguardSpecProvider                                     
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Symbol in 'ProguardSpecProvider' can't be removed, because it's still used by: java_lite_proto_library, java_import
	at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:192)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1499)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2712)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2667)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:282)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:779)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:608)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:678)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by iancha1992** [comment]
@laurentlb Could you please provide sample code to reproduce this issue?

**Comment by laurentlb** [comment]
It repro everywhere, even in an empty workspace.

**Comment by dws** [comment]
In a directory with an empty `MODULE.bazel` file and the following `BUILD.bazel`:
```
genrule(
    name = "gen-rule",
    outs = ["gen-rule.out"],
    cmd = "echo contents > $@",
)
```
I see the problem when running
```
$ ../bazel-8.0.0-linux-x86_64 aquery --incompatible_autoload_externally //:gen-rule
Starting local Bazel server and connecting to it...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Undefined symbol in --incompatible_autoload_externally: //:gen-rule
        at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:153)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1500)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2727)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2682)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:282)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:779)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:677)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by comius** [comment]
We should improve error messaging for newly introduced functionality.

**Comment by igormcoelho** [comment]
I have a similar crash here, couldn't find an example in the Internet... this feature is to allow old rules system to keep working on v8, right? Does it work with rules_cc for C++?
I learned here that I need `@rules_cc`, but it still crashes:

```
 bazel build  --incompatible_autoload_externally=@rules_cc //example/module-library:teste_module
Starting local Bazel server (8.1.1) and connecting to it...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Symbol 'CcInfo' can't be removed, because it's still used by: java_library, java_import, java_runtime, java_binary, java_common, JavaInfo
        at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:214)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1500)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2727)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.sync(SkyframeExecutor.java:2682)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:282)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.syncPackageLoading(CommandEnvironment.java:779)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:677)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by alexeagle** [comment]
Reporting another similar crash:

```
Starting local Bazel server (8.0.1) and connecting to it...
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Undefined symbol in --incompatible_autoload_externally: -incompatible_config_setting_private_default_visibility
        at com.google.devtools.build.lib.packages.AutoloadSymbols.<init>(AutoloadSymbols.java:153)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.preparePackageLoading(SkyframeExecutor.java:1500)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.syncPackageLoading(SkyframeExecutor.java:2727)
```

**Comment by fmeum** [comment]
@alexeagle This error could be explained by a command line such as `--incompatible_autoload_externally --incompatible_config_setting_private_default_visibility`, which is incorrect since the first flag accepts a value (and thus parses the second flag as one).

**Comment by meisterT** [comment]
This is obsolete: the AutoloadSymbols feature and `--incompatible_autoload_externally` were removed and deprecated as no-ops in
  a3dc34c545efb7f70088ab7974aec28c14751722
