### ISSUE TITLE
Bazel@HEAD on Darwin: NativePosixFilesTest fails in sandbox ("/bin" doesn't exist)

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2441]
## Log
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/522/console

## Offending line
https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/src/test/java/com/google/devtools/build/lib/unix/NativePosixFilesTest.java#L111

## Stack trace
```
1) throwsFilePermissionException(com.google.devtools.build.lib.unix.NativePosixFilesTest)
java.lang.AssertionError: Not true that <java.io.FileNotFoundException: /bin (No such file or directory)> has message </bin (Read-only file system)>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.ThrowableSubject$1.fail(ThrowableSubject.java:47)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:295)
	at com.google.common.truth.Subject.fail(Subject.java:272)
	at com.google.common.truth.ThrowableSubject.hasMessage(ThrowableSubject.java:38)
	at com.google.devtools.build.lib.unix.NativePosixFilesTest.throwsFilePermissionException(NativePosixFilesTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:140)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:79)
Caused by: java.io.FileNotFoundException: /bin (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.chmod(Native Method)
	at com.google.devtools.build.lib.unix.NativePosixFiles.setWritable(NativePosixFiles.java:98)
	at com.google.devtools.build.lib.unix.NativePosixFilesTest.throwsFilePermissionException(NativePosixFilesTest.java:105)
	... 32 more
```

**Comment by hermione521** [comment]
It looks weird and it's not failing now. Feel free to reopen when it fails again.
