### ISSUE TITLE
[8.0.0rc4] Bazel crashes when workspace is enabled and trying to build nonexistent repo

### ISSUE THREAD

**Issue by fhanau** [bazelbuild/bazel#24498]
### Description of the bug:

Bazel 8.0.0rc4 crashes with an internal error when trying to build a repo that is not defined anywhere. I encountered this with workspace enabled and bzlmod disabled, didn't test if it also happens in other bases.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a directory with empty WORKSPACE and BUILD files, run `bazel build --noenable_bzlmod --enable_workspace @blah`. `@blah` is not defined, which results in a well-formed error message with Bazel 7.4.1, but in an internal error crash with Bazel 8.0.0rc4:
```
Loading: 0 packages loaded
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPO_FILE:@@blah' (requested by nodes 'IGNORED_SUBDIRECTORIES:@@blah')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
	at com.google.devtools.build.lib.rules.repository.RepositoryDirectoryValue$NoRepositoryDirectoryValue.getPath(RepositoryDirectoryValue.java:164)
	at com.google.devtools.build.lib.skyframe.RepoFileFunction.compute(RepoFileFunction.java:78)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	... 7 more
```

### Which operating system are you running Bazel on?

macOS 15.1.1

### What is the output of `bazel info release`?

release 8.0.0rc4

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
N/A
```

**Comment by fmeum** [comment]
@Wyverald

**Comment by meteorcloudy** [comment]
@bazel-io fork 8.0.0

**Comment by meteorcloudy** [comment]
Bisecting shows 9c6d24f3f7595fc293415c8f60b05360a4ed8f85 is the first bad commit

/cc @lberki
