### ISSUE TITLE
[7.4.1] Cannot allocate memory Server terminated even though system has memory

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#24527]
### Description of the bug:

We're hitting this on bazel 7.4.1 periodically even though our system has 32 GB of memory, container has a 29 GB memory limit. We're hitting this when running bazel coverage
```
java.util.logging.ErrorManager: 1
java.io.IOException: Cannot allocate memory
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(Unknown Source)
	at com.google.common.io.CountingOutputStream.write(CountingOutputStream.java:54)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/java.io.OutputStreamWriter.write(Unknown Source)
	at java.base/java.io.Writer.write(Unknown Source)
	at com.google.devtools.build.lib.util.SimpleLogHandler$Output.write(SimpleLogHandler.java:765)
	at com.google.devtools.build.lib.util.SimpleLogHandler.publish(SimpleLogHandler.java:434)
	at java.logging/java.util.logging.Logger.log(Unknown Source)
	at com.google.common.flogger.backend.system.AbstractBackend.log(AbstractBackend.java:76)
	at com.google.common.flogger.backend.system.SimpleLoggerBackend.log(SimpleLoggerBackend.java:31)
	at com.google.common.flogger.AbstractLogger.write(AbstractLogger.java:137)
	at com.google.common.flogger.LogContext.logImpl(LogContext.java:566)
	at com.google.common.flogger.LogContext.log(LogContext.java:681)
	at com.google.devtools.build.lib.server.PidFileWatcher.runPidFileChecks(PidFileWatcher.java:91)
	at com.google.devtools.build.lib.server.PidFileWatcher.run(PidFileWatcher.java:68)

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/github_actions/.cache/bazel/_bazel_github_actions/049fd0d9a142b0eee346c643b8cf35e6/server/jvm.out')
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

no reliable repro

### What is the output of `bazel info release`?

7.4.1

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

we recently upgraded from 6.5.0 --> 7.3.2 --> 7.4.1 and noticed this occur very frequently on 7.3.2 and 7.4.1

**Comment by meisterT** [comment]
What's the size of your bazel heap? If you do not configure anything Java figures out the heap size itself somehow depending on the available resources. You can check with `bazel info max-heap-size`.

The JSON trace profile also has a row for the memory use of the server, so you can see it grow up to the limit in there.

You can control the heap size by passing the startup option `--host_jvm_args=-Xmx3g` (adjust the 3g to some other value, this is 3GB, you likely need more).

**Comment by Ryang20718** [comment]
@meisterT 

we're running bazel with a heap size of 9GB currently.

We were fine on bazel 6.5 with a heap size of 6GB

**Comment by Ryang20718** [comment]
https://github.com/bazelbuild/bazel/issues/24506 potentially related

**Comment by Ryang20718** [comment]
@meisterT 

I was able to get a heap dump. File size for heap dump is too large for github so I uploaded to [gdrive ](https://drive.google.com/file/d/19LLNzImDe07EmcDdcYDSiCgKNEaswYCz/view?usp=sharing)
```
java.util.logging.ErrorManager: 1
java.io.IOException: Cannot allocate memory
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(Unknown Source)
	at com.google.common.io.CountingOutputStream.write(CountingOutputStream.java:54)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.base/java.io.OutputStreamWriter.write(Unknown Source)
	at java.base/java.io.Writer.write(Unknown Source)
	at com.google.devtools.build.lib.util.SimpleLogHandler$Output.write(SimpleLogHandler.java:765)
	at com.google.devtools.build.lib.util.SimpleLogHandler.publish(SimpleLogHandler.java:434)
	at java.logging/java.util.logging.Logger.log(Unknown Source)
	at com.google.common.flogger.backend.system.AbstractBackend.log(AbstractBackend.java:76)
	at com.google.common.flogger.backend.system.SimpleLoggerBackend.log(SimpleLoggerBackend.java:31)
	at com.google.common.flogger.AbstractLogger.write(AbstractLogger.java:137)
	at com.google.common.flogger.LogContext.logImpl(LogContext.java:566)
	at com.google.common.flogger.LogContext.log(LogContext.java:681)
	at com.google.devtools.build.lib.server.PidFileWatcher.runPidFileChecks(PidFileWatcher.java:91)
	at com.google.devtools.build.lib.server.PidFileWatcher.run(PidFileWatcher.java:68)

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/github_actions/.cache/bazel/bazel/_bazel_github_actions/049fd0d9a142b0eee346c643b8cf35e6/server/jvm.out')
```

**Comment by meisterT** [comment]
> we're running bazel 7.4.1 with a heap size of 9GB currently.
> We were fine on bazel 6.5 with a heap size of 6GB

Did this increase happen right when you switched or did you have other changes (e.g. growing the number of transitive deps) since then?

**Comment by meisterT** [comment]
Is this a multi-target build? If so, can you try adding `--noexperimental_merged_skyframe_analysis_execution` and check whether the heap size increase is related?

**Comment by meisterT** [comment]
Ok, we looked a little bit more into this and realized that we are holding on to some objects / paths longer through `TargetCompleteEvents` longer than we should.

**Comment by fmeum** [comment]
@bazel-io fork 7.5.0

**Comment by fmeum** [comment]
@bazel-io fork 8.0.1

**Comment by Ryang20718** [comment]
> Is this a multi-target build? If so, can you try adding --noexperimental_merged_skyframe_analysis_execution and check whether the heap size increase is related?

yes. sorry for the delayed response. I tried this, but it didn't fix the issue

**Comment by meisterT** [comment]
@fmeum it's very unlikely that a fix for this will be ready for 8.0.1, it likely has to wait until 8.1

**Comment by fmeum** [comment]
> @fmeum it's very unlikely that a fix for this will be ready for 8.0.1, it likely has to wait until 8.1

No pressure, thanks for working on it! 

I marked it as a soft release blocker so that it will "roll over" to 8.1.0 if not fixed in time. It's just generally better to postpone a fix if necessary than to remember only too late that it should have gone into a particular release.

**Comment by Ryang20718** [comment]
@tjgq if we don't use `--build_event_json_file`, we still see this issue. Is increased memory usage expected to still occur even if this flag isn't used?

**Comment by tjgq** [comment]
@Ryang20718 Are you setting any other flags that enable the BEP (`--build_event_{text,binary}_file`, `--bes_backend`)? If not, could you capture a heap dump without the BEP enabled?

**Comment by Ryang20718** [comment]
@tjgq we're setting --build_event_json_file

no bes backend.

I can try to capture a heap dump without BEP enabled. we've seen it happen in the past, but just more rare

**Comment by tjgq** [comment]
To clarify: the suspicion in https://github.com/bazelbuild/bazel/issues/24527#issuecomment-2541683398 only makes sense if at least one of the flags I mentioned is set. If you can still repro without them, we're either seeing two different issues, or the issue we're seeing has a different explanation. A heap dump without those flags would tell us which.

**Comment by alexnovak** [comment]
@tigq thanks for the explanation of this issue previously. Would the increased heap usage also be expected with minimal outputs configured?

**Comment by tjgq** [comment]
If my explanation in https://github.com/bazelbuild/bazel/issues/24527#issuecomment-2541683398 is correct, then it would be a problem regardless of the `--remote_download_outputs` setting.

**Comment by dkashyn-sfdc** [comment]
It feels like `downloadCache` causing the leak 

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/16454ded-a623-475d-b5b9-7566da9fa374" />

There are no traces of BEP.

Idk whether we can trust YK yet no matter how much memory we allocate we run out of memory sooner or later... And those objects seems identical (once again, this is so wrong to be true but I believe YK's judgments).

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/0a898535-ec6d-49b9-bbfa-fcfe660b59a4" />

**Comment by dkashyn-sfdc** [comment]
And yes, those are `TargetCompleteEvents` 

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/465ead4b-8fe3-4068-9958-8d6502b8e995" />

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/dfa2f822-27af-4d72-9ff0-e9c146432c80" />

**Comment by dkashyn-sfdc** [comment]
@coeuvre , there is a HashMap that has no size limit neither cleans up `finished` properly 

<img width="1375" alt="Image" src="https://github.com/user-attachments/assets/ab66d5ca-c446-4b7e-ac67-f3f8d2932f20" />

There seems not enough `finished.remove(key);` calls 

`force == false` and this code exits before cleaning `finished` ever

```
            if (!force && finished.containsKey(key)) {
              onAlreadyFinished.run();
              emitter.onSuccess(finished.get(key));
              return;
            }
            
           finished.remove(key);
``

**Comment by coeuvre** [comment]
The cache is to prevent Bazel from downloading the same output multiple times. From your screenshot, it seems like the `downloadCache` only retain 11.9 MB heap size, which is not a big deal, relatively.

**Comment by dkashyn-sfdc** [comment]
@coeuvre all of the memory consumption tied to `TargetCompleteEvent` in multiple ways 

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/7245583c-3477-402f-9e74-54852406d740" />

<img width="1375" alt="Image" src="https://github.com/user-attachments/assets/6c3ec496-d985-40c1-a4fa-ee78f0c74f5d" />

**Comment by coeuvre** [comment]
According to your screenshot, the real problem is not about the `downloadCache` (there is only one instance of `downloadCache` per invocation), but what @tjgq described in https://github.com/bazelbuild/bazel/issues/24527#issuecomment-2541683398: `TargetCompleteEvent` has a (indirect) reference to `RemoteActionFileSystem` (which is not supposed to) causing Bazel retaining too much memory.

**Comment by dkashyn-sfdc** [comment]
I thought that one because of BEP and we have that specifically disabled. Let me profile this in motion to get ideas how leak can happen.

**Comment by alexnovak** [comment]
Relevant to the issue at the top, when we were seeing a kernel OOM, we eventually found we could keep the memory contained by additionally setting `--host_jvm_args=-XX:MaxDirectMemorySize=<some value>`. We didn't originally understand that this was a separate pool from the JVM heap. By default this is a pool that's equal to the size of your heap size. In our case the heap was larger than half the memory of our machine, so it makes sense how this could have blown up.

I _believe_ the only information that's going to end up in this pool is buffers for network, such as for BEP and remote cache. I don't know if there's a way to configure this to dump in any circumstances - I believe it's a separate pool from heap.

**Comment by iancha1992** [comment]
@bazel-io fork 7.6.0

**Comment by nickdesaulniers** [comment]
I believe we are hitting this, too (moving from bazel 6.4.0 to 7.6.1).  We are setting `--bes_backend=`.
```
$ bazel info max-heap-size
32178MB
```
Should I try bumping our max heap size via `--host_jvm_args=-Xmx64g`?

**Comment by alexnovak** [comment]
@nickdesaulniers You can increase max heap size, but I'd highly recommend trying to cap MaxDirectMemorySize as well. We found that pool grows substantially with bes enabled, and it was causing constant OOMing. Both need to be capped to guarantee that you remain under some maximum memory threshold.

**Comment by nickdesaulniers** [comment]
> Should I try bumping our max heap size via --host_jvm_args=-Xmx64g?

Guess this changed at some point, should have used `--host_jvmopt=-Xmx64g`.

> but I'd highly recommend trying to cap MaxDirectMemorySize as well.
> Both need to be capped

I'm not trying to lower the cap, but raise it.

Do you mean "the cap raised?"  Since my understanding is that the JVM will kill the process once the existing cap is exceeded (rather than begin potentially swapping).

https://stackoverflow.com/a/46103476 (perhaps stale?) mentions:

> if you don't configure -XX:MaxDirectMemorySize and do configure -Xmx5g, the "default" MaxDirectMemorySize will also be 5 Gb

So that doesn't sound _necessary_ (?) 🤷 

---

For future travelers, I added this to my `.bazelrc` file. Haven't seen any OOMs yet. YMMV.
```
startup --host_jvm_args=-Xmx64g
```
`64g` is 64 GB. `bazel info max-heap-size` showed 32 GB on my system, so I simply doubled it.

**Comment by iancha1992** [comment]
@bazel-io fork 7.7.0
