### ISSUE TITLE
`repository_ctx.execute` does not print stderr when `quiet=False` on Windows

### ISSUE THREAD

**Issue by Fil-Den** [bazelbuild/bazel#24557]
### Description of the bug:

On Windows `repository_ctx.execute` with argument `quiet = False` hiding stderr.

Example:
```
$ grep "" *
BUILD.bazel:
WORKSPACE.bazel:load("//:repo_rule.bzl", "my_repository")
WORKSPACE.bazel:
WORKSPACE.bazel:my_repository(
WORKSPACE.bazel:    name = "repo_with_bug"
WORKSPACE.bazel:)
repo_rule.bzl:def _my_repository_impl(repository_ctx):
repo_rule.bzl:    result = repository_ctx.execute(["wrong_path"], quiet = False)
repo_rule.bzl:    fail(result.stderr)
repo_rule.bzl:
repo_rule.bzl:my_repository = repository_rule(
repo_rule.bzl:    implementation = _my_repository_impl,
repo_rule.bzl:    local = True,
repo_rule.bzl:)
```

Windows output:
```
> ..\bazel-7.4.1-windows-x86_64.exe query @repo_with_bug//:all --noenable_bzlmod
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository repo_with_bug instantiated at:
  E:/tmp/bazel_repo_rule_quiet_bug/WORKSPACE.bazel:3:14: in <toplevel>
Repository rule my_repository defined at:
  E:/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl:5:32: in <toplevel>
ERROR: E:/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl:3:9: An error occurred during the fetch of repository 'repo_with_bug':                                                                                          
   Traceback (most recent call last):                                                                                                                                                                                 
        File "E:/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl", line 3, column 9, in _my_repository_impl
                fail(result.stderr)
Error in fail: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("wrong_path"): The system cannot find the file specified.
 (error: 2)
ERROR: no such package '@@repo_with_bug//': java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("wrong_path"): The system cannot find the file specified.
 (error: 2) 
```
Linux output: 
```
$ ../bazel-7.4.1-linux-x86_64 query @repo_with_bug//:all --noenable_bzlmod
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
src/main/tools/process-wrapper-legacy.cc:80: "execvp(wrong_path, ...)": No such file or directory
INFO: Repository repo_with_bug instantiated at:                                                                                                                                                                       
  /mnt/e/tmp/bazel_repo_rule_quiet_bug/WORKSPACE.bazel:3:14: in <toplevel>                                                                                                                                            
Repository rule my_repository defined at:
  /mnt/e/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl:5:32: in <toplevel>
ERROR: /mnt/e/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl:3:9: An error occurred during the fetch of repository 'repo_with_bug':                                                                                      
   Traceback (most recent call last):                                                                                                                                                                                 
        File "/mnt/e/tmp/bazel_repo_rule_quiet_bug/repo_rule.bzl", line 3, column 9, in _my_repository_impl
                fail(result.stderr)
Error in fail: src/main/tools/process-wrapper-legacy.cc:80: "execvp(wrong_path, ...)": No such file or directory
ERROR: no such package '@@repo_with_bug//': src/main/tools/process-wrapper-legacy.cc:80: "execvp(wrong_path, ...)": No such file or directory
```

At Linux, stderr passed to the fail call was above. At Windows, it wasn't. So, if I don't explicitly print stderr, I won't be able to find the real problem error message.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See example in description.

### Which operating system are you running Bazel on?

Windows, Linux

### What is the output of `bazel info release`?

release 7.4.1

**Comment by Wyverald** [comment]
I haven't had time to look too deeply into this, but it seems to me that this bug might only happen if you're trying to execute a nonexistent file. It looks like we create the subprocess, then link up stderr to Bazel's own stderr; this is fine on Linux/Mac, but we use a custom impl of the subprocess creation stuff on Windows, and if the process creation fails right away, we throw before even linking up stderr.

Could you try to see if this bug still happens if you just run a valid program that just prints something to stderr?
