### ISSUE TITLE
Bazel 8 crash when building `ios_application` at the root

### ISSUE THREAD

**Issue by jpsim** [bazelbuild/bazel#24625]
### Description of the bug:

When building an iOS app using [Bazel 8.0.0](https://github.com/bazelbuild/bazel/releases/tag/8.0.0) and [rules_apple 3.16.0](https://github.com/bazelbuild/rules_apple/releases/tag/3.16.0), Bazel crashes with the following output:

```console
$ bazel build //:iOSApp
Analyzing: target //:iOSApp (28 packages loaded, 553 targets configured)
    currently loading: @@rules_python+//python/private

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:iOSApp, config=BuildConfigurationKey[8eddf44734490dc07f46b246d49780b061f129833bf45d4750c99942b5c6ace7]}' (requested by nodes 'ConfiguredTargetKey{label=//:iOSApp, config=BuildConfigurationKey[e5d0b45255bbe29fcc274b3efed42ccbd4b88bf8d5a015d3138aed480339a787]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//:iOSApp)
	at <starlark>.declare_shareable_artifact(<builtin>:0)
	at <starlark>._register_configuration_specific_link_actions(/virtual_builtins_bzl/common/objc/compilation_support.bzl:858)
	at <starlark>._link_multi_arch_binary(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/linking_support.bzl:300)
	at <starlark>._register_binary_linking_action(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/linking_support.bzl:528)
	at <starlark>._ios_application_impl(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/ios_rules.bzl:239)
Caused by: java.lang.IllegalArgumentException: /iOSApp_bin
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.devtools.build.lib.actions.ArtifactFactory.validatePath(ArtifactFactory.java:183)
	at com.google.devtools.build.lib.actions.ArtifactFactory.getDerivedArtifact(ArtifactFactory.java:227)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:282)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:274)
	at com.google.devtools.build.lib.analysis.RuleContext.getShareableArtifact(RuleContext.java:716)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkActionFactory.createShareableArtifact(StarlarkActionFactory.java:1023)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:178)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:78)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execIf(Eval.java:224)
	at net.starlark.java.eval.Eval.exec(Eval.java:300)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFor(Eval.java:138)
	at net.starlark.java.eval.Eval.exec(Eval.java:293)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.evalRule(StarlarkRuleConfiguredTargetUtil.java:100)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:405)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:202)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1389)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:447)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Following the main rules_apple tutorial in [doc/tutorials/ios-app.md](https://github.com/bazelbuild/rules_apple/blob/master/doc/tutorials/ios-app.md) is enough to reproduce the issue.

I also found that if the `ios_application` is not at the root then this crash doesn't occur: e.g. `//foo:iOSApp`

Also using Bazel 7.4.1 works fine. 8.0.0rc1 also crashes in the same way.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Following the main rules_apple tutorial in [doc/tutorials/ios-app.md](https://github.com/bazelbuild/rules_apple/blob/master/doc/tutorials/ios-app.md) is enough to reproduce the issue.

### Which operating system are you running Bazel on?

macOS 15.1.1 (24B2091)

### What is the output of `bazel info release`?

release 8.0.0

### Have you found anything relevant by searching the web?

Originally reported here: https://github.com/bazelbuild/rules_apple/issues/2619

**Comment by keith** [comment]
cc @pzembrod guess this is a bug in the newly used declare_shareable_artifact

**Comment by meteorcloudy** [comment]
@bazel-io fork 8.0.1

**Comment by pzembrod** [comment]
Yeah, just looked at https://github.com/bazelbuild/bazel/issues/24625 - thanks for your comment there

**Comment by pzembrod** [comment]
Definitely something we should fix for 8.0.1.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/24698

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.1 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.0.1rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.0.1rc1. Thanks!

**Comment by jpsim** [comment]
Fix works well, thanks!

**Comment by jpsim** [comment]
I spoke too soon. The issues with `ios_application` are now fixed, but this is still happening on `ios_framework` targets with Bazel 8.0.1 and 8.1.0rc4.

**Comment by keith** [comment]
I actually can't repro with a setup that does crash with 8.0.0, can you verify? 

```
USE_BAZEL_VERSION=8.1.0 bazelisk build ...
```

[repro.zip](https://github.com/user-attachments/files/18812277/repro.zip)

**Comment by jpsim** [comment]
With your repro zip, this produces the crash:

```console
$ USE_BAZEL_VERSION=8.1.0 bazelisk build --apple_generate_dsym //:MyFramework
Starting local Bazel server (8.1.0) and connecting to it...
Analyzing: target //:MyFramework (102 packages loaded, 3298 targets configured)

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:MyFramework, config=BuildConfigurationKey[0bc4d6fd6a877f3fdfa16a026be76c7a62205f8dc7a7bbdb3b4cc433cde2d4b3]}' (requested by nodes 'ConfiguredTargetKey{label=//:MyFramework, config=BuildConfigurationKey[6761439389f74ca083660e94771654dc5f183c94e605e750dbca69f9f1983ade]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//:MyFramework)
	at <starlark>.declare_shareable_artifact(<builtin>:0)
	at <starlark>._link_multi_arch_binary(/private/var/tmp/_bazel_jsimard/8477fe05e788e8079f5b77b2d864c5a0/external/rules_apple+/apple/internal/linking_support.bzl:278)
	at <starlark>._register_binary_linking_action(/private/var/tmp/_bazel_jsimard/8477fe05e788e8079f5b77b2d864c5a0/external/rules_apple+/apple/internal/linking_support.bzl:525)
	at <starlark>._ios_framework_impl(/private/var/tmp/_bazel_jsimard/8477fe05e788e8079f5b77b2d864c5a0/external/rules_apple+/apple/internal/ios_rules.bzl:934)
Caused by: java.lang.IllegalArgumentException: /MyFramework_bin.dwarf
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.devtools.build.lib.actions.ArtifactFactory.validatePath(ArtifactFactory.java:183)
	at com.google.devtools.build.lib.actions.ArtifactFactory.getDerivedArtifact(ArtifactFactory.java:227)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:282)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:274)
	at com.google.devtools.build.lib.analysis.RuleContext.getShareableArtifact(RuleContext.java:716)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkActionFactory.createShareableArtifact(StarlarkActionFactory.java:1022)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:178)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:78)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:809)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:746)
	at net.starlark.java.eval.Eval.eval(Eval.java:561)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:122)
	at net.starlark.java.eval.Eval.exec(Eval.java:286)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:83)
	at net.starlark.java.eval.Eval.execIf(Eval.java:223)
	at net.starlark.java.eval.Eval.exec(Eval.java:301)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:83)
	at net.starlark.java.eval.Eval.execFor(Eval.java:139)
	at net.starlark.java.eval.Eval.exec(Eval.java:294)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:83)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:67)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:809)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:746)
	at net.starlark.java.eval.Eval.eval(Eval.java:561)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:122)
	at net.starlark.java.eval.Eval.exec(Eval.java:286)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:83)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:67)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:809)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:746)
	at net.starlark.java.eval.Eval.eval(Eval.java:561)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:122)
	at net.starlark.java.eval.Eval.exec(Eval.java:286)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:83)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:67)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:809)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.evalRule(StarlarkRuleConfiguredTargetUtil.java:100)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:405)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:202)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1389)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:446)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:370)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by jpsim** [comment]
Fixing in rules_apple here: https://github.com/bazelbuild/rules_apple/pull/2651

**Comment by keith** [comment]
Nice!
