### ISSUE TITLE
`bazel info` crashes due to Bzlmod errors

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24671]
### Description of the bug:

`bazel info` doesn't properly handle errors encountered while computing the main repo mapping required to load the Starlark exec transition while injecting the precomputed baseline config.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`USE_BAZEL_VERSION=last_green bazel info --registry=foobarbaz`

```
Starting local Bazel server (no_version) and connecting to it...
INFO: Invocation ID: 08cc1fa4-e410-4558-8875-2d04b9a75d4d
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "java.util.Optional.orElse(Object)" because the return value of "com.google.devtools.build.lib.analysis.config.StarlarkExecTransitionLoader.loadStarlarkExecTransition(com.google.devtools.build.lib.analysis.config.BuildOptions, com.google.devtools.build.lib.analysis.config.StarlarkExecTransitionLoader$BzlFileLoader)" is null
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getStarlarkExecTransition(SkyframeExecutor.java:2096)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.adjustForExec(SkyframeExecutor.java:1431)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.setBaselineConfiguration(SkyframeExecutor.java:1424)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.lambda$exec$0(InfoCommand.java:156)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:186)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:219)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:697)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:677)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by fmeum** [comment]
@meteorcloudy @susinmotion

**Comment by meteorcloudy** [comment]
Is this only at HEAD or also in 8.0?

**Comment by fmeum** [comment]
Only at HEAD, I think that https://github.com/bazelbuild/bazel/commit/37d733fe121a4e47c006493769310701f44fc8b2 causes this.
