### ISSUE TITLE
RemoteOutputService fails when using directory tree objects larger than 4MB

### ISSUE THREAD

**Issue by quic-sbjorkle** [bazelbuild/bazel#24705]
### Description of the bug:

The current implementation of the remote output service protocol in BazelOutputService.java places all artifacts in a directory tree object within a single message for both StageArtifacts and FinalizeArtifacts. 

As a result, Bazel crashes when a directory object exceeds the 4MB size limit.

> RESOURCE_EXHAUSTED: grpc: received message larger than max (23888933 vs. 4194304)
> java.io.IOException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (23888933 vs. 4194304)
>         at com.google.devtools.build.lib.remote.BazelOutputService.lambda$stageArtifacts$2(BazelOutputService.java:315)
>         at com.google.devtools.build.lib.remote.ReferenceCountedChannel.lambda$withChannelBlocking$2(ReferenceCountedChannel.java:102)
>         at com.google.devtools.build.lib.remote.ReferenceCountedChannel.lambda$withChannel$3(ReferenceCountedChannel.java:145)
>         at com.google.devtools.build.lib.remote.ReferenceCountedChannel.lambda$withChannelConnection$5(ReferenceCountedChannel.java:161)
>         at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:59)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:85)
>         at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:112)
>         at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:65)
>         at io.reactivex.rxjava3.internal.operators.single.SingleDoOnDispose$DoOnDisposeObserver.onSuccess(SingleDoOnDispose.java:84)
>         at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:110)
>         at io.reactivex.rxjava3.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:85)
>         at io.reactivex.rxjava3.subjects.AsyncSubject.subscribeActual(AsyncSubject.java:233)
>         at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13176)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:36)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleDoOnDispose.subscribeActual(SingleDoOnDispose.java:38)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:35)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:85)
>         at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
>         at com.google.devtools.build.lib.remote.grpc.TokenBucket$1.onNext(TokenBucket.java:79)
>         at io.reactivex.rxjava3.internal.util.NotificationLite.accept(NotificationLite.java:247)
>         at io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:507)
>         at io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:468)
>         at io.reactivex.rxjava3.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:224)
>         at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13176)
>         at com.google.devtools.build.lib.remote.grpc.TokenBucket.lambda$acquireToken$0(TokenBucket.java:64)
>         at io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
>         at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
>         at com.google.devtools.build.lib.remote.ReferenceCountedChannel.blockingGet(ReferenceCountedChannel.java:109)
>         at com.google.devtools.build.lib.remote.ReferenceCountedChannel.withChannelBlocking(ReferenceCountedChannel.java:102)
>         at com.google.devtools.build.lib.remote.BazelOutputService.lambda$stageArtifacts$3(BazelOutputService.java:310)
>         at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
>         at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
>         at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
>         at com.google.devtools.build.lib.remote.BazelOutputService.stageArtifacts(BazelOutputService.java:308)
>         at com.google.devtools.build.lib.remote.BazelOutputService.stageArtifacts(BazelOutputService.java:287)
>         at com.google.devtools.build.lib.remote.RemoteExecutionService.downloadOutputs(RemoteExecutionService.java:1370)
>         at com.google.devtools.build.lib.remote.RemoteSpawnRunner.downloadAndFinalizeSpawnResult(RemoteSpawnRunner.java:454)
>         at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:310)
>         at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
>         at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
>         at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
>         at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:266)
>         at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:158)
>         at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:118)
>         at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
>         at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:263)
>         at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1159)
>         at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1076)
>         at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
>         at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
>         at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:573)
>         at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:862)
>         at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:334)
>         at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:172)
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
>         at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
>         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (23888933 vs. 4194304)
>         at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
>         at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
>         at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
>         at com.google.devtools.build.lib.remote.BazelOutputServiceGrpc$BazelOutputServiceBlockingStub.stageArtifacts(BazelOutputServiceGrpc.java:610)
>         at com.google.devtools.build.lib.remote.BazelOutputService.lambda$stageArtifacts$2(BazelOutputService.java:313)
>         ... 74 more
> 

Proposed solution:
Split the artifact list in StageArtifacts and FinalizeArtifacts into multiple messages when the message size exceeds the GRPC max message size limit.

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

large_directory.bzl:
```
def _large_directory_impl(ctx):
    o = ctx.actions.declare_directory(ctx.attr.name + "_dir")
    ctx.actions.run_shell(
        inputs = [],
        outputs = [o],
        command = "for i in {1..100000}; do touch %s/long_filename_which_uses_a_lot_of_index_space_$i; done" % (o.path),
    )
    return DefaultInfo(files = depset([o]))

large_directory = rule(
    implementation = _large_directory_impl,
    attrs = {},
)
```

BUILD.bazel
```
load(":large_directory.bzl", "large_directory")
large_directory(
    name = "large_directory",
)

```

> bazel build :large_directory --config=use_remote_output_service_config

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.4.1

**Comment by meisterT** [comment]
cc @coeuvre

**Comment by quic-sbjorkle** [comment]
@coeuvre, any update or ETA on this issue?

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 9.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/9.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=9.3.0rc1`. Thanks!
