### ISSUE TITLE
Bazel 8.0.0 can crash when attempting to update `MODULE.bazel.lock`

### ISSUE THREAD

**Issue by armandomontanez** [bazelbuild/bazel#24716]
### Description of the bug:

When migrating to Bazel 8.0.0, I started hitting the crash below. I was able to work around by *manually* running `bazel mod deps --lockfile_mode=update`. The produced diff can be seen [here](https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/242033/10..11). The delta that caused this error to start popping up can be seen [here](https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/242033/9..10). This is likely related to removing a `git_override` from the `MODULE.bazel` file.
```
$ bazel build //pw_build/...
Starting local Bazel server and connecting to it...
WARNING: For repository 'com_google_protobuf', the root module requires module version protobuf@28.2, but got protobuf@29.0 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
WARNING: WORKSPACE support will be removed in Bazel 9 (late 2025), please migrate to Bzlmod, see https://bazel.build/external/migration.
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
WARNING: /Users/amontanez/development/projects/pigweed/pigweed/pw_toolchain/arm_gcc/BUILD.bazel:370:10: in toolchain rule //pw_toolchain/arm_gcc:arm_gcc_cc_toolchain_cortex-m33+nofp: target '//pw_toolchain/arm_gcc:arm_gcc_cc_toolchain_cortex-m33+nofp' depends on deprecated target '//pw_build/constraints/arm:cortex-m33+nofp': FPU properties should be expressed with different constraints
WARNING: /Users/amontanez/development/projects/pigweed/pigweed/pw_toolchain/arm_gcc/BUILD.bazel:343:10: in toolchain rule //pw_toolchain/arm_gcc:arm_gcc_cc_toolchain_cortex-m4+nofp: target '//pw_toolchain/arm_gcc:arm_gcc_cc_toolchain_cortex-m4+nofp' depends on deprecated target '//pw_build/constraints/arm:cortex-m4+nofp': FPU properties should be expressed with different constraints
INFO: Analyzed 55 targets (254 packages loaded, 15823 targets configured).
INFO: Found 55 targets...
INFO: Elapsed time: 28.115s, Critical Path: 0.17s
INFO: 44 processes: 175 action cache hit, 44 internal.
INFO: Build completed successfully, 44 total actions
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.bazel.bzlmod.RepoRuleId.toString()" because "repoRuleId" is null
	at com.google.devtools.build.lib.bazel.bzlmod.GsonTypeAdapterUtil$4.write(GsonTypeAdapterUtil.java:114)
	at com.google.devtools.build.lib.bazel.bzlmod.GsonTypeAdapterUtil$4.write(GsonTypeAdapterUtil.java:111)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.write(ReflectiveTypeAdapterFactory.java:247)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:490)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:253)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:154)
	at com.google.devtools.build.lib.bazel.bzlmod.DelegateTypeAdapterFactory$1.write(DelegateTypeAdapterFactory.java:128)
	at com.google.devtools.build.lib.bazel.bzlmod.LockFileModuleExtension_GsonTypeAdapter.write(LockFileModuleExtension_GsonTypeAdapter.java:108)
	at com.google.devtools.build.lib.bazel.bzlmod.LockFileModuleExtension_GsonTypeAdapter.write(LockFileModuleExtension_GsonTypeAdapter.java:17)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:253)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:154)
	at com.google.devtools.build.lib.bazel.bzlmod.DelegateTypeAdapterFactory$1.write(DelegateTypeAdapterFactory.java:128)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:253)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:154)
	at com.google.devtools.build.lib.bazel.bzlmod.DelegateTypeAdapterFactory$1.write(DelegateTypeAdapterFactory.java:128)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue_GsonTypeAdapter.write(BazelLockFileValue_GsonTypeAdapter.java:78)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue_GsonTypeAdapter.write(BazelLockFileValue_GsonTypeAdapter.java:15)
	at com.google.gson.Gson.toJson(Gson.java:944)
	at com.google.gson.Gson.toJson(Gson.java:899)
	at com.google.gson.Gson.toJson(Gson.java:848)
	at com.google.gson.Gson.toJson(Gson.java:825)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileModule.updateLockfile(BazelLockFileModule.java:226)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileModule.afterCommand(BazelLockFileModule.java:131)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:721)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:710)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:253)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$0(GrpcServerImpl.java:677)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

macOS 14.7.1

### What is the output of `bazel info release`?

release 8.0.0

**Comment by fmeum** [comment]
I can't find a call site where the `RepoRuleId` in a `RepoSpec` could ever be `null` and https://github.com/bazelbuild/bazel/commit/3d60f1cf7aaacc98cf06f3c2eb62c2f521ce5868 explicitly bumped the lockfile version when it introduced the `repoRuleId` field. 

Is it possible that your lockfile was subject to some manual merge conflict resolution that somehow ended up preserving the old entries but bumping the `lockfileVersion` field to 16? Can you still reproduce this issue?

**Comment by Wyverald** [comment]
Do you have a pigweed commit where we can try to reproduce this?

**Comment by Silic0nS0ldier** [comment]
`repoRuleId` is a new field in `MODULE.bazel.lock` and it appears in certain circumstances Bazel fails to add it when upgrading the lockfile from an older version.

In our case (Canva), deleting the existing `MODULE.bazel.lock` in order to regenerate it fixed the problem. The diff was;
```diff
diff --git a/MODULE.bazel.lock b/MODULE.bazel.lock
index 03094794cdf7b..a224c2b00171e 100644
--- a/MODULE.bazel.lock
+++ b/MODULE.bazel.lock
@@ -34374,8 +34374,7 @@
         "envVariables": {},
         "generatedRepoSpecs": {
           "nixpkgs": {
-            "bzlFile": "@@rules_nixpkgs_core+//:nixpkgs.bzl",
-            "ruleClassName": "_nixpkgs_http_repository",
+            "repoRuleId": "@@rules_nixpkgs_core+//:nixpkgs.bzl%_nixpkgs_http_repository",
             "attributes": {
               "unmangled_name": "nixpkgs",
               "url": "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz",
```

It isn't clear why this stuck around. To my knowledge we haven't had any merge conflicts (not even a semantic merge conflict).

**Comment by iancha1992** [comment]
@armandomontanez Did you migrate to Bazel 9?

**Comment by iancha1992** [comment]
@bazel-io fork 8.8.0

**Comment by iancha1992** [comment]
@bazel-io fork 9.3.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.8.0 RC4](https://github.com/bazelbuild/bazel/releases/tag/8.8.0rc4). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.8.0rc4`. Thanks!

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 9.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/9.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=9.3.0rc1`. Thanks!
