### ISSUE TITLE
Bazel CI flaky test failure com.google.devtools.build.lib.skyframe.PackageFunctionTest testLoadBadLabel[globUnderSingleDep=true]


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#24774]
CI: https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/09c4c554-6bc3-850d-8e99-ffdf6dfea56b?period=1day&branch=master

 Platform: Ubuntu

 Logs: 
```

java.lang.Exception: Test cancelled
	at com.google.testing.junit.runner.model.TestCaseNode.testInterrupted(TestCaseNode.java:89)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteModel.testRunInterrupted(TestSuiteModel.java:150)
	at com.google.testing.junit.runner.internal.junit4.JUnit4TestXmlListener$WriteXmlSignalHandler.handle(JUnit4TestXmlListener.java:118)
	at com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:62)
	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:218)
	at java.base/java.lang.Thread.run(Thread.java:1583)
``` 
 Culprit: 

 Steps:
  ``` 
  
 ``` 
 CC Greenteam @fweikert

**Comment by coeuvre** [comment]
From the build log, it seems like `PackageFunctionTest` is timed out. This particular test was cancelled due to timeout, I don't think it is flaky. Maybe we should increase the shard count.

**Comment by zhengwei143** [comment]
This seems to have been fixed
