### ISSUE TITLE
Bazel 8.0.0 crashes on windows: Unrecoverable error while evaluating node, java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#24801]
### Description of the bug:

We are seeing this error approx 10-15 times per day in our CI system with bazel 8.0.0. It is for a different DLL each time. Every time it is the same java.nio.file.AccessDeniedException. Rerunning the build command typically succeeds.

```
[391,431 / 405,569] checking cached actions
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupDataN{actionLookupKey=ConfiguredTargetKey{label=//src/path/to:target, config=BuildConfigurationKey[9cfe96a447c6024399e3d957765b4a9c50e92c7d30e8113fa769583f44a41f7f]}, actionIndex=1989}' (requested by nodes 'ArtifactNestedSetKey[210]@660341467')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: D:\udu\b\mor466oi\execroot\_main\bazel-out\x64_windows-opt\bin\src\path\to\libxy.dll
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:519)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:320)
        at com.google.devtools.build.lib.remote.RemoteActionFileSystem.statInternal(RemoteActionFileSystem.java:658)
        at com.google.devtools.build.lib.remote.RemoteActionFileSystem.statIfFound(RemoteActionFileSystem.java:598)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:320)
        at com.google.devtools.build.lib.skyframe.ActionOutputMetadataStore.fileArtifactValueFromArtifact(ActionOutputMetadataStore.java:588)
        at com.google.devtools.build.lib.skyframe.ActionOutputMetadataStore.constructFileArtifactValue(ActionOutputMetadataStore.java:450)
        at com.google.devtools.build.lib.skyframe.ActionOutputMetadataStore.constructFileArtifactValueFromFilesystem(ActionOutputMetadataStore.java:438)
        at com.google.devtools.build.lib.skyframe.ActionOutputMetadataStore.getOutputMetadata(ActionOutputMetadataStore.java:235)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.getOutputMetadataOrConstant(ActionCacheChecker.java:667)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.getOutputMetadataMaybe(ActionCacheChecker.java:694)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.validateArtifacts(ActionCacheChecker.java:223)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:621)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:554)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:677)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:854)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:375)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:216)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
        ... 7 more
Caused by: java.nio.file.AccessDeniedException: D:\udu\b\mor466oi\execroot\_main\bazel-out\x64_windows-opt\bin\src\path\to\libxy.dll
        at com.google.devtools.build.lib.windows.WindowsFileOperations.getLastChangeTime(WindowsFileOperations.java:166)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:155)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:509)
```

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

Windows Server 2022 Standard

### What is the output of `bazel info release`?

8.0.0

**Comment by fmeum** [comment]
@bazel-io fork 8.0.1

**Comment by fmeum** [comment]
Could you try to bisect this down to the breaking commit? My best guess would be the switch over to the toolchain in rules_cc, which may be missing a fix.

**Comment by peakschris** [comment]
It's going to be challenging to bisect as it only fails once every 20 builds or so. If you give me a few commits to manually bisect I can leave each one running for a few hours and see how they get on.

**Comment by fmeum** [comment]
Could you test https://github.com/bazelbuild/bazel/commit/263ad1ae7d2a54ddc8e2c05654ab50156f40082c? That's the parent of the commit that moves the toolchain to rules_cc.

**Comment by fmeum** [comment]
You probably need to prepend the full rules_java release snippet for a recent version to your WORKSPACE file: https://github.com/bazelbuild/rules_java/releases/tag/8.6.3

**Comment by fmeum** [comment]
I'm pretty sure that this error can only arise when WORKSPACE is enabled. Are you sure it's disabled on your repo? Does this reproduce if you create an empty WORKSPACE.bazel file?

**Comment by peakschris** [comment]
Found an errant .bazelrc enable_workspace command, now removed. Now I'm seeing this issue. I have tried rules_java 8.6.1, 8.6.2, 8.6.3

```
bazel build //src/... --noenable_workspace
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
ERROR: Traceback (most recent call last):
        File "D:/udu/b/mor466oi/external/rules_java+/java/private/java_common.bzl", line 323, column 32, in <toplevel>
                java_common = _make_java_common()
        File "D:/udu/b/mor466oi/external/rules_java+/java/private/java_common.bzl", line 313, column 34, in _make_java_common
                if get_internal_java_common().google_legacy_api_enabled():
Error: 'struct' value has no field or method 'google_legacy_api_enabled'
Available attributes: JavaCompilationInfo, JavaPluginDataInfo, collect_native_deps_dirs, compile, expand_java_opts, get_runtime_classpath_for_archive, incompatible_disable_non_executable_java_binary, run_ijar_private_for_builtins, target_kind, to_java_binary_info
WARNING: Target pattern parsing failed.
ERROR: Skipping '@rules_go//go/config:pure': error loading package '@@rules_go+//go/config': Internal error while loading Starlark builtins: Failed to autoload external symbols: at D:/udu/b/mor466oi/external/rules_java+/java/java_import.bzl:16:6: at D:/udu/b/mor466oi/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:10:6: initialization of module 'java/private/java_common.bzl' failed
ERROR: @rules_go//go/config:pure :: Error loading option @rules_go//go/config:pure: error loading package '@@rules_go+//go/config': Internal error while loading Starlark builtins: Failed to autoload external symbols: at D:/udu/b/mor466oi/external/rules_java+/java/java_import.bzl:16:6: at D:/udu/b/mor466oi/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:10:6: initialization of module 'java/private/java_common.bzl' failed
```

**Comment by fmeum** [comment]
Can you test with a custom Bazel binary? Reverting https://cs.opensource.google/bazel/bazel/+/a0a72265ea37270c110630f528127e18939f4016 on 8.0.0 would be an interesting experiment as that's the only change in 8.0.0 that actually touches the method that now fails.

**Comment by peakschris** [comment]
I got set up for a custom build, but unless I'm missing something, that commit isn't part of 8.0.0

**Comment by peakschris** [comment]
as that commit isn't in 8.0.0, I can't back it out. Do you have any other suggestions?

**Comment by jayakasadev** [comment]
will the commit be in the next release?

**Comment by fmeum** [comment]
You're right, it's not in 8. I don't have any guesses then. Will take another look. Trying some rolling releases between the two prod releases would help. 

Maybe @hvadehra can help with the rules_java failures during the bisect (in the new year)?

**Comment by fmeum** [comment]
7b2e6b24d335202675a50140dfe7c5aedb45dce2 is another guess for the culprit. Could you test a custom Bazel build from the `release-8.0.0` branch with this patch applied (a revert of that commit with merge conflicts resolved)?

```patch
diff --git a/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java b/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
index 55cad4046c..e00bff3515 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
+++ b/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
@@ -112,21 +112,21 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
 
   @Nullable private ActionExecutionMetadata action = null;
 
-  /** Describes how to handle symlinks when calling {@link #statInternal}. */
+  /** Describes how to handle symlinks when calling {@link #statUnchecked}. */
   private enum FollowMode {
-    /** Canonicalize the entire path. This is equivalent to {@link Symlinks.FOLLOW}. */
+    /** Dereference the entire path. This is equivalent to {@link Symlinks.FOLLOW}. */
     FOLLOW_ALL,
-    /** Canonicalize the parent path. This is equivalent to {@link Symlinks.NOFOLLOW}. */
+    /** Dereference the parent path. This is equivalent to {@link Symlinks.NOFOLLOW}. */
     FOLLOW_PARENT,
-    /** Do not canonicalize. This is only used internally to resolve symlinks efficiently. */
+    /** Do not dereference. This is only used internally to resolve symlinks efficiently. */
     FOLLOW_NONE
   };
 
-  /** Describes which sources to consider when calling {@link #statInternal}. */
+  /** Describes which sources to consider when statting a file. */
   private enum StatSources {
-    /** Consider all sources (action input map, remote output tree and local filesystem). */
+    /** Consider all sources (action input map, in-memory filesystem and local filesystem). */
     ALL,
-    /** Consider only in-memory sources (action input map and remote output tree). */
+    /** Consider only in-memory sources (action input map and in-memory filesystem). */
     IN_MEMORY_ONLY,
   }
 
@@ -290,9 +290,13 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
 
   private boolean isRemote(PathFragment path) throws IOException {
     // Files in the local filesystem are non-remote by definition, so stat only in-memory sources.
-    var status = statInternal(path, FollowMode.FOLLOW_ALL, StatSources.IN_MEMORY_ONLY);
-    return status instanceof FileStatusWithMetadata fileStatusWithMetadata
-        && fileStatusWithMetadata.getMetadata().isRemote();
+    try {
+      var status = statUnchecked(path, FollowMode.FOLLOW_ALL, StatSources.IN_MEMORY_ONLY);
+      return status instanceof FileStatusWithMetadata fileStatusWithMetadata
+          && fileStatusWithMetadata.getMetadata().isRemote();
+    } catch (FileNotFoundException e) {
+      return false;
+    }
   }
 
   public void updateContext(ActionExecutionMetadata action) {
@@ -328,7 +332,7 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
     //
     // The parent path has already been canonicalized, so FOLLOW_NONE is effectively the same as
     // FOLLOW_PARENT, but much more efficient as it doesn't call stat recursively.
-    var stat = statInternal(path, FollowMode.FOLLOW_NONE, StatSources.ALL);
+    var stat = statUnchecked(path, FollowMode.FOLLOW_NONE, StatSources.ALL);
     if (stat == null) {
       throw new FileNotFoundException(path.getPathString() + " (No such file or directory)");
     }
@@ -420,15 +424,18 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
   }
 
   @Override
-  @Nullable
   protected byte[] getFastDigest(PathFragment path) throws IOException {
     path = resolveSymbolicLinks(path).asFragment();
     // Try to obtain a fast digest through a stat. This is only possible for in-memory files.
     // The parent path has already been canonicalized by resolveSymbolicLinks, so FOLLOW_NONE is
     // effectively the same as FOLLOW_PARENT, but more efficient.
-    var status = statInternal(path, FollowMode.FOLLOW_NONE, StatSources.IN_MEMORY_ONLY);
-    if (status instanceof FileStatusWithDigest fileStatusWithDigest) {
-      return fileStatusWithDigest.getDigest();
+    try {
+      var status = statUnchecked(path, FollowMode.FOLLOW_NONE, StatSources.IN_MEMORY_ONLY);
+      if (status instanceof FileStatusWithDigest fileStatusWithDigest) {
+        return fileStatusWithDigest.getDigest();
+      }
+    } catch (FileNotFoundException e) {
+      // Intentionally ignored.
     }
     return localFs.getPath(path).getFastDigest();
   }
@@ -439,9 +446,13 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
     // Try to obtain a fast digest through a stat. This is only possible for in-memory files.
     // The parent path has already been canonicalized by resolveSymbolicLinks, so FOLLOW_NONE is
     // effectively the same as FOLLOW_PARENT, but more efficient.
-    var status = statInternal(path, FollowMode.FOLLOW_NONE, StatSources.IN_MEMORY_ONLY);
-    if (status instanceof FileStatusWithDigest fileStatusWithDigest) {
-      return fileStatusWithDigest.getDigest();
+    try {
+      var status = statUnchecked(path, FollowMode.FOLLOW_NONE, StatSources.IN_MEMORY_ONLY);
+      if (status instanceof FileStatusWithDigest fileStatusWithDigest) {
+        return fileStatusWithDigest.getDigest();
+      }
+    } catch (FileNotFoundException e) {
+      // Intentionally ignored.
     }
     return localFs.getPath(path).getDigest();
   }
@@ -583,45 +594,34 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
     }
   }
 
-  @Override
-  protected FileStatus stat(PathFragment path, boolean followSymlinks) throws IOException {
-    FileStatus stat = statIfFound(path, followSymlinks);
-    if (stat == null) {
-      throw new FileNotFoundException(path.getPathString() + " (No such file or directory)");
-    }
-    return stat;
-  }
-
   @Nullable
   @Override
   protected FileStatus statIfFound(PathFragment path, boolean followSymlinks) throws IOException {
-    return statInternal(
-        path, followSymlinks ? FollowMode.FOLLOW_ALL : FollowMode.FOLLOW_PARENT, StatSources.ALL);
+    try {
+      return stat(path, followSymlinks);
+    } catch (FileNotFoundException e) {
+      return null;
+    }
   }
 
   @Nullable
   @Override
   protected FileStatus statNullable(PathFragment path, boolean followSymlinks) {
     try {
-      return statIfFound(path, followSymlinks);
+      return stat(path, followSymlinks);
     } catch (IOException e) {
       return null;
     }
   }
 
-  /**
-   * Internal stat implementation.
-   *
-   * @param path the path to stat
-   * @param followMode whether and how to canonicalize the path
-   * @param statSources which sources to consider
-   * @return the file status on success, or null if the file was not found in any of the sources
-   *     under consideration
-   * @throws IOException if an error other than file not found occurred
-   */
-  @Nullable
-  private FileStatus statInternal(PathFragment path, FollowMode followMode, StatSources statSources)
-      throws IOException {
+  @Override
+  protected FileStatus stat(PathFragment path, boolean followSymlinks) throws IOException {
+    return statUnchecked(
+        path, followSymlinks ? FollowMode.FOLLOW_ALL : FollowMode.FOLLOW_PARENT, StatSources.ALL);
+  }
+
+  private FileStatus statUnchecked(
+      PathFragment path, FollowMode followMode, StatSources statSources) throws IOException {
     // Canonicalize the path.
     try {
       if (followMode == FollowMode.FOLLOW_ALL) {
@@ -655,10 +655,10 @@ public class RemoteActionFileSystem extends AbstractFileSystemWithCustomStat
     }
 
     if (statSources == StatSources.ALL) {
-      return localFs.getPath(path).statIfFound(Symlinks.NOFOLLOW);
+      return localFs.getPath(path).stat(Symlinks.NOFOLLOW);
     }
 
-    return null;
+    throw new FileNotFoundException(path.getPathString() + " (No such file or directory)");
   }
 
   private static FileStatusWithMetadata statFromMetadata(FileArtifactValue m) {
diff --git a/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java b/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
index 5820d398fe..7b8d6955ca 100644
--- a/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
+++ b/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
@@ -335,7 +335,6 @@ public abstract class FileSystem {
    * filesystem doesn't support them. This digest should be suitable for detecting changes to the
    * file.
    */
-  @Nullable
   protected byte[] getFastDigest(PathFragment path) throws IOException {
     return null;
   }
```

**Comment by hvadehra** [comment]
> Error: 'struct' value has no field or method 'google_legacy_api_enabled'

> Maybe @hvadehra can help with the rules_java failures during the bisect (in the new year)?

The issue is probably that rules_java (in attempting to maintain backwards compatibility) assumes an unreleased Bazel version is close to HEAD. IOW it does not fallback to native rules as it should for Bazel < 8. 

If you can bisect with Bazel versions built yourself (as opposed to the prebuilts downloaded by bazelisk), then try building with something like `bazel build --stamp --embed_label="7.99.99-$(git rev-parse --short HEAD)" //src:bazel`. (will not work for newer commits closer to HEAD where the native java rules have been deleted, should be fine for things near or before Bazel 8rc1).
