### ISSUE TITLE
Fail fast if AndroidSdkRepositoryFunction sdk doesn't exist

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#2500]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm trying to have [Dagger](https://github.com/google/dagger) update to 0.4.4 and I'm removing `//external:android/support_v4` with `@androidsdk//com.android.support:support-v4-25.0.0`. When I try to build the latter target, I get the following exception thrown:

```
.........
____Loading package: @androidsdk//com.android.support
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
____Loading package: @local_config_cc//
____Loading complete.  Analyzing...
____Loading package: @androidsdk//
____Loading package: @bazel_tools//tools/android
____Loading package: @bazel_tools//tools/zip
____Loading package: @bazel_tools//third_party/py/gflags
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (1080012985 1097602915)' (requested by nodes 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-v4-25.0.0 16977b3b770ee458f7bef259d010b077 (1614875653 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-ui-25.0.0 16977b3b770ee458f7bef259d010b077 (1337032925 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-media-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (262975690 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-utils-25.0.0 16977b3b770ee458f7bef259d010b077 (1810003764 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-fragment-25.0.0 16977b3b770ee458f7bef259d010b077 (53178217 1097602915)')
____Elapsed time: 4.810s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (1080012985 1097602915)' (requested by nodes 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-v4-25.0.0 16977b3b770ee458f7bef259d010b077 (1614875653 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-ui-25.0.0 16977b3b770ee458f7bef259d010b077 (1337032925 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-media-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (262975690 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-utils-25.0.0 16977b3b770ee458f7bef259d010b077 (1810003764 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-fragment-25.0.0 16977b3b770ee458f7bef259d010b077 (53178217 1097602915)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.build(AndroidResourcesProcessorBuilder.java:204)
	at com.google.devtools.build.lib.rules.android.ApplicationManifest.createApk(ApplicationManifest.java:509)
	at com.google.devtools.build.lib.rules.android.ApplicationManifest.packWithDataAndResources(ApplicationManifest.java:345)
	at com.google.devtools.build.lib.rules.android.AarImport.create(AarImport.java:97)
	at com.google.devtools.build.lib.rules.android.AarImport.create(AarImport.java:51)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:276)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:176)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:491)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1094)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:251)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (1080012985 1097602915)' (requested by nodes 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-v4-25.0.0 16977b3b770ee458f7bef259d010b077 (1614875653 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-ui-25.0.0 16977b3b770ee458f7bef259d010b077 (1337032925 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-media-compat-25.0.0 16977b3b770ee458f7bef259d010b077 (262975690 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-core-utils-25.0.0 16977b3b770ee458f7bef259d010b077 (1810003764 1097602915)', 'CONFIGURED_TARGET:@androidsdk//com.android.support:support-fragment-25.0.0 16977b3b770ee458f7bef259d010b077 (53178217 1097602915)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.build(AndroidResourcesProcessorBuilder.java:204)
	at com.google.devtools.build.lib.rules.android.ApplicationManifest.createApk(ApplicationManifest.java:509)
	at com.google.devtools.build.lib.rules.android.ApplicationManifest.packWithDataAndResources(ApplicationManifest.java:345)
	at com.google.devtools.build.lib.rules.android.AarImport.create(AarImport.java:97)
	at com.google.devtools.build.lib.rules.android.AarImport.create(AarImport.java:51)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:276)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:176)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:491)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1094)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:251)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
```

### Environment info
* Operating System: Linux

* Bazel version (output of `bazel info release`):
0.4.4 (from bazel-0.4.4-installer-linux-x86_64.sh)

**Comment by ronshapiro** [comment]
So far I get similar errors for all values in `bazel query @androidsdk//com.android.support:all`

**Comment by aj-michael** [comment]
Hmm, this is strange. The NPE is from Bazel thinking that that AndroidSdk is null. Do you have a bazelrc file that is setting the --android_sdk flag?

**Comment by aj-michael** [comment]
Also, what is the contents of your `WORKSPACE`?

**Comment by ronshapiro** [comment]
No --android_sdk flag/bazelrc file. Should I be setting that?

https://github.com/google/dagger/blob/master/WORKSPACE

**Comment by aj-michael** [comment]
No, you shouldn't need to. If --android_sdk is not set, then the default value is //external:android/sdk, which is bound to @androidsdk//:sdk, which is an alias for @androidsdk//:sdk_<api level> where <api_level> is from your WORKSPACE file.

**Comment by aj-michael** [comment]
So I was able to recreate your issue by setting my android_sdk_repository api_level to 999. Can you check if $ANDROID_HOME/platforms/android-25 exists?

**Comment by aj-michael** [comment]
also, on a mostly unrelated note - I noticed your workaround for $ANDROID_HOME in your WORKSPACE file in https://github.com/google/dagger/blob/master/WORKSPACE#L18. As of Bazel 0.4.4, if you do not specify the path attribute of android_sdk_repository, then Bazel will use $ANDROID_HOME to find the android sdk.

**Comment by ronshapiro** [comment]
Ah, I have that actually as a symlink. Let me try to remove it and configure it properly.

**Comment by ronshapiro** [comment]
That solved the isssue. Is there something we can do to give this a clear error message?

**Comment by aj-michael** [comment]
Yes, there's two (maybe 3?) Bazel issues here that I plan to address (and will leave this issue open until they are addressed):

* AndroidSdkRepositoryFunction, which generates the targets in `@androidsdk//...`, knows which android sdk api levels are installed, and should fail if `api_level` is set to a value that is not installed or doesn't make sense. My repro case was with non-existant platforms directories, while it sounds like your problem was symlinks, so:
** AndroidSdkRepositoryFunction should handle symlinks correctly
* AarImport should fail fast with a helpful message (and certainly not NPE) if the AndroidSdkProvider is null. A simple repro case for that is:

```
$ cat BUILD
alias(
    name = 'sdk',
    actual = 'doesnotexist',
)
aar_import(
    name = 'aar',
    aar = 'foo.aar',
)
$ bazel build --android_sdk=//:sdk //:aar
```

I'm glad you're unstuck and thanks for reporting this!

**Comment by aj-michael** [comment]
Ok, as of cf9a2b662b2764fd3bddcb74d9a0ab70eb2f7f3d both of the action items I mentioned in my previous comment are complete.
