### ISSUE TITLE
CI failure: Windows is failing at HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2527]
http://ci.bazel.io/job/bazel-tests/555/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/console
```
____From Testing //src/test/java/com/google/devtools/build/android/ziputils:ziputils-tests:
==================== Test output for //src/test/java/com/google/devtools/build/android/ziputils:ziputils-tests:
JUnit4 Test Runner
Exception in thread "main" java.lang.IllegalArgumentException: Top test must be a suite
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:53)
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:30)
	at com.google.testing.junit.runner.util.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:92)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:146)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
================================================================================
FAIL: //src/test/java/com/google/devtools/common/options:options_test (see C:/bazel_ci/temp/_bazel_SYSTEM/LhCiLHCO/execroot/windows-x86_64/bazel-out/vc_14_0_x64-fastbuild/testlogs/src/test/java/com/google/devtools/common/options/options_test/test.log)
```

Java tests cannot find TestSuite on Windows.

Culprit: 48e7fe262aacd6602331435e22247ced260c87ec
In this change, the functionality (introduced in https://github.com/bazelbuild/bazel/commit/29e22949664b0c2a0a9cc8d48630f4712a89a067 for solving https://github.com/bazelbuild/bazel/issues/2242) of finding classpath from classpath jar was completely removed, which caused the failure.

@kush-c

**Comment by kush-c** [comment]
Did the rollback fix the issue?
How should I test the issue on a windows machine while submitting the roll-forward, to make sure I don't break this test again?

**Comment by dslomov** [comment]
Rollback fixed the issue.
