### ISSUE TITLE
Tensorflow fails on Windows

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2564]
http://ci.bazel.io/view/Dashboard/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/683/console

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE:[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head]' (requested by nodes 'RECURSIVE_PKG:rootedPath=[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head], excludedPaths=<omitted>)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: relativePath 'C:/jenkins/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/windows-x86_64/.git/HEAD' is absolute, but it's not under root 'C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:56)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:73)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPathMaybeUnderRoot(RootedPath.java:83)
	at com.google.devtools.build.lib.skyframe.FileFunction.getSymlinkTargetRootedPath(FileFunction.java:176)
	at com.google.devtools.build.lib.skyframe.FileFunction.compute(FileFunction.java:101)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
```

seems like the problem is caused by case sensitive filenames.

**Comment by laszlocsomor** [comment]
This was fixed by https://github.com/bazelbuild/bazel/commit/0768f3e444a121c5c8e8e0bd0bb98772fab0e0e2
