### ISSUE TITLE
Bazel-tests are not building on Windows / failing on some other platforms

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2572]
They seem to fail for different reasons on Darwin at HEAD-jdk7 for 2 consecutive builds:

First build:
`//src/tools/singlejar:zip64_test                                        TIMEOUT in 1 out of 2 in 324.3s`

Second build:
```
FAIL: //src/test/java/com/google/devtools/build/lib:foundations_test
1) throwsFilePermissionException(com.google.devtools.build.lib.unix.NativePosixFilesTest)
org.junit.ComparisonFailure: <java.io.FileNotFoundException: /bin (No such file or directory)> does not have message </bin (Read-only file system)> expected:</bin ([Read-only file system])> but was:</bin ([No such file or directory])>
	at com.google.common.truth.Platform.comparisonFailure(Platform.java:126)
	at com.google.common.truth.Truth$1.failComparing(Truth.java:72)
	at com.google.common.truth.ThrowableSubject$1.failComparing(ThrowableSubject.java:66)
	at com.google.common.truth.ThrowableSubject.hasMessage(ThrowableSubject.java:38)
	at com.google.devtools.build.lib.unix.NativePosixFilesTest.throwsFilePermissionException(NativePosixFilesTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:146)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
Caused by: java.io.FileNotFoundException: /bin (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.chmod(Native Method)
	at com.google.devtools.build.lib.unix.NativePosixFiles.setWritable(NativePosixFiles.java:97)
	at com.google.devtools.build.lib.unix.NativePosixFilesTest.throwsFilePermissionException(NativePosixFilesTest.java:106)
	... 32 more
```

They also fail with timeouts on linux/ubuntu

Bazel-tests fail to build on Windows at HEAD and latest:
```
ERROR: Skipping '//src/test/native:all_tests,': no such target '//src/test/native:all_tests,': target 'all_tests,' not declared in package 'src/test/native' (did you mean 'all_tests'?) defined by C:/jenkins/workspace/bazel-tests/BAZEL_VERSION/latest/PLATFORM_NAME/windows-x86_64/src/test/native/BUILD.
ERROR: Skipping '//src/test/native:all_tests,': no such target '//src/test/native:all_tests,': target 'all_tests,' not declared in package 'src/test/native' (did you mean 'all_tests'?) defined by C:/jenkins/workspace/bazel-tests/BAZEL_VERSION/latest/PLATFORM_NAME/windows-x86_64/src/test/native/BUILD.
WARNING: Target pattern parsing failed. Continuing anyway.
```

```
ERROR: C:/jenkins/workspace/bazel-tests/bazel_version/head/platform_name/windows-x86_64/BUILD:54:1: Couldn't build file bazel-srcs.tar: null failed: build_tar failed: error executing command 
  cd C:/bazel_ci/temp/_bazel_system/vzgwz1gf/execroot/windows-x86_64
bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/vc_14_0_x64-fastbuild/bin/bazel-srcs.args: java.io.IOException: CreateProcess(): %1 is not a valid Win32 application.
.
```

**Comment by iirina** [comment]
I am not successful bisecting this. It fails for every commit it tries.  Also #2538 makes it even harder, as bazel cannot do the cleanup after executing the tests.

Besides the errors on Jenkins, I also get

```
ERROR: C:/Users/elenairina/bazel/src/BUILD:341:1: Couldn't build file src/derived_java_srcs.zip: Executing genrule //src:derived_java_srcs failed: bash.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_elenairina/o65kLhlk/execroot/bazel
  SET PATH=C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; src/combine_derived_java_srcs.sh bazel-out/vc_14_0_x64-fastbuild/genfiles/src/derived_java_srcs.zip bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libcommand_server_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libremote_protocol_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libbuild_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libdash_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libdeps_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libjava_compilation_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libcrosstool_config_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libextra_actions_base_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libintellij_ide_info_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libpackage_manifest_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libtest_status_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libplmerge_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libbundlemerge_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libxcodegen_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libworker_protocol_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libinvocation_policy_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libandroid_deploy_info_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libapk_manifest_java_proto_srcjar.srcjar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/libbuild_event_stream_java_proto_srcjar.srcjar: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/combine_derived_java_srcs.sh: line 33: jar: command not found
ERROR: C:/Users/elenairina/bazel/src/main/java/com/google/devtools/build/lib/BUILD:477:1: Couldn't build file src/main/java/com/google/devtools/build/lib/libbuild-base-ijar.jar: Extracting interface //src/main/java/com/google/devtools/build/lib:build-base failed: ijar.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_elenairina/o65kLhlk/execroot/bazel
  SET PATH=C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl
  external/bazel_tools/tools/jdk/ijar/ijar.exe bazel-out/vc_14_0_x64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/libbuild-base.jar bazel-out/vc_14_0_x64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/libbuild-base-ijar.jar: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 35584.
CreateFile(): Access is denied.
```

which seems to also be related to #2538.
