### ISSUE TITLE
Windows, native: uncaught exception in java.util.Logging

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2576]
If you build Bazel with `--cpu=x64_windows_msvc` and run with `--batch --output_user_base=c:\tmp3`, you'll see an uncaught exception:
```
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.InvalidPathException: Illegal char <      > at index 2: c:        mp3l90hcebl\java.log.lck
java.nio.file.InvalidPathException: Illegal char <      > at index 2: c:        mp3l90hcebl\java.log.lck
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:453)
        at java.util.logging.FileHandler.<init>(FileHandler.java:263)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.logging.LogManager$5.run(LogManager.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1777)
        at java.util.logging.Logger.log(Logger.java:735)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.info(Logger.java:1490)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.logVersionInfo(BlazeVersionInfo.java:65)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.setBuildInfo(BlazeVersionInfo.java:80)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

The problem is in [`startup_options.cc`](https://github.com/bazelbuild/bazel/blob/10390f2dac277baeaaff48fbfd663ce687ec92e1/src/main/cpp/startup_options.cc#L415-L416): we write `java.util.logging.FileHandler.pattern=c:\tmp3\l90hcebl/java.log` into the `javalog.properties` file and the `\t` after `c:` is interpreted as a tab character. You can see that rendered in the error message too.

**Comment by laszlocsomor** [comment]
@philwo : FYI
