### ISSUE TITLE
Bazel coverage failing: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel#2577]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at com.google.testing.coverage.JacocoCoverageRunner.analyzeBranch(JacocoCoverageRunner.java:138)
	at com.google.testing.coverage.JacocoCoverageRunner.create(JacocoCoverageRunner.java:84)
	at com.google.testing.coverage.JacocoCoverageRunner$2.run(JacocoCoverageRunner.java:258)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

```
### If possible, provide a minimal example to reproduce the problem:

Run bazel coverage on a passing java test.

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
```
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

release 0.4.4

```

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by iirina** [comment]
Can you copy/paste the command you run and describe your project?

**Comment by prestonvanloon** [comment]
I ran `bazel coverage --test_output=streamed path/to:testTarget`

I'm not sure how to describe the project. 
It has several maven jar dependencies. It uses [rules_protobuf](https://github.com/pubref/rules_protobuf) to implement a gRPC server. 

The test is mocking a few things and testing certain http calls would have happened.

**Comment by iirina** [comment]
@hermione521 can you take a look at the error?

**Comment by hermione521** [comment]
srcjar is not supported in coverage now. But it's on my list! Sorry for the inconvenience.

**Comment by prestonvanloon** [comment]
So this is related to #2528 ?

**Comment by hermione521** [comment]
@prestonvanloon yes, it is.
