### ISSUE TITLE
serve-docs.sh broken by shell highlighting

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#2587]
Commit fa65195662cde0ea9f7c8ff4d07874b0d53dd0be added a section with shell highlighting, but shell highlighting isn't supported by the version of jekyll we're using.

Error:
```
Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'versions/master/docs/skylark/concepts.md':
                    Traceback (most recent call last): File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start res = self.get_data(method, lexer, args, kwargs, text) File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts)) File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text lexer = self.return_lexer(lexer, args, kwargs, code) File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer return lexers.get_lexer_by_name(lexer, **inputs) File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name raise ClassNotFound('no lexer for alias %r found' % _alias) ClassNotFound: no lexer for alias 'shell' found 
jekyll 2.5.3 | Error:  Traceback (most recent call last):
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start
    res = self.get_data(method, lexer, args, kwargs, text)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data
    res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text
    lexer = self.return_lexer(lexer, args, kwargs, code)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer
    return lexers.get_lexer_by_name(lexer, **inputs)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
ClassNotFound: no lexer for alias 'shell' found
```

**Comment by aj-michael** [comment]
FWIW that commit just moved the shell highlighting. c1641b8f953120dc04ac562b1529e8b0d775da25 introduced it. (I was in the process of filing an issue about c1641b8f953120dc04ac562b1529e8b0d775da25 when I saw this issue)

**Comment by katre** [comment]
The downside of blame, thanks.

I've sent https://bazel-review.googlesource.com/c/9090/ to fix it by just removing the "shell".
