### ISSUE TITLE
PathFragment comparison is case-sensitive on Windows (Causing failure of TensorFlow build with Bazel@HEAD)

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2613]
I noticed this error from TensorFlow job http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/676/console

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE:[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head]' (requested by nodes 'RECURSIVE_PKG:rootedPath=[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head], excludedPaths=<omitted>)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: relativePath 'C:/jenkins/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/windows-x86_64/.git/HEAD' is absolute, but it's not under root 'C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:56)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:73)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPathMaybeUnderRoot(RootedPath.java:83)
	at com.google.devtools.build.lib.skyframe.FileFunction.getSymlinkTargetRootedPath(FileFunction.java:176)
	at com.google.devtools.build.lib.skyframe.FileFunction.compute(FileFunction.java:101)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE:[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head]' (requested by nodes 'RECURSIVE_PKG:rootedPath=[C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64]/[tensorflow/tools/git/gen/head], excludedPaths=<omitted>)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: relativePath 'C:/jenkins/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/windows-x86_64/.git/HEAD' is absolute, but it's not under root 'C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:56)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:73)
	at com.google.devtools.build.lib.vfs.RootedPath.toRootedPathMaybeUnderRoot(RootedPath.java:83)
	at com.google.devtools.build.lib.skyframe.FileFunction.getSymlinkTargetRootedPath(FileFunction.java:176)
	at com.google.devtools.build.lib.skyframe.FileFunction.compute(FileFunction.java:101)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
```

I believe this error is triggered by 9b75b684655e31ca0f5cb5ed08697e936d4d5c7e, but the real problem is in [RootedPath.java](https://github.com/bazelbuild/bazel/blob/e08f11c37cfe349c8b687d97100bf4a3af21719a/src/main/java/com/google/devtools/build/lib/vfs/RootedPath.java#L57). PathFragment comparison should be case-insensitive on Windows.

//cc @laszlocsomor

**Comment by laszlocsomor** [comment]
Yes, it seems like we don't ignore the path casing. Look:

```
Caused by: java.lang.IllegalArgumentException: relativePath
'C:/jenkins/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/windows-x86_64/.git/HEAD'
is absolute, but it's not under root
'C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64'
```

I'll fix it.

**Comment by meteorcloudy** [comment]
Thanks!!

**Comment by laszlocsomor** [comment]
Do you have a simple repro case for this?

**Comment by meteorcloudy** [comment]
Hmm.. I don't a simple repo yet.. But the cause sounds right to me.

**Comment by laszlocsomor** [comment]
Never mind! I just wrote a simple test for it and can repro the same error. Working on a fix.

**Comment by laszlocsomor** [comment]
And yes, you were right from the start, it is because of the PathFragment comparison being case-sensitive. I got mislead by the fact that Path comparison (and Path.startsWith) on the other hand is aware of case-(in)sensitivity.

**Comment by meteorcloudy** [comment]
I see, but not sure how to fix it..  How can we know it's a Windows path?

**Comment by laszlocsomor** [comment]
We can convert the Path segments to lower-case in Path.toFragment if the filesystem is case-insensitive. I have a change for that, about to send it out.

**Comment by laszlocsomor** [comment]
https://bazel-review.googlesource.com/c/9124/

**Comment by laszlocsomor** [comment]
Imported.
