### ISSUE TITLE
Intermittent build failures

### ISSUE THREAD

**Issue by simonhorlick** [bazelbuild/bazel#2621]
### Description of the problem:

Occasionally (once per day, or so) I see the following exception thrown by Bazel when I run a build. Unfortunately I haven't been able to narrow down the cause, and re-running the build always completes successfully.

```
[simon@Simons-MacBook 12:26 remote-system-manager (master)]$ bazel build ...
Unhandled exception thrown during build; message: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24]], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]]], elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=1268479874, value=null, lastChangedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, lastEvaluatedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, directDeps=GroupedList{elements=[], size=0}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=BuildingState{hash=1456849658, signaledDeps/evaluating state=0, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}}}
INFO: Elapsed time: 13.233s
java.lang.IllegalStateException: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24]], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]]], elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=1268479874, value=null, lastChangedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, lastEvaluatedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, directDeps=GroupedList{elements=[], size=0}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=BuildingState{hash=1456849658, signaledDeps/evaluating state=0, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}}}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:458)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24]], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], [DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]]], elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 0, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 1, WORKSPACE_FILE:[/Users/simon/projects/ngi/remote-system-manager]/[WORKSPACE], 2, PRECOMPUTED:blaze_directories, ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[platforms], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-24/google_apis], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-wear], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/android-tv], DIRECTORY_LISTING:[/Users/simon/Library/Android/sdk]/[system-images/android-25/google_apis]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=1268479874, value=null, lastChangedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, lastEvaluatedVersion=com.google.devtools.build.skyframe.MinimalVersion@78d4c5b9, directDeps=GroupedList{elements=[], size=0}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=BuildingState{hash=1456849658, signaledDeps/evaluating state=0, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}}}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:458)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### If possible, provide a minimal example to reproduce the problem:

Not able to reliably reproduce.

### Environment info
* Operating System: macOS Sierra

* Bazel version (output of `bazel info release`): 

Built from source of bazel 0.4.5-rc2 (56a628abcb9ba3a904438bf2f34907f12e3513ab)

**Comment by hermione521** [comment]
Thank you for reporting.
Does it only happen with android project? And does it open happen with 0.4.5-rc2? Thanks.

**Comment by simonhorlick** [comment]
I'm not sure, the only project I've used recently has android targets. It's 0.4.5-rc2 (from source, using the commit above). I've seen it only twice during the whole day today, so it's quite hard to reproduce.

**Comment by hermione521** [comment]
Then it will be hard to fix.. @ahumesky Add android person in case he knows.

**Comment by ahumesky** [comment]
we've made a number of changes to the android_sdk_repository rule recently, adam can you take a look?

**Comment by aj-michael** [comment]
I'll take a look this week, but I suspect the culprit is in either 06072c557290b97cb2d2e4fd255b647a9208cb5c or 9d88394848fa6742513d85fa5f892ae1702d015e.

@damienmg Can you confirm that adding the dep on the ANDROID_HOME environment variable did not cause this?

**Comment by damienmg** [comment]
@aj-michael I can confirm it is not 9d88394 but 06072c5 is the likely culprit. More precisely look at https://bazel-review.googlesource.com/c/8137/ which fix similar issues in AndroidNdkRepository.

**Comment by aj-michael** [comment]
@simonhorlick in the android_sdk_repository rule in your WORKSPACE file, are you setting the path attribute or not setting it (which should read from $ANDROID_HOME)?

**Comment by damienmg** [comment]
I wasn't able to repro on the android tutorial, would love to have a good repro.

**Comment by aj-michael** [comment]
I thought I would be able to find a missing null check in 06072c5, but I have not found one. It would be nice if skyframe reported which dependency was null instead of just the GroupedListHelper.

**Comment by damienmg** [comment]
Humm how can we request the directoryListing if we do not have the actionenvvariable resolved?

**Comment by damienmg** [comment]
Ok I think I have the fix, that's stupid me did something incorrect.

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/blob/ed7795234ca7ccd2567007f2c502f853cd947e50/src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidSdkRepositoryFunction.java#L85 does not check for the return value (see the correct code here: https://github.com/bazelbuild/bazel/blob/ed7795234ca7ccd2567007f2c502f853cd947e50/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryFunction.java#L75)

**Comment by aj-michael** [comment]
Ooooh, nice catch :+1: do you have any idea how to write a test for this? I still haven't been able to repro the error.

**Comment by damienmg** [comment]
I have 0 idea how to repro. But I once suggested to ulf that we write a fuzzer to try to set skykeys to null randomly to see if the function behave correctly in all the cases.

**Comment by aj-michael** [comment]
@serynth pointed me towards https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/analysis/BuildViewTest.java#L795 which seems to force the order of skyframe evaluation in the buildview analysis phase. Perhaps we could do something similar?

**Comment by aj-michael** [comment]
OK, I have a reliable repro case (this was obnoxious to track down)

```shell
$ cat WORKSPACE
android_sdk_repository(
    name = "androidsdk",
    api_level = 25,
    build_tools_version = "25.0.1",
    path = "/my/sdk",
)

$ tree -L 2 /my/sdk
/my/sdk
├── build-tools
│   └── 25.0.1
├── platforms
│   └── android-25
└── tools
    ├── android
    └── <snipped for brevity>

$ ANDROID_HOME=/foo bazel build @androidsdk//:files
INFO: Found 1 target...
Target @androidsdk//:files up-to-date (nothing to build)
INFO: Elapsed time: 2.265s, Critical Path: 0.00s

$ sed -i 's/path/#path/g' WORKSPACE

$ ANDROID_HOME=/bar bazel build @androidsdk//:files
ERROR: no such package '@androidsdk//': /bar (No such file or directory).
INFO: Elapsed time: 0.254s

$ ANDROID_HOME=/my/sdk bazel build @androidsdk//:files
Unhandled exception thrown during build; message: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], elements=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=65498421, value=null, lastChangedVersion=IntVersion: 10, lastEvaluatedVersion=IntVersion: 10, directDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories], size=3}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=FullDirtyBuildingState{hash=2107083214, signaledDeps/evaluating state=3, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}, dirtyState=REBUILDING, dirtyDirectDepIndex=4, lastBuildDirectDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories, ERROR_TRANSIENCE:ERROR_TRANSIENCE], size=4}, lastBuildValue=Error: <ErrorInfo exception=java.io.FileNotFoundException: /bar (No such file or directory) rootCauses={REPOSITORY_DIRECTORY:@androidsdk} cycles=[]>}}
INFO: Elapsed time: 0.184s
java.lang.IllegalStateException: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], elements=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=65498421, value=null, lastChangedVersion=IntVersion: 10, lastEvaluatedVersion=IntVersion: 10, directDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories], size=3}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=FullDirtyBuildingState{hash=2107083214, signaledDeps/evaluating state=3, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}, dirtyState=REBUILDING, dirtyDirectDepIndex=4, lastBuildDirectDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories, ERROR_TRANSIENCE:ERROR_TRANSIENCE], size=4}, lastBuildValue=Error: <ErrorInfo exception=java.io.FileNotFoundException: /bar (No such file or directory) rootCauses={REPOSITORY_DIRECTORY:@androidsdk} cycles=[]>}}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:465)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Evaluation of REPOSITORY_DIRECTORY:@androidsdk returned non-null value but requested dependencies that weren't computed yet (one of GroupedListHelper{groupedList=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], elements=[ACTION_ENVIRONMENT_VARIABLE:ANDROID_HOME, DIRECTORY_LISTING:[/my/sdk]/[platforms]], currentGroup=null}), NodeEntry: InMemoryNodeEntry{identity=65498421, value=null, lastChangedVersion=IntVersion: 10, lastEvaluatedVersion=IntVersion: 10, directDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories], size=3}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, buildingState=FullDirtyBuildingState{hash=2107083214, signaledDeps/evaluating state=3, reverseDepsToSignal=ReverseDeps{reverseDeps=REPOSITORY:@androidsdk, singleReverseDep=true, dataToConsolidate=null}, dirtyState=REBUILDING, dirtyDirectDepIndex=4, lastBuildDirectDeps=GroupedList{elements=[PACKAGE_LOOKUP:external, WORKSPACE_FILE:[/usr/local/google/home/ajmichael/playgrounds/yy]/[WORKSPACE], 0, PRECOMPUTED:blaze_directories, ERROR_TRANSIENCE:ERROR_TRANSIENCE], size=4}, lastBuildValue=Error: <ErrorInfo exception=java.io.FileNotFoundException: /bar (No such file or directory) rootCauses={REPOSITORY_DIRECTORY:@androidsdk} cycles=[]>}}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:465)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This repro works whether or not there are system-images and support libraries in the SDK. I will now attempt to confirm that https://bazel-review.googlesource.com/c/9213/ fixes this issue.

**Comment by aj-michael** [comment]
I've confirmed that https://bazel-review.googlesource.com/c/9213 fixes my repro case :rocket: I spent some time trying to figure out how to do this in a unit test, but I think I'm going to give up and add this to android_integration_test.sh.

**Comment by simonhorlick** [comment]
@aj-michael: For your question earlier in the thread, I'm using the path attribute, but I'd love to switch to the environment variable. It makes it way easier to onboard new developers. I'm currently trying out your patch - thanks a lot!
