### ISSUE TITLE
bazel-tests broken on Darwin with JDK7

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#2630]
CI link: http://ci.bazel.io/job/bazel-tests/603/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/
And this [commit](https://github.com/bazelbuild/bazel/commit/0785cbb672357d950e0c045770c4567df9fbdc43) caused it.

**Comment by cushon** [comment]
Are you sure 0785cbb672357d950e0c045770c4567df9fbdc43 is the culprit?

The interesting part of the failure is:

```
Caused by: java.lang.VerifyError: class com.google.devtools.build.lib.query2.engine.SynchronizedDelegatingOutputFormatterCallback overrides final method process.(Ljava/lang/Iterable;)V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

the change that introduced `SynchronizedDelegatingOutputFormatterCallback` has been rolled back: b869e584641521dc063f0589d7ce6a850ffc0b61

**Comment by hermione521** [comment]
Well that breakage goes away now. Only //src/tools/singlejar:output_jar_simple_test is failing.
Reassign to current sheriff for further investigation.

**Comment by vladmos** [comment]
Fixed now.
