### ISSUE TITLE
generate_workspace failed with "Exception in thread "main" java.lang.UnsatisfiedLinkError: no unix in java.library.path"

### ISSUE THREAD

**Issue by rosun82** [bazelbuild/bazel#2654]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

src/tools/generate_workspace/generate_workspace failed with

Exception in thread "main" java.lang.UnsatisfiedLinkError: no unix in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.NativePosixFiles.<clinit>(NativePosixFiles.java:136)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:172)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:163)
	at com.google.devtools.build.lib.unix.UnixFileSystem.getFileSize(UnixFileSystem.java:355)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:954)
	at com.google.devtools.build.lib.syntax.ParserInputSource.create(ParserInputSource.java:48)
	at com.google.devtools.build.workspace.WorkspaceResolver.parse(WorkspaceResolver.java:88)
	at com.google.devtools.build.workspace.GenerateWorkspace.generateFromWorkspace(GenerateWorkspace.java:105)
	at com.google.devtools.build.workspace.GenerateWorkspace.main(GenerateWorkspace.java:62)

### Environment info
* Operating System:

Ubuntu 16.10 on AWS EC2

* Bazel version (output of `bazel info release`):

Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
Assigning to @kchodorow for investigation

**Comment by buchgr** [comment]
I am getting the same error. It works for me when only specifying `--maven_project`, but adding `--bazel_project` crashes.

```
$ bazel-bin/src/tools/generate_workspace/generate_workspace --maven_project=../google-cloud-java/google-cloud-spanner/ --maven_project=../google-cloud-java/google-cloud-core --bazel_project=../grpc-service-demo/
Exception in thread "main" java.lang.UnsatisfiedLinkError: no unix in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.NativePosixFiles.<clinit>(NativePosixFiles.java:136)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.statInternal(UnixFileSystem.java:169)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.stat(UnixFileSystem.java:160)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.getFileSize(UnixFileSystem.java:352)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:954)
	at com.google.devtools.build.lib.syntax.ParserInputSource.create(ParserInputSource.java:48)
	at com.google.devtools.build.workspace.WorkspaceResolver.parse(WorkspaceResolver.java:88)
	at com.google.devtools.build.workspace.GenerateWorkspace.generateFromWorkspace(GenerateWorkspace.java:105)
	at com.google.devtools.build.workspace.GenerateWorkspace.main(GenerateWorkspace.java:62)
```

**Comment by kchodorow** [comment]
Right now `generate_workspace` is depending on Bazel's native file system implementation, which obviously isn't being linked in properly. I'm working on extracting `generate_workspace` to its own project where it uses standard java.io filesystem ops, will update this when that's complete.

**Comment by jin** [comment]
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.
