### ISSUE TITLE
CI is broken due to IllegalArgumentException

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2698]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/651/console

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Testing //scripts/release:release_test (shard 1 of 2)' (TestRunner[[Artifact:[[/home/ci/.cache/bazel/_bazel_ci/a761298a0949227106f79c62c3bebb6e/execroot/linux-x86_64]bazel-out/local-fastbuild/internal]_middlemen/scripts_Srelease_Srelease_Utest-runfiles, Artifact:[/home/ci/.cache/bazel/_bazel_ci/a761298a0949227106f79c62c3bebb6e[source]]external/bazel_tools/tools/test/test-setup.sh] -> [Artifact:[[/home/ci/.cache/bazel/_bazel_ci/a761298a0949227106f79c62c3bebb6e/execroot/linux-x86_64]bazel-out/local-fastbuild/testlogs]scripts/release/release_test/shard_1_of_2/test.log, Artifact:[[/home/ci/.cache/bazel/_bazel_ci/a761298a0949227106f79c62c3bebb6e/execroot/linux-x86_64]bazel-out/local-fastbuild/testlogs]scripts/release/release_test/shard_1_of_2/test.cache_status]])' (requested by nodes 'ARTIFACT:scripts/release/release_test/shard_1_of_2/test.cache_status //scripts/release:release_test 5531140bd7273c20a803b18bf41679a4 (342984972 2052444596)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:455)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:33)
	at com.google.devtools.build.lib.sandbox.SymlinkedExecRoot.createParentDirectoriesForInputs(SymlinkedExecRoot.java:95)
	at com.google.devtools.build.lib.sandbox.SymlinkedExecRoot.createFileSystem(SymlinkedExecRoot.java:50)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.actuallyExec(LinuxSandboxedStrategy.java:139)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:117)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:95)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTest(StandaloneTestStrategy.java:306)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:260)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:137)
	at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:42)
	at com.google.devtools.build.lib.rules.test.TestRunnerAction.execute(TestRunnerAction.java:657)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:706)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:604)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:566)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:376)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:196)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:381)
	... 4 more
```

@ulfjack Do you think it's caused by 59180a4ea66b1395b5b85defd732859ecae919ea? It's weird that I cannot reproduce the failure on my local machine.

**Comment by ulfjack** [comment]
I tried to make sure that the change is a no-op, but it's possible I've missed something. I don't see any obvious connection.
