### ISSUE TITLE
Windows: Bazel doesn't take python3_path when using --host_force_python=py3

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2752]
```
ERROR: C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/external/llvm/BUILD:183:1: Executing genrule @llvm//:abi_breaking_gen failed: bash.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/execroot/tensorflow
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\tools\msys64\usr\bin;C:\Users\Adriano\AppData\Local\Programs\Python\Python35\;C:\bazel\;c;C:\tools\msys64\Program Files\Java\jdk1.8.0_112\;C:\tools\msys64\home\Adriano\cmake-3.6.2-win32-x86\bin\;C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl;.
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/llvm/expand_cmake_vars "HAVE_DIRENT_H=1" "HAVE_DLFCN_H=1" "HAVE_ERRNO_H=1" "HAVE_EXECINFO_H=1" "HAVE_FCNTL_H=1" "HAVE_INTTYPES_H=1" "HAVE_PTHREAD_H=1" "HAVE_SIGNAL_H=1" "HAVE_STDINT_H=1" "HAVE_SYS_IOCTL_H=1" "HAVE_SYS_MMAN_H=1" "HAVE_SYS_PARAM_H=1" "HAVE_SYS_RESOURCE_H=1" "HAVE_SYS_STAT_H=1" "HAVE_SYS_TIME_H=1" "HAVE_SYS_TYPES_H=1" "HAVE_TERMIOS_H=1" "HAVE_UNISTD_H=1" "HAVE_ZLIB_H=1" "HAVE_BACKTRACE=1" "HAVE_DLOPEN=1" "HAVE_FUTIMES=1" "HAVE_GETCWD=1" "HAVE_GETPAGESIZE=1" "HAVE_GETRLIMIT=1" "HAVE_GETRUSAGE=1" "HAVE_GETTIMEOFDAY=1" "HAVE_INT64_T=1" "HAVE_ISATTY=1" "HAVE_LIBEDIT=1" "HAVE_LIBPTHREAD=1" "HAVE_LIBZ=1" "HAVE_MKDTEMP=1" "HAVE_MKSTEMP=1" "HAVE_MKTEMP=1" "HAVE_PREAD=1" "HAVE_PTHREAD_GETSPECIFIC=1" "HAVE_PTHREAD_MUTEX_LOCK=1" "HAVE_PTHREAD_RWLOCK_INIT=1" "HAVE_REALPATH=1" "HAVE_SBRK=1" "HAVE_SETENV=1" "HAVE_SETRLIMIT=1" "HAVE_SIGALTSTACK=1" "HAVE_STRERROR=1" "HAVE_STRERROR_R=1" "HAVE_STRTOLL=1" "HAVE_SYSCONF=1" "HAVE_UINT64_T=1" "HAVE__UNWIND_BACKTRACE=1" "ENABLE_BACKTRACES=1" "LLVM_BINDIR=/dev/null" "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=0" "LLVM_ENABLE_ABI_BREAKING_CHECKS=0" "LLVM_ENABLE_THREADS=1" "LLVM_ENABLE_ZLIB=1" "LLVM_HAS_ATOMICS=1" "LLVM_INCLUDEDIR=/dev/null" "LLVM_INFODIR=/dev/null" "LLVM_MANDIR=/dev/null" "LLVM_NATIVE_TARGET=1" "LLVM_NATIVE_TARGETINFO=1" "LLVM_NATIVE_TARGETMC=1" "LLVM_NATIVE_ASMPRINTER=1" "LLVM_NATIVE_ASMPARSER=1" "LLVM_NATIVE_DISASSEMBLER=1" "LLVM_ON_UNIX=1" "LLVM_PREFIX=/dev/null" "LLVM_VERSION_MAJOR=0" "LLVM_VERSION_MINOR=0" "LLVM_VERSION_PATCH=0" "LTDL_SHLIB_EXT=.so" "PACKAGE_NAME=llvm" "PACKAGE_STRING=llvm tensorflow-trunk" "PACKAGE_VERSION=tensorflow-trunk" "RETSIGTYPE=void" "LLVM_HOST_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_NATIVE_ARCH=X86" "HAVE_MALLOC_H=1" "HAVE_LINK_H=1" "HAVE_MALLINFO=1" "HAVE_FUTIMENS=1"< external/llvm/include/llvm/Config/abi-breaking.h.cmake > bazel-out/host/genfiles/external/llvm/include/llvm/Config/abi-breaking.h: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
Traceback (most recent call last):
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 173, in <module>
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 153, in Main
AssertionError: Could not find python binary: python3.exe
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 194.868s, Critical Path: 22.57s
FAILED: Build did NOT complete successfully
```

A simple repro for this:
```
BUILD:
py_binary(
    name = "bin",
    srcs = ["bin.py"],
    srcs_version = "PY2AND3",
)

genrule(
    name = "gen",
    outs = ["output.txt"],
    cmd = "$(location :bin) > $@",
    tools = [":bin"]
)

bin.py:
print("Hello world")

tools/bazel.rc:
build --force_python=py3
build --host_force_python=py3
build --python3_path="C:/Program Files/Anaconda3/python.exe"
```
Then try to build `:gen`, you'll get:
```
pcloudy@pcloudy0-w MSYS ~/workspace/test_dir
$ bazel build :gen
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
ERROR: C:/tools/msys64/home/pcloudy/workspace/test_dir/BUILD:8:1: Executing genrule //:gen failed: bash failed: error executing command C:/tools/msys64/usr/bin/bash -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/bin > bazel-out/msvc_x64-py3-fastbuild/genfiles/output.txt: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-out\host\bin\bin\__main__.py", line 173, in <module>
  File "bazel-out\host\bin\bin\__main__.py", line 153, in Main
AssertionError: Could not find python binary: python3.exe
Target //:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 1.354s, Critical Path: 0.90s

```

**Comment by meteorcloudy** [comment]
Just noticed this also happens on Linux, but there is usually `python3` available under `/usr/bin`.
But it is not intended to ignore the python3_path for host build, right? @damienmg
