### ISSUE TITLE
Crash in implicit outputs string interpolation

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2766]
For example, I had: `outputs = {'b' : 'b%{testonly}'}` and got:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes 'TARGET_PATTERN://:foo')
INFO: Elapsed time: 0.127s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes 'TARGET_PATTERN://:foo')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Don't know how to handle testonly : boolean
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.attributeValues(ImplicitOutputsFunction.java:327)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.access$000(ImplicitOutputsFunction.java:52)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$1.get(ImplicitOutputsFunction.java:170)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:404)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:377)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$3.getImplicitOutputs(ImplicitOutputsFunction.java:216)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunctionWithMap.calculateOutputs(ImplicitOutputsFunction.java:133)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunction.getImplicitOutputs(ImplicitOutputsFunction.java:65)
	at com.google.devtools.build.lib.packages.Rule.populateImplicitOutputFiles(Rule.java:512)
	at com.google.devtools.build.lib.packages.Rule.populateOutputFiles(Rule.java:478)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1353)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:129)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:175)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:216)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:654)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:735)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:721)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:698)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:197)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1728)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1344)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:504)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes 'TARGET_PATTERN://:foo')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:438)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Don't know how to handle testonly : boolean
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.attributeValues(ImplicitOutputsFunction.java:327)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.access$000(ImplicitOutputsFunction.java:52)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$1.get(ImplicitOutputsFunction.java:170)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:404)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:377)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$3.getImplicitOutputs(ImplicitOutputsFunction.java:216)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunctionWithMap.calculateOutputs(ImplicitOutputsFunction.java:133)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunction.getImplicitOutputs(ImplicitOutputsFunction.java:65)
	at com.google.devtools.build.lib.packages.Rule.populateImplicitOutputFiles(Rule.java:512)
	at com.google.devtools.build.lib.packages.Rule.populateOutputFiles(Rule.java:478)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1353)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:129)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:175)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:216)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:654)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:735)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:721)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:698)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:197)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1728)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1344)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:504)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:373)
	... 4 more
```

Full rule for ease of testing:

```
def _rule_impl(ctx):
  ctx.action(
      outputs = [ctx.outputs.b],
      command = "touch %s" % ctx.outputs.b.path)

my_rule = rule(
    implementation = _rule_impl,
    outputs = {'b' : 'b%{testonly}'}
)
```

It doesn't have to work, but it should probably print something nicer.

**Comment by brandjon** [comment]
Still a crash bug. Low priority because we'd like to remove implicit outputs.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
