### ISSUE TITLE
swift_library rule error when depending on external repository

### ISSUE THREAD

**Issue by ryanfitz** [bazelbuild/bazel#2789]
I'm attempting to build a swift library which depends on an external git repo. I have the external repo building successfully, but when I attempt to build the swift_library target I get the following error:

```
ERROR: /Users/fitz/Code/bazel-examples/cocoapods/BUILD:7:1: in swift_library rule //:main:
Traceback (most recent call last):
        File "/Users/fitz/Code/bazel-examples/cocoapods/BUILD", line 7
                swift_library(name = 'main')
        File "/private/var/tmp/_bazel_fitz/b64302952b2e328b5bdfdbe27f9883ff/external/bazel_tools/tools/build_defs/apple/swift.bzl", line 334, in _swift_library_impl
                _validate_rule_and_deps(ctx)
        File "/private/var/tmp/_bazel_fitz/b64302952b2e328b5bdfdbe27f9883ff/external/bazel_tools/tools/build_defs/apple/swift.bzl", line 172, in _validate_rule_and_deps
                fail(name_error_str % dep.label)
Error in target '@pelotare_repo//:pelotare-lib', Swift target and its dependencies' names can only contain characters in [a-zA-Z0-9_].
ERROR: Analysis of target '//:main' failed; build aborted.
INFO: Elapsed time: 0.097s
```

To confirm I had the external repo setup correctly, I testing building an objc_library which depends on the same external repo. The objc_library target built without issue so this appears to be a specific issue with the swift_library rule.

#### BUILD

```
swift_library(
  name = "main",
  srcs = glob(["*.swift"]),
  deps = ["//external:pelotare"]
)

objc_library(
  name = "objc",
  srcs = glob(["*.m"]),
  hdrs = glob(["*.h"]),
  deps = ["//external:pelotare"]
)
```

#### WORKSPACE
```
bind(name = "xcrunwrapper", actual = "@bazel_tools//tools/objc:xcrunwrapper")

load('@bazel_tools//tools/build_defs/repo:git.bzl', 'new_git_repository')

bind(
  name = "pelotare",
  actual = "@pelotare_repo//:pelotare-lib",
)

new_git_repository(
  name = "pelotare_repo",
  remote = "git@github.com:pelotoncycle/Pelotare.git",
  tag = "0.5.3",
  build_file = "BUILD.pelotare"
)
```

### Environment info
OSX 10.12.3 
```
Bazel version (output of `bazel info release`):
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```

**Comment by sergiocampama** [comment]
Well, the error message relates to the name of the target. "pelotare-lib" contains a "-", which is not allowed in the "[a-zA-Z0-9_]"  character set. Can you try to rename "pelotare-lib" to "pelotare_lib"?

**Comment by ryanfitz** [comment]
@sergiocampama switching to underscored worked. Thanks for the help, I thought it was the "@" symbol needed for the external repo reference that was causing it to fail.
