### ISSUE TITLE
Null Pointer Exception while running Objective C Extra Action on OS X

### ISSUE THREAD

**Issue by salguarnieri** [bazelbuild/bazel#2806]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:

I get an error running https://github.com/google/kythe/blob/master/kythe/cxx/extractor/testdata/run_objc_bazel_extraction.sh

To set up a kythe repo: http://kythe.io/getting-started

```
~/Groksrc/kythe/kythe/cxx/extractor/testdata (git)-[ext ]/kythe/cxx/extractor/testdata  sh ./run_objc_bazel_extraction.sh
INFO: Found 1 target...
ERROR: /Users/salguarnieri/Groksrc/kythe/kythe/cxx/extractor/BUILD:186:1: Creating runfiles tree bazel-out/host/bin/kythe/cxx/extractor/objc_extractor_bazel.runfiles [for host] failed: build-runfiles failed: error executing command 
 ...
Target //kythe/cxx/extractor/testdata:objc_lib failed to build
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Writing file extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa' (FileWrite[[] -> [Artifact:[[/private/var/tmp/_bazel_salguarnieri/ca16ea5a435d8ac2288f379cdf092007/execroot/kythe]bazel-out/apl-ios_x86_64-fastbuild]extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa]])' (requested by nodes 'ARTIFACT:extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa //kythe/cxx/extractor/testdata:objc_lib ef85f6b2ede39c4594e743bc9cda9984 (1678337822 1794899563)')
INFO: Elapsed time: 1.239s, Critical Path: 0.06s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Writing file extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa' (FileWrite[[] -> [Artifact:[[/private/var/tmp/_bazel_salguarnieri/ca16ea5a435d8ac2288f379cdf092007/execroot/kythe]bazel-out/apl-ios_x86_64-fastbuild]extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa]])' (requested by nodes 'ARTIFACT:extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa //kythe/cxx/extractor/testdata:objc_lib ef85f6b2ede39c4594e743bc9cda9984 (1678337822 1794899563)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:416)
	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.addAll(ImmutableCollection.java:500)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:773)
	at com.google.devtools.build.lib.rules.objc.ObjcCompileAction$ObjcCompileActionSpawn.getInputFiles(ObjcCompileAction.java:95)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.getExtraActionInfo(SpawnAction.java:407)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.getExtraActionInfo(SpawnAction.java:386)
	at com.google.devtools.build.lib.rules.extra.ExtraActionInfoFileWriteAction$1.<init>(ExtraActionInfoFileWriteAction.java:56)
	at com.google.devtools.build.lib.rules.extra.ExtraActionInfoFileWriteAction.newDeterministicWriter(ExtraActionInfoFileWriteAction.java:51)
	at com.google.devtools.build.lib.exec.FileWriteStrategy.exec(FileWriteStrategy.java:54)
	at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.execute(AbstractFileWriteAction.java:63)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:778)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:718)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:102)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:608)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:570)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:380)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:196)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Writing file extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa' (FileWrite[[] -> [Artifact:[[/private/var/tmp/_bazel_salguarnieri/ca16ea5a435d8ac2288f379cdf092007/execroot/kythe]bazel-out/apl-ios_x86_64-fastbuild]extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa]])' (requested by nodes 'ARTIFACT:extra_actions/kythe/cxx/extractor/extra_action_objc/kythe/cxx/extractor/testdata/8245c6414543d44e309df1ac85d44b85.xa //kythe/cxx/extractor/testdata:objc_lib ef85f6b2ede39c4594e743bc9cda9984 (1678337822 1794899563)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:416)
	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.addAll(ImmutableCollection.java:500)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:773)
	at com.google.devtools.build.lib.rules.objc.ObjcCompileAction$ObjcCompileActionSpawn.getInputFiles(ObjcCompileAction.java:95)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.getExtraActionInfo(SpawnAction.java:407)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.getExtraActionInfo(SpawnAction.java:386)
	at com.google.devtools.build.lib.rules.extra.ExtraActionInfoFileWriteAction$1.<init>(ExtraActionInfoFileWriteAction.java:56)
	at com.google.devtools.build.lib.rules.extra.ExtraActionInfoFileWriteAction.newDeterministicWriter(ExtraActionInfoFileWriteAction.java:51)
	at com.google.devtools.build.lib.exec.FileWriteStrategy.exec(FileWriteStrategy.java:54)
	at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.execute(AbstractFileWriteAction.java:63)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:778)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:718)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:102)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:608)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:570)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:380)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:196)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
Build failed
```

### Environment info
* Operating System: OS X

* Bazel version (output of `bazel info release`):
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by salguarnieri** [comment]
I just tried using bazel @ head and the NPE doesn't happen any longer, so I'm guessing this will be fixed in the next release.
