### ISSUE TITLE
Windows, msysless: Bazel hangs if the server crashes early

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2817]
### Description of the problem / feature request / question:

I added a ctor to WindowsFileSystem which just throws an exception.
The bazel client appears to hang:
```
C:\work\bazel>C:/tmp-cmd/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe --output_user_root=c:\tmp9 build examples/cpp:hello-world
Extracting Bazel installation...
...............................................................................................................................................................................................................................................................................................................................................................................................^C
```

At the same time I see the exception in the `jvm.out`:

```
C:\work\bazel>type c:\tmp9\o6Hbs7N0\server\jvm.out
java.lang.IllegalStateException: DEBUG: WindowsFileSystem ctor
        at com.google.devtools.build.lib.windows.WindowsFileSystem.<init>(WindowsFileSystem.java:47)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:825)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:971)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:850)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:789)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:570)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
```

### Environment info
* Operating System: Windows 10

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

```
C:\work\bazel>git rev-parse HEAD
8e042300d8e1eb6b9eda8a59bdb809aadb91d23b
```
+ the local modification to add the exception

**Comment by laszlocsomor** [comment]
Ah. The culprit: https://github.com/bazelbuild/bazel/blob/e1c31944c3bcc89722a8e77013b11110edf3b5f6/src/main/cpp/blaze_util_windows.cc#L682
