### ISSUE TITLE
'Exception deframing message' when building large outputs remotely

### ISSUE THREAD

**Issue by ilya-biryukov** [bazelbuild/bazel#2822]
### Description of the problem / feature request / question:

I'm trying to build tensorflow  remotely and getting this exception in the process(full output at end of the issue):
```
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message)
io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
...
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 167773175 exceeds maximum: 104857600, 
...
```

The problem is that some of the tensorflow outputs are more than 100Mb in size, and they are being sent in a single grpc "message", hitting the grpc's limit for the maximal input message size.

### If possible, provide a minimal example to reproduce the problem:
1. Compile `bazel` and `//src/tools/remote_worker `
2. Run remote_worker
```
./bazel-bin/src/tools/remote_worker/remote_worker --listen_port=8080 --work_path=/tmp/test
```
3. Unpack [huge-link.tar.gz](https://github.com/bazelbuild/bazel/files/920294/huge-link.tar.gz).
4. Run bazel to build it
```
bazel --host_jvm_args=-Dbazel.DigestFunction=SHA1 build --spawn_strategy=remote --remote_worker=localhost:8080 --remote_cache=localhost:8080  --noremote_allow_local_fallback --noremote_accept_cached --verbose_failures //:huge
```

**Expected**: builds suceeds
**Actual**: exception "Frame size 167773175 exceeds maximum: 104857600" is fired.

### Environment info 
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`): development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
eecd7128f420b2d404ed2f42d549dea3bd198d9d

### Anything else, information or logs or outputs that would be helpful?

The problem can be easily worked around by calling `maxMessageSize(200 * 1024 * 1024)` in `RemoteUtils.createChannel`. Adding a configurable parameter for that would help.
But I'm not sure that's the right way to fix this. (My suspicion is that grpc keeps deframed messages in memory, which is probably a wrong way to handle large file transfers).

Full exception output:
```
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message)
io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
        at io.grpc.Status.asRuntimeException(Status.java:545)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:504)
        at com.google.devtools.build.lib.remote.GrpcActionCache.downloadAllResults(GrpcActionCache.java:201)
        at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:292)
        at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:71)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1138)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:780)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:723)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:101)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:625)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:582)
        at java.util.concurrent.FutWARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message)
io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
        at io.grpc.Status.asRuntimeException(Status.java:545)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:504)
        at com.google.devtools.build.lib.remote.GrpcActionCache.downloadAllResults(GrpcActionCache.java:201)
        at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:292)
        at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:71)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1138)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:780)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:723)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:101)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:625)
        at WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message)
io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
        at io.grpc.Status.asRuntimeException(Status.java:545)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:504)
        at com.google.devtools.build.lib.remote.GrpcActionCache.downloadAllResults(GrpcActionCache.java:201)
        at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:292)
        at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:71)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1138)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:780)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:723)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:101)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:625)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:582)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:393)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:453)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:202)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 314573818 exceeds maximum: 209715200, 
        at io.grpc.Status.asRuntimeException(Status.java:536)
        at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:337)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:240)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:176)
        at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
        at io.grpc.internal.AbstractClientStream.inboundDataReceived(AbstractClientStream.java:150)
        at io.grpc.internal.Http2ClientStream.transportDataReceived(Http2ClientStream.java:137)
        at io.grpc.netty.NettyClientStream.transportDataReceived(NettyClientStream.java:180)
        at io.grpc.netty.NettyClientHandler.onDataRead(NettyClientHandler.java:251)
        at io.grpc.netty.NettyClientHandler.access$700(NettyClientHandler.java:92)
        at io.grpc.netty.NettyClientHandler$FrameListener.onDataRead(NettyClientHandler.java:588)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:250)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:409)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:240)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:111)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:331)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        ... 1 more
.
ERROR: /usr/local/google/home/ibiryukov/projects/huge-link/BUILD:1:1: C++ compilation of rule '//:huge' failed: io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message.
com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:582)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:393)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:453)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:202)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 314573818 exceeds maximum: 209715200, 
        at io.grpc.Status.asRuntimeException(Status.java:536)
        at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:337)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:240)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:176)
        at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
        at io.grpc.internal.AbstractClientStream.inboundDataReceived(AbstractClientStream.java:150)
        at io.grpc.internal.Http2ClientStream.transportDataReceived(Http2ClientStream.java:137)
        at io.grpc.netty.NettyClientStream.transportDataReceived(NettyClientStream.java:180)
        at io.grpc.netty.NettyClientHandler.onDataRead(NettyClientHandler.java:251)
        at io.grpc.netty.NettyClientHandler.access$700(NettyClientHandler.java:92)
        at io.grpc.netty.NettyClientHandler$FrameListener.onDataRead(NettyClientHandler.java:588)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:250)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:409)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:240)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:111)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:331)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        ... 1 more
.
ERROR: /usr/local/google/home/ibiryukov/projects/huge-link/BUILD:1:1: C++ compilation of rule '//:huge' failed: io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message.
ureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:393)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:453)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:202)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 314573818 exceeds maximum: 209715200, 
        at io.grpc.Status.asRuntimeException(Status.java:536)
        at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:337)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:240)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:176)
        at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
        at io.grpc.internal.AbstractClientStream.inboundDataReceived(AbstractClientStream.java:150)
        at io.grpc.internal.Http2ClientStream.transportDataReceived(Http2ClientStream.java:137)
        at io.grpc.netty.NettyClientStream.transportDataReceived(NettyClientStream.java:180)
        at io.grpc.netty.NettyClientHandler.onDataRead(NettyClientHandler.java:251)
        at io.grpc.netty.NettyClientHandler.access$700(NettyClientHandler.java:92)
        at io.grpc.netty.NettyClientHandler$FrameListener.onDataRead(NettyClientHandler.java:588)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:250)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:409)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:240)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:111)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:331)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        ... 1 more
.
ERROR: /usr/local/google/home/ibiryukov/projects/huge-link/BUILD:1:1: C++ compilation of rule '//:huge' failed: io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message.
```

**Comment by buchgr** [comment]
The proper fix to this problem is to chunk the protobuf message into smaller pieces (say 4KiB messages or so). I wonder why the tensorflow build is not broken by this? Anyway, we are on a very old version of gRPC and since then gRPCs default max message size has been decreased so a saner 4MiB. 

The main problem with very large message sizes is that the whole message needs to eventually be reconstructed in memory. Lot's of buffering overhead internally in gRPC and also (moving) garbage collectors very much dislike objects/byte[] sized >100MiB.

**Comment by ulfjack** [comment]
We're already chunking protobuf messages, aren't we? Maybe the server-side isn't chunking, because our upload code path is chunking, unless I'm misremembering.

**Comment by ulfjack** [comment]
I think this is a bug in remote_worker, not Bazel as such.

**Comment by ola-rozenfeld** [comment]
Sorry, I already have a fix for this, I will send it out for review shortly (need to get some prerequisites in).
