### ISSUE TITLE
out of memory creating hazelcast client

### ISSUE THREAD

**Issue by monchalve** [bazelbuild/bazel#2823]
### Description of the problem / feature request / question:
The change in 0.4.4 to create a new action cache client on every invocation of the RemoteSpawnStrategy is causing out of memory errors if a Hazelcast client is used.

The patch that introduced this:
https://github.com/bazelbuild/bazel/commit/d2997290078e9e5114d604a6cedefda0f0c6dec4

### If possible, provide a minimal example to reproduce the problem:
Happens when using `--hazelcast_node`

### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`):
0.4.5 

cc @ola-rozenfeld 

Stack trace:
```
java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:714)
at com.hazelcast.util.executor.StripedExecutor.(StripedExecutor.java:61)
at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl.(ClientListenerServiceImpl.java:63)
at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.(ClientSmartListenerService.java:53)
at com.hazelcast.client.impl.HazelcastClientInstanceImpl.initListenerService(HazelcastClientInstanceImpl.java:291)
at com.hazelcast.client.impl.HazelcastClientInstanceImpl.(HazelcastClientInstanceImpl.java:175)
at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:84)
at com.google.devtools.build.lib.remote.ConcurrentMapFactory.createHazelcast(ConcurrentMapFactory.java:65)
at com.google.devtools.build.lib.remote.ConcurrentMapFactory.create(ConcurrentMapFactory.java:225)
at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:198)
at com.google.devtools.build.lib.rules.cpp.CppLinkAction.execute(CppLinkAction.java:344)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:763)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:706)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:604)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:566)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:376)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:196)
at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:381)
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
unable to create new native thread
bazel ran out of memory and crashed.```

**Comment by ola-rozenfeld** [comment]
Yes, sorry about that, we are aware of this -- I anticipate a fix in a few
weeks, because we have a few related changes in the pipeline.

**Comment by damienmg** [comment]
(cannot assign to @ola-rozenfeld because she hasn't accepted my invite to the org yet)

**Comment by ulfjack** [comment]
Technically, I fixed this in the replacement implementation, but that hasn't landed yet.
