### ISSUE TITLE
NullPointerException in remote cache for empty files

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2843]
We can get NPEs in the remote cache / execution for empty files in cases where the SpawnInputExpander returns null (representing empty file). We were previously using /dev/null, but that is too platform-specific.

Caused by: java.lang.NullPointerException: at index 10
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:220)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:347)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:257)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:245)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:251)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)

**Comment by ulfjack** [comment]
Not all tests are affected by this. It also affects remote execution, which uses the same code path to build merkle tree.

**Comment by ulfjack** [comment]
Fixed by 59b099b2a7868a0516c54f38f59e89fef8704473.
