### ISSUE TITLE
Test execution swallows IOException

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2845]
When running //src/test/shell/bazel:bazel_toolchain_test with remote caching, the test fails with an error message that the log file was not created. What's happening is that there's actually an IOException thrown, which is swallowed by the TestStrategy. Complete stack trace:

```
com.google.devtools.build.lib.actions.DigestOfDirectoryException: Input is a directory: src/test/shell/bazel/testdata/bazel_toolchain_test_data
	at com.google.devtools.build.lib.exec.SingleBuildFileCache$1.load(SingleBuildFileCache.java:84)
	at com.google.devtools.build.lib.exec.SingleBuildFileCache$1.load(SingleBuildFileCache.java:66)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.devtools.build.lib.exec.SingleBuildFileCache.getDigest(SingleBuildFileCache.java:112)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getDigest(SkyframeActionExecutor.java:1082)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:329)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.computeMerkleDigests(TreeNodeRepository.java:332)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:262)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTest(StandaloneTestStrategy.java:317)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:271)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:137)
	at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:42)
	at com.google.devtools.build.lib.rules.test.TestRunnerAction.execute(TestRunnerAction.java:655)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:780)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:723)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:101)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:625)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:582)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:393)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:453)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:202)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ulfjack** [comment]
The reason is a filegroup in src/test/shell/testdata that names a subdirectory.

**Comment by ulfjack** [comment]
The simple fix is to update the BUILD file not to do that, which is easily possible.

**Comment by ulfjack** [comment]
This is slightly related to #1415.

**Comment by ohler** [comment]
I also have a test that fails with an error message about test.log missing when remote caching is enabled, but succeeds otherwise.  How do I get Bazel to show me the underlying Exception?

**Comment by ulfjack** [comment]
More details please.

This bug is about exposing the underlying exception rather than swallowing it, and that's not implemented yet; that's why the bug is still open?

**Comment by ohler** [comment]
Sorry for not being clearer.  I understand that the lack of diagnostics is what this bug is about.  Still, I'm asking if there's a workaround, so that I can file a useful report on the other error I am seeing.  Since you mentioned the underlying exception in the original report, I concluded there's some way to run bazel in a way that displays it.  Perhaps with a patch, or with a debugger?

The error I'm seeing is easy for me to reproduce, but the repro is a complex setup, a large code base full of custom rules, and the error only happens on some targets but not others, even though they look very similar to me; without more detailed logging, I'm at a loss as to which parts of my setup are triggering the bug.  I could file a vague report, but to make it actionable, I'd rather include specifics.  That's why I'm looking for better debugging tools.

Hence my question: How did you figure out what the underlying exception was?

**Comment by ulfjack** [comment]
I patched Bazel, but I don't remember how exactly. Can you post the output you're seeing?

**Comment by ohler** [comment]
Thanks for confirming that, it's useful to know that there is no easier way.

By staring some more at the set of passing vs. failing tests and what dependencies they have in common, I was able to track it down to the same root cause as in your case, a filegroup that includes a directory; I'll fix the BUILD file not to do that.

For anyone else who runs into this, with Bazel 0.5.2, the symptoms in my case looked like this (I substituted `...target...` and `...environment vars...` to protect the innocent):
```
$ ./scripts/bazel test --remote_rest_cache='http://127.0.0.1:5701/hazelcast/rest/maps/cache' --spawn_strategy=remote -s --verbose_failures ...target...
INFO: Reading 'startup' options from /Users/ohler/shift/25/s0/tools/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1
INFO: Found 2 targets and 1 test target...
>>>>> # //...target... [action 'Testing //...target...']
(cd /private/var/tmp/_bazel_ohler/4c68175f63ffe0fd124ad9f9f698a193/execroot/__main__ && \
  exec env - \
    ...environment vars... \
  external/bazel_tools/tools/test/test-setup.sh ...test executable...)
FAIL: //...target... (see /private/var/tmp/_bazel_ohler/4c68175f63ffe0fd124ad9f9f698a193/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/testlogs/...target.../test.log).
ERROR: Caught I/O exception: java.io.FileNotFoundException: /private/var/tmp/_bazel_ohler/4c68175f63ffe0fd124ad9f9f698a193/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/testlogs/...target.../test.log (No such file or directory).
ERROR: ...target.../BUILD.bazel:89:1:  failed: unexpected I/O exception: /private/var/tmp/_bazel_ohler/4c68175f63ffe0fd124ad9f9f698a193/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/testlogs/...target.../test.log (No such file or directory).
==================== Test output for //...target...:
INFO: Elapsed time: 0.329s, Critical Path: 0.04s
//...target...                      FAILED in 0.0s
```

**Comment by buchgr** [comment]
That's been fixed a while ago. When we find such a directory we do readdir() on it.
