### ISSUE TITLE
ctx.new_file gives awful error message when called with 0 arguments

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2877]
```
def _yaspl_lint_impl(target, ctx):
  ctx.new_file()

yaspl_lint = aspect(
  implementation = _yaspl_lint_impl,
  attr_aspects = [],
)
```

When I run this aspect I get the following error:
```
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/BUILD:266:1: in //libraries:yaspl-lint.bzl%yaspl_lint aspect on yaspl_library rule //libraries:io:
Traceback (most recent call last):
        File "/Users/endobson/proj/racket/yaspl2/libraries/BUILD", line 266
                //libraries:yaspl-lint.bzl%yaspl_lint(...)
        File "/Users/endobson/proj/racket/yaspl2/libraries/yaspl-lint.bzl", line 3, in _yaspl_lint_impl
                ctx.new_file()
Too many arguments (in function new_file() of ctx).
```

I have supplied 0 arguments, I don't know how this could be too many.

**Comment by laurentlb** [comment]
I expect this to be fixed with @c-parsons recent change.
