### ISSUE TITLE
Bazel crashes with unrecoverable error when aspect has two actions for same file

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2879]
```
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel build --aspects libraries/yaspl-lint.bzl%yaspl_lint //libraries:io                                                                                                                     (0)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ASPECT:[]#//libraries:yaspl-lint.bzl%yaspl_lint 97ae9fe0de510a358fc34e4fa09cf85b 97ae9fe0de510a358fc34e4fa09cf85b {}' (requested by nodes 'LOAD_SKYLARK_ASPECT:com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@5a9039')
INFO: Elapsed time: 0.147s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//libraries:yaspl-lint.bzl%yaspl_lint 97ae9fe0de510a358fc34e4fa09cf85b 97ae9fe0de510a358fc34e4fa09cf85b {}' (requested by nodes 'LOAD_SKYLARK_ASPECT:com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@5a9039')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for libraries/lint, previous action: action 'Writing file libraries/lint', attempted action: action 'Generating libraries/lint'
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:46)
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.<init>(ActionLookupValue.java:51)
        at com.google.devtools.build.lib.skyframe.AspectValue.<init>(AspectValue.java:323)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:460)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:291)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        ... 4 more
Caused by: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for libraries/lint, previous action: action 'Writing file libraries/lint', attempted action: action 'Generating libraries/lint'
        at com.google.devtools.build.lib.actions.Actions.maybeFilterSharedActionsAndThrowIfConflict(Actions.java:125)
        at com.google.devtools.build.lib.actions.Actions.filterSharedActionsAndThrowActionConflict(Actions.java:111)
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:43)
        ... 9 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//libraries:yaspl-lint.bzl%yaspl_lint 97ae9fe0de510a358fc34e4fa09cf85b 97ae9fe0de510a358fc34e4fa09cf85b {}' (requested by nodes 'LOAD_SKYLARK_ASPECT:com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@5a9039')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for libraries/lint, previous action: action 'Writing file libraries/lint', attempted action: action 'Generating libraries/lint'
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:46)
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.<init>(ActionLookupValue.java:51)
        at com.google.devtools.build.lib.skyframe.AspectValue.<init>(AspectValue.java:323)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:460)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:291)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        ... 4 more
Caused by: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for libraries/lint, previous action: action 'Writing file libraries/lint', attempted action: action 'Generating libraries/lint'
        at com.google.devtools.build.lib.actions.Actions.maybeFilterSharedActionsAndThrowIfConflict(Actions.java:125)
        at com.google.devtools.build.lib.actions.Actions.filterSharedActionsAndThrowActionConflict(Actions.java:111)
        at com.google.devtools.build.lib.skyframe.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:43)
        ... 9 more
```

My aspect rule.
```
def _yaspl_lint_impl(target, ctx):
  if (ctx.rule.kind == "yaspl_library"):
    outputs = [ctx.new_file("lint") for src in ctx.rule.attr.srcs for file in src.files]
    for output in outputs:
      print(output)
      ctx.file_action(output, "Contents")
      ctx.action(command = "satehastuh", outputs=[output])

  return struct()

yaspl_lint = aspect(
  implementation = _yaspl_lint_impl,
  attr_aspects = [],
)
```

**Comment by c-parsons** [comment]
I've tried to reproduce this issue at HEAD (using `ctx.actions.run_shell`, because `ctx.action` is deprecated) and instead I get: 

```
ERROR: file 'package/a' is generated by these conflicting actions:
Label: //package:bar
RuleClass: dep_rule rule
...
```

which is a more sane error, and not a Bazel crash. So, i believe we should just mark this fixed.
