### ISSUE TITLE
Unhandled exception for data configuration

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2899]
### Description of the problem / feature request / question:

When I try to run our build, it results in an unhandled exception. And the error message is not terribly helpful.

    Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:assets/planets/materials/planet_rigant_moon_003_sparks_001.material.stage1 82b988cccd1a5fb4e16f7165efcd8bb1 (432935828 2023429252)' (requested by nodes 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:all_materials 82b988cccd1a5fb4e16f7165efcd8bb1 (1628497015 2023429252)')
     INFO: Elapsed time: 41.638s
     java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:assets/planets/materials/planet_rigant_moon_003_sparks_001.material.stage1 82b988cccd1a5fb4e16f7165efcd8bb1 (432935828 2023429252)' (requested by nodes 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:all_materials 82b988cccd1a5fb4e16f7165efcd8bb1 (1628497015 2023429252)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
     Caused by: java.lang.IllegalStateException: /my/gof3m_assets/target/uncompressed_debug_high/BUILD:1383:1: _ae_material attribute data is not configured for the data configuration
	at com.google.devtools.build.lib.analysis.RuleContext.checkAttribute(RuleContext.java:1106)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisites(RuleContext.java:714)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.getPrerequisites(Runfiles.java:1112)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.addDataDeps(Runfiles.java:982)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.addRunfiles(Runfiles.java:954)
	at com.google.devtools.build.lib.rules.SkylarkRuleImplementationFunctions$6.invoke(SkylarkRuleImplementationFunctions.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:155)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:616)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:717)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:703)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:676)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:726)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:703)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:79)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.rules.SkylarkRuleConfiguredTargetBuilder.buildRule(SkylarkRuleConfiguredTargetBuilder.java:84)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:268)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:177)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:487)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1109)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:254)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
     java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:assets/planets/materials/planet_rigant_moon_003_sparks_001.material.stage1 82b988cccd1a5fb4e16f7165efcd8bb1 (432935828 2023429252)' (requested by nodes 'CONFIGURED_TARGET://gof3m_assets/target/uncompressed_debug_high:all_materials 82b988cccd1a5fb4e16f7165efcd8bb1 (1628497015 2023429252)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
     Caused by: java.lang.IllegalStateException: /my/gof3m_assets/target/uncompressed_debug_high/BUILD:1383:1: _ae_material attribute data is not configured for the data configuration
	at com.google.devtools.build.lib.analysis.RuleContext.checkAttribute(RuleContext.java:1106)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisites(RuleContext.java:714)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.getPrerequisites(Runfiles.java:1112)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.addDataDeps(Runfiles.java:982)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.addRunfiles(Runfiles.java:954)
	at com.google.devtools.build.lib.rules.SkylarkRuleImplementationFunctions$6.invoke(SkylarkRuleImplementationFunctions.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:155)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:616)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:717)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:703)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:676)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:726)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:703)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:79)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.rules.SkylarkRuleConfiguredTargetBuilder.buildRule(SkylarkRuleConfiguredTargetBuilder.java:84)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:268)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:177)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:487)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1109)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:254)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more

### If possible, provide a minimal example to reproduce the problem:

I have something like:

    def _ae_material(ctx):
        ...
        return struct(
            runfiles=ctx.runfiles(
                 [myfile],
                 collect_default = True,
            ),
        )

    _ae_material = rule(
        attrs = dict({
            ...
            "data": attr.label_list(allow_files = [".myformat"]),
        },

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
Nope

**Comment by abergmeier-dsfishlabs** [comment]
Docs state:

> The configuration "data" is present for legacy reasons and should be used for the data attributes.

So should that be used!? How to fix this?

**Comment by laurentlb** [comment]
"data" configuration is now a no-op.
Stop using it, it will be removed very soon
