### ISSUE TITLE
jacoco deploy jar incorrectly built

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#2904]
split off from https://github.com/bazelbuild/bazel/issues/2528

this is still a problem with 0.4.5

$ git checkout -b coverage origin/master
Branch coverage set up to track remote branch master from origin.
Switched to a new branch 'coverage'

hanwen@hanwen:~/vc/gerrit$ bazel coverage --test_output=streamed //gerrit-common:auto_value_tests
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time.
INFO: Using default value for --instrumentation_filter: "//gerrit-common".
INFO: Override the above default with --instrumentation_filter
INFO: Found 1 test target...
JUnit4 Test Runner
.
Time: 0.03

OK (1 test)

BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2017-04-27 12:31:18 --

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/devtools/lcovmerger/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
FAIL: //gerrit-common:auto_value_tests (see /home/hanwen/.cache/bazel/_bazel_hanwen/92cfb41f49554b16e2b6f54cafbeca56/execroot/gerrit/bazel-out/local-fastbuild/testlogs/gerrit-common/auto_value_tests/test.log).
Target //gerrit-common:auto_value_tests up-to-date:
  bazel-bin/gerrit-common/auto_value_tests.jar
  bazel-bin/gerrit-common/auto_value_tests
INFO: Elapsed time: 2.453s, Critical Path: 0.99s
//gerrit-common:auto_value_tests                                         FAILED in 1 out of 2 in 0.6s
  /home/hanwen/.cache/bazel/_bazel_hanwen/92cfb41f49554b16e2b6f54cafbeca56/execroot/gerrit/bazel-out/local-fastbuild/testlogs/gerrit-common/auto_value_tests/test.log

Executed 1 out of 1 test: 1 fails locally.

hanwen@hanwen:~/vc/gerrit$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

**Comment by hanwen** [comment]
sorry : dup. https://github.com/bazelbuild/bazel/issues/2663

**Comment by hanwen** [comment]
I still can't run coverage on my google linux laptop.

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/devtools/lcovmerger/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)

looks  like lcovmerger is run with the system JVM rather than the bazel one. 

I think this is a separate issue from the problems with jarjar in #2663

**Comment by hanwen** [comment]
(note that my laptop comes with java 7 preinstalled in /usr/bin/)

**Comment by hanwen** [comment]
and it works if I manually set /usr/bin/java to be java 8.

**Comment by mhlopko** [comment]
@lberki @damienmg Is this really a release blocker?

**Comment by damienmg** [comment]
Lukacs fixed several things on building jacoco we should retest with 0.5.0rc7 to assess the issue. I am not sure it should be a release blocker if there isa workaround since it is a feature that was not working correctly in previous releases.

**Comment by lberki** [comment]
@hanwen , you seem to be right, `LcovMerger` is called using whatever JVM `java` gets you:

https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_coverage.sh#L139

Bad!
