### ISSUE TITLE
Poor error when WORKSPACE loads from another directory with WORKSPACE

### ISSUE THREAD

**Issue by brian-peloton** [bazelbuild/bazel#2928]
The error message when WORKSPACE tries to load a .bzl file in a subdirectory which also has a WORKSPACE file is really bad. I'm pretty sure this should fail, but with a nicer error message.

### Description of the problem / feature request / question:
This is what I see:
```
$ ./bazel build ...
.........
Unhandled exception thrown during build; message: topLevelKey: TARGET_PATTERN:...
alreadyReported: false
path to cycle:
TARGET_PATTERN:...
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[], excludedPaths=<omitted>)
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[foo], excludedPaths=<omitted>)
cycle:
PACKAGE_LOOKUP:foo
LOCAL_REPOSITORY_LOOKUP:[/tmp/ajlkfdjsaldf]/[foo]
WORKSPACE_FILE:[/tmp/ajlkfdjsaldf]/[WORKSPACE], 1
SKYLARK_IMPORTS_LOOKUP://foo:foo.bzl (in workspace)
AST_FILE_LOOKUP://foo:foo.bzl

INFO: Elapsed time: 0.651s
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN:...
alreadyReported: false
path to cycle:
TARGET_PATTERN:...
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[], excludedPaths=<omitted>)
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[foo], excludedPaths=<omitted>)
cycle:
PACKAGE_LOOKUP:foo
LOCAL_REPOSITORY_LOOKUP:[/tmp/ajlkfdjsaldf]/[foo]
WORKSPACE_FILE:[/tmp/ajlkfdjsaldf]/[WORKSPACE], 1
SKYLARK_IMPORTS_LOOKUP://foo:foo.bzl (in workspace)
AST_FILE_LOOKUP://foo:foo.bzl

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:82)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:164)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:279)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:133)
	at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:436)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:168)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:65)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:479)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:294)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:47)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:838)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:898)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN:...
alreadyReported: false
path to cycle:
TARGET_PATTERN:...
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[], excludedPaths=<omitted>)
RECURSIVE_PKG:rootedPath=[/tmp/ajlkfdjsaldf]/[foo], excludedPaths=<omitted>)
cycle:
PACKAGE_LOOKUP:foo
LOCAL_REPOSITORY_LOOKUP:[/tmp/ajlkfdjsaldf]/[foo]
WORKSPACE_FILE:[/tmp/ajlkfdjsaldf]/[WORKSPACE], 1
SKYLARK_IMPORTS_LOOKUP://foo:foo.bzl (in workspace)
AST_FILE_LOOKUP://foo:foo.bzl

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:82)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:164)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:279)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:133)
	at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:436)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:168)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:65)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:479)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:294)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:47)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:838)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:101)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:898)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

When doing something similar with a less minimal reproduction, I don't see the stacktraces and the information about what's actually in the cycle only shows up in java.log. I think the difference is there's more stuff in WORKSPACE which errors out before it gets to this code. This is what happens instead:
```
ERROR: Failed to load Skylark extension '//third_party/bazel-rules_go/go:def.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository '' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing.
```

### If possible, provide a minimal example to reproduce the problem:
WORKSPACE:
```python
load('//foo:foo.bzl', 'foo')
```
foo/WORKSPACE is an empty file.

### Environment info
* Operating System:
Debian jessie amd64

* Bazel version (output of `bazel info release`):
```console
$ ./bazel info release
..........
release 0.4.5
```
I've tried 0.4.5 and a recent master with the same results.

###  Have you found anything relevant by searching the web?
#1693 might be related.

**Comment by katre** [comment]
Hmm, this is caused by the added LocalRepositoryLookupFunction call. Since there's a WORKSPACE file in foo/, LRLF is checking whether there's a local_repository() that points to 'foo', but it has to load the WORKSPACE file to check that, leading to the cycle.

It should work if you define the local repository in the main WORKSPACE like this:
```
local_repository(name = 'foo', path = 'foo')
load('@foo//:foo.bzl', 'foo')
```

**Comment by katre** [comment]
But I agree that the error is not ideal.

**Comment by damienmg** [comment]
@katre: can you triage this further?

**Comment by katre** [comment]
Not sure what further triage is needed. We need a better error message in this case but I'm not sure when I'll have time to check into it.

**Comment by abergmeier-dsfishlabs** [comment]
Managed to produce this right now. Man this is not too useful.

   ```
Unhandled exception thrown during build; message: topLevelKey: CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
CONFIGURED_TARGET://bazel/rules:go_default_library 92b1414b49969d42b1c40803cc23d02c (762317911 551016373)
PACKAGE:@com_github_bazelbuild_buildtools//build
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//build
cycle:
REPOSITORY:@com_github_bazelbuild_buildtools
REPOSITORY_DIRECTORY:@com_github_bazelbuild_buildtools
PACKAGE_LOOKUP:@io_bazel_rules_go_repository_tools//
REPOSITORY:@io_bazel_rules_go_repository_tools
REPOSITORY_DIRECTORY:@io_bazel_rules_go_repository_tools
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//

INFO: Elapsed time: 4.540s
java.lang.IllegalStateException: topLevelKey: CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
CONFIGURED_TARGET://bazel/rules:go_default_library 92b1414b49969d42b1c40803cc23d02c (762317911 551016373)
PACKAGE:@com_github_bazelbuild_buildtools//build
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//build
cycle:
REPOSITORY:@com_github_bazelbuild_buildtools
REPOSITORY_DIRECTORY:@com_github_bazelbuild_buildtools
PACKAGE_LOOKUP:@io_bazel_rules_go_repository_tools//
REPOSITORY:@io_bazel_rules_go_repository_tools
REPOSITORY_DIRECTORY:@io_bazel_rules_go_repository_tools
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:279)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:550)
	at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:504)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:213)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:374)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:121)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:160)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:541)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:322)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:863)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:929)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: topLevelKey: CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://assets/gof3m/collect:collect 92b1414b49969d42b1c40803cc23d02c (2077119198 551016373)
CONFIGURED_TARGET://bazel/rules:go_default_library 92b1414b49969d42b1c40803cc23d02c (762317911 551016373)
PACKAGE:@com_github_bazelbuild_buildtools//build
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//build
cycle:
REPOSITORY:@com_github_bazelbuild_buildtools
REPOSITORY_DIRECTORY:@com_github_bazelbuild_buildtools
PACKAGE_LOOKUP:@io_bazel_rules_go_repository_tools//
REPOSITORY:@io_bazel_rules_go_repository_tools
REPOSITORY_DIRECTORY:@io_bazel_rules_go_repository_tools
PACKAGE_LOOKUP:@com_github_bazelbuild_buildtools//

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:279)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:550)
	at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:504)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:213)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:374)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:121)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:160)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:541)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:322)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:863)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:929)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by abergmeier-dsfishlabs** [comment]
In my case, too it could not even find the correct `WORKSPACE` file. The error is misleading.
