### ISSUE TITLE
PathFragment type isn't documented and isn't inspectable

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2931]
I cannot find any documentation on what a `PathFragment` is and what methods/fields it has. Many apis return such objects (e.g. the cpp fragment).

I cannot run `dir` on it, and the error message says that it is not allowed as a Skylark value.
```
ERROR: /Users/endobson/tmp/bazel-bug5/BUILD:2:1: in //:test.bzl%demo aspect on filegroup rule //:empty:
Traceback (most recent call last):
        File "/Users/endobson/tmp/bazel-bug5/BUILD", line 2
                //:test.bzl%demo(...)
        File "/Users/endobson/tmp/bazel-bug5/test.bzl", line 4, in demo_impl
                print(dir(ctx.fragments.cpp.ar_executa...))
        File "/Users/endobson/tmp/bazel-bug5/test.bzl", line 4, in print
                dir(ctx.fragments.cpp.ar_executable)
illegal argument in call to dir: class com.google.devtools.build.lib.vfs.PathFragment is not allowed as a Skylark value.
```

Attempting to call methods on it crashes bazel:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//:test.bzl%demo 5f5c236947cb524bee68cdafac5c6952 5f5c236947cb524bee68cdafac5c6952 {}' (requested by nodes 'LOAD_SKYLARK_ASPECT:com.google.devtools.build.lib
.skyframe.AspectValue$SkylarkAspectLoadingKey@b5312ba9')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: class com.google.devtools.build.lib.vfs.PathFragment is not allowed as a Skylark value
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:61)
        at com.google.devtools.build.lib.syntax.EvalUtils.getSkylarkType(EvalUtils.java:187)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:608)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:715)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:701)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
        at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:674)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:737)
        at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:724)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:701)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
        at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
        at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:81)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
        at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:74)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:357)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:426)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:291)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        ... 4 more
```

**Comment by fahhem** [comment]
Some APIs expected PathFragments and now don't work, such as `ctx.action(executable=...)`. Syncing to head gives me this:

```py
Traceback (most recent call last):
	File "//BUILD", line 13
		raw_binary(name = 'firmware_bin')
	File "//compilers/raw_binary.bzl", line 8, in _bin_impl
		ctx.action(inputs = ([input] + ctx.files._o...), <4 more arguments>)
expected file or PathFragment for executable but got string instead.
```
Here's the definition of `raw_binary` (note that line 13 above does NOT exist in my code, both `src` and `out` are missing for some reason):

```py
# From https://github.com/pedrokiefer/rules_stm32/blob/master/tools/arm_compiler/raw_binary.bzl
def _bin_impl(ctx):
    output = ctx.outputs.out
    input = ctx.file.src
    objcopy = ctx.fragments.cpp.objcopy_executable

    ctx.action(
        inputs=[input] + ctx.files._objcopy,
        outputs=[output],
        progress_message="Creating raw binary from %s" % input.short_path,
        executable = objcopy,
        arguments = [ 
            "-O",
            "binary",
            "-S",
            input.path,
            output.path
        ])

raw_binary = rule(
    attrs = { 
        "src": attr.label(
            mandatory = True,
            allow_files = True,
            single_file = True,
        ),
        "out": attr.output(
            mandatory = True,
        ),
        "_objcopy": attr.label(
            default = Label("@arm_none_eabi_gcc//:objcopy"),
            allow_files = True,
        ),
    },  
    fragments = ["cpp"],
    implementation = _bin_impl,
)
```

**Comment by dslomov** [comment]
Reopened, fix rolled back
