### ISSUE TITLE
uncaught exception in bazel query

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2999]
I'm experimenting with repository rules and I most likely wrote something utterly senseless, yet an error message would be nicer here.

WORKSPACE:
```
$ cat WORKSPACE 
workspace(name = "io_bazel")

load("//foo:repo.bzl", "llvm_configure")

llvm_configure(
    name = "local_config_llvm",
    build_file_content = """
exports_files(glob(["**"]))
"""
)
```

foo/repo.bzl:
```
$  cat foo/repo.bzl 
def _impl(repository_ctx):
  result = repository_ctx.execute(["echo", "/tmp/dummy/path"])
  llvm_path = result.stdout.splitlines()[0]
  repository_ctx.symlink(Label("@%s//:llvm-4.0" % repository_ctx.name), llvm_path)


llvm_autoconf = repository_rule(
    implementation=_impl,
    local = True,
    environ = [])

def llvm_configure(name, build_file = None, build_file_content = None):
  llvm_autoconf(name="%s_impl" % name)

  native.new_local_repository(
      name = name,
      path = "/tmp/dummy", #llvm-4.0",
      build_file = build_file,
      build_file_content = build_file_content,
  )
```

Output:
```
$ bazel query @local_config_llvm_impl//:*
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN:@local_config_llvm_impl//:*
alreadyReported: false
path to cycle:
TARGET_PATTERN:@local_config_llvm_impl//:*
PACKAGE:@local_config_llvm_impl//
cycle:
PACKAGE_LOOKUP:@local_config_llvm_impl//
REPOSITORY:@local_config_llvm_impl
REPOSITORY_DIRECTORY:@local_config_llvm_impl

        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:180)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPattern(SkyframeTargetPatternEvaluator.java:65)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.preloadTargetPatterns(SkyframeTargetPatternEvaluator.java:89)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.preloadOrThrow(BlazeQueryEnvironment.java:421)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:129)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:124)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:65)
        at com.google.devtools.build.lib.runtime.commands.QueryCommand.exec(QueryCommand.java:169)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN:@local_config_llvm_impl//:*
alreadyReported: false
path to cycle:
TARGET_PATTERN:@local_config_llvm_impl//:*
PACKAGE:@local_config_llvm_impl//
cycle:
PACKAGE_LOOKUP:@local_config_llvm_impl//
REPOSITORY:@local_config_llvm_impl
REPOSITORY_DIRECTORY:@local_config_llvm_impl

        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:180)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPattern(SkyframeTargetPatternEvaluator.java:65)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.preloadTargetPatterns(SkyframeTargetPatternEvaluator.java:89)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.preloadOrThrow(BlazeQueryEnvironment.java:421)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:129)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:124)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:65)
        at com.google.devtools.build.lib.runtime.commands.QueryCommand.exec(QueryCommand.java:169)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Bazel version:
```
$ bazel version
Build label: 0.5.0rc6-jdk7
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu May 11 20:08:46 2017 (1494533326)
Build timestamp: 1494533326
Build timestamp as int: 1494533326
```

**Comment by kchodorow** [comment]
Yeah, looks like the cycle reporter just isn't handling this type of cycle.
