### ISSUE TITLE
Building Bazel from source fails

### ISSUE THREAD

**Issue by AlexYursha** [bazelbuild/bazel#3018]
### Description of the problem / feature request / question:

Building Bazel from source fails.

### If possible, provide a minimal example to reproduce the problem:
- Download Bazel 0.4.5 release archive from Github
- Unzip it
- Run a build command as in the log snippet below

### Environment info
* Operating System:
Chromebook Crouton environment, ubuntu-xenial

* Bazel version (output of `bazel info release`):
0.4.5

###  Have you found anything relevant by searching the web?
No

### Anything else, information or logs or outputs that would be helpful?

```
(xenial)alex@localhost:~/Downloads/bazel-0.4.5$ bash ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scrat.......
🍃  Building Bazel with Baz.
.WARNING: /tmp/bazel_v2rmqJQw/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_v2rmqJQw/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /home/alex/Downloads/bazel-0.4.5/src/main/cpp/util/BUILD:101:1: C++ compilation of rule '//src/main/cpp/util:md5' failed: gcc failed: error executing command 
  (cd /tmp/bazel_v2rmqJQw/out/execroot/bazel-0.4.5 && \
  exec env - \
    PATH=/home/alex/bin:/home/alex/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d '-frandom-seed=bazel-out/local-opt/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o' -fPIC -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/util/md5.cc -o bazel-out/local-opt/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //src:bazel failed to build
INFO: Elapsed time: 12.182s, Critical Path: 0.47s

ERROR: Could not build Bazel
```

**Comment by tfarina** [comment]
What is your version of gcc?

**Comment by mhlopko** [comment]
I'd say your g++ is not correctly installed, can you build a C++ hello world? Never played with Crouton, can you just run sudo apt-get install g++ or build-essential there?

**Comment by mhlopko** [comment]
Friendly ping @AlexYursha

**Comment by AlexYursha** [comment]
Installing `g++` and `build-essential` helped to progress further but now I'm getting a different error that embedded tools failed to build. Below is the truncated error message:

```
ERROR: /home/alex/Downloads/bazel-0.4.5/src/BUILD:129:1: Executing genrule //src:embedded_tools failed: bash failed: error executing command 
  (cd /tmp/bazel_M3Z0B8hS/out/execroot/bazel-0.4.5 && \
  exec env - \
    PATH=/home/alex/bin:/home/alex/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; src/create_embedded_tools.sh bazel-out/local-opt/genfiles/src/embedded_tools.zip src/create_embedded_tools.sh tools/BUILD tools/test_sharding_compliant tools/android/jack/BUILD tools/android/jack/fail.sh tools/android/BUILD tools/android/BUILD.tools tools/android/aar_embedded_jars_extractor.py tools/android/aar_native_libs_zip_creator.py tools/android/android_permissions.py tools/android/android_sdk_repository_template.bzl tools/android/bazel_debug.keystore tools/android/build_incremental_dexmanifest.py tools/android/build_split_manifest.py tools/android/fail.sh tools/android/incremental_install.py tools/android/merge_manifests.py tools/android/resource_extractor.py tools/android/strip_resources.py tools/android/stubify_manifest.py tools/android/zip_manifest_creator.sh tools/android/emulator/BUILD.tools tools/android/emulator/googletest.sh tools/android/emulator/no_se_linux.properties tools/build_defs/apple/apple_genrule.bzl tools/build_defs/apple/shared.bzl tools/build_defs/apple/ <...truncated...>
```

**Comment by mhlopko** [comment]
Wasn't there any more detailed error message from bash? What was the return code? Can you reproduce this error (by cd-ing into the execroot and running the command yourself)?

**Comment by AlexYursha** [comment]
You're right. My environment was missing a `zip` command. After installing `zip` package Bazel built successfully. I tested it on version **0.5.1**.

**Comment by Jayoprell** [comment]
/home/nvidia/installTensorFlowTX2/bazel-0.4.5-dist/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android/ziputils:ziputils_lib' failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:673)
	at com.sun.tools.javac.util.Log.printLines(Log.java:485)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:156)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build


Could you know where my problem is?

**Comment by jin** [comment]
@Jayoprell Bazel 0.4.5 was released quite a while ago. Do you mind trying your build again with a later release like 0.9.0? https://github.com/bazelbuild/bazel/releases

**Comment by Jayoprell** [comment]
Hi, thanks for your advice.
I want to install tensorflow on Jetson TX2 and I follow the instructions [http://www.jetsonhacks.com/2017/09/14/build-tensorflow-on-nvidia-jetson-tx2-development-kit/](url) to install it. In the installing process, bazel need to be install first. For the begainning, I compile bazel 0.9.0 and it failed. The errors are as follows:
`ERROR: /home/nvidia/Desktop/bazel/bazel-0.9.0-dist/src/main/java/com/google/devtools/common/options/BUILD:27:1: Building src/main/java/com/google/devtools/common/options/liboptions_internal.jar (35 source files) failed (Exit 1): java failed: error executing command 
  (cd /tmp/bazel_7yWeYgtw/out/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/local_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:third_party/java/jdk/langtools/javac-9-dev-r4023-3.jar -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar @bazel-out/host/bin/src/main/java/com/google/devtools/common/options/liboptions_internal.jar-2.params)
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:788)
	at com.sun.tools.javac.util.Log.printLines(Log.java:586)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:107)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:105)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:108)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:116)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 630.446s, Critical Path: 125.70s
FAILED: Build did NOT complete successfully
`


Then I am wondering whether the version of bazel is not compatible,  so I compile a lower bazel(0.4.5). But it did not work.

**Comment by karthee320** [comment]
I am facing the same issue as @Jayoprell reported:

Bazel 0.5.2
I tried multiple times and each time it is showing same error at different files. The error is,
java.lang.InternalError: Cannot find requested source bundle for locale en_US at(list of files) Caused by: java.util,MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US

Target //src:bazel failed to build

Bazel 0.3.2
When I tried this version, the error is
Error: Java compilation in rule 'Filename': Javac worker (id 0) can no longer be used, because its process terminated itself or got killed.

Target //src:bazel failed to build

Could you please help me resolve this?

**Comment by jin** [comment]
This issue is closed. @karthee320 @Jayoprell do you mind creating new issues? Your error messages are different from the original question.

**Comment by Jayoprell** [comment]
Hi, @karthee320 
I built bazel successfully!(my system is ubuntu16.04)
If you are facing the similar issues as mine, it maybe that you do not install JDK8 correctly. 
Please follow the below link to build bazel.
[https://docs.bazel.build/versions/master/install-ubuntu.html](url)
Please install JDK8 follow the above link, do not install other JDK  on your system(e.g. download a new JDK pakage form official website and then install on your system). If you install two jdk, it maybe confuse when to build bazel!
Hope it will woks!

**Comment by Jayoprell** [comment]
@jin I'm sorry. But I will.

**Comment by Jayoprell** [comment]
Hi, what is your problem? Could you please tell me more details with it?  Are you Chinese? If you are, we can communicate in Chinese😊😃
________________________________
发件人: caiyufeng <notifications@github.com>
发送时间: 2018年3月17日 5:23
收件人: bazelbuild/bazel
抄送: Jayoprell; Mention
主题: Re: [bazelbuild/bazel] Building Bazel from source fails (#3018)


@Jayoprell<https://github.com/jayoprell> can you tell me how to debug this
