### ISSUE TITLE
Build bazel-0.5.0rc9 fails on MIPS arch

### ISSUE THREAD

**Issue by xzy256** [bazelbuild/bazel#3068]
Building  bazel-0.5.0rc9 failed for  `BadExitStatusException: Process exited with status 50`. Terminal output error as follow. 
<pre>
ERROR: /home/xzy/bazel-0.5.0rc9/src/java_tools/singlejar/BUILD:77:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output;mkdir bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/h...' failed: bash failed: error executing command
  (cd /tmp/bazel_Qvcl1sVW/out/execroot/bazel-0.5.0rc9 && \
  exec env - \
    PATH=/opt/j2sdk-image/bin:/usr/local/bin/:/opt/j2sdk-image/bin:/usr/local/bin/:/opt/j2sdk-image/bin:/usr/local/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/xzy/.local/bin:/home/xzy/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output;mkdir bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/java_tools/singlejar/libbootstrap.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/java_tools/singlejar/libskylark-deps.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/auto/auto-common-0.3.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/error_prone/error_prone_annotation-2.0.20-SNAPSHOT.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/error_prone/error_prone_annotations-2.0.20-SNAPSHOT.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/error_prone/error_prone_check_api-2.0.20-SNAPSHOT.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/error_prone/error_prone_core-2.0.20-SNAPSHOT.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/guava/guava-21.0.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/jcip_annotations/jcip-annotations-1.0-1.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/jsr305/jsr-305.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/pcollections/pcollections-2.1.2.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/third_party/checker_framework_dataflow/libbootstrap.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/third_party/jformatstring/libbootstrap.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/libshell-skylark.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
external/local_jdk/bin/jar cmf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_MANIFEST.MF bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar -C bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output .
touch bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 50.
???????
ERROR: I/O error while writing action log: ???????.
Target //src:bazel failed to build
INFO: Elapsed time: 118.800s, Critical Path: 36.91s

$ java -version
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (build 1.8.0_25-rc21-b17)
OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)
$ uname -a
Linux localhost.localdomain 3.10.84 #1 SMP PREEMPT Wed Feb 8 16:03:10 CST 2017 mips64 mips64 mips64 GNU/Linux
</pre>

**Comment by laszlocsomor** [comment]
Do I understand correctly that you ran compile.sh, it built Bazel successfully, then failed in the "Building bazel with bazel" phase?

**Comment by xzy256** [comment]
Thanks your attention, upwards error has fixed. I can run a part of `compile.sh`, then i get error.
<pre>
$bash -x compile.sh
... ...
ERROR: /home/xzy/bazel-0.5.0rc9/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/BUILD:10:1: Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.jar () failed: Worker process returned an unparseable WorkResponse:

---8<---8<--- Exception details ---8<---8<---
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
	at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2678)
	at com.google.protobuf.CodedInputStream$StreamDecoder.skipRawBytesSlowPath(CodedInputStream.java:2886)
	at com.google.protobuf.CodedInputStream$StreamDecoder.skipRawBytes(CodedInputStream.java:2860)
	at com.google.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2040)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1847)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1814)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2396)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2391)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:329)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.parseDelimitedFrom(WorkerProtocol.java:2059)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.execInWorker(WorkerSpawnStrategy.java:337)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.actuallyExec(WorkerSpawnStrategy.java:182)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.exec(WorkerSpawnStrategy.java:131)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.exec(WorkerSpawnStrategy.java:104)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log ---8<---8<---
#
# A fatal error has been detected by the Java Runtime Environment:
by the Java Runtime Environment:
---8<---8<--- End of log ---8<---8<---.
Target //src:bazel failed to build
</pre>

**Comment by xzy256** [comment]
When i exec `bash -x compile.sh` for 3 times, i get  same as `Worker process returned an unparseable WorkResponse` error tips, but different  jar error, What should i do?

first: GenClass.jar failed
<pre>
ERROR: /home/xzy/bazel-0.5.0rc9/src/java_tools/buildjar/
java/com/google/devtools/build/buildjar/genclass/BUILD:10:1: 
Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/
genclass/GenClass.jar () failed: Worker process returned an unparseable WorkResponse
second: `libpackage_manifest_java_proto.jar` failed
</pre>
second: `libpackage_manifest_java_proto.jar` failed
<pre>
ERROR: /tmp/bazel-0.5.0rc9/src/main/protobuf/BUILD:24:2: 
Building src/main/protobuf/libpackage_manifest_java_proto.jar (1 source jar) failed: 
Worker process returned an unparseable WorkResponse
</pre>
third: `liboptions.jar` failed
<pre>
ERROR: /tmp/bazel-0.5.0rc9/src/main/java/com/google/devtools/common/options/BUILD:6:1: 
Building src/main/java/com/google/devtools/common/options/liboptions.jar:
 Worker process returned an unparseable WorkResponse
</pre>
``

**Comment by laszlocsomor** [comment]
@xzy256 : Could you try @aehlig 's suggestion in https://github.com/bazelbuild/bazel/issues/1955#issuecomment-305157094 ?

**Comment by xzy256** [comment]
i have a try, thank you.

**Comment by xzy256** [comment]
@laszlocsomor I have built successful. you can see  [build-bazel-mips64.patch](https://github.com/xzy256/bazel-mips64/blob/master/build-bazel-mips.patch) for  mips64 arch support. Please close this issues.Thanks.
