### ISSUE TITLE
Crash when rule has too many attributes

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3098]
### Description of the problem / feature request / question:

Just hit that error:

    java.lang.AssertionError: can't pack 320 rule indices into bytes
	at com.google.devtools.build.lib.packages.AttributeContainer.<init>(AttributeContainer.java:67)
	at com.google.devtools.build.lib.packages.AttributeContainer.<init>(AttributeContainer.java:59)
	at com.google.devtools.build.lib.packages.AttributeContainer$1.apply(AttributeContainer.java:233)
	at com.google.devtools.build.lib.packages.AttributeContainer$1.apply(AttributeContainer.java:230)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:711)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:725)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:79)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:725)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:224)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:197)
	at com.google.devtools.build.lib.packages.PackageFactory.prefetchGlobs(PackageFactory.java:1780)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1341)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1216)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:510)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    java.lang.AssertionError: can't pack 320 rule indices into bytes
	at com.google.devtools.build.lib.packages.AttributeContainer.<init>(AttributeContainer.java:67)
	at com.google.devtools.build.lib.packages.AttributeContainer.<init>(AttributeContainer.java:59)
	at com.google.devtools.build.lib.packages.AttributeContainer$1.apply(AttributeContainer.java:233)
	at com.google.devtools.build.lib.packages.AttributeContainer$1.apply(AttributeContainer.java:230)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:711)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:725)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:79)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:739)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:725)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:224)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:197)
	at com.google.devtools.build.lib.packages.PackageFactory.prefetchGlobs(PackageFactory.java:1780)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1341)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1216)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:510)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This is probably due to my workaround here: https://stackoverflow.com/questions/43396925/emulate-string-to-label-dict/43472871

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.5.0

**Comment by abergmeier-dsfishlabs** [comment]
For now decreased `_INDEX_COUNT ` to 20 and it works.

**Comment by laszlocsomor** [comment]
I guess this is largely WAI -- rules don't tend to have more than a couple dozen attributes.
The uncaught exception is definitely not WAI.

**Comment by abergmeier-dsfishlabs** [comment]
@dslomov What is the status of `string_keyed_label_dict`? With that limit, the workaround no longer holds.

**Comment by laszlocsomor** [comment]
@abergmeier-dsfishlabs : FYI @dslomov is out on vacation, maybe @laurentlb can answer

**Comment by abergmeier-dsfishlabs** [comment]
Just occured to me that a `label_keyed_string_list_dict` would probably work, too.

**Comment by laurentlb** [comment]
There seems to be a limit of 254 attributes.
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/AttributeContainer.java#L64
We should at least improve the error message and document it.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
