### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3145]
### Description of the problem / feature request / question:

When trying to build a target I get:

    java.lang.IllegalArgumentException: value already present: C:\projects\tools\baz                                                                       el-tools\bazel-out
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$Watc                                                                       herFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:293)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$Watc                                                                       herFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:263)
        at java.nio.file.Files.walkFileTree(Files.java:2677)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.regi                                                                       sterSubDirectoriesAndReturnContents(WatchServiceDiffAwareness.java:258)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.coll                                                                       ectChanges(WatchServiceDiffAwareness.java:242)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.getC                                                                       urrentView(WatchServiceDiffAwareness.java:124)
        at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(D                                                                       iffAwarenessManager.java:92)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.hand                                                                       leDiffs(SequencedSkyframeExecutor.java:364)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync                                                                       (SequencedSkyframeExecutor.java:291)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackage                                                                       Cache(CommandEnvironment.java:504)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildT                                                                       ool.java:137)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(Buil                                                                       dTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(Buil                                                                       dCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExcl                                                                       usively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(Bla                                                                       zeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExe                                                                       cutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(Gr                                                                       pcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcS                                                                       erverImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServe                                                                       rImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                       java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                       .java:617)
        at java.lang.Thread.run(Thread.java:745)
    java.lang.IllegalArgumentException: value already present: C:\projects\tools\baz                                                                       el-tools\bazel-out
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$Watc                                                                       herFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:293)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$Watc                                                                       herFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:263)
        at java.nio.file.Files.walkFileTree(Files.java:2677)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.regi                                                                       sterSubDirectoriesAndReturnContents(WatchServiceDiffAwareness.java:258)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.coll                                                                       ectChanges(WatchServiceDiffAwareness.java:242)
        at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.getC                                                                       urrentView(WatchServiceDiffAwareness.java:124)
        at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(D                                                                       iffAwarenessManager.java:92)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.hand                                                                       leDiffs(SequencedSkyframeExecutor.java:364)
        at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync                                                                       (SequencedSkyframeExecutor.java:291)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackage                                                                       Cache(CommandEnvironment.java:504)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildT                                                                       ool.java:137)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(Buil                                                                       dTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(Buil                                                                       dCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExcl                                                                       usively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(Bla                                                                       zeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExe                                                                       cutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(Gr                                                                       pcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcS                                                                       erverImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServe                                                                       rImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                       java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                       .java:617)
        at java.lang.Thread.run(Thread.java:745)

and a whole lot of other problems and error messages.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.5.1

###  Have you found anything relevant by searching the web?
Nope

**Comment by laszlocsomor** [comment]
Please attach the whole output, the culprit thread's stacktrace was further down.

**Comment by katre** [comment]
Also please give us the command you're using to invoke Bazel, and what is being built.

**Comment by laszlocsomor** [comment]
Please reopen if occurs again, and include more data to repro.
