### ISSUE TITLE
Bazel does not work with server being on other partition

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3146]
### Description of the problem / feature request / question:

I have a `/` EXT4 partition on a HDD in my computer due to file storage size requirements.
For speed reasons I decided to mount `~/.cache` to a XFS-partition on a SSD.
Deleting the `install` directory  and starting a build then gives me:

    Extracting Bazel installation...
    ..
    unexpected pipe read status: (error: 2): No such file or directory
    Server presumed dead. Now printing '/home/andreas/.cache/bazel/_bazel_andreas/384827ac61ea21f490af9da32681de43/server/jvm.out':
    JNI initialization failed: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: failed to map segment from shared object.  Possibly your installation has been corrupted.
    java.lang.UnsatisfiedLinkError: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
	at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1050)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1039)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1032)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
    <unknown> crash in async thread:
    java.lang.UnsatisfiedLinkError: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: /home/andreas/.cache/bazel/_bazel_andreas/install/4b8ade83fd7fa3e82009c0fe0d055d63/_embedded_binaries/libunix.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
	at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1050)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1039)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1032)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.1

**Comment by katre** [comment]
Are we using hard links in the sandbox? That might account for it.

**Comment by philwo** [comment]
Hi @katre,

no, the sandbox only uses symlinks. Can you please paste the output of "mount" here?

Thanks,
Philipp

**Comment by abergmeier-dsfishlabs** [comment]
I think the problem **might** have been the `noexec` flag in the mount options, which gets implicitly added by `user`. Will test after next reboot, whether this indeed makes it work or not.

**Comment by philwo** [comment]
@abergmeier-dsfishlabs Yes, I think that is the reason.

**Comment by abergmeier-dsfishlabs** [comment]
The setup is now a little different but it works now. So it is very likely that it was the `noexec` option.
