### ISSUE TITLE
Java worker process build failed 

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#3154]
Console output:

```
ERROR: /usr/local/google/home/lberki/bazel/gerrit/gerrit-reviewdb/BUILD:24:1: Building gerrit-reviewdb/libserver-class.jar (50 source files) failed: Worker process sent response with exit code: 1.
java.nio.file.FileAlreadyExistsException: bazel-out/local-fastbuild/coverage-metadata/com/google/gerrit/reviewdb/client
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$1.visitFile(JacocoInstrumentationProcessor.java:106)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$1.visitFile(JacocoInstrumentationProcessor.java:91)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.instrumentRecursively(JacocoInstrumentationProcessor.java:89)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.processRequest(JacocoInstrumentationProcessor.java:80)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:112)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:121)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:89)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:66)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Target //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/ssh:ssh failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.149s, Critical Path: 2.79s
```

Upon next try (with unchanged arguments) it worked. The command like I was running was `bazel coverage` one from HEAD but I managed to lose it :(

```
```

**Comment by lberki** [comment]
@iirina

**Comment by gautamraj** [comment]
I also see this often when running with code coverage turned on (bazel coverage //...). The problem goes away when I run with --jobs=1

**Comment by philwo** [comment]
This can only happen when the file it complains about (bazel-out/local-fastbuild/coverage-metadata/com/google/gerrit/reviewdb/client) already exists, but is not a directory. It might be a symlink, for example.

If you can reproduce this, please send the entire command-line and bazelrc. I'm not 100% sure that it is a worker specific problem.

**Comment by ahirreddy** [comment]
I'm seeing a similar error
```
ERROR: /var/lib/jenkins/workspace/Unit/Master/webapp/BUILD:193:1: Couldn't build file webapp/libwebapp_java-class.jar: Building webapp/libwebapp_java-class.jar (2 source files) failed (Exit 1)
java.nio.file.DirectoryNotEmptyException: bazel-out/local-fastbuild/coverage-metadata/com/spotify/docker
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$2.postVisitDirectory(JacocoInstrumentationProcessor.java:153)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$2.postVisitDirectory(JacocoInstrumentationProcessor.java:143)
	at java.nio.file.Files.walkFileTree(Files.java:2688)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.recursiveRemove(JacocoInstrumentationProcessor.java:141)
	at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.processRequest(JacocoInstrumentationProcessor.java:79)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.buildJar(SimpleJavaLibraryBuilder.java:141)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:119)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
```

This is running with coverage and Java workers enabled.

**Comment by vcase** [comment]
I'm experiencing this issue on Ubuntu and Centos-7.  I don't see in on MacOS.

**Comment by jmmv** [comment]
Closing given the lack of a repro case... if you have one, please reopen with the details.
