### ISSUE TITLE
bazel_bootstrap_distfile_test broken on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3186]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/825/console
```
Caused by: java.lang.IllegalStateException: "bazel.windows_unix_root" JVM flag is not set. Use the --host_jvm_args flag or export the BAZEL_SH environment variable. For example "--host_jvm_args=-Dbazel.windows_unix_root=c:/tools/msys64" or "set BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe". parent=(/) name=(usr)
	at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.getCachedChildPathInternalImpl(WindowsFileSystem.java:137)
	at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.access$300(WindowsFileSystem.java:89)
	at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory$1.getCachedChildPathInternal(WindowsFileSystem.java:104)
	at com.google.devtools.build.lib.vfs.Path.getCachedChildPath(Path.java:299)
	at com.google.devtools.build.lib.vfs.Path.getCanonicalPath(Path.java:669)
	at com.google.devtools.build.lib.vfs.Path.getRelative(Path.java:705)
	at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:148)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getPermittedSystemIncludePrefixes(CppCompileAction.java:1288)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.discoverInputsFromDotdFiles(CppCompileAction.java:1254)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1193)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:803)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:746)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:103)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:648)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:605)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:395)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more

ERROR: Could not build Bazel
```

Looks like the culprit is: 9c54e2a764f0ddd2d3787aade1c530c5f43bd26c 
@laszlocsomor Can you fix this?

**Comment by laszlocsomor** [comment]
Yes, I'll fix it right away!

**Comment by laszlocsomor** [comment]
Ah, I know the problem: after commit https://github.com/bazelbuild/bazel/commit/9c54e2a764f0ddd2d3787aade1c530c5f43bd26c it's the client's job to pass the `--host_jvm_args=-Dbazel.windows_unix_root=<path>` flag to the server, but while bootstrapping bazel we run it in client-less mode (run the jar directly).
