### ISSUE TITLE
Android: update //third_party/android_common/*.jar

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3190]
The files under `//third_party/android_common` haven't been updated in 6 months / 1 year.

`third_party/android_common/com.android.tools_sdk-common_25.0.0.jar` in particular contains `com/android/ide/common/res2/MergingException.class` which uses a deprecated Guava method, `com.google.common.base.Objects.firstNonNull` that is no longer available in Guava. `//third_party/guava/guava-21.0-20161101.jar` still contains this method but `//third_party/guava/guava-21.0` doesn't.

I'm hacking on Bazel to try and build Android rules on Windows and apparently end up with the new Guava jar on the classpath, because I'm hitting this code path:
```
  cd C:/tmp1/0qdpngxr/execroot/bazel-examples
bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.cmd --tool PARSE -- --primaryData tutorial/android/src/main/java/com/google/bazel/example/android/activities/res: --output bazel-out/msvc_x64-fastbuild/bin/tutorial/android/activities_symbols/merged.bin: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:129)
        at com.google.devtools.build.android.ParsedAndroidData$Builder.checkForErrors(ParsedAndroidData.java:92)
        at com.google.devtools.build.android.ParsedAndroidData$Builder.build(ParsedAndroidData.java:101)
        at com.google.devtools.build.android.ParsedAndroidData$ParsedAndroidDataBuildingPathWalker.createParsedAndroidData(ParsedAndroidData.java:238)
        at com.google.devtools.build.android.ParsedAndroidData.from(ParsedAndroidData.java:374)
        at com.google.devtools.build.android.AndroidResourceParsingAction.main(AndroidResourceParsingAction.java:70)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$5.call(ResourceProcessorBusyBox.java:77)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:137)
```

**Comment by laszlocsomor** [comment]
@ahumesky , @dslomov : FYI

**Comment by laszlocsomor** [comment]
This could be related to https://github.com/bazelbuild/bazel/issues/3137

**Comment by aj-michael** [comment]
I reported this in https://github.com/bazelbuild/bazel/issues/2709, which is marked as Fixed now which is likely why you didn't find it.

Does your Bazel tree contain the commit that "fixed" that issue?

IIRC correctly, even the newest version of this library depends on an older version of guava than we use in Bazel. So there is not a clear solution here.

**Comment by aj-michael** [comment]
http://mvnrepository.com/artifact/com.android.tools/common/25.3.0

This is the newest version published: it was built against guava 18.

**Comment by laszlocsomor** [comment]
Thanks for the bug reference!

> Does your Bazel tree contain the commit that "fixed" that issue?

I was using Bazel release 0.5.1 which apparently doesn't yet contain the fix.
I just tried with Bazel built from HEAD and that works. Thanks!

**Comment by wiyarmir** [comment]
Hi, any news on when is this going to be synched to public? `master` is still on those old ones 😢
