### ISSUE TITLE
Run bazel command failed with bazel-0.5.0-jdk7 or bazel-0.5.1-jdk7

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/bazel#3198]
### Description of the problem / feature request / question:

After I installed bazel successfullu by using binary installer(bazel-0.5.0-jdk7-installer-linux-x86_64.sh), I have an error when I run any bazel command. And the 0.5.1-jdk7 has the same error.

### If possible, provide a minimal example to reproduce the problem:
```
root@XX:~# bazel version
Extracting Bazel installation...
java.lang.UnsupportedClassVersionError: com/google/protobuf/MessageOrBuilder : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.google.devtools.build.lib.runtime.ServerBuilder.<init>(ServerBuilder.java:39)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1157)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1010)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:753)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:561)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)

```

### Environment info
* Operating System:
ubuntu14.04

* Bazel version (output of `bazel info release`):
0.5.0 or 0.5.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
Running `bazel info release` shows the same error.

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
No.

**Comment by meteorcloudy** [comment]
@ulfjack Do you know how jdk7 Bazel works or someone who knows?

**Comment by ulfjack** [comment]
It suspect someone updated our protobuf libraries to a version that requires Jdk 8.

**Comment by ulfjack** [comment]
Last upgrade was 0acead4ea3631240659836ce6ecd6d7f67fd352b.

**Comment by ulfjack** [comment]
$ javap -v -cp third_party/protobuf/3.2.0/libprotobuf_java.jar com.google.protobuf.MessageOrBuilder | grep "major"
  major version: 52

**Comment by buchgr** [comment]
Good catch! Protobuf java only requires Java 6. S it seems like the .jar artifacts where built with a Java 8's javac compiler without `-target 1.7` specified. I ll update the jars with properly compiled ones.

**Comment by buchgr** [comment]
@GinFungYJF hey! please try again with a bazel built from latest master!

**Comment by GinFungYJF** [comment]
@buchgr But how to build a bazel-jdk7 form the latest master instead of the distribution?

**Comment by GinFungYJF** [comment]
I think this issue should be reopened as the bazel-0.5.2-jdk7 has the same error after I installed it with the bazel-0.5.2-jdk7-installer-linux-x86_64.sh.

**Comment by philwo** [comment]
@ulfjack What shall I do with this bug?

@GinFungYJF Could you use the Bazel version that comes with a bundled OpenJDK8 instead? You can download it from our releases page: [bazel-0.5.2-installer-linux-x86_64.sh](https://github.com/bazelbuild/bazel/releases/download/0.5.2/bazel-0.5.2-installer-linux-x86_64.sh).

**Comment by damienmg** [comment]
We had only 1 bug report for that and the problem has been there for 1 month now. As announced before 0.5.0 we were going to remove support for JDK-7 build, please use the installer with OpenJDK8 bundled instead.

Next release won't have JDK-7 builds anymore, see https://www.bazel.build/blog/2017/04/21/JDK7-deprecation.html

**Comment by philwo** [comment]
Closing because it's obsolete with Bazel 0.5.2 being released and a version with bundled OpenJDK 8 being available.

@GinFungYJF Please let us know if the version with bundled OpenJDK 8 is not usable for you. We would really like to get Bazel to work for you.
