### ISSUE TITLE
Turbine: Jimfs exception on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3220]
### Description of the problem / feature request / question:

Turbine reliably crashes on Windows with a certain invalid java file.

### If possible, provide a minimal example to reproduce the problem:

1. Clone the Bazel repo (`git clone https://github.com/bazelbuild/bazel`)

2. Check out current HEAD (baf7d4bce8bb14d785760d10694122e8ead2a177)

3. Edit `src\tools\android\java\com\google\devtools\build\android\ResourceProcessorBusyBox.java`:

```
diff --git a/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.java b/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.java
index 59f0aeb..c10f4a3 100644
--- a/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.java
+++ b/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.java
@@ -134,6 +134,8 @@ public class ResourceProcessorBusyBox {
     public Tool tool;
   }

+  private static void foo() throws Foo {}
+
   public static void main(String[] args) throws Exception {
     OptionsParser optionsParser = OptionsParser.newOptionsParser(Options.class);
     optionsParser.setAllowResidue(true);
```

4. `bazel build //src/tools/android/java/com/google/devtools/build/android:classes_deploy.jar`
Fails as expected:

```
ERROR: (12:21:16.423) C:/work/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:31:1: Building src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib.jar (71 source files) failed: Worker process sent response with exit code: 1.
src\tools\android\java\com\google\devtools\build\android\ResourceProcessorBusyBox.java:137: error: cannot find symbol
  private static void foo() throws Foo {}
                                   ^
  symbol:   class Foo
  location: class ResourceProcessorBusyBox
Target //src/tools/android/java/com/google/devtools/build/android:classes_deploy.jar failed to build
```

5. `bazel build //src/tools/android/java/com/google/devtools/build/android:embedded_tools`
Crashes, not expected:

```
ERROR: (12:21:27.135) C:/work/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:31:1: Compiling Java headers src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib-hjar.jar (71 files) failed: java.exe failed: error executing command
  cd C:/tmp1/o6hbs7n0/execroot/bazel
  SET LC_CTYPE=en_US.UTF-8
  external/local_jdk/bin/java.exe -Xverify:none -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9-dev-r4023-2.jar -jar external/bazel_tools/tools/jdk/turbine_deploy.jar @bazel-out/msvc_x64-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib-hjar.jar-2.params: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
java.nio.file.InvalidPathException: Jimfs does not currently support the Windows syntax for an absolute path on the current drive (e.g. "\foo\bar": /classes
        at com.google.common.jimfs.WindowsPathType.parsePath(WindowsPathType.java:79)
        at com.google.common.jimfs.PathService.parsePath(PathService.java:209)
        at com.google.common.jimfs.JimfsFileSystem.getPath(JimfsFileSystem.java:270)
        at com.google.common.jimfs.JimfsFileSystem.getPath(JimfsFileSystem.java:171)
        at com.google.devtools.build.java.turbine.javac.JavacTurbineCompiler.compile(JavacTurbineCompiler.java:71)
        at com.google.devtools.build.java.turbine.javac.JavacTurbine.compile(JavacTurbine.java:197)
        at com.google.devtools.build.java.turbine.javac.JavacTurbine.compile(JavacTurbine.java:79)
        at com.google.devtools.build.java.turbine.Turbine.javacTurbineCompile(Turbine.java:74)
        at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:62)
        at com.google.devtools.build.java.turbine.Turbine.main(Turbine.java:33)
```

### Environment info
* Operating System: Windows 10

* Bazel version: 0.5.1 msvc

**Comment by cushon** [comment]
This looks like #2977, which was supposed to be fixed by 17296dade40a2094672e79978d4602d6704dfcc3. It looks like that change missed the baseline for 0.5.1 and wasn't cherry-picked.

Does the crash reproduce if you build Bazel at head?
