### ISSUE TITLE
Bazel crash on BES upload if the service requires TLS

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3223]
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

Technically, this is an issue with netty not catching this properly. buchgr@ promised to fix this in netty; this bug is a reminder for buchgr@ and to make it discoverable for Bazel users.

**Comment by ulfjack** [comment]
The right fix is to pass --tls_enabled if the remote end point requires TLS. We just need a better error message from netty or Bazel in this case.

**Comment by lfpino** [comment]
Encountered this cryptic message when passed an invalid bes_backend address.

**Comment by lfpino** [comment]
The full trace:
```
ERROR: The Build Event Protocol upload failed: INTERNAL: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
INFO: Build completed successfully, 1 total action
Remote logging disabled for testing, forcing abrupt shutdown.
com.google.devtools.build.lib.util.LoggingUtil#logToRemote: BES close failure
java.util.concurrent.ExecutionException: io.grpc.StatusException: INTERNAL: http2 exception
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:557)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:436)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:99)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:292)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.lambda$startCloseTimer$3(BuildEventServiceUploader.java:635)

	at java.base/java.lang.Thread.run(Thread.java:844)
INFO: Build completed successfully, 1 total action
Caused by: io.grpc.StatusException: INTERNAL: http2 exception
	at io.grpc.Status.asException(Status.java:540)
	at com.google.devtools.build.lib.buildeventservice.client.BuildEventServiceGrpcClient.publish(BuildEventServiceGrpcClient.java:77)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishLifecycleEvent(BuildEventServiceUploader.java:582)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.run(BuildEventServiceUploader.java:258)

Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)------------------------------------------------------------------------
test_bes_client_restart FAILED: Expected regexp 'foo' is not recognized not found .

```

**Comment by meisterT** [comment]
I think this is fixed at HEAD.
