### ISSUE TITLE
Adding cpu to execution_requirements leads to failing worker

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3232]
### Description of the problem / feature request / question:

We have a worker which works fine:

    ctx.action(
        outputs = [output],
        inputs = inputs,
        executable = builder,
        arguments = arguments,
        execution_requirements = {
            "supports-workers": "1",
        },
    )

When I additionally add the requirement

            "cpu:3": "",

communication with the worker fails:

    Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

    ---8<---8<--- Exception details ---8<---8<---
    java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.execInWorker(WorkerSpawnStrategy.java:319)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.actuallyExec(WorkerSpawnStrategy.java:182)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.exec(WorkerSpawnStrategy.java:131)
	at com.google.devtools.build.lib.worker.WorkerSpawnStrategy.exec(WorkerSpawnStrategy.java:104)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    ---8<---8<--- End of exception details ---8<---8<---

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.1

###  Have you found anything relevant by searching the web?
Nope

**Comment by philwo** [comment]
That's pretty amazing and I have no idea what could cause this. I'll investigate. 😳

**Comment by abergmeier-dsfishlabs** [comment]
I now had this error even without the cpu arg. So this is probably a corruption rather than connected to that flag.
