### ISSUE TITLE
remote_worker fails in the most mysterious ways when run as a deploy jar

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3249]
First an easy one, it doesn't load the unix JNI library when run via a deploy jar:

```bash
philwo@philwo:~/src/bazel (master)$ rm -rf /usr/local/google/tmp/worker
philwo@philwo:~/src/bazel (master)$ mkdir /usr/local/google/tmp/worker
philwo@philwo:~/src/bazel (master)$ bazel build //src/tools/remote_worker:remote_worker_deploy.jar
philwo@philwo:~/src/bazel (master)$ java -jar bazel-bin/src/tools/remote_worker/remote_worker_deploy.jar --work_path=/usr/local/google/tmp
INFO: Analysed target //src/tools/remote_worker:remote_worker_deploy.jar (0 packages loaded).
INFO: Found 1 target...
Target //src/tools/remote_worker:remote_worker_deploy.jar up-to-date:
  bazel-bin/src/tools/remote_worker/remote_worker_deploy.jar
INFO: Elapsed time: 2.258s, Critical Path: 2.06s
INFO: Build completed successfully, 2 total actions
170622 15:13:29.246:I 1 [com.google.devtools.build.remote.RemoteWorker.main] Initializing in-memory cache server.
170622 15:13:29.250:W 1 [com.google.devtools.build.remote.RemoteWorker.main] Not using remote cache. This should be used for testing only!
Exception in thread "main" java.lang.UnsatisfiedLinkError: no unix in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.NativePosixFiles.<clinit>(NativePosixFiles.java:136)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createDirectory(UnixFileSystem.java:310)
	at com.google.devtools.build.lib.vfs.Path.createDirectory(Path.java:829)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParentsWithCache(FileSystemUtils.java:692)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:652)
	at com.google.devtools.build.remote.RemoteWorker.<init>(RemoteWorker.java:85)
	at com.google.devtools.build.remote.RemoteWorker.main(RemoteWorker.java:170)
```

OK, commenting that out so that it uses JavaIoFileSystem we get further and extremely weird errors during a build:

```bash
philwo@philwo:~/src/bazel (master)$ rm -rf /usr/local/google/tmp/worker
philwo@philwo:~/src/bazel (master)$ mkdir /usr/local/google/tmp/worker
philwo@philwo:~/src/bazel (master)$ bazel build //src/tools/remote_worker:remote_worker_deploy.jar
philwo@philwo:~/src/bazel (master)$ java -jar bazel-bin/src/tools/remote_worker/remote_worker_deploy.jar --work_path=/usr/local/google/tmp
[...]
170622 15:14:52.938:I 1 [com.google.devtools.build.remote.RemoteWorker.main] Initializing in-memory cache server.
170622 15:14:52.943:W 1 [com.google.devtools.build.remote.RemoteWorker.main] Not using remote cache. This should be used for testing only!
170622 15:14:53.066:I 1 [com.google.devtools.build.remote.RemoteWorker.startServer] Starting gRPC server on port 8080.

philwo@philwo:~/src/bazel (master)$ bazel --host_jvm_args=-Dbazel.DigestFunction=SHA1 --blazerc=/dev/null build --spawn_strategy=remote --strategy=Javac=remote --remote_cache=localhost:8080 --remote_executor=localhost:8080 //src:bazel
[...]
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "0c73037e90c21d3a7533aafc5d9c3bb2b793cc69"
size_bytes: 1679
 does not match computed digest hash: "9101deb151a8c13f3cb8e2a4dda3da05"
size_bytes: 1679
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "58479428b3ca345000ea0c4f434447f033a403c5"
size_bytes: 1691
 does not match computed digest hash: "6e060d468f449ad413d19981de2a9a32"
size_bytes: 1691
).
ERROR: /usr/local/google/home/philwo/.cache/bazel/_bazel_but_philwo/591320842d308bc057c7950eeb368324/external/com_google_protobuf/BUILD.bazel:233:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "58479428b3ca345000ea0c4f434447f033a403c5"
size_bytes: 1691
 does not match computed digest hash: "6e060d468f449ad413d19981de2a9a32"
size_bytes: 1691
.
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "243c4aba3fa42fc6e2ec360169d7dd0683f96e29"
size_bytes: 1683
 does not match computed digest hash: "e8b7801be6e4d508f9b1f83edf0532e8"
size_bytes: 1683
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "c66a98af5f1185670c7577231828e49ee08e7497"
size_bytes: 1687
 does not match computed digest hash: "1f8b692c0ef1c6468f23b68924f82909"
size_bytes: 1687
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "754a004e743d653028e3e87c47ae06e2742fedca"
size_bytes: 1655
 does not match computed digest hash: "c04eeb2404869e30625c8dc720f1f890"
size_bytes: 1655
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "cfbf6f53b560254b3ad7e1395228197214d14d96"
size_bytes: 1655
 does not match computed digest hash: "2034f56f3e4e138e338fc37e7507d15a"
size_bytes: 1655
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "ecc40c8fb72fefa72a9f30a7e23ec6fbead7c6e6"
size_bytes: 1710
 does not match computed digest hash: "8c3e32fa5977f31539ea0b55459f591e"
size_bytes: 1710
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): resource_name: Received digest hash: "4b9037da73a64a27a3aad37013823fc4fb72551b"
size_bytes: 1671
 does not match computed digest hash: "77cc1c83ce51acbb629c9a1a22256b21"
size_bytes: 1671
).
WARNING: CppCompile remote work failed (io.grpc.StatusRuntimeException: CANCELLED).
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.042s, Critical Path: 0.31s
```

**Comment by philwo** [comment]
FYI @ola-rozenfeld

**Comment by philwo** [comment]
Oh, and the remote_worker logs these interesting errors when running as a deploy jar:

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 51
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:127)
	at io.grpc.netty.FixedHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(FixedHttp2ConnectionDecoder.java:570)
	at io.grpc.netty.FixedHttp2ConnectionDecoder$FrameReadListener.onDataRead(FixedHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:425)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.grpc.netty.FixedHttp2ConnectionDecoder.decodeFrame(FixedHttp2ConnectionDecoder.java:119)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:341)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ola-rozenfeld** [comment]
It does that when run regularly as well. This is a weird intermittent error
that I'm trying to get to the bottom of. In any case, I think it is
retriable, so the patch I'm preparing right now (retry logic in Bazel)
should drastically cut down the consequences of it.

**Comment by ola-rozenfeld** [comment]
Btw, the digests errors are likely because the "-Dbazel.DigestFunction=SHA1" argument does not apply when you execute a deploy jar. You will likely need to specify it on the command line.

**Comment by jmillikin-stripe** [comment]
I'm hitting the original JNI issue also, and the workaround of commenting out the JNI bits worked for me.

What's the JNI filesystem implementation get us over the JavaIO implementation? Performance? I'd suggest either adding a flag to control which implementation is used, or detect the JNI failure and fall back to JavaIO at initialization time.

If someone in Bazel land can review the PR, I'd be happy to do whichever approach you'd prefer.

**Comment by ulfjack** [comment]
I'd just use the JavaIO implementation for now. It's certainly an important performance difference for Bazel, but I'd be surprised if it was a big issue for the remote worker.
