### ISSUE TITLE
Bazel analyze-profile crashes outside of a workspace

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3256]
I think that's a recent regression.

**Comment by ulfjack** [comment]
```
$ bazel analyze-profile profile
java.lang.NullPointerException
	at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:251)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:552)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:331)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:760)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
java.lang.NullPointerException
	at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:251)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:552)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:331)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:760)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
```
