### ISSUE TITLE
NullPointerException on IJWB update

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3331]
Reported by @harmank in #3196:
```
..............
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes 'REPOSITORY:@local_config_xcode')
  | at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.NullPointerException: null value in entry: =null
  | at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
  | at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:73)
  | at com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:50)
  | at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:418)
  | at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:391)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkOS.<init>(SkylarkOS.java:37)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.<init>(SkylarkRepositoryContext.java:96)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:64)
  | at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:154)
  | at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)
  | ... 4 more
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_xcode' (requested by nodes 'REPOSITORY:@local_config_xcode')
  | at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.NullPointerException: null value in entry: =null
  | at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
  | at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:73)
  | at com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:50)
  | at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:418)
  | at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:391)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkOS.<init>(SkylarkOS.java:37)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.<init>(SkylarkRepositoryContext.java:96)
  | at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:64)
  | at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:154)
  | at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)
  | ... 4 more
```

**Comment by katre** [comment]
SkylarkOS is copying the client environment variables, and finding this invalid value, which then fails because ImmutableMap can't handle null values. We need to clean the environment before using it.

**Comment by ulfjack** [comment]
Where does it get them from? In some contexts, null values imply that we
should take the value from the client environment.

**Comment by katre** [comment]
This is a null value in the client environment, from reading the stack trace.

**Comment by ulfjack** [comment]
Oh, I see. Then this issue can only happen with the patch I posted in #3196, and is not actually an issue with any of the checked-in code in Bazel.
