### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:remote-tests failing on Linux on CI

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3348]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/867/console

```
INFO: Discarding analysis cache: configurations have changed.
........E..................................................
Time: 27.127
There was 1 failure:
1) sameBlobShouldNotBeUploadedTwice(com.google.devtools.build.lib.remote.ByteStreamUploaderTest)
java.lang.AssertionError: Not true that <com.google.common.util.concurrent.SettableFuture@275a3d2f> is the same instance as <com.google.common.util.concurrent.SettableFuture@510d214>
	at com.google.devtools.build.lib.remote.ByteStreamUploaderTest.sameBlobShouldNotBeUploadedTwice(ByteStreamUploaderTest.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
Caused by: java.lang.AssertionError: Not true that <com.google.common.util.concurrent.SettableFuture@275a3d2f> is the same instance as <com.google.common.util.concurrent.SettableFuture@510d214>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:348)
	at com.google.common.truth.Subject.isSameAs(Subject.java:153)
	... 10 more

FAILURES!!!
Tests run: 80,  Failures: 1
```

**Comment by laszlocsomor** [comment]
Attempting to repro locally.

**Comment by laszlocsomor** [comment]
Culprit: https://github.com/bazelbuild/bazel/commit/dc24004873c33568e10a572f8b8b2c667854520a

**Comment by laszlocsomor** [comment]
@buchgr : I can repro this with bazel 0.5.2 on Linux

**Comment by buchgr** [comment]
Looking ...

**Comment by buchgr** [comment]
I can repo the failure, but I can see that it's theoretically possible. Working on a fix.
