### ISSUE TITLE
Windows, CI: bazel-tests broken

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3355]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/870/console

```
____[2,553 / 2,576] PackageTar bazel-srcs.tar
ERROR: C:/jenkins/workspace/bazel-tests/bazel_version/head/platform_name/windows-x86_64/BUILD:63:1: Couldn't build file bazel-srcs.tar: error executing shell command: 'bazel-out/host/bin/tools/build_defs/pkg/build_tar --flagfile=bazel-out/msvc_x64-fastbuild/bin/bazel-srcs.args' failed (Exit 1): bash.exe failed: error executing command 
    SET NO_MSVC_WRAPPER=1
    SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;c:\tools\msys64\usr\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep\;C:\Program Files\Google\Compute Engine\metadata_scripts\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;;;C:\ProgramData\chocolatey\bin;;c:\python_27_amd64\files;C:\Program Files\Java\jdk1.8.0_131\bin;
    SET TMPDIR=c:\bazel_ci\temp
  C:/tools/msys64/usr/bin/bash.exe -c bazel-out/host/bin/tools/build_defs/pkg/build_tar --flagfile=bazel-out/msvc_x64-fastbuild/bin/bazel-srcs.args.
Traceback (most recent call last):
  File "c:\bazel_ci\temp\Bazel.runfiles_iynghp\runfiles\io_bazel\tools\build_defs\pkg\build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "c:\bazel_ci\temp\Bazel.runfiles_iynghp\runfiles\io_bazel\third_party\py\gflags\__init__.py", line 1, in <module>
    from gflags import *
  File "c:\bazel_ci\temp\Bazel.runfiles_iynghp\runfiles\io_bazel\third_party\py\gflags\gflags\__init__.py", line 58, in <module>
    import six
ImportError: No module named six
```

**Comment by laszlocsomor** [comment]
Now it's gone -- let's reopen if it occurs again.
Could've been caused by the recent Jenkins master volume fillup (https://github.com/bazelbuild/continuous-integration/issues/88) or could've been a flake, I don't know.
