### ISSUE TITLE
Bazel crash using new_http_archive

### ISSUE THREAD

**Issue by mikelalcon** [bazelbuild/bazel#3364]
```
[master] ~/dev/bazel$ bazel version
.............
Build label: 0.5.1
Build target: bazel-out/darwin_x86_64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 10:39:21 2017 (1496745561)
Build timestamp: 1496745561
Build timestamp as int: 1496745561
<o> [master] ~/dev/bazel$

git clone github.com/google/copybara

Replace in WORSKPACE:


http_archive(
    name = "io_bazel",
    # TODO(copybara-team): Revisit to try to depend on a tag instead
    # Currently we depend on a specific commit, otherwise the sha-256 would be changing all the
    # times.
    url = "https://github.com/bazelbuild/bazel/archive/b13457b1434d64ab187fb511e73f01d1f2321c1e.zip",
    strip_prefix = "bazel-b13457b1434d64ab187fb511e73f01d1f2321c1e",
)

with:

http_archive(
    name = "io_bazel",
    # TODO(copybara-team): Revisit to try to depend on a tag instead
    # Currently we depend on a specific commit, otherwise the sha-256 would be changing all the
    # times.
    url = "https://github.com/bazelbuild/bazel/archive/77baa4c372ae014db8e17f6d3c60bd88597853d9.zip",
    strip_prefix = "bazel-77baa4c372ae014db8e17f6d3c60bd88597853d9",
)

http_archive(
    name = "com_google_protobuf",
    # TODO(copybara-team): Revisit to try to depend on a tag instead
    # Currently we depend on a specific commit, otherwise the sha-256 would be changing all the
    # times.
    url = "https://github.com/bazelbuild/bazel/archive/77baa4c372ae014db8e17f6d3c60bd88597853d9.zip",
    strip_prefix = "bazel-77baa4c372ae014db8e17f6d3c60bd88597853d9/third_party/protobuf/3.2.0",
)

http_archive(
    name = "com_google_protobuf",
    # TODO(copybara-team): Revisit to try to depend on a tag instead
    # Currently we depend on a specific commit, otherwise the sha-256 would be changing all the
    # times.
    url = "https://github.com/bazelbuild/bazel/archive/77baa4c372ae014db8e17f6d3c60bd88597853d9.zip",
    strip_prefix = "bazel-77baa4c372ae014db8e17f6d3c60bd88597853d9/third_party/protobuf/3.2.0",
)

new_http_archive(
    name = "com_google_protobuf_java",
    # TODO(copybara-team): Revisit to try to depend on a tag instead
    # Currently we depend on a specific commit, otherwise the sha-256 would be changing all the
    # times.
    url = "https://github.com/bazelbuild/bazel/archive/77baa4c372ae014db8e17f6d3c60bd88597853d9.zip",
    strip_prefix = "bazel-77baa4c372ae014db8e17f6d3c60bd88597853d9/third_party/protobuf/3.2.0",
#    build_file = str(Label("@com_google_protobuf_java//:com_google_protobuf_java.BUILD")),
    build_file = "@com_google_protobuf_java//:com_google_protobuf_java.BUILD"
)



Then run:

<o> [master] ~/dev/copybara$ bazel build //...
Unhandled exception thrown during build; message: topLevelKey: CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1722372393 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylarkinterface dd5461492e33c1bd61d975c1f1624c6b (596646116 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:util dd5461492e33c1bd61d975c1f1624c6b (1354491923 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:unix dd5461492e33c1bd61d975c1f1624c6b (228900030 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:vfs dd5461492e33c1bd61d975c1f1624c6b (564692026 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/common/options:options dd5461492e33c1bd61d975c1f1624c6b (39645139 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/protobuf:invocation_policy_java_proto dd5461492e33c1bd61d975c1f1624c6b (220755195 1680288934)
ASPECT:[]#BazelJavaProtoAspect dd5461492e33c1bd61d975c1f1624c6b dd5461492e33c1bd61d975c1f1624c6b {$injecting_rule_kind=[java_proto_library]}
PACKAGE:@com_google_protobuf_java//
cycle:
PACKAGE_LOOKUP:@com_google_protobuf_java//
REPOSITORY:@com_google_protobuf_java
REPOSITORY_DIRECTORY:@com_google_protobuf_java

INFO: Elapsed time: 6.314s
java.lang.IllegalStateException: topLevelKey: CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1722372393 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylarkinterface dd5461492e33c1bd61d975c1f1624c6b (596646116 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:util dd5461492e33c1bd61d975c1f1624c6b (1354491923 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:unix dd5461492e33c1bd61d975c1f1624c6b (228900030 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:vfs dd5461492e33c1bd61d975c1f1624c6b (564692026 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/common/options:options dd5461492e33c1bd61d975c1f1624c6b (39645139 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/protobuf:invocation_policy_java_proto dd5461492e33c1bd61d975c1f1624c6b (220755195 1680288934)
ASPECT:[]#BazelJavaProtoAspect dd5461492e33c1bd61d975c1f1624c6b dd5461492e33c1bd61d975c1f1624c6b {$injecting_rule_kind=[java_proto_library]}
PACKAGE:@com_google_protobuf_java//
cycle:
PACKAGE_LOOKUP:@com_google_protobuf_java//
REPOSITORY:@com_google_protobuf_java
REPOSITORY_DIRECTORY:@com_google_protobuf_java

        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:279)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:558)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:479)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:194)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: topLevelKey: CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
alreadyReported: false
path to cycle:
CONFIGURED_TARGET://third_party:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1014621225 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylark-lang dd5461492e33c1bd61d975c1f1624c6b (1722372393 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:skylarkinterface dd5461492e33c1bd61d975c1f1624c6b (596646116 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:util dd5461492e33c1bd61d975c1f1624c6b (1354491923 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:unix dd5461492e33c1bd61d975c1f1624c6b (228900030 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/build/lib:vfs dd5461492e33c1bd61d975c1f1624c6b (564692026 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/java/com/google/devtools/common/options:options dd5461492e33c1bd61d975c1f1624c6b (39645139 1680288934)
CONFIGURED_TARGET:@io_bazel//src/main/protobuf:invocation_policy_java_proto dd5461492e33c1bd61d975c1f1624c6b (220755195 1680288934)
ASPECT:[]#BazelJavaProtoAspect dd5461492e33c1bd61d975c1f1624c6b dd5461492e33c1bd61d975c1f1624c6b {$injecting_rule_kind=[java_proto_library]}
PACKAGE:@com_google_protobuf_java//
cycle:
PACKAGE_LOOKUP:@com_google_protobuf_java//
REPOSITORY:@com_google_protobuf_java
REPOSITORY_DIRECTORY:@com_google_protobuf_java

        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:279)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:558)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:479)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:194)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:525)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
        at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

----

Exit code is 37:

<o> [master] ~/dev/copybara$ echo $?
37
```

Seems like a cycle (user error) but Bazel shouldn't crash.

**Comment by laszlocsomor** [comment]
Do you also see this with 0.5.2, or with bazel built from head?

**Comment by mikelalcon** [comment]
Seems fixed in head:

$ head_bazel build //...
ERROR: cycle detected loading package '@com_google_protobuf_java//'.
ERROR: Analysis of target '//copybara/integration:reference_doc_test' failed; build aborted.
INFO: Elapsed time: 53.415s
$ echo $?
1
