### ISSUE TITLE
CI: rules_docker broken on all platforms

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3386]
http://ci.bazel.io/view/Dashboard/job/rules_docker/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/136/console
```
ERROR: /home/ci/workspace/rules_docker/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/docker/testdata/BUILD:297:1: in docker_bundle_ rule //docker/testdata:stamped_bundle_test: 
Traceback (most recent call last):
	File "/home/ci/workspace/rules_docker/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/docker/testdata/BUILD", line 297
		docker_bundle_(name = 'stamped_bundle_test')
	File "/home/ci/workspace/rules_docker/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/docker/bundle.bzl", line 34, in _docker_bundle_impl
		_string_to_label(ctx.files.image_targets, ctx.attr....)
	File "/home/ci/workspace/rules_docker/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/docker/label.bzl", line 20, in _string_to_label
		string_list[i]
index out of range (index is 1, but sequence has 1 elements).
WARNING: /home/ci/workspace/rules_docker/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/docker/push.bzl:43:5: Pushing an image based on a tarball can be very expensive.  If the image is the output of a docker_build, consider dropping the '.tar' extension. If the image is checked in, consider using docker_import instead..
ERROR: Analysis of target '//docker:build_oci_test' failed; build aborted.
```

cc: @buchgr

**Comment by laszlocsomor** [comment]
needs bisecting

**Comment by buchgr** [comment]
@laszlocsomor Have you identified the issue yet?

**Comment by laszlocsomor** [comment]
Yes, I'm pushing to github now, that'll trigger a CI rerun and we can see if everything's fixed.
@vladmos is still fixing the rules_web CI job; we just merged his fix for the rules_go (https://github.com/bazelbuild/rules_go/pull/620) but rules_web just needs to depend on rules_go at head, instead of at the released version. Stay tuned.
