### ISSUE TITLE
CI: rules_go, rules_web broken on all platforms

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3387]
http://ci.bazel.io/view/Dashboard/job/rules_go/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/1051/console
```
ERROR: /home/ci/.cache/bazel/_bazel_ci/18356ce76ec27b0c4bd1f77ab8d37827/external/io_bazel_rules_go/go/tools/builders/BUILD:41:1: in go_tool_binary rule @io_bazel_rules_go//go/tools/builders:generate_test_main: 
Traceback (most recent call last):
	File "/home/ci/.cache/bazel/_bazel_ci/18356ce76ec27b0c4bd1f77ab8d37827/external/io_bazel_rules_go/go/tools/builders/BUILD", line 41
		go_tool_binary(name = 'generate_test_main')
	File "/home/ci/.cache/bazel/_bazel_ci/18356ce76ec27b0c4bd1f77ab8d37827/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 35, in _go_tool_binary_impl
		ctx.action(inputs = ((ctx.files.srcs + tool...), <4 more arguments>)
	File "/home/ci/.cache/bazel/_bazel_ci/18356ce76ec27b0c4bd1f77ab8d37827/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 36, in ctx.action
		toolchain.tools
object of type 'Target' has no field 'tools'.
ERROR: Analysis of target '//tests/coverage:go_default_library' failed; build aborted.
```

http://ci.bazel.io/view/Dashboard/job/rules_web/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/632/console
```
ERROR: /home/ci/.cache/bazel/_bazel_ci/194ffd94ac9cdbdf703c1f13816e861a/external/io_bazel_rules_go/go/tools/builders/BUILD:13:1: in go_tool_binary rule @io_bazel_rules_go//go/tools/builders:asm: 
Traceback (most recent call last):
	File "/home/ci/.cache/bazel/_bazel_ci/194ffd94ac9cdbdf703c1f13816e861a/external/io_bazel_rules_go/go/tools/builders/BUILD", line 13
		go_tool_binary(name = 'asm')
	File "/home/ci/.cache/bazel/_bazel_ci/194ffd94ac9cdbdf703c1f13816e861a/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 35, in _go_tool_binary_impl
		ctx.action(inputs = ((ctx.files.srcs + tool...), <4 more arguments>)
	File "/home/ci/.cache/bazel/_bazel_ci/194ffd94ac9cdbdf703c1f13816e861a/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 36, in ctx.action
		toolchain.tools
object of type 'Target' has no field 'tools'.
ERROR: Analysis of target '//go/launcher/cmdhelper:go_default_library' failed; build aborted.
```

cc: @buchgr

**Comment by laszlocsomor** [comment]
FYI: culprit for https://github.com/bazelbuild/bazel/issues/3388 was https://github.com/bazelbuild/bazel/commit/8002b6205e004721f771df20d1d8c1402c03964e.

**Comment by dslomov** [comment]
Culprit for this is different: 97d67087e6199db3b4c69178cf6a2d0c83c19290

**Comment by vladmos** [comment]
The reason of breakage: if a single declared provider is returned from a rule implementation function Bazel used to wrongly treat it as an old-style struct (because providers are special structs). Now that has been fixed and Bazel treats it as a single declared provider, and therefore the provided data should be accessed differently.

Sent a fix to rules_go, and rules_web depends on rules_go and probably doesn't need to be fixed at all (except its rules_go dependency needs to be updated).

**Comment by buchgr** [comment]
The PR got merged. Closing. thanks @vladmos
