### ISSUE TITLE
CI, bazel-tests, Windows: //src/test/py/bazel:bazel_windows_test fails

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3389]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/879/console
```
FAIL: //src/test/py/bazel:bazel_windows_test (see C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/testlogs/src/test/py/bazel/bazel_windows_test/test.log)
____From Testing //src/test/py/bazel:bazel_windows_test:
==================== Test output for //src/test/py/bazel:bazel_windows_test:
F.
======================================================================
FAIL: testUseMSVCWrapperScript (__main__.BazelWindowsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\bazel_ci\temp\Bazel.runfiles_ini8g5\runfiles\io_bazel\src\test\py\bazel\bazel_windows_test.py", line 70, in testUseMSVCWrapperScript
    self.AssertExitCode(exit_code, 0, stderr)
  File "c:\bazel_ci\temp\Bazel.runfiles_ini8g5\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 67, in AssertExitCode
    '(end stderr)------------------------------------------',
AssertionError: Bazel exited with 1 (expected 0), stderr:
(start stderr)----------------------------------------
____Loading package: foo
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
WARNING: C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/io_bazel/_tmp/09a442d3c38d11d600ea6c80ab91c18c/_bazel_system/xyrdiyb3/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start looking for python in PATH.
.
WARNING: C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/io_bazel/_tmp/09a442d3c38d11d600ea6c80ab91c18c/_bazel_system/xyrdiyb3/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Python found at C:/python_27_amd64/files/python.exe
.
____Loading package: @local_config_cc//
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
____[1 / 5] Writing file foo/x.exe-2.params
____[3 / 6] Compiling foo/x.cc
ERROR: C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/io_bazel/_tmp/09a442d3c38d11d600ea6c80ab91c18c/tests_root/foo/BUILD:1:1: Linking of rule '//foo:x' failed (Exit 1104).
____Building complete.
Target //foo:x failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 17.217s, Critical Path: 0.55s
INFO: $TEST_TMPDIR defined: output root default is 'C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/io_bazel/_tmp/09a442d3c38d11d600ea6c80ab91c18c'.
WARNING: Running Bazel server needs to be killed, because the startup options are different.
(end stderr)------------------------------------------

----------------------------------------------------------------------
Ran 2 tests in 89.504s
```

**Comment by laszlocsomor** [comment]
Cannot repro locally, could've been a flake.
