### ISSUE TITLE
Windows tests: failure to auto-conf if there is an equal on the workspace path

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3442]
Repro: test bazel with an equal sign in the workspace path, like in CI: http://ci.bazel.io/job/Global/job/bazel-tests/108/testReport/junit/(root)/(empty)/test_java/

Results:
____Loading package: @local_jdk//
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "C:/temp/2104286f1ce1b1c5200886c360f7e20d/root/nf5aby06/external/bazel_tools/tools/cpp/cc_configure.bzl", line 32
		configure_windows_toolchain(repository_ctx)
	File "C:/temp/2104286f1ce1b1c5200886c360f7e20d/root/nf5aby06/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 316, in configure_windows_toolchain
		_find_env_vars(repository_ctx, vc_path)
	File "C:/temp/2104286f1ce1b1c5200886c360f7e20d/root/nf5aby06/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 202, in _find_env_vars
		(key, value) = env.split("=")
lvalue has length 2, but rvalue has has length 3.
____Elapsed time: 2.260s

/cc @buchgr

**Comment by meteorcloudy** [comment]
What equal sign? Where can I find it?

**Comment by damienmg** [comment]
Oh sorry did not copy it but the equals was on the test setup path, ands split cut on all equals, splitting only on the first one should fix the issue

**Comment by damienmg** [comment]
http://ci.bazel.io/job/Global/job/bazel-tests/108/testReport/(root)/(empty)/test_java_test/ is the correct link

**Comment by meteorcloudy** [comment]
Thanks! I'll send a fix.
