### ISSUE TITLE
Some APIs expected PathFragments but now don't work

### ISSUE THREAD

**Issue by fahhem** [bazelbuild/bazel#3446]
### Description of the problem / feature request / question:

After https://github.com/bazelbuild/bazel/commit/4dfb271df9dcdf01413a216ad046d955669160b7, some APIs that expected PathFragments don't work, such as `ctx.action(executable=...)`. 

From https://github.com/bazelbuild/bazel/issues/2931#issuecomment-317435176:
Syncing to head gives me this:

```py
Traceback (most recent call last):
	File "//BUILD", line 13
		raw_binary(name = 'firmware_bin')
	File "//compilers/raw_binary.bzl", line 8, in _bin_impl
		ctx.action(inputs = ([input] + ctx.files._o...), <4 more arguments>)
expected file or PathFragment for executable but got string instead.
```
Here's the definition of `raw_binary` (note that line 13 above does NOT exist in my code, both `src` and `out` are missing for some reason):

```py
# From https://github.com/pedrokiefer/rules_stm32/blob/master/tools/arm_compiler/raw_binary.bzl
def _bin_impl(ctx):
    output = ctx.outputs.out
    input = ctx.file.src
    objcopy = ctx.fragments.cpp.objcopy_executable

    ctx.action(
        inputs=[input] + ctx.files._objcopy,
        outputs=[output],
        progress_message="Creating raw binary from %s" % input.short_path,
        executable = objcopy,
        arguments = [ 
            "-O",
            "binary",
            "-S",
            input.path,
            output.path
        ])

raw_binary = rule(
    attrs = { 
        "src": attr.label(
            mandatory = True,
            allow_files = True,
            single_file = True,
        ),
        "out": attr.output(
            mandatory = True,
        ),
        "_objcopy": attr.label(
            default = Label("@arm_none_eabi_gcc//:objcopy"),
            allow_files = True,
        ),
    },  
    fragments = ["cpp"],
    implementation = _bin_impl,
)
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): development version (bazelbuild/bazel@624ecabfdce32349ca446dee657403b9939ff2bf)

###  Have you found anything relevant by searching the web?
Nope, this commit came in over the weekend

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by fahhem** [comment]
Looks like this was fixed by a rollback: https://github.com/bazelbuild/bazel/commit/f3c6a9c8f2e806fef1cd2ee8822809d74b4bd718
