### ISSUE TITLE
--action_env is not passed when running `bazel query`

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3465]
In bazelrc, I have:
```
pcloudy@pcloudy0-w MSYS ~/workspace/tensorflow
$ cat .tf_configure.bazelrc
build --action_env PYTHON_BIN_PATH="C:/Program Files/Anaconda3/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Program Files/Anaconda3/lib/site-packages"
...
```
When running a `bazel query` command, bazel complains `PYTHON_BIN_PATH` not set:
```
$ bazel query "somepath($TF_PIP, @boringssl//:crypto)"
ERROR: C:/tools/msys64/home/pcloudy/workspace/tensorflow/util/python/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 310
                _create_local_python_repository(repository_ctx)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
                _get_python_bin(repository_ctx)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 166, in _get_python_bin
                _get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 49, in _get_env_var
                _python_configure_fail("'%s' environment variable is no...)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
                fail("%sPython Configuration Error:%s...))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//util/python:python_headers'.
ERROR: C:/tools/msys64/home/pcloudy/workspace/tensorflow/util/python/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 310
                _create_local_python_repository(repository_ctx)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
                _get_python_bin(repository_ctx)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 166, in _get_python_bin
                _get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 49, in _get_env_var
                _python_configure_fail("'%s' environment variable is no...)
        File "C:/tools/msys64/home/pcloudy/workspace/tensorflow/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
                fail("%sPython Configuration Error:%s...))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//util/python:python_headers'.
ERROR: Evaluation of query "somepath(tensorflow/tools/pip_package:build_pip_package, @boringssl//:crypto)" failed: errors were encountered while computing transitive closure.
```
But when building the target directly, everything is fine.
```
pcloudy@pcloudy0-w MSYS ~/workspace/tensorflow
$ bazel build @local_config_python//...
INFO: Analysed 5 targets.
INFO: Found 5 targets...
INFO: Elapsed time: 14.503s, Critical Path: 3.29s
INFO: Build completed successfully, 4 total actions
```

**Comment by dslomov** [comment]
@aehlig because action_env

**Comment by zz-pony** [comment]
Per my observation, action_env is not passed to "bazel run" command either. Is this caused by the same reason?

**Comment by ulfjack** [comment]
It looks like action_env is also used for workspace rules, which seems off (since they are not actions).

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
