### ISSUE TITLE
--experimental_repository_cache should allow a relative path

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#3516]
Or at least not print a stack trace:

```
java.lang.IllegalArgumentException: my_cache (not an absolute path)
	at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:146)
	at com.google.devtools.build.lib.bazel.BazelRepositoryModule.handleOptions(BazelRepositoryModule.java:189)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:511)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: my_cache (not an absolute path)
	at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:146)
	at com.google.devtools.build.lib.bazel.BazelRepositoryModule.handleOptions(BazelRepositoryModule.java:189)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:511)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:314)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by davido** [comment]
We have a feature request to allow user specific directory: `~/.gerritcodereview/download-cache`.

**Comment by ittaiz** [comment]
+1

**Comment by davido** [comment]
https://github.com/bazelbuild/bazel/issues/2054

**Comment by nevion** [comment]
+1

**Comment by ensonic** [comment]
It only it would resolve env-vars like $HOME or $PWD as a workaround.

**Comment by dslomov** [comment]
crash is P1, feature request seems to be not that hard to implement either

**Comment by ittaiz** [comment]
@dslomov any chance this will allow ~ or $HOME?
@davido did something like this in a different CL he got in a few months ago but I think it's only relevant for his other experimental flag (I think related to local remote cache)

**Comment by ittaiz** [comment]
Why was it undone?

**Comment by davido** [comment]
Because reviewers pointed out, that support for HOME-directory should be generally integrated in Bazel infrastructure.

**Comment by ittaiz** [comment]
I see.
Unlikely you'll pick that one up, right?

**Comment by davido** [comment]
Unfortunately, I cannot work on that atm.

**Comment by aehlig** [comment]
The actual crash is fixed in 157caed02ef354447f673c89c6a0e296bae5341c
and relative paths are interpreted relative to the WORKSPACE directory.
So the intended use case 'bazel build --experimental_repository_cache=my_cache'
works.

Alternatively, 88374614b62b17587453137814d264fdaf7bd70e and
220d650b3f47712a5b82748141f3381075c35c80 add an option --experimental_distdir
allowing to specify a list of read-only directories containing flatly
the archives instead of a cache directory in bazel's internal repository
cache format. Again, relative paths work (interpreted relative to the
WORKSPACE, e.g., 'bazel build --experimental_distdir=distfiles'), as
do absolute path ('bazel build --experimental_distdir=/usr/ports/distfiles').


So, the only remaining part of this issue is what is already tracked
in #2054. Therefore, unless someone objects, I will close this issue leaving
only feature request #2054 open. (For the latter, I'm not sure if it
is really necessary. Options passed on the command line are already
expanded by the shell, and options referring to the user's home directory
are best set in the user's .bazelrc file (which is individual per user);
documentation can still suggest commands like 'echo
$HOME/.gerritcodereview/download-cache >> $HOME/.bazelrc' which again
will be expanded correctly by the shell).

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ittaiz** [comment]
How does this play with a bazelrc file which is checked in to the project?
Unfortunately bazelrc files aren’t hierarchical so one has to use one or
the other and we’re using the checked in version to not have tribal
knowledge of what goes in

**Comment by davido** [comment]
@aehlig Yeah, there is also @3042, where a similar feature request, to provide relative class path for `--experimental_local_disk_cache_path` option is tracked, see my last comment.

**Comment by aehlig** [comment]
> Unfortunately bazelrc files aren’t hierarchical so one has to use one or the other

Indeed, this is yet another independent issue. Filed #4629 to keep track of it.

**Comment by aehlig** [comment]
The actual issue is solved, and all other feature requests that came up in the discussion are tracked in separate issues. Closing.

**Comment by davido** [comment]
@ensonic this feature request is tracked in #2054.
