### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#3533]
Upgraded to `0.5.3` today from `0.4.5` (darwin Sierra 10.12.3).  Have not seen this error before:
Workaround was a forced `bazel shutdown`.

```
BUILD:11:1: Compiling 1754 JavaScript files to app.js failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_pcj/6f0b979dd5a3c718b7bd5e09d42b18bf/bazel-workers/worker-5-Closure.log ---8<---8<---
Exception in thread "main" java.lang.InternalError: java.io.FileNotFoundException: /private/var/tmp/_bazel_pcj/install/e5bd9da1474e6d6cb1535cd55942b349/_embedded_binaries/embedded_tools/jdk/jre/lib/ext/cldrdata.jar (Too many open files in system)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1040)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.ResourceBundle$RBClassLoader.loadClass(ResourceBundle.java:503)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2640)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at java.util.logging.Level.computeLocalizedLevelName(Level.java:265)
	at java.util.logging.Level.getLocalizedLevelName(Level.java:324)
	at java.util.logging.SimpleFormatter.format(SimpleFormatter.java:165)
	at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
	at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:876)
	at com.google.javascript.jscomp.SourceMap.addSourceFile(SourceMap.java:173)
	at com.google.javascript.jscomp.Compiler.addFilesToSourceMap(Compiler.java:3423)
	at com.google.javascript.jscomp.Compiler.init(Compiler.java:507)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1107)
	at com.google.javascript.jscomp.JsCompilerRunner.go(JsCompilerRunner.java:45)
	at com.google.javascript.jscomp.JsCompiler.run(JsCompiler.java:193)
	at com.google.javascript.jscomp.JsCompiler.apply(JsCompiler.java:82)
	at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
	at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:72)
	at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
	at io.bazel.rules.closure.worker.PersistentWorker.runAsPersistentWorker(PersistentWorker.java:144)
	at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:84)
	at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
Caused by: java.io.FileNotFoundException: /private/var/tmp/_bazel_pcj/install/e5bd9da1474e6d6cb1535cd55942b349/_embedded_binaries/embedded_tools/jdk/jre/lib/ext/cldrdata.jar (Too many open files in system)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:930)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:791)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:876)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:869)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:868)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1038)
	... 37 more
---8<---8<--- End of log ---8<---8<---
Target //src/main/www:www failed to build
```

**Comment by mhlopko** [comment]
We also see it on our ci. We think its the closure worker. Already reported a bug there: https://github.com/bazelbuild/rules_closure/issues/218. Will close the issue here, please continue on rules_closure.

**Comment by pcj** [comment]
Ok thanks Marcel
