### ISSUE TITLE
bazel_windows_test fails on windows

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#3584]
bazel_windows_test fails on [bazel CI](http://ci.bazel.io/view/Dashboard/job/bazel-tests/965/consoleFull) on windows with error:

```
FAIL: testWindowsUnixRoot (__main__.BazelWindowsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "c:\windows\temp\Bazel.runfiles__p8has\runfiles\io_bazel\src\test\py\bazel\bazel_windows_test.py", line 38, in testWindowsUnixRoot
     self.AssertExitCode(exit_code, 2, stderr)
   File "c:\windows\temp\Bazel.runfiles__p8has\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 67, in AssertExitCode
     '(end stderr)------------------------------------------',
 AssertionError: Bazel exited with 37 (expected 2), stderr:
 (start stderr)----------------------------------------
 ____Loading package: foo
 ____Loading package: @bazel_tools//tools/cpp
 ____Loading package: @local_config_xcode//
 ____Loading package: @local_jdk//
 ____Loading package: @local_config_cc//
 ____Loading complete.  Analyzing...
 ____Found 1 target...
 ____Building...
 ____[0 / 3] BazelWorkspaceStatusAction stable-status.txt
 ____[1 / 6] Writing file foo/x.exe-2.params
 Target //foo:x failed to build
 Use --verbose_failures to see the command lines of failed build steps.
 Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://foo:x df96db01088201b7688aff2f78e85ab4 (498110004 1756789949), actionIndex=0}' (requested by nodes 'foo/_objs/x/foo/x.o //foo:x df96db01088201b7688aff2f78e85ab4 (645868405 1756789949)')
 ____Elapsed time: 9.529s, Critical Path: 0.34s
 java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://foo:x df96db01088201b7688aff2f78e85ab4 (498110004 1756789949), actionIndex=0}' (requested by nodes 'foo/_objs/x/foo/x.o //foo:x df96db01088201b7688aff2f78e85ab4 (645868405 1756789949)')
 at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
 at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.IllegalStateException: "bazel.windows_unix_root" JVM flag is not set. Use the --host_jvm_args flag or export the BAZEL_SH environment variable. For example "--host_jvm_args=-Dbazel.windows_unix_root=c:/tools/msys64" or "set BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe". parent=(/) name=(usr)
```

@meteorcloudy: If it's not clear to you right away what the culprit is let me know so I would do a git bisect.

**Comment by meteorcloudy** [comment]
@iirina I couldn't tell right away, but I can do the bisect since I already have a Windows machine.

**Comment by iirina** [comment]
Thank you! Let me know what you got.

**Comment by meteorcloudy** [comment]
Got it, the culprit is 2f38404728a12840e416566b453e9cdebab5d859

**Comment by meteorcloudy** [comment]
FYI, @dslomov

**Comment by iirina** [comment]
Thanks Yun! @dslomov do you have a quick fix or should I roll back?

**Comment by iirina** [comment]
I'm preparing a rollback.

**Comment by dslomov** [comment]
Sorry about that, thanks for bisect and rollback!
