### ISSUE TITLE
testReadingAndWritingAfterTermination – com.google.devtools.build.lib.windows.WindowsProcessesTest failed on CI [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3600]
From http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/190/tests/:

```
testReadingAndWritingAfterTermination – com.google.devtools.build.lib.windows.WindowsProcessesTest
a few seconds
Error
Not true that <1> is equal to <-1>
Stacktrace
java.lang.AssertionError: Not true that <1> is equal to <-1>
	at com.google.devtools.build.lib.windows.WindowsProcessesTest.testReadingAndWritingAfterTermination(WindowsProcessesTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
Caused by: java.lang.AssertionError: Not true that <1> is equal to <-1>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:348)
	at com.google.common.truth.Subject.doEqualCheck(Subject.java:127)
	at com.google.common.truth.Subject.isEqualTo(Subject.java:104)
	... 34 more
```

Probably a flake.

**Comment by damienmg** [comment]
Yun: to investigate or reassign

**Comment by meteorcloudy** [comment]
Hmm, couldn't repro locally with both latest Bazel and Bazel@HEAD.
Let's see if it fails again.

**Comment by meteorcloudy** [comment]
Looks like it didn't appear again.
