### ISSUE TITLE
IllegalStateException on `bazel build @non_existent_repo//...`

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3638]
Bazel fails inelegantly when trying to build all rules in a repo that doesn't exist. This is a minor issue as it would fail anyway, but the error message could be better.

```
➜  bazel build @non_existent_repo//...
...............
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '@non_existent_repo//...' (requested by nodes '[@non_existent_repo//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
INFO: Elapsed time: 0.681s
FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '@non_existent_repo//...' (requested by nodes '[@non_existent_repo//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No such repository '@non_existent_repo'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:584)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@non_existent_repo//...' (requested by nodes '[@non_existent_repo//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No such repository '@non_existent_repo'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:584)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
```

Expected behaviour would be something like:

```
➜  bazel build @non_existent_repo//:non_existent_repo
ERROR: Skipping '@non_existent_repo//:non_existent_repo': no such package '@non_existent_repo//': The repository could not be resolved
WARNING: Target pattern parsing failed.
ERROR: no such package '@non_existent_repo//': The repository could not be resolved
INFO: Elapsed time: 0.218s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.5.3

**Comment by dslomov** [comment]
https://github.com/bazelbuild/bazel/commit/f0711024f90541727fab60760f2d1affe12cc917 fixes (incorrect bug reference in commit message, sorry)
