### ISSUE TITLE
Failure in parsing the WORKSPACE file leads to hard crash (instead of nice error message)

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3654]
```
endobson@yggdrasil () ~/proj/bes-example % bazel build @googleapis//...                                                                                                                                                                   (1)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
ERROR: /Users/endobson/proj/bes-example/WORKSPACE:4:3: syntax error at 'commit': expected ,
ERROR: /Users/endobson/proj/bes-example/WORKSPACE:6:1: non-keyword arg after keyword arg.
Unhandled exception thrown during build; message: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': Failed to parse WORKSPACE file rootCauses={WORKSPACE_AST:[/Users/endobson/proj/bes-example]/[WORKSPACE]} cycles=[]>
INFO: Elapsed time: 0.071s
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': Failed to parse WORKSPACE file rootCauses={WORKSPACE_AST:[/Users/endobson/proj/bes-example]/[WORKSPACE]} cycles=[]>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': Failed to parse WORKSPACE file rootCauses={WORKSPACE_AST:[/Users/endobson/proj/bes-example]/[WORKSPACE]} cycles=[]>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
	at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
WORKSPACE file
```
git_repository(
  name = "googleapis"
  commit = "220c359ac969c6bbab7a11077b32de2533cc7bad"
  remote = "https://github.com/googleapis/googleapis.git"
)
```

BUILD file is blank
bazel version = 0.5.4

**Comment by meisterT** [comment]
Fixed at HEAD:
```
$ bazel build @googleapis//...   
ERROR: /usr/local/google/home/twerth/btest3/WORKSPACE:3:5: syntax error at 'commit': expected ,
ERROR: /usr/local/google/home/twerth/btest3/WORKSPACE:3:12: positional argument is misplaced (positional arguments come first)
ERROR: error loading package 'external': Failed to parse WORKSPACE file
```
