### ISSUE TITLE
new_http_archive doesn't handle invalid sha256 checksums

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3656]
```
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
Unhandled exception thrown during build; message: <ErrorInfo exception=com.google.devtools.build.lib.syntax.EvalException: Invalid SHA256 checksum rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
INFO: Elapsed time: 0.199s
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.syntax.EvalException: Invalid SHA256 checksum rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.syntax.EvalException: Invalid SHA256 checksum rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

WORKSPACE file
```
new_http_archive(
  name = "googleapis",
  sha256 = "a",
  urls = ["https://github.com/googleapis/googleapis/archive/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz"],
  build_file = "BUILD.googleapis"
)
```

```
endobson@yggdrasil () ~/proj/bes-example % bazel version                                                                                                                                                                                  (2)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
Build label: 0.5.4- (@non-git)
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 31 04:32:51 2017 (1504153971)
Build timestamp: 1504153971
Build timestamp as int: 1504153971
```

**Comment by endobson** [comment]
When the checksum is wrong it also crashes instead of printing a nice error:

```
endobson@yggdrasil () ~/proj/bes-example % bazel build @googleapis//...                                                                                                                                                                  (37)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
............
Unhandled exception thrown during build; message: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz] to /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/googleapis/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz: Checksum was 0421e89b76a6fa6f820c39ad365a5e490873ae4c7509c8a53f42671f1e53e1e8 but wanted e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
INFO: Elapsed time: 1.289s
java.lang.IllegalArgumentException: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz] to /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/googleapis/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz: Checksum was 0421e89b76a6fa6f820c39ad365a5e490873ae4c7509c8a53f42671f1e53e1e8 but wanted e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz] to /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/googleapis/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz: Checksum was 0421e89b76a6fa6f820c39ad365a5e490873ae4c7509c8a53f42671f1e53e1e8 but wanted e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 rootCauses={REPOSITORY_DIRECTORY:@googleapis} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:175)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:126)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:402)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:157)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:315)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:516)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:330)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:53)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:834)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:106)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:895)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```


```
new_http_archive(
  name = "googleapis",
  sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  urls = ["https://github.com/googleapis/googleapis/archive/220c359ac969c6bbab7a11077b32de2533cc7bad.tar.gz"],
  build_file = "BUILD.googleapis"
)
```

**Comment by dslomov** [comment]
Cannot reproduce at HEAD, regression test: https://bazel-review.googlesource.com/#/c/bazel/+/32112
