### ISSUE TITLE
"Could not find handler for bind rule" error

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3664]
http://ci.bazel.io/job/tf_models_syntaxnet/619/console shows the following error:
`ERROR: no such package '@protobuf//src/google/protobuf': Could not find handler for bind rule //external:protobuf.`

The workspace file contain the correct definition:

```python

bind(
    name = "protobuf",
    actual = "@protobuf_archive//:protobuf",
)
```

/cc @vladmos fyi

**Comment by damienmg** [comment]
Humm the error message comes from the RepositoryFunction. Could that happen because someone redefine the bind symbol?

**Comment by damienmg** [comment]
Ok I got some more log now we are actually crashing:

```
[variation=,node=linux-x86_64] INFO: Elapsed time: 13.320s, Critical Path: 0.06s
[variation=,node=linux-x86_64] java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@protobuf' (requested by nodes 'REPOSITORY:@protobuf')
[variation=,node=linux-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
[variation=,node=linux-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=linux-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=linux-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=linux-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=linux-x86_64] Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.syntax.EvalException: Could not find handler for bind rule //external:protobuf
[variation=,node=linux-x86_64] 	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:133)
[variation=,node=linux-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
[variation=,node=linux-x86_64] 	... 4 more
[variation=,node=linux-x86_64] Caused by: com.google.devtools.build.lib.syntax.EvalException: Could not find handler for bind rule //external:protobuf
[variation=,node=linux-x86_64] 	... 6 more
[variation=,node=linux-x86_64] java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@protobuf' (requested by nodes 'REPOSITORY:@protobuf')
[variation=,node=linux-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
[variation=,node=linux-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=linux-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=linux-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=linux-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=linux-x86_64] Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.syntax.EvalException: Could not find handler for bind rule //external:protobuf
[variation=,node=linux-x86_64] 	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:133)
[variation=,node=linux-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
[variation=,node=linux-x86_64] 	... 4 more
[variation=,node=linux-x86_64] Caused by: com.google.devtools.build.lib.syntax.EvalException: Could not find handler for bind rule //external:protobuf
[variation=,node=linux-x86_64] 	... 6 more
```

**Comment by damienmg** [comment]
clean --expunge fix the build.

**Comment by damienmg** [comment]
Ok zipping the output_base and shipping I was able to repro the issue on my workstation

**Comment by damienmg** [comment]
Ok so syntaxnet renamed a repository into a bind rule...

**Comment by damienmg** [comment]
Copying over some chat:

Grepping the output of dump --skyframe=detailed:

```
$ grep -E '@protobuf([^_]|$)' /tmp/dump.log
REPOSITORY_DIRECTORY:@protobuf|PRECOMPUTED:blaze_directories|PRECOMPUTED:repository_overrides|PACKAGE_LOOKUP:external|WORKSPACE_FILE:[/home/ci/workspace/Global/tf_models_syntaxnet-variation=,node=linux-x86_64/syntaxnet]/[WORKSPACE], 0|WORKSPACE_FILE:[/home/ci/workspace/Global/tf_models_syntaxnet-variation=,node=linux-x86_64/syntaxnet]/[WORKSPACE], 1
```

When I debug I ends up in RepositoryLoaderFunction:46 but the corresponding skykey for RepositoryLoaderFunction is never called

**Comment by damienmg** [comment]
[Uploading dump.log.txt…](output of bazel dump --skyframe=detailed)

**Comment by lberki** [comment]
@damienmg , I don't have your saved output base, but the problem seems to be that when Bazel sees a reference to the `@protobuf` repository, it looks for a rule called `:protobuf` in the WORKSPACE file and find its handler.

Since the rule that is found is not a repository rule but a `bind` one, the handler is not found.

Easy repro:
```
mkdir t
cd t
echo 'bind(name="a", actual="@//:ar")' > WORKSPACE
echo 'filegroup(name="fg", srcs=["@a//:x"])' > BUILD
bazel build //:fg
```

Then enjoy the error message with the release or crash at HEAD.
