### ISSUE TITLE
Bazel hard crashes when 'inputs' argument to 'ctx.action' is a RuleConfiguredTarget

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3714]
It looks like the code is assuming that any value that flows in has been checked by the `@Param` type, but that seems to not be the case.

`@Param` for the argument:
https://github.com/bazelbuild/bazel/blob/67f23f563cc655df7102f798206a3c4d07f46774/src/main/java/com/google/devtools/build/lib/rules/SkylarkActionFactory.java#L249-L260

Where the cast happens:
https://github.com/bazelbuild/bazel/blob/67f23f563cc655df7102f798206a3c4d07f46774/src/main/java/com/google/devtools/build/lib/rules/SkylarkActionFactory.java#L573-L580

Error message:
```
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
................
____Loading package: tests/test-data
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
____Loading package: @local_config_xcode//
____Loading complete.  Analyzing...
____Loading package: @com_google_protobuf//
____Loading package: @bazel_tools//tools/genrule
____Loading package: 
____Loading package: @racket_minimal_x86_64_6_10_osx//file
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 03404db0c64cd2322ae1929c923ef28b 03404db0c64cd2322ae1929c923ef28b {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 03404db0c64cd2322ae1929c923ef28b (1600830686 183214234)')
____Elapsed time: 2.595s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 03404db0c64cd2322ae1929c923ef28b 03404db0c64cd2322ae1929c923ef28b {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 03404db0c64cd2322ae1929c923ef28b (1600830686 183214234)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.analysis.RuleConfiguredTarget cannot be cast to com.google.devtools.build.lib.syntax.SkylarkNestedSet
	at com.google.devtools.build.lib.rules.SkylarkActionFactory.registerSpawnAction(SkylarkActionFactory.java:578)
	at com.google.devtools.build.lib.rules.SkylarkActionFactory.run(SkylarkActionFactory.java:384)
	at com.google.devtools.build.lib.rules.SkylarkRuleImplementationFunctions$1.invoke(SkylarkRuleImplementationFunctions.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:166)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:644)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:741)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:727)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:45)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:43)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:83)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:764)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:750)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:727)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:45)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:43)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.ForStatement.doExec(ForStatement.java:82)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:83)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:79)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:433)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:471)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:320)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 03404db0c64cd2322ae1929c923ef28b 03404db0c64cd2322ae1929c923ef28b {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 03404db0c64cd2322ae1929c923ef28b (1600830686 183214234)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.analysis.RuleConfiguredTarget cannot be cast to com.google.devtools.build.lib.syntax.SkylarkNestedSet
	at com.google.devtools.build.lib.rules.SkylarkActionFactory.registerSpawnAction(SkylarkActionFactory.java:578)
	at com.google.devtools.build.lib.rules.SkylarkActionFactory.run(SkylarkActionFactory.java:384)
	at com.google.devtools.build.lib.rules.SkylarkRuleImplementationFunctions$1.invoke(SkylarkRuleImplementationFunctions.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:166)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:644)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:741)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:727)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:45)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:43)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:83)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:764)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeGlobalFunction(FuncallExpression.java:750)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:727)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:45)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:43)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.ForStatement.doExec(ForStatement.java:82)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:83)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:79)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:433)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:471)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:320)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more
```

Release 0.5.4

**Comment by dslomov** [comment]
working on this.

**Comment by davido** [comment]
It seems, that this CL introduced breakage in rules_closure,
and as the consequence, Gerrit Code Review cannot be built
from the HEAD any more, see: #3782.
