### ISSUE TITLE
Exception when bazel run :target where target is a genrule

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#372]
```
$ bazel run :ubuntu_14.04-x86_64
Unhandled exception thrown during build; message: Attribute 'executable' is potentially configurable - not allowed here
INFO: Elapsed time: 0.791s
java.lang.IllegalStateException: Attribute 'executable' is potentially configurable - not allowed here
    at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
    at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
    at com.google.devtools.build.lib.bazel.rules.genrule.BazelGenRuleRule$1.getDefault(BazelGenRuleRule.java:196)
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:61)
    at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:47)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutableNonTestRule(RunCommand.java:510)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutable(RunCommand.java:496)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTarget(RunCommand.java:447)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTargets(RunCommand.java:403)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.access$000(RunCommand.java:83)
    at com.google.devtools.build.lib.runtime.commands.RunCommand$1.validateTargets(RunCommand.java:117)
    at com.google.devtools.build.lib.buildtool.BuildTool$1.notifyTargets(BuildTool.java:410)
    at com.google.devtools.build.lib.pkgcache.LoadingPhaseRunner.execute(LoadingPhaseRunner.java:391)
    at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:420)
    at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
    at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:342)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:113)
    at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:152)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:427)
    at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1341)
    at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
    at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:420)
    at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:227)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1299)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:1095)
    at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:49)
```

**Comment by stephenchu** [comment]
I hit the same thing, with an extremely simple test case to reproduce.

Am I doing something wrong? Or, does this have a workaround?

#### Steps to Reproduce
```
$ touch WORKSPACE

$ mkdir one

$ echo "FILE1 CONTENT" > one/file1.txt

$ echo '
genrule(
  name = "buggy",
  srcs = [],
  outs = ["output.txt"],
  cmd = "cat file1.txt > $@",
)
' > one/BUILD
```

#### Output
```
$ bazel run //one:buggy
.......
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
Unhandled exception thrown during build; message: Attribute 'executable' is potentially configurable - not allowed here
INFO: Elapsed time: 0.472s
java.lang.IllegalStateException: Attribute 'executable' is potentially configurable - not allowed here
        at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
        at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
        at com.google.devtools.build.lib.bazel.rules.genrule.BazelGenRuleRule$1.getDefault(BazelGenRuleRule.java:204)
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:67)
        at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:47)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutableNonTestRule(RunCommand.java:512)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutable(RunCommand.java:498)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTarget(RunCommand.java:449)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTargets(RunCommand.java:405)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.access$000(RunCommand.java:85)
        at com.google.devtools.build.lib.runtime.commands.RunCommand$1.validateTargets(RunCommand.java:119)
        at com.google.devtools.build.lib.buildtool.BuildTool$1.notifyTargets(BuildTool.java:391)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:201)
        at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:401)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:334)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:115)
        at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:155)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:370)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1009)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
        at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
        at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:968)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:765)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)

$ bazel version
Build label: head (@f1c411b)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel-main_deploy.jar
Build time: Tue Nov 24 23:34:22 2015 (1448408062)
Build timestamp: 1448408062
Build timestamp as int: 1448408062

```

**Comment by damienmg** [comment]
Yes a genrule is not runnable except if you set the executable attribute to 1. In which case the output of the genrule can be run with bazel run. However, this is wrong to throw a stack trace and we should have an explicit message for the user instead.

What you want to do is simply `bazel build //one:buggy && cat bazel-genfiles/one/output.txt

Note that you should declare "file1.txt" as an input of your genrule in the srcs attribute (your system don't support sandboxing so you won't see the problem on yours but in system with sandboxing on, your command would fail).

**Comment by stephenchu** [comment]
Thanks for the explanation. It makes perfect sense.

Do you want me to repurpose this issue to ~"bazel run a genrule should not throw stack trace"?

**Comment by kchodorow** [comment]
The title seems fine as-is, but thanks.

**Comment by helenalt** [comment]
@gregestren are you still the right assignee for this issue?

**Comment by gregestren** [comment]
This was fixed by https://github.com/bazelbuild/bazel/commit/291032ae5dd7776422d692298d36d3dae96b39ed#diff-dc563e4148084671f7d953e1fee35737.
