### ISSUE TITLE
Hard crash when defining aspect that has two rules for the same output file

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3746]
I got the following hard crash when I defined two actions within the same aspect that generated the same output file. While I expect that to be an error I expect it to be a nicely formatted error. Also the printing of Actions solely by their type `SkylarkAction` and their file output seems to be a poor choice in this case because it is unclear that it is two different actions.

```
endobson@yggdrasil () ~/proj/racket/protobuf % bazel build //:test-collection                                                                                                                                                             (1)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 0ac30f10b75c732b566d5dc8df2a430d (807299352 1558115324)', 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}')
INFO: Elapsed time: 0.522s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 0ac30f10b75c732b566d5dc8df2a430d (807299352 1558115324)', 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo, previous action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo', attempted action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo'
        at com.google.devtools.build.lib.actions.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:50)
        at com.google.devtools.build.lib.actions.ActionLookupValue.<init>(ActionLookupValue.java:57)
        at com.google.devtools.build.lib.skyframe.AspectValue.<init>(AspectValue.java:329)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:510)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:320)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
Caused by: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo, previous action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo', attempted action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo'
        at com.google.devtools.build.lib.actions.Actions.maybeFilterSharedActionsAndThrowIfConflict(Actions.java:124)
        at com.google.devtools.build.lib.actions.Actions.filterSharedActionsAndThrowActionConflict(Actions.java:110)
        at com.google.devtools.build.lib.actions.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:47)
        ... 9 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}' (requested by nodes 'CONFIGURED_TARGET://tests/test-data:foo_proto_rkt 0ac30f10b75c732b566d5dc8df2a430d (807299352 1558115324)', 'ASPECT:[]#//:racket_proto_library.bzl%racket_proto_library_aspect 0ac30f10b75c732b566d5dc8df2a430d 0ac30f10b75c732b566d5dc8df2a430d {}')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo, previous action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo', attempted action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo'
        at com.google.devtools.build.lib.actions.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:50)
        at com.google.devtools.build.lib.actions.ActionLookupValue.<init>(ActionLookupValue.java:57)
        at com.google.devtools.build.lib.skyframe.AspectValue.<init>(AspectValue.java:329)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:510)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:320)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
Caused by: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo, previous action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo', attempted action: action 'SkylarkAction tests/test-data/racket_protogen/tests/test-data/compiled/foo-proto_rkt.zo'
        at com.google.devtools.build.lib.actions.Actions.maybeFilterSharedActionsAndThrowIfConflict(Actions.java:124)
        at com.google.devtools.build.lib.actions.Actions.filterSharedActionsAndThrowActionConflict(Actions.java:110)
        at com.google.devtools.build.lib.actions.ActionLookupValue.filterSharedActionsAndThrowRuntimeIfConflict(ActionLookupValue.java:47)
        ... 9 more
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
