### ISSUE TITLE
rules_scala is broken in the nightly

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3792]
This comes from the beginning of the week, this is the only breakage in the nightly that is yet to be triaged

From http://ci.bazel.io/blue/organizations/jenkins/Global%2Frules_scala/detail/rules_scala/185/pipeline/:

```
[rules_scala-variation=,node=darwin-x86_64] Running shell script
+ /Users/ci/.bazel/custom/bazel_nightly/58/variation_/binary/bazel --bazelrc=/Users/ci/workspace/Global/rules_scala-variation=,node=darwin-x86_64/bazel.bazelrc build //test/...
INFO: Loading package: test/src/main/scala/scala/test/srcjars
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @local_jdk//
INFO: Loading package: @local_config_xcode//
INFO: Loading package: @local_config_cc//
INFO: Loading complete.  Analyzing...
INFO: Loading package: tools/defaults
INFO: Loading package: @java_stub_template//file
INFO: Loading package: src/java/io/bazel/rulesscala/io_utils
INFO: Loading package: @io_bazel_rules_scala//src/java/io/bazel/rulesscala/scalac
INFO: Loading package: @io_bazel_rules_scala_org_hamcrest_hamcrest_core//jar
INFO: Loading package: @bazel_tools//src
INFO: Loading package: @bazel_tools//src/tools/launcher
INFO: Loading package: @io_bazel_rules_scala//src/java/com/google/devtools/build/lib
INFO: Loading package: @bazel_tools//src/main/cpp/util
INFO: Loading package: @util_core//jar
ERROR: /private/var/tmp/_bazel_ci/260c930937124e8448b4498dcb02e365/external/io_bazel_rules_scala/third_party/plugin/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/plugin/src/main:dependency_analyzer: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ci/260c930937124e8448b4498dcb02e365/external/io_bazel_rules_scala/third_party/plugin/src/main/BUILD", line 5
		scala_library_for_plugin_bootstrapping(name = 'dependency_analyzer')
	File "/private/var/tmp/_bazel_ci/260c930937124e8448b4498dcb02e365/external/io_bazel_rules_scala/scala/scala.bzl", line 661, in _scala_library_impl
		_lib(ctx, True)
	File "/private/var/tmp/_bazel_ci/260c930937124e8448b4498dcb02e365/external/io_bazel_rules_scala/scala/scala.bzl", line 627, in _lib
		java_common.create_provider(compile_time_jars = scalaattr.co..., <3 more arguments>)
In java_common.create_provider the value of use_ijar is True. Make sure the first argument of the function is the ctx.actions object.
ERROR: Analysis of target '//test:JUnitCompileTimeDep' failed; build aborted: Analysis of target '@io_bazel_rules_scala//third_party/plugin/src/main:dependency_analyzer' failed; build aborted.
INFO: Elapsed time: 8.446s
INFO: Waiting for build event protocol upload: 0s
script returned exit code 1
```

/cc @iirina @dslomov: either comes from skylark or from java_common.

**Comment by damienmg** [comment]
@iirina told me it is a planned breaking change and @ittaiz is supposed to take care of the breakage on rules_scala side.

**Comment by ittaiz** [comment]
Indeed expecting breaking API changes

**Comment by katre** [comment]
Filed https://github.com/bazelbuild/rules_scala/issues/280 on rules_scala to track this there.

**Comment by mhlopko** [comment]
Assigning Irina just to keep an eye on this :P
