### ISSUE TITLE
`maven_aar` rule doesn't work with `com.android.support:preference-v7`

### ISSUE THREAD

**Issue by fishy** [bazelbuild/bazel#3845]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

For any existing, working Android project:

Add the following `external/mave-google.xml` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
      <id>google</id>
      <repositories>
        <repository>
          <id>google</id>
          <name>Google</name>
          <snapshots>
            <enabled>true</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://maven.google.com</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>google</activeProfile>
  </activeProfiles>
</settings>
```

Add the following lines into `WORKSPACE` file:

```python
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_aar")

maven_aar(
    name = "preference_v7",
    artifact = "com.android.support:preference-v7:26.0.2",
    settings = "maven-google.xml",
)
```

Add the following lines into `BUILD` file:

```python
android_library(
    name = "preference_v7",
    exports = ["@preference_v7//aar"],
)
```

Then add `:preference_v7` to the `deps` of `android_binary` rule (let's say it's called `:app`).

`bazel build :preference_v7` works, but `bazel build :app` will show the following error:

```
ERROR: /private/var/tmp/_bazel_fishy/0d3057e4844ea90c65540bdc76dcdc27/external/preference_v7/aar/BUILD:4:1: Merging Android resources for @preference_v7//aar:aar failed (Exit 1).
Sep 29, 2017 10:33:32 PM com.google.devtools.build.android.AndroidResourceMergingAction main
SEVERE: Error during merging resources
com.google.devtools.build.android.AndroidResourceMerger$MergingException: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:45)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:104)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:191)
	at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:91)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:166)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:99)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:75)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:94)
	... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:446)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:362)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:91)
	... 6 more

Exception in thread "main" com.google.devtools.build.android.AndroidResourceMerger$MergingException: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:45)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:104)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:191)
	at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:91)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:166)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:99)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:75)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:94)
	... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: selectableItemBackground
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:446)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:362)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:91)
	... 6 more
Target //:app failed to build
```

### Environment info
* Operating System:
macOS 10.12.6

* Bazel version (output of `bazel info release`):
release 0.6.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

Looks like `preference-v7` is the only one that does NOT work. I didn't see any issue in other Android support libraries (tried `appcompat_v7`, `cardview_v7`, `recyclerview_v7`, `support_compat`, `support_core_ui`, `support_core_utils`, `support_fragment`)

**Comment by aj-michael** [comment]
Hi @fishy, thanks for the detailed reprieve. I’m not at a computer right now to debug, but this is almost certainly because bazel’s Maven rules do not pull in transitive dependencies. The preference v7 Library likely contains resources that depend on resources from appcompat v7, which is causing this failure when we process the resources in the android_library.

As a workaround, you can use Bazel’s support for the Android Support Libraries from within the SDK with @androidsdk//com.android.support:preference-v7-26.0.2. This is documented here: https://docs.bazel.build/versions/master/be/android.html#android_sdk_repository_support_libraries

cc @jin who created the skylark maven rules

**Comment by fishy** [comment]
- I tried to also depends on `appcompat_v7` (and all `support_*` packages I mentioned), either on the `android_library` rule `preference_v7` itself or the `android_binary` rule, none worked.
- Android SDK stopped shipping support libraries after `26.0.0-alpha1`. So the only way to get anything after `26.0.0` is through maven. Yes the Android SDK bundled version works, but I need newer version for Oreo.

**Comment by aj-michael** [comment]
Sorry this took so long.

431b6436373c9feb5d03e488ff72f822bbe55b2d adds a deps attribute to the skylark maven_aar rule which allows users to wire up dependencies between their transitive deps.

I've also created an example bzl file that creates repositories and the dependencies for all artifacts on https://maven.google.com, which includes the support libraries: 

https://github.com/aj-michael/gmaven_rules

**Comment by fishy** [comment]
Thanks, @aj-michael. I can confirm that `preference-v7` now works in the new version (0.8.1).

But I have to point out that using your gmaven_rules does not resolve all the dependency problems. For example in https://github.com/fishy/onepwd/blob/703eb3588fcd8ba80edcbcf046e39b60cbbb7d86/BUILD#L40-L49, I still need to specify a lot of dependencies manually (the ones I used directly are `com_android_support_appcompat_v7_27_0_1` and `com_android_support_preference_v7_27_0_1`, all the others are dependencies I have to add manually. Also `android_arch_core_common_1_0_0`, `android_arch_lifecycle_runtime_1_0_3` and `com_android_support_support_vector_drawable_27_0_1` are runtime dependencies which means it still compiles after removing them, but there will be runtime errors).

A suggestion: can you make git tags for your gmaven_rules? This will make referring the repo in Bazel WORKSPACE files easier.

**Comment by fishy** [comment]
Never mind about the second paragraph. I think it's actually something wrong with the kotlin rule implementation.

**Comment by marup** [comment]
I have the same dependency issues you mention in your second paragraph on Dec 6, 2017. I am using aj-michael's gmaven_rules referenced above (commit 5e89b7c , but have to manually add a number of dependencies, including the ones you mentioned (android_arch_core_common_1_0_0, android_arch_lifecycle_runtime_1_0_3, android_arch_lifecycle_common_1_0_3, com_android_support_support_vector_drawable_27_0_0, etc.). For example, I'm not using RecyclerView directly, but still have to include com_android_support_recyclerview_v7_27_0_0, in order to not get runtime errors.

**Comment by aj-michael** [comment]
@marup - this was a bug I just fixed in aar_import: https://github.com/bazelbuild/bazel/issues/4472

Workarounds include replacing deps with exports in the gmaven bzl file, or waiting for the next bazel release.

**Comment by jin** [comment]
@fishy gmaven_rules are now release based. Check out the releases here: https://github.com/bazelbuild/gmaven_rules/releases
