### ISSUE TITLE
Nested workspaces broken in Bazel 0.6.0

### ISSUE THREAD

**Issue by duggelz** [bazelbuild/bazel#3874]
### Description of the problem / feature request / question:

Having nested workspaces worked in Bazel 0.5.4 and below, but seems to be broken in 0.6.0 and above.  I'm not sure if this is a bug or an intentional removal.

By "nested workspaces", I mean a directory structure like this:

```
mydir/
    WORKSPACE
    BUILD
    ... other files ... 
    mysubdir/
        WORKSPACE
        ... files ...
```

Previously, Bazel would properly handle this, treat `mysubdir` not as part of `mydir`, and I could reference `mysubdir` in the parent WORKSPACE via `local_repository` rules.  (I do this for testing a skylark rule if you're wondering).  Now, Bazel fails with an error (see below).

### If possible, provide a minimal example to reproduce the problem:

https://github.com/google/subpar/tree/dgreiman/blaze-nested-workspaces

`blaze test //...` (or any blaze command)

### Environment info
* Operating System:
  Goobuntu 14.04

* Bazel version (output of `bazel info release`):
  release 0.6.1

###  Have you found anything relevant by searching the web?

No

### Anything else, information or logs or outputs that would be helpful?

Output from Bazel:

```
$ bazel test //...
...............
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE_LOOKUP:tests/test_workspace' (requested by nodes 'RECURSIVE_PKG:rootedPath=[/usr/local/google/home/dgreiman/code/github/subpar]/[tests/test_workspace], excludedPaths=<omitted>)')
INFO: Elapsed time: 0.720s
FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE_LOOKUP:tests/test_workspace' (requested by nodes 'RECURSIVE_PKG:rootedPath=[/usr/local/google/home/dgreiman/code/github/subpar]/[tests/test_workspace], excludedPaths=<omitted>)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: PathFragment tests/test_workspace is not beneath /usr/local/google/home/dgreiman/code/github/subpar/tests/test_workspace
	at com.google.devtools.build.lib.vfs.PathFragment.relativeTo(PathFragment.java:505)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.getPackageLookupValue(PackageLookupFunction.java:235)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.findPackageByBuildFile(PackageLookupFunction.java:128)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.compute(PackageLookupFunction.java:106)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE_LOOKUP:tests/test_workspace' (requested by nodes 'RECURSIVE_PKG:rootedPath=[/usr/local/google/home/dgreiman/code/github/subpar]/[tests/test_workspace], excludedPaths=<omitted>)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: PathFragment tests/test_workspace is not beneath /usr/local/google/home/dgreiman/code/github/subpar/tests/test_workspace
	at com.google.devtools.build.lib.vfs.PathFragment.relativeTo(PathFragment.java:505)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.getPackageLookupValue(PackageLookupFunction.java:235)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.findPackageByBuildFile(PackageLookupFunction.java:128)
	at com.google.devtools.build.lib.skyframe.PackageLookupFunction.compute(PackageLookupFunction.java:106)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
	... 4 more
```

**Comment by duggelz** [comment]
Ok, I have a workaround.

In 0.5.4, I had a `WORKSPACE` like this:

```
workspace(name = "subpar")

local_repository(
    name = "test_workspace",
    path = __workspace_dir__ + "/tests/test_workspace",
)
```

In 0.6.0, I can make it work by changing it to something like this:

```
workspace(name = "subpar")

local_repository(
    name = "test_workspace",
    path = "tests/test_workspace",
)
```

I don't know why I even used `__workspace_dir__` in the first place.

I'll leave this bug open for Bazel maintainers to decide if this should be documented, fixed, ignored as too obscure, or what.

**Comment by damienmg** [comment]
Seems like giving a full path to a nested workspace breaks the nested workspace detection.

**Comment by katre** [comment]
Yeah, that shouldn't be an error, I will investigate.
