### ISSUE TITLE
Windows presubmit failure: GetExitCodeProcess(): The handle is invalid.

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3912]
We saw this on the internal CI (bug 67878584).

Two parts of the build log:
```
Caused by: java.lang.IllegalStateException: GetExitCodeProcess(): The handle is invalid.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.exitValue(WindowsSubprocess.java:195)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.waitForProcess(FutureCommandResultImpl.java:89)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:42)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:270)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:153)
```

In the same log, further down:

```
ERROR: T:/tmp/tmpg24w5c/third_party/BUILD:370:1: Extracting interface //third_party:guava failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: ijar.exe failed: error executing command 
  cd T:/tmp/_bazel_kbuilder/glwgywz0/execroot/io_bazel
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\msys64\usr\bin\;C:\python27;C:\cygwin64\bin;(...);C:\Windows\System32\WindowsPowerShell\v1.0
    SET TEMP=T:\tmp
    SET TMP=T:\tmp
  external/bazel_tools/tools/jdk/ijar/ijar.exe third_party/error_prone/error_prone_annotations-2.1.1.jar bazel-out/host/genfiles/third_party/_ijar/guava/third_party/error_prone/error_prone_annotations-2.1.1-ijar.jar.
Action failed to execute: java.io.IOException: CreatePipe(stdin): The handle is invalid.
```

/cc @lberki

**Comment by laszlocsomor** [comment]
@meteorcloudy -- do you think https://bazel-review.googlesource.com/c/bazel/+/18790 could be relevant here?

**Comment by meteorcloudy** [comment]
That change is not yet submitted. Do you still have the CI link? If it's CR presubmit, it could be.
But I haven't seen this error before.

**Comment by laszlocsomor** [comment]
I don't, but see the internal bug for more data.
The CI run was for the change that we pushed as https://github.com/bazelbuild/bazel/commit/aae614aa45f17ad3932aec59d52d6bc7074d814d.

**Comment by meteorcloudy** [comment]
So it doesn't seem to be caused by  https://bazel-review.googlesource.com/c/bazel/+/18790 
I guess we don't yet have a reproduce out of Kokoro?

**Comment by laszlocsomor** [comment]
Not yet.

**Comment by laszlocsomor** [comment]
Dropping priority because I haven't seen this bug ever since.
