### ISSUE TITLE
Hard crash when trying to open repository with bad url

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3914]
The following causes a hard crash. I expect it to not crash and just print out an error. 

Bazel version 0.6.1

In the workspace file:
```
http_archive(
  name = "distroless",
  sha256 = "a6e4607f270465455f5d62480f805fde236b60762411944e24f62ebf260a4c81",
  strip_prefix = "distroless-494d25e5f55ed8d14fbc66934e53a0a9cb2309b9",
  urls = ["https://github.com/404"]
)
```

```
endobson@yggdrasil () ~/proj/racket/minimal-racket % bazel build @distroless//...
Unhandled exception thrown during build; message: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/404] to /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/distroless/404: Checksum was 97138ae643ffb9f0c501e0e8b4d10aba9473f7193f6a0bcc4931685b05ab067f but wanted a6e4607f270465455f5d62480f805fde236b60762411944e24f62ebf260a4c81 rootCauses={REPOSITORY_DIRECTORY:@distroless} cycles=[]>
INFO: Elapsed time: 1.237s
FAILED: Build did NOT complete successfully
java.lang.IllegalArgumentException: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/404] to /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/distroless/404: Checksum was 97138ae643ffb9f0c501e0e8b4d10aba9473f7193f6a0bcc4931685b05ab067f but wanted a6e4607f270465455f5d62480f805fde236b60762411944e24f62ebf260a4c81 rootCauses={REPOSITORY_DIRECTORY:@distroless} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeysBatch(SkyframeTargetPatternEvaluator.java:232)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:152)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:460)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:339)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: <ErrorInfo exception=java.io.IOException: Error downloading [https://github.com/404] to /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/distroless/404: Checksum was 97138ae643ffb9f0c501e0e8b4d10aba9473f7193f6a0bcc4931685b05ab067f but wanted a6e4607f270465455f5d62480f805fde236b60762411944e24f62ebf260a4c81 rootCauses={REPOSITORY_DIRECTORY:@distroless} cycles=[]>
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeysBatch(SkyframeTargetPatternEvaluator.java:232)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:152)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:58)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:256)
        at com.google.devtools.build.lib.skyframe.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.evaluateTargetPatterns(BuildTool.java:460)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:339)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by aehlig** [comment]
Bazel at head now gives a clean error message. So issue has already been fixed.
