### ISSUE TITLE
testShBinaryLauncher test broken on Windows.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3918]
https://ci.bazel.io/job/bazel-tests/1091/testReport/src_test_py_bazel_launcher_test/exe/src_test_py_bazel_launcher_test_exe/
```
exited with error code 1
Standard Output

...F.
======================================================================
FAIL: testShBinaryLauncher (__main__.LauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\windows\temp\Bazel.runfiles_ybibfj\runfiles\io_bazel\src\test\py\bazel\launcher_test.py", line 270, in testShBinaryLauncher
    if self.IsWindows() else '')
  File "c:\windows\temp\Bazel.runfiles_ybibfj\runfiles\io_bazel\src\test\py\bazel\launcher_test.py", line 88, in _buildShBinaryTargets
    os.linesep.join(stderr))
AssertionError: 'target name extension should match source file extension.' not found in u"Loading:\r\nLoading: 0 packages loaded\r\nERROR: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e44c473f33f8fd476c811c22e44d8fec/tests_root/tmpjlvbqf/foo/BUILD:11:1: in sh_binary rule //foo:bin3.bat: Source file is a Windows executable file, target name extension should match source file extension\r\nERROR: Analysis of target '//foo:bin3.bat' failed; build aborted: Analysis of target '//foo:bin3.bat' failed; build aborted\r\nINFO: Elapsed time: 1.091s\r\nFAILED: Build did NOT complete successfully (0 packages loaded)\r\nINFO: $TEST_TMPDIR defined: output root default is 'c:\\windows\\temp\\_bazel_system\\7bqgevoe\\execroot\\io_bazel\\_tmp\\e44c473f33f8fd476c811c22e44d8fec'."

----------------------------------------------------------------------
Ran 5 tests in 147.844s
```

**Comment by buchgr** [comment]
cc: @laszlocsomor @meteorcloudy

**Comment by meteorcloudy** [comment]
This should be fixed by https://bazel-review.googlesource.com/#/c/bazel/+/19192/
