### ISSUE TITLE
experimental_remote_spawn_cache doesn't work 

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#3930]
I forgot to add RequestMetadata to the context of RemoteSpawnCache:

Caused by: java.lang.IllegalStateException: RequestMetadata not set in current context.
	at com.google.devtools.build.lib.remote.TracingMetadataUtils.fromCurrentContext(TracingMetadataUtils.java:74)
	at com.google.devtools.build.lib.remote.TracingMetadataUtils.headersFromCurrentContext(TracingMetadataUtils.java:87)
	at com.google.devtools.build.lib.remote.TracingMetadataUtils.attachMetadataFromContextInterceptor(TracingMetadataUtils.java:92)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.casBlockingStub(GrpcRemoteCache.java:94)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$getMissingDigests$0(GrpcRemoteCache.java:133)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:203)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.getMissingDigests(GrpcRemoteCache.java:133)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.upload(GrpcRemoteCache.java:349)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.upload(GrpcRemoteCache.java:302)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:151)

**Comment by ola-rozenfeld** [comment]
Correction: I didn't forget to attach it, I just attached it badly (the context does not apply to the returned CacheHanldle class in line 130). Will add a test for this.
