### ISSUE TITLE
Bazel crashes on test success with error java.lang.IllegalStateException

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#3931]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel crashes on test success with `error java.lang.IllegalStateException`

### If possible, provide a minimal example to reproduce the problem:

You can view the results of a TravisCI run here https://travis-ci.org/bazelbuild/bazel-watcher/jobs/288897545

git clone git@github.com:bazelbuild/bazel-watcher.git
cd bazel-watcher
bazel test //...

### Environment info
* Operating System:
Linux and macOS

* Bazel version (output of `bazel info release`):

0.6.1 but also happens on 0.7.0 locally on my laptop.

###  Have you found anything relevant by searching the web?

Not really, it's a prety opaque error. The only results I've found on the web are the actual line of code that throws the exception.

It may be fixed by https://github.com/bazelbuild/bazel/commit/59984b5bb795f6067117be47c44ddb21ccc376de, but even with that new message it's not clear what I am doing wrong.

### Anything else, information or logs or outputs that would be helpful?

https://travis-ci.org/bazelbuild/bazel-watcher/jobs/288897545

**Comment by janakdr** [comment]
Are there logs with the new error? And is this 100% reproducible, or flaky?

**Comment by zmarcantel** [comment]
I am seeing the same thing.

Ironically enough while making a minimal starting point for bazel + cpp.

can be found here: https://github.com/zmarcantel/bazel-bootstrap


# Bazel info

```
zach@glenn $ bazel info
bazel-bin: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin
bazel-genfiles: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/genfiles
bazel-testlogs: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/command.log
committed-heap-size: 322MB
execution_root: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/execroot/__main__
gc-count: 5
gc-time: 55ms
install_base: /var/tmp/_bazel_zach/install/dce1089a74457f8114fdf5e74801035d
java-home: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
java-runtime: Java(TM) SE Runtime Environment (build 1.8.0_152-b16) by Oracle Corporation
java-vm: Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode) by Oracle Corporation
max-heap-size: 3817MB
message_log: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/message.log
output_base: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4
output_path: /private/var/tmp/_bazel_zach/95b3555c02843b32421808c1559172f4/execroot/__main__/bazel-out
package_path: %workspace%
release: release 0.7.0-homebrew
server_pid: 37621
used-heap-size: 122MB
workspace: /Users/zach/projects/bazel-bootstrap
```

# Bazel test output

```
zach@glenn $ bazel test ... --test_output=all
INFO: Found 6 targets and 3 test targets...
INFO: Elapsed time: 0.683s, Critical Path: 0.02s
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:196)
	at com.google.devtools.build.lib.runtime.TestResultAnalyzer.differentialAnalyzeAndReport(TestResultAnalyzer.java:115)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.analyzeTestResults(TestCommand.java:176)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:149)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:104)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:196)
	at com.google.devtools.build.lib.runtime.TestResultAnalyzer.differentialAnalyzeAndReport(TestResultAnalyzer.java:115)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.analyzeTestResults(TestCommand.java:176)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:149)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:104)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

# Straight binary run

```
zach@glenn $ ./bazel-bin/test/foo_test
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Foo
[ RUN      ] Foo.Works
[       OK ] Foo.Works (0 ms)
[----------] 1 test from Foo (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```


# Specifying a specific target does work

```
zach@glenn $ bazel test //test:foo_test --test_output=all
INFO: Found 1 test target...
INFO: From Linking external/googletest/libgtest_main.so:
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
INFO: From Linking external/googletest/libgtest.so:
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
INFO: From Linking test/foo_test:
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
INFO: From Testing //test:foo_test:
==================== Test output for //test:foo_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Foo
[ RUN      ] Foo.Works
[       OK ] Foo.Works (0 ms)
[----------] 1 test from Foo (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
================================================================================
Target //test:foo_test up-to-date:
  bazel-bin/test/foo_test
INFO: Elapsed time: 4.318s, Critical Path: 2.21s
//test:foo_test                                                          PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
```

**Comment by janakdr** [comment]
Hmm, the repro works for me on 0.8.0. Can you check to see if it's still failing for you?
