### ISSUE TITLE
MAX_MEMORY_KBYTES in SimpleBlobStoreActionCache?

### ISSUE THREAD

**Issue by tybook** [bazelbuild/bazel#3939]
### Description of the problem / feature request / question:

I am trying to use a REST remote cache (Apache w/ WebDAV) for the first time with my org's codebase. My `tools/bazel.rc` contains:
```
startup --host_jvm_args=-Dbazel.DigestFunction=SHA1
build --experimental_remote_spawn_cache
build --remote_rest_cache=http://CACHE.SERVER.IP
```

I have it set up and mostly working, but at least one of our build artifacts is larger than the 512MiB hard-coded upload/download size limit enforced by the `MAX_MEMORY_KBYTES` constant in `src/main/java/com/google/devtools/build/lib/remote/SimpleBlobStoreActionCache.java`, so my build errors. Trying to build the offending artifact results in:
```
<snip>
Caused by: java.lang.IllegalArgumentException: Upload: maximum blob size exceeded: 568045K > 524288K.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.checkBlobSize(SimpleBlobStoreActionCache.java:252)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:265)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:260)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadFileContents(SimpleBlobStoreActionCache.java:97)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:210)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:180)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:151)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:100)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:66)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:261)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:269)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:850)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:793)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:107)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:661)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:618)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:404)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
	... 4 more
``` 

**Why is the limit set to this value? Can it be made configurable?** Just bumping the hard-coded value up to, say, 2GiB would also work for my case.

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
`release 0.7.0`

**Comment by tybook** [comment]
dupe of #3250
