### ISSUE TITLE
bazel crash on native.package_name()

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel#3983]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Please take a look https://github.com/excavador/bazel_native_package_name_crash

### If possible, provide a minimal example to reproduce the problem:

Please take a look https://github.com/excavador/bazel_native_package_name_crash

### Environment info
macOS Sierra 10.12.6

```
➜ bazel version
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 09:12:48 2017 (1508404368)
Build timestamp: 1508404368
```

**Comment by excavador** [comment]
Any updates?

**Comment by mpictor** [comment]
I seem to have hit something quite similar with
```python
# mypkg/BUILD
load("//:my.bzl","my_lib")

my_lib(
    srcs=glob(["*.cpp","*.h"]),
)

###################
# my.bzl
def my_lib(
        name=native.package_name(),
        srcs=None,
        deps=None):
    native.cc_library(
        name=name,
        srcs=srcs+tier_hdrs(name),
        hdrs=pub_hdrs(name),
        deps=deps
    )
```

backtrace:
```no-highlight
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:mypkg' (requested by nodes '//mypkg')
INFO: Elapsed time: 0.077s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:mypkg' (requested by nodes '//mypkg')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: update(value == null)
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:349)
        at com.google.devtools.build.lib.syntax.Environment.update(Environment.java:776)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:75)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:741)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:713)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:65)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:196)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:178)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:226)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:199)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1688)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1331)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1289)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:559)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:mypkg' (requested by nodes '//mypkg')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: update(value == null)
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:349)
        at com.google.devtools.build.lib.syntax.Environment.update(Environment.java:776)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:75)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:741)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:713)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:65)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:196)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:178)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:226)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:199)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1688)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1331)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1289)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:559)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
```

**Comment by mpictor** [comment]
same with `v 0.8.1`
```
Build label: 0.8.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Dec 17 03:39:56 2017 (1513481996)
Build timestamp: 1513481996
Build timestamp as int: 1513481996
```

**Comment by laurentlb** [comment]
Sorry for the delay, it's now fixed (as in: it doesn't crash anymore). But I have to point out that you should update your code. You cannot use `package_name` as a default argument.

When bzl files are evaluated, there's no information of package. Multiple BUILD files may reference the same bzl file, so `native.package_name` is failing when you use it in the bzl file (as a default argument or in a global variable). However, the package is defined when a BUILD file calls a function in a bzl file.

Suggested fix:
```
def my_lib(
        name=None,
        srcs=None,
        deps=None):
    name = name or native.package_name()
    native.cc_library(
        name=name,
        srcs=srcs,
        deps=deps
    )
```

**Comment by excavador** [comment]
@laurentlb thank you for update!
I understand now, why it's incorrect. 
Will update my BUILD file.
