### ISSUE TITLE
@zlib seems to conflict with internal zlib bazel definitions.

### ISSUE THREAD

**Issue by jeremyje** [bazelbuild/bazel#3986]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
bazel build @zlib//... crashes with the following data.

Looks like there's a conflict with the internal zlib from the repository which isn't accessible. Renaming to @zlib1 works.

**WORKSPACE file**
```
new_http_archive(
  name = "zlib1",
  urls = [
    "http://localhost:8080/archives/zlib-1.2.11.tar.gz",
  ],
  strip_prefix = "zlib-1.2.11",
  build_file = "third_party/zlib.BUILD",
)
```

**third_party/zlib.BUILD**
```
package(
  default_visibility = ["//visibility:public"],
)

cc_library(
    name = "zlib",
    hdrs = glob([
      "*.h",
    ]),
    srcs = glob([
      "*.c",
    ]),
    linkstatic = 1,
)

cc_binary(
  name = "gun",
  srcs = ["examples/gun.c"],
  deps = [
    ":zlib",
  ],
)

```

### Environment info
* Operating System: Linux

* Bazel version (output of `bazel info release`):
bazel info release
release 0.7.0

###  Have you found anything relevant by searching the web?
```
bazel build @zlib//...
......
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
INFO: Elapsed time: 0.289s
FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No such repository '@zlib'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:594)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No such repository '@zlib'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:594)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=10005) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=10005) to terminate.
Attempted to kill stale server process (pid=10005) using SIGKILL, but it did not die in a timely fashion.
c9user:~/workspace/btest/root $ bazel build @zlib1//...                                                                       
......
INFO: Analysed 2 targets (9 packages loaded).
INFO: Found 2 targets...
INFO: From Compiling external/zlib1/gzlib.c:
external/zlib1/gzlib.c: In function 'gz_open':
external/zlib1/gzlib.c:14:17: warning: implicit declaration of function 'lseek' [-Wimplicit-function-declaration]
 #  define LSEEK lseek
                 ^
external/zlib1/gzlib.c:252:9: note: in expansion of macro 'LSEEK'
         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
         ^~~~~
INFO: From Compiling external/zlib1/gzread.c:
external/zlib1/gzread.c: In function 'gz_load':
external/zlib1/gzread.c:35:15: warning: implicit declaration of function 'read' [-Wimplicit-function-declaration]
         ret = read(state->fd, buf + *have, get);
               ^~~~
external/zlib1/gzread.c: In function 'gzclose_r':
external/zlib1/gzread.c:651:11: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
     ret = close(state->fd);
           ^~~~~
INFO: From Compiling external/zlib1/gzwrite.c:
external/zlib1/gzwrite.c: In function 'gz_comp':
external/zlib1/gzwrite.c:89:20: warning: implicit declaration of function 'write' [-Wimplicit-function-declaration]
             writ = write(state->fd, strm->next_in, put);
                    ^~~~~
external/zlib1/gzwrite.c: In function 'gzclose_w':
external/zlib1/gzwrite.c:661:9: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
     if (close(state->fd) == -1)
         ^~~~~
INFO: Elapsed time: 1.633s, Critical Path: 0.13s
INFO: Build completed successfully, 23 total actions
c9user:~/workspace/btest/root $ bazel build @zlib//...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
INFO: Elapsed time: 0.113s
FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No such repository '@zlib'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:594)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@zlib//...' (requested by nodes '[@zlib//...]com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No such repository '@zlib'
        at com.google.devtools.build.lib.skyframe.EnvironmentBackedRecursivePackageProvider.getPackagesUnderDirectory(EnvironmentBackedRecursivePackageProvider.java:139)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:280)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:594)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
```

**Comment by damienmg** [comment]
Pulling in @janakdr because I have no idea what's going on there.

**Comment by janakdr** [comment]
I don't think I can help here. The exception is being thrown in EnvironmentBackedRecursivePackageProvider because the repository doesn't exist. Why it doesn't exist is far outside my expertise.

**Comment by damienmg** [comment]
What happen if you do `bazel fetch @zlib//...`?

**Comment by damienmg** [comment]
(also the ISE is definitely wrong if the repository not found exception is thrown, the error should bubble up).

**Comment by janakdr** [comment]
See the [comment](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/EnvironmentBackedRecursivePackageProvider.java#L138) in EnvironmentBackedRecursivePackageProvider. The repository should already have been verified. Given that there's some skew here, I don't know that crashing is the wrong thing to do. Maybe @ulfjack has some opinion?

**Comment by ulfjack** [comment]
The WORKSPACE file in the initial report says 'name = "zlib1"' (note the trailing 1). Is that intentional? If so, why are you trying to build @zlib//...?

**Comment by jeremyje** [comment]
zlib1 is the workaround. Rename the targets to zlib and you'll repro the error.

**Comment by ulfjack** [comment]
Works for me at head. Do you still see issues?
