### ISSUE TITLE
native.repository_name() throws

### ISSUE THREAD

**Issue by jonnrb** [bazelbuild/bazel#4007]
### Description of the problem / feature request / question:

[native.repository_name()](https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name) throws an exception when used.

### If possible, provide a minimal example to reproduce the problem:
```bzl
def not_good_fn():
  return native.repository_name()
```

### Environment info
* Operating System: macOS High Sierra

* Bazel version (output of `bazel info release`): `release 0.7.0-homebrew`

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//:avcodec')
INFO: Elapsed time: 0.631s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//:avcodec')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.syntax.EvalUtils.getDataTypeName(EvalUtils.java:205)
	at com.google.devtools.build.lib.syntax.EvalUtils.getDataTypeName(EvalUtils.java:197)
	at com.google.devtools.build.lib.syntax.Type$ConversionException.message(Type.java:260)
	at com.google.devtools.build.lib.syntax.Type$ConversionException.<init>(Type.java:265)
	at com.google.devtools.build.lib.syntax.Type$StringType.convert(Type.java:419)
	at com.google.devtools.build.lib.syntax.Type$StringType.convert(Type.java:395)
	at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:595)
	at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:533)
	at com.google.devtools.build.lib.packages.BuildType.selectableConvert(BuildType.java:172)
	at com.google.devtools.build.lib.packages.RuleClass.convertFromBuildLangType(RuleClass.java:1825)
	at com.google.devtools.build.lib.packages.RuleClass.populateDefinedRuleAttributeValues(RuleClass.java:1529)
	at com.google.devtools.build.lib.packages.RuleClass.populateRuleAttributeValues(RuleClass.java:1486)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1434)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:129)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:175)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:216)
	at com.google.devtools.build.lib.packages.PackageFactory.addRule(PackageFactory.java:1201)
	at com.google.devtools.build.lib.packages.PackageFactory.access$900(PackageFactory.java:96)
	at com.google.devtools.build.lib.packages.PackageFactory$9.invoke(PackageFactory.java:1242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:166)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:741)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:713)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:65)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:196)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:178)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:226)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:199)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1688)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1331)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1289)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:559)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//:avcodec')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.syntax.EvalUtils.getDataTypeName(EvalUtils.java:205)
	at com.google.devtools.build.lib.syntax.EvalUtils.getDataTypeName(EvalUtils.java:197)
	at com.google.devtools.build.lib.syntax.Type$ConversionException.message(Type.java:260)
	at com.google.devtools.build.lib.syntax.Type$ConversionException.<init>(Type.java:265)
	at com.google.devtools.build.lib.syntax.Type$StringType.convert(Type.java:419)
	at com.google.devtools.build.lib.syntax.Type$StringType.convert(Type.java:395)
	at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:595)
	at com.google.devtools.build.lib.syntax.Type$ListType.convert(Type.java:533)
	at com.google.devtools.build.lib.packages.BuildType.selectableConvert(BuildType.java:172)
	at com.google.devtools.build.lib.packages.RuleClass.convertFromBuildLangType(RuleClass.java:1825)
	at com.google.devtools.build.lib.packages.RuleClass.populateDefinedRuleAttributeValues(RuleClass.java:1529)
	at com.google.devtools.build.lib.packages.RuleClass.populateRuleAttributeValues(RuleClass.java:1486)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1434)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:129)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:175)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:216)
	at com.google.devtools.build.lib.packages.PackageFactory.addRule(PackageFactory.java:1201)
	at com.google.devtools.build.lib.packages.PackageFactory.access$900(PackageFactory.java:96)
	at com.google.devtools.build.lib.packages.PackageFactory$9.invoke(PackageFactory.java:1242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:166)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:741)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:713)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:65)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:196)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:178)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:226)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:199)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1688)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingAst(PackageFactory.java:1331)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1289)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:559)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
	... 4 more
```

**Comment by meisterT** [comment]
I could not repro this anymore.
