### ISSUE TITLE
Accessing the CPP config fragment attribute `sysroot` crashes Bazel

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#4074]
`cpp.sysroot` is documented at https://docs.bazel.build/versions/master/skylark/lib/cpp.html#sysroot as being a `string`, or `None` in some cases. But when I try to access it with `print("sysroot: ", ctx.fragments.cpp.sysroot)` it crashes Bazel:

```
java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.cpp.CppConfiguration.getSysroot(CppConfiguration.java:709)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[...]
```

**Comment by steeve** [comment]
Still crash on 0.10.1

**Comment by jmillikin** [comment]
Closing as obsolete now that the C++ toolchain implementation has been overhauled.
