### ISSUE TITLE
dict methods (but not subscripting) leak the underlying Java types

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#4117]
Consider a little workspace with `example.bzl`:
```
def example_impl(ctx):
    print(dir(ctx.attr.d['key']))
    print(dir(ctx.attr.d.get('key')))
    return struct()

example = rule(
    implementation = example_impl,
    attrs = {'d': attr.string_list_dict()},
)
```

and `BUILD`:
```
load(':example.bzl', 'example')
example(
    name = 'ex',
    d = {'key': []},
)
```

Running `bazel build //:ex` should print the same line twice, but instead, it earns you an error:
```
DEBUG: example.bzl:2:5: ["append", "extend", "index", "insert", "pop", "remove"]
ERROR: BUILD:3:1: in example rule //:ex:
Traceback (most recent call last):
    File "BUILD", line 3
        example(name = 'ex')
    File "example.bzl", line 3, in example_impl
        print(dir(ctx.attr.dict.get("key")))
    File "example.bzl", line 3, in print
        dir(ctx.attr.dict.get("key"))
illegal argument in call to dir: class java.util.ArrayList is not allowed as a Skylark value (getSkylarkType() failed)
ERROR: Analysis of target '//:ex' failed; build aborted: Analysis of target '//:ex' failed; build aborted
```

The problem is `IndexExpression` [coerces the result of subscripting into a skylark value](https://github.com/bazelbuild/bazel/blob/2af2bff08c2fab136ea0927242bd4f3fe05456bf/src/main/java/com/google/devtools/build/lib/syntax/IndexExpression.java#L65-L68) whereas the dict methods do not.

**Comment by laurentlb** [comment]
I think this has been fixed:

```
$ bazel build //:ex
Starting local Bazel server and connecting to it...
DEBUG: /tmp/bazel/example.bzl:2:5: ["append", "extend", "index", "insert", "pop", "remove"]
DEBUG: /tmp/bazel/example.bzl:3:5: ["append", "extend", "index", "insert", "pop", "remove"]
```
