### ISSUE TITLE
cc_proto_library rule broken on Windows with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4126]
```
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\\VC
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ASPECT:[]#BazelCcProtoAspect e0f402e95abd03057d52ad714d5ada1b e0f402e95abd03057d52ad714d5ada1b {$injecting_rule_kind=[cc_proto_library]}' (requested by nodes 'CONFIGURED_TARGET://:my_cc_proto e0f402e95abd03057d52ad714d5ada1b (242415415 1426511063)')
INFO: Elapsed time: 30.520s
FAILED: Build did NOT complete successfully (10 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ASPECT:[]#BazelCcProtoAspect e0f402e95abd03057d52ad714d5ada1b e0f402e95abd03057d52ad714d5ada1b {$injecting_rule_kind=[cc_proto_library]}' (requested by nodes 'CONFIGURED_TARGET://:my_cc_proto e0f402e95abd03057d52ad714d5ada1b (242415415 1426511063)')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: C:/tools/msys64/home/pcloudy/workspace/my_tests/cc_proto_library_test/BUILD:6:1: BazelCcProtoAspect[$injecting_rule_kind="cc_proto_library"] aspect on proto_library attribute win_def_file is not defined
        at com.google.devtools.build.lib.analysis.RuleContext.checkAttribute(RuleContext.java:1005)
        at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:785)
        at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteArtifact(RuleContext.java:1088)
        at com.google.devtools.build.lib.rules.cpp.CppModel.createCcLinkActions(CppModel.java:1470)
        at com.google.devtools.build.lib.rules.cpp.CcLibraryHelper.build(CcLibraryHelper.java:977)
        at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect$Impl.<init>(CcProtoAspect.java:190)
        at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect.create(CcProtoAspect.java:96)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:444)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:476)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:323)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
```

Culprit: 9cc954a8c1e1f5134c4b6701588cd226e9e52707

`win_def_file` attribute was not defined for proto_library while evaluating aspect..
@dslomov Do you have any quick idea about why this is happening?

The change for adding win_def_file is not included by 0.8.0, so the next release is not affected by this issue.

**Comment by meteorcloudy** [comment]
Found the cause, working on a fix now
