### ISSUE TITLE
"bazel mobile-install" raises an exception

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#413]
After setting up a WORKSPACE file appropriately:

```
bazel mobile-install //examples/android/java/bazel:hello_world
```

Results in
````
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Generating incremental installation manifest for //examples/android/java/bazel:hello_world' (AndroidDexManifest[[Artifact:[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/7702f1490eb02e4ab2d12bed1e7ae514[source]]external/android_tools/tools/android/build_incremental_dexmanifest.py, Artifact:[[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/7702f1490eb02e4ab2d12bed1e7ae514/android]bazel-out/host/bin]external/android_tools/tools/android/build_incremental_dexmanifest, Artifact:[[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/7702f1490eb02e4ab2d12bed1e7ae514/android]bazel-out/host/internal]_middlemen/external_Sandroid_Utools_Stools_Sandroid_Sbuild_Uincremental_Udexmanifest-runfiles, Artifact:[[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/7702f1490eb02e4ab2d12bed1e7ae514/android]bazel-out/local_linux-fastbuild/bin]examples/android/java/bazel/_dx/hello_world/classes.dex] -> [Artifact:[[/usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/7702f1490eb02e4ab2d12bed1e7ae514/android]bazel-out/local_linux-fastbuild/bin]examples/android/java/bazel/hello_world_files/dexmanifest.txt]])' (requested by nodes 'ARTIFACT:examples/android/java/bazel/hello_world_files/dexmanifest.txt //examples/android/java/bazel:hello_world 0891c086e5b84e080b3df6a2813d5efe')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:762)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: 'external/__init__.py ' does not split into exactly 2 parts
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.mountRunfilesFromManifests(LinuxSandboxedStrategy.java:294)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.getMounts(LinuxSandboxedStrategy.java:194)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:119)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:225)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:769)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:708)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:98)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:609)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:569)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:365)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:726)
	... 4 more
````

**Comment by philwo** [comment]
Hehe, I was waiting for this moment to come. :| We indeed have to replace the way too simple parser of the manifest files with the more complex one...

Will have a look today.

**Comment by ulfjack** [comment]
The parsing isn't actually much more complicated, but you need to create empty files if the right-hand side is unset.

**Comment by philwo** [comment]
A fix for this issue will be part of the next push. :)
