### ISSUE TITLE
Dagger @BindsInstance annotation processing not working with arrays when building with Bazel

### ISSUE THREAD

**Issue by jianglai** [bazelbuild/bazel#4138]
### Description of the problem / feature request / question:
When I use Bazel to build a Java application with Dagger's [@BindsInstance](https://google.github.io/dagger/api/2.13/dagger/BindsInstance.html) annotatoins in it, the annotation processor throws an error if the annotated method's argument is an array (byte[] for example). This does not happen when building the same code with Maven, so I presume this is a Bazel issue.

### If possible, provide a minimal example to reproduce the problem:
An example an be found [here](https://github.com/jianglai/bazel-dagger-issue).
Note that I am using [java_import_external](https://github.com/bazelbuild/rules_closure/blob/master/closure/private/java_import_external.bzl) from closure to import maven artifacts.

```
master jianglai@jianglai:~/bazel-dagger-issue$ bazel build test:all 
INFO: Analysed 2 targets (15 packages loaded).
INFO: Found 2 targets...
ERROR: /usr/local/google/home/jianglai/bazel-dagger-issue/test/BUILD:1:1: Building test/libtest.jar (1 source file) and running annotation processors (ComponentProcessor) failed (Exit 1)
java.lang.RuntimeException: java.lang.IllegalArgumentException: byte[] cannot be converted to an Element
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:105)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:106)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:53)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:109)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:117)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.lang.IllegalArgumentException: byte[] cannot be converted to an Element
	at dagger.shaded.auto.common.MoreTypes$AsElementVisitor.defaultAction(MoreTypes.java:532)
	at dagger.shaded.auto.common.MoreTypes$AsElementVisitor.defaultAction(MoreTypes.java:527)
	at javax.lang.model.util.SimpleTypeVisitor6.visitArray(SimpleTypeVisitor6.java:158)
	at com.sun.tools.javac.code.Type$ArrayType.accept(Type.java:1409)
	at dagger.shaded.auto.common.MoreTypes.asElement(MoreTypes.java:524)
	at dagger.shaded.auto.common.MoreTypes.asTypeElement(MoreTypes.java:553)
	at dagger.internal.codegen.ComponentRequirement.typeElement(ComponentRequirement.java:62)
	at dagger.internal.codegen.ComponentWriter.lambda$canInstantiateAllRequirements$0(ComponentWriter.java:194)
	at com.google.common.collect.Iterators.indexOf(Iterators.java:799)
	at com.google.common.collect.Iterators.any(Iterators.java:688)
	at com.google.common.collect.Iterables.any(Iterables.java:627)
	at dagger.internal.codegen.ComponentWriter.canInstantiateAllRequirements(ComponentWriter.java:192)
	at dagger.internal.codegen.ComponentWriter.addFactoryMethods(ComponentWriter.java:176)
	at dagger.internal.codegen.AbstractComponentWriter.write(AbstractComponentWriter.java:314)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:71)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:35)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:72)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:63)
	at dagger.internal.codegen.ComponentProcessingStep.generateComponent(ComponentProcessingStep.java:154)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:142)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:47)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1204)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1313)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1267)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:943)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	... 10 more
INFO: Elapsed time: 1.534s, Critical Path: 0.25s
FAILED: Build did NOT complete successfully
```

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
release 0.7.0

**Comment by meteorcloudy** [comment]
@cushon Is this caused by some missing java arguments?

**Comment by cushon** [comment]
There was an internal thread about this, and @ronshapiro was investigating.

**Comment by jianglai** [comment]
Yes, I was hoping that maybe some external user/contributor may have seen this issue before.

**Comment by meisterT** [comment]
Closing for lack of activity.
