### ISSUE TITLE
External repository crash

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#4170]
`Build label: 0.8.0rc5`

Repro case: ~~https://github.com/dslomov/workspace_runfiles/commit/fc2e39aa5a194e4cba68c7b4838215b49799b176~~
https://github.com/dslomov/workspace_runfiles/commit/20985c4b23cb4bd4e1b10ee70c30ef417aa0fcd7
```
$ bazel build //src:r_other
WARNING: /usr/local/google/home/dslomov/.cache/bazel/_bazel_dslomov/33196524570d6a6bed1b0f9825078763/external/other_repo/WORKSPACE:1: Workspace name in /usr/local/google/home/dslomov/.cache/bazel/_bazel_dslomov/33196524570d6a6bed1b0f9825078763/external/other_repo/WORKSPACE (@google_dslomov_repo) does not match the name given in the repository's definition (@other_repo); this will cause a build error in future versions
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://src:r_other 31acfcd5805ac0c89a786e97c6a0e803 (109181686 1971063285)' (requested by nodes )
INFO: Elapsed time: 1.047s
FAILED: Build did NOT complete successfully (13 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://src:r_other 31acfcd5805ac0c89a786e97c6a0e803 (109181686 1971063285)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Output artifact 'external/other_repo/repo_tools/tryme.runfiles_manifest' not under package directory 'src' for target '//src:r_other'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:836)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
	at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:623)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.createRunfilesInputManifestArtifact(RunfilesSupport.java:184)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.<init>(RunfilesSupport.java:124)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.withExecutable(RunfilesSupport.java:399)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addSimpleProviders(SkylarkRuleConfiguredTargetUtil.java:491)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.parseDefaultProviderKeys(SkylarkRuleConfiguredTargetUtil.java:428)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addProviders(SkylarkRuleConfiguredTargetUtil.java:320)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:166)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:111)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://src:r_other 31acfcd5805ac0c89a786e97c6a0e803 (109181686 1971063285)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Output artifact 'external/other_repo/repo_tools/tryme.runfiles_manifest' not under package directory 'src' for target '//src:r_other'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:836)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:255)
	at com.google.devtools.build.lib.analysis.RuleContext.getDerivedArtifact(RuleContext.java:623)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.createRunfilesInputManifestArtifact(RunfilesSupport.java:184)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.<init>(RunfilesSupport.java:124)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.withExecutable(RunfilesSupport.java:399)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addSimpleProviders(SkylarkRuleConfiguredTargetUtil.java:491)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.parseDefaultProviderKeys(SkylarkRuleConfiguredTargetUtil.java:428)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addProviders(SkylarkRuleConfiguredTargetUtil.java:320)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:166)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:111)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	... 4 more
```

**Comment by dslomov** [comment]
Update: the correct commit is https://github.com/dslomov/workspace_runfiles/commit/20985c4b23cb4bd4e1b10ee70c30ef417aa0fcd7

**Comment by dslomov** [comment]
Not really an external repo bug. It happens when an executable rule tries to provide the executable from a different package (and it is actually enabled by a  https://github.com/bazelbuild/bazel/issues/3826, where we enabled arbitrary artifacts as executables). The small(er) repro is:

src/rulez.bzl
```python
def _impl(ctx):
  f = ctx.actions.declare_file(ctx.label.name + ".output")
  return [DefaultInfo(executable = ctx.executable.runme,
                      files = depset([f, ctx.executable.runme]),
                     )]


r = rule(_impl,
         executable = True,
         attrs = {
             "runme" : attr.label(executable = True, mandatory = True, cfg = "host"),
             "data" : attr.label_list(allow_files = True)
         },
)
```
tools/BUILD:
```python
sh_binary(name = "tryme",
          srcs = [":tryme.sh"],
          data = ["//data:data.txt", "@other_repo//repo_data:repo_data.txt"],
          visibility = ["//visibility:public"],
)
```
src/BUILD
```python
load("//:rulez.bzl", "r")
r(name = "r_tools", runme = "//tools:tryme")
```

**Comment by dslomov** [comment]
Suggested solution: only allow the executables created in the same rule.
