### ISSUE TITLE
CI, bazel-nightly: bazel-tests are failing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4240]
**This issue is blocking https://github.com/bazelbuild/bazel/issues/3773**.

This bug is branched off https://github.com/bazelbuild/bazel/issues/4233#issuecomment-349679790 .

See https://ci.bazel.io/job/Global/job/bazel-tests/383/consoleFull
The test ran with a Bazel binary built at ddd5ac1.

I tested https://github.com/bazelbuild/bazel/commit/2cf560f83922e6df9626ba3ee063c1caf6797548 locally. It fixes the `load()`-related errors on Windows in https://ci.bazel.io/job/Global/job/bazel-tests/383/consoleFull, but `//src/test/py/bazel:bazel_windows_cpp_test` and `//src/test/py/bazel:bazel_windows_test` are still failing.

**Comment by laszlocsomor** [comment]
I get the same errors with Bazel 0.8.1 on my Windows box. So we know this is not a regression, therefore not a release blocker.

**Comment by laszlocsomor** [comment]
Test log sample:
```
======================================================================
FAIL: testBuildCcBinaryFromDifferentPackage (__main__.BazelWindowsCppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\laszlocsomor\appdata\local\temp\_bazel_laszlocsomor\o6hbs7n0\execroot\io_bazel\tmp24e_5100ab07950c294e\Bazel.runfiles_qokz9r\runfiles\io_bazel\src\test\py\bazel\bazel_windows_cpp_test.py", line 221, in testBuildCcBinaryFromDifferentPackage
    self.AssertExitCode(exit_code, 0, stderr)
  File "c:\users\laszlocsomor\appdata\local\temp\_bazel_laszlocsomor\o6hbs7n0\execroot\io_bazel\tmp24e_5100ab07950c294e\Bazel.runfiles_qokz9r\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 68, in AssertExitCode
    '(end stderr)------------------------------------------',
AssertionError: Bazel exited with 1 (expected 0), stderr:
(start stderr)----------------------------------------
Loading:
Loading: 0 packages loaded
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: registry query result for VC 15.0:

STDOUT(start)



STDOUT(end)
STDERR(start):
ERROR: The system was unable to find the specified registry key or value.

STDERR(end)

DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: registry query result for VC 14.0:

STDOUT(start)



STDOUT(end)
STDERR(start):
ERROR: The system was unable to find the specified registry key or value.

STDERR(end)

DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: registry query result for VC 12.0:

STDOUT(start)

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7
12.0    REG_SZ    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\


STDOUT(end)
STDERR(start):

STDERR(end)

DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/_bazel_laszlocsomor/y84agkcd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\
INFO: Analysed target //main:main (5 packages loaded).
INFO: Found 1 target...
Building: no action
[0 / 16] no action
ERROR: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/_tmp/383a9a577acd27d76846cda13f6e6573/tests_root/tmpnw3msq/BUILD:6:1: Linking of rule '//:A' failed (Exit 1117)
Target //main:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.613s, Critical Path: 0.76s
FAILED: Build did NOT complete successfully
INFO: $TEST_TMPDIR defined: output root default is 'c:\users\laszlocsomor\appdata\local\temp\_bazel_laszlocsomor\o6hbs7n0\execroot\io_bazel\_tmp\383a9a577acd27d76846cda13f6e6573' and max_idle_secs default is '15'.
(end stderr)------------------------------------------
```

**Comment by meteorcloudy** [comment]
@laszlocsomor I don't see the Windows breakage on CI from both https://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/383/pipeline and the latest run https://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/397/pipeline

//src/test/py/bazel:bazel_windows_cpp_test and //src/test/py/bazel:bazel_windows_test are not failing with 0.8.1 on my machine.

Can you tell me how to reproduce this?

**Comment by laszlocsomor** [comment]
I found these in bazel-nightly, i.e. those tests ran using the 0.9.0rc2 binary, at the baseline of the rc (https://github.com/bazelbuild/bazel/commit/ddd5ac16aeffa6c4693c348f73e7365240b1abc5).

**Comment by meteorcloudy** [comment]
Hmm,, I reset my bazel source tree to ddd5ac1, then used 0.9.0rc2 to build and test 
`//src/test/py/bazel:bazel_windows_cpp_test` and `//src/test/py/bazel:bazel_windows_test`
Still got a pass result.
Do you still have the link to the bazel-nightly job where this is failing?

**Comment by laszlocsomor** [comment]
Huh, now that you ask for it, these tests weren't broken on CI!
But in fact they are broken on my machine. I suspect it has something to do with my VC installation.
Shall we debug in person?

**Comment by laszlocsomor** [comment]
We found the culprit: I have VC 12.0 installed (along with Build Tools 2017) and somehow cc_configure.bzl picks up 12.0. The `link.exe` in that version doesn't yet support `/DEBUG:fastlink` which later versions do support, and our crosstool configuration relies on that flag. The tests were failing because of this.
