### ISSUE TITLE
CI, bazel-slow-tests: failing on Darwin due to `git fetch` failure

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4270]
https://ci.bazel.io/view/Dashboard/job/bazel-slow-tests/421/consoleFull

```
[node=darwin-x86_64]  > git rev-parse --is-inside-work-tree # timeout=10
[node=darwin-x86_64] Fetching changes from the remote Git repository
[node=darwin-x86_64]  > git config remote.origin.url https://github.com/bazelbuild/bazel # timeout=10
[node=darwin-x86_64] Cleaning workspace
[node=darwin-x86_64]  > git rev-parse --verify HEAD # timeout=10
[node=darwin-x86_64] Resetting working tree
[node=darwin-x86_64]  > git reset --hard # timeout=10
[node=darwin-x86_64] ERROR: Error fetching remote repo 'origin'
[node=darwin-x86_64] hudson.plugins.git.GitException: Failed to fetch from https://github.com/bazelbuild/bazel
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
[node=darwin-x86_64] 	at hudson.security.ACL.impersonate(ACL.java:260)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
[node=darwin-x86_64] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[node=darwin-x86_64] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[node=darwin-x86_64] Caused by: hudson.plugins.git.GitException: Command "git reset --hard" returned status code 128:
[node=darwin-x86_64] stdout: 
[node=darwin-x86_64] stderr: error: bad signature
[node=darwin-x86_64] fatal: index file corrupt
[node=darwin-x86_64] 
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1892)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1888)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1533)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.reset(CliGitAPIImpl.java:410)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.clean(CliGitAPIImpl.java:731)
[node=darwin-x86_64] 	at hudson.plugins.git.GitAPI.clean(GitAPI.java:311)
[node=darwin-x86_64] 	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
[node=darwin-x86_64] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[node=darwin-x86_64] 	at java.lang.reflect.Method.invoke(Method.java:498)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:896)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:870)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:829)
[node=darwin-x86_64] 	at hudson.remoting.UserRequest.perform(UserRequest.java:208)
[node=darwin-x86_64] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[node=darwin-x86_64] 	at hudson.remoting.Request$2.run(Request.java:360)
[node=darwin-x86_64] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
[node=darwin-x86_64] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[node=darwin-x86_64] 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
[node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[node=darwin-x86_64] 	at ......remote call to JNLP4-connect connection from 104.132.61.102/104.132.61.102:60296(Native Method)
[node=darwin-x86_64] 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1654)
[node=darwin-x86_64] 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:311)
[node=darwin-x86_64] 	at hudson.remoting.Channel.call(Channel.java:905)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
[node=darwin-x86_64] 	at com.sun.proxy.$Proxy77.clean(Unknown Source)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.clean(RemoteGitImpl.java:450)
[node=darwin-x86_64] 	at hudson.plugins.git.extensions.impl.CleanBeforeCheckout.decorateFetchCommand(CleanBeforeCheckout.java:30)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:813)
[node=darwin-x86_64] 	... 13 more
```

**Comment by laszlocsomor** [comment]
manually running the `git reset --hard` command on the machine succeeds

**Comment by laszlocsomor** [comment]
Same error on bazel-tests:

https://ci.bazel.io/view/Dashboard/job/bazel-tests/1448/consoleFull

```
[node=darwin-x86_64]  > git rev-parse --is-inside-work-tree # timeout=10
[node=darwin-x86_64] Fetching changes from the remote Git repository
[node=darwin-x86_64]  > git config remote.origin.url https://github.com/bazelbuild/bazel # timeout=10
[node=darwin-x86_64] Cleaning workspace
[node=darwin-x86_64]  > git rev-parse --verify HEAD # timeout=10
[node=darwin-x86_64] Resetting working tree
[node=darwin-x86_64]  > git reset --hard # timeout=10
[node=darwin-x86_64] ERROR: Error fetching remote repo 'origin'
[node=darwin-x86_64] hudson.plugins.git.GitException: Failed to fetch from https://github.com/bazelbuild/bazel
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
[node=darwin-x86_64] 	at hudson.security.ACL.impersonate(ACL.java:260)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
[node=darwin-x86_64] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[node=darwin-x86_64] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[node=darwin-x86_64] Caused by: hudson.plugins.git.GitException: Command "git reset --hard" returned status code 128:
[node=darwin-x86_64] stdout: 
[node=darwin-x86_64] stderr: fatal: index file smaller than expected
[node=darwin-x86_64] 
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1892)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1888)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1533)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.reset(CliGitAPIImpl.java:410)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.clean(CliGitAPIImpl.java:731)
[node=darwin-x86_64] 	at hudson.plugins.git.GitAPI.clean(GitAPI.java:311)
[node=darwin-x86_64] 	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
[node=darwin-x86_64] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[node=darwin-x86_64] 	at java.lang.reflect.Method.invoke(Method.java:498)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:896)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:870)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:829)
[node=darwin-x86_64] 	at hudson.remoting.UserRequest.perform(UserRequest.java:208)
[node=darwin-x86_64] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[node=darwin-x86_64] 	at hudson.remoting.Request$2.run(Request.java:360)
[node=darwin-x86_64] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
[node=darwin-x86_64] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[node=darwin-x86_64] 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
[node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[node=darwin-x86_64] 	at ......remote call to JNLP4-connect connection from 104.132.61.100/104.132.61.100:41690(Native Method)
[node=darwin-x86_64] 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1654)
[node=darwin-x86_64] 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:311)
[node=darwin-x86_64] 	at hudson.remoting.Channel.call(Channel.java:905)
[node=darwin-x86_64] 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
[node=darwin-x86_64] 	at com.sun.proxy.$Proxy77.clean(Unknown Source)
[node=darwin-x86_64] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.clean(RemoteGitImpl.java:450)
[node=darwin-x86_64] 	at hudson.plugins.git.extensions.impl.CleanBeforeCheckout.decorateFetchCommand(CleanBeforeCheckout.java:30)
[node=darwin-x86_64] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:813)
[node=darwin-x86_64] 	... 13 more
```

**Comment by laszlocsomor** [comment]
StackOverflow says this is due to a corrupt git index file. I'll try the recommended solution.
https://stackoverflow.com/questions/10076036/index-file-smaller-than-expected

**Comment by laszlocsomor** [comment]
Same problem with `gerrit` project; trying the same remedy.
https://ci.bazel.io/view/Dashboard/job/gerrit/1955/consoleFull

**Comment by damienmg** [comment]
This is only happening on Darwin? What about removing all workpsaces from
all Darwin slaves? Radical but likely to remove all problem once and for
all...

**Comment by laszlocsomor** [comment]
Sure, why not. Shall I just delete (rename) the workspace directories?

**Comment by damienmg** [comment]
This is what I would do yes. Just make sure the machine isn't running a
build :)

**Comment by laszlocsomor** [comment]
Done: renamed `/Users/ci/workspace` directory on `darwin-x86_64-3` and `darwin-x86_64-4`.

**Comment by mhlopko** [comment]
I guess it helped (since I don't see such failures on the ci anymore). Can I close this issue now?

**Comment by laszlocsomor** [comment]
Sure. Thanks for checking!
