### ISSUE TITLE
CI, bazel-tests: numerous tests failing on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4288]
https://ci.bazel.io/view/Dashboard/job/bazel-tests/1463/consoleFull

```
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/shell/bazel:bazel_windows_example_test (see C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/shell/bazel/bazel_windows_example_test/test.log)
[node=windows-x86_64,toolchain=msvc] INFO: From Testing //src/test/shell/bazel:bazel_windows_example_test:
[node=windows-x86_64,toolchain=msvc] ==================== Test output for //src/test/shell/bazel:bazel_windows_example_test:
[node=windows-x86_64,toolchain=msvc] INFO[bazel_windows_example_test 05:00:47.125701200 (+0000)] bazel binary is at /c/jenkins/workspace/bazel-tests-node=windows-x86_64,toolchain=msvc/src/test/shell/bin
[node=windows-x86_64,toolchain=msvc] INFO[bazel_windows_example_test 05:00:47.179719200 (+0000)] setting up client in c:/temp/2713b7a92d8298dcf32c3b44de75c8b1/workspace
[node=windows-x86_64,toolchain=msvc] ERROR[bazel_windows_example_test 05:01:09.145552900 (+0000)] 'bazel info bazel-genfiles' failed, stderr: ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/temp/2713b7a92d8298dcf32c3b44de75c8b1/root/se7ga_9z/external/local_config_cc/CROSSTOOL', because of a parser error (157:1: Expected identifier. Found '%')
[node=windows-x86_64,toolchain=msvc] INFO: $TEST_TMPDIR defined: output root default is 'c:\temp\2713b7a92d8298dcf32c3b44de75c8b1' and max_idle_secs default is '15'.
[node=windows-x86_64,toolchain=msvc] ================================================================================
[node=windows-x86_64,toolchain=msvc] [2,597 / 2,741] 48 / 115 tests, 1 failed; Testing //src/test/py/bazel:cc_import_test; 23s local ... (16 actions running)
[node=darwin-x86_64] [4,190 / 4,209] 113 / 307 tests; Testing //scripts/release:release_test (shard 2 of 2); 61s darwin-sandbox ... (8 actions running)
[node=linux-x86_64] [3,395 / 3,410] 89 / 307 tests; Executing genrule //scripts:bash_completion; 5s linux-sandbox ... (10 actions running)
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/py/bazel:runfiles_test (see C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/py/bazel/runfiles_test/test.log)
[node=windows-x86_64,toolchain=msvc] INFO: From Testing //src/test/py/bazel:runfiles_test:
[node=windows-x86_64,toolchain=msvc] ==================== Test output for //src/test/py/bazel:runfiles_test:
[node=windows-x86_64,toolchain=msvc] F
[node=windows-x86_64,toolchain=msvc] ======================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: testAttemptToBuildRunfilesOnWindows (__main__.RunfilesTest)
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Traceback (most recent call last):
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5c1_58b3f667c38acab7\Bazel.runfiles_snr42n\runfiles\io_bazel\src\test\py\bazel\runfiles_test.py", line 30, in testAttemptToBuildRunfilesOnWindows
[node=windows-x86_64,toolchain=msvc]     "\n".join(stderr))
[node=windows-x86_64,toolchain=msvc] AssertionError: 'building runfiles is not supported on Windows' not found in u"INFO: $TEST_TMPDIR defined: output root default is 'c:\\windows\\temp\\_bazel_system\\7bqgevoe\\execroot\\io_bazel\\_tmp\\c3b0bbd16b12dcab62c45e413ccc8e32' and max_idle_secs default is '15'.\nExtracting Bazel installation...\n......................................................................\nLoading:\nLoading: 0 packages loaded\nAnalyzing: 0 targets (0 packages loaded)\nAnalyzing: 0 targets (2 packages loaded)\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.\nAnalyzing: 0 targets (3 packages loaded)\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: Looking for Visual C++ through registry\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: registry query result for VC 15.0:\n\nSTDOUT(start)\n\n\n\nSTDOUT(end)\nSTDERR(start):\nERROR: The system was unable to find the specified registry key or value.\n\nSTDERR(end)\n\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: registry query result for VC 14.0:\n\nSTDOUT(start)\n\nHKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\SxS\\VC7\n14.0    REG_SZ    C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\\n\n\nSTDOUT(end)\nSTDERR(start):\n\nSTDERR(end)\n\nDEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:\nAuto-Configuration Warning: Visual C++ build tools found at C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\\nERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/_bazel_system/wo-ieugv/external/local_config_cc/CROSSTOOL', because of a parser error (157:1: Expected identifier. Found '%')\nINFO: Elapsed time: 22.340s\nFAILED: Build did NOT complete successfully (4 packages loaded)"
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Ran 1 test in 22.409s
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] FAILED (failures=1)
[node=windows-x86_64,toolchain=msvc] ================================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/py/bazel:bazel_clean_test (see C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/py/bazel/bazel_clean_test/test.log)
[node=windows-x86_64,toolchain=msvc] INFO: From Testing //src/test/py/bazel:bazel_clean_test:
[node=windows-x86_64,toolchain=msvc] ==================== Test output for //src/test/py/bazel:bazel_clean_test:
[node=windows-x86_64,toolchain=msvc] F
[node=windows-x86_64,toolchain=msvc] ======================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: testBazelClean (__main__.BazelCleanTest)
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Traceback (most recent call last):
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5bb_6b640ff68471d246\Bazel.runfiles_nfp9ks\runfiles\io_bazel\src\test\py\bazel\bazel_clean_test.py", line 33, in testBazelClean
[node=windows-x86_64,toolchain=msvc]     self.AssertExitCode(exit_code, 0, stderr)
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5bb_6b640ff68471d246\Bazel.runfiles_nfp9ks\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 68, in AssertExitCode
[node=windows-x86_64,toolchain=msvc]     '(end stderr)------------------------------------------',
[node=windows-x86_64,toolchain=msvc] AssertionError: Bazel exited with 2 (expected 0), stderr:
[node=windows-x86_64,toolchain=msvc] (start stderr)----------------------------------------
[node=windows-x86_64,toolchain=msvc] INFO: $TEST_TMPDIR defined: output root default is 'c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\_tmp\8a0a6eaca3beedecec9a7a670beca254' and max_idle_secs default is '15'.
[node=windows-x86_64,toolchain=msvc] Extracting Bazel installation...
[node=windows-x86_64,toolchain=msvc] ..........................................................................
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for Visual C++ through registry
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 15.0:
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(start)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(end)
[node=windows-x86_64,toolchain=msvc] STDERR(start):
[node=windows-x86_64,toolchain=msvc] ERROR: The system was unable to find the specified registry key or value.
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDERR(end)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 14.0:
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(start)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7
[node=windows-x86_64,toolchain=msvc] 14.0    REG_SZ    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(end)
[node=windows-x86_64,toolchain=msvc] STDERR(start):
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDERR(end)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
[node=windows-x86_64,toolchain=msvc] ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_system/wy6w-2fx/external/local_config_cc/CROSSTOOL', because of a parser error (157:1: Expected identifier. Found '%')
[node=windows-x86_64,toolchain=msvc] (end stderr)------------------------------------------
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Ran 1 test in 21.921s
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] FAILED (failures=1)
[node=windows-x86_64,toolchain=msvc] ================================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/py/bazel:action_temp_test (see C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/py/bazel/action_temp_test/test.log)
[node=windows-x86_64,toolchain=msvc] INFO: From Testing //src/test/py/bazel:action_temp_test:
[node=windows-x86_64,toolchain=msvc] ==================== Test output for //src/test/py/bazel:action_temp_test:
[node=windows-x86_64,toolchain=msvc] F
[node=windows-x86_64,toolchain=msvc] ======================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: testStandaloneBuildAction (__main__.ActionTempTest)
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Traceback (most recent call last):
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5be_8d1c15a76c02eb49\Bazel.runfiles_njo4ad\runfiles\io_bazel\src\test\py\bazel\action_temp_test.py", line 25, in testStandaloneBuildAction
[node=windows-x86_64,toolchain=msvc]     self.AssertTempEnvvarWithSpawnStrategy('standalone')
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5be_8d1c15a76c02eb49\Bazel.runfiles_njo4ad\runfiles\io_bazel\src\test\py\bazel\action_temp_test.py", line 41, in AssertTempEnvvarWithSpawnStrategy
[node=windows-x86_64,toolchain=msvc]     outputs = self._BuildRules(strategy)
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5be_8d1c15a76c02eb49\Bazel.runfiles_njo4ad\runfiles\io_bazel\src\test\py\bazel\action_temp_test.py", line 140, in _BuildRules
[node=windows-x86_64,toolchain=msvc]     self.AssertExitCode(exit_code, 0, stderr)
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5be_8d1c15a76c02eb49\Bazel.runfiles_njo4ad\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 68, in AssertExitCode
[node=windows-x86_64,toolchain=msvc]     '(end stderr)------------------------------------------',
[node=windows-x86_64,toolchain=msvc] AssertionError: Bazel exited with 2 (expected 0), stderr:
[node=windows-x86_64,toolchain=msvc] (start stderr)----------------------------------------
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for Visual C++ through registry
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 15.0:
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(start)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(end)
[node=windows-x86_64,toolchain=msvc] STDERR(start):
[node=windows-x86_64,toolchain=msvc] ERROR: The system was unable to find the specified registry key or value.
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDERR(end)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 14.0:
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(start)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7
[node=windows-x86_64,toolchain=msvc] 14.0    REG_SZ    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDOUT(end)
[node=windows-x86_64,toolchain=msvc] STDERR(start):
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] STDERR(end)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
[node=windows-x86_64,toolchain=msvc] ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/5ce268703a95bf68b92c2f4140bcbaf6/_bazel_system/_5gbhntl/external/local_config_cc/CROSSTOOL', because of a parser error (157:1: Expected identifier. Found '%')
[node=windows-x86_64,toolchain=msvc] INFO: $TEST_TMPDIR defined: output root default is 'c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\_tmp\5ce268703a95bf68b92c2f4140bcbaf6' and max_idle_secs default is '15'.
[node=windows-x86_64,toolchain=msvc] (end stderr)------------------------------------------
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Ran 1 test in 23.307s
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] FAILED (failures=1)
[node=windows-x86_64,toolchain=msvc] ================================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/py/bazel:bazel_external_repository_test (see C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/py/bazel/bazel_external_repository_test/test.log)
[node=windows-x86_64,toolchain=msvc] INFO: From Testing //src/test/py/bazel:bazel_external_repository_test:
[node=windows-x86_64,toolchain=msvc] ==================== Test output for //src/test/py/bazel:bazel_external_repository_test:
[node=windows-x86_64,toolchain=msvc] F
[node=windows-x86_64,toolchain=msvc] ======================================================================
[node=windows-x86_64,toolchain=msvc] FAIL: testNewHttpArchive (__main__.BazelExternalRepositoryTest)
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Traceback (most recent call last):
[node=windows-x86_64,toolchain=msvc]   File "c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\tmp5c7_1927ba7739715c6e\Bazel.runfiles_qbtqxb\runfiles\io_bazel\src\test\py\bazel\bazel_external_repository_test.py", line 51, in testNewHttpArchive
[node=windows-x86_64,toolchain=msvc]     self.assertEqual(exit_code, 0, os.linesep.join(stderr))
[node=windows-x86_64,toolchain=msvc] AssertionError: INFO: $TEST_TMPDIR defined: output root default is 'c:\windows\temp\_bazel_system\7bqgevoe\execroot\io_bazel\_tmp\e1a14b16f7259e8a0510ee379b9c98e6' and max_idle_secs default is '15'.

[node=windows-x86_64,toolchain=msvc] Extracting Bazel installation...

[node=windows-x86_64,toolchain=msvc] ..........................................................................

[node=windows-x86_64,toolchain=msvc] Loading:

[node=windows-x86_64,toolchain=msvc] Loading: 0 packages loaded

[node=windows-x86_64,toolchain=msvc] Loading: 0 packages loaded

[node=windows-x86_64,toolchain=msvc] Analyzing: target @six_archive//:six (3 packages loaded)

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for Visual C++ through registry

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 15.0:

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDOUT(start)

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDOUT(end)

[node=windows-x86_64,toolchain=msvc] STDERR(start):

[node=windows-x86_64,toolchain=msvc] ERROR: The system was unable to find the specified registry key or value.

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDERR(end)

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: registry query result for VC 14.0:

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDOUT(start)

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7

[node=windows-x86_64,toolchain=msvc] 14.0    REG_SZ    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDOUT(end)

[node=windows-x86_64,toolchain=msvc] STDERR(start):

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] STDERR(end)

[node=windows-x86_64,toolchain=msvc] 

[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:

[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

[node=windows-x86_64,toolchain=msvc] Analyzing: target @six_archive//:six (4 packages loaded)

[node=windows-x86_64,toolchain=msvc] ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/windows/temp/_bazel_system/7bqgevoe/execroot/io_bazel/_tmp/e1a14b16f7259e8a0510ee379b9c98e6/_bazel_system/oorkg0cp/external/local_config_cc/CROSSTOOL', because of a parser error (157:1: Expected identifier. Found '%')

[node=windows-x86_64,toolchain=msvc] INFO: Elapsed time: 20.892s

[node=windows-x86_64,toolchain=msvc] FAILED: Build did NOT complete successfully (5 packages loaded)
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] ----------------------------------------------------------------------
[node=windows-x86_64,toolchain=msvc] Ran 1 test in 22.285s
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] FAILED (failures=1)
[node=windows-x86_64,toolchain=msvc] ================================================================================
```

**Comment by laszlocsomor** [comment]
Culprit: https://github.com/bazelbuild/bazel/commit/2aeaeba66857c561dd6d63c79a213f1cabc3650d

/cc @mhlopko
