### ISSUE TITLE
Windows, testing: make all tests work on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4292]
As of today, there are 282 tests that Bazel doesn't run on Windows:

```
C:\work\bazel>bazel --output_user_root=c:\tmp2 query "tests(//...)-tests(//src:all_windows_tests)"

```

We need to make them all run on Windows and turn them on on CI, in order to have full test coverage on Windows.

**Comment by laszlocsomor** [comment]
I'm tempted to make this bug P1.
Since we're about to plan the work for next 3 months, I'm marking this bug P1 and P2 at the same time.

**Comment by davido** [comment]
I'm, the most concerned about disabled buildjar tests:

```
//src/java_tools/buildjar/javatests/com/google/devtools/build/java/turbine/javac:TreePrunerTest
//src/java_tools/buildjar/javatests/com/google/devtools/build/java/turbine/javac:ProcessorClasspathTest_bootclasspath
//src/java_tools/buildjar/javatests/com/google/devtools/build/java/turbine/javac:JavacTurbineTest
//src/java_tools/buildjar/javatests/com/google/devtools/build/java/bazel:BazelJavaCompilerTest
//src/java_tools/buildjar/javatests/com/google/devtools/build/buildjar:VanillaJavaBuilderTest
```

TBH with you: I stopped working on gerrit build on Windows, untill these tests are up and running. I was not amused to find out, that transitive classpath calculation in `buildjar` was inherently broken on Windows, and that the existing test, that would probably catch this was disabled (and still broken) on Windows.

**Comment by davido** [comment]
Strictly speaking, removing the warning from Bazel FAQ, that Windows support is bleeding edge, experimental and may produce unexpected results, was a mistake and [this CL should be reverted](https://github.com/bazelbuild/bazel-website/commit/1b04ae399150eec5996391dd6d5ccc11388c8e4e). Nothing document this better as this issue.

**Comment by laszlocsomor** [comment]
David, I'm not sure what reaction you expect.

**Comment by pcj** [comment]
I'm seeing a problem that would likely be addressed by fixing these two tests:

```
//src/java_tools/singlejar/javatests/com/google/devtools/build/zip:ZipTests
//src/java_tools/singlejar/javatests/com/google/devtools/build/singlejar:SingleJarTests
```

```
ERROR: C:/src/jenova/test/baseline/BUILD.bazel:9:1: Building deploy jar test/baseline/ATE-369_xlsx_deploy.jar failed (Exit 1)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 79
        at com.google.devtools.build.zip.ZipUtil.get16(ZipUtil.java:87)
        at com.google.devtools.build.zip.ZipUtil.getUnsignedShort(ZipUtil.java:119)
        at com.google.devtools.build.zip.ZipReader.findEndOfCentralDirectoryRecord(ZipReader.java:277)
        at com.google.devtools.build.zip.ZipReader.readCentralDirectory(ZipReader.java:194)
        at com.google.devtools.build.zip.ZipReader.<init>(ZipReader.java:94)
        at com.google.devtools.build.zip.ZipReader.<init>(ZipReader.java:74)
        at com.google.devtools.build.zip.ZipReader.<init>(ZipReader.java:62)
        at com.google.devtools.build.singlejar.ZipCombiner.addZip(ZipCombiner.java:431)
        at com.google.devtools.build.singlejar.SingleJar.run(SingleJar.java:240)
        at com.google.devtools.build.singlejar.SingleJar.singleRun(SingleJar.java:394)
        at com.google.devtools.build.singlejar.SingleJar.main(SingleJar.java:413)
INFO: Elapsed time: 2.851s, Critical Path: 2.17s
```

**Comment by laszlocsomor** [comment]
Update: I'm still (slowly) working on this issue and P1 is appropriate. Currently I have a PR (https://github.com/bazelbuild/bazel/pull/5141) that makes one shell test use the new Bash runfiles library, but I failed to merge it because, IIRC, some Google-internal tests broke and I haven't yet figured out how to fix them.

**Comment by laszlocsomor** [comment]
Current status (at https://github.com/bazelbuild/bazel/commit/20637b7870a09a35b716f69a6d8ce5b4c5fe3722):
- `bazel query "tests(//src/...)" | wc -l` --> 410
- `bazel query "tests(//src/...)-tests(//src:all_windows_tests)" | wc -l` --> 259

Currently only 63% of all tests under //src/... run on Windows.

**Comment by brandjon** [comment]
Laszlo, from a very quick glance it seems like converting shell tests to windows includes copy/pasting some header boilerplate on each .sh file. Can this boilerplate really not be factored into a common file? What's the plan for if the boilerplate needs to be changed in the future?

More to the point, I want to add a new shell test to src/test/shell/integration. Should I just cargo-cult a header from a converted file?

**Comment by laszlocsomor** [comment]
Jon, indeed there's a copy-pasted boilerplate.

The reason this can't be factored to a common file is, there's no common preamble to sh_* rules where we could source that file. When you "bazel build" a sh_binary, Bazel merely creates a symlink to whatever file is in the rule's `srcs`, be it a shell script or an arbitrary binary. Running the output from bazel-bin runs the file directly, without running it through a launcher like java_binary or py_binary would do. Users may already be depending on this, i.e. the ability to stick an arbitrary binary in sh_binary.srcs and run it without any wrappers, and so without knowing more we should not change this behavior.

**Comment by brandjon** [comment]
That part sounds reasonable, but why can't we factor the boilerplate preamble into a common utility file and explicitly source that file wherever it's needed?

**Comment by laszlocsomor** [comment]
Because we don't know the path of that file at runtime.

**Comment by laszlocsomor** [comment]
Remember we have no runfiles tree on Windows, so we must look up runfiles from a manifest file, but we must first find that manifest file (either from an envvar, or from next to the binary). This is what the boilerplate code actually does.

**Comment by brandjon** [comment]
I see. That's unfortunate...

**Comment by michajlo** [comment]
I'm assuming this is why we have `//src:all_windows_tests` instead of running all the tests and opting out those that are broken? I'm worried that this abstraction may become (or has been becoming) brittle or broken as we restructure our BUILD files.

**Comment by laszlocsomor** [comment]
> I'm assuming this is why we have `//src:all_windows_tests` instead of running all the tests and opting out those that are broken?

IIRC yes.

Today we can skip incompatible targets (yay!) so filtering out incompatible tests is easier.

```
sh_test(
    name = "only_on_linux_arm64",
    srcs = ["a.sh"],
    target_compatible_with = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
    ],
)

sh_test(
    name = "except_on_windows",
    srcs = ["a.sh"],
    target_compatible_with = select({
        "@platforms//os:windows": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
```

**Comment by meteorcloudy** [comment]
Since https://github.com/bazelbuild/bazel/issues/3742 is no longer an issue on BuildKite (because we don't run bazel query first), I think we can switch to the `bazel test --test_tag_filters=-no_windows //...` approach to run Windows tests.
