### ISSUE TITLE
skylark is vulnerable to self-referential data structures

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#4295]
Here's a nice way to get a Java stack trace:
```
# BUILD
evil = []
evil.append(evil)

filegroup(
    name = 'f',
    srcs = evil,
)
```
```
$ bazel --batch build :f
INFO: Elapsed time: 0.402s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
java.lang.StackOverflowError
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:441)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.repr(Printer.java:319)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:445)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.repr(Printer.java:319)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:445)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.repr(Printer.java:319)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:445)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.repr(Printer.java:319)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:445)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.repr(Printer.java:319)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.appendListElements(Printer.java:445)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:427)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:466)
    at com.google.devtools.build.lib.syntax.Printer$BasePrinter.printList(Printer.java:261)
    at com.google.devtools.build.lib.syntax.SkylarkList.repr(SkylarkList.java:102)
...
```

**Comment by laszlocsomor** [comment]
Oops. :)
Nice catch, thanks for reporting!

**Comment by meisterT** [comment]
This is still the case at HEAD.

**Comment by brandjon** [comment]
Yep, there's lots of ways to crash the interpreter with a cyclic data structure, without even using Bazel constructs. E.g.,

```
a = []
a.append(a)
print(a)
```

I filed bazelbuild/starlark#166 to track the question of what to do with the language spec. In general, we'd like to make this not crash Bazel, but it's not very high priority since you don't tend to tickle this bug accidentally.

**Comment by benjaminp** [comment]
@bazelbuild/triage not stale
