### ISSUE TITLE
Various Bazel tools and tests fail under Python 3

### ISSUE THREAD

**Issue by duggelz** [bazelbuild/bazel#4310]
Bazel CI failure: https://ci.bazel.io/blue/organizations/jenkins/PR%2Fbazel-tests/detail/bazel-tests/220/pipeline/25#step-216-log-69

### Description of the problem / feature request / question:

When Bazel runs on a system where the Python interpreter version is >= 3, here is a sampling of tests that fail:

```
INFO: From Testing //tools/android:resource_extractor_test:

==================== Test output for //tools/android:resource_extractor_test:

Traceback (most recent call last):

  File "/home/ci/.cache/bazel/_bazel_ci/667ce0ef36b8ba2f23d5b04798cb9bdc/bazel-sandbox/1942650350792869462/execroot/io_bazel/bazel-out/k8-fastbuild/bin/tools/android/resource_extractor_test.runfiles/io_bazel/tools/android/resource_extractor_test.py", line 17, in <module>

    import StringIO

ImportError: No module named 'StringIO'

================================================================================
```
```
INFO: From Testing //tools/android:merge_manifests_test:

==================== Test output for //tools/android:merge_manifests_test:

Traceback (most recent call last):

  File "/home/ci/.cache/bazel/_bazel_ci/667ce0ef36b8ba2f23d5b04798cb9bdc/bazel-sandbox/975420787232071798/execroot/io_bazel/bazel-out/k8-fastbuild/bin/tools/android/merge_manifests_test.runfiles/io_bazel/tools/android/merge_manifests_test.py", line 21, in <module>

    from tools.android import merge_manifests

  File "/home/ci/.cache/bazel/_bazel_ci/667ce0ef36b8ba2f23d5b04798cb9bdc/bazel-sandbox/975420787232071798/execroot/io_bazel/bazel-out/k8-fastbuild/bin/tools/android/merge_manifests_test.runfiles/io_bazel/tools/android/merge_manifests.py", line 452

    print warning

                ^

SyntaxError: Missing parentheses in call to 'print'
```
```
INFO: From Testing //src/test/skylark:skylark_test_testdata/all_any_sky:

==================== Test output for //src/test/skylark:skylark_test_testdata/all_any_sky:

E

======================================================================

ERROR: testFile (__main__.SkylarkTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/ci/.cache/bazel/_bazel_ci/667ce0ef36b8ba2f23d5b04798cb9bdc/bazel-sandbox/4728463473593327320/execroot/io_bazel/bazel-out/k8-fastbuild/bin/src/test/skylark/skylark_test_testdata/all_any_sky.runfiles/io_bazel/src/test/skylark/skylark_test.py", line 95, in testFile

    tmp.writelines([self.PRELUDE] + chunk)

  File "/usr/lib/python3.4/tempfile.py", line 538, in func_wrapper

    return func(*args, **kwargs)

TypeError: 'str' does not support the buffer interface



----------------------------------------------------------------------
```

### If possible, provide a minimal example to reproduce the problem:

Bazel CI config: https://github.com/bazelbuild/bazel/pull/3873

### Environment info
* Operating System: node=linux-x86_64

* Bazel version (output of `bazel info release`): commit id dbec5e1e19b8ccda27eea141506ce31f14519f83

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/pull/3850/files
https://github.com/bazelbuild/bazel/issues/3816

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
I don't think we officially support python3 yet, so I'll tag it as a feature request to speed up our efforts with python3 support.

As @philwo is handling the relevant pull request, over to him for further triage.

**Comment by duggelz** [comment]
Duplicate of #1580, closing
