### ISSUE TITLE
build error "ByteString would be too long" with remote cache

### ISSUE THREAD

**Issue by gongwei** [bazelbuild/bazel#4329]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I am using bazel 0.5.4 and tried use bazel as gRPC remote cached and hazelcast for remote cache.
It gives build error whenever remote cache is set. It works fine when no remote cache is set.

Target //tensorflow/tools/sdk_package:build_sdk_package failed to build
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1237577046 1862180944), actionIndex=2}' (requested by nodes 'tensorflow/libtensorflow_cc.so //tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1045601756 1862180944)')
INFO: Elapsed time: 1411.342s, Critical Path: 266.73s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1237577046 1862180944), actionIndex=2}' (requested by nodes 'tensorflow/libtensorflow_cc.so //tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1045601756 1862180944)')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: ByteString would be too long: 1506778880+1506804064
        at com.google.protobuf.ByteString.concat(ByteString.java:524)
        at com.google.protobuf.ByteString.balancedConcat(ByteString.java:576)
        at com.google.protobuf.ByteString.copyFrom(ByteString.java:559)
        at com.google.protobuf.ByteString.readFrom(ByteString.java:475)
        at com.google.protobuf.ByteString.readFrom(ByteString.java:429)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadFileContents(SimpleBlobStoreActionCache.java:96)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:202)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:174)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.execLocallyAndUpload(RemoteSpawnRunner.java:282)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.execLocally(RemoteSpawnRunner.java:246)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:131)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:143)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:60)
        at com.google.devtools.build.lib.rules.cpp.CppLinkAction.execute(CppLinkAction.java:329)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:849)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:107)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:660)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:617)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:404)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1237577046 1862180944), actionIndex=2}' (requested by nodes 'tensorflow/libtensorflow_cc.so //tensorflow:libtensorflow_cc.so 8220d375313c09f3185206e594912f7a (1045601756 1862180944)')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: ByteString would be too long: 1506778880+1506804064
        at com.google.protobuf.ByteString.concat(ByteString.java:524)
        at com.google.protobuf.ByteString.balancedConcat(ByteString.java:576)
        at com.google.protobuf.ByteString.copyFrom(ByteString.java:559)
        at com.google.protobuf.ByteString.readFrom(ByteString.java:475)
        at com.google.protobuf.ByteString.readFrom(ByteString.java:429)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadFileContents(SimpleBlobStoreActionCache.java:96)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:202)
        at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:174)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.execLocallyAndUpload(RemoteSpawnRunner.java:282)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.execLocally(RemoteSpawnRunner.java:246)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:131)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:143)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:60)
        at com.google.devtools.build.lib.rules.cpp.CppLinkAction.execute(CppLinkAction.java:329)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:849)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:107)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:660)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:617)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:404)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more
_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
bazel set up

 write_to_bazelrc "startup --host_jvm_args=-Dbazel.DigestFunction=SHA1"
  write_to_bazelrc "build --spawn_strategy=remote"
  write_to_bazelrc "build --strategy=Javac=remote"
  write_to_bazelrc "build --genrule_strategy=remote"
  #write_to_bazelrc "build --remote_rest_cache=http://10.101.219.71:8080/cache"
  write_to_bazelrc "build --remote_cache=10.101.219.71:8080"
  write_to_bazelrc "build --remote_local_fallback=true"
  write_to_bazelrc "build --remote_timeout=5"

* Bazel version (output of `bazel info release`):
0.5.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
As far as I remember, a lot has changed with respect to remote caching since `bazel 0.5.4`. Assigning to our experts for further triage.

**Comment by ulfjack** [comment]
Do you realize that you're trying to upload 3 GB worth of data?

**Comment by buchgr** [comment]
@gongwei can you upgrade to a newer Bazel version please and try again? This particular issue has been fixed in the meantime.

**Comment by gongwei** [comment]
@ulfjack yes, I do. Is this supported?

**Comment by gongwei** [comment]
@buchgr do you have a ticket/change number for this issue fix? I am working on tensorflow which the opensource community still at 0.5.4 and bazel has quite some breaking changes in later version.

**Comment by buchgr** [comment]
@gongwei yes it is supported and #3250 is the issue for it.
