### ISSUE TITLE
CI, bazel-tests: broken on Windows ("Cannot create Unix-style paths on Windows")

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4336]
Commit https://github.com/bazelbuild/bazel/commit/8b3ba50246fed6ff13d70299fb039cc66be465c4 breaks `//src/test/py/bazel:bazel_windows_test` which currently makes bazel-tests fail on Windows.

I added logging to the exception thrown (just print `parent` and `child`), and thus the output is:

```
INFO: From Testing //src/test/py/bazel:bazel_windows_test:
==================== Test output for //src/test/py/bazel:bazel_windows_test:
F
======================================================================
FAIL: testWindowsUnixRoot (__main__.BazelWindowsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\tmp1\o6hbs7n0\execroot\io_bazel\tmp900_c05785e7bc60a6e6\Bazel.runfiles_hvungx\runfiles\io_bazel\src\test\py\bazel\bazel_windows_test.py", line 46, in testWindowsUnixRoot
    self.AssertExitCode(exit_code, 0, stderr)
  File "c:\tmp1\o6hbs7n0\execroot\io_bazel\tmp900_c05785e7bc60a6e6\Bazel.runfiles_hvungx\runfiles\io_bazel\src\test\py\bazel\test_base.py", line 68, in AssertExitCode
    '(end stderr)------------------------------------------',
AssertionError: Bazel exited with 37 (expected 0), stderr:
(start stderr)----------------------------------------
Loading:
Loading: 0 packages loaded
Analyzing: target //foo:x (6 packages loaded)
INFO: Analysed target //foo:x (8 packages loaded).
INFO: Found 1 target...
[0 / 6] no action
Target //foo:x failed to build
Use --verbose_failures to see the command lines of failed build steps.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://foo:x 65684c9e69f8aad9d8934359808ace8d (1353197053 1108775790), actionIndex=0}' (requested by nodes 'foo/_objs/x/foo/x.o //foo:x 65684c9e69f8aad9d8934359808ace8d (1451840937 1108775790)')
INFO: Elapsed time: 2.230s, Critical Path: 0.34s
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://foo:x 65684c9e69f8aad9d8934359808ace8d (1353197053 1108775790), actionIndex=0}' (requested by nodes 'foo/_objs/x/foo/x.o //foo:x 65684c9e69f8aad9d8934359808ace8d (1451840937 1108775790)')
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot create Unix-style paths on Windows. parent=(/) child=(usr)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.getCachedChildPathInternalImpl(WindowsFileSystem.java:113)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.access$300(WindowsFileSystem.java:85)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory$1.getCachedChildPathInternal(WindowsFileSystem.java:100)
at com.google.devtools.build.lib.vfs.Path.getCachedChildPath(Path.java:297)
at com.google.devtools.build.lib.vfs.Path.getCanonicalPath(Path.java:838)
at com.google.devtools.build.lib.vfs.Path.getRelative(Path.java:874)
at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:145)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getPermittedSystemIncludePrefixes(CppCompileAction.java:1231)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.discoverInputsFromDotdFiles(CppCompileAction.java:1197)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1137)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:867)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:810)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:111)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:678)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:635)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://foo:x 65684c9e69f8aad9d8934359808ace8d (1353197053 1108775790), actionIndex=0}' (requested by nodes 'foo/_objs/x/foo/x.o //foo:x 65684c9e69f8aad9d8934359808ace8d (1451840937 1108775790)')
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot create Unix-style paths on Windows. parent=(/) child=(usr)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.getCachedChildPathInternalImpl(WindowsFileSystem.java:113)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.access$300(WindowsFileSystem.java:85)
at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory$1.getCachedChildPathInternal(WindowsFileSystem.java:100)
at com.google.devtools.build.lib.vfs.Path.getCachedChildPath(Path.java:297)
at com.google.devtools.build.lib.vfs.Path.getCanonicalPath(Path.java:838)
at com.google.devtools.build.lib.vfs.Path.getRelative(Path.java:874)
at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:145)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getPermittedSystemIncludePrefixes(CppCompileAction.java:1231)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.discoverInputsFromDotdFiles(CppCompileAction.java:1197)
at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1137)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:867)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:810)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:111)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:678)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:635)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
... 4 more
INFO: $TEST_TMPDIR defined: output root default is 'c:\tmp1\o6hbs7n0\execroot\io_bazel\_tmp\b6bda2f0385d1152d3a7f550c6cc1938' and max_idle_secs default is '15'.
(end stderr)------------------------------------------
```

**Comment by jin** [comment]
This test is now passing on bazel-tests, closing.
