### ISSUE TITLE
0.9.0 bazel build fail with gRPC remote cache

### ISSUE THREAD

**Issue by gongwei** [bazelbuild/bazel#4361]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I use bazel remote worker as a cache server, build would fail if local fallback is disabled (I want to make sure remote cache is really working).

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
remote worker setting: 
        bazel-bin/src/tools/remote_worker/remote_worker   --work_path=/tmp/test  --listen_port=8080

bazel setting:
  write_to_bazelrc "build --spawn_strategy=remote"
  write_to_bazelrc "build --strategy=Javac=remote"
  write_to_bazelrc "build --genrule_strategy=remote"
  write_to_bazelrc "build --remote_cache=10.101.219.71:8080"

### Environment info
* Operating System:
linux redhat

* Bazel version (output of `bazel info release`):
0.9.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
ERROR: /home/admin/wei.gong/tensorflow/tensorflow/compiler/xla/tests/BUILD:115:1: Linking of rule '//tensorflow/compiler/xla/tests:local_client_aot_test_helper' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed after exhausting retry attempts: 5
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:242)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:101)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.download(GrpcRemoteCache.java:203)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.downloadRemoteResults(RemoteSpawnRunner.java:206)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:158)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:97)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:65)
        at com.google.devtools.build.lib.rules.cpp.CppLinkAction.execute(CppLinkAction.java:321)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:860)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:803)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:110)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:671)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:628)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:412)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:523)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.readBlob(GrpcRemoteCache.java:287)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$download$1(GrpcRemoteCache.java:206)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:220)
        ... 21 more
INFO: Elapsed time: 1203.491s, Critical Path: 286.69s
FAILED: Build did NOT complete successfully

**Comment by buchgr** [comment]
Please retry with 0.11.1 and re-open if it's still a problem
