### ISSUE TITLE
bazel hits a NullPointerException when --auth_credentials is passed a non-existent file

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#4386]
### Description of the problem / feature request / question:
When running a build with --auth_credentials provided, but the referenced file not present, bazel hits a NullPointerException then spends about 70s waiting for its server to die. This should be handled more gracefully.

### If possible, provide a minimal example to reproduce the problem:
add `--auth_credentials=blah` to an otherwise reasonable command (may need to be a remote build also, to hit the right code path; unclear at what time this credential actually gets parsed).

### Environment info
* Operating System:
Linux (container: gcr.io/cloud-builders/bazel)

* Bazel version (output of `bazel info release`):
0.9.0

###  Have you found anything relevant by searching the web?
Nope

### Anything else, information or logs or outputs that would be helpful?
Full stdout:

Extracting Bazel installation...
...........................
ERROR: Could not open auth credentials file 'service_account_credential.json': service_account_credential.json (No such file or directory)
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
	at com.google.devtools.build.lib.events.Event.error(Event.java:165)
	at com.google.devtools.build.lib.events.Event.error(Event.java:200)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:470)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
	at com.google.devtools.build.lib.events.Event.error(Event.java:165)
	at com.google.devtools.build.lib.events.Event.error(Event.java:200)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:470)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=21) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=21) to terminate.
Attempted to kill stale server process (pid=21) using SIGKILL, but it did not die in a timely fashion.

**Comment by philwo** [comment]
@buchgr I guess the code might have changed a lot in the meantime and thus this might be fixed - could you have a quick look?

**Comment by buchgr** [comment]
Yep now getting 

```
ERROR: Could not open auth credentials file 'blah'. (No such file or directory)
```
