### ISSUE TITLE
CI, Gerrit: failing to build on linux-x86_64

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4416]
```
[gerrit-variation=,node=linux-x86_64] Running shell script
+ /home/ci/.bazel/latest/binary/bazel --bazelrc=/home/ci/workspace/gerrit-variation=,node=linux-x86_64/bazel.bazelrc build //:release
Loading: 
Loading: 0 packages loaded
Analyzing: target //:release (3 packages loaded)
Analyzing: target //:release (7 packages loaded)
Analyzing: target //:release (177 packages loaded)
Analyzing: target //:release (223 packages loaded)
Analyzing: target //:release (278 packages loaded)
Analyzing: target //:release (279 packages loaded)
ERROR: /home/ci/workspace/gerrit-variation=,node=linux-x86_64/lib/js/BUILD:25:1: no such package '@font-roboto//': failed /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py -b /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py /home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2.npm_binary.tgz -n font-roboto -p PolymerElements/font-roboto -v 1.0.3 -s edf478d20ae2fc0704d7c155e20162caaabdd5ae -o font-roboto__download_bower.zip: /usr/bin/env: node: No such file or directory
Traceback (most recent call last):
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py", line 91, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py", line 87, in main
    subprocess.check_call([bin] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2-adf53529c8d4af02ef24fb8d5341c1419d33e2f7/package/bin/bower', '-l=error', '-j', 'info', 'PolymerElements/font-roboto#1.0.3']' returned non-zero exit status 127
Traceback (most recent call last):
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 128, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 99, in main
    info = bower_info(opts.b, opts.n, opts.p, opts.v)
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 49, in bower_info
    raise OSError('Command failed: %s' % ' '.join(cmd))
OSError: Command failed: /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py /home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2.npm_binary.tgz -l=error -j info PolymerElements/font-roboto#1.0.3
 and referenced by '//lib/js:font-roboto'
ERROR: /home/ci/workspace/gerrit-variation=,node=linux-x86_64/lib/js/BUILD:25:1: no such package '@font-roboto//': failed /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py -b /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py /home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2.npm_binary.tgz -n font-roboto -p PolymerElements/font-roboto -v 1.0.3 -s edf478d20ae2fc0704d7c155e20162caaabdd5ae -o font-roboto__download_bower.zip: /usr/bin/env: node: No such file or directory
Traceback (most recent call last):
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py", line 91, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py", line 87, in main
    subprocess.check_call([bin] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2-adf53529c8d4af02ef24fb8d5341c1419d33e2f7/package/bin/bower', '-l=error', '-j', 'info', 'PolymerElements/font-roboto#1.0.3']' returned non-zero exit status 127
Traceback (most recent call last):
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 128, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 99, in main
    info = bower_info(opts.b, opts.n, opts.p, opts.v)
  File "/home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/download_bower.py", line 49, in bower_info
    raise OSError('Command failed: %s' % ' '.join(cmd))
OSError: Command failed: /usr/bin/python /home/ci/workspace/gerrit-variation=,node=linux-x86_64/tools/js/run_npm_binary.py /home/ci/.cache/bazel/_bazel_ci/dd37f2c93a627e0efa54b3185369e43f/external/bower/bower@1.8.2.npm_binary.tgz -l=error -j info PolymerElements/font-roboto#1.0.3
 and referenced by '//lib/js:font-roboto'
ERROR: Analysis of target '//:release' failed; build aborted: Loading failed
INFO: Elapsed time: 14.427s
FAILED: Build did NOT complete successfully (279 packages loaded)
FAILED: Build did NOT complete successfully (279 packages loaded)
script returned exit code 1
```

Specific error: `/usr/bin/env: node: No such file or directory`

Started failing from https://ci.bazel.build/blue/organizations/jenkins/gerrit/detail/gerrit/2062/pipeline/

cc @davido

**Comment by jin** [comment]
Most likely related to https://github.com/bazelbuild/rules_nodejs/issues/77

**Comment by davido** [comment]
> Most likely related to bazelbuild/rules_nodejs#77

Hm.., we are not using `rules_nodejs`.

Can it be that some external Polymer dependencies were temporarily not available for networking reasons? I just rechecked, and I can build Gerrit@HEAD with Bazel@HEAD from scratch, without any issue.

**Comment by jin** [comment]
Green: https://github.com/bazelbuild/bazel/issues/4416

Root cause: missing `node` on the machine, fixed by @philwo.
