### ISSUE TITLE
CI bazel-integration-testing is failing with bazel 0.10.0 RC1

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4423]
bazel-integration-testing does not build on darwin, linux and ubuntu. The reported error is:
```
ERROR: /Users/ci/workspace/Global/bazel-integration-testing-node=darwin-x86_64/WORKSPACE:7:1: Traceback (most recent call last):

	File "/Users/ci/workspace/Global/bazel-integration-testing-node=darwin-x86_64/WORKSPACE", line 7

		check_bazel_version("0.5.0")

	File "/Users/ci/workspace/Global/bazel-integration-testing-node=darwin-x86_64/bazel_version.bzl", line 34, in check_bazel_version

		fail("\nCurrent Bazel version is {}, ...))



Current Bazel version is 0.10.0rc1, expected at least 0.5.0

ERROR: Error evaluating WORKSPACE file

ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package

ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package

INFO: Elapsed time: 0.386s

FAILED: Build did NOT complete successfully (0 packages loaded)

FAILED: Build did NOT complete successfully (0 packages loaded)

script returned exit code 1
```
The entire console output is [here](https://ci.bazel.build/job/Global/job/bazel-integration-testing/142/console)
This is blocking the 0.10.0 release (#3958).

**Comment by iirina** [comment]
The same error appears when trying to build [eclipse](https://ci.bazel.build/blue/organizations/jenkins/Global%2Feclipse/detail/eclipse/346/pipeline/).

**Comment by jin** [comment]
To fix: https://github.com/bazelbuild/bazel-integration-testing/blob/master/bazel_version.bzl

**Comment by iirina** [comment]
Any update on this?

**Comment by jin** [comment]
yes, once https://github.com/bazelbuild/bazel-skylib/pull/13 is merged, I can update both bazel-integration-testing and eclipse to use the Skylib function.

**Comment by jin** [comment]
Both PRs are merged, this should be unblocked now.

**Comment by jin** [comment]
This issue should be fixed, now that both projects are using Skylib.

**Comment by iirina** [comment]
@jin Thanks!
