### ISSUE TITLE
"IOException: Illegal seek" during build v0.9.0 on Android aarch64

### ISSUE THREAD

**Issue by borisbrodski** [bazelbuild/bazel#4450]
### Description of the problem / feature request:

Can't compile bazel on Android aarch64 (Samsung Galaxy Note 8) under Termux/ArchLinux.

### Bugs: what's the simplest, easiest way to reproduce this bug?

On an Android device (Note 8) install:

* Termux App
* Unter Termux install ArchLinux (https://wiki.termux.com/wiki/Arch)
* ArchLinux: Install with pacman -S: wget, jdk8-openjdk, zlib
* Download bazel-0.9.0-dest.zip, extract it
* Add "-J-Xmx1G" to the call to the javac in bootstrap to avoid OutOfMemory: heap
* ./compile.sh
* Wait for 2-3 hours
* Scroll way back to find exception attached below

### What operating system are you running Bazel on?

    $ uname -a
    Linux localhost 4.4.13-12472670 #1 SMP PREEMPT Thu Nov 30 11:41:23 KST 2017 aarch64 GNU/Linux

### What's the output of `bazel info release`?

Unknown, bazel can't be built

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I'm trying to compile an official release.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

No git repository being used

###  Have you found anything relevant by searching the web?

Absolutely nothing

### Any other information, logs, or outputs that you want to share?

The relevant part of the log

```
Building deploy jar .../buildjar/JavaBuilder_deploy.jar;
[1,619 / 1,789] 6 actions running
Building deploy jar .../singlejar/bazel-singlejar_deploy.jar; 7s local
.../java/com/google/devtools/build/android:android_builder_lib; 0s worker
Building deploy jar .../buildjar/JavaBuilder_deploy.jar;ERROR: /root/bazel-0.9.0/src/main/java/com/google/devtools/build/lib/vfs/BUILD:30:1: Building src/main/java/com/google/devtools/build/lib/vfs/libvfs.jar (22 source files) and running annotation processors (OptionProcessor) failed: Worker process did not return a WorkResponse:
-
---8<---8<--- Start of log, file at /tmp/bazel_arrsxVP9/out/bazel-workers/worker-2-Javac.log ---8<---8<---
OpenJDK 64-Bit Zero VM warning: TieredCompilation is disabled in this release.
java.io.IOException: Illegal seek
         at java.io.FileInputStream.available(Native Method)
         at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
         at java.io.FilterInputStream.read(FilterInputStream.java:133)
         at com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream.read(AbstractMessageLite.java:290)
         at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2777)
         at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2723)
         at com.google.protobuf.CodedInputStream$StreamDecoder.readRawByte(CodedInputStream.java:2803)
         at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64SlowPath(CodedInputStream.java:2594)
         at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint32(CodedInputStream.java:2488)
         at com.google.protobuf.CodedInputStream$StreamDecoder.readStringRequireUtf8(CodedInputStream.java:2268)
         at com.google.devtools.build.lib.worker.WorkerProtocol$Input.<init>(WorkerProtocol.java:105)
         at com.google.devtools.build.lib.worker.WorkerProtocol$Input.<init>(WorkerProtocol.java:62)
         at com.google.devtools.build.lib.worker.WorkerProtocol$Input$1.parsePartialFrom(WorkerProtocol.java:682)
         at com.google.devtools.build.lib.worker.WorkerProtocol$Input$1.parsePartialFrom(WorkerProtocol.java:677)
         at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2362)
         at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.<init>(WorkerProtocol.java:837)
         at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.<init>(WorkerProtocol.java:780)
         at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest$1.parsePartialFrom(WorkerProtocol.java:1773)
         com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest$1.parsePartialFrom(WorkerProtocol.java:1768)
         com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
         at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
         at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
         at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
         at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
```

**Comment by dslomov** [comment]
We do not really test Bazel building on tablets. Exception seems like a protobuf issue.
Why do you need to build it in that environment?

**Comment by borisbrodski** [comment]
I would like to run tensorflow on my mobile device.

It looks like `aarch64` architecture is supported
(at least according to get_cpu_value in tools/cpp/lib_cc_configure.bzl).

Do you have any suggestions about workaround or fix this problem?
Or may be a bazel aarch64 version is available to download?

Thank you!

**Comment by aj-michael** [comment]
@borisbrodski - what are you trying to do? If you goal is just "to run tensorflow on my mobile device", you don't need to compile bazel on your tablet..

**Comment by borisbrodski** [comment]
@aj-michael You are right. This is my goal. But how can I compile/install TensorFlow on my Android without compiling bazel first?

**Comment by aj-michael** [comment]
Do you have access to a computer other than your mobile device? Typically you would run bazel on some other machine that Bazel does support and compile an Android application (.apk) which you can then run on your device. There are some instructions here: https://www.tensorflow.org/mobile/android_build#build_the_demo_using_bazel

**Comment by meisterT** [comment]
It seems that this issue is stale.
