### ISSUE TITLE
rules_webtesting tests are failing with bazel 0.10.0rc2 on windows

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4459]
Error snippet:
```
======================================================================
ERROR: testBrowserProvisioningWithCaps (__main__.BrowserTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/io_bazel_rules_webtesting/testing/web/webtest_test.py", line 37, in testBrowserProvisioningWithCaps
    driver = webtest.new_webdriver_session(capabilities)
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/io_bazel_rules_webtesting/testing/web/webtest.py", line 48, in new_webdriver_session
    return webdriver.WebDriver(address, desired_capabilities=capabilities)
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/org_seleniumhq_py/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/org_seleniumhq_py/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/org_seleniumhq_py/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/home/ci/.cache/bazel/_bazel_ci/140d00ad1dcb33975ec7b5cb001f7b9b/bazel-sandbox/6447244412364996219/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/bin/testing/web/webtest_test_chrome55-win10.runfiles/org_seleniumhq_py/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: [Go WebDriver Client]: invalid character 'S' looking for beginning of value unmarshalling &{Status:<nil> SessionID: Value:<nil> Error: Message: StackTrace:<nil>}
```

Failed tests are [here](https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_webtesting/detail/rules_webtesting/14/tests).
Full console output is [here](https://ci.bazel.build/job/Global/job/rules_webtesting/14/console).

**Comment by iirina** [comment]
@dslomov Can you triage this please? It seems this project was never green on our CI.

**Comment by meteorcloudy** [comment]
Actually, the job doesn't run on Windows, but there are some Windows-like test running on Linux, that's why it's failing. 
@DrMarcII Should we disable these tests on Linux?
```
//go/launcher/proxy/driverhub/mobileemulation:go_default_test_chrome55-win10 FAILED in 2.8s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/go/launcher/proxy/driverhub/mobileemulation/go_default_test_chrome55-win10/test.log

//go/launcher/proxy/driverhub/quithandler:go_default_test_chrome55-win10 FAILED in 2.8s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/go/launcher/proxy/driverhub/quithandler/go_default_test_chrome55-win10/test.log

//go/launcher/proxy/driverhub/scripttimeout:go_default_test_chrome55-win10 FAILED in 0.8s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/go/launcher/proxy/driverhub/scripttimeout/go_default_test_chrome55-win10/test.log

//go/screenshotter:go_default_test_chrome55-win10                        FAILED in 2.5s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/go/screenshotter/go_default_test_chrome55-win10/test.log

//go/webtest:go_default_test_chrome55-win10                              FAILED in 2.0s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/go/webtest/go_default_test_chrome55-win10/test.log

//javatests/com/google/testing/web:WebTestTest_chrome55-win10            FAILED in 2.7s

  /home/ci/.cache/bazel/_bazel_ci/ac8db66124ade103afee81e9bbb26065/execroot/io_bazel_rules_webtesting/bazel-out/k8-fastbuild/testlogs/javatests/com/google/testing/web/WebTestTest_chrome55-win10/test.log

//testing/web:webtest_test_chrome55-win10                                FAILED in 2.7s

```

**Comment by DrMarcII** [comment]
This project has been green on the CI, but https://github.com/bazelbuild/continuous-integration/commit/abae192cfdebe179aaf3be1923dad745fc0fa78c removed the saucelabs support from Jenkins that these tests relied on. For now I suggest you go ahead and disable this project.
