### ISSUE TITLE
iOS static framework does not build with bazel anymore

### ISSUE THREAD

**Issue by spinorx** [bazelbuild/bazel#4466]
### Description of the problem / feature request:
iOS static framework does not build with bazel 0.9.0 (and 0.8.0).  Used to work fine with 0.7.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
$ git clone git@github.com:spinorx/bazel_ios_test.git
$ cd bazel_ios_test
$ bazel build --config ios_dev ios_s_fx
```
Shows:
```
[param@param-mac:~/bazel_ios_test]$ bazel build --config ios_dev ios_s_fx
ERROR: /Users/param/bazel_ios_test/BUILD:27:1: in ios_static_framework rule //:ios_s_fx:
Traceback (most recent call last):
	File "/Users/param/bazel_ios_test/BUILD", line 27
		ios_static_framework(name = 'ios_s_fx')
	File "/private/var/tmp/_bazel_param/6e7baaf7d936c10284a3fa8c52020240/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 336, in _ios_static_framework_impl
		bundler.run(ctx, "IosStaticFrameworkArchive", "i...", <7 more arguments>)
	File "/private/var/tmp/_bazel_param/6e7baaf7d936c10284a3fa8c52020240/external/build_bazel_rules_apple/apple/bundling/bundler.bzl", line 953, in bundler.run
		apple_common.new_objc_provider(**objc_provider_args)
illegal argument in call to new_objc_provider: Argument framework_dir not a recognized key, 'providers', or 'direct_dep_providers'.
ERROR: Analysis of target '//:ios_s_fx' failed; build aborted: Analysis of target '//:ios_s_fx' failed; build aborted
INFO: Elapsed time: 0.213s
FAILED: Build did NOT complete successfully (1 packages loaded)
[param@param-mac:~/bazel_ios_test]$
```

### What operating system are you running Bazel on?
Running on Mac 10.13 and Xcode 9.2.  More details:
```
[param@param-mac:~/bazel_ios_test]$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.2 (17C88)
      Kernel Version: Darwin 17.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: param-mac
      User Name: Param Reddy (param)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 37 days 18:16

[param@param-mac:~/bazel_ios_test]$ /usr/bin/xcodebuild -version
Xcode 9.2
Build version 9C40b
[param@param-mac:~/bazel_ios_test]$
```

### What's the output of `bazel info release`?

```
[param@param-mac:~/bazel_ios_test]$ bazel info release
release 0.9.0-homebrew
[param@param-mac:~/bazel_ios_test]$
```

**Comment by spinorx** [comment]
Any update on this?

**Comment by c-parsons** [comment]
I believe this was fixed in https://github.com/bazelbuild/rules_apple/commit/e921a9f727e039c8b5087d4f98c5d09f189658cd
