### ISSUE TITLE
CI bazel 0.10.0rc4: bazel-tests fails on Windows

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4497]
Error snippet:
```
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/shell/bazel:bazel_bootstrap_distfile_test (see C:/windows/temp/_bazel_system/yuv-tl0g/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/shell/bazel/bazel_bootstrap_distfile_test/test.log)

Stacktrace
Failed to read test report file c:\jenkins\workspace\Global\bazel-tests-node=windows-x86_64,toolchain=msvc\tests-node=windows-x86_64-toolchain=msvc\src\test\shell\bazel\bazel_bootstrap_distfile_test\test.xml
org.dom4j.DocumentException: Error on line 24 of document  : An invalid XML character (Unicode: 0x1b) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x1b) was found in the CDATA section.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:169)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:348)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:281)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:206)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:178)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:143)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2813)
	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 2; An invalid XML character (Unicode: 0x1b) was found in the CDATA section.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1690)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	... 19 more
```

Full log is [here](https://ci.bazel.build/job/Global/job/bazel-tests/453/console). Note there are also some test that failed on Darwin in the console log.

**Comment by laszlocsomor** [comment]
Are you sure this is the correct log link? I can't find the stack trace in it.

**Comment by iirina** [comment]
I didn't double check for the error I copy-pasted.

The log link is correct. The error snippet is from the Blue Ocean view ([link here](https://ci.bazel.build/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/453/tests), the last step under Existing failures).

In the normal Jenkins [view](https://ci.bazel.build/job/Global/job/bazel-tests/453/consoleFull) I see
```
[node=windows-x86_64,toolchain=msvc] FAIL: //src/test/shell/bazel:bazel_bootstrap_distfile_test (see C:/windows/temp/_bazel_system/yuv-tl0g/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/src/test/shell/bazel/bazel_bootstrap_distfile_test/test.log)
```

**Comment by iirina** [comment]
Thanks for looking into this. Do you think the XML character bug could block the release? If not, I'll remove this as a release blocker.

**Comment by laszlocsomor** [comment]
I don't know, I need some more time to figure that out.

**Comment by laszlocsomor** [comment]
I don't think this is a blocker, alas without the original test log I can't say exactly what went wrong.
I guess the culprit might be this line, but I couldn't yet trigger an XML error: https://github.com/bazelbuild/bazel/blob/b4cf329022bb4afd45e96c2990dd869c200dc739/tools/test/test-setup.sh#L153

**Comment by iirina** [comment]
OK, so it looks like it is not a release blocker. If it is, it would be the last one. If it's not, we can release this week. I will help tomorrow in identifying the culprit.

**Comment by iirina** [comment]
This looks like a Jenkins problem to me. Let's loop in @philwo, who also did [a recent change](https://github.com/bazelbuild/continuous-integration/commit/ae7d30ffd524eb30d47dad2fa7ab1fe5438e240e#diff-a0298033335488dc740e44e032104945) to the code that populates the CDATA section.

**Comment by iirina** [comment]
Also the problematic character seems to be escape, which is pretty weird to me.

**Comment by philwo** [comment]
Would love to help out, but that change didn't touch anything related to the CDATA section...?

**Comment by iirina** [comment]
You would think so! It touches `jenkins/lib/vars/bazelCiConfiguredJob.groovy` which is what's inside (almost) every CDATA (see [this search](https://github.com/bazelbuild/continuous-integration/search?utf8=%E2%9C%93&q=CDATA&type=)). I have no idea if it's related or not though.

**Comment by iirina** [comment]
The test is still failing with the invalid XML character error on the CI.

**Comment by iirina** [comment]
This may be related with use of color in the Jenkins report (see [example 1](https://github.com/juhovh/mocha-jenkins-reporter/issues/19) and there was another example but I lost the link :( )

**Comment by iirina** [comment]
I think somehow an escape character (0x1b) is slipping into the test output xml when the test is failing. The fix should be in Bazel's XML writer (somewhere [here](https://github.com/bazelbuild/bazel/tree/c7696b47a4a12b1e56e41246770cbd44ad1c9c3e/src/java_tools/junitrunner/java/com/google/testing/junit/runner/model)).

**Comment by laszlocsomor** [comment]
The test that failed is a shell test, so I'm guessing the relevant code is this: https://github.com/bazelbuild/bazel/blob/f7f37be17506d41c7436807791611c31e216c45c/tools/test/test-setup.sh#L153

This is supposed to filter out escape characters. But it might be wrong. I don't know Perl, so I can't say for sure.
