### ISSUE TITLE
CI bazel 0.10.0rc4   rules_nodejs  fail to build on Windows

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4501]
Error snippet:
```
[93 / 96] SkylarkAction internal/e2e/rollup/bundle.es6.js; 0s local

ERROR: C:/jenkins/workspace/global/rules_nodejs-node=windows-x86_64,toolchain=msys/internal/e2e/rollup/BUILD.bazel:12:1: SkylarkAction internal/e2e/rollup/bundle.es6.js failed (Exit 1): rollup.exe failed: error executing command 

  cd C:/windows/temp/_bazel_system/u5ofeicm/execroot/build_bazel_rules_nodejs

bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.exe --config bazel-out/x64_windows_msys-fastbuild/bin/internal/e2e/rollup/bundle.rollup.conf.js --output.file bazel-out/x64_windows_msys-fastbuild/bin/internal/e2e/rollup/bundle.es6.js --input build_bazel_rules_nodejs/internal/e2e/rollup/foo.js

[!] Error: Cannot find module 'rollup'

  looked in:

   rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\build_bazel_rules_nodejs\node_modules\rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\build_bazel_rules_nodejs_rollup_deps\node_modules\rollup

Error: Cannot find module 'rollup'

  looked in:

   rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\build_bazel_rules_nodejs\node_modules\rollup,

   C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup.exe.runfiles\build_bazel_rules_nodejs_rollup_deps\node_modules\rollup

    at Function.module.constructor._resolveFilename (C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\rollup\rollup_bin_loader.js:152:15)

    at Function.Module._load (module.js:466:25)

    at Module.require (module.js:579:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\windows\temp\_bazel_system\u5ofeicm\execroot\build_bazel_rules_nodejs\bazel-out\x64_windows_msys-fastbuild\bin\internal\e2e\rollup\bundle.rollup.conf.js:5:14)

    at Module._compile (module.js:635:30)

    at Object.require.extensions..js (C:\windows\temp\_bazel_system\u5ofeicm\external\build_bazel_rules_nodejs_rollup_deps\node_modules\rollup\bin\rollup:20371:8)

    at Module.load (module.js:554:32)

    at tryModuleLoad (module.js:497:12)

    at Function.Module._load (module.js:489:3)



INFO: Elapsed time: 2.675s, Critical Path: 1.07s

FAILED: Build did NOT complete successfully
```

Console output is [here](https://ci.bazel.build/job/Global/job/rules_nodejs/190/console).

It seems to be related to https://github.com/bazelbuild/rules_nodejs/commit/c96acafb9df26e44ecc59268a5b3cc9ebafb1d87.

@laszlocsomor @gregmagolan Could you take a look?

**Comment by laszlocsomor** [comment]
Looking.

**Comment by laszlocsomor** [comment]
This is not a regression in Bazel, I can repro it with Bazel 0.9.0 as well as with 0.10.0rc4.

**Comment by laszlocsomor** [comment]
...therefore it's not a release blocker. It may still be a Bazel bug though.

**Comment by laszlocsomor** [comment]
This is fixed at current HEAD (https://github.com/bazelbuild/rules_nodejs/commit/230d39a391226f51c03448f91eb61370e2e58c42) with Bazel 0.9.0.
