### ISSUE TITLE
remote/usability: NPE in RemoteSpawnCache (in bazel 0.10rc5)

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/bazel#4514]
### Description of the problem / feature request:

Bazel 0.10rc5 (and 0.9.0) crash when `--experimental_remote_spawn_cache` is enabled:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET:@bazel_tools//tools/jdk:gen_platformclasspath ab7606f3fc23eafcf7f580c8d4dbc797 (260264079 784429009), actionIndex=0}' (requested by nodes 'external/bazel_tools/tools/jdk/platformclasspath-impl.jar @bazel_tools//tools/jdk:gen_platformclasspath ab7606f3fc23eafcf7f580c8d4dbc797 (255022390 784429009)')
            at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
            at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
            at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:120)
            at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:90)
            at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
            at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
            at com.google.devtools.build.lib.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:77)
            at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:273)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:867)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:810)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:111)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:678)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:635)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
            at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
            at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
            at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I was following:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md#bazel-setup

I'm trying to figure out a setup where action cache can be shared between machines (linux and macos).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/gkossakowski/bazel-scala-example/tree/bazel-remote-spawn-cache-crash

### What operating system are you running Bazel on?

macos 10.12.6

### What's the output of `bazel info release`?

`release 0.9.0- (@non-git)`
built with the script in the repo (downloads dist archive and calls `./compile.sh`)

###  Have you found anything relevant by searching the web?

This issue mentions the issue has been fixed in 0.10:

https://github.com/bazelbuild/bazel/issues/4363

**Comment by iirina** [comment]
@buchgr Can you take a look? We need to release soon.

**Comment by buchgr** [comment]
Good catch. The bug happens when you specify `--experimental_remote_spawn_cache` without specifying `--remote_*_cache`. The spawn cache flag doesn't do anything without the remote cache flag though (it needs to know the caching endpoint). So I think we should print a better error message than a NullPointerException :-). I am removing this from release blocker.

**Comment by gkossakowski** [comment]
ahh, interesting. I was using only `--experimental_remote_spawn_cache` to see whether I can get "hermetic" action cache: https://groups.google.com/forum/#!topic/bazel-discuss/5M-QoZ4gPq8

**Comment by buchgr** [comment]
This has been fixed.
