### ISSUE TITLE
CI: Release jobs fail because of convert_changelog.py

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4530]
Error snippet:
```
[node=linux-x86_64,opts=[-c opt],variation=] ERROR: /home/ci/workspace/bazel/release/scripts/packages/debian/BUILD:98:1: Executing genrule //scripts/packages/debian:generate-changelog-file failed (Exit 1): bash failed: error executing command 
[node=linux-x86_64,opts=[-c opt],variation=]   (cd /home/ci/.cache/bazel/_bazel_ci/f17546af8fc3afba783542703df2c075/execroot/io_bazel && \
[node=linux-x86_64,opts=[-c opt],variation=]   exec env - \
[node=linux-x86_64,opts=[-c opt],variation=]     PATH=/home/ci/node/node-v6.9.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/bin \
[node=linux-x86_64,opts=[-c opt],variation=]   /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; python scripts/packages/debian/convert_changelog.py bazel-out/volatile-status.txt ./CHANGELOG.md bazel-out/k8-fastbuild/genfiles/scripts/packages/debian/changelog')
[node=linux-x86_64,opts=[-c opt],variation=] 
[node=linux-x86_64,opts=[-c opt],variation=] Use --sandbox_debug to see verbose messages from the sandbox
[node=linux-x86_64,opts=[-c opt],variation=] Traceback (most recent call last):
[node=linux-x86_64,opts=[-c opt],variation=]   File "scripts/packages/debian/convert_changelog.py", line 89, in <module>
[node=linux-x86_64,opts=[-c opt],variation=]     main(sys.argv[1], sys.argv[2], sys.argv[3])
[node=linux-x86_64,opts=[-c opt],variation=]   File "scripts/packages/debian/convert_changelog.py", line 49, in main
[node=linux-x86_64,opts=[-c opt],variation=]     parts[2], "(%Y-%m-%d)").strftime("%a, %d %b %Y %H:%M:%S +0100")
[node=linux-x86_64,opts=[-c opt],variation=]   File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
[node=linux-x86_64,opts=[-c opt],variation=]     (data_string, format))
[node=linux-x86_64,opts=[-c opt],variation=] ValueError: time data 'env[TMPDIR]' does not match format '(%Y-%m-%d)'
```

Console log is [here](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/1180/console).

From my experience with jobs started for release candidates: the first one for each RC always fails, and the replay always succeeds.

**Comment by philwo** [comment]
I propose to just get rid of CHANGELOG.md ...

**Comment by iirina** [comment]
FYI the release job for RC8 didn't fail! \o/
