### ISSUE TITLE
Bazel on arm (banana pi m64)

### ISSUE THREAD

**Issue by dntwrd** [bazelbuild/bazel#4578]
When installing the bazel on a banana-pi (os debian jessie), I had such a error. What to do?

`ERROR: /home/pi/tf/bazel-0.4.4/src/main/protobuf/BUILD:25:2: Java compilation in rule '//src/main/protobuf:extra_actions_base_java_proto' failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
        at com.sun.tools.javac.util.Log.localize(Log.java:673)
        at com.sun.tools.javac.util.Log.printLines(Log.java:485)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:156)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:59)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
        ... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 1147.204s, Critical Path: 1061.57s
`

**Comment by philwo** [comment]
It might be an issue with your local JDK or a bug in the Bazel version you're using.

Can you please provide the output of `bazel version` and `java -version`?

**Comment by koleto** [comment]
I have the same error here on Beaglebone Debian 8

ERROR: /home/debian/tf/bazel/src/main/protobuf/BUILD:25:2: Java compilation in rule '//src/main/protobuf:extra_actions_base_java_proto' failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:673)
	at com.sun.tools.javac.util.Log.printLines(Log.java:485)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:156)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 9092.833s, Critical Path: 6668.82s

**Comment by koleto** [comment]
debian@beaglebone:~/tf/bazel$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)

**Comment by philwo** [comment]
Sorry - your JDK is missing required files. Bazel can't do anything about this.
