### ISSUE TITLE
Bazel failed to desugar AutoValue for Android App

### ISSUE THREAD

**Issue by izzyleung** [bazelbuild/bazel#4630]
### Description of the problem:
The desugar tool failed to desugar AutoValue because it cannot find symbol `javax.lang.model.element.ExecutableElement`.

Output of running `bazel build :app` for the example at https://gist.github.com/izzyleung/a04dbd733151768b2d7218ddb5277d92:

```
INFO: Analysed target //:app (1 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @bazel_tools//tools/jdk:gen_platformclasspath [for host]:
Note: external/bazel_tools/tools/jdk/DumpPlatformClassPath.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ERROR: /private/*/**/external/autovalue/jar/BUILD.bazel:2:1: Desugaring external/autovalue/jar/auto-value-1.5.3.jar for Android failed (Exit 1)
Exception in thread "main" java.lang.TypeNotPresentException: Type javax.lang.model.element.ExecutableElement not present
	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:54)
	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
	at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:660)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:647)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:408)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1623)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)
Caused by: java.lang.ClassNotFoundException: Class javax.lang.model.element.ExecutableElement not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
	... 14 more
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.394s, Critical Path: 6.19s
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://gist.github.com/izzyleung/a04dbd733151768b2d7218ddb5277d92

### What operating system are you running Bazel on?

macOS High Sierra 10.13.3

### What's the output of `bazel info release`?

`release 0.10.0-homebrew`

**Comment by cushon** [comment]
@kevin1e100 FYI

It looks like desugar is running on the full implementation of the `AutoValue` annotation processor, which probably isn't something that should be included in Android apps.

I don't think there's a separate autovalue artifact with just the annotations. Does setting [`java_library.neverlink`](https://docs.bazel.build/versions/master/be/java.html#java_library.neverlink) on the `:autovalue` target in that example help?

**Comment by izzyleung** [comment]
@cushon Haven't tried that yet. Will report later when I have the chance to do so.

Also, https://github.com/google/copybara/blob/master/third_party/BUILD#L49 
Seems like CopyBara's author is not quite happy with the way AutoValue exposes its annotation either. 🤣

**Comment by cushon** [comment]
The maven artifact for auto uses `<scope>provided</scope>` to achieve something roughly equivalent to `neverlink`. I can't think of a reason to prefer a separate artifact. (The annotations aren't needed at runtime, so there's no reason to package them into apps either.)

**Comment by izzyleung** [comment]
`neverlink` solves the problem, thanks for the information.

Close the issue for now.

**Comment by pfn** [comment]
sadly, there's no examples of using auto_value with android and bazel anywhere, the gists in the original issue report are now gone, is there any way we can have those reinstated?

**Comment by izzyleung** [comment]
@pfn 

I will be posting that example shortly after this reply.

But in short, you only need to do 3 things.
- Declare the dependency of AutoValue from Maven, like this:
```python
maven_jar(
    name = "autovalue",
    artifact = "com.google.auto.value:auto-value:1.5.3",
)
```
- In either the `BUILD` file in `third_party` folder (Recommended), or in the `BUILD` where your code needs AutoValue:
```python
java_plugin(
    name = "autovalue_plugin",
    processor_class = "com.google.auto.value.processor.AutoValueProcessor",
    deps = [
        "@autovalue//jar",
    ],
)

java_library(
    name = "autovalue",
    neverlink = 1,
    exported_plugins = [
        ":autovalue_plugin",
    ],
    exports = [
        "@autovalue//jar",
    ],
)
```

**Comment by izzyleung** [comment]
@pfn This is the detailed example with Code:

https://gist.github.com/izzyleung/a1a1fab771e15d423a7d605a74620bda
