### ISSUE TITLE
Can't build - Decrementing remaining tasks counter resulted in impossible negative number

### ISSUE THREAD

**Issue by borisbrodski** [bazelbuild/bazel#4648]
### Description of the problem / feature request:

Building bazel 0.10.1 with OpenJDK 8 on ArchLinux (chrooted in Termux on ARM-Android)
results in "Decrementing remaining tasks counter resulted in impossible negative number"

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

    $ unzip bazel-dist'0.10.1.zip
    $ export JAVA_HOME="/path/to/openjdk8"
    $ ./compile.sh

### What operating system are you running Bazel on?

Linux localhost 4.4.13-12472670 #1 SMP PREEMPT Mon Jan 8 20:08:23 KST 2018 aarch64 GNU/Linux

chrooted in Termux on ARM-Android, Note8

### What's the output of `bazel info release`?

Can't build bazel to run it

###  Have you found anything relevant by searching the web?

Nothing

### Any other information, logs, or outputs that you want to share?

```
➜  bazel-0.10.1 ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
WARNING: /tmp/bazel_AI429ULr/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_AI429ULr/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions
Analyzing: target //src:bazel (12 packages loaded)
Analyzing: target //src:bazel (12 packages loaded)             Analyzing: target //src:bazel (13 packages loaded)             Analyzing: target //src:bazel (14 packages loaded)             Analyzing: target //src:bazel (16 packages loaded)             Analyzing: target //src:bazel (18 packages loaded)             Analyzing: target //src:bazel (24 packages loaded)             Analyzing: target //src:bazel (26 packages loaded)             Analyzing: target //src:bazel (38 packages loaded)             Analyzing: target //src:bazel (40 packages loaded)             Analyzing: target //src:bazel (42 packages loaded)             Analyzing: target //src:bazel (45 packages loaded)             Analyzing: target //src:bazel (50 packages loaded)    Analyzing: target //src:bazel (116 packages loaded)                                java.lang.IllegalStateException: Decrementing remaining tasks counter resulted in impossible negative number.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:501)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.decrementRemainingTasks(AbstractQueueVisitor.java:389)
                                                                                   Unhandled exception thrown during build; message: Task com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable@66c37406 rejected from java.util.concurrent.ThreadPoolExecutor@659024dd[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 40762]
at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:364)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
ERROR: bazel crash in async thread:
java.lang.IllegalStateException: Decrementing remaining tasks counter resulted in impossible negative number.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:501)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.decrementRemainingTasks(AbstractQueueVisitor.java:389)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.access$500(AbstractQueueVisitor.java:34)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:364)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Analyzing: target //src:bazel (116 packages loaded)

ERROR: Could not build Bazel
➜  bazel-0.10
```

I also had to increase jvm heap in scripts/bootstrap/compile.sh : -J-Xmx1200m

**Comment by philwo** [comment]
@borisbrodski Can you please let me know the output of `java -version` on your system?

**Comment by philwo** [comment]
1.8.0_111 is a pretty old build - can you easily upgrade to a newer one in your environment?

**Comment by borisbrodski** [comment]
I think, that is the most recent version on my system (ArchLinux ARM, aarch64)
I'm not sure, if I'm able to compile OpenJDK from source on a smart phone :/
If I don't find binaries, I will have to wait til the official update.

**Comment by philwo** [comment]
I'll close this, as it's not something Bazel can workaround. Sorry!
