### ISSUE TITLE
FreeBSD library errors on CI

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4674]
Seeing server startup crashes on the FreeBSD-11 node:
https://ci.bazel.build/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/511/pipeline/29

Error log:
```
[bazel-tests-node=freebsd-11] Running shell script
+ /home/ci/.bazel/custom/bazel_nightly/232/binary/bazel '--bazelrc=/home/ci/workspace/Global/bazel-tests-node=freebsd-11/bazel.bazelrc' version
Extracting Bazel installation...
..........INFO: Reading 'startup' options from /home/ci/workspace/Global/bazel-tests-node=freebsd-11/bazel.bazelrc: --max_idle_secs=600

Server crashed during startup. Now printing '/home/ci/.cache/bazel/_bazel_ci/8a0433955ba76571168afc0d19c575a6/server/jvm.out':
JNI initialization failed: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: Undefined symbol "_Z18portable_lgetxattrPKcS0_PvmPb".  Possibly your installation has been corrupted.
java.lang.UnsatisfiedLinkError: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: Undefined symbol "_Z18portable_lgetxattrPKcS0_PvmPb"
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
	at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1087)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1076)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1069)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:583)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:60)
ERROR: <unknown> crash in async thread:
java.lang.UnsatisfiedLinkError: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: /home/ci/.cache/bazel/_bazel_ci/install/3d78201a2c8e5d13640705d33645c4bb/_embedded_binaries/libunix.so: Undefined symbol "_Z18portable_lgetxattrPKcS0_PvmPb"
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
	at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
	at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1087)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1076)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1069)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:583)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:60)
script returned exit code 37
```

**Comment by katre** [comment]
See also this bazel-tests run: https://ci.bazel.build/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/2101/tests/

**Comment by katre** [comment]
Found the error: ad32f62952e2b6f8293a26ea5fd677e61975c9ff updated the portable_getxattr method but did not update the version for freebsd.

**Comment by aehlig** [comment]
Bisecting shows ad32f62952e2b6f8293a26ea5fd677e61975c9ff as the offending commit.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by katre** [comment]
I just sent a fix via gerrit: https://bazel-review.googlesource.com/c/bazel/+/41370
