### ISSUE TITLE
cc_test with tags=["no-cache"] gets cached, crashes Bazel if run with --nocache_test_results

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4680]
### Description of the problem / feature request:
Two bugs here:
* If I write a `cc_test` with `tags=["no-cache"]`, it gets cached. This violates the documented behavior at https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags, "`no-cache` keyword results in the action or test never being cached."
* If I force it to not cache using `--nocache_test_results`, Bazel crashes in the Skyframe evaluator.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
$ cat BUILD 
cc_test(
    name = "the_test",
    size = "small",
    srcs = ["the_test.cc"],
    tags = ["no-cache"],
)
$ cat the_test.cc 
int main() { return 0; }
```

Bug (1)
```
$ bazel test :the_test
.................................................................................
INFO: Analysed target //:the_test (11 packages loaded).
INFO: Found 1 test target...
Target //:the_test up-to-date:
  bazel-bin/the_test
INFO: Elapsed time: 5.030s, Critical Path: 0.41s
INFO: Build completed successfully, 6 total actions
//:the_test                                                              PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.

$ bazel test :the_test
INFO: Analysed target //:the_test (0 packages loaded).
INFO: Found 1 test target...
Target //:the_test up-to-date:
  bazel-bin/the_test
INFO: Elapsed time: 0.179s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
//:the_test                                                     (cached) PASSED in 0.1s

Executed 0 out of 1 test: 1 test passes.

```

Bug (2)
```
$ bazel test :the_test --nocache_test_results
INFO: Analysed target //:the_test (0 packages loaded).
INFO: Found 1 test target...
Target //:the_test up-to-date:
  bazel-bin/the_test
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://:the_test 351bc8c71a05436a8c8a3988ddd3e7da (178030459 924086365), actionIndex=8}' (requested by nodes 'the_test/test.cache_status //:the_test 351bc8c71a05436a8c8a3988ddd3e7da (1012673499 924086365)')
INFO: Elapsed time: 0.227s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://:the_test 351bc8c71a05436a8c8a3988ddd3e7da (178030459 924086365), actionIndex=8}' (requested by nodes 'the_test/test.cache_status //:the_test 351bc8c71a05436a8c8a3988ddd3e7da (1012673499 924086365)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: no-cache= and no-cache=
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:110)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:96)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:392)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:132)
	at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
	at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:678)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:867)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:810)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:111)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:678)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:635)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://:the_test 351bc8c71a05436a8c8a3988ddd3e7da (178030459 924086365), actionIndex=8}' (requested by nodes 'the_test/test.cache_status //:the_test 351bc8c71a05436a8c8a3988ddd3e7da (1012673499 924086365)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: no-cache= and no-cache=
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:110)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:96)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:392)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:132)
	at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
	at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:678)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:867)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:810)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:111)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:678)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:635)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	... 4 more
```

### What operating system are you running Bazel on?

I can reproduce both bugs on MacOS and Linux (x86-64).

### What's the output of `bazel info release`?

`release 0.10.1`

**Comment by dws-uber** [comment]
I see much the same thing with an `sh_test` tagged with `no-cache` using bazel-0.11.1.

**Comment by Globegitter** [comment]
Just running into this as well with the `jsonnet_to_json` rule. This seems to be the same issue: https://github.com/bazelbuild/bazel/issues/4343

**Comment by buchgr** [comment]
I found that the `no-cache` tag is not supported by most native rule implementations but should be supported by all skylark rules. 

We are definitely looking into fixing the issue for native rules too, but it's a huge effort and will take a while.

**Comment by AdamDorwart** [comment]
@buchgr Could you provide some guidance on how to write a work around skylark rule that doesn't cache test results? From what it seems it's impossible to designate test targets as `no-cache`.

Here's what I tried:
```
def _impl(ctx):
    exe = ctx.attr.target.files_to_run.executable
    ctx.actions.write(
        output = ctx.outputs.executable,
        content = "{path}".format(path=exe.short_path),
        is_executable = True,
    )

    runfiles = ctx.attr.target.default_runfiles.merge(
        ctx.runfiles(files = [exe]))
    return [DefaultInfo(runfiles = runfiles)]

_no_cache_test = rule(
    implementation = _impl,
    attrs = {
        "target": attr.label(),
    }, 
    test = True,
)

def no_cache_test(name, target):
    _no_cache_test(
        name=name,
        target=target,
        tags=['no-cache'],
    )
```

Is there something I'm missing in the Skylark rule API to designate no-cache for tests? I was assuming I needed to use `ctx.actions.run(execution_requirements=...)` but that doesn't seem to be applicable to test targets.

**Comment by ronstripe** [comment]
Seems like it is still broken for native genrules too.

genrule(
    name = "SimpleTest",
    srcs = [],
    outs = ["host.txt"],
    cmd = "(hostname; date) > $(OUTS)",
    tags = ["no-cache"]
)
