### ISSUE TITLE
NPE when running with --experimental_one_version_enforcement

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#4682]
### Description of the problem / feature request:

NPE when running:

$ bazel build --nocheck_visibility --experimental_one_version_enforcement=error //my:target

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

$ bazel build --nocheck_visibility --experimental_one_version_enforcement=error //my:target

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.10.1

### Any other information, logs, or outputs that you want to share?

Stack trace:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://my:target-redacted b23010847995f45ab4ebf1f7363f8718 (206086621 1631692719)' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
        at com.google.devtools.build.lib.collect.nestedset.NestedSetBuilder.add(NestedSetBuilder.java:61)
        at com.google.devtools.build.lib.rules.java.DeployArchiveBuilder.build(DeployArchiveBuilder.java:345)
        at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:406)
        at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:62)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:357)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:234)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:513)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:616)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:261)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://my:target-redacted b23010847995f45ab4ebf1f7363f8718 (206086621 1631692719)' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
        at com.google.devtools.build.lib.collect.nestedset.NestedSetBuilder.add(NestedSetBuilder.java:61)
        at com.google.devtools.build.lib.rules.java.DeployArchiveBuilder.build(DeployArchiveBuilder.java:345)
        at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:406)
        at com.google.devtools.build.lib.rules.java.JavaBinary.create(JavaBinary.java:62)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:357)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:234)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:513)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:616)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:261)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
        ... 4 more
```

**Comment by cushon** [comment]
@nglorioso FYI

**Comment by aehlig** [comment]
@cgrushko to route the issue appropriately

**Comment by cgrushko** [comment]
@aehlig what do you mean?

**Comment by mhlopko** [comment]
@ulfjack who is the most knowledgeable here?

**Comment by nglorioso** [comment]
Sorry folks! The feature is still under development (we're hashing out some issues with how strictly to enforce one version on java classes, for example: android resource files, and mechanisms to allow some sort of whitelisting process for codebases with existing violations who want to ease into enforcement).

Looks like I'm missing a few precondition checks like https://github.com/bazelbuild/bazel/blob/0bf1413833ad78784771fefb468f080a53640136/src/main/java/com/google/devtools/build/lib/rules/java/OneVersionCheckActionBuilder.java#L81 in other places in the Bazel codebase.
