### ISSUE TITLE
NPE building rules_docker java_image

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#4699]
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://java/example:image 026746fa55225ea1daf1ea0b9682764b (389158013 2066560586)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.java.JavaInfo.getTransitiveRuntimeJars(JavaInfo.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:297)
	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
```

**Comment by pcj** [comment]
Appears fixed in 0.11.0
