### ISSUE TITLE
Hard crash in Skyframe when passing invalid toolchain target to --android_crosstool_top with --fat_apk_cpu specified

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4707]
Using Bazel built from HEAD, if more than one CPU is specified in `--fat_apk_cpu` and an invalid toolchain target is specified for `--android_crosstool_top`, a hard crash happens:

```
$ gbazel build //examples/android/java/bazel:hello_world --fat_apk_cpu=arm64-v8a,x86_64 --android_crosstool_top=@androidndk//:invalid_toolchain                                     
Unhandled exception thrown during build; message: //examples/android/java/bazel:hello_world com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@91c4dcf1 false (23535
9719) -> ErrorInfo{exception=com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: no such target '@androidndk//:invalid_toolchain': target 'invalid_toolchai
n' not declared in package '' defined by /private/var/tmp/_bazel_jin/8b243e886b7f4e32fe3486711fb30699/external/androidndk/BUILD.bazel, rootCauses={com.google.devtools.build.lib.sky
frame.BuildConfigurationValue$Key@a4be2a01}, cycles=[], isCatastrophic=false, rootCauseOfException=com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@a4be2a01, isDi
rectlyTransient=false, isTransitivelyTransient=false}                                                                                                                               
INFO: Elapsed time: 0.368s                                                                                                                                                          
FAILED: Build did NOT complete successfully (0 packages loaded)                                                                                                                     
java.lang.IllegalStateException: //examples/android/java/bazel:hello_world com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@91c4dcf1 false (235359719) -> ErrorInf
o{exception=com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: no such target '@androidndk//:invalid_toolchain': target 'invalid_toolchain' not declared i
n package '' defined by /private/var/tmp/_bazel_jin/8b243e886b7f4e32fe3486711fb30699/external/androidndk/BUILD.bazel, rootCauses={com.google.devtools.build.lib.skyframe.BuildConfig
urationValue$Key@a4be2a01}, cycles=[], isCatastrophic=false, rootCauseOfException=com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@a4be2a01, isDirectlyTransient=f
alse, isTransitivelyTransient=false}                                                                                                                                                
        at com.google.common.base.Preconditions.checkState(Preconditions.java:817)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:427)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:287)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:589)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:592)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:238)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:385)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:352)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2$$Lambda$115/1181947865.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Expected normal crash with a single CPU value to `--fat_apk_cpu`:

```
$ gbazel build //examples/android/java/bazel:hello_world --fat_apk_cpu=arm64-v8a --android_crosstool_top=@androidndk//:invalid_toolchain 
....................
ERROR: no such target '@androidndk//:invalid_toolchain': target 'invalid_toolchain' not declared in package '' defined by /private/var/tmp/_bazel_jin/8b243e886b7f4e32fe3486711fb30699/external/androidndk/BUILD.bazel
ERROR: Analysis of target '//examples/android/java/bazel:hello_world' failed; build aborted: no such target '@androidndk//:invalid_toolchain': target 'invalid_toolchain' not declared in package '' defined by /private/var/tmp/_bazel_jin/8b243e886b7f4e32fe3486711fb30699/external/androidndk/BUILD.bazel
INFO: Elapsed time: 5.622s
FAILED: Build did NOT complete successfully (7 packages loaded)
```

**Comment by mpictor** [comment]
I'm seeing something that may be similar (matched a search for `com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key`) - however, I'm _not_ compiling for android.

In my case, I'd accidentally create a symlink loop in my toolchain. So an error is to be expected, but I don't think the exception was.

$ `bazel version`

```
Build label: 0.13.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 2 20:27:37 2018 (1525292857)
Build timestamp: 1525292857
Build timestamp as int: 1525292857
```

$ `bazel build --crosstool_top=//tools/ininbuild_compiler:toolchain --verbose_failures --cpu=k8 --local_resources 8192.0,6.0,0.8 hello`

```
ERROR: circular symlinks detected
[start of symlink cycle]
/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720/pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib
[end of symlink cycle]
Unhandled exception thrown during build; message: //:hello com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fa3ebe50 false (495739068) -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib], isDirectlyTransient=false, isTransitivelyTransient=false}
INFO: Elapsed time: 0.413s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
java.lang.IllegalStateException: //:hello com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fa3ebe50 false (495739068) -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib], isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:828)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:427)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:287)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:595)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:482)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:218)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: //:hello com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fa3ebe50 false (495739068) -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/mark/.cache/bazel/_bazel_mark/66ce7c19ef12345e0ebae28e4b0e335a/external/x86_64_i3linuxhost_linux_gnu_gcc_720]/[pub/tools/linuxhost/linux64/x86_64/x86_64-i3linuxhost-linux-gnu/sysroot/lib64/lib], isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:828)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:427)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:287)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:595)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:482)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:218)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
