### ISSUE TITLE
bazel_windows_example_test fails

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4723]
```
There were 2 failures:
1) testNoArgument(com.example.myproject.TestCustomGreeting)
org.junit.ComparisonFailure: expected:<Bye[] world> but was:<Bye[
] world>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.example.myproject.TestCustomGreeting.testNoArgument(TestCustomGreeting.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
2) testWithArgument(com.example.myproject.TestCustomGreeting)
org.junit.ComparisonFailure: expected:<Bye[] toto> but was:<Bye[
] toto>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.example.myproject.TestCustomGreeting.testWithArgument(TestCustomGreeting.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

FAILURES!!!
Tests run: 2,  Failures: 2
```

**Comment by laszlocsomor** [comment]
At which commit?

**Comment by buchgr** [comment]
At `HEAD`.

**Comment by laszlocsomor** [comment]
Do you have a link?
For the record, current HEAD is 78fa94a6183d417216638144a5e6d0598f1b1afd.
Test (`//src/test/shell/bazel:bazel_windows_example_test`) passes for me at this revision.

**Comment by buchgr** [comment]
https://buildkite.com/bazel/bazel-bazel-postsubmit/builds/333#bb0b9931-10b8-423d-94f1-9176e951d9e6

**Comment by laszlocsomor** [comment]
Thanks!

It looks like a line ending problem. I can repro the problem by editing `examples/java-native/src/main/resources/greeting.txt` to use CRLF instead of LF.

```
[msys] $ echo -e '\x42\x79\x65\x0d\x0a' > examples/java-native/src/main/resources/greeting.txt
---
[cmd.exe] > bazel test //examples/java-native/src/test/java/com/example/myproject:custom
```

Can you log into the VM that ran the test and hexdump this file?
Alternatively, if I send you a CL that adds some logging to the test, can we run it on Buildkite?

Git might be incorrectly configured on the VM. It should have `core.autocrlf = input`.

**Comment by buchgr** [comment]
yes can you just send a github pull request? it will run on buildkite.

**Comment by meteorcloudy** [comment]
I'm able to reproduce this error after changing the line ending of [greeting.txt](https://github.com/bazelbuild/bazel/blob/master/examples/java-native/src/main/resources/greeting.txt) to the Windows style (`\r\n`)

I suspect git did the conversion when cloning Bazel repo. @buchgr @philwo Can you confirm that?

We can fix this by trimming the content read from `greeting.txt`.

**Comment by buchgr** [comment]
Thanks Yun! I can confirm that it works now. Yay!
