### ISSUE TITLE
Remote Caching doesn't work on Windows

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4735]
We found that with Bazel 0.11.0 remote caching doesn't work on Windows and thus we also can't post links with tests results for Windows on our CI i.e. https://source.cloud.google.com/results/invocations/dc0510c0-afc6-42b3-8d2e-6d879dec526a/artifacts 

The error occurs when running `bazel build //src:bazel.exe` on Windows. We found the problem to be that the remote caching code tries to create a Path object to `/dev/null`, which doesn't work on Windows.

Here's the stack trace we got:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=//src:embedded_tools com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@35ab84ab false (1571273713), actionIndex=0}' (requested by nodes 'src/embedded_tools.zip //src:embedded_tools com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@35ab84ab false (1571273713)')
--
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalArgumentException: Cannot create Unix-style paths on Windows.
  | at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.getCachedChildPathInternalImpl(WindowsFileSystem.java:112)
  | at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory.access$300(WindowsFileSystem.java:85)
  | at com.google.devtools.build.lib.windows.WindowsFileSystem$WindowsPathFactory$1.getCachedChildPathInternal(WindowsFileSystem.java:100)
  | at com.google.devtools.build.lib.vfs.Path.getCachedChildPath(Path.java:305)
  | at com.google.devtools.build.lib.vfs.Path.getCanonicalPath(Path.java:688)
  | at com.google.devtools.build.lib.vfs.Path.getRelative(Path.java:724)
  | at com.google.devtools.build.lib.vfs.Path.getRelative(Path.java:747)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:315)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:329)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:271)
  | at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:95)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:90)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
  | at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
  | at com.google.devtools.build.lib.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:77)
  | at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:273)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:891)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:822)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:112)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:689)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:643)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:447)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
  | ... 4 more
```

**Comment by laszlocsomor** [comment]
I want to understand better why Bazel tries to create a Path object for /dev/null.

If there's a good reason, then we can support /dev/null on Windows, but we need to special-case it. On Unix, /dev/null is a lot like a file: you can stat it, it has an absolute path. On Windows, the null device is NUL, but it has no absolute path like c:\nul or something. So we can't really create a Path object for it.

If we do allow creating Unix-style paths on Windows for some whitelisted paths (only "/dev/null" for now), then we need to special-case some of its access methods too (e.g. stat'ing), since those wouldn't be backed by actual filesystem operations.

**Comment by dslomov** [comment]
for the record, `c:\nul` is a valid null file on Windows (any file named `nul` in any directory is a null file; so is `nul.java` or any other extension)

**Comment by laszlocsomor** [comment]
Thanks, I didn't know that!

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/a729b9b4c3d7844a7d44934bf3365f92633c0a60 seems to already fixed this issue, I don't see the error when using Bazel@HEAD

**Comment by meteorcloudy** [comment]
I think we can enable remote cache on Windows after 0.12.0 is released.

**Comment by meteorcloudy** [comment]
@buchgr Can we fix the link for Windows build in pull request presubmit?

**Comment by buchgr** [comment]
fixed
