### ISSUE TITLE
Bazel 0.11.0 regression building Android rules on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4736]
### Description of the problem / feature request:

Bazel 0.11.0 was released with a regression in `tools/android/aar_resources_extractor.py`, making it crash on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
C:\src\bazel-releases\0.11.0\dist>bazel build //examples/android/java/bazel:hello_world
INFO: Analysed target //examples/android/java/bazel:hello_world (24 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/odgg8mic/external/androidsdk/com.android.support/BUILD:99:1: AarResourcesExtractor external/androidsdk/com.android.support/_aar/unzipped/resources/animated-vector-drawable-25.0.0 failed (Exit 1): aar_resources_extractor.exe failed: error executing command
  cd C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/odgg8mic/execroot/io_bazel
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\tools\msys64\mingw64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\python_27_amd64\files;C:\Program Files\gWindows-Updater;C:\Program Files (x86)\Google\Cert Installer\;C:\Windows\mrmagoo;C:\gnubby\bin;C:\Windows\ccmsetup;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Bit9\Parity Agent;C:\gnubby\bin\;C:\Program Files (x86)\Google\gWindowsInformation;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;;C:\Program Files (x86)\Google\Cert Installer;C:\Windows\corpam;C:\Windows\CCM\;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Puppet Labs\Puppet\bin;C:\ProgramData\GooGet;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Google\gNetStatus;C:\Program Files (x86)\Corp SSH Helper;C:\src\bazel-releases\current;C:\python_27_amd64\files;C:\Users\laszlocsomor\AppData\Local\Microsoft\WindowsApps
  bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.exe --input_aar external/androidsdk/extras/android/m2repository/com/android/support/animated-vector-drawable/25.0.0/animated-vector-drawable-25.0.0.aar --output_res_dir bazel-out/android-armeabi-v7a-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/animated-vector-drawable-25.0.0 --output_assets_dir bazel-out/android-armeabi-v7a-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/assets/animated-vector-drawable-25.0.0
Traceback (most recent call last):
  File "c:\users\laszlo~1\appdata\local\temp\Bazel.runfiles_tlrhy4\runfiles\io_bazel\..\bazel_tools\tools\android\aar_resources_extractor.py", line 121, in <module>
    main()
  File "c:\users\laszlo~1\appdata\local\temp\Bazel.runfiles_tlrhy4\runfiles\io_bazel\..\bazel_tools\tools\android\aar_resources_extractor.py", line 115, in main
    ExtractResources(aar, FLAGS.output_res_dir)
  File "c:\users\laszlo~1\appdata\local\temp\Bazel.runfiles_tlrhy4\runfiles\io_bazel\..\bazel_tools\tools\android\aar_resources_extractor.py", line 51, in ExtractResources
    WriteFileWithJunctions(empty_xml_filename, b"<resources/>")
  File "c:\users\laszlo~1\appdata\local\temp\Bazel.runfiles_tlrhy4\runfiles\io_bazel\..\bazel_tools\tools\android\aar_resources_extractor.py", line 80, in WriteFileWithJunctions
    with open(filename, "wb") as openfile:
IOError: [Errno 2] No such file or directory: 'c:\\users\\laszlo~1\\appdata\\local\\temp\\tmpjvadk1\\j\\empty.xml'
Target //examples/android/java/bazel:hello_world failed to build
INFO: Elapsed time: 60.038s, Critical Path: 3.28s
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Windows 10, version 1607

### What's the output of `bazel info release`?

`release 0.11.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I'm building from the 0.11.0 distribution archive.

**Comment by laszlocsomor** [comment]
This was fixed at HEAD in https://github.com/bazelbuild/bazel/commit/fc98b44b6181fa4c3efd8613d887970629468d74.

**Comment by laszlocsomor** [comment]
@katre : Can we make a 0.11.1 patch release, cherrypicking https://github.com/bazelbuild/bazel/commit/fc98b44b6181fa4c3efd8613d887970629468d74 ?

**Comment by katre** [comment]
Makes sense, I'll start on that today.
