### ISSUE TITLE
remote: ManagedChannelImpl allocation trace for close without shutdown{,Now}

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#4803]
### Description of the problem / feature request:

io.grpc prints a warning about not shutting down connections with `shutdown()/shutdownNow()` and `awaitTermination()` at the end of a failing build. If it is running this at termination, there is certainly enough capacity to shut down these connections and limit this noise in the log files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a build with remote ex which does some work, that results in a failure, an interrupt is a fine way to fail.

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

bazel 0.11.0

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

```
180307 22:07:08.933:XT 22233 [io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.cleanQueue] *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-157 for target <remote-ex-host>:<port> was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:991)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:421)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:329)
        at com.google.devtools.build.lib.authandtls.GoogleAuthUtils.newChannel(GoogleAuthUtils.java:64)
        at com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:162)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:290)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by laszlocsomor** [comment]
@buchgr , @ola-rozenfeld , @nlopezgi : could you help me triage this please?

**Comment by ola-rozenfeld** [comment]
I'm having a problem reproducing this -- is the error printout from the server/jvm.out log, or the console? I tried to compile hello-world with HEAD with remote execution, and interrupt it in the middle of compile.

**Comment by buchgr** [comment]
I believe this has been fixed. We are now shutting down channels in the success and error case.
