### ISSUE TITLE
CI: //src/test/java/com/google/devtools/build/lib/rules/cpp:cpp-rules-tests broken on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4894]
https://buildkite.com/bazel/bazel-bazel/builds/862#601013f9-a3d3-45b8-99b0-ad910208cba7
Culprit: https://github.com/bazelbuild/bazel/commit/3c5a1098af0c5ae80d4e3b1fc52dd1fef6027d43

@mhlopko 

```
There were 3 failures:
1) testFeature(com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest)
java.lang.AssertionError: Not true that <
  feature {
    name: 'fully_static_link'
    enabled: true
    flag_set {
      action: 'c++-link-dynamic-library'
      action: 'c++-link-nodeps-dynamic-library'
      flag_group {
        flag: '-a'
        flag: '-b'
        flag: '-c'
      }
    }
  }> is equal to <
  feature {
    name: 'fully_static_link'
    enabled: true
    flag_set {
      action: 'c++-link-dynamic-library'
      action: 'c++-link-nodeps-dynamic-library'
      flag_group {
        flag: '-a'
        flag: '-b'
        flag: '-c'
      }
    }
  }>
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase$3.run(EvaluationTestCase.java:440)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$TestableDecorator.run(EvaluationTestCase.java:491)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$SkylarkTest.run(EvaluationTestCase.java:608)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.runTest(EvaluationTestCase.java:467)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.testStatement(EvaluationTestCase.java:304)
	at com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest.testFeature(SkylarkCcToolchainConfigureTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
2) testFeatureThoroughly(com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest)
java.lang.AssertionError: Not true that <
  feature {
    name: 'fully_static_link'
    enabled: true
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
        flag: '-a'
      }
    }
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
        iterate_over: 'a'
        flag: '-a'
      }
      flag_group {
        expand_if_all_available: 'a'
        expand_if_all_available: 'b'
        expand_if_none_available: 'a'
        expand_if_true: 'a'
        expand_if_true: 'b'
        expand_if_false: 'a'
        expand_if_equal { variable: 'a' value: 'val' }
        flag: '-c'
      }
      flag_group {
        expand_if_all_available: 'a'
        expand_if_all_available: 'b'
        expand_if_none_available: 'a'
        expand_if_true: 'a'
        expand_if_true: 'b'
        expand_if_false: 'a'
        expand_if_equal { variable: 'a' value: 'val' }
        iterate_over: 'a'
        flag: '-c'
      }
    }
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
      flag_group {
        flag: '-a'
      }
      }
    }
  }> is equal to <
  feature {
    name: 'fully_static_link'
    enabled: true
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
        flag: '-a'
      }
    }
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
        iterate_over: 'a'
        flag: '-a'
      }
      flag_group {
        expand_if_all_available: 'a'
        expand_if_all_available: 'b'
        expand_if_none_available: 'a'
        expand_if_true: 'a'
        expand_if_true: 'b'
        expand_if_false: 'a'
        expand_if_equal { variable: 'a' value: 'val' }
        flag: '-c'
      }
      flag_group {
        expand_if_all_available: 'a'
        expand_if_all_available: 'b'
        expand_if_none_available: 'a'
        expand_if_true: 'a'
        expand_if_true: 'b'
        expand_if_false: 'a'
        expand_if_equal { variable: 'a' value: 'val' }
        iterate_over: 'a'
        flag: '-c'
      }
    }
    flag_set {
      action: 'c++-link-dynamic-library'
      flag_group {
      flag_group {
        flag: '-a'
      }
      }
    }
  }>
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase$3.run(EvaluationTestCase.java:440)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$TestableDecorator.run(EvaluationTestCase.java:491)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$SkylarkTest.run(EvaluationTestCase.java:608)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.runTest(EvaluationTestCase.java:467)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.testStatement(EvaluationTestCase.java:304)
	at com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest.testFeatureThoroughly(SkylarkCcToolchainConfigureTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
3) testActionConfig(com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest)
java.lang.AssertionError: Not true that <
  action_config {
    config_name: 'c++-compile'
    action_name: 'c++-compile'
    tool {
      tool_path: '/usr/bin/gcc'
    }
  }> is equal to <
  action_config {
    config_name: 'c++-compile'
    action_name: 'c++-compile'
    tool {
      tool_path: '/usr/bin/gcc'
    }
  }>
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase$3.run(EvaluationTestCase.java:440)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$TestableDecorator.run(EvaluationTestCase.java:491)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$SkylarkTest.run(EvaluationTestCase.java:608)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.runTest(EvaluationTestCase.java:467)
	at com.google.devtools.build.lib.syntax.util.EvaluationTestCase$ModalTestCase.testStatement(EvaluationTestCase.java:304)
	at com.google.devtools.build.lib.rules.cpp.SkylarkCcToolchainConfigureTest.testActionConfig(SkylarkCcToolchainConfigureTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

FAILURES!!!
Tests run: 426,  Failures: 3

```

**Comment by mhlopko** [comment]
Rolled back in https://github.com/bazelbuild/bazel/commit/67549a752c2316234b19d7b50ea84a8ae80d3669

**Comment by meteorcloudy** [comment]
Not fixed yet, reopening

**Comment by meteorcloudy** [comment]
I believe there are two culprits. Another one is 
https://github.com/bazelbuild/bazel/commit/3dab964407a2f1e12feb439d8507079bc06cb769, responsible for
```
1) testSupportsDynamicLinkerCheckFeatures(com.google.devtools.build.lib.rules.cpp.CcToolchainTest)
com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: cc_toolchain_suite '@bazel_tools//tools/cpp:toolchain' does not contain a toolchain for CPU 'x64_windows' and compiler 'compiler_no_dyn_linker'
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:192)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:69)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:45)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:69)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:346)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-bazel/builds/882
@mhlopko You might want to rollback 3dab964 as well.

**Comment by mhlopko** [comment]
FTR, all is fixed after all rollbacks, leaving closed.
