### ISSUE TITLE
mobile-install --device without accompanying --adb_arg's causes exception.

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#4922]
```
$ bazel info release
release 0.11.1
$ bazel mobile-install --device device //:target
...........
Target //:target failed to build
Use --verbose_failures to see the command lines of failed build steps.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=//:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f8836abf false (531530361), actionIndex=41}' (requested by nodes 'target_files/mobile_install_args //:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f8836abf false (531530361)')
INFO: Elapsed time: 11.835s, Critical Path: 0.02s
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=//:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f8836abf false (531530361), actionIndex=41}' (requested by nodes 'target_files/mobile_install_args //:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f8836abf false (531530361)')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at com.google.devtools.build.lib.rules.android.WriteAdbArgsAction$1.writeOutputFile(WriteAdbArgsAction.java:151)
        ...
$ bazel mobile-install --adb_arg=-s --adb_arg=device --device device //:target
Updating 1 dex...
Application resources up-to-date
Updating 0 native libs...
Target //:target up-to-date:
  bazel-bin/target_files/full_deploy_marker
  bazel-bin/target_files/deploy_info_incremental.deployinfo.pb
INFO: Elapsed time: 0.751s, Critical Path: 0.44s
INFO: Build completed successfully, 3 total actions
```
This is caused by [`args.add` here](https://github.com/bazelbuild/bazel/blob/e666d3b88efb59f2a8f10b18882c9f13801508d9/src/main/java/com/google/devtools/build/lib/rules/android/WriteAdbArgsAction.java#L151). `adbArgs` is presumably an immutable list if there are no `--adb_arg`s supplied on the command line. I would fix this myself, but I'm blocked by [another bug](https://github.com/bazelbuild/bazel/issues/4374#issuecomment-376603148).

**Comment by aj-michael** [comment]
I can take a stab at this

**Comment by chaoren** [comment]
That is an impressive commit hash.
