### ISSUE TITLE
SimpleBlobStoreActionCache#downloadBlob should timeout when backend doesn't answer

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#4935]
We had a hanging `bazel build` job on CI this morning:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/180#94b43a46-ccf2-44f9-8b8f-2a7703a60111

I saved the stack trace from the machine:
```
# Connect to the worker.
gcloud compute ssh root@buildkite-ubuntu1604-dncf
# Get the PID of the bazel client (not server!).
ps axuf
# Run jstack on it.
jstack 27831
# This will trigger the server to dump a stack trace into its jvm.out.
# The path to the log is printed in Buildkite:
# Sending SIGQUIT to JVM process 27831 (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dccf24614aa202a669b9d141b873f6b4/server/jvm.out).
exit
gcloud compute scp root@buildkite-ubuntu-1604-dncf:/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dccf24614aa202a669b9d141b873f6b4/server/jvm.out ~/jvm.out
```

Here's the relevant output:
```
"skyframe-evaluator 7" #970 prio=5 os_prio=0 tid=0x00007f40e8019000 nid=0x7193 in Object.wait() [0x00007f423e0dd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:232)
	- locked <0x00000005bef7ee20> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:333)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.get(HttpBlobStore.java:186)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.get(HttpBlobStore.java:170)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.downloadBlob(SimpleBlobStoreActionCache.java:217)
	at com.google.devtools.build.lib.remote.AbstractRemoteActionCache.downloadFile(AbstractRemoteActionCache.java:231)
	at com.google.devtools.build.lib.remote.AbstractRemoteActionCache.download(AbstractRemoteActionCache.java:131)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:124)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:90)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:77)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:273)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:891)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:822)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:112)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:689)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:643)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:413)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:447)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Full log is attached: [jvm.txt](https://github.com/bazelbuild/bazel/files/1859311/jvm.txt)

**Comment by philwo** [comment]
I think it would be good if we could add a few flags to tune the exact behavior here, for example `--experimental_remote_cache_expected_throughput` (so that we can abort when a file hasn't been downloaded in a "reasonable" amount of time), `--experimental_remote_cache_blobstore_retry_backoff` (implement exponential backoff, possibly with a lower bound of 0.1s and an upper bound of 1s) and `--experimental_remote_cache_blobstore_retry_jitter` (in order not to overload GCS when doing many retries at the exact same millisecond).

OK, I'm kidding. But at least having some sort of timeout would help, I guess ;)

**Comment by GregBowyer** [comment]
This _might_ be related to #4944

**Comment by buchgr** [comment]
This has been fixed.
