### ISSUE TITLE
crosstool doesn't resolve relative paths

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#4937]
### Description of the problem / feature request:

My toolchain provides some supplemental implementations of POSIX and system headers within its own package, which is on top of another toolchain repo.

My CROSSTOOL has flags like the following:
 compiler_flag: "-isystem" compiler_flag: "relative/posix/include"

And my cc_toolchain has its files fields refer to a filegroup such as
```
filegroup(
    name = "everything",
    srcs = ["@my_toolchain//:all", "//relative/posix:headers"],
)
```

I want my compiler to try to resolve headers from my supplemental directories before trying the builtin includes. Unfortunately it doesn't know where my supplemental directories are. Am I doing this wrong, or does Bazel need to change?

### Feature requests: what underlying problem are you trying to solve with this feature?

The cxx_builtin_include_directory: field has a useful syntax to ground out my toolchain's paths via e.g., "%package(@my_toolchain)%//x86_64-elf/include" but there is no such interpretation for paths following compiler_flag: "-isystem". Is that perhaps the correct solution to making sense of my relative path? I'm still confused why the paths don't resolve even when building a target within the same workspace as my CROSSTOOL.

### What operating system are you running Bazel on?

Debian Linux

### What's the output of `bazel info release`?

> release 0.11.1, installed from the 0.11.1 release tarball.

### Any other information, logs, or outputs that you want to share?

Compiling with --copt=-E --copt=-v shows that GCC is "ignoring nonexistent directory "relative/posix/include""

**Comment by deeglaze** [comment]
I then tried adding `builtin_sysroot: "/opt/toolchain/x86_64-elf/"` and changed that prefix in my `cxx_builtin_include_directory:` path prefixes, and got an exception:
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '//project:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (
1839747017)' (requested by nodes '//project:dependency com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (1001295532)')                                         
INFO: Elapsed time: 10.717s                                                                                      
FAILED: Build did NOT complete successfully (14 packages loaded)                                                   
java.lang.RuntimeException: Unrecoverable error while evaluating node '//project:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (1839747017)' (request$
d by nodes '//project:dependency com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (1001295532)')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)          
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)           
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)           
        at java.lang.Thread.run(Thread.java:745)                                     
Caused by: com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$ExpansionException: Invalid toolchain configuration: Cannot expand variable 'sysroot': expected sequence, found string
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Variables$VariableValueAdapter.getSequenceValue(CcToolchainFeatures.java:962)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Variables.getSequenceVariable(CcToolchainFeatures.java:1724)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.expand(CcToolchainFeatures.java:421)             
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.expandCommandLine(CcToolchainFeatures.java:483)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.access$600(CcToolchainFeatures.java:369)           
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagSet.expandCommandLine(CcToolchainFeatures.java:555)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagSet.access$1100(CcToolchainFeatures.java:511)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Feature.expandCommandLine(CcToolchainFeatures.java:662)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Feature.access$2100(CcToolchainFeatures.java:618)                        
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FeatureConfiguration.getPerFeatureExpansions(CcToolchainFeatures.java:1839)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FeatureConfiguration.getPerFeatureExpansions(CcToolchainFeatures.java:1823)
        at com.google.devtools.build.lib.rules.cpp.CompileCommandLine.getCompilerOptions(CompileCommandLine.java:116)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getCompilerOptions(CppCompileAction.java:746)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getSystemIncludeDirs(CppCompileAction.java:603)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.verifyActionIncludePaths(CppCompileActionBuilder.java:482)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildAndVerify(CppCompileActionBuilder.java:422)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildOrThrowRuleError(CppCompileActionBuilder.java:280)
        at com.google.devtools.build.lib.rules.cpp.CppModel.createSourceAction(CppModel.java:1051)
        at com.google.devtools.build.lib.rules.cpp.CppModel.createCcCompileActions(CppModel.java:775)
        at com.google.devtools.build.lib.rules.cpp.CcLibraryHelper.compile(CcLibraryHelper.java:1043)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:275)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:95)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:53)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:364)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:240)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:517)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:699)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:278)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//project:target com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (1839747017)' (requested by nodes '//project:dependency com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@344c63c0 false (1001295532)')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$ExpansionException: Invalid toolchain configuration: Cannot expand variable 'sysroot': expected sequence, found string
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Variables$VariableValueAdapter.getSequenceValue(CcToolchainFeatures.java:962)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Variables.getSequenceVariable(CcToolchainFeatures.java:1724)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.expand(CcToolchainFeatures.java:421)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.expandCommandLine(CcToolchainFeatures.java:483)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagGroup.access$600(CcToolchainFeatures.java:369)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagSet.expandCommandLine(CcToolchainFeatures.java:555)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FlagSet.access$1100(CcToolchainFeatures.java:511)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Feature.expandCommandLine(CcToolchainFeatures.java:662)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$Feature.access$2100(CcToolchainFeatures.java:618)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FeatureConfiguration.getPerFeatureExpansions(CcToolchainFeatures.java:1839)
        at com.google.devtools.build.lib.rules.cpp.CcToolchainFeatures$FeatureConfiguration.getPerFeatureExpansions(CcToolchainFeatures.java:1823)
        at com.google.devtools.build.lib.rules.cpp.CompileCommandLine.getCompilerOptions(CompileCommandLine.java:116)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getCompilerOptions(CppCompileAction.java:746)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.getSystemIncludeDirs(CppCompileAction.java:603)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.verifyActionIncludePaths(CppCompileActionBuilder.java:482)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildAndVerify(CppCompileActionBuilder.java:422)
        at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildOrThrowRuleError(CppCompileActionBuilder.java:280)
        at com.google.devtools.build.lib.rules.cpp.CppModel.createSourceAction(CppModel.java:1051)
        at com.google.devtools.build.lib.rules.cpp.CppModel.createCcCompileActions(CppModel.java:775)
        at com.google.devtools.build.lib.rules.cpp.CcLibraryHelper.compile(CcLibraryHelper.java:1043)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:275)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:95)
        at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:53)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:364)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:240)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:517)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:699)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:278)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
        ... 4 more
```

**Comment by jin** [comment]
cc @mhlopko

**Comment by deeglaze** [comment]
I changed my CROSSTOOL to a template that is instantiated in my WORKSPACE via a repository rule that takes an absolute path to the installed toolchain. To get the absolute path to the current workspace that provides the supplemental system includes, I call repository_ctx.execute(["pwd"]) and then append /relative/posix/include for the generated -isystem compiler_flags.

Unfortunately this also doesn't work, because Bazel says the CROSSTOOL file doesn't exist for //relative/cpp:crosstool even though my repository_ctx.template writes to "relative/cpp/CROSSTOOL". To select my crosstool, I have an associated .bazelrc definition for a --config that sets --crosstool_top=@my_sdk//relative/cpp:crosstool. I would have to guess that Bazel is not resolving my WORKSPACE dependencies before trying to comprehend my --crosstool_top flag. How then do I generate my CROSSTOOL?

The call to `pwd` is an obvious hack that would likely break down when my SDK is someone else's dependency, so perhaps this isn't the problem to solve.

**Comment by shieldedexecution** [comment]
I managed to get most of the way there with a symlink to the absolute path of my toolchain and instantiating a CROSSTOOL.tpl. My toolchain relative paths work thanks to the symlink, but the compiler_flag: "-isystem" paths still need to know the absolute location of the workspace that refers to the supplemental headers. I can instantiate my CROSSTOOL.tpl to use the right path, but it requires users of my code to hardcode where they've placed my SDK. It's not so nice a solution.

**Comment by deeglaze** [comment]
I managed to get most of the way there with repository_ctx.symlink to the absolute path of my toolchain and instantiating a CROSSTOOL.tpl in that symlinked path. My toolchain relative paths work thanks to the symlink, but the compiler_flag: "-isystem" paths still need to know the absolute location of the workspace that refers to the supplemental headers. I can instantiate my CROSSTOOL.tpl to use the right path, but it requires users of my code to hardcode where they've placed my SDK. It's not so nice a solution.

**Comment by aiuto** [comment]
@deeglaze  Checking in. Is this still an issue, or have you made a move away from CROSSTOOL to the newer toolchain rules?  We are not likely to fix anything in CROSSTOOL, but perhaps this indicates a feature needed in toolchains.

**Comment by deeglaze** [comment]
We've just been sticking providing a full installation path using our repository rule. We are using a crosstool.bzl toolchain implementation now, but I don't see how to get around the need for full paths.
