### ISSUE TITLE
Reordering deps in a BUILD target causes Android app to crash

### ISSUE THREAD

**Issue by oferb** [bazelbuild/bazel#4953]
### Description of the problem / feature request:

Reordering deps in a BUILD target compiles successfully but causes Android app to crash on startup.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Working app on master:
https://github.com/hasadna/hasadna
To run:
bazel mobile-install //projects/noloan/app

Crashing app on branch dep_reorder_crash:
https://github.com/hasadna/hasadna/tree/dep_reorder_crash
This branch has just one commit to reorder deps and reproduce the crash:
https://github.com/hasadna/hasadna/commit/aeb5046d7def4c9f509403faaaf51c28992d1636
Same command to run:
bazel mobile-install //projects/noloan/app

### What's the output of `bazel info release`?
I've checked this on both versions:
release 0.10.0-2018-03-25 (@b4fcdc3)
development version (based on https://github.com/bazelbuild/bazel/tree/release-0.12.0 from March 29th)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
This is odd, I agree. I can try to clone & rebuild bazel if you want.

###  Have you found anything relevant by searching the web?
Nope.

### Any other information, logs, or outputs that you want to share?
This is the error from the app crash:
04-02 16:20:30.787 25486-25486/projects.noloan.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: projects.noloan.app, PID: 25486
                                                                     java.lang.NoSuchMethodError: No static method setFactory2(Landroid/view/LayoutInflater;Landroid/view/LayoutInflater$Factory2;)V in class Landroid/support/v4/view/LayoutInflaterCompat; or its super classes (declaration of 'android.support.v4.view.LayoutInflaterCompat' appears in /data/local/tmp/incrementaldeployment/projects.noloan.app/dex/incremental_classes1.dex)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.installViewFactory(AppCompatDelegateImplV9.java:1052)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                         at projects.noloan.app.MainActivity.onCreate(MainActivity.java:41)
                                                                         at android.app.Activity.performCreate(Activity.java:6999)
                                                                         at android.app.Activity.performCreate(Activity.java:6990)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

###  Anything else?
Let me know how best to help you reproduce the problem. I want to make it as easy as possible for you. You can reach me at oferb@ ;)

**Comment by oferb** [comment]
Thanks. Should repro now (after `git pull`).

We just added the option to use `java_proto_library` inside `android_binary`, by adding it here to `ALLOWED_DEPENDENCIES`:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L290

**Comment by cushon** [comment]
It still doesn't build for me:

```
ERROR: ./projects/noloan/app/BUILD:1:1: //projects/noloan/app:app: missing input file '//projects/noloan/app:assets/google-services.json'
```

**Comment by cushon** [comment]
Anyway, I suspect the problem is that the target is depending on two difference versions of the API, and it will see whichever appears first on the classpath. If you add `javacopts = ["-verbose"]` to the target, the log output will show which jar it's loading `android.support.v4.view.LayoutInflaterCompat` from.

**Comment by aj-michael** [comment]
It looks like you are depending on parts of the support library from 26.1.0 and 27.0.2. Do you really need both?

**Comment by oferb** [comment]
Indeed the issue was depending on multiple versions of the support libraries.
It was both here and through this remote `http_archive` dependency: https://github.com/google/startup-os/blob/master/android/BUILD#L10

Now it's fixed. Thanks!

I'm working to create a repo (called `startup-os`, see link) with examples of Android, Angular and gRPC on Bazel with an easy setup to Cloud. My thinking was that instead of forking the repo, people could depend on it using `http_archive` in WORKSPACE.
They would depend a specific "release" (a GitHub release tag) of `startup-os`, specified in the `http_archive` target.
Problem with that, is that once they upgrade versions of these libraries or they try to upgrade `startup-os`, they might get collisions. I wonder though if there's a good way to let them know which dependencies are colliding.
