### ISSUE TITLE
High Sierra 10.13.3 facing permission error when running "bazel run"

### ISSUE THREAD

**Issue by aviczhl2** [bazelbuild/bazel#4970]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

MAC OS X error when building bazel

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm a Mac os x user with High Sierra 10.13.3, and bazel 0.11.1. My installation is successful, with --user added in my installation. But when I begin running a simple program 

>bazel run //homework1/helloworld:main

which I've succeeded running in linux ubuntu bazel,
https://github.com/ponyai/PublicCourse/blob/master/homework1/helloworld/main.cc 

The following error message appears

>Unhandled exception thrown during build; message: >com.google.devtools.build.lib.unix.FilePermissionException: /dev/shm/bazel->sandbox.1ad8a41b925879c4f4030222b4f6f567 (Operation not permitted)
>INFO: Elapsed time: 0.786s
>FAILED: Build did NOT complete successfully (1 packages loaded)
>java.lang.IllegalStateException: com.google.devtools.build.lib.unix.FilePermissionException: >/dev/shm/bazel-sandbox.1ad8a41b925879c4f4030222b4f6f567 (Operation not permitted)
>	at com.google.devtools.build.lib.sandbox.SandboxModule.executorInit(SandboxModule.java:69)
>	at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:201)
>	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:189)
>	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:383)
>	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:350)
>	at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:129)
>	at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:168)
>	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:489)
>	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
>	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.devtools.build.lib.unix.FilePermissionException: /dev/shm/bazel-sandbox.1ad8a41b925879c4f4030222b4f6f567 (Operation not permitted)
	at com.google.devtools.build.lib.unix.NativePosixFiles.mkdirs(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createDirectoryAndParents(UnixFileSystem.java:323)
	at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:860)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:627)
	at com.google.devtools.build.lib.sandbox.SandboxModule.executorInit(SandboxModule.java:66)
	... 15 more
java.lang.IllegalStateException: com.google.devtools.build.lib.unix.FilePermissionException: /dev/shm/bazel-sandbox.1ad8a41b925879c4f4030222b4f6f567 (Operation not permitted)
	at com.google.devtools.build.lib.sandbox.SandboxModule.executorInit(SandboxModule.java:69)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:201)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:189)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:383)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:350)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:129)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:168)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:489)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.devtools.build.lib.unix.FilePermissionException: /dev/shm/bazel-sandbox.1ad8a41b925879c4f4030222b4f6f567 (Operation not permitted)
	at com.google.devtools.build.lib.unix.NativePosixFiles.mkdirs(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.createDirectoryAndParents(UnixFileSystem.java:323)
	at com.google.devtools.build.lib.vfs.Path.createDirectoryAndParents(Path.java:860)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.createDirectoryAndParents(FileSystemUtils.java:627)
	at com.google.devtools.build.lib.sandbox.SandboxModule.executorInit(SandboxModule.java:66)
	... 15 more

### What operating system are you running Bazel on?

> High Sierra 10.13.3 and bazel 0.11.1

### What's the output of `bazel info release`?

> release 0.11.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> https://github.com/ponyai/PublicCourse,aea9fbc1f535fdf6c2bbd73ea3c8e56a145e73ca,aea9fbc1f535fdf6c2bbd73ea3c8e56a145e73ca

###  Have you found anything relevant by searching the web?

> No similar problems. 

### Any other information, logs, or outputs that you want to share?
I tried to su root and run the program
> su root 
>bazel run //homework1/helloworld:main

The same "operation not permitted" problem still occurs.

**Comment by jin** [comment]
Is this still an issue with the latest Bazel?

**Comment by jmmv** [comment]
Please reopen when/if you can provide more information to show that this is still a problem with recent Bazel.
