### ISSUE TITLE
android_instrumentation_test test project failing in sandbox on Bazel CI

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4979]
This is the tracking bug for making the canonical [googlesamples/android-testing](https://github.com/googlesamples/android-testing#experimental-bazel-support) project pass on Bazel CI postsubmit. Setup instructions available here: https://gist.github.com/jin/6babcbe600d8ee24c732494118f4bb27

This is __not__ a release blocker for 0.12.0.

Latest run: https://buildkite.com/bazel/android-testing/builds/2

Issues: 

- [x] Requires Bazel 0.12.0 to pass. Tracking progress here: https://github.com/bazelbuild/bazel/issues/4582
- [x] WORKSPACE declaration for android_sdk_repository is invalid. Fix here: https://github.com/googlesamples/android-testing/pull/177.
- [x] [`--spawn_strategy=local` workaround](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/android-testing-postsubmit.yml#L8) required due to Xvfb lockfile bug. internal ref b/72871646 / blocked on on https://github.com/googlesamples/android-testing/pull/184
- [x] Non-deterministic Maven download failures. Fixed by [removing Maven dependency in gmaven_rules](https://github.com/bazelbuild/gmaven_rules/releases/tag/0.1.0).
- [ ] tests are timing out on API 19/21/22 https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/217#5c8577e8-7207-45af-96ec-cb7fc7170f92 / https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/217#d4a14dca-dd33-413b-a05a-04a648f1d9be

**Comment by jin** [comment]
cc @slinzner @ahumesky

**Comment by jin** [comment]
It's passing now: https://buildkite.com/bazel/android-testing/builds/5

**Comment by jin** [comment]
Looks like we're getting non-deterministic failures with the Maven downloads: 

```
[INFO] ------------------------------------------------------------------------
--
  | [INFO] BUILD FAILURE
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time: 5.795s
  | [INFO] Finished at: Fri Apr 13 06:30:02 UTC 2018
  | [INFO] Final Memory: 13M/1811M
  | [INFO] ------------------------------------------------------------------------
  | [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:get (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:2.10:get failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.10 or one of its dependencies could not be resolved: The following artifacts could not be resolved: backport-util-concurrent:backport-util-concurrent:jar:3.1, org.apache.maven.reporting:maven-reporting-impl:jar:2.2: Could not find artifact backport-util-concurrent:backport-util-concurrent:jar:3.1 -> [Help 1]
  | [ERROR]
  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
  | [ERROR]
  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
  |  
  | + mvn -s settings.xml org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dtransitive=false -Dartifact=com.android.support:support-compat:27.0.2:aar
  |  
  | Failed to fetch Maven dependency and referenced by '@com_android_support_support_vector_drawable_27_0_2//aar:aar'
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1e68441e02182c8fbba725ba9b4d7033/external/com_android_support_support_media_compat_27_0_2/aar/BUILD:4:1: no such package '@com_android_support_support_compat_27_0_2//aar': Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1e68441e02182c8fbba725ba9b4d7033/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 292
  | _maven_artifact_impl(ctx, "aar", _maven_aar_build_file_te...)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1e68441e02182c8fbba725ba9b4d7033/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 258, in _maven_artifact_impl
  | _mvn_download(ctx = ctx, paths = paths, fully_qual...)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1e68441e02182c8fbba725ba9b4d7033/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 211, in _mvn_download
  | fail(("%s\n%s\nFailed to fetch Maven ...)))
```

https://buildkite.com/bazel/android-testing/builds/7#bc05d42f-5b5c-45c0-ada4-4ec88d3cb5d0

**Comment by jin** [comment]
We're getting timeout failures for tests on API 19, 21 and 22.

14.04: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/217#5c8577e8-7207-45af-96ec-cb7fc7170f92
16.04 https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/217#d4a14dca-dd33-413b-a05a-04a648f1d9be

**Comment by jin** [comment]
Removed tests for 19, 21 and 22. It's now green again.
