### ISSUE TITLE
bazel-toolchains failing with 0.13.0rc1

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4992]
bazelbuild/bazel-toolchains repository doesn't have GitHub Issues support, so I'm reporting it here.

Same error on both 14.04 and 16.04 on Bazel 0.13.0rc1:

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e2c0be3fb717bbc0cca055cd48729424/external/bazel_toolchains/rules/docker_config.bzl:338:25: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e2c0be3fb717bbc0cca055cd48729424/external/bazel_toolchains/rules/docker_config.bzl", line 336
  | rule(attrs = (_container.image.attrs ...)}), <3 more arguments>)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e2c0be3fb717bbc0cca055cd48729424/external/bazel_toolchains/rules/docker_config.bzl", line 338, in rule
  | attr.string_list(["local_config_cc"])
  | Parameter 'default' is not positional, in method call string_list(list) of 'attr (a language module)'
```

14.04: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/188#913e4105-06de-4cf6-82c0-1f6290f82d54
16:04: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/188#4ca52218-5bde-44c1-bcda-22556ae7b461

@xingao267 @nlopezgi

**Comment by jin** [comment]
Looks like this can be fixed by adding the parameter name `default = ["local_config_cc"]`.
