### ISSUE TITLE
toolchains: crash on two `register_toolchain` calls with non-existent toolchains

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5000]
### Description of the problem / feature request:

Calling `register_toolchain` twice in the `WORKSPACE` file with non-existent toolchains, then trying to build a toolchain-using rule crashes Bazel built at HEAD.

Bazel 0.11.0 displays a proper error message about the missing toolchains.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In an empty directory, create:
-  `WORKSPACE` file:
    ```
    register_toolchains("//:bad1")
    register_toolchains("//:bad2")
    ```
-  `BUILD` file:
    ```
    load(":rules.bzl", "foo")
    foo(name = "foo")
    ```
-  `rules.bzl` file:
    ```
    def _impl(ctx):
      toolchain = ctx.toolchains["//dummy"]
      return []

    foo = rule(
      implementation = _impl,
      toolchains = ["//dummy"],
    )
    ```

Build with release Bazel:
```
  $ bazel build //:foo
..........
ERROR: While resolving toolchains for target //:foo: invalid registered toolchain '//:bad1': no such target '//:bad1': target 'bad1' not declared in package '' defined by /tmp/bzlcrash/BUILD
ERROR: Analysis of target '//:foo' failed; build aborted: invalid registered toolchain '//:bad1': no such target '//:bad1': target 'bad1' not declared in package '' defined by /tmp/bzlcrash/BUILD
INFO: Elapsed time: 1.584s
FAILED: Build did NOT complete successfully (4 packages loaded)
```

Build with head Bazel:
```
  $ ~/stuff/bazel/bazel-bin/src/bazel build //:foo
Starting local Bazel server and connecting to it...
.........
Unhandled exception thrown during build; message: //:foo com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@d31ebb7f false (1190687353) -> ErrorInfo{exception=com.google.devtools.build.lib.cmdline.TargetParsingException: no such target '//:bad2': target 'bad2' not declared in package '' defined by /tmp/bzlcrash/BUILD, rootCauses={//:bad2}, cycles=[], isCatastrophic=false, rootCauseOfException=//:bad2, isDirectlyTransient=false, isTransitivelyTransient=false}
INFO: Elapsed time: 1.533s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded)
java.lang.IllegalStateException: //:foo com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@d31ebb7f false (1190687353) -> ErrorInfo{exception=com.google.devtools.build.lib.cmdline.TargetParsingException: no such target '//:bad2': target 'bad2' not declared in package '' defined by /tmp/bzlcrash/BUILD, rootCauses={//:bad2}, cycles=[], isCatastrophic=false, rootCauseOfException=//:bad2, isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:828)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:427)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:287)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:595)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:482)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:218)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: //:foo com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@d31ebb7f false (1190687353) -> ErrorInfo{exception=com.google.devtools.build.lib.cmdline.TargetParsingException: no such target '//:bad2': target 'bad2' not declared in package '' defined by /tmp/bzlcrash/BUILD, rootCauses={//:bad2}, cycles=[], isCatastrophic=false, rootCauseOfException=//:bad2, isDirectlyTransient=false, isTransitivelyTransient=false}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:828)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:427)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:287)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:595)
        at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:482)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:218)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:349)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.11.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
  $ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
8626623106fc0f9f83781990f7c235074926d196
8626623106fc0f9f83781990f7c235074926d196
```

**Comment by laszlocsomor** [comment]
/cc @katre 

I'll start bisecting.

**Comment by katre** [comment]
I can probably name the change that introduced this. A fix shouldn't be
difficult.

**Comment by laszlocsomor** [comment]
Yes I did. Maybe relevant: I also used `--bazelrc=/dev/null`.

**Comment by katre** [comment]
Yes, that does it. I wonder what's different in my bazelrc? I'll check that, too.

**Comment by laszlocsomor** [comment]
And also, I made a `clean --expunge` before.
The curious thing is: if you query for the toolchain rules in advance, then Bazel seems to work fine (show a proper error).

**Comment by katre** [comment]
Okay, so it's caching the error and handling it in a different level. Definitely shows that my error handling needs a fix.

Thanks for the help reproducing this.

**Comment by katre** [comment]
Also implicated is `--keep_going`, which makes sense as that also changes how errors are handled and reported.
