### ISSUE TITLE
0.12.0 breaks current_java_toolchain

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#5011]
```python
# BUILD
load(":rules.bzl", "example_rule")

example_rule(name = "example")
```
```python
def _example_rule_impl(ctx):
    output = ctx.actions.declare_file("example.jar")
    ctx.actions.write(output, "")
    JavaInfo(actions = ctx.actions, java_toolchain = ctx.attr._java_toolchain, output_jar = output)

example_rule = rule(
    implementation = _example_rule_impl,
    attrs = {
        "_java_toolchain": attr.label(default = Label("@bazel_tools//tools/jdk:current_java_toolchain")),
    },
)
```

---

Bazel 0.11.1

```
$ bazel build :example
INFO: Analysed target //:example (1 packages loaded).
INFO: Found 1 target...
Target //:example up-to-date (nothing to build)
INFO: Elapsed time: 0.180s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

Bazel 0.12.0

```
$ bazel build :example
ERROR: /home/paul/test-bazel/BUILD:3:1: in example_rule rule //:example: 
Traceback (most recent call last):
	File "/home/paul/test-bazel/BUILD", line 3
		example_rule(name = 'example')
	File "/home/paul/test-bazel/rules.bzl", line 4, in _example_rule_impl
		JavaInfo(actions = ctx.actions, java_toolch..., ...)
source_jars, sources and exports cannot be simultaneous empty
ERROR: Analysis of target '//:example' failed; build aborted: Analysis of target '//:example' failed; build aborted
INFO: Elapsed time: 1.870s
FAILED: Build did NOT complete successfully (9 packages loaded)
```

**Comment by pauldraper** [comment]
Never mind. There was a breakage at `https://github.com/andyscott/rules_scala_annex/issues/34`, but this test case doesn't show it.
