### ISSUE TITLE
Android `public.xml` dimen resource crash

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#5077]
### Description of the problem / feature request:

When building an Android library that also provides a `public.xml` file, the resource merging action will crash with a NullPointerException with:
```
SEVERE: Unexpected
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.common.collect.SingletonImmutableSet.<init>(SingletonImmutableSet.java:45)
	at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:84)
	at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:166)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:269)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.chooseTypeIds(PlaceholderIdFieldInitializerBuilder.java:381)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:354)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:91)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:94)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:195)
	at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:236)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:97)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:188)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
I have constructed a repro project at https://github.com/menny/bazel_android_public_dimen
running `bazel build //:hello_world` will result in a Bazel crash.

### What operating system are you running Bazel on?
macoOS

### What's the output of `bazel info release`?

release 0.12.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I built it locally by fetching the `0.12` tag and calling `./compile.sh`

###  Have you found anything relevant by searching the web?

I have not seen any similar issues.

**Comment by jin** [comment]
cc @ahumesky @asteinb

**Comment by asteinb** [comment]
You're running into two issues here. First, our code seems to have a bug where it won't process a public XML file correctly if it has no entries. I'll put in a fix for that.

However, even with that fix, this sort of public XML file is a feature from Gradle that isn't currently supported in Bazel. Even if we handled it properly here (you could work around it here, for example, by adding an entry to the public.xml file), aapt wouldn't be able to deal with it.

**Comment by menny** [comment]
@asteinb will this comit be available in the 0.13 release?

**Comment by asteinb** [comment]
@ahumesky

**Comment by jin** [comment]
0.13.0 [baseline has been cut](https://github.com/bazelbuild/bazel/issues/4583#issuecomment-379332390), but I'll ask for this commit to be cherrypicked.
