### ISSUE TITLE
Bazel stack trace on error in analysis phase of a test

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#5129]
Example:

ERROR: /usr/local/google/tmp/itest.NYaLZq/Workflow/20180501-173705/scratch/test_tmpdirPnsHZ3/foundry_demo_tensorflow.834923636/tensorflow/contrib/lite/examples/android/BUILD:24:1: //tensorflow/contrib/lite/examples/android:tflite_demo: no such attribute 'manifest_merger' in 'android_binary' rule
ERROR: package contains errors: tensorflow/contrib/lite/examples/android
Loading: 201 packages loaded
    currently loading: tensorflow/core ... (28 packages)
WARNING: /usr/local/google/tmp/itest.NYaLZq/Workflow/20180501-173705/scratch/test_tmpdirPnsHZ3/_bazel_alphasource-foundry-guitar-role-acct/91b1f099a9b716bcf9505b1aa516ccf6/external/protobuf_archive/WORKSPACE:1: Workspace name in /usr/local/google/tmp/itest.NYaLZq/Workflow/20180501-173705/scratch/test_tmpdirPnsHZ3/_bazel_alphasource-foundry-guitar-role-acct/91b1f099a9b716bcf9505b1aa516ccf6/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
Remote logging disabled for testing, forcing abrupt shutdown.
com.google.devtools.build.lib.util.LoggingUtil#logToRemote: Invalid EvalException:
java.lang.InterruptedException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:485)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobFuture.get(UnixGlob.java:444)
	at com.google.devtools.build.lib.vfs.UnixGlob$GlobFuture.get(UnixGlob.java:432)
	at com.google.devtools.build.lib.packages.GlobCache.fromFuture(GlobCache.java:219)
	at com.google.devtools.build.lib.packages.GlobCache.getGlobUnsorted(GlobCache.java:161)
	at com.google.devtools.build.lib.packages.GlobCache.globUnsorted(GlobCache.java:248)
	at com.google.devtools.build.lib.packages.PackageFactory$LegacyGlobber.fetch(PackageFactory.java:305)
	at com.google.devtools.build.lib.skyframe.PackageFunction$SkyframeHybridGlobber$HybridToken.resolve(PackageFunction.java:1080)
	at com.google.devtools.build.lib.skyframe.PackageFunction$SkyframeHybridGlobber$HybridToken.access$600(PackageFunction.java:1046)
	at com.google.devtools.build.lib.skyframe.PackageFunction$SkyframeHybridGlobber.fetch(PackageFunction.java:1003)
	at com.google.devtools.build.lib.packages.PackageFactory.callGlob(PackageFactory.java:569)
	at com.google.devtools.build.lib.packages.SkylarkNativeModule.glob(SkylarkNativeModule.java:92)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:360)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.call(BuiltinCallable.java:130)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:462)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:440)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:839)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:823)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:118)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:193)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:210)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:177)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:193)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:462)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:440)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:854)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:826)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:180)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:225)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:198)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1659)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1298)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1234)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:476)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:347)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

The actual error was the "no such attribute 'manifest_merger' in 'android_binary' rule", but it's very hard to see from the stack trace, which is completely irrelevant. It seems that some assumptions on logging from a test have been violated here.

**Comment by benjaminp** [comment]
I suspect this was fixed by 4803293f39b82ca2ed07c123e30c3f808f16e1a8.

**Comment by mboes** [comment]
Hitting the same issue (identical top part  of the stack trace) when building Tensorflow 1.8.0. I don't understand how 4803293 would "resolve" this issue. From what I can tell from the code, that patch is simply rethrowing the original exception under a different form.

**Comment by c-parsons** [comment]
The linked-to patch should "change" the error and make it appear a little less gross -- the linked stack trace has "Invalid EvalException: java.lang.InterruptedException" -- we avoid trying to wrap an InterrutpedException into an EvalException now.

Whatever is throwing the underlying InterruptedException should not change as a result of the patch though, and will need to be debugged separately.

Are you still seeing "Invalid EvalException: java.lang.InterruptedException" after that patch?

**Comment by jin** [comment]
Is this still an issue?

**Comment by c-parsons** [comment]
Without further user feedback I'm going to assume the previously mentioned patch was sufficient. Feel free to reopen if this is not the case.
