### ISSUE TITLE
The system is out of resources. Consult the following stack trace for details. java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by zhangnd** [bazelbuild/bazel#5180]
platform: ubuntu-16.04.3(64 bit system)

bazel-0.11.1-dist.zip
```
$ sudo apt install openjdk-8-jdk
$ cd bazel-0.11.1-dist/
$ ./compile.sh
```
========================================================
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.util.List.prepend(List.java:228)
	at com.sun.tools.javac.code.Types$Subst.subst(Types.java:3021)
	at com.sun.tools.javac.code.Types.subst(Types.java:2974)
	at com.sun.tools.javac.code.Types$19.visitClassType(Types.java:2420)
	at com.sun.tools.javac.code.Types$19.visitClassType(Types.java:2388)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:786)
	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4652)
	at com.sun.tools.javac.code.Types.interfaces(Types.java:2385)
	at com.sun.tools.javac.code.Types$13.visitClassType(Types.java:1973)
	at com.sun.tools.javac.code.Types$13.visitClassType(Types.java:1955)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:786)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4571)
	at com.sun.tools.javac.code.Types.asSuper(Types.java:1952)
	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:921)
	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:844)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:786)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4571)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:840)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:804)
	at com.sun.tools.javac.code.Types.isSubtypeUncheckedInternal(Types.java:757)
	at com.sun.tools.javac.code.Types.isSubtypeUnchecked(Types.java:741)
	at com.sun.tools.javac.comp.Resolve$MethodCheckContext.compatible(Resolve.java:967)
	at com.sun.tools.javac.comp.Check.checkType(Check.java:546)
	at com.sun.tools.javac.comp.Attr$ResultInfo.check(Attr.java:482)
	at com.sun.tools.javac.comp.Resolve$MethodResultInfo.check(Resolve.java:1015)
	at com.sun.tools.javac.comp.Resolve$4.checkArg(Resolve.java:835)
	at com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:735)
	at com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:844)
	at com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:162)
	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:567)
	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1446)
	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1633)

**Comment by philwo** [comment]
Looks like you ran out of memory. Can you give some details about your environment? Did this run on physical hardware or in a VM or in a container? How much RAM and how many CPU cores do you have?

**Comment by aiuto** [comment]
Closing for lack of action. Please reopen if this is still an issue.
