### ISSUE TITLE
Cannot find requested resource bundle for locale en_US

### ISSUE THREAD

**Issue by sandipmgiri** [bazelbuild/bazel#5191]
### Description of the problem / feature request:
I'm trying to build `bazel 0.4.5` , however I'm getting error : `Cannot find requested resource bundle for locale en_US`.

```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
I could build `bazel-0.11.0` without any issue , however I need `bazel-0.4.5 `to build  `Tensorflow-1.2.1`.

Any helps appreciated .Thanks !

```
ERROR: /bazel/src/main/protobuf/BUILD:25:2: Java compilation in rule '//src/main/protobuf:extra_actions_base_java_proto' failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
        at com.sun.tools.javac.util.Log.localize(Log.java:673)
        at com.sun.tools.javac.util.Log.printLines(Log.java:485)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:156)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
        ... 15 more
Target //src:bazel failed to build
```

**Comment by sandipmgiri** [comment]
I have applied these changes - https://github.com/bazelbuild/bazel/commit/cc8e7166e29fee39d44e578cf98a06486084a6bd

However I'm getting below error -

```
1 warning
ERROR: /bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/BUILD:64:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/...' failed: bash failed: error executing command
  (cd /tmp/bazel_SPZt4HFS/out/execroot/bazel && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_java bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_java_list
mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_java
external/local_jdk/bin/javac -g -source 1.8 -target 1.8 -classpath '\''bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar:bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_invalid_command_line_exception.jar:third_party/auto/auto-value-1.2.jar:third_party/auto/auto-common-0.3.jar:third_party/error_prone/error_prone_annotation-2.0.18.jar:third_party/error_prone/error_prone_annotations-2.0.18.jar:third_party/error_prone/error_prone_check_api-2.0.18.jar:third_party/error_prone/error_prone_core-2.0.18.jar:third_party/guava/guava-21.0.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/pcollections/pcollections-2.1.2.jar:bazel-out/host/bin/third_party/checker_framework_dataflow/libbootstrap.jar:bazel-out/host/bin/third_party/jformatstring/libbootstrap.jar:third_party/protobuf/3.0.0/protobuf-java-3.0.0.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/java/jdk/langtools/javac-9-dev-r3297-4.jar:bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar'\'' -d bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output @bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar-2.params
external/local_jdk/bin/jar cf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar -C bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output .
touch bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libbootstrap_plugins.jar.build_output
'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/errorprone/ErrorPronePlugin.java:68: error: cannot find symbol
    BaseErrorProneJavaCompiler.setupMessageBundle(context);
                              ^
  symbol:   method setupMessageBundle(Context)
  location: class BaseErrorProneJavaCompiler
1 error
Target //src:bazel failed to build
INFO: Elapsed time: 92.532s, Critical Path: 66.53s

ERROR: Could not build Bazel
```

**Comment by sandipmgiri** [comment]
I could apply the changes successfully to bazel 0.5.4 - https://github.com/bazelbuild/bazel/commit/cc8e7166e29fee39d44e578cf98a06486084a6bd

TF1.2.1 is supported with bazel0.5.4.
