### ISSUE TITLE
Bazel crashes when a toolchain is given static_runtime_libs

### ISSUE THREAD

**Issue by dapirian** [bazelbuild/bazel#5239]
I have a pretty minimal C++ project that pulls in the standard pre-built clang package and uses it hermetically with bazel. See https://github.com/dapirian/m

If I change [my cc_toolchain](https://github.com/dapirian/m/blob/master/toolchain/BUILD#L36) to have `static_runtime_libs = ["@clang//:runtime_libs"],`, bazel crashes:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '//tests:test 02717e0744b2bdc4ce44def00505ead9 false (943067300)' (requested by nodes )
INFO: Elapsed time: 4.283s
INFO: 0 processes.
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests:test 02717e0744b2bdc4ce44def00505ead9 false (943067300)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:488)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs$SimpleLinkerInput.<init>(LinkerInputs.java:47)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs.simpleLinkerInput(LinkerInputs.java:451)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs.lambda$simpleLinkerInputs$0(LinkerInputs.java:442)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:788)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:244)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:230)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:940)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:397)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:36)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:25)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:379)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:250)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:517)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:742)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:302)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests:test 02717e0744b2bdc4ce44def00505ead9 false (943067300)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:488)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs$SimpleLinkerInput.<init>(LinkerInputs.java:47)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs.simpleLinkerInput(LinkerInputs.java:451)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs.lambda$simpleLinkerInputs$0(LinkerInputs.java:442)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:788)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:244)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:230)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:940)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:397)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:36)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:25)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:379)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:250)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:517)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:742)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:302)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
	... 4 more
```

I'm not 100% sure what the purpose of `static_runtime_libs` is (there's no documentation), but I suspect it's the runtime libs to supply to a `linkstatic = 1` `cc_binary` or `cc_test`? I'd love to know for sure, but no matter what it is, bazel shouldn't crash.

**Comment by dapirian** [comment]
Update - this only happens if I give `so`s to static_runtime_libs. It accepts `.a`s, but "runtime libs" implies libs that should be present in runtime, so super confusing. As far as I can tell there's no way to make a `linkstatic = 1` cc_binary to dynamic link the standard library, which is a problem.

**Comment by hlopko** [comment]
Hi David,

I fully agree things are confusing here. I added some [docs](https://source.bazel.build/bazel/+/84d1a66edadd1657f23c7f14edac6610172438ee:src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainRule.java) to `cc_toolchain` (they will show up on the bazel.build website with Bazel 0.22 release) and I have a [change in flight](https://bazel-review.googlesource.com/c/bazel/+/85230/9/site/docs/crosstool-reference.md) for adding docs to [crosstool reference](https://docs.bazel.build/versions/master/crosstool-reference.html#well-known-features). 

Use of word 'runtime' in this context means C++ runtime library, e.g. `libstdc++.a` or `libstdc++.so`. The whole feature is to link C++ runtime library statically, hence `static_runtime_lib`. `dynamic_runtime_lib` is there only so C++ tests that are linked dynamically link C++ runtime library dynamically as well. With this information, is this issue still valid?
