### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:actions_test is flaky

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#5242]
Logs: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/248#26555ede-d3f4-44e0-bb84-a90d3fe83a02 and https://storage.googleapis.com/bazel-buildkite-artifacts/26555ede-d3f4-44e0-bb84-a90d3fe83a02/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cactions_test%5Cattempt_1.log

Error message:
```
1) testCalculationConcurrency(com.google.devtools.build.lib.actions.DigestUtilsTest)
java.lang.AssertionError: Not true that <0> is equal to <1>
	at com.google.devtools.build.lib.actions.DigestUtilsTest.assertDigestCalculationConcurrency(DigestUtilsTest.java:103)
	at com.google.devtools.build.lib.actions.DigestUtilsTest.testCalculationConcurrency(DigestUtilsTest.java:122)
```

**Comment by laszlocsomor** [comment]
Bisecting.

**Comment by laszlocsomor** [comment]
It's flaky. :(
```
//src/test/java/com/google/devtools/build/lib:actions_test                FLAKY, failed in 3 out of 4 in 7.2s
```

**Comment by laszlocsomor** [comment]
Also just flaked on Linux.

**Comment by laszlocsomor** [comment]
Flake on Linux repro'd again, happens at HEAD too:

```
  $ git rev-parse HEAD
c1bada0b14b5bb8def73b23d29c9139a72224a14

  $ git rev-parse master
c1bada0b14b5bb8def73b23d29c9139a72224a14

  $ bazel test //src/test/java/com/google/devtools/build/lib:actions_test --runs_per_test=100 --notest_keep_going -t-
INFO: Analysed target //src/test/java/com/google/devtools/build/lib:actions_test (0 packages loaded).
INFO: Found 1 test target...
FAIL: //src/test/java/com/google/devtools/build/lib:actions_test (run 20 of 100) (see /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/ad281b85fff6d7688ca089d55ea2d6f2/execroot/io_bazel/bazel-out/k8-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/actions_test/run_20_of_100/test.log)
ERROR: /usr/local/google/home/laszlocsomor/stuff/bazel2/src/test/java/com/google/devtools/build/lib/BUILD:523:1:  failed: Test failed: aborting
Target //src/test/java/com/google/devtools/build/lib:actions_test up-to-date:
  bazel-bin/src/test/java/com/google/devtools/build/lib/actions_test.jar
  bazel-bin/src/test/java/com/google/devtools/build/lib/actions_test
ERROR: Test failed: aborting
INFO: Elapsed time: 57.483s, Critical Path: 55.66s
INFO: 243 processes: 125 linux-sandbox, 118 worker.
INFO: Build completed successfully, 256 total actions
//src/test/java/com/google/devtools/build/lib:actions_test            NO STATUS in 12.8s
  Stats over 11 runs: max = 12.8s, min = 11.9s, avg = 12.3s, dev = 0.3s
  /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/ad281b85fff6d7688ca089d55ea2d6f2/execroot/io_bazel/bazel-out/k8-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/actions_test/run_20_of_100/test.log

Executed 1 out of 1 test: 1 was skipped.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

**Comment by laszlocsomor** [comment]
Bisected again using:
```
bazel test //src/test/java/com/google/devtools/build/lib:actions_test --runs_per_test=100 --notest_keep_going -t-
```

Culprit seems to be https://github.com/bazelbuild/bazel/commit/724bdbfa47576c67eeec5c74d594203fe05188c7.

**Comment by laszlocsomor** [comment]
Rolling back the culprit commit.
