### ISSUE TITLE
Windows C++ installation could be more user-friendly

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#5272]
It took me a while to figure out how to get Bazel on Windows to use MSVC. I only installed the VS Build tools, to the default location. I had to set this to make it work:
```
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
```

https://docs.bazel.build/versions/master/windows.html#using says:
```
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
```

Error message I got with the wrong setting:
```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/cc_configure.bzl", line 36
                configure_windows_toolchain(repository_ctx)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 304, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 234, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 208, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/VC/Tools/MSVC (No such file or directory)
```

Here's what I got when I used tab completion to set BAZEL_VC:
```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/cc_configure.bzl", line 36
                configure_windows_toolchain(repository_ctx)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 304, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 230, in _find_missing_vc_tools
                _find_vcvarsall_bat_script(repository_ctx, vc_path)
        File "C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 179, in _find_vcvarsall_bat_script
                repository_ctx.path(vcvarsall).exists
Illegal char <"> at index 70: C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/external/local_config_cc/"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC"/VC/Auxiliary/Build/VCVARSALL.BAT
```

**Comment by ulfjack** [comment]
Oh, I see; one line says BAZEL_VC the other says BAZEL_VS. *sigh*
