### ISSUE TITLE
Error prone integration: CNFE: org.checkerframework.javacutil.AnnotationProvider

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#5278]
Apply this patch to activate all EP warnings: [1] on Bazel HEAD (e01bca531f332ffd188ebb38222a57d6f55a11b3), and try to build Gerrit from HEAD (d2d204557469f9183f00b317431967aee44a6fcc): 

```
$ bazel build :headless
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
..........
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:98:7: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.7.0.
INFO: Analysed target //:headless (207 packages loaded).
INFO: Found 1 target...
INFO: From Building java/com/google/gerrit/extensions/libclient-class.jar (23 source files):
java/com/google/gerrit/extensions/client/ProjectWatchInfo.java:61: warning: [OrphanedFormatString] String literal contains format specifiers, but is not passed to a format method
      b.append("%filter=").append(filter);
               ^
    (see http://errorprone.info/bugpattern/OrphanedFormatString)
ERROR: /home/davido/projects/gerrit2/proto/BUILD:1:1: Building proto/libcache_proto-speed.jar (1 source jar) failed (Exit 1)
/com/google/gerrit/server/cache/proto/Cache.java:141: warning: [MissingOverride] getPrior implements method in ChangeKindKeyProtoOrBuilder; expected @Override
    public com.google.protobuf.ByteString getPrior() {
                                          ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public com.google.protobuf.ByteString getPrior() {'?
/com/google/gerrit/server/cache/proto/Cache.java:150: warning: [MissingOverride] getNext implements method in ChangeKindKeyProtoOrBuilder; expected @Override
    public com.google.protobuf.ByteString getNext() {
                                          ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public com.google.protobuf.ByteString getNext() {'?
/com/google/gerrit/server/cache/proto/Cache.java:159: warning: [MissingOverride] getStrategyName implements method in ChangeKindKeyProtoOrBuilder; expected @Override
    public java.lang.String getStrategyName() {
                            ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public java.lang.String getStrategyName() {'?
/com/google/gerrit/server/cache/proto/Cache.java:175: warning: [MissingOverride] getStrategyNameBytes implements method in ChangeKindKeyProtoOrBuilder; expected @Override
        getStrategyNameBytes() {
        ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public com.google.protobuf.ByteString'?
/com/google/gerrit/server/cache/proto/Cache.java:355: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
      return this == DEFAULT_INSTANCE
                  ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.1
     BugPattern: ReferenceEquality
     Stack Trace:
     com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/checkerframework/javacutil/AnnotationProvider
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
  	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
  	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
  	at com.google.errorprone.dataflow.DataFlow.methodDataflow(DataFlow.java:167)
  	at com.google.errorprone.dataflow.DataFlow.expressionDataflow(DataFlow.java:226)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessAnalysis.getNullness(NullnessAnalysis.java:59)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.getNullness(AbstractReferenceEquality.java:189)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.addFixes(AbstractReferenceEquality.java:110)
  	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.matchBinary(AbstractReferenceEquality.java:85)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:506)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.visitConditionalExpression(TreeScanner.java:403)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:633)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1391)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:1018)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1548)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:527)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:895)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:602)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:110)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:112)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:110)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:121)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileSources(SimpleJavaLibraryBuilder.java:49)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:124)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:132)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
  Caused by: java.lang.NoClassDefFoundError: org/checkerframework/javacutil/AnnotationProvider
  	at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:120)
  	at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:94)
  	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
  	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
  	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
  	... 92 more
  Caused by: java.lang.ClassNotFoundException: org.checkerframework.javacutil.AnnotationProvider
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 98 more
Target //:headless failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 76.503s, Critical Path: 27.18s
INFO: 284 processes: 271 linux-sandbox, 13 worker.
FAILED: Build did NOT complete successfully
```

[1] https://bazel-review.googlesource.com/c/bazel/+/7891

**Comment by davido** [comment]
Duplicate of: #5134 and is apparently fixed in https://github.com/bazelbuild/bazel/pull/5156.
