### ISSUE TITLE
Empty test.xml is left behind, if the JUnit runner throws an exception during applying filters when --test_filter is used

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/bazel#5289]
If an exception is thrown during reading of a JUnit `Description` (during application of filtering or building the test model), an empty (0-bytes) `test.xml` file will remain on disk.

In our particular case, we're using the Specs2 library for tests in Scala, and it may throw exceptions in the implementation of its `getDescription` method.
This happens, for example, if an exception is thrown during static initialization of a test, e.g.
```
class MyTest extends Specification {
  val myVal: String = { throw new Exception("Boom") }
}
```
In which case, it will be caught internally by specs2, and propagated as a `UserException` back to the runner.
```
    ...
    at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilter(JUnit4Runner.java:159)
    at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilters(JUnit4Runner.java:207)
    at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:95)
    at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
    at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
```

While bazel gracefully terminates from this exception, the empty test.xml will still remain behind. 

We have some post-build tools that accumulate test.xml results, and we had to harden them against reading empty files, but perhaps this issue could be solved in bazel directly (i.e. not producing a file at all, unless successful?)

I sent a [PR to rules_scala](https://github.com/bazelbuild/rules_scala/pull/500) to gracefully handle the exception from specs2 in particular, but perhaps there should be a more general solution for possible exceptions thrown by the underlying runner?

**Comment by hmemcpy** [comment]
I managed to work around the problem by eliminating the 0-byte test.xml, by creating a lazy OutputStream for the xml (see #6000). This ensures the file will only be created if there was actual content written to it by the test model.

This works even better than I'd hoped, since the calling worker strategy will create a test.xml from the produced test.log, which actually solves all issues!
