### ISSUE TITLE
Unrecoverable error while evaluating node 'ActionLookupData{...}' breakages in nightly

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5296]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/259

Same breakage affecting rules_go and rules_nodejs:

rules_go, 14.04:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//tests/core/go_path:go_path_test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false, actionIndex=9}' (requested by nodes 'tests/core/go_path/go_path_test/test.cache_status //tests/core/go_path:go_path_test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false')
--
  | INFO: Elapsed time: 1.780s, Critical Path: 0.89s
  | INFO: 77 processes: 8 remote cache hit, 69 linux-sandbox.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//tests/core/go_path:go_path_test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false, actionIndex=9}' (requested by nodes 'tests/core/go_path/go_path_test/test.cache_status //tests/core/go_path:go_path_test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/k8-fastbuild/bin]tests/core/go_path/copy_path
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
...
```

rules_go, 16.04:

```

INFO: Elapsed time: 1.238s, Critical Path: 0.39s
--
  | INFO: 24 processes: 6 remote cache hit, 18 linux-sandbox.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//tests/core/stdlib:buildid_test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false, actionIndex=9}' (requested by nodes 'tests/core/stdlib/buildid_test/test.cache_status //tests/core/stdlib:buildid_test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/pkg
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
...
```

rules_go, macOS:

```

Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:vet BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false, actionIndex=5}' (requested by nodes 'vet/test.cache_status //:vet BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false')
--
  | INFO: Elapsed time: 1.733s, Critical Path: 0.84s
  | INFO: 5 processes: 1 remote cache hit, 4 darwin-sandbox.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:vet BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false, actionIndex=5}' (requested by nodes 'vet/test.cache_status //:vet BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]all_srcs
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
...
```

rules_nodejs, 14.04:

```

Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false')
--
  | INFO: Elapsed time: 0.400s, Critical Path: 0.04s
  | INFO: 0 processes.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[fdb3894e6ebca3ad1d50fc951f8e9440] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/k8-fastbuild/bin]internal/npm_package/test/test_pkg
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
...
```

rules_nodejs, 16.04:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false')
--
  | INFO: Elapsed time: 0.451s, Critical Path: 0.04s
  | INFO: 0 processes.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[31392ffa42da112162e5d2e8e2fdedd1] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/k8-fastbuild/bin]internal/npm_package/test/test_pkg
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
```

rules_nodejs, macOS:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false')
--
  | INFO: Elapsed time: 0.416s, Critical Path: 0.04s
  | INFO: 0 processes.
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//internal/npm_package/test:test BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false, actionIndex=7}' (requested by nodes 'internal/npm_package/test/test/test.cache_status //internal/npm_package/test:test BuildConfigurationValue.Key[e0c2abb18e3342ac3d3a2f8207241cc4] false')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.IllegalStateException: null for File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]internal/npm_package/test/test_pkg
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
  | at com.google.devtools.build.lib.skyframe.PerActionFileCache.getMetadata(PerActionFileCache.java:53)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$DelegatingPairFileCache.getMetadata(SkyframeActionExecutor.java:1272)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:324)
  | at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:344)
...
```

**Comment by jin** [comment]
The error occurred in the nightly that ran at 2am on 29 May (NY time), but didn't occur in the [previous nightly](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/257).

The commit that introduced this is between https://github.com/bazelbuild/bazel/commit/abf74a135750ca1e8b415632975c738a8edc4d01 and https://github.com/bazelbuild/bazel/commit/e01bca531f332ffd188ebb38222a57d6f55a11b3

**Comment by jin** [comment]
Run before https://github.com/bazelbuild/bazel/commit/c868c47eaa14304fc223b93534c641c04d47d830: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/265 (tests fail)

Run at https://github.com/bazelbuild/bazel/commit/c868c47eaa14304fc223b93534c641c04d47d830: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/264 (tests pass)

@benjaminp please let me know if you have a fix for this, if not we'll need to roll it back.

**Comment by benjaminp** [comment]
Ah, yes, I think I know what's going on. Working on a patch now...

**Comment by jin** [comment]
Perfect!

**Comment by ob** [comment]
I'm seeing this with HEAD while building an iOS application with rules_apple 0.7.0, rules_swift at 7bbcf9584613169cda709b9c217f5ac29cc5a089 and a remote-cache. It's pretty reproducible. Any ideas what could be going on? That `Learning` rule an `ios_application` rule.

```
Target //:Learning failed to build
Use --verbose_failures to see the command lines of failed build steps.
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:Learning BuildConfigurationValue.Key[60edc76b6e51ae9c94f8292c73a6cd21] false, actionIndex=344}' (requested by nodes 'File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]Learning.unprocessed.zip')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:495)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Encountered two inputs with the same path.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:325)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:285)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:994)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:923)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:471)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
	... 4 more

INFO: Elapsed time: 17.489s, Critical Path: 11.81s
INFO: 4 processes: 4 remote cache hit.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:Learning BuildConfigurationValue.Key[60edc76b6e51ae9c94f8292c73a6cd21] false, actionIndex=344}' (requested by nodes 'File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]Learning.unprocessed.zip')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:495)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Encountered two inputs with the same path.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:325)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:285)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:994)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:923)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:471)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:Learning BuildConfigurationValue.Key[60edc76b6e51ae9c94f8292c73a6cd21] false, actionIndex=344}' (requested by nodes 'File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]Learning.unprocessed.zip')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:495)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Encountered two inputs with the same path.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:325)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:348)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:285)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:101)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:994)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:923)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:471)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
@ob could you please open up a new issue for this and reference this PR in it?

**Comment by ob** [comment]
@jin done.
