### ISSUE TITLE
Windows: bazel query "//external:*" crashing [blocking: release 0.15.0]

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5300]
### Description of the problem / feature request:

Using Bazel built at HEAD crashes on `query "//external:*"`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build Bazel at a5ecd8132d3742831eda9730614270604294e410, then use that binary to run `devbazel.exe query "//external:*"`.

Output:

```
C:\src\bazel>C:/tmp1/o6hbs7n0/execroot/io_bazel/bazel-out/x64_windows-fastbuild/bin/src/bazel.exe query "//external:*"
Starting local Bazel server and connecting to it...
...........................
java.lang.RuntimeException: Unrecoverable error while evaluating node '//external:*' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 14: C:\work\bazel\*
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.io.File.toPath(File.java:2234)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:200)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:105)
        at com.google.devtools.build.lib.vfs.FileSystem.statNullable(FileSystem.java:495)
        at com.google.devtools.build.lib.vfs.AbstractFileSystemWithCustomStat.isDirectory(AbstractFileSystemWithCustomStat.java:51)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.isDirectory(WindowsFileSystem.java:170)
        at com.google.devtools.build.lib.vfs.Path.isDirectory(Path.java:452)
        at com.google.devtools.build.lib.packages.Package.getTarget(Package.java:507)
        at com.google.devtools.build.lib.pkgcache.AbstractRecursivePackageProvider.getTarget(AbstractRecursivePackageProvider.java:50)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetOrNull(RecursivePackageProviderBackedTargetPatternResolver.java:116)
        at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetOrNull(RecursivePackageProviderBackedTargetPatternResolver.java:62)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.getWildcardConflict(TargetPattern.java:551)
        at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:485)
        at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:77)
Server terminated abruptly (error code: 14, error message: '', log file: 'c:\_bazel\o2bbs3hu/server/jvm.out')
```

### What operating system are you running Bazel on?

Windows 10

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From a5ecd8132d3742831eda9730614270604294e410, using Bazel 0.13.1 release.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
a5ecd8132d3742831eda9730614270604294e410
a5ecd8132d3742831eda9730614270604294e410
```

**Comment by laszlocsomor** [comment]
Bazel 0.13.1 release and 0.14.0 release candidates are NOT affected.

**Comment by laszlocsomor** [comment]
Culprit: c4f2d80270f1ce947fcf7fb0a4e5f0afb3a7062d
/cc @ulfjack @meisterT

**Comment by ulfjack** [comment]
Is this Windows-only or other platforms as well?

**Comment by laszlocsomor** [comment]
Doesn't happen on Linux.

**Comment by laszlocsomor** [comment]
@meisterT agreed to submit a workaround and I'm writing a regression test.

**Comment by laszlocsomor** [comment]
The regression test is in https://github.com/laszlocsomor/bazel/tree/query-test (not ready to be merged upstream until @meisterT fixes the Bazel side).

**Comment by laszlocsomor** [comment]
Both the fix and the regression test are merged, closing.
