### ISSUE TITLE
NPE when --experimental_remote_spawn_cache specified without --disk_cache

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#5311]
Bazel crashes when --experimental_remote_spawn_cache specified without --disk_cache. Can we do so with more grace? :)

java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/main/java/com/google/devtools/build/lib:bazel/BazelServer com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@add649a false (1492562562), actionIndex=8}' (requested by nodes 'src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles/MANIFEST //src/main/java/com/google/devtools/build/lib:bazel/BazelServer com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@add649a false (1492562562)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:424)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:179)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:98)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:64)
	at com.google.devtools.build.lib.exec.SymlinkTreeHelper.createSymlinks(SymlinkTreeHelper.java:128)
	at com.google.devtools.build.lib.exec.SymlinkTreeStrategy.createSymlinks(SymlinkTreeStrategy.java:72)
	at com.google.devtools.build.lib.analysis.actions.SymlinkTreeAction.execute(SymlinkTreeAction.java:108)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:896)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:827)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:112)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:694)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:648)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:414)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:194)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:347)
	... 4 more

**Comment by ulfjack** [comment]
Can you try Bazel HEAD - I made a change in this area recently, which may have fixed it.

**Comment by ulfjack** [comment]
(experimental_remote_spawn_cache is now a no-op)

**Comment by mhlopko** [comment]
Verified, fixed. Thanks!
