### ISSUE TITLE
Bazel remote cache intermittmently fails when pointed at AWS S3

### ISSUE THREAD

**Issue by jpieper-tri** [bazelbuild/bazel#5353]
### Description of the problem / feature request:

We have bazel configured to use remote caching, with the --experimental_remote_spawn_cache pointed at an Amazon AWS S3 bucket.  Since upgrading from a patched version near 0.13.0 to an unmodified 0.14.0 we have started seeing spurious failures to build.

```
00:08:28.390 java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@ceres//:ceres 006440a593e6d1f9431055a2496c203c false (117166030), actionIndex=126}' (requested by nodes 'external/ceres/_objs/ceres/external/ceres/internal/ceres/implicit_schur_complement.pic.o @ceres//:ceres 006440a593e6d1f9431055a2496c203c false (117166030)')
00:08:28.390 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
00:08:28.390 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
00:08:28.390 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:08:28.390 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:08:28.390 	at java.lang.Thread.run(Thread.java:748)
00:08:28.390 Caused by: java.lang.IllegalStateException: content before headers
00:08:28.390 	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
00:08:28.390 	at com.google.devtools.build.lib.remote.blobstore.http.HttpDownloadHandler.channelRead0(HttpDownloadHandler.java:102)
00:08:28.390 	at com.google.devtools.build.lib.remote.blobstore.http.HttpDownloadHandler.channelRead0(HttpDownloadHandler.java:40)
00:08:28.390 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00:08:28.390 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
00:08:28.390 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
00:08:28.390 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
00:08:28.390 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00:08:28.390 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
00:08:28.390 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
00:08:28.390 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
00:08:28.390 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
00:08:28.390 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
00:08:28.390 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00:08:28.390 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
00:08:28.390 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
00:08:28.390 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
00:08:28.390 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
00:08:28.390 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
00:08:28.390 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
00:08:28.390 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
00:08:28.390 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
00:08:28.390 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
00:08:28.390 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
00:08:28.390 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
00:08:28.390 	... 1 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The problem is intermittment, and not clear how reproducible it is.

### What operating system are you running Bazel on?

Ubuntu 16.04, x86_64

### What's the output of `bazel info release`?

jpieper@megacalculon:~/ghe-driving/src$ bazel info release
Starting local Bazel server and connecting to it...
..............
release 0.14.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Downloading the bazel-0.14.0-dist.zip and running `compile.sh`

###  Have you found anything relevant by searching the web?

The relevant failure: `java.lang.IllegalStateException: content before headers` does not appear anywhere according to google outside of the bazel source tree.

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

It seems plausible that the exception catch at https://github.com/bazelbuild/bazel/blob/61377f7e0b31d47d27b184edf928f2c446da0867/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java#L140 is insufficiently broad?

**Comment by laszlocsomor** [comment]
@buchgr to triage please

**Comment by buchgr** [comment]
Is this still a problem? Also, we don't really support AWS S3 yet. There's a patch that adds support for it https://github.com/bazelbuild/bazel/pull/4889

**Comment by jpieper-tri** [comment]
For the record, this was using the S3 REST interface.  Presumably any production REST interface will occasionally return errors for which retrying is necessary.
