### ISSUE TITLE
NPE with `--remote_http_cache`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5366]
### Description of the problem / feature request:

In any workspace, run:

```
$ bazel build --remote_http_cache=https://example.com --google_default_credentials
```

You'll get:
```
Starting local Bazel server and connecting to it...
.........
ERROR: Failed to init auth credentials: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
        at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
        at com.google.devtools.build.lib.events.Event.error(Event.java:165)
        at com.google.devtools.build.lib.events.Event.error(Event.java:200)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:457)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
        at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
        at com.google.devtools.build.lib.events.Event.error(Event.java:165)
        at com.google.devtools.build.lib.events.Event.error(Event.java:200)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:457)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### What operating system are you running Bazel on?

Debian Rodete

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.14.1
```

**Comment by ulfjack** [comment]
There are three issues here. BlazeCommandDispatcher.execExclusively is blindly relying on getMessage() being non-null, which is a bug. We're also swallowing the internal stack trace, which is a bug. And then there is the actual issue, which we don't know yet, but may have been in 68aa410229cb36ceedc910c803a0aff2db6d027f.

**Comment by irengrig** [comment]
NPE part was already fixed by [e1ada6d](https://github.com/bazelbuild/bazel/commit/e1ada6d351cb714c9e5694e1e58cd2b761c84784) at 2018-05-17
