### ISSUE TITLE
0.1.1 and 0.1.2 RC2 fail with internal compiler error

### ISSUE THREAD

**Issue by Jose123456** [bazelbuild/bazel#537]
Sending SIGTERM to previous Bazel server (pid=6616)... done.
.....
INFO: Found 1 target...
INFO: From Building foo/libapp.jar (1 files):
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NoSuchFieldError: kind
	at com.google.devtools.build.buildjar.javac.plugins.dependency.StrictJavaDepsPlugin$CheckingTreeScanner.visitIdent(StrictJavaDepsPlugin.java:299)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2188)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.tree.TreeScanner.visitAnnotation(TreeScanner.java:322)
	at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2512)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.tree.TreeScanner.visitModifiers(TreeScanner.java:318)
	at com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2541)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.tree.TreeScanner.visitClassDef(TreeScanner.java:79)
	at com.google.devtools.build.buildjar.javac.plugins.dependency.StrictJavaDepsPlugin$CheckingTreeScanner.visitClassDef(StrictJavaDepsPlugin.java:359)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:744)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.google.devtools.build.buildjar.javac.plugins.dependency.StrictJavaDepsPlugin.postAttribute(StrictJavaDepsPlugin.java:152)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.attribute(BlazeJavaCompiler.java:112)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:865)
	at com.sun.tools.javac.main.Main.compile(Main.java:253)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:142)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:134)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:59)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:111)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:39)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:81)
	at java.lang.Thread.run(Thread.java:745)
BazelJavaBuilder threw exception: java compilation returned status ABNORMAL
ERROR: /Users/j/build/src/foo/BUILD:17:1: Java compilation in rule '//foo:app' failed: java failed: error executing command 
  (cd /private/var/tmp/_bazel_j/728e0e32726aa0f961a6ed963c7b6126/_src && \
  exec env - \
  external/local-jdk/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac.jar -client -jar tools/jdk/JavaBuilder_deploy.jar @bazel-out/local_darwin-fastbuild/bin/foo/libapp.jar-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: java failed: error executing command 
  (cd /private/var/tmp/_bazel_j/728e0e32726aa0f961a6ed963c7b6126/_src && \
  exec env - \
  external/local-jdk/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac.jar -client -jar tools/jdk/JavaBuilder_deploy.jar @bazel-out/local_darwin-fastbuild/bin/foo/libapp.jar-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //foo:backend failed to build
INFO: Elapsed time: 3.912s, Critical Path: 1.22s

This is on Mac OS 10.10.5. JDK 1.8.0_65-b17. Locally-built HEAD works fine.

**Comment by philwo** [comment]
@cushon, could you have a look at this?

**Comment by cushon** [comment]
One way that could happen is if your base workspace is in an inconsistent state, and the versions of `javac.jar` and `JavaBuilder_deploy.jar` were different (specifically, on either side of d014b42c11508fc2897ff1f7e0a4c659e8bdc320).

Clean installs of 0.1.1 and 0.1.2rc2 work fine for me. Are you sure you're using the tools from those releases, and not from an existing install?

Do you have a full repro?

**Comment by Jose123456** [comment]
I looked for JavaBuilder_deploy.jar, and there were a couple under /private/var/tmp/_bazel_jose. Removing that directory did the trick. Maybe the install shell script should remove that directory?

I'm building this simple project: https://github.com/Jose123456/bazel-test

**Comment by cushon** [comment]
I'm not familiar enough with the installer to have suggestions, but this issue doesn't sound specific to javabuilder.

@philwo, any ideas?

**Comment by damienmg** [comment]
@Jose123456 Is it still happening?
The thing is a new install should not use the old cache (unless you are reinstalling the same binary). `bazel clean --expunge` is usually the way to clean the cache.

**Comment by Jose123456** [comment]
I did try a `bazel clean --expunge` when I was experiencing this problem. It didn't help.

I haven't tried to install Bazel in a while, but no, upgrading 0.1.1 -> 0.1.2 did not trigger the problem. It must've been a problem with the 0.1.0 installer.

**Comment by damienmg** [comment]
Ok closing this issue then. Please ping back if you experience it again.
