### ISSUE TITLE
Bazel CI: protobuf project is broken

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5383]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro:

1. Clone https://github.com/google/protobuf/commit/ef9d868353acfc919e7e38e961a87f4fa0f1064b
2. Run this command:
```
  $ bazel test --keep_going --announce_rc --build_tests_only //:all
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=140
ERROR: /usr/local/google/home/laszlocsomor/stuff/protobuf/WORKSPACE:32:1: no such package '@six_archive//': Traceback (most recent call last):
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/01c7a16cdc16c48290b25e928dfd648e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 48
                print(("ctx.attr.build_file %s, path %...))))
        File "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/01c7a16cdc16c48290b25e928dfd648e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 49, in print
                ctx.path(ctx.attr.build_file)
Not a regular file: /usr/local/google/home/laszlocsomor/stuff/protobuf/external/six.BUILD and referenced by '//external:six'
ERROR: /usr/local/google/home/laszlocsomor/stuff/protobuf/WORKSPACE:27:1: no such package '@submodule_gmock//': In new_local_repository rule //external:submodule_gmock the 'build_file' attribute does not specify an existing file (/usr/local/google/home/laszlocsomor/stuff/protobuf/third_party/googletest/BUILD.bazel does not exist) and referenced by '//external:gtest_main'
ERROR: /usr/local/google/home/laszlocsomor/stuff/protobuf/WORKSPACE:22:1: no such package '@submodule_gmock//': In new_local_repository rule //external:submodule_gmock the 'build_file' attribute does not specify an existing file (/usr/local/google/home/laszlocsomor/stuff/protobuf/third_party/googletest/BUILD.bazel does not exist) and referenced by '//external:gtest'
WARNING: errors encountered while analyzing target '//:py_descriptor_database_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_json_format_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_unknown_fields_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_reflection_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_service_reflection_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_wire_format_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_descriptor_pool_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_message_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_message_factory_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_proto_builder_test': it will not be built
WARNING: errors encountered while analyzing target '//:protobuf_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_generator_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_symbol_database_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_text_format_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_text_encoding_test': it will not be built
WARNING: errors encountered while analyzing target '//:py_descriptor_test': it will not be built
INFO: Analysed 16 targets (0 packages loaded).
INFO: Found 0 test targets...
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 0.337s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Debian Rodete

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.14.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/google/protobuf.git
ef9d868353acfc919e7e38e961a87f4fa0f1064b
ef9d868353acfc919e7e38e961a87f4fa0f1064b
```

**Comment by laszlocsomor** [comment]
Culprit is https://github.com/google/protobuf/commit/beb2d8dd408c62e7dce3668c4d2db2ba5721bfd2

**Comment by mhlopko** [comment]
This is fixed now (and the CI is bright green :)
