### ISSUE TITLE
Bazel CI: RuntimeException with rules_go

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5396]
### Description of the problem / feature request:

Bazel CI: Bazel (with downstream projects) pipeline is failing in the rules_go job (using Bazel from HEAD).

I can repro this locally, and bisected the culprit to be 45b308a62f42c2c0bcfe79dcd4046c4025a31059.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Build Bazel from https://github.com/bazelbuild/bazel/commit/45b308a62f42c2c0bcfe79dcd4046c4025a31059
2. Clone rules_go from https://github.com/bazelbuild/rules_go/commit/d850f8bbd15d94ce11a078b3933e92ebbf09f715
3. Use the custom Bazel in rules_go to build:

```
  $ ~/stuff/bazel/bazel-bin/src/bazel clean --expunge  ; ~/stuff/bazel/bazel-bin/src/bazel build --keep_going --announce_rc ...
```

Bazel will crash with a RuntimeException:

```
Starting local Bazel server and connecting to it...
.........
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Starting local Bazel server and connecting to it...
..........
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=140
DEBUG: /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/bb8c68dd1d8ec30664744f758b02976f/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl:98:7:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/bb8c68dd1d8ec30664744f758b02976f/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.8.0.
INFO: SHA256 (https://codeload.github.com/golang/crypto/zip/81e90905daefcd6fd217b62423c0908922eadb30) = 29776d8e95a61a5da93d68f7c2594304ff52ebfe458f44bfc6f913e93c910966
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/5d2fd3ccab986d52112bf301d47a819783339d0e) = 31c4b514df1b40d7ade2e6f824dca35a36d9454983e7955074ac6f47f1eb3292
INFO: SHA256 (https://codeload.github.com/bazelbuild/buildtools/zip/799e530642bac55de7e76728fa0c3161484899f6) = ea23bbec9e86205b71ef647e1755ae0ec400aa76aeb5d13913d3fc3a37afbb5f
INFO: SHA256 (https://codeload.github.com/golang/crypto/zip/81e90905daefcd6fd217b62423c0908922eadb30) = 29776d8e95a61a5da93d68f7c2594304ff52ebfe458f44bfc6f913e93c910966
INFO: SHA256 (https://codeload.github.com/golang/crypto/zip/81e90905daefcd6fd217b62423c0908922eadb30) = 29776d8e95a61a5da93d68f7c2594304ff52ebfe458f44bfc6f913e93c910966
INFO: SHA256 (https://codeload.github.com/google/protobuf/zip/106ffc04be1abf3ff3399f54ccf149815b287dd9) = 4d127e1c3608803bc845cc4b3c8c42a6a16263b6ddcb932b53049e7ec8101398
DEBUG: /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/bb8c68dd1d8ec30664744f758b02976f/external/io_bazel_rules_go/go/private/tools/vet.bzl:29:5:
EXPERIMENTAL: the go_vet_test rule is still very experimental
Please do not rely on it for production use, but feel free to use it and file issues
INFO: Analysed 681 targets (402 packages loaded).
INFO: Found 681 targets...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=[]#@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="on",static="auto",msan="auto",race="auto",goos="linux",goarch="amd64",linkmode="normal"] BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] @io_bazel_rules_go//:stdlib BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] false {pure=[on], static=[auto], msan=[auto], race=[auto], goos=[linux], goarch=[amd64], linkmode=[normal]}, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg')
INFO: Elapsed time: 88.733s, Critical Path: 31.14s
INFO: 546 processes: 546 linux-sandbox.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=[]#@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="on",static="auto",msan="auto",race="auto",goos="linux",goarch="amd64",linkmode="normal"] BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] @io_bazel_rules_go//:stdlib BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] false {pure=[on], static=[auto], msan=[auto], race=[auto], goos=[linux], goarch=[amd64], linkmode=[normal]}, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg/linux_amd64/net/textproto.a=[/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/bb8c68dd1d8ec30664744f758b02976f/execroot/io_bazel_rules_go/bazel-out/k8-fastbuild/bin]/[external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg/linux_amd64/net/textproto.a], RegularFileStateValue{digest=null, size=121690, contentsProxy=ctime of 1528975139032 and nodeId of
22182824}
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
        at com.google.devtools.build.lib.skyframe.ActionExecutionValue.transformKeys(ActionExecutionValue.java:212)
        at com.google.devtools.build.lib.skyframe.ActionExecutionValue.transformForSharedAction(ActionExecutionValue.java:227)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:457)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:379)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:226)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=[]#@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="on",static="auto",msan="auto",race="auto",goos="linux",goarch="amd64",linkmode="normal"] BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] @io_bazel_rules_go//:stdlib BuildConfigurationValue.Key[75c1ee5711bf39fe1f9008c77ef96600] false {pure=[on], static=[auto], msan=[auto], race=[auto], goos=[linux], goarch=[amd64], linkmode=[normal]}, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg/linux_amd64/net/textproto.a=[/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/bb8c68dd1d8ec30664744f758b02976f/execroot/io_bazel_rules_go/bazel-out/k8-fastbuild/bin]/[external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/pkg/linux_amd64/net/textproto.a], RegularFileStateValue{digest=null, size=121690, contentsProxy=ctime of 1528975139032 and nodeId of
22182824}
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
        at com.google.devtools.build.lib.skyframe.ActionExecutionValue.transformKeys(ActionExecutionValue.java:212)
        at com.google.devtools.build.lib.skyframe.ActionExecutionValue.transformForSharedAction(ActionExecutionValue.java:227)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:457)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:379)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:226)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
FAILED: Build did NOT complete successfully
```

Bazel doesn't crash if you build it from the previous commit.

### What operating system are you running Bazel on?

Debian Rodete

**Comment by janakdr** [comment]
Thanks for the report and sorry for the breakage! Will investigate today.

**Comment by laszlocsomor** [comment]
Thank you!

**Comment by janakdr** [comment]
Excuse my ignorance, how do I clone rules_go and then use those rules? Do I download them to a different git repository? Then how do I make Bazel use them?

**Comment by laszlocsomor** [comment]
You need to clone both the `rules_go` and the `bazel` repos to separate directories, build Bazel, check out the right commit from rules_go, then build with the custom Bazel binary.

Here's how you do it:

```
mkdir ~/work && cd ~/work

git clone https://github.com/bazelbuild/bazel.git

git clone https://github.com/bazelbuild/rules_go.git

cd ~/work/bazel && bazel build //src:bazel

cd ~/work/rules_go && git checkout d850f8bbd15d94ce11a078b3933e92ebbf09f715

~/work/bazel/bazel-bin/src/bazel clean --expunge 

~/work/bazel/bazel-bin/src/bazel build --keep_going --announce_rc //...
```

**Comment by janakdr** [comment]
Looks like this comes from shared actions that are also creating tree artifacts. Not sure how to fix that. Also not sure why that's happening in the first place...

**Comment by laszlocsomor** [comment]
Thanks for the analysis and for the quick fix!
