### ISSUE TITLE
Bazel CI, Bazel with downstream projects: protobuf is broken on Mac

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5410]
### Description of the problem / feature request:

On Bazel CI, in the "Bazel with downstream projects" pipeline (uses Bazel from HEAD), the "protobuf" pipeline is broken on Mac:

```
--- Fetching protobuf sources
git remote set-url origin https://github.com/google/protobuf.git
--
  | git clean -fdqx
  | git submodule foreach --recursive git clean -fdqx
  | git fetch origin
  | git reset refs/remotes/origin/master --hard
  | HEAD is now at b40cb4bc8bd Merge pull request #4760 from dslomov/fix-buildfile-references
  | git submodule sync --recursive
  | Synchronizing submodule url for 'third_party/benchmark'
  | Synchronizing submodule url for 'third_party/googletest'
  | git submodule update --init --recursive --force
  | fatal: submodule 'third_party/benchmark' cannot add alternate: path '/usr/local/var/bazelbuild/modules/third_party/benchmark/' does not exist
  | Failed to clone 'third_party/benchmark'. Retry scheduled
  | fatal: submodule 'third_party/googletest' cannot add alternate: path '/usr/local/var/bazelbuild/modules/third_party/googletest/' does not exist
  | Failed to clone 'third_party/googletest'. Retry scheduled
  | fatal: submodule 'third_party/benchmark' cannot add alternate: path '/usr/local/var/bazelbuild/modules/third_party/benchmark/' does not exist
  | Failed to clone 'third_party/benchmark' a second time, aborting
  | Traceback (most recent call last):
  |   File "bazelci.py", line 1236, in <module>
  |     sys.exit(main())
  |   File "bazelci.py", line 1223, in main
  |     args.build_only, args.test_only)
  |   File "bazelci.py", line 358, in execute_commands
  |     clone_git_repository(git_repository, platform)
  |   File "bazelci.py", line 611, in clone_git_repository
  |     "--init", "--recursive", "--force"])
  |   File "bazelci.py", line 832, in execute_command
  |     return subprocess.run(args, shell=shell, check=fail_if_nonzero).returncode
  |   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
  |     output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive', '--force']' returned non-zero exit status 1.
  | 🚨 Error: The command exited with status 1
```

### What operating system are you running Bazel on?

Mac

**Comment by mhlopko** [comment]
Oh it's bazel with downstream projects, let me reopen and double check once buchgr@ fixes the issue that dominates there.

**Comment by mhlopko** [comment]
Protobuf is green now. Closing.
