### ISSUE TITLE
ProviderNotFoundException when adding .srcjar to java_library srcs

### ISSUE THREAD

**Issue by rightfold** [bazelbuild/bazel#5418]
### Description of the problem / feature request:

When using a target that outputs a .srcjar in the srcs of a java_library, the following stack trace occurs:

```
java.nio.file.ProviderNotFoundException: Provider not found
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:407)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.getJarFileSystem(SimpleJavaLibraryBuilder.java:226)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.setUpSourceJars(SimpleJavaLibraryBuilder.java:194)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.prepareSourceCompilation(SimpleJavaLibraryBuilder.java:55)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:113)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:132)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
```

Note that this is not about Bazel providers, but about Java NIO file system providers.

It seems like it is the following line that causes the crash:

https://github.com/bazelbuild/bazel/blob/4001dddc38b07fe0ee86f6a9e95ff4a92276bb2d/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/SimpleJavaLibraryBuilder.java#L230

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I was trying to use output generated by ANTLR v4 with Bazel. The Bazel build files can be found in the repository linked below, but the following shortened version produces the same stack trace:

```python
# tools/antlr4.bzl

def _antlr4_sources(ctx):
    ctx.actions.run(
        inputs = ctx.files.srcs,
        outputs = [ctx.outputs.src_jar],
        mnemonic = "antlr4",
        executable = "touch",
        arguments = [ctx.outputs.src_jar.path],
    )

antlr4_sources = rule(
    implementation = _antlr4_sources,
    attrs = {
        "srcs": attr.label_list(
            non_empty = True,
            allow_files = True,
        ),
    },
    outputs = {
        "src_jar": "%{name}.srcjar",
    },
)

# BUILD
load("//tools:antlr4.bzl", "antlr4_sources")

java_library(
    name = "libleekc",
    srcs = [":libleekcparse"],
)

antlr4_sources(
    name = "libleekcparse",
    srcs = "src/main/antlr4/leek/c/parse/Grammar.g4",
)

# src/main/antlr4/leek/c/parse/Grammar.g4
Could be a file with any content.
```

### What operating system are you running Bazel on?

Gentoo GNU/Linux, kernel 4.16.3-gentoo, Intel x86-64.

Java version is:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (Gentoo icedtea-3.7.0)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)

### What's the output of `bazel info release`?

release 0.14.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:rightfold/leek.git
419c8be577d59a33e0f2873f57f44c116de2954b
419c8be577d59a33e0f2873f57f44c116de2954b

###  Have you found anything relevant by searching the web?

Could not find anything related to both Bazel and this exception. The stack trace does not give any useful information about why the exception happened, so I could only guess it had to do with the .srcjar file extension.

**Comment by rightfold** [comment]
It seems like the problem occurred because the .srcjar file wasn't a zip file but a directory. A more informative error message would be very useful.
