### ISSUE TITLE
Bazel sometimes hangs waiting for server response after update

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#545]
Since updating Bazel I now get occasional hangs when running commands, with output like this:

```
# bazel test //mytarget
INFO: Waiting for response from Bazel server (pid 13373)...
^C
Bazel caught interrupt signal; shutting down.

^C
Bazel caught interrupt signal; shutting down.

^C
Bazel caught third interrupt signal; killed.

```

It'll hang for multiple minutes if I don't kill it. This happens maybe about 10% of the time, and usually goes away if I try it again after killing (though sometimes it takes several tries). Multiple people on my team have seen this, on both Linux and Mac.

Another oddity that may or may not be related is that "INFO:" in the output above is printed in white; every other time I've seen it it's been green

**Comment by ulfjack** [comment]
The info line comes from the client, which isn't using color codes when printing it. Only the server is using color codes. It's unrelated.

If this happens, try getting a stack trace from the Java VM with "jstack <pid>".

**Comment by kayasoze** [comment]
I've seen this happen when a child process running under Bazel doesn't close stderr.  See https://github.com/bazelbuild/bazel/issues/220.  It sounds crazy, I know, and, of course, it may not be the same issue.

**Comment by ekuefler** [comment]
It stopped for a bit, but now it's back and I have some stack traces. A lot of threads look like they're blocked on socket connections to bazel dash (I have `--dash_url` set), perhaps connecting to dash isn't timing out properly?
```
2015-11-05 00:32:07
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"Attach Listener" #12726 daemon prio=9 os_prio=0 tid=0x00007f90e8002000 nid=0x6a1b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-30-thread-1" #669 daemon prio=5 os_prio=0 tid=0x00007f9140853800 nid=0x1e61 runnable [0x00007f911678d000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x000000076e9bc418> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.access$000(DashModule.java:260)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender$1.run(DashModule.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-27-thread-1" #666 daemon prio=5 os_prio=0 tid=0x00007f904406d800 nid=0x1979 runnable [0x00007f901a0e0000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x000000076ea67570> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.access$000(DashModule.java:260)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender$1.run(DashModule.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-12-thread-1" #216 daemon prio=5 os_prio=0 tid=0x00007f914086e800 nid=0x59e runnable [0x00007f9114c72000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x000000076ec68420> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.access$000(DashModule.java:260)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender$1.run(DashModule.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-5-thread-1" #18 daemon prio=5 os_prio=0 tid=0x00007f91407d9000 nid=0x4d6 runnable [0x00007f9117599000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x000000076ed04118> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.access$000(DashModule.java:260)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender$1.run(DashModule.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-4-thread-1" #17 daemon prio=5 os_prio=0 tid=0x00007f91407d8000 nid=0x4d5 runnable [0x00007f91246c2000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x00000006c8f54428> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.access$000(DashModule.java:260)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender$1.run(DashModule.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"commons-pool-EvictionTimer" #16 daemon prio=5 os_prio=0 tid=0x00007f914060a000 nid=0x4d4 in Object.wait() [0x00007f91241b9000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000006c6556c58> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Path cache cleanup" #11 daemon prio=5 os_prio=0 tid=0x00007f914034e800 nid=0x4d1 in Object.wait() [0x00007f912c110000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c62eeab0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.google.devtools.build.lib.vfs.Path$1.run(Path.java:98)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007f9140213000 nid=0x4cf runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007f9140205800 nid=0x4ce waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f9140201000 nid=0x4cd waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f91401ff800 nid=0x4cc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f91401fc800 nid=0x4cb waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f91401fa800 nid=0x4ca runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f91401ce000 nid=0x4c9 in Object.wait() [0x00007f912ce6a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c6225878> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f91401cc000 nid=0x4c8 in Object.wait() [0x00007f912cf6b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000006c62bf690> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007f914000a000 nid=0x4be runnable [0x00007f9147618000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	- locked <0x000000076cfc2b78> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.sendMessage(DashModule.java:322)
	at com.google.devtools.build.lib.bazel.dash.DashModule$Sender.<init>(DashModule.java:285)
	at com.google.devtools.build.lib.bazel.dash.DashModule.handleOptions(DashModule.java:108)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.beforeCommand(CommandEnvironment.java:396)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:357)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1012)
	at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
	at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
	at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:971)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:768)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)

"VM Thread" os_prio=0 tid=0x00007f91401c7000 nid=0x4c7 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f914001f000 nid=0x4bf runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f9140021000 nid=0x4c0 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f9140022800 nid=0x4c1 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f9140024800 nid=0x4c2 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007f9140026000 nid=0x4c3 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007f9140028000 nid=0x4c4 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007f9140029800 nid=0x4c5 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007f914002b800 nid=0x4c6 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f9140215800 nid=0x4d0 waiting on condition 

JNI global references: 262
```

**Comment by kchodorow** [comment]
That sounds very likely.  I'll take a look.
