### ISSUE TITLE
compile.sh - The system is out of resources.

### ISSUE THREAD

**Issue by linengmiaoo** [bazelbuild/bazel#5459]
Hello

I am trying to compile bazel from source on my NVIDIA Jetson TK1.
When trying to run compile.sh I get the following error:
```

ubuntu@tegra-ubuntu:~/bazelArtefact/bazel-0.14.1-dist$ ./compile.sh 
🍃  Building Bazel from scratch../usr/lib/jvm/java-8-oracle/bin/javac -classpath third_party/asm/asm-analysis-6.0.jar:third_party/asm/asm-6.0-sources.jar:third_party/asm/asm-tree-6.0-sources.jar:third_party/asm/asm-commons-6.0.jar:third_party/asm/asm-6.0.jar:third_party/asm/asm-commons-6.0-sources.jar:third_party/asm/asm-util-6.0.jar:third_party/asm/asm-util-6.0-sources.jar:third_party/asm/asm-analysis-6.0-sources.jar:third_party/asm/asm-tree-6.0.jar:third_party/bytebuddy/byte-buddy-dep-0.7-rc6.jar:third_party/compile_testing/compile-testing-0.13.jar:third_party/minlog/minlog-1.2.jar:third_party/jackson2/jackson-core-2.8.6.jar:third_party/auth/google-auth-library-credentials-0.6.0.jar:third_party/auth/google-auth-library-oauth2-http-0.6.0.jar:third_party/jsr305/jsr-305.jar:third_party/objenesis/objenesis-1_3.jar:third_party/plexus_component_annotations/plexus-component-annotations-1.6.jar:third_party/xz/xz-1.5.jar:third_party/apache_httpclient/httpclient-4.5.3.jar:third_party/ijar/test/jar-with-manifest.jar:third_party/ijar/test/jar-without-manifest.jar:third_party/ijar/test/libwrongcentraldir.jar:third_party/ijar/test/jar-with-manifest-and-target-label.jar:third_party/maven_model/maven-aether-provider-3.2.3.jar:third_party/maven_model/maven-model-builder-3.2.3.jar:third_party/maven_model/maven-repository-metadata-3.2.3.jar:third_party/maven_model/maven-model-3.2.3.jar:third_party/apache_commons_collections/commons-collections-3.2.2.jar:third_party/jsch/jsch-0.1.54.jar:third_party/auto/auto-common-0.3.jar:third_party/auto/auto-value-1.5.4.jar:third_party/auto/auto-service-1.0-rc2.jar:third_party/java/jdk/langtools/java_compiler.jar:third_party/java/jdk/langtools/jdk_compiler.jar:third_party/java/jdk/langtools/java_compiler-src.jar:third_party/java/jdk/langtools/jdk_compiler-src.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar:third_party/java/jcommander/jcommander-1.48.jar:third_party/java/javapoet/javapoet-1.8.0.jar:third_party/java/android_databinding/v2_3_1/exec.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946-src.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946-src.jar:third_party/java/jacoco/jacocoagent.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946-src.jar:third_party/java/proguard/proguard5.3.3/lib/proguardgui.jar:third_party/java/proguard/proguard5.3.3/lib/proguard.jar:third_party/java/proguard/proguard5.3.3/lib/retrace.jar:third_party/java/proguard/proguard5.3.3/examples/annotations/lib/annotations.jar:third_party/apache_commons_pool2/commons-pool2-2.3.jar:third_party/checker_framework_dataflow/dataflow-2.5.0-sources.jar:third_party/checker_framework_dataflow/dataflow-2.5.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/truth8/truth-java8-extension-0.36.jar:third_party/apache_velocity/velocity-1.7.jar:third_party/junit/junit-4.11.jar:third_party/netty_tcnative/netty-tcnative-boringssl-static-2.0.7.Final.jar:third_party/aether/aether-transport-http-1.0.0.v20140518.jar:third_party/aether/aether-transport-classpath-1.0.0.v20140518.jar:third_party/aether/aether-transport-wagon-1.0.0.v20140518.jar:third_party/aether/aether-connector-basic-1.0.0.v20140518.jar:third_party/aether/aether-spi-1.0.0.v20140518.jar:third_party/aether/aether-util-1.0.0.v20140518.jar:third_party/aether/aether-api-1.0.0.v20140518.jar:third_party/aether/aether-transport-file-1.0.0.v20140518.jar:third_party/aether/aether-impl-1.0.0.v20140518.jar:third_party/apache_commons_compress/apache-commons-compress-1.9.jar:third_party/jimfs/jimfs-1.1.jar:third_party/gson/gson-2.2.4.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/turbine/turbine.jar:third_party/bazel_bootstrap/libunsafe-provider.jar:third_party/bazel_bootstrap/libregistered-singleton.jar:third_party/bazel_bootstrap/libserialization.jar:third_party/bazel_bootstrap/libautocodec-processor.jar:third_party/bazel_bootstrap/libautocodec-annotation.jar:third_party/jgit/org.eclipse.jgit-4.10.0.201712302008-r.jar:third_party/hamcrest/hamcrest-core-1.3.jar:third_party/checker_framework_javacutil/javacutil-2.5.0.jar:third_party/checker_framework_javacutil/javacutil-2.5.0-sources.jar:third_party/plexus_utils/plexus-utils-3.0.21.jar:third_party/maven/maven-builder-support-3.3.3.jar:third_party/maven/maven-settings-3.3.3.jar:third_party/maven/maven-settings-builder-3.3.3.jar:third_party/android_common/com.android.tools_common_25.0.0.jar:third_party/android_common/com.android.tools.build_manifest-merger_25.0.0.jar:third_party/android_common/com.android.tools.layoutlib_layoutlib_25.0.0.jar:third_party/android_common/com.android.tools.build_builder_2.0.0.jar:third_party/android_common/com.android.tools.build_builder-model_2.0.0.jar:third_party/android_common/com.android.tools.external.lombok_lombok-ast_0.2.3.jar:third_party/android_common/com.android.tools_repository_25.0.0.jar:third_party/android_common/com.android_annotations_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-checks_25.0.0.jar:third_party/android_common/com.android.tools_dvlib_25.0.0.jar:third_party/android_common/com.android.tools_sdk-common_25.0.0.jar:third_party/android_common/com.android.tools_ddmlib_25.0.0.jar:third_party/android_common/com.android.tools_sdklib_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-api_25.0.0.jar:third_party/android_common/com.android.tools.build_builder-test-api_2.0.0.jar:third_party/hazelcast/hazelcast-client-3.6.4.jar:third_party/hazelcast/hazelcast-3.6.4.jar:third_party/error_prone/error_prone_annotation-2.3.1.jar:third_party/error_prone/error_prone_annotations-2.2.0.jar:third_party/guava/guava-24.1-jre.jar:third_party/error_prone/error_prone_check_api-2.3.1.jar:third_party/error_prone/error_prone_type_annotations-2.3.1.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0-src.jar:third_party/netty/netty-all-4.1.17.Final.jar:third_party/api_client/google-http-client-1.22.0-SNAPSHOT.jar:third_party/api_client/google-http-client-jackson2-1.22.0.jar:third_party/api_client/google-api-client-1.22.0.jar:third_party/api_client/google-api-client-jackson2-1.22.0.jar:third_party/apache_httpcore/httpcore-4.4.6.jar:third_party/apache_commons_codec/commons-codec-1.9.jar:third_party/allocation_instrumenter/java-allocation-instrumenter-3.0.1.jar:third_party/opencensus/opencensus-api-0.11.0.jar:third_party/opencensus/opencensus-contrib-grpc-metrics-0.11.0.jar:third_party/kryo/kryo-3.0.2.jar:third_party/apache_commons_logging/commons-logging-1.1.1.jar:third_party/javax_annotations/javax.annotation-api-1.3.2-sources.jar:third_party/javax_annotations/javax.annotation-api-1.3.2.jar:third_party/instrumentation/instrumentation-api-0.4.3.jar:third_party/mockito/mockito-all-1.10.19.jar:third_party/apache_commons_lang/commons-lang-2.6.jar:third_party/truth/truth-0.36.jar:third_party/jsr330_inject/javax.inject.jar:third_party/pcollections/pcollections-2.1.2.jar:third_party/plexus_interpolation/plexus-interpolation-1.22.jar:third_party/reflectasm/reflectasm-1.10.1.jar:third_party/slf4j/slf4j-api-1.7.7.jar:third_party/slf4j/slf4j-jdk14-1.7.7.jar:third_party/protobuf/3.4.0/libprotobuf_java_util.jar:third_party/protobuf/3.4.0/libprotobuf_java.jar:third_party/protobuf/protobuf-java-3.0.0-alpha-3.jar:third_party/grpc/grpc-context-1.10.0.jar:third_party/grpc/grpc-netty-1.10.0.jar:third_party/grpc/grpc-auth-1.10.0.jar:third_party/grpc/grpc-core-1.10.0.jar:third_party/grpc/grpc-stub-1.10.0.jar:third_party/grpc/grpc-protobuf-1.10.0.jar:third_party/grpc/grpc-protobuf-lite-1.10.0.jar:third_party/guava/guava-testlib-24.1-jre.jar:third_party/error_prone/error_prone_core-2.3.1.jar:/tmp/bazel_baiAaXPv -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip:src/main/java:src/tools/xcode-common/java/com/google/devtools/build/xcode/common:src/tools/xcode-common/java/com/google/devtools/build/xcode/util:third_party/java/dd_plist/java:/tmp/bazel_baiAaXPv/src -d /tmp/bazel_baiAaXPv/classes -source 1.8 -target 1.8 -encoding UTF-8 @/tmp/bazel_azbWUX1k/param
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:17: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:18: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/skyframe/serialization/autocodec/UnsafeProvider.java:21: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
src/main/java/com/google/devtools/build/lib/skyframe/serialization/DynamicCodec.java:29: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
import sun.reflect.ReflectionFactory;
                  ^
src/main/java/com/google/devtools/build/lib/skyframe/serialization/EnumMapCodec.java:23: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^


The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:629)
	at java.util.HashMap.put(HashMap.java:612)
	at com.sun.tools.javac.code.Types$ImplementationCache.get(Types.java:2676)
	at com.sun.tools.javac.code.Types.implementation(Types.java:2704)
	at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1539)
	at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1528)
	at com.sun.tools.javac.comp.Resolve.notOverriddenIn(Resolve.java:419)
	at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:405)
	at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:365)
	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1463)
	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1633)
	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1704)
	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1677)
	at com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2436)
	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3097)
	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3348)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2433)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2427)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2422)
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:301)
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:236)
	at com.sun.tools.javac.comp.MemberEnter.actualEnterAnnotations(MemberEnter.java:923)
	at com.sun.tools.javac.comp.MemberEnter.access$600(MemberEnter.java:64)
	at com.sun.tools.javac.comp.MemberEnter$5.run(MemberEnter.java:876)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1015)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:902)
```
Initially I thought I was somehow running out of RAM, so I added 4Gb of swapmemory. But that still didn't work. 
So based on [this post on github](https://github.com/bazelbuild/bazel/issues/1308#issuecomment-221405546) in vim scripts/bootstrap/compile.sh I changed: 

"run "${JAVAC}" -classpath "${classpath}" -sourcepath "${sourcepath}"" 
to 
" run "${JAVAC}" -J-Xms256m -J-Xmx384m -classpath "${classpath}" -sourcepath "${sourcepath}""

like so:

```
   run "${javac}" -J-Xms256m -J-Xmx384m -classpath "${classpath}" -sourcepath "${sourcepath}" \
      -d "${output}/classes" -source "$java_version" -target "$java_version" \
      -encoding utf-8 "@${paramfile}"
```

Which allows me to allocate more heap memory.
Yet, when trying to run compile.sh I get this error:
```
ubuntu@tegra-ubuntu:~/bazelArtefact/bazel-0.14.1-dist$ ./compile.sh 
🍃  Building Bazel from scratch.. -J-Xms256m -J-Xmx4096m -classpath third_party/asm/asm-analysis-6.0.jar:third_party/asm/asm-6.0-sources.jar:third_party/asm/asm-tree-6.0-sources.jar:third_party/asm/asm-commons-6.0.jar:third_party/asm/asm-6.0.jar:third_party/asm/asm-commons-6.0-sources.jar:third_party/asm/asm-util-6.0.jar:third_party/asm/asm-util-6.0-sources.jar:third_party/asm/asm-analysis-6.0-sources.jar:third_party/asm/asm-tree-6.0.jar:third_party/bytebuddy/byte-buddy-dep-0.7-rc6.jar:third_party/compile_testing/compile-testing-0.13.jar:third_party/minlog/minlog-1.2.jar:third_party/jackson2/jackson-core-2.8.6.jar:third_party/auth/google-auth-library-credentials-0.6.0.jar:third_party/auth/google-auth-library-oauth2-http-0.6.0.jar:third_party/jsr305/jsr-305.jar:third_party/objenesis/objenesis-1_3.jar:third_party/plexus_component_annotations/plexus-component-annotations-1.6.jar:third_party/xz/xz-1.5.jar:third_party/apache_httpclient/httpclient-4.5.3.jar:third_party/ijar/test/jar-with-manifest.jar:third_party/ijar/test/jar-without-manifest.jar:third_party/ijar/test/libwrongcentraldir.jar:third_party/ijar/test/jar-with-manifest-and-target-label.jar:third_party/maven_model/maven-aether-provider-3.2.3.jar:third_party/maven_model/maven-model-builder-3.2.3.jar:third_party/maven_model/maven-repository-metadata-3.2.3.jar:third_party/maven_model/maven-model-3.2.3.jar:third_party/apache_commons_collections/commons-collections-3.2.2.jar:third_party/jsch/jsch-0.1.54.jar:third_party/auto/auto-common-0.3.jar:third_party/auto/auto-value-1.5.4.jar:third_party/auto/auto-service-1.0-rc2.jar:third_party/java/jdk/langtools/java_compiler.jar:third_party/java/jdk/langtools/jdk_compiler.jar:third_party/java/jdk/langtools/java_compiler-src.jar:third_party/java/jdk/langtools/jdk_compiler-src.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar:third_party/java/jcommander/jcommander-1.48.jar:third_party/java/javapoet/javapoet-1.8.0.jar:third_party/java/android_databinding/v2_3_1/exec.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946-src.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946-src.jar:third_party/java/jacoco/jacocoagent.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946-src.jar:third_party/java/proguard/proguard5.3.3/lib/proguardgui.jar:third_party/java/proguard/proguard5.3.3/lib/proguard.jar:third_party/java/proguard/proguard5.3.3/lib/retrace.jar:third_party/java/proguard/proguard5.3.3/examples/annotations/lib/annotations.jar:third_party/apache_commons_pool2/commons-pool2-2.3.jar:third_party/checker_framework_dataflow/dataflow-2.5.0-sources.jar:third_party/checker_framework_dataflow/dataflow-2.5.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/truth8/truth-java8-extension-0.36.jar:third_party/apache_velocity/velocity-1.7.jar:third_party/junit/junit-4.11.jar:third_party/netty_tcnative/netty-tcnative-boringssl-static-2.0.7.Final.jar:third_party/aether/aether-transport-http-1.0.0.v20140518.jar:third_party/aether/aether-transport-classpath-1.0.0.v20140518.jar:third_party/aether/aether-transport-wagon-1.0.0.v20140518.jar:third_party/aether/aether-connector-basic-1.0.0.v20140518.jar:third_party/aether/aether-spi-1.0.0.v20140518.jar:third_party/aether/aether-util-1.0.0.v20140518.jar:third_party/aether/aether-api-1.0.0.v20140518.jar:third_party/aether/aether-transport-file-1.0.0.v20140518.jar:third_party/aether/aether-impl-1.0.0.v20140518.jar:third_party/apache_commons_compress/apache-commons-compress-1.9.jar:third_party/jimfs/jimfs-1.1.jar:third_party/gson/gson-2.2.4.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/turbine/turbine.jar:third_party/bazel_bootstrap/libunsafe-provider.jar:third_party/bazel_bootstrap/libregistered-singleton.jar:third_party/bazel_bootstrap/libserialization.jar:third_party/bazel_bootstrap/libautocodec-processor.jar:third_party/bazel_bootstrap/libautocodec-annotation.jar:third_party/jgit/org.eclipse.jgit-4.10.0.201712302008-r.jar:third_party/hamcrest/hamcrest-core-1.3.jar:third_party/checker_framework_javacutil/javacutil-2.5.0.jar:third_party/checker_framework_javacutil/javacutil-2.5.0-sources.jar:third_party/plexus_utils/plexus-utils-3.0.21.jar:third_party/maven/maven-builder-support-3.3.3.jar:third_party/maven/maven-settings-3.3.3.jar:third_party/maven/maven-settings-builder-3.3.3.jar:third_party/android_common/com.android.tools_common_25.0.0.jar:third_party/android_common/com.android.tools.build_manifest-merger_25.0.0.jar:third_party/android_common/com.android.tools.layoutlib_layoutlib_25.0.0.jar:third_party/android_common/com.android.tools.build_builder_2.0.0.jar:third_party/android_common/com.android.tools.build_builder-model_2.0.0.jar:third_party/android_common/com.android.tools.external.lombok_lombok-ast_0.2.3.jar:third_party/android_common/com.android.tools_repository_25.0.0.jar:third_party/android_common/com.android_annotations_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-checks_25.0.0.jar:third_party/android_common/com.android.tools_dvlib_25.0.0.jar:third_party/android_common/com.android.tools_sdk-common_25.0.0.jar:third_party/android_common/com.android.tools_ddmlib_25.0.0.jar:third_party/android_common/com.android.tools_sdklib_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-api_25.0.0.jar:third_party/android_common/com.android.tools.build_builder-test-api_2.0.0.jar:third_party/hazelcast/hazelcast-client-3.6.4.jar:third_party/hazelcast/hazelcast-3.6.4.jar:third_party/error_prone/error_prone_annotation-2.3.1.jar:third_party/error_prone/error_prone_annotations-2.2.0.jar:third_party/guava/guava-24.1-jre.jar:third_party/error_prone/error_prone_check_api-2.3.1.jar:third_party/error_prone/error_prone_type_annotations-2.3.1.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0-src.jar:third_party/netty/netty-all-4.1.17.Final.jar:third_party/api_client/google-http-client-1.22.0-SNAPSHOT.jar:third_party/api_client/google-http-client-jackson2-1.22.0.jar:third_party/api_client/google-api-client-1.22.0.jar:third_party/api_client/google-api-client-jackson2-1.22.0.jar:third_party/apache_httpcore/httpcore-4.4.6.jar:third_party/apache_commons_codec/commons-codec-1.9.jar:third_party/allocation_instrumenter/java-allocation-instrumenter-3.0.1.jar:third_party/opencensus/opencensus-api-0.11.0.jar:third_party/opencensus/opencensus-contrib-grpc-metrics-0.11.0.jar:third_party/kryo/kryo-3.0.2.jar:third_party/apache_commons_logging/commons-logging-1.1.1.jar:third_party/javax_annotations/javax.annotation-api-1.3.2-sources.jar:third_party/javax_annotations/javax.annotation-api-1.3.2.jar:third_party/instrumentation/instrumentation-api-0.4.3.jar:third_party/mockito/mockito-all-1.10.19.jar:third_party/apache_commons_lang/commons-lang-2.6.jar:third_party/truth/truth-0.36.jar:third_party/jsr330_inject/javax.inject.jar:third_party/pcollections/pcollections-2.1.2.jar:third_party/plexus_interpolation/plexus-interpolation-1.22.jar:third_party/reflectasm/reflectasm-1.10.1.jar:third_party/slf4j/slf4j-api-1.7.7.jar:third_party/slf4j/slf4j-jdk14-1.7.7.jar:third_party/protobuf/3.4.0/libprotobuf_java_util.jar:third_party/protobuf/3.4.0/libprotobuf_java.jar:third_party/protobuf/protobuf-java-3.0.0-alpha-3.jar:third_party/grpc/grpc-context-1.10.0.jar:third_party/grpc/grpc-netty-1.10.0.jar:third_party/grpc/grpc-auth-1.10.0.jar:third_party/grpc/grpc-core-1.10.0.jar:third_party/grpc/grpc-stub-1.10.0.jar:third_party/grpc/grpc-protobuf-1.10.0.jar:third_party/grpc/grpc-protobuf-lite-1.10.0.jar:third_party/guava/guava-testlib-24.1-jre.jar:third_party/error_prone/error_prone_core-2.3.1.jar:/tmp/bazel_8Xy1UH0w -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip:src/main/java:src/tools/xcode-common/java/com/google/devtools/build/xcode/common:src/tools/xcode-common/java/com/google/devtools/build/xcode/util:third_party/java/dd_plist/java:/tmp/bazel_8Xy1UH0w/src -d /tmp/bazel_8Xy1UH0w/classes -source  -target  -encoding utf-8 @/tmp/bazel_FBVI5aJp/param
scripts/bootstrap/buildenv.sh: line 194: : command not found
```

So I'd like to know what else I could do in order to successfully compile bazel.

Thank you

**Comment by cayman1021** [comment]
Same issue here until I set it to a larger size: "**-J-Xms384m -J-Xmx512m**". However, now I got another problem. It's another issue and won't be mentioned here.

My hardware: Raspberry Pi 3 Model B + Raspbian Stretch

**Comment by linengmiaoo** [comment]
@cayman1021  I still get "command not found" when I use the same values as  you do

**Comment by linengmiaoo** [comment]
Problem solved, I had to capitalize my environment variable: javac to JAVAC. Obviously.
