### ISSUE TITLE
use of UnionFileSystem causes Auto-Configuration Error searching for C/CXX toolchain

### ISSUE THREAD

**Issue by gvacaliuc** [bazelbuild/bazel#5464]
### Description of the problem / feature request:

Using a [trivial example](https://github.com/gvacaliuc/bazel/commit/e2a8f2853d76ec8f84d7733dadf7c48ca40cbc75#diff-7dff227a8d623e0469c26b9316161435R61) of `com.google.common.build.lib.vfs.UnionFileSystem` as Bazel's filesystem leaves Bazel unable to locate the c/c++ toolchain (building the example from [java_tutorial in examples repo](https://github.com/bazelbuild/examples/tree/master/java-tutorial)):

```bash
$ ~/devel/bazel/bazel-bin/src/bazel build //:ProjectRunner
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "/home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/bazel_tools/tools/cpp/cc_configure.bzl", line 56
		configure_unix_toolchain(repository_ctx, cpu_value, overriden...)
	File "/home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 477, in configure_unix_toolchain
		_find_generic(repository_ctx, "gcc", "CC", overriden...)
	File "/home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 459, in _find_generic
		auto_configure_fail(msg)
	File "/home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
		fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
INFO: Elapsed time: 4.362s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
```

Moreover (and I don't know how reproducible this is as this following error occurs on my personal computer but not my work machine:

```bash
$ CC=/usr/bin/gcc GCOV=/usr/bin/gcov ~/devel/bazel/bazel-bin/src/bazel build //:ProjectRunner
INFO: Analysed target //:ProjectRunner (13 packages loaded).
INFO: Found 1 target...
ERROR: missing input file '@local_jdk//:bin/ControlPanel':/home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/local_jdk/bin/ControlPanel/jcontrol (Not a directory)
ERROR: /home/gvacaliuc/devel/learning-bazel/examples/java-tutorial/BUILD:1:1: //:ProjectRunner: missing input file '@local_jdk//:bin/ControlPanel'
Target //:ProjectRunner failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/gvacaliuc/devel/learning-bazel/examples/java-tutorial/BUILD:1:1 1 input file(s) do not exist
INFO: Elapsed time: 3.331s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

```bash
$ ls /home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/066fd80e9ac429594637ee0bd164e530/external/local_jdk/bin/ -l | grep jcontrol
lrwxrwxrwx 1 root root      8 Nov 10  2017 ControlPanel -> jcontrol
-rwxr-xr-x 1 root root   6264 Nov 10  2017 jcontrol
```
where `.../local_jdk/bin` is a symlink to `$JAVA_HOME/bin`.

(Neither of these errors occur on the [development branch](https://github.com/bazelbuild/bazel/commit/c7a2a3dc52d2e8b08b5186cc8c78020a944a0d50) I added my commit to.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
$ cd /tmp && git clone https://github.com/gvacaliuc/bazel.git && cd bazel && git checkout union-filesystem
$ bazel build //src:bazel
$ cd /tmp && git clone git clone https://github.com/bazelbuild/examples.git && cd examples/java-tutorial
$ bazel build //:ProjectRunner
```

### What operating system are you running Bazel on?

```bash
$ uname -sr
Linux 4.4.0-127-generic
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

repo: https://github.com/gvacaliuc/bazel/
branch: union-filesystem

**Comment by gvacaliuc** [comment]
Code in question:

```bash
$ git diff upstream/master origin/union-filesystem -- src
diff --git a/src/main/java/com/google/devtools/build/lib/runtime/BazelFileSystemModule.java b/src/main/java/com/google/devtools/build/lib/runtime/BazelFileSystemModule.java
index a734424..74482ab 100644
--- a/src/main/java/com/google/devtools/build/lib/runtime/BazelFileSystemModule.java
+++ b/src/main/java/com/google/devtools/build/lib/runtime/BazelFileSystemModule.java
@@ -13,6 +13,7 @@
 // limitations under the License.
 package com.google.devtools.build.lib.runtime;
 
+import com.google.common.collect.ImmutableMap;
 import com.google.devtools.build.lib.unix.UnixFileSystem;
 import com.google.devtools.build.lib.util.AbruptExitException;
 import com.google.devtools.build.lib.util.ExitCode;
@@ -21,6 +22,8 @@ import com.google.devtools.build.lib.vfs.DigestHashFunction;
 import com.google.devtools.build.lib.vfs.DigestHashFunction.DigestFunctionConverter;
 import com.google.devtools.build.lib.vfs.FileSystem;
 import com.google.devtools.build.lib.vfs.JavaIoFileSystem;
+import com.google.devtools.build.lib.vfs.PathFragment;
+import com.google.devtools.build.lib.vfs.UnionFileSystem;
 import com.google.devtools.build.lib.windows.WindowsFileSystem;
 import com.google.devtools.common.options.OptionsParsingException;
 import com.google.devtools.common.options.OptionsProvider;
@@ -55,6 +58,10 @@ public class BazelFileSystemModule extends BlazeModule {
     // The JNI-based UnixFileSystem is faster, but on Windows it is not available.
     return OS.getCurrent() == OS.WINDOWS
         ? new WindowsFileSystem(hashFunction)
-        : new UnixFileSystem(hashFunction);
+        : new UnionFileSystem(
+                ImmutableMap.of(
+                    PathFragment.create("/tmp"), 
+                    new UnixFileSystem(hashFunction)), 
+                new UnixFileSystem(hashFunction));
   }
 }
```

**Comment by mhlopko** [comment]
May I have a stupid question? What is this UnionFileSystem and where do we use it?

**Comment by benjaminp** [comment]
33700d64d665f1d708cedf0e6ca660d758392fb1 implies it's used in some tests, which much not be open source.

**Comment by gvacaliuc** [comment]
As far as I can tell the class isn't used anywhere in the Bazel codebase other than its [tests](https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/vfs/UnionFileSystemTest.java).  It's a FileSystem implementation that allows various path prefixes to point to different FileSystems, e.g. `/tmp/foo/bar -> UnixFileSystem`, `/tmp/foo/foo -> CustomFileSystemImpl, etc...

**Comment by mhlopko** [comment]
Well then we'll remove it, it's just a burden. I'll close this issue now. Sorry for the trouble.

**Comment by benjaminp** [comment]
It's not used in any Blaze tests?

**Comment by mhlopko** [comment]
Only in one, and I'm investigating whether the test actually needs onionfs at all.
