### ISSUE TITLE
Android: failure depending on libraries that define a resource with the same name

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#565]
Unlike _Gradle_ Android plugin, _Bazel_ will not merge resources from different modules if the modules are defining resources with the same name.
For example, consider the following dependency graph:

```
WORKSPACE
  |__ BUILD (app)
         |__ BUILD (lib1)
         |__ BUILD (lib2)
```

`lib1` defines string resource `R.string.title`, and so does `lib2`.

Under _Gradle_ merging will work by "overwriting" the resource from the lesser priority lib with the higher priority lib (e.g, `lib1:R.string.title` will be used in all cases instead of `lib2:R.string.title`).

When such case occurs, _Bazel_ will output the following error message (I removed some internal text from the pasted log):

```
INFO: From Processing resources:
Nov 04, 2015 1:34:29 PM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
/var/folders/6x/c5p2dxf13075rcdf4plh6x0c0000gn/T/tmp-deduplicated1035689210117006126/libs/paste/theme/glue/src/main/res/values/textappearance.glue.xml: Error: Duplicate resources: /var/folders/6x/c5p2dxf13075rcdf4plh6x0c0000gn/T/tmp-deduplicated1035689210117006126/libs/paste/theme/glue/src/main/res/values/textappearance.glue.xml:style/TextAppearance, /var/folders/6x/c5p2dxf13075rcdf4plh6x0c0000gn/T/tmp-deduplicated1035689210117006126/libs/paste/theme/cat/src/main/res/values/styles.xml:style/TextAppearance
    at com.android.ide.common.res2.DataSet.checkItems(DataSet.java:380)
    at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:239)
    at com.android.ide.common.res2.ResourceSet.loadFromFiles(ResourceSet.java:47)
    at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:197)
    at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:323)

ERROR: /xxx/libs/debugdialog/BUILD:1:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar ... (remaining 21 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //libs/paste/kitchensink:kitchensink failed to build
```

**Comment by menny** [comment]
@cgrushko FYI

**Comment by ahumesky** [comment]
Bazel resource merging doesn't have an idea of library priority, so it doesn't know which one to get the resource from. However, one way to work around this is to define the resource you want at the android_binary level, which takes precedence over the library.

**Comment by jin** [comment]
Now that Bazel has moved to aapt2 by default, and we'll be removing support for aapt (v1) soon, I'm closing this bug as obsolete.
