### ISSUE TITLE
Bazel 0.16.0 crashes with StackOverflow on Windows

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#5730]
After upgrading our Buildkite VMs to Bazel 0.16.0, we noticed that Bazel reproducibly crashes with a StackOverflow a few seconds after it starts building:

https://buildkite.com/bazel/bazel-bazel/builds/3702#a46f7545-e15e-4eca-bee2-904709ee4fed

I managed to repro this manually on the Windows VM and grabbed the jvm.out log:

```
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: c:users\philwo\_bazel~1\ozmjprom\java.log.lck
java.nio.file.NoSuchFileException: c:users\philwo\_bazel~1\ozmjprom\java.log.lck
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at java.logging/java.util.logging.FileHandler.openFiles(Unknown Source)
	at java.logging/java.util.logging.FileHandler.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at java.logging/java.util.logging.LogManager.createLoggerHandlers(Unknown Source)
	at java.logging/java.util.logging.LogManager.access$1300(Unknown Source)
	at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
	at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(Unknown Source)
	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(Unknown Source)
	at java.logging/java.util.logging.LogManager.access$1800(Unknown Source)
	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(Unknown Source)
	at java.logging/java.util.logging.Logger.getHandlers(Unknown Source)
	at java.logging/java.util.logging.Logger.log(Unknown Source)
	at java.logging/java.util.logging.Logger.doLog(Unknown Source)
	at java.logging/java.util.logging.Logger.log(Unknown Source)
	at java.logging/java.util.logging.Logger.info(Unknown Source)
	at com.google.devtools.build.lib.analysis.BlazeVersionInfo.logVersionInfo(BlazeVersionInfo.java:64)
	at com.google.devtools.build.lib.analysis.BlazeVersionInfo.setBuildInfo(BlazeVersionInfo.java:79)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:65)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/C:/Users/philwo/_bazel_philwo/install/d522db92d7621d404f960f24e49d0696/_embedded_binaries/A-server.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.StackOverflowError
	at java.base/java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.set(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Command-Accumulator-Thread-19"
```

@buchgr and my theory is that it must be caused by one of the last three cherry-picks that went into 0.16.0, because apparently 0.16.0rc3 was tested with downstream projects (which should have showed this issue), but 0.16.0rc4 (which became the final version) wasn't:

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds?branch=release-0.16.0

**Comment by philwo** [comment]
Interestingly, we also had one successful run with Bazel 0.16.0 on Windows: https://buildkite.com/bazel/bazel-bazel/builds/3703#4638243b-5e19-47ba-9cd6-806cf1f49248

**Comment by laszlocsomor** [comment]
The problem seems to be a bad path, see the 2nd line of your log:
```
java.nio.file.NoSuchFileException: c:users\philwo\_bazel~1\ozmjprom\java.log.lck
```
The backslash is missing after "c:". I'll look into it.

**Comment by laszlocsomor** [comment]
Haha, never mind, that has nothing to do with the StackOverflow :)

**Comment by philwo** [comment]
I downgraded our Windows VMs to 0.15.2 and now the same build that reproducibly crashed before seems to work fine.

**Comment by dslomov** [comment]
Any updates on this issue @philwo @buchgr @laszlocsomor ?

**Comment by laszlocsomor** [comment]
Sorry, I have no updates. Anyone else?

**Comment by meteorcloudy** [comment]
Update: I can also reproduce this error on my local machine with 0.16.0rc3

**Comment by meteorcloudy** [comment]
The failure is quite flaky. But with rerunning for multiple times, I can confirm it doesn't happen with 0.16.0rc1, but starting with 0.16.0rc2.
Since 0.16.0rc2 has only one cherry pick, it means 4c9a0c82d308d5df5c524e2a26644022ff525f3e is the culprit.
@buchgr @dslomov

**Comment by meteorcloudy** [comment]
Just tried 0.16.0rc1, it also failed with "Server terminated abruptly". So the culprit is even before the base commit of 0.16.0.

**Comment by meteorcloudy** [comment]
Now I suspect 4c9149d558161e7d3e363fb697f5852bc5742a36, because I can reproduce the same error at this commit.

**Comment by philwo** [comment]
@meteorcloudy I don't think that commit is in Bazel 0.16.0 (it uses OpenJDK 9), though?

**Comment by meteorcloudy** [comment]
I'm running bisect from 0.15.2's base commit to 0.16.0's base commit. It will take some time.

**Comment by buchgr** [comment]
@meteorcloudy if you want to rule out that the JDK9 is at fault, please use https://github.com/bazelbuild/bazel/pull/5786 which is the 0.16.0 code base with JDK8.

**Comment by meteorcloudy** [comment]
@buchgr Are we using JDK9 in 0.15.2?

**Comment by buchgr** [comment]
@meteorcloudy no

**Comment by c-parsons** [comment]
I'm a little unclear on the root cause here -- do we anticipate this is a JDK9 issue that would be fixed by the commits in #5760 ?

**Comment by cushon** [comment]
@c-parsons no, I think this is unrelated to #5760.

**Comment by meteorcloudy** [comment]
@c-parsons Yes, this issue is gone if we revert JDK version to 8. But @buchgr has figured out a fix to make it work with JDK9 as well. I was running a test for a Bazel version of 0.16.0 with his fix all night, it didn't fail after 100 times rerun. 

#5760 is irrelevant to this issue, I'm ccing you in the internal CL for fixing this.
