### ISSUE TITLE
incompatible_no_support_tools_in_action_inputs: Enforce action tools are passed using 'tools' and not 'inputs'.

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5826]
This is a tracking issue for offering a migration solution for
`--incompatible_no_support_tools_in_action_inputs`

This flag would change e.g. `ctx.actions.run()` and `ctx.actions.run_shell()` to enforce action tools are passed using 'tools' and not 'inputs'. (An error is thrown if any tools appear in 'inputs'

**Comment by dslomov** [comment]
@c-parsons when do you intend to flip the flag?

**Comment by laurentlb** [comment]
Still blocked by Tensorflow, rules_k8s, Cloud Robotics Core, Bazel Watcher, Baze;l Remote Cache. All of them have been pinged.

**Comment by laurentlb** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/67

@c-parsons Can you see how to fix Bazel? (looks like we need to update something in third-party)

I'll ping the other projects.

**Comment by meteorcloudy** [comment]
Looks like the latest protobuf release is still broken with this flag
```
pcloudy@pcloudy:~/workspace/tensorflow
$ bazelisk  build --config=opt //tensorflow/tools/pip_package:build_pip_package --incompatible_no_support_tools_in_action_inputs
INFO: Build option --incompatible_windows_escape_jvm_flags has changed, discarding analysis cache.
ERROR: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/rpc/python/kernel_tests/BUILD:13:1: in proto_gen rule //tensorflow/contrib/rpc/python/kernel_tests:test_example_proto_py_genproto: 
Traceback (most recent call last):
        File "/usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/rpc/python/kernel_tests/BUILD", line 13
                proto_gen(name = 'test_example_proto_py_genproto')
        File "/usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/d2f15366e3b15100d3593f2d595721a3/external/protobuf_archive/protobuf.bzl", line 137, in _proto_gen_impl
                ctx.actions.run(inputs = inputs, outputs = outs, arg...]), <3 more arguments>)
Found tool(s) 'bazel-out/host/bin/external/grpc/grpc_python_plugin' in inputs. A tool is an input with executable=True set. All tools should be passed using the 'tools' argument instead of 'inputs' in order to make their runfiles available to the action. This safety check will not be performed once the action is modified to take a 'tools' argument. To temporarily disable this check, set --incompatible_no_support_tools_in_action_inputs=false.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '//tensorflow/contrib/rpc/python/kernel_tests:test_example_proto_py_genproto' failed; build aborted
INFO: Elapsed time: 1.691s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (291 packages loaded, 6072 targets configured)
```
Is there a fix for that?

**Comment by lberki** [comment]
this breaks rules_scala: https://travis-ci.org/bazelbuild/rules_scala/builds/561953949

How was this flag flipped then?
