### ISSUE TITLE
Unable to run Android instrumentation tests on API 26

### ISSUE THREAD

**Issue by shiufai** [bazelbuild/bazel#5876]
### Description of the problem / feature request:

I tried to setup a basic instrumentation test, but hit an error when trying to target a generic_phone:google_26_x86_qemu2 device. I verified that I was able to launch the device manually with bazel run. Targetting a lower API also seems to work (e.g. android_23_x86_qemu2)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See attached [project.](url
[instrument_test.zip](https://github.com/bazelbuild/bazel/files/2284030/instrument_test.zip)
)

### What operating system are you running Bazel on?

Debian

### What's the output of `bazel info release`?

release 0.12.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

###  Have you found anything relevant by searching the web?

N/A

### Any other information, logs, or outputs that you want to share?

WARNING: AndroidDeviceTestSuite Native suite creation failed!
.E
Time: 0.006
There was 1 failure:
1) initializationError(com.google.android.apps.common.testing.suite.AndroidDeviceTestSuite)
java.lang.IllegalStateException: Adb call failed. Exit Code: 1. Args: [/usr/local/google/home/shiufai/.cache/bazel/_bazel_shiufai/b109b1a583e0a6bd274fc08d20edfd44/sandbox/linux-sandbox/2/execroot/__main__/bazel-out/k8-fastbuild/bin/mediarecorder/javatests/com/example/android/mediarecorder/perf_test.runfiles/__main__/../androidsdk/platform-tools/adb, -s, localhost:53029, shell, chmod, 666, /dev/graphics/fb0, /dev/fb0]
        at com.google.common.base.Preconditions.checkState(Preconditions.java:698)
        at com.google.android.apps.common.testing.broker.AdbController.makeCheckedCall(AdbController.java:844)
        at com.google.android.apps.common.testing.broker.AdbController.makeCheckedCall(AdbController.java:835)
        at com.google.android.apps.common.testing.broker.AdbController.makeAdbCall(AdbController.java:831)
        at com.google.android.apps.common.testing.broker.AdbController.makeAdbCall(AdbController.java:826)
        at com.google.android.apps.common.testing.broker.WrappedEmulatedDeviceBroker.leaseDevice(WrappedEmulatedDeviceBroker.java:294)
        at com.google.android.apps.common.testing.suite.AndroidDeviceTestSuite$Builder.makeNativeTestSuite(AndroidDeviceTestSuite.java:140)
        at com.google.android.apps.common.testing.suite.AndroidDeviceTestSuite$Builder.build(AndroidDeviceTestSuite.java:103)
        at com.google.android.apps.common.testing.suite.AndroidDeviceTestSuite.suite(AndroidDeviceTestSuite.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
        at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
        at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.createRunner(MemoizingRequest.java:48)
        at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.getRunner(MemoizingRequest.java:34)
        at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:51)
        at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:30)
        at com.google.testing.junit.runner.util.MemoizingSupplier.get(MemoizingSupplier.java:42)
        at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:92)
        at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

**Comment by jin** [comment]
I managed to reproduce this bug. There actually has been a fix in the test runner to work around this adb call even if it fails. Let me take a further look.

**Comment by jin** [comment]
cc @brettchabot

**Comment by jin** [comment]
Downprioritizing this as we'll be switching to the new Nitrogen-based test infrastructure.

**Comment by BenHenning** [comment]
> Downprioritizing this as we'll be switching to the new Nitrogen-based test infrastructure.

Hi @jin just checking on this--given that it's been a bit more than 3 years, should this issue be reprioritized?

**Comment by jin** [comment]
I don't think the bazel team has any resources for this right now, @ahumesky please correct me. Also I don't have any updates or news for the n2-based infra since I made that comment :(
