### ISSUE TITLE
Build Error for version 0.16.0 - KeyError: 'getpwuid(): uid not found:

### ISSUE THREAD

**Issue by YuMan-Tam** [bazelbuild/bazel#5878]
### Description of the problem / feature request:

While running ```./compile.sh``` for the version ```0.16.0-dist```, the process was stopped by the error ```KeyError: 'getpwuid(): uid not found: ```. I confirmed that the variable ```HOME``` was set and there is no such error when I ran the exact version of ```python``` in the interactive mode.

I was able to proceed without error after modifying the ```expanduser``` function in ```posixpath.py```.

Original:

 ```
 if 'HOME' not in os.environ:
     import pwd
     userhome = pwd.getpwuid(os.getuid()).pw_dir
else:
     userhome = os.environ['HOME']
```

Modified:

 ``` 
if "HOME" not in os.environ:
     userhome = '/sasdata/ra/user/john.doe'
else:
     userhome = os.environ['HOME']
```
This is essentially a hack that bypass the error, but I have no idea why the build script cannot retrieve the ```HOME``` variable which gave the error.  I understand I do not suppose to modify ```posixpath.py```.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash ./compile.sh```

### What operating system are you running Bazel on?

```Red Hat Enterprise Linux Server release 6.10 (Santiago)```

### Any other information, logs, or outputs that you want to share?

```[1A[K[31m[1mERROR: [0m/sasdata/ra/user/john.doe/tmp/tmp/bazel-20180813-821-eybopa/sources/src/BUILD:235:1: Executing genrule //src:embedded_tools_nojdk failed (Exit 1): bash failed: error executing command 
  (cd /sasdata/ra/user/john.doe/tmp/tmp/bazel_VSyrAUGk/out/execroot/io_bazel && \
  exec env - \
    PATH=/sasdata/ra/user/john.doe/.local/brew/bin:/sasdata/ra/user/john.doe/.local/brew/Library/Homebrew/shims/linux/super:/sasdata/ra/user/john.doe/.local/brew/opt/binutils/bin:/usr/bin:/bin:/usr/sbin:/sbin:/sasdata/ra/user/john.doe/.local/brew/opt/gcc/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/src/create_embedded_tools "bazel-out/k8-opt/genfiles/src/embedded_tools_nojdk.zip" bazel-out/k8-opt/bin/src/embedded_tools_nojdk.params')
[32m[2,106 / 2,266] [0m 4 actions running
    Executing genrule //src:embedded_tools_nojdk; 1s local
    .../com/google/devtools/build/lib/skylarkbuildapi/config:config; 0s worker
    .../com/google/devtools/build/lib/skylarkbuildapi/apple:apple; 0s worker
    .../devtools/build/lib/skylarkbuildapi/repository:repository; 0s worker

Traceback (most recent call last):
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/site.py", line 539, in <module>
    main()
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/site.py", line 521, in main
    known_paths = addusersitepackages(known_paths)
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/site.py", line 231, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/sasdata/ra/user/john.doe/.local/brew/Cellar/python@2/2.7.15_1/lib/python2.7/sysconfig.py", line 525, in get_config_var
    return get_config_vars().get(name)
  File "/sasdata/ra/user/john.doe/.local/brew/Cellar/python@2/2.7.15_1/lib/python2.7/sysconfig.py", line 482, in get_config_vars
    _CONFIG_VARS['userbase'] = _getuserbase()
  File "/sasdata/ra/user/john.doe/.local/brew/Cellar/python@2/2.7.15_1/lib/python2.7/sysconfig.py", line 192, in _getuserbase
    return env_base if env_base else joinuser("~", ".local")
  File "/sasdata/ra/user/john.doe/.local/brew/Cellar/python@2/2.7.15_1/lib/python2.7/sysconfig.py", line 178, in joinuser
    return os.path.expanduser(os.path.join(*args))
  File "/sasdata/ra/user/john.doe/.local/brew/bin/../Cellar/python@2/2.7.15_1/lib/python2.7/posixpath.py", line 262, in expanduser
    userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: 12345678'

**Comment by aiuto** [comment]
That looks like the user id you are running as is not in /etc/password.
Similar issue happens lot: 
https://www.google.com/search?q=getpwuid+%27uid+not+found%27&btnK=Google+Search&oq=getpw

The specific uid in your case (12345678) looks suspiciously like a synthetic one, is there something else strange about your environment? 
You could also try:
   HOME='/sasdata/ra/user/john.doe' bash ./compile.sh
do work around the fake uid.

**Comment by YuMan-Tam** [comment]
Thank you for the suggestion, which also worked. I am not sure if I have access to /etc/password.

This means this is likely not a system issue instead of ```Bazel``` issue. There will also a similar failure when I use ```Bazel``` to build ```scripts:bash_completion```. After I add the flag ```--action_env=USER```, the build would proceed. I am closing the issue -- unless there is going to be a fix to address this minor inconvenience. I really appreciate your time.
