### ISSUE TITLE
Build Failure: /lib64/libc.so.6: version `GLIBC_2.14' not found (with JAVA_HOME and CC set)

### ISSUE THREAD

**Issue by YuMan-Tam** [bazelbuild/bazel#5893]
### Description of the problem / feature request:

After building ```Bazel``` with ```bash ./compile.sh``` without errors, I proceed to use ```Bazel``` to build ```scripts:bash_completion```. During the process, I encounter the error:

```_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found```

Here's longer log:

```
JNI initialization failed: /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so).  Possibly your installation has been corrupted.
java.lang.UnsatisfiedLinkError: /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
        at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:50)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1193)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1182)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1175)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:810)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:636)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:66)
ERROR: <unknown> crash in async thread:
java.lang.UnsatisfiedLinkError: /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/generate_bash_completion.SJbgCMxy/root/install/debd9f77f563bf647ce0b8462748a9e6/_embedded_binaries/libunix.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
        at com.google.devtools.build.lib.unix.ProcessUtils.<clinit>(ProcessUtils.java:28)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:50)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1193)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1182)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1175)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:810)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:636)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:66)
```
I did some research online (see below) without success and not sure how to proceed. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 ```./output/bazel --output_user_root /sasdata/ra/user/john.doe/tmp/tmp/bazel-20180814-29476/output_user_root build  --distdir=/sasdata/ra/user/john.doe/tmp/bazel-pkgs --action_env=USER --scripts:bash_completion```

The flags does not seem to affect the error.

### What operating system are you running Bazel on?

```Red Hat Enterprise Linux Server release 6.10 (Santiago)```

### What's the output of `bazel info release`?

``` release 0.16.0- (@not-git)```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I use ```linuxbrew``` to build ```jdk8``` and set ```JAVA_HOME``` to the ```java``` bin. Running ```java -version``` confirms that I am running version 1.8.  Then I extract the zip file for ```0.16.0-dist``` and run ```bash ./compile.sh```.  I tried two ways: 1) without the ```CC``` flag (system ```gcc 4.4```), and 2) with the ```CC``` flag (linuxbrew ```gcc 5.5```). Both produced the same error. The path variable pointed to ```~/.local/brew/bin```. 

###  Have you found anything relevant by searching the web?

There have been similar issues:

 1) https://github.com/bazelbuild/bazel/issues/4374 - Setting ```JAVA_HOME``` did not help.
 2) https://github.com/bazelbuild/bazel/issues/1474 - Setting ```CC``` did not help either. Export LD_LIBRARY_PATH would give ```segmentation fault (core dumped)```, but I believe it might not be relevant for this issue.

I can confirm via ```strace java -version``` that gave a line:

```open("/sasdata/ra/user/john.doe/.local/brew/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3```

indicating that ```java``` is using the self-installed ```glibc``` (version ```2.23```). The system itself has 
 its own ```glibc``` (version ```2.12```), but I do not know how to verify if ```Bazel``` somehow uses the old version.

**Comment by YuMan-Tam** [comment]
Upon doing further research, I also found similar issues here: https://github.com/bazelbuild/bazel/issues/760. 

I tried to follow the thread and replace all paths in ```./tools/cpp/CROSSTOOL``` and add the linker flags ```linker_flag: "-Wl,-R/sasdata/ra/user/john.doe/.local/brew/lib/". But then I encountered the exact error.

**Comment by YuMan-Tam** [comment]
I believe I now understand the root cause of the error.

When I run ```bazel build scripts:bash_completion``` (whether or not using the ```--host_javabase``` flag), the build process will use the downloaded ```open-jdk``` tool, which is configured to be linked with ```/lib64/libc.so.6```. I wonder if there's a way to force ```bazel``` to use ```$JAVA_HOME``` or allow me to configure ```open-jdk``` with something like:

```--host_linkopt="-Wl,--dynamic-linker=/sasdata/ra/user/john.doe/.local/brew/lib/ld-linux-x86-64.so.2"```?

**Comment by YuMan-Tam** [comment]
Update:

I found a fix. Insert the following to ```./scripts/generate_bash_completion.sh```:

```javabase=/sasdata/ra/user/john.doe/.loca/brew/opt/jdk```

This is certainly an ugly hack. If I am correct, setting ```--host_javabase``` and/or ```--javabase``` should achieve the same effect. However, I have no luck thus far. I tried to add the following to ```./BUILD```:

```
java_runtime(
    name =  "jdk_local",
    java_home = "/sasdata/ra/user/john.doe/.loca/brew/opt/jdk",
    visibility = ["//visibility:public"]
)
```

and ```--javabase=:jdk_local```

But then I encounter the same ```glibc``` error. It seems to me that the ```javabase``` variable somehow did not propogate to the ```javabase``` variable in ```./scripts/generate_bash_completion.sh```. What did I do wrong here?

**Comment by aiuto** [comment]
I am sending this to EngProd right now because it seems to be about building bazel. But maybe the Java rules people are the right group.

**Comment by nirvana-msu** [comment]
In case it helps someone, here's a recipe on how one could build a recent Bazel version on RHEL 6.

It is largely based on the [building bazel on CentOS-6](https://gist.github.com/truatpasteurdotfr/d541cd279b9f7bf38ce967aa3743dfcb) gist using `devtoolset-7`, however starting from a certain Bazel release, the build was failing. The missing part was to specify `BAZEL_LINKLIBS=-l%:libstdc++.a` as was pointed out [here](https://github.com/tensorflow/tensorflow/issues/35867#issuecomment-578998683):

```bash
yum -y install wget which findutils tar gzip zip unzip git zlib-devel
yum -y install java-1.8.0-openjdk-devel
yum -y install centos-release-scl-rh
yum -y install devtoolset-7-gcc devtoolset-7-gcc-c++ devtoolset-7-binutils

BAZEL_VERSION=3.2.0
export PATH=/opt/python/cp36-cp36m/bin:$PATH   # some Python 3; this path is for manylinux docker image
pushd ~
  wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-dist.zip
  unzip -d /tmp/bazel-${BAZEL_VERSION}-dist  bazel-${BAZEL_VERSION}-dist.zip && \
  /bin/rm bazel-${BAZEL_VERSION}-dist.zip

  echo "cd /tmp/bazel-${BAZEL_VERSION}-dist && BAZEL_LINKLIBS=-l%:libstdc++.a bash ./compile.sh && cp output/bazel /usr/local/bin" | scl enable devtoolset-7 bash

  /bin/rm -rf  /tmp/bazel-${BAZEL_VERSION}-dist
popd
```
