### ISSUE TITLE
Race condition in HttpBlobStore.releaseUploadChannel

### ISSUE THREAD

**Issue by geoffmaddox** [bazelbuild/bazel#5952]
### Description of the problem / feature request:
Builds can fail with `java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{...}'  ...
Caused by: java.util.NoSuchElementException: io.netty.handler.codec.http.HttpRequestEncoder` when using the HttpBlobStore to cache builds.

It appears a race condition can occur in HttpBlobStore.releaseUploadChannel() when ChannelHandlerContext is closed by HttpUploadHandler.channelRead0 (when not keeping connection alive). Because ChannelHandlerContext.close runs asynchronously and closes all pipelines in reverse order (before the channel is marked as closed), HttpBlobStore.releaseUploadChannel() can be executed while channel is still open and handlers are being removed, causing an exception to be thrown by the ch.pipeline().remove(X) calls.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The issue is a race condition, so it is difficult to reproduce. Use a local HTTP cache that does not keep connections alive and `bazel clean` before starting a new build. 

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.16.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
b942140053981c4da5b2101d5f3a608ac25e7829
3e0024b5771539e6dd860c93cd65a603a0986506

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//foo-service:play-routes BuildConfigurationValue.Key[...] false, actionIndex=0}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]foo-service/play/routes/play_routes')
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:482)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:335)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: io.netty.handler.codec.http.HttpRequestEncoder
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1107)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:449)
    at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.releaseUploadChannel(HttpBlobStore.java:252)
    at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:468)
    at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:426)
    at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadStream(SimpleBlobStoreActionCache.java:183)
    at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:148)
    at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:126)
    at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:186)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:109)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
    at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
    at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:287)
    at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:294)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:992)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:924)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:119)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:768)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:723)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:461)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:512)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:227)
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:405)
FAILED: Build did NOT complete successfully```

**Comment by geoffmaddox** [comment]
I'm about to submit a pull request which fixes this issue.

**Comment by geoffmaddox** [comment]
Here's the pull request: https://github.com/bazelbuild/bazel/pull/5953
