### ISSUE TITLE
Gerrit fails on Bazel@HEAD on JDK9

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#5962]
Trying to build Gerrit on JDK9 on Bazel@HEAD (398478cc334283a6a9c8740f8ac81b5962e5cba7) is failing first with missing dependency in `rules_closure`, that is tracked here: [1] and fixed here: [2].

After the aforementioned fix, trying to build Gerrit on JDK9 is failing with: [3]. That seems to be autovalue related:

```
[...]
ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/server/BUILD:21:1: Building java/com/google/gerrit/server/libserver-class.jar (964 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
Note: Multiple elements named 'javax.annotation.processing.Generated' in modules 'java.base, java.compiler, jdk.jdi, jdk.attach, jdk.jdwp.agent, jdk.management, java.management, java.xml, jdk.sctp, jdk.jartool, jdk.accessibility, java.desktop, java.datatransfer, java.prefs, jdk.security.jgss, java.security.sasl, java.logging, java.security.jgss, java.naming, jdk.security.auth, jdk.unsupported, jdk.httpserver, jdk.dynalink, jdk.xml.dom, jdk.jsobject, jdk.scripting.nashorn, java.scripting, jdk.jconsole, jdk.management.agent, java.management.rmi, java.rmi, jdk.net, java.sql.rowset, java.sql, java.instrument, java.xml.crypto' were found by javax.lang.model.util.Elements.getTypeElement.
Note: Multiple elements named 'java.sql.Timestamp' in modules 'java.base, java.sql, jdk.jdi, jdk.attach, jdk.jdwp.agent, jdk.management, java.management, jdk.javadoc, jdk.compiler, java.compiler, java.xml, jdk.sctp, jdk.jartool, jdk.accessibility, java.desktop, java.datatransfer, java.prefs, jdk.security.jgss, java.security.sasl, java.logging, java.security.jgss, java.naming, jdk.jshell, jdk.security.auth, jdk.unsupported, jdk.httpserver, jdk.dynalink, jdk.xml.dom, jdk.jsobject, jdk.scripting.nashorn, java.scripting, jdk.jconsole, jdk.management.agent, java.management.rmi, java.rmi, jdk.net, java.instrument, java.xml.crypto' were found by javax.lang.model.util.Elements.getTypeElement.
java/com/google/gerrit/server/ReviewerStatusUpdate.java:24: error: @AutoValue processor threw an exception: java.lang.IllegalStateException: Could not find referenced class java.sql.Timestamp
public abstract class ReviewerStatusUpdate {
                ^
  	at autovalue.shaded.com.google$.common.base.$Preconditions.checkState($Preconditions.java:582)
  	at com.google.auto.value.processor.TypeEncoder$TypeRewriter.classForName(TypeEncoder.java:393)
  	at com.google.auto.value.processor.TypeEncoder$TypeRewriter.findReferencedClasses(TypeEncoder.java:385)
  	at com.google.auto.value.processor.TypeEncoder$TypeRewriter.rewrite(TypeEncoder.java:347)
  	at com.google.auto.value.processor.TypeEncoder.decode(TypeEncoder.java:127)
  	at com.google.auto.value.processor.TypeEncoder.decode(TypeEncoder.java:120)
  	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:219)
  	at com.google.auto.value.processor.AutoValueOrOneOfProcessor.process(AutoValueOrOneOfProcessor.java:311)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:964)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:881)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(JavacProcessingEnvironment.java:110)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1202)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1311)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1250)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:928)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:111)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:122)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:125)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:133)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
java.lang.RuntimeException: java.lang.IllegalStateException: Could not find referenced class java.sql.Timestamp
```

Reproducer is here: [4].

* [1] https://github.com/bazelbuild/bazel/issues/5961
* [2] https://github.com/bazelbuild/rules_closure/pull/282
* [3] http://paste.openstack.org/show/728631
* [4] https://gerrit-review.googlesource.com/c/gerrit/+/193830

//CC @cushon @eamonnmcmanus @ronshapiro

**Comment by cushon** [comment]
This is probably also https://bugs.openjdk.java.net/browse/JDK-8209865.

**Comment by cushon** [comment]
This has the same root cause as #5961.

**Comment by davido** [comment]
From the reported bug https://bugs.openjdk.java.net/browse/JDK-8209865 I see that using Java 10 with `--release 9` is affected, so I tried to build gerrit with Bazel@HEAD using Java 10. But it's failing as well:

```
$ java -fullversion
openjdk full version "10.0.2+13-suse-1.1-x8664"

$ b9 build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 :release
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:98:7: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.14.0.
ERROR: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_tools/tools/jdk/BUILD:162:1: no such package '@local_jdk//': Expected directory at /usr/lib64/jvm/java but it does not exist. and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Analysis of target '//:release' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.249s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: java/com/google/gerrit/extensions ... (4 packages)
```
Should I file a different issue or is it a know bug?

**Comment by cushon** [comment]
The `no such package '@local_jdk//'` error is not familiar, do you mind starting another bug for that one and providing a repro?
