### ISSUE TITLE
Setting BAZEL_LINKOPTS to the empty string causes Bazel to crash

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#5973]
### Description of the problem / feature request:

When building a `cc_binary` with the `BAZEL_LINKOPTS` environment variable set to the empty string, Bazel crashes.

```
$ BAZEL_LINKOPTS= bazel build :hello
____Loading complete.  Analyzing...
____Loading package: @local_config_cc//
____Build options have changed, discarding analysis cache.
____Found 1 target...
bazel: Entering directory `/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/2aec36fc73a39e5bf974d138741bbbc1/execroot/__main__/'
bazel: Leaving directory `/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/2aec36fc73a39e5bf974d138741bbbc1/execroot/__main__/'
Target //:hello failed to build
Use --verbose_failures to see the command lines of failed build steps.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:hello BuildConfigurationValue.Key[07268499d71d5934dbb9817e10a7700e] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]hello-2.params')
____Elapsed time: 0.540s, Critical Path: 0.00s
____0 processes.
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:hello BuildConfigurationValue.Key[07268499d71d5934dbb9817e10a7700e] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]hello-2.params')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.extractArgumentsForDynamicLinkParamFile(LinkCommandLine.java:306)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.splitCommandline(LinkCommandLine.java:196)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.access$100(LinkCommandLine.java:43)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine$ParamFileCommandLine.arguments(LinkCommandLine.java:241)
	at com.google.devtools.build.lib.actions.CommandLine.addToFingerprint(CommandLine.java:57)
	at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction.computeKey(ParameterFileWriteAction.java:161)
	at com.google.devtools.build.lib.actions.AbstractAction.getKey(AbstractAction.java:291)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:290)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:249)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:539)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:389)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:hello BuildConfigurationValue.Key[07268499d71d5934dbb9817e10a7700e] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]hello-2.params')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.extractArgumentsForDynamicLinkParamFile(LinkCommandLine.java:306)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.splitCommandline(LinkCommandLine.java:196)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.access$100(LinkCommandLine.java:43)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine$ParamFileCommandLine.arguments(LinkCommandLine.java:241)
	at com.google.devtools.build.lib.actions.CommandLine.addToFingerprint(CommandLine.java:57)
	at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction.computeKey(ParameterFileWriteAction.java:161)
	at com.google.devtools.build.lib.actions.AbstractAction.getKey(AbstractAction.java:291)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:290)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:249)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:539)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:389)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
```

### what underlying problem are you trying to solve with this feature?

@ixdy reported this originally in bazelbuild/rules_go#1681. He was trying to link a Go binary (which uses link flags from the C/C++ toolchain) without the `-lstdc++` flag, which is added automatically when `BAZEL_LINKOPTS` is not set.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD.bazel

```
cc_binary(
    name = "hello",
    srcs = ["hello.c"],
)
```

hello.c

```
int main() {return 0;}
```

Run this command:

```
BAZEL_LINKOPTS= bazel build :hello
```

### What operating system are you running Bazel on?

Linux amd64

### What's the output of `bazel info release`?

0.17.1rc1

**Comment by beasleyr-vmw** [comment]
@lberki filed a duplicate as #7301 and resolved via 41f0657, so I think we can close this now.
