### ISSUE TITLE
Expose timeout time to users of git_repository

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6029]
### Description of the problem / feature request:

bazel build fails on timeout of cloning git repositories

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to be able to supply a longer timeout

cc @aehlig would you open for a very simple small PR to expose this attribute?

**Comment by aehlig** [comment]
> cc @aehlig would you open for a very simple small PR to expose this attribute?

Yes. feel free to send a pull request.

**Comment by dio** [comment]
@ittaiz I'm interested to know the solution for this. Do you have one? Thanks!

**Comment by ittaiz** [comment]
Hi,
Sorry for the late reply. I don’t have one since @aehlig added another awesome feature of a global timeout factor which allows you to just give a factor for the download of repository rules. So one can give a x3 factor for the first long download. I think this is still valuable but not as urgent for us now.

**Comment by bedbad** [comment]
Is there a solution to this as of now?

**Comment by fmeum** [comment]
You can try setting `--experimental_scale_timeouts` to a value higher than `1.0`.

**Comment by Michaelxu2022** [comment]
We had the same git timeout problem when nfs io was high. Is there a solution?

ERROR: error loading package '': Encountered error while reading extension file 'common.bzl': no such package '@common//': Traceback (most recent call last):
	File "/projects_temp/jenkins_hw/workspace/libra_fifo/tmp_libra_fifo/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/projects_temp/jenkins_hw/workspace/libra_fifo/tmp_libra_fifo/external/bazel_tools/tools/build_defs/repo/git.bzl", line 73, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning common:
Timed out; also encountered an error while attempting to retrieve output
ERROR: error loading package '': Encountered error while reading extension file 'common.bzl': no such package '@common//': Traceback (most recent call last):
	File "/projects_temp/jenkins_hw/workspace/libra_fifo/tmp_libra_fifo/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/projects_temp/jenkins_hw/workspace/libra_fifo/tmp_libra_fifo/external/bazel_tools/tools/build_defs/repo/git.bzl", line 73, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning common:
Timed out; also encountered an error while attempting to retrieve output
INFO: Elapsed time: 642.391s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
