### ISSUE TITLE
Docker Build rule fails with internal error when using data_path.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#604]
Error:
```
ERROR: /Users/endobson/tmp/bazel-project/BUILD:9:1: in docker_build_ rule //:my_first_docker_layer:
Traceback (most recent call last):
        File "/Users/endobson/tmp/bazel-project/BUILD", line 9
                docker_build_(name = 'my_first_docker_layer')
        File "/usr/local/lib/bazel/base_workspace/tools/build_defs/docker/docker.bzl", line 221, in _docker_build_impl
                _build_layer(ctx)
        File "/usr/local/lib/bazel/base_workspace/tools/build_defs/docker/docker.bzl", line 88, in _build_layer
                _compute_data_path(ctx.outputs.out, ctx.attr.data_path)
        File "/usr/local/lib/bazel/base_workspace/tools/build_defs/docker/docker.bzl", line 77, in _compute_data_path
                data_path[0]
List index out of range (index is 0, but list has 0 elements).
ERROR: Analysis of target '//:my_first_docker_layer' failed; build aborted.
INFO: Elapsed time: 0.294s
```

Build File:
```
# This is my first build file
load("/tools/build_defs/docker/docker", "docker_build")

filegroup(
  name = "racket_files",
  srcs = glob(["racket/**/*"])
)

docker_build(
  name = "my_first_docker_layer",
  files = glob(["racket/**/*"]),
  data_path = "./"
)
```

When data_path was "" or not provided it worked, but adding it as "./" gave the error.

**Comment by damienmg** [comment]
What about when data_path is simply "."?

**Comment by endobson** [comment]
data_path being "." is what eventually worked for me.
