### ISSUE TITLE
Bazel crash due to --incompatible_disallow_filetype

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6158]
### Description of the problem / feature request:

The following program hard crashes bazel:
Source from: https://github.com/endobson/yaspl2/tree/broken-filetype
```
$ ~/proj/bazel/bazel-bin/src/bazel test //... --incompatible_disallow_filetype
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:7:24: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:8:23: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:231:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 228
		attr.label(mandatory = True, single_file = Tr..., ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 231, in attr.label
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:252:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 251
		attr.label_list(allow_files = racket_src_file_ty..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 252, in attr.label_list
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:282:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 281
		attr.label_list(allow_files = racket_src_file_ty..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 282, in attr.label_list
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:315:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 311
		rule(implementation = _bin_impl, test =..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 315, in rule
		_racket_bin_attrs
name '_racket_bin_attrs' is not defined (did you mean '_racket_bundle_attrs'?)
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:321:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 318
		rule(implementation = _bin_impl, execut..., ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 321, in rule
		_racket_bin_attrs
name '_racket_bin_attrs' is not defined (did you mean '_racket_bundle_attrs'?)
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:329:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 324
		rule(implementation = _lib_impl, output..."}, ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 329, in rule
		_racket_lib_attrs
name '_racket_lib_attrs' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:337:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 332
		rule(implementation = _bootstrap_lib_..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 337, in rule
		_racket_bootstrap_lib_attrs
name '_racket_bootstrap_lib_attrs' is not defined
ERROR: error loading package 'bootstrap': Extension file 'racket.bzl' has errors
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:33:19: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 25
		rule(implementation = _bin_impl, output..."}, <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 32, in rule
		attr.label_list(allow_files = FileType([".prim"]..., <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 33, in attr.label_list
		FileType([".prim"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:71:19: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 64
		rule(implementation = _lib_impl, output..."}, ...")})
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 70, in rule
		attr.label_list(allow_files = FileType([".prim"]..., <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 71, in attr.label_list
		FileType([".prim"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package 'libraries/yaspl/runtime': Extension file 'libraries/prim-language/prim-language.bzl' has errors
ERROR: error loading package 'tools': Extension file 'racket.bzl' has errors
ERROR: error loading package 'libraries/prim-language/examples': Extension file 'libraries/prim-language/prim-language.bzl' has errors
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:126)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:106)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1.206s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:126)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:106)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:126)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:106)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
FAILED: Build did NOT complete successfully (12 packages loaded)
```

### What operating system are you running Bazel on?

macOS 

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From tip of master

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
eb817074c25ec49585152e9f01ff37dad8e03094
eb817074c25ec49585152e9f01ff37dad8e03094

**Comment by laurentlb** [comment]
Sorry for the delay! I have just tried on Linux with Bazel 0.18, but I get an unrelated error (`missing input file '//prebuilt:saved/library_compiler'`).

Can you tell me if you can reproduce the crash with Bazel 0.18?
If so, does it crash also with `bazel build --nobuild //... --incompatible_disallow_filetype`?

**Comment by endobson** [comment]
The missing input file is because you need need to prebuild the compiler via `scripts/prebuild-binaries.sh` or build with `--define yaspl_bootstrap=true` to actually build the main compiler using the bootstrap compiler. My bad for missing that in the instructions.

It looks like it is still broken with 0.18.0.

```
$ ~/proj/bazel-release/bazel-0.18.0-darwin-x86_64  build --nobuild //... --incompatible_disallow_filetype --define yaspl_bootstrap=true

Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:7:24: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:8:23: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:231:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 228
		attr.label(mandatory = True, single_file = Tr..., ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 231, in attr.label
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:252:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 251
		attr.label_list(allow_files = racket_src_file_ty..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 252, in attr.label_list
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:282:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 281
		attr.label_list(allow_files = racket_src_file_ty..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 282, in attr.label_list
		racket_src_file_type
name 'racket_src_file_type' is not defined
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:315:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 311
		rule(implementation = _bin_impl, test =..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 315, in rule
		_racket_bin_attrs
name '_racket_bin_attrs' is not defined (did you mean '_racket_bundle_attrs'?)
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:321:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 318
		rule(implementation = _bin_impl, execut..., ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 321, in rule
		_racket_bin_attrs
name '_racket_bin_attrs' is not defined (did you mean '_racket_bundle_attrs'?)
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:329:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 324
		rule(implementation = _lib_impl, output..."}, ...)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 329, in rule
		_racket_lib_attrs
name '_racket_lib_attrs' is not defined
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:33:19: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 25
		rule(implementation = _bin_impl, output..."}, <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 32, in rule
		attr.label_list(allow_files = FileType([".prim"]..., <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 33, in attr.label_list
		FileType([".prim"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:71:19: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 64
		rule(implementation = _lib_impl, output..."}, ...")})
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 70, in rule
		attr.label_list(allow_files = FileType([".prim"]..., <2 more arguments>)
	File "/Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl", line 71, in attr.label_list
		FileType([".prim"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl:337:11: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 332
		rule(implementation = _bootstrap_lib_..., <2 more arguments>)
	File "/private/var/tmp/_bazel_endobson/f851d7f6c7010ae7d7a3db153bed36de/external/minimal_racket/racket.bzl", line 337, in rule
		_racket_bootstrap_lib_attrs
name '_racket_bootstrap_lib_attrs' is not defined
ERROR: error loading package 'bootstrap': Extension file 'racket.bzl' has errors
ERROR: error loading package 'tools': Extension file 'racket.bzl' has errors
ERROR: error loading package 'libraries/prim-language/examples': Extension file 'libraries/prim-language/prim-language.bzl' has errors
ERROR: error loading package 'libraries/yaspl/runtime': Extension file 'libraries/prim-language/prim-language.bzl' has errors
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1.174s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2286)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
FAILED: Build did NOT complete successfully (12 packages loaded)
```

**Comment by laurentlb** [comment]
I still haven't been able to reproduce the crash.

```
$ git co broken-filetype
Switched to branch 'broken-filetype'
Your branch is up to date with 'origin/broken-filetype'.

$ USE_BAZEL_VERSION=0.18.0 bazelisk build --nobuild //... --incompatible_disallow_filetype --define yaspl_bootstrap=true
...
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/f83b0a8f812c37319a7ce3194fc1cea8/external/minimal_racket/racket.bzl", line 337, in rule
		_racket_bootstrap_lib_attrs
name '_racket_bootstrap_lib_attrs' is not defined
ERROR: error loading package 'bootstrap': Extension file 'racket.bzl' has errors
INFO: Elapsed time: 0.240s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: web-assembly ... (5 packages)
```

I suppose you've found a workaround and you're not blocked by that, right?

**Comment by endobson** [comment]
I never was blocked, this was just a bug about getting a hard crash versus just an error message. It looks like now this just gives the error message as expected.
