### ISSUE TITLE
Runtime exception on Windows when evaluating `BazelCcProtoAspect` nodes

### ISSUE THREAD

**Issue by scottminor-google** [bazelbuild/bazel#6171]
### Description of the problem / feature request:

Build causes a RuntimeException on Windows; this appears to happen when one `proto_library` rule depends on another `proto_library` rule.

#### Command 
`bazel.exe build //some_proto/...`

#### Output
```
Loading: 
Loading: 0 packages loaded
Analyzing: 2 targets (4 packages loaded)
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '[]#BazelCcProtoAspect BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] //some_proto:foo_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false {}' (requested by nodes '//some_proto:foo_cc_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false')
INFO: Elapsed time: 2.187s
INFO: 0 processes.
Analyzing: 2 targets (12 packages loaded)
FAILED: Build did NOT complete successfully (12 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#BazelCcProtoAspect BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] //some_proto:foo_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false {}' (requested by nodes '//some_proto:foo_cc_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:916)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:923)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:713)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:462)
	at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect$Impl.<init>(CcProtoAspect.java:192)
	at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect.create(CcProtoAspect.java:102)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:411)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:613)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:460)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#BazelCcProtoAspect BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] //some_proto:foo_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false {}' (requested by nodes '//some_proto:foo_cc_proto BuildConfigurationValue.Key[3213e4172e1985f81933e1323d6f6468] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:916)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:923)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:713)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:462)
	at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect$Impl.<init>(CcProtoAspect.java:192)
	at com.google.devtools.build.lib.rules.cpp.proto.CcProtoAspect.create(CcProtoAspect.java:102)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:411)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:613)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:460)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
FAILED: Build did NOT complete successfully (12 packages loaded)
```

#### `WORKSPACE`
```
http_archive(
    name = "com_google_protobuf",
    sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
    strip_prefix = "protobuf-3.5.0",
    urls = ["https://github.com/google/protobuf/archive/v3.5.0.zip"],
)
```

#### `some_proto/BUILD`
```
cc_proto_library(
	name = "foo_cc_proto",
	deps = [":foo_proto"],
)

proto_library(
	name = "foo_proto",
	srcs = [":foo.proto"],
	deps = ["//some_other_proto:bar_proto"],
)
```

#### `some_proto/foo.proto`
```
syntax = "proto3";

import "some_other_proto/bar.proto";

message Foo {
	Bar bar = 1;
}
```

#### `some_other_proto/BUILD`
```
package(default_visibility=["//visibility:public"])

cc_proto_library(
	name = "bar_cc_proto",
	deps = [":bar_proto"],
)

proto_library(
	name = "bar_proto",
	srcs = ["bar.proto"],
)
```

#### `some_other_proto/bar.proto`
```
syntax = "proto3";

message Bar {
	int32 baz = 1;
}
```

### What operating system are you running Bazel on?

Windows Server 2012 R2 Datacenter

### What's the output of `bazel info release`?

`release 0.17.1`

###  Have you found anything relevant by searching the web?

I seem to be hitting [this precondition](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/LibrariesToLinkCollector.java#L290) which was introduced in [this commit](https://github.com/bazelbuild/bazel/commit/4e42e1767d1752d6e3fde78a6b184c2231b12ebb).

Symptoms are similar to #6169, and this may be a dupe. However:
* I am able to build protoc, even when updating the version from 3.5.0 in the WORKSPACE listed above to 3.6.1 as mentioned in #6169, so actually I am unable to reproduce #6169 
* This issue manifests when analyzing `proto_library` rules that depend on each other, not protoc itself.

### Any other information, logs, or outputs that you want to share?

* bazel 0.16.1 builds the above fine, but 0.17.1 does not.
* bazel 0.17.1 can build protos with no dependencies (`bazel.exe build //some_other_proto/...` is fine); asking bazel to analyze a `proto_library` with another `proto_library` rule in its `deps` attribute seems to cause the issue.

**Comment by scottminor-google** [comment]
I can reproduce the above example with Windows 10, `release 0.17.2` and protobuf v3.6.1. Is there anything I can do to troubleshoot this issue?
