### ISSUE TITLE
Build Android on Windows: Bazel_tools//src/main/native/windows:windows_jni.dll' failed (Exit -1) 

### ISSUE THREAD

**Issue by Kadanza** [bazelbuild/bazel#6187]
### Description of the problem :

I have Bazel Android project for Windows. When I open and try to sync project I got error. On mac this step  works normal.

### Log 

ERROR: 
```
C:/users/dmitry/_bazel_dmitry/f5rza2b6/external/bazel_tools/src/main/native/windows/BUILD:49:1: Couldn't build file external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/processes-jni.obj: C++ compilation of rule '@bazel_tools//src/main/native/windows:windows_jni.dll' failed (Exit -1).
 
The target you are compiling requires Visual C++ build tools. 
Bazel couldn't find a valid Visual C++ build tools installation on your machine. 
Please check your installation following https://docs.bazel.build/versions/master/windows.html#using 
```

 
### What operating system are you running Bazel on?

Windows 7

### What's the output of `bazel info release`?

0.17.1

**Comment by jin** [comment]
Have you installed Build Tools for VS 2017? https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

https://docs.bazel.build/versions/master/windows.html#using-bazel-on-windows-1

**Comment by Kadanza** [comment]
@jin 
I install Visual Studio Community 2017 with  Build Tools. And I got new error (Exit 2)

`ERROR: C:/users/dmitry/_bazel_dmitry/f5rza2b6/external/bazel_tools/src/main/native/windows/BUILD:49:1: Couldn't build file external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/file-jni.obj: C++ compilation of rule '@bazel_tools//src/main/native/windows:windows_jni.dll' failed (Exit 2).`


I install BAZEL_VS and BAZEL_VC  in system varibales

BAZEL_VC = D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
BAZEL_VS = D:\Program Files (x86)\Microsoft Visual Studio\

**Comment by jin** [comment]
@laszlocsomor, have you seen this error before?

**Comment by laszlocsomor** [comment]
@Kadanza : what's the build command you are running? Could you build with `--verbose_failures` flag and paste here the output?

**Comment by Kadanza** [comment]
@laszlocsomor I just press Sync project with BUILD file button in android studio from Bazel Plugin

![default](https://user-images.githubusercontent.com/35968229/45868243-e1bb7f80-bd8d-11e8-82c3-44a427a24da2.png)

**Comment by laszlocsomor** [comment]
@Kadanza : Could you add the line `build --verbose_failures` to `c:\users\dmitry\.bazelrc`? To do so, you can just run this in Command Prompt:
```
echo build --verbose_failures>>%USERPROFILE%\.bazelrc
```

**Comment by Kadanza** [comment]
@laszlocsomor 
```
ERROR: C:/users/dmitry/_bazel_dmitry/f5rza2b6/external/bazel_tools/src/main/native/windows/BUILD:49:1: C++ compilation of rule '@bazel_tools//src/main/native/windows:windows_jni.dll' failed (Exit 2): cl.exe failed: error executing command 
  cd C:/users/dmitry/_bazel_dmitry/f5rza2b6/execroot/__main__
  SET INCLUDE=D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include;D:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;D:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;D:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;D:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;D:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt
    SET PATH=D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;D:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64;D:\Program Files (x86)\Windows Kits\10\bin\x64;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Users\Dmitry\AppData\Local\Temp
    SET TMP=C:\Users\Dmitry\AppData\Local\Temp
  D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/bazel_tools /Ibazel-out/host/genfiles/external/bazel_tools /Ibazel-out/host/bin/external/bazel_tools /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /Fobazel-out/host/bin/external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/processes-jni.obj /c external/bazel_tools/src/main/native/windows/processes-jni.cc.
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\yvals_core.h(298): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.15 or newer.
Target //app:app failed to build
```

**Comment by Kadanza** [comment]
I don't understand how update MSVC. I download yesterday last version Microsoft Visual Studio

**Comment by Kadanza** [comment]
@meteorcloudy  
I remove  VS 2017,  install VS 2015 from link and change BAZEL_VC , BAZEL_VS   and  it works now!

**Comment by Kadanza** [comment]
when i try to exucute mobile-install I have new error
```

[0 / 6] Injecting mobile install stub application
ERROR: C:/users/dmitry/desktop/projects/example/android/firebase-cloud-messaging/app/BUILD:9:1: Injecting mobile install stub application failed (Exit 1): stubify_manifest.exe failed: error executing command 
  cd C:/users/dmitry/_bazel_dmitry/f5rza2b6/execroot/__main__
bazel-out/host/bin/external/bazel_tools/tools/android/stubify_manifest.exe --mode=mobile_install --input_manifest bazel-out/x64_windows-fastbuild/bin/app/_merged/app/AndroidManifest.xml --output_manifest bazel-out/x64_windows-fastbuild/bin/app/app_files/mobile_install/AndroidManifest.xml --output_datafile bazel-out/x64_windows-fastbuild/bin/app/app_files/stub_application_data/stub_application_data.txt --override_package com.example.myapplication.
Traceback (most recent call last):
  File "\\?\C:\Users\Dmitry\AppData\Local\Temp\Bazel.runfiles_on5gt7__\runfiles\bazel_tools\tools\android\stubify_manifest.py", line 167, in <module>
    main()
  File "\\?\C:\Users\Dmitry\AppData\Local\Temp\Bazel.runfiles_on5gt7__\runfiles\bazel_tools\tools\android\stubify_manifest.py", line 154, in main
    output_file.write("\n".join([old_application, app_package]))
TypeError: a bytes-like object is required, not 'str'
Target //app:app failed to build
```

![default](https://user-images.githubusercontent.com/35968229/45883453-d0886800-bdb9-11e8-969b-5d2c03d7e52b.png)

**Comment by Kadanza** [comment]
I install python 2.7, remove python 3. Add python to PATH. Reinstall windows. And got new error on sync. 

```
ERROR: C:/users/dmitry/_bazel_dmitry/f5rza2b6/external/com_google_firebase_firebase_measurement_connector_16_0_0/BUILD:7:1: Couldn't build file external/com_google_firebase_firebase_measurement_connector_16_0_0/_aar/unzipped/resources/com_google_firebase_firebase_measurement_connector_16_0_0: AarResourcesExtractor external/com_google_firebase_firebase_measurement_connector_16_0_0/_aar/unzipped/resources/com_google_firebase_firebase_measurement_connector_16_0_0 failed (Exit 1): aar_resources_extractor.exe failed: error executing command 
  cd C:/users/dmitry/_bazel_dmitry/f5rza2b6/execroot/__main__
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\python\ffmpeg\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Google\Chrome\Application;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jre1.8.0_31\bin;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Users\Dmitry\.gradle\wrapper\dists\gradle-4.4-rc-3-all\9i0wh6s8d4s09gndqt6ij01o3\gradle-4.4-rc-3\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\adb;C:\Program Files\Git\cmd;C:\msys64\usr\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Python27;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\python\ffmpeg\bin;C:\Python27
  bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.exe --input_aar external/com_google_firebase_firebase_measurement_connector_16_0_0/firebase-measurement-connector-16.0.0.aar --output_res_dir bazel-out/android-armeabi-v7a-fastbuild/bin/external/com_google_firebase_firebase_measurement_connector_16_0_0/_aar/unzipped/resources/com_google_firebase_firebase_measurement_connector_16_0_0 --output_assets_dir bazel-out/android-armeabi-v7a-fastbuild/bin/external/com_google_firebase_firebase_measurement_connector_16_0_0/_aar/unzipped/assets/com_google_firebase_firebase_measurement_connector_16_0_0.
Traceback (most recent call last):
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\aar_resources_extractor.py", line 127, in <module>
    main()
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\aar_resources_extractor.py", line 121, in main
    ExtractResources(aar, FLAGS.output_res_dir)
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\aar_resources_extractor.py", line 51, in ExtractResources
    WriteFileWithJunctions(empty_xml_filename, b"<resources/>")
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\aar_resources_extractor.py", line 80, in WriteFileWithJunctions
    with junction.TempJunction(os.path.dirname(filename)) as junc:
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\junction.py", line 158, in __enter__
    self._max_path)
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\junction.py", line 140, in _MakeLinks
    TempJunction._TryMkdir(childpath)
  File "c:\users\dmitry\appdata\local\temp\Bazel.runfiles_jiq5ae\runfiles\bazel_tools\tools\android\junction.py", line 104, in _TryMkdir
    raise IOError("Could not create directory at '%s': %s" % (path, str(e)))
IOError: Could not create directory at 'bazel-out\android-armeabi-v7a-fastbuild\bin\external\com_google_firebase_firebase_measurement_connector_16_0_0\_aar\unzipped\resources\com_google_firebase_firebase_measurement_connector_16_0_0\res': [Error 206] : 'bazel-out\\android-armeabi-v7a-fastbuild\\bin\\external\\com_google_firebase_firebase_measurement_connector_16_0_0\\_aar\\unzipped\\resources\\com_google_firebase_firebase_measurement_connector_16_0_0\\res' 
```

**Comment by laszlocsomor** [comment]
Ah, now it's a long path issue.
Try adding this line to the `.bazelrc` file I mentioned earlier:
```
startup --output_user_root=c:/_bazel
```

Here's a command to do that:
```
echo startup --output_user_root=c:/_bazel>>%USERPROFILE%\.bazelrc
```

**Comment by laszlocsomor** [comment]
hm.. @hsyed, does the error in https://github.com/bazelbuild/bazel/issues/6187#issuecomment-423572470 look familiar, based on https://github.com/bazelbuild/bazel/issues/4586#issuecomment-402837477 ?

**Comment by laszlocsomor** [comment]
@Kadanza : the MANIFEST file (`C:/_bazel/iqeeg3eh/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder.exe.runfiles/MANIFEST`) is a text file, could you please check if it contains any lines with `lib/kotlin-compiler.jar` in them?

Please run this:
```
C:\msys64\usr\bin\grep.exe lib/kotlin-compiler.jar C:\_bazel\iqeeg3eh\execroot\__main__\bazel-out\host\bin\external\io_bazel_rules_kotlin\src\main\kotlin\builder.exe.runfiles\MANIFEST
```
and paste the output here.

**Comment by hsyed** [comment]
@laszlocsomor [Windows is not yet fully supported](https://github.com/bazelbuild/rules_kotlin/issues/27) -- I got all the builder tests passing but these tests run in a mocked testbench. 

This issue occurs in the [wireup of the builder](https://github.com/bazelbuild/rules_kotlin/blob/92a3cfc08f7f7551ddc1bf92cdc6defb1080b5ff/src/main/kotlin/io/bazel/kotlin/builder/toolchain/KotlinToolchain.kt#L68-L69). This code was written without windows in mind and the bazel runfiles libraries were not available.

If I remember correctly I did have `kt_jvm_library` working in windows at least the wireup wasn't causing errors. A PR would be welcome to straighten the runfiles out in this context -- I think switching to the runfiles library from `@bazel_tools` and then removing `external` from the hardcoded runfile path -- should fix this particular issue.

After this a few more things need to be addressed for windows support but it's better discussed in the thread in kotlin_rules.

For brevity the issues are:

1) singlejar (it was native on *nix and jvm based on windows)
2) *_binary and *_test stub template launch scripts and runfiles ([see](https://github.com/bazelbuild/rules_kotlin/blob/92a3cfc08f7f7551ddc1bf92cdc6defb1080b5ff/kotlin/internal/jvm/impl.bzl#L39-L64).

**Comment by meteorcloudy** [comment]
@hsyed Thanks for trying to make rules_kotlin work on Windows. Adding some related information here

-  Rencently, I added support for [symlink runfiles tree](https://docs.google.com/document/d/1hnYmU1BmtCSJOUvvDAK745DSJQCapToJxb3THXYMrmQ/edit?usp=sharing) on Windows. You can use `--experimental_enable_runfiles` to enable it with Bazel@HEAD or the upcoming 0.18.0 release on Windows 10 (developer mode). But I still recommend you to use the runfiles library if possible.

- singlejar issue: https://github.com/bazelbuild/bazel/issues/2241

- We're not using the java stub template on Windows anymore. Instead, we use a native C++ binary to launch the java program.  See https://github.com/bazelbuild/bazel/blob/eadefbbc6e22eac7300917353987fa088cd03e8d/src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaSemantics.java#L390
But I'm not sure the similar way can be implemented in Skylark rule.

**Comment by jin** [comment]
Looks like this issue (Windows long path problem) is resolved, and things are WAI. If there are issues using mobile-install, please create a new issue.
