### ISSUE TITLE
Incorrect relative path combination on Windows

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#6200]
When trying to get maven rules to work on windows, I happened to see this path appear:

H:/projects/foo/Z:/.m2/settings.xml

This will have arisen from the maven_server rule combining ".m2/settings.xml" with $HOME, and then with the workspace directory. The way it has combined paths to put a drive letter in the middle tells me that there must be a bug somewhere in the logic of Path.getRelative for windows paths, although looking over the code I can't immediately spot it.

I can dig some more if it's not obvious what's gone wrong here.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 0.17.1

**Comment by laszlocsomor** [comment]
Could be related to https://github.com/bazelbuild/bazel/issues/6138 -- `JoinPath` must be fixed on Windows.

**Comment by laszlocsomor** [comment]
@asuffield : Have you seen this bug ever since, particularly with newer Bazel versions? Do you have a repro?

**Comment by asuffield** [comment]
Yes, I can still reproduce this on 0.22. Unfortunately I haven't managed to construct a case I can send you yet - there's something about the environment triggering it, and there's no real logging for this code, and I've not yet managed to build bazel on windows in a way that I can attach a debugger to.

**Comment by asuffield** [comment]
I think I have it: this occurs when HOME is equal to "Z:", with no path segments at all. If I set HOME to "Z:/" then it's fine.

Looking through the windows path handling code, it does look like it could be wrong for the case of a single drive letter with no path segments. Hopefully this is enough for you to reproduce it; if not then I'll have another go.

**Comment by laszlocsomor** [comment]
Thanks, that was enough for me to repro this bug.
I'll create a small repro project.

**Comment by laszlocsomor** [comment]
Repro: https://github.com/laszlocsomor/projects/tree/master/bazel/maven_server_home_envvar-gh6200

Crash with `HOME=d:`:
```
C:\src\my-projects\bazel\maven_server_home_envvar-gh6200>bazel build @thing_a_ma_bop//jar
Starting local Bazel server and connecting to it...
INFO: Reading 'startup' options from c:\users\laszlocsomor\.bazelrc: --output_user_root=c:/_bazel
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=114
INFO: Options provided by the client:
  'build' options: --python_path=C:/python_27_amd64/files/python.exe
INFO: Reading rc options for 'build' from c:\users\laszlocsomor\.bazelrc:
  'build' options: --verbose_failures --announce_rc
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE_STATE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]' (requested by nodes 'FILE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 58: C:\src\my-projects\bazel\maven_server_home_envvar-gh6200\d:\.m2\settings.xml
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.io.File.toPath(Unknown Source)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:218)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:123)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:497)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:449)
        at com.google.devtools.build.lib.actions.FileStateValue.create(FileStateValue.java:82)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:52)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:31)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        ... 4 more

INFO: Elapsed time: 2.119s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE_STATE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]' (requested by nodes 'FILE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 58: C:\src\my-projects\bazel\maven_server_home_envvar-gh6200\d:\.m2\settings.xml
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.io.File.toPath(Unknown Source)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:218)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:123)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:497)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:449)
        at com.google.devtools.build.lib.actions.FileStateValue.create(FileStateValue.java:82)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:52)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:31)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE_STATE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]' (requested by nodes 'FILE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 58: C:\src\my-projects\bazel\maven_server_home_envvar-gh6200\d:\.m2\settings.xml
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.io.File.toPath(Unknown Source)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:218)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:123)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:497)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:449)
        at com.google.devtools.build.lib.actions.FileStateValue.create(FileStateValue.java:82)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:52)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:31)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE_STATE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]' (requested by nodes 'FILE:[C:/src/my-projects/bazel/maven_server_home_envvar-gh6200/d:/.m2/settings.xml]/[]')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 58: C:\src\my-projects\bazel\maven_server_home_envvar-gh6200\d:\.m2\settings.xml
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.io.File.toPath(Unknown Source)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.getAttribs(WindowsFileSystem.java:218)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.stat(WindowsFileSystem.java:123)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.statIfFound(JavaIoFileSystem.java:497)
        at com.google.devtools.build.lib.vfs.Path.statIfFound(Path.java:449)
        at com.google.devtools.build.lib.actions.FileStateValue.create(FileStateValue.java:82)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:52)
        at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:31)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by meisterT** [comment]
Is this still an issue with current Bazel?
