### ISSUE TITLE
Bazel 0.17.2: "Unrecoverable error while evaluating node ActionLookupData" with remote cache

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel#6242]
### Description of the problem:

Since upgrading from Bazel 0.14 to 0.17, we see occasional failures on CI (TeamCity) due to an exception in the Remote Cache code (we use the remote cache, with both CI and developers reading and writing).  In all known cases, re-running the build has resulted in it succeeding.

### What operating system are you running Bazel on?

Our CI runs Linux CentOS 7

### What's the output of `bazel info release`?

release 0.17.2

###  Have you found anything relevant by searching the web?

I searched using the error message and found nothing.

### Any other information, logs, or outputs that you want to share?

We are using the most recent commit of the bazel-remote cache
https://github.com/buchgr/bazel-remote

Here is the error trace:
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/sms/configuration:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/sms/configuration/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
INFO: Elapsed time: 71.129s, Critical Path: 0.63s
INFO: 32 processes: 10 remote cache hit, 22 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/sms/configuration:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/sms/configuration/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: io.netty.handler.stream.ChunkedWriteHandler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1107)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:449)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.releaseUploadChannel(HttpBlobStore.java:270)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:487)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:445)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadStream(SimpleBlobStoreActionCache.java:196)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:161)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:130)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:193)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:109)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/sms/configuration:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/sms/configuration/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: io.netty.handler.stream.ChunkedWriteHandler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1107)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:449)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.releaseUploadChannel(HttpBlobStore.java:270)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:487)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:445)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadStream(SimpleBlobStoreActionCache.java:196)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:161)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:130)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:193)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:109)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
```

I'm not able to reliably reproduce this, so if the error trace is not enough to diagnose the issue then please feel free to close this.

**Comment by robfig** [comment]
Here's another trace. I just noticed they are slightly different

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/approvals/consulting:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/approvals/consulting/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
INFO: Elapsed time: 14.107s, Critical Path: 2.03s
INFO: 20 processes: 1 remote cache hit, 19 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/approvals/consulting:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/approvals/consulting/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: io.netty.handler.codec.http.HttpRequestEncoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1107)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:449)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.releaseUploadChannel(HttpBlobStore.java:269)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:487)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:445)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadStream(SimpleBlobStoreActionCache.java:196)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:161)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:130)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:193)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:109)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//src/com/corp/approvals/consulting:protobuf_compile_imports BuildConfigurationValue.Key[34901bda2329c433045255beb042a9a0] false, actionIndex=1}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/genfiles]src/com/corp/approvals/consulting/_ijar/protobuf_compile_imports/thirdparty/jars/protobuf-java-3.4.0-ijar.jar')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: io.netty.handler.codec.http.HttpRequestEncoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1107)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:449)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.releaseUploadChannel(HttpBlobStore.java:269)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:487)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.put(HttpBlobStore.java:445)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadStream(SimpleBlobStoreActionCache.java:196)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:161)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.upload(SimpleBlobStoreActionCache.java:130)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:193)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:109)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	... 4 more
```

**Comment by philwo** [comment]
@buchgr Please check this.

**Comment by sacha-cs** [comment]
We've been seeing this problem since upgrading to 0.17.2 as well.

There is an earlier issue reporting it https://github.com/bazelbuild/bazel/issues/5952 - which has been fixed in this PR https://github.com/bazelbuild/bazel/pull/5953.

It was released in version 0.18.0, we've upgraded to it and haven't seen this bug occur any more.
