### ISSUE TITLE
Crash because of "Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext"

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#6252]
With a Bazel built from head 73516f333f75c037d25c82f23cc5ee0731f05308 and on macOS Mojave, I tried the following in Bazel's own source tree at that revision:

```
bazel build --nobuild -k //...
ERROR: /Users/jmmv/os/bazel/tools/jdk/BUILD:32:17: in java_home attribute of java_runtime rule //tools/jdk:absolute_javabase: $(ABSOLUTE_JAVABASE) not defined
ERROR: /Users/jmmv/os/bazel/tools/j2objc/BUILD:26:1: no such target '//third_party/java/j2objc:proto_plugin': target 'proto_plugin' not declared in package 'third_party/java/j2objc' defined by /Users/jmmv/os/bazel/third_party/java/j2objc/BUILD and referenced by '//tools/j2objc:j2objc_proto_toolchain'
ERROR: /Users/jmmv/os/bazel/tools/j2objc/BUILD:26:1: no such target '//third_party/java/j2objc:proto_runtime': target 'proto_runtime' not declared in package 'third_party/java/j2objc' defined by /Users/jmmv/os/bazel/third_party/java/j2objc/BUILD and referenced by '//tools/j2objc:j2objc_proto_toolchain'
Internal error thrown during build. Printing stack trace: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
	at java.base/java.security.Provider$Service.newInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getDefault(Unknown Source)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
	at java.base/java.net.URL.openConnection(Unknown Source)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:93)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:301)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:126)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:225)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:131)
	at com.google.devtools.build.lib.bazel.repository.HttpArchiveFunction.fetch(HttpArchiveFunction.java:96)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:213)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

I wouldn't be surprised if the very first error (the one about `ABSOLUTE_JAVABASE`) is not related... but I haven't investigated.

**Comment by tetromino** [comment]
Is this still happening after the 0.18 release?

Do we have a good way to test for it?

**Comment by jmmv** [comment]
I don't know. This was with Blaze built at head; the release is irrelevant.

**Comment by beasleyr-vmw** [comment]
I ran into this recently on 0.21.0 while working on some internal repository rules. I don't have time to write up a concrete test case atm (weekend), but this seems to happen when an error in repo rule A causes Bazel to terminate while repo rule B's fetch is in the middle of its SSL setup.

In my case, rule A's BUILD file referenced packages that weren't on the package search path. When I limited my command to targets based on the rule A, I'd then get a useful error message on the console:

> .../external/myrepo/BUILD.bazel:13:1: no such package 'myother/package': BUILD file not found on package path and referenced by '@myrepo//:somerule'

After correcting that, I stopped seeing the termination with SSL traceback when building my project.

**Comment by beasleyr-vmw** [comment]
> After correcting that, I stopped seeing the termination with SSL traceback when building my project.

FWIW, I don't think this is Apple-specific. I encountered this on CentOS 6.6. I suspect that the implementation `maven_jar` doesn't handle Bazel termination gracefully. See also https://github.com/bazelbuild/bazel/issues/6821.

**Comment by jin** [comment]
@rupertks could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by jmmv** [comment]
I don't know if this is still an issue, but the diagnostic from @beasleyr-vmw seems very plausible and, if so, the issue is most likely still present. Changing team labels as this seems like an issue with external repos.

**Comment by philwo** [comment]
Seems obsolete now that maven_jar is gone?
