### ISSUE TITLE
Remotely execute android_instrumentation_test targets on GCP RBE 

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6290]
`android_instrumentation_test` enables e2e hermetic emulator testing using tools in https://github.com/android/android-test and the `android_device` rule. 

Currently, `android_instrumentation_test` is fully supported to run locally on Linux hosts.

This is the tracking bug to enable remote execution of `android_instrumentation_test` targets on the GCP Remote Build Execution service.

We will use https://github.com/googlesamples/android-testing as the canonical test project.

## Current blockers

- [x] **Unable to build `android_device` remotely**

```
$ bazel build @android_test_support//tools/android/emulated_devices/generic_phone:android_23_x86_qemu2 --config=remote
WARNING: option '--jobs' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
INFO: Streaming Build Event Protocol to https://source.cloud.google.com/results/invocations/1783e496-a91c-44fe-9f5b-7979f09b2ee5
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target @android_test_support//tools/android/emulated_devices/generic_phone:android_23_x86_qemu2 (3 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8ab7e77526294574a2cf2da593f9d458/external/android_test_support/tools/android/emulated_devices/generic_phone/BUILD:43:1: Creating Android image for @android_test_support//tools/android/emulated_devices/generic_phone:android_23_x86_qemu2 failed (Exit 1)
debugfs 1.42.13 (17-May-2015)
debugfs: unlink /vendor/lib/egl
If you want to add certificates to the emulator, Please install MCrypt library using sudo apt-get install python-mcrypt .
KVM Kernel module not readable.
/dev/kvm: not readable or writable by current user
Traceback (most recent call last):
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 1026, in <module>
    app.run()
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 996, in main
    EntryPoint(reporter)
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 833, in EntryPoint
    boot_time_apks)
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 329, in _FirstBootAtBuildTimeOnly
    save_snapshot=FLAGS.save_snapshot)
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1217, in StartDevice
    **images_dict)
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 610, in _StageDataFiles
    self._InitializeRamdisk(system_image_dir)
  File "/b/f/w/run/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1251, in _InitializeRamdisk
    stdout=open('/dev/null'))
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Target @android_test_support//tools/android/emulated_devices/generic_phone:android_23_x86_qemu2 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 52.579s, Critical Path: 51.31s
INFO: 39 processes: 39 remote cache hit.
INFO: Waiting for Build Event Protocol upload to finish.
INFO: Build Event Protocol upload finished successfully.
INFO: Build Event Protocol results available at https://source.cloud.google.com/results/invocations/1783e496-a91c-44fe-9f5b-7979f09b2ee5
FAILED: Build did NOT complete successfully
```

Look into:

- Setting up a local Docker instance using the RBE image to debug.

- [x] **KVM support**

From the error message in 1):

```
KVM Kernel module not readable.
/dev/kvm: not readable or writable by current user
```

Although KVM isn't a requirement to run the Android emulator, from a product perspective, emulator testing isn't usable without it because it's just too slow.

Look into:

- Creating a custom RBE toolchain
- KVM in Docker https://www.spinics.net/lists/kvm/msg159814.html
- Privileged mode

**Comment by nlopezgi** [comment]
you can enable privileged mode for rbe actions running in a container via platform properties (if that is all that is needed)

**Comment by jin** [comment]
Brief update: this is now working with a prototype, and we're progressing on the container release pipeline.

**Comment by jin** [comment]
Update: the android-test container is available in [container-definitions](https://github.com/GoogleCloudPlatform/container-definitions/tree/master/ubuntu1604_android_test) and Android instrumentation tests work in this on a KVM-enabled RBE cluster. It is still in an experimental state and may change while we test this more extensively.

**Comment by jin** [comment]
Now used in production on Bazel CI.

https://buildkite.com/bazel/android-testing/builds/691
