### ISSUE TITLE
Skylint throws java.lang.IllegalArgumentException when file contains tabs

### ISSUE THREAD

**Issue by unapiedra** [bazelbuild/bazel#6367]
### Description of the problem / feature request:

> Running Skylint on a modified `tools/build_defs/repo/git.bzl` file throws `java.lang.IllegalArgumentException` in main.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# Inside bazel repo.
# This is master from around Oct 11, 2018.
❯ git checkout ad0af03b5a408fc8694824cef777057bbb38f15d
# Next line will succeed
❯ bazel run -- //src/tools/skylark/java/com/google/devtools/skylark/skylint:Skylint $(pwd)/tools/build_defs/repo/git.bzl 

# Get the troublesome file.
❯ git fetch https://github.com/unapiedra/bazel feature/git_repo_rule_cache
# The file is also provided as an attachment. 
❯ git checkout 5c5f9bc87c0a57472ed9db8d2a1c0c637181a4ee
# Next line will fail! 
❯ bazel run -- //src/tools/skylark/java/com/google/devtools/skylark/skylint:Skylint $(pwd)/tools/build_defs/repo/git.bzl
INFO: Analysed target //src/tools/skylark/java/com/google/devtools/skylark/skylint:Skylint (0 packages loaded).
INFO: Found 1 target...
Target //src/tools/skylark/java/com/google/devtools/skylark/skylint:Skylint up-to-date:
  bazel-bin/src/tools/skylark/java/com/google/devtools/skylark/skylint/Skylint.jar
  bazel-bin/src/tools/skylark/java/com/google/devtools/skylark/skylint/Skylint
INFO: Elapsed time: 0.205s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Exception in thread "main" java.lang.IllegalArgumentException: end location (38:29) should be after start location (38:30)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at com.google.devtools.skylark.skylint.LocationRange.<init>(LocationRange.java:32)
	at com.google.devtools.skylark.skylint.LocationRange.from(LocationRange.java:44)
	at com.google.devtools.skylark.skylint.Issue.create(Issue.java:32)
	at com.google.devtools.skylark.skylint.Linter.lambda$lint$0(Linter.java:116)
	at com.google.devtools.build.lib.syntax.Lexer.error(Lexer.java:180)
	at com.google.devtools.build.lib.syntax.Lexer.error(Lexer.java:175)
	at com.google.devtools.build.lib.syntax.Lexer.computeIndentation(Lexer.java:289)
	at com.google.devtools.build.lib.syntax.Lexer.tokenize(Lexer.java:743)
	at com.google.devtools.build.lib.syntax.Lexer.nextToken(Lexer.java:156)
	at com.google.devtools.build.lib.syntax.Parser.nextToken(Parser.java:419)
	at com.google.devtools.build.lib.syntax.Parser.expect(Parser.java:324)
	at com.google.devtools.build.lib.syntax.Parser.expectAndRecover(Parser.java:332)
	at com.google.devtools.build.lib.syntax.Parser.parseSimpleStatement(Parser.java:1128)
	at com.google.devtools.build.lib.syntax.Parser.parseStatement(Parser.java:256)
	at com.google.devtools.build.lib.syntax.Parser.parseSuite(Parser.java:1305)
	at com.google.devtools.build.lib.syntax.Parser.parseConditionalStatements(Parser.java:1197)
	at com.google.devtools.build.lib.syntax.Parser.parseIfStatement(Parser.java:1170)
	at com.google.devtools.build.lib.syntax.Parser.parseStatement(Parser.java:247)
	at com.google.devtools.build.lib.syntax.Parser.parseSuite(Parser.java:1305)
	at com.google.devtools.build.lib.syntax.Parser.parseFunctionDefStatement(Parser.java:1231)
	at com.google.devtools.build.lib.syntax.Parser.parseStatement(Parser.java:245)
	at com.google.devtools.build.lib.syntax.Parser.parseTopLevelStatement(Parser.java:1103)
	at com.google.devtools.build.lib.syntax.Parser.parseFileInput(Parser.java:1019)
	at com.google.devtools.build.lib.syntax.Parser.parseFile(Parser.java:196)
	at com.google.devtools.build.lib.syntax.BuildFileAST.parseString(BuildFileAST.java:367)
	at com.google.devtools.skylark.skylint.Linter.lint(Linter.java:112)
	at com.google.devtools.skylark.skylint.Skylint.main(Skylint.java:48)
```

### What operating system are you running Bazel on?
1. macOS High Sierra (10.13.6 (17G65))
2. Linux: ```uname -a
Linux bazelcon-test-ubuntu 4.15.0-1021-gcp #22-Ubuntu SMP Tue Sep 25 10:06:59 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

### What's the output of `bazel info release`?
```bazel info release
release 0.17.2-homebrew```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
The Skylint I run was built with version ad0af03b5a408fc8694824cef777057bbb38f15d (a commit on master)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/bazel
ad0af03b5a408fc8694824cef777057bbb38f15d
ad0af03b5a408fc8694824cef777057bbb38f15d
```

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/4511 (closed)

### Any other information, logs, or outputs that you want to share?

**Comment by unapiedra** [comment]
The file in question: [git.bzl.txt](https://github.com/bazelbuild/bazel/files/2473927/git.bzl.txt)

**Comment by unapiedra** [comment]
Minmal example: 
[minimal.bzl.txt](https://github.com/bazelbuild/bazel/files/2474037/minimal.bzl.txt)

**Comment by laurentlb** [comment]
As we work on a new linter, it's unlikely we fix this.

**Comment by unapiedra** [comment]
@laurentlb so can it be closed as "Won't fix"?

**Comment by laurentlb** [comment]
Yes, unless you want to send a Pull Request.
