### ISSUE TITLE
Bazel CI: Android Testing is failing

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6403]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/505#03a50d78-0f63-4e08-af38-4ecb515998b7

```
1) ChangeTextBehaviorTest-changeText_sameActivity(com.google.android.apps.common.testing.suite.AndroidGoogleTest)
java.lang.RuntimeException: Something went wrong during test instrumentation execution (check "logcat-ChangeTextBehaviorTest-changeText_sameActivity.txt" file below to see if your test threw any uncaught exceptions).
Debug Info: Instrumentation results are expected to have only 1 test, with two parts: Test started, and Test completed (passed, failed, errored).
Test method: com.example.android.testing.espresso.IdlingResourceSample.ChangeTextBehaviorTest#changeText_sameActivity
Test output: [INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.example.android.testing.espresso.IdlingResourceSample.ChangeTextBehaviorTest:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=initializationError
INSTRUMENTATION_STATUS: class=com.example.android.testing.espresso.IdlingResourceSample.ChangeTextBehaviorTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1]

	at com.google.android.apps.common.testing.suite.AndroidGoogleTest.runGoogleAndroidTestCase(AndroidGoogleTest.java:320)
	at com.google.android.apps.common.testing.suite.AndroidGoogleTest.runTest(AndroidGoogleTest.java:393)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

FAILURES!!!
Tests run: 1,  Failures: 1
```

@jin Can you take a look? :)

**Comment by mhlopko** [comment]
Jin, what can we do to minimize android testing failures? It feels like we get a new one everyday. Is it essential that android testing is on our ci?

**Comment by jin** [comment]
Sorry for the breakage! It’s annoying to work with flakes and instability like this. I’ll look into this.
