### ISSUE TITLE
Coverage fails on Windows due to unset JACOCO_METADATA_JAR environment variable

### ISSUE THREAD

**Issue by qwhelan** [bazelbuild/bazel#6407]
### Description of the problem / feature request:

`bazel coverage` for Java targets fails with an exception on Windows due to unset JACOCO_METADATA_JAR environment variable.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Expected output on Linux:
```
../bazel$ bazel coverage //examples/java-native/src/test/java/com/example/myproject:hello
INFO: Using default value for --instrumentation_filter: "//examples/java-native/src/main/java/com/example/myproject".
INFO: Override the above default with --instrumentation_filter
INFO: Analysed target //examples/java-native/src/test/java/com/example/myproject:hello (0 packages loaded).
INFO: Found 1 test target...
Target //examples/java-native/src/test/java/com/example/myproject:hello up-to-date:
  bazel-bin/examples/java-native/src/test/java/com/example/myproject/hello.jar
  bazel-bin/examples/java-native/src/test/java/com/example/myproject/hello
INFO: Elapsed time: 0.358s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//examples/java-native/src/test/java/com/example/myproject:hello (cached) PASSED in 1.6s
  /home/chris/.cache/bazel/_bazel_chris/5cb2061dcf36be26b48ee5bdc19079b7/execroot/io_bazel/bazel-out/k8-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/hello/coverage.dat

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action
```

Output on Windows 10 under Powershell:
```
..\bazel> bazel coverage //examples/java-native/src/test/java/com/example/myproject:hello
INFO: Using default value for --instrumentation_filter: "//examples/java-native/src/main/java/com/example/myproject".
INFO: Override the above default with --instrumentation_filter
INFO: Analysed target //examples/java-native/src/test/java/com/example/myproject:hello (0 packages loaded).
INFO: Found 1 test target...
FAIL: //examples/java-native/src/test/java/com/example/myproject:hello (see C:/users/tophe/_bazel_tophe/yw6ojpnb/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/hello/test.log)
Target //examples/java-native/src/test/java/com/example/myproject:hello up-to-date:
  C:/users/tophe/_bazel_tophe/yw6ojpnb/execroot/io_bazel/bazel-out/x64_windows-fastbuild/bin/examples/java-native/src/test/java/com/example/myproject/hello.jar
  C:/users/tophe/_bazel_tophe/yw6ojpnb/execroot/io_bazel/bazel-out/x64_windows-fastbuild/bin/examples/java-native/src/test/java/com/example/myproject/hello.exe
INFO: Elapsed time: 1.735s, Critical Path: 1.19s
INFO: 1 process: 1 local.
INFO: Build completed, 1 test FAILED, 2 total actions
//examples/java-native/src/test/java/com/example/myproject:hello         FAILED in 1.2s
  C:/users/tophe/_bazel_tophe/yw6ojpnb/execroot/io_bazel/bazel-out/x64_windows-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/hello/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

Inside `test.log`, the relevant error appears to be:
```
Exception in thread "main" java.lang.IllegalStateException: JACOCO_METADATA_JAR environment variable is not set, and no META-INF/MANIFEST.MF on the classpath has a Coverage-Main-Class attribute.  Cannot determine the name of the main class for the code under test.
        at com.google.testing.coverage.JacocoCoverageRunner.getMainClass(JacocoCoverageRunner.java:267)
        at com.google.testing.coverage.JacocoCoverageRunner.main(JacocoCoverageRunner.java:387)
```
### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

```
> bazel info release
release 0.18.0
```

### Any other information, logs, or outputs that you want to share?

I have also tried passing the `--experimental_java_coverage` and `--collect_code_coverage` flags and see no difference in behavior.

**Comment by meisterT** [comment]
If this is still an issue today, feel free to comment.
