### ISSUE TITLE
Bazel won't run/compile on Debian sid version

### ISSUE THREAD

**Issue by brdelphus** [bazelbuild/bazel#6430]
### Description of the problem / feature request:

Bazel won't compile / run in debian sid

### Feature requests: what underlying problem are you trying to solve with this feature?

Getting bazel to be supported on debian sid

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install debian sid version and try to compile bazel from source, or install package and try to compile any project.

### What operating system are you running Bazel on?

debian sid x86_64

### What's the output of `bazel info release`?

doesn't work, but installed version 0.18 from .sh binary pack

###  Have you found anything relevant by searching the web?

Yes, and none found so far

### Any other information, logs, or outputs that you want to share?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/iotad/.cache/bazel/_bazel_iotad/install/f1e11885a5cc7ba9947679cffb18bf94/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalArgumentException: Can't get logical CPU count
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLogicalCpuCountHelper(LocalHostResourceManagerLinux.java:82)
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLogicalCpuCount(LocalHostResourceManagerLinux.java:36)
	at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLocalHostResources(LocalHostResourceManagerLinux.java:46)
	at com.google.devtools.build.lib.actions.LocalHostCapacity.getNewLocalHostCapacity(LocalHostCapacity.java:46)
	at com.google.devtools.build.lib.actions.LocalHostCapacity.getLocalHostCapacity(LocalHostCapacity.java:34)
	at com.google.devtools.build.lib.buildtool.BuildRequestOptions$JobsConverter.convert(BuildRequestOptions.java:426)
	at com.google.devtools.build.lib.buildtool.BuildRequestOptions$JobsConverter.convert(BuildRequestOptions.java:410)
	at com.google.devtools.common.options.OptionDefinition.getDefaultValue(OptionDefinition.java:270)
	at com.google.devtools.common.options.OptionValueDescription$DefaultOptionValueDescription.getValue(OptionValueDescription.java:123)
	at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:356)
	at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:283)
	at com.google.devtools.common.options.OptionsParser.parseWithSourceFunction(OptionsParser.java:624)
	at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseArgsAndConfigs(BlazeOptionHandler.java:202)
	at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseOptions(BlazeOptionHandler.java:246)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:254)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR: bazel crash in async thread:

**Comment by dslomov** [comment]
Offending line is in options related to local execution => team-Local-Exec

**Comment by susinmotion** [comment]
Are you running in a container? What are the contents of /proc/cpuinfo?

**Comment by jmmv** [comment]
Please reopen this bug once you can provide the details requested in the latest update.
