### ISSUE TITLE
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by namtzigla** [bazelbuild/bazel#6480]
### Description of the problem

After a succesful build `bazel build //...` repeating the command returned the following error after ~10 min of execution and nothing is build:
```
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/tom/.cache/bazel/_bazel_tom/5ea100361e27f4970a71553a1ed8602a/command.profile'
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.common.collect.Maps.transformEntries(Maps.java:1806)
	at com.google.common.collect.Maps.transformValues(Maps.java:1669)
	at com.google.devtools.build.skyframe.AbstractSkyFunctionEnvironment.getValues(AbstractSkyFunctionEnvironment.java:145)
	at com.google.devtools.build.skyframe.AbstractSkyFunctionEnvironment.getValue(AbstractSkyFunctionEnvironment.java:59)
	at com.google.devtools.build.lib.skyframe.GlobFunction.compute(GlobFunction.java:64)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO: Elapsed time: 935.686s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (297 packages loaded)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.common.collect.Maps.transformEntries(Maps.java:1806)
	at com.google.common.collect.Maps.transformValues(Maps.java:1669)
	at com.google.devtools.build.skyframe.AbstractSkyFunctionEnvironment.getValues(AbstractSkyFunctionEnvironment.java:145)
	at com.google.devtools.build.skyframe.AbstractSkyFunctionEnvironment.getValue(AbstractSkyFunctionEnvironment.java:59)
	at com.google.devtools.build.lib.skyframe.GlobFunction.compute(GlobFunction.java:64)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
GC overhead limit exceeded

FAILED: Build did NOT complete successfully (297 packages loaded)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I was not able to reproduce this in any other project except the one that I'm working on.

### What operating system are you running Bazel on?

Is reproductible on: ubuntu, arch linux, macOS 

### What's the output of `bazel info release`?

```
release 0.18.0- (@non-git)
```
But we notice this bug since version 0.17

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`pacaur -S bazel`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

it's a private repo 

###  Have you found anything relevant by searching the web?
#5180

### Any other information, logs, or outputs that you want to share?
Attached is an archive with two files, command-crash.profile and command-success.profile.

[command.profile.zip](https://github.com/bazelbuild/bazel/files/2507315/command.profile.zip)

**Comment by DavidGoldman** [comment]
As an immediate workaround, you can try giving the JVM more memory: `bazel --host_jvm_args=-Xmx15G ...`. You can try increasing/decreasing the `15G` as needed.

**Comment by janakdr** [comment]
Bazel will OOM if it's given too large a set of targets to build. Are you saying that doing bazel build //... && bazel build //... will succeed the first time and fail the second time, reproducibly? That would be unexpected. OOMs are non-deterministic, but usually if you succeed on the first build, incremental builds take less memory at peak.

**Comment by namtzigla** [comment]
@janakdr This is a very old issue, it was happen along the lines you described but It might have been fixed long time go and there is no way how I could test it now. We've switch to please.
