### ISSUE TITLE
Unrecoverable error while evaluating node GIT_CLONE

### ISSUE THREAD

**Issue by jishi9** [bazelbuild/bazel#650]
Is it possible to set the temporary directory for bazel to use (e.g. via a commandline flag)?

The main reason driving this is the problem with the case-insensitive filesystem on the mac. It seems that similarly to issue #301 , Bazel crashes when trying to fetch a git repository containing both a `BUILD` file and a `build/` directory. See the stack trace below:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'GIT_CLONE:https://github.com/mzhaom/trunk.git -> /private/var/tmp/_bazel_$USER/e9946435dae6f8c31baddd547472fa88/external/boost_repo (a4daafd562215a9e088cfc8997970d1182523ff9) submodules: false' (requested by nodes 'GIT_REPOSITORY:@boost_repo')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:968)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /private/var/tmp/_bazel_$USER/e9946435dae6f8c31baddd547472fa88/external/boost_repo/third_party/libunwind/build/k8/include failed
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:320)
	at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:131)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:932)
	... 4 more
Caused by: java.io.IOException: Creating directories for /private/var/tmp/_bazel_$USER/e9946435dae6f8c31baddd547472fa88/external/boost_repo/third_party/libunwind/build/k8/include failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:316)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1149)
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:450)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:263)
```

As a workaround I created and mounted a case-sensitive volume, and I now would like bazel to use that as its temporary directory rather than `/private/var/tmp/_bazel_$USER/` (FYI `/var` is symlinked to `/private/var`).

The temporary directory to use seems to be hardcoded in bazel in https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_util_darwin.cc#L36 . I can see also a TODO related to case-insensitive file systems.

**Comment by kchodorow** [comment]
You can override /var/tmp by specifying `--output_root`, e.g.:

```
$ bazel --output_base=/path/to/your/volume build :foo
```

**Comment by jishi9** [comment]
Thanks! That seems to works, though Bazel still seems to use `/var/tmp/_bazel_$USER` to host the `install` subdirectory. I don't think this causes a problem in my specific case, but just FYI:

```
$ bazel --output_base=/path/to/volume build :foo
# performs build...

$ ls -la /path/to/volume
drwx------ 6 $USER 150487713 442 Nov 25 22:28 ./
drwxr-xr-x 6 $USER 150487713 374 Nov 25 22:26 ../
-rw------- 1 $USER 150487713  42 Nov 25 22:28 DO_NOT_BUILD_HERE
-rw------- 1 $USER 150487713 796 Nov 25 22:28 README
-rw------- 1 $USER 150487713 17K Nov 25 22:28 command.log
drwx------ 3 $USER 150487713 102 Nov 25 22:28 cpp/
drwx------ 5 $USER 150487713 204 Nov 25 22:28 external/
lrwx------ 1 $USER 150487713  69 Nov 25 22:28 install -> /var/tmp/_bazel_$USER/install/030eea3f048f457f9da9f46486d60acf/
-rw------- 1 $USER 150487713 842 Nov 25 22:28 java.log
-rwx------ 1 $USER 150487713 331 Nov 25 22:28 javalog.properties*
-rw------- 1 $USER 150487713  48 Nov 25 22:28 lock
drwx------ 2 $USER 150487713 204 Nov 25 22:28 server/
drwx------ 2 $USER 150487713  68 Nov 25 22:28 worker-logs/

```

**Comment by kchodorow** [comment]
You should be able to change that by specifying `--output_user_root`.  From `bazel help --long startup_options`:

```
  --output_base (a path; default: see description)
    If set, specifies the output location to which all build output will be 
    written. Otherwise, the location will be ${OUTPUT_ROOT}/_blaze_${USER}
    /${MD5_OF_WORKSPACE_ROOT}. Note: If you specify a different option from one 
    to the next Blaze invocation for this value, you'll likely start up a new, 
    additional Blaze server. Blaze starts exactly one server per specified 
    output base. Typically there is one output base per workspace--however, 
    with this option you may have multiple output bases per workspace and 
    thereby run multiple builds for the same client on the same machine 
    concurrently. See 'blaze help shutdown' on how to shutdown a Blaze server.
  --output_user_root (a path; default: see description)
    The user-specific directory beneath which all build outputs are written; by 
    default, this is a function of $USER, but by specifying a constant, build 
    outputs can be shared between collaborating users.
```

**Comment by janakdr** [comment]
Is there a separate bug for the crash from the IOException here?

**Comment by kchodorow** [comment]
No, I don't think so. I'll reopen to track that.
