### ISSUE TITLE
Cannot build Gerrit with toolchain_vanilla with Java 10

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#6579]
When trying to build Gerrit master with `toolchain_vanilla` with java 10 (on Bazel@HEAD) I'm seeing this failure:

```
  $ bazel build -s --host_javabase=:absolute_javabase \
  --define=ABSOLUTE_JAVABASE=/usr/lib64/jvm/java-10 \
  --host_java_toolchain=//:toolchain_vanilla  \
  --java_toolchain=//:toolchain_vanilla //java/com/google/gerrit/common:annotations
[...]
INFO: Found 1 target...
SUBCOMMAND: # //java/com/google/gerrit/common:annotations [action 'Building java/com/google/gerrit/common/libannotations.jar (3 source files)']
(cd /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  bin/java -Xverify:none -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/java/com/google/gerrit/common/libannotations.jar-0.params)
ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/common/BUILD:10:1: Building java/com/google/gerrit/common/libannotations.jar (3 source files) failed: IOException while preparing the execution environment of a worker:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Cannot run program "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bin/java" (in directory "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.start(JavaSubprocessFactory.java:141)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.create(JavaSubprocessFactory.java:162)
	at com.google.devtools.build.lib.shell.SubprocessBuilder.start(SubprocessBuilder.java:226)
	at com.google.devtools.build.lib.worker.Worker.createProcess(Worker.java:84)
	at com.google.devtools.build.lib.worker.Worker.prepareExecution(Worker.java:156)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:314)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:168)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:122)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:76)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:284)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:291)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:1009)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:938)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:125)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:778)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:733)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:495)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:536)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:211)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 29 more
---8<---8<--- End of exception details ---8<---8<---
```

//CC @cushon

**Comment by davido** [comment]
Never mind, `--define=USE_ABSOLUTE_JAVABASE=true` option was missing.
