### ISSUE TITLE
Hard crash due to IllegalStateException when loading target patterns

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6586]
### Description of the problem / feature request:

Bazel hard crashes in the following way when I attempt to build my code. (My code is broken but bazel should not have internal errors when dealing with it).

```sh
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel build :all_tests --define yaspl_bootstrap=true 2>&1
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:10:5: syntax error at 'outputs': expected ,
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:17:3: non-keyword arg after keyword arg
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:22:5: syntax error at 'outputs': expected ,
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/prim-language/prim-language.bzl:29:3: non-keyword arg after keyword arg
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2346)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1.007s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2346)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2346)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2346)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:85)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:484)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:870)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:939)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
FAILED: Build did NOT complete successfully (8 packages loaded)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Running the same command line in this repo. 
https://github.com/endobson/yaspl2/tree/hard-crash-illegal-state
I was not able to easily reproduce to a minimal case, it wouldn't crash in my attempts.

### What operating system are you running Bazel on?
macOS

### What's the output of `bazel info release`?
release 0.19.0

**Comment by jin** [comment]
Looks like a hard crash while evaluating Starlark. Assigning to the Starlark team.

**Comment by laurentlb** [comment]
Looks related to Skyframe, not sure which components it is.

**Comment by endobson** [comment]
I'm still able to repro this in bazel 0.28.1.

Using code from:
https://github.com/endobson/yaspl2/tree/86ca596c1cbef7ab4ab5d0794df5f45c70c45bb3

```
$ bazel build :all_tests --define yaspl_bootstrap=true --incompatible_no_rule_outputs_param

Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl:138:17: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/prim-language/prim-language.bzl:44:15: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/prim-language/prim-language.bzl:90:16: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/web-assembly/wasm.bzl:17:18: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /private/var/tmp/_bazel_endobson/c1413d49bc8a9d719fd4a8b56cbe2fdf/external/io_bazel_rules_docker/container/layer.bzl:243:20: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /private/var/tmp/_bazel_endobson/c1413d49bc8a9d719fd4a8b56cbe2fdf/external/io_bazel_rules_docker/container/import.bzl:161:20: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /private/var/tmp/_bazel_endobson/c1413d49bc8a9d719fd4a8b56cbe2fdf/external/io_bazel_rules_docker/container/push.bzl:138:18: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /private/var/tmp/_bazel_endobson/c1413d49bc8a9d719fd4a8b56cbe2fdf/external/io_bazel_rules_docker/container/bundle.bzl:90:21: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /private/var/tmp/_bazel_endobson/c1413d49bc8a9d719fd4a8b56cbe2fdf/external/io_bazel_rules_docker/container/flatten.bzl:63:21: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/prim-language/prim-language.bzl:147:15: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl:161:10: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl", line 178
		_yaspl_binary_rule(False)
	File "/Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl", line 161, in _yaspl_binary_rule
		rule(implementation = _bin_impl, output..."}, <4 more arguments>)
parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl:161:10: Traceback (most recent call last):
	File "/Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl", line 179
		_yaspl_binary_rule(True)
	File "/Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl", line 161, in _yaspl_binary_rule
		rule(implementation = _bin_impl, output..."}, <4 more arguments>)
parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: /Users/endobson/proj/racket/yaspl2-clean/libraries/yaspl.bzl:181:14: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: error loading package 'examples': Extension file 'libraries/yaspl.bzl' has errors
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2825)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:156)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:77)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 2.620s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: error loading package 'examples': Extension file 'libraries/yaspl.bzl' has errors
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2825)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:156)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:77)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: error loading package 'examples': Extension file 'libraries/yaspl.bzl' has errors
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2825)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:156)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:77)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
FAILED: Build did NOT complete successfully (1 packages loaded)

```
