### ISSUE TITLE
omitting the executable from data_runfiles crashes Bazel

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#6607]
```
$ cat rule.bzl
def _broken_executable(ctx):
    other_file = ctx.actions.declare_file('other')
    ctx.actions.write(content = 'foo', output = other_file)
    ctx.actions.write(content = 'bar', output = ctx.outputs.executable)
    return struct(default_runfiles = ctx.runfiles(files=[other_file]))

broken_executable = rule(
    implementation = _broken_executable,
    executable = True,
)
$ cat BUILD
load(":rule.bzl", "broken_executable")

broken_executable(name = "broken")
$ bazel build //:broken
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//:broken BuildConfigurationValue.Key[b4f63d729fb5712a9002341842f4fb65] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: main program File:[[<execution_root>]bazel-out/k8-fastbuild/bin]broken not included in runfiles
	at com.google.devtools.build.lib.analysis.RunfilesSupport.create(RunfilesSupport.java:118)
	at com.google.devtools.build.lib.analysis.RunfilesSupport.withExecutable(RunfilesSupport.java:417)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addSimpleProviders(SkylarkRuleConfiguredTargetUtil.java:579)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.parseDefaultProviderFields(SkylarkRuleConfiguredTargetUtil.java:521)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addProviders(SkylarkRuleConfiguredTargetUtil.java:386)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:209)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:134)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:308)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:636)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:783)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 7 more

```

**Comment by c-parsons** [comment]
I believe this was fixed in https://github.com/bazelbuild/bazel/commit/f13f9fc39a7e48cc3233f763caa499bcf9ec4a9a
