### ISSUE TITLE
bazel test fails on Windows

### ISSUE THREAD

**Issue by RaresI** [bazelbuild/bazel#6682]
### Description of the problem / feature request:

Fix "bazel test" on Windows

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel test //test/Bazel:test4

### What operating system are you running Bazel on?
Microsoft Windows [Version 10.0.16299.785]
perl -e "print $];"
5.024003
### What's the output of `bazel info release`?

release 0.19.1

###  Have you found anything relevant by searching the web?
No

### Any other information, logs, or outputs that you want to share?
Console Output: 
bazel test //test/Bazel:test4
INFO: Analysed target //test/Bazel:test4 (1 packages loaded, 4 targets configured).
INFO: Found 1 test target...
FAIL: //test/Bazel:test4 (see C:/users/rares/_bazel_rares/rqs3mhhq/execroot/__main__/bazel-out/x64_windows-fastbuild/testlogs/test/Bazel/test4/test.log)

Contents of test.log:>>>>>>>>>
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/Bazel:test4
-----------------------------------------------------------------------------
JUnit4 Test Runner
..E
Time: 0.01
There was 1 failure:
1) fails(Bazel.JUnit4Test)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at Bazel.JUnit4Test.fails(JUnit4Test.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

FAILURES!!!
Tests run: 2,  Failures: 1

BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2018-11-15 10:56:09 --

<<<<<<<<<

**Comment by irengrig** [comment]
Thank you for reporting the problem.
I would guess that we may need more information here, as I find the exception not descriptive enough.
1 Do you know if it is a regression from previous Bazel version?
2 Is the failure specific to the invoked test, or does it always fail with any of them?

**Comment by lberki** [comment]
Closing this as there isn't enough information to continue investigation.
