### ISSUE TITLE
Starlark http_archive cannot be referred by //external:[repo_name] from another external repo

### ISSUE THREAD

**Issue by trchen1033** [bazelbuild/bazel#6725]
### Description of the problem / feature request:

A external repo pulled in by Starlark http_archive cannot be referred by //external:_[repo_name]_ from another external repo. @_[repo_name]_//:_[repo_name]_ works just fine.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/trchen1033/bazel_http_archive_bug.git
cd bazel_http_archive_bug/main
bazel build @greeting//:greeting
```

### What operating system are you running Bazel on?

macOS 10.14

### What's the output of `bazel info release`?

release 0.19.2

### Any other information, logs, or outputs that you want to share?

The error message generated from the commands above:
```
ERROR: /Users/trchen/tmp/bazel_http_archive_bug/main/WORKSPACE:3:1: in http_archive rule //external:hello: 
Traceback (most recent call last):
	File "/Users/trchen/tmp/bazel_http_archive_bug/main/WORKSPACE", line 3
		http_archive(name = 'hello')
	File "/private/var/tmp/_bazel_trchen/3f03b5fd6037ac75aea11025dcc545c3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 48, in _http_archive_impl
		ctx.download_and_extract(all_urls, "", ctx.attr.sha256, ctx.attr...., ...)
type 'ctx' has no method download_and_extract(list, string, string, string, string)
ERROR: Analysis of target '@greeting//:greeting' failed; build aborted: Analysis of target '//external:hello' failed; build aborted
INFO: Elapsed time: 0.090s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```
It may or may not be related, the following command will crash bazel server:
```
bazel build //external:greeting
```
```
INFO: Analysed target //external:greeting (3 packages loaded, 20 targets configured).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //external:greeting failed to build
Use --verbose_failures to see the command lines of failed build steps.
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'TargetCompletionKey{configuredTargetKey=//external:greeting BuildConfigurationValue.Key[80b31e5bc953f6394d399e7a85d1e18d] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, willTest=false}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:greeting
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:258)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:66)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.getAndValidate(ConfiguredAttributeMapper.java:101)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.get(ConfiguredAttributeMapper.java:213)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.<init>(TargetCompleteEvent.java:177)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.successfulBuild(TargetCompleteEvent.java:186)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:217)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:118)
	at com.google.devtools.build.lib.skyframe.CompletionFunction.compute(CompletionFunction.java:409)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 4 more

INFO: Elapsed time: 1.388s, Critical Path: 0.02s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'TargetCompletionKey{configuredTargetKey=//external:greeting BuildConfigurationValue.Key[80b31e5bc953f6394d399e7a85d1e18d] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, willTest=false}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:greeting
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:258)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:66)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.getAndValidate(ConfiguredAttributeMapper.java:101)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.get(ConfiguredAttributeMapper.java:213)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.<init>(TargetCompleteEvent.java:177)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.successfulBuild(TargetCompleteEvent.java:186)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:217)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:118)
	at com.google.devtools.build.lib.skyframe.CompletionFunction.compute(CompletionFunction.java:409)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'TargetCompletionKey{configuredTargetKey=//external:greeting BuildConfigurationValue.Key[80b31e5bc953f6394d399e7a85d1e18d] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, willTest=false}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:greeting
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:258)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:66)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.getAndValidate(ConfiguredAttributeMapper.java:101)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.get(ConfiguredAttributeMapper.java:213)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.<init>(TargetCompleteEvent.java:177)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.successfulBuild(TargetCompleteEvent.java:186)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:217)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:118)
	at com.google.devtools.build.lib.skyframe.CompletionFunction.compute(CompletionFunction.java:409)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'TargetCompletionKey{configuredTargetKey=//external:greeting BuildConfigurationValue.Key[80b31e5bc953f6394d399e7a85d1e18d] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, willTest=false}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:greeting
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:258)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:66)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.getAndValidate(ConfiguredAttributeMapper.java:101)
	at com.google.devtools.build.lib.packages.ConfiguredAttributeMapper.get(ConfiguredAttributeMapper.java:213)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.<init>(TargetCompleteEvent.java:177)
	at com.google.devtools.build.lib.analysis.TargetCompleteEvent.successfulBuild(TargetCompleteEvent.java:186)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:217)
	at com.google.devtools.build.lib.skyframe.CompletionFunction$TargetCompletor.createSucceeded(CompletionFunction.java:118)
	at com.google.devtools.build.lib.skyframe.CompletionFunction.compute(CompletionFunction.java:409)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 4 more
FAILED: Build did NOT complete successfully
```

**Comment by dslomov** [comment]
Accessing things via `//external:<repo-name>` is not recommended. However you seem to hit some other issues, starting with the processing of your WORKSPACE file. We definitely should not crash.

**Comment by aehlig** [comment]
> Accessing things via `//external:<repo-name>` is not recommended.
> However you seem to hit some other issues, starting with the
> processing of your WORKSPACE file. We definitely should not crash.

The whole `//external` virtual package seems like a hack. A minimal
example for the crash is the following.

```
mkdir local
touch local/BUILD
mkdir main
cd main
echo 'local_repository(name="local", path="../local")' > WORKSPACE
bazel build //external:local
```

The error message is also quite telling: `No such attribute tags
in local_repository rule //external:local`, i.e., even though the
rule in charge for that target is a repository rule, it is treated
like a normal build rule, that should have tags, etc. That most
likely also explains the error message in the other case: if we
execute the implementaiton function of a repsoitory rule (in this
case http_archive) with a rule context instead of a repository_rule
context as an argument, we ask for trouble and expect to see the
error message we've seen.

Interestingly enough, it is not the case that the local repository is
actually mapped at that place; it is just the target for the repository
rule. Asking for something like `bazel build //external/local/...`
or `bazel build //external/local:it` does not even find the BUILD
file of the directory `local`, regardless what the contents of that
file are.

And that is not even talking about the case that you have a directory
called `external` at the top-level of your workspace...

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
With the crash being fixed, the priority is less urgent. What still remains is the bug that a repository rule is built with a build context, instead of disallowing targets depending on repositories (as such, instead of targets of a repository).

Cleaning up the messed-up `//external` name space is a separate feature request.

**Comment by aehlig** [comment]
Filed #6917 for the feature reqeust to clean up, so that https://bazel-review.googlesource.com/c/bazel/+/84490 can close this issue.
