### ISSUE TITLE
Bazel fails with out of memory error

### ISSUE THREAD

**Issue by dgrnbrg** [bazelbuild/bazel#6751]
### Description of the problem / feature request:

I am trying to use `new_http_archive` to build a complex set of dependencies. I am attempting to build Apache ORC with Bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am using https://github.com/cschuet/snappy for my snappy build, and https://github.com/MarkusTeufelberger/BBW/blob/c6d0ea14bb039d55f368864a5bb83bcbc112576c/packages/github.com/lz4/lz4/lz4_1_7_5%2B.BUILD# for my lz4 build. When I try to compile orc (I can share my ORC building workspace/BUILD file if needed), the build gets far along, but fails on several files: StripeStream, ColumnWriter, ColumnReader, Reader, Writer, TypeImpl, and Statistics (see https://github.com/apache/orc/tree/master/c%2B%2B/src). The error for all of them is:

```
FAILED: Build did NOT complete successfully

Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Requested array size exceeds VM limit

        at java.lang.StringCoding.encode(StringCoding.java:350)

        at java.lang.String.getBytes(String.java:941)

        at com.google.devtools.build.lib.events.Event.getMessageBytes(Event.java:111)

        at com.google.devtools.build.lib.runtime.ExperimentalEventHandler.handleLocked(ExperimentalEventHandler.java:387)

        at com.google.devtools.build.lib.runtime.ExperimentalEventHandler.handleLocked(ExperimentalEventHandler.java:492)

        at com.google.devtools.build.lib.runtime.ExperimentalEventHandler.handle(ExperimentalEventHandler.java:338)

        at com.google.devtools.build.lib.events.Reporter.handle(Reporter.java:105)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.dumpRecordedOutErr(SkyframeActionExecutor.java:1238)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.printError(SkyframeActionExecutor.java:1190)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.reportErrorIfNotAbortingMode(SkyframeActionExecutor.java:1290)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.processAndThrow(SkyframeActionExecutor.java:954)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:1017)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:930)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:770)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:725)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:478)

        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:519)

        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:216)

        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)

        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)
```

which isn't debuggable. I am building with the following command line, which should not be throwing this error:

```
bazel --host_jvm_args=-Xmx20g build @orc//:orc --sandbox_debug --verbose_failures
```

### What operating system are you running Bazel on?

RHEL 7

### What's the output of `bazel info release`?

release 0.19.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I installed bazel via yum.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I don't understand this question--my own code is private on a private network, and I didn't install bazel from git.

###  Have you found anything relevant by searching the web?

I haven't been able to find information about this aspect of bazel.

### Any other information, logs, or outputs that you want to share?

Please let me know if further information would help to diagnose this issue.

**Comment by dslomov** [comment]
Is this a BEP issue? /cc @lfpino 
Is this reliably reproducible @dgrnbrg ?

**Comment by lfpino** [comment]
Doesn't look like BEP to me, this is a different kind of Event.

**Comment by dgrnbrg** [comment]
I worked around this, and haven't repeatedly encountered this issue.

**Comment by gxkevin** [comment]
@dgrnbrg hi，have u build the orc with bazel succssful?  Do u have the workspace/BUILD?
