### ISSUE TITLE
bazel crash while trying to build grpc

### ISSUE THREAD

**Issue by markdroth** [bazelbuild/bazel#6812]
### Description of the problem / feature request:

Bazel crashes with when trying to build grpc on my machine (see output below).  Note that @nicolasnoble has tried exactly the same command on his machine and did not see the same problem, but I don't know what in my environment might be triggering it.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not crashing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the comment shown above.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

Starting local Bazel server and connecting to it...
INFO: Invocation ID: cf87eba9-6615-4a6a-96b8-25cc0d2b9e47
release 0.20.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

roth@segfault:~/grpc> git remote get-url origin ; git rev-parse upstream/master ; git rev-parse HEAD
https://github.com/markdroth/grpc
c3ad2243eefd64bb387476eb1d61428171568bc7
c3ad2243eefd64bb387476eb1d61428171568bc7

###  Have you found anything relevant by searching the web?

Didn't look.  Pretty sure bazel's not supposed to crash, no matter what I do. :)

### Any other information, logs, or outputs that you want to share?

Here's the command I'm running and the error I'm seeing:

```
roth@segfault:~/grpc> bazel test test/cpp/end2end/client_lb_end2end_test --incompatible_remove_native_git_repository=false --incompatible_remove_native_http_archive=false
INFO: Invocation ID: d4d34d31-31a7-491f-97c9-ebdefdfc53d6
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
//:windows_msvc BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1.500s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded, 32 targets con\
figured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
//:windows_msvc BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: topLevelKey: //test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
//:windows_msvc BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: topLevelKey: //test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//test/cpp/end2end:client_lb_end2end_test BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
//:windows_msvc BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown FAILED: Build did NOT complete successfully (9 packages loaded, 32 targets con\
figured)
```

**Comment by lidizheng** [comment]
Same for gRPC Python build. It works for my MacBook Pro, not for my desktop.

### Worked Release on macOS
```
lidiz-macbookpro:grpc lidiz$ bazel info release
release 0.19.0
```

### Not Working Release on Desktop
```
lidiz@ddev:~/src/grpc$ bazel info release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 6425b8f0-d4d4-4bdb-9969-0b23ed1198ce
release 0.20.0
```

### Error log
```
lidiz@ddev:~/src/grpc$ bazel test --spawn_strategy=standalone --genrule_strategy=standalone --test_output=errors //src/python/...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: bde18f3f-da3d-48f0-9e38-6dbfb22c3691
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 4.131s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded, 62 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: topLevelKey: //src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: topLevelKey: //src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
alreadyReported: false
path to cycle:
//src/python/grpcio_channelz/grpc_channelz/v1:grpc_channelz BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false
cycle:
com.google.devtools.build.lib.skyframe.RegisteredExecutionPlatformsValue$Key@f6084b7a
//third_party/toolchains:cc-toolchain-clang-x86_64-default BuildConfigurationValue.Key[5bf2e969a38eb49f752709c0acfde687] false

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:85)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:367)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
FAILED: Build did NOT complete successfully (39 packages loaded, 62 targets configured)
```

**Comment by soheilhy** [comment]
I'm also hitting exact same error for `release 0.20.0`.

**Comment by jmmv** [comment]
This seems to be a crash caused while detecting a cycle in the build graph. Nothing to do with local execution.

**Comment by gregestren** [comment]
I'm not sure what's going on with this specific cycle. But I'm not reproducing with Bazel 0.26.0 on a clean grpc checkout. Is this still an issue?

**Comment by meisterT** [comment]
No response, let's assume this is not an issue anymore.
