### ISSUE TITLE
Protobuf version used in external repository interferes with protobuf version used locally

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#6852]
Gerrit depends on `rules_closure`, that depends on `protobuf` for communication with workers that run closure compiler. In the same time Gerrit depends on `protobuf` to serialize data in persistent caches and for that `protobuf` version 3.6.1 is used in Gerrit build tool chain:

```
maven_jar(
    name = "protobuf",
    artifact = "com.google.protobuf:protobuf-java:3.6.1",
    sha1 = "0d06d46ecfd92ec6d0f3b423b4cd81cb38d8b924",
)
```

To exercise `protobuf` dependency `rules_closure` does this:

```
def com_google_protobuf():
    # Note: Protobuf 3.6.0+ is going to use C++11
    http_archive(
        name = "com_google_protobuf",
        strip_prefix = "protobuf-7b28271a61a3da0a37f6fda399b0c4c86464e5b3",
        sha256 = "9dac7d7cf6e2c88bf92915f9338a26950531c00c05bf86764ab978344b69a45a",
        urls = [
            "https://github.com/google/protobuf/archive/7b28271a61a3da0a37f6fda399b0c4c86464e5b3.tar.gz",
        ],
    )
```

After https://github.com/bazelbuild/bazel/commit/86013a0a23a232d5549bfe1085ebb0fabcd9b23f, that I tried to revert [here](https://bazel-review.googlesource.com/c/bazel/+/83630), gerrit cannot be built any more without passing `--incompatible_package_name_is_a_function=false` option.

To rectify that, I upgraded `rules_closure` to consume `protobuf` from HEAD in this [fork](https://github.com/davido/rules_closure/releases/tag/0.20).

However after this upgrade Gerrit tests are failing, because now there is a mismatch between Bazel's internal `protoc` version (that was overloaded by the `rules_closure` fork) and internal version of `protobuf-java` in gerrit, that is still pointing to 3.6.1 (and there is no new `protobuf-java`  release available on Maven Central to consume for now):

```
1) parseUncheckedWrongProtoType(com.google.gerrit.server.cache.serialize.ProtoCacheSerializersTest)
java.lang.NoSuchMethodError: com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.emptyIntList()Lcom/google/protobuf/Internal$IntList;
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.<init>(Cache.java:3671)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.<clinit>(Cache.java:12345)
	at com.google.gerrit.server.cache.serialize.ProtoCacheSerializersTest.parseUncheckedWrongProtoType(ProtoCacheSerializersTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
```

Environment:

```
  $ bazel version
  Build label: 0.21.0rc2

  $ java -fulversion
  openjdk full version "1.8.0_171-b11"
```

To reproduce:

1. clone [gerrit](https://gerrit.googlesource.com/gerrit)
2. apply this [CL](https://gerrit-review.googlesource.com/c/gerrit/+/206093) to bump `protobuf` in `rules_closure` repository to recent HEAD
3. run:

```
  $ bazel test javatests/com/google/gerrit/server/cache/serialize:tests
  FAIL: //javatests/com/google/gerrit/server/cache/serialize:tests (see /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/server/cache/serialize/tests/test.log)
Target //javatests/com/google/gerrit/server/cache/serialize:tests up-to-date:
  bazel-bin/javatests/com/google/gerrit/server/cache/serialize/tests.jar
  bazel-bin/javatests/com/google/gerrit/server/cache/serialize/tests
INFO: Elapsed time: 101.809s, Critical Path: 43.44s
INFO: 191 processes: 170 linux-sandbox, 21 worker.
INFO: Build completed, 1 test FAILED, 193 total actions
//javatests/com/google/gerrit/server/cache/serialize:tests               FAILED in 0.7s
```

//CC @jin, @meteorcloudy, @laurentlb.

**Comment by meteorcloudy** [comment]
@laurentlb Looks like we should not depends on random protobuf commit. Can we update rules_closure to depends on 3.6.1.2, it should be compatible with 3.6.1

**Comment by davido** [comment]
@meteorcloudy If I update `rules_closure` to `protobuf` 3.6.1.2 instead of to `protobuf` at HEAD, then it seems to work. IOW, `protoc` from 3.6.1.2 seems to be compatible to `protobuf-java` 3.6.1 that is used in gerrit itself.
