### ISSUE TITLE
Bazel failed to run on a CIFS mounted directory

### ISSUE THREAD

**Issue by bashi** [bazelbuild/bazel#6938]
### Description of the problem / feature request:

I tried to run bazel from a CIFS mounted directory on a Linux vm running on hyper-v but got following error:

```sh
$ bazel test :hello_test                                                                                                                                                       
Starting local Bazel server and connecting to it...                                                                                                                                   
Internal error thrown during build. Printing stack trace: java.lang.UnsupportedOperationException: /mnt/hyper-v/work/abseil-hello/bazel-bin (Operation not supported)                 
        at com.google.devtools.build.lib.unix.NativePosixFiles.symlink(Native Method)                                                                                                 
        at com.google.devtools.build.lib.unix.UnixFileSystem.createSymbolicLink(UnixFileSystem.java:330)                                                                              
        at com.google.devtools.build.lib.vfs.Path.createSymbolicLink(Path.java:583)                                                                                                   
        at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:356)                                                                             
        at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:307)
        at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createLink(OutputDirectoryLinksUtils.java:271)
        at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createOutputDirectoryLinks(OutputDirectoryLinksUtils.java:200)
        at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:267)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:164)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:131)
        at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:111)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
$ sudo mount -t cifs '[cifs_path]' /mnt/foo -o uid=1000,gid=1000,user=[username],ip=[ipaddr]
$ cd /mnt/foo
$ git clone https://github.com/abseil/abseil-hello.git; cd abseil-hello
$ bazel test :hello_test
```

### What operating system are you running Bazel on?

```sh
$ uname -a
Linux hyper-v 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

```
bazel-bin: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/execroot/com_google_absl_hello_world/bazel-out/k8-fastbuild/bin
bazel-genfiles: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/execroot/com_google_absl_hello_world/bazel-out/k8-fastbuild/genfiles
bazel-testlogs: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/execroot/com_google_absl_hello_world/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/command.log
committed-heap-size: 222MB
execution_root: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/execroot/com_google_absl_hello_world
gc-count: 6
gc-time: 98ms
install_base: /home/bashi/.cache/bazel/_bazel_bashi/install/3aadb0885b1cb52846820562c39bed63
java-home: /home/bashi/.cache/bazel/_bazel_bashi/install/3aadb0885b1cb52846820562c39bed63/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 9.0.7.1+1) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode) by Azul Systems, Inc.
max-heap-size: 1849MB
output_base: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a
output_path: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/execroot/com_google_absl_hello_world/bazel-out
package_path: %workspace%
release: release 0.20.0
repository_cache: /home/bashi/.cache/bazel/_bazel_bashi/cache/repos/v1
server_log: /home/bashi/.cache/bazel/_bazel_bashi/8c2351849c5d72ff1d6ac221f0aad31a/java.log.hyper-v.bashi.log.java.20181216-164514.11133
server_pid: 11133
used-heap-size: 58MB
workspace: /mnt/hyper-v/abseil-hello
```

###  Have you found anything relevant by searching the web?

Yes.

**Comment by philwo** [comment]
I think if we just catch the exception here (it's probably trying to create the convenience symlinks), this should work.

As a workaround, does it work if you run `bazel build --symlink_prefix=/ ...`? This should disable the generation of the bazel-* symlinks that point to the output files.

**Comment by bashi** [comment]
Yes, passing `--symlink_prefix=/` worked :)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
