### ISSUE TITLE
Exception running bazel build ...

### ISSUE THREAD

**Issue by glinscott** [bazelbuild/bazel#696]
bazel build ... on my repository throws the following exception.

Callstack:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN:...' (requested by nodes )
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:968)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in rule bazel-j2objc
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:223)
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:64)
    at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:49)
    at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:146)
    at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:74)
    at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:72)
    at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:104)
    at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:159)
    at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:448)
    at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:54)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:932)
    ... 4 more
```

Note, I applied the following patch to get past a NullPointerException in NonConfigurableAttributeMapper:

```
diff --git a/src/main/java/com/google/devtools/build/lib/packages/NonconfigurableAttributeMapper.java b/src/main/java/com/googl
index e49aaa4..01259d4 100644
--- a/src/main/java/com/google/devtools/build/lib/packages/NonconfigurableAttributeMapper.java
+++ b/src/main/java/com/google/devtools/build/lib/packages/NonconfigurableAttributeMapper.java
@@ -42,8 +42,10 @@ public class NonconfigurableAttributeMapper extends AbstractAttributeMapper {

   @Override
   public <T> T get(String attributeName, com.google.devtools.build.lib.syntax.Type<T> type) {
-    Preconditions.checkState(!getAttributeDefinition(attributeName).isConfigurable(),
-        "Attribute '%s' is potentially configurable - not allowed here", attributeName);
+    if (getAttributeDefinition(attributeName) != null) {
+      Preconditions.checkState(!getAttributeDefinition(attributeName).isConfigurable(),
+          "Attribute '%s' is potentially configurable - not allowed here", attributeName);
+    }
     return super.get(attributeName, type);
   }
 }
```

**Comment by glinscott** [comment]
Forgot to mention the version of bazel, it's latest master: 30df02a567cbd8a307b96037f0960fca66a5deaf.

**Comment by glinscott** [comment]
I should also mention that it's just a collection of c++ programs, nowhere in my project do I use bazel-j2objc.  Also, if I don't build from the root directory, ie. `bazel build //src/...` it works fine, so it looks related to the base workspace stuff.

**Comment by davidstanke** [comment]
Closing this as it relates to a very old version of Bazel. If it's still an issue, please open a fresh issue. Thanks!
