### ISSUE TITLE
0.21.0 FTBFS: 

### ISSUE THREAD

**Issue by vbatts** [bazelbuild/bazel#6965]
### Description of the problem / feature request:

Building the 0.21.0 dist for fedora
```shell
[vbatts@getdown] {master *} ~/src/github.com/vbatts/copr-build-bazel$ make rpm
warning: Macro expanded in comment on line 2: %define _disable_source_fetch 0 

warning: Macro expanded in comment on line 2: %define _disable_source_fetch 0 

warning: Macro expanded in comment on line 2: %define _disable_source_fetch 0 

rpmbuild \
                --define '_sourcedir /home/vbatts/src/github.com/vbatts/copr-build-bazel' \
                --define '_specdir /home/vbatts/src/github.com/vbatts/copr-build-bazel' \
                --define '_builddir /home/vbatts/src/github.com/vbatts/copr-build-bazel' \
                --define '_srcrpmdir /home/vbatts/src/github.com/vbatts/copr-build-bazel' \
                --define '_rpmdir /home/vbatts/src/github.com/vbatts/copr-build-bazel' \
                -bb ./bazel.spec
warning: Macro expanded in comment on line 2: %define _disable_source_fetch 0 

Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.OTOKTI
+ umask 022
+ cd /home/vbatts/src/github.com/vbatts/copr-build-bazel
+ cd /home/vbatts/src/github.com/vbatts/copr-build-bazel
+ rm -rf bazel-0.21.0
+ /usr/bin/mkdir -p bazel-0.21.0
+ cd bazel-0.21.0
+ /usr/bin/unzip -qq /home/vbatts/src/github.com/vbatts/copr-build-bazel/bazel-0.21.0-dist.zip
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (rpm-jdk8.patch):'
Patch #0 (rpm-jdk8.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p0 --fuzz=0
patching file tools/jdk/default_java_toolchain.bzl
Hunk #2 succeeded at 53 (offset 1 line).
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ValPGc
+ umask 022
+ cd /home/vbatts/src/github.com/vbatts/copr-build-bazel
+ cd bazel-0.21.0
+ CC=gcc
+ CXX=g++
+ ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: b6b66936-28fb-4f56-8ce9-03189d7d032b
DEBUG: /tmp/bazel_30EsNOEf/out/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed target //src:bazel_nojdk (238 packages loaded, 10688 targets configured).
INFO: Found 1 target...
ERROR: /home/vbatts/src/github.com/vbatts/copr-build-bazel/bazel-0.21.0/tools/jdk/BUILD:188:1: SkylarkAction tools/jdk/platformclasspath.jar failed (Exit 1): java failed: error executing command 
  (cd /tmp/bazel_30EsNOEf/out/execroot/io_bazel && \
  exec env - \
  external/remotejdk_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/k8-opt/bin/tools/jdk/platformclasspath_classes:external/remotejdk_linux/lib/tools.jar DumpPlatformClassPath bazel-out/k8-opt/bin/tools/jdk/platformclasspath.jar external/local_jdk)
Execution platform: @bazel_tools//platforms:host_platform
Exception in thread "main" java.nio.file.NoSuchFileException: external/local_jdk/jre/lib/ext/java-atk-wrapper.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:159)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:97)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 10.185s, Critical Path: 2.17s
INFO: 31 processes: 31 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
error: Bad exit status from /var/tmp/rpm-tmp.ValPGc (%build)


RPM build errors:
    Macro expanded in comment on line 2: %define _disable_source_fetch 0

    Bad exit status from /var/tmp/rpm-tmp.ValPGc (%build)
make: *** [Makefile:18: rpm] Error 1
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

on a fedora machine
```shell
git clone https://github.com/vbatts/copr-build-bazel
cd copr-build-bazel
make rpm
```

### What operating system are you running Bazel on?

```shell
[vbatts@getdown] {master *} ~/src/github.com/vbatts/copr-build-bazel$ cat /etc/*release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Server Edition)"
ID=fedora
VERSION_ID=28
VERSION_CODENAME=""
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Comment by laurentlb** [comment]
cc @cushon @meisterT

**Comment by cushon** [comment]
@iirina

**Comment by meisterT** [comment]
What was the fix here? https://github.com/bazelbuild/bazel/issues/6150

**Comment by vbatts** [comment]
On 19/12/18 11:56 -0500, Tobias Werth wrote:
>   What was the fix here? [1]#6150

I have not reviewed the differences from 0.17.1 -> 0.17.2, but the error
output is different from this. Right?

**Comment by laurentlb** [comment]
If someone can run a `git bisect`, that would be very useful.

**Comment by meisterT** [comment]
@vbatts is it possible that the workaround for https://github.com/bazelbuild/bazel/issues/6550 is causing the problem here?
That means, does the build work for you if you don't apply https://github.com/vbatts/copr-build-bazel/blob/master/rpm-jdk8.patch ?

**Comment by vbatts** [comment]
On 19/12/18 13:10 -0500, Tobias Werth wrote:
>   [1]@vbatts is it possible that the workaround for [2]#6550 is causing
>   the problem here?
>   That means, does the build work for you if you don't apply
>   [3]https://github.com/vbatts/copr-build-bazel/blob/master/rpm-jdk8.patch ?

oh oh, right. One sec. Let me check.

**Comment by meisterT** [comment]
Hmm, I cannot repro. If I do the following, the build succeeds for me:
`docker run -it fedora:latest /bin/bash`

and then in the docker container:
```
dnf install rpm-build java-1.8.0-openjdk-devel zlib-devel pkgconfig python gcc-c++
cd /root
curl https://raw.githubusercontent.com/vbatts/copr-build-bazel/master/bazel.spec > bazel.spec
vi bazel.spec # uncomment patching in line 29
curl https://raw.githubusercontent.com/vbatts/copr-build-bazel/master/rpm-jdk8.patch > rpm-jdk8.patch # just because it's referenced in the spec file
rpmbuild -bb --target x86_64 --nodeps bazel.spec
dnf install /root/rpmbuild/RPMS/x86_64/bazel-0.21.0-1.fc28.x86_64.rpm
bazel version
```

How is this different from what you're doing?

**Comment by vbatts** [comment]
On 19/12/18 14:07 -0500, Tobias Werth wrote:
>   Hmm, I cannot repro. If I do the following, the build succeeds for me:
>   docker run -it fedora:latest /bin/bash
>
>   and then in the docker container:
>dnf install rpm-build java-1.8.0-openjdk-devel zlib-devel pkgconfig python gcc-c
>++
>cd /root
>curl https://raw.githubusercontent.com/vbatts/copr-build-bazel/master/bazel.spec
> > bazel.spec
>vi bazel.spec # uncomment patching in line 29
>curl https://raw.githubusercontent.com/vbatts/copr-build-bazel/master/rpm-jdk8.p
>atch > rpm-jdk8.patch # just because it's referenced in the spec file
>rpmbuild -bb --target x86_64 --nodeps bazel.spec
>dnf install /root/rpmbuild/RPMS/x86_64/bazel-0.21.0-1.fc28.x86_64.rpm
>bazel version
>
>   How is this different from what you're doing?

hmm! You're right. My local build host must have gone awry. I usually
smoke test there before sending to the copr build.
I just made a simple Dockerfile to do that smoketest in.

I've kicked off the build for 0.21.0 release
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/838751/
