### ISSUE TITLE
linkstamp not working under windows

### ISSUE THREAD

**Issue by iceboy233** [bazelbuild/bazel#6997]
### Description of the problem / feature request:

linkstamp not working under windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`BUILD`

```
cc_library(
    name = "stamp",
    linkstamp = "stamp.cc",
)

cc_binary(
    name = "main",
    deps = [":stamp"],
)
```

Create `WORKSPACE` and `stamp.cc` as empty file.

Run `bazel build :main`

### What operating system are you running Bazel on?

windows 7 x64

### What's the output of `bazel info release`?

```
INFO: Invocation ID: cc88fec2-4534-4815-9258-15066d7e79b3
release 0.21.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
INFO: Invocation ID: e87fb112-53df-40f4-9fa6-28c9b57dc0ba
Loading:
Loading: 0 packages loaded
Analyzing: target //:main (1 packages loaded, 0 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeExcep
tion: Unrecoverable error while evaluating node '//:main BuildConfigurationValue
.Key[99c851308ce672690ab47bd8a8e4cb79] false' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exe
c(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Sourc
e)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.get
Variables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.cre
ateLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamic
Library(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkA
ctions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkin
gHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLink
ingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:3
99)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:422)
        ... 5 more

INFO: Elapsed time: 1.707s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 68 targets confi
gured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeExcep
tion: Unrecoverable error while evaluating node '//:main BuildConfigurationValue
.Key[99c851308ce672690ab47bd8a8e4cb79] false' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exe
c(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Sourc
e)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.get
Variables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.cre
ateLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamic
Library(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkA
ctions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkin
gHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLink
ingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:3
99)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:422)
        ... 5 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:main B
uildConfigurationValue.Key[99c851308ce672690ab47bd8a8e4cb79] false' (requested b
y nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exe
c(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Sourc
e)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.get
Variables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.cre
ateLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamic
Library(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkA
ctions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkin
gHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLink
ingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:3
99)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:422)
        ... 5 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:main B
uildConfigurationValue.Key[99c851308ce672690ab47bd8a8e4cb79] false' (requested b
y nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exe
c(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Sourc
e)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.get
Variables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.cre
ateLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamic
Library(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkA
ctions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkin
gHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLink
ingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:3
99)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:422)
        ... 5 more
FAILED: Build did NOT complete successfully (8 packages loaded, 68 targets confi
gured)
```

**Comment by laszlocsomor** [comment]
Thanks, I could repro this on Windows 10 x64 as well, and also with older Bazel versions (I tried 0.20.0, 0.19.0, 0.18.0).

**Comment by laszlocsomor** [comment]
AFAICT this is a bug in the C++ rules. /cc @hlopko @scentini @oquenchil

**Comment by hlopko** [comment]
It is indeed! I don't like crashes.

**Comment by pablitens** [comment]
@hlopko has this issue been fixed in P1 release? If not, any hope it gets attention any time soon?

**Comment by wrowe** [comment]
We have to address this in the very near-term for the envoyproxy. Note that the solution isn't apparent to us yet; there is no option to link.exe to embed an arbitrary binary blob.

**Comment by gregestren** [comment]
Given the age I reverted the priority to 'untriaged' to signal a request for a more current prioritization.

**Comment by wrowe** [comment]
It turned out that the linkstamp problem wasn't unique to Windows... Building a library for iOS already had a workaround. This is what we ended up using for Windows in envoyproxy. It would still be nice to have a more generalized solution. Perhaps using the resource compiler and manifest for dll or exe binaries?

**Comment by jheaff1** [comment]
This issue still occurs in bazel 4.2.1. Any update on when it will be fixed? @wrowe May I ask what your workaround was?

**Comment by gregestren** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
Sorry, I don't have any update on this.

**Comment by wrowe** [comment]
We have code common to the library implementation (for iOS) shared with the windows .exe target which ignores the gcc version text section altogether, and uses a typical global static const to return the version, instead.

**Comment by wrowe** [comment]
You can observe our manual_linkstamp logic here https://github.com/envoyproxy/envoy/tree/main/source/common/version

Particularly the BUILD logic. Our top level project .bazelrc toggles manual_stamp for windows targets.

**Comment by zaucy** [comment]
This issue was a blocker for us as well. I ended up making this small header codegen to get us past it. https://github.com/zaucy/rules_cc_stamp
