### ISSUE TITLE
Cannot build gerrit from Bazel@HEAD: com.google.devtools.build.lib.syntax.Environment$Builder$1 cannot be cast to com.google.devtools.build.lib.analysis.skylark.BazelStarlarkContext

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#7102]
Trying to build gerrit@HEAD (5c4bea21ef74170e701db74a1498915771406bab) with Bazel@HEAD(890dfa018882c08c3b54a5c70e9d479cf1392cfd) is failing:

```
$ b10 build :release
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 40827892-20ec-42b8-ab58-6951c0b913ae
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:98:7: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.19.0.
ERROR: /home/davido/projects/gerrit2/WORKSPACE:42:1: Traceback (most recent call last):
	File "/home/davido/projects/gerrit2/WORKSPACE", line 42
		closure_repositories(omit_aopalliance = True, omit_java...)
	File "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/io_bazel_rules_closure/closure/repositories.bzl", line 124, in closure_repositories
		com_google_javascript_closure_library()
	File "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/io_bazel_rules_closure/closure/repositories.bzl", line 654, in com_google_javascript_closure_library
		http_archive(name = "com_google_javascript_cl...", <4 more arguments>)
	File "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/io_bazel_rules_closure/closure/repositories.bzl", line 662, in http_archive
		str(Label("//closure/library:closure..."))
	File "/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/io_bazel_rules_closure/closure/repositories.bzl", line 662, in str
		Label("//closure/library:closure_libra...")
com.google.devtools.build.lib.syntax.Environment$Builder$1 cannot be cast to com.google.devtools.build.lib.analysis.skylark.BazelStarlarkContext
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
INFO: Elapsed time: 13.245s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

The breakage is replicated on Bazel CI as well, with exactly the same stack trace:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/744#65581546-b9e8-4f77-93a6-da642b317894

Note, that all Gerrit jobs (Ubuntu 16.04@JDK 8, Ubuntu 18.04@JDK 9 and macOS) are affected. 

`rules_closure` is failing in the same way. In fact, Gerrit is only using `rules_closure` here.

Offending commit is here: https://github.com/bazelbuild/bazel/commit/f0a9c167879edb0bd6425709db22058c0ef547cc.

Revert is here: https://github.com/bazelbuild/bazel/pull/7103.

Thanks @philwo for making buildkite bazel CI public!

//cc @dkelmer

**Comment by dkelmer** [comment]
The offending PR was rolled back here: https://github.com/bazelbuild/bazel/commit/f44d947a858b29d833f55ebb7f9b49834378c871
