### ISSUE TITLE
Bazel CI: ERROR: Error evaluating WORKSPACE file

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7110]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/745#a166edbe-0167-4472-9b96-d3d4e6237bd3
"bazel info" is broken at HEAD with the following error message:
```
ERROR: Error evaluating WORKSPACE file
--
  | ERROR: error loading package 'external': Package 'external' contains errors
  | Traceback (most recent call last):
  | File "bazelci.py", line 1787, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1771, in main
  | incompatible_flags=args.incompatible_flag,
  | File "bazelci.py", line 471, in execute_commands
  | print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 614, in print_bazel_version_info
  | + ["--nomaster_bazelrc", "--bazelrc=/dev/null", "info"]
  | File "bazelci.py", line 1044, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  | File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['/tmp/tmpbslbufc7/bazel-bin/src/bazel', '--nomaster_bazelrc', '--bazelrc=/dev/null', 'info']' returned non-zero exit status 2.

ERROR: /var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/WORKSPACE:6:1: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/WORKSPACE", line 6
  | closure_repositories()
  | File "/var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/closure/repositories.bzl", line 124, in closure_repositories
  | com_google_javascript_closure_library()
  | File "/var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/closure/repositories.bzl", line 654, in com_google_javascript_closure_library
  | http_archive(name = "com_google_javascript_cl...", <4 more arguments>)
  | File "/var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/closure/repositories.bzl", line 662, in http_archive
  | str(Label("//closure/library:closure..."))
  | File "/var/lib/buildkite-agent/builds/bk-docker-dnlw/bazel-downstream-projects/rules_closure/closure/repositories.bzl", line 662, in str
  | Label("//closure/library:closure_libra...")
  | com.google.devtools.build.lib.syntax.Environment$Builder$1 cannot be cast to com.google.devtools.build.lib.analysis.skylark.BazelStarlarkContext
  | ERROR: Error evaluating WORKSPACE file
  | ERROR: error loading package 'external': Package 'external' contains errors
  | Traceback (most recent call last):
  | File "bazelci.py", line 1787, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1771, in main
  | incompatible_flags=args.incompatible_flag,
  | File "bazelci.py", line 471, in execute_commands
  | print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 614, in print_bazel_version_info
  | + ["--nomaster_bazelrc", "--bazelrc=/dev/null", "info"]
  | File "bazelci.py", line 1044, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  | File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)


```

Bisecting tells the culprit is: https://github.com/bazelbuild/bazel/commit/f0a9c167879edb0bd6425709db22058c0ef547cc

**Comment by meteorcloudy** [comment]
I'm rolling back the change
