### ISSUE TITLE
Firebase Crashlytics support for Android apps

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#7159]
Crashlytics for Android requires additional setup by the build system in order to work. For Gradle, this is done by the Crashlytics plugin: https://fabric.io/kits/android/crashlytics/install

On StackOverflow, we have users requesting for it Fabric support:

https://stackoverflow.com/questions/54144989/fabric-and-crashlytics-not-working-with-bazel-build
https://stackoverflow.com/questions/54237225/how-to-implement-fabric-crashlytics-in-android-with-bazel
https://stackoverflow.com/questions/53956134/how-to-import-a-specific-version-of-fabric-in-android

We'll use this thread to track the requirements to support Fabric integration in the Android rules.

**Comment by jin** [comment]
cc @ahumesky

**Comment by jin** [comment]
```
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     |  | 
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     |  |
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     |  |
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .   \ |  | /
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .    \    /
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     \  /
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .      \/
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: install an Android build tool and ask a team member to invite you to this app's organization.
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .      /\
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     /  \
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .    /    \
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .   / |  | \
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     |  |
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .     |  |
01-17 19:38:08.960 30253 30253 E CrashlyticsCore: .
01-17 19:38:08.962 30253 30253 E AndroidRuntime: FATAL EXCEPTION: main
01-17 19:38:08.962 30253 30253 E AndroidRuntime: Process: burrows.apps.example.template, PID: 30253
01-17 19:38:08.962 30253 30253 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.devtools.build.android.incrementaldeployment.StubApplication: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.google.devtools.build.android.incrementaldeployment.StubApplication.enableContentProviders(StubApplication.java:513)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.google.devtools.build.android.incrementaldeployment.StubApplication.onCreate(StubApplication.java:566)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	... 8 more
01-17 19:38:08.962 30253 30253 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.google.devtools.build.android.incrementaldeployment.StubApplication.enableContentProviders(StubApplication.java:507)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	... 11 more
01-17 19:38:08.962 30253 30253 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to get provider com.crashlytics.android.CrashlyticsInitProvider: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
01-17 19:38:08.962 30253 30253 E AndroidRuntime: install an Android build tool and ask a team member to invite you to this app's organization.
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	... 13 more
01-17 19:38:08.962 30253 30253 E AndroidRuntime: Caused by: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
01-17 19:38:08.962 30253 30253 E AndroidRuntime: install an Android build tool and ask a team member to invite you to this app's organization.
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:242)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:210)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:44)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:611)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:43)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.Kit.initialize(Kit.java:69)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:467)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.init(Fabric.java:411)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:369)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.with(Fabric.java:340)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at com.crashlytics.android.CrashlyticsInitProvider.onCreate(CrashlyticsInitProvider.java:27)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
01-17 19:38:08.962 30253 30253 E AndroidRuntime: 	... 14 more
```

These are the steps I took to get to the above crash while following the [official guide](https://firebase.google.com/docs/crashlytics/get-started?authuser=0#android):

1) Clone https://github.com/jaredsburrows/android-bazel-java-app-template
2) Set up a new Firebase project
3) Download google-services.json
4) Integrate google-services.json using [tools_android ](https://github.com/bazelbuild/tools_android)
5) Add `https://maven.fabric.io/public` to the list of repositories in `maven_install` in the WORKSPACE
6) Add `com.google.gms:google-services:4.2.0`, `com.google.firebase:firebase-core:16.0.6`, and `com.crashlytics.sdk.android:crashlytics:2.9.8` to `maven_install`. We skipped `io.fabric.tools:gradle:1.26.1` because it is a Gradle plugin, and Bazel doesn't (yet) know how to execute its tasks natively.
7) Have the app depend on the above artifacts. 
8) Because Bazel doesn't know how to apply plugins, we had no replacement for `apply plugin: 'io.fabric'`.
9) Launch the app with `bazel mobile-install //src/main:template_app --start_app`.

The next step is to figure out what the `io:fabric` plugin does (what files it generates), and try to replicate that in tools_android like what we did for google-services.json.

**Comment by jin** [comment]
Created a PR in tools_android to add Crashlytics integration: https://github.com/bazelbuild/tools_android/pull/2

**Comment by jin** [comment]
This is now available in tools_android. [Read the instructions here](https://github.com/bazelbuild/tools_android/blob/master/tools/crashlytics/README.md).
