### ISSUE TITLE
Bazel CI: rules_foreign_cc is broken on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7195]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/765#50422cac-b7e0-4d1c-a518-102b74f18738
```

ERROR: D:/b/rs3544hw/external/rules_foreign_cc_tests/cmake_hello_world_lib/static/BUILD:19:1: in cmake_external rule @rules_foreign_cc_tests//cmake_hello_world_lib/static:libhello_win:
--
  | Traceback (most recent call last):
  | File "D:/b/rs3544hw/external/rules_foreign_cc_tests/cmake_hello_world_lib/static/BUILD", line 19
  | cmake_external(name = 'libhello_win')
  | File "D:/b/rs3544hw/external/rules_foreign_cc/tools/build_defs/cmake.bzl", line 47, in _cmake_external
  | cc_external_rule_impl(ctx, attrs)
  | File "D:/b/rs3544hw/external/foreign_cc_impl/framework.bzl", line 200, in cc_external_rule_impl
  | _define_out_cc_info(ctx, attrs, inputs, outputs)
  | File "D:/b/rs3544hw/external/foreign_cc_impl/framework.bzl", line 549, in _define_out_cc_info
  | create_linking_info(ctx, attrs.linkopts, outputs.librari...)
  | File "D:/b/rs3544hw/external/foreign_cc_impl/cc_toolchain_util.bzl", line 200, in create_linking_info
  | cc_common.create_linking_context(user_link_flags = user_link_flag..., ...))
  | File "D:/b/rs3544hw/external/foreign_cc_impl/cc_toolchain_util.bzl", line 202, in cc_common.create_linking_context
  | _create_libraries_to_link(ctx, files)
  | File "D:/b/rs3544hw/external/foreign_cc_impl/cc_toolchain_util.bzl", line 77, in _create_libraries_to_link
  | cc_common.create_library_to_link(actions = ctx.actions, feature_con..., <6 more arguments>)
  | Must pass parameters: static_library, pic_static_library, dynamic_library, interface_library and alwayslink.


```

/cc @oquenchil @irengrig

**Comment by irengrig** [comment]
Resolved by a fix of C++ team. Closing.
//ccc @hlopko
