### ISSUE TITLE
NullPointerException in WorkspaceFactory

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#724]
With bazel HEAD (99a89acf4c7608eb56d77cb746db32842833c6c1):

```
$ $BAZEL_PATH/bazel --batch build :r
Extracting Bazel installation...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/private/tmp/test/m]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
INFO: Elapsed time: 1.176s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/private/tmp/test/m]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:982)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.packages.WorkspaceFactory.setImportedExtensions(WorkspaceFactory.java:157)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.loadSkylarkImports(WorkspaceFileFunction.java:116)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.parse(WorkspaceFileFunction.java:123)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:90)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
	... 4 more
```

With lberki@ repro case:
```
mkdir -p m r
cat > m/WORKSPACE <<EOF
m/WORKSPACE:
local_repository(name="r", path="$PWD/r")
EOF

cat > m/BUILD << EOF
filegroup(name="r", srcs=["@r//:rfg"])
EOF

cat > r/BUILD <<EOF
load("r", "r_filegroup")
r_filegroup(name="rfg", srcs=["rfgf"])
EOF

cat > r/r.bzl <<EOF
def r_filegroup(name, srcs):
    native.filegroup(name=name, srcs=srcs)
EOF

cd m
bazel --batch build :r
```

**Comment by damienmg** [comment]
Simpler repro: put any error in the WORKSPACE file.

**Comment by damienmg** [comment]
Humm cannot reproduce inside a test case, weird

Minimal repro outside:
```

cat > m/BUILD <<EOF
filegroup(name="r", srcs=["@r//:rfg"])
EOF

cat > m/WORKSPACE <<EOF
m/WORKSPACE:
local_repository(name="r", path="//dfs")
EOF

cd m
bazel --batch build :r
```
