### ISSUE TITLE
bazel doesn't work when $HOME path contains non-ASCII characters

### ISSUE THREAD

**Issue by davispuh** [bazelbuild/bazel#7255]
### Description of the problem / feature request:

bazel doesn't work when $HOME path contains non-ASCII characters

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ mkdir /tmp/tēst
$ export HOME=/tmp/tēst
$ bazel version
```

### What operating system are you running Bazel on?

ArchLinux

### What's the output of `bazel version`?

```
Build label: 0.21.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 20 19:15:52 2018 (1545333352)
Build timestamp: 1545333352
Build timestamp as int: 1545333352
```

### Any other information, logs, or outputs that you want to share?

Note that `LANG=lv_LV.UTF-8`

When using ArchLinux provided binary
```
[bazel INFO src/main/cpp/option_processor.cc:359] Looking for the following rc files: /etc/bazel.bazelrc,/mnt/Build/bazel-git/src/bazel-git/.bazelrc,/tmp/tēst/.bazelrc
[bazel INFO src/main/cpp/blaze.cc:1552] Debug logging requested, sending all client log statements to stderr
[bazel INFO src/main/cpp/blaze.cc:1572] Acquired the client lock, waited 0 milliseconds
[bazel USER src/main/cpp/blaze.cc:853] Starting local Bazel server and connecting to it...
[bazel USER src/main/cpp/blaze.cc:892] Server crashed during startup. Now printing /tmp/tēst/.cache/bazel/_bazel_Viesis/49d083d1a0368b9a8f85b056b4534a36/server/jvm.out
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/t??st/.cache/bazel/_bazel_Viesis/install/90846db665bd444d85cd9a305cffe931/_embedded_binaries/A-server.jar
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
        at java.base/java.io.File.toPath(File.java:2290)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1220)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:341)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:312)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:251)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:420)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:637)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:547)

```

Then I compiled latest git master branch but got this instead
```
[bazel INFO src/main/cpp/option_processor.cc:377] Looking for the following rc files: /etc/bazel.bazelrc,/mnt/Build/bazel-git/src/bazel-git/.bazelrc,/tmp/tēst/.bazelrc
[bazel INFO src/main/cpp/blaze.cc:1551] Debug logging requested, sending all client log statements to stderr
[bazel INFO src/main/cpp/blaze.cc:1571] Acquired the client lock, waited 0 milliseconds
[bazel USER src/main/cpp/blaze.cc:853] Starting local Bazel server and connecting to it...
[bazel USER src/main/cpp/blaze.cc:892] Server crashed during startup. Now printing /tmp/tēst/.cache/bazel/_bazel_Viesis/49d083d1a0368b9a8f85b056b4534a36/server/jvm.out
Error occurred during initialization of VM
java.lang.UnsatisfiedLinkError: no zip in java.library.path
        at java.lang.ClassLoader.loadLibrary(java.base/Unknown Source)
        at java.lang.Runtime.loadLibrary0(java.base/Unknown Source)
        at java.lang.System.loadLibrary(java.base/Unknown Source)
        at java.lang.System.initPhase1(java.base/Unknown Source)
```

Then if I tried to run `A-server.jar` directly with java, I got

```
java.util.logging.ErrorManager: 4: Failed to open log file
java.io.FileNotFoundException: /tmp/tÄst/.cache/bazel/_bazel_Viesis/49d083d1a0368b9a8f85b056b4534a36/java.log.tebra5.Viesis.log.java.20190125-174807.12855 (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.devtools.build.lib.util.SimpleLogHandler$Output.open(SimpleLogHandler.java:712)
        at com.google.devtools.build.lib.util.SimpleLogHandler.openOutputIfNeeded(SimpleLogHandler.java:799)
        at com.google.devtools.build.lib.util.SimpleLogHandler.publish(SimpleLogHandler.java:418)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at java.logging/java.util.logging.Logger.doLog(Unknown Source)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at java.logging/java.util.logging.Logger.info(Unknown Source)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.logVersionInfo(BlazeVersionInfo.java:64)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.setBuildInfo(BlazeVersionInfo.java:79)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:68)
Cannot enumerate embedded binaries: /tmp/t?st/.cache/bazel/_bazel_Viesis/install/affda12acdf59171a8bb4a4636ada39f/_embedded_binaries (No such file or directory)
```

Note, that first logging error is because logging `prefix` is written in locale encoding (UTF-8)
```
$ cat /tmp/tēst/.cache/bazel/_bazel_Viesis/49d083d1a0368b9a8f85b056b4534a36/javalog.properties
handlers=com.google.devtools.build.lib.util.SimpleLogHandler
.level=INFO
com.google.devtools.build.lib.util.SimpleLogHandler.level=INFO
com.google.devtools.build.lib.util.SimpleLogHandler.prefix=/tmp/tēst/.cache/bazel/_bazel_Viesis/49d083d1a0368b9a8f85b056b4534a36/java.log
com.google.devtools.build.lib.util.SimpleLogHandler.limit=1024000
com.google.devtools.build.lib.util.SimpleLogHandler.total_limit=20971520
com.google.devtools.build.lib.util.SimpleLogHandler.formatter=com.google.devtools.build.lib.util.SingleLineFormatter
```

But Java reads it as `ISO 8859-1`. Non-ASCII characters should be encoded using `\uXXXX` code points.
See [Properties.load()](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#load(java.io.InputStream))

> Reads a property list (key and element pairs) from the input byte stream.The input stream is in a simple line-oriented format as specified in load(Reader) and is assumed to use the ISO 8859-1 character encoding; that is each byte is one Latin1 character. Characters not in Latin1, and certain special characters, are represented in keys and elements using Unicode escapes as defined in section 3.3 of The Java™ Language Specification.

**Comment by irengrig** [comment]
probably related: #374

**Comment by irengrig** [comment]
Have you tried -Dsun.jnu.encoding=UTF-8?

**Comment by davispuh** [comment]
With ArchLinux provided bazel `0.22.0`

```
$ bazel version
Extracting Bazel installation...
Error: An unexpected error occurred while trying to open file /tmp/t??st/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b/_embedded_binaries/A-server.jar
```

> Have you tried -Dsun.jnu.encoding=UTF-8?
Makes no difference:

```
$ java "-Dsun.jnu.encoding=UTF-8" "-Djava.library.path=/tmp/tēst/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b/_embedded_binaries/" "-Dfile.encoding=ISO-8859-1" "-jar" "/tmp/tēst/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b/_embedded_binaries/A-server.jar" "--batch" "--output_user_root=/tmp/tēst/.cache/bazel/_bazel_Viesis" "--install_base=/tmp/tēst/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b" "--install_md5=5b71f1c3449ce6d1b7b4dca217afa78b" "--output_base=/tmp/tēst/.cache/bazel/_bazel_Viesis/d41d8cd98f00b204e9800998ecf8427e" "version"
febr. 08, 2019 10:20:05 PM com.google.devtools.build.lib.analysis.BlazeVersionInfo logVersionInfo
INFO: Bazel version info: Build label: 0.22.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 19:53:21 2019 (1548705201)
Build timestamp: 1548705201
Build timestamp as int: 1548705201
febr. 08, 2019 10:20:05 PM com.google.devtools.build.lib.runtime.BlazeRuntime batchMain
INFO: Running Bazel in batch mode with pid 16661 and startup args [--batch, --output_user_root=/tmp/t?st/.cache/bazel/_bazel_Viesis, --install_base=/tmp/t?st/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b, --install_md5=5b71f1c3449ce6d1b7b4dca217afa78b, --output_base=/tmp/t?st/.cache/bazel/_bazel_Viesis/d41d8cd98f00b204e9800998ecf8427e]
Cannot enumerate embedded binaries: /tmp/t?st/.cache/bazel/_bazel_Viesis/install/5b71f1c3449ce6d1b7b4dca217afa78b/_embedded_binaries (No such file or directory)
```
