### ISSUE TITLE
NullPointerException from `analyze-profile --vfs_stats`

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#726]
```
$ bazel analyze-profile --vfs_stats /tmp/bazel.prof

...
java.lang.NullPointerException
        at com.google.devtools.build.lib.profiler.output.PhaseText.printVfsStatistics(PhaseText.java:206)
        at com.google.devtools.build.lib.profiler.output.PhaseText.printPhaseStatistics(PhaseText.java:111)
        at com.google.devtools.build.lib.profiler.output.PhaseText.print(PhaseText.java:67)
        at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:283)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:371)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1016)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
        at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
        at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:975)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:772)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)
```

```
$ bazel analyze-profile --html --html_details --vfs_stats /tmp/bazel.prof

...
java.lang.NullPointerException
        at com.google.devtools.build.lib.profiler.output.PhaseHtml.printVfsStatistics(PhaseHtml.java:227)
        at com.google.devtools.build.lib.profiler.output.PhaseHtml.printPhaseStatistics(PhaseHtml.java:132)
        at com.google.devtools.build.lib.profiler.output.PhaseHtml.print(PhaseHtml.java:115)
        at com.google.devtools.build.lib.profiler.output.HtmlCreator.print(HtmlCreator.java:77)
        at com.google.devtools.build.lib.profiler.output.HtmlCreator.create(HtmlCreator.java:195)
        at com.google.devtools.build.lib.runtime.commands.ProfileCommand.exec(ProfileCommand.java:263)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:371)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1016)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
        at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
        at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:975)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:772)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)
```

**Comment by ulfjack** [comment]
I've seen the same issue in our internal binary. I think it's a serious issue because it makes the profiling unusable.
