### ISSUE TITLE
javac turbine needs to be updated

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#7297]
Since d42a026e63872efb9f9f3879248ddf4431c65d20, I've been seeing failures like this:
```
java -Xverify:none -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9+181-r4173-1.jar -jar external/bazel_tools/tools/jdk/turbine_deploy.jar --output ... (remaining 221 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox.
Exception in thread "main" java.lang.IllegalArgumentException: unknown option: --reduce_classpath
	at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:123)
	at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:53)
	at com.google.turbine.options.TurbineOptionsParser.parse(TurbineOptionsParser.java:41)
	at com.google.devtools.build.java.turbine.javac.JavacTurbine.main(JavacTurbine.java:81)
```

**Comment by cushon** [comment]
Hmm, I thought I had updated it: 9259683c6b460629d1ca83759ce26fa76839558d

Are you building with any `--incompatible_` flags?

**Comment by benjaminp** [comment]
I think the problem is that there's also `third_party/java/java_tools/turbine_deploy.jar`.

**Comment by benjaminp** [comment]
I hacked up an integration test to demonstrate the problem:
```
$ git diff
diff --git a/src/test/shell/integration/java_integration_test.sh b/src/test/shell/integration/java_integration_test.sh
index 9435e13101..fc0790afea 100755
--- a/src/test/shell/integration/java_integration_test.sh
+++ b/src/test/shell/integration/java_integration_test.sh
@@ -634,6 +634,7 @@ java_library(name = 'processor_dep',
 
 java_plugin(name = 'processor',
   processor_class = 'test.processor.Processor',
+  generates_api = True,
   deps = [ ':annotation', ':processor_dep' ],
   srcs = [ 'Processor.java' ])
 EOF
@@ -695,6 +696,10 @@ java_library(name = 'client',
      srcs = [ 'ProcessorClient.java' ],
      deps = [ '//$pkg/java/test/processor:annotation' ],
   plugins = [ '//$pkg/java/test/processor:processor' ])
+
+java_binary(name = 'bin',
+  srcs = ['MyBinary.java'],
+  deps = [':client'])
 EOF
 
   cat >$pkg/java/test/client/ProcessorClient.java <<EOF
@@ -704,11 +709,19 @@ import test.processor.TestAnnotation;
 class ProcessorClient { }
 EOF
 
-  bazel build ${bazel_opts[@]+"${bazel_opts[@]}"} //$pkg/java/test/client:client --use_ijars || fail "build failed"
+  cat > $pkg/java/test/client/MyBinary.java <<EOF
+class MyBinary {
+  public static void main(String[] args) {
+    new ProcessorClient();
+  }
+}
+EOF
+
+  bazel build ${bazel_opts[@]+"${bazel_opts[@]}"} //$pkg/java/test/client:bin || fail "build failed"
   unzip -l ${PRODUCT_NAME}-bin/$pkg/java/test/client/libclient.jar > $TEST_log
   expect_log " test/Generated.class" "missing class file from annotation processing"
 
-  bazel build ${bazel_opts[@]+"${bazel_opts[@]}"} //$pkg/java/test/client:libclient-src.jar --use_ijars \
+  bazel build ${bazel_opts[@]+"${bazel_opts[@]}"} //$pkg/java/test/client:libclient-src.jar \
     || fail "build failed"
   unzip -l ${PRODUCT_NAME}-bin/$pkg/java/test/client/libclient-src.jar > $TEST_log
   expect_log " test/Generated.java" "missing source file from annotation processing"
$ bazel test //src/test/shell/integration:java_integration_test --test_filter test_java_plugin
```

**Comment by cushon** [comment]
Thanks, I'd forgotten about #7196.

It's concerning that there apparently aren't any integration tests using `generates_api`.

@lberki are there plans for more automation around `third_party/java/java_tools/update_java_tools.sh`?

**Comment by benjaminp** [comment]
Closing since 92adff893fbd185269bf734abf4d3b12d3117ebc fixed the immediate problem. It doesn't seem like there should be an integration test for javac turbine.

**Comment by Monnoroch** [comment]
I'm getting this error on 0.23.0 with `--all_incompatible_changes`.
