### ISSUE TITLE
Tensorflow is broken on our CI

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#7340]
For example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/789#c2b2e112-acbe-44d5-8853-14188417bc45

Message:
```

You have bazel 0.22.0 installed.
--
  | Please downgrade your bazel installation to version 0.21.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
  | Traceback (most recent call last):
  | File "bazelci.py", line 1923, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1907, in main
  | incompatible_flags=args.incompatible_flag,
  | File "bazelci.py", line 514, in execute_commands
  | execute_shell_commands(config.get("shell_commands", None))
  | File "bazelci.py", line 781, in execute_shell_commands
  | execute_command([shell_command], shell=True)
  | File "bazelci.py", line 1102, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  | File "/usr/lib/python3.6/subprocess.py", line 418, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['echo \'\nimport %workspace%/.bazelrc\' >>bazel.bazelrc\necho \'\nandroid_sdk_repository(name = "androidsdk")\nandroid_ndk_repository(name = "androidndk")\' >>WORKSPACE\ntouch .bazelrc\n./tensorflow/tools/ci_build/builds/configured CPU']' returned non-zero exit status 1.
```

We should either help Tensorflow to upgrade and/or remove them (temporarily?) from CI.

**Comment by rongjiecomputer** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/91da898cb6f6b0e751e15ceb813a37cdfe18a035#diff-ade1d3e4b7c35655f854151d899df62b

**Comment by meisterT** [comment]
Thanks!
