### ISSUE TITLE
pkg_deb fails when control fields contain unicode/utf-8 encoded characters

### ISSUE THREAD

**Issue by imcginnis** [bazelbuild/bazel#7370]
### Description of the problem:

pkg_deb fails when control fields contain unicode characters or the contents of utf-8 encoded files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using the following:
```shell
~/utf8-test$ ls
BUILD  WORKSPACE
```

WORKSPACE
```
```

BUILD
```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_tar(
  name = "data",
)

pkg_deb(
  name = "utf8-test",
  data = ":data",
  maintainer = "foo",
  description = "Unicode symbols ®, Δ, Й, ק ,م, ๗, あ,  叶, 葉, 말, ü and  é",
  package = "utf8-test",
  version = "1.0",
)
```

You will get an error message like the following:
```
~/utf8-test$ bazel build :utf8-test --verbose_failures
INFO: Invocation ID: 4831418c-4a4a-41f7-abf4-d18b50934194
INFO: Analysed target //:utf8-test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/user/utf8-test/BUILD:7:1: MakeDeb utf8-test_1.0_all.deb failed (Exit 1) make_deb failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb '--output=bazel-out/k8-fastbuild/bin/utf8-test_1.0_all.deb' '--changes=bazel-out/k8-fastbuild/bin/utf8-test_1.0_all.changes' '--data=bazel-out/k8-fastbuild/bin/data.tar' '--package=utf8-test' '--architecture=all' '--maintainer=foo' '--version=1.0' '--description=Reserved symbol®' '--distribution=unstable' '--urgency=medium')
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox: make_deb failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb '--output=bazel-out/k8-fastbuild/bin/utf8-test_1.0_all.deb' '--changes=bazel-out/k8-fastbuild/bin/utf8-test_1.0_all.changes' '--data=bazel-out/k8-fastbuild/bin/data.tar' '--package=utf8-test' '--architecture=all' '--maintainer=foo' '--version=1.0' '--description=Reserved symbol®' '--distribution=unstable' '--urgency=medium')
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/sandbox/linux-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 342, in <module>
    main(FLAGS(sys.argv))
  File "/home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/sandbox/linux-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 328, in main
    installedSize=GetFlagValue(FLAGS.installed_size))
  File "/home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/sandbox/linux-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 195, in CreateDeb
    control = CreateDebControl(extrafiles=extrafiles, **kwargs)
  File "/home/user/.cache/bazel/_bazel_user/e6e7bd4474c6bcca1dea3235a205b76e/sandbox/linux-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 163, in CreateDebControl
    f.addfile(tarinfo, fileobj=BytesIO(controlfile.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 136: ordinal not in range(128)
Target //:utf8-test failed to build
INFO: Elapsed time: 0.349s, Critical Path: 0.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```

### What operating system are you running Bazel on?

Ubuntu 16.04 & 18.04

### What's the output of `bazel info release`?

`release 0.22.0`

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Bazel used to work with the "®" symbol in the description field. It seems like the changes to make pkg defs Python 2/3 compatible here: https://github.com/bazelbuild/bazel/commit/6fff4da5f5e436551aa9294b58960da1d64af39a may have introduced the bug. Based on some initial StackOverflow searching it seems like using .decode("utf-8") on the input may be necessary. https://stackoverflow.com/a/16508962 If it's alright, I'd be happy to submit a patch on `tools/build_defs/pkg/make_deb.py` along those lines.

**Comment by jwnimmer-tri** [comment]
If I'm understanding my build errors correctly, this change re-broke the py2/3 compatibility on make_deb.py that #6818 had previously fixed.

```
  File ".../bazel-out/k8-opt/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 301, in GetFlagValue
    flagvalue = flagvalue.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

It's possible that the toolchain changes in 0.25.0 are also at fault and/or the only problem, but with the binary tagged `PY2AND3`, the code doesn't look correct to me on first read.

**Comment by aiuto** [comment]
See https://github.com/bazelbuild/rules_pkg/issues/35
