### ISSUE TITLE
NullPointer in MessageDigest.java

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#742]
Just updated to HEAD (been 5+ weeks).

I ran 'git bisect' and determined that this was broken by:
https://github.com/bazelbuild/bazel/commit/6aff7f4f2bf0c6418fb88e967653f2feeb83819e

Is there some forced migration of WORKSPACE syntax?
This is a java repo with things like:

maven_jar(
    name = "guava-repo",
    artifact_id = "guava",
    group_id = "com.google.guava",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
    version = "18.0",
)

bind(
    name = "guava",
    actual = "@guava-repo//jar",
)

and then uses of "//external:guava"

Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY:@mockito-repo' (requested by nodes 'PACKAGE_LOOKUP:@mockito-repo//jar')
INFO: Elapsed time: 1.788s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY:@mockito-repo' (requested by nodes 'PACKAGE_LOOKUP:@mockito-repo//jar')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:982)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.security.MessageDigest.update(MessageDigest.java:335)
	at com.google.devtools.build.lib.util.Fingerprint.addBytes(Fingerprint.java:116)
	at com.google.devtools.build.lib.rules.repository.RepositoryFunction.computeRuleKey(RepositoryFunction.java:116)
	at com.google.devtools.build.lib.rules.repository.RepositoryFunction.isFilesystemUpToDate(RepositoryFunction.java:183)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:104)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
	... 4 more

**Comment by pmbethe09** [comment]
To clarify, I have not been able yet to create a bare-bones repro example.  But I see the identical issue on multiple java projects.

**Comment by pmbethe09** [comment]
... and apparently the issue is non-backwards compatibility.
I just needed to run:
bazel clean --expunge

**Comment by pmbethe09** [comment]
So, after an expunge, I can build/test fine.  
But... if I change my workspace - in my case changing an out of date junit 4.4 to the latest 4.12 resulted in the same issue, requiring another expunge and build.

**Comment by kchodorow** [comment]
I think there was code that could return null for the byte array that someone actually fixed last week.  Either it hasn't been pushed yet or I'm remembering incorrectly.

**Comment by pmbethe09** [comment]
Current head of d46f474733b048d9ef10dd13ec639b4521693d0a
from Tue Dec 22 21:01:47 2015 +0000
does not appear to have that fix.

**Comment by kchodorow** [comment]
Yeah, we haven't pushed in several days (and I cannot at the moment).

**Comment by pmbethe09** [comment]
Could be fixed -- can't verify as HEAD is broken

INFO: From Building src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib.jar (18 files):
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:323: error: incompatible types: StringBuilder cannot be converted to StringBuffer
          idMatcher.appendReplacement(resourceIds, String.format("public static int %s=0x%08X;",
                                      ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:326: error: incompatible types: StringBuilder cannot be converted to StringBuffer
        idMatcher.appendTail(resourceIds);
                             ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:327: error: incompatible types: StringBuilder cannot be converted to StringBuffer
        innerClassMatcher.appendReplacement(out,
                                            ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:330: error: incompatible types: StringBuilder cannot be converted to StringBuffer
      innerClassMatcher.appendTail(out);
                                   ^
Note: src/tools/android/java/com/google/devtools/build/android/ResourceShrinker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
4 errors
BazelJavaBuilder threw exception: java compilation returned status ERROR
ERROR: /Users//Tools/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:35:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android:android_builder_lib' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/bootstrap_deploy.jar ... (remaining 1 argument(s) skipped): Worker process sent response with exit code: 1.
Target //src:bazel failed to build

**Comment by pmbethe09** [comment]
Note, broken as of effa572812043181d05f8d7375f89bddbb4d9ee0

**Comment by kchodorow** [comment]
Head should now be fixed as of 0e72b69d0df6924537e8c4dd996c10c53586902c.

**Comment by mikea** [comment]
Still not fixed in 
$ bazel version
Build label: 0.1.3
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 11 10:25:30 2016 (1452507930)
Build timestamp: 1452507930
Build timestamp as int: 1452507930

maven_jar(
    name = "rxjava",
    artifact = "io.reactivex:rxjava:1.1.0",
    sha1 = "748f0546d5c3c27f1aef07270ffea0c45f0c42a4",
)


NFO: Elapsed time: 2.197s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY:@rxjava' (requested by nodes 'PACKAGE_LOOKUP:@rxjava//jar')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:982)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.security.MessageDigest.update(MessageDigest.java:335)
        at com.google.devtools.build.lib.util.Fingerprint.addBytes(Fingerprint.java:116)
        at com.google.devtools.build.lib.rules.repository.RepositoryFunction.computeRuleKey(RepositoryFunction.java:116)
        at com.google.devtools.build.lib.rules.repository.RepositoryFunction.isFilesystemUpToDate(RepositoryFunction.java:171)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:92)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
        ... 4 more

**Comment by damienmg** [comment]
0.1.3 did not included 0e72b69 so it is expected.
