### ISSUE TITLE
jvm_maven_import_external throws error when licenses attribute is missing/bad

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#7485]
To reproduce: can try running maven_test.sh test cases without a licenses attribute. 

Stacktrace: 

`Caused by: java.lang.IllegalArgumentException: wrong type for attribute "licenses" in jvm_import_external rule //external:endangered
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:78)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.visitLabels(AbstractAttributeMapper.java:192)
	at com.google.devtools.build.lib.packages.AggregatingAttributeMapper.visitLabels(AggregatingAttributeMapper.java:92)
	at com.google.devtools.build.lib.packages.AggregatingAttributeMapper.visitLabels(AggregatingAttributeMapper.java:75)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.visitLabels(AbstractAttributeMapper.java:183)
	at com.google.devtools.build.lib.packages.Rule.checkForNullLabels(Rule.java:684)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1825)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
	at com.google.devtools.build.lib.packages.WorkspaceFactoryHelper.createAndAddRepositoryRule(WorkspaceFactoryHelper.java:50)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryModule$RepositoryRuleFunction.call(SkylarkRepositoryModule.java:161)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:977)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:889)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:977)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:889)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:250)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:223)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:216)
	at com.google.devtools.build.lib.packages.WorkspaceFactory.execute(WorkspaceFactory.java:174)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:137)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
	... 4 more
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.packages.License cannot be cast to class java.util.List (com.google.devtools.build.lib.packages.License is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
	at com.google.devtools.build.lib.syntax.Type$ListType.cast(Type.java:538)
	at com.google.devtools.build.lib.syntax.Type$ListType.cast(Type.java:521)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:74)`

**Comment by meisterT** [comment]
The test was deleted a while ago.
