### ISSUE TITLE
Bazel CI: rules_k8s is broken by flipping --incompatible_disallow_dict_plus

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7488]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/816#65192acd-1436-4b76-b4ce-b527e7f768d2
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-x4kd/bazel-downstream-projects/rules_k8s/examples/hellogrpc/proto/BUILD:26:1: in proto_compile rule //examples/hellogrpc/proto:simple_cc_grpc_pb:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-x4kd/bazel-downstream-projects/rules_k8s/examples/hellogrpc/proto/BUILD", line 26
  | proto_compile(name = 'simple_cc_grpc_pb')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/9b88f7df8d1df2f8703d35e5dddb98f0/external/build_stack_rules_proto/compile.bzl", line 523, in proto_compile_impl
  | _apply_plugin_transitivity_rules(ctx, targets, plugin)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/9b88f7df8d1df2f8703d35e5dddb98f0/external/build_stack_rules_proto/compile.bzl", line 319, in _apply_plugin_transitivity_rules
  | plugin.transitivity + ctx.attr.transitivity
  | The `+` operator for dicts is deprecated and no longer supported. Please use the `update` method instead. You can temporarily enable the `+` operator by passing the flag --incompatible_disallow_dict_plus=false


```
Suspect culprit: https://github.com/bazelbuild/bazel/commit/b6422285198f0a8851867ded469ee01ea51b8656

**Comment by laurentlb** [comment]
There's a pending pull request for this (https://github.com/bazelbuild/rules_k8s/issues/248#issuecomment-465728843).
