### ISSUE TITLE
java.lang.OutOfMemoryError backtrace when

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#7493]
On Bazel 0.22, when testing Envoy with:

```
bazel test --config libc++ --define signal_trace=disabled  --define hot_restart=disabled --define google_grpc=disabled --define boringssl=fips --define log_debug_assert_in_release=enabled  --define tcmalloc=debug --define quiche=enabled //test/extensions/transport_sockets/tls:ssl_socket_test --test_output=all --runs_per_test=5  --test_arg="-l trace"
```

I observe the following backtrace:

```
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
        at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:176)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:221)
        at com.google.common.io.ByteSource.read(ByteSource.java:289)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.readContent(FileSystemUtils.java:835)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.readContentAsLatin1(FileSystemUtils.java:804)
        at com.google.devtools.build.lib.util.io.FileOutErr$FileRecordingOutputStream.getRecordedOutput(FileOutErr.java:402)
        at com.google.devtools.build.lib.util.io.FileOutErr.outAsLatin1(FileOutErr.java:132)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.dumpRecordedOutErr(SkyframeActionExecutor.java:1286)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.dumpRecordedOutErr(SkyframeActionExecutor.java:1265)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$1100(SkyframeActionExecutor.java:123)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.completeAction(SkyframeActionExecutor.java:916)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:855)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:787)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:541)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:697)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:240)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

This only seems to happen when we have the log level from the test cranked to maximum (`-l trace`).

**Comment by scentini** [comment]
This doesn't seem to be c++ related, @aehlig, as you have touched related code recently, do you know in which component this issue belongs?

**Comment by jin** [comment]
Sorry for the miscategorization, assigning to Local Exec.

**Comment by jmmv** [comment]
Well, the code referenced by this stacktrace has the following comment in `SkyframeActionExecutor.java`:

```
// Bind the output to the prefix event.
// Note: here we temporarily (until the event is handled by the UI) read all
// output into memory; as the output of regular actions (as opposed to test runs) usually is
// short, so this should not be a problem. If it does turn out to be a problem, we have to
// pass the outErrbuffer instead.
```

so your guess that a very long command output can be causing this is plausible.

**Comment by janakdr** [comment]
There have been some changes in this area recently. Is this still an issue?

**Comment by htuch** [comment]
Works fine with the original CLI invocation, so will close this out, thanks.
