### ISSUE TITLE
Bazel CI: remote execution is failing in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7508]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/818#b1049741-1377-4179-b82c-fbc9f265cf01

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-btlg/bazel-downstream-projects/bazel/src/main/java/com/google/devtools/build/lib/BUILD:154:1: Couldn't build file src/main/java/com/google/devtools/build/lib/libclasspath-util.jar: Building src/main/java/com/google/devtools/build/lib/libclasspath-util.jar (1 source file) failed (Exit 34). Note: Remote connection/protocol failed with: execution failed io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid arguments:
--
  | "command.output_files.duplicate_files": Duplicate output file: bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/libclasspath-util.jdeps: java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid arguments:
  | "command.output_files.duplicate_files": Duplicate output file: bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/libclasspath-util.jdeps
  | at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:176)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:248)
  | at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:233)
  | at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:103)
  | at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:240)
  | at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:218)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:112)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:77)
  | at com.google.devtools.build.lib.exec.ProxySpawnActionContext.exec(ProxySpawnActionContext.java:56)
  | at com.google.devtools.build.lib.rules.java.JavaCompileAction.execute(JavaCompileAction.java:295)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:941)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.lambda$run$0(SkyframeActionExecutor.java:903)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.completeAction(SkyframeActionExecutor.java:959)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:903)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:114)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:78)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:556)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:702)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:246)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid arguments:
  | "command.output_files.duplicate_files": Duplicate output file: bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/libclasspath-util.jdeps
  | at io.grpc.Status.asRuntimeException(Status.java:526)
  | at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:557)
  | at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$0(GrpcRemoteExecutor.java:140)
  | at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:233)
  | at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:103)
  | at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:129)
  | ... 23 more


```
https://buildkite.com/bazel/culprit-finder/builds/113#77a9715c-969e-4a54-8a83-fd69ea019676
Culprit finder gave 1898f41b807d846d3553db645e6d718ba2348a60

**Comment by ulfjack** [comment]
This should be fixed by 5e46d7c2f2f2fdfaebc29d3b74400f2437d43833.
