### ISSUE TITLE
Bazel, Java: crash when setting JDK on `--host_java_toolchain`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#7526]
### Description of the problem / feature request:

Uncaught exception when setting JDK to `--host_java_toolchain` flag:
```
  $ bazel build --host_java_toolchain=@remotejdk10_linux//:jdk //src:bazel

...

Starting local Bazel server and connecting to it...
INFO: Invocation ID: 0e4be742-29d5-4cd4-89e0-498ad8378237
Loading: 
Loading: 0 packages loaded
Analyzing: target //src:bazel (1 packages loaded, 0 targets configured)
Analyzing: target //src:bazel (193 packages loaded, 5863 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//third_party:error_prone_annotations BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true' (requested by nodes '//third_party:guava BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.createIjarAction(JavaCompilationHelper.java:902)
        at com.google.devtools.build.lib.rules.java.JavaImport.processWithIjarIfNeeded(JavaImport.java:219)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:76)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:39)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 6 more

INFO: Elapsed time: 2.984s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (203 packages loaded, 6064 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//third_party:error_prone_annotations BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true' (requested by nodes '//third_party:guava BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.createIjarAction(JavaCompilationHelper.java:902)
        at com.google.devtools.build.lib.rules.java.JavaImport.processWithIjarIfNeeded(JavaImport.java:219)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:76)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:39)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 6 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//third_party:error_prone_annotations BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true' (requested by nodes '//third_party:guava BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.createIjarAction(JavaCompilationHelper.java:902)
        at com.google.devtools.build.lib.rules.java.JavaImport.processWithIjarIfNeeded(JavaImport.java:219)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:76)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:39)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 6 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//third_party:error_prone_annotations BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true' (requested by nodes '//third_party:guava BuildConfigurationValue.Key[76702d891372f9d14430e4d30087c1b5] true')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.java.JavaCompilationHelper.createIjarAction(JavaCompilationHelper.java:902)
        at com.google.devtools.build.lib.rules.java.JavaImport.processWithIjarIfNeeded(JavaImport.java:219)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:76)
        at com.google.devtools.build.lib.rules.java.JavaImport.create(JavaImport.java:39)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 6 more
FAILED: Build did NOT complete successfully (203 packages loaded, 6064 targets configured)
```

### What operating system are you running Bazel on?

Debian Linux

### What's the output of `bazel info release`?

```
  $ bazel info release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: eb928dac-6a95-4089-b54d-0c8d1e5e3c85
release 0.22.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
  $ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
34bf56f25eb1bed7fbd5c4cf7bae15bf461cf904
c07dcfddf1f4d610e09010ec0b38447d81615309
```

**Comment by laszlocsomor** [comment]
I can also repro the crash on master, i.e. on 34bf56f25eb1bed7fbd5c4cf7bae15bf461cf904.

**Comment by iirina** [comment]
Hi @laszlocsomor, were you trying to build with `--host_javabase` or `--host_java_toolchain`? Note that `@remotejdk10_linux//:jdk` is a javabase target, not a `java_toolchain`.

**Comment by laszlocsomor** [comment]
Tried both. With `--host_javabase` it crashed, with `--host_java_toolchain` it worked. It's likely that I was just using Bazel wrong, but I think it still shouldn't crash.

**Comment by iirina** [comment]
Agreed that it shouldn't crash. I was trying to understand if there is another bug at play here. Thanks for reporting it!

**Comment by meisterT** [comment]
Still crashes with `bazel build --host_java_toolchain=@remotejdk11_linux//:jdk //src:bazel`

**Comment by comius** [comment]
Closing because --host_java_toolchain is in process of being deprecated. See https://github.com/bazelbuild/bazel/issues/7849
