### ISSUE TITLE
Bazel CI: flipping --incompatible_use_toolchain_providers_in_java_common broke downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7537]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/825#_
```
ERROR: /home/bazel/.cache/bazel/_bazel_bazel/5d706025d280d5fdbb05fa8927483c8f/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/dependency_analyzer/src/main:dependency_analyzer:
--
  | Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/5d706025d280d5fdbb05fa8927483c8f/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD", line 5
  | scala_library_for_plugin_bootstrapping(name = 'dependency_analyzer')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/5d706025d280d5fdbb05fa8927483c8f/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 753, in scala_library_for_plugin_bootstrapping_impl
  | _lib(ctx, scalac_provider.default_class..., <3 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/5d706025d280d5fdbb05fa8927483c8f/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 676, in _lib
  | _compile_or_empty(ctx, ctx.outputs.manifest, cjars, srcj..., <6 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/5d706025d280d5fdbb05fa8927483c8f/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 461, in _compile_or_empty
  | java_common.run_ijar(ctx.actions, jar = ctx.outputs.jar, <2 more arguments>)
  | ConfiguredTarget(@bazel_tools//tools/jdk:current_java_toolchain, a9bf8afaa53ba87d4539f7a4ad4bf485) pass a java_common.JavaToolchainInfo instead of a configured target; see https://github.com/bazelbuild/bazel/issues/7186.

```

**Comment by meteorcloudy** [comment]
Culprit is 993c4843ed807ded975445babefd839923e5d2d9

**Comment by meteorcloudy** [comment]
Looks like `--incompatible_use_toolchain_providers_in_java_common` should not be flipped at this time, because 0.23.0 is the migration window for it. I'm rolling back the CL.

**Comment by cushon** [comment]
> We should not flip a flag until downstream has migrated.

The flip hadn't been released yet; the flag was flipped after the baseline was cut for 0.23.
