### ISSUE TITLE
Bazel CI: downstream projects broken by 046d253791b7f69c1e6444d4aef0625b67be02dc

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7589]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/830#8ec997ab-21fe-4b64-9cc0-f8031f7e3d27
```

/tmp/tmpp0zjo5s_/bazel-bin/src/bazel --nomaster_bazelrc --bazelrc=/dev/null version
--
  | Extracting Bazel installation...
  | Starting local Bazel server and connecting to it...
  | Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
  | Build time: Thu Jan 01 00:00:00 1970 (0)
  | Build timestamp: Thu Jan 01 00:00:00 1970 (0)
  | Build timestamp as int: 0
  |  
  | /tmp/tmpp0zjo5s_/bazel-bin/src/bazel --nomaster_bazelrc --bazelrc=/dev/null info
  | ERROR: /var/lib/buildkite-agent/builds/bk-docker-9z2c/bazel-downstream-projects/rules_k8s/WORKSPACE:140:1: Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-9z2c/bazel-downstream-projects/rules_k8s/WORKSPACE", line 140
  | go_rules_dependencies()
  | File "/home/bazel/.cache/bazel/_bazel_bazel/1915321556576edcfdb3c77b7b8e42f7/external/io_bazel_rules_go/go/private/repositories.bzl", line 28, in go_rules_dependencies
  | versions.check(MINIMUM_BAZEL_VERSION, bazel_versi...)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/1915321556576edcfdb3c77b7b8e42f7/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl", line 100, in versions.check
  | _is_at_least(threshold = minimum_bazel_versio..., ...)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/1915321556576edcfdb3c77b7b8e42f7/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl", line 80, in _is_at_least
  | _parse_bazel_version(version)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/1915321556576edcfdb3c77b7b8e42f7/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl", line 55, in _parse_bazel_version
  | tuple([int(n) for n in version.split("...")])
  | File "/home/bazel/.cache/bazel/_bazel_bazel/1915321556576edcfdb3c77b7b8e42f7/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl", line 55, in tuple
  | int(n)
  | string argument to int() cannot be empty


```

Culprit finder: https://buildkite.com/bazel/culprit-finder/builds/128#80ea37a1-9aaa-4b7f-bb5a-34e5925d8075

**Comment by meteorcloudy** [comment]
@ishikhman Do we have a simple fix for this? Otherwise I'll have to rollback it to fix the CI.

**Comment by meisterT** [comment]
This has to be fixed first: https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl#L55

The actual code change (046d253791b7f69c1e6444d4aef0625b67be02dc) then has to be guarded behind an incompatible flag.

**Comment by buchgr** [comment]
This has been fixe.d
