### ISSUE TITLE
Bazel CI: downstream project broken by flipping incompatible_disable_legacy_cc_provider

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7604]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/834#ec0c601b-1b5a-4c5f-b71e-4f2981976c0e
```

ERROR: /var/lib/buildkite-agent/builds/bk-docker-bx96/bazel-downstream-projects/rules_d/examples/hello_lib/BUILD:22:1: in d_source_library rule //examples/hello_lib:native_greeter:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-bx96/bazel-downstream-projects/rules_d/examples/hello_lib/BUILD", line 22
  | d_source_library(name = 'native_greeter')
  | File "/var/lib/buildkite-agent/builds/bk-docker-bx96/bazel-downstream-projects/rules_d/d/d.bzl", line 356, in _d_source_library_impl
  | fail("d_source_library can only depen...", ...")
  | attribute deps: d_source_library can only depend on other d_source_library or cc_library targets.


```
https://buildkite.com/bazel/culprit-finder/builds/132#f89e2011-c745-4886-a5d0-2b57af383aa0
Culprit: 972e73efbc5572d8d2427c476c424690708fd933

**Comment by meteorcloudy** [comment]
You can check which projects will be broken before you flip the flag at https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/18

**Comment by meteorcloudy** [comment]
This is fixed by rollback the culprit.
