### ISSUE TITLE
Bazel, Windows: Bazel 0.23.1 no longer works when users don't have VC installed

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7661]
To reproduce with Bazel 0.23.1, you can run the following command without VC installed (or if you do you can do `SET BAZEL_VC=C:/foo/bar/VC` first)

```
git clone https://github.com/bazelbuild/examples.git
cd java-maven
bazel build java-maven
```
You'll get 
```
ERROR: C:/src/tmp/gkx4laok/external/local_config_cc/BUILD:131:1: in cc_toolchain_config rule @local_config_cc//:msvc_x64:
Traceback (most recent call last):
        File "C:/src/tmp/gkx4laok/external/local_config_cc/BUILD", line 131
                cc_toolchain_config(name = 'msvc_x64')
        File "C:/src/tmp/gkx4laok/external/local_config_cc/cc_toolchain_config.bzl", line 1355, in _impl
                _windows_msvc_impl(ctx)
        File "C:/src/tmp/gkx4laok/external/local_config_cc/cc_toolchain_config.bzl", line 235, in _windows_msvc_impl
                feature(name = "msvc_link_env", env_sets =... "")])])
        File "C:/src/tmp/gkx4laok/external/local_config_cc/cc_toolchain_config.bzl", line 238, in feature
                env_set(actions = (all_link_actions + [A...]), ... "")])
        File "C:/src/tmp/gkx4laok/external/local_config_cc/cc_toolchain_config.bzl", line 241, in env_set
                env_entry(key = "LIB", value = "")
        File "C:/src/tmp/gkx4laok/external/bazel_tools/tools/cpp/cc_toolchain_config_lib.bzl", line 57, in env_entry
                _check_is_nonempty_string(value, "value", "env_entry")
        File "C:/src/tmp/gkx4laok/external/bazel_tools/tools/cpp/cc_toolchain_config_lib.bzl", line 29, in _check_is_nonempty_string
                fail("{} parameter of {} must be a no...))
value parameter of env_entry must be a nonempty string.
```

This happens after we migrated CROSSTOOL definition to Starlark and CROSSTOOL in Starlark is more strict than CROSSTOOL in proto, these must not be empty:
```
msvc_env_tmp,
msvc_env_path,
msvc_env_include,
msvc_env_lib,
```

I'll send a fix and add a test for this case.

**Comment by laurentlb** [comment]
Is it a regression from 0.22 to 0.23? If so, we might want to cherrypick it.

**Comment by meteorcloudy** [comment]
Yes, the fix is coming soon.
