### ISSUE TITLE
Intermittent python failure: AttributeError: 'module' object has no attribute

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#7754]
We're seeing intermittent build failures due to what appears to be an issue with a `py_binary`'s deps:

```
ERROR: /Users/iosci/Desktop/src/iosci7/lyft/ios/Modules/ScheduledRidesFlow/BUILD:3:1: AssetCatalogCompile Modules/ScheduledRidesFlow/ScheduledRidesFlowResources-intermediates/xcassets failed (Exit 1): xctoolrunner failed: error executing command
  (cd /private/var/tmp/_bazel_iosci/aaff9cc75cb8be4ef9a6584833278430/execroot/lyftios && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=12.1 \
    XCODE_VERSION_OVERRIDE=10.1.0 \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner actool --compile '[ABSOLUTE]bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-dbg/bin/Modules/ScheduledRidesFlow/ScheduledRidesFlowResources-intermediates/xcassets' --platform iphoneos --minimum-deployment-target 10.0 --compress-pngs --product-type com.apple.product-type.bundle --target-device iphone --target-device ipad --output-partial-info-plist '[ABSOLUTE]bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-dbg/bin/Modules/ScheduledRidesFlow/ScheduledRidesFlowResources-intermediates/xcassets-info.plist' Modules/ScheduledRidesFlow/Resources/ScheduledRidesFlow.xcassets)
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_iosci/aaff9cc75cb8be4ef9a6584833278430/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.runfiles/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.py", line 320, in <module>
    main(sys.argv[1:])
  File "/private/var/tmp/_bazel_iosci/aaff9cc75cb8be4ef9a6584833278430/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.runfiles/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.py", line 316, in main
    sys.exit(args.func(args, toolargs))
  File "/private/var/tmp/_bazel_iosci/aaff9cc75cb8be4ef9a6584833278430/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.runfiles/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.py", line 225, in actool
    return execute.execute_and_filter_output(
AttributeError: 'module' object has no attribute 'execute_and_filter_output'
```

This python script comes from rules_apple, the import that's failing is from here:

https://github.com/bazelbuild/rules_apple/blob/88b6b80d5e4331b56eeeef8d0eb49526e351b1c1/tools/xctoolrunner/xctoolrunner.py#L47

And this should be provided by https://github.com/bazelbuild/rules_apple/blob/88b6b80d5e4331b56eeeef8d0eb49526e351b1c1/tools/wrapper_common/execute.py#L26

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.23.1

**Comment by brandjon** [comment]
This should be debugged by the apple rules team. +@sergiocampama. I think we just saw something related to imports failing here due to the repo's top-level `__init__.py` file being omitted in some cases.

**Comment by keith** [comment]
Possibly related https://github.com/bazelbuild/bazel/issues/3925

**Comment by jmmv** [comment]
Given the lack of activity here... I take it this is not a problem any longer for whatever reason? Please reply if it is, and I'll reopen/reroute.
