### ISSUE TITLE
incompatible_string_join_requires_strings: string.join(list) accepts invalid (non-string) list elements

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7802]
With `--incompatible_string_join_requires_strings=false`, this code is accepted by Bazel:

```
>> ",".join(["a", 1, None, (2, 3)])
.. 
"a,1,None,(2, 3)"
```

However the argument of `string.join` should an iterable of strings. Bazel currently implicitly converts each item to a string (https://github.com/bazelbuild/starlark/blob/master/spec.md#stringjoin).

In the future, this will be an error and we'll set `--incompatible_string_join_requires_strings` to true. If your code relies on the old behavior, you may do the conversion explicitly:

```diff
- ", ".join(my_list)
+ ", ".join([str(e) for e in my_list])
```

**Comment by dkelmer** [comment]
@laurentlb, is the migration window 1 release? I added the breaking-change-0.26 label if it is, but if it's not, that needs to be updated

**Comment by davido** [comment]
@laurentlb Is this expected that we see "Internal build error"?

```
$ bazel build :polygerrit 
INFO: Invocation ID: 550150d9-ac5f-401e-b9aa-d22e9662b4f3
INFO: Call stack for the definition of repository 'polymer' which is a bower_archive (rule definition at /home/davido/projects/gerrit2/tools/bzl/js.bzl:121:17):
 - /home/davido/projects/gerrit2/WORKSPACE:1092:1
ERROR: An error occurred during the fetch of repository 'polymer':
   Traceback (most recent call last):
	File "/home/davido/projects/gerrit2/tools/bzl/js.bzl", line 83
		fail(("failed %s: %s" % (" ".join(cmd...)))
	File "/home/davido/projects/gerrit2/tools/bzl/js.bzl", line 83, in fail
		" ".join(cmd)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
Internal error thrown during build. Printing stack trace: java.util.UnknownFormatConversionException: Conversion = ' '
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO: Elapsed time: 8.645s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (135 packages loaded, 1709 targets configured)
    Fetching @iron-flex-layout; fetching 4s
    Fetching @paper-button; fetching 4s
    Fetching @iron-menu-behavior; fetching 4s
Internal error thrown during build. Printing stack trace: java.util.UnknownFormatConversionException: Conversion = ' '
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.util.UnknownFormatConversionException: Conversion = ' '
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
FAILED: Build did NOT complete successfully (135 packages loaded, 1709 targets configured)
    Fetching @iron-flex-layout; fetching 4s
    Fetching @paper-button; fetching 4s
    Fetching @iron-menu-behavior; fetching 4s
```

**Comment by laurentlb** [comment]
Internal errors or Java stack traces are never expected.
I've filed a separate bug for it.

**Comment by lberki** [comment]
rules_scala fails with this flag:

https://travis-ci.org/bazelbuild/rules_scala/jobs/561942959

How was it flipped then?

**Comment by fabboe** [comment]
I'm being referred here by an error message in version 0.28.1 by adding
`unused_dependency_checker_mode = "warn"` to an otherwise finely-working `scala_test` target.
Also unused_dependency_checker_mode = ["warn"] doesn't work.

If I follow this issue correctly, the relevant fix is https://github.com/bazelbuild/rules_nodejs/pull/814 - which is only in 0.31.1 / 0.32.0 following.

I can't parse a workaround form this thread. Would you mind pointing it out? Thanks.

```
$ bz test //some/repo/path:io_test 
ERROR: /home/user/repo/some/repo/path/BUILD:52:1: in scala_test rule //some/repo/path:io_test: 
Traceback (most recent call last):
        File "/home/user/repo/some/repo/path/BUILD", line 52
                scala_test(name = 'io_test')
        File "/home/user/.cache/bazel/_bazel_user/362feef9c5dd3d318e9cffd0a37027cf/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 1091, in scala_test_impl
                _scala_binary_common(ctx, cjars, transitive_rjars, transiti..., <4 more arguments>)
        File "/home/user/.cache/bazel/_bazel_user/362feef9c5dd3d318e9cffd0a37027cf/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 860, in _scala_binary_common
                _compile_or_empty(ctx, ctx.outputs.manifest, cjars, deps...(), <6 more arguments>)
        File "/home/user/.cache/bazel/_bazel_user/362feef9c5dd3d318e9cffd0a37027cf/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 451, in _compile_or_empty
                compile_scala(ctx, ctx.label, ctx.outputs.jar, manif..., <17 more arguments>)
        File "/home/user/.cache/bazel/_bazel_user/362feef9c5dd3d318e9cffd0a37027cf/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 219, in compile_scala
                ",".join([labels[j.path] for j in cjars_l...])
sequence element must be a string (got 'Label'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: Analysis of target '//some/repo/path:io_test' failed; build aborted: Analysis of target '//some/repo/path:io_test' failed; build aborted
```
