### ISSUE TITLE
android_local_test: NPE - could not find build.prop

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#7831]
```
Caused by: java.lang.NullPointerException: could not find build.prop
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
    at org.robolectric.shadows.ShadowSystemProperties.loadProperties(ShadowSystemProperties.java:69)
    at org.robolectric.shadows.ShadowSystemProperties.getProperty(ShadowSystemProperties.java:60)
    at org.robolectric.shadows.ShadowSystemProperties.native_get_int(ShadowSystemProperties.java:30)
    at android.os.SystemProperties.native_get_int(SystemProperties.java)
    at android.os.SystemProperties.getInt(SystemProperties.java:79)
    at android.util.DisplayMetrics.getDeviceDensity(DisplayMetrics.java:305)
    at android.util.DisplayMetrics.__staticInitializer__(DisplayMetrics.java:118)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:280)
    at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
    at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:150)
    at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
    at android.util.DisplayMetrics.<clinit>(DisplayMetrics.java)
```

**Comment by jin** [comment]
This is an issue with the Robolectic / Bazel tooling while generating the robolectric-deps.properties file.

https://github.com/robolectric/robolectric-bazel/blob/d1e66f0dc474a98ebe13361ba8c16c188a5441fd/bazel/gen-deps.py#L10

The number of `../` depends on the directory nesting level of where this script is located. If it's two levels deep, there should be three `../` to traverse to runfiles directory root.
