### ISSUE TITLE
"Server terminated abruptly" due to java.lang.IllegalStateException on invalid flag value

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#7847]
### Description of the problem / feature request:

`bazel build --experimental_generate_json_trace_profile=$PWD/trace.json` causes the Bazel server to crash. This incorrect flag value should be reported to the user as such, instead of crashing the server.

Stack trace:

```
java.lang.IllegalStateException: Unable to set option '--experimental_generate_json_trace_profile' to value 'null'.
        at com.google.devtools.common.options.OptionsParserImpl.getParsedOptions(OptionsParserImpl.java:597)
        at com.google.devtools.common.options.OptionsParser.getOptions(OptionsParser.java:736)
        at com.google.devtools.build.lib.runtime.CommandEnvironment.<init>(CommandEnvironment.java:176)
        at com.google.devtools.build.lib.runtime.BlazeWorkspace.initCommand(BlazeWorkspace.java:204)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:284)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:206)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Can not set boolean field com.google.devtools.build.lib.runtime.CommonCommandOptions.enableTracer to null value
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
        at java.base/jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source)
        at java.base/java.lang.reflect.Field.set(Unknown Source)
        at com.google.devtools.common.options.OptionsParserImpl.getParsedOptions(OptionsParserImpl.java:594)
        ... 11 more
```

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

release 0.24.0

**Comment by laszlocsomor** [comment]
I can repro this with Bazel 0.28.1 on Linux.

Not all boolean flags are affected though: I can repro with `----sandbox_debug=$PWD` but not with `--verbose_failures=$PWD`.

**Comment by laszlocsomor** [comment]
Here's the explanation of what happens.

Two of the first things the Bazel server in BlazeCommandDispatcher.execExclusively is parsing command line options and initializing modules. (Modules are Bazel-internal components.)

Parsing the flags consists of two phases:

1. Tokenizing the flags and storing the raw values as strings. This step is done eagerly.

2. Parsing values out of the strings and assigning them to typed class members. This step is done lazily when something asks the OptionsParser to return a specific Options instance.

Bazel catches bad flag values in step 1 already and stores an error code, but it carries on with initializing all modules. Bazel tries to initialize all modules, even if some of them fail to do so, and only then will Bazel observe the error code.

This is the problem though: if a module that's being initialized tries to read an option that got an invalid value (like SandboxModule trying to read SandboxOptions.sandboxDebug, but "--sandbox_debug" got "/foo" as a value), then the OptionsParser will fail to parse the right value and fail to assign it to the sandboxDebug field, and Bazel crashes.

The fix is to ignore the failure to set the value.  This is fine: Bazel still reports the bad flag, but it also leaves the field at its default value.  I've sent a PR to apply this fix.
