### ISSUE TITLE
Tulsi test fails with Bazel 0.24.0

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7885]
In https://buildkite.com/bazel/tulsi-bazel-darwin/builds/82, there was only one failing test `//src/TulsiEndToEndTests:TulsiEndToEndTest`, but after Bazel 0.24.0 release https://buildkite.com/bazel/tulsi-bazel-darwin/builds/83, `//src/TulsiGeneratorIntegrationTests:EndToEndGenerationTests` started to fail.

This is also why Tulsi is failing in downstream https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/886#5a03f9ff-b713-4577-b61f-70984221ba32

```
> I: Running /private/var/tmp/_bazel_buildkite/cecbba437a8b9f11634ba6698b0a03a1/sandbox/darwin-sandbox/86/execroot/__main__/_tmp/10d75384e975c6513e802780040b3a67/fake_execroot/__main__/tulsi_e2e_output/SimpleCCProject.xcodeproj/.tulsi/Scripts/user_build.py --norun //tulsi_e2e_ccsimple:ccBinary
> W: Failed to bootstrap LLDBInit file, bootstrapping script returned error code 1, Traceback (most recent call last):
  File "/tmp/test_tmp_dir.sLP7IG/EndToEndGenerationTests.xctest/Contents/Resources/bootstrap_lldbinit.py", line 149, in <module>
    BootstrapLLDBInit()
  File "/tmp/test_tmp_dir.sLP7IG/EndToEndGenerationTests.xctest/Contents/Resources/bootstrap_lldbinit.py", line 145, in __init__
    self._LinkTulsiLLDBInit()
  File "/tmp/test_tmp_dir.sLP7IG/EndToEndGenerationTests.xctest/Contents/Resources/bootstrap_lldbinit.py", line 139, in _LinkTulsiLLDBInit
    with open(lldbinit_path, 'w') as outfile:
IOError: [Errno 1] Operation not permitted: '/Users/buildkite/.lldbinit'
```

**Comment by meteorcloudy** [comment]
@fweikert Did we have any infrastructure change on mac machines other than Bazel upgrade?

**Comment by meteorcloudy** [comment]
Error message from the log:
```
ERROR: /private/var/tmp/_bazel_buildkite/05dc194ca495b34fe2b17ee433eed380/sandbox/darwin-sandbox/86/execroot/__main__/_tmp/10d75384e975c6513e802780040b3a67/fake_execroot/__main__/tulsi_e2e_broken_build/BUILD:22:1: //tulsi_e2e_broken_build:Application: no such attribute 'lolno' in 'ios_application' rule
ERROR: error loading package 'tulsi_e2e_broken_build': Package 'tulsi_e2e_broken_build' contains errors
> S: ** Completed generating_project in 2.2763s
> Critical error logged: Project generation failed.
> D: Printing Bazel logs that could contain the error.
> I: Log of Bazel aspect info output follows:
> I: Bazel command info:
/usr/local/bin/bazel --bazelrc=/dev/null build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --define=TULSI_TEST=dbg --workspace_status_command=/usr/bin/true --ios_minimum_os=8.0 --macos_minimum_os=10.10 --tvos_minimum_os=10.0 --watchos_minimum_os=3.0 --xcode_version=10.1 --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc --override_repository=tulsi=/tmp/test_tmp_dir.MxHS24/EndToEndGenerationTests.xctest/Contents/Resources --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi_vUNKNOWN:generator --build_event_json_file=/var/folders/wr/h6kcxcv90m37dzj0q0q8tzpc0000gp/T/build_events_55627.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-_,-default //tulsi_e2e_broken_build:Application
Exited with code 1
```

**Comment by DavidGoldman** [comment]
The failures are due to changes in how Xcode versions are represented, we should just need to update the goldens with the latest Bazel release:

```
src/TulsiGeneratorIntegrationTests/EndToEndGenerationTests.swift:314: error: -[src_TulsiGeneratorIntegrationTests_EndToEndGenerationTests_lib.EndToEndGenerationTests test_macProject] : failed - 818c818
src/TulsiGeneratorIntegrationTests/EndToEndGenerationTests.swift:314: error: -[src_TulsiGeneratorIntegrationTests_EndToEndGenerationTests_lib.EndToEndGenerationTests test_macProject] : failed - < 				TULSI_XCODE_VERSION = 10.1.0.10B61;
src/TulsiGeneratorIntegrationTests/EndToEndGenerationTests.swift:314: error: -[src_TulsiGeneratorIntegrationTests_EndToEndGenerationTests_lib.EndToEndGenerationTests test_macProject] : failed - ---
src/TulsiGeneratorIntegrationTests/EndToEndGenerationTests.swift:314: error: -[src_TulsiGeneratorIntegrationTests_EndToEndGenerationTests_lib.EndToEndGenerationTests test_macProject] : failed - > 				TULSI_XCODE_VERSION = 10.1.0;
```

**Comment by meteorcloudy** [comment]
Great, can you help fixing this? @DavidGoldman

**Comment by meteorcloudy** [comment]
Looks like this is fixed at https://github.com/bazelbuild/tulsi/commit/402b3d80f51355c62a9639d1e1495782da1e9526, thanks!
