### ISSUE TITLE
NullPointerException in skyframe.DelegatingWalkableGraph#getEntry

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#792]
I haven't investigated much but here what I get:
```
$ ${BAZEL} build :*
Sending SIGTERM to previous Bazel server (pid=21104)... done.
........
Unhandled exception thrown during build; message: PACKAGE:@protobuf//
INFO: Elapsed time: 0.648s
java.lang.NullPointerException: PACKAGE:@protobuf//
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:336)
        at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getEntry(DelegatingWalkableGraph.java:50)
        at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getValue(DelegatingWalkableGraph.java:73)
        at com.google.devtools.build.lib.skyframe.TargetPatternsResultBuilder.findPackageInGraph(TargetPatternsResultBuilder.java:108)
        at com.google.devtools.build.lib.skyframe.TargetPatternsResultBuilder.precomputePackages(TargetPatternsResultBuilder.java:81)
        at com.google.devtools.build.lib.skyframe.TargetPatternsResultBuilder.build(TargetPatternsResultBuilder.java:50)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:186)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:417)
        at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:134)
        at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:401)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:334)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:71)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:371)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1016)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
        at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
        at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:975)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:772)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)
```

This is at HEAD (or more precisely at the soon to be 0.1.4rc2 which I am testing right now)

It seems to be here for at least a month because I got it also from a Bazel version from December 1st.

The workspace:
```
$ cat BUILD 
genrule(
  name = "dummy",
  srcs = ["@protobuf//:cc_test_protos"],
  outs = ["dummy.txt"],
  cmd = "ls -l $(SRCS) >$@",
)
$ cat WORKSPACE 
local_repository(
  name = "protobuf",
  path = "/usr/local/google/home/dmarting/toto/protobuf",
)
```

`$BAZEL build @protobuf//:cc_test_protos` seems to fix it.

**Comment by damienmg** [comment]
@mikelalcon Do you have an hint on what is causing it?
