### ISSUE TITLE
crashes when encountering attribute named :foo

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7961]
Reported by @alandonovan

```
touch WORKSPACE
cat > BUILD << EOF
load(":inc.bzl", "foo")
EOF

cat > inc.bzl << EOF
def _foo_impl(ctx):
    pass

foo = rule(
    implementation = _foo_impl,
    attrs = {
        ":x": attr.bool(),
    },
)
EOF
```

```
$ bazel build :all
Starting local Bazel server and connecting to it...
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//:inc.bzl' (requested by nodes 'PACKAGE:')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: late bound attributes require a default value that is late bound (and vice versa): :x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.google.devtools.build.lib.packages.Attribute.<init>(Attribute.java:2002)
	at com.google.devtools.build.lib.packages.Attribute$ImmutableAttributeFactory.build(Attribute.java:472)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttr$Descriptor.build(SkylarkAttr.java:887)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.export(SkylarkRuleClassFunctions.java:677)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.possiblyExport(SkylarkImportLookupFunction.java:566)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.execAndExport(SkylarkImportLookupFunction.java:548)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.createExtension(SkylarkImportLookupFunction.java:529)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.computeInternal(SkylarkImportLookupFunction.java:385)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.compute(SkylarkImportLookupFunction.java:103)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
	... 4 more

INFO: Elapsed time: 1.594s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//:inc.bzl' (requested by nodes 'PACKAGE:')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: late bound attributes require a default value that is late bound (and vice versa): :x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.google.devtools.build.lib.packages.Attribute.<init>(Attribute.java:2002)
	at com.google.devtools.build.lib.packages.Attribute$ImmutableAttributeFactory.build(Attribute.java:472)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttr$Descriptor.build(SkylarkAttr.java:887)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.export(SkylarkRuleClassFunctions.java:677)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.possiblyExport(SkylarkImportLookupFunction.java:566)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.execAndExport(SkylarkImportLookupFunction.java:548)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.createExtension(SkylarkImportLookupFunction.java:529)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.computeInternal(SkylarkImportLookupFunction.java:385)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.compute(SkylarkImportLookupFunction.java:103)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:inc.bzl' (requested by nodes 'PACKAGE:')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: late bound attributes require a default value that is late bound (and vice versa): :x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.google.devtools.build.lib.packages.Attribute.<init>(Attribute.java:2002)
	at com.google.devtools.build.lib.packages.Attribute$ImmutableAttributeFactory.build(Attribute.java:472)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttr$Descriptor.build(SkylarkAttr.java:887)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.export(SkylarkRuleClassFunctions.java:677)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.possiblyExport(SkylarkImportLookupFunction.java:566)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.execAndExport(SkylarkImportLookupFunction.java:548)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.createExtension(SkylarkImportLookupFunction.java:529)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.computeInternal(SkylarkImportLookupFunction.java:385)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.compute(SkylarkImportLookupFunction.java:103)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//:inc.bzl' (requested by nodes 'PACKAGE:')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: late bound attributes require a default value that is late bound (and vice versa): :x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.google.devtools.build.lib.packages.Attribute.<init>(Attribute.java:2002)
	at com.google.devtools.build.lib.packages.Attribute$ImmutableAttributeFactory.build(Attribute.java:472)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttr$Descriptor.build(SkylarkAttr.java:887)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.export(SkylarkRuleClassFunctions.java:677)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.possiblyExport(SkylarkImportLookupFunction.java:566)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.execAndExport(SkylarkImportLookupFunction.java:548)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.createExtension(SkylarkImportLookupFunction.java:529)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.computeInternal(SkylarkImportLookupFunction.java:385)
	at com.google.devtools.build.lib.skyframe.SkylarkImportLookupFunction.compute(SkylarkImportLookupFunction.java:103)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
```

**Comment by katre** [comment]
This is clearly not a P1. Downgrading and sending for re-assessment.

**Comment by brandjon** [comment]
Looks like this has been fixed:

```
Error in rule: attribute name `:x` is not a valid identifier.
```
