### ISSUE TITLE
Blaze query crashes

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#805]
I recently switched from a home grown CI setup to the [ci.sh](https://github.com/bazelbuild/bazel/commit/f88f4d81acead9ef3e2f73d9a44afd76c2c239c1) script included in this repo. I have Jenkins clone my base repo then run a copy of ci.sh. However, when I run it I get this exception:

```sh
++ bazel query --keep_going --noshow_progress 'kind(.*_binary, rdeps(//..., set(//third_party/binaries:BUILD' //third_party/grpc_gateway:BUILD '//third_party/protobuf:BUILD)))'
java.lang.RuntimeException: Unrecoverable error while evaluating node 'GIT_CLONE:https://github.com/gengo/grpc-gateway -> /var/lib/jenkins/.cache/bazel/_bazel_jenkins/d83dacdc5908886419244afd9568baf4/external/grpc_gateway_files (86c2fc2b7b7902b45ce3d1c021e07a79d81d3f4d) submodules: true' (requested by nodes 'NEW_GIT_REPOSITORY:@grpc_gateway_files')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:745)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Destination path "grpc_gateway_files" already exists and is not an empty directory
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:152)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:68)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:709)
	... 4 more
```

In my WORKSPACE I have an entry:
```python
new_git_repository(
    name = "grpc_gateway_files",
    commit = "86c2fc2b7b7902b45ce3d1c021e07a79d81d3f4d",
    remote = "https://github.com/gengo/grpc-gateway",
    build_file = "third_party/grpc_gateway/BUILD",
    init_submodules = True,
)
```

I'm not even sure where to start on debugging this. It only occurs when I do an automated build in Jenkins. If I sudo -u jenkins -i and then run the command it succeeds. Can you help point me in a direction?

**Comment by damienmg** [comment]
@davidzchen @kchodorow could you take a look?

**Comment by bsilver8192** [comment]
That looks like a problem related to files left laying around in the output of the repository. What's in the external/grpc_gateway_files folder under the output base? It'll probably be in ~jenkins/.cache/bazel/_bazel_jenkins/[some hex characters].

Have you tried restarting Bazel since this happened the first time?

What version are you running? dfc44a4f14582fdfdebd7f0a6d56ec23fc2ed6 fixed an issue with the same error message.

**Comment by achew22** [comment]
I was running an old version of Bazel on my CI box. I have corrected for that and added a call to bazel version to the top of my build log. Hopefully I'll see that and realize what's up next time. Sorry for the spam :frowning:

**Comment by davidzchen** [comment]
No problem. Feel free to open a bug if you see the issue again.
