### ISSUE TITLE
Bazel CI: Tulsi is broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8084]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/921#41afb3c1-6def-42ca-991a-17eccfb18dac
```
ERROR: /Users/buildkite/builds/buildkite-imacpro-7/bazel-downstream-projects/tulsi/src/tools/bazel_cache_reader/BUILD:7:1: in @build_bazel_rules_apple//apple/internal/aspects:resource_aspect.bzl%apple_resource_aspect aspect on objc_library rule //src/tools/bazel_cache_reader:bazel_cache_reader_lib:
--
  | Traceback (most recent call last):
  | File "/Users/buildkite/builds/buildkite-imacpro-7/bazel-downstream-projects/tulsi/src/tools/bazel_cache_reader/BUILD", line 7
  | @build_bazel_rules_apple//apple/internal/aspects:resource_aspect.bzl%apple_resource_aspect(...)
  | File "/private/var/tmp/_bazel_buildkite/b65b9eaa06eabe2a766aa8d0e0f8ba76/external/build_bazel_rules_apple/apple/internal/aspects/resource_aspect.bzl", line 73, in _apple_resource_aspect_impl
  | providers.extend([x[AppleResourceInfo] for x in c...])
  | File "/private/var/tmp/_bazel_buildkite/b65b9eaa06eabe2a766aa8d0e0f8ba76/external/build_bazel_rules_apple/apple/internal/aspects/resource_aspect.bzl", line 75, in providers.extend
  | ctx.rule.attr.bundles
  | No attribute 'bundles' in attr. Make sure you declared a rule attribute with this name.
  | Available attributes: _action_listener, _apple_sdk, _cc_toolchain, _cc_toolchain_type, _config_dependencies, _header_scanner, _libtool, _xcode_config, _xcrunwrapper, alwayslink, compatible_with, copts, data, defines, deprecation, deps, enable_modules, features, generator_function, generator_location, generator_name, hdrs, includes, licenses, module_map, module_name, name, non_arc_srcs, pch, restricted_to, runtime_deps, sdk_dylibs, sdk_frameworks, sdk_includes, srcs, tags, testonly, textual_hdrs, toolchains, transitive_configs, visibility, weak_sdk_frameworks
```

Culprit: 5456e41342c394ba443dd2aef6253d78997b0cde
https://buildkite.com/bazel/culprit-finder/builds/149

@sergiocampama @c-parsons

**Comment by meteorcloudy** [comment]
This is fixed now
