### ISSUE TITLE
"--package_path" is broken in Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8288]
Bazel supports finding packages in multiple paths. 
https://docs.bazel.build/versions/master/user-manual.html#flag--package_path 
This is currently broken at HEAD.

Note that this is a different issue as b/132327507 which is already fixed by 9835cb4135503768cdf1161746b95d7969ccb938

Culprit: 9c5b310257ca5c85ae261a43187d0b949319a514

To reproduce with https://github.com/meteorcloudy/my_tests/tree/master/multiple_package_path_test

```
$ bazel-9c5b310257ca5c85ae261a43187d0b949319a514 build //... --package_path ../buildfiles
Starting local Bazel server and connecting to it...
INFO: Reading 'startup' options from c:\users\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=320
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python36/python.exe
INFO: Reading rc options for 'build' from c:\users\pcloudy\.bazelrc:
  'build' options: --curses=yes --color=yes --verbose_failures --announce_rc
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2149)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2119)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getPlatformMappingValue(SkyframeExecutor.java:2071)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfigurations(SkyframeExecutor.java:1900)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1486)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:245)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:272)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:97)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:498)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:206)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:527)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
        ... 3 more
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.skyframe.PlatformMappingFunction.compute(PlatformMappingFunction.java:64)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:450)
        ... 4 more

INFO: Elapsed time: 2.075s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2149)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2119)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getPlatformMappingValue(SkyframeExecutor.java:2071)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfigurations(SkyframeExecutor.java:1900)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1486)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:245)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:272)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:97)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:498)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:206)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:527)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
        ... 3 more
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.skyframe.PlatformMappingFunction.compute(PlatformMappingFunction.java:64)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:450)
        ... 4 more
java.lang.IllegalStateException: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2149)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2119)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getPlatformMappingValue(SkyframeExecutor.java:2071)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfigurations(SkyframeExecutor.java:1900)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1486)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:245)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:272)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:97)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:498)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:206)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:527)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
        ... 3 more
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.skyframe.PlatformMappingFunction.compute(PlatformMappingFunction.java:64)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:450)
        ... 4 more
java.lang.IllegalStateException: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2149)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2119)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getPlatformMappingValue(SkyframeExecutor.java:2071)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfigurations(SkyframeExecutor.java:1900)
        at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createConfigurations(SkyframeExecutor.java:1486)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:245)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:272)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:97)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:498)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:206)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:527)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
        ... 3 more
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.skyframe.PlatformMappingFunction.compute(PlatformMappingFunction.java:64)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:450)
FAILED: Build did NOT complete successfully (2 packages loaded)
```

**Comment by meteorcloudy** [comment]
Although I tested on Windows, this is also broken on Linux.

**Comment by janakdr** [comment]
This isn't a bug with --package_path. The issue is that there's no WORKSPACE file under the package_path you specified. You'll see the same crash happen if you remove the WORKSPACE file from the root of your workspace and run bazel with no --package_path argument there. That being said, we should certainly not crash in this situation, even though we're going to error out momentarily because there's no WORKSPACE file.

**Comment by janakdr** [comment]
Actually, it looks like we tolerate the absence of a WORKSPACE file ok, at least inside Google. The right fix here might actually be to make this --platform_mappings flag package-path aware. That is, it could search through the package paths looking for the file. @aragos , what do you think? Should this flag be package-path aware, or should it just look at the first entry? Either should work.

**Comment by meteorcloudy** [comment]
No matter this is a bug or not, it is definitely an incompatible change, because the above example works with Bazel built before 9c5b310

**Comment by janakdr** [comment]
I wouldn't describe it as an incompatible change: it's just a bug. Fixing it with my pending internal change will revert to the previous behavior except with multiple package paths, and I don't think behavior in that case was ever specified.
