### ISSUE TITLE
Empty http_proxy will cause ERROR in _get_java_proxy_args

### ISSUE THREAD

**Issue by wlx65003** [bazelbuild/bazel#8344]
### Description of the problem / feature request:

Empty $http_proxy will cause ERROR in _get_java_proxy_args

```
ERROR: Analysis of target '//java:org_ray_ray_test_pom' failed; build aborted: no such package '@maven//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 438
		repository_ctx.execute(_generate_coursier_command(repos...))
	File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 438, in repository_ctx.execute
		_generate_coursier_command(repository_ctx)
	File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 371, in _generate_coursier_command
		_get_java_proxy_args(repository_ctx)
	File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 394, in _get_java_proxy_args
		http_proxy.split("://", 1)[1]
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> just export http_proxy=""

### What operating system are you running Bazel on?

> macOS

### What's the output of `bazel info release`?

INFO: Invocation ID: 159e72a1-450f-4546-8dd8-5dd1f6b1c6f1
release 0.25.2-homebrew

**Comment by wlx65003** [comment]
https://github.com/bazelbuild/rules_jvm_external/pull/145

**Comment by wlx65003** [comment]
[https://github.com/bazelbuild/rules_jvm_external/pull/145](https://github.com/bazelbuild/rules_jvm_external/pull/145)

**Comment by wlx65003** [comment]
I have submitted a PR to fix it.
https://github.com/bazelbuild/rules_jvm_external/pull/145
