### ISSUE TITLE
Error message doesn't include why argument is wrong

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#8396]
### Description of the problem:

When reporting bad arguments for `DefaultInfo`, bazel doesn't actually include any information about the actual argument and why it was wrong.

```
~/tmp/example-repo % bazel build //:target                                                                                                                                                                          (0)
ERROR: /Users/endobson/tmp/example-repo/BUILD:3:1: in my_rule rule //:target:
Traceback (most recent call last):
        File "/Users/endobson/tmp/example-repo/BUILD", line 3
                my_rule(name = 'target')
        File "/Users/endobson/tmp/example-repo/rules.bzl", line 4, in _my_rule_impl
                DefaultInfo(data_runfiles = runfiles_var)
expected value of type 'runfiles or NoneType' for parameter 'data_runfiles', for call to function DefaultInfo(files = None, runfiles = None, data_runfiles = None, default_runfiles = None, executable = None)
WARNING: errors encountered while analyzing target '//:target': it will not be built
INFO: Analyzed target //:target (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.137s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
``` 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/endobson/examples/tree/bazel-default-info-error and then run
```
bazel build //:target
```

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

```
% bazel version                                                                                                                                                                                  (1)
Build label: 0.25.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 7 17:59:07 2019 (1557251947)
Build timestamp: 1557251947
Build timestamp as int: 1557251947
% bazel info release                                                                                                                                                                             (0)
release 0.25.1
```

**Comment by brandjon** [comment]
This appears to be fixed now:

```
Error in DefaultInfo: in call to DefaultInfo(), parameter 'data_runfiles' got value of type 'int', want 'runfiles or NoneType'
```
