### ISSUE TITLE
--persistent_android_resource_processor logs a warning to stdout, causing failure

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#8505]
### Description of the problem / feature request:

In at least one case, doing resource processing, the worker enabled by `--persistent_android_resource_processor` forwards a resource merge warning to stdout, causing inter-worker protocol to throw an exception.  It needs to take tool output and ensure it only writes logging output to stderr.

### Feature requests: what underlying problem are you trying to solve with this feature?

Use the persistent worker. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unsure, as it's specific to our deps graph, but it seems to involve including a dep that has `com.evernote.android.job.gcm.PlatformGcmService`. 

It results in a warning from resource processing, and the following trace: 

```
Did you try to print something to stdout? Workers aren't allowed to do this, as it breaks the protocol between Bazel and the worker process.

---8<---8<--- Exception details ---8<---8<---
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1936)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1886)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2503)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2497)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:347)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.parseDelimitedFrom(WorkerProtocol.java:2145)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:349)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:172)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:121)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:224)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:113)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:78)
	at com.google.devtools.build.lib.exec.ProxySpawnActionContext.exec(ProxySpawnActionContext.java:52)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:322)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:830)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:965)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:937)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:114)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:78)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:563)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:707)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:253)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log ---8<---8<---
Warning: /var/folders/4y/grml08d12tx1b8ftq5y829vw0000gn/T/android_resource_merge_tmp11346016350146985260/AndroidManifest.xml:15:9-17:35 Warning:
	service#com.evernote.android.job.gcm.PlatformGcmService was tagged at AndroidManifest.xml:15 to remove other declarations but no other declaration present
6016350146985260/AndroidManifest.xml:15:9-17:35 Warning:
	service#com.evernote.android.job.gcm.PlatformGcmService was tagged at AndroidManifest.xml:15 to remove other declarations but no other declaration present
---8<---8<--- End of log ---8<---8<---
```

### What operating system are you running Bazel on?

Mac OS X 10.14.5

### What's the output of `bazel info release`?

`development version`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

We took the 0.25.2 release tag, cherry picked the commit from PR https://github.com/bazelbuild/bazel/issues/8109, and built.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:cgruber/bazel.git
99013ea0b9601d91f4a4e9b01ff6490553cab645
413ed96c5f250e2adf4c2fce20bb94eda25a4cf1
```

###  Have you found anything relevant by searching the web?

Nope. 

### Any other information, logs, or outputs that you want to share?

Code that warns seems to be from dep `com.evernote:android-job:1.3.0-rc1` in case that helps repro.

**Comment by cgruber** [comment]
Found another one. 

```
Warning: /private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/common/background-job/src/main/AndroidManifest.xml:12:5-14:30 Warning:
    service#com.evernote.android.job.gcm.PlatformGcmService was tagged at AndroidManifest.xml:12 to remove other declarations but no other declaration present
__/common/background-job/src/main/AndroidManifest.xml:12:5-14:30 Warning:
    service#com.evernote.android.job.gcm.PlatformGcmService was tagged at AndroidManifest.xml:12 to remove other declarations but no other declaration present
```

Bazel workers should be trapping any and all output by their underlying tools, and avoiding publishing it to stdout - and if they run things in-process, they should use `System.setOut` to defensively capture standard out from libraries.

**Comment by cgruber** [comment]
Meh - sorry, it's the same error.  It just keeps happening all over the place.

**Comment by cgruber** [comment]
Ah - but I was working around this bug via `build --strategy=AndroidResourceMerger=standalone`, but as of 0.29.0, that is not working.  Was this functionality split out into a different worker, with a different mnemonic?

**Comment by cgruber** [comment]
At this point, it seems to work if I disable workers for all three fo AndroidResourceMerger, ManifestMerger, AND AndroidCompiledResourceMerger.  Or disable `--persistent_android_resource_processor` of course.
