### ISSUE TITLE
Unrecoverable error while evaluating node '//lib/js:webcomponentsjs'

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#8541]
I'm trying to adapt [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) code to disallow rule implementation functions returning struct and comply with upcoming  '--incompatible_disallow_struct_provider_syntax' flag flip (that is tracked [here](https://github.com/bazelbuild/bazel/issues/7347)).

The diff against Gerrit@HEAD (17896064512bba58802db9d193d5cb7b080ab72a) is here: [1] (using one single provider: [2] has not fixed the breakage). The error message is:

```
  $ b10 build --incompatible_string_join_requires_strings=false --incompatible_disallow_struct_provider_syntax :release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 933dfb2f-b55c-4f92-a3c4-3dc743b213ee
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_toolchains/rules/version_check.bzl:45:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.25.2'
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_toolchains/rules/version_check.bzl:45:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.25.2'
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:96:13: Current Bazel is not a release version; cannot check for compatibility. Make sure that you are running at least Bazel 0.25.0.
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//lib/js:webcomponentsjs BuildConfigurationValue.Key[2cc9a671ca11dbd22621bbbb1a1cd006] false' (requested by nodes '//polygerrit-ui/app:polygerrit_ui BuildConfigurationValue.Key[2cc9a671ca11dbd22621bbbb1a1cd006] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.packages.SkylarkProvider.getKey(SkylarkProvider.java:169)
	at com.google.devtools.build.lib.packages.SkylarkProvider.getKey(SkylarkProvider.java:48)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.addProviders(SkylarkRuleConfiguredTargetUtil.java:371)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:223)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:148)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:774)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:845)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
	... 7 more

INFO: Elapsed time: 6.619s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 623 targets configured)
    currently loading: @go_sdk//
    Fetching @gitiles-servlet; fetching
```

The failing check is here:

```java
  @Override
  public boolean isExported() {
    return key != null;
  }

  @Override
  public SkylarkKey getKey() {
    Preconditions.checkState(isExported()); // <== failing here
    return key;
  }
```

I am using Bazel@HEAD (2b3c879a6507f17030fdf9fba2a1704cb09eb5f3).

[1] http://paste.openstack.org/show/752397
[2] http://paste.openstack.org/show/752398

**Comment by c-parsons** [comment]
I suspect this might be because you are defining the providers from inside an rule implementation function. In other words:

```
def _rule_impl(ctx):
   MyProvider = provider()
   ...
   return [MyProvider()]
```

Might be problematic

Instead do:

```
MyProvider = provider()

def _rule_impl(ctx):
   ...
   return [MyProvider()]
```

Still, we should always avoid a Bazel stacktrace, and should provide a more helpful error, when this sort of thing occurs. I'll work on a fix.

**Comment by c-parsons** [comment]
(Confirmed, my suspicion was correct)
