### ISSUE TITLE
Unable to fetch image from a repository during bazel build. Call stack points towards a syntax error in the __init__.py of httplib2.

### ISSUE THREAD

**Issue by HVP1621** [bazelbuild/bazel#8619]
I am using bazel to build my own Docker images. As a toy example, I would like to pull an image from the gcr and extend custom layers on top of it. Below are my WORKSPACE and BUILD files.
## WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()


load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
)

container_pull(
  name = "gcrbase",
  registry = "gcr.io",
  repository = "distroless/base",
  tag = "debug",
)

```
## BUILD

```
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

# The base image layer
container_image(
    name = "layer1",
    base = "@gcrbase//image:image.tar",
)

# Creating an empty layer
container_image(
        name = "layer2",
        base = "layer1",
)
```
When build the target `bazel build //foo:layer1`,  I get the following error:
```
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Call stack for the definition of repository 'gcrbase' which is a container_pull (rule definition at /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/io_bazel_rules_docker/container/pull.bzl:173:18):
 - /home/harshvardhan/Desktop/del/WORKSPACE:29:1
ERROR: An error occurred during the fetch of repository 'gcrbase':
```
Below is the complete error message which is returned

```
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Call stack for the definition of repository 'gcrbase' which is a container_pull (rule definition at /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/io_bazel_rules_docker/container/pull.bzl:173:18):
 - /home/harshvardhan/Desktop/del/WORKSPACE:29:1
ERROR: An error occurred during the fetch of repository 'gcrbase':
   Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/__main__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/docker_creds_.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/httplib2/__init__.py", line 988
    raise socket.error, msg
                      ^
SyntaxError: invalid syntax
 (/usr/bin/python /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded --directory /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/gcrbase/image --os linux --os-version  --os-features  --architecture amd64 --variant  --features  --name gcr.io/distroless/base:debug)
ERROR: /home/harshvardhan/Desktop/del/foo/BUILD:5:1: no such package '@gcrbase//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/__main__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/docker_creds_.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/httplib2/__init__.py", line 988
    raise socket.error, msg
                      ^
SyntaxError: invalid syntax
 (/usr/bin/python /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded --directory /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/gcrbase/image --os linux --os-version  --os-features  --architecture amd64 --variant  --features  --name gcr.io/distroless/base:debug) and referenced by '//foo:layer1'
ERROR: Analysis of target '//foo:layer1' failed; build aborted: no such package '@gcrbase//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/__main__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/containerregistry/client/docker_creds_.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded/httplib2/__init__.py", line 988
    raise socket.error, msg
                      ^
SyntaxError: invalid syntax
 (/usr/bin/python /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/puller/file/downloaded --directory /home/harshvardhan/.cache/bazel/_bazel_harshvardhan/12f7c6f48721be2af9e8cae0c8829345/external/gcrbase/image --os linux --os-version  --os-features  --architecture amd64 --variant  --features  --name gcr.io/distroless/base:debug)
INFO: Elapsed time: 0.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```
## Bazel Release Version
` release 0.26.1`

## Operating System
` Ubuntu 18.04.2 LTS 64-Bit AMD`

## Python
`The default Python version is 3.6.8`

Can anyone please point towards what might be going wrong. 
## Attempt 1 to correct the issue
I realise that maybe I should have posted this under `bazelbuild/rules_docker`. This seemed to be related to [Issue #57](https://github.com/bazelbuild/rules_docker/issues/57) on docker pull. I tried the workaround mentioned there which was:
`bazel build --force_python=py2 --python2_path=/usr/bin/python2 //foo:layer1`

and got the following error:
```
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
ERROR: `--force_python` is disabled by `--incompatible_remove_old_python_version_api`
ERROR: Build options are invalid
INFO: Elapsed time: 0.184s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

```

**Comment by nlopezgi** [comment]
I do think this issue belongs in rules_docker repo. Have you tried adding the flags recommended in https://github.com/bazelbuild/rules_docker/blob/master/.bazelrc#L18?

**Comment by HVP1621** [comment]
Hey!! Thanks for pointing towards the above resource. Unfortunately, even after adding the flag(s) to the `.bazelrc` file, it gives me the same errors :(
I have noticed that it gives similar errors while trying to push an image onto any registry, its just that it cannot find `email.FeedParser` module when parsing some code in `httplib2`.

**Comment by dslomov** [comment]
Please file this in https://github.com/bazelbuild/rules_docker
