### ISSUE TITLE
Bazel CI: Downstream jobs are broken by git_repository refactoring

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8623]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1035

Bazel Codelabs
```
ERROR: An error occurred during the fetch of repository 'org_golang_google_grpc':
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 158
  | _clone_or_update(ctx)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 31, in _clone_or_update
  | git_repo(ctx, directory)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
  | _update(ctx, git_repo)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 104, in _update
  | reset(ctx, git_repo)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 124, in reset
  | _git(ctx, git_repo, "reset", "--hard", git_re...)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 142, in _git
  | _error(ctx.name, (start + list(args)), st.s...)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dba31623650bde83bfd5e4fc944f26a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 164, in _error
  | fail(("error running '%s' while worki...)))
  | error running 'git reset --hard 2fdaae294f38ed9a121193c51ec99fecd3b13eb7' while working with @org_golang_google_grpc:
  | fatal: Could not parse object '2fdaae294f38ed9a121193c51ec99fecd3b13eb7'.

```
Culprit: 50a2d6c9b9c55776ec747a656a2edd971e723771
https://buildkite.com/bazel/culprit-finder/builds/165

/cc @irengrig 

FYI @buchgr for Green Team rotation.

**Comment by meteorcloudy** [comment]
@philwo found out this fix is lost after refactoring: https://github.com/bazelbuild/bazel/commit/39688b2454965eb45aa2f02a3f078adeee06ccd1

**Comment by meteorcloudy** [comment]
The breakage has been fixed by rollback
