### ISSUE TITLE
type 'NoneType' has no operator [](string) using env["FOO"], env["BAR"]

### ISSUE THREAD

**Issue by rlewkowicz** [bazelbuild/bazel#8637]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

python formatted bazel seems unable to access env as in `env["PATH"]` after 24.1.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm just trying to build tensorflow 2.0 with avx and or mkl

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

VScode 2019, bazel 25 or 26, build TensorFlow 2.0 from source on windows:
```
 bazel build --config=opt --config=cuda --config=mkl --config=v2 --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```
### What operating system are you running Bazel on?
Windows

### What's the output of `bazel info release`?
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/Ryan/AppData/Local/Programs/Python/Python36/python.exe
INFO: Reading rc options for 'info' from c:\users\ryan\desktop\tensorflow\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'info' from c:\users\ryan\desktop\tensorflow\.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Ryan/AppData/Local/Programs/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Ryan/AppData/Local/Programs/Python/Python36/lib/site-packages --python_path=C:/Users/Ryan/AppData/Local/Programs/Python/Python36/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1 --config=cuda --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file c:\users\ryan\desktop\tensorflow\.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\users\ryan\desktop\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\ryan\desktop\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:monolithic in file c:\users\ryan\desktop\tensorflow\.bazelrc: --define framework_shared_object=false
release 0.25.3
```

###  Have you found anything relevant by searching the web?
Nope! I'm actually even just trying to understand how env works in a python bazel file and I can't even find that. 

### Any other information, logs, or outputs that you want to share?

```
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1267
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1195, in _create_local_cuda_repository
                cuda_defines.update(_get_win_cuda_defines(repository...))
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1195, in cuda_defines.update
                _get_win_cuda_defines(repository_ctx)
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 172, in _get_win_cuda_defines
                print("HERE:", env["PATH"])
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 172, in print
                env["PATH"]
type 'NoneType' has no operator [](string)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1267
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1195, in _create_local_cuda_repository
                cuda_defines.update(_get_win_cuda_defines(repository...))
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 1195, in cuda_defines.update
                _get_win_cuda_defines(repository_ctx)
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 172, in _get_win_cuda_defines
                print("HERE:", env["PATH"])
        File "C:/users/ryan/desktop/tensorflow/third_party/gpus/cuda_configure.bzl", line 172, in print
                env["PATH"]
type 'NoneType' has no operator [](string)
INFO: Elapsed time: 4.721s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by rlewkowicz** [comment]
I'm missing something. It's trouble some everything just gets immediately esoteric. I'm like patching everything as I go, but I'm missing something
