### ISSUE TITLE
neither native.rule nor native.existing_rule work from macros called from WORKSPACE

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#865]
I'm trying to use macros to keep declaration of jars maintainable. I was trying to add code to make sure I don't declare a maven_jar twice.

I tried `rule` and `native_rule` and both give:

```
ERROR: /Users/oscar/stripe/uppsala/WORKSPACE:37:1: Traceback (most recent call last):
        File "/Users/oscar/stripe/uppsala/WORKSPACE", line 37
                hadoop("2.5.0")
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 44, in hadoop
                cascading("2.6.1")
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 19, in cascading
                _cascading_jar(mod, version)
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 3, in _cascading_jar
                native.rule(nm)
struct has no method 'rule'.
ERROR: Error evaluating WORKSPACE file /Users/oscar/stripe/uppsala/WORKSPACE.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.074s
```
```
ERROR: /Users/oscar/stripe/uppsala/WORKSPACE:37:1: Traceback (most recent call last):
        File "/Users/oscar/stripe/uppsala/WORKSPACE", line 37
                hadoop("2.5.0")
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 44, in hadoop
                cascading("2.6.1")
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 19, in cascading
                _cascading_jar(mod, version)
        File "/Users/oscar/stripe/uppsala/3rdparty/scalding.bzl", line 3, in _cascading_jar
                native.existing_rule(nm)
struct has no method 'existing_rule'.
ERROR: Error evaluating WORKSPACE file /Users/oscar/stripe/uppsala/WORKSPACE.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.083s
```

**Comment by damienmg** [comment]
Yes the native module is different in the WORKSPACE file. Because this feature does not has it's own documentation yet, it is not obvious this does not exist. Anyway would make sense to add those function.

**Comment by damienmg** [comment]
I re-read the description of the existing_rules and though it was for checking the existing *rules* (in which case it would not have helped you) but it is for checking the existing *rule targets*. This is confusing.

**Comment by damienmg** [comment]
And I just read the code, it use the same native module as base, I did a test seems like it works:
```
$ bazel build @local_jdk//:bin/java
WARNING: /private/tmp/test/test.bzl:2:3: rules: [android/appcompat_v4,android/appcompat_v7,android/crosstool,android/design,android/sdk,bazel_j2objc,bazel_tools,bootclasspath,extdir,jar,java,javac,jdk-default,jni_header,jni_md_header-darwin,jni_md_header-freebsd,jni_md_header-linux,jre-default,local_jdk].
WARNING: /private/tmp/test/test.bzl:3:3: rule local-jdk: new_local_repository.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.099s
$ ls
BUILD		bazel-bin	bazel-out	bazel-testlogs
WORKSPACE	bazel-genfiles	bazel-test	test.bzl
$ cat WORKSPACE
load("//:test.bzl", "macro")
macro()
$ cat BUILD
$ cat test.bzl
def macro():
  print("rules: [%s]" % ",".join([s for s in native.existing_rules()]))
  print("rule local-jdk: " + native.existing_rule("local_jdk")["kind"])
$
```

Tested with 0.2.0rc1 :)
