### ISSUE TITLE
Bazel crashes with "Not-yet-present artifact owner"

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#8693]
Repro:

With `ANDROID_HOME` and `ANDROIDNDK_HOME` properly setup do:

```
git clone git@github.com:bazelbuild/rules_jvm_external.git
cd rules_jvm_external/examples/android_local_test
bazel build //... --copt=-Dfoo=bar
```

The value of the option is not important, it can also be omitted. The build succeeds. 

Now change the value of the option:

```
bazel build //... --copt=-Dfoo=bar2
```

And Bazel crashes:

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties' (requested by nodes 'ActionLookupData{actionLookupKey=//src/test:main_activity_test BuildConfigurationValue.Key[ef6ae5260571a057024d65376ee215ec] false, actionIndex=10}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not-yet-present artifact owner: @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false (File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:842)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.getActionLookupValue(ArtifactFunction.java:398)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction$ArtifactDependencies.discoverDependencies(ArtifactFunction.java:459)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.compute(ArtifactFunction.java:86)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties' (requested by nodes 'ActionLookupData{actionLookupKey=//src/test:main_activity_test BuildConfigurationValue.Key[ef6ae5260571a057024d65376ee215ec] false, actionIndex=10}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not-yet-present artifact owner: @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false (File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:842)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.getActionLookupValue(ArtifactFunction.java:398)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction$ArtifactDependencies.discoverDependencies(ArtifactFunction.java:459)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.compute(ArtifactFunction.java:86)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties' (requested by nodes 'ActionLookupData{actionLookupKey=//src/test:main_activity_test BuildConfigurationValue.Key[ef6ae5260571a057024d65376ee215ec] false, actionIndex=10}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Not-yet-present artifact owner: @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false (File:[[<execution_root>]bazel-out/k8-fastbuild/bin]external/robolectric/bazel/robolectric-deps.properties @robolectric//bazel:properties BuildConfigurationValue.Key[875ff4344fb7628cf467bdd188a5711d] false)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:842)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.getActionLookupValue(ArtifactFunction.java:398)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction$ArtifactDependencies.discoverDependencies(ArtifactFunction.java:459)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.compute(ArtifactFunction.java:86)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)

```

**Comment by hlopko** [comment]
CC the attack team: @meteorcloudy @aehlig @buchgr @philwo @jmmv @meisterT :)

**Comment by meisterT** [comment]
Also fails for 0.26.1 and 0.25.3, so downgrading to P2.

**Comment by hlopko** [comment]
Also with 0.23.1 and 0.20.0..

**Comment by philwo** [comment]
Pretty mysterious (does that flag work in other circumstances? Or did it just never work?), but at least it doesn't open a print dialog, so we have that going for us...

**Comment by benjaminp** [comment]
Bazel's `android_local_test` rule is very naughty and caches artifacts globally.
```
diff --git a/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidLocalTest.java b/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidLocalTest.java
index e55439a54c..3a9b6b36dd 100644
--- a/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidLocalTest.java
+++ b/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidLocalTest.java
@@ -38,8 +38,6 @@ public class BazelAndroidLocalTest extends AndroidLocalTestBase {
     super(BazelAndroidSemantics.INSTANCE);
   }
 
-  Artifact androidAllJarsPropFile;
-
   @Override
   protected AndroidSemantics createAndroidSemantics() {
     return BazelAndroidSemantics.INSTANCE;
@@ -95,14 +93,6 @@ public class BazelAndroidLocalTest extends AndroidLocalTestBase {
   // throw an error.
   protected Artifact getAndroidAllJarsPropertiesFile(RuleContext ruleContext)
       throws RuleErrorException {
-    if (androidAllJarsPropFile == null) {
-      androidAllJarsPropFile = getAndroidAllJarsPropertiesFileHelper(ruleContext);
-    }
-    return androidAllJarsPropFile;
-  }
-
-  private Artifact getAndroidAllJarsPropertiesFileHelper(RuleContext ruleContext)
-      throws RuleErrorException {
     Iterable<RunfilesProvider> runfilesProviders =
         ruleContext.getPrerequisites("deps", Mode.TARGET, RunfilesProvider.class);
     for (RunfilesProvider runfilesProvider : runfilesProviders) {
```

**Comment by jin** [comment]
Nice catch @benjaminp! Would you like to submit a PR for that?

cc @ahumesky

**Comment by benjaminp** [comment]
Someone with access to `BlazeAndroidLocalTest.java` (or whatever that's called) will probably have an easier time doing a proper fix. I imagine `getJvmFlags` will have to take an additional parameter in order for the rule analysis logic to avoid computing the `roboelectric-deps.properties` artifact twice.

**Comment by hlopko** [comment]
I'll give it a shot. Thanks Benjamin!
