### ISSUE TITLE
java.lang.IllegalStateException: Can't find tenured space; update this class for a new collector

### ISSUE THREAD

**Issue by lioramilbaum** [bazelbuild/bazel#8775]
### Description of the problem / feature request:

Server crashed during startup on rhel7

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

run - ```bazel info```

### What operating system are you running Bazel on?

rhel7
yum  repo - bazel.x86_64 0:0.27.0-7.el7
java - java-11-openjdk-11.0.3.7-0.el7_6.x86_64

### What's the output of `bazel info release`?

Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing /home/lmilbaum/.cache/bazel/_bazel_lmilbaum/55f4e23676d5e49ea9e22174e2f40c96/server/jvm.out
java.lang.IllegalStateException: Can't find tenured space; update this class for a new collector
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.runtime.RetainedHeapLimiter.<init>(RetainedHeapLimiter.java:64)
	at com.google.devtools.build.lib.runtime.RetainedHeapLimiter.<init>(RetainedHeapLimiter.java:58)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.<init>(BlazeRuntime.java:167)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.<init>(BlazeRuntime.java:132)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1566)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1292)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1063)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:799)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:72)

**Comment by meisterT** [comment]
Please reopen if this is still a problem with current bazel.

**Comment by meisterT** [comment]
@sheltongeosx what JDK/JRE are you using?

We might want to relax this preconditions check: https://github.com/bazelbuild/bazel/blame/master/src/main/java/com/google/devtools/build/lib/runtime/RetainedHeapLimiter.java#L69

cc @janakdr

**Comment by jeosol** [comment]
Has this bug been resolved. I installed bazel today (Jul 8, 2021) and tried to follow the C++ tutorial example and got the same error. 

<pre>Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing /home/xxx/.cache/bazel/_bazel_xxxx/740a946ba5071ae4dc5a1db849476dbe/server/jvm.out
java.lang.IllegalStateException: Can&apos;t find tenured space; update this class for a new collector
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.runtime.RetainedHeapLimiter.&lt;init&gt;(RetainedHeapLimiter.java:64)
	at com.google.devtools.build.lib.runtime.RetainedHeapLimiter.&lt;init&gt;(RetainedHeapLimiter.java:58)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.&lt;init&gt;(BlazeRuntime.java:175)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.&lt;init&gt;(BlazeRuntime.java:139)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1601)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1340)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1113)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:849)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:75)</pre>

bazel version info: 
   bazel 2.0.0- (@non-git) 

System info:
NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by meisterT** [comment]
Yes, install a bazel version >= 3.3.0.

**Comment by jeosol** [comment]
ah ok. MeisterT, thanks for the info. I install via Opensuse's 'zypper install bazel' and the one packaged is probably old.

**Comment by jeosol** [comment]
@meisterT I see sever v5.00 prelease and a v4.1. Which one do you recommend to download ( not sure if the v5.00 preleases are stable or have issues). 

My intented  use is with Common Lisp, but I plan to follow the C++ tutorial to get a good handle of how bazel works.  I am aware of the qitab/bazelisp repo but not sure how both are linked. I assume I still need bazel to be able to use bazelisp. Don't worry about the lisp part, as I sent an email to one of the devs already. 

Now I just need bazel to work property with the packaged C++ examples.

**Comment by meisterT** [comment]
https://blog.bazel.build/2021/06/15/bazel-rolling-releases.html has some info about rolling releases.

I would recommend v4.1.0 for now

**Comment by jeosol** [comment]
@meisterT 

Thanks. I will take a look at the link you added. I will go ahead to install v4.1.0 for now.
