### ISSUE TITLE
new_git_repository doesn't work on Windows

### ISSUE THREAD

**Issue by Lunarsong** [bazelbuild/bazel#8781]
### Description of the problem / feature request:

**new_git_repository** doesn't work on Windows

Ever since __--incompatible_remove_native_git_repository=false__ was removed there doesn't seem to be a way to make __new_git_repository__ work on Windows, so depending on external git repos without a BUILD file is impossible.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a WORKSPACE with:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "glm",
    build_file_content = """
cc_library(
    name = "glm",
    includes = ["."],
    srcs = glob(["glm/**/*.hpp"]) + glob(["glm/**/*.h"]),
    hdrs = glob(["glm/**/*.inl"]),
    visibility = ["//visibility:public"],
    defines = [
        "GLM_FORCE_RADIANS",
        "GLM_FORCE_LEFT_HANDED",
        "GLM_FORCE_DEPTH_ZERO_TO_ONE",
    ],
)""",
    commit = "8cd6db11cd8d2bf68aaad86097f15a9f94604dc4",
    init_submodules = 1,
    remote = "https://github.com/g-truc/glm.git",
)
```

and a simple project depending on @glm//:glm. 

```
cc_binary(
    name = "example",
    srcs = [ 
        "main.cpp",
    ],
    deps = [
        "@glm//:glm",
    ],
    visibility = ["//visibility:public"],
)
```

main.cpp

```cpp
#include <GLM/glm.hpp>

int main() {
  return 0;
}
```

Build __example__ will result in:

```
main.cpp(2): fatal error C1083: Cannot open include file: 'GLM/glm.hpp': No such file or directory
```

Looking at the generated folder _C:\Users\shane\_bazel_shane\civbz5t3\external\glm_ reveals it is empty besides a _WORKSPACE_ and _BUILD.bazel_ files. The repo itself isn't there.

Replacing _build_file_content_ with _build_file_ shows a different issue. If

```
    build_file = "@//third_party/glm.BUILD",
```

Then

```
INFO: Call stack for the definition of repository 'glm' which is a new_git_repository (rule definition at C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl:239:22):
 - C:/projects/tactics/WORKSPACE:3:1
ERROR: An error occurred during the fetch of repository 'glm':
   Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party/glm.BUILD:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party/glm.BUILD
ERROR: C:/projects/tactics/BUILD:1:1: no such package '@glm//': Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party/glm.BUILD:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party/glm.BUILD and referenced by '//:game'
ERROR: Analysis of target '//:game' failed; build aborted: no such package '@glm//': Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party/glm.BUILD:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party/glm.BUILD
INFO: Elapsed time: 0.596s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
```

Or, 

```
    build_file = "@//third_party:glm.BUILD",
```

Results in:

```
INFO: Call stack for the definition of repository 'glm' which is a new_git_repository (rule definition at C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl:239:22):
 - C:/projects/tactics/WORKSPACE:3:1
ERROR: An error occurred during the fetch of repository 'glm':
   Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/cpp/cc_configure.bzl:121:15):
 - C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/cpp/cc_configure.bzl:162:5
 - /DEFAULT.WORKSPACE.SUFFIX:293:1
ERROR: C:/projects/tactics/BUILD:1:1: no such package '@glm//': Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party and referenced by '//:game'
ERROR: Analysis of target '//:game' failed; build aborted: no such package '@glm//': Traceback (most recent call last):
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 228
                workspace_and_buildfile(ctx)
        File "C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //third_party:glm.BUILD: BUILD file not found in any of the following directories.
 - C:/projects/tactics/third_party
INFO: Elapsed time: 0.409s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

I can confirm the existence of C:/projects/tactics/third_party/glm.BUILD

### What operating system are you running Bazel on?

Windows 10 Version	10.0.17763 Build 17763

### What's the output of `bazel info release`?

release 0.27.1

Also tried with release 0.26

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/Lunarsong/tactics.git
1ffa799b89e1dc1244f530063296316326e0de82
1ffa799b89e1dc1244f530063296316326e0de82

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/2090

### Any other information, logs, or outputs that you want to share?

In the full project I get more errors, such as:

```
Build __example__ may result in some debug outputs:
DEBUG: Rule 'glm' indicated that a canonical reproducible form can be obtained by modifying arguments commit = ""
DEBUG: Call stack for the definition of repository 'glm' which is a new_git_repository (rule definition at C:/users/shane/_bazel_shane/civbz5t3/external/bazel_tools/tools/build_defs/repo/git.bzl:239:22):
```

**Comment by Lunarsong** [comment]
A working alternative is:

```
http_archive(
    name = "glm",
    build_file = "@//third_party:glm.BUILD",
    strip_prefix = "glm-0.9.9.5",
    url = "https://github.com/g-truc/glm/archive/0.9.9.5.zip",
)
```
And 

```
http_archive(
    name = "glm",
    build_file_content = """
cc_library(
    name = "glm",
    includes = ["."],
    srcs = glob(["glm/**/*.hpp"]) + glob(["glm/**/*.h"]),
    hdrs = glob(["glm/**/*.inl"]),
    visibility = ["//visibility:public"],
    defines = [
        "GLM_FORCE_RADIANS",
        "GLM_FORCE_LEFT_HANDED",
        "GLM_FORCE_DEPTH_ZERO_TO_ONE",
    ],
)""",
    strip_prefix = "glm-0.9.9.5",
    url = "https://github.com/g-truc/glm/archive/0.9.9.5.zip",
)
```

Both seem to work. However not all repos I'm depending on have a release.

**Comment by laszlocsomor** [comment]
Using exactly the example you provided, I can build `//:example` on Windows 10 with Bazel 0.27.

Let's debug!
- could you try building with: `bazel --output_user_root=c:\_bazel build //:example`
- where do you have MSYS2 installed?
- what's the `BAZEL_SH` envvar's value?
- do you have Git for Windows installed, and where?
- could you create a public GitHub repo that I could clone and repro the issue from? I copy-pasted your example but that works fine on my machine.

> (Also, is this correct it should be _build_file = "@//:third_party/glm.BUILD"_ ? Seems odd, as usually I expect the _:_ to be before the filename.)

The ":" separates the package's path from the target's path within the package.

Remember that a package is simply a directory with a BUILD file in it, plus all of its subdirectories that do NOT have a BUILD file in them, plus all files in these directories.

If a label is `//foo/bar:baz/qux/bla.txt`, it means that:
- the package is "//foo/bar"
- the package's BUILD file is at "foo/bar/BUILD" (or "foo/bar/BUILD.bazel")
- the label refers to "baz/qux/bla.txt" within that package, i.e. to the "foo/bar/baz/qux/bla.txt" file
- there is no BUILD file under "foo/bar/baz" nor under "foo/bar/baz/qux", otherwise they would be separate package and not be part of the "foo/bar" package

Therefore if `@//:third_party/glm.BUILD` is what works, it shows that the nearest `BUILD` file is `@//:BUILD` and there's no BUILD (or BUILD.bazel) file under "third_party/".

**Comment by meisterT** [comment]
Please reply if this is still a problem at head.
