### ISSUE TITLE
Android: Desugaring fails on Sceneform with "Type com.google.ar.schemas.sceneform.LightingDef not present"

### ISSUE THREAD

**Issue by jfaust** [bazelbuild/bazel#8791]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Trying to build and Android app using Sceneform, I get:
```
Exception in thread "main" java.lang.TypeNotPresentException: Type com.google.ar.schemas.sceneform.LightingDef not present
	at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:97)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:60)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)
	at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)
	at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:660)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:647)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:408)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2235)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:632)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:463)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:405)
	at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1035)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:988)
Caused by: java.lang.ClassNotFoundException: Class com.google.ar.schemas.sceneform.LightingDef not found
	at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)
	... 16 more
```

Disabling desugaring results in an opcode error I can't fix because `rules_jvm_external` doesn't allow me to specify `--android-sdk-min` to dex.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use `rules_jvm_external` to bring in the sceneform library from maven:
```
RULES_JVM_EXTERNAL_TAG = "2.2"

RULES_JVM_EXTERNAL_SHA = "f1203ce04e232ab6fdd81897cf0ff76f2c04c0741424d192f28e65ae752ce2d6"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.ar.sceneform.ux:sceneform-ux:aar:1.10.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

Build an Android binary with `@maven//:com_google_ar_sceneform_ux_sceneform_ux` as a dependency.

### What operating system are you running Bazel on?

macOS 10.14.5

### What's the output of `bazel info release`?

release 0.27.1

###  Have you found anything relevant by searching the web?

Just this:
https://github.com/xamarin/XamarinComponents/issues/578

Which implies that Xamarin has this issue with VS2017, but not VS2019 - I believe in VS2019 they upgraded to use `d8` instead of `dx`

**Comment by jfaust** [comment]
I'm trying to work around this by using `--desugar_for_android=false`, however that results in:
```
Exception in thread "main" java.util.concurrent.ExecutionException: com.android.dx.cf.code.SimException: ERROR in com.google.ar.sceneform.rendering.CameraStream.<init>:(ILcom/google/ar/sceneform/rendering/Renderer;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:487)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.google.devtools.build.android.dexer.DexBuilder.produceDexArchive(DexBuilder.java:253)
	at com.google.devtools.build.android.dexer.DexBuilder.buildDexArchive(DexBuilder.java:136)
	at com.google.devtools.build.android.dexer.DexBuilder.main(DexBuilder.java:123)
Caused by: com.android.dx.cf.code.SimException: ERROR in com.google.ar.sceneform.rendering.CameraStream.<init>:(ILcom/google/ar/sceneform/rendering/Renderer;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
	at com.android.dx.cf.code.Simulator.fail(Simulator.java:947)
	at com.android.dx.cf.code.Simulator.checkInvokeDynamicSupported(Simulator.java:848)
	at com.android.dx.cf.code.Simulator.access$700(Simulator.java:43)
	at com.android.dx.cf.code.Simulator$SimVisitor.visitConstant(Simulator.java:711)
	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:780)
	at com.android.dx.cf.code.Simulator.simulate(Simulator.java:117)
	at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:789)
	at com.android.dx.cf.code.Ropper.doit(Ropper.java:744)
	at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:309)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:150)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:102)
	at com.google.devtools.build.android.dexer.Dexing.addToDexFile(Dexing.java:198)
	at com.google.devtools.build.android.dexer.DexConverter.toDexFile(DexConverter.java:31)
	at com.google.devtools.build.android.dexer.DexConversionEnqueuer$ClassToDex.call(DexConversionEnqueuer.java:173)
	at com.google.devtools.build.android.dexer.DexConversionEnqueuer$ClassToDex.call(DexConversionEnqueuer.java:156)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:258)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
	at com.google.devtools.build.android.dexer.DexConversionEnqueuer.toDex(DexConversionEnqueuer.java:113)
	at com.google.devtools.build.android.dexer.DexConversionEnqueuer.call(DexConversionEnqueuer.java:93)
	at com.google.devtools.build.android.dexer.DexConversionEnqueuer.call(DexConversionEnqueuer.java:46)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm currently happy targeting just Android versions that support API 26 and higher -- I've managed to get a local version of bazel to do this by modifying `src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java` to set `result.minSdkVersion = 26;` in `toDexOptions()`. Is this something that could be exposed via a `--experimental_android_dex_min_sdk_version` or similar? I'd be happy to submit a PR, as at least it'd allow us to work around this in the short term.

**Comment by jfaust** [comment]
Hmm. My workaround doesn't fully work - after hitting a couple other hurdles (like having to explicitly compile in the `core-lambda-stubs.jar` file), I'm getting verification rejections running the code on a phone. I think this basically blocks our ability to use Bazel to build these artifacts, so I'm going to need to switch over to Gradle for the java part of this build.

**Comment by jin** [comment]
The root failure is from `@maven//:com_google_ar_sceneform_rendering`:

```
$ bazel build :app --verbose_failures
INFO: Analyzed target //:app (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jingwen/42c04ae92ceb2bcd18ee8aebe023cfa2/external/maven/BUILD:211:1: Desugaring external/maven/_aar/com_google_ar_sceneform_rendering/classes_and_libs_merged.jar for Android failed (Exit 1)
Type com.google.ar.schemas.sceneform.LightingDef not presentTarget //:app failed to build
INFO: Elapsed time: 0.243s, Critical Path: 0.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

BUILD:

```
android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    custom_package = "not.used",
    deps = [
        "@maven//:com_google_ar_sceneform_rendering",
    ],
)
```

which depends on `@maven//:com_google_ar_core`:

```
$ bazel query --output=build @maven//:com_google_ar_sceneform_rendering
# /private/var/tmp/_bazel_jingwen/42c04ae92ceb2bcd18ee8aebe023cfa2/external/maven/BUILD:211:1
aar_import(
  name = "com_google_ar_sceneform_rendering",
  tags = ["maven_coordinates=com.google.ar.sceneform:rendering:aar:1.10.0"],
  deps = ["@maven//:com_google_ar_core"],
  aar = "@maven//:v1/https/maven.google.com/com/google/ar/sceneform/rendering/1.10.0/rendering-1.10.0.aar",
)
```

Neither the Sceneform Rendering nor AR Core AARs contain the class for `LightingDef`:

```
$ unzip rendering-1.10.0.aar && jar tf classes.jar | grep LightingDef
$ unzip core-1.10.0.aar && jar tf classes.jar | grep LightingDef
```

So, the question now is figuring out where is the `LightingDef` class defined or generated.

The pom file for rendering-1.10.aar doesn't suggest any dependency that `rules_jvm_external` may have missed:

```xml
$ cat rendering-1.10.0.pom
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation=  "http://maven.apache.org/POM/4.0.0
  http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.ar.sceneform</groupId>
  <artifactId>rendering</artifactId>
  <version>1.10.0</version>
  <packaging>aar</packaging>
  <licenses>
  <license>
    <name>Apache License, Version 2.0</name>
    <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    <distribution>repo</distribution>
    <comments>A business-friendly OSS license</comments>
  </license>
</licenses>
<dependencies>
<dependency>
    <groupId>com.google.ar</groupId>
    <artifactId>core</artifactId>
    <version>1.10.0</version>
    <type>aar</type>
</dependency>

</dependencies>
</project>
```

Same thing for `core-1.10.0`'s pom:

```xml
$ cat core-1.10.0.pom
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation=  "http://maven.apache.org/POM/4.0.0
  http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.ar</groupId>
  <artifactId>core</artifactId>
  <version>1.10.0</version>
  <packaging>aar</packaging>
  <licenses>
  <license>
    <name>Apache License, Version 2.0</name>
    <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    <distribution>repo</distribution>
    <comments>A business-friendly OSS license</comments>
  </license>
</licenses>
<dependencies/>
</project>
```

**Comment by jfaust** [comment]
Ahh, I didn't even think it might be a dependency problem - I just assumed it was an issue with desugaring, since it works in Gradle. I found `LightingDef` in `sceneform-base`, which `sceneform.core` depends on, but `sceneform.rendering` does not actually seem to have a dependency on `sceneform.core`. I'm confused how this works in Gradle.

**Comment by jfaust** [comment]
https://mvnrepository.com/artifact/com.google.ar.sceneform/rendering/1.10.0 only shows a dependency on `com.google.ar.core`, not `com.google.ar.sceneform.core`.

Is this something I should submit to https://github.com/google-ar/sceneform-android-sdk ?

**Comment by jin** [comment]
> Is this something I should submit to https://github.com/google-ar/sceneform-android-sdk ?

Yes. Additionally, `rendering` should also depend on `filament-android`, so the final `aar_import` should look like this:

```
aar_import(
   name = "com_google_ar_sceneform_rendering",
   aar = "v1/https/maven.google.com/com/google/ar/sceneform/rendering/1.10.0/renderin    g-1.10.0.aar",
   deps = [
     ":com_google_ar_core",
     ":com_google_ar_sceneform_sceneform_base",
     ":com_google_ar_sceneform_filament_android",
   ],
   tags = ["maven_coordinates=com.google.ar.sceneform:rendering:aar:1.10.0"],
 )
```

`rendering` depends on a class in `filament`:

```
$ bazel build :app --verbose_failures
INFO: Analyzed target //:app (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jingwen/42c04ae92ceb2bcd18ee8aebe023cfa2/external/maven/BUILD:211:1: Desugaring external/maven/_aar/com_google_ar_sceneform_rendering/classes_and_libs_merged.jar for Android failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_jingwen/42c04ae92ceb2bcd18ee8aebe023cfa2/bazel-workers/worker-4-Desugar.log ---8<---8<---
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/android/filament/android/UiHelper$RendererCallback
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:67)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.findTargetMethod(LambdaDesugaring.java:327)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.queueUpBridgeMethodIfNeeded(LambdaDesugaring.java:236)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.access$200(LambdaDesugaring.java:56)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:413)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2235)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:657)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:488)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:428)
	at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1067)
	at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:1031)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:1011)
Caused by: java.lang.ClassNotFoundException: Class com.google.android.filament.android.UiHelper$RendererCallback not found
	at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more
---8<---8<--- End of log ---8<---8<---
Target //:app failed to build
INFO: Elapsed time: 0.556s, Critical Path: 0.43s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
