### ISSUE TITLE
bazel-integration-testing fails with bazel at HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8825]
### Description of the problem / feature request:

https://github.com/bazelbuild/bazel-integration-testing/commit/d51598450e8095bad4966f7089f0415db0e4e0e0 with Bazel built at https://github.com/bazelbuild/bazel/commit/9c913b93e275038393e4ba5f67b7421919d93cf9, the repo fetching phase fails:

```
C:\src\bazel-integration-testing>set PATH=c:\msys64\usr\bin;c:\Windows\System32

C:\src\bazel-integration-testing>bazel-9c913b93e275038393e4ba5f67b7421919d93cf9.exe fetch --repository_cache= //javatests/build/bazel/tests/integration:WorkspaceDriverIntegrationTest
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'bazel_skylib' which is a git_repository (rule definition at C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - C:/src/bazel-integration-testing/WORKSPACE:30:1
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 126, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", git_re...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin tags/0.8.0:tags/0.8.0' while working with @bazel_skylib:
BUG: run-command.c:500: disabling cancellation: Invalid argument
      0 [main] git 14712 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
ERROR: no such package '@bazel_skylib//lib': Traceback (most recent call last):
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 126, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", git_re...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin tags/0.8.0:tags/0.8.0' while working with @bazel_skylib:
BUG: run-command.c:500: disabling cancellation: Invalid argument
      0 [main] git 14712 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
Loading: 0 packages loaded
```

After a clean --expunge, using Bazel built at the previous commit (https://github.com/bazelbuild/bazel/commit/c7e8a922a38ea7db29d207fbd43a6af6231c7478):

```
C:\src\bazel-integration-testing>bazel-c7e8a922a38ea7db29d207fbd43a6af6231c7478.exe fetch --repository_cache= //javatests/build/bazel/tests/integration:WorkspaceDriverIntegrationTest
(...)
INFO: All external dependencies fetched successfully.
Loading: 30 packages loaded
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/bazelbuild//bazel-integration-testing
d51598450e8095bad4966f7089f0415db0e4e0e0
d51598450e8095bad4966f7089f0415db0e4e0e0
```

**Comment by laszlocsomor** [comment]
I'm using MSYS git:

```
$ git version
git version 2.21.0

$ cygpath -w $(realpath $(which git))
C:\msys64\usr\bin\git.exe
```

**Comment by laszlocsomor** [comment]
An important question is, why Bazel CI did not show this error?
The pipeline has been green lately:
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1080#e4dbd75a-d958-42b0-9d85-511191d2ce14
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1073#79c9f84f-e070-4041-a66e-3f51209d2ad4
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1072#efc63c96-7b6f-4c14-b9b6-954bd0381bba

**Comment by laszlocsomor** [comment]
I can repro this with Bazel built at HEAD, the one used for https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1080#e4dbd75a-d958-42b0-9d85-511191d2ce14 :

```
C:\src\bazel-integration-testing>bazel-b4d9588efd3b425c8dca83a6267b75ce0280724c.exe fetch //...
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'bazel_skylib' which is a git_repository (rule definition at C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - C:/src/bazel-integration-testing/WORKSPACE:30:1
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 126, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", git_re...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin tags/0.8.0:tags/0.8.0' while working with @bazel_skylib:
BUG: run-command.c:500: disabling cancellation: Invalid argument
      1 [main] git 12576 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
ERROR: no such package '@bazel_skylib//lib': Traceback (most recent call last):
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 126, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", git_re...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "C:/_bazel/if4trwy3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin tags/0.8.0:tags/0.8.0' while working with @bazel_skylib:
BUG: run-command.c:500: disabling cancellation: Invalid argument
      1 [main] git 12576 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
Loading: 0 packages loaded
```

**Comment by laszlocsomor** [comment]
I found a workaround:
1. uninstall git from msys: `pacman -R git`
2. use git from git-for-windows: `set Path=c:\msys64\usr\bin;c:\git\mingw64\bin`

But now after I re-install git for msys, I can no longer repro this bug.
