### ISSUE TITLE
depending on a java_library from an android_library results in dexer failures

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#886]
This is bazel 0.1.5 I tried this in:

Simple repro step:
1. Write a `java_library`
2. Depend on it in an `android_library`
3. Build an `android_binary` that depends on that `android_library`

You'll see something like this when you try to install/build:

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
    at com.android.dx.command.dexer.Main.processClass(Main.java:752)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
    at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
    at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:672)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
    at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
    at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
    at com.android.dx.command.dexer.Main.processClass(Main.java:749)
    ... 12 more

Workaround: change `java_library` to `android_library`.

PS: I chose to use `java_library` because my package doesn't use any Android SDK features, so pure javac should be OK for me.

More details: https://stackoverflow.com/questions/24662801/bad-class-file-magic-or-version

**Comment by ahumesky** [comment]
"bad class file magic (cafebabe) or version (0034.0000)"
0x34 is java 8 bytecode, which dx can't consume. You can fix this by adding -target 7 -source 7 to the javacopts of the library, or use --java_copts="-target 7 -source 7" which will set those opts for all java rules, or adjust the java_toolchain rule.

**Comment by perezd** [comment]
Yes, I could do that, or bazel could realize that and do it for me.

Why do I have to know/care about this? Bazel should have enough context to fix this for me. I think its a bit hasty to close this without considering a way to make this suck less for people who are just getting started.

**Comment by perezd** [comment]
Also, why is this my problem as an end user? What if I want to use this code in different build contexts? If the code is JDK7 and JDK8 compliant, why can't I just blindly depend on it and let my binary context figure this out for me? 

This feels like it violates the principal of least surprise.

**Comment by ahumesky** [comment]
Unfortunately there isn't a good mechanism at the moment for an android_library (or any rule for that matter) to influence its dependencies in this way, and for the reason you describe: a single rule could be depended upon by multiple rules that want different configurations, and for that we'll need dynamic configurations, which are a ways out: https://docs.google.com/document/d/1uoU8t7loTOu6uyzez-ilhcYgEXg4xjViJu0aqrf69TY/edit
I'll reopen this though since we could make this better one day.

**Comment by JakeWharton** [comment]
> This feels like it violates the principal of least surprise.

Changing the behavior to that which you describe would actually be the most surprising to me.

If I write a Java library that links against a Java 8 API and then later I add that library as a dependency to to android library suddenly its Java platform changes and compilation of the java library fails? Or what if the Java library only uses Java 6 APIs but contains a lambda?

The classfile version that your Java library targets is part of its public API which effects downstream consumers and thus your problem to regulate. I do not want to see the build system doing anything clever here. Especially since modern versions of Android actually do have some of the Java 8 APIs and the toolchain may actually support ingesting version 52 classfiles in the future.

**Comment by aj-michael** [comment]
This seems like an ideal candidate for Bazel's [constraint system](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintSemantics.java)

**Comment by ahumesky** [comment]
Consolidating this with bugs
https://github.com/bazelbuild/bazel/issues/2222
and
https://github.com/bazelbuild/bazel/issues/1386
