### ISSUE TITLE
git_repository fails with extra remotes in ~/.gitconfig

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#8957]
### Description of the problem / feature request:

`git_repository` fails if `~/.gitconfig` has configurations for other remotes than `origin` without specifying any `remote.<my-remote>.url` value. I expect the url specified in the `git_repository` rule to be used and that no other remote is used.

Please also check the trace from a Bazel **crash**, which I can't reproduce, at the end of this issue description.

```
$ bazel fetch @starlark//:foo
INFO: Call stack for the definition of repository 'starlark' which is a git_repository (rule definition at /home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /home/myuser/bazel-git-issue/WORKSPACE:3:1
ERROR: An error occurred during the fetch of repository 'starlark':
   Traceback (most recent call last):
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 124, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "--all")
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch --all' while working with @starlark:
fatal: 'mybackup' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch mybackup
ERROR: no such package '@starlark//': Traceback (most recent call last):
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 124, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "--all")
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "/home/myuser/.cache/bazel/_bazel_myuser/9195df7af0878e6c2c936b9f641b6fd1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch --all' while working with @starlark:
fatal: 'mybackup' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch mybackup
Loading: 0 packages loaded
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cat > WORKSPACE <<EOF
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "starlark",
    remote = "https://github.com/bazelbuild/starlark.git",
    commit = "99bb1d334bd672d03131f95a8913ed1f6df505ba",
    shallow_since = "1563796553 +0200",
)
EOF
git config --global remote.mybackup.prune True
bazel fetch @starlark//:foo
```

### What operating system are you running Bazel on?

Linux 4.10.0-40-generic

### What's the output of `bazel info release`?

`release 0.28.1`

###  Have you found anything relevant by searching the web?

I have not found any recent GitHub issue about `git_reporitory`.

https://github.com/bazelbuild/bazel/commit/9c913b93e275038393e4ba5f67b7421919d93cf9#diff-e7fe1746423d8146f7284080388e7104R124 with `git fetch --all` seems to be the problem.

### Any other information, logs, or outputs that you want to share?

I even got a crash once, but I can't reproduce it:
```
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'org_golang_google_grpc' which is a git_repository (rule definition at /home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/io_bazel_rules_go/go/private/repositories.bzl:237:9
 - /home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/io_bazel_rules_go/go/private/repositories.bzl:163:5
 - /home/myuser/git/github/bazelstuff/buildbarn/WORKSPACE:112:1
ERROR: An error occurred during the fetch of repository 'org_golang_google_grpc':
   Traceback (most recent call last):
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 124, in fetch
		_git_maybe_shallow(ctx, git_repo, "fetch", "--all")
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
		_error(ctx.name, (start + args_list), st.st...)
	File "/home/myuser/.cache/bazel/_bazel_myuser/c9bc5fb95ac25c51e773646199643d31/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
error running 'git fetch --all' while working with @org_golang_google_grpc:
fatal: 'mybackup' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch mybackup
fatal: 'mybackup2' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch mybackup2
Internal error thrown during build. Printing stack trace: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.lang.String.format(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 29.764s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (27 packages loaded, 6482 targets configured)
    Fetching @com_github_prometheus_client_golang; Restarting. 9s
    Fetching @bazel_gazelle_go_repository_tools; fetching 9s
    Fetching @com_github_bazelbuild_remote_apis; Restarting. 8s
    Fetching @com_github_grpc_ecosystem_go_grpc_prometheus; Restarting. 8s
    Fetching @org_golang_x_tools; Cloning 589c23e65e65055d47b9ad4a99723bc389136265 of https://go.googlesource.com/tools
Internal error thrown during build. Printing stack trace: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.lang.String.format(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:98)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:524)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.lang.String.format(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(ParallelEvaluator.java:70)
	at com.google.devtools.build.skyframe.InMemoryMemoizingEvaluator.evaluate(InMemoryMemoizingEvaluator.java:205)
	at com.google.devtools.build.skyframe.SequentialBuildDriver.evaluate(SequentialBuildDriver.java:38)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.configureTargets(SkyframeExecutor.java:2381)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:373)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:399)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:198)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:110)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
FAILED: Build did NOT complete successfully (27 packages loaded, 6482 targets configured)
    Fetching @com_github_prometheus_client_golang; Restarting. 9s
    Fetching @bazel_gazelle_go_repository_tools; fetching 9s
    Fetching @com_github_bazelbuild_remote_apis; Restarting. 8s
    Fetching @com_github_grpc_ecosystem_go_grpc_prometheus; Restarting. 8s
    Fetching @org_golang_x_tools; Cloning 589c23e65e65055d47b9ad4a99723bc389136265 of https://go.googlesource.com/tools
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
```

**Comment by moroten** [comment]
This might be argued to be a bug in git. I'm fine with that.

**Comment by laurentlb** [comment]
The crash of Bazel ("Internal error...") has been fixed very recently.

Assigning to Klaus to triage the git failure.

**Comment by philwo** [comment]
Looks more like a Git bug to me. Not sure what Bazel could do to fix / workaround this. 🤔 Is this still an issue?

**Comment by moroten** [comment]
`git fetch` with specifying `origin` solves the problem, see https://github.com/bazelbuild/bazel/blob/7abfa307aa9aa7daea0b2caeee9377861c060948/tools/build_defs/repo/git_worker.bzl#L124
It is working in Bazel 4.0.
