### ISSUE TITLE
Workspace download retries with read timeouts

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8974]
It seems like currently if bazel fails to download something from the WORKSPACE that has multiple URLs defined, it doesn't always fallback to the other URL. For example I hit this error:

```
Starting local Bazel server and connecting to it...
 - /root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl:93:5
 - /root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl:261:13
 - /tmp/share/code/WORKSPACE:83:1
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/go_sdk/go_sdk.tar.gz: Read timed out
ERROR: While resolving toolchains for target @com_github_bazelbuild_buildtools//buildifier:buildifier: invalid registered toolchain '@go_sdk//:go_android_amd64': no such package '@go_sdk//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/go_sdk/go_sdk.tar.gz: Read timed out
ERROR: Analysis of target '//:buildifier.check' failed; build aborted: invalid registered toolchain '@go_sdk//:go_android_amd64': no such package '@go_sdk//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /root/.cache/bazel/_bazel_root/c99f8fb4c845b3aae6d69f1a3c75aa35/external/go_sdk/go_sdk.tar.gz: Read timed out
ERROR: Build failed. Not running target
```

When my WORKSPACE contained:

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "8df59f11fb697743cbb3f26cfb8750395f30471e9eabde0d174c3aebc7a1cd39",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.19.1/rules_go-0.19.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/0.19.1/rules_go-0.19.1.tar.gz",
    ],
)
```

I would have expected this to fallback to the GitHub URL before failing.

### What's the output of `bazel info release`?

release 0.28.0

**Comment by artem-zinnatullin** [comment]
I've submitted two fixes for this issue:

- #9015 which makes `HttpDownloader` to actually use provided `urls` as fallback if HTTP payload errors out
- #9008 which brings back the recovery from `SocketTimeoutException` occurred during HTTP connection (it was broken few months ago)

---

I also think `HttpDownloader`, `HttpConnector` and `HttpConnectorMultiplexer` based on `HttpUrlConnection` should be deprecated in favor of more modern non-blocking Netty based code — `HttpDownloadHandler`, potentially would need to be abstracted out so both repository downloads and blob downloads could reuse it.

Would be happy to work on this if we achieve consensus 😊

**Comment by buchgr** [comment]
> Would be happy to work on this if we achieve consensus blush

We wanted to do this for a while. It's just been that we never got around to do it. Feel free to send patches!

**Comment by artem-zinnatullin** [comment]
Great! 

Would it be ok to open a separate issue to outline the `HttpUrlConnection` → `Netty` migration details and track its progress?

---

Can you please consider #9015 and #9008 in the mean time as they significantly improve resiliency of repository downloads? 😊
