### ISSUE TITLE
Can't write an executable genrule

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#918]
Create this BUILD file in an empty directory with an empty WORKSPACE:

```
genrule(
	name = "x",
	srcs = [],
	executable = 1,
	outs = ["out.sh"],
	cmd = "echo echo Hello World > $@",
)
```

`bazel build //:x` works, and then `bazel-genfiles/out.sh` works, but `bazel run //:x` fails.

```
$ bazel run //:x
Unhandled exception thrown during build; message: Attribute 'executable' is potentially configurable - not allowed here
INFO: Elapsed time: 0.089s
java.lang.IllegalStateException: Attribute 'executable' is potentially configurable - not allowed here
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:222)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.bazel.rules.genrule.BazelGenRuleRule$1.getDefault(BazelGenRuleRule.java:197)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:62)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:47)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutableNonTestRule(RunCommand.java:515)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.isExecutable(RunCommand.java:501)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTarget(RunCommand.java:452)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.validateTargets(RunCommand.java:408)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.access$000(RunCommand.java:85)
	at com.google.devtools.build.lib.runtime.commands.RunCommand$1.validateTargets(RunCommand.java:119)
	at com.google.devtools.build.lib.buildtool.BuildTool$1.notifyTargets(BuildTool.java:391)
	at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:201)
	at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:401)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:334)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.processRequest(RunCommand.java:115)
	at com.google.devtools.build.lib.runtime.commands.RunCommand.exec(RunCommand.java:155)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:371)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1021)
	at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
	at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
	at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:976)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:773)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)
```

**Comment by dfabulich** [comment]
It even fails like this when I remove the `executable` attribute from the `BUILD` file.

**Comment by dfabulich** [comment]
```
$ bazel version
Build label: 0.1.5-homebrew
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 9 23:35:58 2016 (1455060958)
Build timestamp: 1455060958
Build timestamp as int: 1455060958
```

**Comment by dfabulich** [comment]
I just tried building the latest master revision; that fails, too, with the same error.

```
$ /Users/dfabulich/git/bazel/output/bazel version
......
Build label: head (@9e100ac)
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 16 22:23:58 2016 (1455661438)
Build timestamp: 1455661438
Build timestamp as int: 1455661438
```

**Comment by ahumesky** [comment]
I can reproduce this -- very strange error

**Comment by ahumesky** [comment]
I think the rule definition became misconfigured when it was moved to bazel, I think this line:
https://github.com/bazelbuild/bazel/blob/9e100ac1ddfc8aac2cd4185824d1abdf5a456169/src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BazelGenRuleRule.java#L182
should have nonconfigurable()

**Comment by ahumesky** [comment]
Hmm, there might be a way to make executable correctly configurable (i.e., able to accept the result of a select() call), but that will take a bit more investigation. For now though, you can work around this by patching by applying nonconfigurable() as above, or doing a build and running the script manually.
