### ISSUE TITLE
java.lang.ClassCastException: class com.google.devtools.build.lib.actions.Artifact$SourceArtifact cannot be cast to class com.google.devtools.build.lib.actions.Artifact$DerivedArtifact

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#9182]
### Description of the problem:

Crash:
```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//package:gql-gen BuildConfigurationValue.Key[b67bdc290fb31b127eacf7a9889db436] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class com.google.devtools.build.lib.actions.Artifact$SourceArtifact cannot be cast to class com.google.devtools.build.lib.actions.Artifact$DerivedArtifact (com.google.devtools.build.lib.actions.Artifact$SourceArtifact and com.google.devtools.build.lib.actions.Artifact$DerivedArtifact are in unnamed module of loader 'app')
	at com.google.devtools.build.lib.actions.Actions.assignOwnersAndMaybeFilterSharedActionsAndThrowIfConflict(Actions.java:228)
	at com.google.devtools.build.lib.actions.Actions.assignOwnersAndFilterSharedActionsAndThrowActionConflict(Actions.java:157)
	at com.google.devtools.build.lib.analysis.RuleConfiguredTargetBuilder.build(RuleConfiguredTargetBuilder.java:227)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.createTarget(SkylarkRuleConfiguredTargetUtil.java:226)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:148)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:315)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:776)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:891)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:351)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
	... 7 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro:
https://gist.github.com/duarten/5c8ca4b45f593e54a435f92f279ec71f

### Any other information, logs, or outputs that you want to share?

Context:
https://groups.google.com/d/topic/bazel-discuss/6I6Af4JgtgE/discussion

**Comment by thundergolfer** [comment]
For anyone else arriving at this issue, I followed the [google groups link listed in "Context"](https://groups.google.com/d/topic/bazel-discuss/6I6Af4JgtgE/discussion) and someone mentioned that the bug may be caused by putting some outputs in the `inputs` attr of a `ctx.actions.run` invocation.

That looks to have been on the money for @ahumesky, and I also had the same problem. 👍

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
