### ISSUE TITLE
remote_jdk11 doesn't include required security policy configs

### ISSUE THREAD

**Issue by AngusDavis** [bazelbuild/bazel#9189]
### Description of the problem / feature request:

When running with --config=docker-sandbox or --config=remote and using a --javabase/--host_javabase of @bazel_tools//tools/jdk:remote_jdk11, attempting to initialize SSL (e.g., from tests) fails with the following:
```
Time: 0.043
There was 1 failure:
1) testSslInit(TestSsl)
java.lang.ExceptionInInitializerError
        at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
        at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2624)
        at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2646)
        at java.base/sun.security.ssl.SSLCipher.isUnlimited(SSLCipher.java:540)
        at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
        at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:174)
        at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
        at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:348)
        at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:579)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1848)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at TestSsl.testSslInit(TestSsl.java:11)

[ snip ]
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:120)
        ... 41 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
        at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:326)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:111)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:108)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:107)
        ... 41 more
```
TestSsl looks like the following:

```java
import javax.net.ssl.SSLContext;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class TestSsl {

  @Test
  public void testSslInit() throws Exception {
    SSLContext.getDefault();
  }
}
```

Adding debug print statements shows that when running locally, the directory specified in `System.getProperty("java.home")` contains a conf directory containing security/**. When running in a docker sandbox or remote, the conf directory doesn't exist. 

I *think* adding a conf include to [jdk.BULD](https://github.com/bazelbuild/bazel/blob/9606887fde143abedd19787be5187d47cc7e06a7/src/main/tools/jdk.BUILD#L189) would work (don't know if it'll be an incompatible change or not, though).

A workaround for now is to define a java_runtime using an http_archive that includes all JDK files.
In our WORKSPACE we have:
```
http_archive(
    name = "openjdk11_linux_archive",
    build_file_content = "java_runtime(name = 'runtime', srcs =  glob(['**']), visibility = ['//visibility:public'])",
    sha256 = "cd807601c93d2e9c0e524b251d277da0add8026c4a7fb9908c72dcc19135edc6",
    strip_prefix = "zulu11.33.15-ca-jdk11.0.4-linux_x64",
    urls = [
      "https://cdn.azul.com/zulu/bin/zulu11.33.15-ca-jdk11.0.4-linux_x64.tar.gz",
    ]
)
```
and then use --javabase and --host_javabase of @openjdk11_linux_archive//:runtime.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

$ ./bazelisk info release
release 0.28.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

**Comment by iirina** [comment]
Thanks for filing the issue. You are right that adding the conf directory in the `jdk` target in  `jdk.BUILD` solves this problem. I'm hesitant to make this change for two reasons: 1) the jdk target contains only a minimal set of files and adding more increases the cache usage for everyone (not an incompatible change but a rather unpleasant one), 2) bazel moves in the direction of eliminating the predefined http archvies like `remotejdk11_linux` in favor of letting the user define their own. Based on the latter you're already defining the http_archive.

What would help as an intermediate step is if bazel adds the remote jdk archives only if they're not already defined by the user. In that case you can name your target `remotejdk11_linux` and won't have to point `--host_javabase` at your target since it will be considered by default.

**Comment by AngusDavis** [comment]
Thanks @iirina. The first argument doesn't seem to be too strong, imo (except for the fact caches might be invalidated). The jdk/lib directory is included at ~55M while the conf directory is ~44K. An increase of 0.1% doesn't seem to be too unpleasant when the alternative is tests / genrules(?) not working as expected with a bundled runtime. 

That said, if the direction is to move away from bazel_tools JDK / JRE in general, then it doesn't seem too important to change.

**Comment by iirina** [comment]
> The jdk/lib directory is included at ~55M while the conf directory is ~44K. An increase of 0.1% doesn't seem to be too unpleasant when the alternative is tests / genrules(?) not working as expected with a bundled runtime.

That's true, but adding the conf directory raises more questions regarding which other directories to add and how do we make the choice.

**Comment by jabdoa2** [comment]
Is there a recommended way to work around this? We are experiencing this, too.
