### ISSUE TITLE
Missing fragments trigger exception

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#9193]
### Description of the problem

Omitting a fragment that should have been declared in the rule definition causes an exception to be raised, rather than a user-friendly error.

### Bugs: what's the simplest, easiest way to reproduce this bug?

Remove the `fragments = ["cpp"]` line from any rule that uses the `cpp` fragment. `bazel build` will result in:

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@rules_haskell//haskell:toolchain-libraries BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false' (requested by nodes '//tests/hackage:base BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalArgumentException: haskell_toolchain_libraries has to declare 'CppConfiguration' as a required fragment in target configuration in order to access it.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:477)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:451)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:443)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:462)
	at com.google.devtools.build.lib.rules.cpp.CcModule.configureFeatures(CcModule.java:147)
	at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:135)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:930)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:898)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:72)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:192)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:129)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:315)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:776)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:891)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:351)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@rules_haskell//haskell:toolchain-libraries BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false' (requested by nodes '//tests/hackage:base BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalArgumentException: haskell_toolchain_libraries has to declare 'CppConfiguration' as a required fragment in target configuration in order to access it.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:477)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:451)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:443)
	at com.google.devtools.build.lib.analysis.RuleContext.getFragment(RuleContext.java:462)
	at com.google.devtools.build.lib.rules.cpp.CcModule.configureFeatures(CcModule.java:147)
	at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:135)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:930)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:898)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:72)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:192)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:129)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:315)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:182)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:776)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:891)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:351)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
FAILED: Build did NOT complete successfully (40 packages loaded, 812 targets configured)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

v0.28.0

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
