### ISSUE TITLE
examples broken on macOS in downstream pipeline

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9257]
```

(04:07:22) ERROR: /Users/buildkite/builds/bk-imacpro-1/bazel-downstream-projects/examples/tutorial/ios-app/BUILD:13:1: in ios_application rule //ios-app:ios-app:
--
  | Traceback (most recent call last):
  | File "/Users/buildkite/builds/bk-imacpro-1/bazel-downstream-projects/examples/tutorial/ios-app/BUILD", line 13
  | ios_application(name = 'ios-app')
  | File "/private/var/tmp/_bazel_buildkite/b42e9b29c31ef948534f92963b7ac858/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 159, in _ios_application_impl
  | run_support.register_simulator_executable(ctx, executable)
  | File "/private/var/tmp/_bazel_buildkite/b42e9b29c31ef948534f92963b7ac858/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 28, in run_support.register_simulator_executable
  | ctx.actions.expand_template(output = output, is_executable = T..., <2 more arguments>)
  | File "/private/var/tmp/_bazel_buildkite/b42e9b29c31ef948534f92963b7ac858/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 36, in ctx.actions.expand_template
  | shell.quote(ctx.fragments.objc.ios_simulator...)
  | File "/private/var/tmp/_bazel_buildkite/b42e9b29c31ef948534f92963b7ac858/external/bazel_skylib/lib/shell.bzl", line 49, in shell.quote
  | s.replace("'", "'\\''")
  | type 'NoneType' has no method replace()


```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1167#5154e04d-23ff-47c7-9d3c-d6cb6cbfb905

**Comment by meteorcloudy** [comment]
Culprit is 903a7b91dc1a668275f92052e6bbef78678c764c

@keith
