### ISSUE TITLE
Alarming-looking log output when worker process dies

### ISSUE THREAD

**Issue by qaiffluke** [bazelbuild/bazel#9366]
### Description of the problem:

>  I'm trying to build my angular templates and the bazel builder throws me errors I cannot understand. I'm a newbie and need help in understanding what's wrong.

### What operating system are you running Bazel on?

> Windows 10

### What's the output of `bazel info release`?

> release 0.29.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> It's a private repo

###  Have you found anything relevant by searching the web?

> Nothing so far

### Any other information, logs, or outputs that you want to share?

> This is the OUTPUT I get

```
INFO: Analyzed target //app:bundle (508 packages loaded, 24940 targets configured).
INFO: Found 1 target...
ERROR: C:/users/qshaikh/downloads/angular/lopez-ui/app/BUILD.bazel:111:1: Compiling Angular templates (ngc) //app:app failed: Worker process quit or closed its stdin stream when we tried to
send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(36968): The pipe is being closed.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:263)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:33)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:57)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2935)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2954)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1331)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2751)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2724)
        at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2721)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:220)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2800)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1009)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:330)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:172)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:121)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:225)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:123)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:88)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.actions.SpawnContinuation$1.execute(SpawnContinuation.java:80)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction$SpawnActionContinuation.execute(SpawnAction.java:1344)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:314)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:123)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:851)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:985)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:957)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:577)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:760)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:275)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/users/administrator/_bazel_administrator/vqxrcad2/bazel-workers/worker-0-AngularTemplateCompile.log ---8<---8<---
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\tslib\tslib.js:65:9)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:115:17
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:314:6
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:3:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:20:22
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:10:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\program.js:31:23
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\program.js:10:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\ngtsc\program.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\program.js:27:21
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\program.js:10:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\program.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\entry_points.js:21:21
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\entry_points.js:10:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\src\transformers\entry_points.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\index.js:39:26
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\index.js:3:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\compiler-cli\index.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\bazel\src\ngc-wrapped\index.js:19:16
    at C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\bazel\src\ngc-wrapped\index.js:10:17
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\external\npm\node_modules\@angular\bazel\src\ngc-wrapped\index.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Object.<anonymous> (C:\users\administrator\_bazel_administrator\vqxrcad2\execroot\lopez_ui\bazel-out\host\bin\external\npm\@angular\bazel\bin\ngc-wrapped_bin_loader.js:522:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
---8<---8<--- End of log ---8<---8<---
Target //app:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 827.359s, Critical Path: 14.65s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

> This is my WORKSPACE file
```
# The WORKSPACE file tells Bazel that this directory is a "workspace", which is like a project root.
# The content of this file specifies all the external dependencies Bazel needs to perform a build.

################################################################################################################################################

# ESModule imports (and TypeScript imports) can be absolute starting with the workspace name.
# The name of the workspace should match the npm package where we publish, so that these
# imports also make sense when referencing the published package.
workspace(
    name = "lopez_ui",
    managed_directories = {"@npm": ["node_modules"]},
)

################################################################################################################################################

# These rules are built-into Bazel but we need to load them first to download more rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

################################################################################################################################################

# Fetch rules_nodejs so we can install our npm dependencies
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "da72ea53fa1cb8ab5ef7781ba06b97259b7d579a431ce480476266bc81bdf21d",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.36.2/rules_nodejs-0.36.2.tar.gz"],
)

# git_repository(
#     name = "build_bazel_rules_nodejs",
#     commit = "76156572a614289d67fe537d92e02ff1a4d5d4be",
#     remote = "https://github.com/bazelbuild/rules_nodejs.git",
# )

################################################################################################################################################

# Fetch sass rules for compiling sass files
http_archive(
    name = "io_bazel_rules_sass",
    sha256 = "4f05239080175a3f4efa8982d2b7775892d656bb47e8cf56914d5f9441fb5ea6",
    strip_prefix = "rules_sass-86ca977cf2a8ed481859f83a286e164d07335116",
    url = "https://github.com/bazelbuild/rules_sass/archive/86ca977cf2a8ed481859f83a286e164d07335116.zip",
)

################################################################################################################################################

# Fetch web testing rules for web repositories and browser repositories
# http_archive(
#     name = "io_bazel_rules_webtesting",
#     sha256 = "f1f4d2c2f88d2beac64c82499a1e762b037966675dd892da89c87e39d72b33f6",
#     urls = [
#         "https://github.com/bazelbuild/rules_webtesting/releases/download/0.3.2/rules_webtesting.tar.gz",
#     ],
# )

################################################################################################################################################

# Check the bazel version and download npm dependencies
load("@build_bazel_rules_nodejs//:defs.bzl", "check_bazel_version", "yarn_install", "node_repositories")

# Bazel version must be at least the following version because:
#   - 0.27.0 Adds managed directories support
check_bazel_version(
    message = """
You no longer need to install Bazel on your machine.
Angular has a dependency on the @bazel/bazel package which supplies it.
Try running `yarn bazel` instead.
    (If you did run that, check that you've got a fresh `yarn install`)
""",
    minimum_bazel_version = "0.27.0",
)

# Setup the Node.js toolchain & install our npm dependencies into @npm
yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
    always_hide_bazel_files = True,
)

node_repositories(
    package_json = ["//:package.json"],
    node_repositories = {
        "10.16.0-darwin_amd64": ("node-v10.16.0-darwin-x64.tar.gz", "node-v10.16.0-darwin-x64", "6c009df1b724026d84ae9a838c5b382662e30f6c5563a0995532f2bece39fa9c"),
        "10.16.0-linux_amd64": ("node-v10.16.0-linux-x64.tar.xz", "node-v10.16.0-linux-x64", "1827f5b99084740234de0c506f4dd2202a696ed60f76059696747c34339b9d48"),
        "10.16.0-windows_amd64": ("node-v10.16.0-win-x64.zip", "node-v10.16.0-win-x64", "aa22cb357f0fb54ccbc06b19b60e37eefea5d7dd9940912675d3ed988bf9a059"),
    },
    node_version = "10.16.0",
)

################################################################################################################################################

# Install all bazel dependencies of our npm packages
load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")
install_bazel_dependencies()

# Load npm_bazel_protractor dependencies
load("@npm_bazel_protractor//:package.bzl", "npm_bazel_protractor_dependencies")
npm_bazel_protractor_dependencies()

# Load npm_bazel_karma dependencies
load("@npm_bazel_karma//:package.bzl", "rules_karma_dependencies")
rules_karma_dependencies()

################################################################################################################################################

# Setup the rules_webtesting toolchain
load("@io_bazel_rules_webtesting//web:repositories.bzl", "web_test_repositories")
web_test_repositories()

# Temporary work-around for https://github.com/angular/angular/issues/28681
# TODO(gregmagolan): go back to @io_bazel_rules_webtesting browser_repositories
load("@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl", "browser_repositories")
browser_repositories()

################################################################################################################################################

# Setup the rules_typescript tooolchain
load("@npm_bazel_typescript//:index.bzl", "ts_setup_workspace")
ts_setup_workspace()

# Setup the rules_sass toolchain
load("@io_bazel_rules_sass//sass:sass_repositories.bzl", "sass_repositories")
sass_repositories()

################################################################################################################################################

# Support for Remote Execution
http_archive(
    name = "bazel_toolchains",
    sha256 = "88e818f9f03628eef609c8429c210ecf265ffe46c2af095f36c7ef8b1855fef5",
    strip_prefix = "bazel-toolchains-92dd8a7",
    urls = [
        "https://github.com/bazelbuild/bazel-toolchains/archive/92dd8a7.zip",
    ],
)

################################################################################################################################################

# Support creating Docker images for our node apps
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)

load("@io_bazel_rules_docker//nodejs:image.bzl", nodejs_image_repos = "repositories")

nodejs_image_repos()

################################################################################################################################################
```

> Please let me know the problem here.
> Also if this is not the right place to ask, what is?

Thank you!

**Comment by irengrig** [comment]
Hi @qaiffluke , thank you for reporting the issue!
I wanted to clarify, if this issue is persistent, or you can get the build to work after some repeating attempts?

**Comment by qaiffluke** [comment]
@irengrig the issue persists irrespective of the number of attempts.

Also, I have assumptions that the second half of this error might be an issue due to incorrect dependencies in angular packages, so it would be better to get some good error messages for that.

**Comment by qaiffluke** [comment]
@irengrig the issue persists irrespective of the number of attempts.

Also, I have an assumption that the second half of the error might be because of the incorrect dependencies in angular packages. So if that's the case, a good error message would be a great help.

PS: closed the issue by mistake

**Comment by qaiffluke** [comment]
Closed the issue by mistake

**Comment by susinmotion** [comment]
It's possible that we're not handling the exception correctly, so it's still present when we go to print out the error message in ErrorMessage.Java. Despite the error message looking scary, Blaze hasn't crashed, so it's just a cosmetic issue, hence p2.
