### ISSUE TITLE
Bazel Build Android kotlin don't work.

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/bazel#9418]
Hi,

I have a error when building an android project with bazel.

Can somebody help me ? 

**WORSPACE FILE:**

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(
    name = "androidsdk",
    path ="/Users/smba/Library/Android/sdk",
    api_level = 29,
    build_tools_version = "28.0.3"
)

http_archive(
    name = "rules_android",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
)

GMAVEN_TAG = "20180723-2"
http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)
load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")
gmaven_rules()

rules_kotlin_version = "f7a3b5fd823c2418fc2c2881c00e27e4d63475d5"
rules_kotlin_compiler_release = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v1.2.70/kotlin-compiler-1.2.70.zip",
    ],
    "sha256": "a23a40a3505e78563100b9e6cfd7f535fbf6593b69a5c470800fbafbeccf8434",
}

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/globegitter/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version,
    sha256 = "716127f93bfb09c577712c049b0812640f293362db2714489b78cb231c020a29",
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()

**Build File:**

load("@gmaven_rules//:defs.bzl", "gmaven_artifact")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

MANIFEST = "AndroidManifest.xml"

android_binary(
    name = "appsimpleandroid",
    manifest = MANIFEST,
    resource_files = glob(["res/**"]),
    multidex = "native",
    dex_shards = 10,
    deps = [
        "src"
    ]
)

kt_android_library(
    name = "src",
    manifest = MANIFEST,
    srcs = glob(["java/com/example/appsimpleandroid/MainActivity.kt"]),
    resource_files = glob(["res/**"]),
    deps = [
        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2"),
        gmaven_artifact("androidx.annotation:annotation:1.0.0-beta01"),
        gmaven_artifact("androidx.fragment:fragment:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-common:2.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-viewmodel:aar:2.0.0-beta01"),
        gmaven_artifact("androidx.core:core:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.drawerlayout:drawerlayout:aar:1.0.0-beta01")
    ]
)

**Comment by salim-boudriiya** [comment]
the error is:

ERROR: /Users/smba/repo/Android/AppSimpleAndroid/app/src/main/BUILD:16:1: Validating Android resources for //AppSimpleAndroid/app/src/main:src_base failed (Exit 1) ResourceProcessorBusyBox failed: error executing command bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool VALIDATE -- --buildToolsVersion 28.0.3 --aapt ... (remaining 16 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Error: /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/tmp-expanded/res/layout/content_main.xml:2: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').
Error: 
Sep 23, 2019 2:21:54 PM com.google.devtools.build.android.AndroidResourceValidatorAction main
SEVERE: Unexpected
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-29/android.jar -M /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/manifest-aapt-dummy/AndroidManifest.xml -S /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/tmp-expanded/res -m -J /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/generated_resources --output-text-symbols /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/generated_resources -F bazel-out/android-armeabi-v7a-fastbuild/bin/AppSimpleAndroid/app/src/main/src_base_files/library.ap_ --debug-mode --custom-package main --non-constant-id -0 apk
Error Code:
	1
Output:
	
Error at 2 : /var/folders/tx/9n9trqnx7hb90g4bk6czbyrxbn6n7b/T/resource_validator_tmp16563103594698722728/tmp-expanded/res/layout/content_main.xml:2: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').
0	:  <?xml version="1.0" encoding="utf-8"?>
1	:  <android.support.constraint.ConstraintLayout
2	:          xmlns:android="http://schemas.android.com/apk/res/android"
3	:          xmlns:tools="http://schemas.android.com/tools"
4	:          xmlns:app="http://schemas.android.com/apk/res-auto"
5	:          android:layout_width="match_parent"
6	:          android:layout_height="match_parent"
	

	at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:422)
	at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:149)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:72)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:242)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
