### ISSUE TITLE
Failure without useful error message when using experimental_remote_download_outputs without remote endpoint flags.

### ISSUE THREAD

**Issue by martensryan** [bazelbuild/bazel#9421]
### Description of the problem / feature request:

Bazel fails without a useful error message when using --experimental_remote_download_outputs=toplevel without specifying the remote endpoints.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run bazel with --experimental_remote_download_outputs=toplevel without specifying:
--remote_executor=grpcs://remotebuildexecution.googleapis.com
--remote_cache=grpcs://remotebuildexecution.googleapis.com

For reference, I used this .bazelrc file:
https://github.com/envoyproxy/envoy/blob/master/.bazelrc#L128
using --config=remote-clang (which does not include --config=remote-ci).

### What operating system are you running Bazel on?

Linux (Ubuntu 16.04)

### What's the output of `bazel info release`?

release 0.29.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/envoyproxy/envoy.git
98c35eff10ad170d550fb5ecfc2c6b3637418c0c
98c35eff10ad170d550fb5ecfc2c6b3637418c0c

###  Have you found anything relevant by searching the web?

NA

### Any other information, logs, or outputs that you want to share?

Here is the output:

Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: actionContextProvider was null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.google.devtools.build.lib.remote.RemoteModule.afterAnalysis(RemoteModule.java:327)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:114)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:518)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by keith** [comment]
Seeing this one too. @buchgr any idea if this is network flakiness or another issue?

**Comment by keith** [comment]
FWIW after merging these flags we saw this so many times with RBE that we've had to revert.

**Comment by coeuvre** [comment]
Should be fixed by #11898. Closing.
