### ISSUE TITLE
Can't reference styles with dots in the name from <declare-styleable> attribute

### ISSUE THREAD

**Issue by kitterion** [bazelbuild/bazel#9434]
### Description of the problem:

Referencing style names in android `values/filename.xml` from `declare-styleable` with dots in the name produces the following stacktrace (release 0.29.0):
```
Exception in thread "main" com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging
	at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:75)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:276)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$8.call(ResourceProcessorBusyBox.java:108)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:242)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: a
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:99)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:271)
	... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: App attribute not found: a
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:451)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:367)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:91)
	... 6 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Take any `android_binary` and add the following to any .xml file under res/values
```xml
    <style name="a" />
    <style name="a.b" />
    <declare-styleable name="ds">
        <attr format="reference" name="a.b" />
    </declare-styleable>
```
I'm not an android expert, but i'm pretty sure this is valid android code.

### What operating system are you running Bazel on?

MacOS Mojave 10.14.6

### What's the output of `bazel info release`?

The issue is reproducible with:
release 0.29.0
release 1.0.0rc3

It is not reproducible in bazel 0.28.1 and it seems to have appeared in release 0.29.0

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

Doing `git bisect`, I have narrowed it down that this was introduced in the the commit 6530003204dec22875c5cfce8e41c5c88eabe1aa.
After doing some digging, it turned out that changing this pattern
https://github.com/bazelbuild/bazel/blob/e95eca85e905da98423c0150e98c2b0fc96aaa3a/src/tools/android/java/com/google/devtools/build/android/FullyQualifiedName.java#L146
to include dots in the name, i.e. from `<name>\\w+` to `<name>[\\w\\.]+` solves the issue.

**Comment by jin** [comment]
cc @bchang @donaldchai

**Comment by donaldchai** [comment]
For what it's worth,

```xml
    <declare-styleable name="ds">
        <attr format="reference" name="a.b" />
    </declare-styleable>
```

is declaring an attribute named "a.b" rather than referencing any existing entities with that name, in particular it's not referencing a style called "a.b".

**Comment by kitterion** [comment]
I see. I didn't fully understand how that works. Not sure I still do but hopefully I got it right this time.
A dependency of a project I'm trying to convert to bazel uses the same names for styles and for the attributes in `<declare-styleable>` and that's probably were I got confused.
I guess, a more correct example should be something like
```xml
    <declare-styleable name="ds">
        <attr format="reference" name="a.b" />
    </declare-styleable>
    <style name="c">
        <item name="a.b">@style/c.d</item>
    </style>
    <style name="c.d" />
```
