### ISSUE TITLE
http_archive - NPE & doesn't follow redirections

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#959]
Hello,
when using git master, `WORKSPACE` with such `http_archive`:

    http_archive(
        name = "pcre",
        sha256 = "9883e419c336c63b0cb5202b09537c140966d585e4d0da66147dc513da13e629",
        type = "tar.gz",
        url = "https://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.gz/download",
    )

is throwing `java.lang.NullPointerException`:

    Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@pcre_http' (requested by nodes 'REPOSITORY:@pcre_http')
    INFO: Elapsed time: 4.657s
    java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@pcre_http' (requested by nodes 'REPOSITORY:@pcre_http')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
        at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
        at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
        at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
        at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:57)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:140)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
        ... 4 more

Older version (Bazel-0.1.2, 0d2e409) complains about SHA256 mismatch (it compares it to the SHA256 of the "redirection" HTML, since it doesn't follow redirections), when using the same `WORKSPACE`:

    ERROR: Error downloading from https://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.gz/download to $HOME/.cache/bazel/_bazel_XXXXX/826d5352cb80d517ce576d3c406c4f6a/external/pcre_http_test: Downloaded file at $HOME/.cache/bazel/_bazel_XXXXX/826d5352cb80d517ce576d3c406c4f6a/external/pcre_http_test/download.tar.gz has SHA-256 of 07d2e2724e84031361964c9a2a25fb920018c4f6c024c08765fb9e03e4ddb35a, does not match expected SHA-256 (9883e419c336c63b0cb5202b09537c140966d585e4d0da66147dc513da13e629).

but at least it doesn't throw `java.lang.NullPointerException`.

Redirections (and this `WORKSPACE`) used to work a while ago, but I cannot find offending commit...

**Comment by michajlo** [comment]
It looks like HttpURLConnection doesn't like following https <-> http redirects (http://stackoverflow.com/questions/1884230/urlconnection-doesnt-follow-redirect). In the short term you should be able to work around this by using `curl -I $url` to follow the redirects manually and then put the final url, or url from the point where redirects don't change protocol, in your http_archive rule.

The https -> http redirect would need to be implemented in bazel, assuming we're ok with the https -> http downgrade (perhaps configurable?). The NPE is a result of us expecting non-200 response to be an error, but in this case it's a 3XX that wasn't followed.

**Comment by PiotrSikora** [comment]
Well, the integrity is protected via SHA256, so I don't care _that_ much about HTTPS in this particular case... and SourceForge mirrors don't serve distfiles over HTTPS anyway.

The issue is that the redirect chain (HTTP -> HTTPS -> HTTP) is done in a way that I cannot bypass protocol change without sticking to a particular mirror, so the ability to follow such redirects would be definitely welcome:

    http://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.gz/download
    https://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.gz/download
    http://downloads.sourceforge.net/project/pcre/pcre/8.38/pcre-8.38.tar.gz?r=&ts=1456260328&use_mirror=iweb
    http://iweb.dl.sourceforge.net/project/pcre/pcre/8.38/pcre-8.38.tar.gz
