### ISSUE TITLE
Bazel issue with https_proxy

### ISSUE THREAD

**Issue by mahmoodn** [bazelbuild/bazel#9612]
I am trying to install tensorflow 2 on a computer that is behind a proxy. With bazel 0.29.1 and the environment variables for `http_proxy` and `https_proxy`, I hit this error

```
INFO: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /home/mnaderan/tensorflow-2.0.0/WORKSPACE:35:1
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_docker':
   Traceback (most recent call last):
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", <2 more arguments>)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @io_bazel_rules_docker:
fatal: unable to access 'https://github.com/bazelbuild/rules_docker.git/': gnutls_handshake() failed: An unexpected TLS packet was received.
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", <2 more arguments>)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @io_bazel_rules_docker:
fatal: unable to access 'https://github.com/bazelbuild/rules_docker.git/': gnutls_handshake() failed: An unexpected TLS packet was received.
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
                fetch(ctx, git_repo)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
                _git_maybe_shallow(ctx, git_repo, "fetch", "origin", <2 more arguments>)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
                _error(ctx.name, (start + args_list), st.st...)
        File "/home/mnaderan/.cache/bazel/_bazel_mnaderan/e028f545b86fd8a8b51eff16707000f6/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(("error running '%s' while worki...)))
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @io_bazel_rules_docker:
fatal: unable to access 'https://github.com/bazelbuild/rules_docker.git/': gnutls_handshake() failed: An unexpected TLS packet was received.
INFO: Elapsed time: 12.692s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I searched a lot but it seems that this is a bazel related problem. How can I fix that?

**Comment by aiuto** [comment]
Can you provide reproduction for this
-  a small WORKSPACE file
- sanitized proxy settngs
- what kind of proxy? There are all sorts of things out there. Is it an MITM one?

**Comment by mahmoodn** [comment]
Excuse me, but I can not reproduce that. Things are complex in tensorflow!
Since it has a problem with `io_bazel_rules_docker`, from the traces, I see the following paths:

1- https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L38
2- https://github.com/tensorflow/tensorflow/blob/master/third_party/toolchains/preconfig/generate/workspace.bzl#L2 or https://github.com/tensorflow/tensorflow/blob/master/third_party/toolchains/preconfig/generate/workspace.bzl#L6


The proxy is set as the following:

```
export http_proxy=http://proxy.somewhere.com:3128
export https_proxy=https://proxy.somewhere.com:3128
```

**Comment by philwo** [comment]
The error message comes from Git. You'll have to configure your Git to use the proxy server, e.g. like this: https://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server-fails-with-request-timed-out

**Comment by puraminy** [comment]
I also set the proxy to https://127.0.0.1:8118 and got the same error:

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @io_bazel_rules_docker

**Comment by puraminy** [comment]
Setting `git` proxy can resolve the problem, however it should be `https` and not only `http` proxy.

    git config --global https.proxy https://127.0.0.1:8118

If you run this command in the docker container, you must use `--network=host` option for the docker to recognize the localhost IP address. The `--net=host` option is used to make the programs inside the Docker container look like they are running on the host itself, from the perspective of the network.
