### ISSUE TITLE
ci.bazel.io build is broken

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#968]
I just wanted to have one change out (so we have a link from the blog post to the actual release), got a full breakage:

http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/377/

This is pretty serious:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@scala' (requested by nodes 'REPOSITORY:@scala')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
	at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
	at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
	at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
	at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:57)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:140)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
	... 4 more
```
Because it is late, assigning to the current sheriff.

**Comment by michajlo** [comment]
Looks like #959 again, the http url is redirecting to https, and our error handling doesn't handle this nicely.
