### ISSUE TITLE
Null Pointer exception on http_file

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#969]
This happens in 0.1.5 and 0.2.0

I can download the link it is trying to get:

http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz

but it looks like a 301 moved permanently:
```
st-oscar1:Downloads oscar$ curl http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
```
03:12:36 Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@scala' (requested by nodes 'REPOSITORY:@scala')
03:12:36 ____Elapsed time: 4.133s
03:12:36 java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@scala' (requested by nodes 'REPOSITORY:@scala')
03:12:36 	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
03:12:36 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
03:12:36 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
03:12:36 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
03:12:36 	at java.lang.Thread.run(Thread.java:745)
03:12:36 Caused by: java.lang.NullPointerException
03:12:36 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
03:12:36 	at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
03:12:36 	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
03:12:36 	at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
03:12:36 	at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
03:12:36 	at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
03:12:36 	at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:57)
03:12:36 	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:124)
03:12:36 	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
03:12:36 	... 4 more
```

**Comment by philwo** [comment]
Could you please check if this was fixed by https://github.com/bazelbuild/bazel/commit/6e30521e0d230ba8138cb8bbe3bf3f4fb4fbfa60?

**Comment by johnynek** [comment]
I tried, but I can't replicate it because the URL has been fixed by the owners of that URL and I don't know another example.

Hopefully it works.

**Comment by damienmg** [comment]
Let close it. There is a specific test for it now so we should be safe :)
