### ISSUE TITLE
generate_workspace fails with a maven artifact option

### ISSUE THREAD

**Issue by davidsantiago** [bazelbuild/bazel#973]
When the command below is run, generate_workspace fails with a class cast exception. This also happens when run on the bazel project that contains this artifact as a maven_jar() rule in its workspace. I haven't been able to find a work around. 

```
$ bazel run //src/tools/generate_workspace -- --artifact="com.treasuredata.client:td-client:0.7.6"
INFO: Found 1 target...
Target //src/tools/generate_workspace:generate_workspace up-to-date:
  bazel-bin/src/tools/generate_workspace/generate_workspace.jar
  bazel-bin/src/tools/generate_workspace/generate_workspace
INFO: Elapsed time: 0.114s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/src/tools/generate_workspace/generate_workspace '--artifact=com.treasuredata.client:td-client:0.7.6'
Exception in thread "main" java.lang.ClassCastException: sun.net.www.protocol.ftp.FtpURLConnection cannot be cast to java.net.HttpURLConnection
    at com.google.devtools.build.workspace.maven.DefaultModelResolver.pomFileExists(DefaultModelResolver.java:114)
    at com.google.devtools.build.workspace.maven.DefaultModelResolver.getModelSource(DefaultModelResolver.java:100)
    at com.google.devtools.build.workspace.maven.DefaultModelResolver.resolveModel(DefaultModelResolver.java:72)
    at com.google.devtools.build.workspace.maven.DefaultModelResolver.resolveModel(DefaultModelResolver.java:132)
    at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:898)
    at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:750)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:309)
    at com.google.devtools.build.workspace.maven.Resolver.resolveEffectiveModel(Resolver.java:212)
    at com.google.devtools.build.workspace.maven.Resolver.resolveArtifact(Resolver.java:197)
    at com.google.devtools.build.workspace.GenerateWorkspace.generateFromArtifacts(GenerateWorkspace.java:115)
    at com.google.devtools.build.workspace.GenerateWorkspace.main(GenerateWorkspace.java:62)
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by ahumesky** [comment]
I can reproduce the problem here. Clearly, somewhere we think an ftp thing is an http thing.

**Comment by ahumesky** [comment]
So as a temporary way around this just to get you unblocked, you could just change this line to not call pomFileExists:
https://github.com/bazelbuild/bazel/blob/6beaebdfa7ea3d0bcfd58511dbf6f588b206914d/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/DefaultModelResolver.java#L100

or you could check here that the return UrlConnection is really an HttpUrlConnection:
https://github.com/bazelbuild/bazel/blob/6beaebdfa7ea3d0bcfd58511dbf6f588b206914d/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/DefaultModelResolver.java#L114

(bazel run will recompile generate_workspace for you)

I'm not sure yet of the correct solution to check the ftp url if the file exists

**Comment by dslomov** [comment]
@kchodorow could you take a look?

**Comment by kchodorow** [comment]
Yeah, I'll fix.

**Comment by petroseskinder** [comment]
@kchodorow and @ahumesky I believe this issue can be closed. I do not receive this error with bazel release 0.4.5-homebrew.

**Comment by kchodorow** [comment]
Indeed.
