### ISSUE TITLE
Error in docstring with CRLF line-endings on Windows

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel#9999]
### Description of the problem:

On Windows, if there is a docstring that looks like this:

```
def check_bazel_version(minimum_bazel_version, message = ""):
    """
    Verify the users Bazel version is at least the given one.

    This should be called from the `WORKSPACE` file so that the build fails as
    early as possible. For example:
    ...
```

and `core.autocrlf = true` in gitconfig so that line endings are converted to CRLF on checkout, Starlark doc outputs the following error when running a build.

```
ERROR: C:/users/gmago/google/rules_nodejs/docs/BUILD.bazel:17:1: Generating proto for Starlark doc for builtins failed (Exit 1)
Exception in thread "main" com.google.devtools.build.skydoc.rendering.DocstringParseException: Unable to generate documentation for function check_bazel_version (defined at internal/common/check_bazel_version.bzl:28:5) due to malformed docstring. Parse errors:
  internal/common/check_bazel_version.bzl:28:5 line 2: the one-line summary should be followed by a blank line

        at com.google.devtools.build.skydoc.rendering.FunctionUtil.fromNameAndFunction(FunctionUtil.java:62)
        at com.google.devtools.build.skydoc.rendering.ProtoRenderer.appendUserDefinedFunctionInfos(ProtoRenderer.java:58)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:263)
```

I can work-around the issue by either

1) changing the docstring to:

```
def check_bazel_version(minimum_bazel_version, message = ""):
    """Verify the users Bazel version is at least the given one.

    This should be called from the `WORKSPACE` file so that the build fails as
    early as possible. For example:
    ...
```

so that there is no CRLF before the one-line-summary _or_

2) Changing the .gitconfig core.autocrlf option to `input` so that LF is preserved on checkout

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

clone `git@github.com:bazelbuild/rules_nodejs.git` on Windows with your .gitconfig `core.autocrlf` set to `true` and run `bazel test ... --test_tag_filters=-e2e,-examples,-fix-windows`

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 0.29.1

###  Have you found anything relevant by searching the web?

No. I was surprised no one had run into this yet.

**Comment by laszlocsomor** [comment]
Minimal repro: `bazel build //docs:builtins`

```
ERROR: C:/src/rules_nodejs/docs/BUILD.bazel:17:1: Generating proto for Starlark doc for builtins failed (Exit 1)
Exception in thread "main" com.google.devtools.build.skydoc.rendering.DocstringParseException: Unable to generate documentation for function check_bazel_version (defined at internal/common/check_bazel_version.bzl:28:5) due to malformed docstring. Parse errors:
  internal/common/check_bazel_version.bzl:28:5 line 2: the one-line summary should be followed by a blank line

        at com.google.devtools.build.skydoc.rendering.FunctionUtil.fromNameAndFunction(FunctionUtil.java:62)
        at com.google.devtools.build.skydoc.rendering.ProtoRenderer.appendUserDefinedFunctionInfos(ProtoRenderer.java:58)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:263)
Target //docs:builtins failed to build
INFO: Elapsed time: 3.717s, Critical Path: 0.71s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

This looks like a bug in Skydoc, not in Bazel.

[Skydoc is deprecated in favor of Stardoc](https://github.com/bazelbuild/stardoc/blob/master/docs/skydoc_deprecation.md). Could you try migrating to Stardoc and see if that has the bug? If the bug is there, could you please [open a bug for Stardoc](https://github.com/bazelbuild/stardoc/issues/new)?
